### ISSUE TITLE
jx promote failed becuase of jenkins chart museum is down or returning 404

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1003]
https://chartmuseum.build.cd.jenkins-x.io/ is returning 404

**Comment by beerkeeper** [comment]
At the moment it's actually returning a 503 and causing all builds to fail on my Jenkins-X installation.

```
helm repo add chartmuseum http://jenkins-x-chartmuseum:8080
"chartmuseum" has been added to your repositories
helm repo add chartmuseum https://chartmuseum.build.cd.jenkins-x.io
Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch https://chartmuseum.build.cd.jenkins-x.io/index.yaml : 503 Service Unavailable
```

**Comment by merou** [comment]
same issue here https://chartmuseum.build.cd.jenkins-x.io returns a 503

**Comment by Kevgilmore** [comment]
same here `Error: Looks like "http://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.build.cd.jenkins-x.io/index.yaml : 503 Service Unavailable`

**Comment by juanserra** [comment]
I have the same problem too! It's been fine until a few hours ago, promotions are all failing right now because of this - 503 service unavailable

**Comment by Naoises** [comment]
Also Having this issue get 404 when I connect to https://chartmuseum.build.cd.jenkins-x.io

**Comment by pasikon** [comment]
Same for me, is there any workaround?

**Comment by rawlingsj** [comment]
https://chartmuseum.build.cd.jenkins-x.io giving a 404 is expected.  

The health endpoint is 
https://chartmuseum.build.cd.jenkins-x.io/health which returns `{"healthy":true}` and charts are in the index.yaml which is https://chartmuseum.build.cd.jenkins-x.io/index.yaml

Both these endpoints are working so I'm going to close this.

**Comment by rawlingsj** [comment]
There have been a couple of service disruptions and we are looking to switch to github pages or scale up chartmuseum so we get a HA service but that's something we should be working on soon.

**Comment by udbscience** [comment]
curl: (7) Failed to connect to chartmuseum.build.cd.jenkins-x.io port 443: Operation timed out

**Comment by pdutta777** [comment]
Getting a 504 error while trying to reach the health check URL

**Comment by datangliang** [comment]
> There have been a couple of service disruptions and we are looking to switch to github pages or scale up chartmuseum so we get a HA service but that's something we should be working on soon.

Is there an exist github hosted jenkins x chartmuseum avaliable until now? @rawlingsj
