### ISSUE TITLE
error creating cluster exit status 2

### ISSUE THREAD

**Issue by steinko** [jenkins-x/jx#1007]
First I have created a cluster on google cloud. Then I created a cluster on Azur: jx create cluster aks
Execution of this command ended in an error: error creating cluster exit status 2. How could I fix this?
[Error.txt](https://github.com/jenkins-x/jx/files/2089662/Error.txt)

**Comment by rawlingsj** [comment]
It's been a while and the installer has been pretty solid, I wonder if this is still an issue?  Currently our automated tests don't yet validate on AKS but we hope to sort that soon.

/kind bug
/kind needs-validation

**Comment by ccojocar** [comment]
Closing this because there is no follow up with addition details.
