### ISSUE TITLE
external-dns integration

### ISSUE THREAD

**Issue by JonnyBGod** [jenkins-x/jx#1010]
[external-dns](https://github.com/kubernetes-incubator/external-dns) provides configurable dns management with multiple providers:
```
Google CloudDNS
AWS Route 53
AWS Service Discovery
AzureDNS
CloudFlare
DigitalOcean
DNSimple
Infoblox
Dyn
OpenStack Designate
PowerDNS
```

It would be great to have JX giving the option to install it.

**Comment by stormmore** [comment]
I would much prefer the granularity of DNS options that external-dns offers over giving a wildcard entry to Jenkins X and have it make opinionated choices with regard to my DNS structure, i.e. `<service name>.<namespace>.domain.com` is great for my non production environments but my production environments are just `<service name>.domain.com`.

In fact, that example is an over simplification of my DNS setup, I have one internal sub-domain that I use for all services related to running a Kubernetes clusters and then the services that I actually run are on a public sub-domain that is completely different from the internal one, e.g. `k8s.domain.com` and `services.domain.com`.

**Comment by afirth** [comment]
/remove-lifecycle stale

This is actually "in" the feature set for something (upgrade ingress maybe?) but totally broken depending on the path the user tries to go down. Even if the answer is to add the annotation to everything but not install it, that would be a good resolution I think.

**Comment by ccojocar** [comment]
We support now external-dns in boot. @cagiti Can we close this one? Thanks

**Comment by cagiti** [comment]
Yes, external-dns is now supported  using `jx boot` and configuring the following file: `https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/jx-requirements.yml`

**Comment by cagiti** [comment]
I'm /close 'ing this issue @afirth,  please re-open if you disagree

**Comment by Markus-ipse** [comment]
I'm sorry to comment on a closed issue, but I cannot find and docs, guides, blog posts or issues (except this one) giving me any kind of help regarding how to use cloudflare (or anything else other than google dns) as dns provider when using `jx boot`. 

jx-requirements.yaml only allow me (afaik) to specify domain and externalDNS (true/false) but nothing specifying the provider and the provider specific setup. Could you point me to any more detailed information than just the jx-requirements-file? @cagiti @ccojocar @afirth

**Comment by afirth** [comment]
> I'm sorry to comment on a closed issue, but I cannot find and docs, guides, blog posts or issues (except this one) giving me any kind of help regarding how to use cloudflare (or anything else other than google dns) as dns provider when using `jx boot`.
> 
> jx-requirements.yaml only allow me (afaik) to specify domain and externalDNS (true/false) but nothing specifying the provider and the provider specific setup. Could you point me to any more detailed information than just the jx-requirements-file? @cagiti @ccojocar @afirth

Further doco is on the external-dns side. It must be configured for your dns provider, but from the jx side there is simply the annotations. There's a helm chart to install, or you can set the container args directly on the external-dns deployment. I'm not familiar with how jx sets it up, I abandoned getting that working
