### ISSUE TITLE
jx import --url invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#1013]
When I import a project from github got some erros:
Here is my cmd `x import --url git@github.com:LinuxSuRen/jx-demo-test.git`

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x22fccbe]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).Run(0xc42011f400, 0xc420341c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:221 +0x8ce
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdImport.func1(0xc420430a00, 0xc42019a8c0, 0x0, 0x2)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:141 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420430a00, 0xc42019a8a0, 0x2, 0x2, 0xc420430a00, 0xc42019a8a0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42009f680, 0xc42022ea00, 0xc42042a780, 0xc420234c80)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42009f680, 0xc4200f6f80, 0x34a5a40)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4203bdf70, 0x2397a89)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22

**Comment by ysaakpr** [comment]
Same happening with bitbucket with the latest jenkins x

```
jx                 1.2.123
jenkins x platform 0.0.1298
kubernetes cluster v1.9.6
kubectl            v1.10.0
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.7.4
```

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x16f9f8e]
> 
> goroutine 1 [running]:
> github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).Run(0xc420107200, 0xc420315c50, 0x0)
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:221 +0x8ce
> github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdImport.func1(0xc420506780, 0xc420184bc0, 0x0, 0x4)
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:141 +0x75
> github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420506780, 0xc420184b80, 0x4, 0x4, 0xc420506780, 0xc420184b80)
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
> github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420081400, 0xc420548780, 0xc420500500, 0xc4203aaa00)
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
> github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420081400, 0xc42017af80, 0x28a0a40)
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
> github.com/jenkins-x/jx/cmd/jx/app.Run(0xc420091f70, 0x1794c59)
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
> main.main()
> 	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22

**Comment by jstrachan** [comment]
I think this is now fixed - I wonder could you try reproduce it again after running `jx upgrade cli`

**Comment by jstrachan** [comment]
cc @LinuxSuRen @ysaakpr

**Comment by LinuxSuRen** [comment]
Before error is gone after I upgrade jx. But I get other issues, now I can't access http://jenkins.jx.localhost/me/configure

NAME               VERSION
jx                 1.2.135
jenkins x platform 0.0.1193
kubernetes cluster v1.9.2
kubectl            v1.9.2
helm client        v2.8.2+ga802316
helm server        v2.8.2+ga802316
git                git version 2.17.0

localhost:a mac$ kubectl get all -n jx
NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/jenkins                         1         1         1            1           14m
deploy/jenkins-x-chartmuseum           1         1         1            1           14m
deploy/jenkins-x-docker-registry       1         1         1            1           14m
deploy/jenkins-x-heapster              1         1         1            1           14m
deploy/jenkins-x-mongodb               1         1         1            1           14m
deploy/jenkins-x-monocular-api         1         1         1            1           14m
deploy/jenkins-x-monocular-prerender   1         1         1            1           14m
deploy/jenkins-x-monocular-ui          1         1         1            1           14m
deploy/jenkins-x-nexus                 1         1         1            1           14m
deploy/pipelinecontroller              1         1         1            1           14m

NAME                                         DESIRED   CURRENT   READY     AGE
rs/jenkins-7cd58d874c                        1         1         1         14m
rs/jenkins-x-chartmuseum-7b95b777b           1         1         1         14m
rs/jenkins-x-docker-registry-6786bc55b7      1         1         1         14m
rs/jenkins-x-heapster-76df87bd59             1         1         1         14m
rs/jenkins-x-heapster-96bd95dcf              0         0         0         14m
rs/jenkins-x-mongodb-6c84f866dc              1         1         1         14m
rs/jenkins-x-monocular-api-5f9f84ff59        1         1         1         14m
rs/jenkins-x-monocular-prerender-6d8897856   1         1         1         14m
rs/jenkins-x-monocular-ui-69b4b898c4         1         1         1         14m
rs/jenkins-x-nexus-57866468c9                1         1         1         14m
rs/pipelinecontroller-5dbc96bbd4             1         1         1         14m

NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/jenkins                         1         1         1            1           14m
deploy/jenkins-x-chartmuseum           1         1         1            1           14m
deploy/jenkins-x-docker-registry       1         1         1            1           14m
deploy/jenkins-x-heapster              1         1         1            1           14m
deploy/jenkins-x-mongodb               1         1         1            1           14m
deploy/jenkins-x-monocular-api         1         1         1            1           14m
deploy/jenkins-x-monocular-prerender   1         1         1            1           14m
deploy/jenkins-x-monocular-ui          1         1         1            1           14m
deploy/jenkins-x-nexus                 1         1         1            1           14m
deploy/pipelinecontroller              1         1         1            1           14m

NAME                                         DESIRED   CURRENT   READY     AGE
rs/jenkins-7cd58d874c                        1         1         1         14m
rs/jenkins-x-chartmuseum-7b95b777b           1         1         1         14m
rs/jenkins-x-docker-registry-6786bc55b7      1         1         1         14m
rs/jenkins-x-heapster-76df87bd59             1         1         1         14m
rs/jenkins-x-heapster-96bd95dcf              0         0         0         14m
rs/jenkins-x-mongodb-6c84f866dc              1         1         1         14m
rs/jenkins-x-monocular-api-5f9f84ff59        1         1         1         14m
rs/jenkins-x-monocular-prerender-6d8897856   1         1         1         14m
rs/jenkins-x-monocular-ui-69b4b898c4         1         1         1         14m
rs/jenkins-x-nexus-57866468c9                1         1         1         14m
rs/pipelinecontroller-5dbc96bbd4             1         1         1         14m

NAME                                               READY     STATUS    RESTARTS   AGE
po/jenkins-7cd58d874c-9cncr                        1/1       Running   2          14m
po/jenkins-x-chartmuseum-7b95b777b-tczbt           1/1       Running   0          14m
po/jenkins-x-docker-registry-6786bc55b7-bc84j      1/1       Running   0          14m
po/jenkins-x-heapster-76df87bd59-49nqq             2/2       Running   0          14m
po/jenkins-x-mongodb-6c84f866dc-5hnwv              1/1       Running   0          14m
po/jenkins-x-monocular-api-5f9f84ff59-lf6fl        1/1       Running   1          14m
po/jenkins-x-monocular-prerender-6d8897856-rg2cg   1/1       Running   0          14m
po/jenkins-x-monocular-ui-69b4b898c4-fxl2p         1/1       Running   0          14m
po/jenkins-x-nexus-57866468c9-rxbff                1/1       Running   0          14m
po/pipelinecontroller-5dbc96bbd4-wbkgs             1/1       Running   0          14m

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
svc/heapster                        ClusterIP   10.100.183.154   <none>        8082/TCP    14m
svc/jenkins                         ClusterIP   10.97.11.230     <none>        8080/TCP    14m
svc/jenkins-agent                   ClusterIP   10.101.57.191    <none>        50000/TCP   14m
svc/jenkins-x-chartmuseum           ClusterIP   10.99.248.51     <none>        8080/TCP    14m
svc/jenkins-x-docker-registry       ClusterIP   10.97.24.175     <none>        5000/TCP    14m
svc/jenkins-x-mongodb               ClusterIP   10.102.80.156    <none>        27017/TCP   14m
svc/jenkins-x-monocular-api         ClusterIP   10.104.39.47     <none>        80/TCP      14m
svc/jenkins-x-monocular-prerender   ClusterIP   10.97.152.130    <none>        80/TCP      14m
svc/jenkins-x-monocular-ui          ClusterIP   10.110.165.62    <none>        80/TCP      14m
svc/nexus                           ClusterIP   10.111.70.139    <none>        80/TCP      14m

**Comment by LinuxSuRen** [comment]
I already fixed my problem. Thanks @jstrachan again.
