### ISSUE TITLE
Refactor the cmd package by grouping the related commands in sub-packages

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#1016]
It would be nice to organise the related commands in sub-packages, and maybe move out some general purpose packages such as log.

**Comment by garethjevans** [comment]
I was also wondering if we could make the commands a little more testable.  The runCommand* methods are a little hard to mock out

**Comment by garethjevans** [comment]
Something like https://npf.io/2015/06/testing-exec-command/

**Comment by jstrachan** [comment]
that sounds good!

**Comment by rawlingsj** [comment]
@ccojocar with your recent refactoring is this something that's more achievable?

/kind enhancement 
/priority important-longterm

**Comment by ccojocar** [comment]
@rawlingsj I think we have done a fair amount of refactoring moving out the common code in separate packages. I would say that now it would be possible to start splitting the commands in separate packages.

**Comment by pmuir** [comment]
Why did you close this @ccojocar it's still a big mess.

**Comment by ccojocar** [comment]
We can keep it open, but we can also follow up with small issue.

**Comment by ccojocar** [comment]
A few refactorings go merged. They are required to start splitting the clients factory and common in separate packages from cmd.

**Comment by ccojocar** [comment]
Next step is to extract the clients factory in a separate package, and use it only as a private field in the `CommonOptions`. The goal is to avoid using it directly in the `cmd` package.

**Comment by ccojocar** [comment]
Next step at this stage is to move the `CommonOptions` in a separate package. Finally, we can group the commands in separate packages after this is done.

**Comment by hferentschik** [comment]
Heads up, I am working on a pull request to restructure the commands into subpackages. I'll open a follow-up issue I guess.
