### ISSUE TITLE
jx install fail

### ISSUE THREAD

**Issue by guleng** [jenkins-x/jx#1026]
Installed on kubernetes Report errors
Execute a command    jx    install   Installation failure

The failure hints are:
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
ingress init failed: service jxing-nginx-ingress-controller never became ready
error: service jxing-nginx-ingress-controller never became ready

Ask for help。

**Comment by ccojocar** [comment]
@guleng Please could you provide more information regarding your setup? Which Kubernetes cluster do you run? Version?

**Comment by guleng** [comment]
@ccojocar The version of kubernetes cluster  is 1.9.1

**Comment by dongdan39** [comment]
Hi, guleng,
   Are you installing on a local Kubernetes cluster? I'm afraid later you will fail the installation on PV/PVC creation. Please keep us updated about your jx installation status. Thanks!

Cheers,
Dan

**Comment by guleng** [comment]
@dongdan39 Do you have the installation help document to recommend sharing? There are too many problems.

Seek help
Thank you！

**Comment by guleng** [comment]
@ccojocar jxing-nginx-ingress-controller        LoadBalancer   10.254.197.233   <pending>     80:1118/TCP,443:46967/TCP   15m .       
Is this automatically acquired or is the load balancing IP specified during installation?

**Comment by dongdan39** [comment]
@guleng Seems we have very limited official help documents for jx installation. Wish jx experts to give more hands on this issue. Otherwise, people will try, fail and leave soon.

**Comment by jstrachan** [comment]
@guleng I wonder if you could try the kubernetes compliance tests? That might help find any particular anomolies of your cluster:
```
jx compliance run
jx compliance results
```
Does your cluster have RBAC enabled?

Just knowing helm can't install a fairly straightforward chart unfortunately doesn't give us lots of information to help diagnose the problem. I wonder if 

```
jx install --verbose
```
gives any more information about why things fail?

BTW the ingress controller doesn't use any persistence AFAIK; so its not storage related. My guess is its RBAC maybe?

**Comment by jstrachan** [comment]
I wonder if this is a duplication of this issue: https://github.com/jenkins-x/jx/issues/552#issuecomment-397191010

**Comment by jstrachan** [comment]
the new `1.2.136` release is out which has this issue fixed AFAIK. 

To upgrade try:
```
jx upgrade cli
```
then here's the docs on how to use it:
https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise

**Comment by guleng** [comment]
@jstrachan   I upgraded JX 1.2.136, HELM v2.8, k8s 1.9

use installation  "JX install --provider=kubernetes --on-premise" Report errors
----------------------------------------------------------------------------------------------------
helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://chartmuseum.build.cd.jenkins-x.io/index.yaml: dial tcp 35.205.186.189:443: connect: connection refused
make: *** [build] 错误 1
Error: Command failed  make ARGS=--values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2

Thank you very much.

**Comment by jstrachan** [comment]
@guleng looks like a temporary issue with chart museum being down - we're looking at an alternative more reliable chart repository implementation. I wonder if you could retry again now that it looks like chartmuseum is back up again

**Comment by guleng** [comment]
@jstrachan 
Try again. Report errors
-----------------------------------------------------------------------------------------------
Update Complete. ⎈ Happy Helming!⎈ 
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.1436 --values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: a release named jenkins-x already exists.
Run: helm ls --all jenkins-x; to check the status of the release
Or run: helm del --purge jenkins-x; to delete it
make: *** [install] 错误 1
Error: Command failed  make ARGS=--values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2

**Comment by guleng** [comment]
@jstrachan   
same Report errors
---------------------------------------------------------------------------------------------
helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: read tcp 192.168.79.130:47108->35.205.186.189:443: read: connection reset by peer
make: *** [build] 错误 1
Error: Command failed make ARGS=--values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2

**Comment by jstrachan** [comment]
I wonder is there a firewall blocking access? e.g. try:
```
curl -v https://chartmuseum.build.cd.jenkins-x.io/api/charts
```
does it return json?

**Comment by guleng** [comment]
@jstrachan  
-----------------------------------------------------------------------------------------------
install New progress
------------------------------------------------------------------------------------------------
jenkins-x-chartmuseum-7b95b777b-sdsqj           0/1       ContainerCreating
jenkins-x-docker-registry-6786bc55b7-b2fhx      0/1       ContainerCreating
jenkins-x-mongodb-6c84f866dc-sqbhc              0/1       ContainerCreating
jenkins-x-nexus-57866468c9-x8vvb                0/1       ContainerCreating

Unable to mount volumes for pod "jenkins-x-chartmuseum-7b95b777b-sdsqj_jx(027d6b9f-75a1-11e8-bc9c-000c294be5f3)": timeout expired waiting for volumes to attach/mount for pod "jx"/"jenkins-x-chartmuseum-7b95b777b-sdsqj". list of unattached/unmounted volumes=[storage-volume]

-----------------------------------------------------------------------------------------------
These are ahead of time create volume ？
------------------------------------------------------------------------------------------------
jenkins-x-monocular-api-78dbc7b98f-ws84v        0/1       CrashLoopBackOff

kubectl describe  pod -n jxjenkins-x-monocular-api-78dbc7b98f-ws84v 
            ........
            ...............
          Normal   Started                53m (x4 over 55m)    kubelet, 192.168.79.132  Started container
  Normal   Pulling                30m (x10 over 55m)   kubelet, 192.168.79.132  pulling image "bitnami/monocular-api:v0.6.1"
  Warning  BackOff                29s (x235 over 54m)  kubelet, 192.168.79.132  Back-off restarting failed container

kubectl logs -n jx jenkins-x-monocular-api-78dbc7b98f-ws84v          
time="2018-06-21T23:11:10Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-06-21T23:11:10Z" level=info msg="Configuration file found!" 
time="2018-06-21T23:11:10Z" level=info msg="Loading CORS from config file" 
time="2018-06-21T23:11:10Z" level=info msg="Loading repositories from config file" 
time="2018-06-21T23:11:10Z" level=info msg="Configuration bootstrap finished" 
time="2018-06-21T23:11:21Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017"
--------------------------------------------------------------------------------------------

Seek help
Thank you！

**Comment by livelyRyan** [comment]
@guleng  朋友  我遇到了和你一样的问题  缺少pv。我是在virtualbox里搭的集群，请问你这个问题解决了吗

**Comment by jstrachan** [comment]
@guleng whats the output of `kubectl get pvc` if the PVCs are unbound then its possible your k8s cluster does not have a default storage class defined?
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

**Comment by livelyRyan** [comment]
@dongdan39 Hi ,dongdan39,
I’m installing on a local Kubernetes cluster . As you expected, I failed the installation on PV/PVC creation.
Components require 5 PVCs and no PVs available. How can i get PVs? I built the cluster by using virtualbox.

**Comment by jstrachan** [comment]
@livelyRyan see the above link - you need a default storage class for implementing PVs

**Comment by guleng** [comment]
@jstrachan  

[root@hp-001 ~]# jx install --provider=kubernetes --on-premise 
Git configured for user: guleng and email guleng
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Error: failed to download "stable/nginx-ingress"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: failed to download "stable/nginx-ingress"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: failed to download "stable/nginx-ingress"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: failed to download "stable/nginx-ingress"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
ingress init failed: deployments.extensions "jxing-nginx-ingress-controller" not found
error: deployments.extensions "jxing-nginx-ingress-controller" not found

**Comment by guleng** [comment]
@jstrachan  @jstrachan 

Then COPY the token and enter in into the form below:

? API Token: Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
Counting objects: 718, done.
Total 718 (delta 0), reused 0 (delta 0), pack-reused 718
error: secrets "jx-install-config" already exists
[root@hp-001 ~]#

**Comment by guleng** [comment]
@jstrachan  
        Getting Jenkins API Token
retrying after error:unable to find external URL annotation on service jenkins
retrying after error:unable to find external URL annotation on service jenkins
error: after 3 attempts, last error: unable to find external URL annotation on service jenkins

**Comment by livelyRyan** [comment]
@jstrachan 
Ye, I have solved this problem by your link, thank you very much.
But I now have the same problem as @guleng .
command `jx install --provider kubernetes --on-premise` got the result：
```
        Getting Jenkins API Token
using url http://jenkins.jx.192.168.1.169/me/configure
unable to automatically find API token with chromedp using URL http://jenkins.jx.192.168.1.169/me/configure
Please go to http://jenkins.jx.192.168.1.169/me/configure and click Show API Token to get your API Token
Then COPY the token and enter in into the form below:

? API Token: 
```
I can't access this URL, so I can't get the token.The pod jenkins is normal.

**Comment by McDingl** [comment]
@jstrachan@guleng     i got the same  err:
![image](https://user-images.githubusercontent.com/37035429/42803654-349d474e-89d9-11e8-9827-bdf5b198c661.png)
jstrachan

**Comment by ccojocar** [comment]
The compliance tests take about 1 hour. What does `jx compliance status` return? You can retrieve the results only when you see in the status message that the compliance tests are completed.

**Comment by McDingl** [comment]
@ccojocar  jx compliance status  output：

error: failed to retrieve the status: pod has status "Pending"

**Comment by ccojocar** [comment]
@McDingl I would run again the compliance. You can execute the following commands:

`jx compliance delete`
`jx compliance run`

Wait for about 1 hour, you can check the status with `jx compliance status`

`jx compliance results`

**Comment by McDingl** [comment]
@ccojocar " jx compliance run"   will run in background 1 hour?    seem run 3 second in terminal.

**Comment by ccojocar** [comment]
That's right. I will run in background for about 1 hour.

**Comment by McDingl** [comment]
@ccojocar thanks , after 1 hour : 
1.jx compliance status:
error: failed to retrieve the status: pod has status "Pending"
2.jx compliance results:

ERRO[0000] unable to upgrade connection: container not found ("kube-sonobuoy")
error: could not extract the compliance results from archive: no compliance results archive found

**Comment by ccojocar** [comment]
@McDingl What do you get when running:

```kubectl get all -n heptio-sonobuoy```

All the compliance resources are created in this namespace.

Which Kubernetes cluster are you trying to validate?

**Comment by ccojocar** [comment]
I would try to do a `kubectl describe` on the POD which is pending. I think that there is some dependency which is missing and Kubernetes cannot schedule the POD.

**Comment by kumarinfo90** [comment]
I am trying to jx cluster on azure and i am getting the following error.
error creating cluster failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.2789 --values /root/.jx/cloud-environments/env-aks/myvalues.yaml --values /root/.jx/cloud-environments/env-aks/secrets.yaml --values /root/.jx/gitSecrets.yaml --values /root/.jx/adminSecrets.yaml --values /root/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/root/.jx/cloud-environments/env-aks', output: 'Release "jenkins-x" does not exist. Installing it now.
Error: watch closed before Until timeout': exit status 1

please give me a solution.

**Comment by bisi1** [comment]
@kumarinfo90  were you able to fix the issue. I am also getting the same error.

**Comment by rbizzell40** [comment]
I am trying to install jx on existing cluster and I am running into failure.
jx install --provider gke --tekton --external-dns
existing ingress controller found, no need to install a new oneWaiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
FATAL: ingress init failed: service jxing-nginx-ingress-controller never became ready
I have tried to edit the jx-requirements.yml and input my existing dns but it still fails to provision

**Comment by jstrachan** [comment]
@rbizzell40 the `jx-requirements.yml` file is used for `jx boot` not `jx install` https://jenkins-x.io/docs/getting-started/setup/boot/

**Comment by rbizzell40** [comment]
Sorry typo I meant jx install

**Comment by rbizzell40** [comment]
This is the command I executed

jx install --provider gke --tekton --external-dns

existing ingress controller found, no need to install a new one

Waiting for external loadbalancer to be created and update the
nginx-ingress-controller service in kube-system namespace

FATAL: ingress init failed: service jxing-nginx-ingress-controller never
became ready

**Comment by prashankprince** [comment]
jx boot fails in STEP: create-install-values command with below error:

STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /home/ubuntu/jenkins-x-boot-config/env

Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
If you are installing Jenkins X on premise you may want to use the '--on-premise' flag or specify the '--external-ip' flags. See: https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output: ''


Tried to do jx init as well , similar error:

jx init
? Cloud Provider aws
Git configured for user: xxx and email xxx@xxx.com
Helm installed and configured
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
FATAL: ingress init failed: service jxing-nginx-ingress-controller never became ready

Can someone help here?
