### ISSUE TITLE
should we look at GoFish to improve installation of tools on Windows + Linux?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1033]
brew works fine for OS X but it might be nice to use something like GoFish for Windows/Linux?
https://www.gofi.sh/

**Comment by bacongobbler** [comment]
Having more options never hurt, and you know who to ping if you're running into issues (hint: it's me 😉)

I maintain this project on my free time but would love to support jx! It should be fairly straightforward to make a package. Let me know if you have any questions/concerns.
