### ISSUE TITLE
Volatile Load Balancer IP in jx created AWS Cluster

### ISSUE THREAD

**Issue by biancajiang** [jenkins-x/jx#1050]
Created two clusters with jx and got all services (Jenkins console, chartmuseum, docker-registry etc.) up and running.  Then after a couple hours the Load Balancer IP will change and causing no services accessible anymore even everything is healthy.  

There's a note from AWS load balancer page in console that states:

"Because the set of IP addresses associated with a LoadBalancer can change over time, you should never create an "A" record with any specific IP address. If you want to use a friendly DNS name for your load balancer instead of the name generated by the Elastic Load Balancing service, you should create a CNAME record for the LoadBalancer DNS name, or use Amazon Route 53 to create a hosted zone. For more information, see Using Domain Names With Elastic Load Balancing."

Does this happen to anybody else?  Any temporary workaround?

**Comment by rawlingsj** [comment]
Yes this behaviour has been reported on slack but not the explanation you've quoted above.  I expect this is going to be the same for EKS.

**Comment by jstrachan** [comment]
am working on this ATM - hoping to have a fix soon. see https://github.com/jenkins-x/jx/issues/1256
