### ISSUE TITLE
Support helm values file while doing jx promote

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1052]
This is the code snippet from promote.go, The helm upgrade doesnt support modifying the values file.
In this design how are one supposed to modify the helm values for every environment to different one.
```
promoteKey.OnPromoteUpdate(o.Activities, startPromote)

	if version != "" {
		err = o.runCommand("helm", "upgrade", "--install", "--wait", "--namespace", targetNS, "--version", version, releaseName, fullAppName)
	} else {
		err = o.runCommand("helm", "upgrade", "--install", "--wait", "--namespace", targetNS, releaseName, fullAppName)
	}
```

**Comment by jstrachan** [comment]
I think the code you are looking at is for the non-GitOps approach. When using GitOps the git repository for each environment has a `env/values.yaml` file which is used to store any environment specific settings.

e.g. type:
```
jx get env
```
then click on the git source URL for the `staging` environment, then navigate to the `env/values.yaml` file and edit it.

Then for an app, `foo` thats deployed into `Staging` add this to the bottom of the file:
```
foo:    
  replicaCount: 2  
```

Commit that change to master then when the `Staging` pipeline runs you should see `foo` scale up to 2 pods. You've now made an environment specific configuration change for `foo` using GitOps
