### ISSUE TITLE
docker-credential-ecr-login in builder base

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1062]
In order to do ecr integration, can we make the builder base to support docker-credential-ecr-login binary.

**Comment by jstrachan** [comment]
see https://github.com/jenkins-x/jx/issues/399#issuecomment-397863351

we already have a secret mounted into all build pods that contains the docker `config.json` required to talk to any docker registry

**Comment by ysaakpr** [comment]
I already tried with this approach, but i am always getting Error: docker-credential-ecr-login  not found in $PATH. Following is my config.json.

```
{
  "credHelpers": {
    "account.dkr.ecr.ap-south-1.amazonaws.com": "ecr-login"
  }
}
```

Am i doing anything wrong

**Comment by jstrachan** [comment]
looks like we'll need to mount a Secret for the docker-credential-ecr-login

**Comment by ysaakpr** [comment]
docker-credential-ecr-login is not a secret, btw its a binary file, having that the docker will automatically able to authenticate with ecr, without configuring the ecr secrets. Can you direct me if i am wrong ?

**Comment by ysaakpr** [comment]
@jstrachan  @rajdavies created a pull request to support ecr-login helper in the builder base. Can you please try merging it if you find its good to go..
https://github.com/jenkins-x/builder-base/pull/358

**Comment by jstrachan** [comment]
@yahavi many thanks, will take a look!

**Comment by jstrachan** [comment]
@yahavi merged - will have a release with it inside in a few hours, I'll update this issue when its out

**Comment by ysaakpr** [comment]
@jstrachan Thanks a lot...Looks like jx-platform and jenkins-x-image are not building. You might need to trigger a manual build for both of them.
