### ISSUE TITLE
--exposer=NodePort creates LoadBalancer service

### ISSUE THREAD

**Issue by arkadiyk** [jenkins-x/jx#1064]
I am trying to install jx on my in-house cluster:

```sh
jx install --exposer=NodePort --on-premise=true --provider=kubernetes --verbose
```
The script creates `LoadBalancer` instead of `NodePort`

```
==> v1/Service
NAME                                 TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)                     AGE
jxing-nginx-ingress-controller       LoadBalancer  10.43.30.202   <pending>    80:32171/TCP,443:32216/TCP  2s
jxing-nginx-ingress-default-backend  ClusterIP     10.43.196.246  <none>       80/TCP                      2s
```

Thanks

**Comment by jstrachan** [comment]
we don't currently support `NodePort`

**Comment by cvila84** [comment]
@arkadiyk it is a nice to have as loadbalancer services also imply nodeport to be created (32171 and 32216 in your example). the only drawback is that your external IP remains pending indefinitely but adding `--on-premise` prevents jenkins-x to wait for external IP to be fulfilled by cloud provider

**Comment by sercanacar** [comment]
@cvila84 did you remember if you were able to successfully install and access jx `on-premise`? I'm having problems accessing service via HTTP after a successful `jx install`, nothing is exposed on port 80/443

**Comment by ccojocar** [comment]
Closing this since we are not planning to support NodePort. Typically Kubernetes recommend the usage of ClusterIP.
