### ISSUE TITLE
Define the Kubernetes pod and network security policies in jenkins-x platform

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#1074]
It would be nice to define the POD and Network security policies for Jenkins X platform in order to increase the isolation between the CI/CD platform and the environments where the applications are running. 

This could make some users more confident to use the Jenkins X platform in the same cluster with the production environment.

https://speakerdeck.com/ianlewis/kubernetes-security-best-practices?slide=36
https://github.com/freach/kubernetes-security-best-practice

**Comment by madchap** [comment]
Cilium would probably be useful here (https://cilium.io) and worth a look rather sooner than later, even if it is not doing anything much at first (log only?). Just to avoid as much as possible costly rework down the road. Thoughts?
