### ISSUE TITLE
support an alternative github pages style repository instead of chart museum?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1079]
it seems our current chart museum can go down from time to time. Lets investigate switching to a github pages style helm chart repository?

see https://github.com/technosophos/helm-github

**Comment by rawlingsj** [comment]
yeah - being able to switch to using github pages gets a big +1 from me

**Comment by rawlingsj** [comment]
if nobody picks this up I will after I clear my current list
