### ISSUE TITLE
Problems interacting with Git

### ISSUE THREAD

**Issue by RamonGebben** [jenkins-x/jx#1095]
While trying to use the `jx` cli I'm running into some trouble with Git interactions.

When I try to create a quickstart like so:
```bash
jx create quickstart
# Selected node-http
```
It walks me through the creation process:

```? select the quickstart you wish to create node-http
? Project name demo
Generated quickstart at /Users/ramongebben/Projects/demo
### NO charts folder /Users/ramongebben/Projects/demo/charts/node-http
Created project at /Users/ramongebben/Projects/demo

? Do you wish to use RamonGebben as the git user name: Yes
? Would you like to initialise git now? Yes
Initialized empty Git repository in /Users/ramongebben/Projects/demo/.git/
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   .gitignore
	new file:   LICENSE
	new file:   README.md
	new file:   curlloop.sh
	new file:   index.html
	new file:   package.json
	new file:   server.js
	new file:   watch.sh
? Commit message:  Initial import
[master (root-commit) 936b554] Initial import
 8 files changed, 320 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 LICENSE
 create mode 100644 README.md
 create mode 100755 curlloop.sh
 create mode 100644 index.html
 create mode 100644 package.json
 create mode 100644 server.js
 create mode 100755 watch.sh

Git repository created
fatal: repository 'master' does not exist
error: failed to git clone to /Users/ramongebben/.jx/draft/packs/master due to exit status 128
```

The same `due to exit status 128` I also receive when trying to run `jx import` from an existing directory.

**Version**
```
NAME               VERSION
jx                 1.3.13
jenkins x platform 0.0.1456
kubernetes cluster v1.8.10-gke.0
kubectl            v1.10.4
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.1 (Apple Git-101)
```
Any ideas on how to correct this?

**Comment by jstrachan** [comment]
I'm a bit confused by the line:
```
error: failed to git clone to /Users/ramongebben/.jx/draft/packs/master due to exit status 128
```
I get:
```
Cloning into '/Users/jstrachan/.jx/draft/packs/github.com/jenkins-x/draft-packs'...
```
I wonder what is the output of
```
jx get buildpack
```
I wonder have you tried to configure the build pack URL to something, like `master`? FWIW the output for me is:
```
$ jx get buildpack
BUILD PACK GIT URL                           GIT REF
https://github.com/jenkins-x/draft-packs.git 2.0
```

**Comment by RamonGebben** [comment]
I get this as output: 
```
jx get buildpack
BUILD PACK GIT URL GIT REF
master             2.0
```

I think I need to set that to the correct value?
What I tried with this information is:

```
jx edit buildpack
```
And provided the value: `https://github.com/jenkins-x/draft-packs.git` and "Build pack git ref" to 2.0.
However when I get it again it changes into:
```
BUILD PACK GIT URL GIT REF
2.0                2.0
```
Which I might be a bug on it's own.
When I provide the URL twice( as url and git ref) it looks like it works because my `jx get buildpack` looks like this:
```
BUILD PACK GIT URL                           GIT REF
https://github.com/jenkins-x/draft-packs.git 2.0
```

And I get this output when running `jx import`.

```💩 : jx import
? git user name: Sensorfactdev
Already up to date.
performing pack detection in folder /Users/ramongebben/Sensorfact/service-mongo
--> Draft detected YAML (46.406045%)
--> Could not find a pack for YAML. Trying to find the next likely language match...
--> Draft detected RPM Spec (19.132720%)
--> Could not find a pack for RPM Spec. Trying to find the next likely language match...
--> Draft detected Perl (18.771353%)
--> Could not find a pack for Perl. Trying to find the next likely language match...
--> Draft detected Assembly (6.307490%)
--> Could not find a pack for Assembly. Trying to find the next likely language match...
--> Draft detected Coq (4.717477%)
--> Could not find a pack for Coq. Trying to find the next likely language match...
--> Draft detected Smarty (3.390276%)
--> Could not find a pack for Smarty. Trying to find the next likely language match...
--> Draft detected Text (0.663601%)
--> Could not find a pack for Text. Trying to find the next likely language match...
--> Draft detected M (0.611038%)
--> Could not find a pack for M. Trying to find the next likely language match...
error: there was an error detecting the language using packs from /Users/ramongebben/.jx/draft/packs
```
Which I think is an issue I need to address in my project.

**Comment by jstrachan** [comment]
@RamonGebben thanks for the heads up! yes we had a bug in the `jx edit buildpack` which was using the ref for both URL and ref ;) Just pushed a fix, should be released in an hour or so.

It looks like its working fine for your project now. If there's a specific build pack you wanna force you can use the `jx import --pack javascript` or whatever https://jenkins-x.io/commands/jx_import/

more info on build packs: https://jenkins-x.io/architecture/build-packs/

let us know if you want help setting up a build pack for your project; we could add it to the build pack library

**Comment by RamonGebben** [comment]
@jstrachan I'm currently trying to add MongoDB to my cluster so I assumed I needed to make a project for that. This project would hold the charts. 
I'm not sure this is the way if you could point me in the correct direction, that would be great.
I would have expected those kind of services also being documented in the Jenkins X docs so when I figure it out, I'd love to contribute to the documentation of it.

**Comment by jstrachan** [comment]
@RamonGebben thanks; we're working on some quickstarts using databases to help folks grok how to do it all. 

For now you can either add your database as a dependent chart in `charts/foo/requirements.yaml`

**Comment by jstrachan** [comment]
here's an example of adding postgres into an app's requirements.yaml: https://github.com/ryandawsonuk/example-runtime-bundle/blob/develop/charts/example-runtime-bundle/requirements.yaml
