### ISSUE TITLE
Error on jx install

### ISSUE THREAD

**Issue by Raichel** [jenkins-x/jx#1096]
After install jx, minikube and virtuabox on my macos
I run `jx install` and I keep getting this error:
error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
what do I miss here? is this token supposed to be on my local machine? where do I get it from?

appreciate any help

**Comment by jstrachan** [comment]
are you in a terminal that can access the k8s cluster when you type `jx install`? e.g. can you type: `kubectl get node` and what is the response?

**Comment by Raichel** [comment]
kubectl is working perfect, I have full access to all minikube resources. for instance, this is the result of kubectl get nodes:
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     master    3h        v1.10.0

I also have two other clusters in IBM where I get the same error. Is there any thing to do with serviceaccount token? do I need to do something with RBAC on minikube

**Comment by jstrachan** [comment]
could you show the full output of `jx install` please to see where that error message occurs?

**Comment by jstrachan** [comment]
btw you are running `jx install` outside of a pod right?

**Comment by Raichel** [comment]
Yes, I'm on my local machine, what is the correct way of doing this? should I connect to a pod (which pod) on my cluster and install JX there?

**Comment by Raichel** [comment]
@jstrachan  More info...

this is the output of `jx create cluster minikube --local-cloud-environment=true --verbose`:

`Creating Minikube cluster...
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
Minikube cluster created.
clusterrolebinding.rbac.authorization.k8s.io "add-on-cluster-admin" created
Initialising cluster ...
error creating cluster open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`

**Comment by jstrachan** [comment]
I wonder if its that when you don't run as root the current user can't access `~/.kube/config`? That file should  exist and be readable by the current user if the current user can run `kubectl get pods` correctly

**Comment by jstrachan** [comment]
@Raichel try `ls -al ~/.kube/config` and see what it looks like?

**Comment by Raichel** [comment]
@jstrachan ok, solved!
I'm working with bluemix (IBM) my config files are in different folder `~/.bluemix/...`
I do have an the correct path in KUBECONFIG, but it seems jx only case abour `~/.kube/config`
Anyways, when the contexts are defined in .kube/config, it looks like it's working

Thanks a lot @jstrachan, and KUDOS for this nice project
