### ISSUE TITLE
jx version continually prompts to upgrade

### ISSUE THREAD

**Issue by jtfogarty** [jenkins-x/jx#1109]
On OS X I executed the below;
It says that 1.3.18 is available but 1.3.17 is the latest brew knows about

> Jeffs-iMac:google.golang.org jeff-imac$ jx version
> NAME               VERSION
> jx                 1.2.122
> jenkins x platform 0.0.1193
> kubernetes cluster v1.8.10-gke.0
> kubectl            v1.10.0
> helm client        v2.9.1+g20adb27
> helm server        v2.9.1+g20adb27
> git                git version 2.16.3
> 
> ? Would you like to upgrade to the new jx version? Yes
> ? Would you like to upgrade to the new jx version? [? for help] (Y/n) Y
> Jeffs-iMac:google.golang.org jeff-imac$ jx version
> NAME               VERSION
> jx                 1.3.17
> jenkins x platform 0.0.1193
> kubernetes cluster v1.8.10-gke.0
> kubectl            v1.10.0
> helm client        v2.9.1+g20adb27
> helm server        v2.9.1+g20adb27
> git                git version 2.16.3
> 
> ? Would you like to upgrade to the new jx version? Yes
> ? Would you like to upgrade to the new jx version? [? for help] (Y/n) 
> Error: Command failed  brew upgrade jx
> error: exit status 1
> Jeffs-iMac:google.golang.org jeff-imac$ brew upgrade jx
> Error: jenkins-x/jx/jx 1.3.17 already installed
> Jeffs-iMac:google.golang.org jeff-imac$ jx version
> NAME               VERSION
> jx                 1.3.17
> jenkins x platform 0.0.1193
> kubernetes cluster v1.8.10-gke.0
> kubectl            v1.10.0
> helm client        v2.9.1+g20adb27
> helm server        v2.9.1+g20adb27
> git                git version 2.16.3
> 
> A new jx version is available: 1.3.18
> ? Would you like to upgrade to the new jx version? [? for help] (Y/n)

**Comment by jstrachan** [comment]
I wonder if you run it 2 more times its up to date now? I wonder if its due to our CI/CD system being a little behind; that there's a release on github but brew hasn't caught up yet?

**Comment by jtfogarty** [comment]
yeah, I ran the update again and it went to 1.3.19
I ran jx version and it showed 1.3.24 being available but only 1.3.22 was installed

**Comment by i0n** [comment]
From https://github.com/jenkins-x/jx/releases/tag/v1.3.159 onwards we have semver enabled dev builds. If you are tracking development or contributing I would suggest that it's best to clone or fork the repo and make builds locally. If you're just looking to use the most recent release then you may find the version published on homebrew can be a little out of sync depending on the backlog of work on our CI/CD as we're often releasing multiple versions per day. I'm gonna close this for now, but feel free to open a new issue if you'd like to chat about how to sync this up perfectly.
