### ISSUE TITLE
jx sync error

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#1119]
jx version is here:

jx                 1.3.22
jenkins x platform 0.0.1436
kubernetes cluster v1.9.6
kubectl            v1.9.2
helm client        v2.8.2+ga802316
helm server        v2.9.1+g20adb27
git                git version 2.17.0

when I run jx sync, get some error

rpc error: code = Unknown desc = Error response from daemon: client is newer than server (client API version: 1.25, server API version: 1.24

I think we maybe should not get latest version, like this:
latestVersion, err := util.GetLatestVersionFromGitHub("vapor-ware", "ksync")

**Comment by jstrachan** [comment]
we do use that `latestVersion, err := util.GetLatestVersionFromGitHub("vapor-ware", "ksync")` code to install ksync already: https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/common_install.go#L635

I wonder if its due to the client being newer than a previous install of ksync?

**Comment by LinuxSuRen** [comment]
ksync need overlay or overlay2
docker version v17.06+ will support overlay2

@jstrachan  So I suggest give users some tips, or detect docker version.
