### ISSUE TITLE
You must verify your email address

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#1128]
When I promote app to env, get some errors like:

remote: You must verify your email address.
remote: See https://github.com/settings/emails.
fatal: unable to access 'https://github.com/jx-practice-k2/spring-boot-web.git/': The requested URL returned error: 403
make: *** [tag] Error 128

And I found the pod template like this:
spec:
  containers:
  - args:
    - cat
    command:
    - /bin/sh
    - -c
    env:
    - name: JENKINS_SECRET
      value: ad4f6260abdf60b063793f74db05cbab71671e77c99cfe7462f09e604f5ed129
    - name: JENKINS_TUNNEL
      value: jenkins-agent:50000
    - name: DOCKER_CONFIG
      value: /home/jenkins/.docker/
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot

How can I configure email as mine.

**Comment by ccojocar** [comment]
You can either overwrite the ` GIT_AUTHOR_EMAIL` and `GIT_COMMITTER_NAME` environment variables in the platform helm values or in the Jenkinsfile.

I am closing this for now. Feel free to open it again you still encounter the problem.
