### ISSUE TITLE
jx Install issue on EKS

### ISSUE THREAD

**Issue by sourabhg** [jenkins-x/jx#1132]
Following steps have been taken,

[Amazon EKS Getting Started](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)

Above tutorial has been followed to the point, after this tried installing jx on the cluster but getting following error

`$ jx install --provider=eks`
`error: invalid configuration: no configuration has been provided`

**Comment by jstrachan** [comment]
I wonder if you could try `jx create cluster eks` now instead? https://jenkins-x.io/commands/jx_create_cluster_eks/

**Comment by sourabhg** [comment]
I tried this following command

`jx create cluster eks --cluster-name "test-platform" --domain "kube.${mydomain}.com" --nodes 5 --region "us-east-1" --ssh-public-key "~/.ssh/test_kube.pub" --default-admin-password "testpass12"`

where ${mydomain} is actual domain and full entry for kube.${mydomain}.com is in Route 53. 

I am getting following error 

ingress init failed: Unauthorized
error: failed to initialize the jx: Unauthorized

**Comment by jvz** [comment]
Related to #1498?

**Comment by ccojocar** [comment]
The related issue seems to be fixed.
