### ISSUE TITLE
Docker registry contains "/"

### ISSUE THREAD

**Issue by liuxiaopiao** [jenkins-x/jx#1134]
If we use private docker registry and the pro name contains "/", it will throw error when building release:

[golang-http] Running shell script

+ make tag

sed -i -e "s/version:.*/version: 0.0.1/" Chart.yaml

sed -i -e "s/repository: .*/repository: XXXXX/XXXXX\/liuxiaopiao\/golang-http/" values.yaml

sed: -e expression #1, char 42: unknown option to `s'

make: *** [tag] Error 1

script returned exit code 2

**Comment by rawlingsj** [comment]
I guess a quick workaround would be to use a different delimiter?

i.e. something like..

sed -i -e "s|repository: .*|repository: XXXXX/XXXXX/liuxiaopiao/golang-http|" values.yaml

**Comment by rawlingsj** [comment]
If that works then we can update the [draft-packs](https://github.com/jenkins-x/draft-packs) repo to use a pipe delimiter instead.

**Comment by jstrachan** [comment]
I didn't think a docker registry can include a `/` can it? I thought it must be a hostname or hostname+port only?

**Comment by liuxiaopiao** [comment]
@jstrachan , yeah. the docker registry such like "registryprivate" doesn't contains "/" but we need to add the tenancy name so that we can push/pull  image in the format that "registryprivate/compute/liuxiaopiao/test:0.1"

In the project Makefile,  it has the line like 
`sed -i -e "s/repository: .*/repository: $(DOCKER_REGISTRY)\/liuxiaopiao\/$(NAME)/" values.yaml
`
So we need to specify DOCKER_REGISTRY as "registryprivate/compute" in jenkins configuration page.

**Comment by mlaflamm** [comment]
> I didn't think a docker registry can include a / can it? I thought it must be a hostname or hostname+port only?

FYI my AWS ECR repo does contains a /. When I run `aws ecr describe-repositories` I get this and the respositoryUri:
```
{
    "repositories": [
        {
            "registryId": "000000000000", 
            "repositoryName": "hilarious-sheepdog-1530035275", 
            "repositoryArn": "arn:aws:ecr:us-west-2:000000000000:repository/hilarious-sheepdog-1530035275", 
            "createdAt": 1530041803.0, 
            "repositoryUri": "000000000000.dkr.ecr.us-west-2.amazonaws.com/hilarious-sheepdog-1530035275"
        }
    ]
}

```

**Comment by hhuiliu** [comment]
@rawlingsj , any chance for you to take further checking for this issue?  Thanks a lot

**Comment by rawlingsj** [comment]
Ah sorry I got side tracked.  So I think all we need to do it update both the main chart and preview Makefiles in each draft-pack in this repo https://github.com/jenkins-x/draft-packs

i.e. main chart example 
https://github.com/jenkins-x/draft-packs/blob/master/packs/maven/charts/Makefile#L35-L40

preview chart example
https://github.com/jenkins-x/draft-packs/blob/master/packs/maven/preview/Makefile#L8-L15

Did you want to pop a PR together?  Or I can take a look soon.

**Comment by hhuiliu** [comment]
Sure. I will do one PR  now.

**Comment by rawlingsj** [comment]
awesome - thanks!

**Comment by hhuiliu** [comment]
Has submitted the pull request. For main chart makefile, just replace the slash with "|". For preview chart makefile, also delete "." in "sed -i -e "s/repository: **.***/repository:"

Please take a look at it.  Thanks a lot. This kind of modification works in my environment.

**Comment by hhuiliu** [comment]
Close the issue as this need to be fixed in draft-pack repo

**Comment by rawlingsj** [comment]
Fixed via https://github.com/jenkins-x/draft-packs/pull/46#pullrequestreview-134016178 thanks!
