### ISSUE TITLE
Failed to pull image "draft:0.0.2": 

### ISSUE THREAD

**Issue by liuxiaopiao** [jenkins-x/jx#1136]
I have the latest version jx cli and would like to try creating one quickstart project such like golang-http.
After the "jx creat quickstart" finished, I can get the application url by:
`[opc@demotest golang-http]$ jx get apps

APPLICATION STAGING PODS URL                                                 PRODUCTION PODS URL

golang-http 0.0.2        http://golang-http.jx-staging.111.111.111.80.nip.io
`

When trying to access http://golang-http.jx-staging.111.111.111.80.nip.io, it said 503 error. 

And checking pod status:
`[opc@demotest golang-http]$ kubectl describe pod/jx-staging-golang-http-7c8f549bb6-h5kmn --namespace=jx-staging
Name:           jx-staging-golang-http-7c8f549bb6-h5kmn
Namespace:      jx-staging
Node:           111.111.111.80/10.0.11.74
Start Time:     Mon, 25 Jun 2018 14:09:37 +0000
Labels:         app=jx-staging-golang-http
                draft=draft-app
                pod-template-hash=3749105662
Annotations:    <none>
Status:         Pending
IP:            111.111.111.80
Controlled By:  ReplicaSet/jx-staging-golang-http-7c8f549bb6
Containers:
  golang-http:
    Container ID:
    Image:          draft:0.0.2
    Image ID:
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  256Mi
    Requests:
      cpu:        80m
      memory:     128Mi
    Liveness:     http-get http://:8080/ delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:8080/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lkb59 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-lkb59:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lkb59
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From                      Message
  ----     ------                 ----               ----                      -------
  Normal   Scheduled              5m                 default-scheduler         Successfully assigned jx-staging-golang-http-7c8f549bb6-h5kmn to 129.146.134.132
  Normal   SuccessfulMountVolume  5m                 kubelet, 111.111.111.80  MountVolume.SetUp succeeded for volume "default-token-lkb59"
  Normal   Pulling                3m (x4 over 5m)    kubelet, 111.111.111.80  pulling image "draft:0.0.2"
  Warning  Failed                 3m (x4 over 5m)    kubelet, 111.111.111.80  Failed to pull image "draft:0.0.2": rpc error: code = Unknown desc = Error response from daemon: pull access denied for draft, repository does not exist or may require 'docker login'
  Warning  Failed                 3m (x4 over 5m)    kubelet,111.111.111.80  Error: ErrImagePull
  Warning  Failed                 3m (x6 over 5m)    kubelet, 111.111.111.80  Error: ImagePullBackOff
  Normal   BackOff                10s (x21 over 5m)  kubelet, 111.111.111.80  Back-off pulling image "draft:0.0.2"
`

Could you please give some advice here? I did successful deployment even last Friday.  Thanks a lot.

Btw, I am using the private docker repo and can see the app image successfully pushed into the repo.

**Comment by liuxiaopiao** [comment]
And the pipeline job log is as follows:
`jx promote -b --all-auto --timeout 1h --version $(cat ../../VERSION)
— Shell Script
3m 6s
[golang-http] Running shell script

++ cat ../../VERSION

+ jx promote -b --all-auto --timeout 1h --version 0.0.2

Promoting app golang-http version 0.0.2 to namespace jx-staging

Using pipeline: liuxiaopiao/golang-http/master build: #3

Cloning into '/home/jenkins/.jx/environments/liuxiaopiao/environment-apemercury-staging'...

Found remote branch names master, HEAD -> origin/master, master

Switched to branch 'promote-golang-http-0.0.2'

[promote-golang-http-0.0.2 5b29615] Promote golang-http to version 0.0.2

 1 file changed, 8 insertions(+), 5 deletions(-)

To https://github.com/liuxiaopiao/environment-apemercury-staging.git

 * [new branch]      HEAD -> promote-golang-http-0.0.2

Created Pull Request: https://github.com/liuxiaopiao/environment-apemercury-staging/pull/1



Using pipeline: liuxiaopiao/golang-http/master build: #3

WARNING: Failed to query the Pull Request last commit status for https://github.com/liuxiaopiao/environment-apemercury-staging/pull/1 ref 5b29615948e7ea6f67b1556d03da1c28a5a005eb Could not find a status for repository liuxiaopiao/environment-apemercury-staging with ref 5b29615948e7ea6f67b1556d03da1c28a5a005eb

Pull Request https://github.com/liuxiaopiao/environment-apemercury-staging/pull/1 is merged at sha 115d5b7d7ff68aca95669bcffa0fef49f572f5e1

Merge commit has not yet any statuses on repo liuxiaopiao/environment-apemercury-staging merge sha 115d5b7d7ff68aca95669bcffa0fef49f572f5e1

merge status: pending for URL https://api.github.com/repos/liuxiaopiao/environment-apemercury-staging/statuses/115d5b7d7ff68aca95669bcffa0fef49f572f5e1 with target: http://jenkins.jx.111.111.111.80.nip.io/job/liuxiaopiao/job/environment-apemercury-staging/job/master/2/display/redirect description: This commit is being built

EXITCODE   0merge status: success for URL https://api.github.com/repos/liuxiaopiao/environment-apemercury-staging/statuses/115d5b7d7ff68aca95669bcffa0fef49f572f5e1 with target: http://jenkins.jx.111.111.111.80.nip.io/job/liuxiaopiao/job/environment-apemercury-staging/job/master/2/display/redirect description: This commit looks good

Merge status checks all passed so the promotion worked!

Application is available at: http://golang-http.jx-staging.111.111.111.80.nip.io`

**Comment by liuxiaopiao** [comment]
And all my previous projects which were working before are having similar issue:
 Failed to pull image "draft:0.0.8": rpc error: code = Unknown desc = Error response from daemon: pull access denied for draft, repository does not exist or may require 'docker login'

**Comment by jstrachan** [comment]
I don't grok where the `draft` name is coming from - what is the value of `DOCKER_REGISTRY`? Do you have any of your quickstarts on github so we can have a look at the source?

**Comment by liuxiaopiao** [comment]
Close the issue and we need to update the image name in values.yaml.  
And also need to follow this https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret to create imagePullSecret.

Thanks a lot for the help in channel
