### ISSUE TITLE
Android quickstart project resulted in a pipeline failure

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#1138]
This is the default pipeline that was generated by Jenkins X with no user intervention. The build failed with an exception.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by rawlingsj** [comment]
What version are you on?

`jx version`

The android sdk was added last week https://github.com/jenkins-x/builder-gradle/commit/b86c18d3a832bb6fd292818c4349b7da2c2b9b58#diff-3254677a7917c6c01f55212f86c57fbf 

Perhaps try `jx upgrade platform`

FWIW there's actually still some work needed for the android docker build to work so once you get past this issue it's likely you'll hit that.  I'll raise an issue so you can track the development of that.

**Comment by rawlingsj** [comment]
related issue https://github.com/jenkins-x/jx/issues/1139

**Comment by junibutler** [comment]
This is the version that I have right now - pretty recent I would say. 

I can upgrade of course - should I?

Junis-MacBook-Pro:workspace juni$ jx version
NAME               VERSION
jx                 1.3.20
jenkins x platform 0.0.1436
kubernetes cluster v1.8.10-gke.0
kubectl            v1.10.1
helm client        v2.9.0+gf6025bb
helm server        v2.9.0+gf6025bb
git                git version 2.15.1 (Apple Git-101)

A new jx version is available: 1.3.28
? Would you like to upgrade to the new jx version? [? for help] (Y/n)

**Comment by junibutler** [comment]
Also, I can wait for a more stable version. I tried this more out of curiosity than anything else. Please let me know once we have a stable version.

**Comment by junibutler** [comment]
Yes absolutely, I am watching that one, thank you James. And also, I upgraded my jx platform right now - so all good.

**Comment by rajdavies** [comment]
moved to #1139
