### ISSUE TITLE
'jx create cluster minikube' should have an option for the switch.

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#115]
On windows using hyper-v you likely already have some switches.

picking an arbitrary one is generally doomed to failure so the minukube option to specify the switch should be exposed.

workaround is to create the `minikube` with the arguments you need and then run `jx install`

**Comment by rawlingsj** [comment]
OK thanks, yeah we'll need to allow the optional flag `--hyperv-virtual-switch` to be passed through to minikube start https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_cluster_minikube.go#L206
