### ISSUE TITLE
Spring Boot maven wrapper fails in devpod

### ISSUE THREAD

**Issue by sdoxsee** [jenkins-x/jx#1150]
When using `jx create spring`, I see that the devpod comes with `mvn` pre-installed. I prefer using the `./mvnw` approach as it makes the version of maven git-controlled (not to say that the `mvn` version in the pod isn't...but it's currently a mystery to me how it is chosen). In any case, although it works when i run `mvn install`, when i use the maven wrapper (`./mvnw install`) there are some permission issues and it fails (trying to write it to /root). Don't have the error available off-hand but could provide that if it's helpful.

**Comment by ascheman** [comment]
`mvnw` is now part of the Spring project setup. However, it fails in devpod since the home is set to `/root` which is mounted readonly (and/or has some symlinks to a writeable/overlay FS like `~/.m2/settings.xml` and the `localRepository`):

```
./mvnw clean
/home/jenkins/wrk/jenkins/jenkinsx/jx-demo-180811-1200
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.3/apache-maven-3.5.3-bin.zip

Exception in thread "main" java.io.FileNotFoundException: /root/.m2/wrapper/dists/apache-maven-3.5.3-bin/2c22a6s60afpuloj4v181qvild/apache-maven-3.5.3-bin.zip.part (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
```
