### ISSUE TITLE
jx setup fails (in initial pipelines) if helm client is old: should manage/warn about helm client version

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#1172]
At least with helm2, you can run into problems if the client (eg on macos) is older than what jenkinsX expects on the server:

```
1 chart(s) linted, no failures
Applying helm chart at . as release name jx-staging to namespace jx-staging
[debug] Created tunnel using local port: '36566'

[debug] SERVER: "127.0.0.1:36566"

Error: UPGRADE FAILED: incompatible versions client[v2.9.1] server[v2.8.2]
Error: Command failed  helm upgrade jx-staging . --install --namespace jx-staging --debug
error: exit status 1
```

Generally the user will have to update helm locally. I am not sure if jx installed helm, or if user is required to install it via brew, but at least while tiller is used, probably should warn/error if helm version is too old? 

OR jx needs to get its own version of heml binary into ~/.jx/bin and use that over the system one so it works?

**Comment by rawlingsj** [comment]
I think we can close this now as we have validation to ensure client and server helm versions match.  We also have an option to avoid installing tiller until helm 3 arrives.
```
jx install --no-tiller
```
