### ISSUE TITLE
allow post preview jobs to be configured on a team

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1176]
e.g. to enable things like OWasp which is then automatically triggered on a preview chart.

so folks can do something like this to enable OWasp on previews in a Team:
```
jx create post preview job --name owasp --image owasp/zap2docker-stable:latest -c "zap-baseline.py" -c "-t" -c "\$(JX_PREVIEW_URL)" 
```

cc @michaelneale

**Comment by jstrachan** [comment]
adding commands `jx get post preview job` and `jx delete post preview job` too btw

**Comment by michaelneale** [comment]
@jstrachan how are the results reported?

**Comment by michaelneale** [comment]
@jstrachan ok finally getting a chance to try this out. So how does this apply on a job by job basis? or does it apply across all pipelines once added?

**Comment by jstrachan** [comment]
so each Job thats defined as a post-preview job at a Team level is run in turn and the pipeline waits for it to complete/fail

**Comment by michaelneale** [comment]
enables https://github.com/jenkins-x/jx/issues/1176 in theory.. still not able to make it work (command line hassles)

**Comment by michaelneale** [comment]
@jstrachan I wasn't able to get this to work, mostly as I am looking for a specific exit code of the process to deem it a failure. 

ie what I want to do is: 

```
docker run -t owasp/zap2docker-stable zap-baseline.py -t THE_URL_HERE || if [ $? -eq 1 ]; then exit 1; else exit 0; fi
```

however I can't do this with the post preview. I have tried many permutations, such as: 

```
jx create post preview job --name owasp --image owasp/zap2docker-stable:latest -c "zap-baseline.py" -c "-t" -c "\$(JX_PREVIEW_URL)" -c " || if [ \$? -eq 1 ]; then exit 1; else exit 0; fi"
```

however it is failing for various reasons. 

Any ideas? One option is to allow the post preview job to take a param saying the expected return type or something? or is there some other way I can script it? 

I also tried: 

```
jx create post preview job --name owasp --image owasp/zap2docker-stable:latest -c "zap-baseline.py \$(JX_PREVIEW_URL) || if [ \$? -eq 1 ]; then exit 1; else exit 0; fi" 
``` to no avail either.
