### ISSUE TITLE
Install fails if you don't choose GitHub 

### ISSUE THREAD

**Issue by huang-jy** [jenkins-x/jx#1179]
How to replicate

1. Delete `~/.jx` 
2. `jx create git server [type] [host]` (e.g. `jx create git server GitLab http://www.gitlab.com`)
3. `jx install` and select the other server your created (GitLab in the above case)

When it gets to the access/api token, the url will fail. If you manually get the token from the respecitve area on your git server, it'll continue.

When it gets to generating the initial staging/production environments, it will fail with this message:

`error: Server https://github.com has no user auths defined!`

Which is true since we haven't given the auth details. This should be fixed. Not everyone who wants to use JX will have a GitHub account, or will want to use their own internal git server (self-hosted BitBucket, self-hosted GitLab, etc.)

**Comment by allen-servedio** [comment]
I see the same behavior for GitHub Enterprise: https://github.com/jenkins-x/jx/issues/525#issuecomment-402286293

**Comment by ccojocar** [comment]
@huang-jy I am going to close this issue, because the install has improved ever since. Please feel free to open another issue if you are still see the problem occurring. Thanks
