### ISSUE TITLE
could jx import from a fork detect the github org and repo?

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jx#1194]
We have projects that run in JX that we'd like people to be able to fork and import. But our projects contain a Jenkinsfile and skaffold.yaml that contain hard-coded values for the github organization and repo (in the Jenkinsfile the `ORG` and `APP_NAME`). These were created by jx at the time we first did `jx import`. So could `jx import` also replace these with the values appropriate to the fork?

I notice the code currently replaces [`REPLACE_ME_APP_NAME` from a template](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L33). But I wonder if it could search for and replace by patterns for this case. So for the Jenkinsfile it would need to find:
```
      ORG               = '*'
      APP_NAME          = '*'
```
And for the skaffold file it would be each of
```
      template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/*:{{.VERSION}}"
        template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/*:{{.DIGEST_HEX}}"
          image.repository: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/*"
```

**Comment by rawlingsj** [comment]
I wonder if instead of folks manually forking and importing these projects you could instead create your own quickstarts and build-packs if they differ from the default Jenkins X ones?

Then your developers can reuse the existing jx tooling to fork / clone and import using `jx create quickstart --organisations foo`?

**Comment by ryandawsonuk** [comment]
We would like to but we're not quite ready to offer a quickstart yet. In the meantime we'd like to be able to tell users to use a fork. 

@MiguelRuizDev took a fork and [tried deleting those files](https://github.com/MiguelRuizDev/example-runtime-bundle/commit/db09e6fb30ffaaf64230dcdc14415079a41caeac) before doing a `jx import` but he got the error:

```
Failed to run draft create in /Users/miguelruiz/projects/example-runtime-bundle due to mkdir /Users/miguelruiz/projects/example-runtime-bundle/charts/maven: file exists
error: error renaming /Users/miguelruiz/projects/example-runtime-bundle/charts/example-runtime-bundle to /Users/miguelruiz/projects/example-runtime-bundle/charts/example-runtime-bundle, failed to copy source dir /Users/miguelruiz/projects/example-runtime-bundle/charts/example-runtime-bundle to /Users/miguelruiz/projects/example-runtime-bundle/charts/example-runtime-bundle: destination already exists
```
Seems from "destination already exists"  that it doesn't like the charts directory being present. We have customisations we need to apply to the helm charts and would rather not tell users to do that.

Could this be changed so that it doesn't error if the charts directory is present? Then it would be easier for us to ask users to fork a repo and do a `jx import`.
