### ISSUE TITLE
jx install problem on miniube, git provider = bitbucket.

### ISSUE THREAD

**Issue by mrpity** [jenkins-x/jx#1199]
After creation of staging, production environment is not created. Could you help me? Maybe i doing something wrong...

Logs:

Created environment staging
Updated the Jenkins ConfigMap jenkins
Safe Restarted Jenkins server
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Created Jenkins Project: http://jenkins.jx.192.168.99.100.nip.io/job/dkhodakivsky/job/environment-warriortree-staging/

Note that your first pipeline may take a few minutes to start while the necessary docker images get downloaded!

error: Status: 400 Bad Request, Body: {"type": "error", "error": {"fields": {"url": ["Invalid URL"]}, "message": "Bad request"}}

**Comment by mrpity** [comment]
jx version
> NAME               VERSION
> jx                 1.3.35
> jenkins x platform 0.0.1655
> kubernetes cluster v1.10.0
> kubectl            v1.10.5
> helm client        v2.9.1+g20adb27
> helm server        v2.9.1+g20adb27
> git                git version 2.1.4

**Comment by mrpity** [comment]
When I do jx import i get the same error:

> jx import --pack='go'
> ? Do you wish to use dkhodakivsky as the git user name: Yes
> trying to use draft pack: go
> selected pack: /home/dkhodakivsky/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/go
> existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step
> Created Jenkins Project: http://jenkins.jx.k8s.whirl.sg/job/dkhodakivsky/job/jx_test_repo/
> 
> Watch pipeline activity via:    jx get activity -f jx_test_repo -w
> Browse the pipeline log via:    jx get build logs dkhodakivsky/jx_test_repo/master
> Open the Jenkins console via    jx console
> You can list the pipelines via: jx get pipelines
> When the pipeline is complete:  jx get applications
> 
> For more help on available commands see: https://jenkins-x.io/developing/browsing/
> 
> Note that your first pipeline may take a few minutes to start while the necessary docker images get downloaded!
> 
> error: Status: 400 Bad Request, Body: {"type": "error", "error": {"fields": {"url": ["Invalid URL"]}, "message": "Bad request"}}

What does this ERROR mean?

**Comment by mrpity** [comment]
Jenkins Root URL is n't set correctly or Bitbucket doesn't have access to Jenkins host ?

**Comment by mrpity** [comment]
The problem was with jenkins access from outside(from bitbucket).

**Comment by wbrefvem** [comment]
@mrpity Are you still having this issue? minikube won't work with Bitbucket unless you're also running it in the same local environment.

**Comment by ccojocar** [comment]
Closing this issue since the use doesn't seem to follow up with additional information.
