### ISSUE TITLE
jx import results in "image [changeme] is not used by the deployment" after GitHub id renamed

### ISSUE THREAD

**Issue by miguelruizdev** [jenkins-x/jx#1209]
I changed my GitHub id because I had uppercase in my id and that was causing an error - that error actually got resolved but the renaming has caused a different issue. Now when I import my app the pipeline errors with:

Build complete in 9.20702028s
Starting deploy...
time="2018-07-05T08:44:07Z" level=warning msg="image [changeme] is not used by the deployment"
error: no objects passed to apply
time="2018-07-05T08:44:08Z" level=fatal msg="deploy step: deploying manifests: exit status 1"

Actually the same error as https://github.com/jenkins-x/jx/issues/1193 but I think for a different reason.

My Jenkins still references the old uppercase id:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/32025234/42312943-6f2ab274-8039-11e8-8a46-66fda11b06e9.png">

I'm guessing I have to recreate my cluster?

**Comment by ccojocar** [comment]
@miguelruizdev Please could you provided the sequence of steps you follow? Did you delete the old project and then reimport it with the new name?

**Comment by miguelruizdev** [comment]
As far as I can remember, I recreated the whole cluster and the problem was fixed

**Comment by ccojocar** [comment]
Thanks! Closing this issue.
