### ISSUE TITLE
Unable to sync files within the devpod with "jx sync"

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#1216]
I am not sure how I can run "./watch.sh" without first syncing? Or, do you mean a different watch?

Tried to follow this: https://www.cloudbees.com/blog/don%E2%80%99t-install-development-tools, but could not get this to work.

Can someone help?

[root@juni-nodejs-ync code]# pwd
/code
[root@juni-nodejs-ync code]# ls -l
total 0
[root@juni-nodejs-ync code]# jx sync
ksync is already available on your PATH at /root/.jx/bin/ksync
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-07-05T17:25:57Z" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
FATA[0000] missing pre-requisites, run init to fix      
WARNING: Failed on ksync watch: exit status 1
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-07-05T17:25:58Z" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
FATA[0000] missing pre-requisites, run init to fix      
WARNING: Failed on ksync watch: exit status 1
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-07-05T17:26:00Z" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
FATA[0000] missing pre-requisites, run init to fix      
WARNING: Failed on ksync watch: exit status 1
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-07-05T17:26:01Z" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
FATA[0000] missing pre-requisites, run init to fix      
^C

**Comment by junibutler** [comment]
@rajdavies do you have any update on this issue? Happens on the latest version as well.

**Comment by jasgeo75** [comment]
I had the same problem.  Running the command below reported missing binaries.  A little vague, but still a clue...

`~/.jx/bin/ksync doctor `


The fix was to run 

`~/.jx/bin/ksync init.  `

**Comment by ccojocar** [comment]
This seems to be an issue related to `ksync` not `jx`.
