### ISSUE TITLE
how to view apps / versions / environment versions etc

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#122]
right now we have a way to view the pipelines in jenkins:
```
jx get pipeline
```
and a way to view the versions + pods of each app in each environment:
```
jx get version
```
but no way to just list the apps folks are working on (maybe with their latest version + date?).

Also there's no way to view  all the versions of an app.

So maybe `jx get app` should show a list of apps and their version?

Maybe then `jx get version foo` would list the versions of app `foo`?

**Comment by michaelneale** [comment]
perhaps this could be solved with aliases alone without changing api/model just yet. 

I was looing for some kind of "list" command, or "apps" - but they are kind of just aliases for things that already exist I think

**Comment by michaelneale** [comment]
hrm maybe it does make sense to call out apps. As if there are additional pipelines used via "gitops" for promotions, it may be ambiguous what pipeline one is referring to, when they really mean the running app

**Comment by michaelneale** [comment]
@jstrachan I think there at least needs to be a `jx apps` command. everytime I play, I find I am CONSTANTLY reaching for it. If jenkins-x is all about the apps - it seems crazy to not have one, even if it is effectively an alias. It is how I explore a system, just another way to view the information of what apps exist with what pipelines, what state they are in (maybe something is not ready and you thought it should be) and environment stuff. This could also include detailed info about instances and health (that any UI will need). 

its kind of cross cutting with an environment/stage centric view of things.

**Comment by jstrachan** [comment]
we have ‘jx get apps’ now - though missing a way to delete an app from an Environment or remove its pipeline

**Comment by michaelneale** [comment]
@jstrachan cool - I didn't see where in the code apps is (build from master, but also didnt' see any open PRs) - is there some sample of using it?
