### ISSUE TITLE
jx 1.2.136  in install k8s

### ISSUE THREAD

**Issue by guleng** [jenkins-x/jx#1220]
[root@hp-001 ~]# jx install --provider=kubernetes --on-premise 
Git configured for user: guleng and email guleng
Tiller Deployment is running in namespace kube-system
Already up-to-date.
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: https://192.168.10.1
The Ingress address https://192.168.10.1 is not an IP address. We recommend we try resolve it to a public IP address and use that for the domain to access services externally.
? Would you like wait and resolve this address to an IP address and use it for the domain? No

WARNING: Still not managed to resolve address https://192.168.10.1 into an IP address. Please try figure out the domain by hand
You can now configure a wildcard DNS pointing to the new loadbalancer address https://192.168.10.1
? Domain https://192.168.10.1
nginx ingress controller installed and configured
Lets set up a git username and API token to be able to perform CI/CD

? Do you wish to use guleng as the GitHub username for CI/CD pipelines: Yes
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
....
....
==> v1/PersistentVolumeClaim
NAME                       STATUS   VOLUME  CAPACITY  ACCESS MODES  STORAGECLASS  AGE
jenkins-x-chartmuseum      Pending  1m
jenkins-x-docker-registry  Pending  1m
jenkins                    Pending  1m
jenkins-x-mongodb          Pending  1m
jenkins-x-nexus            Pending  1m

==> v1/ClusterRoleBinding
NAME            AGE
gc-previews-jx  1m

waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx

        ********************************************************

             NOTE: Your admin password is: shriekerash

        ********************************************************

        Getting Jenkins API Token
retrying after error:unable to find external URL annotation on service jenkins
retrying after error:unable to find external URL annotation on service jenkins
error: after 3 attempts, last error: unable to find external URL annotation on service jenkins

Ask for help

**Comment by livelyRyan** [comment]
Is your jenkins pod normal?

**Comment by guleng** [comment]
@livelyRyan  
It's normal .    They are not in a namespace . OK?

**Comment by jstrachan** [comment]
whats the output of these commands:
```
jx version
kubectl get pvc
kubectl get pod
```

**Comment by locorocoo** [comment]
I'm having similar issues when create cluster in eks:

```
$ jx version                                                         
NAME               VERSION
jx                 1.3.90
jenkins x platform 0.0.1827
kubernetes cluster v1.10.3
kubectl            v1.11.0
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.16.3
```

```
$ k get pvc                                                                                [ruby-2.3.3p222]
NAME                        STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jenkins                     Bound     pvc-1c37aa32-8799-11e8-9b3d-065afefffb42   30Gi       RWO            gp2            4m
jenkins-x-chartmuseum       Bound     pvc-1c35e8be-8799-11e8-9b3d-065afefffb42   8Gi        RWO            gp2            4m
jenkins-x-docker-registry   Bound     pvc-1c36b4df-8799-11e8-9b3d-065afefffb42   100Gi      RWO            gp2            4m
jenkins-x-mongodb           Bound     pvc-1c386bc8-8799-11e8-9b3d-065afefffb42   8Gi        RWO            gp2            4m
jenkins-x-nexus             Bound     pvc-1c39ede2-8799-11e8-9b3d-065afefffb42   8Gi        RWO            gp2            4m
```

```
$ k get pod                                                                                [ruby-2.3.3p222]
NAME                                             READY     STATUS    RESTARTS   AGE
jenkins-9f7f96bfb-s6zvs                          1/1       Running   0          4m
jenkins-x-chartmuseum-5bfc74798d-t7pmm           1/1       Running   0          4m
jenkins-x-docker-registry-f5f9b7bc9-pl9ns        1/1       Running   0          4m
jenkins-x-heapster-c6d44bc95-6lrdp               2/2       Running   0          4m
jenkins-x-mongodb-77c6dc684c-4sbvg               1/1       Running   0          4m
jenkins-x-monocular-api-65999df584-h7f6v         1/1       Running   2          4m
jenkins-x-monocular-prerender-64f989797b-h4mbs   1/1       Running   0          4m
jenkins-x-monocular-ui-56ff7bfff7-4wcsr          1/1       Running   0          4m
jenkins-x-nexus-75dd6d4446-kgz2l                 1/1       Running   0          4m
pipelinecontroller-55d65ccc6-2f2xm               1/1       Running   0          4m
```

**Comment by empath** [comment]
I'm guessing it's related to not setting up an ingress when you first started?

I'm having the same problem and i skipped the ingress creation

**Comment by ccojocar** [comment]
@guleng Do you have the ingress controller installed?

What returns the following command?
```
 kubectl get pods -n kube-system --selector=app=nginx-ingress
```

**Comment by ccojocar** [comment]
Closing this because the user haven't followed up with addition information.
