### ISSUE TITLE
Failed to create the folder in jekins: invalid character 'F' looking for beginning of value

### ISSUE THREAD

**Issue by christianmue1980a** [jenkins-x/jx#1231]
### Summary 
During ` jx install --provider=kubernetes --on-premise --verbose` I get the error:

```
Created environment staging
retrying after error:Failed to create the xyz folder in jenkins: invalid character 'F' looking for beginning of value
```

Any ideas? How can I get more information about the background of this error?

What I noticed is that jx cannot get the token for jenkins automatically, i.e. I have to look it up manually
```
unable to automatically find API token with chromedp using URL http://jenkins.jx.....de/me/configure
```

I use traefik as ingress controller and it seems to work fine in my desktop browser (e.g. I can create a new folder in jenkins UI). 

### Jx version

```
NAME               VERSION
jx                 1.3.74
jenkins x platform 0.0.1722
kubernetes cluster v1.10.1
kubectl            v1.10.3
git                git version 2.7.4
```

### Kubernetes cluster provider / Version

1.10.1

### Operating system / Environment
ubuntu

**Comment by jstrachan** [comment]
is there some http proxy going on or are you using some custom ingress controller or something? Looks like the jenkins client cannot talk to jenkins properly via the Jenkins REST API

**Comment by christianmue1980a** [comment]
Hm, yes, we are using Traefik as ingress controller... Is there a way to increase logging to actually see the failing request? Would be helpful for further debugging of traefik.

**Comment by rawlingsj** [comment]
Are there any errors in the Traefik logs?

**Comment by christianmue1980a** [comment]
Will have to reproduce the issue at the weekend and capture the debug logs in traefik. Will come back to you then

**Comment by christianmue1980a** [comment]
I was able to check it right now - no error in the traefik log. I tried to find the failing request and this one seems to be a candidate

```
time="2018-07-11T16:59:40Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.42.2.4:8080\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"de-DE,de;q=0.9,en-US;q=0.8,en-DE;q=0.7,en;q=0.6\"],\"Cookie\":[\"JSESSIONID.7eda27e5=node0eg6woag81f5qrsfg3zcet2q256.node0\"],\"Dnt\":[\"1\"],\"Referer\":[\"https://jenkins.jx.k8s.intern.*******.de/\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"jenkins.jx.k8s.intern.******.de\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.18.4:53209\",\"RequestURI\":\"/loginEntry?from=%2F\",\"TLS\":null}"

```

My guess is based on `\"RequestURI\":\"/loginEntry?from=%2F\"` which fits to the error with `invalid character 'F' looking for beginning of value`

But since already the RequestURI is missing in the debug log, I think the issue is on the CLI side?

**Comment by superbarne** [comment]
hey @christianmue1980a how did you solve this issue?

**Comment by christianmue1980a** [comment]
I did not do any further investigations, left Jenkins-X and switched to Gitlab CI. But I am still interested in a solution because Jenkins-X might come up again here as a topic.

**Comment by rawlingsj** [comment]
We've not tried working with the Traefik ingress controller yet however I think some folks in the community on slack have.  I'll try and find more info.  We have a number of nginx specific annotations for example:

https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L627
https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L640
https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L682

which we'd need to override with custom config https://jenkins-x.io/getting-started/config/

/area ingress
/kind bug
/priority backlog

**Comment by ccojocar** [comment]
@christianmue1980a I am going to close this issue because Traefik is not in the scope of jx for now. Thanks
