### ISSUE TITLE
TLS errors ("default backend - 404", invalid certificate error)

### ISSUE THREAD

**Issue by shaicoleman** [jenkins-x/jx#1232]
### Summary 
The installation doesn't set up HTTPS correctly

### Steps to reproduce the behavior
`jx install --provider=gke --tls-acme=true --http=false`
The installation will return an error on the HTTPS endpoints
```
$ curl https://jenkins.jx.35.189.69.77.nip.io/me/configure
curl: (60) server certificate verification failed.

$ curl -k https://jenkins.jx.35.189.69.77.nip.io/me/configure
default backend - 404
```

### Jx version
1.3.74

### Kubernetes cluster provider / Version
Client Version: v1.10.5
Server Version: v1.9.7-gke.3

### Operating system / Environment
Ubuntu 16.04

### Expected behavior
Should not return 404 on HTTPS URLs, and should not return a certificate error

**Comment by riqbal-rocketlawyer** [comment]
I have come across same issue. I did not pass http=false option so it works on http but on https it gives me 404.

**Comment by ccojocar** [comment]
This should be fixed in the current install command.
