### ISSUE TITLE
how to change default-admin-password

### ISSUE THREAD

**Issue by rhinoceros** [jenkins-x/jx#1237]
### Summary 
I want to change the default password , what can I do?

### Jx version
```
Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Error: unknown command "version --short" for "helm"
Run 'helm --help' for usage.': exit status 1
NAME               VERSION
jx                 1.3.74
jenkins x platform 0.0.1722
kubernetes cluster v1.9.7-gke.3
kubectl            v1.9.7
git                git version 2.11.0
```
### Kubernetes cluster provider / Version
gke
### Operating system / Environment
gke

**Comment by ccojocar** [comment]
Have you tired to run the `jx upgrade platform` with a new admin password in the `adminSecrets.yaml` file from `~/.jx` folder? 

Closing this issue for now, since does not seem to be a bug or an enhancement request.

**Comment by saadgen** [comment]
Use "jx <command> --help" for more information about a given command.
Use "jx options" for a list of global command-line options (applies to all commands).
saad@cloudshell:~/.jx (ambient-hulling-246420)$ jx upgrade platform
Using provider 'gke' from team settings
Already installed platform version 2.0.911. Skipping upgrade process.


this is what i am getting but jenkins X password is not getting updated
