### ISSUE TITLE
Lazy creation of ecr repository failing due to capitalized git user name

### ISSUE THREAD

**Issue by sekmarco** [jenkins-x/jx#1238]
### Summary 

I encounter an error when initializing `jx create spring -d web -d actuator`. Because my GitHub name started with capital letter the default name namespace of the repo generated will start with an capital letter 
https://github.com/jenkins-x/jx/blob/8a0b18118312cb3c318302c819a8bbc74b0affdd/pkg/cloud/amazon/ecr.go#L66

which is not allowed by ECR. 
I could not initialize the demo. I changed the username to the correct format and it worked.

### Steps to reproduce the behavior

Initalized jenkins-x on AWS with an capitalized git user name
and run `jx create spring -d web -d actuator`

### Jx version

1.3.74

### Expected behavior

use small letters for the namespace

### Actual behavior

aborting creation

**Comment by rawlingsj** [comment]
wonder if we just need to 

```
orgName = strings.ToLower(orgName)
appName = strings.ToLower(appName)
```

In the function https://github.com/jenkins-x/jx/blob/8a0b18118312cb3c318302c819a8bbc74b0affdd/pkg/cloud/amazon/ecr.go#L58

**Comment by ccojocar** [comment]
@rawlingsj I think, they need to be lower case also when the docker image is built and pushed to registry.
