### ISSUE TITLE
document steps for installing in a air gap environment

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#1241]
We have a few external dependencies, off the top of my head 
- upstream stable and the Jenkins X helm chart repos 
- git repos
     1.  https://github.com/jenkins-x/jenkins-x-platform
     2. https://github.com/jenkins-x/draft-packs
     3. https://github.com/jenkins-x/default-organisation
     4. https://github.com/jenkins-x/default-environment-charts
     5. https://github.com/jenkins-x/cloud-environments
- dockerhub for all docker images used by Jenkins X

Guess we can start pulling a list of what's needed then we can add some docs on how to install Jenkins X in an air gapped environment

**Comment by keskad** [comment]
Hi, was this completed? :slightly_smiling_face:
