### ISSUE TITLE
jx step helm release failing.

### ISSUE THREAD

**Issue by paolocarta** [jenkins-x/jx#1248]
### Summary 
jx step helm release failing.
![screen shot 2018-07-10 at 1 52 12 pm](https://user-images.githubusercontent.com/4989554/42508447-d9387c88-8448-11e8-8a1e-1747369a143a.png)

### Steps to reproduce the behavior
Import a project or create a new one. The build breaks at jx step helm release.
### Jx version
JX: 1.3.76
Platform: 0.0.1764
### Kubernetes cluster provider / Version
GKE - Version 1.10.5-gke.0
### Operating system / Environment
All build agents.
### Expected behavior
Command completes successfully.
### Actual behavior
Command completes with error.

**Comment by i0n** [comment]
Hey there. I'm seeing this too, I'm looking into what's happened.

**Comment by garethjevans** [comment]
this should be resolved now - it was fixed in #1261
