### ISSUE TITLE
Creating cluster on Google Cloud platform fails

### ISSUE THREAD

**Issue by kevindmoore** [jenkins-x/jx#1255]
### Summary 
Trying to create the cluster on Google Cloud values with an exit status of 1.
### Steps to reproduce the behavior
1. Create a new Google Cloud Account
2. Create a new project named "Jenkins"
3. Install the Cloud Shell
4. Follow the instructions to create the cluster
There are several options that are not mentioned in the documentation that I wasn't sure what to choose.
### Kubernetes cluster provider / Version
Google Cloud/Latest
### Operating system / Environment
Cloud
### Actual behavior
Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to jenkins-209820.
Use “gcloud config set project” to change to a different project.
kevin@cloudshell:~ (jenkins-209820)$ curl -L https://github.com/jenkins-x/jx/releases/download/v1.3.79/jx-linux-amd64.tar.gz | tar xzv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   612    0   612    0     0    816      0 --:--:-- --:--:-- --:--:--   817
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0jx
100 17.4M  100 17.4M    0     0  3788k      0  0:00:04  0:00:04 --:--:-- 4538k
kevin@cloudshell:~ (jenkins-209820)$ sudo mv jx /usr/local/bin
kevin@cloudshell:~ (jenkins-209820)$ jx create cluster gke --skip-login
helm not found
? Missing required dependencies, deselect to avoid auto installing: helm
Downloading https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz to /home/kevin/.jx/bin/helm.tgz...
Downloaded /home/kevin/.jx/bin/helm.tgz
error: error installing helm: failed to run '/home/kevin/.jx/bin/helm plugin install https://github.com/futuresimple/helm-secrets' command in directory '', output: 'Error: plugin home "$HELM_HOME/plugins" does not exist
': exit status 1
kevin@cloudshell:~ (jenkins-209820)$ jx create cluster gke --skip-login
? Google Cloud Project: jenkins-209820
Updated property [core/project].
Lets ensure we have container and compute enabled on your project via: gcloud services enable container compute
Waiting for async operation operations/tmo-acf.67e08fd5-8099-40e0-adbd-086b3b5f9528 to complete...
Operation finished successfully. The following command can describe the Operation details:
 gcloud services operations describe operations/tmo-acf.67e08fd5-8099-40e0-adbd-086b3b5f9528
Downloaded /home/kevin/.jx/bin/helm.tgz
Waiting for async operation operations/tmo-acf.a39e89f0-30ea-4695-8ff4-d7d32a0b0007 to complete...
Operation finished successfully. The following command can describe the Operation details:
 gcloud services operations describe operations/tmo-acf.a39e89f0-30ea-4695-8ff4-d7d32a0b0007
No cluster name provided so using a generated one: foxsprinkle
? Google Cloud Zone: us-west1-a
? Google Cloud Machine Type: n1-standard-4
? Minimum number of Nodes 3
? Maximum number of Nodes 5
Creating cluster...
Error: Command failed  gcloud container clusters create foxsprinkle --zone us-west1-a --num-nodes 3 --machine-type n1-standard-4 --enable-autoscaling --min-nodes 3 --max-nodes 5 --labels=created-by=kevin
error creating cluster exit status 1
error: exit status 1

**Comment by jstrachan** [comment]
could be related to https://github.com/jenkins-x/jx/issues/1236 - as in `helm init` needs to be done earlier by `jx` before any other related helm stuff

**Comment by sundeer** [comment]
similar but not sure. 

mac os
helm client v2.9.1
jx v1.3.88


```
kubernetes - feature/gcp_kubernetes! ❯ jx create cluster gke --verbose
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A...

? Google Cloud Project: friedchicken-dev-96f4a2
Updated property [core/project].
Lets ensure we have container and compute enabled on your project via: gcloud services enable container compute
Waiting for async operation operations/tmo-acf.d3f2fa6a-1197-49f1-81eb-ff2a89aae92d to complete...
Operation finished successfully. The following command can describe the Operation details:
 gcloud services operations describe operations/tmo-acf.d3f2fa6a-1197-49f1-81eb-ff2a89aae92d
Waiting for async operation operations/tmo-acf.21469cd2-2a6a-4775-b49f-2e4ffdc6fd32 to complete...
Operation finished successfully. The following command can describe the Operation details:
 gcloud services operations describe operations/tmo-acf.21469cd2-2a6a-4775-b49f-2e4ffdc6fd32
No cluster name provided so using a generated one: houndfoam
? Google Cloud Zone: us-central1-f
? Google Cloud Machine Type: n1-standard-2
? Minimum number of Nodes 3
? Maximum number of Nodes 5
Creating cluster...
WARNING: Currently node auto repairs are disabled by default. In the future this will change and they will be enabled by default. Use `--[no-]enable-autorepair` flag  to suppress this warning.
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Starting in Kubernetes v1.10, new clusters will no longer get compute-rw and storage-ro scopes added to what is specified in --scopes (though the latter will remain included in the default --scopes). To use these scopes, add them explicitly to --scopes. To use the new behavior, set container/new_scopes_behavior property (gcloud config set container/new_scopes_behavior true).
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=project "friedchicken-dev-96f4a2" has no network named "default".
Error: Command failed  gcloud container clusters create houndfoam --zone us-central1-f --num-nodes 3 --machine-type n1-standard-2 --enable-autoscaling --min-nodes 3 --max-nodes 5 --labels=created-by=rs
error creating cluster exit status 1
error: exit status 1
```
The account I authenticated with during the failed install is part of a group that has ```owner``` role for the project. I used a terraform service account to create the project inself.

I then created a new project in the gui with that same account and tried again. After authenticating  as before and selecting the new project, jx installed without errors.

I'm new to gcp iam so I not sure why it wouldn't work the first time but at least in my case it seems like it was a permission issue.

**Comment by jstrachan** [comment]
@sundeerlooks like you need to create a network called default. Maybe we can get jx to query the networks

**Comment by sundeer** [comment]
Not sure how I missed that, having been written in black and white and me having eyes and all. :flushed:
