### ISSUE TITLE
https://chartmuseum.build.cd.jenkins-x.io/   404

### ISSUE THREAD

**Issue by rhinoceros** [jenkins-x/jx#1257]
### Summary 
https://chartmuseum.build.cd.jenkins-x.io/   404
### Actual behavior
![image](https://user-images.githubusercontent.com/512834/42556058-ed810244-851c-11e8-95a6-6a1f7d1fdc75.png)

**Comment by rawlingsj** [comment]
This is working as expected.  The two URLs that we use are:

https://chartmuseum.build.cd.jenkins-x.io/health
https://chartmuseum.build.cd.jenkins-x.io/index.yaml
