### ISSUE TITLE
should we add a new diagnostic command? e.g. `jx diagnostic`

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1258]
it seems when folks have issues we tend to ask them to run a few different commands like:
```
jx version
kubectl get pvc
kubectl get pod
```

I wonder if we should have a simple single command we can generate a nice output of, say, those 3 commands to start with? Then over time we can improve the output to add more useful information over time?

**Comment by jstrachan** [comment]
I guess another option is to add a verbose version of `jx status` maybe?

**Comment by tdcox** [comment]
I was thinking of adding a helm diagnostic so perhaps make this an extendable command hierarchy?

**Comment by rawlingsj** [comment]
I like the idea of a diagnostic command that we can add more stuff to as we include more features or learn of common failures.  Even offer things to try, or auto search for existing issues on jx?

**Comment by jstrachan** [comment]
@tdcox @rawlingsj agree to both of those! 

it could also output a link to the FAQ as well - have started curating a list of common issues there https://jenkins-x.io/faq/issues/

**Comment by johnmcollier** [comment]
I can tackle this one. Here's what I'm thinking of having it print:
- `jx status`
- `jx version`
- `kubectl get po`
- `kubectl get pvc`
- `kubectl get svc`
- `helm list`

Anything else I should add as a starter? And if I add a command for Helm (such as `jx diagnostic helm`), what should I add there?

**Comment by johnmcollier** [comment]
I've got a change here that implements it: https://github.com/johnmcollier/jx/commit/6c417c52a2bada2c816b87afe02f83cb11cfed70

I'll clean it up a bit later and open a PR.
