### ISSUE TITLE
jx update cluster aws provides help

### ISSUE THREAD

**Issue by bowlesns** [jenkins-x/jx#1267]
### Summary 
Jx update cluster aws doesn't work

### Steps to reproduce the behavior
run the command: jx update cluster aws

### Jx version
NAME               VERSION
jx                 1.3.85
jenkins x platform 0.0.1785
kubernetes cluster v1.9.6
kubectl            v1.10.2
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.10.1 (Apple Git-78)

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Cluster created on AWS using jx create cluster command

### Operating system / Environment
MacOS
### Expected behavior
Updates cluster
### Actual behavior
Tells me what command to run.

Output:
jx update cluster aws
This command updates an existing kubernetes cluster, it can be used to apply minor changes to a cluster / node pool

Valid kubernetes providers include:

    * aks (Azure Container Service - https://docs.microsoft.com/en-us/azure/aks)
    * aws (Amazon Web Services via kops - https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/readme.adoc)
    * eks (Amazon Web Services Elastic Container Service for Kubernetes - https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
    * gke (Google Container Engine - https://cloud.google.com/kubernetes-engine)
    * oke (Oracle Cloud Infrastructure Container Engine for Kubernetes - https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengoverview.htm)
    * kubernetes for custom installations of Kubernetes
    * minikube (single-node Kubernetes cluster inside a VM on your laptop)
	* minishift (single-node OpenShift cluster inside a VM on your laptop)
	* openshift for installing on 3.9.x or later clusters of OpenShift
    * coming soon:
        eks (Amazon Elastic Container Service - https://aws.amazon.com/eks)

Examples:
  jx update cluster gke
Available Commands:
  update cluster gke Updates an existing kubernetes cluster on GKE: Runs on Google Cloud
Usage:
  jx update cluster [kubernetes provider] [flags] [options]
Use "jx <command> --help" for more information about a given command.
Use "jx update options" for a list of global command-line options (applies to all commands).

**Comment by jstrachan** [comment]
not sure this command is implemented yet am afraid - we should maybe remove it for now
