### ISSUE TITLE
Draft don't use organisation when replacing placeholders

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#1275]
### Summary 

When creating spring application using `jx create spring -d web -d actuator` the git organisation in the files in the repo are incorrect. 

### Steps to reproduce the behavior

1. Run `jx create spring -d web -d actuator`
1. Choose an organisation that isn't my username.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.86
jenkins x platform 0.0.1785
kubernetes cluster v1.10.3
kubectl            v1.11.0
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.16.2
```

### Kubernetes cluster

`jx create cluster eks --environment-git-owner=deniedboarding`

### Expected behavior

Application is deployed correctly

### Actual behavior

Build is failing with
`pushing [xxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/username/demo:0.0.4]: name unknown: The repository with name 'msvticket/demo' does not exist in the registry`

### Additional information

To fix it I did a search and replace of username to organisation in the following files in application repo: charts/demo/Makefile charts/preview/Makefile skaffold.yaml Jenkinsfile

And reading import.go it’s clear that it can’t go any other way: getOrganisation get the organisation from the git url, but the git repo isn’t created yet when it’s called. So the falllback (username) is used instead. But during project creation the organisation is used correctly to create the image repository.

**Comment by msvticket** [comment]
I'm starting to work on a fix for this now.

**Comment by msvticket** [comment]
When I tried now it did work. This was on a kops via terraform created cluster in aws. I think what I made differently was specifying myself as the owner on the question "? git user name:",  not the organisation. So there is something fishy in the behaviour, but I won't look into it further at the moment.

**Comment by pmuir** [comment]
Unfortunately this broke commands like `jx import` and `jx create quickstart`. I've put in #1904 to revert it. @ccojocar tried to fix it in #1987 but that isn't passing the test suite, so I think a revert and redo is the best option

**Comment by msvticket** [comment]
In what way did it break `jx import` and `jx create quickstart`? It was with `jx create quickstart` I tried my fix, but there are many ways to run the commands so some details would be useful.

**Comment by ccojocar** [comment]
I think this is fixed by now.
