### ISSUE TITLE
jx compliance run faild

### ISSUE THREAD

**Issue by vlingfu** [jenkins-x/jx#1293]
### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.90
kubernetes cluster v1.10.1
kubectl            v1.10.1
helm client        v2.9.0+gf6025bb
helm server        v2.9.0+gf6025bb
git                git version 1.8.3.1

### Operating system / Environment
Linux kube-master1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

command jx compliance run faild , 
![image](https://user-images.githubusercontent.com/35830275/42751841-a9e569fc-891e-11e8-96a9-2f58e541aa3e.png)

please help

**Comment by ccojocar** [comment]
@vlingfu The compliance test takes about 60 minutes. You can check the status using:
```
jx compliance status
Compliance tests are still running, it can take up to 60 minutes.
```
As long as, the test are running you cannot retrieve the results. After about 1 hour, you should see in the status message that the tests are completed. 

What does the status return?
