### ISSUE TITLE
"jx create cluster aks" gives an error

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#1299]
### Steps to reproduce the behavior

jx create cluster aks

### Jx version

The output of `jx version` is:

Junis-MacBook-Pro:workspace juni$ jx version
NAME               VERSION
jx                 1.3.88
jenkins x platform 0.0.1436
kubernetes cluster v1.8.10-gke.0
kubectl            v1.10.1
helm client        v2.9.0+gf6025bb
helm server        v2.9.0+gf6025bb
git                git version 2.15.1 (Apple Git-101)

COPY OUTPUT HERE

I tried both eastus and westus.

Junis-MacBook-Pro:workspace juni$ jx create cluster aks
az not found
? Missing required dependencies, deselect to avoid auto installing: az

No resource name provided so using a generated one: ferretvaliantNo cluster name provided so using a generated on? Location eastus
? Virtual Machine Size: Standard_D2s_v3
? Number of Nodes 3
Logging in to Azure interactively...
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all subscriptions you have access to...
[
  {
    "cloudName": "AzureCloud",
    "id": "0ee859ed-0f8b-45c0-b61c-011a254f5736",
    "isDefault": true,
    "name": "Pay-As-You-Go - CloudBees Primary",
    "state": "Enabled",
    "tenantId": "70a3cdd2-f9bb-4cac-884d-4a8b1e7d8f2c",
    "user": {
      "name": "jmukherjee@cloudbees.onmicrosoft.com",
      "type": "user"
    }
  }
]
Error: Command failed  az provider register -n Microsoft.Compute
error creating cluster exit status 1
Junis-MacBook-Pro:workspace juni$ 
Junis-MacBook-Pro:workspace juni$ 
Junis-MacBook-Pro:workspace juni$ jx create cluster aks
No resource name provided so using a generated one: roarsplashNo cluster name provided so using a generated one: ? Location westus
? Virtual Machine Size: Standard_D2s_v3
? Number of Nodes 3
Logging in to Azure interactively...
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all subscriptions you have access to...
[
  {
    "cloudName": "AzureCloud",
    "id": "0ee859ed-0f8b-45c0-b61c-011a254f5736",
    "isDefault": true,
    "name": "Pay-As-You-Go - CloudBees Primary",
    "state": "Enabled",
    "tenantId": "70a3cdd2-f9bb-4cac-884d-4a8b1e7d8f2c",
    "user": {
      "name": "jmukherjee@cloudbees.onmicrosoft.com",
      "type": "user"
    }
  }
]
Error: Command failed  az provider register -n Microsoft.Compute
error creating cluster exit status 1
Junis-MacBook-Pro:workspace juni$ 

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by rajdavies** [comment]
This is because you do not have the authorisation to register with Microsoft.Compute. I would check with your Microsoft account.

**Comment by ilyaa1** [comment]
Just for future reference: I've had the same exact problem - turned out to be the limitation of the Free Tier subscription on Azure. Upgrading to Pay-As-You-Go solved _this_ particular problem 😉 

Enabled file logging for Azure CLI, and found the following:

```
28381 : 2018-07-31 17:09:20,496 : DEBUG : msrest.exceptions : Provisioning of resource(s) for container service slothsavage in resource group myResourceGroup failed. Message: Operation results in exceeding quota limits of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 6. Please read more about quota increase at http://aka.ms/corequotaincrease.. Details: 
28381 : 2018-07-31 17:09:21,177 : ERROR : cli.azure.cli.core.util : Deployment failed. Correlation ID: xxxxxxxx-c4cc-xxxx-804b-0eadxxxxa0f7. Provisioning of resource(s) for container service slothsavage in resource group myResourceGroup failed. Message: Operation results in exceeding quota limits of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 6. Please read more about quota increase at http://aka.ms/corequotaincrease.. Details: 
```
