### ISSUE TITLE
Error adding https://chartmuseum.build.cd.jenkins-x.io repository (Chinese GFW).

### ISSUE THREAD

**Issue by gcontini** [jenkins-x/jx#1306]
### Summary 
I'm having a  problem in jx release caused by the fact that "https://chartmuseum.build.cd.jenkins-x.io" has a strange behavior here in China.
### Steps to reproduce the behavior
install the spring boot tutorial, the "Promote to Environments" stage fails

### Jx version

The output of `jx version` is:

```
jx                 1.3.75
jenkins x platform 0.0.1722
kubernetes cluster v1.10.5
kubectl            v1.11.0
git                git version 2.17.1
```
This is what happens when i connect to the pod and i try to add jenkins-x repo:
```
bash-4.2#  helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: http2: server sent GOAWAY and closed the connection; LastStreamID=1, ErrCode=NO_ERROR, debug=""
```
The site seems reachable:
```
bash-4.2# ping chartmuseum.build.cd.jenkins-x.io
PING chartmuseum.build.cd.jenkins-x.io (35.205.186.189) 56(84) bytes of data.
64 bytes from 189.186.205.35.bc.googleusercontent.com (35.205.186.189): icmp_seq=1 ttl=37 time=425 ms
64 bytes from 189.186.205.35.bc.googleusercontent.com (35.205.186.189): icmp_seq=2 ttl=37 time=415 ms
```
Accessing the repo over http seem to work:
```
bash-4.2#  helm repo add jenkins-x http://chartmuseum.build.cd.jenkins-x.io
"jenkins-x" has been added to your repositories
bash-4.2# helm update
Command "update" is deprecated, use 'helm repo update'

Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "releases" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "jenkins-x" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```
I don't know what to say exactly... the Chinese GFW is completely opaque software, so today i can access via http, tomorrow who knows... I suggest to set up a mirror on another website (Microsoft is usually well accepted here, or aws, or github)

**Comment by beebird** [comment]
As a Chinese, I encountered the same issue,  and here's my workaround:
```sh
container('nodejs') {
   ...
   # add a hosts entry in pipeline steps like this:
   sh 'echo 35.205.186.189 chartmuseum.build.cd.jenkins-x.io >/etc/hosts'
  ...
}
```
Although it works in most cases, sometimes the command ``helm repo add jenkins-x http://chartmuseum.build.cd.jenkins-x.io`` still gets stuck, because helm tries to cache the ``index.yaml`` to ``~/.helm/repository/cache/jenkins-x-index.yaml``, which is a large file(easy to be blocked by GFW) . So another suggestion is to host this ``index.yaml`` in a mirror site and add the repo in pipeline scripts.

Life is so tough

**Comment by beebird** [comment]
Can we move the ``index.yaml`` of ``jenkins-x`` repo to behind a CDN or some other widely accessible and big bandwidth site?

It's toooo slow to download the yaml file and always gets timeout.

**Comment by ccojocar** [comment]
Closing this for now since not related to the jx charts repository availability. An workaround is documented in #1171.
