### ISSUE TITLE
ClusterRole in version "v1" cannot be handled as a ClusterRole

### ISSUE THREAD

**Issue by deedeky** [jenkins-x/jx#1311]
### Summary 
Trying to: 
```
jx install --provider=aks
```

getting:
 
role cluster-admin already exists for the cluster
error: failed to create the cluster admin: 
Command failed 'kubectl create -f C:\Users\DEJAN~1.SUB\AppData\Local\Temp\Fliercopper.yml':
 Error from server (BadRequest): error when creating "C:\\Users\\DEJAN~1.SUB\\AppData\\Local\\Temp\\Fliercopper.yml": 
 ClusterRole in version "v1" cannot be handled as a ClusterRole: 
	no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1" exit status 1

### Steps to reproduce the behavior
jx-windows-amd64.exe install --provider=aks

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.98
kubernetes cluster v1.7.7
kubectl            v1.9.2
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

AKS / Kubernetes cluster, created with az acs create

### Operating system / Environment
Windows x64

### Expected behavior
Installing JenkinsX on top of existing AKS

### Actual behavior
Getting the error

**Comment by rawlingsj** [comment]
It looks like RBAC moved to v1 as of Kubernetes 1.8 "As of 1.8, RBAC mode is stable and backed by the rbac.authorization.k8s.io/v1 API" https://kubernetes.io/docs/reference/access-authn-authz/rbac/ . Are you planning on upgrading from Kubernetes v1.7.7 anytime soon?

**Comment by deedeky** [comment]
unfortunately I can't upgrade since orchestrator-version is supported only in some regions ( not mine :( ) - by default it is 1.7.7 currently when you do az acs create...

--orchestrator-version              
: Feature in preview, only in canadacentral, canadaeast, centralindia, koreasouth, koreacentral, southindia, uksouth, ukwest, westcentralus, westindia, westus2. Use Orchestrator Version to specify the semantic version for your choice of orchestrator.

thanks for the tip! 
will see to go around this somehow, maybe with az aks.. 
you can close the issue

**Comment by rawlingsj** [comment]
Ok sorry about that - thanks for the update and hope you have better luck with `az aks`
