### ISSUE TITLE
jx promotion does nothing?

### ISSUE THREAD

**Issue by MaxCCC** [jenkins-x/jx#1315]
### Summary 
jx promote does nothing? (promote form staging to production)

### Steps to reproduce the behavior
```
cd git-repo
jx import
```

### Jx version
1.3.100

The output of `jx version` is:
```
NAME               VERSION
jx                 1.3.100
jenkins x platform 0.0.1827
kubernetes cluster v1.9.7-gke.3
kubectl            v1.10.4
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GCP using `jx create`

### Operating system / Environment
Default GKE OS for GKE

### Expected behavior
I would expect my application to get promoted to the jx-production ns

### Actual behavior
I see a few logs but nothing happens?
```
jx promote --env production --version 0.0.3 myapp
Promoting app myapp version 0.0.3 to namespace jx-production
pipeline user/myapp/master
Using pipeline: user/myapp/master build: #3
```
After this nothing happens.

**Comment by MaxCCC** [comment]
@rawlingsj There was no PR created. Also my local git repo is matching with the remote repo on GitHub (git status = no differences)

**Comment by rawlingsj** [comment]
Hmm.  I'm not too sure yet but could you try to run the promote command from the root of the cloned repo?

I.e.
```
cd your_project
jx promote --env production --version 0.0.3
```

**Comment by lvthillo** [comment]
@MaxCCC @rawlingsj I seem to have the same issue. 
My repositories are public:
https://github.com/lvthillo/environment-jenkins-x-kubernetes-production
https://github.com/lvthillo/environment-jenkins-x-kubernetes-staging
https://github.com/lvthillo/python-flask-docker

The staging and production pipeline are working. But I had to reinstall helm (newest version) to make it initially work: `helm client        v2.10.0-rc.1+gaa98e7e`

I don't know why it does not want to promote my working app from staging to production?

**Comment by lvthillo** [comment]
unfortunately the `--verbose` flag is not providing any more information. Just the logs @MaxCCC mentioned and it stops immediately

**Comment by lvthillo** [comment]
Can it have to do I'm just working on my master branch without real PR's? (I've just deployed an app to staging, did some commits, (every commit increased the version with 0.0.1). Now I just want to promote that application to my production environment.

I went inside the git repository and tried: `jx promote --env production --version 0.0.3 --timeout 1h`

**Comment by lvthillo** [comment]
For me it works now. I think recreation of my cluster without removing `~/.jx ` caused it. Recreating everything didn't work, than I deleted that directory and recreated everything again and it worked.

**Comment by gcontini** [comment]
I had the same issue. Deleting the files in `~/.jx/environments/<mygitusername>/environment-jx-production[*]` together with deleting and recreating the production environment made it work (it's a bit more conservative that @lvthillo solution).

**Comment by ccojocar** [comment]
This issue seems to be fixed by now.
