### ISSUE TITLE
Can't install using an internal load balancer

### ISSUE THREAD

**Issue by empath** [jenkins-x/jx#1318]
### Summary 
Our office network is connected into our private vpc.  I want to setup jenkins x using an internal rather than an external load balancer.

I can change the annotation on the nginx load balancer service to use an internal load balancer, and it does create, but then I get the following error:
```
Jenkins X deployments ready in namespace jx


	********************************************************

	     NOTE: Your admin password is: hunter2

	********************************************************

	Getting Jenkins API Token
retrying after error:unable to find external URL annotation on service jenkins in namespace jx
retrying after error:unable to find external URL annotation on service jenkins in namespace jx
error: failed to get the Jenkins API token: after 3 attempts, last error: unable to find external URL annotation on service jenkins in namespace jx
```

this is what the jenkins service looks like:

```
1 ❯ kubectl describe service jenkins
Name:         jenkins
Namespace:    jx
Labels:       app=jenkins
              chart=jenkins-0.10.29
              component=jenkins-x-jenkins-master
              heritage=Tiller
              release=jenkins-x
Annotations:  fabric8.io/expose=true
              fabric8.io/ingress.annotations=kubernetes.io/ingress.class: nginx
nginx.ingress.kubernetes.io/proxy-body-size: 500m
Selector:          component=jenkins-x-jenkins-master
Type:              ClusterIP
IP:                172.20.97.249
Port:              http  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.44.0.10:8080
Session Affinity:  None
Events:            <none>
```

### Jx version

The output of `jx version` is:

```
❯ jx version
NAME               VERSION
jx                 1.3.104
jenkins x platform 0.0.1827
kubernetes cluster v1.10.3
kubectl            v1.11.0
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

It's an EKS cluster.

### Expected behavior

Jx installs and runs

### Actual behavior
see above error.

Is it actually possible to use jenkins x in an entirely internal vpc or does it need external endpoints?

**Comment by ijcd** [comment]
Any thoughts or progress on this? 

@empath Where did you make the changes you tried, and what were they?

**Comment by ccojocar** [comment]
@empath Jenkin X needs access to internet in order to downloads charts and some git repositories.  I am going to close this issue. There is also https://github.com/jenkins-x/jx/issues/3081. Thanks

**Comment by romil-punetha** [comment]
@ccojocar An internal load balancer will restrict inbound access to within VPC. It should still be able to access internet for downloading packages.
