### ISSUE TITLE
Does jenkins-x plan to support SVN Service?

### ISSUE THREAD

**Issue by becile** [jenkins-x/jx#1320]
### Summary 
Does jenkins-x plan to support SVN Service?

### Steps to reproduce the behavior
nothing.

### Jx version
The output of `jx version` is:1.3.101

### Kubernetes cluster
What kind of Kubernetes cluster are you using & how did you create it?
On-Premise kubernetes 1.10

### Operating system / Environment
RHEL7.4

### Expected behavior
jenkins-x support SVN.

### Actual behavior
jenkins-x don't support SVN.

**Comment by rawlingsj** [comment]
I'm afraid there are no plans to support SVN we are only focused on Git for now.  We have a couple of reasons documented here https://jenkins-x.io/about/decisions/#git.

**Comment by becile** [comment]
We work with subversion.
Can i pull code repository from SVN Server. code in svn，the environment and application chart in Git?

**Comment by rawlingsj** [comment]
Right now no there's no way.  If someone wanted to contribute support for SVN then we can help point them in the right direction but it may end up being a fair bit of work.

**Comment by becile** [comment]
ok, Thank you
