### ISSUE TITLE
Dev Suggestions

### ISSUE THREAD

**Issue by tremulaes** [jenkins-x/jx#1327]
### Summary 

Not a bug, removing bug sections.

I think it could be helpful for new contributors to add the following to the project:

* Add `CONTRIBUTORS.MD` for clarity on project maintainers (ie, who to tag on issues/PRs). This seems to be the standard for github according to [this doc](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)  
* Add a 'Pull Request' section to the `docs/contributing/hacking.md` that tells how you'd like people to handle new PRs, tagging, labels, etc. Not sure if this has been spelled out yet or not, but I know some projects will respond pretty quickly to PRs without tags (like @rawlingsj did on #1326 ) but others will ignore anything that doesn't tag a specific person/bot.

**Comment by rawlingsj** [comment]
I think those are great ideas and points.  We can add a `CONTRIBUTORS.MD` but might hold off doing the pull request section until next week as a few things are going to change. 

In short we're adopting prow which isn't too far away.  Some info is here https://github.com/istio/istio/wiki/Working-with-Prow
With this we'll get a lot of automation around labels, assigning and adding reviewers so hopefully this will dramatically improve the experience for new contributors very soon!
