### ISSUE TITLE
Generated Jenkins Console URL when creating the cluster is not accessible

### ISSUE THREAD

**Issue by Gogs008** [jenkins-x/jx#1333]
### Summary 
I ran `jx create cluster eks --nodes 6 --cluster-name my-cool-app` and when the CLI produces the URL to the Jenkins console:
`http://jenkins.jx.acaf1452a8d2511e8907d068d1dc5805-1240326808.us-west-2.elb.amazonaws.com/me/configure`
to log in to and fetch the generated API key, the URL generated to the Jenkins Console is unreachable.

However when I go to the ELB portion of that generated URL: `acaf1452a8d2511e8907d068d1dc5805-1240326808.us-west-2.elb.amazonaws.com` I am able to at least get a 404. So I know that the ELB DNS is definitely up and working.

### Steps to reproduce the behavior
run `jx create cluster eks --nodes 6 --cluster-name my-cool-app` . Note that this will default to the `US-West-2` region for AWS as there and `US-East-1` are the only places EKS is "Generally Available" at the moment. For some reason the `jx create cluster eks --nodes 6 --cluster-name my-cool-app` command will fail early on in the script even if you add flags to create the cluster in `US-East-1` (this issue should probably be another ticket issue).

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.101
jenkins x platform 0.0.1878
kubernetes cluster v1.10.3
kubectl            v1.10.3
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.7.4
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it? 
EKS through the `jx` CLI
I ran `jx create cluster eks --nodes 6 --cluster-name my-cool-app`

### Operating system / Environment: 
Ubuntu on the Linux Subsystem on Windows 10

### Expected behavior: 
The Jenkins server URL should be accessible (since after all the ELB url is accessible).

### Actual behavior: 
The Jenkins server URL is not accessble, even though the ELB URL is accessible.

![image](https://user-images.githubusercontent.com/17715904/43040103-4ddedfd2-8d09-11e8-815d-13d641623d76.png)

**Comment by jstrachan** [comment]
BTW we've made some recent changes on `eksctl` to add the right roles + switch to NLB for stable load balancer IP addresses.

I wonder if you could delete the cluster `eksctl delete cluster foo` - maybe remove stuff in the AWS console too if things don't remove themselves properly.

Then try ensuring you've the latest [eksctl release](https://github.com/weaveworks/eksctl/releases) - at least `0.1.0-beta.4` and try `jx upgrade cli` then try again?

**Comment by jstrachan** [comment]
BTW that version of `jx` is very old - make sure you're on something like `1.3.141` or later

**Comment by jstrachan** [comment]
@Gogs008 let us know how you get on - its working great here ;)

**Comment by Gogs008** [comment]
Hi @jstrachan, my apologies for the late reply. Unfortunately I am unable to even get that far anymore as I am encountering another issue https://github.com/jenkins-x/jx/issues/1526#issuecomment-416141807 . :( Thanks.

**Comment by ccojocar** [comment]
Closing this issue which might be fixed by now.
