### ISSUE TITLE
should we use helm local by default if using helm2?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1341]
https://github.com/adamreese/helm-local

so that tiller would run as a local process in the pipeline containers; or as a local daemon process when installing Jenkins X in the first place?

**Comment by jstrachan** [comment]
there's also this blog post: https://rimusz.net/tillerless-helm/

**Comment by rawlingsj** [comment]
Yeah I think it's worthwhile trying.  With Helm 3 seeming a way off it would be good to avoid the client / server incompatible version issue everyone keeps hitting.

**Comment by jstrachan** [comment]
gonna close this, the implementation is being tracked here: #1634
