### ISSUE TITLE
Create gc-activities folder under jx/charts/jx

### ISSUE THREAD

**Issue by angoothachap** [jenkins-x/jx#1342]
### Summary 
- Create folder called gc-activities under jx/charts/jx

- Create files such as:

 1. Chart.yaml
 2. Makefile
 3. requirements.yaml
 4. values.yaml
 
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by rawlingsj** [comment]
Yeah so the idea is that we can have multiple charts under the `jx/charts` directory that refer to the `jx/charts/jx` base chart.  Each of these new ones can then easily be configured and released at the same time.

I.e
```
jx
- charts
   - jx
   - gc-activities
   - gc-previews
   - step-service-link
```
In each we can then have separate charts similar to our previews, each would contain these files, I've added an example of what the gc-activities could look like:
- Chart.yaml
```
apiVersion: v1
description: Helm chart to garbage collect pipeline activities
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/go.png
name: gc-activities
version: 0.1.0-SNAPSHOT
```
- Makefile
- requirements.yaml
```
dependencies:
- name: gc-activities
   repository: file://../jx
```
- values.yaml
copied from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L54-L79


Then the new service link chart should just be able to change 
https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L57-L58
to 
```
  job:
    enabled: true
```
And update the roles required for this step.

**Comment by angoothachap** [comment]
@rawlingsj  Created pull requet for gc-activities.
https://github.com/jenkins-x/jx/pull/1365

Cc: @jstrachan

**Comment by angoothachap** [comment]
#573

**Comment by jstrachan** [comment]
there's now the charts in the values.yaml
https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L60
