### ISSUE TITLE
Incorrect flag documented in `jx get cve` help text

### ISSUE THREAD

**Issue by jvz** [jenkins-x/jx#1343]
### Summary 

The help text for `jx get cve` says you can use a flag, `--env`, to specify the environment, but the only flags that actually seem to work for this are `-e` and `--environment`.

### Steps to reproduce the behavior

    jx get cve --help

This outputs an example with `--env staging`, though if we try that command:

    jx get cve --env staging

We get the output `Error: unknown flag: --env`.

Related, when I run just `jx get cve`, I get the error message `error: no --image-name, --image-id or --env flags set`, though `--env` is the wrong flag again.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.113
jenkins x platform 0.0.1889
kubernetes cluster v1.9.7-gke.3
kubectl            v1.11.1
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.18.0
```

### Kubernetes cluster

GKE, free trial, using `jx create cluster gke`, custom domain.

### Operating system / Environment

Default Linux setup from Jenkins X.

### Expected behavior

Either `--env` should also work as a synonym for `--environment` (as either an exact alias or as a feature to allow shortened unambiguous command line flags), or the docs and examples should be corrected.

### Actual behavior

Incorrect docs or missing alias for `--env` flag.

**Comment by garethjevans** [comment]
Thanks @jvz for the report, there is PR (#1357) for this.
