### ISSUE TITLE
InvalidParameterException: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression

### ISSUE THREAD

**Issue by gregpardo** [jenkins-x/jx#1344]
### Summary 

When running jx import from existing github repository.

Repository name for ec2 is invalid because includes organization name. 
Fails on 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*

For example our repo name that is trying to be created looks like this: Organization/repo-name which fails ec2 check

### Jx version

The output of `jx version` is:

jx                 1.3.111
jenkins x platform 0.0.1881
kubernetes cluster v1.9.8
kubectl            v1.11.1
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.16.2

### Kubernetes cluster

kops

### Operating system / Environment

MacOS

### Expected behavior

EC2 repository should be automatically created with valid name. Perhaps sanitization is required for creating EC2 repository name.

### Actual behavior

EDIT: It looks like its failing due to capital letters

**Comment by NadeemYunus** [comment]
repository name should be all in lowercase, helped thanks
