### ISSUE TITLE
add a `jx create docker auth` command

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1348]
so that we can easily add new auth entries into the `config.json` in the docker secret like these docs:
https://jenkins-x.io/architecture/docker-registry/#update-the-config-json-secret

maybe something like `jx create docker auth -- host my.private.docker.registry --user foo` then if no pwd/auth given on the CLI it could prompt for it to be entered or something? Then it'd edit the config.json to add the necessary json for that host + user + pwd/auth value

**Comment by angoothachap** [comment]
https://github.com/jenkins-x/jx/pull/1553

**Comment by jstrachan** [comment]
see https://jenkins-x.io/commands/jx_create_docker/
