### ISSUE TITLE
How to add mongo in my pod?

### ISSUE THREAD

**Issue by ComplyOnline** [jenkins-x/jx#1354]
### Summary 

I have a node.js service which has a dependency on mongodb. I am new at creating Jenkinsfile and I am not sure where I should add this dependency as my tests require it.

### Steps to reproduce the behavior

* Import an existing node.js service using `jx import`
* I had my own .yaml file to deploy to kubernetes
* How do I add a container entry to make sure mongodb is loaded before tests are executed?

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.117
jenkins x platform 0.0.1881
kubernetes cluster v1.10.5-gke.3
kubectl            v1.9.7
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.1 (Apple Git-101)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
* GKE
* Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

MacOS

**Comment by patrickleet** [comment]
Hey - you would add this as a dependency in the environment chart

**Comment by patrickleet** [comment]
or as a dependency for that chart, depending on how you want to use it

**Comment by ccojocar** [comment]
Closing this since does not seem to be a `jx` related issue.
