### ISSUE TITLE
Cannot pass additional flags to helm through jx step helm

### ISSUE THREAD

**Issue by deyceg** [jenkins-x/jx#1358]
### Summary 

Cannot specify `--tiller-namespace` `--service-account` and `tls` config via `jx step helm apply`

### Jx version

The output of `jx version` is:

jx                 1.3.117
jenkins x platform 0.0.1881
kubernetes cluster v1.9.9
kubectl            v1.9.9
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.9.3 (Apple Git-75)

### Kubernetes cluster

kops/aws/1.9.x

### Operating system / Environment

N/A

### Expected behavior

`jx step helm build [jx step flags] -- [helm args]` should pass `[helm args]` to the underlying client

### Actual behavior

Only things defined in `[jx step flags]` will be passed. This means reverting to using `helm` explicitly

**Comment by jstrachan** [comment]
yeah, we need to add support for those flags!
