### ISSUE TITLE
Sorry, your reply was invalid: GET https://gitlab.com/api/v4/projects/myusername: 401 {message: 401 Unauthorized}

### ISSUE THREAD

**Issue by rherrad** [jenkins-x/jx#1371]
### Summary 
Hello, I get 401 Unauthorized error on jx quickstart creation even if local gitlab server is configured
this is the message returned by jx:

https://gitlab.com/api/v4/projects/$myusername/demo1: 401 {message: 401 Unauthorized} 

### Steps to reproduce the behavior
jx create spring cd  -d web -d actuator -x
### Jx version
1.3.118
The output of `jx version` is:

https://gitlab.com/api/v4/projects/$myusername/demo1: 401 {message: 401 Unauthorized} 

gitAuth.yaml : gitAuth.yaml                                                                                                                        X
servers:
- url: https://git.mycompany.com
  users:
  - username: myusername1
    apitoken: d-JDJDHDKEU87EJEJ
    bearertoken: ""
  name: gitlab
  kind: gitlab
  currentuser: myusrmyusername1e2
defaultusername: myusername1
currentserver: https://git.mycompany.com

### Kubernetes cluster
BareMetal 
What kind of Kubernetes cluster are you using & how did you create it?

### Operating system / Environment
Centos 7
### Expected behavior
Project quickstart
### Actual behavior
https://gitlab.com/api/v4/projects/$myusername/demo1: 401 {message: 401 Unauthorized}

**Comment by jstrachan** [comment]
sounds like a bug with the gitlab support - are you sure your username + API token are correct?

**Comment by rherrad** [comment]
Yes i've verified username and API token.

the question is why jx import go to gitlab.com even if i specify my private gitlab provider with 

`jx create git server ....`

it looks like it's seeking for a hook but i dont understand this behavior.

thnx

**Comment by ccojocar** [comment]
@wbrefvem Is this still an issue? Can we close it? Thanks

**Comment by wbrefvem** [comment]
@ccojocar Let's leave this one open. I don't know for sure, but I suspect this is still an issue. If I can't repro, I'll close it.
