### ISSUE TITLE
CRITICAL: Parallel build of environments fails constituently

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1374]
### Summary 
Environment deployment is consistently failing in case of parallel build of environment with multiple applications. 

### Steps to reproduce the behave
Create more than 20 applications in an environment, and try to build all the applications parallel. They will eventually trigger the environment deployment, which is not waiting for any helm deployment to finish, hence the deployment is getting corrupted or failed.  After a failure helm upgrade always fails with error "resource already exists".

### Jx version
The output of `jx version` is:
```
jx                 1.3.107
jenkins x platform 0.0.1877
kubernetes cluster v1.9.6
kubectl            v1.11.1
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.7.4

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by ysaakpr** [comment]
https://github.com/helm/helm/issues/3275 might be related

**Comment by jstrachan** [comment]
we've been testing this too & made a few fixes (e.g. to only run the promote pipeline in one branch at once to avoid parallel promote pipelines causing issues). I wonder if you `jx upgrade platform` then retest if this issue is fixed for you?

cc @i0n

**Comment by ysaakpr** [comment]
@jstrachan thank you so much..appreciate your effort on this project, will definitely test this and get back to you.

**Comment by ccojocar** [comment]
@ysaakpr I am going to close this issue. Please feel free to open another issue if you are still seeing the problem occurring. Thanks.
