### ISSUE TITLE
option in jx promote cmd to avoid waiting for completion of deployment

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1375]
### Summary .
@jstrachan  While promoting its becoming mandatory to wait for the deployment to be successful. In our setup, we are interested to just trigger the promotion, and exit the build as success. The deployment will be tracked at the env build.  Is there any option to exit immediately after ensuring the merge is done.

**Comment by ysaakpr** [comment]
adding timeout to "" or poll interval to "" wont help here, because which wont merge the env pull request.

On promotion, i think there should be an option to completely  trigger the environment deployment, (PULL REQUEST and MERGE ) and then exit the job as success.

**Comment by jstrachan** [comment]
you can work around this today by just using `--timeout 0` we should allow the promotion timeout to be configured on a per team basis to make it easier for you to adopt without changing your `Jenkinsfiles`

**Comment by jstrachan** [comment]
ah yeah! :) we probably wanna add a `--no-wait` or something flag that avoids polling and doesn't fail the build

**Comment by ysaakpr** [comment]
@jstrachan 
i found two new flags are provided, `--no-poll`, `--no-merge`, but both are not matching this requirement.
I tired do this by adding a no-wait-deployment flag, but somehow its working. It will be really helpful incase if you can add these flags or help me in understanding the git operations in between. I tried to add the loop exits at https://github.com/jenkins-x/jx/blob/f0be6b754116f6b4bf49ba5b27868e131d243b0d/pkg/jx/cmd/promote.go#L672
 and tried to end the loop once https://github.com/jenkins-x/jx/blob/f0be6b754116f6b4bf49ba5b27868e131d243b0d/pkg/jx/cmd/promote.go#L577 this condition is met. But both was not working correctly. It will be really helpful for me to go ahead with jenkins-x with this option.

**Comment by jtnord** [comment]
fixed in #1569
