### ISSUE TITLE
`jx` test-suite is user context sensitive - leading to non-deterministic test results

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#1377]
### Summary

`make test` (or `./test.sh`) depends on user settings.

### Epic

I seem to have a general problem with the testing approach. I tried to find out why the tests of my PR-1353 (Fix for #1352) ran into errors on the reference server: #1353. 

Some tests were even failing locally.
It turned out that the test-suite tries to make use of a credential for github in ~/.jx/gitAuth.yaml. Unfortunately I had experimented with having different user tokens there. Hence, the test-suite tried to open a dialogue to ask me which user I wanted to use.

One workaround was to just set `JX_HOME` to an empty directory. In this case some test cases were simply not executed.

To conclude: I see the test-suite is *highly context dependent* (on settings in my user home) and therefore non-deterministic with respect to different user environments, which is generally a bad idea for a test-suite. How to deal with that?

I now got all tests to pass (or even execute nothing) locally and still have no clue why the tests on the reference environment fail (and still have no access to the log over there).

**Comment by i0n** [comment]
Hi there!

This is something we are aware of, hopefully we'll get everything isolated very soon. PRs very welcome!

**Comment by i0n** [comment]
This should be fixed by https://github.com/jenkins-x/jx/pull/1503
