### ISSUE TITLE
Support for Knative-serve for serverless apps and functions

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#1379]
### Summary 

It would be nice to support google knative https://cloud.google.com/knative/ via a build pack+add on that sets it up in a cluster if it is not already there. 

Setup looks fairly "standard" if long winded right now, but it would be a nice value-add for Jenkins X (and can also make use of pipelines/environments)

This could be the default for quickstarts (ie so all webapps scale to zero).

**Comment by jstrachan** [comment]
agreed!

FWIW I've managed to get a jenkins x release pipeline working in knative too

**Comment by michaelneale** [comment]
@jstrachan still relevant for quickstarts? I should have mentioned this was knative-serve (not build) - ie just the hosting of apps/functions

**Comment by michaelneale** [comment]
Perhaps, although it looks more and more like it is a good default to use for quickstarts and possibly even services in Jenkins X itself which don’t always need to be running.

**Comment by pmuir** [comment]
We can have apps that are installed by default.

**Comment by michaelneale** [comment]
I think this is already possible - documented on the site. Closing I think? IN future can make default serverless.
