### ISSUE TITLE
Pass ENV vars to jx promote

### ISSUE THREAD

**Issue by mrpity** [jenkins-x/jx#1383]
### Summary 
 It would be great if there was an opportunity to pass ENV variables to command "jx preview", and after rewrite vars in Helm charts and in Dockerfile as well...
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.117
jenkins x platform 0.0.1912
kubernetes cluster v1.10.5
kubectl            v1.11.0
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.11.0

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
- kubernetes on-premise
- kubespray
### Operating system / Environment
- Ubuntu 16.04.4 LTS

### Expected behavior
I expect to pass variables to preview env something like this:
```
jx preview --set var:test
```
And then it should rewrites vars for HELM charts and Dockerfile as well
### Actual behavior
As I understand it doesn't implemented in such way.

**Comment by jstrachan** [comment]
could you not just add whatever env vars you wish into the `charts/preview/values.yaml` for the preview helm chart?

**Comment by ccojocar** [comment]
Solution is to pass the env variables in the `charts/preview/values.yaml` files and then reference them in the chart YAML files.

**Comment by iftachsc** [comment]
> Solution is to pass the env variables in the `charts/preview/values.yaml` files and then reference them in the chart YAML files.

This does not help when you want to dynamically send different values to conditions of the requirements.yaml to support Preview flows i.e. different sets of dependencies per PR of the service u r testing. for example in one scenario i need all of the other microservices and in another just 2 or none. i need a way to pass params from pipeline to preview chart. values.yaml is static. thus cannot elevate dependencies conditions of helm
