### ISSUE TITLE
Environments are not being created in the right github org if using a different user

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#1385]
I just tried creating my default environments using a bot github user account.  I noticed that even though I specified the `jenkins-x-bot` user the environment was created under my `rawlingsj` account.  We've had a simnilar report on the Jenkins X office hours this week.

A quick look at the code shows this https://github.com/jenkins-x/jx/blob/master/pkg/gits/github.go#L206-L208

Think this is because there's two APIs for creating github repos, one for users and another for orgs.  https://developer.github.com/v3/repos/#create

Issue seems to be that when the `jenkins-x-bot` user is selected it is removed by the code above and the initial or default git user (rawlingsj) was used instead.

**Comment by rawlingsj** [comment]
So this means the authenticated user is not the user that's being selected in the Survey wizard when asking which user to create the environment user as.

**Comment by tdcox** [comment]
We are finding that every time we onboard a new developer, their account ends up getting used instead of the bot set originally. We could probably use some instructions on how to change the Jenkins-x user after the fact as well as a bug fix, I guess.

**Comment by rawlingsj** [comment]
My particular issue was a bad token, but I'm still sure there's a bug somewhere around using multiple git accounts.  

Closing this.  Lets create a new one with steps to recreate if there is another issue with multiple git accounts.
