### ISSUE TITLE
jx env delete issue

### ISSUE THREAD

**Issue by ervikrant06** [jenkins-x/jx#1389]
### Steps to reproduce the behavior

Created new env with name vikrant.

~~~
$ jx get env
NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER SOURCE                                                                REF PR
dev        Development Development Never   jx            0
staging    Staging     Permanent   Auto    jx-staging    100           https://github.com/ervikrant06/environment-swisherrose-staging.git
vikrant    Vikrant     Permanent   Never   jx-vikrant    100           https://github.com/ervikrant06/jx-vikrant.git
production Production  Permanent   Manual  jx-production 200           https://github.com/ervikrant06/environment-swisherrose-production.git
~~~

By mistake I issued the wrong command which leads to change my env to vikrant.

~~~
$ jx env vikrant delete
Now using environment 'vikrant' in team 'jx' on server 'https://192.168.99.100:8443'.
~~~

Deleted the env when it was my current env. 

~~~
$ jx delete env vikrant
Deleted environment vikrant
To delete the associated namespace vikrant for environment jx-vikrant then please run this command
  kubectl delete namespace jx-vikrant
~~~

As indicated in above command. Deleted the ns also from k8.

~~~
$ kubectl delete namespace jx-vikrant
namespace "jx-vikrant" deleted
~~~

While issuing any command it's giving me any error. 

~~~
$ jx get activity -f python-http -w
error: namespaces "jx-vikrant" not found
~~~

Tried to switch to available env but no luck. Created the K8 ns again. Create the ns manually. 

~~~
$ kubectl create ns jx-vikrant
namespace "jx-vikrant" created
~~~

Current env is set to jx-vikrant

~~~
$ jx env
Using namespace 'jx-vikrant' from context named 'minikube' on server 'https://192.168.99.100:8443'.
~~~

While trying to switch to any other env getting the error. 

~~~
$ jx env jx
error: Invalid argument: jx
Possible values:
~~~

### Jx version

The output of `jx version` is:

```
$ jx version
Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: incompatible versions client[v2.9.1] server[v2.10.0-rc.1]': exit status 1
NAME               VERSION
jx                 1.3.127
kubernetes cluster v1.10.0
kubectl            v1.9.5
helm client        v2.9.1+g20adb27
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.15.2 (Apple Git-101.1)

A new jx version is available: 1.3.132
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it? minikube. Created minikube using minikube command and then initialize the jx. 

### Expected behavior

It should allow me to switch the envs. 

### Actual behavior

It's not allowing me to switch the envs.

**Comment by ccojocar** [comment]
@ervikrant06 I looks like the `jx` environment does not exist. This is the reason why it cannot switch. I am going to close this issue. Please feel free to open another issue if you are still seeing this problem. Thanks
