### ISSUE TITLE
jx create cluster eks does not accept --zones flag

### ISSUE THREAD

**Issue by gossnj** [jenkins-x/jx#1413]
### Summary 
`jx create cluster eks` does not accept `--zones` flag. This is a flag in eksctl, and as noted in README (https://eksctl.io/), frequently necessary for creation us-east1 at the moment. 

### Steps to reproduce the behavior

`jx create cluster eks --region=us-east-1` will frequently fail, producing an UnsupportedAvailabilityZoneException and recommending specifying availability zones. However, there is no way to do this from jx create cluster eks. 

Help text makes reference to EKS_AVAILABILITY_ZONES env var, but as far as I can tell, that is unused.

### Jx version

The output of `jx version` is:

```
1.3.144
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Attempting to create EKS cluster, 1.10

### Operating system / Environment

Mac OS X 10.13.4, EKS

### Expected behavior

`--zones` is accepted and passed on to eksctl. 

### Actual behavior

Error/help text is shown, and there is no way to create cluster in specific availability zones.

**Comment by jstrachan** [comment]
the fix should be released within the hour
