### ISSUE TITLE
Failed `create` with kops on AWS

### ISSUE THREAD

**Issue by kmadel** [jenkins-x/jx#1414]
### Jx version

The output of `jx version` is:

```
jx                 1.3.144
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Attempting to install aws kops v1.9.8: 
```
export AWS_REGION=us-east-1
jx create cluster aws
```

### Operating system / Environment
Mac OS X
### Expected behavior
create runs successfully
### Actual behavior
exits with error:
```
Waiting for the Cluster configuration...
retrying after error: Command failed 'kops get cluster aws1.cluster.k8s.local -ojson': State Store: Required value: Please set the --state flag or export KOPS_STATE_STORE.
A valid value follows the format s3://<bucket>.
A s3 bucket is required to store cluster state information. exit status 1

.......export KOPS_STATE_STORE=s3://kops-state-268150017804-f77e4de9-95cb-11e8-a206-4a0000871f40
...............................................................................................................................................................................................error: Failed to wait for the Cluster JSON: after 200 attempts, last error: Command failed 'kops get cluster aws1.cluster.k8s.local -ojson': State Store: Required value: Please set the --state flag or export KOPS_STATE_STORE.
A valid value follows the format s3://<bucket>.
A s3 bucket is required to store cluster state information. exit status 1
```
I would assume that jx should be exporting the KOPS_STATE_STORE as part of the create process.

**Comment by remear** [comment]
Are there any updates on this? I still experience this issue with jx 1.3.256 and kops 1.10.0.

**Comment by jstrachan** [comment]
@remear whats is the value of $KOPS_STATE_STORE for you?

I wonder if the bug is if the value is defined, we need to assign to `state` here:....
https://github.com/jenkins-x/jx/blob/8d7e1284ffe77536c007b3559b0e92243fddbc74/pkg/jx/cmd/create_cluster_aws.go#L178-L180
e.g. something like...
```go
		kopsState := os.Getenv("KOPS_STATE_STORE")
		if kopsState != "" {
			state = "s3://" + kopsState
```
does that sound right?
