### ISSUE TITLE
Deployment jenkins-x-monocular-api failed to become ready in namespace jx

### ISSUE THREAD

**Issue by kevinsuperped** [jenkins-x/jx#1417]
### Summary 
I am installing JX on a cluster on premise. It is one master three worker nodes. It is using rook for storage and creates dynamic pvs. I kick off the install and jenkins-x-monocular-api and jenkins-x-monocular-ui continuously crash loop backoff. The logs on monocular-api are as follows:

```
time="2018-08-02T19:41:26Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml"
time="2018-08-02T19:41:26Z" level=info msg="Configuration file found!"
time="2018-08-02T19:41:26Z" level=info msg="Loading CORS from config file"
time="2018-08-02T19:41:26Z" level=info msg="Loading repositories from config file"
time="2018-08-02T19:41:26Z" level=info msg="Configuration bootstrap finished"
time="2018-08-02T19:41:37Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017"
```

The mongodb is up and running, this seems to be a DNS issue. Logging on to the machine, I can confirm I cannot look up the service.  

### Steps to reproduce the behavior
Install JX on a on-premise cluster

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.144
jenkins x platform 0.0.2017
kubernetes cluster v1.11.0
kubectl            v1.11.1
helm client        v2.10.0-rc.2+g5615410
helm server        v2.10.0-rc.2+g5615410
git                git version 2.7.4
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
On premise, on Ubuntu 1604. Using kubeadm 

### Operating system / Environment
16.04 Ubuntu on Proxmox

### Expected behavior
Installs all the pods

### Actual behavior
Doesn't install monocular-api and monocular-ui

**Comment by sercanacar** [comment]
Same issue

**Comment by jakelima18** [comment]
I have the same issue

**Comment by gigyas** [comment]
Also having this issue. EKS cluster on AWS.
monocular-api continually crashes with log:

```
$ kc logs -f jenkins-x-monocular-api-5467bcbb7b-hvgrc
time="2018-10-29T14:53:18Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml"
time="2018-10-29T14:53:18Z" level=info msg="Configuration file found!"
time="2018-10-29T14:53:18Z" level=info msg="Loading CORS from config file"
time="2018-10-29T14:53:18Z" level=info msg="Loading repositories from config file"
time="2018-10-29T14:53:18Z" level=info msg="Configuration bootstrap finished"
time="2018-10-29T14:53:28Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017"
```

jx version:
```
$ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.483
jenkins x platform 0.0.2789
Kubernetes cluster v1.10.3-eks
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.16.2
```

**Comment by shawnwhit** [comment]
Same issue here, On EKS

NAME VERSION
jx                 1.3.528
jenkins x platform 0.0.2859
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1

**Comment by jadepeng** [comment]
same issue too
NAME               VERSION
jx                 1.3.534
jenkins x platform 0.0.2871
Kubernetes cluster v1.12.2
kubectl            v1.12.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 1.8.3.1


time="2018-11-08T07:17:33Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-11-08T07:17:33Z" level=info msg="Configuration file found!" 
time="2018-11-08T07:17:33Z" level=info msg="Loading CORS from config file" 
time="2018-11-08T07:17:33Z" level=info msg="Loading repositories from config file" 
time="2018-11-08T07:17:33Z" level=info msg="Configuration bootstrap finished" 
time="2018-11-08T07:17:44Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017"

**Comment by ccojocar** [comment]
This issue seems to be fixed in the latest chart version of chartmuseum.
