### ISSUE TITLE
Different helm versions on client and server sides installed by `jx create cluster eks`

### ISSUE THREAD

**Issue by vochicong** [jenkins-x/jx#1419]
### Summary 

I used `jx create cluster eks` to install jx, and found that it could not create preview environment due to helm versions mismatch on client and server sides. 

After install the same helm version into the server side, the preview environment was built.

### Steps to reproduce the behavior

1. jx create cluster eks
2. jx create quickstart, choose rails-shopping-cart
3. Create a PR for rails-shopping-cart

### Jx version

The output of `jx version` is:

Just after step 1

```
NAME               VERSION
jx                 1.3.144
jenkins x platform 0.0.2017
kubernetes cluster v1.10.3
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.18.0
```

When the PR preview environment failed 

```
NAME               VERSION
jx                 1.3.145
kubernetes cluster v1.10.3
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.18.0
```

After
```
helm init --upgrade --force-upgrade
```

```
$ jx version
NAME               VERSION
jx                 1.3.145
jenkins x platform 0.0.2017
kubernetes cluster v1.10.3
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.18.0
```

and the PR preview environment was built.

### Kubernetes cluster

EKS, using ` jx create cluster eks`

### Operating system / Environment

MacOS

### Expected behavior

Able to build PR preview environment.

**Comment by vochicong** [comment]
Related to https://github.com/jenkins-x/jx/issues/1271

**Comment by jstrachan** [comment]
we're hoping to automate this better to validate the version of helm on the current laptop and so forth - see https://jenkins-x.io/faq/issues/#helm-fails-with-error-upgrade-failed-incompatible-versions-client-server

**Comment by vochicong** [comment]
This issue is not for for my laptop, since I use the same helm version as the one used in JX server.

It's the helm version in build container 'ruby'. Should I run `helm init --upgrade`  inside the container before doing `jx preview` ?

**Comment by tdcox** [comment]
@vochicong The version of helm required by the version of Jenkins-X you are running is defined based upon the helm client installed in the build containers. At the time of writing, this is v2.10.0-rc.1+gaa98e7e. If you install this version on the local machine that you are using to run `jx` commands and then upgrade the ‘helm server’ / ‘Tiller’ component, you will have matching versions of helm everywhere. This is advisable since there are some issues with earlier versions of helm when used with Jenkins-X.

**Comment by vochicong** [comment]
I'm confused. How does the helm version on my local Machine relate to that version in the build container and helm server?

**Comment by ccojocar** [comment]
This issue might be fixed by now. An other option is to use `no-tiller` to avoid the version incompatibility between the client and the server.
