### ISSUE TITLE
Jenkin-X already installed - how do use another computer to operate using jx ? 

### ISSUE THREAD

**Issue by iamsharife** [jenkins-x/jx#1424]
### Summary 
I already installed Jenkin-X using another computer - i would like to use an alternative machine to interact with it as well.

### Steps to reproduce the behavior
* Install jx using Computer A 
* Install Cluster using Computer A - jx install 
* Login on another computer (Computer B)
* Install jx using Computer B
* Not sure at this point how to connect ? 

### Jx version

The output of `jx version` is:

```
1.3.147
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

EKS - v1.10.3

### Operating system / Environment
MacOSX

### Expected behavior
Command that allows me to pull down or setup jx with an existing install jx cluster

**Comment by paolocarta** [comment]
The steps should be the following as far as I know:
- jx ns jx
- jx status

I will have a look documentation about it and add a few lines if not available.

**Comment by svilenvul** [comment]
We are also interested in these instructions.

**Comment by svilenvul** [comment]
@i0n, sorry, didn't unassign you intentionally :)
