### ISSUE TITLE
jx create cluster eks with --profile switch fails at register DNS alias step

### ISSUE THREAD

**Issue by chuckwilbur** [jenkins-x/jx#1431]
### Summary 
jx create cluster eks using a --profile switch fails at register DNS alias step

### Steps to reproduce the behavior
default profile with limited access
alternate profile with access required by jx
domain pre-created in Route 53
`jx create cluster eks --profile <alternate>`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.149
kubernetes cluster v1.10.3
kubectl            v1.11.1
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.10.1 (Apple Git-78)
```

### Kubernetes cluster

EKS

### Operating system / Environment
MacOS

### Expected behavior
Cluster created, jx set up on domain pre-created in Route 53

### Actual behavior

```
Would you like to register a wildcard DNS ALIAS to point at this ELB address?  Yes

? Your custom DNS name:  <domain>.com
ingress init failed: AccessDenied: User: arn:aws:iam::<default restricted user> is not authorized to perform: route53:ListHostedZones
	status code: 403, request id: 24d16140-9982-11e8-b59d-535395213cdd
error: failed to initialize the jx: AccessDenied: User: arn:aws:iam::<default restricted user> is not authorized to perform: route53:ListHostedZones
	status code: 403, request id: 24d16140-9982-11e8-b59d-535395213cdd
```

**Comment by jvz** [comment]
Seems as though the issue here is that `amazon.RegisterAwsCustomDomain` only takes a domain and ELB address as params. The profile lookup is done via environment variables instead of being passed from the CLI options.

**Comment by ccojocar** [comment]
@chuckwilbur I am going to close this issue. The EKS support has improved a lot in the meantime. Please feel free to open another issue if you are still seeing this issue. Thanks
