### ISSUE TITLE
Unable to fully create an environment in batch mode

### ISSUE THREAD

**Issue by darthcabs** [jenkins-x/jx#1432]
### Summary
I can't seem to be able to automate the creation of an environment in Jenkins X, without any human interaction using `jx`. From what I could observe, upon creating an environment interactively, I get asked for 12 pieces of information, many of which I was able to find the corresponding `jx` flag to:

Name.................................................-n
Label..................................................-l
Namespace........................................-s
Domain...............................................--domain
Cluster................................................-c
Promotion...........................................-p auto
Provider..............................................--git-provider-url https://github.com
Git Username.....................................--git-username
GitHub Org.........................................???
Repo name.........................................???
Git branch...........................................--branches "master"
Jenkins Pipeline Username................???

However, I couldn't find a way to provide **GitHub Org**, **Repo name** (In which it will create the environment) and **Jenkins Pipeline Username** (it's just for confirming that I want to use my Git username as my Jenkins pipeline username too).

My question is: Is there really a way of providing those info, in order to make the creation of the environment truly automated?

### Steps to reproduce the behavior

Issue command `jx create env -n bruvs-butthead -l bruvs-butthead -s jx-bruvs --domain butthead.bruvs.example.com	-c -p auto --git-api-token a65cfe9043cd92d8b885f0ad26b7667553aac289 --git-provider-url https://github.com --git-username darthcabs --branches "master"` and notice that it still asks for more information.

### Jx version

```
NAME               VERSION
jx                 1.3.144
jenkins x platform 0.0.2017
kubernetes cluster v1.9.8
kubectl            v1.11.0
helm client        v2.10.0-rc.2+g5615410
helm server        v2.10.0-rc.2+g5615410
git                git version 2.13.3

```

### Kubernetes cluster

Created using Kops. Installed Jenkins X with `jx install --provider=aws`

### Operating system / Environment

linux-amd64

### Expected behavior

I should be able to achieve the same results either interactively or in batch mode.

### Actual behavior

Even using all `jx` flags, I cannot create an environment in an automated way.

**Comment by ccojocar** [comment]
@darthcabs It should be working now in batch mode. I am going to close this issue. Thanks
