### ISSUE TITLE
Can Jenkins-X actually be installed on premise?

### ISSUE THREAD

**Issue by kevinsuperped** [jenkins-x/jx#1434]
### Summary 
I have tried numerous times to install Jenkins-x on 4 Ubuntu 16.04 VMs, and it always fails trying to get to its own frontend. At the Please go to http://jenkins.jx.<wildcard domain>/me/configure step, it fails to scrape its own IP and I cannot get to the page. The ingress the script creates doesn't create an ingress connect to a NodePort, which is required for nginx ingress on non-cloud k8s. I have tried editing the ingess multiple times. adding flags like --report-node-internal-ip-address, but it never is bound to any node ip

*EDIT*
I wrote that late at night, but to offer more clarity, I have tried everything I can think of, I have DNS record pointing to the IPs, setting the external IP flag at the install, switching the service from LB to NodePort. I fear that the script grabs the API IP, and sets up a nginx ingress that would not work on a baremetal cluster. I know the k8s project is more focused on a cloud install, but this seems like it should work.

Do I need a ingress set up before hand? Can I use a flag to skip ingress install(I looked didn't see one)? Anyone have any success install JX on premise and know of a guide or short statement on how they exposed the service? 

### Steps to reproduce the behavior
Install jx on premise kuberneted
### Jx version

The output of `jx version` is:

```
jx                 1.3.90
jenkins x platform 0.0.2017
kubernetes cluster v1.11.0
kubectl            v1.11.0
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.7.4E
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
created using kubeadm on one master three node cluster. Other deployments work fine. 
### Operating system / Environment
Ubuntu 16.04 VMs on Proxmox using Rook for ceph dynamic storage provider
### Expected behavior
Jenkins ingress bound to node or cluster IP
### Actual behavior
It isn't

**Comment by johnaoss** [comment]
I managed to get a workaround by setting up the ingress controller before running `jx install`. I installed the `stable/nginx-ingress` Helm chart, in the  and specified the servicetype on that to be NodePort, and set an external IP. Once running, take note of the deployment name and service name.

You can then specify them when using `jx install` like so:

```bash
jx install --provider=kubernetes --external-ip 10.123.0.17 --ingress-service=$(yoursvcname) --ingress-deployment=$(yourdeployname) --ingress-namespace=kube-system
```

Hope this helps!

**Comment by ccojocar** [comment]
The solution is documented. Closing this issue.

**Comment by marcstreeter** [comment]
@johnaoss after you get Jenkins-X installed, are you somehow connecting it to an onprem Gitlab or Gitea?  I'm very interested in the onprem (and airgapped) story for CI/CD.  It seems like it would be a natural fit, but I've been hitting roadblocks where there doesn't seem to be a way to do the full process (Jenkins-X with gitlab or Gitea for example) outside of a cloud provider (on baremetal).

This probably isn't the right place to ask this question so I'm open to taking it offline/elsewhere if preferred.

**Comment by codiophile** [comment]
@jstrachan @ccojocar The linked documentation is marked as deprecated and on the non-deprecated install and setup page only lists GCP and AWS as options. So does that mean that Jenkins X can no longer be installed on premise or that the new documentation is lacking?

**Comment by bmgeek** [comment]
> @jstrachan @ccojocar The linked documentation is marked as deprecated and on the non-deprecated install and setup page only lists GCP and AWS as options. So does that mean that Jenkins X can no longer be installed on premise or that the new documentation is lacking?

interested in this question.

did you find any information?
