### ISSUE TITLE
how to change the urls

### ISSUE THREAD

**Issue by song316** [jenkins-x/jx#1437]
### Summary 
i change the k8s ingress to my own domain allready, but exec "jx get urls" show *.jx.y ? 

[.jx] jx get urls                                                                                                                  
Name                      URL
jenkins                   http://jenkins.jx.y
jenkins-x-chartmuseum     http://chartmuseum.jx.y
jenkins-x-docker-registry http://docker-registry.jx.y
jenkins-x-monocular-api   http://monocular.jx.y
jenkins-x-monocular-ui    http://monocular.jx.y
nexus                     http://nexus.jx.y

### Jx version
1.3.144
The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.144
jenkins x platform 0.0.784
kubernetes cluster v1.10.4
kubectl            v1.11.1
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.14.3 (Apple Git-98)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by song316** [comment]
I resolved by myself.
change the service's Annotations resolved my problem.

**Comment by mcncyo** [comment]
how do you do this?

**Comment by artsilenkov** [comment]
@mcncyo use
`kubectl edit svc` command for each svc with annotation in jx environment
