### ISSUE TITLE
Unable to use GitLab as git provider

### ISSUE THREAD

**Issue by kurktchiev** [jenkins-x/jx#1438]
### Summary 
I am doing an installation on premise and would like to use our internal GitLab server as inbound traffic to our network is not allowed and I cannot make any of the demo apps to work as they are trying to ping back the jenkins server with a webhook.

### Steps to reproduce the behavior
1. jx create git server gitlab URL -n SolGit
2. jx install --provider='kubernetes' --domain=ingress.sol.local --skip-ingress=true --headless=true --skip-tiller=true --default-admin-password='c00ldemo'
3. Select my newly added git provider at the start 
4. Fail with the following:
Created user admin API Token for Jenkins server jenkins.jx.ingress.sol.local at http://jenkins.jx.ingress.sol.local
Updating Jenkins with new external URL details http://jenkins.jx.ingress.sol.local
Creating default staging and production environments
Using git provider GitHub at https://github.com
error: failed to create staging environment: Server https://github.com has no user auths defined!

It basically is not actually acknowledging that I selected a non github provider.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.151
jenkins x platform 0.0.2017
kubernetes cluster v1.8.11
kubectl            v1.11.1
helm client        v2.8.0+g14af25f
helm server        v2.8.0+g14af25f
git                git version 2.18.0
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Local vanilla k8s cluster (non minikube)

### Operating system / Environment
CentOS

### Expected behavior
do the install using my desired git provider

### Actual behavior
still using Github regardless of selection

**Comment by 2ZZ** [comment]
I am also having this issue

**Comment by wbrefvem** [comment]
@ebalsumgo

This issue may have been fixed by https://github.com/jenkins-x/jx/pull/1488. Are you still having the same issue?

**Comment by ebalsumgo** [comment]
I will have to try it out and report

**Comment by ebalsumgo** [comment]
@wbrefvem so running into a new problem thats keeping from answering the original question. The mongo instances are not standing up due to enabling ipv6 by default in the mongo chart, to get it going I have to disable it, but I do not see anything in https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml that references it so not sure how to overwrite the parameter. https://github.com/helm/charts/commit/4e3544cf3c34c328470a343f38a01c66d29e0842 this commit added the ability to toggle ipv6 suggestions?

**Comment by ccojocar** [comment]
@kurktchiev I am going to close this issue. Please feel free to open another issue for the second issue you are describing. Thanks
