### ISSUE TITLE
jx promote continuously fails after first failure

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1441]
### Summary 
Related to https://github.com/helm/helm/pull/3597, 
How do we address this case in jx promote command, this becoming a tedious process to do manual clean after every failed deployment of the env repo

**Comment by jstrachan** [comment]
does this just mean we need to add `--force` to the `helm upgrade --install` command right?

**Comment by tdcox** [comment]
Potentially need to be mindful of install hooks being run instead of upgrade in that scenario...

**Comment by ysaakpr** [comment]
But...what is the reason for this kind of failure..Looking on the helm
ticket still there are no mention of the cause of this issue and have
proper fix for it.
As far as i understand..in case of a failure helm does an automatic
rollback.. What could be the ideal fix for this..instead of using --force.
Which does a clean install in case of a failure, which will trigger the
install hooks again.

**Comment by ccojocar** [comment]
The force flag is now turned on when running the helm upgrade command.
