### ISSUE TITLE
Install jx on private kubenetes cluster

### ISSUE THREAD

**Issue by anupts** [jenkins-x/jx#1447]
We are very new to Jenkins-X and want to know how we can install it on private kubernetes cluster ?

Is minikube same as private kubernetes cluster ?

**Comment by rawlingsj** [comment]
Yes you can although there's some prerequisites, details are described here https://jenkins-x.io/getting-started/install-on-cluster/

**Comment by anupts** [comment]
Hi ,

Thank you. We have our own docker enterprise version. is there a way to use with that?

**Comment by alexanderrtaylor** [comment]
Your own docker enterprise version should not matter since that would be configured within your kubernetes cluster. As long as your kubernetes cluster is able to pull down images and start them up then you are still meeting the requirements

Please correct me if I am wrong @rawlingsj

**Comment by alexanderrtaylor** [comment]
Hey Anup,

>I am not sure how to connect our docket enterprise and kubernetes .

This is not something which will be within the Jenkins-X documentation since we assume a functional kubernetes cluster. Once you are able to integrate your Kubernetes cluster with your docker enterprise then you would follow the Jenkins-X docs mentioned on the article linked earlier https://jenkins-x.io/getting-started/install-on-cluster/.

For connecting docker and kubernetes you should probably be looking at docker documentation rather than Jenkins.

**Comment by anupts** [comment]
Hello,

I have downloaded the docker bundle and able to set the cluster.Now how to use this?


Cluster "ucp_ucp.com:6443_User" set.
User "ucp_ucp.com:6443_User" set.
Context "ucp_ucp.com:6443_User" created.

**Comment by johnaoss** [comment]
@anupts If your Docker Enterprise comes with a registry, you can specify it using the `--docker-registry=host:port` on `jx install`, replacing host and port with your respective values.

**Comment by scblur869** [comment]
I have a vanilla cluster running in AWS and cannot get the jx install to recognize the proxy running in the VPC. I an curl the .yaml files required and that works..but jx install will not pull them down..times out..any idea?

**Comment by anupts** [comment]
Hello,
 i tried many things but couldn't succeed in installing jx.

Could you please let me know the procedure to install jx using minikube? What are the pre-requisites to install and procedure to install the pre-requisites ?

I tried the below steps:

========================================================


curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube
curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo cp kubectl /usr/local/bin/ && rm kubectl

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
mkdir -p $HOME/.kube
touch $HOME/.kube/config

export KUBECONFIG=$HOME/.kube/config
sudo -E minikube start --vm-driver=none

================================================================

It gave error saying docker daemon is not running. And then i tried to install docker but couldn't succeed..
