### ISSUE TITLE
How to start jx cluster and server after reboot?

### ISSUE THREAD

**Issue by janwendt** [jenkins-x/jx#1448]
I created a minikube cluster using:

```
jx create cluster minikube
```
Everything worked as aspected. 
After restarting my computer the cluster and the jenkins server are not running e.g. `jx open` results in:
```
Unable to connect to the server: dial tcp 192.168.99.100:8443: 
```
How to restart the cluster and server as `jx create cluster` did it? I did not find any suitable command in the docs. Thanks!

**Comment by ccojocar** [comment]
dup of #933
