### ISSUE TITLE
Update via "jx version"

### ISSUE THREAD

**Issue by marob** [jenkins-x/jx#1452]
### Summary 

When `jx version` asks

```
? Would you like to upgrade to the new jx version? [? for help] (Y/n)
```

Answering `y` will download the new version in `~/.jx/bin`.
But [install documentation](https://jenkins-x.io/getting-started/install/) instructs to move the binary in /usr/local/bin (`sudo mv jx /usr/local/bin`) which results in 2 `jx` binaries and using the one that is not updated (the one in `/usr/local/bin`) unless the `~/.jx/bin` directory has been added in the $PATH before `/usr/local/bin`.

Also, pressing "CTRL+C" starts updating `jx`!?

### Steps to reproduce the behavior
See summary.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.151
jenkins x platform 0.0.2017
kubernetes cluster v1.9.1+a0ce1bc657
kubectl            v1.11.2
helm client        v2.10.0-rc.2+g5615410
helm server        v2.10.0-rc.2+g5615410
git                git version 2.17.1
```

### Kubernetes cluster
N/A

### Operating system / Environment

Ubuntu 18.04

### Expected behavior
Consistency between `jx` update mechanism and documentation.
Do not update when CTRL+C.

### Actual behavior
See summary.

**Comment by i0n** [comment]
This should be fixed from: 1.3.189+
