### ISSUE TITLE
Use AWS config to set region instead of environment variables in `ecr.go`

### ISSUE THREAD

**Issue by sanketjpatel** [jenkins-x/jx#1453]
[WIP] - add more details

### Summary 
Currently `ecr.go` creates the registry in `us-west-2` by default if the `AWS_REGION` environment variable is not set. We should probably read the config from `~/.aws/config` to set the appropriate region instead.

**Comment by polothy** [comment]
This has happened to me as well.

**Comment by polothy** [comment]
Looks like there is more traction over in #1376

**Comment by msvticket** [comment]
What would make sense to me is using the registry stored in configmap jenkins-x-docker-registry, which is created when installing Jenkins-X.
