### ISSUE TITLE
jx upgrade with custom configurations are not working

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1463]
### Summary 
Unable to successfully upgrade the platform using jx upgrade command
### Jx version
latest

The output of `jx version` is:

```
jx                 1.3.153
jenkins x platform 0.0.2087
kubernetes cluster v1.9.8
kubectl            v1.11.1
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.7.4
```

Unable to upgrade the platform using jx upgrade command. Especially confused on how to set the docker registry to custom ECR docker URL, Its always getting reset to the local docker registry url.

**Comment by ysaakpr** [comment]
https://github.com/jenkins-x/jenkins-x-platform/issues/2600

**Comment by deyceg** [comment]
@ysaakpr last time I checked, avoid `jx upgrade` it doesnt do what you think it does. Or at least, its not consistent with `jx install` so you get weird results

A good example is the jenkins password gets reset to admin/admin :)

I've favored running `jx install` again, and accepting the admin password gets rotated and may need a restart of the pod

**Comment by ysaakpr** [comment]
yes...i too faced same thing...but what is the other wway to upgrade the
jenkins platform safly

**Comment by jjouanno** [comment]
Hi,

so what do the "jx upgrade platform" cmd?

And how to update jenkins master version and adding plugins persitant for next restart?

Thanks

**Comment by ccojocar** [comment]
You can find some docs at https://jenkins-x.io/getting-started/config/#readout, which explains how to overwrite the current platform values when running the `jx upgrade platform` command.
