### ISSUE TITLE
Feature: Artifactory Documentation

### ISSUE THREAD

**Issue by cdenneen** [jenkins-x/jx#1464]
Based on README and website I'd like to create this to track work on creating documentation for switching to Artifactory:

As mentioned here: https://jenkins-x.io/architecture/components/
2, 3, 4 should be able to be swapped out for Artifactory and how to do that would be worth having documentation on each:

- [ ] Replacing Nexus with Artifactory for binary repository
- [ ] Using Artifactory as Docker Registry
- [ ] Using Artifactory as Helm Chart Repository

I do not yet have any of these working or even a wip yet but wanted to created this for track just in case others have figured out what changes need to happen to make this a reality.

**Comment by pmuir** [comment]
Dupe of #805
