### ISSUE TITLE
Failed to configure ingress controller on EKS

### ISSUE THREAD

**Issue by fdouek** [jenkins-x/jx#1472]
### Summary 
When using jx to create a new EKS cluster, the cluster is created successfully, however it fails to configure the ingress controller.

### Steps to reproduce the behavior
jx create cluster eks --cluster-name demojx2 --ssh-public-key devopsdemo.pub

### Jx version
NAME               VERSION
jx                 1.3.164
kubernetes cluster v1.10.3
kubectl            v1.10.3
helm client        v2.10.0-rc.2+g5615410
helm server        v2.10.0-rc.2+g5615410
git                git version 2.14.4

The output of `jx version` is:

```
2018-08-13T01:50:56Z [✔]  EKS cluster "demojx2" in "us-west-2" region is ready

Initialising cluster ...
Creating default storageclass gp2 with provisioner kubernetes.io/aws-ebs
Git configured for user: fdouek and email fdouek@gmail.com
Trying to create ClusterRoleBinding devopsdemo-demojx2-us-west-2-eksctl-io-cluster-admin-binding for role: cluster-admin for user DevOpsDemo@demojx2.us-west-2.eksctl.io
: clusterrolebindings.rbac.authorization.k8s.io "devopsdemo-demojx2-us-west-2-eksctl-io-cluster-admin-binding" not foundCreated ClusterRoleBinding devopsdemo-demojx2-us-west-2-eksctl-io-cluster-admin-binding
Created ServiceAccount tiller in namespace kube-system
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
Created ClusterRoleBinding tiller
Initialising helm using ServiceAccount tiller in namespace kube-system
helm installed and configured
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Using helm values file: /tmp/ing-values-313143387
Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true --values /tmp/ing-values-313143387' command in directory '', output: 'Error: a release named jxing already exists.
Run: helm ls --all jxing; to check the status of the release
Or run: helm del --purge jxing; to delete it': exit status 1
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
ingress init failed: service jxing-nginx-ingress-controller never became ready
error: failed to initialize the jx: service jxing-nginx-ingress-controller never became ready
```

### Kubernetes cluster

EKS. Cluster created by jx

### Expected behavior
Cluster successfully created and a successful response from jx when all tasks completed.

### Actual behavior
Error message mentioned in the jx output

**Comment by jstrachan** [comment]
the error message `Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true --values /tmp/ing-values-313143387' command in directory '', output: 'Error: a release named jxing already exists.` - it looks like you already had a `jxing` release installed - maybe from a previous attempt?

try running `helm delete --purge jxing` and try again?

**Comment by fdouek** [comment]
Thanks @jstrachan , for the quick reply. The error is happening on a clean cluster create, I'm able to reproduce the issue by creating a new cluster.
I will try to run again, and add more details to this ticket. Is there anything specific which could help to troubleshooting?

**Comment by psiwczak** [comment]
I have exactly same issue

JX version: 1.3.163

**Comment by ccojocar** [comment]
I think the `LoadBalancer` does not get assigned a public IP.  This issue appears to me to be in the EKS/AWS cloud provider for Kubernetes.

Could you deploy the `nginx-ingress` controller standalone?

**Comment by fabiodouek** [comment]
Hi @ccojocar , sure I can deploy the nginx-ingress controller. I believe Jenkins-x swicthed to NLB instead of Classic layer 4?

**Comment by shcallaway** [comment]
I'm having the same problem as OP. I can do `helm install stable/nginx-ingress` no problem, but `jx install` results in:

```
? Cloud Provider eks
Creating default storageclass gp2 with provisioner kubernetes.io/aws-ebs
Git configured for user: REDACTED and email REDACTED
Trying to create ClusterRoleBinding aws-cluster-admin-binding for role: cluster-admin for user aws
: clusterrolebindings.rbac.authorization.k8s.io "aws-cluster-admin-binding" not foundCreated ClusterRoleBinding aws-cluster-admin-binding
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
Created ClusterRoleBinding tiller
Tiller Deployment is running in namespace kube-system
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Using helm values file: /var/folders/28/44fwxs2s5c75zbtk5c2d_qg40000gn/T/ing-values-400495247
Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true --values /var/folders/28/44fwxs2s5c75zbtk5c2d_qg40000gn/T/ing-values-400495247' command in directory '', output: 'Error: a release named jxing already exists.
Run: helm ls --all jxing; to check the status of the release
Or run: helm del --purge jxing; to delete it': exit status 1
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
ingress init failed: service jxing-nginx-ingress-controller never became ready
error: failed to initialize the jx: service jxing-nginx-ingress-controller never became ready
```

**Comment by scblur869** [comment]
I have the same issue with just regular AWS and a KOPs installed cluster. @ccojocar do you know if the ingress controller has to be external?  or can it be internal as well with the ```service.beta.kubernetes.io/aws-load-balancer-internal: ‘true’ ``` annotation. Can I use a private subnet with this ingress controller? currently i fails because it says there is not a subnet available which this would be true for public ones since I only have private subnets

**Comment by scblur869** [comment]
Hi All, so in further testing in AWS with jx, it seems like when helm tries to create the ingress controller for jxing that is fails if all of the subnets are "private". In our configuration we have a private VPC and a public VPC. In the private VPC there is no internet gateway and no public subnets since this VPC has a direct connection to our Corporate network. I do not thing jenkins-x will work in the private. If anyone has other thoughts on this please share!

**Comment by scblur869** [comment]
Hi, I can run ``` jx init ``` to create he ingress controller. It will fail to finalize the controller if there is not a public subnet in the VPC. I can edit the values yaml, add the annotation two comments up and rerun the helm command that jx was running, it will then finalize the controller but pass no traffic. I am wondering if this is more of an nlb issue in k8s since i think its still in alpha

**Comment by ccojocar** [comment]
@fdouek I am going to close this issue. Please feel free to open another issue if you are still seeing this problem occurring. Thanks

**Comment by surajr** [comment]
@scblur869 Could you please share your resolution? I'm facing the same issue

**Comment by phillycheeze** [comment]
This happens even if the VPC has a public subnet for our setup, when trying to install to an already existing EKS cluster. If other people know of a resolution, it would be great if you could share it!

**Comment by larrybolt** [comment]
Facing the same issue on GCP
