### ISSUE TITLE
Creation of Jenkins Jobs failed if old enviroments are available in .jx

### ISSUE THREAD

**Issue by sekmarco** [jenkins-x/jx#1480]
### Steps to reproduce the behavior

* Create Cluster via Kops including helm and nginx with classic load balancer
* Create hosted route53 zone
* `jx install --provider aws`

jenkins-x environment is working fine

remove everything with 
`kops delete cluster --name $clustername --yes`

redo same steps with old files in .jx

* Create Cluster via Kops including helm and nginx with classic load balancer
* Create hosted route53 zone
* `jx install --provider aws`

### Jx version

The output of `jx version` is:

```
jx                 1.3.164
jenkins x platform 0.0.2131
kubernetes cluster v1.9.8
kubectl            v1.11.2
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

kops create cluster aws

### Operating system / Environment

Mac/OS

### Expected behavior

Creation of Jenkins jobs are working

### Actual behavior

`Created environment staging`
`retrying after error:Failed to create the $folder folder in jenkins: 500 Server Error`

after deleting .jx and redo the `jx install`, it is working

**Comment by ccojocar** [comment]
@sekmarco I think this issue has been fixed in the meantime. I am going to close it. Please feel free to open another issue if you see the problem occurring again. Thanks
