### ISSUE TITLE
`jx create quickstart` does not register on AWS ECR

### ISSUE THREAD

**Issue by sekmarco** [jenkins-x/jx#1484]
### Summary 

Project created via `jx create quickstart`do not register automatically on AWS ECR
and need to be manually added afterwards

### Steps to reproduce the behavior

Setup jx on AWS cluster

`jx create quickstart`

### Jx version

The output of `jx version` is:

```
jx                 1.3.164
jenkins x platform 0.0.2131
kubernetes cluster v1.9.8
kubectl            v1.11.2
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Kubernetes cluster on AWS, created via kops

### Expected behavior

create ECR entry

### Actual behavior

```
Let's ensure that we have an ECR repository for the docker image sekmarco/rust-http
Created ECR repository: $AWS-ECR-URL/$owner/rust-http
Created Jenkins Project: http://jenkins.jx.atb.local/job/$owner/job/rust-http/
```

with no ECR entry

**Comment by polothy** [comment]
How do you do this manually?  Our pipeline fails when it tries to push to ECR with what looks like a permission error.  The ECR repository does exist.  Wondering if this is related...

**Comment by msvticket** [comment]
It could be that the ECR repository is created in the wrong AWS region. That is an issue that we have experienced. Does `$AWS-ECR-URL` really match where Jenkins is trying to push the image?

**Comment by ccojocar** [comment]
It might be fixed by https://github.com/jenkins-x/jx/pull/1999.
