### ISSUE TITLE
helm chart install fails when kube config is set with a variable

### ISSUE THREAD

**Issue by cmosetick** [jenkins-x/jx#1487]
### Summary 
Using a Kube Config file variable, helm install / upgrade does not work.
This seems to be because kubectl set current-context does not work correctly with kubeconfig environment variables.

### Steps to reproduce the behavior
- Set an environment variable with `export KUBECONFIG=$PWD/kube-config`
- helm install /upgrade section fails.
- `unset KUBECONFIG` variable.
- copy the local dir kubeconfig file to ~/.kube/config for the same exact cluster and the helm install install/upgrade works.
- `cd to $HOME/.jx/cloud-environments/env-aws`
- run the helm install / upgrade again and it works this time
```
helm upgrade --namespace jx1 --install --timeout 6000 --version 0.0.2131 --values ./myvalues.yaml --values ./secrets.yaml --values $HOME/.jx/gitSecrets.yaml --values $HOME/.jx/adminSecrets.yaml --values $HOME/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform
```

### Jx version
The output of `jx version` is:

```
jx                 1.3.168
jenkins x platform 0.0.2131
kubernetes cluster v1.10.3
kubectl            v1.11.2
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.18.0
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AWS EKS cluster created with Terraform

### Operating system / Environment
Mac OS 10.13.6

### Expected behavior
A kubeconfig variable should be detected early on in the install process, and if not really supported, exit out before creating a jenkins-x installation.

### Actual behavior
The jx install command proceeds all the way to helm chart installation where it then fails with this output:

```
Installing Jenkins X platform helm chart from: $HOME/.jx/cloud-environments/env-aws
error: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx1 --install --timeout 6000 --version 0.0.2131 --values ./myvalues.yaml --values ./secrets.yaml --values $HOME/.jx/gitSecrets.yaml --values $HOME/.jx/adminSecrets.yaml --values $HOME/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '$HOME/.jx/cloud-environments/env-aws', output: 'Error: an error on the server ("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.15.2</center>\r\n</body>\r\n</html>") has prevented the request from succeeding (get pods)': exit status 1
```

**Comment by ccojocar** [comment]
@cmosetick Does it work, if you run `helm` standalone without `jx` but with `$KUBECONFIG` set? It looks to me like a helm issue.

**Comment by ccojocar** [comment]
Closing this since it seems to be related to the kube configuration.
