### ISSUE TITLE
create a Team controller 

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1491]
it would be nice to have a controller which manages installing/upgrading of Teams. e.g. if an admin user runs:

`jx create team myname`

Then it should trigger the controller to provision a new team (namespaces, install of Jenkins X, environments etc).

We could use a git repository to store template files, such as default `Environment` objects, `Role` resources and `EnvRoleBinding` resources to be used for the team. We can also add extra stuff like:

* `myvalues.yaml` file used for [configuring the shared nexus etc](https://jenkins-x.io/getting-started/config/)
* additonal CLI arguments used to run the underlying `jx install` command like `--docker-registry` etc

**Comment by amenick** [comment]
Hi everyone,
as my understanding is that Team Controller isn't in place yet... what's the best way for creating and installing a new team?
I mean, am I supposed to firstly create a new team by means of
`jx create team mynewteam`
then I should switch from the default jx team to the new one, via
`jx team mynewteam`
and then I must execute in a specific folder, which contains the well-known `myvalues.yaml` (mentioned here https://jenkins-x.io/getting-started/config/ ) the installation
`jx install [all my args]`

Lastly, if my understanding is correct, by specifing the proper links to nexus, chartmuseum that point to jx namespace (that is the default team), I can set up everything the new team needs (e.g. its environments), reusing the same repositories (nexus, chartmuseum and image registry) but with dedicated jenkins.

**Comment by ccojocar** [comment]
I am going to close this in favour of https://github.com/jenkins-x/jx/issues/6453, which propose a revamp of the user management in Jenkins X, which follows more standardised practices.
