### ISSUE TITLE
MongoDB fails to start on GKE

### ISSUE THREAD

**Issue by cpoenisch** [jenkins-x/jx#1505]
### Summary 

After cluster creation on GKE and invoking JX installation the MongoDB pod does not start properly.

### Steps to reproduce the behavior

- Create cluster and install JX on GKE: ```jx create cluster gke --skip-login```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.175
jenkins x platform 0.0.2191
kubernetes cluster v1.9.7-gke.5
kubectl            v1.9.7
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.11.0
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE: ```jx create cluster gke --skip-login```

### Operating system / Environment

GCP Cloud Console

### Expected behavior

JX installation completes and all services/pods are up and running.

### Actual behavior

jenkins-x-mongodb crashes repeatedly and does not come up.

Error message:
CrashLoopBackOff: Container 'jenkins-x-mongodb' keeps crashing. 
Error with exit code 2: jenkins-x-mongodb: docker.io/bitnami/mongodb:3.6.6-debian-9 

```
I  nami    INFO  Initializing mongodb
 
I  mongodb INFO  ==> Deploying MongoDB with persisted data...
 
I  mongodb INFO  ==> No injected configuration files found. Creating default config files...
 
I  mongodb INFO 
 
I  mongodb INFO  ########################################################################
 
I  mongodb INFO   Installation parameters for mongodb:
 
I  mongodb INFO     Persisted data and properties have been restored.
 
I  mongodb INFO     Any input specified will not take effect.
 
I  mongodb INFO   This installation requires no credentials.
 
I  mongodb INFO  ########################################################################
 
I  mongodb INFO 
 
I  nami    INFO  mongodb successfully initialized
 
E  [0m[38;5;2mINFO [0m ==> Starting mongodb... 
 
E  [0m[38;5;2mINFO [0m ==> Starting mongod...
 
E  Expected boolean switch but found string:  for option: net.ipv6
 
E  try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

**Comment by ccojocar** [comment]
This should be fixed. Bitnami released a new docker image witch should work.
