### ISSUE TITLE
jx install messed up users

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#1516]
### Summary 

I am doing jx install into an existing GKE cluster.  I have two git users and I want to do this installation just for one of them.

### Steps to reproduce the behavior
have two GitHub users that you used in the past configured

```
salaboys-MacBook-Pro:updatebot salaboy$ jx install
? Cloud Provider gke
Git configured for user: salaboy and email salaboy@gmail.com

```

Then I get the question:
```
? GitHub username for CI/CD pipelines: salaboy
Cloning the Jenkins X cloud environments repo to /Users/salaboy/.jx/cloud-environments

```

Then when creating the environments I can't choose where to create them.. it just pick the other user without asking:

```
Creating default staging and production environments
Using git provider GitHub at https://github.com


About to create repository environment-ridgegentle-staging on server https://github.com with user jx-activiti-cloud

Creating repository jx-activiti-cloud/environment-ridgegentle-staging

```

The expected output should be to ask for which user to use for the environments or just use the one selected in the first step. 

### Jx version

The output of `jx version` is:

```
salaboys-MacBook-Pro:updatebot salaboy$ jx version
Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: incompatible versions client[v2.10.0-rc.2] server[v2.10.0]': exit status 1
NAME               VERSION
jx                 1.3.183
kubernetes cluster v1.9.7-gke.5
kubectl            v1.11.1
helm client        v2.10.0-rc.2+g5615410
helm server        v2.10.0+g9ad53aa
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GKE

### Operating system / Environment

GKE

**Comment by i0n** [comment]
Hey there. What do you have in your ~/.jx/gitAuth.yaml? (Redact the actual API tokens)
Could you try with the very latest version of jx please?

**Comment by ryandawsonuk** [comment]
I'm in the same team as @salaboy and have been trying to do the same thing. I'd raised a separate issue (https://github.com/jenkins-x/jx/issues/1731) as I thought I was having a `jx import` issue but actually I believe this is just the same `jx install` issue. I'm experiencing this on the latest jx version

**Comment by ccojocar** [comment]
The install command was refactored to configure separately the local and the pipeline git users. Closing this issue for now. Please open another issue if you see the problem occurring again.
