### ISSUE TITLE
Create Spring Cloud Gateway + Prometheus quickstart

### ISSUE THREAD

**Issue by hekonsek** [jenkins-x/jx#1521]
Hi,

I've created a companion quickstart for the spring-boot-rest-prometheus [1]. It is Spring Cloud Gateway [2] with Prometheus support. We are using gateway as a ingress entry point and then route traffic into internal services from it - such quickstart would be really helpful to provide template for this kind of applications. And Prometheus, because you know, Promethus ;) - you have to make your application observable. 

You can find the quickstart here [3]. If you happen to find it useful and add it to quickstarts, please be so kind and add me as a maintainer of the repository so I can keep it up to date.

Cheers!  

[1] https://github.com/jenkins-x-quickstarts/spring-boot-rest-prometheus
[2] https://cloud.spring.io/spring-cloud-gateway
[3] https://github.com/hekonsek/spring-cloud-gateway-prometheus

**Comment by hekonsek** [comment]
Hi guys. Any updates on this?

**Comment by binoydev** [comment]
@hekonsek  Will this work with [spring-cloud-kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes)  ie. a spring cloud/boot app deployed in kubernetes as a service is auto discover-able from spring-cloud gateway
