### ISSUE TITLE
'jx upgrade platform' throws an error using myvalues.yaml

### ISSUE THREAD

**Issue by riqbal-rocketlawyer** [jenkins-x/jx#1523]
### Summary 
I created local override myvalues.yml which works fine when I run `jx install` but I am getting error when I run `jx upgrade platform` using same local override

Log output
```~/jenkins » jx upgrade platform                                                                                                                       2.4.0
Cloning the Jenkins X cloud environments repo to /Users/rameez/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Cloning the Jenkins X cloud environments repo to /Users/rameez/.jx/cloud-environments
Counting objects: 825, done.
Total 825 (delta 0), reused 0 (delta 0), pack-reused 825
Upgrading to version 0.0.2191
Using local value overrides file /Users/rameez/jenkins/myvalues.yaml
error: failed to run 'helm upgrade --namespace  --values /Users/rameez/jenkins/myvalues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '', output: 'Error: found in requirements.yaml, but missing in charts/ directory: jenkins, exposecontroller, exposecontroller, pipelinecontroller, chartmuseum, nexus, heapster, monocular, docker-registry, jx, jx': exit status 1
```
### Steps to reproduce the behavior
Create an override values file like this
```
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: "quay.io"
PipelineSecrets:
  # used by pipelines to tag new releases
  DockerConfig: |-
      {
          "auths": {
            "quay.io": {
              "auth": "xxxx",
              "email": ""
            }
          }
      }
```
jx install --provider=gke
jx upgrade platform
### Jx version

The output of `jx version` is:

```
jx                 1.3.185
jenkins x platform 0.0.2191
kubernetes cluster v1.9.7-gke.5
kubectl            v1.9.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE. Created using google console.

### Expected behavior
Should be able to upgrade jx
### Actual behavior
Upgrade fails with an error

**Comment by jjouanno** [comment]
HI, 

I have same behavior but with a timeout:

> error: failed to run 'helm upgrade --namespace  --values /home/jonathan_jouanno/.jx/myvalues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '', output: 'Error: UPGRADE FAILED: timed out waiting for the condition': exit status 1

I am on GKE:

> NAME               VERSION
jx                 1.3.200
jenkins x platform 0.0.2267
kubernetes cluster v1.9.7-gke.6
kubectl            v1.9.7
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.11.0

I need to delete expose job after that due to another relative bug

> kubectl delete job expose

For restarting installation I launch "jx install" but this command don't use all parameters (like admin password) but use seem use myvalues.yaml.

So how to upgrade platform with my personnal jenkins image container that I have configured in myvalues.yaml?

Thanks

**Comment by ccojocar** [comment]
@riqbal-rocketlawyer I am going to close this issue. The upgrade platform has improved. Please try the latest version and open another issue if you still have this issue. Thanks
