### ISSUE TITLE
Need imagePullPolicy set to "IfNotPresent" when running compliance

### ISSUE THREAD

**Issue by beebird** [jenkins-x/jx#1530]
Currently, the pods created by ``jx compliance run`` are using ``imagePullPolicy: Always``, and there's no option to set an alternative mirror registry. I wonder if we can change the policy to "IfNotPresent" ?

The background situation is the access to gcr.io is blocked in China... I can manage to download the required images manually and re-tag them, but it's almost impossible to pull them directly from my nodes.

**Comment by ccojocar** [comment]
We want to keep the `Always`, in order to make sure that the latest image version is always pulled. Maybe the solution is to mirrored the compliance docker image in a registry which you can access. 

Closing this issue for now.
