### ISSUE TITLE
unable to integrating gitea with jenkins-x

### ISSUE THREAD

**Issue by sreekanthreddyggk** [jenkins-x/jx#1536]
### Summary 
I have created cluster with GKE and unable to integrate with gitea, i have installed gitea in another vm.
### Jx version
1.3.X
The output of `jx version` is:
jx                 1.3.191
jenkins x platform 0.0.2252
kubernetes cluster v1.9.7-gke.6
```
COPY OUTPUT HERE
```
Creating repository gitea/environment-antfog-staging
Creating git repository gitea/environment-antfog-staging
error: failed to create staging environment: Failed to create repository gitea/environment-antfog-staging due to: Post http://35.231.59.10:3000/api/v1/user/repos: dial tcp 35.231.59.10:3000: i/o timeout

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

created cluster in google console with kubernetes engine

### Operating system / Environment
linux

**Comment by jstrachan** [comment]
this is a known issue am afraid; hoping we can get it sorted soon though https://github.com/jenkins-x/jx/issues/432#issuecomment-397531961

**Comment by ccojocar** [comment]
dup of #432
