### ISSUE TITLE
bug: jx step changelog does not include all commits between release tags

### ISSUE THREAD

**Issue by igdianov** [jenkins-x/jx#1543]
### Summary 
The `jx step changelog --version v1.0.6` command generates release notes that contain only latest release commit tag and single commit before it. All other commits from previous release tag are missing from release notes in Gihub. See https://github.com/igdianov/changelog/releases/tag/v1.0.6 for example. 

The best way that I found so far to get a list of all direct commits on the release branch from history that excludes any commits on pull request branches is `git rev-list --tags --first-parent --grep ^Release` options:
```sh
export REV=$(git rev-list --tags --max-count=1 --grep ^Release)
export PREVIOUS_REV=$(git rev-list --tags --max-count=1 --skip=1 --grep ^Release)
export REV_TAG=`git describe $REV`
export PREVIOUS_REV_TAG=`git describe $PREVIOUS_REV`
echo Found commits between $PREVIOUS_REV_TAG[$PREVIOUS_REV] and $REV_TAG[$REV] tags:
git rev-list $PREVIOUS_REV..$REV --first-parent --pretty
```

Alternatively, `git tag` command can be used to grab latest pair of release tags, convert them into hash with `git show-ref --hash` for `git rev-list` command:

```sh
export REV_TAG=$(git tag | sort -V | tail -1)
export REV=`git show-ref $REV_TAG --hash`
export PREVIOUS_REV_TAG=$(git tag | sort -V | tail -2 | head -1)
export PREVIOUS_REV=`git show-ref $PREVIOUS_REV_TAG --hash`
echo Found commits between $PREVIOUS_REV_TAG[$PREVIOUS_REV] and $REV_TAG[$REV] tags:
git rev-list $PREVIOUS_REV_TAG..$REV_TAG --first-parent --pretty

```

and then use the release tag hashes to generate changelog with additional arguments:

```sh
jx step changelog --version v$REV_TAG --generate-yaml=false --rev=$REV --previous-rev=$PREVIOUS_REV
```
### Steps to reproduce the behavior
Fork & clone https://github.com/igdianov/changelog

Use GNU Make to generate commit history with provided Makefile in the root for the example:
```bash
make checkout 
make commit/fix Update1x
make commit/fix Update2x
make commit/fix Update3x
make version 
make tag 
make changelog
```
The commit history in Git repository is as follows:

![image](https://user-images.githubusercontent.com/20428629/44696015-99c56900-aa2a-11e8-83dd-b26f078a5334.png)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.191
jenkins x platform 0.0.2261
kubernetes cluster v1.10.6-gke.1
kubectl            v1.10.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0.windows.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
N/A

### Operating system / Environment
Windows 10 / Git Bash

### Expected behavior
All commits between tags 1.0.5 and 1.0.6 should appear in the release notes:

![image](https://user-images.githubusercontent.com/20428629/44692452-ce7bf500-aa17-11e8-9e85-325d9900eed8.png)

### Actual behavior
Only `Release 1.0.6` and `fix: Commit Update3` are listed in the generated changelog:

![image](https://user-images.githubusercontent.com/20428629/44692274-06366d00-aa17-11e8-89c6-89de6fb3a063.png)

**Comment by jtnord** [comment]
Additionally on the jx repo - it does include all the commits between tags - but alas it seems to be 2 tags behind the last release.  e.g. https://github.com/jenkins-x/jx/releases/tag/v1.3.743 shows https://github.com/jenkins-x/jx/commit/3d6050e4ac51ca27671dd4d5a40f6a9a0c4a0a95 but that was merged and in 1.3.741
