### ISSUE TITLE
On-Premise Unexpected Message from Helm "Error: a release named jxing already exists"

### ISSUE THREAD

**Issue by meltingturret** [jenkins-x/jx#1544]
### Summary 
Running jx install against on-premise cluster, jx noticed that we did not have controller installed so we said yes please install controller for us, checking we can see deployment was ok.

```
kube-system       jxing-nginx-ingress-controller-7b7bdc8977-g4gg9       1/1       Running   0          2m        10.46.0.2       XXX.com   <none>
kube-system       jxing-nginx-ingress-default-backend-7f5c759f7-k8fnk   1/1       Running   0          2m        10.40.0.2       XXX.com   <none>
```

Then there is a wait and we see message:

```
Tiller Deployment is running in namespace kube-system
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true' command in directory '', output: 'Error: a release named jxing already exists.
Run: helm ls --all jxing; to check the status of the release
Or run: helm del --purge jxing; to delete it': exit status 1
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: 10.230.46.122
```
It appears that helm is called to install the ingress chart after it was installed using some other mechanism as the pods are already running. Checking we have:

```
$ helm list
NAME    REVISION        UPDATED                         STATUS  CHART                   APP VERSION     NAMESPACE
jxing   1               Tue Aug 28 08:22:55 2018        FAILED  nginx-ingress-0.25.1    0.17.1          kube-system
```

### Steps to reproduce the behavior

jx install --provider=kubernetes --on-premise --external-ip 10.230.46.122

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.191
kubernetes cluster v1.11.2
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 1.8.3.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Simple installation on RedHat 7.5 Enterprise.

### Operating system / Environment

Red Hat Enterprise Linux Server release 7.5 (Maipo)

### Expected behavior

Ingress controller should install and bind to provided external IP address.

### Actual behavior

Left over helm release in error

**Comment by mobara67** [comment]
Any update on fixing this issue? I am encountering same issue installing jx on-prem using RedHat 7.5.

**Comment by rawlingsj** [comment]
Sorry for the slow response, we're juggling quite a few things during the build up of Jenkins World in two weeks. 

I just took a quick look at the code which TBH does look a bit odd, I'm not quite sure why there's a loop around this.  I wonder if you have any time if you fancied digging deeper and seeing if there's an easy fix? https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/init.go#L536-L554

It should be relatively simple to recreate and retry the `jx install` with some extra logging to see what's going on, here's some docs on building `jx` https://github.com/jenkins-x/jx/blob/master/docs/contributing/hacking.md#hacking-on-jx.  

If you need any help we hang out in the Kubernetes slack team in Jenkins X channels https://jenkins-x.io/community/

**Comment by ccojocar** [comment]
@meltingturret You can delete the exiting jxing release. `helm delete --purge jxing` and run again the install. 

I am going to close this issue. Please feel free to open another issue if you are still seeing this problem occurring. Thanks
