### ISSUE TITLE
Jenkins-X builder pod Docker host security and resource isolation problems

### ISSUE THREAD

**Issue by igdianov** [jenkins-x/jx#1563]
### Summary 
We have been adopting and using JenkinsX CI/CD in Kubernetes for Activiti Cloud OSS project: https://www.activiti.org/.  Our pipelines use Docker client provided in Jenkins X builder to run CI tests by creating and running Docker containers from inside Builder Maven container, and to build and publish Docker images with Skaffold to Docker registry outside cluster.

The main problem we have discovered is that Jenkins Kubernetes Plugin build pod template uses Docker-out-of-Docker (DooD) setup with VM host Docker daemon accessible via /var/run/docker.sock. It makes all VM host K8s runtime containers guts with shared Docker graph storage fully exposed and unsecured from inside builder containers.

### Steps to reproduce the behavior

When Skaffold builds images from many concurrent pipelines, it will use and add Docker image layers to the shared storage graph of the host Docker daemon.  There is no GC to clean up after Skaffold builds as far as I understand, which causes the VM host run out of disk storage very quickly under normal use. 

GKE VM also uses Docker 17.x as part of container optimized OS which has problems supporting running multi-stage builds. It is not possible to upgrade Docker run-time inside managed Kubernetes OS image to be able support multi-stage Docker builds for micro-services. I know you are working to integrate Kaniko to solve this problem eventually.

During CI tests,  when Docker commands are sent to the host Docker daemon, Kubernetes does not know anything about this newly created container and does nothing to manage it. If a named container is created using Docker commands, container creation might fail if the named container already exists. Also, since the new container does not know anything about Pod networking, any open ports will not be reachable using the Pod's IP.  The port mapping specification on the Docker command (e.g. docker run -v 8080:80 httpd:latest) will open ports on the host, a limited and contended resource. When the container terminates, the layers of graph storage will not be deleted by Kubernetes and logs will not be cleaned up by Kubernetes. 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.191
jenkins x platform 0.0.2261
kubernetes cluster v1.10.6-gke.1
kubectl            v1.10.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0.windows.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE Kubernetes Cluster 1.10.6-gke.1

### Operating system / Environment

GKE Container-Optimized OS (cos)

### Expected behavior

* Docker daemon on VM host is fully secured and isolated from Jenkins X builder pods. 
* Concurrent Jenkins X pipeline Docker builds and CI tests are fully isolated from each other.
* CI Docker containers are deleted by Kubernetes when Pod is deleted
* CI Docker containers are accessible by CI tests via http://localhost:port inside builder container.
* Docker graph storage space is reclaimed by Kubernetes when Pod is deleted

### Actual behavior

* Kubernetes Security - VM host Docker daemon is fully exposed from inside builder container.
* Pod Networking - Cannot access the CI container using Pod IP.
* Pod Lifecycle - On Pod termination, the CI container will keep running especially if the container was started with -d flag.
* Pod Cleanup - Graph storage will not be cleanup after pod terminates.
* Scheduling and Resource Utilization - Cpu and Memory requested by Pod, will only be for the Pod and not the container spawned from the Pod. Also, limits on CPU and memory set for the Pod will not be inherited by the spawned container.

### Next Steps

The major problem that needs to be addressed is full isolation of the concurrent build pipeline runs from each other and securing K8s Docker daemon access from inside the builder pod.

I would like to start a conversation and collaborate to help solve these problems in Jenkins X.

**Comment by Salaboy** [comment]
More than happy to collaborate, to understand and to solve the problems described in this issue.

**Comment by jstrachan** [comment]
We are hoping to move to kaniko to avoid using the docker daemon at all.

I don’t yet grok why there is a need to run docker commands in CI though - maybe you need a DinD build pod for that?

**Comment by rawlingsj** [comment]
Here's a couple of links on kanico that's I've had bookmarked but not tried yet.  If you wanted to experiment with kanico it doesn't look too hard https://medium.com/@sebgoa/building-docker-images-with-kaniko-6e2421b018 and when we use knative a build spec (coming soon) could use something like the pod spec here https://cloudplatform.googleblog.com/2018/04/introducing-kaniko-Build-container-images-in-Kubernetes-and-Google-Container-Builder-even-without-root-access.html

**Comment by paveq** [comment]
Note sure how relevant these points are today, but this kind of DinD is adviced against here: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

I've concerned is that DinD would still require builder pod to run with "privileged" flag, causing possible security and isolation issues. As I understand, Kaniko would not require this.

**Comment by igdianov** [comment]
@paveq Thank you for feedback. This article is quite old and does not consider running sidecar DinD container inside Kubernetes Pod context. 

In fact, having option of DinD container running inside Jenkins build pod, will isolate VM's Docker, CPU and memory resources from pipelines. DinD setup will also use and apply pod resource limits constraints to schedule Jenkins agents  based on available cluster resources. 

Kaniko will solve only Docker build isolation problem between concurrent pipelines. Also, Kaniko is not using native Docker for building images.

With so many use cases, the users should be able to customize how they want to use Docker to build, run CI tests, and publish Docker image from Jenkins pipeline.

**Comment by igdianov** [comment]
@jstrachan @rawlingsj What do you think about this customization?  I also curious what is the purpose of generating pod templates yaml in jenkins-x-pod-templates ConfigMap? It does not seem to be having any effect on Jenkins XML pod templates ConfigMap:

```yaml
# Source: jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "jenkins-x-pod-templates"
data:
  dlang: |-
....
```

I will appreciate your feedback....

**Comment by davidcurrie** [comment]
If security wasn't a good enough reason for moving away from mounting the Docker socket, here's another one: it's no longer possible to run Jenkins-X on the Kubernetes 1.11 version of the IBM Kubernetes Service as it has switch to use containerd rather than Docker!

**Comment by amoussawi** [comment]
Any update here? 
@igdianov has pointed out some real issues with mounting the host docker daemon, that I think some users won't notice, me included until I ran `docker run -d`. 
Is there any specific reason why a DooD approach is used instead of a DinD sidecar approach, if it was already possible?
