### ISSUE TITLE
jx import from gitea is not working by default it is taking from github

### ISSUE THREAD

**Issue by phanisowjanyavutukuri** [jenkins-x/jx#1566]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by jstrachan** [comment]
see https://github.com/jenkins-x/jx/issues/432#issuecomment-397531961

**Comment by ccojocar** [comment]
dup of #432
