### ISSUE TITLE
jx create spring -d web -d actuator fails to init the git repo and complete

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#157]
If I run the command in the subject, I get: 

```
Error: could not load /Users/michaelneale/.draft/packs/github.com/jenkins-x/draft-repo/packs/java: lstat /Users/michaelneale/.draft/packs/github.com/jenkins-x/draft-repo/packs/java/charts/: no such file or directory
WARNING: Failed to run draft create in /Users/michaelneale/projects/paas/jenkins-x/gke-playing/demo due to exit status 1fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by jstrachan** [comment]
@michaelneale is this still an issue? wonder if it was fixed with install/create cluster running the initialise to setup draft?

**Comment by michaelneale** [comment]
nope - closing it. thanks for looking. I am trying to close old ones as I find them.

**Comment by talk2jk** [comment]
I'm running into the same problem. What was the solution, @michaelneale ?

**Comment by jstrachan** [comment]
@talk2jk I wonder if its related to the version of git you are using? Wonder what the output of this gives:
```
jx version
```
Would be good to see the output of your `jx create spring` shell too

**Comment by talk2jk** [comment]
@jstrachan please fin the  j`x version`  
`
NAME        VERSION
jx          1.1.10
Jenkins X   0.0.393
Kubernetes  v1.8.8-gke.0
Helm Client v2.6.2+gbe3ae4e
Helm Server v2.6.2+gbe3ae4e
Git         git version 2.13.0
`
And `jx create spring`:
`
~/D/V/p/b/backend-services ❯❯❯ jx create spring -d web -d actuator
? Language: java
? Group: com.example
? Artifact: demo
Created spring boot project at /Users/jannyK/DEV/VipiCash/projects/backend/backend-services/demo
The directory /Users/jannyK/DEV/VipiCash/projects/backend/backend-services/demo is not yet using git
? Would you like to initialise git now? Yes
Reinitialized existing Git repository in /Users/jannyK/DEV/VipiCash/projects/backend/backend-services/demo/.git/
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   pom.xml
	new file:   src/main/java/com/example/demo/DemoApplication.java
	new file:   src/test/java/com/example/demo/DemoApplicationTests.java

? Commit message:  Initial import
[master a9a5711] Initial import
 3 files changed, 28 insertions(+), 23 deletions(-)
 create mode 100644 src/main/java/com/example/demo/DemoApplication.java
 create mode 100644 src/test/java/com/example/demo/DemoApplicationTests.java

Git repository created
error: could not load /Users/jannyK/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/java: error reading /Users/jannyK/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/java: open /Users/jannyK/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/java: no such file or directory
`

**Comment by jstrachan** [comment]
@talk2jk ah - I think you've just got an old jx - if you upgrade it should work

**Comment by jstrachan** [comment]
see https://github.com/jenkins-x/jx/releases - e.g. `brew upgrade jx` or download a new binary etc
