### ISSUE TITLE
jx batch-mode fails 

### ISSUE THREAD

**Issue by colltie** [jenkins-x/jx#1571]
### Summary 
The run fails with the following error. I don't know what else can be done here.
Note: This can be manually bypassed.

### Steps to reproduce the behavior
jx install \
       --batch-mode \
       --default-admin-password xxxxxxxx \
       --tls-acme true \
       --provider gke \
       --headless \
       --git-provider-url https://github.com \
       --git-username xxxx \
       --git-api-token xxxxxxxx

###output
unable to automatically find API token with chromedp using URL https://jenkins.jx.xx.xxx.xxx.xx.nip.io/me/configure
error: failed to get the Jenkins API token: after 3 attempts, last error: Running in batch mode and no default api token found

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 1.3.204
kubernetes cluster v1.10.6-gke.2
kubectl            v1.9.7
helm client        v2.6.2+gbe3ae4e
helm server        v2.10.0+g9ad53aa
git                git version 2.11.0

**Comment by Riduidel** [comment]
Was fed up with that proxy problem, so I spawned a VM on GCE to administer my cluster.

**Comment by colltie** [comment]
My cluster is running on GCE and i'm still facing the same issue.

**Comment by iharrington** [comment]
Having similar issue trying to automate build using Ansible +  AKS @colltie are you still having issues or did you find a solution?

**Comment by ccojocar** [comment]
@colltie jx in batch mode should work now with GKE cluster. I am going to close this issue. Thanks
