### ISSUE TITLE
Add quickstart to show watching a pipeline activity

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1573]
Please add this github quickstart: https://github.com/pmuir/node-http-watch-pipeline-activity

**Comment by rawlingsj** [comment]
I've invited you to the jenkins-x-quickstarts org so you should be able to transfer the repo.  Then it should automatically be picked up via `jx create quickstart`

**Comment by pmuir** [comment]
ok

**Comment by pmuir** [comment]
Added
