### ISSUE TITLE
jx rsh doesn't seem to accept --environment

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1575]
### Steps to reproduce the behavior

jx --environment staging rsh

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.207
jenkins x platform 0.0.2267
kubernetes cluster v1.9.7-gke.6
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```

### Kubernetes cluster

GKE via jx install

### Operating system / Environment

Mac OS X

### Expected behavior

I can use --environment. Furthermore -e short option is in use already for --execute

**Comment by johnmcollier** [comment]
I can tackle this one, have a PR that should be ready soon-ish.
