### ISSUE TITLE
Problem while pushing Docker images to ECR and creating cluster ressources when running watch.sh in a devpod

### ISSUE THREAD

**Issue by Rude-Monkey** [jenkins-x/jx#1629]
### Summary 

I was following the instructions ([here](https://jenkins-x.io/developing/devpods/ "Jenkins X CLI documentation")) to synchronize the code on my machine with the code running inside a pod on my cluster but I came accross a few errors: 

First, when I ran `jx sync` I got told to run `ksync init` first.

After I did so, running the watch.sh script inside the devpod showed some errors regarding ingress and service creation for the project being deployed via the devpod. 

- no service gets created with my deployment, resulting in the following warning appearing in my devpod's terminal: `WARN[0004] error adding label to runtime object: patching resource /golang-http: services "golang-http" not found`

- typing `kubectl get ingress golang-http-golang-http` as told in the devpod's terminal shows that no ressources called "golang-http-golang-http" exist: 
```
kubectl get ingress golang-http-golang-http
No resources found.
Error from server (NotFound): ingresses.extensions "golang-http-golang-http" not found
```
Also, Reflex seems to be missing in my devpod.

Moreover, by looking on my Kubernetes dashboard, I noticed there was an error with my deployment: 

```
Failed to apply default image tag "301517625970.dkr.ecr.eu-west-3.amazonaws.com/rude-monkey/golang-http:": couldn't parse image reference "301517625970.dkr.ecr.eu-west-3.amazonaws.com/rude-monkey/golang-http:": invalid reference format
Error: InvalidImageName
```

### Steps to reproduce the behavior

As stated [here](https://jenkins-x.io/developing/devpods/ "Jenkins X CLI documentation"), run the following commands: 

First run this in one terminal
```
 jx sync
```
Then cd into your project dir, and run 
```
jx create devpod --reuse --sync
```
Once in the DevPod run 
```
./watch.sh
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.235
jenkins x platform 0.0.2328
kubernetes cluster v1.9.6
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 1.8.3.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

AWS cluster built using kops version 1.10.0
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

Docker container running CentOS 7.
+ Kubernetes cluster, each node running the default AMI used by the Kops project

### Expected behavior

watch.sh script builds a Docker image then lets Helm deploy it and expose it.

### Actual behavior

The image gets built but can't be pushed on/pulled from ECR + neither an ingress or a service get created to expose the app.

**Comment by Rude-Monkey** [comment]
I forgot to mention, but reflex also seems to be missing in the devpod.

**Comment by ccojocar** [comment]
dup of #3161
