### ISSUE TITLE
 confimap  exposecontroller does not created during `jx platform upgrade` if myvalues.yaml file exists

### ISSUE THREAD

**Issue by almerico** [jenkins-x/jx#1636]
### Summary 
 confimap  exposecontroller does not created during `jx platform upgrade` if myvalues.yaml file exists
### Steps to reproduce the behavior
```
jx install
jx upgrade
with myvalues.yaml
```
### Jx version

The output of `jx version` is:

```
jx                 1.3.241
jenkins x platform 0.0.2328
kubernetes cluster v1.10.6-gke.2
kubectl            v1.10.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.15.2 (Apple Git-101.1)```

### Kubernetes cluster

```jx install --provider gke```

### Operating system / Environment
macosx
### Expected behavior
```jx upgrade```  finished successfully
### Actual behavior
Expose controller crush prevents jx upgrade from succeed 
![screen shot 2018-09-11 at 10 06 12 am](https://user-images.githubusercontent.com/2116248/45343759-7b26ac80-b5aa-11e8-9a4d-8c8c44b7f126.png)
```
$ kubectl logs expose-z2d4j
I0910 17:51:58.705047       1 exposecontroller.go:60] Using build: '2.3.71'
I0910 17:51:58.728340       1 config.go:22] No /etc/exposecontroller/config.yml file found.  Will try to figure out defaults
W0910 17:51:58.728437       1 exposecontroller.go:81] %!s(<nil>)
W0910 17:51:58.731095       1 exposecontroller.go:98] Could not find ConfigMap exposecontroller in namespace jx
I0910 17:51:58.731267       1 exposecontroller.go:103] Config file before overrides exposer: ""
path-mode: ""
apiserver-protocol: ""
watch-namespaces: ""
watch-current-namespace: false
http: false
tls-acme: false
I0910 17:51:58.731324       1 exposecontroller.go:133] Config file after overrides exposer: ""
path-mode: ""
apiserver-protocol: ""
watch-namespaces: ""
watch-current-namespace: true
http: false
tls-acme: false
I0910 17:51:58.731343       1 exposecontroller.go:177] Running in : `jx`
I0910 17:51:58.731461       1 controller.go:78] NewController false
I0910 17:51:58.733734       1 auto.go:32] Using exposer strategy: ingress
F0910 17:51:58.736481       1 exposecontroller.go:180] failed to create new strategy: failed to create auto expose strategy: failed to get a domain: failed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope: Unknown user "system:serviceaccount:jx:expose"

```
related to #1620

**Comment by ccojocar** [comment]
@almerico Is this still the case? Thanks

**Comment by almerico** [comment]
@ccojocar don’t see it lately

**Comment by ccojocar** [comment]
@almerico Thanks! I am going to close it.
