### ISSUE TITLE
Add westeurope in supported Azure region with "jx create cluster aks"

### ISSUE THREAD

**Issue by tgarlot** [jenkins-x/jx#1640]
### Summary 
Azure West Europe data center is not proposed in the list of available location
Probably because it is missing in https://github.com/jenkins-x/jx/blob/master/pkg/cloud/aks/helper.go

### Steps to reproduce the behavior
Launch the command "jx create cluster aks". 
westeurope is not proposed

### Jx version

The output of `jx version` is:

```
NAME VERSION
jx   1.3.241
```

Happy to PR this one.

**Comment by jstrachan** [comment]
@tgarlot ooh a PR would be lovely thanks!

**Comment by tgarlot** [comment]
According to this page https://docs.microsoft.com/en-us/azure/aks/container-service-quotas, AKS is clearly not available in all regions. Should I align the current list with the one published by Microsoft (and so not only add westeurope but also remove others) ? Not sure if creating a cluster in westindia would work as it does not seems to be available there...

**Comment by tgarlot** [comment]
Confirmed via az cli: 
The provided location 'westindia' is not available for resource type 'Microsoft.ContainerService/managedClusters'. List of available regions for the resourcetype is 'eastus,westeurope,centralus,canadacentral,canadaeast,uksouth,westus,westus2,australiaeast,northeurope,japaneast,eastus2,southeastasia'.

Propose to align the regions on the one listed just above then.

**Comment by tgarlot** [comment]
not sure if it will be closed automatically so closing as PR was merged
