### ISSUE TITLE
imagePullSecrets for Pod Template

### ISSUE THREAD

**Issue by beebird** [jenkins-x/jx#1642]
### Jx version

The output of `jx version` is:

```
jx                 1.3.245
jenkins x platform 0.0.2267
kubernetes cluster v1.10.1
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.8.0
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

* env-kubernetes

### Operating system / Environment

* CentOS 7.4

### Expected behavior

* Pull the new app image and run the container

### Actual behavior
* ImagePullBackOff with error: no basic auth credentials
```
Failed to pull image"xxxx/python-http:0.0.16": rpc error: code = Unknown desc = Error response from daemon: Get xxxx/python-http/manifests/0.0.16: no basic auth credentials
```
More detail:

I'm using a private docker registry with authentication (not the jenkins-x-docker-registry-* one). At the beginning pipeline was even unable to push new built images to the registry during the build because of the auth issue. After I manually create a secret ``kubectl create secret generic jenkins-docker-cfg --from-file=~/.docker/config.json -n jx``, the image built can be pushed.

But the new image still cannot be deployed because of this error, and I didn't see any imagePullSecrets setting in the pod template.

I also tried ``jx create docker auth`` but seemed no luck.

I don't know if it's an issue, or can someone tell me the correct way to set the docker credential? Thanks!

**Comment by beebird** [comment]
BTW, I also create a pull request https://github.com/jenkins-x/jx/pull/1645 .

```diff
-       cmd.Flags().StringVarP(&options.Secret, "email", "e", "", "The email to associate auth component of config.json")
+       cmd.Flags().StringVarP(&options.Email, "email", "e", "", "The email to associate auth component of config.json")
```

**Comment by yuwzho** [comment]
I am also suffer from this problem. The `jx create docker auth` command just updates the docker auth in `jx` namespace, where hosts a Jenkins image. But in the production/staging namespace, there is no such docker secret, and the kubernetes deployment yaml file doesn't specify the `imagePullSecrets` and regards the image is host in a public registry as default.

So I just wonder is there a way to specify the `imagePullSecrets` in the k8s yaml, and apply the corresponding docker  secret to the production/staging namespace?

**Comment by yuwzho** [comment]
I make it work with staging environment by adding 
```yaml
imagePullSecrets:
- name: docker-cfg
```
in the code repo's `charts/demo/templates/deployment.yaml`, and create the docker-cfg in the jx-production/jx-staging namespaces in the kubernetes. Still don't know how to solve this for the dynamic created pr namespace. And wonder if there is a standard way to solve this.

**Comment by jakelima18** [comment]
I have the same issue

**Comment by beebird** [comment]
I guess I've figured it out.

In ``Build Release`` stage, all image building and pushing jobs are running in **jx** namespace, where there's a secret ``jenkins-docker-cfg`` (mount as ~/.docker/config.json on builder container), so we need to configure this secret.

In ``Promote to Environment`` stage, however, the image pulling jobs are running in **staging** or **production** namespaces, where no docker credential is configured.

solution from @yuwzho works,  and if you don't want to manually update your yaml file, here's what I did:
```bash
# suppose your docker credential file is  ~/.docker/config.json
scp ~/.docker/config.json  root@<ip of each node>:/var/lib/kubelet/config.json
```
From kubernetes document, kubectl will try to read ``config.json`` from a search paths list, and if you put the file at ``~/.docker/config.json`` then you might need to set ``HOME=/root`` explicitly in your environment file for kubelet

More detail at [https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry)

**Comment by ccojocar** [comment]
Thanks for workaround. I am going to close this issue.

**Comment by tryggth** [comment]
Actually, this is sort of a problem. The permissions on the secret need to be read-only. Not to mention, not everyone can put arbitrary stuff on the build nodes.

**Comment by aweis89** [comment]
@ccojocar can we possibly reopen this issue? Ideally jx would copy the imagePullSecret in the jx namespace and add it to dynamic namespaces (for both preview environments and devpods). Would also be nice if we could add the imagePullSecret to the namespaces default service account.

Manually uploading secrets to instances seem more like a hack than an ideal solution, specially considering the often dynamic nature of instances in k8s.

**Comment by vvanouytsel** [comment]
I am running into the same issue.
Could we not copy the necessary secrets from the `jx` namespace, to the dynamic namespaces?

**Comment by adrianiacob22** [comment]
I am having the same issue and since my Kubernetes cluster is running in cloud (IKS) I don't have access to nodes so I cannot do the proposed workaround above. 
Is there any way to reopen this item?

**Comment by hervelemeur** [comment]
@adrianiacob22 you can reopen a new issue.
