### ISSUE TITLE
AKS cluster creation - add client-secret, service-principal and account

### ISSUE THREAD

**Issue by tgarlot** [jenkins-x/jx#1643]
### Summary 

When we run `jx create cluster aks`, there is no option to pass service principal (and associated client secret) to be used by the cluster. 
As a consequence, when your Azure account does not have the right to create it (as no access to AD), the command failed.

### Steps to reproduce the behavior
run the command `jx create cluster aks` and when prompted to authenticate with Azure, use a User that does not have the priviledge to create a Service Principal. Then the cluser creation failed with: error creating cluster exit status 1

### Jx version
The output of `jx version` is:

```
NAME VERSION
jx   1.3.241
```

### Kubernetes cluster
AKC cluster

### Proposal

Add 3 new options to jx create cluster aks (client-secret, service-principal and account) that would be passed to az aks create command to use an existing service principal and set the default subscription

Happy to try the PR.

**Comment by jstrachan** [comment]
@tgarlot a PR would be lovely thanks!

**Comment by tgarlot** [comment]
I will also add --account to set the subscription in case the user has many, like me. Otherwise it use the default one and if the RG is not in the default one, the creation failed.

**Comment by tgarlot** [comment]
PR done, not including the --account. Will need another PR for this one (more complex than expected...)
