### ISSUE TITLE
Cannot setup path based routing with jx install

### ISSUE THREAD

**Issue by krishshenoy** [jenkins-x/jx#1664]
### Summary 
I am trying to use jx to setup jenkins-x with my kubernetes cluster. This isnt a kubernetes cluster deployed using a cloud provider.  If I deploy using the default subdomains for each of the jenkins-x deployments ( jenkins-x,nexus, ..) I got everything to work. However this has the disadvantage of having to create a wildcard CNAME record for each deployment. I wanted to configure using path based routing instead. However I cannot get jx installation to complete path based routing

### Steps to reproduce the behavior
1. Create a kubernetes cluster using vke 
2. Run "helm init" to get tiller up and running 
3.  Deploy ingress controller using helm
 helm install -n k8s-ingress stable/nginx-ingress --set rbac.create=true --version 0.23.0 --namespace kube-system
4. . The ingress controller gets deployed with the following DNS endpoint 
k8s-ingress-nginx-ingress-controller.jenkinsx3-c9.cascade-domain.com

4. Run jx install using the pre-deployed ingress controller. 
_jx install --provider=kubernetes --external-ip k8s-ingress-nginx-ingress-controller.jenkinsx3-c9.cascade-domain.com --ingress-service=k8s-ingress-nginx-ingress-controller --ingress-deployment=k8s-ingress-nginx-ingress-controller --ingress-namespace=kube-system --exposecontroller-pathmode='path'_

5. Accessing the path based uRL for jenkins 
_http://k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com/loginEntry?from=%2Fjx%2Fjenkins%2Fme%2Fconfigure_
Returns 
**default backend - 404**

6. Also running _kubectl get pods_ shows several 
jenkins-x-gc-activities-1536777000-*** pods that are in error state.
jenkins-x-nexus pod is always stuck in "Container creating" state

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 1.3.243
jenkins x platform 0.0.2328
kubernetes cluster v1.10.2
kubectl            v1.10.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.14.3 (Apple Git-98)
```
COPY OUTPUT HERE
```

 **jx install --provider=kubernetes --external-ip k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com --ingress-service=k8s-ingress-nginx-ingress-controller --ingress-deployment=k8s-ingress-nginx-ingress-controller --ingress-namespace=kube-system --exposecontroller-pathmode='path'**
set exposeController Config PathMode path
Git configured for user: krishshenoy and email shenoyk@vmware.com
Using helm2
Tiller Deployment is running in namespace kube-system
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: **k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com**
The Ingress address k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com is not an IP address. We recommend we try resolve it to a public IP address and use that for the domain to access services externally.
? Would you like wait and resolve this address to an IP address and use it for the domain? No

Still not managed to resolve address k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com into an IP address. Please try figure out the domain by hand
You can now configure a wildcard DNS pointing to the new loadbalancer address k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com

If you do not have a custom domain setup yet, Ingress rules will be set for magic dns nip.io.
Once you have a customer domain ready, you can update with the command jx upgrade ingress --cluster
If you don't have a wildcard DNS setup then setup a new CNAME and point it at: k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com then use the DNS domain in the next input...
? Domain [? for help] (k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac? Domain k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com
nginx ingress controller installed and configured
Lets set up a git username and API token to be able to perform CI/CD

? Do you wish to use krishshenoy as the GitHub username for CI/CD pipelines: Yes
Cloning the Jenkins X cloud environments repo to /Users/shenoyk/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? No
Generated helm values /Users/shenoyk/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /Users/shenoyk/.jx/cloud-environments/env-kubernetes
Using local value overrides file /Users/shenoyk/aws/myvalues.yaml
Installing jx into namespace jx
waiting for install to be ready, if this is the first time then it will take a while to download images

deployment jenkins-x-nexus failed to become ready in namespace jx
Jenkins X deployments ready in namespace jx

	********************************************************

	     NOTE: Your admin password is: *********

	********************************************************

	Getting Jenkins API Token
using url http://k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com/jx/jenkins/me/configure
unable to automatically find API token with chromedp using URL http://k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com/jx/jenkins/me/configure
Please go to http://k8s-ingress-nginx-ingress-controller.jenkinsx3-e68c9152-b6b2-11e8-bdc2-0abf80d9c876.b9524f87-0c48-4c95-9edd-8ac5741df1c9.cascade-domain.com/jx/jenkins/me/configure and click Show API Token to get your API Token
Then COPY the token and enter in into the form below:

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
The kubernetes version is 1.10.2. It is deployed on Vmware Kubernetes Engine (VKE)

### Operating system / Environment
Linux/VKE
### Expected behavior
Path based routing to be successfully configured 
### Actual behavior
All deployments are not successful and cannot successfully configure jenkins-x

**Comment by jstrachan** [comment]
BTW I've tried a few times using path based routing when I hit similar issues on AWS; the thing is its super hard to make any-old-app work with path based routing. e.g. it requires custom hacks in simple apps like jenkins + nexus to get them to work - ditto just about any other web application needs custom tweaks to work properly when hosted at an arbitrary path at some domain
