### ISSUE TITLE
reflex missing on go devpod

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1671]
### Summary 

reflex is not installed by default on go devpod

### Steps to reproduce the behavior

```bash
jx create devpod -l go
...
./watch.sh
````

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.261
jenkins x platform 0.0.2341
kubernetes cluster v1.9.7-gke.6
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```

### Workaround

Run `go get github.com/cespare/reflex` on creating devpod.

**Comment by ccojocar** [comment]
There `reflex` tool is now installed in the builder base image: https://github.com/jenkins-x/jenkins-x-builders/blob/94fd5579c4bf7f3d709a52fe6efbda97de68e4b8/builder-base/Dockerfile#L134
