### ISSUE TITLE
Unable to delete invalid pipeline user using "jx" commands

### ISSUE THREAD

**Issue by johnmcollier** [jenkins-x/jx#1679]
### Summary 
During Jenkins X setup, I accidentally passed in a nonexistent github account to jx as a pipeline user and now I have no way of deleting it. Additionally, every jx create fails as it tries to add the nonexistent github user as a collaborator to the project. I get this output:
```
app name: demo, git server: github.com, org: johnmcollier, docker registry org: johnmcollier
skipping directory "/root/jenkins-x/demo/.git"
Using git provider GitHub at https://github.com


About to create repository demo on server https://github.com with user johnmcollier
? Which organisation do you want to use? johnmcollier
? Enter the new repository name:  demo


Creating repository johnmcollier/demo
Pushed git repository to https://github.com/johnmcollier/demo

Automatically adding the pipeline user: johncollier139 as a collaborator.
error: PUT https://api.github.com/repos/johnmcollier/demo/collaborators/johncollier139: 404 Not Found []
[root@johncollier-linuxdev1 jenkins-x]# jx delete
Deletes one or many resources.

```

I've tried searching the docs on how to delete a pipeline user and found nothing. I ended up having uninstall Jenkins-X and clean out the `~/.jx` folder and reinstall Jenkins-X. Is there a way to do so using `jx` commands?

### Steps to reproduce the behavior
Create a pipeline user pointing to a non-existent github account. Try to create a project, (e.g use `jx create spring -d web -d actuator`). The create will eventually fail as it tries to add the pipeline user as a collaborator to the project.

### Jx version

The output of `jx version` is:

```
[root@johncollier-linuxdev1 jenkins-x]# jx version
NAME               VERSION
jx                 1.3.259
jenkins x platform 0.0.2397
kubernetes cluster v1.11.1+icp-ee
kubectl            v1.9.3
helm client        v2.9.1+g20adb27
helm server        v2.9.1+icp+g843201e
git                git version 2.16.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
IBM Cloud Private

### Operating system / Environment
Ubuntu 16.04

### Expected behavior
Some way to delete a pipeline user using a `jx` command of some sort, instead of having to reinstall Jenkins-X and clean out the `~/.jx` folder

**Comment by ccojocar** [comment]
I think in this case you can use:
```
jx delete git token
jx create git token
```

**Comment by ccojocar** [comment]
@johnmcollier I am going to close this issue. Please try to workaround posted above. Thanks

**Comment by magicians2019** [comment]
@ccojocar : delete and create token didn't help in fixing same issue.

**Comment by doc-olliday** [comment]
@ccojocar : Same problem here. Once entered the wrong pipeline user, the work around above doesn't help. The Jenkins pipeline still tries to use the wrong credentials, although all git tokens have been removed and the correct one was created.

**Comment by doc-olliday** [comment]
Also, tried
```
jx edit pipelineusername
```
without success.

**Comment by opyh** [comment]
Same problem here. After deleting the token, `jx create quickstart` still tries to add the non-existing user as collaborator.

**Comment by ScottyVG** [comment]
@ccojocar @johnmcollier Was this issue ever resolved? I have the same issue.

I tried `jx edit pipelineusername`,  `jx delete git token` and then `jx create git token`. These commands attempt to change my local scottyvg token but do not allow me to change the token for the invalid Jenkins collaborator email address. This is what the command line says when it fails: "Automatically adding the pipeline user" <jenkins collaborator email> "as a collaborator."

I then get the following error:
```
error: PUT https://api.github.com/repos/<github org name>/<github repo name>/collaborators/<jenkins collaborator email> 404 Not Found []
```

**Comment by muratkars** [comment]
Changing the username using `jx edit pipelineusername` worked for me. 
In my case, token was created for the user that I wanted to change the username to in first place.
