### ISSUE TITLE
`jx promote` should also generate an entry in the `values.yaml` file

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1683]
when we generate a Pull Request to promote an app into an environment we currently just add the chart to the `requirements.yaml`. I'd be nice to also add a key into the `values.yaml` to show folks where the environment specific configuration will go.

If we ever move to a `values/` folder using separate files, then we'd create a folder `env/values/myapp/values.yaml` instead - with maybe a `README.md` in the new folder indicating that this is where the environment configuration for `myapp` lives
https://github.com/jenkins-x/jx/issues/1105#issuecomment-405596538

**Comment by lvlds** [comment]
Hello,
I am working with jx lately, thanks for all the work you guys are doing.
I would like to help with this issue, is **jx/pkg/jx/cmd/promote.go** related?
Where can I start or how can I get more context/info?
Regards.

**Comment by jstrachan** [comment]
Hi @lvlds thanks for your kind words. Yes thats the command that triggers the promotion Pull Request etc.

The actual code that loads the `requirements.yaml` file and invokes a callback to modify it is here:
https://github.com/jenkins-x/jx/blob/985e6bd93fc94c5154e60c1589c570245a98993f/pkg/jx/cmd/common_environments.go#L123-L134 so if that succeeds we should hopefully be able to add some code to look for the `values.yaml` and see if there's a line of the form `$chartName:` and if not add that line

**Comment by lvlds** [comment]
I'll get some time to work on it this week.
I'll ask my questions on the slack channel #jenkins-x-dev, if that is okay.

**Comment by NandoTheessen** [comment]
Hey, this doesn't look super active.
I'd like to have a Go at this, is this still needed?

**Comment by NandoTheessen** [comment]
It looks like this was already implemented with gitOps and is now handled by the `ModifyChartFiles` function.
