### ISSUE TITLE
jx import is not utilising --org or --docker-registry-org params

### ISSUE THREAD

**Issue by riqbal-rocketlawyer** [jenkins-x/jx#1699]
### Summary 

When importing a project I want jx not to use my GitHub username as registry org and Jenkins folder. I tried using parameters from documentation to override i.e. `jx import --org myorg --docker-registry-org myorg'

But it didn't make any difference. My skaffold still used GitHub username as org and Jenkins job was also created in wrong folder.

### Steps to reproduce the behavior

Run this command on a new project

jx import --org myorg --docker-registry-org myorg

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.274
jenkins x platform 0.0.2397
kubernetes cluster v1.9.7-gke.6
kubectl            v1.9.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

gke
created using gcloud then used `jx install --provider=gke`

### Operating system / Environment

Mac OS

### Expected behaviour

Org parameters should be utilised

### Actual behavior
Org parameters are ignored

**Comment by alokrajiv** [comment]
Maybe related to PR https://github.com/jenkins-x/draft-packs/pull/72 ?

**Comment by riqbal-rocketlawyer** [comment]
Yes exactly. This PR is going to resolve the issue.

**Comment by ccojocar** [comment]
@riqbal-rocketlawyer Is this still an issue? Can we close it? Thanks
