### ISSUE TITLE
Allow users to override the docker-registry used in DevPods.

### ISSUE THREAD

**Issue by johnmcollier** [jenkins-x/jx#1714]
Users should be able to specify a docker-registry override when launching DevPods, for example with a `--docker-registry` flag. This may be useful if users want to launch a DevPod that uses a separate docker registry than other DevPods. It would also prevent the user having to change the $DOCKER_REGISTRY environment variable at the Jenkins-X level.

I see it working like so:
```
jx create devpod -l maven --sync --docker-registry <registry-url>
```

I've got a PR open here https://github.com/jenkins-x/jx/pull/1713 that does this. I've tested with two separate registries, as well as having separate registries in use alongside each other and with the built-in registry. Everything looks good with the changes.

**Comment by ccojocar** [comment]
fixed by #1713
