### ISSUE TITLE
Looking for suggestions for using databases with Jenkins x

### ISSUE THREAD

**Issue by sdoxsee** [jenkins-x/jx#1715]
### Summary 

From what I understand, jx is meant to help get people running on k8s without having to know all the details at first (and I've found it to be super cool and right on in that goal). However, speaking as a k8s rookie, one very quickly gets to the point where they want to store data rather than create a hello world app. 

I was able to create a database service and deployment for mssql server and was able to use it just like I would if it was a Docker container i brought up using Docker compose. However, I've frequently been warned about having databases (notably production) in containers (no reference but easy to google). Just makes me wonder if I could ever even use a preview environment if I don't have provisioning of a database. I did this by using my application code to create the database if it wasn't there, migrate the schema, and I seeded the database with demo data. Seemed to work fine but I'm wanting to build for production. 

Some say statefulsets are the solution but many seem to agree that the db should be outside k8s. Google suggests some [ways of handling databases external to k8s](https://cloudplatform.googleblog.com/2018/05/Kubernetes-best-practices-mapping-external-services.html?m=1
) but I like the simplicity of all environments (preview, staging, production) being very similar and, for preview, a db container was just fine for me.

Could the spring boot tutorial go a bit further to hook it up to some state?

**Comment by sdoxsee** [comment]
Maybe something like this but provisioning isn't as simple as referencing a docker image. Your probably need jx to run a gcloud or curl 
command or employ terraform? https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine

**Comment by MichalFoksa** [comment]
@sdoxsee bit more elaborated #2604: [Jenkins X: Preview Environment](https://medium.com/@MichalFoksa/jenkins-x-preview-environment-3bf2424a05e4)
