### ISSUE TITLE
error: headGitRepo.AddRemote: exit status 128 - error: could not lock config file config: File exists

### ISSUE THREAD

**Issue by kiss0840** [jenkins-x/jx#1717]
### Summary 
+ jx promote -b --all-auto --timeout 1h --version 1.0.1
Using helmBinary helm, with local tiller falsePromoting app spring-boot-watch-pipeline-activity version 1.0.1 to namespace jx-staging
error: headGitRepo.AddRemote: exit status 128 - error: could not lock config file config: File exists
fatal: could not set 'remote.tmp-pull-74.url' to '/data/git/gitea-repositories/gitea****/environment-jx-staging.git'
### Steps to reproduce the behavior
Follow by the document
### Jx version

The output of `jx version` is:
Using helmBinary helm, with noTiller false
NAME               VERSION
jx                 1.3.281
jenkins x platform 0.0.2468
kubernetes cluster v1.11.1
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 1.8.3.1

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
k8s

### Operating system / Environment
CentOS
### Expected behavior
the Promote procedure are passed
### Actual behavior
Failed in 'headGitRepo.AddRemote could not lock config file config: File exists'

**Comment by ccojocar** [comment]
@kiss0840 Which git provider are you using?

**Comment by ccojocar** [comment]
@kiss0840 I am going to close this issue since the requested evidence weren't provided.
