### ISSUE TITLE
error: unexpected end of JSON input

### ISSUE THREAD

**Issue by aniketksh** [jenkins-x/jx#1727]
### Issue

I have ACR created in my Azure account. While creating a cluster, I had provided `<username>.azurecr.io` for  `--docker-registry` flag. Now, according to documentation on, https://jenkins-x.io/getting-started/config/#docker-registry, If I am not using default container registry, I have to configure the Docker Registry. I followed the documentation and according to documentation, I have to need to update the config.json secret for docker using following cmd,
```sh
$ jx create docker auth --host "<username>.azurecr.io" --user "<username>" --secret "<SampleSecrete>" --email "<emailaddress>" 
```

but getting the error message as follows
```
error: unexpected end of JSON input
```

### Jx version

The output of `jx version` is:

```
jx                 1.3.288
jenkins x platform 0.0.2454
kubernetes cluster v1.9.9
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.7.4
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?:

I have AKS cluster up and running, created by `jx create cluster aks` command

**Comment by ccojocar** [comment]
It looks that the parameters you are providing to the command are producing a malrfomed `config.json` file. 

Please follow the solution suggested above to debug the issue.
