### ISSUE TITLE
Don't allow the cloudbees --sso addon to be created until the SSO resources are ready

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1770]
### Summary 

If you try to create the cloudbees addon too soon after creating the SSO addon, the cloudbees addon won't work. You need to leave at least 2 minutes. We should just not allow the cloudbees addon to be created until the SSO addon is ready, or worst case make it really clear how long you have to wait.

**Comment by ccojocar** [comment]
dup of #1773

**Comment by pmuir** [comment]
No, it isn't. This issue (#1770) refers to the fact that you need to wait about 2 minutes between `jx create addon sso --namespace=sso` completing and running `jx create addon cloudbees --sso`. If you don't wait the cloudbees addon is in a bad state and the only way to proceed is to delete it, and start again. #1773 refers to the fact that after running `jx create addon cloudbees --sso` you need to wait a further 45s for the addon to start, but you can immediately run `jx cloudbees` and get a URL with no status to say 'please wait' (or something like that) and instead you just see a 500 from the app when opening the URL.
