### ISSUE TITLE
Login via GitHub now doesn't work

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1775]
### Summary 

You just end up back at the same page

### Steps to reproduce the behavior

Install a cluster following the https://cloudbees.atlassian.net/wiki/spaces/JX/pages/580190553/Installing+Kube+CD and then try to log in. You need to grant access to the right org on the Authorize screen.

### Jx version

The output of `jx version` is:

```
✔ pmuir:workspace ➭ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.315
jenkins x platform 0.0.2544
kubernetes cluster v1.9.7-gke.6
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Operating system / Environment

### Expected behavior

### Actual behavior

**Comment by pmuir** [comment]
Video of this at https://drive.google.com/file/d/1KD6j6onsvR3p5D7CSuKJ_K2-JWiV7-n3/view

**Comment by pmuir** [comment]
I suggest we provide the user with a set of instructions on the Login screen that explains in detail what to do on the Grant screen - this should minimise the number of users ending up in this state. We should also be able to detect that they are returning on the OAuth 2 flow and give them a nice hint that they didn't do the right clicks in GitHub, and tell them how to proceed. Just displaying a page again is a very poor UX.

**Comment by ccojocar** [comment]
As far as I understand, the user which install the addon is an admin user which has enough rights to proceed with the installation, while the user which runs the login does not have much information about how the addon was installed. 

I agreed that it would be nice to improve the UX. It would be great, if you could send some patches for this.

**Comment by ccojocar** [comment]
There is a secret which contains the dex configuration in the namespace where the `sso` addon is installed. The GitHub organisations can be parsed from there.
