### ISSUE TITLE
Document (or possibly fix) method to change domain after install

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1776]
### Summary 

Currently if you install using one domain I don't think you can change the domain to another domain. `jx upgrade ingress` looks promising, but if you change the domain here it doesn't update all dependent services (at least chartmuseum was broken for me at this point). If you aren't supposed to change the domain during `jx upgrade ingress` then we shouldn't prompt for it.

**Comment by ccojocar** [comment]
This requires some work in the `sso-operator`. I created this issue https://github.com/jenkins-x/sso-operator/issues/14 to handle the updates of SSO resource.
