### ISSUE TITLE
Error: a release named jxing already exists

### ISSUE THREAD

**Issue by sercanacar** [jenkins-x/jx#1802]
### Summary 
Running the following on a clean environment (Hoping its clean)

`jx install --provider=kubernetes --on-premise --external-ip=XXXXX`

Installing using helm binary: helm
Installing using helm binary: helm
Installing using helm binary: helm
**Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true' command in directory '', output: 'Error: a release named jxing already exists.**
Run: helm ls --all jxing; to check the status of the release
Or run: helm del --purge jxing; to delete it': exit status 1
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: XXXXXX
You can now configure a wildcard DNS pointing to the new loadbalancer address XXXXX

### Steps to reproduce the behavior

Run jx install on provider kubernetes

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.330
Kubernetes cluster v1.10.5+2.0.2.el7
kubectl            v1.10.5+2.0.2.el7
git                git version 1.8.3.1

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
1 master node, 3 workers

### Operating system / Environment
Oracle Linux 7.5

**Comment by jstrachan** [comment]
it looks like a previous helm install exists. e.g. try:
```
helm list
```
as the output says you can fix this by running
```
helm del --purge jxing
```
then re-trying

**Comment by yanhongwang** [comment]
Hello @jstrachan 

I meet the same error message like @sercanacar 

I tried to delete that chart with purge option.
And execute again:

jx install --provider=kubernetes

The result still keep the same.
Some other idea?

Thanks.

**Comment by jstrachan** [comment]
as the output says did you try...
```
Run: helm ls --all jxing; to check the status of the release
Or run: helm del --purge jxing; to delete it': exit status 1
```

**Comment by ccojocar** [comment]
@sercanacar I am going to close this issue. The solution is to delete the existing jxing release and run again the install.
