### ISSUE TITLE
Better integration with ACR as docker registry

### ISSUE THREAD

**Issue by tgarlot** [jenkins-x/jx#1805]
I would like to improve the way Jenkins-X is configure with Azure Container Registry.
Typically "autodetect" if there is already a ACR in the RG where AKS cluster will be installed and use it (set up automatically the SP role) or use the --docker-registry parameter and if it's an ACR, try to configure Jenkins to use it.

Will start on this. Any comment / idea is welcome. 

PS: ACR can now be used as Helm repository (replacement of chartmuseum). Woud that make sense to also investigate how to use it and remove chartmuseum installation on Azure (optional for sure)?

**Comment by tgarlot** [comment]
I think it's a bad idea to create the ACR in the RG that is automatically created by Azure with the agent nodes: if we delete the "AKS service", it would delete the whoe RG thus the ACR too...
So I think it's better for the ACR to be by default in the same RG thatn the "AKS service".

Creating the ACR automatically: I would say "yes if it does not already exist or is not provided with the docker-registry parameter" of the `jx create cluster`

**Comment by yuwzho** [comment]
Hi @tgarlot , how's this issue going?

As the ACR is a private registry, but I don't find there is a standard way to support private registry. Do you have any plan to work this out? Or I can take my time on it. To filling the gap, the following steps should be implemented. Any comment is welcome. 

## 1. Support private registry
#### Configuration
   * Receive the registry URL by `--docker-registry`
   * Receive the registry username/password by `--docker-username` and `--docker-password`. Also use these two fields to identify this is a private registry
#### Set registry/credential for Jenkins master
   * Auto configure the docker registry in the Jenkins system configuration
   * Save docker registry credential in the jx namespace for Jenkins master
#### Set registry/credential for Kubernetes
   * Create environment with registry's secret (production/staging/PR) for deployment
   * Add `imagePullSecrets` in the [deployment.yaml](https://github.com/jenkins-x/jx/blob/master/charts/jx/templates/deployment.yaml) if it is a private registry
## 2. Configure ACR as a private regitry
#### Get URL of a given ACR
   * Receive via `--docker-registry`
   * Auto detect the ACR in the same resource group
   * Auto create an ACR in the same resource group when creating AKS using jx
#### Get Credential of the ACR
   * Get from `--docker-username` and `--docker-password` as other private registry
   * Retrieve ACR's credential if `admin-enabled`
   * Create  service principal for ACR image pull/push

**Comment by tgarlot** [comment]
@yuwzho, no time to really start on it yet, was trying to do exactly what you did : summarizing the changes to be done. 

Few comments on your proposal:
* Private registry:
** would rather use `--docker-registry-username` and `--docker-registry-password` to make it even clearer that they are credentials for the private registry

* ACR as private registry
** Perhaps we should also NOT install the private registry in jx in this case ? What do you think?
** There is already some parameters `--service-principal` and `--client-secret` that are used to pass an existing SP to be used by the cluster. Perhaps we can re-use them instead of using docker-username or docker-password?
** We also need to give some permissions to the cluster to Read in the ACR (see [Azure doc](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks)

I won't have a lot of time to start on this "soon" so if you want to start, no pb for me. Happy to help to test and review PR if this help.

I would like to start also looking at using ACR as Helm repo instead of Chartmuseum (it's a preview but really cool [link](https://docs.microsoft.com/fr-fr/azure/container-registry/container-registry-helm-repos)

**Comment by yuwzho** [comment]
@tgarlot I am not get `Perhaps we should also NOT install the private registry in jx in this case`, would you like to give more explain?

As ACR supports authentication in SP and username/password 2 ways, we can support username/password falling back to common private registry, and support SP for ACR specifically, and as you mentioned, need to grant the ACR access to the SP.

**Comment by jstrachan** [comment]
@yuwzho I'd love to make ACR the default when using AKS like we've done for EKS/ECR! So lets do it! BTW I think the comment `Perhaps we should also NOT install the private registry in jx in this case` was about not installing the internal docker registry we install by default. We can disable that via these flags: https://github.com/jenkins-x/cloud-environments/blob/master/env-eks/myvalues.yaml#L11-L12 which we can add into the default AKS configuration: https://github.com/jenkins-x/cloud-environments/blob/master/env-aks/myvalues.yaml#L6

BTW we've already added the docker credstore in the above file; we've just not defaulted the docker registry itself to default to ACR yet.

**Comment by yuwzho** [comment]
I am now getting a more Azure way to integrate ACR and AKS for the private registry issue in ARM(Azure Resource Management) level. We only need to do the following 2 things:

1. [Set registry credential for Jenkins Master](https://jenkins-x.io/architecture/docker-registry/#using-a-different-docker-registry)
    * Navigate to Jenkins Mater's `Manage Jenkins` -> `Configure System` and change the `DOCKER_REGISTRY` environment variable to point to your docker registry of choice.
    * `jx create docker auth --host "foo.private.docker.registry" --user "foo" --secret "FooDockerHubToken" --email "fakeemail@gmail.com"`
2. [Assign ACR reader role to AKS](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks#grant-aks-access-to-acr)
    
   ```bash
   #!/bin/bash

   AKS_RESOURCE_GROUP=myAKSResourceGroup
   AKS_CLUSTER_NAME=myAKSCluster
   ACR_RESOURCE_GROUP=myACRResourceGroup
   ACR_NAME=myACRRegistry

   # Get the id of the service principal configured for AKS
   CLIENT_ID=$(az aks show --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --query "servicePrincipalProfile.clientId" --output tsv)

   # Get the ACR registry resource id
   ACR_ID=$(az acr show --name $ACR_NAME --resource-group $ACR_RESOURCE_GROUP --query "id" --output tsv)

   # Create role assignment
   az role assignment create --assignee $CLIENT_ID --role Reader --scope $ACR_ID
   ```
