### ISSUE TITLE
pipeline failure "Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.RC1"

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkins-x/jx#181]
### Problem

By default, JenkinsX's built-in Nexus repository only mirrors Maven Central. When building spring boot applications, we need  https://repo.spring.io/milestone and https://repo.spring.io/snapshot.

https://gist.github.com/cyrille-leclerc/f09adbab099a71656d6f751cfc099d4d

### Workaround

Update Nexus config and declare mirrors for https://repo.spring.io/milestone and https://repo.spring.io/snapshot .

* Open Nexus web console using `jx open nexus`
* Login with admin/admin123
* Create "Maven 2 Proxy" repositories for 
   * https://repo.spring.io/milestone : type "release"
   * https://repo.spring.io/snapshot : type "snapshot
* Add these two repositories to the "Maven 2 Group" repository "maven-public"

### Error message

Error in the pipeline build logs 

```
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Scanning for projects...
[INFO] Downloading: http://jenkins-x-sonatype-nexus:8081/repository/maven-public/org/springframework/boot/spring-boot-starter-parent/2.0.0.RC1/spring-boot-starter-parent-2.0.0.RC1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.cloudbees.test.kubernetes.draft:draft-spring-boot-app:0.0.1-SNAPSHOT: Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.RC1 in nexus (http://jenkins-x-sonatype-nexus:8081/repository/maven-public/) and 'parent.relativePath' points at no local POM @ line 14, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.cloudbees.test.kubernetes.draft:draft-spring-boot-app:0.0.1-SNAPSHOT (/home/jenkins/workspace/raft-spring-boot-app_master-UYE7LYZTRFK2QPXLTMX2XRNZQF2OAOQU5YJA6IJXVYDFB3ZANCRQ/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.cloudbees.test.kubernetes.draft:draft-spring-boot-app:0.0.1-SNAPSHOT: Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.RC1 in nexus (http://jenkins-x-sonatype-nexus:8081/repository/maven-public/) and 'parent.relativePath' points at no local POM @ line 14, column 10 -> [Help 2]
```

**Comment by jtnord** [comment]
the default settings should just be `mirroOf=central` for a kick the tires approach (or a list of the repos that are mirrored) so that users can add their own repos in the `pom.xml` (not that adding repos in poms is a good idea)

**Comment by rawlingsj** [comment]
Yeah, we ship nexus (possible artifactory soon) so the preferred approach is to add proxies which also means deps are cached.  I think we mentioned the steps on hipchat but even better would be to automate the setup of repos to proxy.  Think I did this for nexus 3 in fabric8 so it should just be a case of digging out the scripts.

**Comment by rawlingsj** [comment]
I'm pretty sure this is the nexus 3 config we can use https://github.com/fabric8io-images/nexus-docker/blob/nexus3/spring-milestone.json so this works OOTB.

**Comment by rawlingsj** [comment]
FWIW this repo contains a load of repos that we can use to preconfigure nexus proxies https://github.com/fabric8io-images/nexus-docker/tree/nexus3

**Comment by cyrille-leclerc** [comment]
@rawlingsj registering these repositories seem to be a good idea.

**Comment by rawlingsj** [comment]
Yeah - I think it's pretty easy to do so will take a look once I've cleared more immediate tasks. 

Hopefully in the next day or two.

**Comment by cyrille-leclerc** [comment]
@rawlingsj thanks, it's not urgent. For the moment, I would prefer us to focus on the happy path. By the time Jenkins X is out, Spring Boot 2 will GA and their will be less attraction for milestones.

**Comment by rawlingsj** [comment]
These are available in the nexus image - closing https://github.com/jenkins-x/nexus/tree/master/repositories

**Comment by binoydev** [comment]
@rawlingsj  Please add  https://repo.spring.io/snapshot : type "snapshot  also.
