### ISSUE TITLE
step jx promote  failed  : Failed to query the Pull Request last commit status for https://github.com/xxx/pull/1 ref 1027.. Could not find a status for repository staging with ref 1027..

### ISSUE THREAD

**Issue by zgorizzo69** [jenkins-x/jx#1851]
### Summary 
brand new install on gcloud
I even have purged the jx config files 
```
rm ~/.jx/chartmuseumAuth.yaml
rm ~/.jx/jenkinsAuth.yaml
```

I tried the quickstart node and go and none of them is working
this build step of promote environment failed
```
jx promote -b --all-auto --timeout 1h --version $(cat ../../VERSION)
```
probably because of the timeout as this task took more than 1h

### Steps to reproduce the behavior
start with a brand new cluster on gcloud
```
jx create cluster gke --domain=xxx.com --tls-acme=true --http=false  --min-num-nodes=3 --max-num-nodes=5
```
then launch the quickstart
```
jx create quickstart -l go
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.353
jenkins x platform 0.0.2691
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.10.5
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.17.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
gke
```
jx create cluster gke --domain=xxx.com --tls-acme=true --http=false  --min-num-nodes=3 --max-num-nodes=5
```

### Operating system / Environment
ubuntu bionic beaver

### Expected behavior
pipeline success
### Actual behavior
pormote to environment failed:

[golang-http] Running shell script
```
++ cat ../../VERSION

+ jx promote -b --all-auto --timeout 1h --version 0.0.1

Using helmBinary helm with feature flag: none

Promoting app golang-http version 0.0.1 to namespace jx-staging

Created Pull Request: https://github.com/zgorizzo69/environment-carverquiver-staging/pull/1

Failed to query the Pull Request last commit status for https://github.com/xxx/environment-staging/pull/1 ref 1027....  Could not find a status for repository xxx/environment-staging with ref 1027....
the same message multiple times (during 1h)

Failed to query the Pull Request last commit status for https://github.com/xxx/environment-staging/pull/1 ref 1027....  Could not find a status for repository xxx/environment-staging with ref 1027....

Cannot contact go-pptn2: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from 10.60.0.15/10.60.0.15:35482 failed. The channel is closing down or has closed down
```

**Comment by rawlingsj** [comment]
Looks like the webhook did not trigger the CI build for this PR https://github.com/zgorizzo69/environment-carverquiver-staging/pull/1

Can you check the qwebhook events on that repo?  Go to settings > webhooks and scroll down to see the events and check they were successfully sent.

**Comment by zgorizzo69** [comment]
I have deleted the environment and recreated them I have then import the repo (jx import) and now it is working thanks ;)
