### ISSUE TITLE
`jx` does not discover some github orgs I could create repos into

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkins-x/jx#186]
Why doesn't `jx create environment` propose me the `cloudbeers` github org?

```
$ jx create environment
? Name: production
? Label: Production
? Namespace: ecommerce-production
? Cluster URL:
? Promotion Strategy: Auto
? Would you like to use GitOps to manage this environment? : Yes
? Would you like to create a new Git repository to store this Environments source code? : Yes
Using git provider GitHub at github.com
? Do you wish to use cyrille-leclerc as the git user name? Yes


About to create a repository on server github.com with user cyrille-leclerc
? Which organisation do you want to use?
  CloudBees-community
❯ cyrille-leclerc
  jmxtrans
```

**Comment by jstrachan** [comment]
can you scroll down to see the other organisations I wonder? The console CLI only shows a fixed number of choices in a combo box UI - then you have to use the down cursor key to scroll down.

There's a pending issue to be able to easily filter the list which might help https://github.com/AlecAivazis/survey/issues/61#issuecomment-356746606

**Comment by jstrachan** [comment]
@cyrille-leclerc could you confirm the above please?

**Comment by cyrille-leclerc** [comment]
@jstrachan problem still there with `jx:1.0.50`, even scrolling down. See screencast below

```
$ jx version
NAME         VERSION
jx           1.0.50
Kubernetes   v1.9.0
Helm Client  v2.8.0+g14af25f
Helm Server  v2.8.0+g14af25f
Draft Client v0.9.0
Draft Server v0.9.0
```
https://www.youtube.com/watch?v=srDkNOC7mzk&feature=youtu.be
