### ISSUE TITLE
Github Apps support

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#1866]
GitHub is pushing hard for all integrations to be a Github App. 

The benefits: 
* Newer apis
* Ability to use checks API/tab
* Apps can show up (discoverable) on the market place eg like <a href='https://github.com/marketplace/category/continuous-integration'>this</a>
* Apps do not use a user seat/licence (eg in GHE)
* User can have finer grained clearer permissions (and can easily adjust them, app can request what is needed)

This allows things to operate as a bot without it being a pretend user. Can also do things on behalf of a user (you can request a token to let you take actions on behalf of the user). This allows smoother experience (and more secure) as no copy pasting of personal access tokens. 

Some more info here: https://developer.github.com/apps/differences-between-apps/#machine-vs-bot-accounts.

This could possibly done with a singular Jenkins X Github App hosted somewhere, which lets people grant (perhaps) access to their instance of Jenkins X (not sure of the details here though).

**Comment by jglick** [comment]
Possibly duplicate of https://github.com/kubernetes/test-infra/issues/10423.

**Comment by michaelneale** [comment]
yes I think it would be.
