### ISSUE TITLE
Add `hacktoberfest` topic/label to the repo.

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-x/jx#1876]
Jenkins X project participates in the Hacktoberfest: https://jenkins.io/blog/2018/10/01/hacktoberfest/
It would be great to add a `hacktoberfest` label to the repo so that it appears on https://hacktoberfest.digitalocean.com/

CC @rawlingsj

**Comment by ricardoseriani** [comment]
I'm not sure if there is a "way" to use the hacktoberfest label in the repository or only in issues.
Can you confirm this to me, please ?

**Comment by pmuir** [comment]
I don't understand? You can the label to issues and to prs.

**Comment by oleg-nenashev** [comment]
Hacktoberfest does not require labeling issues or PRs this year.
This issue is only about tagging repos

**Comment by jtnord** [comment]
seems like this was done but not closed.
