### ISSUE TITLE
creating multiple expose-xxxx pods in cluster 

### ISSUE THREAD

**Issue by sriharim** [jenkins-x/jx#1878]
### Summary 
While installing JX in existing AWS kubernetes cluster using "jx install". it is created multiple pods 

jx            expose-4k558                                            0/1     ContainerCreating   0          2s
jx            expose-527cl                                            0/1     Error               0          29s
jx            expose-ckhc2                                            0/1     Error               0          13s
jx            expose-ffntt                                            0/1     Error               0          6s
jx            expose-hdl5l                                            0/1     Error               0          41s
 
### Steps to reproduce the behavior
1) Exported cluster names 
2) jx install

### Jx version

The output of `jx version` is:

```
jx   1.3.340
git  git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AWS  Kubernetes cluster ( Created using KOPS) 

### Operating system / Environment
Ubuntu 

### Expected behavior
Creating non-recognised pods  
jx            expose-4k558                                            0/1     ContainerCreating   0          2s
jx            expose-527cl                                            0/1     Error               0          29s
jx            expose-ckhc2                                            0/1     Error               0          13s
jx            expose-ffntt                                            0/1     Error               0          6s
jx            expose-hdl5l                                            0/1     Error               0          41s

### Actual behavior

**Comment by rawlingsj** [comment]
can you attach the logs of one of the failed pods please?

**Comment by ccojocar** [comment]
@sriharim I am going to close this issue since the requested evidence weren't provided.
