### ISSUE TITLE
Link to user in Jira in changelog

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#1880]
### Steps to reproduce the behavior

Create a release for a project with Jira as the issue tracker

### Expected behavior

Links to assignees for related issues in the changelog leads to the user in Jira.

### Actual behavior

When a changelog is generated for a project with Jira as the issue tracker the links to issues are correct, but links to the assignees of the issues go to github (where the jira user is likely to not exist or actually is another user).

**Comment by msvticket** [comment]
/remove-lifecycle stale

Also I would argue that this is not an enhancement but a bug.

**Comment by tomhobson** [comment]
Hey @msvticket, is this still an issue?

**Comment by msvticket** [comment]
Well, yes. In jx2 there was a faulty link to github, while in jx3 the assignee doesn't link anywhere. So the bug is gone, but the feature would still be practical.
