### ISSUE TITLE
`jx create spring` and `jx import` assume that the "staging" environment exists 

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkins-x/jx#189]
`jx create spring` and `jx import` assume that the "staging" environment exists but it's not always the case, at least if "create team" has not been invoked

https://github.com/jenkins-x/jx/blob/v1.0.34/pkg/jx/cmd/import.go#L97

```
...
stage('Deploy Staging') {
      steps {
        dir ('./charts/%s') {
          container('maven') {
            sh 'make release'
            sh 'helm install . --namespace staging --name example-release'
            sh 'exposecontroller --namespace staging --http' // until we switch to git environments where helm hooks will expose services
          }
        }
      }
    }
...
```

**Comment by rawlingsj** [comment]
This is going to be removed when we integrate `jx promote`

**Comment by cyrille-leclerc** [comment]
ack thx

**Comment by jstrachan** [comment]
should be fixed in the new jx version now - we use `jx promote --all-auto` which promotes to all environments defined for your team.

I'll leave this issue open for a while until we've got bdd tests passing that uses this though ;)

**Comment by cyrille-leclerc** [comment]
@i386 I'll assume that you understand how this `jx promote` feature work, I am not up to speed on this feature.

**Comment by i386** [comment]
@cyrille-leclerc no idea right now
