### ISSUE TITLE
`jx version` initiated upgrade removes jx before confirming install

### ISSUE THREAD

**Issue by BlackMaria** [jenkins-x/jx#1893]
### Summary 

* When `jv version` offers to upgrade, jx is removed before confirming download worked. In the following, I had to manually install jx since it was deleted. 

* **nb** this happened today during the migration to your server-less jx builds

### Steps to reproduce the behavior

1. type `jv version`
2. answer `yes` to `Would you like to upgrade`

### Jx version
```
The output of `jx version` is:
bash-4.4# jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.369
Kubernetes cluster v1.10.6
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0

? Would you like to upgrade to the new jx version? Yes
? Would you like to upgrade to the new jx version? [? for help] (Y/n) y
Downloading https://github.com/jenkins-x/jx/releases/download/v1.3.373/jx-linux-amd64.tar.gz to /usr/local/bin/jx.tgz...
Downloaded /usr/local/bin/jx.tgz
panic: unexpected EOF
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x62dd52]

goroutine 1 [running]:
compress/gzip.(*Reader).Close(0x0, 0x292e340, 0xc000098040)
	/usr/local/go/src/compress/gzip/gunzip.go:292 +0x22
```

**Comment by johnmcollier** [comment]
I can tackle this.

Simple solution would be to untar the jx binary into a temp file (something like binDir/jx-tmp). Then only overwrite the old jx binary if we get a working binary.

**Comment by hekonsek** [comment]
Actually `os.rename()` may fail if operation is performed between different block devices:

```
[hekonsek@konsekranch ~]$ jx upgrade cli
Downloading https://github.com/jenkins-x/jx/releases/download/v1.3.412/jx-linux-amd64.tar.gz to /home/hekonsek/.jx/bin/jx.tgz...
Downloaded /home/hekonsek/.jx/bin/jx.tgz
error: rename /tmp/jx /home/hekonsek/.jx/bin/jx: invalid cross-device link
```

@johnmcollier  Your solution is generally correct, but you cannot extract into temp directory which might be located on the different block device which will cause `os.rename()` to fail.

**Comment by hekonsek** [comment]
I've just submitted #1950 which uses `~/.jx` as a temporary directory. So the problem described in this issue is still fixed, but we use temporary directory which is outside of PATH, but on the same device as `~/.jx/bin/jx`.

**Comment by johnmcollier** [comment]
@hekonsek Ah okay, that sounds good then. Thanks for catching it!
