### ISSUE TITLE
The Docker registry should support authentication

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkins-x/jx#190]
The pipeline to deploy to the Docker Registry does not seem to support authentication of the `docker push`.

We need to support a "Bring Your Own Docker Registry" model with authentication.

https://github.com/jenkins-x/jx/blob/v1.0.34/pkg/jx/cmd/import.go#L86

```
        container('maven') {
          sh 'mvn clean deploy'
          sh "docker build -f Dockerfile.release -t $JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST:$JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT/$ORG/$APP_NAME:\$(cat VERSION) ."
          sh "docker push $JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST:$JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT/$ORG/$APP_NAME:\$(cat VERSION)"
        }
```

**Comment by rawlingsj** [comment]
We have two options, we can use nexus which is authenticated but when on public cloud it would be better to use the native registries for AWS, Azure and Google Cloud.

**Comment by rawlingsj** [comment]
Also the docker registry chart we use has recently added support for auth - so that's an option too.

**Comment by cyrille-leclerc** [comment]
I would be interested in looking for a "standard jenkins pipeline solution".

**Comment by rawlingsj** [comment]
We can now easily use cloud provider registries which are authenticated details https://jenkins-x.io/architecture/docker-registry/
