### ISSUE TITLE
jx imports chokes if .gitignore is a directory

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1905]
### Summary 

https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L1093 is causing jx to hang if `.gitignore` is directory (which is now the defualt for github.com new repos).

**Comment by davidcurrie** [comment]
I see `jx import` fail with:
```
error: there was an error detecting the language: error reading .gitignore: read /Users/dcurrie/code/src/github.com/davidcurrie/.gitignore: is a directory
```
Is the error you were seeing or something else? This is coming from linguist via draft. Also, GitHub is still just creating regular `.gitignore` files for me in a new repo.

**Comment by pmuir** [comment]
That's the one.

**Comment by davidcurrie** [comment]
I'm still intrigued by how you ended up with a `.gitignore` directory though. I can submit a PR to draft but I'm not sure I'd have much sympathy for it given you're well off the beaten path.
