### ISSUE TITLE
jx compliance does not show results on failure

### ISSUE THREAD

**Issue by abergmeier** [jenkins-x/jx#1916]
### Summary

It seems like `compliance` command is not working properly on OpenShift.

### Steps to reproduce the behavior

1. Execute `jx compliance run`.
2. After a while `jx compliance status` gives:
```
Compliance tests have failed. You can check what happened with `jx compliance results`.
```
3. Then `jx compliance status`:
```
Compliance results not ready. Run `jx compliance status` for status.
```

### Jx version

The output of `jx version` is: 

```
1.3.380
```

### Kubernetes cluster

Openshift 3.9

### Expected result
Would expect this to give a proper errror report.

**Comment by johnmcollier** [comment]
I've seen the exact same type of error on IBM Cloud Private.

**Comment by abergmeier** [comment]
I think there is a problem with error messages. See https://github.com/jenkins-x/jx/commit/e1b409c76c9f65a6d4e8d1739ea40e407ce481d0#r30849852

**Comment by johnmcollier** [comment]
@abergmeier Agreed with your comment. The results from `jx compliance` should still be visible if the status is failed and not complete.

**Comment by abergmeier** [comment]
Trying to fix in https://github.com/jenkins-x/jx/pull/1957
