### ISSUE TITLE
Fails to query last commit status on repo

### ISSUE THREAD

**Issue by aespejel** [jenkins-x/jx#1923]
### Summary 

Jenkins fails to query the status of the PRs in gitlab v11.1.4 so, it can't complete a simple promote pipeline. Webhooks are created correctly, manually added access to all and notify everything to the webhook (just in case).

### Steps to reproduce the behavior

jx create git gitlab https://mygitlab.onpremise.local
jx create git token myname
jx import $my_very_simple_python_proyect

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.391
jenkins x platform 0.0.2755
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.7.4
```

### Kubernetes cluster

EKS cluster, created with terraform using the eks module.

### Operating system / Environment

Tested on Ubuntu and Fedora

### Expected behavior

Jenkins is able to understand that the PR is created, merge it and finish the pipeline successfully deploying code in the next environment.

### Actual behavior

The PR is created in the next environment repo, but jenkins keeps showing:
```Failed to query the Pull Request last commit status for https://mygitlab.onpremise.local/myname/environment-jx-sta/merge_requests/1 ref...```

If I merge it manually it starts showing:
```Pull Request https://mygitlab.onpremise.local/myname/environment-jx-sta/merge_requests/1 is merged at sha ...
Merge commit has not yet any statuses on repo myname/environment-jx-sta merge sha ... ```

The code is actually deployed to the staging environment, but looks like the pipeline can't check it and times out.

**Comment by omermizrahi** [comment]
Having the same issue

**Comment by dimmel82** [comment]
Hi, I have the same issue. When I manually post the following to gitlab api the Jenkins job is completed:
`curl --request POST --header "PRIVATE-TOKEN: **my-gitlab-api-token**" "http://**my-gitlab-host**/api/v4/projects/10/statuses/**sha-of-the-merge**?state=success"`

> merge status: success for URL  with target:  description: 
> Merge status checks all passed so the promotion worked!

Maybe the post should be added in the promote.go as an extra step for Gitlab provider.

Btw, Jenkins X is really amazing

**Comment by MastanaGuru** [comment]
I have the same issue with github, but after 15-20 tries it does complete.

**Comment by jasoncarreira** [comment]
Having this problem now... Any progress? @dimmel82 's curl suggestion got it past where it was stuck, but now it's stuck here:

```Pull Request http://foo/jcarreira/environment-jx-staging/merge_requests/3 is merged at sha 1d01672712987676d3f10a68e6f27671e89c7c3b

Merge commit has not yet any statuses on repo jcarreira/environment-jx-staging merge sha 1d01672712987676d3f10a68e6f27671e89c7c3b```

I think it's because the build pipeline for jx-staging is stuck here:
```jx step helm build

No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080

Adding missing Helm repo: jenkins-x http://chartmuseum.jenkins-x.io

Successfully added Helm repository jenkins-x.

Adding missing Helm repo: releases http://jenkins-x-chartmuseum:8080

Successfully added Helm repository releases.```

**Comment by erSitzt** [comment]
Where and when is the commit status set when using GitHub ?

**Comment by dimmel82** [comment]
For anyone interested, I'm using the following additional setup in the pipelines of environments (e.g. `environment-jx-staging` pipeline) to bypass the issue until the Jx-Gitlab integration is fully implemented:

> pipeline {
>   options {
>     disableConcurrentBuilds()
>     #Add a gitlab connection in the Jenkins configuration and use it here
>     gitLabConnection('<gitlab connection id>')
>   }
> ....
>   post {
>     failure {
>       updateGitlabCommitStatus name: "build${env.BUILD_NUMBER}", state: 'failed'
>     }
>     success {
>       updateGitlabCommitStatus name: "build${env.BUILD_NUMBER}", state: 'success'
>     }
>   }
> }

The only issue is that the "promote-" branch is not automatically deleted from the environment's git repo.

**Comment by erSitzt** [comment]
@dimmel82 thanks its working :)

i hope this issue and #3339 get fixed soon :)

**Comment by VonNaturAustreVe** [comment]
> Hi, I have the same issue. When I manually post the following to gitlab api the Jenkins job is completed:
> `curl --request POST --header "PRIVATE-TOKEN: **my-gitlab-api-token**" "http://**my-gitlab-host**/api/v4/projects/**my-project-id**/statuses/**sha-of-the-merge**?state=success"`
> 
> > merge status: success for URL  with target:  description:
> > Merge status checks all passed so the promotion worked!
> 
> Maybe the post should be added in the promote.go as an extra step for Gitlab provider.
> 
> Btw, Jenkins X is really amazing

This worked for me.

**Comment by dodwyer** [comment]
I added `--no-wait=true --no-poll=true` to my `jx promote` command and the automatic merge works as expected.

**Comment by VonNaturAustreVe** [comment]
> I added `--no-wait=true --no-poll=true` to my `jx promote` command and the automatic merge works as expected.

Thanks, --no-wait=true --no-poll=true work with me.
