### ISSUE TITLE
Seg faults with exposecontroller happening (unmarshalling config.yaml)

### ISSUE THREAD

**Issue by a-roberts** [jenkins-x/jx#1937]
### Summary 

I consistently see the following when using --tls-acme and an ingress option for my cloud provider myvalues.yaml. Not sure if an issue with my cloud provider or jx at this stage, curious if anybody else is hitting this too. So there's no config.yml somehow, and we try to unmarshal nothing? 

```
adams-mbp:jx aroberts$ k logs expose-q5njx
I1009 14:40:25.650686       1 exposecontroller.go:60] Using build: '2.3.71'
I1009 14:40:25.689075       1 config.go:22] No /etc/exposecontroller/config.yml file found.  Will try to figure out defaults
W1009 14:40:25.689116       1 exposecontroller.go:81] %!s(<nil>)
I1009 14:40:25.693123       1 exposecontroller.go:87] Using ConfigMap exposecontroller to load configuration...
W1009 14:40:25.693777       1 exposecontroller.go:93] Could not parse the config text from exposecontroller ConfigMap  failed to unmarshal config: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `--helm-...` into bool
I1009 14:40:25.693921       1 exposecontroller.go:95] Loaded ConfigMapexposecontroller to load configuration!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5ce8c]

goroutine 1 [running]:
main.main()
        /home/jenkins/go/src/github.com/jenkins-x/exposecontroller/_gopath/src/github.com/jenkins-x/exposecontroller/exposecontroller.go:103 +0x48c
```

Example install command:
`build/jx install --tls-acme  --helm-client-only=true   --skip-ingress   --provider=kubernetes (in my case I change it to be the cloud provider name I am working on)   --skip-tiller   --tiller-namespace=default   --external-ip=9.20.201.31 --domain=9.20.201.31.nip.io   --docker-registry=mycluster.icp:8500/jx`

Ingress option as follows, for Jenkins master:
```
 Master:
    ServiceAnnotations:
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/proxy-body-size: 500m\nkubernetes.io/tls-acme: true\ncertmanager.k8s.io/cluster-issuer: icp-ca-issuer"
    Readiness:
      InitialDelaySeconds: 10
    Liveness:
      InitialDelaySeconds: 10
```

### Steps to reproduce the behavior
Try install using a cloud provider with the following chart annotation:

And --tls-acme on the install command.

### Jx version
master

The output of `jx version` is:

```
1.3.400-dev+1bf5c22a
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
IBM Cloud Private 3.1,  runs Kube 1.11

### Operating system / Environment
Issue will be platform agnostic, but it's all x86-64 Linux

### Expected behavior
Not a seg fault

### Actual behavior
A seg fault 😢

**Comment by a-roberts** [comment]
Actually it's to do with --tls-acme: it should be --tls-acme=true. 

I searched on tls-acme in the jx repo and found https://github.com/jenkins-x/jx/blob/3787c05d00a423ce896fcb4bf5181c18261ddcf5/pkg/config/helm_values.go#L90

so presumably the solution to do this is to make sure a value gets set for it. I can't tell from our docs or `--help` output what other acceptable values for this are...

**Comment by johnmcollier** [comment]
Couldn't we just set the option to BoolVarP instead? If it only accepts true/false values then it should  only be set to that.

**Comment by johnmcollier** [comment]
Actually, looking further, it seems like it's not that simple. This commit https://github.com/jenkins-x/jx/commit/b6cc765fefaef8163835fdf5d2e07852ae1c31cd#diff-f2f70abbff35106f168908e7db627f58 shows that the Helm values that are boolean need to be quoted. So the options can't be set through BoolVarP.
