### ISSUE TITLE
jx create quickstart still prompts in batch mode

### ISSUE THREAD

**Issue by rajivnathan** [jenkins-x/jx#1953]
### Summary 
The `jx create quickstart` command prompts for selection even if the batch mode `-b` option is specified. This causes scripts to hang. This PR simply adds a check for batch mode and returns an error to avoid prompting.

### Steps to reproduce the behavior
jx create quickstart -b --language JavaScript --project-name testname

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.408
Kubernetes cluster v1.10.0
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.10.0+g9ad53aa
git                git version 2.17.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Minikube

### Operating system / Environment

Mac OSX

### Expected behavior
Should not prompt

### Actual behavior
Prompts

Proposed fix in https://github.com/jenkins-x/jx/pull/1952

**Comment by garethjevans** [comment]
Closing this issue as fix has been merged
