### ISSUE TITLE
Set default GitHub project PRIVATE

### ISSUE THREAD

**Issue by Larzack** [jenkins-x/jx#1977]
### Summary 
Hello, could you please set project created by Jenkins PRIVATE, for people who has private accounts, when Jenkins do something with GitHub ? All projects are OPENED ! All my enterprise data are accessible to competitors, this is a big security issue !

### Steps to reproduce the behavior
`jx create cluster eks`
`jx import`
etc..
### Jx version

The output of `jx version` is:
1.3.399

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AWS EKS created using `jx create cluster eks`

### Operating system / Environment
OS X 10.13.6 ( Changing soon to 10.14 )

### Expected behavior

Private repositories 

### Actual behavior

Opened repositories

**Comment by Larzack** [comment]
No, 

But private should be the default value. And you put it public when you want.

**Comment by paveq** [comment]
I agree, private should be default. Or at least it should be prompted and not come as a surprise to the user.

**Comment by ggilley** [comment]
Upvote for this one. Was surprised to find out my code was suddenly public.

**Comment by ccojocar** [comment]
@hferentschik Probably, this is related to the work you recently have done for private repositories https://github.com/jenkins-x/jx/pull/5284.
