### ISSUE TITLE
Import not working ( PHP/Symfony4/ApiPlatform project )

### ISSUE THREAD

**Issue by Larzack** [jenkins-x/jx#1978]
### Summary 

When I import a new ApiPlatform project ( https://github.com/api-platform/api-platform ) I have this issue : 

retrying after error:500 Server Error
error: error creating Jenkins credential jenkins-x-chartmuseum after 3 attempts, last error: 500 Server Error

### Steps to reproduce the behavior

1) You must have Composer installed
2) Install Symfony 
`composer create-project symfony/skeleton symfonyproject`
3) Install ApiPlatform 
`cd symfonyproject`
`composer require api`
4) Import the project
`jx import --pack php`

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.425
jenkins x platform 0.0.2755
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.0
helm client        v2.9.1+g20adb27
helm server        v2.10.0+g9ad53aa
git                git version 2.17.1 (Apple Git-112)

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AWS EKS created with `jx create cluster eks`

### Operating system / Environment

OS X 10.13.6

**Comment by jstrachan** [comment]
could you try re-importing - we've a working PHP quickstart now

**Comment by jstrachan** [comment]
this quickstart works great now btw https://github.com/jenkins-x-quickstarts/php-helloworld 

let us know if there's anything particularly different about your Symfony4 dockerfile etc
