### ISSUE TITLE
jx create spring -d web -d actuator fails at git add

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#200]
Running jx create spring -d web -d actuator fails under jx v1.0.40 with the following error:

Failed to run git add in /Users/Allan/test01 due to exit status 1

**Comment by cyrille-leclerc** [comment]
Could it be similar to #176 ? which version of git are you using (`git version`) ?  I had problems with git-2.16.1 and draft and I had to downgrade git to git-2.15.1.

**Comment by jstrachan** [comment]
@tdcox could you run this please:
```
$ git version
```
and list the output here

**Comment by tdcox** [comment]
2.14.3 (Apple Git-98)

**Comment by rawlingsj** [comment]
Not heard anymore reports of this.  Closing but please reopen if it's still a problem.
