### ISSUE TITLE
Old resources not removed by `jx step helm apply` in platform installed with --no-tiller

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#2003]
### Steps to reproduce the behavior

1. Install Jenkins-X with `jx install --no-tiller`
2. Promote application to environment
3. Remove application from environment

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: template-mode
NAME               VERSION
jx                 1.3.399
jenkins x platform 0.0.2755
Kubernetes cluster v1.9.8
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
git                git version 2.16.2
```

### Kubernetes cluster

AWS cluter created with kops via terraform.

### Expected behavior

Resources generated from helm chart that is removed from requirements.yaml is removed from the environment by the jenkins job for the environment, in particular by `jx step helm apply`.

### Actual behavior

No resources are removed.

**Comment by msvticket** [comment]
Looking at the code in `helm_template.go` it seems like the problem is that the version assigned to the label `jenkins.io/version` never changes. This version seem to come from the version in `Chart.yaml` in the environment repo, but that version is never changed.

Maybe it would be a good idea to have `jx step helm apply` make use of `jx-release-version` to find a new version number and then push a release tag.

**Comment by jstrachan** [comment]
@msvticket great catch. I was thinking of adding this command into the pipelines of the Environment git repos...
https://jenkins-x.io/commands/jx_step_helm_version/

`jx step helm version`

which would automate the upgrade of the chart version in `env/Chart.yaml` on each pipeline

**Comment by msvticket** [comment]
To try the idea out I changed the Jenkinsfile in an environment. I replaced 
```
sh 'jx step helm apply'
```
with
```
sh '''
	git checkout master
	git config --global credential.helper store
	jx step git credentials
	RELEASE_VERSION=`jx-release-version`
	sed -i -e "s/version:.*/version: ${RELEASE_VERSION}/" Chart.yaml
	jx step helm apply
	git tag -fa v$RELEASE_VERSION -m "Release version $RELEASE_VERSION"
	git push origin v$RELEASE_VERSION
'''
```

So far it seems to work

**Comment by msvticket** [comment]
Yeah, `jx step helm version` should work as well (and it's simpler than the solution I copied from an application Jenkinsfile). The problem with adding it to the Jenkinsfile of https://github.com/jenkins-x/default-environment-charts now is that it won't work for those of us that have already created our environments.

Couldn't `jx step helm apply` call UpgradeChart with a version fetched with getBuildNumber?

**Comment by jstrachan** [comment]
I guess we could optionally invoke `jx step helm version` in the `jx step helm apply` and do it by default - unless folks opt out of it? Then things will just work OOTB without folks changing it?

**Comment by msvticket** [comment]
Sounds good to me
