### ISSUE TITLE
jx create fails to install gcloud sdk

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2006]
### Summary 

downloaded `jx` (1.3.441) and attempted to create a new cluster with `jx create terraform --environment-git-owner cb-kubecd --verbose` 
I was told there was missing requirements and I left all options selected to install.

 Was then presented with

```
[gke-sso] C:\workarea\jx>jx create terraform --environment-git-owner cb-kubecd --verbose
? Missing required dependencies, deselect to avoid auto installing: gcloud, terraform, helm
error: error installing gcloud: please install missing gcloud sdk - see https://cloud.google.com/sdk/downloads#interactive
```

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
Failed to find helm installs: failed to run 'helm list' command in directory '', output: '': exec: "helm": executable file not found in %PATH%
Failed to get helm version: failed to run 'helm version --short' command in directory '', output: '': exec: "helm": executable file not found in %PATH%
NAME               VERSION
jx                 [32m1.3.441[0m
Kubernetes cluster [32mv1.9.7-gke.5[0m
kubectl            [32mv1.10.3[0m
git                [32mgit version 2.16.2.windows.1[0m```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GCP - but cluster doesn't exist as I am trying to create it.

### Operating system / Environment

Windows 10 

### Expected behavior

The download works and things progress

### Actual behavior

The download of gcloud failed and stuff bombed out.

**Comment by agentgonzo** [comment]
@jtnord  AFAIK the install of `gcloud` on Windows is a manual thing (because you have to go and click stuff)
It even says you should do it in the error: `please install missing gcloud sdk - see https://cloud.google.com/sdk/downloads#interactive`

Can we close this?

**Comment by jtnord** [comment]
https://cloud.google.com/sdk/install#installation_options. 

Besides there is still a bug even if you need to manually install it,. Namely it should not offer to install it for you...

**Comment by jtnord** [comment]
Also see using the interactive installer in non interactive mode...
https://cloud.google.com/sdk/docs/downloads-interactive#silent
