### ISSUE TITLE
jx says gcloud is not installed but it lies.

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2008]
### Summary 

nuff said...   gcloud is installed but jx says it is not...

### Steps to reproduce the behavior

grab a windows box. 
install gcloud sdk
try to create a cluster in GCP with jx create

### Jx version

The output of `jx version` is:

```
[gke-sso] C:\workarea\jx>jx create terraform --environment-git-owner cb-kubecd --verbose
? Missing required dependencies, deselect to avoid auto installing:  [Use arrows to move, type to filter]
> [x]  gcloud
  [x]  terraform
  [x]  helm
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

N/A

### Expected behavior

I am not told that gcloud is not installed when it is installed.

### Actual behavior

jx says gcloud is not installed.

**Comment by agentgonzo** [comment]
@jtnord I don't get this anymore - not sure if it's my environment or it has been fixed.

**Comment by garethjevans** [comment]
@agentgonzo I thought i'd fixed this, didn't realise there was a ticket open
