### ISSUE TITLE
Support multiple installs in a single cluster

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#2033]
### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.448
jenkins x platform 0.0.2781
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```

### Kubernetes cluster

EKS - created via jx

### Expected behavior

Ran `jx install --namespace xxx` and expected to end up with a Jenkins X install in that namespace.

### Actual behavior

Install failed with:
```
error: failed to wait for jenkinx-x chart installation to be ready: no deployments found in namespace xxx
```

There was already a Jenkins X install in another namespace in the cluster and it looks like the install just went ahead and Helm upgraded that.

At a minimum, it should cowardly fail the install upfront indicating that there is already an install in another namespace. Ideally, it should support multiple installs in a cluster (not every team has the luxury of just spinning up another cluster when they want to try something).

**Comment by garethjevans** [comment]
Hi @davidcurrie, this is an issue we face with helm/tiller, at the moment the only options are to use the --helm3 flag which will enable an alpha version of helm3 which doesn't suffer from this issue.  Or to use the helm template mode (I can't remember the flag for this of the top of my head)

**Comment by davidcurrie** [comment]
Why does helm/tiller prevent multiple installs? Because the release name is hard-coded? Would I have done better with `--global-tiller=false`?

**Comment by jstrachan** [comment]
We use multiple teams (installs) per cluster right now - we do this by disabling tiller via `—no-tiller` 
https://jenkins-x.io/news/helm-without-tiller/

We need this to avoid having a global tiller which enforces globally unique release names in helm (we default to `jx` right now).

**Comment by jstrachan** [comment]
we will switch to `—prow —no-tiller` by default soon for Jenkins X 2.0
