### ISSUE TITLE
jx step link services is not working

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#2037]
### Steps to reproduce the behavior

1. Have service logmessage in namespace core-test and another namespace as current
2. `jx step link services --from-namespace core-test  --includes logmessage`

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: template-mode
NAME               VERSION
jx                 1.3.448
jenkins x platform 0.0.2755
Kubernetes cluster v1.9.8
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
git                git version 2.16.2
```

### Expected behavior

The service logmessage being created in current namespace linking to logmessage in core-test.

### Actual behavior

The error message is shown:
```
Failed to create the service 'logmessage' in target namespace 'core-deniedboarding-userprofile-pr-3'. Error: Service "" is invalid: [metadata.name: Required value: name or generateName is required, spec.ports: Required value]
```

**Comment by steffenwald** [comment]
+1 same here.
