### ISSUE TITLE
Jenkinsfile placeholder replacement uses personal users owner not Organisation

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2042]
If you `jx create quickstart` in a GitHub organisation that you are part and use your personal github account to create the commit the Jenkinsfile placeholder replacement uses the users owner not the organisation. https://github.com/jenkins-x/draft-packs/blob/175f15f/packs/maven/Jenkinsfile#L6

**Comment by msvticket** [comment]
This sounds as the same as #1275
