### ISSUE TITLE
jx import will commit and push gitignored files

### ISSUE THREAD

**Issue by snoopdave** [jenkins-x/jx#2049]
### Steps to reproduce the behavior
- Create a Git repository and commit project files
- Add some files but do not commit them
- Create a .gitignore file to ignore those same files
- Run jx import to import the project
- The ignored files were committed and pushed to the project repo, and then should not have been.

### Jx version

The output of `jx version` is: 1.3.246

```
$ jx --version
1.3.246
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE created by jx

### Operating system / Environment

Mac

### Expected behavior
- Ignored files should be ignored and not commited or pushed to the repo

### Actual behavior
- Ignored files should be ignored and not commited or pushed to the repo

**Comment by jstrachan** [comment]
I guess the git add logic should ensure it add any `.gitignore` files if they are not already added first before adding everything else
