### ISSUE TITLE
Pipelines hung waiting for maven nodes

### ISSUE THREAD

**Issue by llizamab** [jenkins-x/jx#2050]
### Summary 
I started a jenkins x with google cloud tutorial and after create an application test with: jx create spring -d web -d actuator
The first build and deploy on stage works ok but after a few pulls request the maven nodes are always on failed state and the pipelines hung

### Steps to reproduce the behavior
follow the steps on https://jenkins-x.io/getting-started/tutorials/
create an app jx create spring -d web -d actuator
clone the repo. make some changes. push the branch
create a pull request to master
make some other changes
create another pull request to master

### Jx version

The output of `jx version` is:
```
jx                 1.3.450
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.10.7
helm client        v2.11.0+g2e55dbe
helm server        v2.10.0+g9ad53aa
git                git version 2.11.0
```
### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Following the tutorial on Creating your first JX install on GKE

### Operating system / Environment
Google cloud

### Expected behavior
jenkins nodes working

### Actual behavior
jenkins nodes fail

Some logs:

INFO: Waiting for Pod to be scheduled (96/100): maven-wwht7
Oct 20, 2018 5:13:29 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (97/100): maven-wwht7
Oct 20, 2018 5:13:29 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (97/100): maven-f1b51
Oct 20, 2018 5:13:35 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (98/100): maven-f1b51
Oct 20, 2018 5:13:35 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (98/100): maven-wwht7
Oct 20, 2018 5:13:41 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (99/100): maven-f1b51
Oct 20, 2018 5:13:41 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (99/100): maven-wwht7
Oct 20, 2018 5:13:47 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Template for label jenkins-maven: Kubernetes Pod Template
Oct 20, 2018 4:39:07 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: maven-bbqdn, template=PodTemplate{inheritFrom='', name='maven', slaveConnectTimeout=0, label='jenkins-maven', serviceAccount='jenkins', nodeSelector='', volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], SecretVolume [mountPath=/root/.m2/, secretName=jenkins-maven-settings], SecretVolume [mountPath=/home/jenkins/.docker, secretName=jenkins-docker-cfg], SecretVolume [mountPath=/home/jenkins/.gnupg, secretName=jenkins-release-gpg]], containers=[ContainerTemplate{name='jnlp', image='jenkinsci/jnlp-slave:3.14-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='100m', resourceRequestMemory='128Mi', resourceLimitCpu='', resourceLimitMemory=''}, ContainerTemplate{name='maven', image='jenkinsxio/builder-maven:0.1.21', privileged=true, workingDir='/home/jenkins', command='/bin/sh -c', args='cat', ttyEnabled=true, resourceRequestCpu='400m', resourceRequestMemory='512Mi', resourceLimitCpu='1', resourceLimitMemory='1024Mi'}], envVars=[ContainerEnvVar [getValue()=/home/jenkins/.docker/, getKey()=DOCKER_CONFIG], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_AUTHOR_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_AUTHOR_NAME], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_COMMITTER_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_COMMITTER_NAME], ContainerEnvVar [getValue()=http://jenkins:8080, getKey()=JENKINS_URL], ContainerEnvVar [getValue()=/home/jenkins, getKey()=XDG_CONFIG_HOME], ContainerEnvVar [getValue()=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m, getKey()=_JAVA_OPTIONS]]}
java.lang.IllegalStateException: Container is not running after 100 attempts, status: Pending
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:169)
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

llizamab@cloudshell:~/jx-tutorial (my-project-1527800405208)$ kubectl get pods
NAME                                                READY     STATUS      RESTARTS   AGE
jenkins-d7784d757-kbvxw                             1/1       Running     0          2h
jenkins-x-chartmuseum-645d78c798-snfbb              1/1       Running     0          2h
jenkins-x-controllercommitstatus-7467949fd6-znfzc   1/1       Running     0          2h
jenkins-x-controllerteam-858ff8c6b8-qxsl6           1/1       Running     0          2h
jenkins-x-controllerworkflow-945dfd4f6-f5mzh        1/1       Running     0          2h
jenkins-x-docker-registry-dcb6d6d44-wzjdx           1/1       Running     0          2h
jenkins-x-gcactivities-1540047600-gkhtb             0/1       Completed   0          2h
jenkins-x-gcactivities-1540049400-fhs72             0/1       Completed   0          1h
jenkins-x-gcpreviews-1540047600-txrlv               0/1       Completed   0          2h
jenkins-x-heapster-96bd95dcf-m5sms                  2/2       Running     0          2h
jenkins-x-mongodb-968b595dd-h4pmq                   1/1       Running     1          2h
jenkins-x-monocular-api-7c7f7b59cb-8dxrh            1/1       Running     5          2h
jenkins-x-monocular-prerender-6d8897856-cwxcj       1/1       Running     0          2h
jenkins-x-nexus-55f87888dc-rgjjm                    1/1       Running     0          2h
maven-2hbzt                                         0/2       Pending     0          24m
maven-39lxv                                         1/2       Error       0          58m
maven-4ldcv                                         0/2       Pending     0          17m
maven-4p1k7                                         1/2       Error       0          2h
maven-5bfcw                                         0/2       Pending     0          17m
maven-7hrx3                                         0/2       Pending     0          31m
maven-91klg                                         0/2       Pending     0          31m
maven-994rc                                         0/2       Pending     0          17m
maven-b7lbj                                         0/2       Pending     0          24m
maven-bbqdn                                         0/2       Pending     0          44m
maven-f1b51                                         0/2       Pending     0          10m
maven-g1vg9                                         1/2       Error       0          45m
maven-gdmsn                                         1/2       Error       0          2h
maven-l4f0q                                         1/2       Error       0          1h
maven-mf7xg                                         0/2       Pending     0          38m
maven-r5fq3                                         1/2       Error       0          2h
maven-rssvj                                         1/2       Error       0          1h
maven-sh0pc                                         1/2       Error       0          2h

llizamab@cloudshell:~/jx-tutorial (my-project-1527800405208)$ kubectl logs maven-sh0pc jnlp
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Warning: SECRET is defined twice in command-line arguments and the environment variable
Warning: AGENT_NAME is defined twice in command-line arguments and the environment variable
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
Oct 20, 2018 3:06:04 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: maven-sh0pc
Oct 20, 2018 3:06:04 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Oct 20, 2018 3:06:04 PM hudson.remoting.Engine startEngine
WARNING: No Working Directory. Using the legacy JAR Cache location: /home/jenkins/.jenkins/cache/jars
Oct 20, 2018 3:06:04 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins:8080]
Oct 20, 2018 3:06:04 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Oct 20, 2018 3:06:04 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins-agent
...
INFO: Trying protocol: JNLP4-connect
Oct 20, 2018 3:06:05 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: 67:e2:ce:e0:33:ea:61:bc:65:55:ea:90:3e:09:25:c2
Oct 20, 2018 3:06:05 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
Oct 20, 2018 3:13:03 PM hudson.util.ProcessTree get
WARNING: Error while determining if vetoers exist
hudson.remoting.RequestAbortedException: hudson.remoting.Channel$OrderlyShutdown
        at hudson.remoting.Request.abort(Request.java:329)
        at hudson.remoting.Channel.terminate(Channel.java:992)
        at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1225)
        at hudson.remoting.Channel$1.handle(Channel.java:560)
        at hudson.remoting.AbstractByteBufferCommandTransport.processCommand(AbstractByteBufferCommandTransport.java:202)
        at hudson.remoting.AbstractByteBufferCommandTransport.receive(AbstractByteBufferCommandTransport.java:188)
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onRead(ChannelApplicationLayer.java:186)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecv(ApplicationLayer.java:207)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
        at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
        at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
        at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at hudson.remoting.Engine$1$1.run(Engine.java:98)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection to jenkins-agent/10.35.249.225:50000
                at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
                at hudson.remoting.Request.call(Request.java:192)
                at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:284)
                at com.sun.proxy.$Proxy5.fetch3(Unknown Source)

Also my cluster increase to 5 instances. I don't know why a simple microservice need some many resources :(
I love the potential of jenkins-x and what can achieve. please any help, advice it will be aprecieted.

**Comment by jstrachan** [comment]
did the pipeline start for your app? If so what’s the log of the pipeline? Eg open the Jenkins console via `jx console`

What’s the output of `jx status`

Did it all work when you upped your cluster to 5 nodes?

A common issue is not enough nodes - particularly if using small nodes (a small number of large nodes is better than lots of little nodes). Did you use the default node sizes? If so 3 nodes should be fine on GKE.

We’re moving to Prow soon which has a much lower footprint (eg no Jenkins master & smaller build pods for promotion)
https://medium.com/@jdrawlings/serverless-jenkins-with-jenkins-x-9134cbfe6870

**Comment by ccojocar** [comment]
@llizamab I am going to close this issue, it seems to be outdated.
