### ISSUE TITLE
Failed to deploy artifacts: Could not transfer artifact

### ISSUE THREAD

**Issue by clsaa** [jenkins-x/jx#2052]
I finished ```jx install``` then ```$ jx create spring -d web -d actuator```, but something wrong in the end of  building process.

It likes jx don't have nexus password, but I find the password at jenkins-maven-settings in k8s.  And I also find the username and password in the file .

```
<settings>
      <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
      <localRepository>${user.home}/.mvnrepository</localRepository>
      <!-- lets disable the download progress indicator that fills up logs -->
      <interactiveMode>false</interactiveMode>
      <mirrors>
          <mirror>
          <id>nexus</id>
          <mirrorOf>external:*</mirrorOf>
          <url>http://nexus/repository/maven-group/</url>
          </mirror>
      </mirrors>
      <servers>
          <server>
          <id>local-nexus</id>
          <username>admin</username>
          <password>foxroad</password>
          </server>
      </servers>
      <profiles>
          <profile>
              <id>nexus</id>
              <properties>
                  <altDeploymentRepository>local-nexus::default::http://nexus/repository/maven-snapshots/</altDeploymentRepository>
                  <altReleaseDeploymentRepository>local-nexus::default::http://nexus/repository/maven-releases/</altReleaseDeploymentRepository>
                  <altSnapshotDeploymentRepository>local-nexus::default::http://nexus/repository/maven-snapshots/</altSnapshotDeploymentRepository>
              </properties>
          </profile>
          <profile>
              <id>release</id>
              <properties>
                  <gpg.executable>gpg</gpg.executable>
                  <gpg.passphrase>mysecretpassphrase</gpg.passphrase>
              </properties>
          </profile>
      </profiles>
      <activeProfiles>
          <!--make the profile active all the time -->
          <activeProfile>nexus</activeProfile>
      </activeProfiles>
  </settings>
```

```
[INFO] Installing /home/jenkins/workspace/clsaa_demo_master-6FA3G2D6MXHSYBLQSBJZN7WZYHSCXPU34BFU2FYLUABSJZHBVB3Q/target/demo-0.0.1.jar to /root/.mvnrepository/com/clsaa/demo/0.0.1/demo-0.0.1.jar
[INFO] Installing /home/jenkins/workspace/clsaa_demo_master-6FA3G2D6MXHSYBLQSBJZN7WZYHSCXPU34BFU2FYLUABSJZHBVB3Q/pom.xml to /root/.mvnrepository/com/clsaa/demo/0.0.1/demo-0.0.1.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ demo ---
[INFO] Using alternate deployment repository local-nexus::default::http://nexus/repository/maven-releases/
[INFO] Uploading to local-nexus: http://nexus/repository/maven-releases/com/clsaa/demo/0.0.1/demo-0.0.1.jar
[INFO] Uploading to local-nexus: http://nexus/repository/maven-releases/com/clsaa/demo/0.0.1/demo-0.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:45 min
[INFO] Finished at: 2018-10-21T10:57:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project demo: Failed to deploy artifacts: Could not transfer artifact com.clsaa:demo:jar:0.0.1 from/to local-nexus (http://nexus/repository/maven-releases/): Failed to transfer file: http://nexus/repository/maven-releases/com/clsaa/demo/0.0.1/demo-0.0.1.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Environments)
Stage "Promote to Environments" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
```

**Comment by clsaa** [comment]
same as https://github.com/jenkins-x/nexus/issues/12

**Comment by dimmel82** [comment]
I had the same problem after a recent upgrade of jenkins x platform to 0.0.3320 (not sure which version I had before, but it used to worked ok). The problem is with the `local-nexus` server id which does not match the `nexus` mirror id, so the credentials are not applied.
 A solution that I applied directly in the "Replay" pipeline while investigating the issue was to:
1. copy the read-only settings.xml to a new file,
2. replace the id using sed and
3. use the new file in the mvn steps:
>       steps {
>         container('maven') {
>           sh "cp /root/.m2/settings.xml settings.xml"
>           sh "sed -i 's/>nexus/>local-nexus/g' settings.xml"
>           
>           // ensure we're not on a detached head
>           sh "git checkout master"
>           ... other steps ...
>           sh "mvn -s settings.xml clean deploy"

To fix it more properly you can edit the `jenkins-maven-settings` secret and change the mirror id.

**Comment by garethjevans** [comment]
@dimmel82 you can use `jx upgrade platform --update-secrets` to regenerate the jenkins-maven-settings.xml

**Comment by garethjevans** [comment]
you may also need to add the flag `--always-upgrade` if you are already at 0.0.3320

**Comment by jglick** [comment]
Note that the recent regression was about the `<mirror>`, used to download artifacts from Central. My PR does _not_ fix this reported issue, which is about `deploy`ing new build products to Nexus, and which presumably has some unrelated cause (it works for me).

**Comment by dimmel82** [comment]
@jglick the fact that the anonymous access was disabled perfectly explains my question about what was the cause of the different behaviour after upgrading!!
And as you said, the problem that I faced is not the same with the current issue, as I could not download artifacts from nexus while this issue is about deploying artifacts.

**Comment by polothy** [comment]
Can confirm that this fixes it for us: `jx upgrade platform --verbose --log-level=debug --version=0.0.3402 --update-secrets --always-upgrade`

We were getting download errors though, not upload.  Though I suspect upload would fail too since auth was basically broken.

**Comment by fgeckeler** [comment]
/remove-lifecycle rotten

Is there any update on that issue?
I am exploring jx at the moment with the goal to create a custom buildpack. 
Sadly I get the same error as reported (401) [1]. Upgrading the platform with the --upgrade-secrets flag did not solve my issue.

I have a cluster running on GCP and all pods are available.

Maybe to add here: I get the same error when trying to deploy the go-http buildpack to chartmusuem [2]

[1]

>  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project jxSpring: Failed to deploy artifacts: Could not transfer artifact com.fgeckeler:jxSpring:jar:0.0.1-20190711.121700-1 from/to nexus (http://nexus/repository/maven-snapshots/): 
Failed to transfer file http://nexus/repository/maven-snapshots/com/fgeckeler/jxSpring/0.0.1-SNAPSHOT/jxSpring-0.0.1-20190711.121700-1.jar with status code 401 -> [Help 1]

[2]

> WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080 
Uploading chart file jxgo-0.0.1.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 401 response: {"error":"unauthorized"}

**Comment by Jeffery-L** [comment]
You need delete property config of 'altDeploymentRepository' in maven's version 2.8.2. 
else version,if deploy failed:
```xml
  <properties>
                  <altDeploymentRepository>local-nexus::default::http://nexus/repository/maven-snapshots/</altDeploymentRepository>
                  <!--altReleaseDeploymentRepository>local-nexus::default::http://nexus/repository/maven-releases/</altReleaseDeploymentRepository-->
                  <!--altSnapshotDeploymentRepository>local-nexus::default::http://nexus/repository/maven-snapshots/</altSnapshotDeploymentRepository-->
              </properties>
```
or 

```xml
	<distributionManagement>
		<repository>
			<id>local-nexus</id>
			<layout>default</layout>
			<url>http://nexus/repository/maven-releases/</url>
		</repository>
		<snapshotRepository>
			<id>local-nexus</id>
                        <layout>default</layout>
			<url>http://nexus/repository/maven-snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
```

try 一 try  :)

**Comment by TuralAsgar** [comment]
> I had the same problem after a recent upgrade of jenkins x platform to 0.0.3320 (not sure which version I had before, but it used to worked ok). The problem is with the `local-nexus` server id which does not match the `nexus` mirror id, so the credentials are not applied. A solution that I applied directly in the "Replay" pipeline while investigating the issue was to:
> 
> 1. copy the read-only settings.xml to a new file,
> 2. replace the id using sed and
> 3. use the new file in the mvn steps:
> 
> > ```
> >   steps {
> >     container('maven') {
> >       sh "cp /root/.m2/settings.xml settings.xml"
> >       sh "sed -i 's/>nexus/>local-nexus/g' settings.xml"
> >       
> >       // ensure we're not on a detached head
> >       sh "git checkout master"
> >       ... other steps ...
> >       sh "mvn -s settings.xml clean deploy"
> > ```
> 
> To fix it more properly you can edit the `jenkins-maven-settings` secret and change the mirror id.
> 
> Strange thing is that the MavenSettingsXML at jenkins-x-platform/values.yaml has not changed any time recently, so the real cause for the error may be somewhere else.

Using `mvn -s settings.xml clean deploy` worked for me.
Thank!

My problem was not jenkins related, I was trying to deploy using cli.
