### ISSUE TITLE
jx uninstall tries to delete default namespace

### ISSUE THREAD

**Issue by magnuhho** [jenkins-x/jx#2055]
### Summary 

jx uninstall seems to assume the default that jx is installed in whatever namespace is active at the time of execution

As a result, if you change active namespace, jx uninstall gives 
error: failed to delete team namespace namespace: failed to delete the namespace 'default': namespaces "default" is forbidden: this namespace may not be deleted

### Steps to reproduce the behavior

Setup k8s with Kubespray
bin/jx install --provider=kubernetes --on-premise

Change namespace for default context back to "default"
kubectl config set-context default-system --cluster=default-cluster --user=default-admin --namespace=default

Uninstall jx
jx uninstall

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.461
Kubernetes cluster v1.10.2
kubectl            v1.10.4
helm client        v2.9.1+g20adb27
helm server        v2.10.0+g9ad53aa
git                git version 1.8.3.1

```

### Kubernetes cluster

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Setup with Kubespray

### Operating system / Environment
CoreOS

### Expected behavior
I would expect jx uninstall to lookup which name space jx is installed in and then try to delete that one instead of the namespace configured for the current kubectl context

**Comment by johnmcollier** [comment]
I think a better approach would be for `jx uninstall` to check if there's a Jenkins-X installation installed in the specified (or current) namespace, as that will need to be done if multi-tenancy is supported in the future.

**Comment by markediez** [comment]
Maybe we could add labels to JX-created resources and only delete those resources on `jx uninstall`.

**Comment by jstrachan** [comment]
I guess we should label/annotate the namespace if its created via Jenkins X so we can know if we should uninstall it. Though for now maybe we just never try to delete the `default` namespace (as you can't delete it)

**Comment by alejandroandreu** [comment]
Hey! I've spent some time teaching myself Go and would like to give this issue a try to kickstart my Golang journey. Would you guys be OK with me working on it (at my own pace) by following your approach? That is:

1. Label namespaces (not sure if all resources?) that are created by `jx`
2. When calling `jx uninstall` it only deletes those namespaces

cc @jstrachan

**Comment by jstrachan** [comment]
welcome @alejandroandreu 

we have a helper method to get the 'dev' namespace for a team - e.g. if the user is in the `jx-staging` repo it'll return the `jx` namespace correctly.

```
	jxClient, devNs, err := o.JXClientAndDevNamespace()
```

if `devNs` is empty then we could try find all the Namespaces with a team label on it - if there is > 1 then prompt the user to pick one to delete. This is kinda the logic in `jx team` right now which we could copy/paste...

https://github.com/jenkins-x/jx/blob/9bb0b3ecc935705d52faef28e0a39bdcbd263095/pkg/jx/cmd/team.go#L78-L98

**Comment by alejandroandreu** [comment]
After poking with the code I realized I've got a lot to learn re. certain libreries and so on, so if anyone wants to tackle this issue please go ahead.
