### ISSUE TITLE
why select organisation does't take effect ?

### ISSUE THREAD

**Issue by wodog1** [jenkins-x/jx#2068]
### Summary 

```bash
jx create quickstart
```

![image](https://user-images.githubusercontent.com/24648185/47376570-8c281900-d725-11e8-8f52-05c3e346ccd0.png)

why select **backend** organisation, but actually create **gitlab username** repo

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.465
jenkins x platform 0.0.2771
Kubernetes cluster v1.11.2
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.13.6 (Apple Git-96)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior
create repo `https://git.kid17.com/backend/golang-http`

### Actual behavior
create repo `https://git.kid17.com/wodog/golang-http`

**Comment by stieler-it** [comment]
We are experiencing the same problem using GitLab. Which Git provider are you using?

**Comment by rawlingsj** [comment]
Agreed this is an issue and I've seen I think a related issue where the build pipeline fails to clone the repo because `jx` does the placeholder replacement in the Jenkinsfile with the org/repo names before folks choose them.  The placeholder replacement is using the defaults.

I wonder if we need to move the org / name questions above the placeholder replacement? https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L515-L518

/kind bug
/priority important-soon

**Comment by jstrachan** [comment]
I just tried this with the latest jenkins x binary (`1.3.673`) and it used the selected github organsation - I tried a golang and nodejs quickstart and both worked great

**Comment by stieler-it** [comment]
I just tried this with latest jenkins x binary (1.3.791) and it still fails to use the selected orgainzation. 

```
? Which organisation do you want to use? org1
...
app name: spring-demo, git server: gitlab.intern.gec.io, org: org1, Docker registry org: org1
...
About to create repository spring-demo on server https://gitlab.our.domain/ with user wrong
...
Creating repository org1/spring-demo
Pushed Git repository to https://gitlab.our.domain/wrong/spring-demo
```

where `org1` is the organization I chose and `wrong` is my username.

@jstrachan did you maybe miss that the OP is using Gitlab as you are speaking of github organizations?

Please re-open.
