### ISSUE TITLE
Integrate semantic release

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#2085]
### Summary 

There is a version of semantic release for go - https://github.com/go-semantic-release/semantic-release - if we integrate this into JX then we can have commit messages drive version number changes. 

### Expected behavior

When you run`jx step next-version --semantic` use semantic-release to create the next version number.

**Comment by amuniz** [comment]
That library uses the GitHub HTTP API to get the information to calculate the new version. Is this the approach to follow here? All needed information is available locally (within the Git clone), so I don't think using HTTP requests is the best thing in this context.

An adapter layer could be written to create `semrel.Commit` objects from the local clone commits, but that seems a bigger task to me and I'm not sure if it is worth the effort.

What do you think?

**Comment by pmuir** [comment]
I hadn't looked at the code, I assumed it was like semantic-release, which just works locally. It would be better to not tie this to GitHub, I agree. Maybe there is another library we can use, or like you say perhaps we can contribute the support upstream.
