### ISSUE TITLE
Question --- JenkinsX/EKS -VPC/Subnet/SecurityGroups-

### ISSUE THREAD

**Issue by rainmanh** [jenkins-x/jx#2095]
### Summary 

This is more a question.
I have read all what I could but I haven't really found what I need.

I am trying to spin an AWS/EKS cluster within a pre-defined VPC, certain Subnets and SecurityGroups without Internet Access.
I have been testing the solution as it is, out of the box, but I haven't really found within the multiple flags/options anything of that sort.

Would be possible to have any guidance in that direction?

Many thanks

**Comment by rainmanh** [comment]
I think I have posted in the wrong repository when this should happen in `eksctl` instead
Apologies

**Comment by jtnord** [comment]
Hi @rainmanh

Please use the [slack](https://jenkins-x.io/community/#slack) or the [mailing list](https://jenkins-x.io/community/#email) for user related questions.

Thanks
