### ISSUE TITLE
Could not find URL for service jenkins in namespace jx

### ISSUE THREAD

**Issue by wangxiang5050** [jenkins-x/jx#2096]
### Jx version
The output of `jx version` is:
jx                 1.3.474

### Actual behavior
Hi, I'm using jenkin-x, but when all pods are running, command "jx status " print an error message "error: Could not find URL for service jenkins in namespace jx". And I think it's related to ingress, but I don't know how to reslove it.

[root@service1 jenkins-x]# kc get pods
NAME                                               READY   STATUS      RESTARTS   AGE
curl-5cc7b478b6-p7fzp                              1/1     Running     1          22m
jenkins-86b44c8c7b-qnsdq                           1/1     Running     0          4h27m
jenkins-x-chartmuseum-75d45b6d7f-zfjcm             1/1     Running     0          4h27m
jenkins-x-controllercommitstatus-d865b5695-gwkmq   1/1     Running     0          4h27m
jenkins-x-controllerteam-7f965c8b9c-p89hn          1/1     Running     0          4h27m
jenkins-x-controllerworkflow-c674f6657-stwrh       1/1     Running     0          4h27m
jenkins-x-docker-registry-6d555974c7-48f5k         1/1     Running     0          4h27m
jenkins-x-gcactivities-1540528200-spvnv            0/1     Completed   0          3h11m
jenkins-x-gcactivities-1540537200-bk9xw            0/1     Completed   0          41m
jenkins-x-gcactivities-1540539000-hgv7l            0/1     Completed   0          12m
jenkins-x-gcpreviews-1540526400-5cvrb              0/1     Completed   0          3h41m
jenkins-x-gcpreviews-1540537200-kjjtb              0/1     Completed   0          41m
jenkins-x-heapster-65d7b4bb5d-zmfd9                2/2     Running     0          4h22m
jenkins-x-mongodb-696fdf64fc-c95l8                 1/1     Running     0          4h27m
jenkins-x-monocular-api-6d78cdb696-hgcgf           1/1     Running     6          4h27m
jenkins-x-monocular-prerender-77f6cd8449-7pzgs     1/1     Running     0          4h27m
jenkins-x-monocular-ui-76f44c687-5cfpk             1/1     Running     0          4h27m
---
[root@service1 jenkins-x]# kc get pods -n kube-system | grep ingress
jxing-nginx-ingress-controller-75dbf5ddd5-qpjcg        1/1     Running   0          3h44m
jxing-nginx-ingress-default-backend-568dc9b8d9-9mz6s   1/1     Running   0          3h44m
---
[root@service1 jenkins-x]# jx status 
? Pick service to open:  jenkins
Cluster(kubernetes): 3 nodes, memory 7% of 98038092Ki, cpu 15% of 12 Jenkins not found
error: Could not find URL for service jenkins in namespace jx

**Comment by enkicoma** [comment]
How you fix it?

**Comment by dhorskyi** [comment]
same...

**Comment by mdcsaenz** [comment]
same..

**Comment by ahmade3** [comment]
same

**Comment by mohamedazizhorrigue** [comment]
same
