### ISSUE TITLE
switch references of https://chartmuseum.build.cd.jenkins-x.io to http://chartmuseum.jenkins-x.io  to ensure HA 

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2102]
There still seems to be references to https://chartmuseum.build.cd.jenkins-x.io/ which causes severe issues if we recreate the prod cluster.  All charts are backed up to google storage and the highly available endpoint is http://chartmuseum.jenkins-x.io

This has caused downtime to Jenkins X users today and this should not happen again.

BTW bonus points if we can also make this https.  As it's out of cluster we can't use jx integration with cert manager handle it, need to find a way.

**Comment by beebird** [comment]
Hi @rawlingsj ，

The new repo endpoint is hosted on googleusercontent.com, which is indeed faster and more reliable, while the connection always gets reset by Chinese GFW...  

Before the switch, ``helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io/`` was very slow but sometimes worked.  But now ``helm repo add jenkins-x http://chartmuseum.jenkins-x.io`` fails forever... 

So can we use another site to host the repo? Or use some CDN such as cloudflare?

BTW, I think [the repository address in requirements file of the default environment repo](https://github.com/jenkins-x/default-environment-charts/blob/master/env/requirements.yaml) needs an update.

**Comment by rawlingsj** [comment]
Ah thanks for the link to the old endpoint, fixed https://github.com/jenkins-x/default-environment-charts/commit/4a9e98cb51e5f2ce9eb877dc948ea7ad885fcce0

dam - didn't realise that URL doesn't work behind GFW.  @i0n can you think of any options here?

**Comment by pmuir** [comment]
If we have access to a CDN (like cloudflare or akamai) we should be able to introduce e.g. .cdn.jenkins-x.io and then have it mirror out the repo - but we do need a CDN.

**Comment by beebird** [comment]
Thanks for the reply. My current workaround is to synchronize the ``index.yaml`` to a object storage(similar to AWS S3) and customize my environment repo like this:
in ``Jenkinsfile``
```diff
+            sh 'helm repo add jenkins-x https://<endpoint of object storage>/charts/jenkins-x'

+            # hack to cheat helm as if the repo is added with the correct url 
+            # so jx won't try to add it again and get stuck

+            sh 'sed -i \'s/https:\\/\\/<endpoint of object storage>\\/charts\\/jenkins-x/http:\\/\\/chartmuseum.jenkins-x.io/\' ~/.helm/repository/repositories.yaml'
             sh 'jx step helm build'
```

Because I don't use exposecontroller in staging/production environments, so I can safely comment them out in ``/env/requirements.yaml``
```diff
+#- alias: expose
+  #name: exposecontroller
+  #repository: http://chartmuseum.jenkins-x.io
+  #version: 2.3.58
+#- alias: cleanup
+  #name: exposecontroller
+  #repository: http://chartmuseum.jenkins-x.io
+  #version: 2.3.58
```

**Comment by ysaakpr** [comment]
Team, what is the appropriate way to address this issue. Should i upgrade jx-platform or can I update the variable some where to update to the new URL

**Comment by pmuir** [comment]
A `jx upgrade platform` and `jx upgrade cli` should do the trick!

**Comment by rawlingsj** [comment]
I think we can close this issue although to @beebird point we do need to have a better solution to handle the Chinese GFW.

@beebird would you be happy creating a specific issue about that?
