### ISSUE TITLE
Prow Jenkins config issues

### ISSUE THREAD

**Issue by stevef1uk** [jenkins-x/jx#2106]
On GKE created a cluster of 3 nodes using latest k8s version with 2VCPus each as I found that it didn't build anything.

Basically, I needed to change the Jenkins configuration Cloud section set-up to:

1.  Add a credential selected 'kind' = Kubernetes Service Account  with 'Secret Text'
2. Changed the cosmincojocar/builder-dlang in the Docker Image field of the dlang Kubernetes pod template to jenkinsxio/builder-dlang

After doing this I got around the errors preventing a build working

**Comment by stevef1uk** [comment]
ok next issue:


[Pipeline] }
[Pipeline] // dir
[Pipeline] dir
Running in /home/jenkins/go/src/github.com/stevef1uk/serverless-jenkins-demo/charts/serverless-jenkins-demo
[Pipeline] {
[Pipeline] sh
[serverless-jenkins-demo] Running shell script
+ git config --global credential.helper store
[Pipeline] sh
[serverless-jenkins-demo] Running shell script
+ jx step validate --min-jx-version 1.1.73
/home/jenkins/go/src/github.com/stevef1uk/serverless-jenkins-demo/charts/serverless-jenkins-demo@tmp/durable-536236aa/script.sh: 2: /home/jenkins/go/src/github.com/stevef1uk/serverless-jenkins-demo/charts/serverless-jenkins-demo@tmp/durable-536236aa/script.sh: jx: not found

**Comment by ccojocar** [comment]
@stevef1uk are you still facing these issues?

**Comment by stevef1uk** [comment]
No idea. I deleted the cluster & gave up. I try occasionally to give this project a chance to stabilise, but so far haven't got it to work.

**Comment by ccojocar** [comment]
The prow installation has improved since you opened the issue. I will give it a go again. 

Closing this issue since these problems are a bit old, and I think they are fixed by now. Please open another issue if you see them occurring again. Thanks
