### ISSUE TITLE
Prow quickstarts not using DOCKER_REGISTRY

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#2116]
### Summary 

Jenkins builds fail when running with prow enabled on EKS:
```
time="2018-10-29T17:04:16Z" level=fatal msg="build step: building [changeme]: tagging: Error parsing reference: \"<no value>:<no value>/davidcurrie/golang-http:0.0.0-SNAPSHOT-PR-1-1\" is not a valid repository/tag: invalid reference format"
```

Looks like the `prow` branch of the quickstarts is still using `JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST` and `JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT` which are only available in an environment where Jenkins X is installing its own Docker registry (e.g. GKS). They need to switch to use `DOCKER_REGISTRY` as on the 2.x branches.

### Steps to reproduce the behavior

1. `jx create cluster eks`
2. `jx create quickstart`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.483
jenkins x platform 0.0.2789
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```

### Kubernetes cluster

EKS cluster

### Expected behavior

Build completes successfully.

### Actual behavior

Build fails.

**Comment by jtnord** [comment]
@davidcurrie is this now fixed?

**Comment by davidcurrie** [comment]
It is
