### ISSUE TITLE
jx create spring does not build with serverless jenkins

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2118]
### Summary 
When creating a spring boot app using `jx create spring`, the builds are failing.

### Steps to reproduce the behavior

1. jx create spring
2. open a PR on the new project
3. Trigger the build by commenting `/test this`

### Jx version

jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.485
jenkins x platform 0.0.2789
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1

### Kubernetes cluster

GKE using terraform

### Operating system / Environment
Ubuntu 18.04

### Expected behavior
Build should succeed

### Actual behavior
Build is failing with the following logs:

`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.923 s
[INFO] Finished at: 2018-10-30T11:28:37Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project jx-test: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire/surefirebooter2030877174127674869.jar /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire 2018-10-30T11-28-36_929-jvmRun1 surefire5950687462811555027tmp surefire_05204490327293782982tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire/surefirebooter2030877174127674869.jar /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire 2018-10-30T11-28-36_929-jvmRun1 surefire5950687462811555027tmp surefire_05204490327293782982tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:494)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:441)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:293)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire/surefirebooter2030877174127674869.jar /tmp/jenkinsTests.tmp/jenkins7389192482474338033test/workspace/job/target/surefire 2018-10-30T11-28-36_929-jvmRun1 surefire5950687462811555027tmp surefire_05204490327293782982tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:429)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:406)
[ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Release)
Stage "Build Release" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Environments)
Stage "Promote to Environments" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
`

**Comment by pmuir** [comment]
https://stackoverflow.com/questions/50661648/spring-boot-fails-to-run-maven-surefire-plugin-classnotfoundexception-org-apache/50661649#50661649

**Comment by romainverduci** [comment]
@pmuir Thanks for the workaround !
Should we set that in the template when the project is created ?

**Comment by garethjevans** [comment]
@pmuir do we need to allocate more memory/cpu to this build template?

**Comment by pmuir** [comment]
I should have updated the issue, this is actually caused by a bug in surefire that was introduced by Debian upgrading OpenJDK 8 quite 'promptly'. See https://github.com/apache/maven-surefire/pull/197 - I believe that the right answer is for us/Spring to upgrade to the newer surefire (or we could go back to an older OpenJDK but IIRC the fix from Debian was a security fix, so probably not a good idea?)

**Comment by pmuir** [comment]
Also https://issues.apache.org/jira/browse/SUREFIRE-1588

**Comment by Tibor17** [comment]
There is a release Vote. https://lists.apache.org/thread.html/b3bf172d2ff909be34d5ab04605299d60749e1ec1537183fa254d8dd@%3Cdev.maven.apache.org%3E
Pls use the staging repo, check it out with version 3.0.0-M1 and put your `+1` in the Vote. Thx

**Comment by Tibor17** [comment]
@pmuir Version `3.0.0-M1` is on Maven Central now.

**Comment by pmuir** [comment]
Thanks @Tibor17 - testing it out!

**Comment by jstrachan** [comment]
we got the updatebot mvn plugin to update the `maven-deploy-plugin` in any `pom.xml` as old versions of that plugin caused issues - we could do similar things to force an upgrade of the surefire plugin?

**Comment by jstrachan** [comment]
https://github.com/jenkins-x/jx/blob/b14555952d33d1e5e2876edf04e691872a6aa657/pkg/jx/cmd/import.go#L1379

we could try doing something similar - adding this code...

```go
		out, err := options.getCommandOutput(dir, "mvn", "io.jenkins.updatebot:updatebot-maven-plugin:RELEASE:plugin", "-Dartifact=maven-surefire-plugin", "-Dversion=3.0.0-M1")
		if err != nil {
			return fmt.Errorf("Failed to update maven plugin: %s output: %s", err, out)
		}
```

**Comment by jstrachan** [comment]
though we probably need surefire to be upgraded in the base spring parent pom really
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.0.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```
I wonder if spring boot are gonna upgrade soon?

**Comment by jstrachan** [comment]
that seemed to work fine!
https://github.com/jstrachan/demo167/commit/76244326068e3d702ce5e51416b3e25abc928246

lemme push the code change

**Comment by pmuir** [comment]
I would think it will be a while before Spring Boot upgrade as this is only an M1 and I guess they will want to wait. Though it depends on how widespread this Java update (that causes the surefire issue to occur) becomes.

**Comment by Tibor17** [comment]
The plan in 3.0.0-Mx is to make frequent releases. This means We have to however break backwards compatibility in order to get rid of critical and blocker issues, but meanwhile at least `3.0.0-M2` would be dedicated to bugfixing and JUnit5 support. In some later milestone we would make bigger change in the API and additionally we will drop some deprecated config parameters. Then we will introduce Extensions to Surefire and Failsafe plugin which is the target of release of version 3.0.0. With these extensions we want to give the user to `plugin` already the Maven plugin Surefire and Failsafe. We expect smaller workload on Jira issues after these Extensions.
