### ISSUE TITLE
JenkinsX offline installation

### ISSUE THREAD

**Issue by mordf** [jenkins-x/jx#2120]
Provide the ability to install JenkinsX in a totally disconnected environment, the preliminary steps which should be taken (the one's that I could think of) prior to installation in such an environment are: 
1) Adding all the needed Docker images i.e: **jenkinsxio/builder-maven** to your private registry with the correct tag
2) Redirecting all calls to the Docker images in **values.yaml** files, **Dockerfiles** and several **.go** files to your private registry, it's best if it would be done dynamically by adding the private registry using some environment variable or by CLI switch something like **PRIVATE_REGISTRY** variable or **jx create --ofline --private-registry=[yourRegistry]**
3) For starters this feature would probably work only on existing Kubernetes clusters, maybe at a later stage combine it with something like Kubespray which would create the cluster as well

These are the things I could think of, please add what ever you think would be helpful for this feature.

**Comment by rawlingsj** [comment]
Related discussion on reddit https://www.reddit.com/r/jenkinsci/comments/cefkmt/our_ama_with_jenkins_x_experts_starts_now/
