### ISSUE TITLE
projects created outside the org do not trigger from Prow

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2122]
### Summary 

I ran jx create quickstart and ended up creating a project against the buildbot user rather than the organsiation.

the project is registered and will build when things are merged to a branch but pull-requests do not build (even after `/approve` `/ok-to-test`)

### Steps to reproduce the behavior

create a serveless JX install.
`jx create quickstart`

choose the buildbot user and not an organisation to store the repo. (to be honest I do not recall where I chose the user rather than an organisation, it could have been when creating the cluster, but the environments repositories where created under the organisation)

### Jx version

(jx has been upgraded a few times since)

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 [32m1.3.441[0m
jenkins x platform [32m0.0.2771[0m
Kubernetes cluster [32mv1.9.7-gke.6[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.11.0+g2e55dbe[0m
helm server        [32mv2.11.0+g2e55dbe[0m
git                [32mgit version 2.16.2.windows.1[0m
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

gke created with terraform option to jx create

### Operating system / Environment

Windows

### Expected behavior

PRs will build in the cluster when they are approved for testing

### Actual behavior

PRs do not build and are not approved.
see https://github.com/jenkins-x-bot-test/james-stoopid-test-project/pull/2
Note I am in the OWNERS file for the repo...

![image](https://user-images.githubusercontent.com/494726/47730459-17d80300-dc5a-11e8-8cee-ed8ff84e4568.png)

**Comment by ccojocar** [comment]
@jtnord Is this still an issue with the current version?

**Comment by ccojocar** [comment]
@jtnord I am going to close this issue. Probably the other project is not configured in prow as a job.
