### ISSUE TITLE
nexus password not updated when running jx install on existing installation

### ISSUE THREAD

**Issue by hangchan** [jenkins-x/jx#2123]
### Summary 
Nexus admin password does not get updated after running "jx install" again after the initial install
### Steps to reproduce the behavior
jx install
### Jx version
1.3.488
The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.488
jenkins x platform 0.0.2806
Kubernetes cluster v1.11.3
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior
nexus password is updated to the one that is displayed after jx installs successfully
### Actual behavior
it's using the old password from the initial install of jx

**Comment by ccojocar** [comment]
@hangchan Is this sill an issue with the latest version?

**Comment by hangchan** [comment]
This is still an issue.

**Comment by ccojocar** [comment]
I think is a dup of #3060.
