### ISSUE TITLE
Error to install Jenkins X on a AWS Cluster

### ISSUE THREAD

**Issue by nattymachado** [jenkins-x/jx#2135]
### Summary 
I am trying to install Jenkins X on an existent cluster and I am getting an error when it is creating Jenkins Folder.

### Steps to reproduce the behavior
1. Set the KUBECONFIG with the configurations of the cluster.
2. Execute this command to install: 
  `  jx install --provider=aws --verbose=true --log-level=debug`
3. Insert a valid wildcard DNS ALIAS
4. Access the Jenkins Server and create a Token
5. Insert the created Token

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.362
jenkins x platform 0.0.2806
Kubernetes cluster v1.9.10
kubectl            v1.7.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.7.4

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
The cluster was created on AWS using Kops.

### Expected behavior
The folder created on Jenkins Server

### Actual behavior
I am getting this error: 

```
Created environment staging
retrying after error:Failed to create the nattymachado folder in Jenkins: unexpected end of JSON input
retrying after error:Failed to create the nattymachado folder in Jenkins: unexpected end of JSON input
retrying after error:Failed to create the nattymachado folder in Jenkins: unexpected end of JSON input
```

**Comment by nattymachado** [comment]
I tested with the new version of jx and I am facing the same problem:

 jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.495
jenkins x platform 0.0.2806
Kubernetes cluster v1.9.10
kubectl            v1.7.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.7.4

**Comment by nattymachado** [comment]
The problem was the Proxy...

**Comment by jtnord** [comment]
@nattymachado can you give some more details on what was wrong with the proxy?
was it returning a response code other than `200` or is there anything else we could do to detect this issue in code and display a more helpful error?

**Comment by ccojocar** [comment]
No follow up. Closing this issue.
