### ISSUE TITLE
REPLACE_ME_ORG contains username not org

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#2136]
### Summary 

When running `jx create quickstart`, the replacement of `REPLACE_ME_ORG` in the draft generated content happens before the target git org has actually been selected - it, therefore, defaults to using the selected git username instead. This means that, for example, any `git` commands in the Jenkinsfile are attempting to checkout the source from the wrong organization.

### Steps to reproduce the behavior

Run `jx create quickstart` and select an organization that does not match the selected user.

### Jx version

The output of `jx version` is:

```
jx                 1.3.483
jenkins x platform 0.0.2806
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```

### Kubernetes cluster

```
jx create cluster eks --region=us-east-1 -z us-east-1a,us-east-1b,us-east-1c -n cloudbees-dcurrie-prow -p cloudbees-arc --prow --git-username=demo-bot --nodes 4 --domain currie.cloud
```

### Expected behavior

`REPLACE_ME_ORG` contains the selected git org name.

### Actual behavior

`REPLACE_ME_ORG` contains the selected git user name.

**Comment by msvticket** [comment]
I would guess that @ccojocar was confusing #1839 with another issue I created: #1275. I do think this issue is a dup of #1275.

**Comment by davidcurrie** [comment]
Either way, it does now appear to be resolved!
