### ISSUE TITLE
ECR interactions use default IAM profile

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#2137]
### Summary 

On a JX cluster created on EKS specifying a particular IAM profile, the ECR registry specified in `jenkins-x-docker-registry` and under which repositories are created by `jx import` or `jx create quickstart` is, instead, using the default profile. When the pipeline comes to push to the repository the EKS node role does not have permission.

### Steps to reproduce the behavior

```
jx create cluster eks --region=us-east-1 -z us-east-1a,us-east-1b,us-east-1c -n cloudbees-dcurrie-prow -p cloudbees-arc --prow --git-username=demo-bot
kubectl get configmap jenkins-x-docker-registry -o yaml
```

The specified registry is for the root user that is the `default` profile in `~/.aws/credentials` and not for the profile `cloudbees-arc`.

### Jx version

The output of `jx version` is:

```
jx                 1.3.483
jenkins x platform 0.0.2806
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```

### Kubernetes cluster

See above.

### Expected behavior

Registry should match the profile specified on cluster creation.

### Actual behavior

Registry is based on default profile.

**Comment by jtnord** [comment]
@davidcurrie if you used the default IAM profile then this would be for everything for all teams which, naively, to me would sound like it would be an issue?
