### ISSUE TITLE
Error on `jx create devpod`

### ISSUE THREAD

**Issue by amuniz** [jenkins-x/jx#2157]
### Summary 

Error on `jx create devpod`

### Steps to reproduce the behavior

```
$> jx create devpod
? Pick which kind of DevPod you wish to create:  go
Namespace jx-edit-amuniz created 
 Installing the ExposecontrollerService in the namespace: jx-edit-amuniz
Updating Helm repository...
Using helmBinary helm with feature flag: none
Helm repository update done.
error: failed to run 'helm upgrade --namespace jx-edit-amuniz --install --force --timeout 6000 --version  jx-edit-amuniz-es jenkins-x/exposecontroller-service' command in directory '', output: 'Error: failed to download "jenkins-x/exposecontroller-service" (hint: running `helm repo update` may help)': exit status 1
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.465
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.10.0+g9ad53aa
git                git version 2.7.4
```

### Kubernetes cluster

This was in the JX prod cluster.

### Operating system / Environment

Ubuntu 16.04

### Expected behavior

The dev pod to be created, I guess.

### Actual behavior

Error message.

**Comment by amuniz** [comment]
The error must be blocking the creation of the pod, as `jx rsh -d` does not work.

**Comment by jeremy-seiu** [comment]
I'm encountering this on 1.3.788 (helm 2.12.2)

**Comment by ccojocar** [comment]
@amuniz I am going to close this issue. It seems that with the current version the devpod can be created. Fell free to open another issue if you still see the problem occurring again. Thanks
