### ISSUE TITLE
Offer CLI on Snap Store

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2158]
For Linux users, especially Ubuntu, lots of useful tools are available via the `snap` packager. For example, that is the simplest way to install [`gcloud`](https://snapcraft.io/google-cloud-sdk) or (Tillerless) [`helm`](https://snapcraft.io/helm) or even [`kubectl`](https://snapcraft.io/kubectl). We should make `jx` available this way too, so people do not have to go through [this ugly installation process](https://jenkins-x.io/getting-started/install/#linux) and [manually upgrade](https://jenkins-x.io/commands/jx_upgrade_cli/).

AFAICT, what would be involved is for `Makefile#release` to run the snap tool (most easily [via Docker](https://docs.snapcraft.io/build-on-docker/4158)), given a [`snap.yaml`](https://docs.snapcraft.io/the-snap-format/698) kept in the `jx` repo defining a [prebuilt app](https://docs.snapcraft.io/pre-built-apps/6739) with the right version substituted, plus [tab completion](https://docs.snapcraft.io/tab-completion-for-snaps/2261) via `./build/linux/jx completion bash` and using [classic confinement mode](https://blog.ubuntu.com/2017/01/09/how-to-snap-introducing-classic-confinement) since this is a developer tool expected to have widespread filesystem access. Then someone on the JX team would need to [create a developer account](https://docs.snapcraft.io/creating-your-developer-account/6760) and add the credentials to whatever `Secret` you have in your cluster and reference via `Jenkinsfile`, [register](https://docs.snapcraft.io/registering-your-app-name/6793) the name `jenkins-x` (the actual command would continue to be `jx`), and have the `release` target [push a `stable` release](https://docs.snapcraft.io/releasing-your-app/6795).

**Comment by jtnord** [comment]
not sure this is a particularly great idea, especially for `helm` as the local version needs to match the version installed in the cluster otherwise things don;t work.  with `snap` helm would be upgraded to the latest release automatically (as decided by the publisher of helm) which could break your ability to manage `jx`.

**Comment by jglick** [comment]
/remove-lifecycle stale

Would still love to see this, so that I do not need to include `jx upgrade cli` in my system update script!

**Comment by jglick** [comment]
> for `helm` as the local version needs to match the version installed in the cluster

This should no longer be an issue as of Helm 3.
