### ISSUE TITLE
Unable to create Quickstart Project for serverless

### ISSUE THREAD

**Issue by idea360** [jenkins-x/jx#2160]
### Summary 
Unable to create quickstart with Jenkins X Serverless on EKS.

### Steps to reproduce the behavior

```
jx create quickstart
error: No quickstarts match filter
```

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.508
jenkins x platform 0.0.2806
Kubernetes cluster v1.10.3-eks
kubectl            v1.12.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.19.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AWS EKS Cluster
```
jx install --domain  myrealdomain.com
```

### Operating system / Environment
```
Linux XXXXX 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected behavior
I can create the quickstart for serverless.

### Actual behavior
I get an error:
```
error: No quickstarts match filter
```

**Comment by ccojocar** [comment]
dup of #553
