### ISSUE TITLE
a couple of places in the code use the default http client

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2184]
### Summary 

there are (at least) 2 occurences of code using the default http client.  This is bad as the default client is configured with no timeout whatsoever and can result in a seemingly hung `jx`

### Steps to reproduce the behavior

N/A  code inspection
[discussion](https://github.com/jenkins-x/jx/pull/2130/files#r229792604)

### Jx version

The output of `jx version` is:

```
1.3.525
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

N/A

### Operating system / Environment

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by mikecirioli** [comment]
FYI - I am working on this (not currently in the right group to take proper ownership)

**Comment by jtnord** [comment]
@mikecirioli did you make any progress on this?

**Comment by mikecirioli** [comment]
This was resolved and merged here:  https://github.com/jenkins-x/jx/pull/2228

Not sure why this is still open, i thought it was moved to done in the jira board.
