### ISSUE TITLE
prow config contains incorrect repo name

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2194]
cluster was created by `jx create cluster gke` and the config that was generate looked like

```
cloudbees/environment-jx-:
```
not
```
cloudbees/environment-jx-cd-process-staging:
```

**Comment by patrickleet** [comment]
I saw this today in a cluster I created with `jx create terraform`

**Comment by rawlingsj** [comment]
@garethjevans if you're in the area fancy having a crack at this?  If not I'm happy to take it on this week.

**Comment by rawlingsj** [comment]
I noticed this recently with `jx create env --prow`

**Comment by garethjevans** [comment]
@rawlingsj I'll get looking at this today (I've no meetings!)
