### ISSUE TITLE
Tide merged approved PR despite commits following approval

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2209]
Consider https://github.com/jenkins-x/jenkins-x-serverless/pull/56. I filed it with [one commit](https://github.com/jenkins-x/jenkins-x-serverless/pull/56/commits/c552b25169c4af84ffa3a3354c0b3e88a0c64ebb); @rawlingsj `/approve`d it and triggered tests, which failed. From that point, new commits are automatically tested. I pushed two more before I got a successful build. And then it was merged, with no code review on the [latter portion of the PR](https://github.com/jenkins-x/jenkins-x-serverless/pull/56/files/c552b25169c4af84ffa3a3354c0b3e88a0c64ebb..3fe803fd642b2b18a3ee1b8ebe7e536d17de6ea2). Presumably at this point in the process I am a known contributor, not a capricious person on the Internet, but I was certainly not expecting an automated merge of code changes no one else has looked at.

GitHub’s built-in review system tracks which PR head commit a review applies to, and when review is mechanically enforced, it is [able to decide](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/) that a PR has become ineligible for merge due to subsequent commits:

> If both required reviews and stale review dismissal are enabled and a code-modifying commit is pushed to the branch of an approved pull request, the approval is dismissed. The pull request must be reviewed and approved again before it can be merged.

Prow’s comment-based system is relatively crude and not well integrated with the GitHub review feature from what I can see, but it should at least be able to determine that an approval comment chronologically precedes some commits. I suppose the real problem is that Tide is not paying attention to the _comment_ but to the `approved` _label_ which Hook added in response to the comment—and this label has no chronological context.

**Comment by wbrefvem** [comment]
I agree with the logic of requiring another approval after failed tests, and the point about the lack of chronological context in labels is well taken. The virtue of the label-based implementation is that it's relatively generic across git providers. I'd rather see a solution that either removes the `approved` label upon a failed test or adds `do-not-merge`.

**Comment by jglick** [comment]
I would even suggest removing the `approved` label upon any new push to the PR.

**Comment by rawlingsj** [comment]
There’s a LGTM comment and label we can start using which gets removed on subsequent commits which will prevent auto merge. 

I’ll enable this tomorrow

**Comment by jtnord** [comment]
@jglick @rawlingsj I beleive we can close this now?

**Comment by jglick** [comment]
If something got fixed, just link to and close I guess?

**Comment by ccojocar** [comment]
I think this got fixed. I am going to close it.
