### ISSUE TITLE
 jenkins-x-monocular-ui pods start failed

### ISSUE THREAD

**Issue by chilibreaker** [jenkins-x/jx#2217]
### Summary 

I use 'jx install' on my kubernetes v1.11.2 (centos 7.5) .All things goes well and pvc auto bound to default pv and all pods come to running except  jenkins-x-monocular-ui pod.
The output error of  jenkins-x-monocular-ui pod:
```
Send us your feedback at containers@bitnami.com
 nami    INFO  Initializing nginx
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/nginx/conf' -&gt; '/opt/bitnami/nginx/conf'
```
And my docker is using overlay2 as the storage-driver.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.530
jenkins x platform 0.0.2871
Kubernetes cluster v1.11.2
kubectl            v1.11.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1
```

### Kubernetes cluster

I use kubeadm to create Kubernetes cluster on my centos 7.5 EC2 servers.

### Operating system / Environment

CentOS Linux release 7.5.1804 (Core)

### Expected behavior

All pods running correctly

**Comment by beebird** [comment]
Looks like an issue with OverlayFS, I can see [some similar issues](https://github.com/bitnami/bitnami-docker-dokuwiki/issues/36)

What's your Linux Kernel version? Could you try to upgrade the kernel to have a try again?

**Comment by chilibreaker** [comment]
> Looks like an issue with OverlayFS, I can see [some similar issues](https://github.com/bitnami/bitnami-docker-dokuwiki/issues/36)
> 
> What's your Linux Kernel version? Could you try to upgrade the kernel to have a try again?

Thanks for your help.
That works.
All our dev env docker is using overlay2.And it's difficult to change the docker-storage type.
May I have any methods to make it works well by using docker-storage overlay2?

Thanks.

**Comment by ccojocar** [comment]
@beebird are you still having this issue?

**Comment by beebird** [comment]
not me, I was just asking @chilibreaker to verify. We can close this now.

**Comment by beebird** [comment]
@ccojocar
