### ISSUE TITLE
After deleting an environment and recreating with the same values the environment's namespace isn't created

### ISSUE THREAD

**Issue by masterdrdark** [jenkins-x/jx#2224]
### Summary 

I created a staging environment manually using `jx create environment --git-provider-url=https://gitlab.com/ --git-username=user --git-private staging` and then deleted it using `jx delete environment staging` and then `kubectl delete ns jx-staging` like jx CLI instructed me to. After a while I created the same environment using the same command. I went to the Jenkins master to see the pipeline but I saw that it failed with an error saying:
```
error: failed to run 'helm upgrade --namespace jx-staging --install --wait --force --timeout 600 jx-staging .' command in directory '.', output: 'Error: UPGRADE FAILED: failed to create resource: namespaces "jx-staging" not found': exit status 1
```
I ended up creating the namespace manually using `kubectl create ns jx-staging`

### Steps to reproduce the behavior

`jx create environment --git-provider-url=https://gitlab.com/ --git-username=user --git-private staging`
`jx delete environment staging`
`kubectl delete ns jx-staging`
`jx create environment --git-provider-url=https://gitlab.com/ --git-username=user --git-private staging`

### Jx version

The output of `jx version` is:
```
$ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.544
jenkins x platform 0.0.2871
Kubernetes cluster v1.10.3
kubectl            v1.12.2
helm client        v2.9.1+g20adb27
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1
```

### Kubernetes cluster

AWS provisioned using KOPS

### Operating system / Environment

Kubuntu 18.04

### Expected behavior

After recreating an environment I expect it to create a namespace for it

### Actual behavior

No namespace was created for the recreated environment and therefor the build pipeline failed throwing this error: 
```
error: failed to run 'helm upgrade --namespace jx-staging --install --wait --force --timeout 600 jx-staging .' command in directory '.', output: 'Error: UPGRADE FAILED: failed to create resource: namespaces "jx-staging" not found': exit status 1
```

**Comment by rawlingsj** [comment]
Thanks for reporting

/kind bug
/kind needs-validation
/priority important-soon
