### ISSUE TITLE
GKE cluster failed to create because the name was too long (more than 30 chars)

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2227]
### Summary 
Trying to `jx create terraform`, it failed because the name of the cluster was too long throwing the following error:

error: failed to run 'gcloud iam service-accounts create jx-fingersapphire-rverduci-test --project jenkinsx-dev' command in directory '', output: 'ERROR: (gcloud.iam.service-accounts.create) argument NAME: Bad value [jx-fingersapphire-rverduci-test]: Service account name must be between 6 and 30 characters (inclusive), must begin with a lowercase letter, and consist of lowercase alphanumeric characters that can be separated by hyphens.

### Steps to reproduce the behavior

Run `jx create terraform` and set a long cluster name (the name + auto generated prefix should be more than 30 chars)

### Jx version

The output of `jx version` is:

Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.496
jenkins x platform 0.0.2869
Kubernetes cluster v1.9.7-gke.7
kubectl            v1.10.4
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)

### Kubernetes cluster

GKE

### Operating system / Environment

Mac OS

### Expected behavior

We should do some basic validation of the name length or at least provide a maximum in the CLI inline doc.
Although in my case the name became more than 30 chars because of the auto generated prefix.

### Actual behavior
Nothing is telling you that the name max length is 30 chars, the `jx create` command is failing and exiting.

**Comment by mikecirioli** [comment]
Why do we add the autogenerated bits in the first place?  And if we really need to do that, we should have some logic to truncate the auto-generated bits to keep things under the limit, or make it clear to the user that they must choose a cluster name that is (30 - AUTOGENERATE_MAX) chars long.
