### ISSUE TITLE
Unable to create GKE cluster with JX due to ingress controllers stuck in creating state

### ISSUE THREAD

**Issue by brettwporter** [jenkins-x/jx#2229]
### Summary 
I am attempted to create a gke cluster with jenkins-x installed on it using `jx create terraform`. The cluster creation works and all pods come up and the cli tool even says jx installed successfully on the cluster. However the hook and monocular-api ingress controller are stuck in a creating state and eventually gives me this error `googleapi: Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1, invalid`. I've deleted everything and reran `jx create terraform` a few times with this same issue occurring. Also the Github hooks get 200 responses from the cluster. In terms of functionality jenkins is not discovering repos in my Github at all.

### Steps to reproduce the behavior
Run `jx create terraform` on a gke cluster using all the defaults.

### Jx version
The output of `jx version` is:
```
jx                 1.3.508
jenkins x platform 0.0.2871
Kubernetes cluster v1.9.7-gke.7
kubectl            v1.11.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1 (Apple Git-112)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

I'm using a GKE cluster that was created by terraform using `jx create terraform`.

### Operating system / Environment

Running jx commands on Mac OS X Mojave 10.14

### Expected behavior

GKE cluster and jx associated Kubernetes resources all create successfully.

### Actual behavior

The hook and monocular-api ingress controller returns errors during creation. Error is `googleapi: Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1, invalid`

**Comment by ccojocar** [comment]
@brettwporter Is this still an issue?

**Comment by ccojocar** [comment]
@brettwporter I am going to close this issue. The current version seems to work. Fee free to open another issue if you are still facing the problem.
