### ISSUE TITLE
Depdencies check during installation

### ISSUE THREAD

**Issue by amuniz** [jenkins-x/jx#2231]
### Summary 

A version check on cli dependencies would be good to avoid installation problems.

### Steps to reproduce the behavior

When using `jx create terraform [...]` I've got:

```
Initialising Terraform
error: failed to run 'terraform init /home/amuniz/.jx/organisations/my-org/clusters/dev/terraform' command in directory '', output: 'Initializing configuration from: "/home/amuniz/.jx/organisations/my-org/clusters/dev/terraform"...
Initializing the backend...

Error configuring the backend "gcs": Failed to configure remote backend "gcs": missing 'path' configuration

Please update the configuration in your Terraform files to fix this error
then run this command again.
': exit status 1
```

Reason is my `terraform` binary is older than required. So I update it and re-tried the installation (with the same input parameters, as the GH repo was already created). It proceeded and the installation was resumable from that point.

### Jx version

The output of `jx version` is:

```
NAME VERSION
jx   1.3.552
git  git version 2.7.4
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE

### Operating system / Environment

Ubuntu

**Comment by garethjevans** [comment]
This is fixed now, we are checking for a terraform version > 0.11.0
