### ISSUE TITLE
add a CLI command to check if we should perform a new release

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#224]
it might be nice to check the current commits (and/or PRs) in a CD pipeline and look for some magic comment/text/string to know if a new CD release should be created or not.

e.g. so we could add a comment on a commit to disable releases; then the CD pipeline would detect that comment and skip the release.

Maybe the Jenkinsfile could check if the generated version is empty? Then we could make `jx-release-version` (or maybe `jx step create version`?) wrap up the logic to detect if no release should be done?

**Comment by jstrachan** [comment]
it would be nice to automatically join together PRs from updatebot into a single release.

e.g. if there are 3 PRs on jenkins-x-platform from updatebot, it'd be nice to wait for all 3 PRs to merge before releasing. If thats taking too long folks can always close a PR or trigger a manual merge.

**Comment by jstrachan** [comment]
having a default quiet period would also help; so that we trigger a new release after, say, 30 mins of no new updatebot PR or merge?

**Comment by jstrachan** [comment]
It might be nice to define a source file - like ‘.(git|draft|helm)ignore)’ that we can use to ignore file changes that result in a new CD release?

Eg if ‘.jxignore’ exists it could list the file patterns for excluded releases - such as...

    # let’s ignore docs...
    ^.md

**Comment by jstrachan** [comment]
I wonder what the comment conventions are in other communities like circleci/ bamboo etc to add a commit comment to disable release?

Also I like the idea of adding a ‘no release’ label to PRs so that you could select a few PRs and label them & merge, knowing the pipeline will wait for the next unlabelled PR

**Comment by jtnord** [comment]
should not be an issue for serveless mode IIUC as batch merging is handled in prow. @oswaldohp
