### ISSUE TITLE
jx create spring -d actuator-docs is failing to unzip the project

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2241]
### Summary 
Running `jx create spring -l java -a test-jx-spring -g com.test -d actuator-docs` is failing with the following error: 

error: Failed to unzip new project file /Users/.../.../.../test-jx-spring.zip due to zip: not a valid zip file

### Steps to reproduce the behavior
Run jx create spring -l java -a test-jx-spring -g com.test -d actuator-docs

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.555
jenkins x platform 0.0.2871
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.10.4
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)

### Kubernetes cluster

GKE created with jx create terraform..

### Operating system / Environment

Mac Os

### Expected behavior
We should be able to create a spring boot project with any of the dependencies provided

### Actual behavior
Failing to unzip the project.

**Comment by garethjevans** [comment]
If you look at the contents of the downloaded zip file, it says:

{"timestamp":"2018-11-13T13:50:52.550+0000","status":400,"error":"Bad Request","message":"Dependency 'actuator-docs' is not compatible with Spring Boot 2.1.0.RELEASE","path":"/starter.zip"}

**Comment by romainverduci** [comment]
@garethjevans I've just seen that and there are other dependencies provided that are not compatible with Spring boot. As jx create spring is forcing the Spring Boot version, should we filter the dependencies that are not compatible ?

**Comment by garethjevans** [comment]
Fixed in 1.3.559
