### ISSUE TITLE
`jx install --provider=gke --exposer=LoadBalancer` doesn't create the URL for Jenkins

### ISSUE THREAD

**Issue by ravitejb** [jenkins-x/jx#2243]
### Summary 
When installing Jenkins on GKE, using the exposer as LoadBalancer, everything is created successfully, and I'm able to access the jenkins from the LoadBalancer IP. But at the end of the install, while generating the API token jx errors out as below:
```bash
Getting Jenkins API Token
retrying after error:unable to find external URL annotation on service jenkins in namespace jx
retrying after error:unable to find external URL annotation on service jenkins in namespace jx
error: failed to get the Jenkins API token: after 3 attempts, last error: unable to find external URL annotation on service jenkins in namespace jx
```
But all the logs are normal, and the expose job is getting deleted automatically even though after provigin `--keep-exposecontroller-job=true` to install step

### Steps to reproduce the behavior
```bash
jx install --provider=gke --install-dependencies=false --exposer="LoadBalancer" --keep-exposecontroller-job=true --verbose=true
```
### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.560
jenkins x platform 0.0.2871
Kubernetes cluster v1.10.9-gke.3
kubectl            v1.11.1
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.14.3 (Apple Git-98)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
I'm using GKE cluster which is created by terraform

### Operating system / Environment
Running jx on Mac OS High Sierra Version 10.13.3
### Expected behavior
It should ask for the API token and after that `jx console` should open the jenkins
### Actual behavior
Stuck in API token generation step and `jx open` gives below output
```
Name URL
```

`jx console` output:
```
? Pick service to open:  jenkins
If the app jenkins is running in a different environment you could try: jx get applications
error: Could not find URL for service jenkins in namespace jx
```

**Comment by ccojocar** [comment]
this issue should be fixed by https://github.com/jenkins-x/jx/pull/2659
