### ISSUE TITLE
unprintable characters when using `jx create cluster gke`

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#225]
when using the normal code page (850) in windows when running `jx create cluster gke` in a command shell (windows) you see unmappable characters in the console.

![image](https://user-images.githubusercontent.com/494726/35978148-d710d330-0cdc-11e8-8f75-0f03fdce38ff.png)

**Comment by cpanato** [comment]
I think this is more an issue for the survey lib (https://github.com/AlecAivazis/survey). I will check

**Comment by jstrachan** [comment]
@cpanato thanks! yeah - we maybe need a different windows specific set of characters to use

**Comment by jtnord** [comment]
this issue seems to be working as of today.

![image](https://user-images.githubusercontent.com/494726/49076689-7e3c4b00-f231-11e8-9caf-b145d7ba2f9d.png)
