### ISSUE TITLE
Unable to automatically find API token with chromedp

### ISSUE THREAD

**Issue by olblak** [jenkins-x/jx#2258]
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.531
jenkins x platform 0.0.2871
Kubernetes cluster v1.11.2
kubectl            v1.11.0
helm client        v2.9.1+g20adb27
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AKS created with Terraform

### Expected behavior
When I run 
```jx install --verbose=true --provider=aks --no-default-environments=true --tls-acme=true --http=false``` with a 'myvalues.yaml' file containing 
```
jenkins:
  Master:
    AdminPassword: xxx
```
I expect jenkins-x to correctly configure the jenkins token and then return an output
```
	********************************************************
	
	     NOTE: Your admin password is: xxx
	
	********************************************************

``` 

### Actual behavior

Jenkins-x can't configure the jenkins token which needs to be done manually and then display a wrong password

```
	********************************************************
	
	     NOTE: Your admin password is: <not_this_password>
	
	********************************************************

```

**Comment by ccojocar** [comment]
This should be fixed by https://github.com/jenkins-x/jx/pull/2659
