### ISSUE TITLE
Unable to create GKE cluster

### ISSUE THREAD

**Issue by Nagamohan1** [jenkins-x/jx#2259]
### Summary  
 I try to create gke cluster on my windows-10 box using jx cli, but always giving following error, I tried so many times by changing the zones, but no luck always giving the same error.

error creating cluster exit status 1
error: exit status 1

Please let me know am I missing any obvious env settings here and let me know how I can make this happen?

### Steps to reproduce the behavior
Run command : **jx create cluster gke**

### Jx version

The output of `jx version` is:

```
C:\WINDOWS\system32>jx version
Using helmBinary helm with feature flag: none
Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 192.168.99.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.': exit status 1
Failed to get Kubernetes server version: Get https://192.168.99.100:8443/version?timeout=32s: dial tcp 192.168.99.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Failed to get kubectl version: Command failed 'kubectl version --short': Client Version: v1.10.3
Unable to connect to the server: dial tcp 192.168.99.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. exit status 1

Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.11.0+g2e55dbe
Error: Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 192.168.99.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.': exit status 1
NAME VERSION
jx   [32m1.3.552[0m
git  [32mgit version 2.19.0.windows.1[0m
error: Unable to get latest version for github.com/jenkins-x/jx Get https://api.github.com/repos/jenkins-x/jx/releases/latest: dial tcp: lookup api.github.com: no such host
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

I am trying to use GCP.

### Operating system / Environment

OS:Windows 10

Google Cloud SDK 225.0.0
bq 2.0.37
core 2018.11.09
gsutil 4.34

### Expected behavior

It should suppose to create cluster.

### Actual behavior
not creating the cluster with error exit status -1

**Comment by wbrefvem** [comment]
From your error messages, it looks like you're having network problems. Is your network working otherwise?

**Comment by Nagamohan1** [comment]
Attaching GCP console activity error
![gcp-console-avtivity](https://user-images.githubusercontent.com/10858684/48574118-5c3ef080-e934-11e8-85a4-81cf9061763d.png)

**Comment by garethjevans** [comment]
Hi, Can you try running the gcloud command to see what the error is?

**Comment by Nagamohan1** [comment]
> Hi, Can you try running the gcloud command to see what the error is?

Hi, I did run the gcloud command, but got the following error

![jenkinsx-gcloud-cmd-error](https://user-images.githubusercontent.com/10858684/49002232-09abd280-f185-11e8-834f-f1cf1b2d69c0.PNG)

**Comment by Nagamohan1** [comment]
Accidentally closed reopening the issue 

I did run the gcloud command, but got the following error

![jenkinsx-gcloud-cmd-error](https://user-images.githubusercontent.com/10858684/49002324-4c6daa80-f185-11e8-8b37-b44a338ad473.PNG)

**Comment by jtnord** [comment]
the error says a cluster with that name already exists.  Can you delete the cluster from the GCP console and then try again?
you may need to clear `%HOMEDRIVE%%HOMEPATH%\.jx` to remove clean your local state.

**Comment by Nagamohan1** [comment]
Hi James,

Thanks for quick reply, it seems there is some problem with my gloud billing account which got closed, after fixing the issue able to create the cluster.
