### ISSUE TITLE
jx delete vault leaves a lot of crud lying around

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#2265]
### Summary 
`jx delete vault` leaves a lot of resources in GCP lying around, like the storage bucket, the service account, the KMS keys... basically everything it creates.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by ccojocar** [comment]
@agentgonzo `jx delete vault` has an option `--remove-cloud-resources` which will clean up alls GCP related cloud resources. This options is disabled by default only to avoid losing encrypted secrets. 

Is this what are you looking for?

**Comment by agentgonzo** [comment]
Yep. Didn't realise it was there
