### ISSUE TITLE
Bogus buildUrl / buildLogsUrl defined even in Prow mode

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2266]
Looking at a `PipelineActivity` created on Nov 08 in a Prow-based cluster, I see

```yaml
  buildLogsUrl: https://JENKINS_SERVER/job/ORG/job/REPO/job/PR-8/1/console
  buildUrl: https://JENKINS_SERVER/blue/organizations/jenkins/ORG%2FREPO/detail/PR-8/1/pipeline
```

which does not make sense—these URLs give 503s since there is no running Jenkins service. If there is nothing to replace them, it would be better to just omit them.

**Comment by jstrachan** [comment]
I'm pretty sure I fixed this - we now only update the build logs for prow when we've created the long term persistent URLs (in github / cloud storage)
