### ISSUE TITLE
Support EKS eksctl --vpc-cidr argument in jx create cluster eks

### ISSUE THREAD

**Issue by nukepuppy** [jenkins-x/jx#2267]
### Summary 
Support --vpc-cidr when using  `jx create cluster eks` 
eksctl supports the --vpc-cidr flag when doing `eksctl create cluster`

May be as simple as another https://github.com/jenkins-x/jx/pull/1461

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Combination of eksctl / kops / jx for different purposes.. until feature parity exists between them all.

### Expected behavior
Ideal goal is build the cluster I want on the network I want.  

This facilitates being able to create an enterprise network structure and allow for peering and other network layer enhancements that are too restricting on the default VPC CIDR ranges

### Actual behavior
Does not support the --vpc-cidr flag yet

**Comment by rainmanh** [comment]
eksctl also supports existing subnets.
Probably a similar approach would work
