### ISSUE TITLE
Add support for kustomize

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#2302]
it would be awesome to be able to use kustomize YAML in an environment git repository to provide environment specific overrides for apps.

e.g. having a folder structure...
```
kustomize/
  app1/
    mydeployment.yaml
  app2/
    someservice.yaml
```

Then when using [no tiller]() we use helm to generate the YAML and post process it. We could trivially detect the `kustomize` folder and then just run `kustomize` against the YAML before we apply it - i.e. here: https://github.com/jenkins-x/jx/blob/master/pkg/helm/helm_template.go#L284

we'd just need to 

(i) add kustomise to our builder images
(ii) detect the `kustomize` folder in the current folder and apply it before the above line. 

simples!

**Comment by jstrachan** [comment]
we may also want to support kustomise folder in the preview chart in an app if we want to do any customisation to the preview chart `charts/preview/kustomize/*.yaml` e.g. to kustomize a dependent chart (postgres or something)

**Comment by polothy** [comment]
is there a way to support these things with `helm3`?  `no tiller` has its own drawbacks* and we were hoping `helm3` would solve all our problems ;) (I know... it'll make new ones!)

\* Doesn't support deploying to multiple namespaces, misses deleting resources like custom CRDS, etc.
