### ISSUE TITLE
Unable to push docker image to insecure registry on Minishift

### ISSUE THREAD

**Issue by halltony** [jenkins-x/jx#2311]
### Summary 
When using the node-http quick start on a minishift implementation the docker push fails.  The error reported is:

The push refers to a repository [docker-registry.default.svc:5000/halltony/tony5-node-http]
EXITCODE   0time="2018-11-22T20:40:25Z" level=fatal msg="build step: building [changeme]: pushing: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp 92.242.132.24:5000: i/o timeout"

This is well documented and fixes for this seem to be listed for many platforms but not minishift.

Is there documentation on how to either change the call to http or secure the registry and add credentials for it to jx?

### Steps to reproduce the behavior

jx create Quickstarts
node-http
etc.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.578
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.12.2
git                git version 2.17.2 (Apple Git-113)```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
jx create cluster minishift

### Operating system / Environment
macOS 10.14.1 (18B75)

### Expected behavior
Docker push successful without intervention

### Actual behavior
Failure listed above

**Comment by MastanaGuru** [comment]
I am getting a similar error. 
Successfully built 7522206a7626
The push refers to a repository [docker-registry.default.svc:5000/u740885/providermfsvc]
time="2019-01-04T20:37:46Z" level=fatal msg="build failed: building [changeme]: tagging: pushing: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc on 10.0.2.3:53: no such host"

docker images lists the created image 
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
c3c41b185ac530befdc6c15c9f6cbb7f                         latest              7522206a7626        4 hours ago         474MB
**docker-registry.default.svc:5000/u740885/providermfsvc   1.0.21              7522206a7626        4 hours ago         474MB**
jenkinsxio/exposecontroller                              2.3.88              7ff649d047ef        10 hours ago        27.6MB
jenkinsxio/builder-maven                                 0.1.172             dd5863e4ec29        17 hours ago        2.37GB
jenkinsxio/builder-go                                    0.1.172             df5e18388da1        17 hours ago        4.16GB
jenkinsxio/jx                                            1.3.689             4d3414d32fd3        31 hours ago        292MB
openshift/origin-node                                    v3.11.0             53dee2de37b2        32 hours ago        1.16GB

jx version
NAME               VERSION
jx                 1.3.694
jenkins x platform 0.0.3143
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.13.1
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.20.0
Operating System   Mac OS X 10.14.2 build 18C54

minishift version
minishift v1.28.0+48e89ed

**Comment by jstrachan** [comment]
looks like the minishift setup needs to enable insecure docker registries...
https://jenkins-x.io/faq/issues/#http-server-gave-http-response-to-https-client
