### ISSUE TITLE
jx to manage and update pipeline secrets

### ISSUE THREAD

**Issue by dcanadillas** [jenkins-x/jx#2313]
### Summary 
When having GitHub authentication issues in the pipeline during build time in Jenkins-X, it would be nice to have a jx command that could manage to check the user and organisation used in the pipeline execution, as well as quickly update

### Steps to reproduce the behavior
- Create a quickstart (jx create quickstart -l go)
- Pipeline is not launched automatically in serverless, so I commit a new change to force a build
- Build is triggered and check activities with "jx get activities"
- After a while, you can see the build log with "jx get build log"
- Build fails with "stderr: remote: Invalid username or password"
- Then I can check in gitAuth.yaml the usernames and tokens, but not sure which one is used, except for the log build, where I see it is using a wrong github repo (wrong organization)
- So, I check a secret with "kubectl get secret oauth-token -o yaml | grep oauth: | awk '{print $2}' | base64 -D"

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.585
jenkins x platform 0.0.2902
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.12.0
helm client        v2.10.0-rc.1+gaa98e7e
helm server        v2.10.0-rc.1+gaa98e7e
git                git version 2.19.1
Operating System   Mac OS X 10.14 build 18A391

### Kubernetes cluster
GKE created with the terraform installation ("jx create terraform")

### Operating system / Environment
Operating System   Mac OS X 10.14 build 18A391

### Expected behavior
Would be nice to have a jx command to check the user and tokens secrets for pipeline executions and updating

### Actual behavior
Not sure how to check that the right user/token is used

**Comment by ccojocar** [comment]
Closing this one since it is manly fixed by boot and a number of refactoring around the auth config. The recommended way to install Jenkins X now is boot.
