### ISSUE TITLE
jx create terraform does not install gcloud cli

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2316]
### Summary 
jx create terraform does not install gcloud cli if it's not present on the machine, see the output of the command when gcloud is not present:

osboxes@osboxes:~$ jx create terraform --environment-git-owner kubecd-github-organization-you-created-earlier --verbose
Error: Command failed  gcloud auth login --brief
error: exec: "gcloud": executable file not found in $PATH

### Steps to reproduce the behavior

1. Download jx
2. Run jx create terraform --environment-git-owner kubecd-github-organization-you-created-earlier --verbose

### Jx version

The output of `jx version` is:

Failed to find helm installs: failed to run 'helm list' command in directory '', output: '': exec: "helm": executable file not found in $PATH
Failed to connect to Kubernetes: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Failed to get kubectl version: Command failed 'kubectl version --short':  exec: "kubectl": executable file not found in $PATH

Failed to get helm version: failed to run 'helm version --short' command in directory '', output: '': exec: "helm": executable file not found in $PATH
NAME             VERSION
jx               1.3.585
git              git version 2.17.1
Operating System Ubuntu 18.04.1 LTS

### Kubernetes cluster

No cluster yet but trying to create on GKE

### Operating system / Environment
Ubuntu 18.04

### Expected behavior
gcloud should be installed by the jx create terraform command

### Actual behavior
The install is failing because gcloud is not present

**Comment by jtnord** [comment]
imported as PLAT-349
