### ISSUE TITLE
jx create spring -d web -d actuator fails with segmentation violation

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#232]
Using:
NAME         VERSION                    
jx           1.0.58            
Jenkins X    0.0.55            
Kubernetes   v1.8.0            
Helm Client  v2.8.0+g14af25f   
Helm Server  v2.8.0+g14af25f   
Draft Client v0.9.0            
Draft Server v0.9.0            
Git          git version 2.15.1

Actions:
When applying jx create spring -d web -d actuator the following error occurs:

Pushed git repository to https://github.com/tdcox/test002

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13a6d96]

goroutine 1 [running]:
github.com/jenkins-x/jx/vendor/github.com/jenkins-x/golang-jenkins.(*Jenkins).buildUrl(0x0, 0xc42040b4c0, 0x3f, 0x0, 0xc420711010, 0x2)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/jenkins-x/golang-jenkins/jenkins.go:81 +0x26
github.com/jenkins-x/jx/vendor/github.com/jenkins-x/golang-jenkins.(*Jenkins).get(0x0, 0xc42040b4c0, 0x3f, 0x0, 0x202e380, 0xc42039f8b0, 0x3f, 0xc420690ae0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/jenkins-x/golang-jenkins/jenkins.go:214 +0x4d
github.com/jenkins-x/jx/vendor/github.com/jenkins-x/golang-jenkins.(*Jenkins).GetCredential(0x0, 0xc420690ae0, 0x10, 0x4, 0x1, 0xc420690ae0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/jenkins-x/golang-jenkins/jenkins.go:480 +0xe4
github.com/jenkins-x/jx/pkg/jenkins.ImportProject(0x2d32e40, 0xc420090008, 0x0, 0xc4204d4b10, 0x24, 0x22dfe63, 0xb, 0xc420690ae0, 0x10, 0x0, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jenkins/import.go:28 +0x1fe
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).DoImport(0xc420306500, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:693 +0x219
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).Run(0xc420306500, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:297 +0x1ee
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateProjectOptions).ImportCreatedProject(0xc420306500, 0xc42040a140, 0x3a, 0xc420493ca0, 0x1)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create.go:91 +0x6a
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateSpringOptions).Run(0xc420306500, 0x2d556c0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_spring.go:114 +0x2f2
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdCreateSpring.func1(0xc42035c480, 0xc4203317c0, 0x0, 0x4)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_spring.go:63 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc42035c480, 0xc420331740, 0x4, 0x4, 0xc42035c480, 0xc420331740)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:636 +0x23d
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420255b00, 0xc4203526c0, 0x1f80101, 0xc420352480)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:722 +0x2fe
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420255b00, 0xc4202bd4fe, 0x2d32dc0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc420159f70, 0x1f89e99)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22

**Comment by tdcox** [comment]
Hmmm, looks like there is a namespace problem. This was a clean install using minikube delete and jx create cluster minikube. Helm command installed jenkins-x to default namespace but the jx commands are looking for it in jx namespace.

**Comment by rawlingsj** [comment]
I think I might know what this is.  There was a recent change to `jx create cluster gke` to install Jenkins X into a jx namespace rather than default.  Then jx is supposed to change the current kubectl context so that you are in the `jx` namespace.  

If you run `jx namespace jx` and try the import again does that help?

**Comment by tdcox** [comment]
Still bombs out with the same error, unfortunately.

**Comment by rawlingsj** [comment]
I think this should fix the issue https://github.com/jenkins-x/jx/pull/234 I've tested locally a fresh minikube and am able to import a project again. 

Note there is also another change to jenkins x platform which is being released at the moment so in about half an hour everything should be released and available.

**Comment by tdcox** [comment]
Confirmed
