### ISSUE TITLE
jx delete eks fails because the ELB is not deleted.

### ISSUE THREAD

**Issue by martijnburger** [jenkins-x/jx#2333]
### Summary 
After installing an EKS cluster using `jx install eks testenv`  and creating an application on that cluster, deleting the cluster with `jx delete eks testenv` fails on the deletion of the eksctl-tenev-cluster cloudformation stack. The reason that it fails is because there is and ELB created that needs to be removed before the cloudformation stack is removed.

### Steps to reproduce the behavior
1. Follow the AWS tutorial on: https://aws.amazon.com/blogs/opensource/continuous-delivery-eks-jenkins-x/
2. Remove the stack using `jx delete eks <name-of-cluster>`

### Jx version
1.3.591

The output of `jx version` is:

NAME               VERSION
jx                 [32m1.3.591[0m
Kubernetes cluster [32mv1.10.3[0m
kubectl            [32mv1.10.3[0m
git                [32mgit version 2.19.2.windows.1[0m
Operating System   [32mWindows 10 Pro 1803 build 17134[0m

### Kubernetes cluster

Amazon EKS Cluster

### Operating system / Environment
Windows 10

### Expected behavior
The cluster stack is succesfully deleted

### Actual behavior
The cluster stack fails to delete. Workaround: Manually delete the ELB from the EC2 console.

**Comment by hekonsek** [comment]
Hi Martijn. This is more eksctl issue then jx one. I'm already talking with eksctl authors and we will try to improve this behavior there.

For a time being, you can try to clear dead VPC with its dependencies using the following command - `jx delete aws --vpc-id=yourVpcId`. It should remove VPC with it's dependencies including ELBs.

**Comment by ccojocar** [comment]
@hekonsek Thanks for providing a workaround for this issue.

@martijnburger Could we close the issue on jx side?

**Comment by hekonsek** [comment]
BTW I'm also improving `jx delete aws` behavior a little bit for some use cases - https://github.com/jenkins-x/jx/pull/2726 . Removing AWS garbage in a reliable manner is more difficult than it seems. Even AWS console doesn't handle it well all the time :) .

**Comment by martijnburger** [comment]
> @hekonsek Thanks for providing a workaround for this issue.
> 
> @martijnburger Could we close the issue on jx side?

Yes, fine by me! Thanks for the followup.

**Comment by darkn3rd** [comment]
It looks like https://aws.amazon.com/blogs/opensource/continuous-delivery-eks-jenkins-x/ has been removed.
