### ISSUE TITLE
jx install: Unclear how to use internal help-repo rather public one

### ISSUE THREAD

**Issue by papanito** [jenkins-x/jx#2340]
### Summary 

I try to install jenkins x on a internal kubernetes cluster. The installation process will try to add the missing helm repo
```
Adding missing Helm repo: jenkins-x http://chartmuseum.jenkins-x.io
```
As outgoing traffic has to go trough a proxy we have a proxy repository setup on our internal Nexus artifact repository server for `jenkins-x http://chartmuseum.jenkins-x.io` so the repo is actually reachable via `https://nexus.intra/repository/helm-chartmuseum/`

I would like to know how I can tell the jx install process to use the internal url for the helm-repo rather than the public one

### Steps to reproduce the behavior

Run
```
jx install --provider=kubernetes --on-premise --skip-ingress --git-provider-url=https://scm.intra --git-username=userxyz
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.594
Kubernetes cluster v1.11.3
kubectl            v1.11.0
helm client        v2.9.1+g20adb27
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1.windows.2
Operating System   Windows Server 2016 Standard 1607 build 14393
error: Unable to get latest version for github.com/jenkins-x/jx Get https://api.github.com/repos/jenkins-x/jx/releases/latest: dial tcp 192.30.253.116:443: i/o timeout
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Operating system / Environment

Client: Windows Server 2016 Standard 1607 build 14393
Cluster Nodes: RedHat 6

### Expected behavior

Specify the usage of internal helm-repo

### Actual behavior

Unable to install of jx on-premise as there is no connection

**Comment by beebird** [comment]
A possible solution might be cheating jx as if the repo has been added successfully.

```bash
helm repo add jenkins-x https://nexus.intra/repository/helm-chartmuseum/
sed -i \'s/https:\\/\\/nexus.intra/repository/helm-chartmuseum/http:\\/\\/chartmuseum.jenkins-x.io/\' ~/.helm/repository/repositories.yaml
```

But if there's no external network in your cluster, how could docker pull the images such as jenkins/exposecontroller/chartmuseum?

**Comment by papanito** [comment]
We use Nexus to proxy the required repos. The point is that for every aspect of the installation I want to be able to use internal resources rather than external resources. See also #2339

**Comment by LeoQuote** [comment]
https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/opts/helm.go#L226 adding jenkins-x chartmuseum is the default behavior of helmInit , which is basically doing everywhere , and the default value of kube.DefaultChartMuseumURL is hardcoded in https://github.com/jenkins-x/jx/blob/master/pkg/kube/constants.go#L5 , using you own helm repo needs doing following steps:

1. edit the constans.go , change the default value 
2. rebuild jx and add them to every build image
3. replace all your build image with modified version

overall, thats a huge task , I would rather just modify the DNS resolve of chartmuseum.jenkins-x.io and point it to your server.

I hope we can configure this default chartmuseum in k8s cluster or somewhere else. 

by the way, GWF sucks.

**Comment by LeoQuote** [comment]
Any progress?

**Comment by LeoQuote** [comment]
@papanito does this problem still exist? I'm not using the latest jx lately,

**Comment by papanito** [comment]
I would say yes but I would have to double check to confirm
