### ISSUE TITLE
remove heapster rememants

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2342]
### Summary 

There are some remenants of heapster in the code (platform requirements, documentation and jx cmd) that should be removed as we no longer use heapster

### Steps to reproduce the behavior

https://github.com/jenkins-x/jx/blob/858ac5c21a871185256760b41932d38965814305/pkg/jx/cmd/metrics.go
https://jenkins-x.io/commands/jx_metrics/
https://github.com/search?q=org%3Ajenkins-x+heapster&type=Code

### Jx version

The output of `jx version` is:

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

production jx cluster

### Operating system / Environment

N/A

### Expected behavior

heapster and metrics are not present

**Comment by axsaucedo** [comment]
@jtnord this is still the case, when doing a `jx install --provider=kubernetes` it still installs jenkins-x-heapster pod. Would be good to re-open the issue.

**Comment by jtnord** [comment]
anyone should be able to re-open the issue

**Comment by axsaucedo** [comment]
Thank you @jtnord. I tried commentig with /reopen but it didn't seem to do anything. Perhaps I didn't wait enough. Thanks for the heads up and for re-opening.

**Comment by martin-patsov** [comment]
Maybe my issue is related. After a fresh install with `jx create cluster eks ...` I had the following output from `jx get urls --verbose`:

```
DEBUG: finding service url for heapster in namespace cd
DEBUG: couldn't find service url, attempting to look up via ingress
ERROR: error finding ingress for heapster in namespace cd - err ingresses.extensions "heapster" not found
DEBUG: finding service url for pipelinerunner in namespace cd
DEBUG: couldn't find service url, attempting to look up via ingress
ERROR: error finding ingress for pipelinerunner in namespace cd - err ingresses.extensions "pipelinerunner" not found
DEBUG: finding service url for tekton-pipelines-controller in namespace cd
DEBUG: couldn't find service url, attempting to look up via ingress
ERROR: error finding ingress for tekton-pipelines-controller in namespace cd - err ingresses.extensions "tekton-pipelines-controller" not found
DEBUG: finding service url for tekton-pipelines-webhook in namespace cd
DEBUG: couldn't find service url, attempting to look up via ingress
ERROR: error finding ingress for tekton-pipelines-webhook in namespace cd - err ingresses.extensions "tekton-pipelines-webhook" not found
NAME                  URL
deck                  http://deck.cd.***.nip.io
hook                  http://hook.cd.***.nip.io
jenkins-x-chartmuseum http://chartmuseum.cd.***.nip.io
tide                  http://tide.cd.***.nip.io
```

*** is the ip.

**Comment by martin-patsov** [comment]
@ccojocar Maybe this should be reopened as it is not yet fixed?

**Comment by martin-patsov** [comment]
Related to: #5215
