### ISSUE TITLE
AWS CodeCommit Integration

### ISSUE THREAD

**Issue by tclaudino** [jenkins-x/jx#2344]
Hi,

I'm following the Jenkins X discussions and roadmap.
But I didn't find any topic about AWS CodeCommit.

There is a plan to support CodeCommit integration?

Thanks.

Best Regards,
Thiago

**Comment by Juandavi1** [comment]
someone here ?

**Comment by jstrachan** [comment]
see https://github.com/jenkins-x/issues/issues/35
