### ISSUE TITLE
"jx uninstall" generates a "error: failed to cleanup namespaces in namespace jx" error

### ISSUE THREAD

**Issue by gilesgas** [jenkins-x/jx#2351]
### Summary 

Running `jx uninstall` generates a `error: failed to cleanup namespaces in namespace jx` error, along with other error messages.

### Steps to reproduce the behavior

1. Run `jx uninstall` at the command line.
1. After completing what I believe to be are the correct parameter/values, I received the error below.

### Jx version

I can't remember sorry, but it was before 1.3.599.

The output of `jx version` is:

```
Giless-MacBook-Pro:demo giles$ kubectl config current-context
gke_jenkinsx-dev_australia-southeast1-a_ogrezest-dev
Giless-MacBook-Pro:demo giles$ jx uninstall
? Enter the current context name to confirm uninstallation of the Jenkins X platform from the jx namespace: [? for help]? Enter the current context name to confirm uninstallation of the Jenkins X platform from the jx namespace: gke_jenkinsx-dev_australia-southeast1-a_ogrezest-dev
Removing installation of Jenkins X in team namespace jx
deleting namespace jx
deleting namespace jx
deleting namespace jx-production
deleting namespace jx-staging
error: failed to cleanup namespaces in namespace jx: failed to delete namespace jx: failed to delete the namespace 'jx': Operation cannot be fulfilled on namespaces "jx": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
Giless-MacBook-Pro:demo giles$ 
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Afaik, a Jenkins X GKE cluster on Google Cloud Platform - attempting to install Jenkins X + CloudBees for Kubernetes CD (formerly Kube CD).

### Operating system / Environment

Locally, running `jx` on macOS.

### Expected behavior

A clean uninstallation of CloudBees for Kubernetes CD.

### Actual behavior

Had to go into GCP console admin and delete the CloudBees for Kubernetes CD cluster I created. However, I'm not sure whether or not this would have happened automatically from running the `jx unisntall` command - despite the errors.

**Comment by ccojocar** [comment]
This issue was fixed.

**Comment by engmsaleh** [comment]
I still have the same issue with the following version
```
jx                 1.3.998
jenkins x platform 0.0.3553
Kubernetes cluster v1.10.12
kubectl            v1.10.11
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.18.0
Operating System   Mac OS X 10.14.3 build 18D109
```
