### ISSUE TITLE
Failure on `jx start pipeline`

### ISSUE THREAD

**Issue by amuniz** [jenkins-x/jx#2355]
### Summary 

`jx start pipeline` fails with:

```
[Pipeline] sh
[job] Running shell script
+ cat VERSION
+ jx step tag --version 0.0.1
error: failed to run 'git push origin v0.0.1' command in directory '', output: 'To https://github.com/example-org-kubernetes/demo.git
 ! [remote rejected] v0.0.1 -> v0.0.1 (cannot lock ref 'refs/tags/v0.0.1': reference already exists)
error: failed to push some refs to 'https://github.com/example-org-kubernetes/demo.git'': exit status 1
```

### Steps to reproduce the behavior

1. Install a cluster: `jx create terraform --environment-git-owner example-org-kubernetes --verbose`
2. Create an app: `jx create quickstart` (select `golang-http`, but it's irrelevant for this matter)
3. Start the master pipeline to get the app to the staging env: `jx start pipeline example-org-kubernetes/demo/master`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.602
jenkins x platform 0.0.2940
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.7.4
Operating System   Ubuntu 16.04.5 LTS
```

### Kubernetes cluster

See above.

### Expected behavior

Tag 0.0.1 is created in Git and the app is deployed to staging.

### Actual behavior

Tag `0.0.1` is created in Git and the pipeline fails. The app is not deployed in staging.

**Comment by amuniz** [comment]
Imported as PLAT-371

**Comment by rawlingsj** [comment]
thanks
