### ISSUE TITLE
jx install fails when it tries to create the github repositories

### ISSUE THREAD

**Issue by cvanballegooijen** [jenkins-x/jx#2357]
### Summary 
Creating default staging and production environments
Using Git provider GitHub at https://github.com

About to create repository environment-lynxmaple-staging on server https://github.com with user cvanballegooijen

Creating repository cvanballegooijen/environment-lynxmaple-staging
Creating Git repository cvanballegooijen/environment-lynxmaple-staging
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1f33659]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/kube.CreateEnvGitRepository(0x1, 0xc001326100, 0x20, 0xc0013240c0, 0xc003910000, 0xc003910c00, 0xc00095b6a0, 0x340e0de, 0x3b, 0xc0009e79e0, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/env.go:283 +0x7c9
github.com/jenkins-x/jx/pkg/kube.CreateEnvironmentSurvey(0x2ee5b01, 0xc001326100, 0x20, 0xc0013240c0, 0xc003910000, 0xc003910c00, 0xc00095b6a0, 0x340e0de, 0x3b, 0xc000e6d1c8, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/env.go:236 +0x4ee
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateEnvOptions).Run(0xc00095b4a8, 0x35, 0x337b0ab)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_env.go:184 +0x49b
github.com/jenkins-x/jx/pkg/jx/cmd.(*InstallOptions).Run(0xc00095b000, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:1270 +0x45a0
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdInstall.func1(0xc000694780, 0x50d9540, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:246 +0x64
github.com/spf13/cobra.(*Command).execute(0xc000694780, 0x50d9540, 0x0, 0x0, 0xc000694780, 0x50d9540)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b9400, 0xc000974500, 0xc000759180, 0xc000868780)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0000b9400, 0xc00067bdc0, 0x372a300)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc00052bf88, 0xc0000ac058)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0xdc
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
### Steps to reproduce the behavior
jx install

### Jx version

The output of `jx version` is:
jx                 1.3.605
jenkins x platform 0.0.2940
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.12.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.1 build 18B75

What kind of Kubernetes cluster are you using & how did you create it?
GKE using the GCloud console

### Operating system / Environment
Mac client with GKE as the Kubernetes service

### Expected behavior
Creating the necessary jx repositories in my GitHub account 
### Actual behavior
See summary

**Comment by ccojocar** [comment]
This part of the install was in the meantime refactored to avoid this kind of issues. jx will prompt to the user a list of available GitHub organisations.

Please open another issue if you still see the problem occurring. I am going to close this issue.
