### ISSUE TITLE
jx create pullrequest is DOA

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2365]
### Summary 

`jx create pullrequest` does not create a pull request but errors out.

### Steps to reproduce the behavior

```
hub clone org/repo
hub fork username
git checkout -b somebranch
echo hello world > file.txt
git add file.txt
git commit -a -m "added file
jx create pullrequest
```
answer the questions....

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 [32m1.3.604[0m
Kubernetes cluster [32mv1.9.7-gke.11[0m
kubectl            [32mv1.10.3[0m
git                [32mgit version 2.16.2.windows.1[0m
Operating System   [32mWindows 10 Pro 1803 build 17134[0m
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GCP but this is local so...

### Operating system / Environment

as above

### Expected behavior

a PR is created using the PR template provided by the github repo

### Actual behavior

```
C:\workarea\source\github\blah>jx create pullrequest
? user name to use for authenticating with git issues jtnord
? PullRequest title: added file
error: POST https://api.github.com/repos/cloudbees/astro/pulls: 422 Validation Failed [{Resource:PullRequest Field:head Code:invalid Message:}]
```

**Comment by agentgonzo** [comment]
As a workaround, you can use `hub`, or your IDE, or the GitHub UI
