### ISSUE TITLE
jx create cluster minikube fails under Linux with kvm

### ISSUE THREAD

**Issue by Kevgilmore** [jenkins-x/jx#237]
Selecting kvm as driver on a Linux system with a working kvm instance fails with the error:

error installing missing dependencies unknown dependency to install kvm, please fix or install manually then try again

This seems to be coming from here:
https://github.com/jenkins-x/jx/blob/dd4707ad4360c73e182928149e189b567e35ee02/pkg/jx/cmd/create_cluster.go#L218

**Comment by sasiarivukalanjiam** [comment]
Command :  jx create cluster minikube

Error 
----

? Select driver: kvm
error installing missing dependencies unknown dependency to install kvm
, please fix or install manually then try again

**Comment by jasjeetkaur2211** [comment]
I am getting the same error while trying to install the cluster with minishift.

Command: 
`jx create cluster minishift`

## Error
? Select driver: kvm
error installing missing dependencies unknown dependency to install kvm
, please fix or install manually then try again

**Comment by sasiarivukalanjiam** [comment]
It would be better if they provide how to install kubernets manually for jx and how to use that created kubernetes cluster environment for jx as most of the people have to do these things by searching random stuffs and trying out odd number of ways ... A good document on,
1. How to create Kubernetes cluster for JX
2. How to use the created Kubnernetes cluster with jx for a simple job 
this will be much appreciated 😄 as it would kick start the container world exploration with jenkins

**Comment by i0n** [comment]
Hey there!

It looks like there might be several different issues lurking in here. What's the current status?

**Comment by ccojocar** [comment]
@Kevgilmore Are you still facing this issue?

**Comment by ccojocar** [comment]
@Kevgilmore I am going to close this issue, since it appears to be quite old. Please feel free to open another issue. Thanks
