### ISSUE TITLE
jx install is skipped if (some undetermined) options specified to jx

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2372]
### Summary 

I attempted to install jx  with `jx create terraform --environment-git-owner my-org --verbose -o testing --cluster goodclustername=gke --git-username=my-bot --git-api-token=somelonghash`

after terraform created the cluster I expected jx to be installed.

### Steps to reproduce the behavior

`jx create terraform --environment-git-owner my-org --verbose -o testing --cluster goodclustername=gke --git-username=my-bot --git-api-token=somelonghash`

### Jx version

The output of `jx version` is:

```

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior

the cluster is created using the options supplied **and jx is installed**.

### Actual behavior

The install of jx was "skipped" after the creation of the cluster

```
<snip>
google_container_node_pool.jx-node-pool: Still creating... (2m50s elapsed)
google_container_node_pool.jx-node-pool: Creation complete after 2m50s (ID: europe-west2-a/jamesntesting-jamesntesting/default-pool)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

cluster_endpoint = 35.242.180.127
cluster_master_version = 1.9.7-gke.11
Fetching cluster endpoint and auth data.
kubeconfig entry generated for jamesntesting-jamesntesting.Skipping jx install
```

**Comment by jtnord** [comment]
seems to be if the `--cluster` option is specified

**Comment by agentgonzo** [comment]
This is because the cluster name doesn't match the `jx-environment` parameter (which defaults to "dev"). It's not obvious, but it say "Skipping jx install" right at the end of your output.
If you specify `--jx-environment=goodclustername` then it _will_ install it. 

https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_terraform.go#L638-L650

**Comment by agentgonzo** [comment]
Whether it _should_ do this is up for debate. IMO it's a bit pointless using `jx create` if you're _not_ going to install Jenkins X in the cluster
