### ISSUE TITLE
jx command hangs when kubctx is set to offline minikube

### ISSUE THREAD

**Issue by recampbell** [jenkins-x/jx#2376]
### Summary 

When I try to run the `jx` command it hangs when my `kubectx` is pointing a local minikube cluster which isn't running. It hangs while running any jx command like `jx login` and `jx help`

### Steps to reproduce the behavior

1. Install minikube
2. Don't start minikube
3. Set the kubectx context to the minikube context
4. Try to run jx login or or jx help

You will see the jx command always hang

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               1.3.612
git              git version 2.17.2 (Apple Git-113)
Operating System Mac OS X 10.14 build 18A391
```

### Kubernetes cluster

I had minikube installed, but wasn't trying to use it. I was trying to login to a cluster.

### Operating system / Environment

OS X 10.14 (18A391)
### Expected behavior

The `jx help` and `jx login` commands should still work even if my kubectx is pointing at a down or inoperative kubernetes cluster.

### Actual behavior

The jx commands just hangs indefinitely.

**Comment by thebalaa** [comment]
I also encountered this issue while running the Kubernetes that ships with Docker for Mac. When Docker / Kubernetes aren't running `jx` would hang for a long time.

Unsetting the current-context seems to resolve the issue for me:

`kubectl config unset current-context`
