### ISSUE TITLE
When using GCP Cloud shell to install jx, installation will fail if git user.email/user.name is not configured

### ISSUE THREAD

**Issue by mikecirioli** [jenkins-x/jx#2387]
### Summary 
When using GCP Cloud shell to install `jx`, installation will fail if the local git instance does not have `user.email` and `user.name` configured.  This is likely the default scenario for a user who is trying out `jx` for the first time.

### Steps to reproduce the behavior

1. open a GCP Cloud Shell and follow the installation instructions in the JX install guide.
2. Installation will fail with the following error prior to applying terraform configuration:
```
Created /home/mcirioli/.jx/organisations/mikec-bugbash-org/clusters/dev/terraform/terraform.tf
error: failed to run 'git commit -m Add organisation clusters' command in directory '/home/mcirioli/.jx/organisations/mikec-bugbash-org', output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```
Supplying any values for `user.name` and `user.email` and re-running the `jx` install process appear to be sufficient to allow the install to succeed.

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               1.3.615
git              git version 2.11.0
Operating System Debian GNU/Linux 9.6 (stretch)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GCP cluster created using `jx install`
### Operating system / Environment
GCP shell
### Expected behavior
the `jx` install process would validate pre-requisites before beginning the install process

### Actual behavior
no pre-requisite validation is being done (at least in this case)

**Comment by jstrachan** [comment]
were you using `jx install` or `jx create terraform`? Am guessing the latter from the error?

We already have the code to check for git being setup btw; sounds like we just need to reuse that code for `jx create terraform`
https://github.com/jenkins-x/jx/blob/d13d041fa92069c228e53e9b78eda9e62d85bdc8/pkg/jx/cmd/init.go#L723

**Comment by garethjevans** [comment]
@jstrachan, looks like `jx create terraform` is being used here, I can add in a fix for that - I didn't know that function existed!

**Comment by rawlingsj** [comment]
Maybe we need a label of soon-ish? :) . Was just throwing it in here hoping it's an easy one.

**Comment by garethjevans** [comment]
Resolved in the latest version
