### ISSUE TITLE
Allow users to specify a custom image for a devpod template

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#2389]
### Summary 

Currently `jx create devpod` matches a label to a pod template in `configmaps/jenkins`. This is slightly counterintuitive, since one might expect that changing, for instance, the image used by a pod template in the Jenkins UI would result in that image being used to create the DevPod, which isn't the case.

### Steps to reproduce the behavior

1. Change the image specified in a pod template in the Jenkins UI.
2. Create a DevPod with `jx create devpod -l <the template I just edited>`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.615
jenkins x platform 0.0.2902
Kubernetes cluster v1.11.2-gke.18
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.1 build 18B75
```

### Kubernetes cluster

GKE, `jx create cluster gke`

### Operating system / Environment
```
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
```

### Expected behavior

`jx create devpod` should use the pod template configuration specified in Jenkins

### Actual behavior

`jx create devpod` uses a static config specified in `cm/jenkins` that is not easily editable.

**Comment by johnmcollier** [comment]
+1 Would love to see a way to override the image when running `jx create devpod`. Maybe an image flag?

**Comment by jstrachan** [comment]
BTW if you change the configuration of pod templates via helm - then both the Jenkins pod templates and the dev pod templates are updated: https://jenkins-x.io/getting-started/config/

e.g. like this: https://jenkins-x.io/getting-started/create-custom-builder/

If you modify build pods directly via the Jenkins console - then your changes will be lost next time you run a `jx upgrade platform` anyway.

I'm all for making it easier to add new kinds of pod templates however - but I'd hope we can keep the same images by default for pipelines + devpods?
