### ISSUE TITLE
create a build pack and quickstart for a helm chart

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#2391]
folks might want to be able to just generate a helm chart from some existing YAML files and have changes to the YAML be verified (maybe a Preview Environment?) and then released on merge to master as a new versioned helm chart that can then easily be [promoted via the CLI](https://jenkins-x.io/developing/promote/)

so it might be nice to have a hello world quickstart that deploys a known docker image using a `Service/Deployment` that folks could use as a base and then just change the docker image/YAML?

**Comment by wadadli** [comment]
I'm all for this!

**Comment by igdianov** [comment]
@jstrachan @rawlingsj We are looking to provide an Activiti Cloud Application Quickstart for Activiti7 Helm chart, so folks could quickly get up and running by using `jx create quickstart activiti-cloud-application-quickstart`  from Activiti Github location and import the Helm chart into their environment as any other project with templated values.yaml? 

What needs to exists to support this case? 

Will Jx be able to detect Helm chart project and apply a Helm build pack for it? 

Is there a Helm build pack or is it needed to be created in common repo?
