### ISSUE TITLE
jx delete devpod fails when --username parameter is specified during creation.

### ISSUE THREAD

**Issue by martijnburger** [jenkins-x/jx#2392]
### Steps to reproduce the behavior
jx create devpod --username my-user
- exit out of pod created
jx delete devpod
### Jx version
1.3.613
The output of `jx version` is:
NAME               VERSION
jx                 1.3.613
jenkins x platform 0.0.2940
Kubernetes cluster v1.10.3-eks
kubectl            v1.10.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1.windows.1
Operating System   Windows 10 Pro 1803 build 17134
COPY OUTPUT HERE
error: There are no DevPods for user AzureAD\MartijnBurger in namespace jx. You can create one via: jx create devpod
### Kubernetes cluster
EKS
What kind of Kubernetes cluster are you using & how did you create it?
Using jx create eks demo
### Operating system / Environment
Windows 10
### Expected behavior
Pick up on created username or add a parameter to the jx delete devpod command to specify the username
### Actual behavior
Impossible to delete devpod with jx. Workaround is to delete pod manually with kubectl

**Comment by ccojocar** [comment]
Fixed by PR https://github.com/jenkins-x/jx/pull/2693
