### ISSUE TITLE
cloud-environments should be per team

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2396]
### Summary 

I amy want to manage multiple clusters from the same machine.  Currently `jx` keeps a single cloud-platform repo at `~/cloud-environments` which means when you switch between clusters you may end up using the wrong information, or overwriting the wrong information.

### Steps to reproduce the behavior

create 2 clusters
give one some custom behaviur in the `cloud-environments` repo.
switch to a different cluster
run `jx update platform`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 [32m1.3.620[0m
jenkins x platform [32m0.0.2940[0m
Kubernetes cluster [32mv1.9.7-gke.11[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.11.0+g2e55dbe[0m
helm server        [32mv2.11.0+g2e55dbe[0m
git                [32mgit version 2.16.2.windows.1[0m
Operating System   [32mWindows 10 Pro 1803 build 17134[0m
```

### Kubernetes cluster

GKE terraform

### Expected behavior

I have a location per cluster not per user/system

### Actual behavior

I have a location per user/system

**Comment by jstrachan** [comment]
cloud environments are typically constants per kubernetes kind - not per team

**Comment by rawlingsj** [comment]
I think the move to gitops for the dev environment + vault should solve this.

/CC @ccojocar @garethjevans @jstrachan @agentgonzo
