### ISSUE TITLE
chartmuseum.build.cd.jenkins-x.io gateway timeout

### ISSUE THREAD

**Issue by udbscience** [jenkins-x/jx#2399]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by garethjevans** [comment]
Hi @udbscience, we are currently performing some maintenance on this cluster so it should be restored soon.  However, this is a deprecated endpoint, you should be using http://chartmuseum.jenkins-x.io/ instead as this is a HA endpoint

**Comment by joannbrereton** [comment]
Is that ever going to be a secured endpoint? @garethjevans

**Comment by udbscience** [comment]
I have changed the requirements.yaml to point to the ha one, but preview seems to be looking at the old deprecated url. Where do I need to change it to point to HA endpoint? @garethjevans

**Comment by avara1986** [comment]
Hi,

chartmuseum.build.cd.jenkins-x.io returns timeout: 

```
jx step helm build

No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Using helmBinary helm with feature flag: none
Adding missing Helm repo: jenkins-x https://chartmuseum.build.cd.jenkins-x.io
retrying after error:failed to add the repository 'jenkins-x' with URL 'https://chartmuseum.build.cd.jenkins-x.io': failed to run 'helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io' command in directory '.', output: 'Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch https://chartmuseum.build.cd.jenkins-x.io/index.yaml : 504 Gateway Timeout': exit status 1
```
```
jx step helm release

No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Using helmBinary helm with feature flag: none
Adding missing Helm repo: jenkins-x https://chartmuseum.build.cd.jenkins-x.io
retrying after error:failed to add the repository 'jenkins-x' with URL 'https://chartmuseum.build.cd.jenkins-x.io': failed to run 'helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io' command in directory '.', output: 'Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch https://chartmuseum.build.cd.jenkins-x.io/index.yaml : 504 Gateway Timeout': exit status 1
```

We have changed all the urls to chartmuseum.jenkins-x.io but helm is looking for chartmuseum.build.cd.jenkins-x.io. Where do we change it?

Thanks a lot

**Comment by ysaakpr** [comment]
https://github.com/jenkins-x/jenkins-x-platform/issues/4408

**Comment by ysaakpr** [comment]
http://chartmuseum.jenkins-x.io/ > Https endpoint please

**Comment by avara1986** [comment]
@garethjevans @joannbrereton we have solved the problem with this steps:
* Updating **helm** and **JX** binaries
* Updating **tiller** in cluster
* Running in our local server:
```bash
helm repo remove jenkins-x
helm repo add jenkins-x http://chartmuseum.jenkins-x.io/
jx upgrade platform
```

I hope this helps and thanks @plsanchezfaure who found the solution.

**Comment by rawlingsj** [comment]
Thanks all for baring with us, yes the HA endpoint is http://chartmuseum.jenkins-x.io, by the sounds of it you're replaced all the references to the old URL so am going to close but please reopen if there's still an issue.
