### ISSUE TITLE
No option to add a new pipeline user if some already exist during the install

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#2401]
### Summary 

During the install process, it would be nice to be prompted to see if we want to add a new user, rather than select from the existing users configured in `gitAuth.yaml`.  

Currently we are only prompted if no users exist.

**Comment by ccojocar** [comment]
I think this was fixed with the `install` command refactoring. You can now select if you want to use the same local user for the pipeline or not. If not, you can define a new user for the pipeline. 

I am going to close this issue.
