### ISSUE TITLE
jx create command fails with "service not found".

### ISSUE THREAD

**Issue by meghalidhoble** [jenkins-x/jx#2403]
### Summary 
Tried creating sample apps using "jx create spring" OR "jx create quickstart" both commands fail with same error. 

### Steps to reproduce the behavior
I have build the source and tried to validate the base jx commands.
I have a local minikube setup with kubernetes and running pods in place. jx get commands are working for me, 

~/Meghali# jx get env
NAME LABEL       KIND        PROMOTE NAMESPACE ORDER CLUSTER SOURCE REF PR
dev  Development Development Never   jx        0

~/Meghali# jx get apps
No applications found in environments
~/Meghali#

### Jx version

The output of `jx version` is:

```
Updated the team settings in namespace jx
Using helmBinary helm with feature flag: none
Updated the team settings in namespace jx
NAME               VERSION
jx                 1.3.565-dev+41f300a
Kubernetes cluster v1.8.0
kubectl            v1.10.2
helm client        v2.4.1+g46d9ea8
helm server        v2.4.1+g46d9ea8
git                git version 2.7.4
```

### Kubernetes cluster
Minikube setup I have 
I am using "kubectl" commands to create pods and deploy.

### Operating system / Environment
Ubuntu 16.04 with ppc64le

### Expected behavior
Command should not fail.

### Actual behavior
"jx create " fails with "service 'jenkins' not found"

```
~/Meghali# jx create quickstart
? select the quickstart you wish to create  [Use arrows to move, type to filter]
? select the quickstart you wish to create angular-io-quickstart
? Project name (angular-io-quickstart)
Generated quickstart at /root/Meghali/angular-io-quickstart
### NO charts folder /root/Meghali/angular-io-quickstart/charts/angular-io-quickstart
Created project at /root/Meghali/angular-io-quickstart
error: services "jenkins" not found
```

Am I missing some step of the configuration? Can someone give me pointers to resolve this? 

My list of services seen as below:

```
root@pts00433-vm2:~/Meghali# kubectl get svc
NAME                                  TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
awesome-rattlesnake-ibm-rstudio-dev   NodePort   10.109.167.243   <none>        8787:32631/TCP   4h
hello-k8s                             NodePort   10.98.144.254    <none>        8080:30560/TCP   1d
```

Please note that the pod is running for the above service "awesome-rattlesnake-ibm-rstudio-dev". Also the jenkins service is running on the host.

**Comment by rawlingsj** [comment]
I wonder, have you installed Jenkins X first using the docs [here](https://jenkins-x.io/getting-started/create-cluster/#using-minikube-local)?  TBH minikube isn't the greatest as it's a bit unreliable running kubernetes locally.  We try to nudge folks to using a managed Kubernetes service if possible on the pubic cloud like [GKE](https://cloud.google.com/kubernetes-engine/) there's a free tier and once you have a google project you can create a cluster + install Jenkins X using `jx create cluster gke` https://jenkins-x.io/getting-started/create-cluster/#using-google-cloud-gke

**Comment by meghalidhoble** [comment]
Thanks @rawlingsj , for the response.
Yes, I have followed the instructions for minikube install as per Jenkins X docs.  
The minikube status is seen up and running : 
```
~/Meghali/kube_services# minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 127.0.0.1
```
However I will try to use GKE setup and see if that helps. 
Thanks,

**Comment by ccojocar** [comment]
@meghalidhoble Have you managed to deploy your app? It looks to me that the jenkins-x platform was not properly installed.

`kubectl get svc -n jx` Does return the `jenkins` service?

I am going to close this issue for now. Feel free to open another issue if you still aren't able to deploy the app after following the installation instructions for GKE.
