### ISSUE TITLE
The generated password should not include less than character "<" 

### ISSUE THREAD

**Issue by shaedis** [jenkins-x/jx#2406]
### Summary 
The generated password included "less than" character "<" and this cause the following fatal error in Maven-container:
[FATAL] Non-parseable settings /root/.m2/settings.xml: unexpected character in markup < (position: START_TAG seen ...</username>\n          <password>****<... @17:42)  @ /root/.m2/settings.xml, line 17, column 42
The password created looked like:
<password>ueh683jkp8vFU8<</password>

### Steps to reproduce the behavior
I received the error when I was trying to build my java app with Maven via Jenkins X

### Jx version
The output of `jx version` is:
```
NAME               VERSION
jx                 1.3.620
jenkins x platform 0.0.2940
Kubernetes cluster v1.12.1
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1
Operating System   "Red Hat Enterprise Linux Server release 7.5 (Maipo)"
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Kubernetes On-premises

### Operating system / Environment
Red Hat Enterprise Linux Server release 7.5 (Maipo)
### Expected behavior
Should not include "less than" character , otherwise this will cause Syntax error in password field in Maven settings.xml

### Actual behavior
Generated password include "less than" character:  ueh683jkp8vFU8<

**Comment by rawlingsj** [comment]
ah interesting, so it was a generated password rather than one specified using `--default-admin-password`?  either way yes we should protect against that.  Thanks for the issue!

**Comment by shaedis** [comment]
> ah interesting, so it was a generated password rather than one specified using `--default-admin-password`? either way yes we should protect against that. Thanks for the issue!

Yes, it was generated without using '--default-admin-password' to 'jx install'.

**Comment by jtnord** [comment]
the password should not be inlined as is but actually encoded correctly.  `&` would also need encoding or removing

**Comment by garethjevans** [comment]
This should be fixed in the latest version by removing <>& from the allowed list of symbols
