### ISSUE TITLE
installing the sso addon only uses the first entry from gitAuth.yaml to suggest organisation to pick

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2407]
I suspect this is a common issue and not just affecting the sso addon but below are the steps to recreate.  When creating the sso addon if you have an entry in you `gitAuth.yaml` file it seems `jx` uses the first entry to get a list of associated orgs which are then displayed for the user to select from.  We should probably pick which git user we want to use to list associated orgs instead of using the first entry.

```
➜  ~ jx create addon sso --namespace=sso
Looking for cert-manager deployment in namespace cert-manager...
Installing dex identity provider...
? Domain: foo.bar.io
Configuring GitHub connector
Please go to https://github.com/settings/applications/new and create a new OAuth application with an Authorization Callback URL of https://dex.sso.foo.bar.io/callback.
Choose a suitable Application name and Homepage URL.
Copy the Client ID and the Client Secret and paste them into the form below:
? Client ID: 123
? Client Secret: abc123
? Select GitHub organizations to authorize users from:  [Use arrows to move, type to filter]
> [x]  wine
```

If I change the order of another git username to the top of my `gitAuth.yaml` file then I get a different selection of orgs returned, e.g:

```
➜  ~ jx create addon sso --namespace=sso
Looking for cert-manager deployment in namespace cert-manager...
Installing dex identity provider...
? Domain: foo.bar.io
Configuring GitHub connector
Please go to https://github.com/settings/applications/new and create a new OAuth application with an Authorization Callback URL of https://dex.sso.foo.bar.io/callback.
Choose a suitable Application name and Homepage URL.
Copy the Client ID and the Client Secret and paste them into the form below:
? Client ID: 123
? Client Secret: abc123
? Select GitHub organizations to authorize users from:  [Use arrows to move, type to filter]
> [x]  cheese
```

**Comment by rawlingsj** [comment]
I saw another affect of the first entry in the `gitAuth.yaml` file today, even though other git secrets contained the correct pipeline bot token the `jx-pipeline-git-github-github` secret had an incorrect token which happened to be the first one in the  `gitAuth.yaml` file during the install.

**Comment by rawlingsj** [comment]
@ccojocar you have a bit of work to finish and I have a number of issues to sort so the race is on between us to sort this one out :)

**Comment by ccojocar** [comment]
@rawlingsj Have you managed to fix this issue?

**Comment by ccojocar** [comment]
@rawlingsj I did some fixes yesterday in the `sso` addon, and I saw that all my organisations were displayed. Could we close this?

**Comment by rawlingsj** [comment]
Sounds good to me
