### ISSUE TITLE
Nexus pod never came to life due resource limit on Azure

### ISSUE THREAD

**Issue by yregaieg** [jenkins-x/jx#2413]
### Summary 
It seems like the smallest node size possible on Azure (aks) when creating a new cluster using the "jx create cluster" command is not enough for jenkins-x to run.
I have been struggling all day to get it up and running, but only after I deleted the nexus pod that I have gotten a meaningful error message : 
```
 AttachVolume.Attach failed for volume "pvc-***" : Attach volume "kubernetes-dynamic-pvc-***" to instance "aks-nodepool1-***" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="The maximum number of data disks allowed to be attached to a VM of this size is 4." 
```
Note that the initial error shown in the dashboard was different and misleading, and that the nexus pod has been PendingCreation ....
### Steps to reproduce the behavior
- Create a new cluster on AKS using the smallest node size available in the prompt, and specifying 1 as number of nodes.
- Last pod to be created (nexus in my case) wasn't able to attach pvc
### Jx version

The output of `jx version` is:

```
22:16 $ jx version
NAME               VERSION
jx                 1.3.623
jenkins x platform 0.0.2940
Kubernetes cluster v1.9.11
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
Operating System   Mac OS X 10.14.1 build 18B75

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AKS, created using jx

### Operating system / Environment
N/A
### Expected behavior
N/A
### Actual behavior
N/A

**Comment by rawlingsj** [comment]
Yeah it would be nice for jx to check the resources available in the cluster before attempting an install.
