### ISSUE TITLE
Jx confused if importing apps from two different Git repositories (Bitnucket and Gitlab) into same Jenkins

### ISSUE THREAD

**Issue by shaedis** [jenkins-x/jx#2419]
### Summary 
I encontered this strange behavior of Jx if I am trying to import my apps from different repositories( different git providers) into same Jenkins. The last promote-step is strange:

+ jx promote -b --all-auto --timeout 1h --version 0.0.12
Promoting app test-build version 0.0.12 to namespace dev
Created Pull Request: https://bitbucket.org/myTeam/environment-jx-dev/pull-requests/5

replaced sha with ##################

Pull Request https://bitbucket.org/myTeam/environment-jx-dev/pull-requests/5 is merged at sha ##################
Merge commit has not yet any statuses on repo myTeam/environment-jx-dev merge sha ##################
merge status: in-progress for URL https://api.bitbucket.org/2.0/repositories/myTeam/environment-jx-dev/commit/################## with target: https://api.bitbucket.org/2.0/repositories/myTeam/environment-jx-dev/commit/b##################/statuses/build/################## description: The tests have started...
merge status: success for URL https://api.bitbucket.org/2.0/repositories/myTeam/environment-jx-dev/commit/################## with target: https://api.bitbucket.org/2.0/repositories/myTeam/environment-jx-dev/commit/b##################/statuses/build/e################## description: This commit looks good
Merge status checks all passed so the promotion worked!
Promoting app test-build version 0.0.12 to namespace dev
error: failed to run 'git push origin HEAD' command in directory '/home/jenkins/.jx/environments/myuser/environment-jx-dev-gl', output: 'fatal: could not read Username for 'https://gitlab.com': No such device or address': exit status 128

== Why suddently switching from Bitbucket to Gitlab?

### Steps to reproduce the behavior
$jx create env --git-provider-url='https://bitbucket.org' -n dev -l Dev --namespace dev -p Auto --domain='my.domain.com'
$jx create env --git-provider-url='https://gitlab.com' -n dev-gl -l Dev-gl --namespace dev -p Auto --domain='my.domain.com'
# Go to my app and import myapp
$ jx import  -u   https://bitbucket.org/myTeam/myapp.git

$jx get env
NAME   LABEL       KIND        PROMOTE NAMESPACE ORDER CLUSTER        SOURCE                                                REF    PR
dev    Development Development Never   jx        0
dev    Dev         Permanent   Auto    dev       100                  https://bitbucket.org/myTeam/environment-jx-dev.git master
dev-gl Dev-gl      Permanent   Auto    dev       100   xxx.xxx.xxx.xx https://gitlab.com/myuser/environment-jx-dev-gl.git   master

### Jx version

The output of `jx version` is:
```
NAME               VERSION
jx                 1.3.620
jenkins x platform 0.0.2940
Kubernetes cluster v1.12.1
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1
Operating System   "Red Hat Enterprise Linux Server release 7.5 (Maipo)"
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
On premise kubernetes created by our admin

### Operating system / Environment
Red Hat Enterprise Linux 
### Expected behavior
git push origin HEAD ======> should push to env 'Dev' , not to 'Dev-gl' , i.e. should run in /home/jenkins/.jx/environments/myTeam/environment-jx-dev 
### Actual behavior
error: failed to run 'git push origin HEAD' command in directory '/home/jenkins/.jx/environments/myuser/environment-jx-dev-gl'

**Comment by shaedis** [comment]
I removed the newly added environment dev-gl in order to be able to fix it:

$jx delete env dev-gl
$jx get env
NAME LABEL       KIND        PROMOTE NAMESPACE ORDER CLUSTER SOURCE                                                REF    PR
dev  Development Development Never   jx        0
dev  Dev Permanent   Auto    dev        100           https://bitbucket.org/myTeam/environment-jx-dev.git master

**Comment by rawlingsj** [comment]
Interesting, so you want to promote automatically to two environments which use different git providers for the respective environments?

/priority important-longterm
/area git
