### ISSUE TITLE
helm failing during create cluster minikube

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#242]
Using:
NAME         VERSION                    
jx           1.0.63            
Kubernetes   v1.8.0            
Helm Client  v2.8.0+g14af25f   
Helm Server  v2.8.0+g14af25f   
Draft Client v0.9.0            
Draft Server v0.9.0            
Git          git version 2.15.1

Actions:
jx create cluster minikube runs as far as the helm install for jenkins-x then fails with the following:

helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.73 --values=/Users/terry/.jx/gitSecrets.yaml --values=/Users/terry/.jx/extraValues.yaml --namespace=jx
Error: failed to parse /Users/terry/.jx/extraValues.yaml: error converting YAML to JSON: yaml: line 13: found unexpected end of stream

**Comment by rawlingsj** [comment]
recreated and fix on its way

**Comment by rawlingsj** [comment]
1.0.64 release has started and should be available in ~20 mins
