### ISSUE TITLE
Deployment scenario not working 'out of the box' due to no environments

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#244]
Using:
NAME         VERSION                    
jx           1.0.64            
Jenkins X    0.0.83            
Kubernetes   v1.8.0            
Helm Client  v2.8.0+g14af25f   
Helm Server  v2.8.0+g14af25f   
Draft Client v0.9.0            
Draft Server v0.9.0            
Git          git version 2.15.1

Actions:
Post-installation, the following recommendation is made to the user:

```
Jenkins X installation completed successfully

To import existing projects into Jenkins: jx import
To create a new Spring Boot microservice: jx create spring -d web -d actuator
```

If a new Spring Boot microservice is created at this point, a build will run then the user will receive the following message:

> WARNING: No Environments have been created yet in team default. Please create some via 'jx create env'

There are a number of issues relating to this:

1. It's not really a warning, it's an error, since deployment fails silently at this point.
2. The Jenkins-X install should work minimally, 'out-of-the-box', so either create cluster should prompt the user to create environments, or create some appropriate defaults.
3. What is a 'team' in jx speak? They can't be created or viewed and aren't documented.
4. It's not actually accurate. In this case, two environments were created using 'jx create env' prior to creating the microservice, but these are presumably not associated with the 'team'.
5. A Dev environment is created by default, but this is not recognised by the build either.
6. I can't see an obvious way to associate an app with a namespace when 'jx create spring' is run?

**Comment by jstrachan** [comment]
Agreed - it’s confusing ;)

I was hoping to get ‘jx install’ & ‘jx create cluster *’  to default to setttig up a Staging and Prod environment using Auto - so that the OOTB experience is more useful.

You can also use the ‘jx promote’ command to manually promote to an environment  too

**Comment by tdcox** [comment]
It appears that the Dev environment is only partially created upon installation. jx get env shows no environments out of the box and build complain of no environments and fail. However, if you jx create env a Staging environment, the Dev environment suddenly appears (in the jx namespace) and builds can be deployed with jx promote.

**Comment by rawlingsj** [comment]
Yeah we dont currently create default environments but will do in the next day or two.

**Comment by michaelneale** [comment]
@rawlingsj 👍🏻
