### ISSUE TITLE
Add ability to apply basic manifests

### ISSUE THREAD

**Issue by jaxxstorm** [jenkins-x/jx#2442]
### Summary 

Following the discussion twitter, I'd like to ask that the ability to apply manifests directly be considered for addition

I spoke with @jstrachan on twitter regarding this, and he said:

> we should be able to use tagged/sha's of git repos instead of helm chart tarballs if you like pretty easily - we just need a canonical file format to refer to git repos + shas/versions so we can easily automate the promotion/rollback PRs

Essentially, I'd like to point to an existing git repo containing a set of manifests, perhaps under subdirectories, and jenkins-x will check out a specific tag or commit and apply the manifests

**Comment by rawlingsj** [comment]
I think we should be able to do this relatively easily.  Right now we just run a `helm apply` step when deploying but we could witch that to `kubectl apply -f .` instead.  

We use knative build templates to perform the deployment steps, here's the example for helm https://github.com/jenkins-x-charts/jx-build-templates/blob/master/jx-build-templates/templates/knative-deploy-buildtemplate.yaml

Let's try a kubectl apply version of this, we can use the same service account too.

/kind feature

**Comment by jaxxstorm** [comment]
I'd also recommend looking at [kubecfg](https://github.com/ksonnet/kubecfg) which has support for diff'ing and removing old resources with garbage-collection tags, too

**Comment by rawlingsj** [comment]
We can probably have a team setting to describe which type of deployment folks want, helm / kubectl right now.  Then when we create a new quickstart or import a new application we can check the team settings and use the correct knative build template for the prow config.

https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L896

**Comment by rawlingsj** [comment]
> I'd also recommend looking at kubecfg which has support for diff'ing and removing old resources with garbage-collection tags, too

ok great, yes let's add that as an option too!
