### ISSUE TITLE
Environment pipeline not able to run

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#245]
When creating an environment with GitOps enabled, there seems to be an error in the Jenkins log associated with creating the environment:

```
+ make install
helm upgrade "jx-staging" "env" --install --namespace "jx-staging"
Release "jx-staging" does not exist. Installing it now.
Error: release jx-staging failed: no objects visited
make: *** [install] Error 1
```

**Comment by jstrachan** [comment]
this is now fixed; newly created GitOps environments come with pre-populated objects so that empty environments don't fail
