### ISSUE TITLE
Jx integration tests in CI have high memory usage and can cause Serverless Jenkins JVM to OOM

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2457]
Here's a screenshot from stackdriver of a build pod, the spike is during the integration tests

<img width="499" alt="screen shot 2018-12-07 at 17 27 45" src="https://user-images.githubusercontent.com/1457180/49663217-dc450b80-fa45-11e8-87bc-f73555a4ee2d.png">

/area infra
/priority important-longterm

**Comment by ccojocar** [comment]
I will try to profile the integration tests to spot the memory peak.

**Comment by ccojocar** [comment]
Profiled the integration tests from `cmd_test`. They are consuming ~270MB. See the attached graph. 

[pprof_cmd_test.svg.txt](https://github.com/jenkins-x/jx/files/2803783/pprof_cmd_test.svg.txt)

**Comment by ccojocar** [comment]
The issue might be related to the number of parallel processes run by the `go build` command. I set it  to 2 in this PR and seems to help. 
https://github.com/jenkins-x/jx/pull/2867

**Comment by rawlingsj** [comment]
I just dug out the memory usage from stackdriver for the build pod that ran the reduced parallelism job referenced above.  Looks like there's still a big spike in memory used...

<img width="1315" alt="screen shot 2019-01-29 at 09 57 31" src="https://user-images.githubusercontent.com/1457180/51900151-7e310680-23ac-11e9-8edf-b2ab30c37f9e.png">

**Comment by rawlingsj** [comment]
```
jenkins-x        jx                   PR-2867 16    44m   Succeeded jenkinsxio/jenkins-go:skaffold_dev23   950a5747-23a4-11e9-8a00-0a580a300e34-pod-2023bb https://github.com/jenkins-x/jx.git
```

**Comment by ccojocar** [comment]
there is still this on master release build even with --p 2:

```
go build github.com/jenkins-x/jx/pkg/jx/cmd: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
FAIL	github.com/jenkins-x/jx/pkg/jx/cmd [build failed]
```
