### ISSUE TITLE
compliance command error due to sonobuoy 

### ISSUE THREAD

**Issue by msigler-cb** [jenkins-x/jx#2464]
### Summary 

compliance command error due to sonobuoy 

### Steps to reproduce the behavior

```
$ jx compliance status
error: failed to retrieve the status: sonobuoy namespace does not exist: namespaces "heptio-sonobuoy" not found
```

### Jx version

The output of `jx version` is:

```
jx version
Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: incompatible versions client[v2.12.0] server[v2.11.0]': exit status 1
NAME               VERSION
jx                 1.3.640
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.13.0
helm client        v2.12.0+gd325d2a
helm server        v2.11.0+g2e55dbe
git                git version 2.20.0
Operating System   Mac OS X 10.14.1 build 18B75
```

### Kubernetes cluster

GCP

### Operating system / Environment

macOS 10.14.1

### Expected behavior

While this may be related to client versions, I would still expect helm to be able to execute a list. Further, if this command is dependent on ```sonobuoy``` then it would be good to report the error as such, and better to suggest corrective action.

### Actual behavior

sonobuoy namespace does not exist

**Comment by ccojocar** [comment]
@msigler-cb I agree that the error message needs some tweaking. I think you didn't start the compliance scan at all. 

You can do so and then get the status:

`jx compliance run`
`jx compliance status`

after about 1 hour

`jx compliance results` 

You can view the live logs of the compliance scan at any time with `jx compliance logs -f`

**Comment by msigler-cb** [comment]
@ccojocar  Indeed, I did not start the ```run``` prior to ```status```.  Perhaps a better UX would be to prompt the user to do a ```run``` and inform them that it could take awhile to complete?
