### ISSUE TITLE
jx create spring is failing because it can not find spring-boot-starter-parent:pom:2.2.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2467]
### Summary 
`jx create spring` is failing because of 

`[FATAL] Non-resolvable parent POM for org.rverduci:test-pr:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.BUILD-SNAPSHOT in https://nexus-internal.cloudbees.com/content/groups/staged was cached in the local repository, resolution will not be reattempted until the update interval of cloudbees-internal has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 10`

### Steps to reproduce the behavior

1. go through all the steps of `jx create spring`
2. When it's trying to build the project, it will fail

### Jx version

The output of `jx version` is:

jx                 1.3.642
jenkins x platform 0.0.3036
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.10.4
helm client        v2.12.0+gd325d2a
helm server        v2.12.0+gd325d2a
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14 build 18A391

### Kubernetes cluster
GKE

### Operating system / Environment
Mac OS Mojave

### Expected behavior
Spring project should be building after we just create it

### Actual behavior
The first build is failing because of a spring dependency not found: org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.BUILD-SNAPSHOT

**Comment by romainverduci** [comment]
Imported as CNJ-87

**Comment by garethjevans** [comment]
@romainverduci are you able to attach some of the build log before the error?

**Comment by romainverduci** [comment]
Using the --advanced mode of `jx create spring` and selecting 2.2.0.BUILD-SNAPSHOT version of spring boot I'l getting:

`romains-macbook-pro:demo romain$ jx create spring --advanced
? Language: java
? Spring Boot version: 2.2.0.BUILD-SNAPSHOT
? Java version: 1.8
? Packaging: jar
? Build Tool: maven-project
? Group: com.example
? Artifact: demo2
? Dependencies: actuator, web
Created Spring Boot project at /Users/romain/workspace/github/rverduci-test-org/demo/demo2
No username defined for the current Git server!
? Git user name: romainverduci
The directory /Users/romain/workspace/github/rverduci-test-org/demo/demo2 is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
selected pack: /Users/romain/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/maven
? Which organisation do you want to use? rverduci-test-org
replacing placeholders in directory /Users/romain/workspace/github/rverduci-test-org/demo/demo2
app name: demo2, git server: github.com, org: rverduci-test-org, Docker registry org: rverduci-test-org
skipping directory "/Users/romain/workspace/github/rverduci-test-org/demo/demo2/.git"
error: Failed to update maven deploy plugin: Command failed 'mvn io.jenkins.updatebot:updatebot-maven-plugin:RELEASE:plugin -Dartifact=maven-deploy-plugin -Dversion=2.8.2': [INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.example:demo2:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.BUILD-SNAPSHOT in https://nexus-internal.cloudbees.com/content/groups/staged was cached in the local repository, resolution will not be reattempted until the update interval of cloudbees-internal has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example:demo2:0.0.1-SNAPSHOT (/Users/romain/workspace/github/rverduci-test-org/demo/demo2/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.example:demo2:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.BUILD-SNAPSHOT in https://nexus-internal.cloudbees.com/content/groups/staged was cached in the local repository, resolution will not be reattempted until the update interval of cloudbees-internal has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException exit status 1
`

**Comment by agentgonzo** [comment]
I suspect that this is because either your maven settings file is not correct or the nexus repo is not set up to mirror the spring snapshot repos. I get the same results as you, but if I delete my ~/.m2/settings.xml file, it builds fine.
