### ISSUE TITLE
Use different default Jenkins password

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#248]
I am not sure if there is a longer term plan for dev previews, but a hard coded default is not great when tyre kicking on GKE or other public clouds. It should be randomised. 

(also it would be nice if it could open() the browser to the Jenkins path to fetch the token, if that is to be a setup experience).

**Comment by rawlingsj** [comment]
Yeah hopefully we’ll get that sorted in the next few days. The idea is on jx create cluster or jx install you can either use flags or be promoted for a default admin password.

**Comment by rawlingsj** [comment]
You can now set a default admin password when creating clusters using the flag `--default-admin-password`.  If left blank a password is generated and printed at the end of the terminal output after creation.
