### ISSUE TITLE
jx env apply results in clusterrolebindings error

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#2480]
jx env apply results in clusterrolebindings error

**Comment by jtnord** [comment]
IIUC editing the git repo is only supported if the cluster was created with GitOPS enabled (`--gitops`) (which is still not a default)

@jstrachan am I correct/wrong here?

**Comment by jtnord** [comment]
(not sure this is team releated either - seems to be in the main jx namespace  `team: jx`)

**Comment by deanesmith** [comment]
Test 123

**Comment by deanesmith** [comment]
Closing since this bit will no longer be important with recent functionality.
