### ISSUE TITLE
add support for harbor registry 

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2489]
see https://www.cncf.io/blog/2018/07/31/cncf-to-host-harbor-in-the-sandbox/

/kind enhancement
/assign rawlingsj

**Comment by SyCode7** [comment]
Is this feature now available ?

**Comment by fjudith** [comment]
+1 

Harbor also support LDAP and OIDC for AuthN/AuthZand 
It is also fully manageable via REST API.

**Comment by leosunmo** [comment]
This is something that will probably stop me from properly using Jenkins X. Is there a nice way to use existing Chartmuseums and Docker registries right now even if it's not a "nice" out-of-the-box experience?

**Comment by athilaelhuno** [comment]
Hello, any news about this request

**Comment by bbhuston** [comment]
+1   Harbor + JenkinsX integration would be a great feature, specially given the fact that 1) Harbor will soon be able to host other artifacts (i.e., it could be a full Nexus replacement) and 2) the Harbor community is working to completely refactor the app to run natively as Kubernetes CRDs (think Strimzi Kafka Operator etc).

**Comment by marthydavid** [comment]
+1
