### ISSUE TITLE
(may be irrelevant) Unable to create without gitops now

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#249]
```
? Would you like to create a new Git repository to store this Environments source code? : No
? Git URL for the Environment source code: 
✘ Sorry, your reply was invalid: Value is required
```

If I pick No - it still asks me for a git url. 

(I am trying sans gitops as the gitops pipeline seems broken right now)

**Comment by michaelneale** [comment]
if non gitops is going away - can close this ticket.

**Comment by rawlingsj** [comment]
I think we can close this based on only pushing gitops.
