### ISSUE TITLE
Jenkins UI was gone

### ISSUE THREAD

**Issue by imroc** [jenkins-x/jx#2491]
### Summary 
when I reinstall jx and jenkins-x platform with the latest version, I found that the jenkins UI was gone, there's no jenkins pod and ingress for the UI like before. And I also found that there's five version added in one day... waht a frequent updates..
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.651
jenkins x platform 0.0.3036
Kubernetes cluster v1.10.5-qcloud-rev1
kubectl            v1.10.5-qcloud-rev1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.7.4
Operating System   Ubuntu 16.04.1 LTS
```

**Comment by garethjevans** [comment]
Hi @imroc, what flags did you use when reinstalling jx?  Am wondering if you are using prow?

**Comment by beebird** [comment]
try to run ``~/.jx/bin/helm get values jenkins-x`` to check what values were used during installation.

**Comment by imroc** [comment]
@garethjevans yep, jx install --prow

**Comment by garethjevans** [comment]
Ah, so with a prow based install, the jenkins ui isn't used, all the webhooks are sent directly to `hook` and `prowjobs`/`knative` builds are used to run each build.  As the jenkins-ui, in this configuration is just wasting memory/cpu in the cluster, we've disabled it.

**Comment by imroc** [comment]
@garethjevans  I got it. Is that only support github?

**Comment by garethjevans** [comment]
Prow currently only supports github. Although work is being done to allow it to support other providers (GHE, bitbucket)

**Comment by imroc** [comment]
Looking forward to prow can quickly support other git providers :)
