### ISSUE TITLE
Please upgrade kaniko

### ISSUE THREAD

**Issue by imroc** [jenkins-x/jx#2498]
I want to use kaniko to build images without previledged in localDir, not the gcsBucket, but the default build packs in current jenkins-x version, the skaffold.yaml use the apiVersion `skaffold/v1alpha2`, which do not support this configuration in `skaffold/v1beta1`:
``` bash
build:
  kaniko:
    buildContext:
      localDir: {}
```

**Comment by garethjevans** [comment]
The latest skaffold (0.19.0) is installed within the builder & serverless images.  If you have that installed locally you can run `skaffold fix` to update the scehema.

**Comment by ccojocar** [comment]
@garethjevans Can we merge the PR and fix this issue? Is anything preventing this?

**Comment by garethjevans** [comment]
I think we can close this, I'll create another one for the overall Skaffold / Kaniko upgrade work.
