### ISSUE TITLE
jx create terraform fails on initialising helm

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2507]
### Summary 
Running `jx create terraform` fails initialising helm the first run, then re running the command is working fine

### Steps to reproduce the behavior
1. Run `jx create terraform ...`

### Jx version

The output of `jx version` is:

jx 1.3.658
Kubernetes cluster v1.10.9-gke.5
kubectl v1.10.4
helm client v2.12.0+gd325d2a
helm server v2.11.0+g2e55dbe
git git version 2.17.2 (Apple Git-113)
Operating System Mac OS X 10.14 build 18A391

### Kubernetes cluster
GKE

### Operating system / Environment
Mac OS Mojave

### Expected behavior
Should work the first time.

### Actual behavior
romains-macbook-pro:rverduci-test-org romain$ jx create terraform --environment-git-owner rverduci-test-org -o rverduci-test-org --verbose
unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
? Missing required dependencies, deselect to avoid auto installing: helm
Installing helm
==> Downloading https://homebrew.bintray.com/bottles/kubernetes-helm-2.12.0.moja
Already downloaded: /Users/romain/Library/Caches/Homebrew/downloads/f4083b3cf983d6395cd5c8d7945d114195c659f64e74b4be26ce49848da2b187--kubernetes-helm-2.12.0.mojave.bottle.tar.gz
==> Pouring kubernetes-helm-2.12.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
/usr/local/etc/bash_completion.d

zsh completions have been installed to:
/usr/local/share/zsh/site-functions
==> Summary
🍺 /usr/local/Cellar/kubernetes-helm/2.12.0: 51 files, 79.4MB
Installing helm secrets plugin
Using helmBinary helm with feature flag: none
Initialising Helm 'init'
error: error installing helm: failed to initialize helm: failed to run 'helm init' command in directory '', output: '$HELM_HOME has been configured at /Users/romain/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:8080: connect: connection refused': exit status 1

**Comment by romainverduci** [comment]
Imported as CNJ-100

**Comment by garethjevans** [comment]
@romainverduci I can't reproduce this, anything else that was done before the command was run?

**Comment by garethjevans** [comment]
```11:37 $ jx create terraform --verbose
? Missing required dependencies, deselect to avoid auto installing: helm
Installing helm
==> Downloading https://homebrew.bintray.com/bottles/kubernetes-helm-2.12.0.moja
Already downloaded: /Users/garethjevans/Library/Caches/Homebrew/downloads/f4083b3cf983d6395cd5c8d7945d114195c659f64e74b4be26ce49848da2b187--kubernetes-helm-2.12.0.mojave.bottle.tar.gz
==> Pouring kubernetes-helm-2.12.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kubernetes-helm/2.12.0: 51 files, 79.4MB
Installing helm secrets plugin
Using helmBinary helm with feature flag: none
Initialising Helm 'init'
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&prompt=select_account&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&access_type=offline


Checking Terraform Version...
Determined terraform version as 0.11.10
Terraform version appears to be valid
Git configured for user: Gareth Evans and email gareth@bryncynfelin.co.uk

**Comment by romainverduci** [comment]
@garethjevans Nothing done before running the command but if you can not reproduce it's probably something with my local configuration.
I removed both ~/.jx and ~/.helm before running the `jx create terraform` command. 
Do you know if something else could have an impact ?

**Comment by garethjevans** [comment]
@romainverduci ok cheers, I tried removing ~/.helm beforehand, but not ~/.jx, will give that a go

**Comment by romainverduci** [comment]
@garethjevans After investigations, it looks like it's due to the fact that my kubectl was configured to a cluster I deleted before running my new install.
The `jx create terraform` is trying to do something with that cluster that has been removed and failing, we should definitely not do that.
