### ISSUE TITLE
add ability to use Preemptible VMs on GKE

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#2517]
When using GKE, it would be nice if we could allow user to choose to use preemptible vms.  these can offer a cost saving of 80% over a regular vm.

Would need to add configuration options to `jx create cluster gke` & `jx create terraform`

**Comment by ccojocar** [comment]
@garethjevans Isn't this fix?

**Comment by garethjevans** [comment]
@ccojocar yes, I'll close this, have opened another ticket for the terraform installation
