### ISSUE TITLE
Jenkins plugins directory missing

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#2522]
After migrating to the latest jenkins-x-platform, i am loosing the plugins directory after few builds. After that i am getting random behaviours.

Current jenkins version is 2.150.1

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during semantic analysis: Unable to load resource jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/validator/Messages.properties

java.util.MissingResourceException: Unable to load resource jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/validator/Messages.properties
	at org.jvnet.localizer.ResourceBundleHolder.get(ResourceBundleHolder.java:121)
	at org.jvnet.localizer.ResourceBundleHolder.get(ResourceBundleHolder.java:128)
```
/var/jenkins_home/plugins/ is . missing in the master

> jx                 1.3.620
> jenkins x platform 0.0.3034
> Kubernetes cluster v1.10.3
> kubectl            v1.12.3
> helm client        v2.11.0+g2e55dbe
> helm server        v2.11.0+g2e55dbe
> git                git version 2.8.4
> Operating System   "CentOS Linux release 7.6.1810 (Core) "

**Comment by ysaakpr** [comment]
In the resent jenkins-x-platform  i observed that the jenkins version is upgraded, is it related to any jenkins old data migration issue.

I tried restarting it. Initially few builds it works and i see that the plugins directory is getting removed after sometime.

**Comment by ccojocar** [comment]
@yahavi Still facing this issue? Please could you provide more details, how the plugins were installed.

**Comment by ccojocar** [comment]
@ysaakpr I am going to close this issue since it seems to be related to Jenkins plugins not jx.

**Comment by matiashaller** [comment]
Hello,

Sorry for reopening this issue, Did you find a solution?, I having same problem after some builds plugin folder gets removed.

Thank you!
Matias

**Comment by ysaakpr** [comment]
Restarting jenkins helped and i found that it was because of hard disk
getting filled and I increased and never faced the pblm later

**Comment by sso679** [comment]
Hello,guys i am facing the same issue .when i restart the jenkins master, which is running in container ,jenkins_home/plugins directory has list of all plugins .However, after sometime ,plugins directory is empty .
As you told hard disk need to be increased .could you please elaborate because my jenkins master is running in container.
