### ISSUE TITLE
Does jx on EKS need "gcloud"?

### ISSUE THREAD

**Issue by Only1Loatheb** [jenkins-x/jx#2527]
### Summary 
I try to automate jx install by using the options and I run into:
error: creating the system vault: Command failed 'gcloud projects list':  exec: "gcloud": executable file not found in $PATH

### Steps to reproduce the behavior
jx create cluster eks  --region=eu-west-1 --default-admin-password=mypassword -n tomek --skip-installation
jx install --provider=eks --namespace='jx' --default-admin-password=mypassword  --git-provider-url="https://github.com" --environment-git-owner='Only1Loatheb' --git-username="Only1Loatheb"  --gitops=true  --git-api-token "actual token" 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.657
jenkins x platform 0.0.3078
Kubernetes cluster v1.10.11-eks
kubectl            v1.13.0
helm client        v2.12.0+gd325d2a
helm server        v2.12.0+gd325d2a
git                git version 2.17.1
Operating System   Ubuntu 18.04.1 LTS
```

### Kubernetes cluster

jx create cluster eks  --region=eu-west-1 --default-admin-password=mypassword -n tomek --skip-installation

### Operating system / Environment
Operating System   Ubuntu 18.04.1 LTS
No pods stuck in pending. 

### Expected behavior
Not trying to use "gcloud" binary on EKS

### Actual behavior
jx install --provider=eks --namespace='jx' --default-admin-password=mypassword  --git-provider-url="https://github.com" --git-username="Only1Loatheb"  --gitops=true --environment-git-owner='Only1Loatheb' --git-api-token "actual token" --vault=false
Error loading team settings. Unable to locate dev environment resource definition in namespace default, No Environment called: dev or with selector: env=dev found 0 entries: []
Error loading team settings. Unable to locate dev environment resource definition in namespace default, No Environment called: dev or with selector: env=dev found 0 entries: []
Using helmBinary helm with feature flag: none
Git configured for user: Only1Loatheb and email myMail@gmail.com
Using helm2
Configuring tiller
Tiller Deployment is running in namespace kube-system
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
External loadbalancer created
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller

On AWS we recommend using a custom DNS name to access services in your Kubernetes cluster to ensure you can use all of your Availability Zones
If you do not have a custom DNS name you can use yet, then you can register a new one here: https://console.aws.amazon.com/route53/home?#DomainRegistration:

? Would you like to register a wildcard DNS ALIAS to point at this ELB address?  No

The Ingress address a65cbbf4e020411e98d080a73bef9c13-9110da45b004eafc.elb.eu-west-1.amazonaws.com is not an IP address. We recommend we try resolve it to a public IP address and use that for the domain to access services externally.
? Would you like wait and resolve this address to an IP address and use it for the domain? Yes

Waiting for a65cbbf4e020411e98d080a73bef9c13-9110da45b004eafc.elb.eu-west-1.amazonaws.com to be resolvable to an IP address...
a65cbbf4e020411e98d080a73bef9c13-9110da45b004eafc.elb.eu-west-1.amazonaws.com resolved to IP the.ip.of.k8s
You can now configure a wildcard DNS pointing to the new loadbalancer address the.ip.of.k8s

If you do not have a custom domain setup yet, Ingress rules will be set for magic dns nip.io.
Once you have a custom domain ready, you can update with the command jx upgrade ingress --cluster
If you don't have a wildcard DNS setup then setup a DNS (A) record and point it at: the.ip.of.k8s then use the DNS domain in the next input...
? Domain the.ip.of.k8s.nip.io
nginx ingress controller installed and configured
Installing vault-operator...
Updating Helm repository...
Helm repository update done.
Upgrading Chart 'upgrade --namespace  --install --force --timeout 6000 --version  --set image.repository=banzaicloud/vault-operator --set image.tag=0.3.17 --set  vault-operator jenkinsxio/vault-operator'
vault-operator addon succesfully installed.
Creating new system vault
error: creating the system vault: Command failed 'gcloud projects list':  exec: "gcloud": executable file not found in $PATH

**Comment by rawlingsj** [comment]
Agreed this is wrong and likely a bug.

/area install
/bug

**Comment by dimmel82** [comment]
Same issue with `--provider=minikube` when using `--gitops=true`.

**Comment by jstrachan** [comment]
I think the issue is specifying `--vault=false` . Try just don't mention `--vault` at all and it should be fine?

**Comment by jstrachan** [comment]
btw I'd ignore `--gitops` for now too until its more baked

**Comment by RiceBowlJr** [comment]
Hi,

I juste encountered the same issue:

```
jx install \
  --provider=eks \
  --git-username <myuser> \
  --git-api-token <my-token> \
  --git-private=true \
  --domain='meero.dev' \
  --git-provider-kind='github' \
  --global-tiller=true \
  --kaniko=true \
  --local-helm-repo-name='meero' \
  --namespace='jx' \
  --ng=true \
  --skip-setup-tiller=true \
  --tekton=true \
  --tiller-cluster-role=tiller \
  --tiller-namespace='kube-system' \
  --version='0.0.3561'
```

And I have the following result:

```
setting the dev namespace to: jx
Using helmBinary helm with feature flag: template-mode
Enabling helm template mode in the TeamSettings
Git configured for user: RiceBowlJr and email <mail>@gmail.com
Using helm2
Skipping tiller
Using helmBinary helm with feature flag: template-mode
Initialising Helm 'init --client-only'
helm installed and configured
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
External loadbalancer created
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
About to insert/update DNS CNAME record into HostedZone /hostedzone/<ID> with wildcard *.<domain> pointing to <ID>.elb.eu-west-1.amazonaws.com
Updated HostZone ID /hostedzone/<ID> successfully
nginx ingress controller installed and configured
error: creating the system vault: system vault is not supported for eks provider
```

I tried with and without the `--vault=false` option so that doesn't solve the issue. Any help there? I don't understand, if it doesn't work for me it shouldn't work for anybody on any provider other that GCP.

**Comment by RiceBowlJr** [comment]
Actualy it did come from the `ng=true` option which deploys a Vault.
