### ISSUE TITLE
PRs missing git credentials in prow mode

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#2549]
### Summary 

With Jenkins X in prow mode, with a private repo builds off master pass but those for PRs fail with:
```
F1220 12:36:33.361263       1 main.go:38] Unexpected error running git [fetch --depth=1 --recurse-submodules=yes origin 47c507eec2ee1d59cbaaa32af54775edc025fa5d]: exit status 128
fatal: could not read Username for 'https://github.com': No such device or address
```

**Workaround**: the service account used for PRs is missing the secret containing the git credentials. Add it as follows:
```
kubectl edit sa helm
```
and append:
```
  secrets:
  - name: knative-basic-user-pass
```

### Steps to reproduce the behavior

1. Install Jenkins X in prow mode
2. Import a private repo
3. Trigger a build for a PR

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.675
jenkins x platform 0.0.3110
Kubernetes cluster v1.11.5-gke.4
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.18.0
Operating System   Mac OS X 10.14.1 build 18B75
```

### Kubernetes cluster

GKE via `jx install`

### Expected behavior

PR builds fail

### Actual behavior

PR builds succeed

**Comment by rawlingsj** [comment]
this is now fixed and released https://github.com/jenkins-x-charts/knative/blob/d112e61/knative-build/templates/helm-sa.yaml#L5-L6

**Comment by rstriedl** [comment]
Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
