### ISSUE TITLE
Distinguish between org/repo/branches that differ only in case

### ISSUE THREAD

**Issue by markawm** [jenkins-x/jx#2551]
### Summary 

Various places we convert org/repo/branch into lowercase to meet the restrictions of K8S names (e.g. PipelineActivity.Name). This works fine, and allows org/repo/branch of mixed case to work ok. But wouldn't work if we ever happened to have two or more org/repo/branches that differed _only_ in case, e.g.
* my-org/my-repo/my-branch
* my-org/my-repo/My-Branch
 - these could be two different branches within GitHub, but would get mapped to the same K8S Name within Jenkins X and end up conflicting (e.g. being seen as the same pipeline).

Need to either have a way to encode the names into a K8S-safe name that is _also_ non-conflicting (this is what has been missing in the past, e.g. in `kube.ToValidName`), or just generate UUID style names and add a separate field to hold the human-readable display name (though don't like this as there is a helluva lot to be said for being able to quickly identify what a CRD 'is' by just looking at its Name).

### Steps to reproduce the behavior

Create two branches that differ only in case, watch confusion unfold...

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.645
jenkins x platform 0.0.3097
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.13.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.20.1
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by pmuir** [comment]
There is starting to be a lot of code which assume what the name of the activity is (all the apps/policy engine stuff). We should really change this to work on labels for lookup (i.e. a label for org, a label for repo and a label for branch) - can we do that *first* so we can migrate the apps etc. over to using labels? Note that labels don't suffer from the same character restrictions.

**Comment by markawm** [comment]
👍 
Agreed - like the display name would much prefer this is done by labels than the Name, which is very constrained.
(btw, I'm not planning to do anything on this imminently, was just raising it to track whilst fixing up some case sensitivity problems causing occasional duplicate PipelineActivities).
