### ISSUE TITLE
Forward slash in branch not properly escaped

### ISSUE THREAD

**Issue by sboardwell** [jenkins-x/jx#2563]
### Summary 

Branch names with a forward slash (e.g. `feature/jenkinsfile-testing-1`) are causing the jenkins-x-gcactivities pods to fail with:
```
$ kubectl logs jenkins-x-gcactivities-1545382800-7d9cl
error: failed to delete activity my-project-feature%2fjenkinsfile-testing-1: invalid resource name "my-project-feature%2fjenkinsfile-testing-1": [may not contain '%']
```
### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.671
jenkins x platform 0.0.3097
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.11.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.18.0
Operating System   Mac OS X 10.13.6 build 17G4015
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE - created by following the docs

**Comment by jglick** [comment]
There is also the problem that `PipelineActivitySpec.Pipeline` is a blank `string` which actually consists of `GitRepository` + `GitOwner` + a branch, and https://github.com/jenkins-x/jx/blob/994d0e709f4b4dc5c2d28b9fa210dcf3f5336e06/pkg/apis/jenkins.io/v1/types_pipeline.go#L249:L270 tries to parse it out. That code will break if branches with slashes in them are left unencoded.

**Comment by anub1s187** [comment]
Any update on this issue?
