### ISSUE TITLE
Jenkins-x Bitbucket server integration issues.

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [jenkins-x/jx#2564]
### Summary 
Unable to set up jx install with bitbucket server provider. I have provided the token with admin access but receiving the following  error.

 "Sorry, your reply was invalid: Status: 401 Unauthorized, Body: {"context":null,"message":"You are not permitted to access this resource"
 
Bitbucket server URL : https://git.XXXXXX.com/bitbucket

### Steps to reproduce the behavior
Run, jx create env staging --git-provider-url=https://git.XXXXXX.com/bitbucket
? Label: Staging
? Namespace: jx-staging
? Domain: X.X.X.X.nip.io
? Cluster URL: https://<clusterurl>
? Promotion Strategy: Auto
? We will now create a Git repository to store your staging environment, ok? : Yes
Using Git provider git.XXXXX.com at https://git.XXXXXXX.com/bitbucket
? Git user name? <username>

Which organisation do you want to use? <By default it takes my user name as org and not allowing me to enter any and i am not sure what to enter also for bitbucket>

### Jx version
1.3.681

The output of `jx version` is:
```
COPY OUTPUT HERE
```
NAME               VERSION
jx                 1.3.681
jenkins x platform 0.0.3110
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.11.5
helm client        v2.12.0+gd325d2a
helm server        v2.12.0+gd325d2a
git                git version 2.18.0.windows.1
Operating System  Windows 10 Pro 1703 build 15063

A new jx version is available: 1.3.684

### Kubernetes cluster
AWS - EKS
What kind of Kubernetes cluster are you using & how did you create it?
eksctl
### Expected behavior
Bitbucket repos should be created for staging and production by just pointing the Bitbucket server URL : https://git.XXXXXX.com/bitbucket by using jx cli.

### Actual behavior
Failing to authenticate and access bitbucket server with 404,401 etc. though API token has all the necessary access.

**Comment by UlaganathanNamachivayam** [comment]
Team, Appreciate if anyone could shed some light on it. I am receiving the following after choosing the project repo in bitbucket server.



Creating repository [32m????/environment-boazircon-staging[0m
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits.BitbucketServerRepositoryToGitRepository(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/bitbucket_server.go:117 +0x35a
github.com/jenkins-x/jx/pkg/gits.(*BitbucketServerProvider).GetRepository(0xc00088bad0, 0xc000ab7768, 0x4, 0xc0006e2e20, 0x1d, 0xc000635b18, 0x0, 0x0)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/bitbucket_server.go:137 +0x14a
github.com/jenkins-x/jx/pkg/kube.createEnvironmentGitRepo(0x2252601, 0x2c6d0e0, 0xc000aa97e0, 0xc000517000, 0x2930db6, 0x3b, 0xc000979110, 0x27, 0xc000635b18, 0xc000452d80, ...)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/env.go:351 +0x330
github.com/jenkins-x/jx/pkg/kube.CreateEnvGitRepository(0x1, 0x2c6d0e0, 0xc000aa97e0, 0xc000516000, 0xc000517000, 0xc0006356a0, 0x2930db6, 0x3b, 0xc000979110, 0x27, ...)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/env.go:287 +0x78e
github.com/jenkins-x/jx/pkg/kube.CreateEnvironmentSurvey(0x23dfb01, 0x2c6d0e0, 0xc000aa97e0, 0xc000516000, 0xc000517000, 0xc0006356a0, 0x2930db6, 0x3b, 0xc000a280dc, 0x2, ...)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/env.go:241 +0x5ef
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateEnvOptions).Run(0xc0006354a8, 0xc000a42600, 0x0)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_env.go:185 +0x466
github.com/jenkins-x/jx/pkg/jx/cmd.(*InstallOptions).createEnvironments(0xc000635000, 0x2897df1, 0x2, 0x0, 0x0)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:2007 +0x2ec
github.com/jenkins-x/jx/pkg/jx/cmd.(*InstallOptions).Run(0xc000635000, 0x0, 0x0)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:562 +0xd51
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdInstall.func1(0xc000673400, 0x4695fb8, 0x0, 0x0)
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/install.go:254 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000673400, 0x4695fb8, 0x0, 0x0, 0xc000673400, 0x4695fb8)
        /home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007b0000, 0x0, 0x0, 0x0)
        /home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xc0007b0000, 0xc0002d5400, 0x2c4ae60)
        /home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x32
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc000729f88, 0xc00007e058)
        /home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0xe3
main.main()
        /home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x29

**Comment by ansib** [comment]
I can confirm that this bug already exists.

Jenkins Serverless Version with Bitbucket Server 5.13.

API Token exists and has full rights. I tried it with write/admin rights.

NAME                     VERSION
jx                             1.3.911
Kubernetes cluster  v1.12.4+icp-ee
kubectl                    v1.10.11
git                           git version 2.18.0.windows.1
Operating System  Windows 10 Pro 1803 build 17134

What informations do you need?
