### ISSUE TITLE
servlerss jenkins hook ingress-service error

### ISSUE THREAD

**Issue by bygui86** [jenkins-x/jx#2572]
### Summary
During installation of serverless JX, the creation of "hook" ingress fails with this error: Error during sync: error while evaluating the ingress spec: service "jx/hook" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

### Steps to reproduce the behavior

* creation of a new GKE cluster

	* method 1: create a new GKE cluster using JX
```
		jx create cluster gke \
			--default-admin-password ***** \
			--kubernetes-version 1.11.5-gke.5 \
			--no-tiller \
			--zone europe-west2-a \
			--min-num-nodes 3 \
			--max-num-nodes 3 \
			--machine-type n1-standard-2 \
			--project-id ***** \
			--cluster-name jx-serverless \
			--default-environment-prefix jx-serverless \
			--domain ***** \
			--environment-git-owner interdiscount \
			--git-private true
```

	* method 2: 
```
		jx create terraform \
			--kubernetes-version 1.11.5-gke.5 \
			--default-admin-password ***** \
			--organisation-name ***** \
			--environment-git-owner ***** \
			--git-private true \
			--verbose
```

* go through the whole installation process

* look for created ingresses (I removed nexus and other tools ingresses due to security internal policy) (see screenshot below)
![image](https://user-images.githubusercontent.com/22518997/50382954-8d84ac00-06aa-11e9-87be-81b37c127199.png)

* giving a deeper look on "hook" ingress (see screenshot below)
![image](https://user-images.githubusercontent.com/22518997/50382955-91b0c980-06aa-11e9-82a2-d4fb42c9e5ba.png)

* giving a deeper look on "hook" service (see screenshot below)
![image](https://user-images.githubusercontent.com/22518997/50382956-95445080-06aa-11e9-92a9-c3f5df7d9db6.png)

### Jx version
1.3.684

### Kubernetes cluster
GKE version 1.11.5-gke.5

### Operating system / Environment
MacOsX 10.14.2

### Expected behavior
After the creation of a new GKE cluster using JX, the creation of "hook" ingress does not fail.

### Actual behavior
After the creation of a new GKE cluster using JX, the creation of "hook" ingress fails with this error: Error during sync: error while evaluating the ingress spec: service "jx/hook" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

**Comment by ccojocar** [comment]
cc @rawlingsj

**Comment by ccojocar** [comment]
@rawlingsj @garethjevans Is this issue fixed in the latest release or prow?

**Comment by bygui86** [comment]
I tested it 2 times between today and yesterday.
The hook ingress is presented by gke-dashboard having an error, but it is able to receive hooks from GitHub :)
So probably it is "partially" fixed.

```
jx version

jx                 1.3.733
jenkins x platform 0.0.3193
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.13.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.8.1
Operating System   Mac OS X 10.14.2 build 18C54
```

**Comment by rawlingsj** [comment]
Yeah I think this is just a log level as we see a lot of these in the API server logs but it shouldn't affect anything.  As far as I know this causes no issue apart from the message in the UI.  Would be good to fix but a low priority AFAICT.

**Comment by fai555** [comment]
Any update on this? Facing the same issue.
