### ISSUE TITLE
GKE cluster create with enable-autoupgrade fails

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#2573]
### Summary 

Creating a k8s cluster with `jx create cluster gke --enable-autoupgrade=true` fails

### Steps to reproduce the behavior

see above

### Jx version

The output of `jx --version` is:

```
1.3.686
```

### Kubernetes cluster

GKE

### Expected behavior

Forwarding the flag correctly to `gcluster containers cluster create ...`

### Actual behavior

The flag is appended by the value `true` as in `gcloud container clusters create ... --enable-autoupgrade true ...`.
However, the gcloud command does not accept a parameter for this option.

**Comment by garethjevans** [comment]
Closing this issue, the referenced PR appears to have been merged which should resolve the issue
