### ISSUE TITLE
Could not find a pack for Java. Trying to find the next likely language match...

### ISSUE THREAD

**Issue by MastanaGuru** [jenkins-x/jx#2580]
### Summary 
Newbie to jenkins-x. Getting pack errors trying to run jx import for a Java Rest Service project

### Steps to reproduce the behavior
jx import --url GitUrl
performing pack detection in folder /Users/u740885/jxProjects/PMFSvc/ProviderMFSvc
--> Draft detected Java (94.126469%)
--> Could not find a pack for Java. Trying to find the next likely language match...
--> Draft detected XML (3.107456%)
--> Could not find a pack for XML. Trying to find the next likely language match...
--> Draft detected RPM Spec (1.295966%)
--> Could not find a pack for RPM Spec. Trying to find the next likely language match...
--> Draft detected Eagle (0.858386%)
--> Could not find a pack for Eagle. Trying to find the next likely language match...
--> Draft detected Coq (0.433633%)
--> Could not find a pack for Coq. Trying to find the next likely language match...
--> Draft detected Java Server Pages (0.178090%)
--> Could not find a pack for Java Server Pages. Trying to find the next likely language match...
error: there was an error detecting the language using packs from /Users/u740885/jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs
### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.688
jenkins x platform 0.0.3125
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.13.1
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.20.0
Operating System   Mac OS X 10.14.2 build 18C54

### Kubernetes cluster

minishift v1.28.0+48e89ed

**Comment by michaelneale** [comment]
@jstrachan what should default for java be - does such a thing make sense or it needs to know what kind of java app?

**Comment by michaelneale** [comment]
yeah that makes sense - there is no generic way to "build java" in any case - there is no prescribed structure (other than the package paths, but that doesn't say where the root is, or what dependencies are) so not surprising. If anything if it sees no dependency thing like maven or gradle, but knows it is java, it probably needs to error out ideally.
