### ISSUE TITLE
Build badge for Jenkins X powered builds

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#2581]
Would be nice to have a build badge that can be places as an image tag on repo readmes (similar to travis, Jenkins classic) etc. to indicate the status of the default branch build for CI builds. 

The info is likely there so this could probably be done with a small service that serves up the appropriate image only

**Comment by michaelneale** [comment]
Start of an implementation of this as a microservice: https://github.com/michaelneale/jx-buildbadge

if that was wired into the pipeline CRD may make sense to run this as a knative app - this would require https://github.com/jenkins-x/jx/issues/1379 to support knative "serverless" apps, as it would be absurd to run this service except for when needed, but in theory does make sense as an add on like this.

**Comment by garethjevans** [comment]
@michaelneale take a look at https://github.com/jenkins-x-apps/jx-app-statusbadge/blob/master/README.md, this is running on our production cluster and can be used with shields.io to generate a badge
