### ISSUE TITLE
controller.go:188: failed to reconcile /jx/…: nil BuildSpec

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2582]
### Summary 

I opened two pull requests on the same repo, each modifying the same file but in different parts. I waited for PR builds of both to finish successful. Then I `/approve`d each at the same time. The first one got automatically merged as expected. The second one, however, stayed open despite having all statuses successful:

> **tide** — In merge pool.

Upon inspecting the cluster, I saw that there was a `ProwJob`  with no corresponding `Build`:

```yaml
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: serverless-jenkins
  creationTimestamp: "2018-12-28T00:15:57Z"
  generation: 1
  labels:
    created-by-prow: "true"
    prow.k8s.io/job: serverless-jenkins
    prow.k8s.io/refs.org: …
    prow.k8s.io/refs.pull: …
    prow.k8s.io/refs.repo: …
    prow.k8s.io/type: presubmit
  name: …
  namespace: jx
  resourceVersion: …
  selfLink: /apis/prow.k8s.io/v1/namespaces/jx/prowjobs/…
  uid: …
spec:
  agent: knative-build
  context: serverless-jenkins
  job: serverless-jenkins
  refs:
    base_ref: master
    base_sha: …
    org: …
    pulls:
    - author: …
      number: …
      sha: …
    repo: …
  report: true
  rerun_command: /test this
  type: presubmit
status:
  startTime: "2018-12-28T00:15:57Z"
  state: triggered
```

and in the `prow-build` logs I saw

```
jx/prow-build-…[prow-build]: E1228 00:20:46.911683       1 controller.go:188] failed to reconcile /jx/…: nil BuildSpec
```

Indeed acc. to

```sh
kubectl get -o json prowjobs | jq '.items | .[] | {name: .metadata.name, sa: .spec.build_spec.serviceAccountName}'
```

this was the only `ProwJob` with no `BuildSpec`.

### Steps to reproduce the behavior

Unknown. Race condition perhaps?

### Jx version

```yaml
Pod Template:
  Labels:           app=prow-build
  Service Account:  prow-build
  Containers:
   prow-build:
    Image:      rawlingsj/build:upstream76
```

### Kubernetes cluster

GKE

**Comment by jglick** [comment]
Adding `/test this` seems to serve as a workaround.

**Comment by jglick** [comment]
@Vlatombe suggests that `ProwJob`s created by Tide, as opposed to Hook, were missing the `build_spec`; and that upgrading Tide to `gcr.io/k8s-prow/tide:v20181204-7cd5855` fixes the issue. Unfortunately I did not think to record the `tide` deployment version in use at the time of the error.

**Comment by Vlatombe** [comment]
I would guess the version currently referenced in the chart (https://github.com/jenkins-x-charts/prow/blob/master/prow/values.yaml#L206): `gcr.io/k8s-prow/tide:v20181113-9b11013`
