### ISSUE TITLE
jx upgrade  ingress  --cluster not working on EKS (http -> https)

### ISSUE THREAD

**Issue by thebalaa** [jenkins-x/jx#2584]
### Summary 

I have a jx  cluster created with `jx create cluster eks`

### Steps to reproduce the behavior

Vanilla  eks jx cluster

Run `jx upgrade ingress --cluster`

Cluster is broken; SSL error in browser

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.688
Kubernetes cluster v1.10.11-eks
kubectl            v1.13.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

`jx create cluster eks`

### Operating system / Environment

N/A

### Expected behavior

jx cluster becomes available via https

### Actual behavior

cluster is broken

**Comment by HarryCaveMan** [comment]
Same issue,  luster working with http then run `jx upgrade ingress -- cluster`  and only get timeouts

**Comment by HarryCaveMan** [comment]
# Update:
I retried this using the latest release (1.3.816) which was about 6 hours ago. One thing I failed to mention earlier is that I chose serverless Jenkins. I now get an error message running `js upgrade ingress`:

The part right before failure:
```sh
Certificate issuer letsencrypt-prod does not exist. Creating...
Updating Helm repository...
Helm repository update done.
```
The error on the next line:
```sh
error: creating the ingress rules: failed waiting for exposecontroller job to succeed: job exposecontroller never succeeded
```

**Comment by hnioche** [comment]
I have the same issue. I tried either to upgrade using
```
jx upgrade ingress --cluster
```

Or a total new installation using `--tls-acme=true` parameter.
In both situation I endup with a non functioning installation where both HTTP and HTTPS ingress time outs.

I don't know if it's relevant, I'm new to Jenkins X and Kubernetes, but I noticed this message after certificates have been generated in the cert-manager pod living in the `cert-manager` namespace:
```
I0131 14:22:41.294838       1 controller.go:189] orders controller: Finished processing work item "jx/tls-hook-106593683"
I0131 14:22:48.572799       1 controller.go:173] ingress-shim controller: syncing item 'jx/cm-acme-http-solver-s2pkm'
I0131 14:22:48.572885       1 sync.go:64] Not syncing ingress jx/cm-acme-http-solver-s2pkm as it does not contain necessary annotations
I0131 14:22:48.572899       1 controller.go:179] ingress-shim controller: Finished processing work item "jx/cm-acme-http-solver-s2pkm
```

**Comment by hnioche** [comment]
I now got it working by adding manually the HTTPS mapping in the load balancer service used for ingress, even after the upgrade it was only setup for HTTP.

To summarize what I had to do to get jx `upgrade ingress --cluster` working:
* Run `jx upgrade ingress --cluster` until no more certificate error or timeout error was displayed
* Manually add HTTPS mapping in the load balancer service

I'm totally new to this so I can't provide relevant logs, but I'm happy to do the process again and produce some if needed as long as someone can tell me where should I get those.

**Comment by fleskesvor** [comment]
I'm having the same issue on GKE. The process seemingly succeeds and new ingresses are created, but there are no https mappings.

**Comment by dmonteiro-paddle** [comment]
@hnioche i'm having the same issue as you. can you give me an example on how you changed the https mapping? 

What i tried was on the nginx controller service, edit the yaml file and change this: 
"spec": {
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 80,
        "targetPort": "http",
        "nodePort": 31583
      }
    ],

to

**Comment by hnioche** [comment]
@dmonteiro-paddle I've changed my setup, so this is what I did from what I remember:
* Make sure that 443 and 80 are mapped to the cluster nodes target groups. The load balancer that has been created should be an NLB, so it should ask you for a certificate.
* Make sure that 443 and 80 are open in your node security group

AWS support confirmed that there's an issue with the security group missing one of the port after an update to the ingress controller. This is being dealt with on Kubernetes side. They also advised me not to use NLB with kubernets for now as the implementation is not considered as stabled. You should be able to switch to a classic ELB by removing the NLB annotation in the load balancer service created by Jenkins X.

**Comment by macalinao** [comment]
I'm getting this when adding 443 TCP to my NLB:

```
 % curl https://jenkins.jx.<redacted>.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by uny** [comment]
I could make it work following this:
https://github.com/jenkins-x/jx/issues/6029#issuecomment-552738474

**Comment by dgozalo** [comment]
EKS is now supported for Jenkins X Boot instead of Jenkins X Install.

Upgrade ingress will not work with Boot as the way to make this work is to run the dev environment master pipeline again to apply new configuration. 

I'm closing this issue as it won't apply to the current state of EKS support.
