### ISSUE TITLE
jx import process fails on differing artifactid and app name

### ISSUE THREAD

**Issue by jecafarelli** [jenkins-x/jx#2586]
### Summary 
Found 2 bugs I am combining together on this one issue. Once triaged, they can be split up if its easier.

bug 1. if there are any changes to the git repo when it gets to [this section of the code](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L1291), it will try to commit code only in the chart folder. If there are no modifications to this directory, the import process will fail with error below:

```
error: failed to run 'git commit -m fix:(chart) fix up the probe path' command in directory '/home/jenkins/workspace/import/git_repo', output: '# On branch jx-import-process-52
# Your branch is ahead of 'origin/jx-import-process-52' by 3 commits.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   .dockerignore
#
no changes added to commit (use "git add" and/or "git commit -a")': exit status 1
```

bug 2. I found the bug above, because the import process was not properly fixing the probe path in the values.yaml of the chart. When manually running [this command](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L1277), I found below output:

```bash-4.2$ ~/.jx/maven/bin/mvn io.jenkins.updatebot:updatebot-maven-plugin:RELEASE:chart
[INFO] Scanning for projects...
[INFO] 
...
[WARNING] The values.yaml file: /home/jenkins/workspace/import/git_repo/charts/${ARTIFACT_ID}/values.yaml does not exist
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.625 s
[INFO] Finished at: 2018-12-31T15:11:55Z
[INFO] ------------------------------------------------------------------------
```

It turned out that our artifact id in our pom.yaml did not match the APP name that was generated (guessing from the git repo name?), making the probe path not be updated, and silently failing. Should be some sort of validation that the artifact id matches the app name, or have this java command use the env var over artifact id so that it does not just silently fail when this situation happens

### Steps to reproduce the behavior
1. create a java repo to import. 
2. create a file with a .dockerignore that has Dockerfile and some other lines in it
3. create a pom.xml that has an artifact Id that does not match with the APP NAME pulled from repo im guessing?
4. do a jx import using the maven build pack.
### Jx version

```
The output of `jx version` is:
bash-4.2$ jx version
NAME               VERSION
jx                 1.3.688
jenkins x platform 0.0.3125
Kubernetes cluster v1.10.11
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.12.0+gd325d2a
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core) 
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
AWS kubernetes cluster using kops
### Expected behavior
jx import should fail if artifactid doesnt match generated chart path name, or fix it, or use the generated path name and not artifactid.

jx import should be able to tell if there are changes to the git repo directory; check it its changes in the chart directory and skip commit if there are no changes.
### Actual behavior

jx import silently fails to update probe path because it cant find the directory to the chart that matches the artifactid.

jx import checked for changes in git directory, then tries adding the chart directory and fails if there are no changes in that directory

**Comment by jstrachan** [comment]
@jecafarelli fancy submitting a Pull Request by any chance? :)

**Comment by ccojocar** [comment]
dup of #2699
