### ISSUE TITLE
Docker registry does not get created

### ISSUE THREAD

**Issue by MastanaGuru** [jenkins-x/jx#2592]
### Summary 
jx create cluster minishift  does not create a jenkins-x docker repository. The generated file  ⁨jx⁩/cloud-environments⁩/⁨env-minishift⁩/myvalues.yaml has 
# disable monocular until the routing is fixed
monocular:
     enabled: false
docker-registry:
     enabled: false      
 
Global:
    EnvVars:
      DOCKER_REGISTRY: "docker-registry.default.svc:5000"

           
### Steps to reproduce the behavior
jx create cluster minishift --git-provider-url=ghegitURL --git-username=ghegitusername --git-api-token=ghegitApiToken  --git-private=true  --default-environment-prefix='xyz'  --default-admin-password='xxxx' --vm-driver='virtualbox'

### Jx version
NAME               VERSION
jx                 1.3.688
jenkins x platform 0.0.3125
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.13.1
helm client        v2.12.1+g02a47c7
helm server        v2.12.0+gd325d2a
git                git version 2.20.0
Operating System   Mac OS X 10.14.2 build 18C54

### Kubernetes cluster

minishift v1.28.0+48e89ed

**Comment by jstrachan** [comment]
this is by design I think - to reuse the docker registry inside openshift?

**Comment by MastanaGuru** [comment]
@jstrachan I am getting the below error, is there any parameters I need to change to use the openshift registry ?
Successfully built 7ebb0db126c8
The push refers to a repository [docker-registry.default.svc:5000/u740885/providermfsvc]
time="2019-01-04T16:31:17Z" level=fatal msg="build failed: building [changeme]: tagging: pushing: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc on 10.0.2.3:53: no such host"
