### ISSUE TITLE
Upgrade helm/tiller to 2.12.1

### ISSUE THREAD

**Issue by polothy** [jenkins-x/jx#2595]
### Summary 

Looks like Helm 2.12 introduced a regression that was reverted in 2.12.1.

* Release notes: https://github.com/helm/helm/releases/tag/v2.12.1
* Regression: https://github.com/helm/helm/issues/5054

We didn't experience this with JX itself, but rather when we were installing Istio.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior

When running Helm install, it does not error by complaining about a CRD already existing.

### Actual behavior

Helm install complains about CRDs already existing when you are attempting to install the CRDs.

**Comment by polothy** [comment]
Created:

- https://github.com/jenkins-x/jenkins-x-serverless/pull/207
- https://github.com/jenkins-x/jenkins-x-builders/pull/194

**Comment by michaelneale** [comment]
I think I have seen this too - cc @jstrachan @ccojocar

**Comment by jstrachan** [comment]
release complete with new helm version
