### ISSUE TITLE
How to install an additional namespace additional to default created?

### ISSUE THREAD

**Issue by lcrodriguez** [jenkins-x/jx#2600]
### Summary 

I'm trying to add a new namespace to separate a new team in the same cluster.
I'm not finding any documentation on how to do it in an easy way or complex way.

### Steps to reproduce the behavior

I'm trying to run: jx install --namespace='anotherteamname'

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.693
jenkins x platform 0.0.3143
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.10.7
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.6 (stretch)

### Kubernetes cluster

Created on Google Cloud.

### Expected behavior

A new namespace with its own jenkins be setup and work as the main one installed by default with the 3 defaults environments.

I've executed:

jx install --namespace=newname

### Actual behavior

Got an error:

waiting for install to be ready, if this is the first time then it will take a while to download images
error: installing the Jenkins X platform: failed to wait for jenkinx-x chart installation to be ready: no deployments found in namespace northstar

**Comment by jstrachan** [comment]
for multiple teams in the same cluster you need to also add the `--no-tiller` argument to disable the global tiller (which only allows 1 install of jx per cluster).

could you try `jx install --no-tiller --namespace northstar`

**Comment by markediez** [comment]
Last time I checked, you can create JX Teams. Each team has its own namespace and jenkins. The namespace 'jx' itself is a team (which is why you can run `jx team jx` to get to the proper namespace and context).

So if you run `jx team <new team name>` . Wait a bit. It should start spinning up a new jenkins instance with its own namespace.

**Comment by jstrachan** [comment]
I think this is fixed now - there's documentation here: https://jenkins-x.io/about/features/#teams

**Comment by debu99** [comment]
it failed when the default namespace is not jx

**Comment by jstrachan** [comment]
@debu99 could you raise a new issue please with the failure log?
