### ISSUE TITLE
How to link external service in preview environment

### ISSUE THREAD

**Issue by MichalFoksa** [jenkins-x/jx#2604]
### Summary 
From a preview environment I want to access a MySQL database located in staging environment (namespace `jx-staging`). Target database service name in `jx-staging` namespace is called `mysql`.

I am following [Service Linking](https://jenkins-x.io/developing/preview/#adding-more-resources) documentation with no success.

I created a service file in `charts/preview/resources/mysql.yaml` with following content, but the Kubernetes service is not created in preview namespace.

    # charts/preview/resources/mysql.yaml
    kind: Service
    apiVersion: v1
    metadata:
      name: mysql
    spec:
      type: ExternalName
      externalName: mysql.jx-staging.svc.cluster.local
      ports:
      - port: 3306

Manual service creation works `kubecrl create -n <PREVIEW-NS> -f charts/preview/resources/mysql.yaml`

Information available is confusing. Documentation claims service linking works, but after reading #573 I wonder if the functionality is implemented. Then #1227 implements something in the matter, but I do not know how it is related.

**My question is [How to link external service in preview environment](https://stackoverflow.com/questions/54027529/jenkins-x-how-to-link-external-service-in-preview-environment)?**

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.688
jenkins x platform 0.0.3125
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.10.7
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.6 (stretch)
```

### Kubernetes cluster
It is Google Kubernetes engine:

    jx create cluster gke --skip-login --project-id=test-and-eval \
      --default-admin-password=[PASSWORD] \
      --cluster-name=jx-e1 \
      --domain=cp1.example.com \
      --git-username=[GITUSER] \
      --git-api-token=TOKEN \
      --machine-type=n1-standard-2 \
      --min-num-nodes=2 \
      --max-num-nodes=5 \
      --zone=us-central1-a \
      --verbose=true

**Comment by jstrachan** [comment]
I've just fixed the typo in those service linking docs; the path should have been `charts/preview/templates/mysql.yaml` - i.e. not `/resources/` - I wonder if that fixes your issue and you get the `Service` created?

e.g. `jx get service -n jx-myuser-myapp-pr-1 -oyaml`

you can find the namespace of a Preview Environment via `jx get preview` btw
