### ISSUE TITLE
`jx uninstall` should delete the environment repos that are created on install

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#2606]
### Steps to reproduce the behavior
Do a `jx install` or `jx create cluster`
jx will create github repos for the `staging` and `production` environments
do a `jx uninstall`

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 ?[32m1.3.693?[0m
Kubernetes cluster ?[32mv1.10.9-gke.5?[0m
kubectl            ?[32mv1.10.3?[0m
helm client        ?[32mv2.11.0+g2e55dbe?[0m
helm server        ?[32mv2.11.0+g2e55dbe?[0m
git                ?[32mgit version 2.15.1.windows.2?[0m
Operating System   ?[32mWindows 10 Pro 1809 build 17763?[0m
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GKE

### Expected behavior
jx should delete the github repos for staging and production that it created

### Actual behavior
it does not, and you end up with 300 repos cluttering up your organisation.

**Comment by jstrachan** [comment]
deleting git repos should be optional though - as you may want to recreate a k8s cluster while keeping the git history and repos

**Comment by agentgonzo** [comment]
oh totally agree it should be optional (whether the default is `true` or `false` is open to debate though)
