### ISSUE TITLE
deployment build-controller never became ready

### ISSUE THREAD

**Issue by dattran929** [jenkins-x/jx#2612]
### Summary 
I'm trying to install jenkins x on digital ocean kubernetes cluster.  But i got the error build-controller never became ready.  checking the pod status it showed InvalidImageName. The yaml output showed the image name as rawlingsj/build-controller:upstream3:9502ac4288ac2cd0f42352913ddf15aebc8319239e1118f08fae217d5b5536ee 
### Steps to reproduce the behavior
jx install

### Jx version
jx version 1.3.699

The output of `jx version` is:

```
jx                 1.3.699
jenkins x platform 0.0.3143
Kubernetes cluster v1.13.1
kubectl            v1.13.0
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.11.0 (Apple Git-81)
Operating System   Mac OS X 10.12.6 build 16G29
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
digital ocean managed kubernetes.  Created using digital ocean dashboard

### Operating system / Environment
debian
### Expected behavior
successful installation
### Actual behavior
deployment build-controller never became ready.  Pod showing InvalidImageName

**Comment by rawlingsj** [comment]
@dattran929 this should be fixed now, can you get the latest `jx` again and run the upgrade please?
```
jx upgrade cli
jx upgrade addon prow
```
