### ISSUE TITLE
--pending flag ignored for jx get users

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2616]
### Summary 

according to the help --pending should `Display only pending Users which are not yet provisioned yet`

ergo `jx get users --pending=true` and `jx get users --pending=false` must show different output

However this is not the case.  (I am also unclear how a user can be pending)

### Steps to reproduce the behavior

run
* jx get users --pending=true` 
then
* `jx get users --pending=false`

compare the output

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 [32m1.3.696[0m
jenkins x platform [32m0.0.3143[0m
Kubernetes cluster [32mv1.11.5-gke.5[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.11.0+g2e55dbe[0m
helm server        [32mv2.11.0+g2e55dbe[0m
git                [32mgit version 2.16.2.windows.1[0m
Operating System   [32mWindows 10 Pro 1803 build 17134[0m
```

### Kubernetes cluster

GKE, terraform

### Operating system / Environment

can be removed - see above

### Expected behavior

the commands have different output (one shows only pending users and the other shows only non pending users)

### Actual behavior

the output is identical

**Comment by jstrachan** [comment]
looks like a copy/paste help text issue - there's no such thing as a pending user AFAIK - thats from Teams
