### ISSUE TITLE
jx import fails with https

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#2622]
### Summary 
I have setup the jenkins service to be available only on https, and to redirect all traffic from http to https. When I try to import my code, jx defaults to the http version, and fails to import because of the 301 redirect.

### Steps to reproduce the behavior
1. Setup forced https redirect on jenkins url
2. Import a project

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.700
jenkins x platform 0.0.3143
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.13.1
helm client        3.alpha-js-1+unreleased+g4544d69
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GKE - COS images - created manually

### Operating system / Environment
Mac OS 10.14.2

### Expected behavior
jx import should work.

### Actual behavior
jx import should work

**Comment by heroic** [comment]
As per the source, the url is picked based on whether the jenkins ingress has a tls and a host. However,  as we use an API gateway, this didn't work for us. Maybe we can use a configmap for the jenkins url and let the user decide if they need to use http or https?

**Comment by lgg42** [comment]
Have you checked your ~/.jx/jenkinsAuth.yaml file?

**Comment by heroic** [comment]
@lgg42 not even sure what the issue was anymore! I've moved to jx ng, and mostly things are working fine. I'll close this issue as it doesn't seem anyone else is facing it anymore!
