### ISSUE TITLE
Promote to environments dies

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#2628]
### Summary 
Once the build finishes, jenkins starts the Promote to environment step. The script dies trying to generate the changelog.

### Steps to reproduce the behavior
1. import an existing nodejs app from url
2. let the jenkins build fail a few times, before getting a success
3. the build passes and promote to environment step starts
4. the pipeline dies

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.702
jenkins x platform 0.0.3143
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.13.1
helm client        3.alpha-js-1+unreleased+g4544d69
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Operating system / Environment
COS image / GKE

### Expected behavior
The changelog should be generated

### Actual behavior
The changelog generation dies with the error:

```
++ cat ../../VERSION
+ jx step changelog --version v1.0.17
Using batch mode as inside a pipeline
Generating change log from git ref v1 => 20a29b3b45469538da3d33927c6eea9caae87a54
error: object not found
script returned exit code 1
```

The command works on my dev machine though

**Comment by heroic** [comment]
This got fixed if I deleted all previous tags. Leaving this open since the root cause is still unknown

**Comment by ccojocar** [comment]
@heroic Is the entire pipeline or the `jx step changelog` command which cannot fetch the changes from you git repo. Could you please try to run the command against your repo?

**Comment by heroic** [comment]
@ccojocar This works if I run the command locally. However, in jenkins it dies. It works if I delete all the tags, and run the build again though.

Just the `jx step changelog` command fails

**Comment by ccojocar** [comment]
@heroic I am going to close this issue. There is another issue for changelog https://github.com/jenkins-x/jx/issues/3008. Thanks
