### ISSUE TITLE
Create / Import fails with Server Error

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#263]
Using:

> NAME        VERSION                    
> jx          1.0.72            
> Jenkins X   0.0.102           
> Kubernetes  v1.8.6-gke.0      
> Helm Client v2.8.0+g14af25f   
> Helm Server v2.8.0+g14af25f   
> Git         git version 2.15.1

Actions:
Delete Jenkins-X install on GKE cluster with jx uninstall
Reinstall Jenkins-X with jx install --provider gke -d <redacted>
Create new app with jx create spring -d web -d adaptor

After creation of the git repository, the process fails with the following message:

```
About to create a repository on server github.com with user <redacted>
? Enter the new repository name:  deleteme02

Creating repository <redacted>/deleteme02
Counting objects: 48, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (35/35), done.
Writing objects: 100% (48/48), 51.22 KiB | 7.32 MiB/s, done.
Total 48 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), done.
To https://github.com/<redacted>/deleteme02.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Pushed git repository to https://github.com/<redacted>/deleteme02

error: error creating jenkins credential jenkins-x-chartmuseum 500 Server Error
```

Looks like the problem is whilst creating the Jenkins Credential here:
https://github.com/jenkins-x/jx/blob/51ce7e31ea0033e2f35544c3adc92db397b67e44/pkg/jx/cmd/import.go#L793

A previously created environment was still visible after install, so I am guessing that uninstall doesn't return the cluster to a clean state?

**Comment by michaelneale** [comment]
@tdcox quite possibly yes - although I was able to create a fresh cluster but keep my local cache intact just before (this is using the latest version, may be a recent fix)

**Comment by carlossg** [comment]
this is probably the same issue as #414, 500 due to existing previous credentials

**Comment by rawlingsj** [comment]
this has been fixed now https://github.com/jenkins-x/jx/pull/979
