### ISSUE TITLE
knative-build chart installation fails but installation continues

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/jx#2637]
### Summary 

When reinstalling after purging all jx related helm charts the installation succeeds but knative-build chart is not installed. Even though the log shows 

```
Installing knative into namespace jx
Updating Helm repository...
Helm repository update done.
Upgrading Chart 'upgrade --namespace jx --install --force --timeout 6000 --version  --set build.auth.git.username=xxx --set build.auth.git.password=xxx --set  knative-build jenkins-x/knative-build'
```

Trying to install manually noticed that the crds were already present, so purging the knative-build chart does not delete the crds.
The new installation fails because the crds already exist and jx does not detect the helm failure and continues installation

### Steps to reproduce the behavior

```
jx install
jx uninstall
helm delete --purge knative-build
jx install
```

Install will succeed but knative-build helm chart is not installed

### Jx version

```
jx                 1.3.704
Kubernetes cluster v1.11.5-gke.5
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

GKE created with jx create

### Expected behavior

`jx install` should have failed
`helm delete --purge knative-build` should have deleted the knative crds

### Actual behavior

jx install succeeded but knative helm chart was not installed

**Comment by rawlingsj** [comment]
referenced wrong issue in PR

**Comment by rawlingsj** [comment]
rather than running the helm purge command use jx instead:
```
jx delete addon knative-build
```
