### ISSUE TITLE
Please update eksctl to support more EKS regions

### ISSUE THREAD

**Issue by aiqdevops** [jenkins-x/jx#2638]
### Summary 
I want to deploy to in Singapore region with jx create cluster eks, but it prompted me this region not supported. Apparently AWS has updated EKS support in this region. So please update the eksctl version which is currently hardcoded in the code.

### Jx version

The output of `jx version` is: 1.3.628

```
1.3.628
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

jx create cluster eks

**Comment by hekonsek** [comment]
I've upgraded eksctl to the most recent version in this PR - https://github.com/jenkins-x/jx/pull/2709
