### ISSUE TITLE
Potential architectural conflict

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#264]
From the types of issues I am seeing, I have a concern that there may be a conflict of models in operation here and would like to understand the approach to mitigating that.

Kubernetes is declarative in nature - you tell it what you want and it works out how to provision it.

JX is somewhat more procedural, with lazy instantiation and client-side caching - you tell it what to do and it gathers required state for that process.

The risk is that JX is therefore vulnerable to assumptions about the state of the cluster that may not be valid. For example:

- cluster state and local client cached data may go out of sync
- JX platform may be redeployed, but previously deployed pods/namespaces etc remain active

As a result, the presence of data on the cluster or in the cache may suggest that a required prior procedure has been undertaken (with side effects) when it has not, or it's side effects have been erased by other activity. Under these circumstances, the errors tend to be unpredictable and unresolvable by the user.

It feels like we need some assertions around the assumed state of the cluster with a standard way to self-heal in the event of divergence?

**Comment by michaelneale** [comment]
@tdcox good points - in terms of the day to day of things, like promotion and creation, at least using pipelines maps more to declarative (ie the state you want will apply eventually, not necessarily when the command returns to you).

**Comment by michaelneale** [comment]
perhaps @tdcox could put this in the wiki to discuss?

**Comment by tdcox** [comment]
@michaelneale I'm afraid I don't have access, but please feel free to forward on my behalf.
