### ISSUE TITLE
mvn not found in executor 

### ISSUE THREAD

**Issue by NoahMarconi** [jenkins-x/jx#2640]
### Summary 

I am trying to set up Jenkinx X and make use of the quick starts. With the camel quickstart, I'm getting a mvn not found error on the Jenkins executor.

### Steps to reproduce the behavior

- Set up cluster with `jx create cluster eks`
- Set up quickstart with `jx create camel`
- Log into Jenkins
- Change number of executors from `0` to `1`
- Commit change to quickstart came repo

Executor begins and logs this error:

```




cat VERSION


mvn versions:set -DnewVersion=


/var/jenkins_home/workspace/testApp_master@tmp/durable-d2f04c7a/script.sh: 1: /var/jenkins_home/workspace/testApp_master@tmp/durable-d2f04c7a/script.sh: mvn: not found

script returned exit code 127
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.688
jenkins x platform 0.0.3125
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.1
helm client        v2.12.1+g02a47c7
helm server        v2.12.0+gd325d2a
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

`jx create cluster eks`

### Operating system / Environment

Local is Mac OS X remote is AWS EKS created with jx

### Expected behavior

mvn should not be a missing dependency on executor

### Actual behavior

mvn is missing on executor:

```
cat VERSION


mvn versions:set -DnewVersion=


/var/jenkins_home/workspace/testApp_master@tmp/durable-d2f04c7a/script.sh: 1: /var/jenkins_home/workspace/testApp_master@tmp/durable-d2f04c7a/script.sh: mvn: not found

script returned exit code 127

```

**Comment by MichalFoksa** [comment]
Hi @NoahMarconi ,

I cannot reproduce the bug, what do you mean by:
> Change number of executors from 0 to 1

?

**Comment by NoahMarconi** [comment]
I deleted the cluster but let me reproduce again and share some extra info. 

To answer the question about changing the number of executors, this was in the jenkins UI as the default was set to 0 so the pipeline didn't run at all. I had to set it to 1 to have it attempt to run, then it threw the `mvn not found` error

**Comment by MichalFoksa** [comment]
On a commit push, Jenkins created a new maven pod and built application. Without any intervention from my side.

**Comment by rawlingsj** [comment]
Yeah as @MichalFoksa suggests, we use build pods as Jenkins agents.  These should all be automatically created using the kubernetes-plugin and config setup by Jenkins X.  You shouldn't need to change the executors on the Jenkins server as you will hit the error you get above because we only install build tools in the build pods (not the Jenkins server).

I wonder if there's another issue where the build pod doesn't start.  Can you see anything in the Jenkins pod logs?
