### ISSUE TITLE
AWS ECR registry created in default profile region but not in the same region with cluster

### ISSUE THREAD

**Issue by StephenWangasg** [jenkins-x/jx#2652]
### Summary 
ECR registry is always created in default AWSCLI profile region. but not in the region where the cluster is hosted.

### Steps to reproduce the behavior
1. Create two AWSCLI profiles at different region
   $aws configure set default.region ap-southeast-1
   $aws configure set profile.profile-sydney.region ap-southeast-2

2. Create a cluster with profile-sydney
    $jx create cluster aws --profile profile-sydney

DOCKER_REGISTRY is ${ACCOUNTID}.dkr.ecr.ap-southeast-1.amazonaws.com

### Jx version

The output of `jx version` is:

```
1.3.688
```

**Comment by hekonsek** [comment]
Hi Stephen. This PR is gonna to fix this issue - https://github.com/jenkins-x/jx/pull/2707
