### ISSUE TITLE
jx import -u fails

### ISSUE THREAD

**Issue by cnorburn** [jenkins-x/jx#2660]
When ```jx import -u URL``` is run importing from one cluster to a new one, it fails in Jenkins when executing the Jenkinsfile

Have two clusters, one working, one newly created, try and import jobs from old to new

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.714
jenkins x platform 0.0.3143
Kubernetes cluster v1.11.4
kubectl            v1.13.0
helm client        v2.9.1+g20adb27
helm server        v2.12.1+g02a47c7
git                git version 2.8.3
Operating System   Mac OS X 10.14.1 build 18B75
```

### Kubernetes cluster

```jx create cluster aks```

### Operating system / Environment
Azure

### Expected behavior

A successful import of a job from an old cluster to a new one

### Actual behavior

Jenkins job fails with -
```
+ jx step changelog --version v1.0.13
Using batch mode as inside a pipeline
Generating change log from git ref v1.0.0 => 181334a8814441c3b479e6a62fd4cb2e494b5650
error: object not found

```

**Comment by warrenbailey** [comment]
I can't seem to recreate this issue. I've managed to import a Java Spring project between clusters a couple times now using that version of `jx`

@cnorburn is this still a problem for you?  If so, do you have any more information? What type of project is it? A link to the github repository your trying to import would be extremely useful.

**Comment by cnorburn** [comment]
Thanks @warrenbailey.

It's a private repo i'm afraid.

I worked around it by renaming the repo, create a new one with the same name and then manually creating the job in Jenkins.

I suspect, but haven't tried yet, that my laptops .jx, .azure, .git and .kube config files are in a mess and need cleaning up.

I'll close this now.
