### ISSUE TITLE
"jx step helm release" received 409 response: {"error":"file already exists"} when promote to environments

### ISSUE THREAD

**Issue by sonyafenge** [jenkins-x/jx#2661]
### Summary 
when running promote to environments, "jx step helm release" always try to upload chart file [RepoName]-0.1.0-SNAPSHOT.tgz to http://jenkins-x-chartmuseum:8080/api/charts, so received 409 response: {"error":"file already exists"}.
previous step: "jx step changelog --version v$(cat ../../VERSION) — Shell Script" running good with correct VERSION,

### Steps to reproduce the behavior
1. jx create quick start, 
2. change code, commit, and merge from github;
3. get error and log as below:

```
jx step helm release — Shell Script
[sonyardccdemo06] Running shell script

+ jx step helm release

No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080

Using helmBinary helm with feature flag: none

Adding missing Helm repo: jenkins-x http://chartmuseum.jenkins-x.io

Successfully added Helm repository jenkins-x.

Adding missing Helm repo: releases http://jenkins-x-chartmuseum:8080

Successfully added Helm repository releases.

No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080

Uploading chart file sonyardccdemo06-0.1.0-SNAPSHOT.tgz to http://jenkins-x-chartmuseum:8080/api/charts

Received 409 response: {"error":"file already exists"}

error: Failed to post chart to http://jenkins-x-chartmuseum:8080/api/charts due to response 409: {"error":"file already exists"}

script returned exit code 1
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.706
Kubernetes cluster v1.11.2
kubectl            v1.11.3
helm client        v2.12.0+gd325d2a
helm server        v2.11.0+g2e55dbe
git                git version 2.7.4
Operating System   Ubuntu 16.04.5 LTS

```

### Kubernetes cluster

aws and using quick start for Kubernetes by Heptio

### Operating system / Environment
AWS EC2 Linux
### Expected behavior
"jx step helm release" uploading correct version chart to chartmuseum and run successfully

### Actual behavior
"jx step helm release" uploading wrong version chart to chartmuseum

**Comment by sonyali03** [comment]
@genglj, I checked Makefile. it looks good. VERSION has correct value as you mentioned:
```
CHART_REPO := http://jenkins-x-chartmuseum:8080
CURRENT=$(pwd)
NAME := sonyardccdemo06
OS := $(shell uname)
VERSION := $(shell cat ../../VERSION)
```
looks like  "step_helm_release.go" get version information from chart.yaml. but chart.yaml in github repo never get updated and always keep "version: 0.1.0-SNAPSHOT". I tried to manually chage chart.yaml to correct version and then "restart promote to environments", "jx step helm release " run successfully and uploading correct version's chart file to chart museum.

**Comment by rawlingsj** [comment]
Is this from one of the Jenkins X quickstarts?  I just tried one here and the VERSION was set correctly, if it's not one of the quickstarts are you able to point us at the project (or one that fails in the same way if it's a private repo) so we can recreate and fix the issue?

/priority awaiting-more-evidence
/area quickstart

**Comment by sonyali03** [comment]
yes, this is from the Jenkins X quickstarts - golang.

**Comment by sonyali03** [comment]
Should chart.yaml be updated for each time when promote to staging environment or just keep the preview snapshot version is by design? looks like  "step_helm_release.go" got version information from chart.yaml, but I cannot find where chart.yaml is updated. from previous step:  "jx step changelog --version", it looks like only release tag updated to github.

**Comment by DXTimer** [comment]
We were experiencing similar behaviour, which was due to the charts not being tagged with the new version.
It was mentioned that in previous versions the Makefiles were used to carry out the tagging, however, it was deprecated in favour of [jx step tag --version X.X.X](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/step_tag.go).

Our immediate solution is to run an edited version of the Makefile `:tag` right before the release.

**Comment by iftachsc** [comment]
@DXTimer can u share exactly what u did?
