### ISSUE TITLE
add the ability to locate the 'admin' namespace

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2662]
### Summary 

From [https://kubernetes.slack.com/archives/C9LTHT2BB/p1547215177297500](slack)
Certain parts of `jx` need to know where the admin namespace is.  currently there is no easy way to find this.
It would be great if there was an easy way to find this (e.g. a label) so when performing actions like `jx create team` `jx create user` the CRDs will end up in the correct namespace.

Currently there is nothing to prevent a user performing a full install into distinct namespaces, as part of this the second install could be rejected and the user directed to create a team instead.  Or the user could be allowed to do this - in which case finding the admin namespace would likely resort to the first admin namespace found (which would likely cause confusion, and not be as good.) or more work would be to introduce a new parameter `--adminnamespace` for the case of multiple installs.

### Steps to reproduce the behavior

N/A

### Jx version

jx 1.3.702

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

N/a

### Operating system / Environment

N/A

### Expected behavior

code can easily identify the admin namespace.

### Actual behavior

code has to jump through some hoops to guess the admin namespace.

**Comment by jstrachan** [comment]
we could add a label to the namespace when folks create a Team/User etc?

**Comment by jtnord** [comment]
@jstrachan If I understand you mean when you do `jx create team` the team would have a label `adminNamespace` that points back to admin (`jx`) namespace?

then this would be used by `jx create user` / `jx edit userrole` etc?

That would work - and would mean that you could still have multiple installs (distinct from a teams) which I guess would be handy for the BDD tests.

I guess we can add this label to existing teams in the team controller when it is first run (by looking at the team CRDs).
