### ISSUE TITLE
AWS: Error: NoCredentialProviders: no valid providers in chain  during install

### ISSUE THREAD

**Issue by gumerman** [jenkins-x/jx#2663]
### Summary 
Get an error after prompt for how many nodes to create about credentials.  Where do I find instructions on how to let install see these credentials?
### Steps to reproduce the behavior
jx create cluster aws --no-default-environments
### Jx version

The output of `jx version` is:

```
[root@ip-10-10-10-10 richard.gumerman]# jx version

Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: could not find tiller': exit status 1

Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.12.1+g02a47c7

Error: could not find tiller': exit status 1

NAME               VERSION

jx                 1.3.706

Kubernetes cluster v1.12.2

kubectl            v1.12.2

git                git version 1.8.3.1

Operating System   Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Actual behavior
[richard.gumerman@ip-10-10-10-10 ~]$ sudo su

[root@ip-10-10-10-10 richard.gumerman]# mkdir -p ~/.jx/bin

[root@ip-10-10-10-10 richard.gumerman]# curl -L Caution-https://github.com/jenkins-x/jx/releases/download/v1.3.706/jx-linux-amd64.tar.gz | tar xzv -C ~/.jx/bin

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   612    0   612    0     0   2169      0 --:--:-- --:--:-- --:--:--  2177

jx

100 32.9M  100 32.9M    0     0  7766k      0  0:00:04  0:00:04 --:--:-- 9934k

[root@ip-10-10-10-10 richard.gumerman]# export PATH=$PATH:~/.jx/bin

[root@ip-10-10-10-10 richard.gumerman]# echo 'export PATH=$PATH:~/.jx/bin' >> ~/.bashrc

[root@ip-10-10-10-10 richard.gumerman]# jx create cluster aws --no-default-environments

? Missing required dependencies, deselect to avoid auto installing: kops, helm

Installing kops

Downloading Caution-https://github.com/kubernetes/kops/releases/download/1.11.0/kops-linux-amd64 to /root/.jx/bin/kops.tmp...

Downloaded /root/.jx/bin/kops.tmp

Installing helm

Downloading Caution-https://storage.googleapis.com/kubernetes-helm/helm-v2.12.1-linux-amd64.tar.gz to /root/.jx/bin/helm.tgz...

Downloaded /root/.jx/bin/helm.tgz

Installing helm secrets plugin

? nodes 3

error: NoCredentialProviders: no valid providers in chain. Deprecated.

        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by wbrefvem** [comment]
It looks like you don't have tiller installed on your cluster, so helm commands are failing.

**Comment by ccojocar** [comment]
@gumerman Try to follow these instructions to install on AWS https://jenkins-x.io/getting-started/create-cluster/#using-amazon-aws and https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-a-cloud

**Comment by ccojocar** [comment]
@gumerman I am going to close this issue. Please fell free to open another one if you are still facing the problem. Thanks
