### ISSUE TITLE
Document the security process

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2684]
### Summary 

As a user or developer of Jenkins-X discovering a security issue I need to know where to report that vulnerability.

As a developer of Jenkins-x I need to know how we will release and announce security fixes in a co-ordinated way.

### Steps to reproduce the behavior

N/A purely documentation at this point.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by jtnord** [comment]
@jstrachan is reporting that we use the same way as Jenkins (the SECURITY project in issues.jenkins-ci.org) for reporting issues.

**Comment by jtnord** [comment]
@pmuir this has some overlap with apps, not sure if the same process should be used here or not (but for now I will assume yes)

**Comment by garethjevans** [comment]
After speaking to the JenkinsCI security team, we need to add some text on the jenkins-x website documenting how to use the process.
