### ISSUE TITLE
jx create team does not work

### ISSUE THREAD

**Issue by StephenWangasg** [jenkins-x/jx#2694]
### Summary 
Jx create team does not work as expected. Team Controller has a bug looking for organization setting from previous jx install.

### Steps to reproduce the behavior

1. Create cluster
$jx create cluster eks --skip-installation

2.create first team 'Team-A"
$jx install --namespace Team-A --provider eks 

3. create second team "Team-B"
$jx create team Team-B

### Jx version

The output of `jx version` is:

```
1.3.723
```

### Expected behavior
Team Controller creates "Team-B" by calling 'jx install' in the background.

### Actual behavior
Logs:
Creating default staging and production environments
Unable to install jx for team Team-B: creating the environments: building the Git repository options for environments: determining the git owner for environments: Unable to find development environment in 'jx' to take git owner from

Comments:
Apparently I do not have 'jx' namespace in my system. The coder naively assumed user created the first team using the default 'jx' namespace.

**Comment by jtnord** [comment]
I have just merged something that hopefully helps.
although if the code really does hard code jx then it won't help.
the controller would as a fallback have used the current namespace...

**Comment by jtnord** [comment]
did you change namespace before running `jx create team Team-B`. create team should just create the card in the admin namespace which (with the code just merged) if you are not in a teams namespace or environment will just use the current namespace (but then that should not have a controller...)

**Comment by StephenWangasg** [comment]
I am in the Team-A namespace when run `jx create team Team-B`.
I checked the code I think the problem is with controller_team.go
`io.SetDevNamespace(teamNs)`
Then you run `io.Run()` which does not know which namespace to look for extra information it needed during jenkins-x installation. So it had go to 'jx' namespace to search.
Error is found in install.go
```
func (options *InstallOptions) buildGitRepositoryOptionsForEnvironments() (*gits.GitRepositoryOptions, error) {
    //...
    org := options.Flags.EnvironmentGitOwner
    //controller_team.go did not pass EnvironmentGitOwner in, so it't nil
    if org == "" {
      //...
      org, err = kube.GetDevEnvGitOwner(jxClient)
      //...
    }
    // ...
}
```


```
func GetDevEnvGitOwner(jxClient versioned.Interface) (string, error) {

	adminDevEnv, err := GetDevEnvironment(jxClient, "jx")

	if err != nil {
		log.Errorf("Error loading team settings. %v\n", err)
		return "", err
	}
	if adminDevEnv != nil {
		return adminDevEnv.Spec.TeamSettings.EnvOrganisation, nil
	}
	return "", errors.New("Unable to find development environment in 'jx' to take git owner from")
}
```

**Comment by patrickleet** [comment]
running `jx controller team` manually will initialize teams that have been created with `jx create team` that didn't actually get created

**Comment by patrickleet** [comment]
even so, the gc-activities and gc-previews for the new teams continue to fail
