### ISSUE TITLE
Issue to override the MavenSettingsXML value

### ISSUE THREAD

**Issue by glefevre** [jenkins-x/jx#2695]
### Summary 
I am trying to update the configuration of my Jenkins X instance in order to define a custom value for the Maven settings but my custom definition is not taken into account when doing a `jx install`, only the default value is used.

### Steps to reproduce the behavior
I have created a `myvalues.yaml` file in which I have defined the following:
```
PipelineSecrets:
  MavenSettingsXML: |-
    <settings>
    [...] 
    </settings>
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.736
jenkins x platform 0.0.3193
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.13.1
helm client        Client: v2.12.1+g02a47c7
git                git version 2.14.1
Operating System   Ubuntu 17.10
```

### Kubernetes cluster

I am using GKE 

### Expected behavior
The generated templates use the overridden value of the property `PipelineSecrects.MavenSettingsXML` and not the default one defined in `values.yaml`.

### Actual behavior
After running the `jx install` command, I have checked the creation of the jenkins-maven-settings secret and it is still the default value (even when I manually delete it before re-installing jenkins-x). In the output templates, the value is the default value and not my own override.

**Comment by garethjevans** [comment]
Hi @glefevre, does `jx upgrade platform` also override this?

**Comment by glefevre** [comment]
It worked like a charm! Thanks a lot for your help!
