### ISSUE TITLE
unable to contact server for jx get apps/versions (jx 1.0.80)

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#270]
Setting up a fresh cluster on GKE

* Both staging and production environments are created automatically (nice)

run `jx get apps` or `jx get versions`: 

`error: the server could not find the requested resource`

* Create a sample spring boot app, pipeline runs, gitops pipeline run SUCCESS

however still not able to run `jx get versions`

**Comment by jstrachan** [comment]
we chatted about this and its probably because the PR for the promotion didn't get merged. We're working on auto-merging the PRs by default in `jx promote`...

**Comment by jstrachan** [comment]
BTW just merged a `jx promote` that does the PR too now. You'll need to create/import a new project or hand-edit your `Jenkinsfile` to add the `--timeout 1h` argument to the `jx promote` line

**Comment by michaelneale** [comment]
ok cool - I think I had a problem with the PR merging and the deploy job running, but I will retest fresh today

**Comment by michaelneale** [comment]
@jstrachan as of latest version - the PRs to the environment repos were merged and deployed - but jx get versions/apps still isn't returning anything.

**Comment by jstrachan** [comment]
@michaelneale yeah - I got that too sorry! ;) lemme look, must have broken something...

**Comment by michaelneale** [comment]
yep all good now
