### ISSUE TITLE
jenkinsx does not accept maven properties in plugins pom xml

### ISSUE THREAD

**Issue by bygui86** [jenkins-x/jx#2703]
### Summary
Project import fails because of a maven error.
Looking around seems that JX does not like maven properties usage in plugin section of maven pom xml.
This happens to me just with two plugins:

* maven-deploy-plugin
* maven-surefire-plugin

This is not working

```
...
<properties>
	...
	<maven-surefire-plugin.version>3.0.0-M1</maven-surefire-plugin.version>
	<maven-deploy-plugin.version>2.8.2</maven-surefire-plugin.version>
	...
</properties>
...
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>${maven-surefire-plugin.version}</version>
</plugin>
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-deploy-plugin</artifactId>
	<version>${maven-deploy-plugin.version}</version>
</plugin>
...
```

This works

```
...
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>3.0.0-M1</version>
</plugin>
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-deploy-plugin</artifactId>
	<version>2.8.2</version>
</plugin>
...
```

### Steps to reproduce the behavior

* create a GKE cluster using `jx create cluster gke`
* clone project repo locally
* run `jx import`

Here logs from `jx import`:

```
No username defined for the current Git server!
? Git user name: bygui86
selected pack: /Users/matteobaiguini/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/maven
existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step
? Which organisation do you want to use? interdiscount
replacing placeholders in directory /Users/matteobaiguini/projects/officials/interdiscount/microservices/inventory-service
app name: inventory-service, git server: github.com, org: interdiscount, Docker registry org: interdiscount
skipping ignored file "/Users/matteobaiguini/projects/officials/interdiscount/microservices/inventory-service/.DS_Store"
skipping directory "/Users/matteobaiguini/projects/officials/interdiscount/microservices/inventory-service/target"
...
skipping ignored file "/Users/matteobaiguini/projects/officials/interdiscount/microservices/inventory-service/testing/.DS_Store"
error: Failed to update maven surefire plugin: Command failed 'mvn io.jenkins.updatebot:updatebot-maven-plugin:RELEASE:plugin -Dartifact=maven-surefire-plugin -Dversion=3.0.0-M1': [INFO] Scanning for projects...
[INFO]
[INFO] ----------< ch.interdiscount.microservices:inventory-service >----------
[INFO] Building inventory-service 0.0.127
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- updatebot-maven-plugin:1.1.12:plugin (default-cli) @ inventory-service ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.500 s
[INFO] Finished at: 2019-01-16T15:01:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.jenkins.updatebot:updatebot-maven-plugin:1.1.12:plugin (default-cli) on project inventory-service: Execution default-cli of goal io.jenkins.updatebot:updatebot-maven-plugin:1.1.12:plugin failed.: UnsupportedOperationException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException exit status 1
 output:
```

### Jx version
1.3.733

### Kubernetes cluster
GKE version 1.10.9-gke.5

### Operating system / Environment
MacOsX 10.14.2

### Expected behavior
The project should be imported without problems also using properties for the afore mentioned maven plugins.

### Actual behavior
The project import fails when properties are specified in the plugin section of maven pom xml.

**Comment by aheritier** [comment]
Can we ask to `jx import` to run maven with `-X` ?

**Comment by garethjevans** [comment]
@bygui86 a new flag has been introduced into `jx import` called `--disable-updatebot`, can you try this when importing the project? It should allow you to skip the failing part of the process.

**Comment by bygui86** [comment]
@garethjevans thank you very much!
I will try for sure as soon as #2704 will be merged. At the moment my cluster is stuck with the ingress problem.

**Comment by bygui86** [comment]
@garethjevans may I ask you what exactly does this "update bot"?

**Comment by garethjevans** [comment]
sure, its a tool that can be used to update dependencies in a project.  When we import a maven project, we use it to attempt to set some plugin versions (there are some known broken plugins), but it looks like it doesn't handle maven properties correctly.  There was already code to skip this step, but the flag has only just been exposed to the cli.

https://github.com/jenkins-x/updatebot
https://dzone.com/articles/using-jenkins-x-updatebot

**Comment by bygui86** [comment]
Got it. Thanks a lot!

**Comment by bygui86** [comment]
#2704 seems to be resolved.
I'm preparing a new application to be imported with `jx import --disable-updatebot`.
I will let you know the results.

**Comment by bygui86** [comment]
@garethjevans the command `jx import --disable-updatebot` seems to work.
Unfortunately I have other issue on the cluster so I can't say that ti worked 100% properly...

**Comment by garethjevans** [comment]
Closing this as the issue is now fixed
