### ISSUE TITLE
 Add prefix to dev build tag to ease image deletion

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#2706]
The storage usage can increase quickly in the docker registry when using a devpod, therefore support for deleting dev images is needed.

As far as I know there is no mechanism in Jenkins-X to clean away dev images from the registry (created with skaffold -p dev).

But an easy work around that would help at least with AWS ECR is to use a special prefix in the image tag. Then a lifecycle policy can be created to delete these images after, say, a day.

**Comment by tomhobson** [comment]
Hey, with the jenkins-x v3 changes, it now seems like we prefix preview images and they can now be purged cleanly. So closing this issue.

Thanks!

**Comment by msvticket** [comment]
dev images are something else than preview images: https://jenkins-x.io/docs/reference/devpods/

But jx3 doesn't have support for dev pods, so I don't object to closing this issue.
