### ISSUE TITLE
Enable skaffold / kaniko to build all docker images by default

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#2711]
We should remove the mounting of the docker socket and switch to skaffold / kaniko for building all docker images on jenkins-x.

Requires: https://github.com/GoogleContainerTools/skaffold/pull/1466

Should provide the basis for a number of issues:
https://github.com/jenkins-x/jx/issues/2153
https://github.com/jenkins-x/jx/issues/850

**Comment by garethjevans** [comment]
May also depend on https://github.com/jenkins-x/jx/issues/2697 if a GCS bucket is required to share the build context.

**Comment by garethjevans** [comment]
Suggested rollout plan:

1. skaffold PR needs to be merged & released
1. update skaffold in jenkins-x-builders/jenkins-x-serverless
1. wait to ensure the rollout of base images
1. update buildpacks to generate updated skaffold configuration (v1beta3)?
1. create docs for switching to GCR & Dockerhub rather than internal registry

**Comment by garethjevans** [comment]
Getting https://github.com/GoogleContainerTools/skaffold/pull/1458 merged in v0.21.0 would also make it much easier.

**Comment by joostvdg** [comment]
It seems [GoogleContainerTools/skaffold#1458](https://github.com/GoogleContainerTools/skaffold/pull/1458) was cancelled. Is this still the plan?

**Comment by abayer** [comment]
Do we still care about this?

**Comment by deanesmith** [comment]
@garethjevans what do you think?

**Comment by pmuir** [comment]
@garethjevans I've flagged this as stale as we don't seem to be working on it
