### ISSUE TITLE
gcpreviews jobs failing because helm is missing

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#2723]
### Summary 

https://github.com/jenkins-x/jx/pull/2668 and https://github.com/jenkins-x/jenkins-x-platform/pull/4652 broke the gcpreviews job, because it tries to run helm from inside the `jenkinsxio/jx` docker image - which only contains `jx`

### Steps to reproduce the behavior

- create a PR with `jx` >= 1.3.748
- merge or close the PR
- if running jenkins-x-platform >= 0.0.3247, the gcpreview job will try to use helm to delete the release, and fail

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.750
jenkins x platform 0.0.3247
Kubernetes cluster v1.11.5-gke.5
kubectl            v1.13.2
helm client        Client: v2.12.2+g7d2b0c7
Server: v2.12.2+g7d2b0c7
git                git version 2.20.1
Operating System   Mac OS X 10.12.6 build 16G1510
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior

gcpreviews jobs succeeding

### Actual behavior

gcpreviews jobs failing

**Comment by vbehar** [comment]
@ccojocar it's fixed in https://github.com/jenkins-x/jenkins-x-platform/pull/4692 - just need to merge it

**Comment by vbehar** [comment]
I used a custom-made image with my local changes on jx (before creating a PR), and with helm/tiller/kubectl - basically something like https://github.com/jenkins-x/jx/pull/2725
it's just that I forgot that I added more tools to the image when creating the PR

**Comment by ccojocar** [comment]
Thanks, I approved the PR.
