### ISSUE TITLE
secrets.yaml.dec is ignored during `jx install`

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#2732]
### Summary 

When reinstalling jx-infra, helm successfully decrypted the secrets.yaml file in cloud-environments, but then used the encrypted version when installing jx.

This appears to be a regression since some of the vault work.

**Comment by ccojocar** [comment]
@garethjevans Are the decrypted secretes in `~/.jx/adminSecrets.yaml` or newly generated?

**Comment by garethjevans** [comment]
@ccojocar it's when we read them from cloud-environments/env-$provider/secrets.yaml, when they are decrypted, they end up in cloud-environments/env-$provider/secrets.yaml.dec, but the original file is used for the install
