### ISSUE TITLE
jx promote  error "error: error unmarshaling JSON"

### ISSUE THREAD

**Issue by athilaelhuno** [jenkins-x/jx#2734]
### Summary 
I cannot use  `jx promote microservice01 --version 0.0.1 --env production`

### Steps to reproduce the behavior

`jx promote microservice01 --version 0.0.1 --env production`

### Jx Version
```
NAME               VERSION
jx                 1.3.750
jenkins x platform 0.0.3193
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.2
helm client        v2.12.2+g7d2b0c7
helm server        v2.12.1+g02a47c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G4015
```

### Kubernetes cluster
EKS

### What kind of Kubernetes cluster are you using & how did you create it?

```
jx install --provider=eks --domain=efermin.cf --default-environment-prefix=reactive  --default-admin-password=xxxxxxxxxxx

```

### Expected behavior

I want to promote the application manually to production environment 

### Actual behavior

```
argos:microservice01 efermin$ jx promote microservice01 --version 0.0.1 --env production
Promoting app microservice01 version 0.0.1 to namespace jx-production
pipeline efermin-jenkins/microservice01/master
error: error unmarshaling JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
```

The incredible thing is if I create an environment with auto deploy the promote works without problem

**Comment by deciian** [comment]
I don't know if it's the same issue but using `jx promote spring` for a Spring app created by `jx create spring -d web -d actuator` also leads to:
```
error: error unmarshaling JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
```
