### ISSUE TITLE
lets add a prow command to enable/disable previews

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#2736]
we want to make it easy for folks to enable by default previews or disable them by default - then use prow to decide if the `preview` label gets applied to a new PR - then use the presence of the `preview` label in a PR pipeline to create the preview.

e.g. we could define at a `Team` or `SourceRepository` level to enable PRs by default. Or like with approvers in prow, we could use the `OWNERS` file to keep a list of contributors who want to enable previews for their PRs (e.g. all PRs from user joe get a preview).

Then support `/preview` and `/preview hold` type commands so anyone in the `OWNERS` file can trigger the creation/deletion of a preview

**Comment by pmuir** [comment]
Best done as an external plugin for Prow (see for example https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker) which can then be installed as an app (TODO, ping me)

**Comment by jstrachan** [comment]
sounds perfect!

I guess we can use labels on the PR to decide if `jx preview` does or does not create a Preview (based on project defaults maybe) - then have the `/preview` or `/preview delete` commands change the labels and retrigger a pipeline. Might be fairly simple to implement really.

I wonder if its easy for a prow plugin to default the labels on the PR to enable/disable previews based on defaults + who the PR is from before the pipeline is triggered?

**Comment by pmuir** [comment]
Yes, that's the way to do it - the commands change the labels, and then also the plugin can manipulate CRDs. 

If you want to do permissions, then take a look at the ok-to-test plugin, which does something similar (adds `needs-ok-to-test` if the user is not trusted by default, and then when someone issues `/ok-to-test` it removes that label). So, for example, the plugin checks at the start if the user is trusted, if not adds `needs-ok-to-generate-preview`. Someone trusted (in the `OWNERS` file or the org - I would copy the prow logic/config here) issues `/ok-to-generate-preview` which then removes the `needs-ok-to-generate-preview` label. You also want to sync this status to a CRD (e.g. PipelineActivity?) to control whether the preview is allowed to be generated or not. Add `/preview-hold` which would generate the label `generate-preview/hold` (and again I think the best is to sync this to a CRD as well). I guess `/preview delete` would need to actually remove the preview env and not affect labels? and same with `/preview`?

**Comment by jstrachan** [comment]
yeah that all sounds great. BTW to simplify commands and labels, how about we just do `s/test/preview` so `ok-to-preview` or `needs-ok-to-preview` then they look and feel similar to `test`

**Comment by pmuir** [comment]
Yes, that's also ok (though not gramatically correct :-p)
