### ISSUE TITLE
create cluster script asking for wildcard DNS twice

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#275]
Using:
NAME        VERSION                                   
jx          1.0.80                           
Jenkins X   0.0.137                          
Kubernetes  v1.7.12-gke.1                    
Helm Client v2.8.1+g6af75a8                  
Helm Server v2.8.1+g6af75a8                  
Git         git version 2.14.3 (Apple Git-98)

Actions:
jx create cluster gke -n abc --git-username redactedbot -m n1-standard-2 --num-nodes 3 -z europe-west2-a

Survey asks to configure the wildcard DNS twice:
```
You can now configure a wildcard DNS pointing to the new loadbalancer address 100.200.101.102
? Domain redacted.com
nginx ingress controller installed and configured
Context "gke_exalted-kayak-123456_europe-west2-abc" modified.
Lets set up a git username and API token to be able to perform CI / CD

? Do you wish to use redactedbot as the GitHub username for CI/CD pipelines: Yes
You can now configure a wildcard DNS pointing to the new loadbalancer address 100.200.101.102
? Domain redacted.com

```

**Comment by rawlingsj** [comment]
Yeah I've seen this too - not dug into it yet.  It seemed to start happening recently.

**Comment by tdcox** [comment]
It didn't happen when I ran jx install, so I suspect something associated with the create cluster script?
