### ISSUE TITLE
jx upgrade ingress - cert wrongly set to ingress.local

### ISSUE THREAD

**Issue by dspeers** [jenkins-x/jx#2752]
### Summary 

After creating a new cluster on GKE and running jx upgrade ingress the SSL cert shows up with the wrong domain:  ingress.local

### Steps to reproduce the behavior
```
jx create cluster gke --prow=true --tls-acme=true --http=false
```
Then when prompted for the domain where the nip.io default also shows the load balancer IP, I update my DNS A record for my custom domain to this new ip.  Before continuing I make sure the DNS cache is updated with the right IP address for the custom domain and then enter that name to replace the nip.io default.

This jx install is configured to use Kubernetes Workloads: Automated CI+CD with GitOps Promotion.

Next:
```
jx-demo-a me$ jx upgrade ingress
looking for existing ingress rules in current namespace jx
? Existing ingress rules found in current namespace.  Confirm to delete and recreate them Yes
? Expose type Ingress
? Domain: jxdemo.<snip>.com
? If your network is publicly available would you like to enable cluster wide TLS? Yes

? Use LetsEncrypt staging or production? production
? Email address to register with LetsEncrypt: dan@<snip>.com
? Using config values {dan@<snip>.com jxdemo.<snip>.com letsencrypt-prod Ingress true}, ok? Yes

Looking for cert-manager deployment in namespace cert-manager...
? CertManager deployment not found, shall we install it now? Yes

Updating Helm repository...
Helm repository update done.
Namespace cert-manager created
 waiting for CertManager deployment to be ready, this can take a few minutes
Deleting ingress jx/hook
Deleting ingress jx/monocular
Deleting ingress jx/nexus
Deleting ingress jx/tide
Deleting ingress jx/chartmuseum
Deleting ingress jx/deck
Deleting ingress jx/docker-registry
Updating Helm repository...
Helm repository update done.
Previous webhook endpoint https://hook.jx.jxdemo.<snip>.com/hook
Updated webhook endpoint https://hook.jx.jxdemo.<snip>.com/hook
? Do you want to update all existing webhooks? Yes

Webhook URL unchanged. Use --force to force updating
```
From there opening any URL (jx get urls) in the web browser shows an invalid certificate assigned to ingress.local instead of my custom domain.   Proceeding past the warning the page does show.

I imported a project which was registered with prow so it shows up in deck.jx as pending.  After waiting a long time I copied the retry URL and it returned this:

```
Unable to connect to the server: x509: certificate is valid for ingress.local, not deck.jx.jxdemo.<snip>.com
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.750
jenkins x platform 0.0.3193
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.9.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.18.0
Operating System   Mac OS X 10.14 build 18A391
```

### Kubernetes cluster
```
jx create cluster gke --prow=true --tls-acme=true --http=false
```
### Operating system / Environment

Mac OS X 10.14 build 18A391

### Expected behavior

The SSL Cert should show the custom domain, not ingress.local

### Actual behavior

The SSL cert shows ingress.local instead of the custom domain.

**Comment by ccojocar** [comment]
dup of  #2704
