### ISSUE TITLE
Support for GitHub deployments API

### ISSUE THREAD

**Issue by c-knowles** [jenkins-x/jx#2756]
### Summary 

Currently Jenkins X posts comments to GitHub for deployments. There is a slightly more native way that looks a bit like [this screenshot](https://assertible.com/docs/guide/deployments#github) in the UI. To get that we'd have to push the appropriate info to this endpoint - https://developer.github.com/v3/repos/deployments/. Would switching to this be viable? I was looking through the code and it seems it would involve a few changes to how PRs are retrieved and what info is passed through to the git provider code.

**Comment by pmuir** [comment]
Seems like a good idea to me.
/area git-providers
/priority backlog

**Comment by ndeloof** [comment]
I was about to report this exact same RFE.
This is pretty confusing to read a comment "PR built and available in a preview environment foo-pr-4 here" and just next "This branch has not been deployed - No deployments"
