### ISSUE TITLE
`jx create cluster` fails to run the first time when in batch mode

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#2759]
### Summary 

I’m trying to create a `jx`  cluster using batch mode but it fails with `error creating cluster configuring the git auth: creating a user authentication for git server GitHub: Running in batch mode and no default Git username found`. I thought that `--environment-git-owner`, `--git-provider-kind`, `--git-username`, and `--git-provider-url` should fix it but still the same problem. Am I missing something or there is a bug. Please note that the issue occurs only when running for the first time (with empty `~/.jx` dir).

### Steps to reproduce the behavior

Delete contents of the `~/.jx` directory and execute `jx create cluster ... -b`. 

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               1.3.768
git              git version 2.17.2 (Apple Git-113)
Operating System Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

GKE created with `jx create cluster gke`. I tried the same with EKS as well and the issue persists.

### Operating system / Environment

MacOS

### Expected behavior

Respect `--environment-git-owner`, `--git-provider-kind`, `--git-username`, and `--git-provider-url` arguments when creating a cluster for the first time.

### Actual behavior

Fails

**Comment by hferentschik** [comment]
@vfarcic did you specify the `git-api-token` as well? That seems to cut it for me.

Here is what I used:

```
$ jx -b create cluster gke -p <gke-project-id>  -z europe-west1-c \
--machine-type=n1-standard-2 --min-num-nodes=3 --max-num-nodes=4 --cluster-name my-cluster --default-environment-prefix=foo \
--git-provider-url=https://github.com --git-username=<git-user-name> --git-api-token=<git-api-token> --environment-git-owner=<git-organisation> \
--ng true --no-tiller=true --skip-login=true --preemptible=false
```

Might be a documentation issue. Maybe the getting started guide should include a batch mode example!?

**Comment by vfarcic** [comment]
That's the one that was missing.
