### ISSUE TITLE
jx install stage bombs out if previous GitOps repo found

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#276]
Using:
NAME        VERSION                                   
jx          1.0.80                           
Jenkins X   0.0.137                          
Kubernetes  v1.7.12-gke.1                    
Helm Client v2.8.1+g6af75a8                  
Helm Server v2.8.1+g6af75a8                  
Git         git version 2.14.3 (Apple Git-98)

Actions:
jx create cluster gke -n abc --git-username redactedbot -m n1-standard-2 --num-nodes 3 -z europe-west2-a

```
About to create repository environment-staging on server github.com with user redactedbot

Creating repository redacted/environment-staging
error creating cluster Failed to create repository redacted/environment-staging due to: POST https://api.github.com/orgs/redacted/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}]
error: Failed to create repository redacted/environment-staging due to: POST https://api.github.com/orgs/redacted/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}]

```

**Comment by rawlingsj** [comment]
yeah not sure what's best to do here, here's a few options:

- maybe we add the cluster name into the git repo name so we don't duplicate default envs across clusters?  so a repo name would be _environment-staging-mytestcluster_
- we could ask to import an existing repo if found
- we could ask to delete the existing repo if found
- a combination of the above?

**Comment by tdcox** [comment]
I can see at least two scenarios:

1. Recreating a failed cluster - where we would like to reproduce the state of the original cluster

2. A team of developers all with minikube instances that they have pointed at the same GitHub organisation - where name clashes are likely to cause unanticipated randomness.
