### ISSUE TITLE
Remove the kube provider form team settings

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#2768]
### Summary 

The team provider is not available in the cluster install configuration, we should remove it from team settings.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by garethjevans** [comment]
@ccojocar are you referring to https://github.com/jenkins-x/jx/blob/9ac619687f8e60b249d823ae0b483a7e6b8473da/pkg/apis/jenkins.io/v1/types_environment.go#L153?

**Comment by ccojocar** [comment]
Yes, and use this value introduced by this PR https://github.com/jenkins-x/jx/pull/2767/files/a741e76c57e6ff85fdd0fc193e6acd5aacfd735c#diff-38abbe8b0ca806e9c7ff799bd76e0fc9

**Comment by garethjevans** [comment]
Ah, ok, makes sense.  Are we planning on migrating existing values across so we don't break any existing clusters?
