### ISSUE TITLE
Use the generic create bucket method to provision a bucket for Vault

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#2769]
### Summary 

Use the generic create bucket method when provisioning a vault. This will allow in future to create buckets also for other cloud providers such as AWS/AKS.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

**Comment by helayoty** [comment]
Hi, How can I help here to expedite this feature for AKS?
