### ISSUE TITLE
create git server fail

### ISSUE THREAD

**Issue by jinjie2088** [jenkins-x/jx#2782]
### Summary 
[root@host-10-0-251-228 ~]# jx create git server -k github -u http://10.0.250.70:8088 -n localgit
Added Git server localgit for URL http://10.0.250.70:8088
error: Failed to create GitService with name : GitService.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required

what mean?

### Jx version
[root@host-10-0-251-228 ~]# jx version
NAME               VERSION
jx                 1.3.781
jenkins x platform 0.0.3271
Kubernetes cluster v1.9.0
kubectl            v1.9.0
helm client        v2.12.2+g7d2b0c7
helm server        v2.12.2+g7d2b0c7
git                git version 1.8.3.1
Operating System   "CentOS Linux release 7.2.1511 (Core) "

**Comment by jinjie2088** [comment]
i find reason, please close.

**Comment by LinuxSuRen** [comment]
It would be better if you can post your solution in here. Thanks.
