### ISSUE TITLE
jx install fails with 500 server error

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#279]
Using:
NAME VERSION
jx 1.0.80
Jenkins X 0.0.137
Kubernetes v1.7.12-gke.1
Helm Client v2.8.1+g6af75a8
Helm Server v2.8.1+g6af75a8
Git git version 2.14.3 (Apple Git-98)

Actions:
jx create cluster gke -n abc --git-username redactedbot -m n1-standard-2 --num-nodes 3 -z europe-west2-a --domain redacted.com --skip-login

Script fails whilst creating jenkins credentials:

```
Created environment staging
? Do you wish to use redactedbot as the user name for the Jenkins Pipeline Yes
error creating cluster error creating jenkins credential jenkins-x-git at http://jenkins.jx.redacted.com 500 Server Error
error: error creating jenkins credential jenkins-x-git at http://jenkins.jx.redacted.com 500 Server Error

```

**Comment by jstrachan** [comment]
I guess wildcard DNS wasn't setup so that http://jenkins.jx.redacted.com didn't return anything - or is there something wrong with the Jenkins at http://jenkins.jx.redacted.com

**Comment by michaelneale** [comment]
I was able to run that version but without a domain flag, so that seems likely

**Comment by tdcox** [comment]
> Using:
> NAME        VERSION
> jx          1.0.84
> Jenkins X   0.0.137
> Kubernetes  v1.7.12-gke.1
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)
I am still seeing the same error when trying to install to GKE. I am able to successfully access the jenkins dashboard at that address, so it's not a DNS problem.

**Comment by michaelneale** [comment]
@tdcox if you run "jx create cluster gke" and make it fresh (use defaults mostly) - does it work for you?

**Comment by tdcox** [comment]
@michaelneale Nope. I'm installing with default settings. Checking the source to see if I can get any clues.

**Comment by tdcox** [comment]
Hmmm, if I access the Jenkins API path that the failing call is going to, it redirects me to log in, but then throws a 400 error if there are no credentials passed. Thinking about it, it can't have been a DNS problem as it is connecting to something which returned the 500 error.

**Comment by tdcox** [comment]
Ok, by deleting the contents of the .jx directory on the client, I am able to install. Looks like it was a cached token problem.
