### ISSUE TITLE
add a BDD test that asserts all the pods in the dev namespace and valid and have not failed

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#2806]
I just ran the BDD tests and saw some CronJob pods that failed. Its very easy for us to make an RBAC error in the CronJobs causing a failure that goes undetected in our BDD tests

So lets add a BDD test to the https://github.com/jenkins-x/bdd-jx after we have run a set of BDD tests - to then test there's no failed pods in the dev namespace.

Ideally we'd figure out a way to trigger all the CronJobs to ensure each pod has ran for 20 seconds to ensure we detect all possible cron failures. e.g. I wonder if we can in BDD tests use CronJob timers of 1 minute; as by the time we've run the BDD tests we'll have a cluster/team running for 5 mins minimum so should have a few pods completed by then?

**Comment by jstrachan** [comment]
a few implementation notes; you should be able to list all the Pods via `kubeClient.CoreV1().Pods(ns).List()` and then look at the `pod.Status` and check or error pods.

If a pod has an issue you could save the Pod as YAML using the `github.com/ghodss/yaml ` library to do `data, err := yaml.Marshal(&pod)` and then dump the pod to stdout.

You may need to noodle the k8s docs to find how to test if a pod failed or terminated gracefully....
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#podstatus-v1-core

looking at the container statuses: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#containerstatus-v1-core

e.g. here's a failed `gcactivities` pod in a prow cluster - see the failure at `containerStatuses[0].state.terminated.exitCode > 0 + reason string`
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-01-23T09:31:57Z
  generateName: jenkins-x-gcactivities-1548235800-
  labels:
    app: gcactivities
    controller-uid: 774003ec-1ef1-11e9-be61-42010a840118
    job-name: jenkins-x-gcactivities-1548235800
    release: jenkins-x
  name: jenkins-x-gcactivities-1548235800-svlwn
  namespace: jx
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: jenkins-x-gcactivities-1548235800
    uid: 774003ec-1ef1-11e9-be61-42010a840118
  resourceVersion: "451655"
  selfLink: /api/v1/namespaces/jx/pods/jenkins-x-gcactivities-1548235800-svlwn
  uid: ba5ddb46-1ef1-11e9-be61-42010a840118
spec:
  containers:
  - args:
    - gc
    - activities
    - --batch-mode
    command:
    - jx
    env:
    - name: cheese
      value: wine
    - name: foo
      value: bar
    image: jenkinsxio/jx:1.3.769
    imagePullPolicy: IfNotPresent
    name: gcactivities
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jenkins-x-gcactivities-token-kncg4
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-jstrachan-prow11-default-pool-0a4ea95a-hkdr
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: jenkins-x-gcactivities
  serviceAccountName: jenkins-x-gcactivities
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jenkins-x-gcactivities-token-kncg4
    secret:
      defaultMode: 420
      secretName: jenkins-x-gcactivities-token-kncg4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-01-23T09:31:57Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-01-23T09:31:57Z
    message: 'containers with unready status: [gcactivities]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-01-23T09:31:57Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b78c5448deff4c0d77e544d2f1f55c3bf1ba525b88e9e81f5699f9051ffd4f17
    image: jenkinsxio/jx:1.3.769
    imageID: docker-pullable://jenkinsxio/jx@sha256:acd2afc0f27de170922e9f97b47e09c3e67e64c849b032f9a6e621266d96e409
    lastState: {}
    name: gcactivities
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://b78c5448deff4c0d77e544d2f1f55c3bf1ba525b88e9e81f5699f9051ffd4f17
        exitCode: 1
        finishedAt: 2019-01-23T09:31:59Z
        reason: Error
        startedAt: 2019-01-23T09:31:59Z
  hostIP: 10.132.0.35
  phase: Failed
  podIP: 10.56.0.147
  qosClass: BestEffort
  startTime: 2019-01-23T09:31:57Z
```

**Comment by jstrachan** [comment]
if its available it might be nice if you find a failed pod, to try grab its log and output it to the test log  - thats often got the reason for the failure:
```
$ kubectl logs jenkins-x-gcactivities-1548235800-svlwn
error: strconv.Atoi: parsing "0.0.1": invalid syntax
```

**Comment by jstrachan** [comment]
thinking a little bit more about this - we could make the 'verify pods have not failed' be a generic `jx step` something like `jx step verify pod` or something which could optionally take label selectors to filter pods (or exclude pods) for being checked - then the command can fail if there's failed pods - outputting the above information (the pod yaml + pod log).

Then folks could just run `jx step verify pod` from time to time and get output of what failed. Maybe CLI options to enable/disable levels of logging (e.g. disable the YAML output - folks may just want to see the logs)?

**Comment by warrenbailey** [comment]
I started to implement the `jx step verify pod` command and have discovered that `--pods` is already an option to the `jx step verify` command. That checks the number of pods running during a pipeline build.

It feels a bit confusing to me to have these two commands do different things but be named so similarly.

At the minute I have implemented it as a `jx step status` command but that doesn't feel right either as its too similar to `jx status`. So I think a sub-command to verify is probably the way to go, just not sure what that sub command should be named.

**Comment by warrenbailey** [comment]
There's a branch on my jx fork with my initial workings https://github.com/warrenbailey/jx/tree/issue-2806

**Comment by warrenbailey** [comment]
Added a BDD test https://github.com/jenkins-x/bdd-jx/pull/8

**Comment by jstrachan** [comment]
I wonder if we rename the current `jx step verify` to be something like `jx step verify pod count` as thats really what it does - then your new command could be maybe `jx step verify pod ready` or something which verifies the pods are all ready/good?

**Comment by warrenbailey** [comment]
Yep, that sounds like a good idea. I can do that

**Comment by warrenbailey** [comment]
Rename here: https://github.com/jenkins-x/jx/pull/3069

**Comment by warrenbailey** [comment]
Fixed by https://github.com/jenkins-x/bdd-jx/pull/8
