### ISSUE TITLE
Prow Batch jobs behave as releases

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#2810]
### Summary 
When a batch job runs, it sets the `BRANCH` to `master`. The `Jenkinsfile` we use then assumes that this is a release job.
### Steps to reproduce the behavior
Get prow to do a batch job, and look at the build job

Suggested fix is to set an env var for postsubmit jobs (e.g. POSTSUBMIT=1) and then do a selector in the `Jenkinsfile` based on that

**Comment by pmuir** [comment]
Particularly a problem if the batch fails (e.g. infra instability) part way through the release (e.g. after tag, before helm charts), as then the tag can effectively go backwards (the next release won't be the batch, it will be one from the batch)

**Comment by rawlingsj** [comment]
There's an env var
```
        - name: JOB_TYPE
          value: postsubmit
```
would that help?

**Comment by pmuir** [comment]
yeah - we just then need to make the `Jenkinsfile` use that rather than branch to select the stage.

**Comment by warrenbailey** [comment]
@pmuir can this be closed?
