### ISSUE TITLE
Let's Encrypt Rate Limit hit on first try

### ISSUE THREAD

**Issue by dspeers** [jenkins-x/jx#2815]
### Summary 

After creating a new cluster on GKE with a custom domain and then doing a 'jx upgrade ingress' none of the certificates get created.  Every new order results in a rate limit issue.

### Steps to reproduce the behavior
```
jx create cluster gke --prow=true --tls-acme=true --http=false
```
Use a custom domain - in this specific case I used a domain that I had never used with GKE or jx before.  So the domain name should not be the cause of the rate limit.
```
jx upgrade ingress
```
Updated production to use TLS with my custom domain.   Waited 15m or so once it was done and then checked the status of each of the certificates.
```
$ kubectl get cert
NAME                  AGE
tls-chartmuseum       1h
tls-deck              1h
tls-docker-registry   1h
tls-hook              1h
tls-monocular         1h
tls-nexus             1h
tls-tide              1h
```
Then for each cert:
```
kubectl describe cert tls-deck
```
Scroll to the end of the output and I see this:
```
Events:
  Type     Reason          Age                From          Message
  ----     ------          ----               ----          -------
  Normal   CreateOrder     41m (x5 over 50m)  cert-manager  Created new ACME order, attempting validation...
  Warning  ErrCreateOrder  4m (x36 over 39m)  cert-manager  Error creating order: acme: urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
```
### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.790
jenkins x platform 0.0.3286
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.9.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.18.0
Operating System   Mac OS X 10.14 build 18A391
```

### Jenkins type

- [ ] Classic Jenkins
- [X] Serverless Jenkins

**Comment by jstrachan** [comment]
I'm not sure what we can do if you hit rate limiting on letsencrypt - there's nothing really that can be done other than wait and try again later? 

I'm gonna close this for now unless anyone has any great ideas for what we could do if the user hits rate limiting on letsencrypt

**Comment by amuniz** [comment]
Related to https://github.com/jenkins-x/jx/issues/2270

**Comment by dspeers** [comment]
Seems like a deeper issue than a simple rate limit.  Being a new TLD and a new GKE cluster there apparently is no reason it should have hit a rate limit.   I suspect this may be happening due to the cert-manager picking up the wrong DNS name (ingress.local)  and using that to create the lets encrypt order.   The first time I tried this with a different custom domain the certs were created but with the wrong domain (ingress.local).

See:  https://github.com/jetstack/cert-manager/issues/1216
