### ISSUE TITLE
Opening a pull request triggers an auto deploy and version bump for environments incorrectly

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#282]
So I created the default app (spring boot) and then did a PR to my source repo. 

The PR build ran fine, and told github. 

However according to `jx get apps` it is now running the 0.0.2 version, despite it still being in PR: 

```
 ~/Downloads/demo  (master) ➔  jx get apps
APPLICATION STAGING PODS PRODUCTION PODS
demo        0.0.1   1/1  0.0.1      1/1
```
*makes edit to source, opens a PR*
```
 ~/Downloads/demo  (master) ➔  jx get apps
APPLICATION STAGING PODS PRODUCTION PODS
demo        0.0.2   1/1  0.0.2      1/1
```

This is clearly not quite right 

the repo is: https://github.com/michaelneale/demo

https://github.com/michaelneale/demo/commits/v0.0.2 is the commit history of the new 0.0.2 version. Has no real changes other than version. 

The PR is https://github.com/michaelneale/demo/pull/1
which has a java file changed. 

So it isn't actually deploying the PR (good) but it is triggering a version bump and auto deploy (bad).

**Comment by jstrachan** [comment]
yeah - we've removed temporarily the PR logic for now until Milestone 2 - but sounds like we should put it back in ASAP :) @rawlingsj

**Comment by rawlingsj** [comment]
Yeah it's not been removed, just was never added to the default pipeline :) will add it now though.

**Comment by michaelneale** [comment]
ping @rawlingsj still happening in 

```
jx          1.0.96
Jenkins X   0.0.186
```

**Comment by rawlingsj** [comment]
Yeah just waiting to submit a PR on draft so we get preview envs OOTB. If I don’t get to it today I’ll at least add the CI pipeline so we get a maven build and test until we add the preview env too.
