### ISSUE TITLE
add the "all" category to CRDs

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2827]
### Summary 

It would be great if all the JX CRDs where added to the "all" category so that `kubectl get all` returned also the Jenkins-X resources.

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#categories

### Steps to reproduce the behavior

`kubectl get all`

### Expected behavior

Jenkins-X resources are also returned

### Actual behavior

Jenkins-X resources are not returned

### Jx version

The output of `jx version` is:

```
N/A
```

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

**Comment by jglick** [comment]
I assume the `all` category exists for a reason. Perhaps it would be better to create a new category like `jx` so you could write

    kubectl get jx

if you were interested in all the JX-specific CRs (including potentially ones added by various apps)?

**Comment by girishramnani** [comment]
assuming if we just add a `jx` in the yaml instead of `all` it would be done, no extra step to create a new category?

**Comment by jtnord** [comment]
the all category is there to say `"everything"` as far as I am aware.  
Nothing stopping us from having multiple categories so can `kubectl get jx` and `kubectl get all`

the referenced example even shows you how to do it with `all` for a CRD belonging to `example.com`

**Comment by girishramnani** [comment]
opened a PR for this https://github.com/jenkins-x/jx/pull/2930
