### ISSUE TITLE
Minishift - docker repo problem

### ISSUE THREAD

**Issue by turulb** [jenkins-x/jx#2828]
### Summary 
Build is failing as cannot push docker image to repository.
I've read #1243 and the related documentation (https://jenkins-x.io/architecture/docker-registry/) but couldn't fix the docker repo problem. Tried with https://hub.docker.com/ as well as with my gitlab repo, without success.
Used this command template:
jx create docker auth --host "foo.private.docker.registry" --user "foo" --secret "FooDockerHubToken" --email "fakeemail@gmail.com"

From the log it seems it tries to upload to the correct repo 
"The push refers to a repository [registry.gitlab.com/myacc/demo]"

But after that when it tries to upload
"time="2019-01-23T13:35:06Z" level=fatal msg="build failed: building [changeme]: tagging: pushing: denied: access forbidden"

### Steps to reproduce the behavior
See description
### Expected behavior
Build upload docker to external repo.

### Actual behavior
"time="2019-01-23T13:35:06Z" level=fatal msg="build failed: building [changeme]: tagging: pushing: denied: access forbidden"

### Jx version
The output of `jx version` is:
NAME               VERSION
jx                 1.3.792
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.13.0
git                git version 2.19.1.windows.1
Operating System   Windows 10 Pro 1803 build 17134
```
COPY OUTPUT HERE
```

### Jenkins type
- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
minishift

### Operating system / Environment
Win10/cygwin

**Comment by ccojocar** [comment]
@turulb  Are you able to push images, If you set the docker auth manually in a Pod?

**Comment by ccojocar** [comment]
I would check how the `~/.docker/config.json` looks like in the build pods, and compare it with the `~/.docker/config.json` generated by `docker login` command. Maybe there is some inconsistency in the file created by `jx`.

**Comment by turulb** [comment]
Trying to do that. Which pod is that (or how can i do that)?

**Comment by ccojocar** [comment]
@turulb Are you still facing this issue? Can we close it?
