### ISSUE TITLE
[Feature request] Harbor as registry/chartmuseum/monocular replacement

### ISSUE THREAD

**Issue by sn00p** [jenkins-x/jx#2829]
It could be great to have https://goharbor.io/ installation as a replacement for registry+chartmuseum+monocular stack or as addon or whatever.
1. Harbor is maintaining actively,
2. It has nice webUI and ACLs for users/groups/projects,
3. It is able to store charts too,
4. It has internal clair implementation to scan images for vulnerability,
5. It also has notary to properly sign images,
6. It is able to use federations and registry synchronizations out of the box. 
7. It has API 
8. Could use different storages like S3 or ceph buckets.

Internal docker registry has almost zero functionality and feels like black box.
Monocular is clunky and slow and has issues in installations with self-signed certs. Could breaks suddenly with an endless loading screen. 

I've tested it and it works good for me. Sadly it requires a lot of manual reconfiguring to connect it now. 
Also harbor itself goes to kubernetes easily as a Helm chart.

**Comment by ccojocar** [comment]
This is a dup of #2489
