### ISSUE TITLE
generate Preview (and maybe developer Snapshot) images + charts somewhere else? 

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#283]
I love preview snapshots; but worry that they may accidentally leak into real environments. 

e.g. right now all the docker images for previews and real ones end up in the same place which is confusing for end users:
https://hub.docker.com/r/jenkinsxio/builder-maven/tags/

It would be nice if by default Preview images+charts could only be used in Preview Environments. (Maybe one day we have the idea of a Editing image/chart and Editing Environment for incremental changes before developers commit).

From a helm chart perspective; charts with increasing semantic versions get installed ahead of older versions; so the worry for Preview charts is they get promoted to Production by helm!

So I wonder if we should move  preview/snapshot images/charts into a 'different place' like maven does for artefacts?

e.g. use a different helm chart name for Preview / Snapshots? So that folks installing 'demo' would only see prod versions, installing 'demo-preview' would see all the preview versions? 

So I'm wondering if for preview / snapshot builds we change the name of the image/chart to avoid confusion/leaks? 

Longer term we could get clever and use separate chart repos / docker registries for preview/snapshots?

**Comment by rawlingsj** [comment]
yeah I was thinking about this, personally I wasn't too worried about preview versions being in dockerhub but it was monocular I didn't like.

I wondered if we have a second chartmusem repo where we push preview charts and monocular doesn't have that one registered?

**Comment by rawlingsj** [comment]
just chatting about it and we can `helm install .` in preview environments which solves the chart issue but not the snapshot docker images.

**Comment by jstrachan** [comment]
if we do a local `helm install .` then that avoids the worry on preview charts getting into a repo. There's no way folks can re-deploy that chart into other environments other than from the local helm tarball right?

**Comment by rawlingsj** [comment]
yeah
