### ISSUE TITLE
Write a quickstart for a CLI plugin that uses cobra

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#2832]
### Summary 
`jx` CLI plugins are best written using cobra and importing `jx` as a library in order to do some stuff. We should have a quickstart for this.

This will also require creating a buildpack for CLI plugins

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by wazery** [comment]
Can this repo serve as a quick start? https://github.com/wazery/cobra-quickstart Please let me know if it needs any edits/improvements.

**Comment by ivostoyanov-bc** [comment]
I'd like to work on this.

**Comment by 524119574** [comment]
Is there anyone working on this right now?
