### ISSUE TITLE
jx create cluster minikube none

### ISSUE THREAD

**Issue by scones** [jenkins-x/jx#2839]
### Summary 

When i operate on a linux system i can actually use the `none` option for virtualization.
This specific option will install binaries into the host system /usr/bin directory (at least on ubuntu) upon minikube start
This directory is write protected for normal users.
Thus the process errors out

### Steps to reproduce the behavior

- blank ubuntu with curl and jx (and all the other bare system requirements for jx)
- `jx create cluster minikube --local-cloud-environment=true`
- choose the defaults
- choose none driver

### Expected behavior

it should create the minikube cluster

### Actual behavior

it errors out

### Jx version

The output of `jx version` is:

```
jx               1.3.797
git              git version 2.19.1
Operating System Ubuntu 18.10
```

### Jenkins type

- [ x ] Classic Jenkins
- [ ] Serverless Jenkins

### Operating system / Environment

see above

### solution proposal

start minikube for `none` with sudo
yielding:
`sudo minikube start --memory 4096 --cpus 3 --disk-size 150GB --vm-driver none --bootstrapper=kubeadm`

as this produces a new problem, you'd need these steps:

```
export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true

minikube config set WantReportErrorPrompt false

sudo minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf --apiserver-name localhost --kubernetes-version=${current_stable} --bootstrapper=kubeadm

sudo chown -R $USER $HOME/.kube
sudo chgrp -R $USER $HOME/.kube

sudo chown -R $USER $HOME/.minikube
sudo chgrp -R $USER $HOME/.minikube
```

this should provide a clean startup sequence for minikube with `none`.

**Comment by RomanHiden** [comment]
Affects me as well

**Comment by scones** [comment]
just remove the none option, if you are not willing to support it.
