### ISSUE TITLE
create Preview Environments for editing code?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#284]
I'd like to be able to create a Preview Environment from my local file system (e.g. a local git clone / fork / branch that I'm editing code inside with my IDE).

e.g. 

```
/> cd my-project
/my-project> jx edit
Editing my-project.....
Created environment edit-jstrachan-my-project
Application is running at http://jstrachan-my-project.myteam.acme.com/
Waiting for code changes....
....
Updated app...
```

Then under the covers: 

* there's a `remote edit branch` created for my edits on the remote repo, named something like `edit-username-branchname`
* a new JX Environment of kind `Edit` is created for my user, repo, `remote edit branch`
* the MultiBranchProject runs a Pipeline on each push to the `remote edit branch`
* `jx edit` then watches the file system; any changes to the local files are pushed into the `remote edit branch` to trigger a rebuild/run
* any git commit/push from my local branch should regenerate the `remote edit branch` from the real remote branch (i.e. the `remote edit branch` only contains pending source changes not yet pushed during development

Then if we do `jx delete env edit-jstrachan-my-project` it removes the Environment, the underlying namespace/charts and the `remote edit branch`.

### Bonus points

It currently takes a while from a webhook to the kubernetes plugin actually spinning up a build pod to run a build. It would be pretty slick to have the Pipelines for `edit environments` sit in a loop waiting for changes; so that the local maven repo is all downloaded, warmed and ready, everything's built locally and the build pod basically sits in an infinite fast loop trying to rebuild/redeploy ASAP to get maximum fast feedback.

So rather than a full 'clean maven build' thing; its more of an incremental build running all the time, watching the underlying file system (thats polled/updated on webhooks)

**Comment by jstrachan** [comment]
we've made a start of this work here: http://jenkins-x.io/developing/devpods/ - though we'd ideally use Preview Environments (separate namespaces per user) to avoid team members clashing together etc

**Comment by jstrachan** [comment]
implemented today via DevPods and using `skaffold dev -p dev` inside a DevPod http://jenkins-x.io/developing/devpods/

**Comment by aweis89** [comment]
@jstrachan this has been something my organization has been interested in and sorry if I'm missing something but do you mind elaborating on how `skaffold dev -p dev` fulfills this feature request. More specifically my understanding is that devpods use a single jenkins build images and not helm charts or the deploy image specific by the Dockerfile.

Do you think it still makes sense to have a feature request for code syncing to an environment built using the `charts/preview` helm chart (and perhaps the target pod can be selected via an annotation)?
