### ISSUE TITLE
jx get pipelines returns nothing in a serverless cluster

### ISSUE THREAD

**Issue by escoem** [jenkins-x/jx#2845]
### Summary 

In a serverless installation, run `jx get pipelines`

```
Name                                                          URL LAST_BUILD STATUS DURATION
itsme/sample-project/master                             N/A N/A        N/A    N/A
itsme/jx-test/master                                N/A N/A        N/A    N/A
itsme/environment-itsme-dev-production/master N/A N/A        N/A    N/A
itsme/environment-itsme-dev-staging/master    N/A N/A        N/A    N/A
```

What is exposed is completely useless regarding the status...

### Steps to reproduce the behavior

Run `jx get pipelines`

### Expected behavior

The same (almost at least) than in a classic Jenkins 

### Actual behavior

N/A is returned for all values

### Jx version

1.3.798

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

MacOS / Linux

**Comment by garethjevans** [comment]
Looks like we need to implement a prow version of this command, or change both versions to read the data from the pipeline activities?

**Comment by rawlingsj** [comment]
yeah - getting them from the pipeline activities would be nice

**Comment by jennbriden** [comment]
I'd like to bump up the priority of this ticket.
