### ISSUE TITLE
Where to add custom credentials for other services?

### ISSUE THREAD

**Issue by ximbal** [jenkins-x/jx#2846]
### Summary 

I know that all the JX platform is immutable and driven by configurations, I am wondering where can I add custom credentials for services, I mean I can add them manually on Jenkins (Global Credentials) but in which configmap (K8s) should I add them in order for them to persist POD updates/lifecycles?

### Steps to reproduce the behavior

Add credentials to a configuration file instead of manually

### Expected behavior

Add credentials to a configuration file instead of manually

### Actual behavior

Unsure if possible

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ X] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GCP Hosted Cluster

### Operating system / Environment

MAC OS X

**Comment by ccojocar** [comment]
@ximbal Which other services are you referring to?

**Comment by ccojocar** [comment]
@ximbal You can create new Kubernetes secrets in which you can store your credentials. This is an example https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/blob/master/docs/examples/username-pass.yaml.

You can then reference the secret from your Jenkinsfile by secret name e.g. like this https://github.com/jenkins-x/jx/blob/8007f3351bc7701a0a76d6888ccb90697bef9368/Jenkinsfile#L5  

Do you need more help? Could we close this issue?

**Comment by iharrington** [comment]
I have a similar question, is it possibly to create a Global credential on install (inside myvalues.yaml)? Not for pipelines per-se but to be used with plugins.

**Comment by ccojocar** [comment]
@ximbal I am going to close this issue. Fell free to open another issue if you still have questions. Thanks
