### ISSUE TITLE
minishift install fails at Jenkins API token configuration

### ISSUE THREAD

**Issue by duffn** [jenkins-x/jx#2847]
### Summary 

Attempted creation of a cluster in minishift fails during the `Configure Jenkins API Token` stage.

### Steps to reproduce the behavior

```
$ minishift delete
$ jx create cluster minishift
? memory (MB) 4096
? cpu (cores) 3
? Select driver: virtualbox
```

### Expected behavior

The cluster is created successfully. 

### Actual behavior

The cluster creation fails during the `Configure Jenkins API Token` stage. Steps up to this point complete successfully.

```
Configure Jenkins API Token
error creating cluster configuring Jenkins: Command failed 'oc serviceaccounts get-token jenkins -n jx': The connection to the server 192.168.99.114:8443 was refused - did you specify the right host or port? exit status 1
```

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.799
jenkins x platform 0.0.3286
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.13.1
helm client        v2.12.2+g7d2b0c7
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D42
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

`jx create cluster minishift`

### Operating system / Environment

`Mac OS X 10.14.3 build 18D42`

**Comment by ccojocar** [comment]
@duffn I think the `oc` client cannot connect to the client. Could you please check if is configured properly?

**Comment by duffn** [comment]
What configuration should I be checking?
