### ISSUE TITLE
Installation of latest cert-manager helm chart version v0.6.0 in broken

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#2851]
### Summary 

A new version (v0.6.0)  of `cert-manager` chart was recently released which does not seem to get successfully installed by `jx upgrade ingress` command.

https://github.com/helm/charts/tree/master/stable/cert-manager

### Steps to reproduce the behavior
jx upgrade ingress -b --skip-resources-update --namespaces=jx --services=jenkins

### Expected behavior

Should install the cert if is missing 

### Actual behavior

Looking for cert-manager deployment in namespace cert-manager...
Updating Helm repository...
Helm repository update done.
Namespace cert-manager created
 error: ensure cert-manager setup: CertManager deployment failed: failed to run 'helm upgrade --namespace cert-manager --install --force --timeout 6000 --set
rbac.create=true --set ingressShim.extraArgs='{--default-issuer-name=letsencrypt-staging,--default-issuer-kind=Issuer}' cert-manager stable/cert-manager' com$
and in directory '', output: 'Release "cert-manager" does not exist. Installing it now.
Error: validation failed: [unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1", unable to recognize "": no matc
hes for kind "Certificate" in version "certmanager.k8s.io/v1alpha1", unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alp
ha1", unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"]'

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
It seem that the CRDs are not anymore part of the chart, they need to be installed separately, form README:

```
## IMPORTANT: you MUST install the cert-manager CRDs **before** installing the
## cert-manager Helm chart
$ kubectl apply \
    -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml

$ helm install --name my-release stable/cert-manager
```

**Comment by rawlingsj** [comment]
Ouch - are you happy assigning this to yourself @ccojocar?  Shout if you're overloaded.

BTW I've actually wondered in the past if we should do a similar thing with CRDs as they're a pain to update in a helm chart.

**Comment by ccojocar** [comment]
I am planning to register the CRDs programatically, and also use the cert-manager client to create the issuers. They also introduced a validating webhook which checks the CRD when are being created/updated in the api-server. This seems to be enabled by default but it keeps crashing. I am going to disable it for now.

**Comment by amuniz** [comment]
Should not we use a fixed version of cert-manager instead of the latest one? That seems quite risky.
