### ISSUE TITLE
Git repository is not created in GitLab

### ISSUE THREAD

**Issue by turulb** [jenkins-x/jx#2855]
### Summary 
Installation fails at the end creating the environment in the git repo. The currently used GitLab api is outdated. JX uses v3 which is not supported in my git repo (it seems the supported version is v4)

### Steps to reproduce the behavior
Install with  minikube with private git repository gitlab.mycompany.com (tried with a www.gitlab.com where the repository created but the webhooks are not registered, but that is probably another issue.)

When the repo created I get this error msg:
Sorry, your reply was invalid: GET https://gitlab.mycompany.ch/api/v3/repos/d.turul/environment-jx-staging: 410  []

The response from the gitlab server:
{"error":"API V3 is no longer supported. Use API V4 instead."}

### Expected behavior
The git creates the project
### Actual behavior
Described above
### Jx version
1.3.802

The output of `jx version` is:
NAME               VERSION
jx                 1.3.802
jenkins x platform 0.0.3286
Kubernetes cluster v1.13.2
kubectl            v1.13.2
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.17.1
Operating System   Ubuntu 18.04.1 LTS

```
COPY OUTPUT HERE
```

### Jenkins type
- [x ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

Minikube

### Operating system / Environment
Ubuntu 18.04.1

**Comment by mulanshandi** [comment]
Try to run `jx get git server`.  The gitkind of gitlab.mycompany.com must be gitlab.

**Comment by npolagani** [comment]
I am facing similar issue, is this resolved by any chance ?

**Comment by bitsofinfo** [comment]
option for either v3 or v4 should be supported

**Comment by orinbou** [comment]
I am very annoyed with the same error too.

* gitlab resp
```
{"error":"API V3 is no longer supported. Use API V4 instead."}
```

Please tell me how to solve this problem.

* My env info
```
jx version
NAME               VERSION
jx                 2.0.1243
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.14.7-eks-1861c5
helm client        2.12.2
git                2.25.1
```
Please....

**Comment by deanesmith** [comment]
This is fixed in a recent release of Jenkins X.
