### ISSUE TITLE
non uniqueness in kube.ToValidName

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2864]
### Summary 

various places need to encode some unique string as the id for a k8s resource.  to do this they call [`kube.ToValidName()`](https://github.com/jenkins-x/jx/blob/43f6dae88b40a139572758149d92df6d366796ab/pkg/kube/names.go#L8-L53)  which encodes with dataloss and hence will allow collisions.

~It looks like the the SourceRepo uses `org/reponame` as the name for the CRD.~

~However when encoded this becomes `org-reponame`.~

~the issue is that organisations can contain the dash character thus if you have an organisation `jenkins-x` and a repo `wibble`  this will collide if you also use an organisation `jenkins` that contains a repo called `x-wibble`~

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by jtnord** [comment]
Note I think this uses the everything in jx calls [`kube.ToValidName()`](https://github.com/jenkins-x/jx/blob/43f6dae88b40a139572758149d92df6d366796ab/pkg/kube/names.go#L8-L53)  which encodes with dataloss and will allow collisions.

This is likely going to be problematic for different types (before it is for a SourceRepo)

**Comment by jstrachan** [comment]
its not an issue with the `ToValidName()` function per se - more an issue with the code which calls it. e.g. to create a name for a SR or PA the code could query for an existing object using labels / name and if there is a different object (say for a different repo) it could generate a new name

**Comment by dwnusbaum** [comment]
Is this function is intended to be used to turn things into [RFC 1035/1123](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#identifiers-and-names-in-kubernetes) compliant DNS labels, should it make sure the result is no more than 63 characters?

**Comment by jtnord** [comment]
using labels means you need to have `list` access which you may not have.  (ie it is overly broad)

**Comment by jstrachan** [comment]
@jtnord I don't see why `list` on something like a `SourceRepository` would not be allowed. If RBAC is so locked down we maybe need 2 functions; one that tries adding numeric suffixes and doing lots of `Get` calls due to fear of using `List` - the other that can rely on `List` to avoid lots of `Get` calls.

**Comment by jtnord** [comment]
this is not just in use by `SourceRepository`  I am thinking bigger picture - and trying to use the same thing everywhere.

**Comment by ccojocar** [comment]
@jtnord @dwnusbaum Can we close this issue?

**Comment by jtnord** [comment]
still an issue.

**Comment by jtnord** [comment]
Additionally the function strips leading digits which is [incorrect](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md). 

https://www.ietf.org/rfc/rfc1123.txt sec 2.1

      2.1  Host Names and Numbers

      The syntax of a legal Internet host name was specified in RFC-952
      [DNS:4].  One aspect of host name syntax is hereby changed: the
      restriction on the first character is relaxed to allow either a
      letter or a digit.  Host software MUST support this more liberal
      syntax.

Tagged as urgent also due to the the longer this stays here, the harder any data migration will be - as the names of things that have been mapped will no longer match - and there is an open question on exactly how that should occur.

**Comment by rheinwein** [comment]
James reached out to me to flag this issue again -- it still occurs per the comments above, and it has potential security implications which jtnord can elaborate on. Maybe @jtnord, @ccojocar, and @warrenbailey or @cagiti could sync on this and figure out what the next steps should be?

**Comment by rawlingsj** [comment]
> James reached out to me to flag this issue again -- it still occurs per the comments above, and it has potential security implications which jtnord can elaborate on. 

I wonder if this is still an issue on our new prod cluster?  We plan on retiring the old prod cluster in the next few days or week and currently don't plan to migrate data between them.

**Comment by warrenbailey** [comment]
@rheinwein Happy to have a look at it

**Comment by ccojocar** [comment]
@jtnord Just to make it clear, the intend of `ToValidName` is not to generate unique names but to convert a given name to a valid Kubernetes name. 

Form the Docs:
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

```
By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.
```

As you already mentioned, it is a bit more restrictive because it drops the non-letters at the beginning of the name. This is not necessarily an issue. 

We should truncate the name to 253 characters instead of the MaxInt to be compliant.

**Comment by jtnord** [comment]
@ccojocar whatever the intent of that function I have not seen any code that uses it like that.  everything uses it to go from "I have a thing called X" to "X shall be persisted as X'".

You can rewrite this ticket however you desire or close it and create a new one that states all the jx codebase is incorrectly calling this one helper function, but the big scary bug remains.

**Comment by jtnord** [comment]
could use something similar to IDN?  [Punny Code](https://en.wikipedia.org/wiki/Punycode), issue would remain with truncating.

**Comment by ccojocar** [comment]
@jtnord If I understand correctly, your concern is that potentially two slightly different names could map to the same Kubernetes name. In the current implementation, the collision is more likely if the name contains many non-alphanumeric characters which get replaced with a '-'.

Probably, we need a better hash function which still produces human readable name but with low collision rate.

**Comment by jtnord** [comment]
@ccojocar exactly your last comment
