### ISSUE TITLE
github : failed to Creating default staging and production environments 

### ISSUE THREAD

**Issue by devopsgong** [jenkins-x/jx#2889]
### Summary 
$ jx install --provider=eks --default-environment-prefix=codecloud
failed at the step:
? Select the organization where you want to create the environment repository: devopsgong
error: creating the environments: building the Git repository options for environments: updating the TeamSettings with Environments organisation: failed to create the jx Dev namespace: Failed to create Namespace jx namespaces "jx" already exists

### Steps to reproduce the behavior
1) install jx on Ubuntu 18.04
2) jx create cluster eks --cluster-name=codecloud --skip-installation=true
3) jx install --provider=eks --default-environment-prefix=codecloud

### Expected behavior
I am following the steps described at https://www.bogotobogo.com/DevOps/Docker/Docker_Kubernetes_Jenkins-X-EKS.php

Jenkins is successfully installed in EKS, I can login

Expect to create staging and production environments in GitHub

### Actual behavior
jx install stopped with error
? Select the organization where you want to create the environment repository: devopsgong
error: creating the environments: building the Git repository options for environments: updating the TeamSettings with Environments organisation: failed to create the jx Dev namespace: Failed to create Namespace jx namespaces "jx" already exists

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.810
jenkins x platform 0.0.3321
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.0
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.17.1
Operating System   Ubuntu 18.04.1 LTS

```

### Jenkins type

- [ x] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by devopsgong** [comment]
used EKS cluster

running jx cli on Ubuntu 18.04

**Comment by ccojocar** [comment]
@devopsgong Please could you verify if the step 2 already created the `jx` namespace and did some basic installation? It seems that something is already there.

**Comment by ccojocar** [comment]
@devopsgong I am going to close this issue. Please feel free to open another issue if you are still facing this problem. Thanks
