### ISSUE TITLE
jx create spring build succeeds but deploy fails

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#290]
> Using:
> NAME        VERSION
> jx          1.0.85
> Jenkins X   0.0.137
> Kubernetes  v1.7.12-gke.1
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

Actions:
jx create spring -d web -d actuator
Deployment hangs for a long time, with the following warning, then fails with the subsequent error

```
WARNING: Failed to query the Pull Request last commit status for https://github.com/redacted/environment--staging/pull/1 ref c269de9b60985144eed89d72989f5be5437ee4c2 Could not find a status for repository redacted/environment--staging with ref c269de9b60985144eed89d72989f5be5437ee4c2

Pull Request https://github.com/redacted/environment--staging/pull/1 is merged at sha 99779bd0e12d8b7b1eee0d94d1850d14072938ec
merge status: pending for URL https://api.github.com/repos/redacted/environment--staging/statuses/99779bd0e12d8b7b1eee0d94d1850d14072938ec with target: http://unconfigured-jenkins-location/job/redacted/job/environment--staging/job/master/2/display/redirect description: This commit is being built

EXITCODE   0WARNING: merge status: error URL: http://unconfigured-jenkins-location/job/redacted/job/environment--staging/job/master/2/display/redirect description: This commit cannot be built
error: Status: error URL: http://unconfigured-jenkins-location/job/redacted/job/environment--staging/job/master/2/display/redirect description: This commit cannot be built
```

Looks like something is not configured.

**Comment by rawlingsj** [comment]
I'm 99% sure this is related to some exposecontroller config changes that are reflected in jx and the default environments.  The main problem is we always clone master of the default environments repo and release jx independently of the cloud-environments repo.  I think we need to figure out a way to coordinate releasing these repos a bit better.

We're in a state of flux ATM but things should calm down by next week and avoid situations like this.  I'll take a look first thing and fix up what's going wrong here.

**Comment by tdcox** [comment]
Ah, I have done a couple of uninstall/install cycles to fix another problem, so perhaps I have a stale exposecontroller?

**Comment by tdcox** [comment]
Just done a clean cluster install and now the exposecontroller is not routing traffic.

**Comment by rawlingsj** [comment]
This is resolved now and verified in the latest release, fix is https://github.com/jenkins-x/jx/commit/99362f765769fcdcbbbef02bd140f959d7b14784

jx version 1.0.94
jenkins-x-platform 0.0.187
