### ISSUE TITLE
Error:  deployment jenkins-x-mongodb failed to become ready in namespace jx

### ISSUE THREAD

**Issue by trevorputbrese** [jenkins-x/jx#2907]
### Summary -- Performing JX install on PKS.  Have set default storageclass for clusters.  PVC is showing as bound for the mongodb pod:
root@cli-vm:~/.jx/cloud-environments/env-pks# kubectl get pvc
NAME                        STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jenkins                     Bound     pvc-f2c10e22-2418-11e9-ae96-00505688f9d0   30Gi       RWO            thin-disk      42m
jenkins-x-chartmuseum       Bound     pvc-f2bd35d2-2418-11e9-ae96-00505688f9d0   8Gi        RWO            thin-disk      42m
jenkins-x-docker-registry   Bound     pvc-f2bf93c6-2418-11e9-ae96-00505688f9d0   100Gi      RWO            thin-disk      42m
jenkins-x-mongodb           Bound     pvc-f2c50a38-2418-11e9-ae96-00505688f9d0   8Gi        RWO            thin-disk      42m
jenkins-x-nexus             Bound     pvc-f2c7dd59-2418-11e9-ae96-00505688f9d0   8Gi        RWO            thin-disk      42m

Status of MongoDB pod is in CrashLoopBackoff.  Pod details:

root@cli-vm:~# kubectl describe pod jenkins-x-mongodb-6bfd5d9c79-rszsv
Name:               jenkins-x-mongodb-6bfd5d9c79-rszsv
Namespace:          jx
Priority:           0
PriorityClassName:  <none>
Node:               0294dab6-0424-4a1b-a17a-85f0292bc8b6/172.15.0.5
Start Time:         Tue, 29 Jan 2019 14:55:22 -0800
Labels:             app=mongodb
                    chart=mongodb-4.0.4
                    pod-template-hash=2698185735
                    release=jenkins-x
Annotations:        <none>
Status:             Running
IP:                 172.16.4.9
Controlled By:      ReplicaSet/jenkins-x-mongodb-6bfd5d9c79
Containers:
  jenkins-x-mongodb:
    Container ID:   docker://c441ea35f3a44731b1eeb0702f720ca98eff4903af0814f8be2c5418e3e22173
    Image:          docker.io/bitnami/mongodb:3.6.6-debian-9
    Image ID:       docker-pullable://bitnami/mongodb@sha256:110d3d4bfa71c8ebaabc4ee0a8fd19464b68fe239c5c4effcd41c585cc53665a
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    100
      Started:      Tue, 29 Jan 2019 15:46:35 -0800
      Finished:     Tue, 29 Jan 2019 15:46:40 -0800
    Ready:          False
    Restart Count:  14
    Liveness:       exec [mongo --eval db.adminCommand('ping')] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      MONGODB_ROOT_PASSWORD:  <set to the key 'mongodb-root-password' in secret 'jenkins-x-mongodb'>  Optional: false
      MONGODB_USERNAME:
      MONGODB_DATABASE:       monocular
      MONGODB_EXTRA_FLAGS:
    Mounts:
      /bitnami/mongodb from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tgsdq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  jenkins-x-mongodb
    ReadOnly:   false
  default-token-tgsdq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tgsdq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                From                                           Message
  ----     ------                  ----               ----                                           -------
  Normal   Scheduled               55m                default-scheduler                              Successfully assigned jx/jenkins-x-mongodb-6bfd5d9c79-rszsv to 0294dab6-0424-4a1b-a17a-85f0292bc8b6
  Normal   SuccessfulAttachVolume  55m                attachdetach-controller                        AttachVolume.Attach succeeded for volume "pvc-f2c50a38-2418-11e9-ae96-00505688f9d0"
  Warning  Failed                  52m (x2 over 53m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Failed to pull image "docker.io/bitnami/mongodb:3.6.6-debian-9": rpc error: code = Canceled desc = context canceled
  Warning  Failed                  52m (x2 over 53m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Error: ErrImagePull
  Warning  Failed                  52m (x2 over 53m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Error: ImagePullBackOff
  Normal   BackOff                 52m (x2 over 53m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Back-off pulling image "docker.io/bitnami/mongodb:3.6.6-debian-9"
  Normal   Pulling                 52m (x3 over 54m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  pulling image "docker.io/bitnami/mongodb:3.6.6-debian-9"
  Normal   Started                 49m                kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Started container
  Normal   Created                 49m                kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Created container
  Warning  Unhealthy               49m                kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Readiness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:01:40.313+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:01:40.314+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Readiness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:01:49.990+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:01:49.991+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Readiness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:01:59.648+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:01:59.648+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Liveness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:04.647+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:04.648+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Readiness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:09.741+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:09.742+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Liveness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:14.740+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:14.740+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Readiness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:19.916+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:19.917+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Liveness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:24.783+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:24.784+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Readiness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:29.642+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:29.642+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  48m (x3 over 48m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  (combined from similar events): Liveness probe failed: MongoDB shell version v3.6.6
connecting to: mongodb://127.0.0.1:27017
2019-01-29T23:02:44.924+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-01-29T23:02:44.946+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
  Normal   Pulled   19m (x12 over 49m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Successfully pulled image "docker.io/bitnami/mongodb:3.6.6-debian-9"
  Warning  BackOff  4m (x189 over 46m)  kubelet, 0294dab6-0424-4a1b-a17a-85f0292bc8b6  Back-off restarting failed container
root@cli-vm:~#

### Jx version

The output of `jx version` is:
root@cli-vm:~# jx version
NAME               VERSION
jx                 1.3.27
jenkins x platform 0.0.3321
kubernetes cluster v1.11.2
kubectl            v1.11.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.7.4

**Comment by ccojocar** [comment]
@trevorputbrese mongodb is a dependency of monocular chart. 

https://github.com/helm/monocular/blob/master/chart/monocular/requirements.yaml

Can you install `monocular` with mongodb outside of jx, or just mongo db?

**Comment by trevorputbrese** [comment]
Nope.  Looks like I'm have some issues with monucular.  I'm getting an error installing it separately from jx.  Thanks for the quick response.  I'll work on figuring out this issue, then get back to the jx install.
