### ISSUE TITLE
Let's improve the serverless install when selecting git accounts

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2908]
Let's add some validation when using `--prow` or selecting serverless during the install that ensures the git pipeline user is different from the the local git user.  I know we've iterated on this but reckon UX might like to input here as it's one of the most common setup issues folks have with serverless installs.  

/cc @rheinwein - sorry I don't have Joseph B github ID to tag here, do you have it?
```
? local Git user for GitHub server: rawlingsj
Select the CI/CD pipelines Git server and user
? Do you wish to use GitHub as the pipelines Git server: Yes
? pipelines Git user for GitHub server: jenkins-x-bot-test
```

/area install

**Comment by rheinwein** [comment]
@josephbrueggen can give some input here!

**Comment by josephbrueggen** [comment]
@rawlingsj Validation at crucial steps is generally a good idea, and especially so if this is a common setup issue.

It seems that the git pipeline user must always be different from the local git user—is that correct?

If so, then I'd advise implementing guidance in the current instruction line. ie: _Select the CI/CD pipelines Git server and user. This user must be different from the local Git user._

This way they are informed before making their selection. Validation can also be added after the selection. ie: _Pipelines Git user confirmed unique from local Git user._
