### ISSUE TITLE
Update prow status when build is running

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2914]
### Summary 

When prow receives the GitHub hook it sets the PR status on the build to "Pending - Pending".
This status is the same until the build has completed (success, failed).

However if the cluster is low on resources, or for any other reason the build may start for some time, and it is not possible to tell this from the GitHub check status.

It would also be good if apps could extend / contribute to the status as the stages progress (e.g.  building, integration testing) and augment it with a URL.

Note: the extensibility is a different request but I think the solution may be the same - so filing both here and in the case I am wrong please subdivide this issue.

### Steps to reproduce the behavior

Install jenkins-x with serverless workloads.
import a project whose build takes a long time
create a PR
look at the status or the checks in GitHub for the PR.

### Expected behavior

The status of the prow check changes as the build starts (and moves through stages)

### Actual behavior

The status of the prow check is set to "pending" before the build starts (when the hook is received) and not updated until the build completes.

### Jx version

1.3.784

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE but really N/A

### Operating system / Environment

N/A this is server side.

**Comment by rawlingsj** [comment]
I've had similar thoughts in the past, would be nice to have a pipeline widget that we could update the stages of on the PR.
