### ISSUE TITLE
Provide option for deleting merged branches

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#2917]
### Summary 

Providing an option to delete merged branches from a repo. They are not needed anymore and just distract.

### Steps to reproduce the behavior

Using JenkinsX a lot of branches get created for pull requests which could be deleted. For example https://github.com/jenkins-x/cloud-environments has currently 58 branches. Arguably the deletion of a merged branch can be automated, but I think it would be nice to have this as a dedicated option as well, especially since there is already a `jx delete branch`.

### Expected behavior

Provide something like `jx delete branch -o my-org -n my-repo --merged` which deletes all merged branches.

### Actual behavior

ATM there is no such option.

### Jx version

The output of `jx version` is:

```
jx                 1.3.807
jenkins x platform 0.0.3320
Kubernetes cluster v1.10.11-gke.1
kubectl            v1.10.7
helm client        v2.10.0+g9ad53aa
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS 10.14

**Comment by polothy** [comment]
This actually turned into a problem for us.  With static Jenkins, it does a branch scan every 5 minutes.  For reach branch, it does API calls to our Bitbucket Server to check on the pull request status.  Kinda did a DDoS on our server.

**Comment by mrageh** [comment]
I'd be happy to take this on

**Comment by polothy** [comment]
Any thoughts on how to use this in an automated way?  Or do we need to update something like `jx promote` to delete merged branches?

**Comment by lukaszlenart** [comment]
> Any thoughts on how to use this in an automated way? Or do we need to update something like `jx promote` to delete merged branches?

Any hints how to use this command?
