### ISSUE TITLE
Extract Monocular to an app

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2925]
Currently Monocular [gets installed](https://github.com/jenkins-x/jenkins-x-platform/blob/5ad0c169571ad733b3f543ad98a8e2427a52ebec/requirements.yaml#L26) as part of the JX platform, along with [its dependency MongoDB](https://github.com/helm/monocular/blob/be856b128888c7ddaf71498aeecbb6712b085a91/chart/monocular/requirements.yaml#L2). This seems like overhead and complexity that teams may not care for. Assuming it is not a hard dependency of anything else in JX, just a nicety, could it be extracted to an app? (`jx-eclipse-plugin` would need to be adapted, perhaps.)

**Comment by hferentschik** [comment]
OOI what is the difference between _app_ and _addon_? Are both concepts staying around? Or is app going to replace _addon_? 
To a certain degree, my understanding was that _apps_ are part of the pipeline execution which do something with the application code (for example create some form of a report). Things like Monocular or Nexus are more infrastructure services. So maybe both concepts _apps_ and _addons_ are needed? WDYT?
Or is the general idea, anything optional is an app?

**Comment by pmuir** [comment]
/priority backlog
/kind enhancement

> OOI what is the difference between app and addon? Are both concepts staying around? Or is app going to replace addon?

App will replace addon as soon as we have enough infrastructure in place
