### ISSUE TITLE
'jx create quickstart' and 'jx import' need a way to provide Helm chart values

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#2928]
### Summary 

For some charts values need to be provided for the installation. At the moment there is no way to do that.

### Steps to reproduce the behavior

Neither `jx quickstart create` nor `jx import` have an option to specify Helm charts values, for example, an admin password for a service. At best default values, if specified in the chart are used.

### Expected behavior

Have some sort of `--set` flag which gets passed through to Helm.

### Actual behavior

No option exist. 

### Jx version

The output of `jx version` is:

```
jx                 1.3.807
jenkins x platform 0.0.3320
Kubernetes cluster v1.10.11-gke.1
kubectl            v1.10.7
helm client        v2.10.0+g9ad53aa
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS 10.14

**Comment by vfarcic** [comment]
+1

**Comment by igdianov** [comment]
We are also looking to provide a quickstart for Activiti7 Application Helm chart, so folks could quickly get up and running by using i.e. ` jx create quickstart activiti-cloud-application-quickstart` from Activiti Github location and import the Helm chart into their environment as any other project with default values.yaml. 

It would be awesome to be able to specify helm values to override default quickstart values, somehow. 

What needs to exists to support this case?

Will Jx be able to detect Helm chart project and apply a Helm build pack for it?

Is there a Helm build pack or is it needed to be created in common repo?

**Comment by igdianov** [comment]
'Jx create env - - fork-git-url'  command should also support providing values via '- - set'  or  '- - values' options for script automation for environment Helm charts.
