### ISSUE TITLE
`create devpod` does not honor `--no-tiller`

### ISSUE THREAD

**Issue by amuniz** [jenkins-x/jx#2933]
### Summary 

`create devpod` does not honor `--no-tiller`.

It is trying to use tiller. I've noticed this because my cluster was created with `--no-tiller` so my local helm version does not match with the cluster one. It was a problem as everything was _tillerless_, but `jx create devpod` is complaining about helm+tiller versions not aligned.

```
$ jx create devpod
? Pick which kind of DevPod you wish to create:  go
Namespace jx-edit-amuniz created 
 Installing the ExposecontrollerService in the namespace: jx-edit-amuniz
Updating Helm repository...
Helm repository update done.
error: failed to run 'helm upgrade --namespace jx-edit-amuniz --install --force --timeout 6000 jx-edit-amuniz-es jenkins-x/exposecontroller-service' command in directory '', output: 'Error: UPGRADE FAILED: incompatible versions client[v2.12.3] server[v2.11.0]'
```

### Steps to reproduce the behavior

1. Install a cluster with `--no-tiller` enabled
2. Try to create a devpod

### Expected behavior

It works regardless your local `helm` version.

### Actual behavior

It is requiring your local `helm` to be compatible with remote tiller.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.818
jenkins x platform 0.0.3321
Kubernetes cluster v1.10.11-gke.1
kubectl            v1.13.1
helm client        v2.12.3
helm server        v2.11.0
git                git version 2.19.2
Operating System   Ubuntu 16.04.5 LTS
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

terraform, gke, prow, no-tiller

### Operating system / Environment

Ubuntu.

**Comment by doc-olliday** [comment]
A similar problem here.
Installed jx on minikube with '--no-tiller', created a golang quickstart and generated a devpod based on the quickstart project.
Starting the watch.sh script from within the devpod, it ends up with following output:
```
Starting deploy...
Error: could not find tiller
Helm release mygo not installed. Installing...
No requirements found in charts/mygo/charts.
EnvVarMap: map[string]string{"DIGEST_HEX":"53f32382cdfd1006814db18e3ff9dc093231ae9274ac12319961ce531be2f379", "IMAGE_NAME":"", "DIGEST":"_DEPRECATED_DIGEST_HEX_@sha256:53f32382cdfd1006814db18e3ff9dc093231ae9274
ac12319961ce531be2f379", "DIGEST_ALGO":"_DEPRECATED_DIGEST_HEX_@sha256"}
Error: could not find tiller
WARN[0000] error retrieving helm deployment info: Error: could not find tiller 
FATA[0000] deploy failed: deploying mygo: exit status 1 
make: *** [skaffold-run] Error 1
```
The '_DEPRECATED_DIGEST_HEX_' thing seems to be some other problem with skaffold.

**Comment by langleyd** [comment]
Still seems to be an issue. version:

```
jx                 2.0.61
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

**Comment by afirth** [comment]
try `export JX_NO_TILLER=true` 
see #4082

**Comment by rsmolgovsky-lendage** [comment]
I have similar problem just when running ./watch.sh .
The cluster was created with jx create cluster gke 
Output:
....

_DEPRECATED_DIGEST_HEX_: digest: sha256:0605fe0407faafd0da29d2e55cf4abee4c7bce8ce04794524c371cac369f4339 size: 1579
Build complete in 2.795029545s
Starting test...
Test complete in 5.517µs
Starting deploy...
Error: could not find tiller
Helm release spring-boot-web-dev not installed. Installing...
No requirements found in charts/spring-boot-web-dev/charts.
EnvVarMap: map[string]string{"DIGEST_HEX":"0605fe0407faafd0da29d2e55cf4abee4c7bce8ce04794524c371cac369f4339", "IMAGE_NAME":"rsmolgovsky-lendage/spring-boot-web-dev", "DIGEST":"_DEPRECATED_DIGEST_HEX_@sha256:0605fe0407faafd0da29d2e55cf4abee4c7bce8ce04794524c371cac369f4339", "DIGEST_ALGO":"_DEPRECATED_DIGEST_HEX_@sha256"}
Error: could not find tiller
WARN[0003] error retrieving helm deployment info: Error: could not find tiller
FATA[0003] deploy failed: deploying spring-boot-web-dev: exit status 1

**Comment by haysclark** [comment]
I'm having the same issue as @rsmolgovsky-lendage on a gke cluster created with _jx_ 2.0.296.  Cluster created with ```jx create cluster gke --ng --skip-login --default-admin-password="MY_PASSWORD" -n jx-ng-cluster```.

Error from DevPod when running ```./watch.sh``` from _NodeJS_ quickstart.
```
[root@hays-nodejs workspace]# ./watch.sh 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] config version (skaffold/v1beta2) out of date: upgrading to latest (skaffold/v1beta11) 
Generating tags...
 - jx-ng-infinitedescent/next-jx-nodejs -> WARN[0000] {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are deprecated, image digest will now automatically be appended to image tags 
gcr.io/jx-ng-infinitedescent/next-jx-nodejs:_DEPRECATED_DIGEST_HEX_
Tags generated in 884.059µs
Starting build...
Building [jx-ng-infinitedescent/next-jx-nodejs]...
Sending build context to Docker daemon  15.36kB
Step 1/6 : FROM node:9-slim
 ---> e20bb4abe4ee
Step 2/6 : ENV PORT 8080
 ---> Using cache
 ---> 7aa1336332a1
Step 3/6 : EXPOSE 8080
 ---> Using cache
 ---> cfe8d8aaaabb
Step 4/6 : WORKDIR /usr/src/app
 ---> Using cache
 ---> c0030b89eacb
Step 5/6 : COPY . .
 ---> Using cache
 ---> 946e6cf7d986
Step 6/6 : CMD npm start
 ---> Using cache
 ---> f2221a6e9b6a
Successfully built f2221a6e9b6a
The push refers to a repository [gcr.io/jx-ng-infinitedescent/next-jx-nodejs]
17300e27e38c: Preparing
df8507921217: Preparing
e16c226cf2a8: Preparing
7fd597d009e4: Preparing
7c6ab5fb7059: Preparing
ed271eac23e9: Preparing
156ff16f37e4: Preparing
ed271eac23e9: Waiting
156ff16f37e4: Waiting
17300e27e38c: Layer already exists
7c6ab5fb7059: Layer already exists
df8507921217: Layer already exists
e16c226cf2a8: Layer already exists
7fd597d009e4: Layer already exists
ed271eac23e9: Layer already exists
156ff16f37e4: Layer already exists
_DEPRECATED_DIGEST_HEX_: digest: sha256:3c2874b20c95bae6ff12988ee55184a3984171be1450b9e57c730afb8fe14af4 size: 1785
Build complete in 1.604312172s
Starting test...
Test complete in 5.029µs
Starting deploy...
Error: could not find tiller
Helm release next-jx-nodejs not installed. Installing...
No requirements found in charts/next-jx-nodejs/charts.
EnvVarMap: map[string]string{"IMAGE_NAME":"jx-ng-infinitedescent/next-jx-nodejs", "DIGEST":"_DEPRECATED_DIGEST_HEX_@sha256:3c2874b20c95bae6ff12988ee55184a3984171be1450b9e57c730afb8fe14af4", "DIGEST_ALGO":"_DEPRECATED_DIGEST_HEX_@sha256", "DIGEST_HEX":"3c2874b20c95bae6ff12988ee55184a3984171be1450b9e57c730afb8fe14af4"}
Error: could not find tiller
WARN[0001] error retrieving helm deployment info: Error: could not find tiller 
FATA[0001] deploy failed: deploying next-jx-nodejs: exit status 1 
```

**Comment by lujunbofan** [comment]
Just writing to confirm that the problem still presents in the most up-to-date jx version:

> NAME               VERSION
jx                 2.0.837
jenkins x platform 2.0.1391
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

Specifically, 'jx install' already has '--no-tiller=true' by default, so only helm client is installed and configured. However, 'jx create devpod' does not have the same default, and as a result, watch.sh always fails with:

`WARN[0005] error retrieving helm deployment info: Error: could not find tiller`

Please either fix the bug or provide an effective workaround. Thanks.

**Comment by tdcox** [comment]
This is still broken.

**Comment by sstubbs** [comment]
I am also having this issue.

**Comment by tilted** [comment]
I am continuing to have this issue as well.
