### ISSUE TITLE
jx install/create --helm3 regression

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#2951]
### Summary 
This worked a couple of days ago, but now using `--helm3=true` on install or create cluster attempts to use `helm` binary which fails

### Steps to reproduce the behavior
jx install --helm3=true

### Expected behavior
Uses helm3 binary

### Actual behavior
Uses helm binary

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.819
jenkins x platform 0.0.3313
Kubernetes cluster v1.10.11-eks
kubectl            v1.13.2
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.19.1
Operating System   Mac OS X 10.14.1 build 18B75
```

(didn't happen on this already installed cluster - it failed on creating a new one, and then installing on that newly created cluster)

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

jx create terraform

### Operating system / Environment

MacBook Pro

**Comment by patrickleet** [comment]
```
➜  clusters git:(master) ✗ jx install --prow=true --gitops=true --tls-acme=true --vault=true --recreate-existing-draft-repos=true --helm3=true
Using helmBinary helm with feature flag: none
? Cloud Provider gke
Git configured for user: Patrick Scott and email pat@patscott.io
Using helm3
Skipping tiller
helm installed and configured
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Installing using helm binary: helm
```

**Comment by patrickleet** [comment]
`ln helm3 helm`  works for now

**Comment by patrickleet** [comment]
actually, `ln` will only get you so far as eventually it tries to run `--client-only` and crashes as it doesn't exist in the helm3 bin

**Comment by ccojocar** [comment]
@jstrachan I am wondering if we should remove `helm3` options in favour of `no-tiller`. We can avoid some confusion. We should use `helm3` only when it gets officially released.

**Comment by patrickleet** [comment]
fine with me - was just playing with it - would you like me to close this ticket?
