### ISSUE TITLE
`jx edit buildpack` defaults when name is specified

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#2955]
### Summary 

If `-n kubernetes-workloads` is specified, `jx edit buildpack` is ignoring `-u` and `-r` arguments. It always uses default values.

### Steps to reproduce the behavior

```bash
jx edit buildpack \
    -n kubernetes-workloads \
    -u https://github.com/vfarcic/jenkins-x-kubernetes \
    -r master -b
```

### Expected behavior

The output should be (notice the GitHub user):

```
Setting the team build pack to kubernetes-workloads repo: https://github.com/vfarcic/jenkins-x-kubernetes.git ref: master
```

### Actual behavior

The output should NOT be (notice the GitHub user):

```
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.791
jenkins x platform 0.0.3321
Kubernetes cluster v1.10.11-gke.1
kubectl            v1.13.2
helm client        v2.12.1+g02a47c7
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [X] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

MacOS

**Comment by Guschtel** [comment]
I can validate this is also happening to me.
Would be great, if one could set the teams own git repository.

This can be achieved by:
- kubectl edit env dev - fix the buildPackUrl to your own kubernetes repo
- Fix the url in the import module, kubernetes references classic via import.yaml, see https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/imports.yaml  
Set your own url there.
