### ISSUE TITLE
jx import fails to push to chart museum on fresh install

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#2969]
### Summary 
on a fresh install, a `jx import` will build the imported project, but will fail to push to chartmuseum

### Steps to reproduce the behavior
fresh install
`jx import`

### Expected behavior
build succeeds

### Actual behavior
build fails with 
```
Received 401 response: {"error":"unauthorized"}
error: Failed to post chart to http://jenkins-x-chartmuseum:8080/api/charts due to response 401: {"error":"unauthorized"}
```

Workaround: kill the chartmuseum pod. The replacement pod that gets created seems to work

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 ?[32m1.3.825?[0m
jenkins x platform ?[32m0.0.3321?[0m
Kubernetes cluster ?[32mv1.10.11-gke.1?[0m
kubectl            ?[32mv1.13.2?[0m
helm client        ?[32mv2.11.0+g2e55dbe?[0m
helm server        ?[32mv2.12.2+g7d2b0c7?[0m
git                ?[32mgit version 2.15.1.windows.2?[0m
Operating System   ?[32mWindows 10 Pro 1809 build 17763?[0m
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster
GKE

**Comment by jinjie2088** [comment]
the same error, how to fix?

**Comment by shahnewazrifat** [comment]
Any update on this one? Facing the same on fresh jx installation with Tekton as pipeline runner

**Comment by dbwest** [comment]
Bump. Getting this as well.
