### ISSUE TITLE
Use a simpler version scheme

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2972]
Reading [this post](https://blog.armesto.net/automatically-versioning-your-application-on-jenkins-x/) by @fiunchinho reminds that `jx-release-version` and Git tags with `jx step tag` are unnecessary overkill for (IMO) all users of the Kubernetes (CD) buildpacks and the great majority of users of the Classic buildpacks. Even if you buy into semver’s idea of compatibility guarantees (and I think it is wishful thinking), that is only meaningful for authors of library components with public distribution, such as Java APIs uploaded to Maven Central, which is certainly not the principal use case for JX. The Git tags are also created on special commits off the `master` branch, which is awkward since `git pull` will not find them by default.

In [JEP-305](https://jenkins.io/jep/305) I chose a version format which can be deterministically computed from the Git repository itself¹, without needing special tools, version number vending, Git push credentials, etc.; and which produces versions which compare naturally in various senses. I would propose that `jx-release-version` and `jx step tag` be deprecated, and that the buildpacks simply set²

```sh
VERSION=$(git rev-list --count HEAD).$(git rev-parse --short=12 HEAD)
```

You will get a numeric component which is guaranteed to be monotonically increasing in the `master` branch from which releases are cut; a nonnumeric component for the commit hash of a `master`-branch Git commit that can be easily pasted into `git` commands; and no unused `0.0.` or `0.1.` prefix clutter that is meaningless in a CD environment.

Sample change (from a real project):

```diff
-0.0.103
+448.801a18c69f6e
```

----

¹Regardless of refs (works on a detached `HEAD`), _but_ may not work in a shallow clone, which Knative Build used last I checked—noticed because it broke Sonar scans, worked around via

```groovy
sh 'git fetch --unshallow && git branch -m $BRANCH_NAME'
```

²In the case of the Maven pack, `mvn versions:set` could if desired be skipped in favor of a Maven extension like that in JEP-305, though this would require changes to the quickstarts as well.

**Comment by fiunchinho** [comment]
We used a similiar approach on my former employer, but we used the current date when the build was being made, instead of the count of commits in the branch.

I think the suggested approach it's better since:
- has no dependencies on external tooling
- no need for manual intervention as opposed to releasing a new major/minor version when using jx-release-version
- it's a commit: no need to go and see what commit is 1.2.3 referring to.

**Comment by jglick** [comment]
Indeed you can also simply use a timestamp (optionally with a short commit hash in an informative section). The drawback is that the version is not then a function of your sources; it is essentially arbitrary. While for JEP-305 this distinction [was critical](https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc#alternatives-based-on-iep-9), for the K8s buildpack a timestamp might be fine, since the version is merely an identifier of a chart to deploy—there is no expectation that it will be used in a build system dependency.

**Comment by jglick** [comment]
@jstrachan mentions that there is a new system for `master` tags used in Tektōn mode. This still feels like overkill for the typical uses of JX—why do we need tags at all when we can pick a reasonable version number and deploy it on `master` commits without further ado?

**Comment by sboardwell** [comment]
Curious as to whether and how something like this would work with an approach such as GitFlow? i.e. creating a release branch from develop, fine tuning, etc, then pushing to master...
