### ISSUE TITLE
default environments are missing the domain

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#298]
after the last release when a GKE cluster is created the default environments jobs fail because there's no domain in the helm values.yaml, i.e
```
expose:
  domain: foo.io
```

pretty sure this is a recent change causing the domain to not be copied from the initial dev team environment to the default staging and prod envs.

**Comment by michaelneale** [comment]
yes I saw this too with a fresh cluster: 

```
[-banehill-production_master-ICE5VEP3JYKL2CZ73T7PI5P56K6W53UUYBWO6U4JWBGQXIG2D5NQ] Running shell script
+ make install
helm upgrade "jx-production" "env" --install --namespace "jx-production"
Release "jx-production" does not exist. Installing it now.
EXITCODE   0Error: timed out waiting for the condition
make: *** [install] Error 1
```

**Comment by rawlingsj** [comment]
yeah - I'm just going through it now, hope to have a fix soon
