### ISSUE TITLE
jx create cluster iks does does not create cluster in EU

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#2984]
### Steps to reproduce the behavior

Run `jx create cluster iks -n xxx -r eu-de -z fra04 --kube-version 1.10.12 -m b2c.4x16`

### Expected behavior

IBM k8s cluster in Europe is created

### Actual behavior

    error creating cluster region "fra04" not found in "us-east"

### Jx version

The output of `jx version` is:

```
// Some warnings since there is no cluster yet
NAME             VERSION
jx               1.3.830
git              git version 2.20.1
Operating System Mac OS X 10.14.2 build 18C54```
```

### Additional hints

There seems to be a mix of region name and region alias. The interactive dialogue to choose a reqion shows `eu-de` and tries to use this internally. Within the API the string `eu-central` must be used, as returned by curl https://containers.bluemix.net/v1/regions

```
{
	"regions": [{
			"name": "ap-north",
			"alias": "jp-tok",
			"cfURL": "api.au-syd.bluemix.net",
			"freeEnabled": false
		},
		{
			"name": "ap-south",
			"alias": "au-syd",
			"cfURL": "api.au-syd.bluemix.net",
			"freeEnabled": true
		},
		{
			"name": "eu-central",
			"alias": "eu-de",
			"cfURL": "api.eu-de.bluemix.net",
			"freeEnabled": true
		},
		{
			"name": "uk-south",
			"alias": "eu-gb",
			"cfURL": "api.eu-gb.bluemix.net",
			"freeEnabled": true
		},
		{
			"name": "us-east",
			"alias": "us-east",
			"cfURL": "api.ng.bluemix.net",
			"freeEnabled": false
		},
		{
			"name": "us-south",
			"alias": "us-south",
			"cfURL": "api.ng.bluemix.net",
			"freeEnabled": true
		}
	]
}
```

**Comment by ccojocar** [comment]
@ascheman Is this still an issue?

**Comment by ascheman** [comment]
I think so, @ccojocar. I was not running into the problem recently since I was just using the default region _us-east_. If you have not fixed it somehow, I guess using eu-de (aka. eu-central) would still run into the problem. There needs to be a transformation between the alias (used in UI) and the name (used in API-Calls).

**Comment by ccojocar** [comment]
@a-roberts I think you originally contributed the IKS support. Do you mind having a look at this issue? Thanks

**Comment by a-roberts** [comment]
^^ @bkuschel

**Comment by dcberg** [comment]
This does not appear to be a problem when using the IKS CLI. I am able to use the `eu-de` alias to set the region with the IKS CLI. From the commands below you can see that I can set the region and list the zones of which `fra04` is a valid zone.
What version of the CLI are you using (see below).
What code path are you using to set the region endpoint?

`container-service/kubernetes-service   0.2.80`

```
ibmcloud ks region-set eu-de
OK
```

```
 ibmcloud ks region

Region:   eu-de
```

```
ibmcloud ks zones
OK
Zone
ams03
mil01
osl01
par01
fra02
fra04
fra05
```

**Comment by ascheman** [comment]
@dcberg this is not an issue with IKS CLI but with `jx` CLI. `ibmcloud` is never used directly nor indirectly (as a subtask of the `jx` execution). `jx` calls the IBM cloud RESTful API, but obviously in the wrong way - unless someone has fixed the issue in the mean time.
