### ISSUE TITLE
support adding PR labels as environment variables

### ISSUE THREAD

**Issue by sboardwell** [jenkins-x/jx#2990]
### Summary 

As discussed [in Slack](https://kubernetes.slack.com/archives/C9LTHT2BB/p1549035265988100)

Pipelines could benefit from knowing the labels for a given PR, using them as conditionals, etc.

### Expected behavior

`jx step pr labels` outputs the labels found on the PR

* Using a default prefix (maybe `JX_PR_LABEL_` by default?)
* any non letter/digits to `_` (regardless of emojis, etc)

#### Example:
a label `bug :bug:` would become env var `JX_PR_LABEL_BUG__BUG_=bug :bug:`

### Questions:

Given `jx step pr labels` returns
```
JX_PR_LABELS_SIZE_M=size/M
JX_PR_LABELS_OKAY_TO_TEST=ok-to-test
```
how would these values be set, for example, in the `env` object of a declarative pipeline? Would this have to be done in the Jenkinsfile? Here is an example using the readProperties step (replace the PR_LABELS with a call to the actual pre labels step):
```
PR_LABELS="""
JX_PR_LABELS_SIZE_M=size/M
JX_PR_LABELS_OKAY_TO_TEST=ok-to-test
"""

pipeline {
    agent any
    stages {
        stage('Set Vars') {
            steps {
                script { def props = readProperties(text: PR_LABELS.trim()).each { k, v -> env."${k}" = "${v}" } }
            }
        }
        stage('Test Var Exists') {
            when {
                expression { return env.JX_PR_LABELS_OKAY_TO_TEST != null  }
            }
            steps {
                echo "Running the tests JX_PR_LABELS_OKAY_TO_TEST"
                echo "${JX_PR_LABELS_OKAY_TO_TEST}"
            }
        }
        stage('Test Var Non-Existent') {
            when {
                expression { return env.JX_PR_LABELS_OKAY_TO_TEST2 != null  }
            }
            steps {
                echo "Running the tests JX_PR_LABELS_OKAY_TO_TEST2"
                echo "${env.JX_PR_LABELS_OKAY_TO_TEST2}"
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}
```

However, it doesn't seem a very elegant solution.

**Comment by sboardwell** [comment]
I will start working on this today.

**Comment by suhas1git** [comment]
How to add GitHub PR Labels via jenkins Declarative Pipelines ?
