### ISSUE TITLE
jx create cluster iks should create IBM Docker registry namespace

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#2997]
### Summary 

Per default on IBM K8s the IBM Docker registry is used instead of the internal JX Docker registry, cf. jenkins-x/cloud-environments#255. If there is no namespace created manually, JX Docker builds cannot push the created images.

### Steps to reproduce the behavior

```
jx create cluster iks 
```

_I am not sure which parameter sets the Docker registry namespace_. Let's say it was `xxx`.

### Expected behavior

The namespace would have been created and visible on the IBM Cloud:

```
ibmcloud cr namespaces
Listing namespaces...

Namespace
xxx

OK
```

### Actual behavior

No namespace was created:

```
ibmcloud cr namespaces
Listing namespaces...

OK
```

Therefore all Docker pushes fail.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.836
jenkins x platform 0.0.3321
Kubernetes cluster v1.10.12+IKS
kubectl            v1.13.2
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.20.1
Operating System   Mac OS X 10.14.3 build 18D42
```

**Comment by ccojocar** [comment]
@a-roberts I think you originally contributed the IKS support. Do you mind having a look at this issue? Thanks

**Comment by a-roberts** [comment]
Hey @ccojocar, I contributed towards the IBM Cloud Private (ICP support), my colleague @bkuschel is who you're looking for
