### ISSUE TITLE
jx step changelog does not find commit hash if tag already exists for imported projects

### ISSUE THREAD

**Issue by hangchan** [jenkins-x/jx#3008]
### Summary 
Issue in https://github.com/jenkins-x/jx/issues/2934 is not fixed.  jx step changelog works if all the tags were created by jx.  If there are existing tags referring to commits in the master branch, this will fail.
### Expected behavior
```
++ cat ../../VERSION
+ jx step changelog --version v5.3.58
Using batch mode as inside a pipeline
Generating change log from git ref 6809c62fe648241816733687309ef1e06e76a712 => c2e1b808b30a350734a1e32b68f87fc36a66607e
Unable to find user: jenkins-x.googlegroups.com -- users.jenkins.io "jenkins-x.googlegroups.com" not found
Unable to find user: jenkins-x.googlegroups.com -- users.jenkins.io "jenkins-x.googlegroups.com" not found
```
### Actual behavior
```
++ cat ../../VERSION
+ jx step changelog --version v5.3.57
Using batch mode as inside a pipeline
Generating change log from git ref 5.3.55 => 14372096fc7930810876ec69281fc39c7b3b43cd
error: object not found

script returned exit code 1
```

### Jx version
1.3.831
The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@a-roberts I think you originally contributed the IKS support. Do you mind having a look at this issue? Thanks

**Comment by a-roberts** [comment]
^^ @bkuschel
