### ISSUE TITLE
jx create quickstart --no-import doesn't run draft 

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#3012]
### Summary 

Running `jx create quickstart --no-import` only clones the quickstart. It doesn't set up git and it doesn't run draft.

### Steps to reproduce the behavior

```
$ jx create quickstart --no-import
Using Git provider GitHub at https://github.com
? Git user name? davidcurrie

About to create repository  on server https://github.com with user davidcurrie
? Which organisation do you want to use? davidcurrie-org
? Enter the new repository name:  test

Creating repository davidcurrie-org/test
? select the quickstart you wish to create golang-http
Generated quickstart at /Users/dcurrie/code/src/github.com/davidcurrie-org/test
### NO charts folder /Users/dcurrie/code/src/github.com/davidcurrie-org/test/charts/golang-http
Created project at /Users/dcurrie/code/src/github.com/davidcurrie-org/test

$ ls test
Makefile    README.md   curlloop.sh main.go     watch.sh
```

### Expected behavior

My expectation (perhaps incorrect) was this it would do everything but the pipeline setup.

### Actual behavior

Command does nothing but the clone.

### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 1.3.841
jenkins x platform 0.0.3321
Kubernetes cluster v1.11.5-gke.5
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.18.0
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

MacOS

**Comment by ccojocar** [comment]
draft is only executed by the import command, which is invoked from `create quickstart`. The `no-import` option disables entire the import command.

**Comment by ccojocar** [comment]
@davidcurrie Can we close this issue, or are you interested to have the requested behaviour?

**Comment by davidcurrie** [comment]
I have no personal requirement for this but my expectation is that `--no-import` would just prevent the project being added to Jenkins X but should otherwise generate the same files. If there's no particular interest in promoting `jx create quickstart` as a tool for generating best practice projects regardless of whether they are then going to be built/deployed with Jenkins X then this can be closed.
