### ISSUE TITLE
jenkins-x-controllerteam   0/1   ImagePullBackOff

### ISSUE THREAD

**Issue by ffinkdevs** [jenkins-x/jx#3029]
### Summary 
Failed to pull image "jenkinsxio/builder-go:0.1.232": rpc error: code = Unknown desc = failed to get image information: failed to get image diffIDs: manifest sha256:2afc7342580a90995393453dec204e043845e31af456e2f92cd51b803e4d2bab: not found

### Steps to reproduce the behavior
/jx install --provider=kubernetes \      
--external-ip=xxxxxx \
--domain=ci.xxxxxx.xxxx --skip-ingress 

### Expected behavior
installs a version of controllerteam which exists
### Actual behavior
tries to install a version which does not exist
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.854
jenkins x platform 0.0.3368
Kubernetes cluster v1.13.3
kubectl            v1.13.2
helm client        &version.Version{SemVer:"v2.11.0+unreleased",
helm server        v2.11.0+g2e55dbe
git                git version 2.19.2
Operating System   Unkown Linux distribution Linux version 4.19.16 (nixbld@localhost) (gcc version 7.4.0 (GCC)) #1-NixOS SMP Wed Jan 16 21:04:38 UTC 2019

```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

Installed via hetzner kube cli tool, 3 workers 1 master, installed longhorn for storage
and a ingress for public endpoints
### Operating system / Environment

NixOs

**Comment by ccojocar** [comment]
@ffinkdevs Are you able to pull other images? Is only the `go-builder` image failing?

**Comment by ffinkdevs** [comment]
It's the only image which fails, tried on other kubernetes clusters and a
new version of jx, it fails with all of em, on docker hub the image does
not exist

**Comment by seanpianka** [comment]
If you're still experiencing this issue, read [this SO post](https://stackoverflow.com/questions/49414735/minikube-external-registry-failed-to-pull-image-redis-ha) which explains that issues pulling the images during `$ jx create cluster ...` might be caused by a corporate VPN.
