### ISSUE TITLE
Jenkins-x-versions CI setup issues

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#3037]
### Summary 

the Jenkins-x-versions repo CI is not correct

### Steps to reproduce the behavior

create a PR (like jenkins-x-versions#20)  and run the tests

### Expected behavior

Given the triviality the tests should run and pass

### Actual behavior

they fail

Additionally if you trigger a build of master to compare to try and work out how anything was merged, you get a comepletely useless build.  [ref](https://core.jx.cd.jenkins-x.io/teams/jx/projects/browse/jenkins-x-versions/master/10)

Additionally even though they fail they do not notify the GitHub PR and the "serverless jenkins" check stays in pending.

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by warrenbailey** [comment]
Tests on this repository now exist but need to be invoked manually.

/close
