### ISSUE TITLE
JX add dependencies such as ImageMagick

### ISSUE THREAD

**Issue by agentmarine** [jenkins-x/jx#3038]
### Summary 
The project that I am attempting to deploy into a JX cluster has a requirement for ImageMagick to be installed on the NodeJS pod, I've attempted a few things to do this but I think I am still missing some thing.

Can any one provide some more information on how I might be able to add this dependency?

**Comment by patrickleet** [comment]
I imagine this would go in the Dockerfile of the NodeJS App

**Comment by patrickleet** [comment]
Here's a tutorial from the top of Google - https://medium.com/@aungmt/image-manipulation-in-nodejs-bdc31da22d08

**Comment by ccojocar** [comment]
@agentmarine Do you need more help? Can we close this issue?

**Comment by agentmarine** [comment]
The resource Patrickleet gave was fantastic, I forgot that I had to build my self a dockerfile at one point so i thought it was down to the base images within JX.
