### ISSUE TITLE
jx delete application prompts multiple times for github user to use for pull requests

### ISSUE THREAD

**Issue by mikecirioli** [jenkins-x/jx#3044]
### Summary 
When running `jx delete application` I am prompted for the guthub user account to use for each pull request.  I expected i would be prompted only once - not sure if this is an error with my assumption or a true bug.

### Steps to reproduce the behavior
run `jx delete application` for an app that has preview & production environments
### Expected behavior
i would be prompted once for the GH user to use
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.841
jenkins x platform 0.0.3354
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.16.0
Operating System   Mac OS X 10.14.2 build 18C54

```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by heavyengineer** [comment]
I've observed this behaviour  bitbucket cloud too.

**Comment by ccojocar** [comment]
@mikecirioli Please could you check if the user and token is configured in `~/.jx/gitAuth.yaml` after the first prompt? I think, it should prompt only if the git server is not configured.

**Comment by mikecirioli** [comment]
i believe so, my `gitAuth.yaml` looks like this:

```
>$ cat ~/.jx/gitAuth.yaml
servers:
- url: https://github.com
  users:
  - username: mikecirioli
    apitoken: <redacted>
    bearertoken: ""
  - username: jenkinsx-dev-mikec-bot
    apitoken: <redacted>
    bearertoken: ""
  - username: jenkins-x-bot-test
    apitoken: <redacted>
    bearertoken: ""
  name: github.com
  kind: github
  currentuser: mikecirioli
defaultusername: mikecirioli
currentserver: https://github.com
pipelineusername: jenkinsx-dev-mikec-bot
pipelineserver: https://github.com
```
