### ISSUE TITLE
jx install ignores AdminPassword in myvalues.yaml

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3050]
### Summary 
When installing with `jx install` it always defaults to creating a new adminpassword even if one has been given in myvalues.yaml

### Steps to reproduce the behavior
Add jenkins.Master.AdminPassword in myvalues.yaml. Run jx install. A new password is generated.

### Expected behavior
For gitops, the yaml file should be the single source of truth. The CLI does have a flag, but bare bones command should follow the yaml file as much as possible, and as such no password should be generated

### Actual behavior
A new password is generated.

### Jx version

The output of `jx version` is:

```
jx                 1.3.867
jenkins x platform 0.0.3368
Kubernetes cluster v1.11.6-gke.6
kubectl            v1.13.3
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE highly available cluster. Created manually.

### Operating system / Environment

Mac OSX

**Comment by ccojocar** [comment]
@heroic You can also configure the admin password using the `--default-admin-password' option of the install command.

**Comment by heroic** [comment]
the issue is I am trying to create a gitops install. For our setup the
gitops flag isn't working(some issue in creating value). myvalues.yaml gets
overwritten at install time by extraValues.yaml.

**Comment by ccojocar** [comment]
@heroic is this still an issue for you? Are you interested to migrate to boot instead of using the `install` command.

**Comment by heroic** [comment]
@ccojocar I have migrated to using boot now. Not sure if this still remains an issue.
