### ISSUE TITLE
Support for private source and environment repos

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#306]
What is the story for supporting private (github) repos? 

If I wanted to pre-setup a repo for my environments, I may want to set it up with permissions, as a private repo, and then install jx/create a team that uses those repos (the repos are per team per environment right?)

For importing/creating a repo, I guess I have options there to have an existing private repo, so I think this is mostly about the environment repos right? 

The last I tried, if the repositories pre-existed it would fail.

**Comment by rawlingsj** [comment]
yeah we need a flag to create private repos though once there it should all work as we Jenkins X is working with our own CDX private repos.

> The last I tried, if the repositories pre-existed it would fail.
Yeah that still happens although now we include the cluster name (can override with a `--default-environment-prefix` flag) in the environment repo name to cut down on the chance of preexisting repo names.

**Comment by michaelneale** [comment]
@rawlingsj - so if there is an eexisting private repo it can use it? I know it should for the source code, but what about the environments?

**Comment by jstrachan** [comment]
so far GitHub Enterprise is working great. BitBucket + gitea really close too
