### ISSUE TITLE
Unable to change nexus password by updating the secrets

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#3060]
### Summary 

When the nexus password is changed from updating the secrets, the change doesn't propagate to the nexus.  This is down to the way that the nexus password is configured.

https://github.com/jenkins-x/nexus/blob/master/postStart.sh#L58-L69

We would need both passwords to update automatically.

### Jx version

The output of `jx version` is:

```
1.3.868
```

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

**Comment by garethjevans** [comment]
Workaround is to change the nexus password in the UI post install

**Comment by polothy** [comment]
Think this is what got me in #3451 - I think what we did was that our password got changed on an upgrade, by accident.  We changed it back via `jx upgrade platform` and Nexus kept the old password somehow.  I'm not 100% certain on the details of how our password changed in the first place.
