### ISSUE TITLE
Naming is inconsistent between apps and applications

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#3062]
### Summary 
Mostly due to renaming and legacy, but at present, `apps` and `applications` are _not_ the same thing.
But there is legacy code where `app` is a contraction of `applications` and is not actually referring to `apps`
eg, `jx get apps` in an alias to `jx get applications` and refers built applications that are created as a result of `jx import` or `jx create quickstart` and are running in the platform
but `jx delete app` deletes an 'app', that is a platform addon managed by the `apps.jenkins.io` CRD.

We should remove all `apps` aliases when referring to `applications`

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by pmuir** [comment]
I *think* this is sorted now.
