### ISSUE TITLE
Failed to re-install jenkins-x platform

### ISSUE THREAD

**Issue by StephenWangasg** [jenkins-x/jx#3083]
### Summary 
Unable to re-install jenkins-x
### Steps to reproduce the behavior

1. `jx install --namespace n1 --provider eks --username admin  --domain n1.com --buildpack kubernetes-workloads --no-tiller --git-private`
2. `jx uninstall`
3.  `jx install --namespace n1 --provider eks --username admin  --domain n1.com --buildpack kubernetes-workloads --git-private`
### Actual behavior
```error: installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace n1 --install --timeout 6000 --version 0.0.3368 --values /home/stephen/.jx/cloud-environments/env-eks/myvalues.yaml --values /home/stephen/.jx/myvalues.yaml --values /home/stephen/.jx/adminSecrets.yaml --values /home/stephen/.jx/extraValues.yaml --values /home/stephen/.jx/cloud-environments/env-eks/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/home/stephen/.jx/cloud-environments/env-eks', output: 'Release "jenkins-x" does not exist. Installing it now.
Error: release jenkins-x failed: clusterroles.rbac.authorization.k8s.io "controllercommitstatus-n1" already exists'
```

### Jx version
1.3.870

### Jenkins type

- [x ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

eksctl

### Operating system / Environment

Ubuntu 18.04

**Comment by jstrachan** [comment]
a workaround for now is to add `--no-tiller` to the `jx install` command
