### ISSUE TITLE
Should 2 auto deploy environments be installed out of the box? 

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#309]
When you install JenkinsX, you get staging and production environments out of the box. 

This is great, however with both set to auto and with defaults, that means that releases pass through staging and then production, which is a little contrived right? 

Does it make sense to have these 2 environments if they aren't adding any extra testing? Perhaps production could be made manual (so they have to promote from staging, or turn on auto promote - is that possible right now? in the Jenkinsfile?)

**Comment by rawlingsj** [comment]
Yeah I went to change this yesterday however a little more work is needed so that the manual promote works from your machine as it needs to use the new generated password in ~/.jx/chartmuseumAuth.yaml. I think I should be able to sort that today and switch to manual promote fir prod.

**Comment by michaelneale** [comment]
I was able to promote using

```
jx promote -e production -v 0.0.2 demo
``` 

with my version (not sure if I am missing something) but that was to the auto deploy production environment

**Comment by michaelneale** [comment]
Fixed. It now only autodeploys to staging
