### ISSUE TITLE
The maven build shows Execution exception: Java heap space

### ISSUE THREAD

**Issue by ica10888** [jenkins-x/jx#3098]
When I build my own java project.

The maven build pipeline shows error.

``` shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.0.0:jar (default) on project service-cloud-dataview-server: Error creating source archive: Problem creating jar: Execution exception: Java heap space -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

It seems like heap memory is not enough.

When I changed global setting Kubernetes Pod Template maven's envionment variables 

``` shell
_JAVA_OPTIONS
-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx128m
```

to

``` shell 
_JAVA_OPTIONS
-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx512m
```

`-Xmx128m` change to `-Xmx512m`

pipeline run passed.

It also configured at configmaps `jenkins-x-pod-templates` in `jx`namespaces. 

So I suggest that template maven config change default `-Xmx128m`  to `-Xmx512m`

**Comment by ccojocar** [comment]
@ica10888 Thanks for point this out. Please could you send a PR to https://github.com/jenkins-x/jenkins-x-platform/blob/705e1d3f0779aa825920501ea21c1642309e1a31/values.yaml#L882? Thanks

**Comment by ica10888** [comment]
I have sent a pr at https://github.com/jenkins-x/jenkins-x-platform/pull/4859
Please review it.
Thanks a lot.

**Comment by ccojocar** [comment]
Thanks, Which kind of nodes are you using in your cluster? I am asking this because I would like to avoid getting build pods stuck due to lack of memory. Especially, in a default GKE cluster with 3 n1-standard-2 nodes.

**Comment by ica10888** [comment]
I am using kubernetes cluster is set up in aliyun ECS cluster.( memory average 16g)

The  memory is not enough due to my springboot project's a little massive maven build process，especially maven  plugins.

 The pod maven which is in `jx` namespace is request 800m and limit 1g memory.

if node's memory is not enough， the pod will till keep "Pending".

The maven build I think it is mainest in pod maven .not to mention that  maven pod has 1g memory.

**Comment by ccojocar** [comment]
@ica10888 I am going to close this since it will be fixed by https://github.com/jenkins-x/jenkins-x-platform/pull/4859 Thanks. 

You can also provide the custom heap configuration in `myvaulues.yaml` file.

**Comment by neethualex** [comment]
> When I build my own java project.
> 
> The maven build pipeline shows error.
> 
> ```shell
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.0.0:jar (default) on project service-cloud-dataview-server: Error creating source archive: Problem creating jar: Execution exception: Java heap space -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> ```
> 
> It seems like heap memory is not enough.
> 
> When I changed global setting Kubernetes Pod Template maven's envionment variables
> 
> ```shell
> _JAVA_OPTIONS
> -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx128m
> ```
> 
> to
> 
> ```shell
> _JAVA_OPTIONS
> -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx512m
> ```
> 
> `-Xmx128m` change to `-Xmx512m`
> 
> pipeline run passed.
> 
> It also configured at configmaps `jenkins-x-pod-templates` in `jx`namespaces.
> 
> So I suggest that template maven config change default `-Xmx128m` to `-Xmx512m`

Where is the location in minikube local vm ? can you give me the absolute path to change this setting ?
