### ISSUE TITLE
Connecting to an existing devpod is not obvious

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#3099]
### Summary 
Creating/listing/deleting devpods is done via jx `create devpod`, `get devpods`, `delete devpod`, yet connecting to a devpod is via the rather obtuse `jx rsh -d` command. It would make much more sense to attach/connect to an existing devpod with a command such as `jx attach devpod`

**Comment by ccojocar** [comment]
I think, the shell should be opened automatically in the DevPod when it is first time created. I agree that it would be nice to have a more intuitive command to attach to an existing DevPod.

**Comment by agentgonzo** [comment]
>I think, the shell should be opened automatically in the DevPod when it is first time created

It is, but that's not what this is about. If I disconnect from the devpod, I want an intuitive way to reconnect/reattach.
