### ISSUE TITLE
jx import attempts to trigger pipeline with non-TLS Jenkins URL

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#3110]
### Summary 

After upgrading ingresses with TLS, `jx import` is still using the old, non-TLS URL to trigger the initial pipeline build.

### Steps to reproduce the behavior

1. Install Jenkins X without TLS support.
2. Run `jx upgrade ingress`
3. Run `jx import`

### Expected behavior

`jx import` should successfully trigger the initial pipeline build.

### Actual behavior

It fails with:

```
retrying after error:Failed to trigger job http://jenkins.jx.example.com/job/wbrefvem/job/create-spring-bbcloud/ due to 308 Permanent Redirect
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.884
jenkins x platform 0.0.3354
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE
`jx create cluster gke`

### Operating system / Environment

```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by ccojocar** [comment]
It seems that the Jenkins URL is only updated into the GitHub webhooks. Probably, we should detect dynamically throughout the jx code if the  HTTPS is enabled.

**Comment by ypto** [comment]
Same issue here.

To start the pipeline, i needed to go to Jenkins console and scan the repository.

Another issue after this one, is that as soon the pipeline finishes and puts the application on staging environment, when you do `jx get applications`, the URL shown is on HTTP and not on HTTPS.

Any way around this?

Cheers.

**Comment by ypto** [comment]
Same issue here.

To start the pipeline, i needed to go to Jenkins console and scan the repository.

@ccojocar 
Another issue after this one, is that as soon the pipeline finishes and puts the application on staging environment, when you do `jx get applications`, the URL shown is on HTTP and not on HTTPS.

Any way around this?

Cheers.

**Comment by ccojocar** [comment]
@ypto Please could you open a separate issue for the second problem? I think the promote does not update the ingress of the application. Are you able to access it over HTTP?
