### ISSUE TITLE
Jenkins X for Android

### ISSUE THREAD

**Issue by paulvi** [jenkins-x/jx#3112]
While Jenkins X should be in great shape for Java apps ( https://amazonaws-china.com/blogs/opensource/continuous-delivery-eks-jenkins-x/, https://jenkins-x.io/developing/import/  ),  
I wonder would there magic be there for Android project?

The expectation would be to have needed Jenkins plugins installed, and Android emulator running somehow the App with just freshly built apk.

Searching online for "jenkins x for android" can be tough luck as X would be ignored by  search engines,
so asking directly here.  
Please consider it as feature request, if it not yet supported.

**Comment by ccojocar** [comment]
@paulvi There is an android quick start, but to be honest I don't know in which state it is. 

https://github.com/jenkins-x-quickstarts/android-quickstart

**Comment by ccojocar** [comment]
What it would be your expectation from supporting Android? I think, we will also need to have a dedicated build pack for this with some common development tools for Android.

**Comment by paulvi** [comment]
I checked that Android is not (yet) on roadmap https://jenkins-x.io/contribute/roadmap/

and the most knowledgeable person for the matter is Christopher @orrc, the author of https://wiki.jenkins.io/display/JENKINS/Android+Emulator+Plugin

Answering to https://github.com/jenkins-x/jx/issues/3112#issuecomment-463955937
> What it would be your expectation from supporting Android?

I think it should stay in some parity to other runtimes.  
But as I see now, support for those is powered by Kubenetes, so that should issue of kubernetes if it can somehow pop up an Android VM.  

At least Jenkins X should produce apk, that is just build.

Again, there is hints from @orrc within https://jenkins.io/blog/2018/01/08/moving-from-buddybuild-for-android/ that gives `Jenkinsfile` example.

**Comment by heroic** [comment]
I had an interaction with @jstrachan about this once. He referred me to fastlane. That should work well on jx, at least for android.

**Comment by EamonKeane** [comment]
Bitrise maintain a good docker image which could be the basis of a build pack. It is very large due to all the SDKs (6 GBs I think).

https://github.com/bitrise-docker/android/blob/master/Dockerfile

**Comment by jstrachan** [comment]
a build pack for fastlane would rock!

**Comment by kenyee** [comment]
Android builds usually use gradle...which has a crapload of plugins.
There's no need for fastlane support IMHO, though the buildpack should include fastlane support in the docker image in case it's needed.  iOS developers usually suggest fastlane to Android developers, but they don't have gradle so fastlane was their first decent command line automation build tool ;-)

/remove-lifecycle stale
