### ISSUE TITLE
Jenkins-x-versions directory already exists

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#3117]
### Summary 
There are some instances where jx will complain that the ~/.jx/jenkins-x-version directory already exists and will bail out of the command.

I've seen it on `jx create spring` but it appears intermittent and I've also seen it on `jx create cluster` which seems a bit more consistent. I actually had it twice in a row. 

### Steps to reproduce the behavior
1. Create a new cluster
2. Create a second cluster
3. Second cluster will fail with below error

### Expected behavior
Second cluster is created successful.

### Actual behavior

Cluster creation fails with:

ingress init failed: failed to load version of chart stable/nginx-ingress: cloning "https://github.com/jenkins-x/jenkins-x-versions" repository into "/Users/warrenbailey/.jx/jenkins-x-versions" dir: repository already exists
error creating cluster initializing the Jenkins X platform: initializing the Jenkins X platform: failed to load version of chart stable/nginx-ingress: cloning "https://github.com/jenkins-x/jenkins-x-versions" repository into "/Users/warrenbailey/.jx/jenkins-x-versions" dir: repository already exists

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.885
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.13.2
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.20.1
Operating System   Mac OS X 10.13.6 build 17G5019

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment
Mac OS

### Workaround
Delete the ~/.jx/jenkins-x-version before running the command

**Comment by ranginuitrot** [comment]
Experienced this yesterday.

**Comment by ccojocar** [comment]
@warrenbailey Probably the issue is somewhere here https://github.com/jenkins-x/jx/blob/a0045ec7c4877c53c3ebcdfdfac3bb868ce3190c/pkg/jx/cmd/common_helm.go#L341

**Comment by warrenbailey** [comment]
The steps detailed above do not result in consistent failures, as I've just managed to create two clusters in a row. However I have had that error multiple times over the last few days so will investigate.

**Comment by warrenbailey** [comment]
@ccojocar yeah I think you're right. I was just looking at that code i'm going to tweak the error handling. There's definitely a path it can go down and result in that failure.

**Comment by markawm** [comment]
Hey @warrenbailey - I just spotted this issue, and I think the PR I filed might be relevant: https://github.com/jenkins-x/jx/pull/3123

I saw this a while ago, but then it seemed to go away. I think the intermittency might be down to whether the clone needs updating.

**Comment by warrenbailey** [comment]
Hi @markawm, quite possibly thanks. I'll take a look at that PR now. At the minute I think the update errors then subsequent delete fails which means the fresh clone doesn't work. It looks like your PR would solve the second step in that.
