### ISSUE TITLE
any options dont inicialiaze web pages for home of jenkins x

### ISSUE THREAD

**Issue by rafaelpolo19** [jenkins-x/jx#3126]
any options dont inicialiaze web pages for home of jenkins x

I try whit all options like:
jenkins-x chartmuseum
jenkins-x-docker-registry
jenkins-x-mongodb
jenkins-x-monocular-api
jenkins-x-monocular-prender
jenkins-x-monocular-ui

what is te home page that i shoudl view?
thanks for the response ;)

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@rafaelpolo19 Please could you provide more details? What exactly is the issue? Which command are you running?

**Comment by rafaelpolo19** [comment]
- Ok, once Jenkins-x is installed through the chocolate, I proceeded to create the cluster

![image](https://user-images.githubusercontent.com/47400788/53026117-49a2ee80-3430-11e9-9d6e-cdf9a0bf4bc6.png)

- then two options come out:

Select Jenkins installation type:  [Use arrows to move, type to filter]
> Serverless Jenkins   --> I choose this.
  Static Master Jenkins

- Solicita un usuario git y un token al que usualmente lo depositó.

-then ask: 

Pick workload build pack:   [Use arrows to move, type to filter]
> Kubernetes Workloads: Automated CI+CD with GitOps Promotion --> I choose this.
  Library Workloads: CI+Release but no CD

-the result is this:

![image](https://user-images.githubusercontent.com/47400788/53026471-fda47980-3430-11e9-9164-4becb04fb502.png)

-I enter the ip in a browser and nothing comes out.

![image](https://user-images.githubusercontent.com/47400788/53026542-22005600-3431-11e9-9609-ed87705465f2.png)

**Comment by ccojocar** [comment]
@rafaelpolo19 On Serverless Jenkins the only UI available is deck. You can try to open `deck.jx...`.

**Comment by ccojocar** [comment]
Do you need more help? Can we close this PR?

**Comment by ccojocar** [comment]
I am going to close this. Please feel free to open another issue if you are still facing this problem. Thanks
