### ISSUE TITLE
jx export

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3127]
### Summary 
Currently when you install and use jx, a lot of state changes. However, unless someone started with gitops, there is no way for them to switch to gitops for jx itself.

Adding an export will allow people to carry over their whole infra to a new cluster, and to convert any non-gitops install to gitops

### Steps to reproduce the behavior
NA

### Expected behavior
JX should allow people to "gitops"-ify their installs

### Actual behavior
JX doesn't allow non gitops install to be converted to one.

### Jx version

The output of `jx version` is:

```
jx                 1.3.889
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.3
helm client        Client: v2.12.3+geecf22f
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE. manually

### Operating system / Environment

Mac OSX Mojave

**Comment by jstrachan** [comment]
we have a solution now
https://jenkins-x.io/docs/labs/boot/

In particular https://jenkins-x.io/docs/labs/boot/getting-started/repository/#upgrading-an-existing-cluster

though note this is currently alpha - feedback highly appreciated
