### ISSUE TITLE
jx upgrade ingress --cluster not able to get letsencrypt prod certificates

### ISSUE THREAD

**Issue by ypto** [jenkins-x/jx#3134]
### Summary 
After executing jx upgrade ingress --cluster, if the choice is letsencrypt prod, it never gets the certificates and gets a timeout. This won't happen, if the choice is letsencrypt staging.

### Steps to reproduce the behavior
jx upgrade ingress --cluster

### Expected behavior

Obtaining letsencrypt production certificates

### Actual behavior

Expecting certificates: [jx/tls-chartmuseum jx/tls-jenkins jx/tls-monocular jx/tls-nexus]
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Certificate issuer letsencrypt-prod already configured.
Updating Helm repository...
Helm repository update done.
Ingress rules recreated
Waiting for TLS certificates to be issued...
Timeout reached while waiting for TLS certificates to be ready

inside certificate manager service logs:

 I0218 10:56:39.408469       1 controller.go:179] ingress-shim controller: Finished processing work item "jx/jenkins"
I0218 10:56:39.409264       1 controller.go:173] ingress-shim controller: syncing item 'jx/monocular'
I0218 10:56:39.409315       1 sync.go:177] Certificate "tls-monocular" for ingress "monocular" already exists
I0218 10:56:39.409330       1 sync.go:180] Certificate "tls-monocular" for ingress "monocular" is up to date
I0218 10:56:39.409338       1 controller.go:179] ingress-shim controller: Finished processing work item "jx/monocular"
I0218 10:56:54.362701       1 controller.go:145] certificates controller: syncing item 'jx/tls-chartmuseum'
I0218 10:56:54.363082       1 sync.go:354] Error issuing certificate for jx/tls-chartmuseum: applying acme order back-off for certificate jx/tls-chartmuseum because it has failed within the last 1h0m0s
E0218 10:56:54.363106       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-chartmuseum" due to error processing: applying acme order back-off for certificate jx/tls-chartmuseum because it has failed within the last 1h0m0s
I0218 10:56:55.110962       1 controller.go:145] certificates controller: syncing item 'jx/tls-monocular'
I0218 10:56:55.111338       1 sync.go:354] Error issuing certificate for jx/tls-monocular: applying acme order back-off for certificate jx/tls-monocular because it has failed within the last 1h0m0s
E0218 10:56:55.111365       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-monocular" due to error processing: applying acme order back-off for certificate jx/tls-monocular because it has failed within the last 1h0m0s
I0218 10:56:56.783664       1 controller.go:145] certificates controller: syncing item 'jx/tls-nexus'
I0218 10:56:56.784096       1 sync.go:354] Error issuing certificate for jx/tls-nexus: applying acme order back-off for certificate jx/tls-nexus because it has failed within the last 1h0m0s
E0218 10:56:56.784127       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-nexus" due to error processing: applying acme order back-off for certificate jx/tls-nexus because it has failed within the last 1h0m0s
I0218 10:56:57.453890       1 controller.go:145] certificates controller: syncing item 'jx/tls-jenkins'
I0218 10:56:57.454266       1 sync.go:354] Error issuing certificate for jx/tls-jenkins: applying acme order back-off for certificate jx/tls-jenkins because it has failed within the last 1h0m0s
E0218 10:56:57.454291       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-jenkins" due to error processing: applying acme order back-off for certificate jx/tls-jenkins because it has failed within the last 1h0m0s
I0218 10:58:14.363257       1 controller.go:145] certificates controller: syncing item 'jx/tls-chartmuseum'
I0218 10:58:14.363643       1 sync.go:354] Error issuing certificate for jx/tls-chartmuseum: applying acme order back-off for certificate jx/tls-chartmuseum because it has failed within the last 1h0m0s
E0218 10:58:14.363671       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-chartmuseum" due to error processing: applying acme order back-off for certificate jx/tls-chartmuseum because it has failed within the last 1h0m0s
I0218 10:58:15.111562       1 controller.go:145] certificates controller: syncing item 'jx/tls-monocular'
I0218 10:58:15.112024       1 sync.go:354] Error issuing certificate for jx/tls-monocular: applying acme order back-off for certificate jx/tls-monocular because it has failed within the last 1h0m0s
E0218 10:58:15.112050       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-monocular" due to error processing: applying acme order back-off for certificate jx/tls-monocular because it has failed within the last 1h0m0s
I0218 10:58:16.784270       1 controller.go:145] certificates controller: syncing item 'jx/tls-nexus'
I0218 10:58:16.784593       1 sync.go:354] Error issuing certificate for jx/tls-nexus: applying acme order back-off for certificate jx/tls-nexus because it has failed within the last 1h0m0s
E0218 10:58:16.784617       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-nexus" due to error processing: applying acme order back-off for certificate jx/tls-nexus because it has failed within the last 1h0m0s
I0218 10:58:17.454422       1 controller.go:145] certificates controller: syncing item 'jx/tls-jenkins'
I0218 10:58:17.454802       1 sync.go:354] Error issuing certificate for jx/tls-jenkins: applying acme order back-off for certificate jx/tls-jenkins because it has failed within the last 1h0m0s
E0218 10:58:17.454830       1 controller.go:147] certificates controller: Re-queuing item "jx/tls-jenkins" due to error processing: applying acme order back-off for certificate jx/tls-jenkins because it has failed within the last 1h0m0s
Logs from 2/18/19 10:55 AM to 2/18/19 10:58 AM UTC

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.890
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.3
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.1 (Apple Git-112)
Operating System   Mac OS X 10.13.6 build 17G2208
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

jx create cluster eks

### Operating system / Environment

Mac OS X 10.13.6 build 17G2208

**Comment by ccojocar** [comment]
@ypto I think the ACME back-off kicked in. Did you hit the Let's Encrypt API rate limit before?

**Comment by ypto** [comment]
@ccojocar at least i never got on the logs any message about rate limit. The thing is that from lets encrypt staging all goes well and gets the certificate. I've already waited one week to see if it was rate limits for production, but still on the same situation.

**Comment by ccojocar** [comment]
@ypto Maybe try also to restart the cert-manager, maybe it got into a strange state. I am going to close this issue since is more related to cert-manager than jx. Thanks

**Comment by haysclark** [comment]
Anyone running into this issue should read the cert-manager guide for [troubleshooting-installation](https://docs.cert-manager.io/en/latest/getting-started/troubleshooting.html#troubleshooting-installation).

Clusters running kubernetes v1.12 or under need to have a Label set on their _cert-manager_ pod.

The fix is the following:
```
kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
```

The rerun the ingress setup:
```
jx upgrade ingress
```
