### ISSUE TITLE
Can't update expired Git API token

### ISSUE THREAD

**Issue by svilenvul** [jenkins-x/jx#3139]
### Summary 

I have created some git repositories with a token that expired. I can't fetch code from git now until I update the token.

### Steps to reproduce the behavior

 `jx create env development .. --git-api-token XXXXX` 
 `jx create env staging .. --git-api-token XXXXX` 
 `jx create env production .. --git-api-token XXXXX` 
 `jx create quickstart .. --git-api-token XXXXX` 
 `jx create quickstart .. --git-api-token XXXXX` 

Token expires.

### Expected behavior

I expected that there is an option to update the API token in a central place or for each repository individually.

### Actual behavior

Can't update expired token.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.841
jenkins x platform 0.0.3368
Kubernetes cluster v1.10.0
kubectl            v1.13.1
helm client        Client: v2.12.3+geecf22f
git                git version 2.17.1
Operating System   Ubuntu 18.04.1 LTS
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

minikube

### Operating system / Environment

Ubuntu

**Comment by ccojocar** [comment]
@svilenvul Have you tried `jx delete git token` and then `jx create git token` commands?

**Comment by svilenvul** [comment]
Yes I did it, but still had problems after that.
More specifically, multi branch pipeline failed to checkout a branch when new PR was available.

Anyway I started with a fresh install, I think we can close it for now.

**Comment by anmolnagpal** [comment]
facing same issue
