### ISSUE TITLE
Using gitops flag, GKE installation fails on a project where KMS has never been used.

### ISSUE THREAD

**Issue by Vlatombe** [jenkins-x/jx#3140]
### Steps to reproduce the behavior

* Create a new gce project
* `jx create cluster gke --gitops`
* Follow default jx install steps, when prompted for keyring creation, provide the same project/region as for the cluster

### Expected behavior

KMS configuration is set up. The installation process should ensure the Google Cloud KMS API is enabled on the project, or enable it if needed.

### Actual behavior

The following error is raised

```
Setting up GCP KMS configuration
error: creating the system vault: creating KMS configuration: creating kms keyring 'jx-vault-chestfring-keyring': creating kms keyring: failed to run 'gcloud kms keyrings create jx-vault-chestfring-keyring --location global --project vlatombe' command in directory '', output: 'ERROR: (gcloud.kms.keyrings.create) FAILED_PRECONDITION: Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=626285976735 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.'
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.891
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.11.5
git                git version 2.20.1
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@Vlatombe I think the workaround for now is to enable the KMS service on GCP project before starting the installation. 

We should make sure that is enabled.

**Comment by Vlatombe** [comment]
Yes, this is what I did to fix the problem for my installation.

Le mar. 19 févr. 2019 à 11:49, Cosmin Cojocar <notifications@github.com> a
écrit :
