### ISSUE TITLE
jx create command does not create repo under organization when using gitlab

### ISSUE THREAD

**Issue by tonygilkerson** [jenkins-x/jx#3143]
### Summary 
I use gitlab and when I run a `jx create env` or `jx create quickstart` the repos are created under my user but it should be created under the organization in gitlab

### Steps to reproduce the behavior
jx create cluster gcp

jx create env \
  --name staging \
  --label staging \
  --cluster myenv \
  --prefix myenv \
  --namespace myenv-staging \
  --promotion Auto \
  --git-provider-url https://gitlab.com \
  --git-owner myorg \
  --git-username myuser

also

jx create quickstart \
  --name myapp \
  --language javascript \
  --project-name myproj \
  --git-provider-kind gitlab \
  --git-provider-url https://gitlab.com/ \
  --org myorg \
  --git-username myuser

### Expected behavior

I expect that source repos are created at:

https:/gitlab.com/myorg/environment-myenv-staging.git
http://gitlab.com/myorg/myapp.git

### Actual behavior

Instead they were created under `myuser` but it should be created under `myorg`

https:/gitlab.com/myuser/environment-myenv-staging.git
http://gitlab.com/myuser/myapp.git

below is the actual command output for the create quickstart

```
$ jx create quickstart \
>   --name $QS_PROJECT \
>   --language javascript \
>   --project-name $QS_PROJECT \
>   --git-provider-kind gitlab \
>   --git-provider-url https://gitlab.com/ \
>   --org mile-two \
>   --git-username tgilkerson
Using Git provider gitlab at https://gitlab.com


About to create repository  on server https://gitlab.com with user tgilkerson
? Which organisation do you want to use? mile-two
? Enter the new repository name:  testapp1


Creating repository mile-two/testapp1
? select the quickstart you wish to create node-http
Generated quickstart at /Users/tonygilkerson/gitlab/testapp1
### NO charts folder /Users/tonygilkerson/gitlab/testapp1/charts/node-http
Created project at /Users/tonygilkerson/gitlab/testapp1

The directory /Users/tonygilkerson/gitlab/testapp1 is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
performing pack detection in folder /Users/tonygilkerson/gitlab/testapp1
--> Draft detected JavaScript (36.530078%)
selected pack: /Users/tonygilkerson/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/javascript
replacing placeholders in directory /Users/tonygilkerson/gitlab/testapp1
app name: testapp1, git server: gitlab.com, org: mile-two, Docker registry org: mile-two
skipping directory "/Users/tonygilkerson/gitlab/testapp1/.git"
Pushed Git repository to https://gitlab.com/tgilkerson/testapp1

organisation tgilkerson detected from URL https://gitlab.com/tgilkerson/testapp1.git. '--org mile-two' will be ignored
Created Jenkins Project: http://jenkins.sbox1.<ip not shown>.nip.io/job/tgilkerson/job/testapp1/

Watch pipeline activity via:    jx get activity -f testapp1 -w
Browse the pipeline log via:    jx get build logs tgilkerson/testapp1/master
Open the Jenkins console via    jx console
You can list the pipelines via: jx get pipelines
When the pipeline is complete:  jx get applications

For more help on available commands see: https://jenkins-x.io/developing/browsing/

Note that your first pipeline may take a few minutes to start while the necessary images get downloaded!
```

### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 1.3.891
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.10.11
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [ x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

jx create cluster gke \
  --project-id $PROJECT \
  --cluster-name sbox1 \
  --default-environment-prefix sbox1 \
  --namespace sbox1 \
  --zone us-east1-b \
  --default-admin-password mypass \
  --machine-type n1-standard-2 \
  --min-num-nodes 1 \
  --max-num-nodes 5 \
  --no-default-environments \
  --preemptible=true

### Operating system / Environment

Operating System   Mac OS X 10.14.3 build 18D109

**Comment by dimmel82** [comment]
I think that to make it work the gitlab.go CreateRepository function (https://github.com/jenkins-x/jx/blob/master/pkg/gits/gitlab.go#L97:113) must also pass the **NamespaceID** argument to the **CreateProjectOptions**, as declared in https://github.com/xanzy/go-gitlab/blob/master/projects.go#L426.
The NamespaceID is the numeric id of the group, so a search by name must be performed first to get the group's id using the given "org".
As an exercise while taking my first steps in Golang I'll try to fix and test the code in a forked repo (and hopefully submit a PR), but I'm not sure I will have it any time soon.
The fix should also solve #1063.
