### ISSUE TITLE
Clone of https://github.com/jenkins-x/jenkins-x-versions fails behind a proxy

### ISSUE THREAD

**Issue by papanito** [jenkins-x/jx#3150]
### Summary 

My development machine sits behind a corporate proxy with a self-signed certificate and the installation of jx fails while cloning the Jenkins X versions repo

```powershell
error: cloning the jx versions repo: cloning "https://github.com/jenkins-x/jenkins-x-versions" repository into "C:\\Users\\xxxxx\\.jx\\jenkins-x-versions" dir: Get https://github.com/jenkins-x/jenkins-x-versions/info/refs?service=git-upload-pack: dial tcp 140.82.118.3:443: i/o timeout
```

even so the proxy settings are configured for git

```powershell
$ git config --global -l
....
http.https://github.com/.proxy=http://proxy.sc.intra:8080
ssl.backend=schannel
```

The error message is slightly different when setting the proxy on os level:
```powershell
getting latest release using HTTP redirect (getting https://github.com/jenkins-x/jx/releases/latest: Get https://github.com/jenkins-x/jx/releases/latest: proxyconnect tcp: tls: first record does not look like a TLS handshake) - using API instead
```

It is not clear what/how I have to configure jx in order to route traffic trough a proxy server and trust (or ignore) self-signed certificates

### Steps to reproduce the behavior

1. Configure git to use proxy for github

    ```
    git config --global http.https://github.com/.proxy http://proxy.sc.intra:8080
   ```
1. run `jx install`

### Expected behavior

jx installation takes the git global config into consideration for cloning from a git(hub) repo

### Actual behavior

jx cannot clone github repo cause git config is ignored

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.892
Kubernetes cluster v1.11.6
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.12.3+geecf22f
git                git version 2.17.1.windows.2
Operating System   Windows Server 2016 Standard 1607 build 14393
```

### Kubernetes cluster

On-premise cluster

### Operating system / Environment

Windows Server 2016 Standard 1607 build 1439

**Comment by ccojocar** [comment]
@papanito Are you able to access GitHub through your proxy?

**Comment by papanito** [comment]
yes, from the same machine where I use jx;
```bash
git clone https://github.com/jenkins-x/jx.git
Cloning into 'jx'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 69510 (delta 5), reused 2 (delta 1), pack-reused 69501
Receiving objects: 100% (69510/69510), 47.57 MiB | 17.25 MiB/s, done.
Resolving deltas: 100% (39880/39880), done.
Checking out files: 100% (1362/1362), done.
```
however it takes some seconds until connection is established...

**Comment by papanito** [comment]
@ccojocar I see the issue is still flagged with `priority/awaiting-more-evidence`, do you need anything else?

**Comment by ccojocar** [comment]
I think we need to configure the proxy in [go-git](https://github.com/src-d/go-git) which is used to clone this repo instead of the CLI.

**Comment by dimmel82** [comment]
@papanito Hi, I had several issues with proxy too, it worked for me with
http.https://github.com.proxy=http://myproxy:8080
Try to remove the last "/" before ". proxy"

**Comment by dimmel82** [comment]
Additionally I had to add the following for Helm to work on Windows 10,  maybe this is also required for the issue with git:
'set https_proxy=http://myproxy:8080&&set no_proxy=myexclusions&&jx install'

**Comment by papanito** [comment]
@ccojocar can you reopen it, think it is still valid
