### ISSUE TITLE
There is no out-of-date build killer for Prow with Knative

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3158]
### Summary 
There is no out-of-date build killer for Prow with Knative
When you rapid change a PR (e.g. push fixes for Hound) you end up with a job being created for each push and /test this. What Prow does if not using knative is look at the jobs running, and kill the ones that aren’t yet complete for anything but the last triggered. This code is missing for knative. This can be a problem as if (for some reason e.g slow builds) an earlier build reports later than a later build (and the status of that earlier build is different) this causes problems as the commit status is updated for the last reporting build, and so you can end up with the wrong status in tide. This is also a waste of resources.

Solution: Apply the code in prow that does this work for non-knative builds to non knative-builds

Both jenkins-x-builders & jenkins-x-serverless are using kaniko now, although image layer caching isn’t perfect - it has made an improvement.

The jx repo is the next repo that is creating the most docker images via the cluster daemon

**Comment by ccojocar** [comment]
This is merged in https://github.com/jenkins-x/test-infra and the PR sent upstream.

**Comment by ccojocar** [comment]
I am going to close it.
