### ISSUE TITLE
Do not add issuer annotation

### ISSUE THREAD

**Issue by okgolove** [jenkins-x/jx#3174]
### Summary 
I have 2 ClusterIssuers which works via DNS01 challenge. I wouldn't add any annotations related to certmanager to ingresses.

### Steps to reproduce the behavior
jx ingress update

### Expected behavior
Have an ability to skip certmanager annotations (or use ClusterIssuer instead of Issuer, or config Issuer to use DNS01 challenge)

### Actual behavior
Service has next annotations:
```
    fabric8.io/ingress.annotations: |-
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/issuer: letsencrypt-prod
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.905
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.2
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.19.1
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

MacOS X

**Comment by brokenjacobs** [comment]
This would help on prem clusters quite a bit as dns01 validation doesn’t require externally hosted services (besides dns)
