### ISSUE TITLE
Extract timeouts from BDD test code

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3183]
### Summary 

In https://github.com/jenkins-x/bdd-jx/blob/master/main.go we hardcode various timeouts - we should extract these to the `Makefile`

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by mikecirioli** [comment]
see [PR](https://github.com/jenkins-x/bdd-jx/pull/20)
