### ISSUE TITLE
support custom Jenkins servers

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#3196]
it would be great to be able to support `0..N` custom Jenkins Servers in a Jenkins X Team so that we can support a mixed set of workloads; either using the Jenkins X build packs and execution engine (a static jenkins server or serverless) and then also support optional additional Jenkins servers using the upstream Helm chart of jenkins that can be configured in any way, with any plugins to handle any kind of Jenkins pipeline.

We can then let Jenkins X orchestrate adding/removing Jenkins servers using the App extension model and using Prow to orchestrate builds and add ChatOps to all workloads whether serverless or using any jenkins server

**Comment by jstrachan** [comment]
we now have a custom Jenkins server App here: https://github.com/jenkins-x-apps/jx-app-jenkins you can install it via:

```
jx add app jx-app-jenkins

```

**Comment by ccojocar** [comment]
@jstrachan Can we close this one?

**Comment by jstrachan** [comment]
I was gonna close it once we can `jx import` projects using a `Jenkinsfile` which could then use a custom jenkins server to implement the pipeline - so I hope to close soon once I've tweaked `jx import ` a little to handle the custom jenkins use case

**Comment by jstrachan** [comment]
lets close for now - we can add more issues around improved `jx import` capability later
