### ISSUE TITLE
jx create terraform ignores --prow=false

### ISSUE THREAD

**Issue by kmadel** [jenkins-x/jx#3204]
### Summary 
When creating a cluster with `jx create terarform --prow=false` and select GKE as your target, you don't get the option to select static Jenkins instead of the default Serverless Jenkins.
### Steps to reproduce the behavior
jx create terraform --cloud-provider=gke --prow=false
### Expected behavior
You should be given the option to select static and prow should not be installed.
### Actual behavior
Serverless is automatically enabled with prow being installed.
### Jx version
1.3.925
The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.2
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.9.2
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster
GKE

### Operating system / Environment
Mac OS X

**Comment by ccojocar** [comment]
I think this a dup of #3052.
