### ISSUE TITLE
Creating GKE Cluster Ignores `--preemptible=false` flag

### ISSUE THREAD

**Issue by kmadel** [jenkins-x/jx#3205]
### Summary 
When creating a cluster with `jx create cluster gke —-prow=false --verbose --zone='us-east1-b' --preemptible=false --min-num-nodes='3' --max-num-nodes='5' --project-id='ckcd-sa-demo' --machine-type='n1-standard-4'` you are still asked if you want to use preemptible VMs or not
### Steps to reproduce the behavior
Run the following command:  `jx create cluster gke —-prow=false --verbose --zone='us-east1-b' --preemptible=false --min-num-nodes='3' --max-num-nodes='5' --project-id='ckcd-sa-demo' --machine-type='n1-standard-4'`
### Expected behavior
You shouldn't be prompted to use preemptible VMs or not.
### Actual behavior
You are still prompted.
### Jx version
1.3.925
The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.2
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.9.2
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster
GKE

### Operating system / Environment
Mac OS X

**Comment by hferentschik** [comment]
I have a patch for this. The issue is that the code does not distinguish between a default _false_ value of a flag or whether it was explicitly set to _false_. 

ATM, there is the capability missing to ask Cobra whether a given flag was explicitly provided by the user.
