### ISSUE TITLE
jx import --git-provider-url<> --url<> fails because a false organisation is detected

### ISSUE THREAD

**Issue by lpetrea** [jenkins-x/jx#3211]
### Summary 
I am trying to import a project into Jenkins X. We are using a BitBucket server at a specific URL that looks like https://company.com/BitBucketServer. The command fails because the wrong bitbuckerserver URL is detected. The detected URL is https://company.com. The command shows also that the git URL is build from project URL in a wrong manner for this case. 

### Steps to reproduce the behavior

jx import --git-provider-kind=bitbucketserver --git-provider-url=https://company.com/BitBucketServer  --org orga  --url https://company.com/BitBucketServer/scm/orga/project-test.git --verbose=true

### Expected behavior

I expect the command to run with success.

### Actual behavior

The command fails with:

Could not find a username for Git server https://company.com

The git server should be https://company.com/BitBucketServer

The command throws the following warning:

organisation BitBucketServer detected from URL https://company.com/BitBucketServer/scm/orga/project-test.git. '--org orga' will be ignored

The detection is wrong in this case.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.10.11
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.20.1
Operating System   Mac OS X 10.14.3 build 18D109

### Jenkins type

- [x ] Classic Jenkins

### Kubernetes cluster

I created the cluster with the command:

jx create cluster eks

### Operating system / Environment

Mac OS X

**Comment by abiycisco** [comment]
same issue here.

**Comment by arbe** [comment]
Same issue here. I can't import any project using bitbucketserver

**Comment by Goodsmileduck** [comment]
any news? can you turn off forcing value from parsed url instead of parameter `--org`?
In gitlab you can't import repos with subgroups: `https://gitlab.com/org/suborg/repo.git`

**Comment by zjawol** [comment]
Same issue. I can't import any projects from bitbucket server.

**Comment by ralph089** [comment]
Same issue here.
