### ISSUE TITLE
Pipeline shows failure for Go quickstart, but is Successful in log

### ISSUE THREAD

**Issue by dcanadillas** [jenkins-x/jx#3213]
### Summary 
When building a Go quickstart from scratch Pipeline log (jx logs -k) shows the pipeline succeeded, but the pipeline activity shows a failure because of an error:
```
ERROR: logging before flag.Parse: W0225 15:24:42.824075   11501 reflector.go:270] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: watch of *v1.PipelineActivity ended with: too old resource version: 15282 (15350)
```

### Steps to reproduce the behavior
1. Create a new quickstart application:
`jx create quickstart`
2. Select Go as language
3. Watch the pipeline activity with `jx get activity -f <my-app> -w`:
error is shown in 
4. What pipeline log with `jx logs -k` shows a successful build

![pipelines_fails goquickstart _20190225](https://user-images.githubusercontent.com/41782403/53346921-4e780e80-3918-11e9-9fec-30de694ed2db.png)

### Expected behavior
Pipeline should finish successfully, or at least showing same status in both logs
### Actual behavior
Pipeline is successful in pipeline log, but failed in pipelineactivities

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.3
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.20.1
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE cluster. Created with `jx create cluster gke ...`

### Operating system / Environment

Mac OS X 10.14.3 build 18D109

**Comment by kmadel** [comment]
I see the same thing with Serverless Jenkins

### Jx version
The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.2
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.9.2
Operating System   Mac OS X 10.14.2 build 18C54
```

**Comment by dcanadillas** [comment]
It happens with every build of the app, not only when creating the quickstart. I updated JX and addons and it continues to happen.

Could it be because the namespace of Prowjob and the one defined in the pipeline are different? The pipeline log is complaining about it, but at the end of the log says SUCCESS.

The prow job is creating a job with {"spec":{"namespace":"jx"}, so the pipeline activity is having the same, but the pipeline Jenkinsfile is using to do the release _(HELM_RELEASE = "$PREVIEW_NAMESPACE".toLowerCase())_ for building a different one in the case of working with a pull request for the preview environment. 

I attach the images where it can be seen.

<img width="1434" alt="screenshot 2019-03-01 at 17 18 27 prowjob" src="https://user-images.githubusercontent.com/41782403/53655711-da57a680-3c48-11e9-9256-2c8bdec24359.png">
<img width="798" alt="screenshot 2019-03-01 at 17 18 59 jenkinsfile" src="https://user-images.githubusercontent.com/41782403/53655794-260a5000-3c49-11e9-9fa0-9bad826fcbfe.png">
<img width="1438" alt="screenshot 2019-03-01 at 17 26 38 pipelineactivity" src="https://user-images.githubusercontent.com/41782403/53655714-daf03d00-3c48-11e9-8da6-8754ae75d132.png">
