### ISSUE TITLE
Mini Nexus as a Nexus replacement

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#3214]
### Summary 

Extend to the https://github.com/jenkins-x/nexus-minimal to be viable as a Nexus replacement. It can be run either as a side car container to the build or a standalone service. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
The project repository is https://github.com/jenkins-x/bucketrepo

**Comment by sdoxsee** [comment]
@ccojocar this sounds great! Nexus is a beast and [Artifactory](https://www.jfrog.com/confluence/display/RTF/System+Requirements#SystemRequirements-RecommendedHardware) doesn't seem any better. What kind of resource requirements does bucketrepo have?

**Comment by ccojocar** [comment]
Exactly is based on nexus-minimal with an extensive reworked. This is mentioned in the README. At the moment it just requires a cloud storage bucket.

**Comment by sdoxsee** [comment]
Hi @ccojocar. Is this closed because a mini nexus is no longer desired? I think it would be nice to have a mini nexus that doesn't require ~4GB RAM as a default deployment for the jenkins-x platform (https://help.sonatype.com/repomanager3/system-requirements#SystemRequirements-Memory).

**Comment by ccojocar** [comment]
We have a solution for this https://github.com/jenkins-x/bucketrepo

**Comment by sdoxsee** [comment]
Boom! That's great. Thanks @ccojocar

**Comment by sdoxsee** [comment]
@ccojocar Curious if there is integration into jx for this yet? i.e. something like `jx install --bucketrepo` when you're creating a cluster or installing the jx platform? Or an addon `jx create addon bucketrepo`?

I wouldn't expect so since it's so new. Should a new issue be created for this? Thanks!

**Comment by axsaucedo** [comment]
Thanks for the demo @sdoxsee, this looks quite interesting. @ccojocar I am also wondering, has Minio been considered for artefact management? Are there advantages of Nexus (and the bucketrepo implementation) over Minio?
