### ISSUE TITLE
migrate Jenkins X repos to next gen pipeline with Tekton

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#3225]
Right now all Jenkins X repos are being built with Jenkinsfile Runner.  Now that we have starting integrating with Tekton via the Next Gen pipeline initiative we should walk the talk and move to this new world so that we flush out issues ASAP.  

- This also means we should gain the benefits from all repos using Kaniko along with base image and layer caching which should reduce the need to recycle nodes so often and cause cancelled jobs.

- Dramatically improved pipeline times, initial spike at moving the jx repo resulted in completed builds ~ 20 mins compared with an unreliable 1hr ish.

- Move to official builder images like `docker.io/golang:1.11.5` rather than our monolith builder images, early tests also show that containers need to run with much less ram, 4GB compared with 12GB currently.  Not 100% if related but let's investigate and confirm.

- Run parallel tasks in multiple pods that could help improve build times and with autoscaling issues that @garethjevans noticed with using initcontainers.

- Currently their is some frustration with the jx, builder and serverless jenkins build in particular being unstable so this is expected to help, if not directly at least make it easier to identify problems.

Let's add sub issues for broken down tasks and link back to this one.

/priority critical-urgent
/area infrastructure
/assign rawlingsj
/assign warrenbailey
/assign garethjevans

**Comment by abayer** [comment]
Is this still incomplete?

**Comment by warrenbailey** [comment]
We've moved all the main ones now, I think we're safe to close this issue
