### ISSUE TITLE
jx get apps returns error

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#3227]
### Summary 

`jx get apps` returns the following error:

```
error: No Apps found in
```

At a minimum this is an unhelpful error.

### Steps to reproduce the behavior

Install an app, such as with `jx create spring`.

### Expected behavior

After the initial pipeline run succeeds, `jx get apps` should return a list of apps that contains the app just installed.

### Actual behavior

```
$ jx get apps
error: No Apps found in
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.932
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.12.0
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE
`jx create cluster gke`

### Operating system / Environment

```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by ccojocar** [comment]
@wbrefvem I think this is a confusion. The `get apps` command is not returning the applications created with `create spring` command. You need to run `get applications` for that. 

The `get apps` returns the apps created with the apps framework, such as these apps https://github.com/jenkins-x-apps

IMO this naming clashing it will confuse a lot of people. Naming is hard :) cc @pmuir @jstrachan

**Comment by hferentschik** [comment]
> I think this is a confusion. The get apps command is not returning the applications created with create spring command. You need to run get applications for that.

To be fair, 'apps' used to be an alias for 'application'. However, this has changed and 'apps' does now stand for Jenkins X Apps (plugins), for example, the Jacoco App - https://github.com/jenkins-x-apps/jx-app-jacoco. 

Personally, I also find this super confusing. Apps is imo an abbreviation of application, so we are trying to use the same term for two different concepts.  Assuming we want to stick to 'apps' for the Jenkins X extension mechanism, I'd suggest renaming 'applications' to 'projects'. The earlier we would do such a rename the better.

**Comment by pmuir** [comment]
We should probably just add some help text for this.
