### ISSUE TITLE
jx delete app fails

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#3228]
### Summary 

`jx delete app foo` fails to delete foo.

### Steps to reproduce the behavior

1. Create an app.
2. Try to delete it with `jx delete app [my app name]`

### Expected behavior

The app should be successfully deleted.

### Actual behavior

Nothing gets deleted, and the command returns the following error:

```
$ jx delete app foo
error: failed to run 'helm delete --purge foo' command in directory '', output: 'Error: release: "foo" not found'
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.932
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.12.0
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE
`jx create cluster gke`

### Operating system / Environment
```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by ccojocar** [comment]
See the `https://github.com/jenkins-x/jx/issues/3227`.

**Comment by pmuir** [comment]
@wbrefvem is this an app app or is this an application app? We perhaps just add some help text for this.

**Comment by deanesmith** [comment]
@wbrefvem is this still an issue?
