### ISSUE TITLE
jx upgrade ingress always deletes current certificates

### ISSUE THREAD

**Issue by ypto** [jenkins-x/jx#3229]
### Summary 
Right now, everytime the command jx upgrade ingress --cluster is executed, it will try to get new certificates and removes the current certiticates. The issue is Lets encrypt has rate limits and after 5 executions of the command, you will hit the limit, even if there aren't any changes to the ingress.

So, when you need actually to import any application by using jx import , it will create the pod and ingress and to work on https, the jx upgrade ingress needs to be executed again.

There will be no issue with this application since it's a new one, but services like jenkins, nexus, etc will fail to obtain the certificate because it will hit the rate limits.

Theres any solution to avoid getting certificates to all services or at least to keep the current certificates and only obtain for new services? 

### Steps to reproduce the behavior

jx upgrade ingress --cluster more than 5 times less than a week.

### Expected behavior

Keep the current certificates and get only for new services.

### Actual behavior

Remove all certificates for all services and get new one's.

### Jx version

jx               1.3.903

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

jx create cluster eks

### Operating system / Environment

macOS 10.13.6 (17G2208)

**Comment by ccojocar** [comment]
You can run `jx upgrade ingress --namespaces=<ns> --services=<service>` instead to fetch only the certificate of a specific service. 

The `--cluster` options regenerates the certificates within the entire cluster. Normally after you run it once the certificates should be renewed automatically by the cert-manager when they are about to expire.

**Comment by ypto** [comment]
Yes @ccojocar you are correct. Thank you.

Today, they got renewed.

Another question is, i have a service named ico on staging and cert-manager is getting a certificate for it but i have the same service with same name on production and it doesn't obtain any certificate and the cert-manager does not even try to get one. Could this be related, since the ingress for both services has the same name ('ico') ?

the only thing different is really the namespace name and the certificate that it tries to obtain has the same name as well(tls-ico).

**Comment by ccojocar** [comment]
I think, the certificates should be namespaced. Is this happening with a `ClusterIssuer` or with namespace `Issuer`?

**Comment by ypto** [comment]
Happening with namespace Issuer
