### ISSUE TITLE
we could do with some validation on the jenkins-x.yml, specifically the PipelineKind

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#3232]
I was trying a new pull request based `jenkins-x.yml` and no resources were being generated, in fact there wasn't much info at all, just dug into it and found there was a casing issue in my `jenkins-x.yml`...

I had all lowercase `pullrequest`:
```
pipelineConfig:
  pipelines:
    pullrequest:
```
but it should have been
```
pipelineConfig:
  pipelines:
    pullRequest:
```
totally my bad but wonder if we can get some validation parsing the yaml file to provider faster feedback when folks do things like me?

/area ng-pipeline
/priority important-soon
/assign ng-pipeline

**Comment by rawlingsj** [comment]
tried to add a github team but that didn't work so assigning the main folks..
/assign abayer
/assign kshultzCB
/assign dwnusbaum

**Comment by abayer** [comment]
yesssssss. We validate the "pipeline" itself, but not the rest of the `jenkins-x.yml`, and I already felt dirty about that.

**Comment by rawlingsj** [comment]
LOL - ok I had a feeling it would be on your radar already :)

**Comment by abayer** [comment]
It was! But then I forgot about it, so having an issue to track it is a Good Thing.

**Comment by rawlingsj** [comment]
@abayer FWIW I created a new `ng-pipeline` label that can be assigned to issues using `/area ng-pipeline` - rename to something that suites you (think you should have karma) and you should be able to filter issues accordingly as long as you're happy with that.

**Comment by abayer** [comment]
Cool cool - I'll see if I can think of a better name. =)

**Comment by abayer** [comment]
Actually got this done a while ago. =)
