### ISSUE TITLE
Configure Chart Museum url during install, import or CLI edit

### ISSUE THREAD

**Issue by porterja31** [jenkins-x/jx#3261]
### Summary 
We would like to be able to configure a chart repo during installation that all of our installs can point to and push/pull from during build and import

### Steps to reproduce the behavior
N/A

### Expected behavior
Configuration through install or cli to set up single source chart museum to push and pull from.

### Actual behavior
None

### Jx version

The output of `jx version` is:

```
jx                 1.3.899
jenkins x platform 0.0.3368
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.10.11
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G5019
```

### Jenkins type

- [ x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

EKS in house terraform script

**Comment by ccojocar** [comment]
@porterja31 Do you want to use an external chartmuseum service?

**Comment by porterja31** [comment]
An external service or something like S3 or other cloud provider storage that could act like a museum.
