### ISSUE TITLE
Wrong options for 'jx get apps'

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#3270]
### Summary 

The new `jx get apps` commands has unexepcted/wrong options.

### Steps to reproduce the behavior

```
$ jx get apps -h
Display installed Apps

Aliases:
Apps, app, apps
Examples:
  # List all apps
  jx get apps

  # Display details about the app called cheese
  jx get app cheese
Options:
  -o, --output='': The output format such as 'yaml'
Usage:
  jx get Apps [flags] [options]
```

There is an -o/output option. This is unexpected and also not working since even if specified the default table is displayed.

### Expected behavior

I would expect to have other options to filter and environment/namespace which aligns with the other `jx get` commands.

On a slightly different note, should there be an option to show the status of the App? @pmuir once mentioned that `get apps` should replace `helm status`, but afaict `get apps` does not contain any status information. 

Last but not least, I don't think that `apps` should be aliased to `Apps` with capital 'A'.

### Actual behavior

See above

### Jx version

The output of `jx version` is:

jx --version
1.3.948

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

**Comment by skiingandhiking** [comment]
Remove all options, and re-address

**Comment by daveconde** [comment]
The capital 'Apps' alias has been removed as it was causing a docs generation issue.

**Comment by hferentschik** [comment]
> The capital 'Apps' alias has been removed as it was causing a docs generation issue.

For once a side effect I don't mind :-)

**Comment by hferentschik** [comment]
@daveconde @dgozalo  - I just noticed a different issue. You can install the same app multiple time into different workspaces, eg:

```
$ jx add app --repository http://127.0.0.1:8879 -n sandbox -v 1.0.0-dev jx-app-jacoco
$ jx add app --repository http://127.0.0.1:8879 -n jx -v 1.0.0-dev jx-app-jacoco
```

Now when I do a `get apps`:
```
$ jx get apps
Name                  Version   Description                              Chart Repository
jx-app-jacoco         1.0.0-dev A Helm chart for the JenkinsX JaCoCo App http://127.0.0.1:8879
jx-app-test-lifecycle 0.0.2     A Helm chart for Kubernetes              http://chartmuseum.jenkins-x.io
jx-app-jacoco         1.0.0-dev A Helm chart for the JenkinsX JaCoCo App http://127.0.0.1:8879
```

Two apps, but seemingly no difference.

**Comment by hferentschik** [comment]
Also, I am not sure whether `add app` properly pass the namespace through to Helm. I can add to apps into two different namespaces and `get app` is reporting two apps, but it seems I only end up with one deployed pod. Something is fishy here.
