### ISSUE TITLE
jx doesn't promote simple app to staging as expected, can't communicate with docker

### ISSUE THREAD

**Issue by alphabettispaghetti** [jenkins-x/jx#3301]
### Summary 
When following a tutorial we cannot get jenkins x to authenticate with the internal docker registry, thus the pipeline is broken.
### Steps to reproduce the behavior
I am following this tutorial https://itnext.io/deploy-a-basic-python-application-using-jenkins-x-kubernetes-4adace2fe345 except we are running this on AWS instead of GCP, when we try to run 
```
jx import --url https://github.com/alphabettispaghetti/python-flask-docker/branches
```
our output doesn't at all match the expected output.
### Expected behavior
the web app should be promoted to staging
### Actual behavior

```
<prompt>$ jx get activity -f python-flask-docker -w
STEP                                              STARTED AGO DURATION STATUS
alphabettispaghetti/python-flask-docker/master #1       6m53s      58s Succeeded
  Credential Initializer                                6m53s       0s Succeeded
  Git Source 0                                          6m52s       2s Succeeded https://github.com/alphabettispaghetti/python-flask-docker.git
  Jenkins                                               5m55s       0s Succeeded
```

looking at our fork of the repo, we see that Jenkins has created another branch called `gh-pages` and wrote a log:
```

    
Step: build-step-credential-initializer:

Unable to retrieve container logs for docker://61ecd51f843ed1b42319a4f88e4ea5c83f9847f00d68b7c54c2ee1a0036203d3
Step: build-step-git-source-0:

Unable to retrieve container logs for docker://637940f013c4d245164af6dcc4a60cdb182e705d0074cbeb066f4ad879341a94
Step: build-step-jenkins:

Unable to retrieve container logs for docker://e00b5b6b5720c70235c8f407808a457c97cf46ebf755ebd65e5d6f26013de86a
```

### Jx version

The output of `jx version` is:

```
jx                 1.3.956
jenkins x platform 0.0.3513
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.10.11
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.19.1
Operating System   Mac OS X 10.14 build 18A391
```

### Jenkins type

- [ ] Classic Jenkins
- [ X] Serverless Jenkins

### Kubernetes cluster

created using jx create cluster aws

### Operating system / Environment

MacOS Mojave 10.14.3

**Comment by jstrachan** [comment]
I wonder if one of the quickstarts work for you? BTW we should default to using ECR if you use `jx create cluster aws`
