### ISSUE TITLE
Feature request: automate passing options to jx create cluster <providor>

### ISSUE THREAD

**Issue by alphabettispaghetti** [jenkins-x/jx#3302]
I would like to raise all infrastructure in a 1 click fashion.

When I run 
```
jx create cluster <providor>
```
I am prompted for options that I cannot (or at least do not know how to) specify with a flag as described in `https://jenkins-x.io/commands/jx_create_cluster_aws/` (I'm currently using AWS). As a result I am unsure how to run this command in an automated fashion.

**Comment by ccojocar** [comment]
@alphabettispaghetti You can run the command in batch mode. This is an example for GKE:

```
jx create cluster gke -m n1-standard-2 --min-num-nodes=3 --max-num-nodes=5 -z europe-west1-b --skip-login  --default-admin-password=<ADMIN_PASS> --project-id projectId  --git-username <USER> --git-api-token <TOKEN>  -b
```

**Comment by alphabettispaghetti** [comment]
thank you very much @ccojocar :)
