### ISSUE TITLE
Tekton based environment does not work with private repository

### ISSUE THREAD

**Issue by noni73** [jenkins-x/jx#3307]
### Summary 

error: pulling environment repo https://github.com/<org>/<environment_repo>.git into /builder/home/.jx/environments: failed to fork GitHub repo <org>/<environment_repo> to user <user>: Failed to fork repository <org>/<environment_repo> due to: POST https://api.github.com/repos/<org>/<environment_repo>/forks: 403 The repository exists, but forking is disabled. []

### Steps to reproduce the behavior

Create a tekton based repository with git-private option enabled

### Expected behavior

jx start build should complete without errors.

### Actual behavior

The build does not work and the error from summary is seen in the logs of container "build-step-promote-jx-promote"

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.965
jenkins x platform 0.0.3515
Kubernetes cluster v1.12.6
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [X] Serverless Jenkins

### Kubernetes cluster

azure aks

### Operating system / Environment

Operating System   Mac OS X 10.14.3 build 18D109

I have changed the git repo to public. Then it works correct.
If the git repo is private you cannot allow forking.

**Comment by rawlingsj** [comment]
Does the pipeline user you have in cluster definitely have access to that repo?  
Tip: to decode secrets easily we tend to use [ksd](https://github.com/ashleyschuett/kubernetes-secret-decode#installation)
I.e. if you run..
```
kubectl get secrets knative-git-user-pass -oyaml | ksd
```
then using that user and github personal access token try to query the repo using the REST API...
```
curl -u $USER:$PASS https://api.github.com/repos/$OWNER/$REPO
```

**Comment by noni73** [comment]
The user has access to the repository. I found the option to enable fork for the organisation.
Forking was not needed for knative builds. Is this a new requirement?
