### ISSUE TITLE
Jenkins static master fails to load k8s secrets

### ISSUE THREAD

**Issue by EamonKeane** [jenkins-x/jx#3308]
### Summary 
After upgrading/restarting a kubernetes node which contains the static jenkins-x master, the restarted jenkins-x master does not load the secrets from kubernetes. This leads to webhooks not being received from github and the platform not functioning. This is resolved by restarting the jenkins-x master (deleting the pod and the deployment recreates it).

### Steps to reproduce the behavior
On GKE apply an upgrade the the relevant worker node pool. Navigate to `Administration > Credentials` and observe that `jx-pipeline-git-github-github` and `jenkins-x-chartmuseum` secrets are not visible. By tailing the logs of the jenkins-x master, the following error is visible:

```
Feb 05, 2019 11:18:32 AM com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider startWatchingForSecrets
SEVERE: Failed to initialise k8s secret provider, secrets from Kubernetes will not be available
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Secret]  with name: [null]  in namespace: [jx]  failed.
    at 
```

### Expected behavior
Secrets are available.

### Actual behavior
Secrets are not there leading to jenkins-x failing for end users to start pipelines.

### Jx version

The output of `jx version` is:

```
jx                 1.3.956
Kubernetes cluster v1.12.5-gke.5
kubectl            v1.12.2
helm client        v2.13.0+g79d0794
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.4 build 18E205e
```

### Jenkins type

- [x ] Classic Jenkins

### Kubernetes cluster

GKE manually created.

### Operating system / Environment

Mac OS

**Comment by Yiadh** [comment]
any news regarding this issue. I am facing it also.
