### ISSUE TITLE
Could jx pipeline.go embed Tekton step resource types?

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#3312]
In prow land they embed a `podspec`, `buildspec`,`pipelinerunspec` into their [prowjob types](https://github.com/kubernetes/test-infra/blob/e69c335/prow/config/jobs.go#L104-L106).  Which means it’s super easy to add resources, limits anything from a pod spec.   

I wondered if we could do the same for Pipeline?  I.e use a Tekton `stepspec` rather than duplicating the types as we’re missing resources, env vars etc.  Right now The syntax half feels like a Tekton step but it’s not, kinda feels a little confusing? https://github.com/jenkins-x/jx/blob/9d0b23c/pkg/tekton/syntax/pipeline.go#L125

/area ng-pipeline

**Comment by abayer** [comment]
So my thinking here is that at least for now, we'll add our own `stepspec` type in our syntax, which we can then translate into an actual `Container` behind the scenes. Does that sound reasonable?
