### ISSUE TITLE
Use PATCH over UPDATE when updating CRs

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#3314]
Instead of using the `Update` method for the various generated clientset interfaces, we should use the `Patch` approach, specifying a JSON path over updating the whole CR.
This approach reduces the amount of data sent over the wire and it should reduce the number of conflicts when trying to update.

**Comment by jglick** [comment]
Should also avoid data-loss bugs caused by extant CRs using schemas slightly different than what the `jx` command‘s `struct`s were expecting.

**Comment by hferentschik** [comment]
> using schemas slightly different than what the jx command‘s structs were expecting.

what exactly do you mean with that?
