### ISSUE TITLE
`jx get build logs` performance degrades, perhaps with growing pipelineruns

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#3316]
Running `jx get build logs` just took 18 seconds to return a list to pick from.  It could be related to `pipelineruns` as it's been getting worse all day.  I currently have 62 pipelinerun resources.

/area tekton
/priority important-soon

**Comment by abayer** [comment]
I'm entirely willing to bet that my logic (particularly in `pipeline_info.go`) is...less than optimal. =)

**Comment by abayer** [comment]
Yeah, it's listing pods way too much. Trying an experiment to see if I can drop that.

**Comment by abayer** [comment]
Still more work to go - got down from ~20 seconds with 26 `PipelineRun`s with their `Pod`s still around to ~11 seconds, but that needs to be improved. =)

**Comment by rawlingsj** [comment]
ah great - it's going the right way :)

**Comment by abayer** [comment]
Basically, there are a lot of redundant list calls for various things, so I'm figuring out how to avoid that.

**Comment by abayer** [comment]
How would you like ~1s? 'cos I just got there. I'll clean it up and open a PR after I get dinner. =)
