### ISSUE TITLE
Steps to intigrate the jenkins with knative build on eks cluster using kubernaties

### ISSUE THREAD

**Issue by kirangavali** [jenkins-x/jx#3324]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

**Comment by kirangavali** [comment]
Steps to intigrate the jenkins with knative build on eks cluster using kubernaties

Please any one can help to  install Steps to intigrate the jenkins with knative build on eks cluster using kubernaties

**Comment by ccojocar** [comment]
@kirangavali Please could you provide more details which describe your request? You can retrieve the build logs with `jx get build logs`.
