### ISSUE TITLE
Support for Alibaba Cloud

### ISSUE THREAD

**Issue by zeusro** [jenkins-x/jx#3326]
### Summary 

Alibaba Cloud is the biggest Cloud in China.

But there is no option in jx create cluster,which meams Jenkins X does not support Alibaba Cloud natively.

### Expected behavior

`create cluster` supports aliyun.

### Actual behavior

Doesn't support.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.971
Kubernetes cluster v1.11.5
kubectl            v1.13.4
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.14.3 (Apple Git-98)
Operating System   Mac OS X 10.13.6 build 17G65
```

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

Aliyun

### Operating system / Environment

Mac OS X 10.13.6 build 17G65

**Comment by ccojocar** [comment]
@zeusro We are willing to accept contributions for this. Thanks

**Comment by carlossg** [comment]
see https://github.com/jenkins-x/jenkins-x-platform/issues/5551 and https://jenkins-x.io/news/alibaba-container-service-jenkins-x/

**Comment by carlossg** [comment]
@zeusro from my short experience, even getting JX to run in the Alibaba China region you would need the ICP Filing to access the services in the cluster

**Comment by zeusro** [comment]
@carlossg  You are so sweet!Thx a lot.I move the docker images to my local registry to solve the problem temporarily.But it would be better if you move those docker images to  Dockerhub.

Unlike gcr.io,we can access the Dockerhub by our Chinese proxy service.

BTW,the ICP License is easy to get for normal China company,it just need to take some times.
