### ISSUE TITLE
Test compilation taking too long to compile

### ISSUE THREAD

**Issue by joseronierison** [jenkins-x/jx#3332]
### Summary 
The application is taking to long (more than an hour and sometime it breaks) to run compile the unit test using scala/sbt.

I have disabled the parallel execution, anyway when I took a look on the pod resource usage it was on the limit of CPU the the pod (I think is this one configured on the folder https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/tree/master/packs/scala)

There is a wait to setup a custom Pod with a custom CPU resource?

### Steps to reproduce the behavior

Run pipeline with sbt unit test.

### Jx version

The output of `jx version` is: 1.3.971

It get stuck in the following log:
```
[info] Compiling 63 Scala sources and 2 Java sources to /home/jenkins/workspace/****_master/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.11. Compiling...
[info]   Compilation completed in 36.016 s
[info] Compiling 22 Scala sources to /home/jenkins/workspace/****_master/target/scala-2.11/test-classes...
```

### Jenkins type
- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
GKE

**Comment by ccojocar** [comment]
@joseronierison Are you using the Scala build template? You can find more details here how to customise the build template for classic Jenkins https://jenkins-x.io/getting-started/create-custom-builder/.

Do you need more help? Thanks

**Comment by joseronierison** [comment]
Hi @ccojocar 
yes, I am using the scala build template that came with the default installation of jenkins-x.

I will try this out and let you know if it worked.

Thanks
