### ISSUE TITLE
use GitLab with jenkins-x problem

### ISSUE THREAD

**Issue by ouyangshixiong** [jenkins-x/jx#3338]
### Summary 
use  jx create quickstart --git-provider-url='http://gitlab.datangliang.com' --git-host='gitlab.datangliang.com' --git-provider-kind='gitlab' --git-username='jenkins-x-127'
created  project(quickstart3) didn't create right git url as github does.

### Steps to reproduce the behavior
jx create git server gitlab http://gitlab.datangliang.com/
jx create git token -n gitlab jenkins-x-127
jx create quickstart --git-provider-url='http://gitlab.datangliang.com' --git-host='gitlab.datangliang.com' --git-provider-kind='gitlab' --git-username='jenkins-x-127'
 cd quickstart3/
git remote -v

### Expected behavior
show the correct gitlab project url such as: http://gitlab.datangliang.com/jenkins-x-127/quickstart3.git

### Actual behavior
origin  http://jenkins-x-127:personalaccesstoken@gitlab.example.com/jenkins-x-127/quickstart3.git (fetch)
origin  http://jenkins-x-127:personalaccesstoken@gitlab.example.com/jenkins-x-127/quickstart3.git (push)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.971
jenkins x platform 0.0.3515
Kubernetes cluster v1.13.0
kubectl            v1.13.3
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)

```

### Jenkins type

 Classic Jenkins

### Kubernetes cluster

premise Kubernetes cluster ( created by kubeadm )
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

### Operating system / Environment

CentOS7  
company's preinstalled gitlab software(standalone).

**Comment by erSitzt** [comment]
I use the same version of jx with GitLab and with this command

`jx create quickstart --verbose true --git-host https://srv-git.zentrale.domain.de --git-provider-kind gitlab --git-provider-url https://srv-git.zentrale.domain.de`

i get

```
origin  https://buehring:mCmTMixdr-MyZ7Xvua1r@srv-git.zentrale.domain.de/buehring/quickstart3.git (fetch)
origin  https://buehring:mCmTMixdr-MyZ7Xvua1r@srv-git.zentrale.domain.de/buehring/quickstart3.git (push)
```

can you list list all of your git servers with `jx get git server` ?

**Comment by ouyangshixiong** [comment]
@erSitzt  I think we are facing the same issue. my kubernetes cluster come out the same problem as yours.

**Comment by erSitzt** [comment]
No i meant its working correctly with my setup using the same version of jx

**Comment by ouyangshixiong** [comment]
@erSitzt you mean this kind of urls is correct?  Ok.
Is your webhook in gitlab work correctly? Or should I config something for gitlab in my jenkins-x

**Comment by erSitzt** [comment]
Are you talking about your remotes or about webhooks ? you example is only listing your remote git repo, not any webhooks.

in your example your domains differ, thats why i asked you to post your output of the `jx get git server` command. But you still havent shared this...

**Comment by ouyangshixiong** [comment]
@erSitzt  Thank you very much for your reply.   
The command line output is this:
[root@activiti7-master ~]# jx get git server
Name   Kind   URL
GitHub github https://github.com
github http://gitlab.datangliang.com/

I had doing more learning  on JenkinsX with GitLab, 
For examle, just install jx using this:
jx install --git-provider-url='http://gitlab.datangliang.com/' --provider=kubernetes  --external-ip=192.168.1.127 --domain=192.168.1.127.nip.io --no-default-environments --verbose=true --git-username jenkins-x-127 --git-api-token tokenstring
I was trying to pass more parameters on jx initialization. I hope it might works. 
After a sucessful installation, I just want to import a project into jenkins X. I got this error:
[root@activiti7-master bp3]# jx import
? Which Git service do you wish to use http://gitlab.datangliang.com/
No username defined for the current Git server!
? Do you wish to use jenkins-x-127 as the Git user name: Yes
**error: no Git service resource found with URL 'http://gitlab.datangliang.com/' in namespace jx**
So I wonder if it is possible to install jenkins x on company's inner network with company's gitlab.
Or It's beter to use ngork（or some software like it）  to proxy github webhook to my k8s cluster?
Pls give me some suggestion, Thank you.
