### ISSUE TITLE
jx should not keep asking the user which user they want to use for git

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#334]
once we have setup a default user name for a git repo; we should probably just accept it for operations that perform git operations (like `jx create spring / jx import / jx create issue`).

Maybe we need to ask the user if we want to set the `defaultUser` and use it for the future by default?

**Comment by tdcox** [comment]
From a customer perspective, I still feel that it's not clear what all these user accounts relate to. Under what circumstances might someone want to use different accounts and which systems do those accounts relate to?

**Comment by jstrachan** [comment]
usually a user uses their own github account when doing commits & PRs for example. Once setup you rarely ever change it or have to specify it again. In your IDE you never switch users or keep getting asked what user you wanna do commits as.

However jx is using the same set of git auth config for installing jenkins x (e.g. using a `cd user` for installing jenkins, doing releases & updatebot PRs) as when creating/importing projects.

So we kinda need a way, when doing 'user things' rather than 'installing jenkins x' of letting the user specify if a particular github user is their default user for that service (e.g. github) - then defaulting to that from then on until the user changes it (which they typically would never do)

**Comment by tdcox** [comment]
My point was trying to suggest that at the moment we aren't clearly explaining that model to the user which is leading to some odd behaviours like people typing random stuff in like the Jenkins admin account...

**Comment by jstrachan** [comment]
agreed! 

we should probably have a separate set of files / credentials used to 'install jenkins x' from those used when using it. Though I guess some users may wanna share the same user id...

**Comment by jstrachan** [comment]
@suhancz coud you raise a separate issue please - that sounds like the CLI argument processing of `jx import` is not correctly reusing the provided username

**Comment by suhancz** [comment]
Thenks @jstrachan , I opened https://github.com/jenkins-x/jx/issues/2802 for that issue

**Comment by ssathi** [comment]
This is exactly what I need right now. I'm trying to automate jx import whenever we add a new micro-service. I'm adding a new arg 'use-default-git' to skip user prompt. Is that acceptable? 

This is my requirement:
I have a monorepo having many micro services. I need jenkins to run jx import when a new service added (with a pattern like 'b2m-service-*').

**Comment by jstrachan** [comment]
@ssathi yeah adding a `--use-default-git` flag sounds good to me.

BTW I'm not sure how the import-per-microservice would work with Jenkins X - right now a pipeline runs in a repo on commit so it only needs importing once

**Comment by ssathi** [comment]
@jstrachan 

We have a mono repo with many micro services. We first run jx step split then, run jx import for each micro service.

I will write a test for this and create a pull request.
