### ISSUE TITLE
jx create cluster gke --skip-login fails

### ISSUE THREAD

**Issue by stevef1uk** [jenkins-x/jx#3340]
### Summary 
Tied the command: jx create cluster gke --skip-login

### Steps to reproduce the behavior
Created a new cluster with bigger instances than the default & 4 nodes
Kaniko selected
Said yes to install Ingress controller
### Expected behavior
A successful installation
### Actual behavior
Installing Chart 'install --wait --name jxing --namespace kube-system stable/nginx-ingress --version 1.3.1 --set rbac.create=true'
Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --version 1.3.1 --set rbac.create=true' command in directory '', output: 'Error: failed to download "stable/nginx-ingress"'
ingress init failed: deployments.apps "jxing-nginx-ingress-controller" not found
error creating cluster initializing the Jenkins X platform: initializing the Jenkins X platform: deployments.apps "jxing-nginx-ingress-controller" not found

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 1.3.974
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.4
helm client        v2.8.2+ga802316
helm server        v2.8.2+ga802316
git                git version 2.17.1
Operating System   Mac OS X 10.14.3 build 18D109

### Jenkins type
The default

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
GKE & let jx create from scratch with 4 nodes & each with 4 vCPUs

### Operating system / Environment

Mac Os
Darwin Stevens-iMac.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Comment by ccojocar** [comment]
@stevef1uk It seems that it fails to install the ingress controller? Can you provider some logs and the state of the PODs for ingress controller?

Can you install ingress controller manually?

**Comment by stevef1uk** [comment]
Sorry, my free period has ended so I can't do this. I sort of expected it to work OOTB.
