### ISSUE TITLE
Pipeline extensibility for Tekton

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3342]
Currently there are some ways to extend pipeline e.g. you can put a pipeline definition in a build pack but there is no way to provide any intermediate configuration. This is also not consistent with the other ways we do extensibility which is via CRDs

Acceptance Criteria:

* Consistent with the rest of the JX extensibility
* Blocks pipeline execution until all extensions are applied.

**Comment by hferentschik** [comment]
The current idea is to create a meta pipeline prior to the actual build pipeline. This meta pipeline gets also the source code injected and is then able to contribute to the pipeline by modifying the pipeline config (`jenkins-x.yml`) or any other file of the project (eg a `pom.xml`).

Once the meta pipeline is built and executed, the actual build pipeline is created and executed. 

Apps can "register" themselves as wanting to contribute/modify the pipeline. They do that via a label, eg:

```yaml
  labels:
    jenkins.io/app-name: jx-app-acme
    jenkins.io/app-type: pipeline-extension
``` 

When the meta pipeline is built, all Apps with app-type  pipeline-extension are discovered. Each of this apps needs to have a `PipelineExtension` defined in their App CRD:

```go
type PipelineExtension struct {
	// Name of the container specified as a DNS_LABEL.
	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
	// Docker image name.
	Image string `json:"image,omitempty" protobuf:"bytes,2,opt,name=image"`
	// Entrypoint array. Not executed within a shell.
	Command string `json:"command,omitempty" protobuf:"bytes,3,rep,name=command"`
	// Arguments to the entrypoint.
	Args []string `json:"args,omitempty" protobuf:"bytes,4,rep,name=args"`
}
```

`PipelineExtension` contains all the information needed to build a Tekton task to be executed as part of the meta pipeline. 

In a first version, there is no order in which the Apps get executed, but as a next step we could add a order/priority label as well.

Another idea which needs to be discussed further is to commit the changes each Apps makes to the config/source. This could either be done by the App itself or by the controller building the meta pipeline. TBD.

**Comment by hferentschik** [comment]
Related pull requests:

- #4004 
- #4051

**Comment by hferentschik** [comment]
The first step in the metapipeline would be the generation of a canonical/effective `jenkins-x.yml`. This would be achieved by calling `jx step syntax canonical` (see pull request #4135) which generates something like `jenkins-x-<context>-canonical.yml`. Apps wanting to extend/modify the pipeline need to edit this canonical configuration. See also https://github.com/jenkins-x/jx/pull/4135#discussion_r292778627

**Comment by hferentschik** [comment]
Followed up by issues:

- #4448
