### ISSUE TITLE
Binary jx missing on github

### ISSUE THREAD

**Issue by tre7roja** [jenkins-x/jx#3356]
### Summary 
The binary below is missing:
https://github.com/jenkins-x/jx/releases/download/v1.3.979/jx-linux-amd64.tar.gz
### Steps to reproduce the behavior
curl -L https://github.com/jenkins-x/jx/releases/download/v1.3.979/jx-linux-amd64.tar.gz
### Expected behavior
Download
### Actual behavior
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>116400734/94213d80-4746-11e9-8c45-7664a9391320</Key><RequestId>0FC822A0C7634339</RequestId><HostId>aYzXt0bcO7ve3NM0PWSRNjsUvf6tLH9C8FUg6y+H+DyuywNK5qZKFmEqjPMH19ecHtL1WwWvKCw=</HostId></Error>
### Jx version

The output of `jx version` is:

```
v1.3.979
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@tre7roja Please try to use the lastest binary version https://github.com/jenkins-x/jx/releases/download/v1.3.980/jx-linux-amd64.tar.gz. 

I think there were some glitches when we were switching the `jx` repository to `tekton` pipeline. 

I am going to close this issue for now. Thanks for reporting.
