### ISSUE TITLE
tekton cluster not showing all pipelines

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#3358]
### Summary 

the Core UI and `jx get pipelines` is not returning the fill list of pipelines configured in the tekton cluster

### Steps to reproduce the behavior

run `jx get pipelines`

### Expected behavior

results shows all pipelines that are configured in the cluster

### Actual behavior

many are missing.

e.g.

```
 ☸ jx-cluster-cgzqdg5vcmqsbmdpdgh1yg-ctx:jx C:\Users\jnord>jx get pipelines
Name                                     URL LAST_BUILD STATUS DURATION
jenkins-x/jenkins-x-builders-base/master N/A N/A        N/A    N/A
jenkins-x/jenkins-x-builders/master      N/A N/A        N/A    N/A
jenkins-x/jenkins-x-serverless/master    N/A N/A        N/A    N/A
 ☸ jx-cluster-cgzqdg5vcmqsbmdpdgh1yg-ctx:jx C:\Users\jnord>
```

shows only 3 projects, yet...

```
 ☸ jx-cluster-cgzqdg5vcmqsbmdpdgh1yg-ctx:jx C:\Users\jnord>jx get build logs --repo=jenkins-x-versions
? Which build do you want to view the logs of?:   [Use arrows to move, type to filter]
> jenkins-x/jenkins-x-versions/PR-100 #8
  jenkins-x/jenkins-x-versions/PR-103 #13
  jenkins-x/jenkins-x-versions/PR-103 #12
  jenkins-x/jenkins-x-versions/PR-103 #11
  jenkins-x/jenkins-x-versions/PR-103 #10
  jenkins-x/jenkins-x-versions/PR-103 #9
  jenkins-x/jenkins-x-versions/PR-104 #14
```

shows that there are other pipelines that the system knows about.

the same is shown via the GUI (only 3 projects are shown)

### Jx version

The output of `jx version` is:

```
 ☸ jx-cluster-cgzqdg5vcmqsbmdpdgh1yg-ctx:jx C:\Users\jnord>jx version
NAME               VERSION
jx                 [32m1.3.967[0m
Kubernetes cluster [32mv1.11.7-gke.4[0m
kubectl            [32mv1.13.0[0m
helm client        [32mClient: v2.11.0+g2e55dbe[0m
git                [32mgit version 2.16.2.windows.1[0m
Operating System   [32mWindows 10 Pro 1809 build 17763[0m

A new jx version is available: 1.3.980
? Would you like to upgrade to the new jx version? No

```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

This is the (temproary) Tekton cluster set yup by @rawlingsj 

### Operating system / Environment

Windows

**Comment by amuniz** [comment]
Is this tekton specific? I think `jenkins-x/jenkins-x-versions` is not showing up in `jx get pipelines` because there is no _release_ pipeline for it, so there is no pipeline to trigger on it.
