### ISSUE TITLE
NG Pipeline support secretKeyRef

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#3366]
### Summary 
It would be great if we could support secretKeyRef in the jenkins-x.yml.

I'm trying to convert the jenkins-x-charts repositories over to tekton pipelines but at the minute I can't easily mimic the behaviour of secretKeyRef from the knative build templates i.e.:
https://github.com/jenkins-x-charts/jx-build-templates/blob/8337686e405b74be8587a2e21a9b36ead1543d55/jx-build-templates/templates/knative-chart-release-buildtemplate.yaml#L40

### Expected behavior
N/A 

### Actual behavior
N/A

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by abayer** [comment]
This is actually closed by #3421 but didn't get linked properly.
