### ISSUE TITLE
jx version in builder images out of date

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#3367]
jx version in the `builder-`foo images is old, pretty sure this is down to the moving of repos, pipelines and infra to Tekton.  

I'm working on fixing.

/priority critical-urgent
/assing rawlingsj

**Comment by polothy** [comment]
hey @rawlingsj, noticed there is a new JX Platform version that might be using JX 1.3.998.  You think this has all been sorted out now?

**Comment by abayer** [comment]
This was fixed a while back.
