### ISSUE TITLE
Preview Builds when commit is from a bot

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#3369]
### Summary 

Github Apps are able to create commits and PRs using a user with a [bot] label.

The Jenkins Preview Build chokes when it comes across the `[`s in the username as it doesn't match the current regex.

I suspect over time there will be more bot users, and also fear that merging this PR will cause problems for all PRs going forward if it scans history.

### Steps to reproduce the behavior

Add Renovate Bot (https://renovatebot.com/) to a Node.js repo, which will make a PR to update dependencies using the bot user

### Expected behavior

The PR is built and tested per usual

### Actual behavior

Error:
```
+ jx preview --app xxx --dir ../..

Creating a preview

Commit author email is empty for: 6a2e7e019ad69b9a497068c8581e1de567e6f77e

Looking for commits in: /home/jenkins/workspace/xxx_xxx_PR-10/

error: unable to parse requirement: invalid label value: "renovate[bot]": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

script returned exit code 1
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.933
jenkins x platform 0.0.3402
Kubernetes cluster v1.10.13-eks-g484b8
kubectl            v1.13.2
helm client        Client: v2.13.0+g79d0794
git                git version 2.19.1
Operating System   Mac OS X 10.14.1 build 18B75
```

### Jenkins type

- [x] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

EKS - `jx create cluster eks`

also seeing on GKE created via terraform

Happens in classic and serverless

### Operating system / Environment

MacOS

**Comment by patrickleet** [comment]
Tracking this down a bit... seems to be happening in this `Resolve` function
![image](https://user-images.githubusercontent.com/474827/54713559-4c732b00-4b25-11e9-8532-1f27b73fe460.png)

**Comment by ccojocar** [comment]
@patrickleet I think the expected username should be alphanumerical. We may be able to extend this function to parse users which contains special characters.

**Comment by patrickleet** [comment]
yea - seems like bots can have square brackets on GitHub now: `renovate[bot]`. Updating the regex, or even just replacing them with _ or something before it compares should get it working.

**Comment by desmondhume** [comment]
I'm seeing the same when using [Dependabot](https://dependabot.com/). Has there been any progress on this issue? Thanks for your work!

**Comment by marissa-halpert** [comment]
Hello! We are seeing the same problem with Dependabot. Was wondering if there has been any progress? Thank you!

**Comment by galtzo** [comment]
This is blocking simultaneous use of @jenkins-x and @dependabot & @renovatebot & any other GitHub bot-based automation.

**Comment by patrickleet** [comment]
I'd argue that this seems more like a bug than an enhancement to me.

Thanks for all the work on the project! I appreciate all of the devs and maintainers!

**Comment by deanesmith** [comment]
Will need to further investigate the optimal solution.  Suggestion to base64 encode the string.

**Comment by patrickleet** [comment]
any workarounds for this yet?

**Comment by patrickleet** [comment]
After speaking with renovate bot creator, he pointed out that the commit is from `renovate-bot` and the PR's author is `renovate[bot]`. 

I assumed it was the commit that it was getting hung up on but it actually appears to be the PR Author.

**Comment by deanesmith** [comment]
@patrickleet not yet.  I bumped up the priority accordingly since this is becoming more prevalent.

**Comment by patrickleet** [comment]
The PR that was merged mentions that it fixes this issue - I haven't tested it out yet though, can anyone confirm?

**Comment by deanesmith** [comment]
@marissa-halpert , @desmondhume, @galtzo, would any of you be able to confirm.  We do not have functional testing that includes this specific case.  Any help would be greatly appreciated.

**Comment by daveconde** [comment]
@mrageh If you had a bit of time to validate this it would be awesome
