### ISSUE TITLE
add a CLI command to create a branch for an issue?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#337]
I wonder if we should have a CLI command to automate creating a new branch from `master` (by default) using the number/name of a current pending issue on a project? So that when the work is committed or submitted as a PR automatically associates with the issue?

Maybe IDEs are better at this kinda stuff though.

I guess we would need to wait for a commit that marks the issue as fixed anyway; in which case not sure there's a need for this command?

**Comment by ccojocar** [comment]
These issue seems a bit out of scope. It is possible to use the IDE or CLI tools provided by the issue tracker to automate this branch creation.
