### ISSUE TITLE
`jx get build logs` not returning master branch pipelines anymore

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#3370]
jx 1.3.980

I just upgraded to the latest jx (unfortunately I don't know the version I was on before) and I'm now not seeing master branch pipelines returned in the list to choose.  I only see PR related pipelines.

Think it may be a regression?

**Comment by rawlingsj** [comment]
@abayer not sure if you've seen anything around this lately?

**Comment by abayer** [comment]
I've never actually done anything involving master branch pipelines, so I'm not sure. Presumably this is related, but I don't know how to reproduce it.
