### ISSUE TITLE
Bitbucket cloud org error in promote

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3374]
### Summary 
Promote command fails to merge PR

### Steps to reproduce the behavior
Import a bitbucket cloud repository from a team. Promote it using jx.

### Expected behavior
PR should be merged

### Actual behavior
Merge PR fails with error:

`error: Status: 400 Bad Request, Body: {“type”: “error”, “error”: {“fields”: {“source”: [“branch not found: jenkins-x-bot:promote-deadpool-0.0.93"]}, “message”: “source: branch not found: jenkins-x-bot:promote-deadpool-0.0.93"}}`

Looks like jx is trying to find the branch under the user and not under the gitOwner.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.980
jenkins x platform 0.0.3553
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.4
helm client        Client: v2.13.0+g79d0794
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE. Created manually

### Operating system / Environment

MacOS X 10.14.3

**Comment by skyionblue** [comment]
I am experiencing the same issue, 

Hey Guys… I have been fighting this error or going on a month now… anyone have any advice?

Promoting app dashboard version 1.0.13 to namespace jx-staging
error: Status: 404 , Body: {“errors”:[{“context”:null,“message”:“Repository \“env-beta-os-staging\” of project with key \“GDO\” has no branch \“PIDJENKINSKSBOTT:promote-dashboard-1.0.13\“”,“exceptionName”:“com.atlassian.bitbucket.commit.NoSuchCommitException”}]}
24 replies

James Rawlings   [3 hours ago]
hmm I’m not familiar with the bitbucket provider, I wonder if @wbrefvem has an idea?

James Celli   [1 hour ago]
Its supposed to be a bitbucketserver… We host it in house…

wbrefvem   [1 hour ago]
okay, so a couple of questions:
1. what do you get from `jx version`?
2. what version of Bitbucket Server are you using?
3. what steps do you take that produce this error?

James Celli   [1 hour ago]
jx version 0.0.3555
Atlassian Bitbucket v5.9.1
I have created bash scripts to do the install, and I have let it create the default ENVs, I have also deleted the ENVs, and re-created them both ended up with the same error listed above

James Celli   [1 hour ago]
Supposedly https://github.com/jenkins-x/jx/issues/3292 was going to resolve this issue…
yyolk
#3292 jx promote always tries to fork and fails
*Summary*

after upgrading our version of jx - we get:

```$ jx promote --version 0.0.5 --env production
Promoting app roof-slope-vision-api version 0.0.5 to namespace jx-production
pipeline arturo-ai/roof-slope-vision-api/master
error: pulling environment repo https://github.com/arturo-ai/environment-prod-arturo-ai-production.git into /Users/joshtrotter/.jx/environments: failed to fork GitHub repo arturo-ai/environment-prod-arturo-ai-production to user arturo-bot: Failed to fork repository arturo-ai/environment-prod-arturo-ai-production due to: POST https://api.github.com/repos/arturo-ai/environment-prod-arturo-ai-production/forks: 403 The repository exists, but forking is disabled. []```

 Show more
Labels
area/promote, kind/bug, priority/backlog
Comments
4
jenkins-x/jxMar 6thAdded by GitHub

James Celli   [44 minutes ago]
From what I can see, and I could be wrong but bitbucketserver URLs are different than github URLs… in that:

github.com/owner/repo
stash.xactware.com/scm/owner/repo

and when I import my Java project it says that the ORG I set in the ENV is going to be ignored as one was found in the URL…

James Celli   [44 minutes ago]
If that makes sense

wbrefvem   [42 minutes ago]
could you paste the full output of `jx version`? thanks

James Celli   [42 minutes ago]
Sure….

James Celli   [36 minutes ago]
NAME               VERSION
jx                 1.3.992
Kubernetes cluster v1.12.0
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G5019

wbrefvem   [28 minutes ago]
is the repo a private repo?

James Celli   [25 minutes ago]
I am going to say yes….

James Celli   [25 minutes ago]
all of the repos we have are only accessible from our network… and the public accessible option is disabled…

James Celli   [24 minutes ago]
When I create the ENV, this is the command I use:

jx create env \
 -n production \
 -l “Online Services Production” \
 --env-job-credentials=“stash-pidjenkins-k8s-bott-auth” \
 --domain=“geomnidev.net” \
 --namespace=“jx-production” \
 --git-owner=“GDO” \
 --git-api-token=‘REMOVED’ \
 --git-private \
 --git-provider-url=“https://stash.xactware.com/” \
 --git-provider-kind=“bitbucketserver” \
 --git-username=“PIDJENKINSKSBOTT” \
 --git-ref=“master” \
 --order=“200" \
 --prefix=“beta-os” \
 --promotion=“Manual” (edited)

wbrefvem   [23 minutes ago]
hmm okay

James Celli   [23 minutes ago]
jx get envs
NAME       LABEL                      KIND        PROMOTE NAMESPACE     ORDER CLUSTER SOURCE                                                                   REF    PR
dev        Development                Development Never   jx            0
production Online Services Production Permanent   Manual  jx-production 200           https://PIDJENKINSKSBOTT@stash.xactware.com/scm/gdo/env-beta-os-prod.git master

James Celli   [22 minutes ago]
That is what I get right after I create the ENV….

wbrefvem   [22 minutes ago]
would you mind raising an issue and including the information you've posted here? that'll make it easier for us to track and for others to weigh in.

James Celli   [21 minutes ago]
Absolutely… I am wondering if it has something to do with the /scm/ part of the URL….

James Celli   [21 minutes ago]
I have attempted to use a different URL setup, however I am not sure of the alternate URLs that bitbucketserver will work with…

James Celli   [19 minutes ago]
Odd… when I try to edit the ENV now, I am getting the following error:

jx edit env production -o 200
? Label: Online Services Production
? Namespace: jx-production
? Domain: geomnidev.net
? Cluster URL: https://api.k8s.geomnidev.net
? Promotion Strategy: Manual
? Git URL for the Environment source code: https:://GIT_PROVIDER/scm/gdo/env-beta-os-prod.git
? Git branch for the Environment source code: master
Updated environment production
error: Invalid path  could not determine organisation and repository name (edited)

wbrefvem   [17 minutes ago]
we've tackled that problem in the past, so i'm not sure that's what's going on here, but i'll investigate and see what i can find.

**Comment by skyionblue** [comment]
Just wanted to add some additional information, the branch does exist in the correct Repo. What I mean by that is that the branch is in the staging ENV Repo, and if I manually merge it with the master branch then the pipeline will start..

**Comment by heroic** [comment]
@skyionblue Yes. However, in my case the branch is in searchable using org:branch_name, whereas jx tries to find it with user:branch_name

**Comment by skyionblue** [comment]
That is exactly the same thing that is happening on my end as well... the PIDJENKINSKSBOTT is the pipelineusername, where GDO is the Repo Owner.

**Comment by polothy** [comment]
Just FYI, pretty sure this has already been fixed in https://github.com/jenkins-x/jx/commit/fda389af308210f43a9435ea319008bd74748e18 ([this line specifically](https://github.com/jenkins-x/jx/commit/fda389af308210f43a9435ea319008bd74748e18#diff-e7781ea1145f91b873a4efd8091b56d8R148)) - it just hasn't been released yet in JX Platform.

Sounds like JX team is reworking their infra right now, so it may take a while to get a new JX Platform that has the fix in it.  I was told to watch https://github.com/jenkins-x/jx/issues/3367 for when the new infra is up and a new release is out.

**Comment by skyionblue** [comment]
This has been resolved, quite a few versions back. Please close this issue.

**Comment by wbrefvem** [comment]
@heroic Has this been resolved to your satisfaction?

**Comment by heroic** [comment]
@wbrefvem I think it was resolved, but we moved to github since it was the first class citizen here :)
