### ISSUE TITLE
feature: importing arbitrary jobs

### ISSUE THREAD

**Issue by alphabettispaghetti** [jenkins-x/jx#3376]
### Summary 
It would be nice to be able to support the automation of importing pipelines that build and provision infrastructure (e.g. Ansible, terraform, puppet, chef). Not sure if this already exists or not but we can't find it.

Alternatively it would be nice to be able to automatically import arbitrary jobs and pipelines to jx instead of just application support. This would provide a huge advantage over regular jenkins in being able to run essentially vanilla jenkins in a distributed way with the inherent advantages of kubernetes.

**Comment by ccojocar** [comment]
@alphabettispaghetti Is this feature request for Classic Jenkins or Serverless?
