### ISSUE TITLE
Add support for conditional questions to Apps

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3378]
### Summary 

Apps can ask questions based on JSON schema when being installed, which generates a `values.json`. Sometimes you want to have some of the questions only be asked if the answer to a previous question was `y`. For example, if you are installing the athens app, then you could be asked the question:

```
Do you want to configure persistent storage" (y/N)
```

And only if you answer yes do you get asked some more questions about e.g. the type of persistent storage that is created.

**Comment by pmuir** [comment]
I haven't worked out how to do this in JSON schema in a natural way yet.

**Comment by daveconde** [comment]
This has been implemented using [json schema conditionals](https://json-schema.org/understanding-json-schema/reference/conditionals.html)
