### ISSUE TITLE
Jenkinsfile should only do releases if the git repo owner is the upstream

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#338]
if folks fork a repo then import the fork into jenkins x it'll try to release the fork via a CD pipeline.

We should add an organisation check into the CD pipeline section of the `Jenksinfile` so that if you import a fork into jenkins x then it should either ignore master or do a CI build on it etc

**Comment by jtnord** [comment]
@jstrachan this issue is not clear as this is often exactly what you want to do.  e.g. https://github.com/jenkins-x/updatebot.

Do you mean just importing a project outside of the main (GitHub) organisation - not sure how that would map to other git providers though.

// cc @oswaldohp

**Comment by ccojocar** [comment]
@jstrachan I am going to close this issue since it seems to be stalled.
