### ISSUE TITLE
jenkins X for non Continuous Delivery/Deployment

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [jenkins-x/jx#3381]
### Summary 
This is a question about using Jenkins X for Continuous Integration without Continuous Delivery/Deployment.

I administer a Jenkins system for a group of researchers and their scientific programs. I've had some success on in-house hardware, but would like to be provide more scaling and am trying to move it to AWS EKS. Finding out jx could create a cluster with one command was exciting, but I'm concerned about the differences between Jenkins and Jenkins X.

None of the developers need or want Continuous Delivery functionality. We've had great success with setting up Jenkinsfiles, but their programs are not web services and many of the CD features do not make sense for them. I also saw mention that Jenkins X would automatically create a helm chart for each project, which is definitely not something we need.

Is it possible to create a normal Jenkins cluster with the jx tool, or is there some way to disable these other features?

Thanks

**Comment by ccojocar** [comment]
Maybe you can try to use the library option when installing Jenkins X. This option providers some build-packs which don't perform a deployment.

**Comment by tjesser-ucdavis-edu** [comment]
I'm not sure what option you are referring to, as I'm unable to find it in the CLI help.

```
tjesser@computer:~$ jx create cluster eks --help | grep -i library
tjesser@computer:~$ jx install --help | grep -i library
tjesser@computer:~$
```

**Comment by tjesser-ucdavis-edu** [comment]
I would really like to get more information about this library option so I can begin testing it.

**Comment by deanesmith** [comment]
@tjesser-ucdavis-edu Noticed this issue.  Take a look at - 
https://github.com/jenkins-x-buildpacks/jenkins-x-classic
https://jenkins-x.io/architecture/build-packs/#readout
https://jenkins-x.io/commands/jx_step_buildpack_apply/
