### ISSUE TITLE
jx cli cannot communicate with jenkins after force-ssl-redirect

### ISSUE THREAD

**Issue by romil-punetha** [jenkins-x/jx#3384]
### Summary 

I'm have a internal cluster running on eks, with jenkinsx installed. I forced redirection on jenkins server from http to https via an annotation in the jenkins ingress as I am only able to configure an ELB with K8s (I couldn't add an ALB... is it supported?), which does not have its own redirection mechanism unlike an ALB, hence I had to handle redirection at application level. However, after this change, I cannot use jx cli. 

### Steps to reproduce the behavior

1. Setup a cluster in private networking mode, with an ELB attached. 
2. Redirect all http traffic to https via the `nginx.ingress.kubernetes.io/force-ssl-redirect:  
true` annotation in the jenkins ingress.
3. Try `jx delete application`.

### Expected behavior

It should ask me which app to delete from a list of apps

### Actual behavior

`error: deleting application: 308 Permanent Redirect`

### Jx version

The output of `jx version` is:  

```
1.3.974
```

### Jenkins type

- [ ! ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@romil-punetha I think jx is not able to infer the new HTTPS URL. At the moment is checking the ingress-config, you can also edit that manually to enable TLS.

**Comment by romil-punetha** [comment]
@ccojocar Can you enlist the steps to do so? Also, can the same be automated via config map entries or ingress annotations?
