### ISSUE TITLE
CLA/DCO ?

### ISSUE THREAD

**Issue by duglin** [jenkins-x/jx#3385]
### Summary 

I might be missing it, but do the docs say what people need to do w.r.t. DCOs/CLAs to contribute code? I think it would be good to mention this in the CONTIBUTING.md file. This is kind of an important question for many folks (especially from company lawyers :-) so making it easy to find this info will help speed up the process for new contributors.

**Comment by davidcurrie** [comment]
Surely you don't work for a company run by lawyers @duglin ?! ;)

**Comment by duglin** [comment]
"run by"... "inundated by" .... nope, not me  :-)

**Comment by ccojocar** [comment]
The Jenkins X project is using the Apache 2.0 license. I am not sure if the CLA/DCO is relevant. cc @dennisnewel @jstrachan

**Comment by duglin** [comment]
Yea, Apache 2.0 License is good but the legal aspects of contributing need to be spelled out too. E.g. see the text in here for DCO: https://developercertificate.org/

**Comment by dennisnewel** [comment]
Not really my expertise, so i had to google both terms :) i found a [counter argument for CLAs](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/) that makes sense to me, but a DCO doesn't sound like a bad idea. 
I can check with our legal department to get their take on it

**Comment by davidcurrie** [comment]
@dennisnewel - would be good to see some consistency across the CDF projects here. I know, for example, the CNCF advocates for DCO with CLA exception in its project. I see that @duglin has [asked the same question of Spinnaker](https://github.com/spinnaker/spinnaker/issues/4155) which also does not have this called out.

**Comment by dennisnewel** [comment]
good point @davidcurrie. i'm trying to figure out where to get an answer to this question, but CDF is probably the right level (and not CloudBees)

**Comment by duglin** [comment]
if it were up to me, I'd use DCOs - they're much easier for devs to deal with - but I know some companies really prefer CLAs.

**Comment by duglin** [comment]
Hi - any update on this?
