### ISSUE TITLE
should we do CI builds (and previews) on all branches that are not master?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#339]
I wonder if we should widen the `PR-*` match in our OOTB Jenkinsfile?
https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/import.go#L71

e.g. this notation works fine for the CI section
```groovy
            when {
                not {
                    branch 'master'
                }
            }
```

I wonder if we should use a variable for `master` so folks can change that in one place?

**Comment by michaelneale** [comment]
Github can have a default branch set (as can bitbucket) but would require api integration to find that out at runtime

**Comment by jstrachan** [comment]
yeah - ideally the default branch would be exposed as a `when` expression in declarative

**Comment by michaelneale** [comment]
@jstrachan yeah would be a good RFE, but this ticket was about something else right?

**Comment by jstrachan** [comment]
Yeah - the motivation behind this ticket was more for everything-but-master branch. Namely I was trying to use CI + Preview environments for "preview branches" or feature branches while developing and before I was ready to submit a Pull Request. So I'm thinking we maybe wanna default to anything not master run a CI pipeline.

**Comment by michaelneale** [comment]
I think preview to anything that has a PR open, ideally (and ideally it would idle the app - a future enhancement to save resources). if it is just a branch, with no open PR, no need for a review app IMO

**Comment by jstrachan** [comment]
so the reason I raised this PR is I wanted to be able to run CI & create a preview environment on a branch I was developing *before* I raised the PR. Folks are gonna want a way to run stuff in k8s before they submit a PR.

So I did a `jx import` on my fork; though to get CI to kick in I must name my branch "PR-xxxx" which seems an unnecessary restriction really. You can choose when importing what branches you want the MultiBranchProject to build anyway; so that seems a better way of filtering things than hard coding "PR-*" as the only branches that ever gets a CI build

**Comment by michaelneale** [comment]
@jstrachan I can understand that - you just want to muck around. Is there some cli thing that you could go "make me a review env of this branch?"

Otherwise I think this should require that a PR be opened for this (from a fork or branch). PRs are perfectly acceptable to NOT be ready in this day an age. 

A few options I guess...

**Comment by jstrachan** [comment]
Right now the 'make a review env of this branch' feature is to just run `jx import` in your fork/branch - it detects you are in a fork and just enables the current branch for now.

I hear you on the PR thing - only its odd having to create a PR just so you can build stuff - folks may then think its mergeable - and it avoids all that stuff adding "DO NOT MERGE'  commands to PRs and stuff.

So we definitely need a way to say 'enable CI / preview' on a per branch basis. However we should not have to then start hacking the Jenkinsfile in each branch just to change the `PR-*` filter - its far better to just use patterns in the `MultiBranchProject` when you do a `jx import`

Right now `jx import` lets you specify a branch pattern for the branches to enable. If it detects you are in a fork it just defaults to the current branch name but you can override this with the `--branches` option

**Comment by jstrachan** [comment]
I don't grok the pollution angle nor why it matters how soon folks submit the PR :) 

If each user has their own fork that they wish to import, then each users forks are in their own folder in jenkins for the stuff that user is working on. e.g. the jenkins folder structure would be like...

```
jstrachan
  repo1/
   fix1/
   wacky-idea2/
   PR-356
  repo2/
    234/
michaelneale/
   repo2/
     PR-1234 (WIP - DON'T MERGE)
     PR-456  (WIP - DON'T MERGE)
jenkins-x/
   jx/
     master/
      PR-....
```
etc

i.e. folks can have their own areas for their own forks; or can import additional branches on team repos via `jx import` using whatever branch patterns they want.


On the WIP PR thingy - maybe we could add a way to mark a PR as WIP so that it can't be merged. Maybe we can just mark PRs as requiring a review from yourself? :)

**Comment by michaelneale** [comment]
oh I just mean having stuff in kube that is very much WIP that may not get cleaned up

On PRs, my reply was to this:

>I hear you on the PR thing - only its odd having to create a PR just so you can build stuff - folks may then think its mergeable - and it avoids all that stuff adding "DO NOT MERGE' commands to PRs and stuff.

What I was saying is that it may not be odd to open a PR to get JenkinsX to put a review app link into it

but I may be misunderstanding this whole thing.

**Comment by jstrachan** [comment]
So I'd like to use Jenkins X to be able to edit code, debug, submit PRs and release - which I guess is a different approach to traditional CI - only do stuff when a PR shows up. 

Background here: https://github.com/jenkins-x/jx/issues/284

So ideally I'd like to be able to edit code on my laptop and have Jenkins X automatically redeploy the app to a Preview namespace for me ASAP - while in parallel running all the tests to check I've not broken anything. Lets reuse the cloud to make developers faster at all stages of development.

I love that PRs generate Preview environments & CD pipelines releasing after merging to master. But I think we could do better to reuse the same technology, containers, platform, images + pipelines for development too - not just from 'create PR' onwards.

e.g. I'd like to move us more away from running stuff on our laptops thats never the same as the docker images we use for CI / CD - towards reusing the exact same docker images, build pods, tool versions, operating system, disk, network, platform at all stages of development. This would reduce lots of waste when we think there are issues - but really its just the operating system / local install / tool versions on our laptops rather than the one we're gonna run production on.

It should be trivial for example to have a personal pipeline for the repos/branches you're working on; then use 'jx rsh foo' to open a terminal inside that build pod and run stuff in there (mvn / make / whatever) to ensure you're running on the same OS, install & versions of stuff. We should be able to do fast incremental builds on file changes and whatnot.

I realise this might all sound a bit wacky though - so its totally fine if folks want to opt out of everything and just submit PRs - thats totally fine - its an optional thing to decide to create 'edit environments' or `jx import` personal forks/branches etc

**Comment by michaelneale** [comment]
@jstrachan wow. 

Can that be a blog post? This is pretty cool! Now I get you.

**Comment by jstrachan** [comment]
yeah - would love a blog post around that ;) there's so many blog posts we could write...

**Comment by tdcox** [comment]
+1 on this. I would like to see a default path that hides most of the complexity from new developers so that they can be productive whilst they learn the platform.

**Comment by ysaakpr** [comment]
+1 ....we too had same issue and now have to re write the Jenkins file in order to have development branch build support..I belive the jenkins file should be writen in such a way where any commit to default branch(master) should be build and tagged with main line version.. and any other branch should be versioned as snapshots..thats how we have done the CI/CD in our org;
