### ISSUE TITLE
jx step git credentials error: Failed to get the development environment namespaces <custom namespace> is forbidden: User "system:serviceaccount:<custom namespace>:default" cannot get namespaces in the namespace <custom namespace> Failed to get the development environment namespaces from Jenkins Pipeline

### ISSUE THREAD

**Issue by ximbal** [jenkins-x/jx#3401]
### Summary 
Our pipelines stopped working with this error message, I've been trying to figure out a way out of it but I haven't please help.

### Steps to reproduce the behavior
Freshl JX local install, fresh k8s cluster, latest jx version

### Expected behavior

Establish git credentials and able to reach the namespaces @ k8s cluster

### Actual behavior

Error in a jenkins pipeline with step: 

jx step git credentials error: Failed to get the development environment namespaces <CUSTOM NAMESPACE> is forbidden: User "system:serviceaccount:<CUSTOM NAMESPACE>:default" cannot get namespaces in the namespace  <CUSTOM NAMESPACE> Failed to get the development environment namespaces from Jenkins Pipeline

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.998
jenkins x platform 0.0.3321
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.10.7
helm client        v2.12.2+g7d2b0c7
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [X] Classic Jenkins
- [ ] Serverless Jenkins

### Operating system / Environment
MAC OS X Mojave and K8s 1.11.7-gke.4 Container-Optimized OS (cos)

**Comment by ccojocar** [comment]
@ximbal I which namespace did you install Jenkins X?

**Comment by romil-punetha** [comment]
Getting the same issue. Jenkinsx is installed in jx namespace.

**Comment by anub1s187** [comment]
Getting the same here, JenkinsX installed in jx namespace, AWS cluster built by JenkinsX create cluster.

NAME               VERSION
jx                 2.0.263
jenkins x platform 2.0.330
Kubernetes cluster v1.12.7
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
