### ISSUE TITLE
Support "jx create cluster eks" using existing VPC and subnets

### ISSUE THREAD

**Issue by mailjunze** [jenkins-x/jx#3404]
### Summary 
jx create cluster eks doesnt allow to choose existing subnets
### Expected behavior
jx create cluster eks --subnets <subnet1,subnet2>

eksctl provides supports for VPC/Subnets|

eksctl create cluster \
  --vpc-private-subnets=subnet-0ff156e0c4a6d300c,subnet-0426fb4a607393184 \
  --vpc-public-subnets=subnet-0153e560b3129a696,subnet-009fa0199ec203c37
### Jx version

The output of `jx version` is:
jx version                                                                                                                                                                                   ec2-user@ip-172-31-9-12
NAME               VERSION
jx                 1.3.1008
jenkins x platform 0.0.3588
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.11.5
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.17.2
Operating System   Linux distribution Linux version 4.14.77-86.82.amzn2.x86_64 ) (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Mon Dec 3 19:40:13 UTC 2018

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by SharePointOscar** [comment]
Right, `jx create cluster eks` does not have flags to pass existing VPC/subnets.  What you can do, is create your cluster using other tools like `eksctl` or `KOPS`.  Once it is created, you can set your `kubectl` context to said cluster, then execute the `jx install`.

**Comment by patrickleet** [comment]
@SharePointOscar was thinking of doing the above with EKS next time around to take advantage of their new declarative/gitops configs

**Comment by SharePointOscar** [comment]
@ccojocar if we implement this for EKS, would it make sense to also implement for Azure and GCP to also allow folks to install on specific networks?
