### ISSUE TITLE
When creating Jenkins token, the username is incorrect

### ISSUE THREAD

**Issue by GoTheExtraMile** [jenkins-x/jx#3412]
### Summary 
When creating Jenkins token, the username is ingress svc ip .
The correct value should be admin

[22/Mar/2019:07:42:45 +0000] "POST /j_security_check?j_username=192.168.100.50&j_password=admin HTTP/1.1" 303 5 "-" "Go-http-client/1.1" 174 0.004 [jx-jenkins-8080] 10.233.72.182:8080 0 0.004 303

### Steps to reproduce the behavior
Execute the JX command:

jx install --provider=kubernetes \
--on-premise \
--skip-ingress \
--external-ip= 192.168.100.50 \
--domain=ssy \
--default-admin-password=admin \
--git-provider-kind=gitlab \
--git-provider-url=http://192.168.x.x:x \
--docker-registry=https://192.168.x.x \
--version=0.0.3589 \
--log-level=debug \
--local-cloud-environment=false

Viewing logs using kubectl command:

kubectl logs nginx-ingress-controller-745bf85f5d-dlf9h -n default

[22/Mar/2019:07:42:45 +0000] "POST /j_security_check?j_username=192.168.100.50&j_password=admin HTTP/1.1" 303 5 "-" "Go-http-client/1.1" 174 0.004 [jx-jenkins-8080] 10.233.72.182:8080 0 0.004 303

### Expected behavior
POST /j_security_check?j_username=admin&j_password=admin

### Actual behavior
POST /j_security_check?j_username=192.168.100.50&j_password=admin

### Jx version
NAME               VERSION
jx                 1.3.998
jenkins x platform 0.0.3589
Kubernetes cluster v1.10.0
kubectl            v1.10.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.3.1611 (Core)

### Jenkins type

- [ ] Classic Jenkins

### Kubernetes cluster

manual create k8s v1.10.0

### Operating system / Environment

centOS7

**Comment by GoTheExtraMile** [comment]
No one handled the problem, I give up jenkinsX
if need me to close this issue, let me know

**Comment by ccojocar** [comment]
Thanks for reporting this! We recommend using `boot` for installing Jenkins X. I am going to close it for now.
