### ISSUE TITLE
jx install gke return invalid url http://jenkins.jx.y/login

### ISSUE THREAD

**Issue by krithiva** [jenkins-x/jx#3414]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by SharePointOscar** [comment]
Can you provide a bit more information?   What command did you use to install on GKE?  Are you using a domain?

**Comment by ccojocar** [comment]
@krithiva This looks like an empty issue. I am going to close it. Please open another issue with a detailed description. Thank you!
