### ISSUE TITLE
User already exists on jx preview

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#3420]
### Summary 

Build fails on `jx preview` with the following error:
```
+ jx preview --app xxx --dir ../..
Creating a preview
Commit author email is empty for: 19bb0e04b83ef5d1fdccd2a10243ccf4817b6acf
Looking for commits in: /home/jenkins/go/src/github.com/cloudbees/xxx/
error: users.jenkins.io "davidcurrie" already exists
```

As far as I can tell from the GitHub API, the referenced commit *does* have an author email. The only thing of note is that the "davidcurrie" user that already exists has a different email address (the default on my GitHub account).

### Steps to reproduce the behavior

1. Import project
2. Create PR

### Expected behavior

Build passes.

### Actual behavior

Build fails.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1011
jenkins x platform 0.0.3629
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.18.0
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by davidcurrie** [comment]
At least the first part of the mystery is solved, `GetPullRequestCommits` is always going to find an empty email address as it is looking in author.email. As https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request shows, the email address is actually at commit.author.email.

**Comment by davidcurrie** [comment]
As discussed in Slack, a `User` has been created by core UI that specifies `davidcurrie` and one email address but does not provide an `AccountReference` as it does not know what provider that identity came from. `users.Resolve` correctly rejects this user as it has a different email address from the one in the commit but then attempts to create a new `User` with the same resource name.

**Comment by davidcurrie** [comment]
Note that the issue in the first comment still stands but it just results in the spurious message and some unnecessary processing retrieving the email address from the commit history.

**Comment by davidcurrie** [comment]
Also, note that the current fallback of trying to retrieve the `User` by matching on email address also fails to work correctly in my case. Because it has a user login, it attempts to retrieve my user info but, as my password is set to private, it gets back `""` and then refuses to match that on any jx `User`.

**Comment by zawadzkip** [comment]
``` jx preview --app APP_NAME --dir ../.. 


Creating a preview 


Commit author email is empty for: 499ade923fac83f0af63bf5d9f5d7d990ff944e9 

Looking for commits in: /home/jenkins/workspace/APP_NAME_PR-22/ 
error: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required 
script returned exit code 1```
