### ISSUE TITLE
Preview environments not getting GC'd

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#3430]
### Summary 

`gcpreviews` pods failing with:
```
error: namespaces "jx" is forbidden: User "system:serviceaccount:jx:jenkins-x-gcpreviews" cannot get namespaces in the namespace "jx"
```

There is no clusterrole or clusterrolebinding defined for this sa. Looks like `clusterrole` has too much indentation here:
https://github.com/jenkins-x/jenkins-x-platform/pull/5012/files#diff-ba05023d0f1b5d4b64b6cad4cf9a7ecdR53

### Steps to reproduce the behavior

Install cluster

### Expected behavior

GC job runs cleanly

### Actual behavior

GC job fails

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1011
jenkins x platform 0.0.3629
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.18.0
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [ ] Classic Jenkins
- [X] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by msdemt** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/38455670/55051262-4635ff00-508f-11e9-8145-2113ce40a550.png)

**Comment by romainverduci** [comment]
I'm working on a fix, should be in a PR soon.

**Comment by amoussawi** [comment]
@romainverduci I thing this https://github.com/jenkins-x/jenkins-x-platform/pull/5012 broke it. I changed the service account of the gcpreviews cronjob back to jenkins and it's working fine now.

**Comment by romainverduci** [comment]
@amoussawi using jenkins as a service account is only working if your jx cluster is configured with a static jenkins master and won't work for serverless installs. https://github.com/jenkins-x/jenkins-x-platform/pull/5115 should have fix this issue.

**Comment by amoussawi** [comment]
@romainverduci no I was still having this issue with the jenkins-x-platform version 2.0.191 until I changed the service account back to jenkins, and other users https://github.com/jenkins-x/jx/issues/3463 are still having the same issue too.

**Comment by abayer** [comment]
Worth mentioning that on prod this is particularly hairy, due to helm client/server incompatibility. =)

**Comment by warrenbailey** [comment]
Fixed and should be in the next release of jenkins-x-versions

**Comment by warrenbailey** [comment]
@abayer yeah I think so. I'll check

**Comment by warrenbailey** [comment]
It's a different error in prod though, like you said its a helm version mismatch issue.
