### ISSUE TITLE
Issues with jx create quickstart ruby application and importing ruby application

### ISSUE THREAD

**Issue by krishnakumar6893** [jenkins-x/jx#3438]
### Summary 
Issues with jx create quickstart ruby application and importing ruby application

### Steps to reproduce the behavior
Setup JX locally and try to quickstart a ruby based application or import an existing ruby application

### Expected behavior
Should setup a sample ruby application when using jx create quickstart -> ruby

### Actual behavior
Throws error script.sh: docker: not found
jx create quickstart works fine with other applications, only issue is with Ruby. Below is the contents from Jenkinsfile. By comparing with other Jenkinsfile created from other applications could see skaffold stuffs are missing.

pipeline {
  agent {
    label "jenkins-ruby"
  }
  environment {
    ORG = 'krishnakumar6893'
    APP_NAME = 'ddd'
    CHARTMUSEUM_CREDS = credentials('jenkins-x-chartmuseum')
  }
  stages {
    stage('CI Build and push snapshot') {
      when {
        branch 'PR-*'
      }
      environment {
        PREVIEW_VERSION = "0.0.0-SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER"
        PREVIEW_NAMESPACE = "$APP_NAME-$BRANCH_NAME".toLowerCase()
        HELM_RELEASE = "$PREVIEW_NAMESPACE".toLowerCase()
      }
      steps {
        container('ruby') {
          sh "docker build -t $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION ."
          sh "docker push $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION"
          sh "jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION"
          dir('./charts/preview') {
            sh "make preview"
            sh "jx preview --app $APP_NAME --dir ../.."
          }
        }
      }
    }
    stage('Build Release') {
      when {
        branch 'master'
      }
      steps {
        container('ruby') {

          // ensure we're not on a detached head
          sh "git checkout master"
          sh "git config --global credential.helper store"
          sh "jx step git credentials"
          sh "jx step next-version --use-git-tag-only --tag"
          sh "docker build -t $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION) ."
          sh "docker push $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)"
          sh "jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)"
        }
      }
    }
    stage('Promote to Environments') {
      when {
        branch 'master'
      }
      steps {
        container('ruby') {
          dir('./charts/ddd') {
            sh "jx step changelog --version v\$(cat ../../VERSION)"

            // release the helm chart
            sh "jx step helm release"

            // promote through all 'Auto' promotion Environments
            sh "jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)"
          }
        }
      }
    }
  }
  post {
        always {
          cleanWs()
        }
  }
}

### Jx version

The output of `jx version` is:

NAME                           VERSION
jx                                   1.3.1030
Kubernetes cluster        v1.13.4
kubectl                           v1.13.2
helm client                     v2.13.1+g618447c
helm server                    v2.12.2+g7d2b0c7
git                                  git version 2.17.1
Operating System         Ubuntu 18.04.2 LTS
Docker                           18.09.3, build 774a1f4

### Jenkins type

- [x] Classic Jenkins

### Kubernetes cluster

Setup locally with minikube and kubectl
jx create cluster minikube

### Operating system / Environment
Ubuntu 18.04.2 LTS

**Comment by warrenbailey** [comment]
I've just tried and I have the same issue with the ruby buildpack

**Comment by krishnakumar6893** [comment]
Thanks for the response @warrenbailey, any idea why it happens? Particularly with the ruby builds!

**Comment by krishnakumar6893** [comment]
@jstrachan @rawlingsj Guys, any idea why failure with ruby buildpacks occur? We don't see issues with other quickstart applications!

**Comment by krishnakumar6893** [comment]
Issue is fixed now by trying to install skaffold before the docker build happens. This can be done by adding suitable skaffold installation steps in the Jenkinsfile generated by Jenkins-X.

**Comment by krishnakumar6893** [comment]
For instance, added below steps before the docker build happens and it worked perfectly!

sh "curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64"
sh "chmod +x skaffold"
sh "mv skaffold /usr/local/bin"
sh "export VERSION=x.x.x && skaffold build -f skaffold.yaml"
sh "jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:x.x.x"
