### ISSUE TITLE
Send notification when a master build failed

### ISSUE THREAD

**Issue by fiunchinho** [jenkins-x/jx#3449]
### Summary 
We can see the status of the Pull Requests' builds on Github UI, and see that something failed. But when merging a PR to master, we'd like to get a notification with the outcome. Currently, there is no easy way to see what happened with the build when merging to master.

### Steps to reproduce the behavior
Merge a PR and try to figure out what happened.

### Expected behavior
Get slack notification when the build failed, and additional information about the changes.

### Actual behavior
No easy way to see what happened with the build when merging to master.

### Jx version

The output of `jx version` is:

```
jx                 1.3.1016
jenkins x platform 0.0.3321
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.14.0
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.21.0
Operating System   Mac OS X 10.14.3 build 18D109
```

**Comment by msabastian** [comment]
Is the still an open feature request? I would like to enable it for our repos too. 😅

**Comment by gazal-k** [comment]
We are also looking for this feature.

A prerequisite for this would be to define steps in `jenkins-x.yml` that are executed no matter what. Like a `finally` block. Then we should be able to define a step to send a notification to slack or ms teams or something.

@abayer is this something you can help with?

**Comment by pazt** [comment]
Wow, this could be so awesome!
Notification to Slack when a master build is failed sounds like a must thing for us to move with the JX to live production.

Also, a final block (some steps that runs anyway even if we had a previous failure), sounds like a very important capability (for example for cleaning side car pods).
