### ISSUE TITLE
jx create pull-request

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#345]
similar to the `hub pull-request`, it would be nice to create a pull request using jx.

**Comment by jtnord** [comment]
@rawlingsj.  @oswaldohp and myself are unclear on the value of this.  it is adding code for little gain and most developers are used to doing this either from their IDE (with better integration) or the command line using tools that better support their underlying Git provider than we could ever hope to match,

**Comment by ccojocar** [comment]
@jtnord @oswaldohp This is done. There is a command `jx create pullrequest` which works with other Git providers than GitHub. I would close it.
