### ISSUE TITLE
error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found

### ISSUE THREAD

**Issue by donhui** [jenkins-x/jx#3452]
When running “jx create spring -d web -d actuator --log-level='debug' --verbose=true”, the git repository was created and pushed to github, but failed to create jenkins job.
The error is:
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
retrying after error:Failed to create the xxxxxx folder in Jenkins: 404 Not Found
error: after 10 attempts, last error: Failed to create the xxxxxx folder in Jenkins: 404 Not Found

The output of jx version is:
NAME               VERSION
jx                 1.3.992
jenkins x platform 0.0.3636
Kubernetes cluster v1.10.1
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.15.2 (Apple Git-101.1)
Operating System   Mac OS X 10.13.6 build 17G65

**Comment by warrenbailey** [comment]
Hi @donhui I've tried this but it worked for me.

Where does the error appear? In the console logs?

Are you using a static master or serverless jenkins?

A link to the created github repository would also be very useful?

**Comment by donhui** [comment]
> Hi @donhui I've tried this but it worked for me.
> 
> Where does the error appear? In the console logs?
> 
> Are you using a static master or serverless jenkins?
> 
> A link to the created github repository would also be very useful?

I‘m using the static master jenkins, jx can't create the jenkins job and there is no any logs in jenkins console.

**Comment by donhui** [comment]
@warrenbailey
I have solved the issue, which the root cause is the domian in ingress is not consistent with the service exposeUrl.
Thank you !
