### ISSUE TITLE
custom domain not working as expected 

### ISSUE THREAD

**Issue by LeoQuote** [jenkins-x/jx#3457]
### Summary 
I tried to add custom domain while installing , but ingress was still set to ``XXX.nip.io ``
### Steps to reproduce the behavior
1. install using 
```
jx install --no-default-environments  --external-ip 192.168.109.241 --git-provider-url http://git.some_d.com --domain jx.corp.some_d.com
```
2. add DNS for jx.corp.some_d.com and *.jx.corp.some_d.com to an nginx and ``proxy_pass``to k8s master 
### Expected behavior
I can access jenkins through jenkins.jx.corp.some_d.com
### Actual behavior
I can only access it through XXX.nip.io:some_port
At the end of the installation
```
waiting up to 0s for the Jenkins server to be healty at URL http://jenkins.jx.192.168.109.241.nip.io/login
```
It means the nip.io domain is still being used instead of the custom domain.
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1037
jenkins x platform 0.0.3657
Kubernetes cluster v1.13.3
kubectl            v1.13.3
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.2.1511 (Core)
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

kubeadm

### Operating system / Environment

Linux

**Comment by LeoQuote** [comment]
I tried to edit domain using 

```
jx upgrade ingress --cluster
```
At last a ``UrlTemplate`` was required, I'm puzzled about what I should fill.

```
[root@docker01 ~]# jx upgrade ingress --cluster
? Expose type Ingress
? Domain: jx.corp.some_d.com
? If your network is publicly available would you like to enable cluster wide TLS? No

? UrlTemplate: (jenkins.jx.corp.some_d.com)
```

**Comment by LeoQuote** [comment]
Checked source code and found a default ``UrlTemplate ``

https://github.com/jenkins-x/jx/blob/master/pkg/config/helm_values_test.go#L61

set the UrlTemplate to ``"{{.Service}}-{{.Namespace}}.{{.Domain}}"`` (must have quote 'cause or will be error) and it works, hope this can be added to the doc.

**Comment by ccojocar** [comment]
@LeoQuote Did you register the provided domain before the installation? The domain should point to your cluster IP.

What does return the `kubectl get ing -n jx`?

**Comment by LeoQuote** [comment]
@ccojocar thanks for you reply!

I've used the command 

```
jx upgrade ingress --cluster
```

and changed the domain successfully. The only thing I'm puzzled is about the UrlTemplate as I mentioned above.

I cannot reproduce this with ``jx install`` cause I do not have another k8s cluster to do that.

**Comment by ccojocar** [comment]
I think, you can accept the default value. It would built the urls in the form `{{.Service}}-{{.Namespace}}.{{.Domain}}` as you mentioned above. 

Do you need a different format for your URLs?

**Comment by LeoQuote** [comment]
@ccojocar The default value works pretty well! But the point is the ``jx upgrade ingress --cluster`` did not provide the default value and proper document, I did not know what to fill until I checked the source code , I wonder if we can add some help text or document , so people can what to fill at ``UrlTemplate``

**Comment by Cressida8** [comment]
@LeoQuote  can you please elaborate how did you fix this issue? what did you fill at uriTemplate?

**Comment by LeoQuote** [comment]
@Cressida8 this was the default value in source then:

{{.Service}}-{{.Namespace}}.{{.Domain}}

You can try to fill it like this.

The documents and codes may have changed, I suggest you look into the document and get latest information
