### ISSUE TITLE
Adding anchore causes build failure

### ISSUE THREAD

**Issue by icewhite** [jenkins-x/jx#3466]
### Summary 
After adding anchore our build is failing with this message:
```
error: error adding image to CVE provider: no JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST env var found 
```
This environment variable doesn't appear to exist any more. Wondering if step_post_build.go needs to be updated to reference DOCKER_REGISTRY env var instead?

### Steps to reproduce the behavior
```
jx env dev
jx create addon anchore
```
Then trigger a release.

### Expected behavior
Build passes

### Actual behavior
Build fails with message above.

### Jx version

The output of `jx version` is:

```
jx version 
NAME                                   VERSION 
jx                                           1.3.1044 
jenkins x platform             0.0.3631 
Kubernetes cluster           v1.12.6 
kubectl                              v1.13.4 
helm client        v2.13.1+g618447c 
helm server        v2.13.1+g618447c 
git                git version 2.21.0.windows.1 
Operating System   Windows Server 2019 Datacenter 1809 build 17763 
```

### Jenkins type

- [X] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

AKS

### Operating system / Environment

Windows

**Comment by ccojocar** [comment]
Yeah, you need to configure the env variables `JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST` and `JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT` in the Jenkinsfile.
