### ISSUE TITLE
add OOTB grafana dashboards to the metrics addon

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#347]
when the metrics addon is enabled we should use the [dashboard helm values](https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L542) so we get out of the box grafana charts

**Comment by jtnord** [comment]
//cc @jennbriden

**Comment by msigler-cb** [comment]
Need to rationalize with suite. Need to support the K8s ecosystem but have value added commercial.
