### ISSUE TITLE
jx is trying to use https instead of http when pushing image to registry

### ISSUE THREAD

**Issue by LeoQuote** [jenkins-x/jx#3472]
### Steps to reproduce the behavior
1. start a quickstart project
2. go to the jenkins console and look at the log
### Expected behavior

1. image pushed to http://10.1.63.62:5000/v2/
### Actual behavior
image was pushed to https://10.1.63.62:5000/v2/ (it uses the HTTPS instead of HTTP)
causing a timeout http error
```
Successfully built 6d46407dd36c

Successfully tagged 10.1.63.62:5000/some_user/quickstart-jx7:0.0.2

The push refers to repository [10.1.63.62:5000/some_user/quickstart-jx7]

time="2019-03-29T04:17:41Z" level=fatal msg="build failed: building [changeme]: build artifact: Get https://10.1.63.62:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

script returned exit code 1
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1048
jenkins x platform 0.0.3657
Kubernetes cluster v1.13.3
kubectl            v1.13.3
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.2.1511 (Core)
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

kubeadm
### Operating system / Environment
linux

**Comment by LeoQuote** [comment]
possible duplicate #2311

**Comment by retr0h** [comment]
@LeoQuote  did you ever figure this out?

**Comment by LeoQuote** [comment]
@retr0h please follow the issue I provided above to find solutions
