### ISSUE TITLE
--tekton should disable option to install kaniko

### ISSUE THREAD

**Issue by ndeloof** [jenkins-x/jx#3503]
### Summary 

When using `--tekton` flag, Jenkins X will install Kaniko but still ask users about it, default value being "No"

### Steps to reproduce the behavior

run `jx create cluster gke --tekton`

### Expected behavior

Tekton is enabled without asking

### Actual behavior

? Would you like to enable Kaniko for building container images No

### Jx version

The output of `jx version` is:

```
1.3.1071
```

**Comment by jstrachan** [comment]
this is fixed now I think
