### ISSUE TITLE
Tekton Buildpack not use container option at step level

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#3534]
### Summary 

While updating the new apps build pack, I noticed that the generated tekton files don't take into account containers at the step level. It only picks up the agent level one.

e.g. https://github.com/warrenbailey/jenkins-x-kubernetes/blob/go-build/packs/apps/pipeline.yaml

### Steps to reproduce the behavior
1. Attempt to use the above build pack, but remove the agent level container and replace it with 'container: go'. 
1. Generate the tekton files

### Expected behavior
The image in the tekton file should be the one defined in the build pack steps, e.g gcr.io/jenkinsxio/builder-go:0.0.0-SNAPSHOT-PR-380-56

### Actual behavior
The image in the tekton file is the latest go version in jenkins-x-platform e.g. 0.1.339. The step level container is ignored.

### Jx version

The output of `jx version` is:

jx                 1.3.1073
jenkins x platform 0.0.3698
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.13.2
helm client        v2.12.1+g02a47c7
helm server        v2.12.2+g7d2b0c7
git                git version 2.20.1
Operating System   Mac OS X 10.14.2 build 18C54

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by abayer** [comment]
So it sounds like it's ignoring the top-level container as well as the individual steps' containers, right?

**Comment by warrenbailey** [comment]
The top level one was working for me

**Comment by abayer** [comment]
oh duh, I didn't read the ticket well enough. =)
