### ISSUE TITLE
Tekton Buildpack not generating Promote steps

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#3538]
### Summary 
I've created an apps build pack with a promote stage inside the release pipeline. https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/apps/pipeline.yaml

However the promote steps are not being run in a tekton cluster and are not present in the generated tekton files.

### Steps to reproduce the behavior

Run a build using the apps build pack. An example is here: https://github.com/jenkins-x-apps/jx-app-test-lifecycle/pull/5

### Expected behavior
The promote steps should execute

### Actual behavior
The promote steps are not executing

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.1073
jenkins x platform 0.0.3698
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.13.2
helm client        v2.12.1+g02a47c7
helm server        v2.13.1+g618447c
git                git version 2.20.1
Operating System   Mac OS X 10.14.2 build 18C54

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

Mac OS

**Comment by abayer** [comment]
@warrenbailey So the issue is https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/4ec526a85a5e1d8868bb28e506ab632e37febe53/packs/apps/pipeline.yaml#L30 - `build` is not a valid lifecycle key, so it just gets ignored. Relates to #3544, which I opened earlier today and needs discussion.

**Comment by warrenbailey** [comment]
ah ok, thanks. I'll change the build pack.
