### ISSUE TITLE
main ERROR Could not determine local host name java.net.UnknownHostException

### ISSUE THREAD

**Issue by kmarker1101** [jenkins-x/jx#3554]
### Summary 
Job fails to complete due too to error

### Expected behavior
Job completes
### Actual behavior
Job Fails
### Jx version

The output of `jx version` is:

```
jx                 1.3.1075
jenkins x platform 0.0.3734
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.0
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

eks created with jx

**Comment by ccojocar** [comment]
@kmarker1101 Could provide more details? Which particular task is executed by the pipeline when you see this message?

**Comment by kmarker1101** [comment]
This can be closed. I added a docker flag `--network=host` and is resolved the problem.
