### ISSUE TITLE
jx upgrade platform fails with ConfigMap is invalid: Too long: must have at most 1048576 characters

### ISSUE THREAD

**Issue by n8mellis** [jenkins-x/jx#3561]
### Summary 
I am trying to do a Jenkins-X platform upgrade from version 0.0.3402 to version 0.0.3793. The helm upgrade fails because one of the ConfigMaps (jenkins-x.v2) exceeds the max ConfigMap size.

### Steps to reproduce the behavior
Install jx platform version 0.0.3402. Then run `jx upgrade platform`.

### Expected behavior
Config maps built by the jx cli don't exceed the max ConfigMap size.

### Actual behavior
```
error: unable to upgrade helm chart: failed to run 'helm upgrade --namespace jx --version 0.0.3793 --values ~/.jx/cloud-environments/env-eks/myvalues.yaml --values ~/.jx/extraValues.yaml --values ~/.jx/adminSecrets.yaml --values ~/.jx/cloud-environments/env-eks/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '', output: 'Error: UPGRADE FAILED: ConfigMap "jenkins-x.v2" is invalid: []: Too long: must have at most 1048576 characters'
```

### Jx version

The output of `jx version` is:

```
1.3.1096
```

### Jenkins type

```
- [X] Classic Jenkins
```

### Kubernetes cluster

EKS. Created using the AWS EKS standard instructions.

### Operating system / Environment

macOS Mojave 10.14.3

**Comment by athilaelhuno** [comment]
I have the same issue, any way to fix this issue?

**Comment by usultis** [comment]
same here, also EKS, 
jx 1.3.1102

**Comment by pmuir** [comment]
Fix coming soon.

**Comment by kmarker1101** [comment]
same here. Any update?
`NAME               VERSION
jx                 2.0.2
jenkins x platform 0.0.3734
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.0
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226`

**Comment by jstrachan** [comment]
just waiting for the fix to get through our BDD tests...

**Comment by ccojocar** [comment]
@jstrachan Is this fix? Can we close it?

**Comment by jstrachan** [comment]
fix has been released - we moved the pod templates into separate ConfigMaps
