### ISSUE TITLE
builder-ruby is missing jx-release-version

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3563]
### Summary 
builder-ruby does not seem to have the jx-release-version binary installed in the container.

### Steps to reproduce the behavior
Run a CI/CD pipeline using Ruby. The pipeline dies with the error that no jx-release-version command was found.

### Expected behavior
Pipeline should build.

### Actual behavior
Pipeline dies.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1096
jenkins x platform 0.0.3832
Kubernetes cluster v1.12.6-gke.10
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

Mac OSX

**Comment by ccojocar** [comment]
@garethjevans Is this fix? Can we close it?

**Comment by heroic** [comment]
@ccojocar Nope. Upgraded to platform version 2.0.53, but the issue still persists.
