### ISSUE TITLE
Make jx create cluster interactive

### ISSUE THREAD

**Issue by macox** [jenkins-x/jx#3568]
### Summary 
The `jx create cluster` command could provide the user with a selectable list of providers (gke, aks ....), giving consistency with other jx commands.

### Steps to reproduce the behavior
`jx create cluster` 

### Expected behavior
An interactive list of providers is displayed.

### Actual behavior
Static information about valid providers and possible dependencies is displayed.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.992
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.13.4
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G6030
```

**Comment by rawlingsj** [comment]
sounds like a great idea
