### ISSUE TITLE
Issue running `jx upgrade webhooks`

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#3592]
### Summary 

```jx update webhooks -o jenkins-x -r jenkins-x-serverless-filerunner --previous-hook-url https://hook.jx.tekton.rawlings.it/hook```

fails with 

```
Error querying webhooks on jenkins-x/jenkins-x-serverless-filerunner: Get https://fake.git/api/v3/repos/jenkins-x/jenkins-x-serverless-filerunner/hooks: dial tcp: lookup fake.git on 1.1.1.1:53: no such host
Checking hooks for repository jenkins-x-serverless-filerunner
```

### Jx version

1.3.1096

GKE / --ng

**Comment by pmuir** [comment]
Downgrading to critical as no one other Gareth is encountering this right now

**Comment by ccojocar** [comment]
@garethjevans Closing this one since it seems to work when using boot.
