### ISSUE TITLE
helm fails to install jenkins-x on OKE

### ISSUE THREAD

**Issue by GingerBuffalo** [jenkins-x/jx#3595]
### Summary 
jx install fails to install Jenkins-x-platform on my OKE cluster. This was previously working, but is now failing on every attempt to run on any new OKE cluster I create. 

### Steps to reproduce the behavior
- Create a fresh OKE cluster on OCI. 
- Set kubectl context to the cluster, upgrade Helm Tiller, etc. 
- Attempt to run jx install.

### Expected behavior
Up until last week, jx install was successfully completing all steps. 

### Actual behavior
It is now failing to install jenkins-x-platform, and abandoning further steps. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

OKE (Oracle Cloud Infra). Created through the quick-create UI on OCI console. 

### Operating system / Environment

MacOS - High Sierra.

Attempting install with this command:
jx install --git-username=someusername --git-provider-kind=gitlab --git-provider-url=https://someurl --default-environment-prefix=someprefix --environment-git-owner=someownervalue --provider=oke

As of about Friday last week, every attempt results in this failure to install jenkins-x:
Installing jx into namespace jx
using stable version 0.0.3832 from charts of jenkins-x/jenkins-x-platform from /Users/ploveles/.jx/jenkins-x-versions
Installing jenkins-x-platform version: 0.0.3832
Adding values file /Users/ploveles/.jx/cloud-environments/env-oke/myvalues.yaml
Adding values file /Users/ploveles/.jx/adminSecrets.yaml
Adding values file /Users/ploveles/.jx/extraValues.yaml
Adding values file /Users/ploveles/.jx/cloud-environments/env-oke/secrets.yaml
Upgrading Chart 'upgrade --namespace jx --install --timeout 6000 --version 0.0.3832 --values /Users/ploveles/.jx/cloud-environments/env-oke/myvalues.yaml --values /Users/ploveles/.jx/adminSecrets.yaml --values /Users/ploveles/.jx/extraValues.yaml --values /Users/ploveles/.jx/cloud-environments/env-oke/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform'
error: installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.3832 --values /Users/ploveles/.jx/cloud-environments/env-oke/myvalues.yaml --values /Users/ploveles/.jx/adminSecrets.yaml --values /Users/ploveles/.jx/extraValues.yaml --values /Users/ploveles/.jx/cloud-environments/env-oke/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/Users/ploveles/.jx/cloud-environments/env-oke', output: 'Release "jenkins-x" does not exist. Installing it now.
NAME: jenkins-x
Error: getting deployed release "jenkins-x": release: "jenkins-x" not found'

jx version:
NAME VERSION
jx 1.3.1096
Kubernetes cluster v1.12.7-3+1a4d39a9763d23
kubectl v1.13.4
helm client v2.13.0+g79d0794
helm server v2.13.0+g79d0794
git git version 2.17.2 (Apple Git-113)
Operating System Mac OS X 10.13.6 build 17G5019

**Comment by desolatorxxl** [comment]
Please take a look at https://github.com/jenkins-x/jx/issues/3574.

**Comment by jstrachan** [comment]
I think this should be fixed now due to the smaller Jenkins ConfigMap
