### ISSUE TITLE
jx step helm build failed

### ISSUE THREAD

**Issue by LeoQuote** [jenkins-x/jx#3603]
### Summary 
installed a none-tiller jx and started a quickstart-go , this is what happend when building staging environment

```
+ jx step helm build --verbose
No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Using helmBinary helm with feature flag: template-mode
Initialising Helm 'init --client-only'

error: failed to add chart repositories: failed to retrieve the install charts: failed to list repositories: failed to run 'helm repo list' command in directory '.', output: 'Error: Couldn't load repositories file (/home/jenkins/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)'
```
this step took about 2 minutes , that's way too long.
### Steps to reproduce the behavior
1. install jx with jx install --no-tiller
2. start a quickstart project
3. promote the project to staging environment
### Expected behavior
1. build successfully and promote 
### Actual behavior
1. Environment build failed because ``failed to run 'helm repo list'``
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1101
jenkins x platform 0.0.3832
Kubernetes cluster v1.13.3
kubectl            v1.13.3
helm client        Client: v2.12.2+g7d2b0c7
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.2.1511 (Core)
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
kubeadm

### Operating system / Environment
linux

**Comment by krishnakumar6893** [comment]
@LeoQuote I was also facing similar issue with jx step helm release, so tried adding helm install steps before the release happens. This should be added in jenkinsfile. Below is my sample steps added.

sh "curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh"
sh "chmod 700 get_helm.sh"
sh "./get_helm.sh"
sh "helm init"
sh "helm repo add jenkins-x http://chartmuseum.jx.192.168.99.158.nip.io"
sh "jx step helm release"

**Comment by LeoQuote** [comment]
@krishnakumar6893 Thanks for your reply , I figured out my solution yesterday . 
like your solution , I also added 'helm init' in my Jenkinsfile , but I added 

sh 'helm init --stable-repo-url http://mirror.azure.cn/kubernetes/charts/' 

since sometimes https://kubernetes-charts.storage.googleapis.com/ would become unavailable in my environment , the azure mirror is quite stable.

If you're also in mainland China, you can also use my solution. It works pretty well.

**Comment by YuTingLiu** [comment]
@LeoQuote @krishnakumar6893 How do you guys avoid `Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io` fail. 
'''
error: failed to add chart repositories: failed to add Helm repository 'http://chartmuseum.jenkins-x.io': failed to add the repository 'chartmuseum.jenkins-x.io' with URL 'http://chartmuseum.jenkins-x.io': failed to run 'helm repo add chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io' command in directory '.', output: 'Error: Looks like "http://chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.jenkins-x.io/index.yaml : 504 Gateway Timeout'
'''
