### ISSUE TITLE
Unable to achieve installation on GKE

### ISSUE THREAD

**Issue by xsof115** [jenkins-x/jx#3604]
### Summary 
Hi all, after many tries I'm unable to install jenkins-x on gke (free account). Even if I select all default values I receive this error:
Error: getting deployed release "jenkins-x": release: "jenkins-x" not found'

### Steps to reproduce the behavior
login in google cloud
open a cloudshell
run 'jx create cluster gke --skip-login --verbose' command

### Expected behavior
End of installation procedure without errors

### Actual behavior
End of installation with error: 
error: installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.3832 --values 
/home/andrealamotta/.jx/cloud-environments/env-gke/myvalues.yaml --values /home/andrealamotta/.jx/adminSecrets.yaml --values /home/andrealamotta/.jx/extraValues.yaml --values /home/andrealamotta
/.jx/cloud-environments/env-gke/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/home/andrealamotta/.jx/cloud-environments/env-gke', output: 'Release "jenkins-x" does 
not exist. Installing it now.
NAME:   jenkins-x
Error: getting deployed release "jenkins-x": release: "jenkins-x" not found'
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1103
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.11.9-dispatcher
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.8 (stretch)
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by desolatorxxl** [comment]
Please take a look at https://github.com/jenkins-x/jx/issues/3574.

**Comment by jstrachan** [comment]
I think this should be fixed now
