### ISSUE TITLE
Helm release fails in Jenkins X pipeline for Ruby applications

### ISSUE THREAD

**Issue by krishnakumar6893** [jenkins-x/jx#3608]
### Summary 

Facing issue with helm release during Jenkins-X build pipeline.

### Steps to reproduce the behavior

Setup Jenkins-X locally using minikube and kubectl and tried to import/create ruby applications.

### Expected behavior

Build happens and the application is imported.

### Actual behavior

Facing issue with helm release during Jenkins-X build pipeline. Below is the error that occurs during Ruby build pipeline. However the build happens successfully for other applications. Only issue is with Ruby.

+ jx step helm release
No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
error: failed to build dependencies for chart from directory '.': failed to add chart repositories: failed to retrieve the install charts: failed to list repositories: failed to run 'helm repo list' command in directory '.', output: ''

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.907
Kubernetes cluster v1.14.0
kubectl            v1.13.2
helm client        v2.13.1+g618447c
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

### Jenkins type

- [ ] Classic Jenkins

### Kubernetes cluster

Minikube

### Operating system / Environment

Linux 18.04

Locally setup using minikube

**Comment by mokyskury** [comment]
same issue,have you resolved

**Comment by krishnakumar6893** [comment]
@mokyskury yes, added steps to install helm and adding helm repo in Jenkinsfile fixed the issue.
