### ISSUE TITLE
jx git operations are not working as expected

### ISSUE THREAD

**Issue by GingerBuffalo** [jenkins-x/jx#3614]
### Summary 
jx create and delete git operations are not working as expected. When a new git server is added an error message returns "error: the server could not find the requested resource (get gitservices.jenkins.io)", yet the server is added. When I attempt to delete a git server, either GitHub or the one I've added, the same error message returns, but the delete is not performed. 

Attempts to add git tokens a similar error message results "failed to list git services: the server could not find the requested resource (get gitservices.jenkins.io)", and the token is not added. 

This was working in previous versions of jx, so seems to be a regression.

### Steps to reproduce the behavior
jx create git server -k gitlab -n somegitlabserver -u https://somegitlab.server.com
jx delete git server GitHub
jx create git token someusername -t someapitoken -n somegitlabserver

### Expected behavior
Create git server adds the gitlab server with no error message.
Delete git server removes default GitHub server.
Create git token is successful without an error message

### Actual behavior
jx create git server -k gitlab -n somegitlabserver -u https://somegitlab.server.com 
results:
Added Git server somegitlabserver for URL https://somegitlab.server.com
error: failed to ensure GitService exists for kind gitlab server https://somegitlab.server.com in namespace default: failed to list git services: the server could not find the requested resource (get gitservices.jenkins.io)

jx delete git server GitHub
results:
error: the server could not find the requested resource (get gitservices.jenkins.io)

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 1.3.1106
Kubernetes cluster v1.12.7-3+1a4d39a9763d23
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.8.2+ga802316
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G5019
### Jenkins type

- [ x ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

OKE, manually created.

### Operating system / Environment

iTerm2 for MacOS

**Comment by iharrington** [comment]
Having the same issue:

`NAME             VERSION
jx               1.3.1096
git              git version 2.8.4
Operating System "CentOS Linux release 7.6.1810 (Core) "`

**Comment by jstrachan** [comment]
looks like you need to run `jx upgrade crds` first to get your cluster up to date with the [CRDs from Jenkins X](https://jenkins-x.io/architecture/custom-resources/)

**Comment by iharrington** [comment]
So, I now have to do this on every new cluster created. I just created a new cluster and it failed unless I ran `jx upgrade crds` as a step in my automation, is this going to be the case moving forward? @jstrachan
