### ISSUE TITLE
jx install --provider=eks fails 403 route53:ListHostedZones when using diferent AWS profile

### ISSUE THREAD

**Issue by ivan-californias** [jenkins-x/jx#3617]
### Summary 
I have an AWS user that has permission to assume other roles for other accounts, so with this same user I can authenticate and operate switching accounts, switching the profile configured to assume other roles.

When trying to install jx on a running cluster in an other account using an alternate profile, I get an error when jx tries to install the ingress service controller due to user not authorized, but the user that it is taking to perform this step is the user in the root account, not the assumed role for the account of the alternate profile. Previous steps work as expected, like creating the load balancer for the ingress controller, it is created in the correct account using the correct role. But when it reaches this step it uses the user in the root account.

### Steps to reproduce the behavior
1. Configure other profiles for aws-cli
2. `export AWS_DEFAULT_PROFILE=profile2`
3. Have an EKS cluster up and running (withing profile2 account)
4. `jx install --provider=eks`

### Expected behavior
jx is installed and all required services and configurations are installed within the account the the selected profile mandates

### Actual behavior
```
$ jx install --provider=eks --domain=mydomain.dev
Setting the dev namespace to: jx
Using helmBinary helm with feature flag: none
Context "arn:aws:eks:us-east-1:{other_account_id}:cluster/eks-cluster-dev-us-east-1" modified.
Git configured for user: Ivan Californias and email ivan.californias@gmail.com
Using helm2
Configuring tiller
Tiller Deployment is running in namespace kube-system
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace                                                                                            
External loadbalancer created
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller                                                                          
ingress init failed: AccessDenied: User: arn:aws:iam::{root_account_id}:user/{user_in_root} is not authorized to perform: route53:ListHostedZones                                                                          
        status code: 403, request id: ea375c11-5c7b-11e9-ac1a-29ded90382c4
error: initializing the Jenkins X platform: initializing the Jenkins X platform: AccessDenied: User: arn:aws:iam::{root_account_id}:user/{user_in_root} is not authorized to perform: route53:ListHostedZones              
        status code: 403, request id: ea375c11-5c7b-11e9-ac1a-29ded90382c4

```

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 1.3.1108
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.0
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.20.1
Operating System   "Fedora release 29 (Twenty Nine)"
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

I created an EKS cluster using terrform with these guides:
https://learn.hashicorp.com/terraform/aws/eks-intro
https://aws.amazon.com/blogs/opensource/continuous-delivery-eks-jenkins-x/

### Operating system / Environment

Fedora 29

**Comment by rverma-nikiai** [comment]
Its not just the domain setup stage, the dependency of static credentials is at various stages and this virtually makes it impossible to use with profile.

**Comment by deanesmith** [comment]
Hi @ivan-californias, we put quite a bit of effort in to EKS support including Terraform, IRSA, and docs.  I am closing this issue due to its age and we believe the matter is largely addressed - https://jenkins-x.io/docs/getting-started/ (see the AWS section)
