### ISSUE TITLE
Unable to install Minishift

### ISSUE THREAD

**Issue by svallepu** [jenkins-x/jx#3619]
I'm trying to install the minishift on my MAC . got below issue:
```
./jx create cluster minishift
? memory (MB) 16384
? cpu (cores) 2
? Select driver: virtualbox
Installing virtualbox
We cannot yet automate the installation of VirtualBox - can you install this manually please?
Please see: https://www.virtualbox.org/wiki/Downloads
Installing default addons ...
Enabling admin user...
Creating cluster...
Error: Command failed  minishift start --memory 16384 --cpus 2 --vm-driver virtualbox
error creating cluster exit status 1
```

**Comment by akin-ozer** [comment]
I have no problem with kvm2 driver, does minishift start normally without jx?

**Comment by hferentschik** [comment]
@svallepu did you install VirtualBox? Also as @akin-ozer you can always try to install Minishift independently and see whether you get it to work. This isolates the problem. 
Once you have Minishift running you can use `jx install` to install Jenkins-X onto your existing Minishift instance.

**Comment by svallepu** [comment]
Yea minishift is installed on my mac and able to access . but jx install is failing .

./jx install
Setting the dev namespace to: jx
Failed to retrieve team settings: failed to create the jx Dev namespace: Failed to create Namespace jx the server has asked for the client to provide credentials (post namespaces) - falling back to default settings...
Using helmBinary helm with feature flag: none
Context "acq-marketing-platform/master-e31blue-v3-epaas-aexp-com:8443/svallepu" modified.
? Cloud Provider minishift
error: configuring the team settings in the dev environment: updating the team setttings in the dev environment: failed to create the jx Dev namespace: Failed to create Namespace jx the server has asked for the client to provide credentials (post namespaces)

**Comment by hferentschik** [comment]
So, now this is a different error though right? So now you have Minishift installed, but you cannot install Jenkins-X on it?

**Comment by svallepu** [comment]
yes minishift installed separately . Then tried jx install after that

**Comment by akin-ozer** [comment]
Can you completely clear minishift instances with this command and try again?(note: these commands will clear your profile datas, addon selections etc.)You should be able to try "fresh" with this.
`minishift delete --force`
`rm -rf ~/.minishift/machines/minishift-state.json`

**Comment by svallepu** [comment]
After removing and reinstalling now am facing 
jx
Failed to retrieve team settings: failed to create the jx Dev namespace: Failed to create Namespace jx Post https://192.168.99.101:8443/api/v1/namespaces: x509: cannot validate certificate for 192.168.99.101 because it doesn't contain any IP SANs - falling back to default settings...
Using helmBinary helm with feature flag: none
Context "minishift" modified.
? Cloud Provider minishift
error: configuring the team settings in the dev environment: updating the team setttings in the dev environment: failed to create the jx Dev namespace: Failed to create Namespace jx Post https://192.168.99.101:8443/api/v1/namespaces: x509: cannot validate certificate for 192.168.99.101 because it doesn't contain any IP SANs
