### ISSUE TITLE
Preview is failing when jx cannot find github metadata

### ISSUE THREAD

**Issue by porterja31** [jenkins-x/jx#3620]
### Summary 
When trying to create preview environments from PRs our builds are failing due to missing some metadata in our github commits or commit history.

### Steps to reproduce the behavior
Unsure all our preview builds from our enterprise github seem to be failing on this same error.

### Expected behavior
Preview environments should build if metadata isn't present

### Actual behavior
`+ jx preview --app app-name --dir ../..
Creating a preview
Commit author email is empty for: 499ade9xxxxxxxxxf5d9f5d7d990ff944e9
Looking for commits in: /home/jenkins/workspace/T-Software_app_name_PR-22/
error: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required`

### Jx version

The output of `jx version` is:

```
jx                 1.3.1091
jenkins x platform 0.0.3368
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.10.11
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

MacOS/EKS terminal

**Comment by SharePointOscar** [comment]
I experienced the same error, but in my case, the **User.jenkins.io** did have a value of "SharePointOscar", but the regex check is failing.

`{"level":"info","msg":"Looking for commits in: /workspace/source/\n","time":"2019-04-19T22:16:04Z"}
error: User.jenkins.io "SharePointOscar" is invalid: metadata.name: Invalid value: "SharePointOscar": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
{"component":"entrypoint","error":"wrapped process failed: exit status 1","level":"error","msg":"Error executing test process","time":"2019-04-19T22:16:04Z"}
WARN[0050] container build-step-promote-jx-preview failed with exit code 1:  
WARN[0050] pod sharepointoscar-node-test-app-p-4-from-build-pack-d2fgt-pod-8`

**Comment by jstrachan** [comment]
this should be fixed now

**Comment by alexvolsh** [comment]
The same issue with 2.0.204. Any ideas on how to fix that?

**Comment by alexvolsh** [comment]
> The same issue with 2.0.204. Any ideas on how to fix that?

Seems like it was a problem with bitbucket cloud itself because everything it working now, without any changes from my side.

**Comment by porterja31** [comment]
Is a default user supposed to be created when you do JX install? Or are we supposed to create a user with jx create user?

**Comment by lgg42** [comment]
> > The same issue with 2.0.204. Any ideas on how to fix that?
> 
> Seems like it was a problem with bitbucket cloud itself because everything it working now, without any changes from my side.

Hey, is your setup still working? It happened to us, but it broke again like 3 days ago...

**Comment by lgg42** [comment]
> Is a default user supposed to be created when you do JX install? Or are we supposed to create a user with jx create user?

In our case, we have existing users. (Output of `jx get user` or `kubectl get user`), but we didn't create them, we assume that each time a new PR is opened, the author of that PR is created as a user. We don't know for certain, but our existing users are the only ones that have opened/merged PRs

**Comment by srtvasu** [comment]
> > Is a default user supposed to be created when you do JX install? Or are we supposed to create a user with jx create user?
> 
> In our case, we have existing users. (Output of `jx get user` or `kubectl get user`), but we didn't create them, we assume that each time a new PR is opened, the author of that PR is created as a user. We don't know for certain, but our existing users are the only ones that have opened/merged PRs

We are also facing the same issue.

```
+ jx preview --alias preview --dir ../.. --verbose=true --no-comment=true
Creating a preview
Using helmBinary helm with feature flag: template-mode
error: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required

```
Our git provider is BitBucket Cloud

**Comment by okgolove** [comment]
+1, the same problem.
