### ISSUE TITLE
Banzaicloud vaults

### ISSUE THREAD

**Issue by macalinao** [jenkins-x/jx#3628]
### Summary 

I get this error:
```
 % jx get vaults
error: listing vaults in namespace 'jx': the server could not find the requested resource (get vaults.vault.banzaicloud.com)
```

### Steps to reproduce the behavior

Run `jx get vaults`

### Expected behavior

Should list my vaults

### Actual behavior

Returns error message

### Jx version

The output of `jx version` is:

```
 % jx version
NAME               VERSION
jx                 1.3.1098
jenkins x platform 0.0.3737
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.13.4
helm client        &version.Version{SemVer:"v2.11.0+unreleased",
helm server        v2.13.1+g618447c
git                git version 2.19.2
Operating System   Unkown Linux distribution Linux version 4.19.30 (nixbld@localhost) (gcc version 7.4.0 (GCC)) #1-NixOS SMP Tue Mar 19 12:12:42 UTC 2019
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

Nixos unstable

**Comment by jstrachan** [comment]
vaults are only available if you install/create a cluster with `--vault` or `--ng` - did you do that?

**Comment by masseybradley** [comment]
@jstrachan is this documented somewhere / where should it be documented? Playing with `minikube` and receiving `system vault is not supported for minikube provider` errors? Digging a little I noticed ...
```
# pkg/jx/cmd/install.go
2089         if options.Flags.Provider != cloud.GKE && options.Flags.Provider != cloud.EKS && options.Flags.Provider != cloud.AWS {
2090             return fmt.Errorf("system vault is not supported for %s provider", options.Flags.Provider)
2091         }
```
... are there any plans to support vault with `minikube`?

**Comment by jstrachan** [comment]
Typically vault is used for production like environments with KMS + cloud storage; not trying things out on a developer laptop. So we've no plans to support vault on minikube any time soon - but patches always welcome though!

**Comment by masseybradley** [comment]
@jstrachan thanks for the feedback - I'm not familiar enough to propose a patch just yet but I could do a PR to document the current supported providers and the mention of vaults only being available if you install the cluster with `--vault` or `--ng` if you could point me in the right direction (I didn't see anything related to documentation in the [CONTRIBUTING.md](https://github.com/jenkins-x/jx/blob/master/CONTRIBUTING.MD).

**Comment by ccojocar** [comment]
@macalinao It is not clear to me what is the description of this issue? Do you you want a more friendly message if vault is not installed?

**Comment by macalinao** [comment]
@ccojocar Yes. I thought this would initialize Vault for me.

Another side question-- will I be able to set up Vault with `jx upgrade --vault --ng`?

**Comment by ccojocar** [comment]
The `upgrade platfrom` command does not setup a vault, only the install command. You can create a vault with `jx create addon vault-operator` and then `jx create vault <vault-name>`
