### ISSUE TITLE
PR preview app is missing link for serverless/knative apps

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#3632]
### Summary 

If you use the serverless mode https://jenkins-x.io/developing/knative/ the PR message that the preview app is ready will not show up with a link

### Steps to reproduce the behavior

Enable gloo app and serverless/knative
Open a PR to a new project in serverless style

### Expected behavior

has a link to PR app

### Actual behavior

Does not have link in PR comment (but has a comment)

### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 1.3.1114
jenkins x platform 0.0.3832
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.12.2
helm client        Client: v2.12.1+g02a47c7
git                git version 2.20.1
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

GKE
### Operating system / Environment

macos

**Comment by jstrachan** [comment]
fixed this now - release should go out soon.

BTW make sure any created quickstarts you tinker with your charts (or remove the charts and reimport) to ensure there's this in your `ksvc.yaml` file: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/maven/charts/templates/ksvc.yaml#L5-L9
