### ISSUE TITLE
Merge failed on the last stage of Jenkins-X pipeline

### ISSUE THREAD

**Issue by krishnakumar6893** [jenkins-x/jx#3634]
### Summary 

Merge failed on the last stage of Jenkins-X pipeline

### Steps to reproduce the behavior

Setup minikube locally and tried to import an existing project

### Expected behavior

Should be promoted to staging environment

### Actual behavior

merge status: error URL: http://jenkins.jx.192.168.99.162.nip.io/job/krishnakumar6893/job/environment-fairylead-staging/job/master/4/display/redirect description: This commit cannot be built

This works when we create quickstart for Nodejs application, it throws above error when importing.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.1116
Kubernetes cluster v1.14.0
kubectl            v1.13.2
helm client        v2.13.1+g618447c
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

### Jenkins type

- [ ] Classic Jenkins

### Operating system / Environment

Ubuntu 18.04

**Comment by jstrachan** [comment]
any chance you could view the build log of the master branch of the staging repository to find out what the error is?

e.g. the log of  http://jenkins.jx.192.168.99.162.nip.io/job/krishnakumar6893/job/environment-fairylead-staging/job/master/4

**Comment by krishnakumar6893** [comment]
@jstrachan I don't see any specific logs for above error, only the commit failed error message.
It succeeds for quickstart application.

**Comment by jstrachan** [comment]
the error message will be in the promotion pipeline in the staging environment.

If quickstarts work but your custom pipeline doesn't I suspect you are either not producing the helm chart with the right name/version that matches the promotion Pull Request or there's an issue with your helm chart - but without the log of the failed promotion pipeline we're just guessing
