### ISSUE TITLE
Failure when running jx create terraform

### ISSUE THREAD

**Issue by micke** [jenkins-x/jx#3640]
### Summary 
Getting the following error when trying to create a jx setup with terraform, bot locally and in a fresh cloud shell on GCP.

```
WARN[0099] WARNING: The current user cannot query secrets in the namespace default: Failed to create a Kubernetes client unable to load i
n-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
error: failed to find development namespace: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT
 must be defined
```

Tried locally with `jx create terraform --skip-login --verbose --ng --git-private --jx-environment=tools --gke-preemptible --gke-use-enhanced-apis --gke-use-enhanced-scopes --docker-registry=eu.gcr.io --docker-registry-org redacted -c tools=gke -c sandbox=gke -c staging=gke -c prod=gke`

And by following the exact steps at https://jenkins-x.io/getting-started/tutorials/#installing-jx-on-gke-with-terraform

### Steps to reproduce the behavior
Follow https://jenkins-x.io/getting-started/tutorials/#installing-jx-on-gke-with-terraform

### Expected behavior
To be able to create cluster with terraform and get a serverless jenkins-x environment.
At the very least being able to follow the steps at https://jenkins-x.io/getting-started/tutorials/#installing-jx-on-gke-with-terraform

### Actual behavior
![image](https://user-images.githubusercontent.com/22270/56164155-63942400-5fd0-11e9-8312-0c2b8d1d6185.png)

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               2.0.1
git              git version 2.11.0
Operating System Debian GNU/Linux 9.8 (stretch)
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

N/A. Trying to create with the CLI

### Operating system / Environment
macOS Mojave and Cloud Shell on GCP

**Comment by helhindi** [comment]
+1 - Same issue when following the guide here:
https://jenkins-x.io/news/terraform-jenkins-x/

`$ jx create terraform -c dev=gke -c stage=gke -cprod=gke`
`WARN[0053] WARNING: The current user cannot query secrets in the namespace myproject: Failed to get the development environment Get https://192.168.64.3:8443/api/v1/namespaces/myproject: dial tcp 192.168.64.3:8443: i/o timeout
error: failed to find development namespace: Get https://192.168.64.3:8443/api/v1/namespaces/myproject: dial tcp 192.168.64.3:8443: i/o timeout`

`$ jx version`
`Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:15:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: dial tcp 192.168.64.3:8443: i/o timeout`

**Comment by joostvdg** [comment]
I ran into the same problem, working on a PR (https://github.com/jenkins-x/jx/pull/3739) that solves the issue for me. Feel free to come up with a better solution though, not entirely sure about this approach.

**Comment by micke** [comment]
@joostvdg thanks for working on fixing this issue! I will try to see if your change fixed my issue tomorrow!
