### ISSUE TITLE
jx upgrade platform fails on chartmuseum update

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#365]
> Using:
> NAME        VERSION
> jx          1.0.125
> Jenkins X   0.0.283
> Kubernetes  v1.7.12-gke.1
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

Actions:
`jx upgrade platform`

A new jenkins-x-chartmuseum pod is created but the old pod is not deleted, so it holds the lock on the persistent volume. The new pod then throws the error:

```
Unable to mount volumes for pod "jenkins-x-chartmuseum-2048894958-jzg7p_jx(07723f4a-22c6-11e8-84cc-42010a9a003a)": timeout expired waiting for volumes to attach/mount for pod "jx"/"jenkins-x-chartmuseum-2048894958-jzg7p". list of unattached/unmounted volumes=[storage-volume]

Multi-Attach error for volume "pvc-a697f811-1da4-11e8-84cc-42010a9a003a" Volume is already exclusively attached to one node and can't be attached to another
```

Manually deleting the first pod allowed the second pod to grap the volume whilst the first was being replicated. Once the second pod was successfully instantiated, the newly created third pod from the old replicaset was automatically removed, suggesting that there is an issue with the sequence of operations?

**Comment by imorti** [comment]
Yeah, I'm having this problem as well. Not even during an upgrade.

**Comment by jtnord** [comment]
@tdcox is this still an issue with the latest jx versions?

**Comment by ccojocar** [comment]
I can reproduce this issue. It seems to be outdated.
