### ISSUE TITLE
Support password protected helm repos for apps

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3656]
### Summary 
Fixed by #3586 

If you have a password protected helm repo, store the username and password in vault so that other people using the cluster (or a job) can use the repo later without reentering creds

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@pmuir I think this is done. The helm repository password seems to be retrieved now from vault. I am closing it.
