### ISSUE TITLE
Support vault URLs in templates

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3657]
### Summary 
Support replacing tokens with URIs in `values.yaml` and then replace them when the chart is applied

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins

**Comment by ccojocar** [comment]
@pmuir Can we close this issue? This feature is implemented.

**Comment by ccojocar** [comment]
This seems to be already implemented. See the vault secrets interpolation in the `values.tmpl.yaml`.
