### ISSUE TITLE
jx preview overrides my values.yaml image name in preview chart

### ISSUE THREAD

**Issue by RiceBowlJr** [jenkins-x/jx#3683]
### Summary 

When doing a `jx preview --app <my-app>`, `jx` does overrides the image name I define i nmy values.yaml for preview chart.
This put the image name `repo/org/app` by default without using the one I set in my values.yaml. So I cannot use the name I want for my repositories to use the `jx preview` feature.

### Steps to reproduce the behavior

Use my pipeline here:

```
          container('docker') {
            sh "docker build -t $JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST/$SERVICE:${PREVIEW_VERSION} -f ./Dockerfile ."
            sh "docker push $JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST/$SERVICE:${PREVIEW_VERSION}"
          }
          dir ('./charts/preview') {
            container('jx-cli') {
              sh "make preview"
              sh "jx preview --app $APP_NAME --dir ../.. --tls-acme=\"true\""
            }
          }
```

Use the default values in the preview Helm chart.
Customize the Makefile within the preview chart like so:

```
...
else ifeq ($(OS),Linux)
	sed -i -e "s/version:.*/version: $(PREVIEW_VERSION)/" Chart.yaml
	sed -i -e "s/version:.*/version: $(PREVIEW_VERSION)/" ../*/Chart.yaml
	sed -i -e "s|repository:.*|repository: $(JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST)\/<app>|" values.yaml
	sed -i -e "s/tag:.*/tag: $(PREVIEW_VERSION)/" values.yaml
...
```

### Expected behavior

I expect that it deploys my app in a preview env with the image name I specified in my values.yaml (otherwise why do I set it here?).

### Actual behavior

It deploys my app with an overrided image name constructed with `<docker_registry>/<github_org>/<github_repo>`.

I did quite some digging and found out [where the errors occurs](https://github.com/jenkins-x/jx/blob/25201d9063d1b6853b3e09435c187e744aed64b6/pkg/jx/cmd/preview.go#L901). It is in the `jx preview` command, you can find that the image and tag are set directly into the code without any flexibility from the `repo/org/app` pattern.

### Jx version

The output of `jx version` is:

```
2.0.6
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

AWS EKS cluster spawn with my own Terraform template.

### Operating system / Environment

In a Docker container within a DevPod. The container is FROM alpine:3.9.3, I added git, build-base, jx, helm.

**Comment by lgg42** [comment]
Same thing over here. We want to use a different registry for the preview snapshots and we also note that even if `make preview` does the substitution well, the command `jx preview` outputs something different.

**Comment by lgg42** [comment]
@RiceBowlJr hey! Have you had the chance to test if maybe in recent jx versions this issue is solved? Or maybe have you found any workaround?
