### ISSUE TITLE
Creating a DevPod fails

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3689]
### Summary 

Since recent releases, creating a DevPod fails.

### Steps to reproduce the behavior

Enter inside a repository

```bash
jx create devpod -b
```

### Expected behavior

DevPod is created

### Actual behavior

```
error: Failed to create pod pods "vfarcic-go" is forbidden: error looking up service account jx/tekton-bot: serviceaccount "tekton-bot" not found
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.22
jenkins x platform 2.0.78
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [X] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOOS

**Comment by vfarcic** [comment]
I suspect that the problem is in https://github.com/jenkins-x/jx/commit/b2475cde5257b04e3ae9efb51057a332afba8ca9#diff-29cb186faba8621cbbc93da2d14d63e8 . `IsJenkinsXPipelines` returns `true` even when static Jenkins is used.

**Comment by jstrachan** [comment]
were you in the `jx` namespace when you ran that command?

**Comment by vfarcic** [comment]
I was.

**Comment by vfarcic** [comment]
I tried it a few times with fresh GKE clusters.

**Comment by vfarcic** [comment]
Also, I had a workshop a few days ago and it failed for everyone (e.g., AKS, EKS, GKE). None of them changed k8s context so they were all in the `jx` Namespace.

**Comment by jstrachan** [comment]
fix on its way!
