### ISSUE TITLE
Better wording about GitHub token in `jx install`

### ISSUE THREAD

**Issue by jlong** [jenkins-x/jx#369]
The first time I ran the `jx install` command I pasted the token in the GitHub username prompt.

This is because the prompt is written this way:

    $ jx install
    Context "minikube" modified.
    Lets set up a git username and API token to be able to perform CI / CD

    To be able to create a repository on GitHub we need an API Token
    Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook

    Then COPY the token and enter in into the form below:
    
    ? GitHub user name: a239234ae734234bfa234237ae134234bf
    ? API Token: 

I read the part about copying the token into the form below but failed to realize I needed to enter my username first.

I'd suggest that we update it to work like this:

    $ jx install
    Context "minikube" modified.
    Lets set up a git username and API token to be able to perform CI / CD.

    ? GitHub user name: jlong

    To be able to create a repository on GitHub we need an API Token
    Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook

    Then COPY the token and PASTE it below:

    ? API Token: a239234ae734234bfa234237ae134234bf

**Comment by jstrachan** [comment]
sounds good to me!
