### ISSUE TITLE
Jx 2.0 install command should ask about Tiller configuration option in survey

### ISSUE THREAD

**Issue by igdianov** [jenkins-x/jx#3690]
### Summary 

The default for `jx install` has changed from `--no-tiller=false` in 1.3.x to `--no-tiller=true` in 2.0.x It is not desirable to change defaults for Static Jenkins Master setup without asking the user to use Tillerless Helm. 

It would be much better to ask user in the survey.

### Steps to reproduce the behavior

`jx install` or `jx create` uses `--no-tiller=true` by default  

### Expected behavior

`jx install` or `jx create` should ask about Helm Tiller/Tillerless option in the survey

### Actual behavior

`jx install` or `jx create` does not ask the user.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.22
jenkins x platform 0.0.3588
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.13.4
helm client        v2.12.2+g7d2b0c7
helm server        v2.12.2+g7d2b0c7
git                git version 2.18.0.windows.1
Operating System   Windows 10 Pro 1809 build 17763
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

```
git                git version 2.18.0.windows.1
Operating System   Windows 10 Pro 1809 build 17763
```

**Comment by pmuir** [comment]
This was one of the changes that prompted the bump to 2.0. I don't think we'll be adding this to the survery.
