### ISSUE TITLE
jx create devpod -l cshap error

### ISSUE THREAD

**Issue by iswing** [jenkins-x/jx#3693]
### Summary 
jx create devpod -l csharp  
error: Invalid option: --label csharp

then i try

jx create devpod -l jx-base                                                                                      
 Creating a DevPod of label: jx-base
error: Failed to create pod Pod "myname-jx-base" is invalid: [spec.containers[0].ports[0].containerPort: Required value, spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/var/run/docker.sock": must be unique]

### Expected behavior
create devpod success
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.11
jenkins x platform 2.0.72
Kubernetes cluster v1.13.1
kubectl            v1.11.3
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14 build 18A391
```

### Jenkins type

Next Generation (Tekton + Prow)

**Comment by pmuir** [comment]
The valid options are 

```aws-cdk, dlang, go, gradle, jx-base, machine-learning, maven, maven-java11, maven-nodejs, newman, nodejs, nodejs10x, nodejs8x, promote, python, python2, python37, ruby, rust, scala, swift, terraform```

**Comment by pmuir** [comment]
If you want to contribute dotnet support, please say

**Comment by stepanselyuk** [comment]
@pmuir so is there a way to use `jx-base` for devpod? 
Related https://github.com/jenkins-x/jx/issues/5026
