### ISSUE TITLE
GitOps and multiple clusters

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#3695]
### Summary 
When installing using GitOps, jx creates a local folder called jenkins-x-dev-environment, regardless of the the prefixes used for all the environments. As a result, if a second cluster is created from the same working directory, the dev environments will clash.

This occurs before the questionnaire about creating the GitOps dev environment so the damage is done before the user is made aware that there may be a problem.

This may be the desired behaviour to migrate a configuration from one cluster instance to another but it would be good to check at the start of the install and warn the user in case they are unaware of the new behaviour.

### Jx version

The output of `jx version` is:

```
x                 2.0.22
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.13.4
helm client        Client: v2.13.0+g79d0794
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by pmuir** [comment]
Already fixed
