### ISSUE TITLE
error when applying patch

### ISSUE THREAD

**Issue by mrtylerzhou** [jenkins-x/jx#3696]
version latest:

when use jx install --no-tiller

get the following error,can any one have any idears about what the problem is and how to resolve it?

Error from server (Invalid): error when applying patch:
{"spec":{"clusterIP":""}}
to:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "jxing-nginx-ingress-default-backend", Namespace: "kube-system"
Object: &{map["status":map["loadBalancer":map[]] "kind":"Service" "apiVersion":"v1" "metadata":map["annotations":map["jenkins.io/chart":"nginx-ingress" "jenkins.io/chart-app-version":"0.22.0" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"jenkins.io/chart\":\"nginx-ingress\",\"jenkins.io/chart-app-version\":\"0.22.0\"},\"labels\":{\"app\":\"nginx-ingress\",\"chart\":\"nginx-ingress-1.3.1\",\"component\":\"default-backend\",\"heritage\":\"Tiller\",\"jenkins.io/chart-release\":\"jxing\",\"jenkins.io/version\":\"1.3.1\",\"release\":\"jxing\"},\"name\":\"jxing-nginx-ingress-default-backend\",\"namespace\":\"kube-system\"},\"spec\":{\"clusterIP\":\"\",\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\",\"targetPort\":\"http\"}],\"selector\":{\"app\":\"nginx-ingress\",\"component\":\"default-backend\",\"release\":\"jxing\"},\"type\":\"ClusterIP\"}}\n"] "name":"jxing-nginx-ingress-default-backend" "namespace":"kube-system" "selfLink":"/api/v1/namespaces/kube-system/services/jxing-nginx-ingress-default-backend" "uid":"46d84f9b-64ed-11e9-a627-0050568417a2" "resourceVersion":"6561743" "creationTimestamp":"2019-04-22T10:56:27Z" "labels":map["release":"jxing" "app":"nginx-ingress" "chart":"nginx-ingress-1.3.1" "component":"default-backend" "heritage":"Tiller" "jenkins.io/chart-release":"jxing" "jenkins.io/version":"1.3.1"]] "spec":map["ports":[map["port":'P' "targetPort":"http" "name":"http" "protocol":"TCP"]] "selector":map["app":"nginx-ingress" "component":"default-backend" "release":"jxing"] "clusterIP":"10.99.95.127" "type":"ClusterIP" "sessionAffinity":"None"]]}
for: "/tmp/helm-template-workdir-384071021/jxing/output/nginx-ingress/templates/default-backend-service.yaml": Service "jxing-nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable

**Comment by mrtylerzhou** [comment]
i noticed that the `jxing-nginx-ingress-controller `service is always in a state of pending

**Comment by mrtylerzhou** [comment]
nearly none of the pod at state of running,myabe the image repo can not be accessed in cn,I hope you can push the images to dockerhub(most of times it can be visited,althrough it is very slow),or you can make another plan to install it ,but not use command(privide yaml files)

**Comment by jstrachan** [comment]
what kind of kubernetes cluster do you have? the diagnostic steps here could help: https://jenkins-x.io/faq/issues/#jenkins-x-does-not-startup

**Comment by jstrachan** [comment]
whats the output of these commands:
```
jx version
jx status
kubectl get pvc
kubectl get pod
```

**Comment by afirth** [comment]
I get this on init when I don't set --domain and the cluster doesn't yet have an ingress controller

**Comment by deanesmith** [comment]
Hi @mrtylerzhou, I believe this issue has been resolved, especially if you take advantage of [JX Boot](https://jenkins-x.io/getting-started/boot/)
