### ISSUE TITLE
Staging Application Returning 502 Bad Gateway

### ISSUE THREAD

**Issue by alancphilpott** [jenkins-x/jx#3697]
### Summary 
After merging a pull request to master, the application is deployed successfully to the staging environment but when trying to access the URL, the web page is showing "502 Bad Gateway".

### Steps to reproduce the behavior
Application created through the Google Cloud Shell. I then created a Spring Project with the required dependencies. I created a new branch for the application where I added all project files such as the source folder and updated POM file. I created pull request and the pipeline successfully ran and produced a link to a preview application, the preview was unavailable when visiting the link (503 Service Temporarily Unavailable). I ignored the fact the preview application was not working as the pipeline was passing, and merged to pull request to master. The master pipeline then ran and succeeded and produced the staging application URL, I visited this URL and received the 502 Bad Gateway.

### Expected behavior
Application is available for preview through the staging application link.

### Actual behavior
Staging application page shows 502 Bad Gateway.

### Jx version

The output of `jx version` is:
jx                 2.0.22
jenkins x platform 2.0.78
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.11.9-dispatcher
helm client        Client: v2.13.1+g618447c
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.8 (stretch)

### Jenkins type
Static Jenkins and Jenkinsfiles
Kubernetes Workloads: Automated CI+CD with GitOps Promotion

### Kubernetes cluster
The kubernetes cluster was created through executing the "jx create cluster gke" command using the default pod sizing and domain settings.

### Operating system / Environment
All jx commands are performed through the Google Cloud Shell.

Some more information which I think may help. If I'm not mistaken, the dev environment should have a source reference to repository holding the application which was created through the "jx create spring" command.

![Capture](https://user-images.githubusercontent.com/22529612/56501644-68dcfb80-6507-11e9-87ac-8c504a405fb1.PNG)

**Comment by jstrachan** [comment]
try `kubectl get pod -n jx-staging` to see the status of your application in staging - it could just be the pod was starting up slowly - but could also be that the app is failing

**Comment by jstrachan** [comment]
btw the output shows above that there are no pods running yet in the staging environment (see the blank under `PODS` in the output of `jx get applications`. It could be there was a failure in the staging pipeline on the master branch - or maybe your cluster is out of capacity to provision more pods?

Whats the output of `jx status`

**Comment by alancphilpott** [comment]
@jstrachan I was definitely under the assumption that the pod was starting up slowly due to watching numerous videos on YouTube of you demonstrating Jenkins X, although in comparison to videos a year ago, things nowadays seem a lot more snappy to spin up.

The output of `kubectl get pod -n jx-staging` is below:
![Capture](https://user-images.githubusercontent.com/22529612/56576261-cc2a6480-65bf-11e9-8457-bd12296c140f.PNG)

The output of `jx status` seems to be good:
![Capture](https://user-images.githubusercontent.com/22529612/56576330-f3813180-65bf-11e9-9c2c-037fca455d92.PNG)

**Comment by jstrachan** [comment]
looks like there is an issue with the liveness/readiness checks with that pod. 

could you run `kubectl describe pod jx-storkxxxxx -n jx-staging` and `kubectl logs -n jx-staging jx-storkxxxxx` to see why the pod is never becoming ready?

if this is a spring application, did you include the actuator as a dependency in the `pom.xml`? I suspect not...

**Comment by jstrachan** [comment]
or maybe you changed spring versions without updating the liveness probe URL? (the URL changes in different spring versions)

**Comment by EliasNeypes** [comment]
I want to add here because I am having a very similar issue and very similar symptoms.

**Expected behavior**

Application is available for preview after a PR .

**Actual behavior**

Staging application page shows 502 Bad Gateway.

**Jx version**

The output of jx version is:
_jx                 2.0.86
jenkins x platform 2.0.191
Kubernetes cluster v1.12.7
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.7.4
Operating System   Ubuntu 16.04.6 LTS_

**Jenkins type**

Static Jenkins and Jenkinsfiles
Kubernetes Workloads: Automated CI+CD with GitOps Promotion

**Kubernetes cluster**

The kubernetes cluster was created through Azure console with 2 nodes, 2 vcpus each.

**Operating system / Environment**

I'm currently using a free tier AWS EC2 VM (OS above)

**Comment by alancphilpott** [comment]
> looks like there is an issue with the liveness/readiness checks with that pod.
> 
> could you run `kubectl describe pod jx-storkxxxxx -n jx-staging` and `kubectl logs -n jx-staging jx-storkxxxxx` to see why the pod is never becoming ready?
> 
> if this is a spring application, did you include the actuator as a dependency in the `pom.xml`? I suspect not...

Thanks very much for your help James, I accidentally removed the actuator dependency from the POM file so that was causing the issue.

**Comment by jstrachan** [comment]
@EliasNeypes try `jx ns jx-staging` to switch to the staging namespace, then `kubectl get pod` to find the pod name and `kubectl describe pod xxxx` to see why it’s not running.

You could try looking at its logs (`jx logs`). It could be the liveness probe doesn’t work or the expose port is wrong

**Comment by EliasNeypes** [comment]
@jstrachan I looked at it, and there seems to be a problem with pulling image from the container registry. I performed the commands to add CR credentials in both contexts of the jx and jx-staging namespaces, but the problem persists.

**Comment by EliasNeypes** [comment]
UPDATE: I just decided to go ahead with a new cluster and fresh install of jx and everything I've seen works as expected.

**Comment by jstrachan** [comment]
great thanks! So I think this issue is fixed for now.

I’m hoping to add a better diagnostic UX soon to help folks figure out why stuff isn’t working...
