### ISSUE TITLE
jx step helm release publishes incorrect version

### ISSUE THREAD

**Issue by dvaletin** [jenkins-x/jx#3701]
### Summary 
Gitops promotion failed with error:
`Error: Can't get a valid version for repositories single-api. Try changing the version constraint in requirements.yaml'`

When examining build logs I found a strange behavior:
`+ jx step changelog --version **v0.0.480**`

`+ jx step helm release
{"level":"info","msg":"Uploading chart file **single-api-0.0.479.tgz** to http://jenkins-x-chartmuseum:8080/api/charts\n","time":"2019-04-22T17:33:01Z"}
{"level":"info","msg":"Received 201 response: {\"saved\":true}\n","time":"2019-04-22T17:33:01Z"}`
`+ jx promote -b --all-auto --timeout 1h --version **0.0.480**`

So, technically, jx step helm release uploaded previouse version tag to chartsmuseum, since it does not exists (previous build was incomplete), so current gotops promotion to staging has failed.

### Steps to reproduce the behavior

Fail build, for instance by cancelling deploy then run clean build.

### Expected behavior
jx step helm release should upload file with current build version
### Actual behavior
jx step helm release upload file with previouse build version
### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 2.0.22
jenkins x platform 2.0.78
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.11.2
helm client        Client: v2.12.2+g7d2b0c7
git                git version 2.20.1
Operating System   Mac OS X 10.14.4 build 18E226```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [ ] Next Generation (Tekton + Prow)
- [X] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->
AWS EKS, manually created and then having fresh jx install
### Operating system / Environment
OSX
<!--
In which environment are you running the jx CLI?
-->

**Comment by dvaletin** [comment]
Was our issue, our builder app were updating VERSION file silently, which confused jenkins pipeline.

**Comment by rawlingsj** [comment]
thanks for reporting back @dvaletin :)
