### ISSUE TITLE
WARN[0001] Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...

### ISSUE THREAD

**Issue by npolagani** [jenkins-x/jx#3702]
### Summary 

jx get eks is not showing existing cluster

jx version has below output:

WARN[0001] Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings... 
NAME               VERSION
jx                 2.0.22
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.10.11
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.21.0

### Steps to reproduce the behavior

jx version

### Expected behavior

jx get eks should show the clusters

### Actual behavior

no output

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
WARN[0001] Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings... 
NAME               VERSION
jx                 2.0.22
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.10.11
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.21.0

**Comment by jstrachan** [comment]
this command currently only works if you are connected to a Jenkins X cluster and are in a team namespace. I suspect if you do `jx ns jx` first - assuming you are connected to a cluster with Jenkins X installed it may work better

**Comment by npolagani** [comment]
I did try to install JX in an existing cluster and faced above issues.  now I have created a new cluster with jx and I don't see the issue now.  Thanks.  Please close the ticket.

**Comment by dinagit2711** [comment]
I have done done my setup on window's 10 getting the below warning 
c:\kubernetes>jx version
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'kube-system': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
NAME               VERSION
jx                 2.0.579
Kubernetes cluster v1.14.0
kubectl            v1.14.0
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.3+g0e7f3b6
git                2.22.0.windows.1
Operating System   Windows 10 Home Single Language 1803 build 17134

**Comment by fbucci1** [comment]
I am getting the same warning. Installed git, helm and jx using official installation instructions.

$jx version
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
NAME               VERSION
jx                 2.0.998
Kubernetes cluster v1.16.3
kubectl            v1.16.3
git                2.18.1
Operating System   CentOS Linux release 8.0.1905 (Core)


verifying packages
? A local Jenkins X versions repository already exists, pulling the latest: Yes

**Comment by sanrum21** [comment]
i am also getting the same warning. installed jx on already existing cluster and also ran "jx complaince run" command . When i executed jx version , i get warning about the default namespace. 
# jx version
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
NAME               VERSION
jx                 2.0.1275
Kubernetes cluster v1.13.10
kubectl            v1.13.10
git                1.8.3.1
Operating System   Unknown Linux distribution Linux version 3.10.0-1062.9.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Dec 6 15:49:49 UTC 2019


Can any one help here .
