### ISSUE TITLE
Installing jx on gke with --vault and --batch-mode requires user input

### ISSUE THREAD

**Issue by danielleffler** [jenkins-x/jx#3705]
### Summary 
Installing jx on gke with --vault and --batch-mode requires user input
### Steps to reproduce the behavior
jx install \
--provider gke \
--git-username ${GIT_USERNAME} \
--git-api-token ${GIT_API_TOKEN} \
--environment-git-owner ${GIT_USERNAME} \
--default-environment-prefix ${NAME} \
--no-tiller \
--vault \
--git-private \
--batch-mode
### Expected behavior
It should install without user input and accept a --zone
### Actual behavior
There isn't an option to pass in a zone therefore it prompts user to select
### Jx version

The output of `jx version` is:

```
jx                 1.3.1114
jenkins x platform 2.0.80
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

1.11.8-gke.6 created on GKE via jx binary
### Operating system / Environment

docker container

**Comment by afirth** [comment]
It also prompts for the project-id, and this option is also not supported.
