### ISSUE TITLE
log output is mostly unintelligable on windows

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#3708]
### Summary 

the log format has changed and is no longer being colourised correctly on windows, which is causing the logs to be hard to read.

#3624 introduced this issue with the log migration.

### Steps to reproduce the behavior

run a jx command which produces some logging on windows

### Expected behavior

output is colourized

### Actual behavior

output contains ansi escape sequences/

### Jx version

The output of `jx version` is:

```
c:\Users\jnord\go\src\github.com\cloudbees\core-backend>jx version
NAME               VERSION
jx                 2.0.22
jenkins x platform 2.0.88
Kubernetes cluster v1.12.6-gke.10
kubectl            v1.13.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.16.2.windows.1
Operating System   Windows 10 Pro 1809 build 17763
time="2019-04-23T13:16:39+01:00" level=warning msg="\nA new \x1b[32mjx\x1b[0m version is available: \x1b[32m2.0.24\x1b[0m\n"
? Would you like to upgrade to the new jx version? Yes

time="2019-04-23T13:47:09+01:00" level=info msg="Downloading \x1b[32mhttps://github.com/jenkins-x/jx/releases/download/v2.0.25/jx-windows-amd64.zip\x1b[0m to \x1b[32mC:\\tools\\jx.exe.tmp\x1b[0m...\n"
time="2019-04-23T13:47:36+01:00" level=info msg="Downloaded \x1b[32mC:\\tools\\jx.exe.tmp\x1b[0m\n"
time="2019-04-23T13:47:38+01:00" level=info msg="Jenkins X client has been installed into \x1b[32mC:\\tools\\jx.exe\x1b[0m\n"```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [x] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [x] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->

### Operating system / Environment

<!--
In which environment are you running the jx CLI?
-->

**Comment by igdianov** [comment]
https://github.com/jenkins-x/jx/issues/3688

**Comment by jtnord** [comment]
issue is present in  `v1.3.1112` but not in  `v1.3.1111`  looks suspisiously like the logging upgrade.

**Comment by jtnord** [comment]
confirmed introduced in commit a04fc962c5c1c4bf9676064fcf6c69ae50d9eb9d
which is #3624

**Comment by jtnord** [comment]
this looks like a log formatting issue.
on Linux you have
> `INFO[0000] Blah`
on windows you have a timestamp and level and message
> `time="2019-04-23T13:47:09+01:00" level=info msg="Blah\n"`
thus rather than printing the message as is it is escamping it into the message string.

**Comment by jtnord** [comment]
the [`IsInCluster`](https://github.com/jenkins-x/jx/blob/ce26a168cf589990715c446943594cf86430cab8/pkg/log/log.go#L18-L24) is returning true on windows which is returning the json formatter incorrectly.

**Comment by jtnord** [comment]
seems to be https://github.com/sirupsen/logrus/issues/763

**Comment by jtnord** [comment]
https://github.com/sirupsen/logrus/pull/957
