### ISSUE TITLE
jx get preview --current --url-only

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3713]
### Summary 

`jx get preview` cannot retrieve only the address, instead of a log entry.

### Steps to reproduce the behavior

```bash
jx get preview --current -o jsonpath="{.msg}"
```

### Expected behavior

Only the message (it contains only the URL).

### Actual behavior

Log output. `-o` is ignored (not implemented).

**Comment by deanesmith** [comment]
Hi @vfarcic, is this still an issue?

**Comment by vfarcic** [comment]
Now it's worse and I cannot even execute `jx get preview --current`. Now I'm getting `error: No $JOB_NAME defined for the current pipeline job to use`.

**Comment by hferentschik** [comment]
@vfarcic, where and how do you want to run `jx get preview --current`? Have you seen the help for this command:

```
# View the current preview environment URL
# inside a CI pipeline
jx get preview --current
```

The intent of the command is to run in the pipeline where it has the available context information, aka the "current" build. 

What is the semantics you would expect from `jx get preview --current`? `jx get preview` can be run from anywhere listing all previews, what do you expect from `--current`.

My guess is that you expect this to be run from a given checkout of a project and you want to get the latest (in terms of time) deployed preview for this project.

**Comment by hferentschik** [comment]
@vfarcic could you also explain:

> jx get preview cannot retrieve only the address, instead of a log entry.

With "address", you mean the preview URL right? And with log entry a row in the default output of `jx get preview`?

> jx get preview --current -o jsonpath="{.msg}"

I am not following on the -o option? I guess you envision `jx get preview --current ` to display something in the same form as the default output, but filtered by 'current' (see discussion above) and then you'd like an additional -o option to select a specific value/column of this output, right?

**Comment by hferentschik** [comment]
Ahh, and in the title you mention `--url-only`. Is this an alternative for `-o`? Would you prefer a specific `--url-only` or a more generic `-o`?

**Comment by vfarcic** [comment]
We can close this issue. It's been over 6 months since I created it and I do not even remember anymore what's it about.
