### ISSUE TITLE
Can not use gitlab hosted on non-root domain

### ISSUE THREAD

**Issue by olivierboudet** [jenkins-x/jx#3721]
### Summary 

I try to use jx with a gitlab hosted on http://mydomain.com/gitlab but the jx command try to get the git server with root URL only.

### Steps to reproduce the behavior

I created the git server with this command : 
```
$ jx create git  server --kind gitlab --url http://mydomain.com/gitlab/
```

When trying to edit an environment, I have this error : 
```
error: no Git service resource found with URL 'http://mydomain.com' in namespace jx
```
If I create another git server with the root domain URL only as following, I can edit the environment by specifing --git-provider-url. 
```
$ jx create git  server --kind gitlab --url http://mydomain.com
$ jx edit environment integration --git-provider-kind gitlab --git-private --git-provider-url http://mydomain.com/gitlab/ --domain integration.mydomain.com --git-url http://mydomain.comt/gitlab/my-group/environments/integration
INFO[0027] Created Jenkins Project: http://jenkins.jx.tools.mydomain.com/job/gitlab/job/my-group/ 

INFO[0027] Note that your first pipeline may take a few minutes to start while the necessary images get downloaded!
```
### Expected behavior

I can use a gitlab server hosted on non-root domain without creating a fake git server in jx.
The name of the folder and project in Jenkins is correct.

### Actual behavior

I have to create a fake git server with url http://mydomain.com even if my gitlab server is hosted at http://mydomain.com.gitlab.
In Jenkins, I have a folder named gitlab (the URL context of gitlab on my domain) and a project called my-group (the name of the group in gitlab in which I have created my git repository to host environment configuration).

Also there is no credentials created in Jenkins, so my project has this error : "Cannot find any credentials with id jx-pipeline-git-gitlab-gitlab".

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.37
jenkins x platform 0.0.3877
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.13.4
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Existing GKE cluster

### Operating system / Environment
 Ubuntu 18.04.2 LTS

**Comment by olivierboudet** [comment]
I have a similar issue with trying to promote an application. My environment is declared as follow : 
```
$ jx get environments
NAME        LABEL       KIND        PROMOTE NAMESPACE   ORDER CLUSTER              SOURCE                                                                    REF    PR
dev         Development Development Never   jx          0                                                                                                           
integration Integration Permanent   Auto    integration 100   https://xxx.xxx.xxx.xxx http://mydomain.com/gitlab/my-group/environments/integration master 
```

When I promote my application the URL used to connect to gitlab API is not correct, the context root /gitlab is missing : 
```
 $ jx promote -b --all-auto --timeout 1h --version 1.5.0-SNAPSHOT
Promoting app my-app version 1.5.0-SNAPSHOT to namespace integration
pipeline gitlab/my-group/develop
error: GET http://mydomain.com/api/v4/users/gitlab/projects: 404 {message: }

```

**Comment by deanesmith** [comment]
Hi @olivierboudet,

We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.  You will find early support for Gitlab available now for Tekton pipelines using Lighthouse - our own Prow substitute.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
