### ISSUE TITLE
jx does not respect `docker-registry.enabled: true` in myvalues.yaml

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3725]
### Summary 

Since recently, jx does not respect `docker-registry.enabled: true` in myvalues.yaml. Builds are failing by trying to push container images to Google Container Registry.

### Steps to reproduce the behavior

```bash
PROJECT=[...] # Replace `[...]` with the name of the GCP project (e.g. jx).

echo "docker-registry:
  enabled: true
" | tee myvalues.yaml

jx create cluster gke \
    -n jx-rocks \
    -p $PROJECT \
    -r us-east1 \
    -m n1-standard-2 \
    --min-num-nodes 1 \
    --max-num-nodes 2 \
    --default-admin-password=admin \
    --default-environment-prefix tekton \
    --git-provider-kind github \
    --namespace cd \
    --prow \
    --tekton \
    -b

jx create quickstart \
  -l go \
  -p jx-prow \
  -b

jx get build logs
```

Part of the output of the last command.

```
error pushing image: failed to push to destination gcr.io/devops24-book/jx-prow:0.0.1: DENIED: Token exchange failed for project 'devops24-book'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
{"component":"entrypoint","error":"wrapped process failed: exit status 1","level":"error","msg":"Error executing test process","time":"2019-04-24T12:29:21Z"}
```

### Expected behavior

Image is pushed to the registry in the cluster.

### Actual behavior

Image is pushed to the service registry and it failed. The problem is not the failure itself, but that the image is NOT pushed to the in-cluster registry.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.33
jenkins x platform 2.0.106
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by vfarcic** [comment]
I'm convinced that this problem was caused either by a release in the last 24 hours or there's something new/different in GKE.

**Comment by jstrachan** [comment]
hmm - I just created a tekton cluster on GKE and a promotion worked fine

**Comment by jstrachan** [comment]
btw there's no need to add `docker-registry.enabled: true` either

**Comment by jstrachan** [comment]
is it getting the wrong google project name (for the image) I wonder?

**Comment by vfarcic** [comment]
Did you use the same command to create the cluster as me? If you did, I guess that the only difference between the two would be in our local `~/.jx` directories. Let me delete it and create the cluster again...

**Comment by vfarcic** [comment]
I just removed the whole `~/.jx` and recreated the cluster without the batch mode (but with the same arguments as before). It failed in the same place.

In your case @jstrachan, did it push to the in-cluster registry instead of GCR? I noticed even before this issue that `jx` pushes to GCR no matter whether we choose that or not. It's just that now it fails to do so. In either case, I believe that the problem is probably in what you said. The name of the image is wrong.

**Comment by vfarcic** [comment]
I removed GCR repositories and it worked. So the error is gone, but the base problem still persists. jx in GKE pushes images to GCR no matter whether that was selected when creating the cluster or not.

Should I close this issue and open another one?

**Comment by EamonKeane** [comment]
@vfarcic the reason is that `jenkins-x-platform` in `jx-2 `is a subchart, and so when `myvalues.yaml` is merged by `jx` into the global `values.yaml` it is namespaced (`jenkins-x-platform.docker-registry.enabled`).

In helm conditions on chart requirements need to be set at the global level. In the short term, the solution is to not run `jx step env apply` until after you have added `docker-registry: enabled: true` to the top-level `values.yaml`.

https://helm.sh/docs/developing_charts/
```
Tags and Condition Resolution
Tags and conditions values must be set in the top parent’s values.
```

**Comment by grassiale** [comment]
I opened this: https://github.com/jenkins-x/jenkins-x-platform/pull/5710 just yesterday in order to try to address the issue reported by @EamonKeane, because I have the same behavior with chartmuseum and nexus when I want to use externally linked ones .
