### ISSUE TITLE
Undefined fields in jenkins-x.yml or pipeline.yaml are silently ignored

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#3728]
### Summary 

Because we're using `yaml.Unmarshal` and not `yaml.UnmarshalStrict` (see #3544 for my first discussion on that front), fields in `jenkins-x.yml` or `pipeline.yaml` are silently ignored if they don't correspond to a field in the underlying structs. This means that you could have the wrong syntax but not know it, which is non-ideal.

### Steps to reproduce the behavior

Add a random field to `jenkins-x.yml`. Nothing fails.

### Expected behavior

There should be a validation failure, pointing out the field you added that isn't defined, with full qualification (`yaml.UnmarshalStrict` just gives you `key`, not `full.path.to.key`, so that's not good enough either).

### Actual behavior

No error, the unknown field is just ignored.

### Jx version

The output of `jx version` is:

```
jx                 2.0.0-dev+27e543059
jenkins x platform 0.0.3877
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.1
helm client        Client: v2.12.3+geecf22f
git                git version 2.20.1
Operating System   Ubuntu 18.04.1 LTS```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

Doesn't really matter, but OS X and Ubuntu.

**Comment by tdcox** [comment]
I have found this particularly frustrating over the past few days whilst trying to puzzle out the syntax. In my experience, one of the worst problems with this type of solution is silent failures in config that lead to unexpected downstream behaviour as they are impossible to debug without expert system knowledge. Strict validation should help avoid that.
