### ISSUE TITLE
generate-openapi isn't using a pinned version

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#3738]
### Summary 

In the refactor of codegen a month ago, some logic was missed and now it always uses latest of `openapi-gen`, which is...not what we want.

### Steps to reproduce the behavior

Run `make generate-openapi` on `master`. 

### Expected behavior

Generated files should not have changed.

### Actual behavior

Generated files did, in fact, change.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.0-dev+77369785a
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.12.0
helm client        Client: v2.12.3+geecf22f
git                git version 2.19.0
Operating System   Mac OS X 10.13.5 build 17F77
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

Mac, Linux, whatever. =)

**Comment by pmuir** [comment]
Done a while back
