### ISSUE TITLE
jx install --ng fails when deploying tekton

### ISSUE THREAD

**Issue by wadadli** [jenkins-x/jx#3741]
### Summary 

A `jx install --ng` fails when deployed using a vanilla `.jx` and a vanilla GKE cluster.

### Steps to reproduce the behavior
1) stand a new GKE cluster up using terraform 
2) remove the jx dir in $HOME
`rm --recursive --force ~/.jx`
3) reinstall jx as per guide 
4) begin an install using the following comand:
`jx install --namespace=serverless --ng --environment-git-owner=[redacted] --domain=[redacted] --default-environment-prefix=releng --git-private --git-username=[redacted] --git-api-token=[redacted] --provider=gke --ingress-namespace=kube-system --ingress-deployment=nginx-ingress-controller --ingress-service=nginx-ingress-controller`

### Expected behavior
jx installs successfully on a GKE cluster

### Actual behavior
The installation fails with this error
```
error: applying the GitOps development environment config: appyting the dev environment configuration: building helm chart in dir /home/null/jenkins-x-dev-environment/env: failed to lint the chart '/home/null/jenkins-x-dev-environment/env': failed to run 'helm lint' command in directory '/home/null/jenkins-x-dev-environment/env', output: '==> Linting .
[ERROR] templates/: render error in "env/charts/tekton/templates/250-git-secret.yaml": template: env/charts/tekton/templates/250-git-secret.yaml:4:43: executing "env/charts/tekton/templates/250-git-secret.yaml" at <b64enc>: invalid value; expected string
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.38
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.20.1
Operating System   Fedora release 29 (Twenty Nine)
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
GKE created using TF

### Operating system / Environment
Fedora release 29 (Twenty Nine)

**Comment by wadadli** [comment]
*NB:* I have also tried the installation without the `--namespace` option and have gotten the same issue.

**Comment by rawlingsj** [comment]
Could you try to delete your local `~/.jx` folder and try again please?

**Comment by wadadli** [comment]
> Could you try to delete your local `~/.jx` folder and try again please?

I have.. I think I have tried just about everything at this point.  I've been trying to install for 48 hours pretty much heh

**Comment by jhonissouza-ignite** [comment]
Same error here, the only difference is that I'm trying to just follow the tutorial (https://jenkins-x.io/getting-started/tutorials/) and not installing on a preexisting cluster.
@wadadli have you found a solution to this?
