### ISSUE TITLE
Failed to compile java11 source

### ISSUE THREAD

**Issue by aucfan-makise** [jenkins-x/jx#3742]
### Summary 
`buildPack: maven-java11` is specified in `jenkins-x.yaml` but `gcr.io/jenkinsxio/builder-maven` is used as containers' image.

### Steps to reproduce the behavior

```
jx create spring -d web -d actuator -j 11
```

### Expected behavior
`builder-maven-java11` is used to build.

### Actual behavior
Build failed.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project spring-test: Fatal error compiling: invalid target release: 11 -> [Help 1]
```

I have checked the created task and found that `builder-maven` is used as containers' image.

### Jx version

The output of `jx version` is:

```
jx                 2.0.41
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.0
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

EKS

### Operating system / Environment
OS X

**Comment by aucfan-makise** [comment]
I guess below code are cause of the problem.

https://github.com/jenkins-x/jx/blob/77369785a09984be79ee69edfb241203ce473ca9/pkg/jx/cmd/step_create_task.go#L537

https://github.com/jenkins-x/jenkins-x-platform/blob/44456a90a75fc757b89c1f67bfec72a53d9a0ace/jenkins-x-platform/values.yaml#L1033

https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/maven-java11/pipeline.yaml#L5

**Comment by babadofar** [comment]
The quickstart for java-11 fails due to this
https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/issues/69

**Comment by babadofar** [comment]
A workaround for this is to define the jenkins-x.yml like this

```
buildPack: maven-java11
pipelineConfig:
  agent:
    image: maven-java11
```

**Comment by RafalKorepta** [comment]
@jstrachan Maybe build pack for java 11 could have container set up to maven-java11 as per https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/pull/16? I'm not sure why there was need for consolidation in https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/commit/6cd979b6c543e34050164c38fe81a1a96012543f.
