### ISSUE TITLE
Chinese developers voide should be heard

### ISSUE THREAD

**Issue by mrtylerzhou** [jenkins-x/jx#3743]
you host some images on your own website,but depends on so many images on gcr.io,which is not accessable in China!.

many developers try to find a way to insall k8s by privide custom googlecontainerimages,but only popular k8s related images,your images can not be found!

I used jenkins for about two years,and I 'd like to have a try jenkinsx,althrough you provide a simmple command `jx install` it,but the image source can not be changed

**Comment by pmuir** [comment]
Dupe of #3691
