### ISSUE TITLE
JX Import fails for PHP buildpack due to pipeline.yaml missing

### ISSUE THREAD

**Issue by shahnewazrifat** [jenkins-x/jx#3747]
### Summary 
PHP Build pack is detected and it cannot fine a pipeline.yaml (?) and fails.

performing pack detection in folder /var/tmp/xyz-com-devhub
--> Draft detected INI (58.818128%)
--> Could not find a pack for INI. Trying to find the next likely language match...
--> Draft detected PHP (23.340275%)
selected pack: /root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/php

### Steps to reproduce the behavior
Try to import a nginx-php application using JX
### Expected behavior
Import should pass
### Actual behavior
Import fails
### Jx version

The output of `jx version` is:

```
2.0.36
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

```
Eks cluster
```

### Operating system / Environment

```
Linux/Debian
```

**Comment by jstrachan** [comment]
fixed now

**Comment by jstrachan** [comment]
this quickstart works great now btw https://github.com/jenkins-x-quickstarts/php-helloworld

**Comment by shahnewazrifat** [comment]
Thanks @jstrachan !! You're just amazing!
