### ISSUE TITLE
Use jx preview without git server ?

### ISSUE THREAD

**Issue by olivierboudet** [jenkins-x/jx#3771]
### Summary 

As reported in #3721, I can't use our hosted gitlab with jx because it is deployed on the context path /gitlab.
But I would like to use jx preview without interacting with a PR (to deploy a temporary environment to run some e2e tests). 

### Steps to reproduce the behavior
Run the following command without git server configured : 
```
jx preview --no-wait=true --no-merge=true --no-comment=true --pr=0 --app myapp --dir ../..
Creating a preview
error: no Git service resource found with URL 'http://mydomain.com' in namespace jx
```

### Expected behavior

I can deploy a preview without git server configured as I disable comment, wait and merge options.

### Actual behavior

Without git server configured, I encounter the following error : 
```
error: no Git service resource found with URL 'http://mydomain.com' in namespace jx

```

With a git server configured on a non-root context, I encounter the following error : 
```
error: cannot create Git provider Running in batch mode and no default API token found
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.42
jenkins x platform 2.0.108
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.13.4
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [X] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Existing GKE cluster

### Operating system / Environment

Ubuntu 18.04.2 LTS

**Comment by Guschtel** [comment]
@olivierboudet In order to fix the first error, you can create a GitResource -> jx create/edit git server and/or edit the environments.
But somehow i was not able to set a default token with jx create/edit token, so i ended up destroying and re-creating the complete environments.
