### ISSUE TITLE
`jx get environments` do not list preview environments

### ISSUE THREAD

**Issue by plucury** [jenkins-x/jx#3781]
### Summary 
`jx get environments` do not list preview environments

### Steps to reproduce the behavior
`jx get environments`

### Expected behavior
List all environments within preview environments

### Actual behavior
Only list non-preview environments

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.56
jenkins x platform 2.0.78
Kubernetes cluster v1.9.8
kubectl            v1.12.2
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14 build 18A391
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by jstrachan** [comment]
we have a separate command for that: `jx get preview`
https://jenkins-x.io/commands/jx_get_previews/

I'm just about to add a PR to link those commands on the CLI / doc help...

**Comment by plucury** [comment]
@jstrachan Yes, sure. But I'd think preview is a kind of environment,  right?  So it better to describe `jx get environments` as 'List all environments except preview ones'.

**Comment by jstrachan** [comment]
yeah, we tend to think of `environments` as being an abbreviation of `permanent environments` and `previews` as an abbreviation of  `preview environments `

We could maybe add `jx get env —all` to show them all?

**Comment by plucury** [comment]
`jx get env —all` looks nice 👍
