### ISSUE TITLE
improve release notes for `jenkins-x-builders` + `jenkins-x-platform`

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#3783]
it would be awesome to generate nice release notes for `jenkins-x-builders` so for each builders version we know what version of common apps are in there `jx, kubectl, helm, skaffold`.

Then given a docker image we can easily know the versions of things in there...

Then it'd be awesome if we linked the builders release notes from the `jenkins-x-platform` release notes too; so we can do the same; given a platform version we know the buildlers -> jx version etc

**Comment by tdcox** [comment]
Good plan.

**Comment by pmuir** [comment]
Marking this as done as although we don't have all the dependencies listed they will start to appear as they get updated

We currently do this for jx
