### ISSUE TITLE
retry build Job

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#3784]
it would be awesome to setup an automatic retry `CronJob` that if enabled, retriggers any failed jobs  given a list of predicates (e.g. from bot users).

e.g. we should retry, say, 5 times with exponential backoff all PRs from bots (particularly promote / updatebot / jenkins x bot) which may be due to infrastructure issues.

we often get a failed pipeline when doing a promotion PR which should be retried

**Comment by rawlingsj** [comment]
Wonder if the retry should be in the pipeline?  

@abayer does this overlap with any plans from the Pipeline team?

/priority important-soon

**Comment by abayer** [comment]
So there's https://github.com/tektoncd/pipeline/pull/658 - but I think that's just limited to individual taskruns for now?
