### ISSUE TITLE
ERROR: error creating cluster configuring and installing Prow: installing Prow: configmaps "ingress-config" not found

### ISSUE THREAD

**Issue by langleyd** [jenkins-x/jx#3789]
### Summary 
 Can't install latest on GKE with '--ng'. Tried in a new GCP account.

### Steps to reproduce the behavior
1. jx create cluster gke --default-admin-password='redacted' --git-private --ng=true -n upswing-qa

### Expected behavior
Install succeeds

### Actual behavior
Install fails with:
ERROR: error creating cluster configuring and installing Prow: installing Prow: configmaps "ingress-config" not found

Full install log:
[ng-install.txt](https://github.com/jenkins-x/jx/files/3125743/ng-install.txt)

```
Setting the dev namespace to: jx
Generated helm values /Users/davidlangley/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /Users/davidlangley/.jx/cloud-environments/env-gke
Configuring the TeamSettings for Prow with engine Tekton
Setting the current namespace to: jx
ERROR: error creating cluster configuring and installing Prow: installing Prow: configmaps "ingress-config" not found
error: configuring and installing Prow: installing Prow: configmaps "ingress-config" not found
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.61
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.0
git                git version 2.20.1 (Apple Git-117)
helm client  Client: v2.13.1+g618447c
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

```
jx create cluster gke --default-admin-password='redacted' --git-private --ng=true -n upswing-qa
```

### Operating system / Environment
GKE / Cloud shell

**Comment by langleyd** [comment]
I checked in in the configs and I do see the `ingress-config` under the jx namespace.
It's contents are:

```
apiVersion: v1
data:
  clusterissuer: "false"
  domain: upswingapiqa.com
  email: ""
  exposer: Ingress
  issuer: ""
  tls: "false"
  urltemplate: ""
kind: ConfigMap
metadata:
  creationTimestamp: 2019-04-29T00:16:34Z
  name: ingress-config
  namespace: jx
  resourceVersion: "2871"
  selfLink: /api/v1/namespaces/jx/configmaps/ingress-config
  uid: 0c1ec1a3-6a14-11e9-8e13-42010af00122
```

**Comment by jstrachan** [comment]
is your wildcard DNS setup correctly with an A record?

**Comment by langleyd** [comment]
![image](https://user-images.githubusercontent.com/6135282/56883216-eb147500-6a5d-11e9-9935-4a7e59262bcd.png)

Think so yea, I was verifying that a ping was hitting the IP specified in the installation prompt before continuing. URLs like deck would load ok with it also.

**Comment by langleyd** [comment]
Just got it again on `2.0.62` with just:
```
jx create cluster gke --skip-login  --git-private --ng=true
```
and using `nip.io`

**Comment by paolocarta** [comment]
Having the same problem with JX 2.0.67 and the default nip.io domain.

**Comment by EamonKeane** [comment]
I had this problem after a partial install - `rm -rf ~/.jx` and reinstalling fixed it.

**Comment by romainverduci** [comment]
Having the same issue with jx `2.0.70`.
I tried with both `jx create terraform --ng` and `jx create cluster gke --ng`.
Having cleaned `~/.jx` and a well configured DNS, can't figure out how to workaround or fix that so it prevents me to have a running cluster.

**Comment by jstrachan** [comment]
incidentally our BDD tests are green for `jx create cluster gke --ng` - still not figured out whats going wrong yet

**Comment by EamonKeane** [comment]
@jstrachan 

This might not help, but I got that message again. Applying the exact same command again (without even clearing ~/.jx) worked though.... so there may be a strange race condition. The same config has worked many times with this only appearing once or twice.

>>>NAME               VERSION
jx                 2.0.71
Kubernetes cluster v1.12.7-gke.7
kubectl            v1.12.2
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.4 build 18E215a

**Comment by tdcox** [comment]
I can confirm that this is happening here too on a GKE cluster. The ingress-config CM exists in the JX namespace.

**Comment by tdcox** [comment]
Maybe unrelated but I got asked for an API token twice but was only asked for one git identity.

**Comment by langleyd** [comment]
As @EamonKeane mentioned I was able to work around this after the `jx create cluster` failed by running a subsequent 'jx install'.

**Comment by romainverduci** [comment]
After some investigation I have a bit more information about what's happening on my environment:
Root cause: for some reason `jx create cluster gke --ng` does not set a namespace for the current context of the installing cluster in `~/.kube/config`.

Behaviour:
- `jx create cluster gke --ng` not set the namespace in the `~/.kube/config` file.
- If you run `jx install --ng` right after the failure, it will keep failing.
- If you run `jx ns default` then `jx install --ng`, it will set the namespace to `default` in `~/.kube/config` but the install will still fail same reason
- Finally, if you run `jx ns jx` then `jx install --ng`, it will work and process to the install just fine.

**Comment by romainverduci** [comment]
@langleyd This issue should be fixed by https://github.com/jenkins-x/jx/pull/3864

**Comment by langleyd** [comment]
Yup looks good
