### ISSUE TITLE
collision in vault bucket name

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#3795]
### Summary 

when creating a new cluster with vault the bucket name that it crates is non unique.
it is created by the truncation of the cluster name to 14 characters.

However as naming conventions often have department ids etc in the cluster names assuming that these 14 caharacters will be unique is a mistake.

indeed when creating a new cluster you are prompted if you want to wipe out this existing bucket - and the default is "`Y`" 

This behaviour and the defaults can lead to a user loosing all the vault configuration.

Choosing `N` does not wipe the bucket but just uses it anyway (by the looks of the logs) 
this has the potential to either
1) to cause clusters to break if secrets are keyed by the same id
2) expose secrets to clusters/users that should not have access to them

### Steps to reproduce the behavior

1. `jx create cluster gke --cluster-name=plat-shared-rbac-yolo`
2. `jx create cluster gke --cluster-name=plat-shared-rbac-yolo`

### Expected behavior

if the cluster name is truncated to create the bucket then you should either perform a uniqueness or allow the user to then specify a different bucket name to use a different new bucket.

it would probably be better to always use a unique name and just label the bucket.  if you want to re-use one then make the user pass the bucket id in at creation time

### Actual behavior

nothing to see here move allong I will just use this existing thing and potentially wiope it out.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by ccojocar** [comment]
Closing this since the `boot` allows to specify the vault bucket name in the config.
