### ISSUE TITLE
jx step changelog produces release template that can't be compiled

### ISSUE THREAD

**Issue by grahammather** [jenkins-x/jx#3804]
### Summary 

The web app that we're building is a React app. The syntax for passing an object literal to a react JSX tag component uses double curly braces, which is the same syntax that the release template uses for parameters.  Using that specific React syntax in a PR comment produces a release template that can't be compiled by `jx step helm release`. 

### Steps to reproduce the behavior

- create a new cluster building the node-http quickstart webapp
- use github for scm
- create a PR with the following markup in the description: <MyComponent style={{display:"none"}} />
- the PR build should succeed because the changelog is not generated for PRs
- merge the PR
- master build fails

### Expected behavior

`jx step helm release` should succeed.

### Actual behavior

`jx step helm release` fails with the following error:

```
error: failed to build dependencies for chart from directory '.': failed to lint the chart '.': failed to run 'helm lint' command in directory '.', output: '==> Linting .

[ERROR] templates/: parse error in "<project>/templates/release.yaml": template:<project>/templates/release.yaml:2345: function "display" not defined
```

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.11
jenkins x platform 2.0.88
Kubernetes cluster v1.12.7-gke.7
kubectl            v1.14.0
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.10.5 build 14F2511
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Custom GKE cluster created by hand, jx installed with `jx install` and then a lengthy custom config process.

### Operating system / Environment

MacOS

**Comment by matiashaller** [comment]
I having same error in one of my branches, 

error: failed to build dependencies for chart from directory '.': failed to lint the chart '.': failed to run 'helm lint --values values.yaml' command in directory '.', output: '==> Linting .
[ERROR] templates/: parse error in "formsproduct/templates/release.yaml": template: formsproduct/templates/release.yaml:368: function "this" not defined


Did you get any work around? 

Thank you 
Matias
