### ISSUE TITLE
jx create cluster fails on iks

### ISSUE THREAD

**Issue by fluxens** [jenkins-x/jx#3807]
### Summary 

`jx create cluster iks --sso --kube-version=1.13.5` fails.

### Steps to reproduce the behavior

Run the above command, select us_south and any machine type and number.

### Expected behavior

Cluster is created and jx installation continues

### Actual behavior
The cluster is created but `jx`stops with the following output

```
ERROR: error creating cluster Request failed with status code: 503, ServerErrorResponse: ���
�@���\�F��VEV�
              ��$.��c��	�{	�n9��
                                     �U��s��f��� !*K�7/�kv�r���q̬2���"<��@���ĉ�ݬ���a��#E�K�[����&Й�-F��{9��>`��Ќ5ǻP}y�O?�"!ה�_N�4`��{7�>_鮩�
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.69
Kubernetes cluster v1.11.8
kubectl            v1.14.1
helm client        v2.12.2+g7d2b0c7
helm server        v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

irrelevant.

### Kubernetes cluster

see above

### Operating system / Environment

see above. installed via brew.

**Comment by takara9** [comment]
I also faced the same issue.

by my investigation, 
the following file has issue.
github.com/jenkins-x/jx/pkg/jx/cmd/create_cluster_iks.go

in this file,  function "cluster.Find()" returns error code 503 
it means that IBM Cloud API is not available at current situation.

--- create_cluster_iks.go
...
cluster, err := clusters.Find(createResponse.ID, target)                                                                                                                                                                            
if err != nil {                                                                                                                                                                                                                     
      return err                                                                                                                                
}  
...
---

"cluster" is from  github.com/IBM-Cloud/bluemix-go/api/container/containerv1
so, this cause issue that Cloud API does not working.


plus,
there are more issue in github.com/jenkins-x/jx/pkg/cloud/iks/auth.go

---
func ConfigFromJSON(config *ibmcloud.Config) (accountID string, err error) {
        configjson := new(ConfigJSON)
        usr, err := user.Current()
        if err == nil {
                jsonFile, err := os.Open(usr.HomeDir + "/.bluemix/config.json")
                if err == nil {
                        defer jsonFile.Close()
                        byteValue, _ := ioutil.ReadAll(jsonFile)

			json.Unmarshal(byteValue, configjson)
                        config.Region = configjson.Region    <-- it over write arg value as "--region"
---
