### ISSUE TITLE
tekton-pipelines-webhook error

### ISSUE THREAD

**Issue by fangchao117** [jenkins-x/jx#3808]
### Summary 

tekton-pipelines-webhook  CrashLoopBackOff
tide CrashLoopBackOff

### Steps to reproduce the behavior

jx install --provider=kubernetes --external-ip k8s.today36524.srv --no-default-environments --git-provider-kind='gitlab' --ingress-namespace=ingress-nginx --ingress-deployment='ingress-nginx-controller' --ingress-service='default-backend' --verbose --prow=true --tekton

### Jx version

NAME               VERSION
jx                 2.0.69
jenkins x platform 2.0.141
Kubernetes cluster v1.13.5
kubectl            v1.13.5
helm client        Client: v2.13.1+g618447c
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)
![2181B02C-9F17-44b5-9D32-53FB782031B2](https://user-images.githubusercontent.com/20237080/56951699-1afd6e80-6b6b-11e9-9c13-b699a48539b2.png)
![10389F03-1E40-402f-854F-F021D06C6368](https://user-images.githubusercontent.com/20237080/56951702-1b960500-6b6b-11e9-88c0-479a6a542d3b.png)

**Comment by ccojocar** [comment]
This should be fixed. Please could you try with a recent version? Can we close this issue? Thanks
