### ISSUE TITLE
Issue with Minishift start -  Waiting for the kube-apiserver to be ready; connection refused

### ISSUE THREAD

**Issue by shneha** [jenkins-x/jx#3809]
### Summary 
Unable to access minishift URL

### Steps to reproduce the behavior
minishift start
(using hyper-v, windows 10)
### Expected behavior
should give the complete message along with URL
### Actual behavior
C:\minishift-1.33.0-windows-amd64>minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'shneha Virtual Switch' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.59 MiB / 53.59 MiB [==============================================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [============================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM .................................................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image .......................................................................................................... OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ..............................................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.1.6 --routing-suffix 192.168.1.6.nip.io
err     : Process exited with status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0430 07:28:17.364796    7345 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0430 07:28:22.778421    7345 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 84% complete
Pulled 5/6 layers, 87% complete
Pulled 5/6 layers, 89% complete
Pulled 5/6 layers, 91% complete
Pulled 5/6 layers, 93% complete
Pulled 5/6 layers, 95% complete
Pulled 5/6 layers, 97% complete
Pulled 5/6 layers, 100% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.1.6 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0430 07:32:41.876004    7345 config.go:40] Running "create-master-config"
I0430 07:32:47.053298    7345 config.go:46] Running "create-node-config"
I0430 07:32:48.877645    7345 flags.go:30] Running "create-kubelet-flags"
I0430 07:32:49.435677    7345 run_kubelet.go:49] Running "start-kubelet"
I0430 07:32:49.724898    7345 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0430 07:37:49.744346    7345 run_self_hosted.go:571] API server error: Get https://192.168.1.6:8443/healthz?timeout=32s: dial tcp 192.168.1.6:8443: connect: connection refused ()
Error: timed out waiting for the condition

**Comment by bgrabows1** [comment]
The same issue with minishift 1.33 and openshift 3.11.0.

**Comment by pmuir** [comment]
I'm not sure what this has to do with Jenkins X - this looks like a pure minishft issue. Closing. Please reopen if it does relate to Jenkins X and explain how.

**Comment by niteshthakur** [comment]
Workaround which has worked for me :

Using hyperv + oc 3.11 + minishift v1.34.1+c2ff9cb.
Problem only on not so good internet connections.
Once minishift start command fails for the first time, ssh into minishift vm. Run oc cluster down followed by oc cluster up (copy this from the logs). Repeat this down/up step till your cluster is up. It could be 10-20 times or more or less depending on the network maybe.
Once the cluster is up, run minishift stop/ start and then you will be ready.
Hope this helps

**Comment by Vanguardcreed** [comment]
The same issue presist...
I am using Mac OS Catalina with minishift + xhyve.
Problem is waiting for kubeapi server to respond.
Help ! Many Thanks.

**Comment by bugmaker31** [comment]
> Problem only on not so good internet connections.

Seems to be my case :-(

> Once minishift start command fails for the first time, ssh into minishift vm.  Run oc cluster down 

Using which Unix account? `docker`?

> followed by oc cluster up (copy this from the logs). Repeat this down/up step till your cluster is up. It could be 10-20 times or more or less depending on the network maybe.
> Once the cluster is up, run minishift stop/ start and then you will be ready.
> Hope this helps

I'll tell you soon...

**Comment by TekKanPassion** [comment]
Same problem came up for me as well... any pointers to debug and fix it?

Error snippet -->

-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 172.30.172.21 --routing-suffix 172.30.172.21.nip.io
err     : Process exited with status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 172.30.172.21 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0519 11:19:00.434078   20008 flags.go:30] Running "create-kubelet-flags"
I0519 11:19:00.907995   20008 run_kubelet.go:49] Running "start-kubelet"
I0519 11:19:01.207882   20008 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0519 11:24:01.231450   20008 run_self_hosted.go:571] API server error: Get https://172.30.172.21:8443/healthz?timeout=32s: dial tcp 172.30.172.21:8443: connect: connection refused ()
Error: timed out waiting for the condition

**Comment by subodhraj** [comment]
there is no fix for this shit
