### ISSUE TITLE
Add external DNS TTL annotation to ingresses, defaults to 300s on GCP

### ISSUE THREAD

**Issue by EamonKeane** [jenkins-x/jx#3821]
### Summary 
When installing `next-gen` for the first time with vault, the vault ingress takes 300s+ to be registered via external DNS. The installer currently fails waiting for vault to be reachable over http (e.g. `http://my-vault.my-domain.com`). This also applies to any preview environments on initial PR. 

For a better user experience a default annotation could be added to all ingresses e.g.:

`external-dns.alpha.kubernetes.io/ttl: "30"`

https://github.com/kubernetes-incubator/external-dns/blob/master/docs/ttl.md

```
Google Provider
Previously with the Google Provider, TTL's were hard-coded to 300s. For safety, the Google Provider overrides the value to 300s when the TTL is 0. This value is a constant in the provider code.

For the moment, it is impossible to use a TTL value of 0 with the AWS, DigitalOcean, or Google Providers. This behavior may change in the future.
```

**Comment by ccojocar** [comment]
Closing this since now the recommended way to install Jenkins X is `boot` instead of `install --ng` option.
