### ISSUE TITLE
Tekton helm chart linting fails due to missing tekton.auth.git.password in values.yaml

### ISSUE THREAD

**Issue by EamonKeane** [jenkins-x/jx#3822]
### Summary 
Attempting to install a dev environment via `jx step env apply --namespace jx` fails due to a missing tekton password in values.yaml. Adding a password git token at `tekton.auth.git.password` string in global `values.yaml` fixes this.

```
env/charts/tekton/templates/250-git-secret.yaml" at <b64enc>: invalid value; expected string
```

### Steps to reproduce the behavior
Run `jx step env apply --namespace jx` after running through the install but without applying it to the cluster during the installation.

```bash
jx install --ng=true \
    --provider=gke  \
    --ingress-deployment='nginx-ingress-controller' \
    --ingress-namespace='kubeprod' \
    --ingress-service='nginx-ingress' \
    --domain=${DOMAIN} \
    --urltemplate='"{{.Service}}-{{.Namespace}}.{{.Domain}}"' \
    --git-api-token=${GIT_API_TOKEN} \
    --git-username=${GIT_USERNAME} \
    --git-private=true \
    --docker-registry='gcr.io' \
    --docker-registry-org='my-repo' \
    --default-environment-prefix=${ENVIRONMENT_PREFIX} \
    --no-default-environments=true
```

### Expected behavior
`jx step env apply --namespace jx` works first time.

### Actual behavior
Dev environment fails to be set up.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.71
Kubernetes cluster v1.12.7-gke.7
kubectl            v1.12.2
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.4 build 18E215a
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)

### Kubernetes cluster

GKE `1.12.7`, made manually

**Comment by chrismellard** [comment]
Just run across this issue too so I might take a look at a PR for this.

**Comment by chrismellard** [comment]
My issue is related to the provider `aks` and lack of vault integration so no secrets are being made available which is unrelated to this issue. [vault integration](https://github.com/jenkins-x/jx/issues/703)

**Comment by masseybradley** [comment]
Got this error trying to upgrade my initial dev environment (`jx upgrade platform`) in GKE using `jx`:
```
NAME               VERSION
jx                 2.0.618
Kubernetes cluster v1.13.7-gke.19
kubectl            v1.15.1
helm client        Client: v2.14.1+g5270352
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS
```
... trying to upgrade the platform to `2.0.951`. Error is: "Pipeline failed on stage 'from-build-pack' : container 'step-build-helm-build'".

**Comment by ccojocar** [comment]
`install --ng` is now replaced by `boot` command. Closing this issue.
