### ISSUE TITLE
How to install Jenkin X on existing GKE cluster

### ISSUE THREAD

**Issue by svallepu** [jenkins-x/jx#3829]
Hi  I have only access to gcloud command and i have logged in using gloud auth and 
downloaded JX binary and Tried below to install from why ./jx install

error: setting up current namespace: creating kube client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

Pls help me on this.

Thanks

**Comment by sharepointoscar** [comment]
@svallepu can you please ensure you follow the following documentation?  https://jenkins-x.io/getting-started/jenkins-x-gke-install-with-bot 

Also, if you've tried multiple installs, please delete your ~/.jx folder.

**Comment by jstrachan** [comment]
does the command `kubectl get node` work? Basically you need to connect properly to the cluster via `gcloud` first (eg hit the `Connect` button in the web console view of the Kubernetes clusters and copy paste the connect command into a shell
