### ISSUE TITLE
Missing draft pack?

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#383]
> Using:
> NAME        VERSION
> jx          1.0.135
> Jenkins X   0.0.319
> Kubernetes  v1.7.12-gke.1
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

Actions:
Upgrade jx to 1.0.135
Running `jx import` now results in:

```
➜ jx import             
error: could not load /Users/terry/.draft/packs/github.com/jenkins-x/draft-packs/packs/java: error reading /Users/terry/.draft/packs/github.com/jenkins-x/draft-packs/packs/java: open /Users/terry/.draft/packs/github.com/jenkins-x/draft-packs/packs/java: no such file or directory
```

**Comment by tdcox** [comment]
Whole folder missing:

```
➜ ls /Users/terry/.draft/packs/github.com/jenkins-x/           
draft-repo
```

Not fixed by `draft pack-repo update` or running `jx init`

**Comment by rawlingsj** [comment]
We’re currently in the middle of a release which involves multiple repos and we don’t yet have the gates in place to avoid this situation. This should be sorted soon and will update this issue but for today stick to the previous jx version.

**Comment by jstrachan** [comment]
@tdcox think this is fixed now
