### ISSUE TITLE
jx create spring with --name does not use given name

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#3832]
### Summary 

When creating a new JX application with `jx create spring --name xxx ...` an application/repository name is still requested. Running the create in batch mode takes over the name parameter.

### Steps to reproduce the behavior

```bash
: ${JX_ARTIFACT:="jx-demo-`date +%y%m%d-%H%M%S`"}

exec jx create spring \
    --name ${JX_ARTIFACT} \
    --git-username ascheman \
    --org ascheman \
    -l java \
    -g net.aschemann.demos.jx \
    -a ${JX_ARTIFACT} \
    -d actuator \
    "$@"
```

### Expected behavior

The name (jx-demo-...) is proposed for completion and can either be changed or acknowledged.

### Actual behavior

An empty name is proposed in the user interaction.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.72
jenkins x platform 2.0.177
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

`jx create cluster gke ...`

### Operating system / Environment

OSX

**Comment by sonyafenge** [comment]
same as https://github.com/jenkins-x/jx/issues/4549. 
should be fixed by https://github.com/jenkins-x/jx/pull/4578
