### ISSUE TITLE
PVC are not getting deleted

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3836]
### Summary
PVC are not getting deleted after the pipeline run is complete

### Steps to reproduce the behavior
Using next gen jx, setup a pipeline. Create a PR. merge the PR. The PVC still exists.

### Expected behavior
The PVC should be deleted after the PipelineRun is complete.

### Actual behavior
The PVC is not deleted after the PipelineRun is complete.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.70
Kubernetes cluster v1.12.7-gke.7
kubectl            v1.14.1
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE Manually

### Operating system / Environment

MAC OS X

**Comment by heroic** [comment]
Here's an example claim that's lying around since 9 days

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2019-04-23T07:11:54Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: org-org-master-1-pvc
  namespace: org
  ownerReferences:
  - apiVersion: tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: PipelineRun
    name: org-org-master-1
    uid: 12ce823f-6597-11e9-b4f5-42010aa10006
  resourceVersion: "21841749"
  selfLink: /api/v1/namespaces/collectr/persistentvolumeclaims/org-org-master-1-pvc
  uid: 12d1d93c-6597-11e9-a7e7-42010aa10004
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: pvc-12d1d93c-6597-11e9-a7e7-42010aa10004
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
```

**Comment by abayer** [comment]
Ok, so the PVCs are apparently only cleaned up when the `PipelineRun` gets deleted, which doesn't happen automatically and shouldn't be happening very often anyway. I think this probably merits an issue in Tekton to clean up the PVCs after completion - I'll handle that.

**Comment by abayer** [comment]
Ok, Tekton issue: https://github.com/tektoncd/pipeline/pull/823, and PR: https://github.com/tektoncd/pipeline/pull/832

**Comment by abayer** [comment]
This actually is fixed now, or should be at least.
