### ISSUE TITLE
Make it possible to override the root directory in jenkins-x.yml

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3838]
### Summary 

I'm reusing a build pack to get my steps, but I want to build a subdirectory of the git repo, not the root directory (as the root directory is generating code to place in the subdirectory). Make it possible to override the directory being used for the whole pipeline.

**Comment by abayer** [comment]
Seems reasonable - basically this would mean, I think, something that could be set on either the pipeline as a whole or individual stages to change the default working directory for steps. So, in other words, automatically setting the `dir` for steps.
