### ISSUE TITLE
Builds don't work with interactive install - Missing option: --docker-registry

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#3839]
### Summary 
After creating a new cluster and adding some projects/quickstarts, no builds commence.
### Steps to reproduce the behavior
Create a cluster using defaults 
`jx create cluster gke --skip-login  --default-admin-password=blahblah -n blahblah`
Add some quickstarts.
Watch and wait.  Nothing happens.
### Expected behavior
Adding quickstarts should immediately generate master builds.
### Actual behavior
No builds are started
### Jx version

The output of `jx version` is:

```
jx                 2.0.0-dev+90cba9a90
jenkins x platform 2.0.177
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.11.9-dispatcher
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Operating system / Environment

See snippet of `kubectl logs pipelinerunner-6c6fdcfb8c-589qs` below.  Notice 'Missing option: --docker-registry'

{"level":"info","msg":"shallow cloning repository https://github.com/deanesmith/dks-proph2.git to temp dir /tmp/git470645087\n","time":"2019-05-01T21:44:19Z"}
{"level":"warning","msg":"no SHAs to merge, falling back to initial cloned commit","time":"2019-05-01T21:44:20Z"}
{"level":"info","msg":"setting up docker registry for https://github.com/deanesmith/dks-proph2.git\n","time":"2019-05-01T21:44:20Z"}
{"level":"info","msg":"removing the temp directory /tmp/git470645087\n","time":"2019-05-01T21:44:20Z"}
{"level":"error","msg":"Missing option: --docker-registry Missing option: --docker-registry","time":"2019-05-01T21:44:20Z"}
{"level":"error","msg":"Missing option: --docker-registry","time":"2019-05-01T21:44:20Z"}

**Comment by rawlingsj** [comment]
Sounds like the same error that @michaelneale mentioned this morning.  We think there might be a UX issue.  Will dig out the thread and paste relevant help here.

**Comment by deanesmith** [comment]
@rawlingsj let me know if you need anything else.  I think I used every default option.  I'll keep the cluster around for a few days.

**Comment by deanesmith** [comment]
@rawlingsj workaround to use the --tekton option.  So, this works - `jx create cluster gke --tekton --skip-login --default-admin-password=blahblah -n blahblah`.  Since the happy path is interactive install and tekton is the default, this is probably very important to fix?

**Comment by highlyunavailable** [comment]
I ran into that issue yesterday, I fixed it by doing `jx install --kaniko --docker-registry gcr.io` as the options and that set it up right. The --kaniko part was the important bit otherwise the registry credentials couldn't make it into the container.

**Comment by michaelneale** [comment]
Yes - this is exactly what I saw. 

The questions that the interactive installer asks if you do NOT use --tekton are non sensical and can't work: 

```
? What type of cluster would you like to create Zonal
? Google Cloud Zone: australia-southeast1-a
? Google Cloud Machine Type: n1-standard-2
? Minimum number of Nodes (per zone) 3
? Maximum number of Nodes 5
? Would you like use preemptible VMs? No
? Would you like to access Google Cloud Storage / Google Container Registry? No
? Would you like to enable Cloud Build, Container Registry & Container Analysis APIs? No
? Would you like to enable Kaniko for building container images No
```

I believe you have to say yes to the last 2 - if you want to pick Serverless/tekton later. 

This means the default interactive install will NOT work (as serverless later is the first choice) - so I think the defaults need to change and possibly have the interactive installer tested. 

Secondly as we discussed, there need to be fewer choices here, perhaps hidden behind a --verbose. 

Also why is --tekton not the default? is it because it takes away the choice of a static master?

**Comment by rawlingsj** [comment]
ok lets sort this ASAP
/kind bug
/priority critical-urgent
/area install
