### ISSUE TITLE
Deployment of LetsEncrypt TLS certificates broken

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#3845]
### Summary 
Creating a cluster with TLS enabled on the ingress was failing so to debug I created a cluster without TLS then ran `jx upgrade ingress --cluster` using letsencrypt staging certs. 

Testing shows access to jx services over https is failing because the proxy is still using the kubernetes default fake certificate.

`kubectl get certificates` returns a single result 'tls-deck'.

The nginx ingress controller log is showing something interesting...

```
W0503 08:36:53.309658       8 controller.go:1094] Using default certificate
W0503 08:36:53.309682       8 controller.go:1086] Unexpected error validating SSL certificate "jx/tls-deck" for server "jx-vault-jx-07.jx.redacted.com": x509: certificate is valid for deck.jx.redacted.com, not jx-vault-jx-07.jx.redacted.com
W0503 08:36:53.309700       8 controller.go:1087] Validating certificate against DNS names. This will be deprecated in a future version.
W0503 08:36:53.309711       8 controller.go:1092] SSL certificate "jx/tls-deck" does not contain a Common Name or Subject Alternative Name for server "jx-vault-jx-07.jx.redacted.com": x509: certificate is valid for deck.jx.redacted.com, not jx-
vault-jx-07.jx.redacted.com
```
This repeats for all exposed services. Looks like the ingress is expecting a wildcard cert but the setup has requested a normal cert...

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.75
jenkins x platform 2.0.191
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.11.9-dispatcher
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Debian GNU/Linux 9.8 (stretch)
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
GKE

**Comment by tdcox** [comment]
Tried deleting the tls-deck cert and restarting the cert-manager pod but the cert is just recreated.

It appears to be a valid staging cert setup for the deck service.

**Comment by tdcox** [comment]
Just tried `jx upgrade ingress --cluster` with the letsencrypt prod server whilst monitoring the cert-manager logs. I can see that the default is to use HTTP01 verification and this is failing repeatedly as HTTP requests are made to verification paths that are 404 or 503.

**Comment by tdcox** [comment]
In that last execution a single secret 'tls-monocular' was created this time. Closer inspection shows that whilst it is called 'tls-monocular', it contains annotations for nexus and presumably the certificate for nexus as well.

That would imply that something is overwriting this single secret instead of creating multiple copies.

**Comment by wenzlaff** [comment]
might be related to https://github.com/jenkins-x/exposecontroller/issues/182

**Comment by vitalis** [comment]
I have the same issue, tried different versions of cert-manager always the same result.
```
NAME               VERSION
jx                 2.0.88
jenkins x platform 2.0.191
Kubernetes cluster v1.12.7-gke.7
kubectl            v1.12.1
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.19.0
Operating System   Mac OS X 10.14.4 build 18E226
```

**Comment by tdcox** [comment]
Snapshot of cert-manager log: https://gist.github.com/tdcox/3ba0f41fea303fe13d5e79b394cf20d3

**Comment by wenzlaff** [comment]
Should finally been fixed with https://github.com/jenkins-x/exposecontroller/pull/184

**Comment by wenzlaff** [comment]
@tdcox could you please close this issue or does it still exists?

**Comment by pmuir** [comment]
Closing as should be fixed
