### ISSUE TITLE
Latest and previous tag for changelog generation not correct

### ISSUE THREAD

**Issue by beebird** [jenkins-x/jx#3866]
### Summary 
The issue with ``jx step changelog`` has been existing for a long time. 

#### In short, the command doesn't pick up ``latestTag`` and ``previousTag`` correctly.  

I dig into the source code and find the git command that ``jx`` calls is not reliable.
```go
latestTag, err := g.gitCmdWithOutput(dir, "describe", "--abbrev=0", "--tags", "--always")

previousTag, err := g.gitCmdWithOutput(dir, "describe", "--abbrev=0", "--tags", "--always", latestTag+"^")

```
Take my project as an example. If I issue the command:
```sh
git describe --abbrev=0 --tags --debug # find latest tag
```
> describe HEAD
> No exact match on refs or tags, searching to describe
>  lightweight     2241 6.9.1
>  lightweight     2239 6.8.1
>  lightweight     2242 6.8.0
>  lightweight     2255 6.7.1
>  lightweight     2308 6.7.0
>  lightweight     2336 6.6.1
>  lightweight     2364 6.6.0
>  lightweight     2371 6.5.1
>  lightweight     2396 6.5.0
>  lightweight     2407 6.4.1
> traversed 3028 commits
> more than 10 tags found; listed 10 most recent
> gave up search at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 6.9.1
> 

```sh
git describe --abbrev=0 --tags --debug --always 6.9.1^ # find previous tag
```
> describe 6.9.1^
> No exact match on refs or tags, searching to describe
>  lightweight      115 6.8.1
>  lightweight      118 6.8.0
>  lightweight      131 6.7.1
>  lightweight      184 6.7.0
>  lightweight      212 6.6.1
>  lightweight      240 6.6.0
>  lightweight      247 6.5.1
>  lightweight      272 6.5.0
>  lightweight      283 6.4.1
>  lightweight      288 6.4.0
> traversed 290 commits
> more than 10 tags found; listed 10 most recent
> gave up search at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 6.8.1

**So I get ``previousTag`` = ``6.8.1``, while it's a very old tag, the latest should be ``v6.10.194`` and previous should be ``v6.10.193``** (After a previous jx upgrade, it adds a "v" as a prefix in the label, and I don't know when) 

I can prove this by checking the tags with another way:
```sh
git describe --tag  $(git rev-list --tags --max-count=10 --skip=0)
```
> v6.10.194
> v6.10.193
> 6.9.1-2241-gxxxxxxxxxx
> 6.9.1-2240-gxxxxxxxxxx
> v6.10.192
> 6.9.1-2239-gxxxxxxxxxx
> 6.9.1-2238-gxxxxxxxxxx
> v6.10.191
> v6.10.190
> 6.9.1-2237-gxxxxxxxxxx

### The Consequence

-  **Extremely slow CI process**

-  **The releases chart too long** (releases.jenkins.io must have at most 262144 characters)

-  **Repeated release note** (not only to me, I can see lots of repeated change logs in[ jx release page ](https://github.com/jenkins-x/jx/releases)as well)

Could someone take a look? It' really a pain. 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.56
jenkins x platform 2.0.151
Kubernetes cluster v1.13.1
kubectl            v1.14.0
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

**Comment by beebird** [comment]
I did more investigation and found out that the root cause might be here:
```bash
git commit -a -m "release $(VERSION)" --allow-empty
git tag -fa v$(VERSION) -m "Release version $(VERSION)"
git push origin v$(VERSION)
```
jx only pushes the new tag to remote,  leaving alone the regular (empty) commit in local repo folder. So the commit is lost.

Then in next build, the command
```bash
git describe --abbrev=0 --tags --debug --always v$(VERSION)^
```
always picks up the previous tag that associated with a regular commit:
```bash
git:(master) git cat-file -t v6.10.201
tag  #(ignore because it't not a commit)

git:(master) git cat-file -t 6.9.1
commit  #(pick it up as previous commit)
```

I did some testing in my own repo that is worked as expected.
So my suggested fix is to push the empty commit, what do you think? @hferentschik

**Comment by hferentschik** [comment]
As a reference, this pull request is related to this issue - https://github.com/jenkins-x/jx/pull/3790.

**Comment by hferentschik** [comment]
> jx only pushes the new tag to remote, leaving alone the regular (empty) commit in local repo folder. So the commit is lost.

Yes, that's correct. Are you using `jx step tag` for tagging? How is the repository checked out? Just trying to get more context about your concrete setup.

That said, the issue you describe is known. Tags created in this form are "invalid" since they refer to commits which never make it into the repository. The problem with pushing the commit is that this would trigger another release build. We are looking for a proper solution for this.

One way around is to do the release commit and tag on a release branch. This way you get valid commits. The problem is that `git describe --abbrev=0 --tags` does not work then anymore. One need to manually determine and pass the start and end revision to the changelog generation.

**Comment by beebird** [comment]
Thanks for you reply. Yes I noticed the PR and saw your comment. In my situation, jx can always fetch a previousTag, but not the expected one. So I think the solution might be a little different.

I believe the jx project itself is using the similar logic to tag a new release and pick up changelogs.
However, compared with jx repo, I can see the type of the tag object is different:
```
git cat-file -t v1.3.249
commit
```
While in my project handled (tagged) by jenkins-x CI:
```
git cat-file -t v6.10.201
tag
```

So I'm suspecting that the reason to this difference is that jx doesn't push the empty commit before it pushes the tag.  Does it make sense? If you agree with me then I'd like to open a PR. Thanks.

**Comment by hferentschik** [comment]
The difference is between annotated tags and non annotated tags. The former includes a commit which the tag refers to, the latter is only an entry in the refs. 

Per default `git describe` does only list annotated tags, and one has to use `--tag` or  `--all` to get annoated and non annotated tags.

What's happening at the moment in the `jx` repo is that there is a commit to change the version which is tagged, but we don't update the master ref. This way you can push the version commit and tag without triggering another build. However, it also means that `GetPreviousGitTagSHA` is broken. `git describe` lists tags which are reachable from a given commit. These new type of tags are not reachable to each other. 

So I think one needs to also use `git merge-base` to determine for each tag (latest and previous) the merge base onto master. Once you have the two merge points on master you do the changelog between them. This should also work if you actually have the tags on master directly. Something like this - https://github.com/jenkins-x-apps/jx-app-jacoco/blob/master/Makefile#L74

So imo, it should be like this:

- Find latest and previous tag. IMO one cannot use `git describe` to do this, but `git for-each-ref`. Also the current logic for finding the previous tag does still not work in the case that we only have a single tag. The edge cases are not implemented correctly. 
- For each tag (latest and previous) determine its merge base (using `git merge-base`). Per default this should be against master, but I think the "release" branch should be an option which defaults to master
- One you have determined the two tags on the release branch you can pass this to the current changelog logic. 

This should work for annotated tags as well and non annotate tags, as well as for tags on the release branch as well as for tags on "release branches".

WDYT?

**Comment by hferentschik** [comment]
>  Does it make sense? If you agree with me then I'd like to open a PR. Thanks.

It would be awesome if you would like to work on this. I am happy to help as well. I think it is essential though that we back the implementation up with unit tests. This code has been "fixed" multiple times, but in the end it is still not working as expected. The unit test would prove that it works.

**Comment by beebird** [comment]
Excellent explanation! I totally agree with your analysis.  Will try to provide a candidate fix this weekend if no fix before then. 

Although I've submitted pull requests to jx project before, I'm not good at golang so unit tests might be a difficult part... Anyway, I'll take a try. Thanks!

**Comment by hferentschik** [comment]
>  I totally agree with your analysis. Will try to provide a candidate fix this weekend if no fix before then.

That would be awesome. 

> Although I've submitted pull requests to jx project before, I'm not good at golang so unit tests might be a difficult part... Anyway, I'll take a try.

As said, I am happy to help on this front. We can iterate on this. The good thing is that we can just test on the git level. Things gets much harder if one needs to test against an installed Jenkins-X install.

I imagine for example that one could create a tmp directory, call `git init` on it and create a set of commits and tags. Then one runs for example `GetPreviousGitTagSHA` to verify that it works as intended. It should be straight forward to create temporary gitr epos with various forms of tags on and off the main branch.

**Comment by hferentschik** [comment]
Either way I am tempted to close  pull request  #3790 since I feel it falls short of solving the underlying issues.

**Comment by beebird** [comment]
Hi @hferentschik ,

I just opened a pull request #4027.  I didn't get time to write the unit tests although I've done quite some tests under different circumstances.  And please feel free to close it if you have any concern, also I'm happy if you can help with the tests :)

I did some research based on our discuss and chose an slightly different way to pick up the "real" commit hash, the main steps are as follows:
```bash
# my testing repo: # https://github.com/beebird/testrepo.git
# find the 2 most recent tags 
$ git for-each-ref --count=2 --sort=-creatordate --format='%(refname:lstrip=-1) %(objecttype) %(objectname)' refs/tags
v1.3.10
v1.3.6

# dereference the tag recursively until a non-tag object is found (from git documentation)
$ git rev-parse v1.3.10^{}
7e4cc7989f98918c7ffe4420c033a58a985813dc

$ git rev-parse v1.3.6^{}
e162e99509af226b37dd62d194115f46b30e0bbc
```

I compared ``git rev-parse`` with ``git merge-base`` and in most cases they have the same behavior, but if I switched to "release" branch, ``git rev-parse ...^{}`` always returned the correct commit hash while ``git merge-base ... release`` sometimes didn't.

It's too late now and I have to go to work tomorrow...

Thanks!

**Comment by hferentschik** [comment]
@beebird awesome, thanks. I'll take a look asap.

**Comment by hferentschik** [comment]
> I compared git rev-parse with git merge-base and in most cases they have the same behavior, but if I switched to "release" branch, git rev-parse ...^{} always returned the correct commit hash while git merge-base ... release sometimes didn't.

Fair enough, let me look into this.

**Comment by hferentschik** [comment]
I think the use of `for-each-ref` looks good. I am not sure yet regarding `rev-parse`. Can you describe where `merge-base` did not return the right sha, but `rev-parse` did?
I think we won't get around some sort of test harness here. I have some ideas. I try to come up with something asap.

**Comment by beebird** [comment]
Thanks for you help and I have competed the lint test in the pull request.

About the different behavior between ``merge-base`` and ``rev-parse``, I can reproduce it in my public [repo](https://github.com/beebird/testrepo.git).

Below is a piece of my commit logs generated by ``tig log``, there're 3 commits (2 empty commits and one file change)
```
commit 9a17467f651bf761c9c843ab5a1fad8b140baf15
Refs: <v1.3.4>
Author: Beebird <beebird@gmail.com>
Date:   Thu May 16 20:43:49 2019 +0800

    release v1.3.4

commit 71601b4ce9df1da41940da2a9a5ef614d97e92bc
Author: Beebird <beebird@gmail.com>
Date:   Thu May 16 20:43:44 2019 +0800

    update

 Readme.md | 1 +
 1 file changed, 1 insertion(+)

commit 23c0bacdd6d1f31e053725ab875736a677c4bfa2
Refs: <v1.3.3>
Author: Beebird <beebird@gmail.com>
Date:   Thu May 16 19:37:35 2019 +0800

    release v1.3.3

```

Then with ``git log $(git rev-parse v1.3.3^{})...$(git rev-parse v1.3.4^{})`` I get:
```
commit 9a17467f651bf761c9c843ab5a1fad8b140baf15 (tag: v1.3.4)
Author: Beebird <beebird@gmail.com>
Date:   Thu May 16 20:43:49 2019 +0800

    release v1.3.4

commit 71601b4ce9df1da41940da2a9a5ef614d97e92bc
Author: Beebird <beebird@gmail.com>
Date:   Thu May 16 20:43:44 2019 +0800

    update

commit 23c0bacdd6d1f31e053725ab875736a677c4bfa2 (tag: v1.3.3)
Author: Beebird <beebird@gmail.com>
Date:   Thu May 16 19:37:35 2019 +0800

    release v1.3.3
```

But with ``git log $(git merge-base v1.3.3 master)...$(git merge-base v1.3.4 master)`` nothing returns. Apparently the commit ``71601b4ce9df1da41940da2a9a5ef614d97e92bc`` with real file changes is missing....

**Comment by hferentschik** [comment]
> But with git log $(git merge-base v1.3.3 master)...$(git merge-base v1.3.4 master) nothing returns. Apparently the commit 71601b4ce9df1da41940da2a9a5ef614d97e92bc with real file changes is missing....

Hmm, I am wondering how you constructed this repo. `git merge-base v1.3.3 master` and `git merge-base v1.3.4 master` both return `04f52fe8cd8b08cd0106a790d0c6eaa9cc68d610`. `71601b4` is not returned on the latter, since it is not on master. Have a look at the output of `git log --graph --all`. I'd argue the repo is not properly constructed since not all commits are on the main (master) branch. 

For this reason, it would also be beneficial to have (unit) tests since they would set the expectation s.

**Comment by beebird** [comment]
I cannot recall exactly what I did with the repo, perhaps I pushed some tags on "release" without pushing "release" branch itself ...

Agree that we need more tests before merge to master. I can continue woking on this but may need your help. For example, if we run unit tests, how to confirm the commit hashes returned are correct? Or can we run some other tests to check if it works as expected?

**Comment by hferentschik** [comment]
> Agree that we need more tests before merge to master. I can continue woking on this but may need your help.

No worries. I just started to create a generic test harness around git_cli. I will try to create all the basics and maybe even a couple of test cases just for the different scenarios around determining the commits for the changelog. I'll keep you posted.

**Comment by hferentschik** [comment]
I think there are three valid ways to go about doing releases:

- Everything is on master. When doing a release you create your release commit on master and tag on master. I guess this is still quite widely used. I am thinking maven here or Rake's Gem release tasks. In the case of Jenkins-X this is not working atm, since pushing the release commit to master would trigger an endless release loop. However, I think eventually it should become an option to prevent a release build based on a certain type of commit comment and/or changes to a certain type of files. 
- The second option is that you literally create a release branch (`checkout -b`) and create your release commit(s) and tag on there. 
- The third option is to switch into a detached HEAD mode (by eg explicitly checking out the HEAD commit) and then creating release commit(s) and tag on this detached HEAD. Being in the detached HEAD mode will ensure that the HEAD ref is not getting updated.

With the right test harness it should be quite easy to create small test repos for all these three cases and ensure that the right commits are picked up.

**Comment by hferentschik** [comment]
I closed PR #4027. I think more work is needed. Using `for-each-ref` seems to be ok, but I think we still need the discussed `merge-base` part. I added a bit of a test harness I think we can use to test all this. For now, I added some tests for `GetCurrentGitTagRev` and `GetPreviousGitTagRev`. You can find the tests on my dev branch https://github.com/hferentschik/jx/tree/issue-3866. Have a look whether it makes sense. It uses Ginko and looks a bit like this:

```go
Describe("Get version tags", func() {
	Context("when tags are on master", func() {
		BeforeEach(func() {
			writeFile(Fail, repoDir, "a.txt", "a")
			add(Fail, repoDir)
			commit(Fail, repoDir, "first commit")
			tag(Fail, repoDir, "v0.0.1")
			writeFile(Fail, repoDir, "b.txt", "b")
			add(Fail, repoDir)
			commit(Fail, repoDir, "second commit")
			tag(Fail, repoDir, "v0.0.2")
			writeFile(Fail, repoDir, "c.txt", "c")
			add(Fail, repoDir)
			commit(Fail, repoDir, "third commit")
			tag(Fail, repoDir, "v0.0.3")
		})
		It("GetCurrentGitTagRev returns the sha of the latest tag", func() {
			tagRef, err := git.GetCurrentGitTagRev(repoDir)
			Expect(err).Should(BeNil())
			Expect(tagRef).Should(Equal("v0.0.3"))
		})
		It("GetPreviousGitTagRev returns the sha of the latest tag", func() {
			tagRef, err := git.GetPreviousGitTagRev(repoDir)
			Expect(err).Should(BeNil())
			Expect(tagRef).Should(Equal("v0.0.2"))
		})
	})
})
```

The idea is to build a test repo in the `BeforeEach` section and then run the various commands needed to determine the tag shas as well as the commits which should go into the changelog.

Hope it makes sense. You can run just this test by `make test-single-file TEST=pkg/gits/git_cli_test.go`

I think what's missing right now is something like `MergeBase(dir string, sha string, base string)`. Base would per default be `master`, but I guess eventually one would like to make this an option of the changelog command. 

Note, you also need the merge base for the case where you have multiple commits on a release branch prior to the release tag. Think about the case where one creates a release branch, modifies one file, commits, modifies a second file, commits and then tags the release. You really want to find the commits on the release (master) branch for the changelog. One might one to include commits on the current release branch, but any additional commits on the previous release branch should not be included. 

Let me know whether you want to give it another go.

**Comment by beebird** [comment]
Awesome! Your thought is more comprehensive and I agree that the merge-base can meet our requirement (and we can start from "master" branch and add support to "release" branch later) 

I'll run some tests on your dev branch and provide feedback :)

**Comment by hferentschik** [comment]
@beebird hi, just wondering whether there is any update on this? Did you have time to give it another go?
