### ISSUE TITLE
Question: jx User vs kubernetes user

### ISSUE THREAD

**Issue by TarekAS** [jenkins-x/jx#3870]
Hello, I do not understand how JenkinsX Users (object) and kubernetes users are related. The [documentation](https://jenkins-x.io/architecture/access-control/) on this is not clear. Do I have to create two types of User for the same real-life user?

Right now this is what I know:

1. Create external IAM user (e.g. AWS IAM)
2. Map IAM user to k8s (e.g. aws-auth ConfigMap)
3. Create user via JenkinsX  (how does this user map to the k8s user?)

Who is referenced in the EnvironmentRoleBinding, the JenkinsX user or the k8s user? Or are they the same?

Thank you

**Comment by pguimaraes** [comment]
Any updates?  I have the same question.

**Comment by deanesmith** [comment]
@TarekAS I realize this is an old question but there are now some resources available to help distinguish these concepts of a "user".   Firstly, Jenkins X users and roles are reasonably well described here - https://jenkins-x.io/docs/managing-jx/common-tasks/access-control/.  At the end of January 2020, the CloudBees Jenkins X Distribution (and upstream JX) will have increased support for EKS.A good deal of work and documentation is being established to help set up IAM respectively for JX on EKS.
