### ISSUE TITLE
pipelinerunner error log help 

### ISSUE THREAD

**Issue by fangchao117** [jenkins-x/jx#3885]
### Summary 
jx import pipelines error
### Steps to reproduce the behavior

jx install --provider=kubernetes --external-ip='k8s.today36524.srv' --no-default-environments --default-admin-password='admin' --default-admin-username='admin' --docker-registry='10.100.184.90' --domain='today36524.srv' --git-provider-kind='github' --ingress-namespace='ingress-nginx' --ingress-deployment='ingress-nginx-controller' --ingress-service='default-backend' --verbose --prow --tekton --no-tiller

### Expected behavior
build app
### Actual behavior
pipelinerunner pod logs error

### Jx version
NAME               VERSION
jx                 2.0.87
jenkins x platform 2.0.191
Kubernetes cluster v1.13.5
kubectl            v1.13.5
helm client        Client: v2.13.1+g618447c
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)

```
{"level":"info","msg":"running command: jx step tag --version \\$(cat VERSION)\n","time":"2019-05-08T09:33:49Z"}
error: Have you set up a git credential helper? See https://help.github.com/articles/caching-your-github-password-in-git/
: git output: fatal: could not read Username for 'https://github.com': No such device or address: failed to run 'git push origin v0.0.1' command in directory '', output: 'fatal: could not read Username for 'https://github.com': No such device or address'
```

### Jenkins type

- [√] Next Generation (Tekton + Prow)
- [√] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Why does the project have no jenkinsfile when using the bow?

**Comment by usvgmani** [comment]
I get the same for jx installed on AWS EKS. 
jx install --provider=eks --skip-ingress --no-default-environments --tekton --no-tiller
jx               2.0.101
git              git version 2.17.2

am i missing something?

Logs below:
--------

{"level":"info","msg":"Generated Git credentials file /home/jenkins/git/credentials\n","time":"2019-05-10T19:22:22Z"}
{"level":"info","msg":"triggering pipeline for repo https://github.com/xxxx branch master revision master context \n","time":"2019-05-10T19:22:22Z"}
{"level":"info","msg":"Deleting and cloning the Jenkins X versions repo","time":"2019-05-10T19:22:22Z"}
{"level":"info","msg":"Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /root/.jx/jenkins-x-versions\n","time":"2019-05-10T19:22:22Z"}
Enumerating objects: 13, done.
.... done.
Total 1273 (delta 1), reused 11 (delta 1), pack-reused 1260
{"level":"info","msg":"shallow cloning repository https://github.com/xxxx to temp dir /tmp/git884070833\n","time":"2019-05-10T19:22:23Z"}
{"level":"warning","msg":"no SHAs to merge, falling back to initial cloned commit","time":"2019-05-10T19:22:25Z"}
{"level":"info","msg":"setting up docker registry for https://github.com/xxxx","time":"2019-05-10T19:22:25Z"}
{"level":"info","msg":"generating build number...\n","time":"2019-05-10T19:22:25Z"}
{"level":"info","msg":"generated build number 1 for https://github.com/xxxxx","time":"2019-05-10T19:22:25Z"}
{"level":"info","msg":"about to create the tekton CRDs\n","time":"2019-05-10T19:22:26Z"}
{"level":"info","msg":"running command: echo \\$(jx-release-version) \u003e VERSION\n","time":"2019-05-10T19:22:26Z"}
{"level":"info","msg":"\n","time":"2019-05-10T19:22:26Z"}
{"level":"info","msg":"running command: jx step tag --version \\$(cat VERSION)\n","time":"2019-05-10T19:22:26Z"}
{"level":"info","msg":"Updating chart version in charts/xxx/Chart.yaml to 0.0.1\n","time":"2019-05-10T19:22:26Z"}
{"level":"info","msg":"Updating repository in charts/xxx/values.yaml to xxx\n","time":"2019-05-10T19:22:27Z"}
{"level":"info","msg":"Updating tag in charts/xxxto 0.0.1\n","time":"2019-05-10T19:22:27Z"}
error: Have you set up a git credential helper? See https://help.github.com/articles/caching-your-github-password-in-git/
: git output: fatal: could not read Username for 'https://github.com': No such device or address: failed to run 'git push origin v0.0.1' command in directory '', output: 'fatal: could not read Username for 'https://github.com': No such device or address'
{"level":"info","msg":"removing the temp directory /tmp/git884070833\n","time":"2019-05-10T19:22:27Z"}
{"level":"error","msg":"failed to generate Tekton CRD: failed to set the version on release pipelines: failed to run '/bin/sh -c jx step tag --version $(cat VERSION)' command in directory '/tmp/git884070833', output: '' failed to generate Tekton CRD: failed to set the version on release pipelines: failed to run '/bin/sh -c jx step tag --version $(cat VERSION)' command in directory '/tmp/git884070833', output: ''","time":"2019-05-10T19:22:27Z"}
{"level":"error","msg":"failed to generate Tekton CRD: failed to set the version on release pipelines: failed to run '/bin/sh -c jx step tag --version $(cat VERSION)' command in directory '/tmp/git884070833', output: ''","time":"2019-05-10T19:22:27Z"}
