### ISSUE TITLE
error: pulling environment repo  failed to fork GitHub 

### ISSUE THREAD

**Issue by udbscience** [jenkins-x/jx#3896]
### Summary 
jx promote fails

### Steps to reproduce the behavior
jx promote -b --app ${APP} --env ${JX_ENV} --version ${VER}

### Expected behavior
app get promoted

### Actual behavior
pipeline xxx/xxxx/master
WARNING: Waiting for the fork of xxxx/environment-xx-xxxx to appear...
error: pulling environment repo https://xxxxxxxx into /home/ec2-user/.jx/environments: failed to fork GitHub repo xxxxx/xxxxx to user xxxxx: Gave up waiting for Repository xxxxx/environment-xx-xxxxx to appear: GET https://xxxxxx/api/v3/repos/xxxx/xxxx-xx-xxxxx: 404 Not Found []

### Jx version
jx                 2.0.102

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.102
jenkins x platform 2.0.191
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.17.2
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [-] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

EKS 1.12

**Comment by athilaelhuno** [comment]
I have the same issue, any news about how we can fix

**Comment by ruzin** [comment]
same issue as well

**Comment by ruzin** [comment]
@jstrachan

**Comment by olektretiak** [comment]
I have the same issue

NAME               VERSION
jx                 2.0.310
jenkins x platform 2.0.672
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.14.5
Operating System   Unkown Linux distribution Linux version 4.9.17-8.31.amzn1.x86_64 (mockbuild@gobi-build-60008) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Sat Apr 1 01:22:16 UTC 2017

**Comment by imp20052904** [comment]
I hava the same issue

NAME               VERSION
jx                 2.0.329
jenkins x platform 2.0.768
Kubernetes cluster v1.14.3
kubectl            v1.15.0
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.12.6 build 16G1918

**Comment by ZedYeung** [comment]
Same issue. It is already Aug, any progress?

**Comment by oren-icx** [comment]
Same here.

NAME               VERSION
jx                 2.0.590
jenkins x platform 2.0.948
Kubernetes cluster v1.13.8-eks-a977ba
kubectl            v1.13.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.7.4
Operating System   Ubuntu 16.04.6 LTS

**Comment by olektretiak** [comment]
I was used to have it fixed, the issue is related to the GitHub credentials
Just setup a user with password instead of GitHub token

**Comment by oren-icx** [comment]
> I was used to have it fixed, the issue is related to the GitHub credentials
> Just setup a user with password instead of GitHub token

@olektretiak - how do you replace the current token being used by jx to username and password?

**Comment by olektretiak** [comment]
After workers nodes updates I was not able to login, I just reinstalled my installation. By the way I believe you can play with jx to remove you git and user settings

**Comment by doc-olliday** [comment]
Same issue, but with gitlab.com instead.

**Comment by bnerDY** [comment]
Same issue, with github enterprise instead.

**Comment by jstrachan** [comment]
try using `jx boot` which sets up and verifies the git token during installation:
https://jenkins-x.io/getting-started/boot/

**Comment by jstrachan** [comment]
here's docs on configuring git with `jx boot` https://jenkins-x.io/getting-started/boot/#git

**Comment by bnerDY** [comment]
@jstrachan thanks for your help. I will try to use it.

**Comment by siddharthkaushal90** [comment]
Hi,
I am facing the same issue
```
error: pulling environment repo https://github.com/siddharthkaushal90/environment-scribewax-production.git into /home/siddharthkaushal90/.jx/environments: git output: usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
                       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear: failed to run 'git stash push' command in directory '/home/siddharthkaushal90/.jx/environments/production', output: 'usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
                       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear'
```

any resolution for this instead of reconfiguring git?

**Comment by prashankprince** [comment]
Upgrading git version to 2.15.0 and later will help resolve this issue
