### ISSUE TITLE
jx gc previews fails to work when a preview build never succeeds

### ISSUE THREAD

**Issue by Tom-Hobson** [jenkins-x/jx#3898]
### Summary 

jx gc previews fails when a preview build has failed but the PR has been closed.

and because one has failed all future previews never get garbage collected.

### Steps to reproduce the behavior

Make a pull request to create a preview and break it. (maybe put some invalid characters in the requirements yaml or whatever)

see the build break and the environment not be created.

in kubectl get services -A

Close the pull request (without merging)

try to garbage collect the previews with

jx gc previews

### Expected behavior

The delete is skipped as there is no environment to delete.

### Actual behavior

see it fail because the pull request exists and has been closed but the environment doesn't exist.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.109
jenkins x platform 2.0.191
Kubernetes cluster v1.12.7
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.17.1
Operating System   Ubuntu 18.04.1 LTS
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

aks cluster.

### Operating system / Environment

Ubuntu console within windows 10

**Comment by deanesmith** [comment]
@Tom-Hobson Can you supply the error message your received when it failed and/or any relevant logs.

**Comment by Tom-Hobson** [comment]
Hi @deanesmith , Seems to work now.

Think it was due to the pr being open but no namespace or pods existing due to the build failing.

**Comment by deanesmith** [comment]
Thank you @Tom-Hobson.  I will close this Issue this issue based on your comment.  If something comes up please submit a new one.
