### ISSUE TITLE
simplify the UX of `jx create cluster / jx install`

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#3915]
right now the CLI asks way too many questions when not in batch mode.

How about we move most of the questions into an `--advanced` mode so if folks really want they can tweak thing - but just use smart defaults for most questions.

I guess we need to decide what are the minimal questions; I guess its

* tekton v jenkins
* domain
* where to put the environment git repos

thats probably about it?

**Comment by afirth** [comment]
would it be possible to move towards a yaml spec rather than command line flags? I know SIG cluster-api is doing a lot around there and will be allowing cluster creation. To me it would make sense to have the jx configuration in yaml, maybe even CRD - then checks can be done early and testing can be simplified. I think everything is already in the config object right?

**Comment by leosunmo** [comment]
I agree with @afirth . For me having it in a config file would make it a lot easier to customise the ingress setup as I recently had a lot of issue with Services, exposecontroller, the webhook URL and multiple ingress classes.
In all enviornments I've worked in we've always had two or more ingress classes. Right now I have a legacy ingress, private ingress and public ingress. I want the webhook behind the public ingress but all other services behind the private ingress.

Another issue is that I terminate my TLS at the Loadbalancer (this is common in at least AWS and as far as I know GKE) which means it's http inside the cluster (ingresses are *not* aware of TLS, there's no TLS field in ingress resources) but the URLs are always `https://`. Having a more advanced YAML config spec and less magic if you would rather configure some of this yourself would be a huge plus for me and probably a lot of other people that do not spin up a cluster purely for Jenkins X.

**Comment by jstrachan** [comment]
a long term solution to this is: https://jenkins-x.io/getting-started/boot/
