### ISSUE TITLE
jx create step is broken

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3925]
### Summary 

@abayer  The commit 98a094d98c282fe4d42e533b0abda3b078538632 broke the functionality of `jx create step`. Now it adds an empty `agent` (unnecessary clutter) and `loop` with `null` as values for `steps` and `values` inside. Such a loop fails to run and it does not pass the validations.

On top of that, `command` (it was `sh` before) does not execute at all so even if the `loop` section is removed manually after executinh `jx create step`, it does not do anything.

If the fix is not quick, can we revert the change to `create_step.go` while waiting for reorganization to finish?

**Comment by abayer** [comment]
I'll look into this tomorrow.

**Comment by abayer** [comment]
PR up - if there are test cases you'd like me to add, let me know and I will do so!
