### ISSUE TITLE
Adding new team fails to find vault

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#3931]
### Summary 

Adding a team causes team controller to fail with error about not being able to find the system vault name.

### Steps to reproduce the behavior
1. jx install -ng
2. jx create team A

### Expected behavior
Team A should be created

### Actual behavior
Team A does not get created. TeamController shows the following log:
`Unable to install jx for team A: configuring the git auth: creating the git auth config service: could not find the system vault name in namespace \"A\"`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.118
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE. Created manually.

### Operating system / Environment

Mac OSX

**Comment by msvticket** [comment]
I think I might have fixed this with the fix in step_helm_apply.go in #6220

**Comment by heroic** [comment]
@msvticket Your fix seems to be for AWS, while the error I was getting was for GKE. Would it still be fixed? The Changelog doesn't seem to indicate so, so I'm not sure.
