### ISSUE TITLE
Pipeline tekton quickstarts not working

### ISSUE THREAD

**Issue by carlosrodlop** [jenkins-x/jx#3941]
### Summary 

Tekton pipelines quickstarts do not work

It might be related to:

- https://github.com/jenkins-x/jx/issues/3928
- https://github.com/jenkins-x/jx/issues/3921

### Steps to reproduce the behavior

1.- Installing tekton in an existing cluster  `jx install --tekton`
2.- `jx create quickstart`

### Expected behavior

* Next Generation Pipelines being triggered
* A complete `jenkins-x.yml`

### Actual behavior

Git repository is created in the organization including the Jenkins X pipeline definition jenkins-x.yml but, the quickstart pipelines are not triggered. Observation: `jenkins-x.yml` has nothing apart from buildPack: <whatver-buildpack>

```
$> jx get activity -f quickstart-example
^C // It gets stuck so we canceled
$> jx get build logs jx-cluster-example/quickstart-example/master
error: No Pipeline found for name jx-support-beescloud/quickstart-example/master in values: 
$> jx get pipelines
Name                                                                        URL LAST_BUILD STATUS DURATION
jenkins-x/dummy/master                                                      N/A N/A        N/A    N/A
 jx-cluster-example/org-example-dev-production/master N/A N/A        N/A    N/A
 jx-cluster-exampled/org-example-dev-staging/master    N/A N/A        N/A    N/A
 jx-cluster-example/quickstart-example/master                               N/A N/A        N/A    N/A
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.111
jenkins x platform 2.0.191
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by sharepointoscar** [comment]
What cloud are you deploying your cluster to?  Are you deploying Jenkins X into an existing cluster, or are you able to create it as well?  It might be easier to run the following command.  But also, do upgrade to the latest `jx` build.

If you are using GKE, you can use the following which works:

`jx create cluster gke -m n1-standard-2 --min-num-nodes=3 --max-num-nodes=5 -z us-west1-a --skip-login  --default-admin-password=<my-password> --project-id <gcp-project-id> --tekton --git-username <bot-username> --git-api-token <github-apitoken>  --environment-git-owner <github-organization> `

**Comment by hferentschik** [comment]
I am going to close this issue. Using the latest version of `jx` and the boot install process as outlines [here](https://jenkins-x.io/getting-started/boot/), the quickstarts seems to work as expected.

@carlosrodlop, maybe you want to try the latest version of Jenkins-X and see whether things work for you. If you still have the same issue feel free to open a new issue or reopen this one if the same error occurs.
