### ISSUE TITLE
unknown flag: --wait while add app

### ISSUE THREAD

**Issue by Modelizer** [jenkins-x/jx#3947]
### Summary 
![Screenshot 2019-05-14 at 16 57 04](https://user-images.githubusercontent.com/7669734/57708280-5a4ab580-7669-11e9-8c74-87e2c874cc32.png)

### Jx version

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.119
jenkins x platform 2.0.276
Kubernetes cluster v1.11.7
kubectl            v1.10.11
helm client        Client: v2.13.0+g79d0794
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

As I remember I selected this
- [x] Serverless Jenkins (Tekton)

### Kubernetes cluster

KOPS (AWS)

### Operating system / Environment

dev

**Comment by garethjevans** [comment]
Hi @Modelizer, I think this is down to your version of kubectl, that flag was introduced in a later version (although I'm not sure which one - for reference, I'm on v1.14.1 and that flag exists), Gareth

**Comment by Modelizer** [comment]
Thanks @garethjevans problem fixed by update kubectl. 👍
