### ISSUE TITLE
jx step helm build Error: chart metadata (Chart.yaml) missing

### ISSUE THREAD

**Issue by s1apped** [jenkins-x/jx#3950]
### Summary 

jx step helm build throws error when promoting to Staging Environment 

### Steps to reproduce the behavior
1. jx create cluster aks  --cluster-name jxCluster --no-default-environments --git-provider-kind bitbucketcloud --git-provider-url https://bitbucket.org
2. create staging and production environments 
3. jx create spring --type gradle-project --git-provider-url=https://bitbucket.org --git-private

### Expected behavior

Successful jx step helm build

### Actual behavior
"Error: chart metadata (Chart.yaml) missing" 
![error](https://user-images.githubusercontent.com/32245059/57720663-9f2f1600-7682-11e9-9944-387a29f3ada5.png)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.119
jenkins x platform 2.0.276
Kubernetes cluster v1.12.7
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [X] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

AKS using jx create cluster aks

### Operating system / Environment
Ubuntu

**Comment by mamunozgonzalez** [comment]
I'm also having the same issue, but instead of AKS I created the cluster in GKE

**Comment by mamunozgonzalez** [comment]
Maybe is it required that we provided a Chart.yaml file in the repo? I'm pretty new to JX and I'm just follow simple tutorials but do not seem to work due to this issue.
