### ISSUE TITLE
Webhook issue while importing from Bitbucket Cloud

### ISSUE THREAD

**Issue by Modelizer** [jenkins-x/jx#3960]
### Summary 
When I try to import bitbucket cloud repository I see status 401 error.

### Steps to reproduce the behavior
- Create App Password from bitbucket setting.
- Configure bitbucket cloud server https://jenkins-x.io/developing/git/#bitbucket-cloud
- Import repository `jx import --url https://md-fortel@bitbucket.org/your-team/your-repo.git`

### Expected behavior
It should import successfully

### Actual behavior
`error: POST https://bitbucket.org/api/v3/repos/your-team/your-repo/hooks: 401  []`

### Jx version
```
NAME               VERSION
jx                 2.0.119
jenkins x platform 2.0.276
Kubernetes cluster v1.11.7
kubectl            v1.14.1
helm client        Client: v2.13.0+g79d0794
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

KOPS

### Operating system / Environment

Linux/AWS

**Comment by hervelemeur** [comment]
Probably related: #2149
