### ISSUE TITLE
Send logs to long term storage or a configured hot storage while the build is still executing

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#3964]
### Summary 

At the moment, when the CLI executes `jx get build logs`. these are obtained directly from the pods output for running builds and a configured bucket for finished builds.

There is a problem when a build doesn't end correctly as the logs are never sent to long term storage. If some time has passed, the pods will have been garbage collected and logs won't be accessible. 

### Steps to reproduce the behavior

Execute a build that fails or has one pod destroyed, wait some minutes for pods to be removed, try to get logs for that build. No logs will be available.

### Expected behavior

There should always be a log to check even if (and specially if) the build failed available in long term storage or some kind of hot storage.

### Actual behavior

There are no logs for some failed builds or builds that got a pod destroyed.

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by angoothachap** [comment]
If a build succeeds and there are some builds in `Running` state (from `jx get activity`), the latest build logs are till not found in long term storage

`$jx get activity
practise/s-with-d/master #4                                            Running Version: 0.0.5
  Release                                                              4h40m20s     1m0s Succeeded
  Promote: staging                                                     4h39m20s     1m7s Succeeded
    PullRequest                                                        4h39m20s     1m7s Succeeded  PullRequest: https://github.com/practise/dummy-cluster-staging/pull/4 Merge SHA: b40e779833
    Update                                                             4h38m13s       0s Succeeded
    Promoted                                                           4h38m13s       0s Succeeded  Application is at: http://s-with-d.jx-staging.35.200.119.91.nip.io
practise/s-with-d/master #5
practise/s-with-d/master #6                                            Running Version: 0.0.7
  Release                                                              3h54m21s     1m0s Succeeded
  Promote: staging                                                     3h53m21s     1m6s Succeeded
    PullRequest                                                        3h53m21s     1m6s Succeeded  PullRequest: https://github.com/practise/dummy-cluster-staging/pull/5 Merge SHA: 72224f0a36af
    Update                                                             3h52m15s       0s Succeeded
    Promoted                                                           3h52m15s       0s Succeeded  Application is at: http://s-with-d.jx-staging.35.200.119.91.nip.io
practise/s-with-d/master #7                                            Running Version: 0.0.8
  Release                                                              1h17m47s     1m0s Succeeded
  Promote: staging                                                     1h16m47s          Running
    PullRequest                                                        1h16m47s          Running  PullRequest: https://github.com/practise/dummy-cluster-staging/pull/6
practise/s-with-d/master #8                                            Running Version: 0.0.9
  Release                                                                 37m2s     1m0s Succeeded
  Promote: staging                                                        36m2s     1m8s Succeeded
    PullRequest                                                           36m2s     1m7s Succeeded  PullRequest: https://github.com/practise/dummy-cluster-staging/pull/7 Merge SHA: 1fb4ab2747f80
    Update                                                               34m55s       1s Succeeded
    Promoted                                                             34m55s       1s Succeeded  Application is at: http://s-with-d.jx-staging.35.200.119.91.nip.io`

`$ jx get build logs practise/s-with-d/master
? Which build do you want to view the logs of?:  practise/s-with-d/master #8
Build logs for practise/s-with-d/master #8
error: the build pods for this build have been garbage collected and the log was not found in the long term storage bucket`
