### ISSUE TITLE
Jenkins hostname should be set (for pull request links)

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#397]
Currently the PR links are to "unknown-hostname" for Jenkins, when ideally it would be configured with Jenkins actual host name (jenkins config can be updated to it)

**Comment by rawlingsj** [comment]
I’ve noticed this too. Interestingly I found that if you go to the Jenkins system config page and update anything on there, save then subsequent builds seemed to get the URL. if that is the case then there must be some logic somewhere we can reuse / trigger.

**Comment by michaelneale** [comment]
oh - so it is actually set correctly in the config on disk, its just not loaded... I wonder if a restart picks it up?

**Comment by michaelneale** [comment]
A restart did not make it pick it up https://stackoverflow.com/questions/46483609/jenkins-slack-notification-shows-unconfigured-jenkins-location implies it needs a port, but then a save cycle didn't do it. 

@rawlingsj can you point me to where in the cost the hostname is set?

**Comment by rawlingsj** [comment]
I just went to the jenkins config page for my test cluster http://jenkins.jx.35.195.227.251.nip.io/configure and clicked save, then retriggered a PR build that had previously run and when I click details on the CI checks on the PR it has the correct URL.  

https://github.com/rawlingsj/node3/pull/2

I can see the URL is in the configure page but it's odd that I have to hit save for the github detail link on the PRs to pick up the correct URL.

**Comment by rawlingsj** [comment]
> can you point me to where in the cost the hostname is set?

sorry do you mean in the config?  I think this is it..

<img width="1090" alt="screen shot 2018-03-15 at 23 02 19" src="https://user-images.githubusercontent.com/1457180/37495411-0585abb2-28a5-11e8-8436-180903e35aa1.png">

**Comment by michaelneale** [comment]
@rawlingsj oh - I was just trying to see if restart with help, I am sure a save works. 

I was more meaning where in the jx code is that hostname set programmatically (if it is)

**Comment by michaelneale** [comment]
@rawlingsj had any luck with this? All I can think of is that the email needs to be set to something non empty? Maybe that iwll make it pick it up automatically.

**Comment by rawlingsj** [comment]
I've honestly no idea about this - my guess is it's something in Jenkins, perhaps we could get someone from core to take a look and see if it sounds familiar?

**Comment by apaz037** [comment]
Still experiencing the issue with a cluster on GKE that was created via jx create cluster.
The following is jx version output.

![carbon 8](https://user-images.githubusercontent.com/17068663/42466690-9a81cc36-837d-11e8-8d91-cd8de7124731.png)

**Comment by rawlingsj** [comment]
I have a fix for this.  Pushing shortly.

**Comment by rawlingsj** [comment]
This is fixed and released https://github.com/jenkins-x/jx/releases/tag/v1.3.90

**Comment by rawlingsj** [comment]
you can force an update of Jenkins using `jx upgrade ingress`

**Comment by vm31** [comment]
i have upgrade my jenkins with jx upgrade ingress , what show i do after that? i mean how can i give valid hostname instead of localhost?
