### ISSUE TITLE
iks cluster needs kaniko

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#3971]
### Summary 

IBM Kubernetes Services (aka. `iks`) does not have dockerd running on its nodes as of k8s version 1.11. Instead they run containerd. So the default installation of JX cannot build Docker images any longer. It would need `kaniko` to enable this.

But `kaniko` is not yet available for `iks` clusters.

### Steps to reproduce the behavior

```bash
#!/bin/bash

set -eu

: ${JX_GIT_USER:="ascheman"}
# TODO filter for username
: ${JX_GIT_APITOKEN:=`yq r ~/.jx/gitAuth.yaml servers[0].users[0].apitoken`}

export JX_GIT_USER JX_GIT_APITOKEN

: ${JX_HOME:="$HOME/.jx_iks"}
# Name must not be longer than 10 chars - at least for default region us-east
: ${JX_NAME:="jx`date +%m%d%H`"}
: ${JX_REGION:="us-east"}

export JX_HOME JX_NAME JX_REGION

jx install \
    --provider=iks \
    --domain=${JX_NAME}.${JX_REGION}.containers.appdomain.cloud \
    --default-environment-prefix=${JX_NAME} \
    --on-premise \
    --environment-git-owner=${JX_GIT_USER} \
    --git-username=${JX_GIT_USER} \
    --git-api-token=${JX_GIT_APITOKEN} \
    \
    --kaniko=true \
    -b
```

### Expected behavior

Usable JX cluster on iks.

### Actual behavior

The install process aborts with 

```
error: unable to generate the Kaniko configuration: Kaniko is not supported for iks provider
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.123
jenkins x platform 2.0.191
Kubernetes cluster v1.12.8+IKS
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Kubernetes cluster

Created according to README in env-iks of cluster setup.

**Comment by pablog12** [comment]
I need a solution for this aswell, currently IBM dropped support of Kube v1.10, we were forced to update to version 1.12 so our setup stopped working altogether since jenkins is not able to build. We are pretty much stuck badly at this point.

Meanwhile, is there anything I can do to get it working again from my end?

**Comment by jstrachan** [comment]
creating a cluster with `--tekton` should now default to use kaniko btw

**Comment by ascheman** [comment]
Hmm, I suspect as long as there is this hard coded check for GKE kaniko will not work on IKS: https://github.com/jenkins-x/jx/blob/0229801795274d058047bf855f35edd43bc58fde/pkg/cmd/create/install.go#L2168-L2170
