### ISSUE TITLE
Upgrade skaffold dependency to satisfy Jenkins and EKS

### ISSUE THREAD

**Issue by phillycheeze** [jenkins-x/jx#3972]
### Summary 

The current version of skaffold shipped with jx is outdated. Particularly, EKS in it's latest AMI node release disables the bridge network (see: https://github.com/awslabs/amazon-eks-ami/issues/183)

Skaffold has added a new configuration option in skaffold/v1beta10 (release 0.29.0) for specifying the docker.network parameter passed along to the docker run command (see https://github.com/GoogleContainerTools/skaffold/issues/1771)

In that issue it is recommended to start docker with the `--network=host` argument in order for the docker container to connect to the internet.

### Steps to reproduce the behavior

1. Spin up jx in an existing EKS cluster with kubernetes 1.12 node AMIs (this is only reproducible on 1.12)
2. Build out a pipeline using the default Jenkinsfile and skaffold.yaml that is generated from `jx import`
3. The docker container being built by skaffold can't resolve any DNS or hit any IP address due to the bridge network being disabled in the latest AMIs.

### Expected behavior

The docker container should be able to reach the network.

### Actual behavior

No network connection inside of the docker container.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.101
jenkins x platform 2.0.276
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [*] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

AWS EKS created manually. 

### Operating system / Environment

OSX - not using CLI.

**Comment by garethjevans** [comment]
Closing this, the latest install has skaffold v0.31.0 available

**Comment by martin-patsov** [comment]
For anybody having the following errors: 
`Your Skaffold version might be too old. Download the latest version (0.37.1) at https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64` or `creating runner: parsing skaffold config: unable to parse config: yaml: unmarshal errors:\n  line 8: field network not found in type v1beta2.DockerArtifact`:

This may not be working out of the box for you. You may need to update the first line of `skaffold.yaml` to a greater version. E.g. `apiVersion: skaffold/v1beta11` is working.
