### ISSUE TITLE
Loop is not working

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3975]
### Summary 

The pipeline:

```grooovy
buildPack: go
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        preSteps:
        - command: echo "START"
        - loop:
            variable: ARCH
            values:
            - arch-1
            - arch-2
            - arch-3
            steps:
            - command: echo ${ARCH}
        - command: echo "END"
```

### Steps to reproduce the behavior

Run the pipeline.

### Expected behavior

Output one message for each value in the `loop`.

### Actual behavior

```
getting the log for build vfarcic/go-demo-6/PR-74 #13 serverless-jenkins stage from build pack and container build-step-build-step2
START
getting the log for build vfarcic/go-demo-6/PR-74 #13 serverless-jenkins stage from build pack and container build-step-build-step3
END
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.122
jenkins x platform 2.0.276
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by abayer** [comment]
Any chance you could get the `image` in your `pipelinerunner` controller? `loop` should be working in jx `2.0.119` and later, but I can never tell when that gets in the controller images etc...

**Comment by abayer** [comment]
Yup, verified in a test that it is doing the right thing - I think you're on `jenkinsxio/builder-maven:0.1.451`, but the fix for `loop` in build packs is in a later version (`0.1.453`, I believe).

**Comment by vfarcic** [comment]
It works now. There is a problem with `name` but I'll open a different issue for that.
