### ISSUE TITLE
regression: Pull requests are not built due to preview deploy failure

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#398]
To reproduce: 

* Fresh cluster
* Create spring boot app
* Open a PR on it
* Note PR fails 

Seems to be since preview environments were introduced 

```
helm lint
==> Linting .
[WARNING] templates/: directory not found

1 chart(s) linted, no failures
[Pipeline] sh
[preview] Running shell script
+ jx preview --app demo --dir ../..
Created environment ****-demo-pr-2
expose:
  config:
    domain: 35.189.48.145.nip.io
    exposer: ""
    http: ""
    tlsacme: ""
preview:
  image:
    repository: 10.23.244.38:5000/jenkinsx/demo
    tag: 0.0.0-SNAPSHOT-PR-2-1
Release "jx-****-demo-pr-2" does not exist. Installing it now.
EXITCODE   0Error: timed out waiting for the condition
Error: Command failed  helm upgrade jx-****-demo-pr-2 . --install --wait --namespace jx-****-demo-pr-2 --values=/home/jenkins/workspace/****_demo_PR-2-OSFA5LJP5GDPUEYCNY76RSVAC34X5B2JOTYRXZ2CV52BU3LTYJAA/charts/preview/extraValues.yaml
error: exit status 1
```

**Comment by rawlingsj** [comment]
I wonder if rbac is causing it to fail or maybe the helm version upgrade. I’ll take a look.

**Comment by michaelneale** [comment]
thanks @rawlingsj - didn't see another error. On retry it fails as it tried to update something that doens't exist (I think that may be a bum steer though, and this first error is the real one)

**Comment by rawlingsj** [comment]
yeah there's a helm issue that prevents deployments if the previous one was a failure.  Am just about to look into the first one.

**Comment by rawlingsj** [comment]
yeah it was an RBAC issues in the preview env, upgrading exposecontroller sorted it.  This is released now so available.
