### ISSUE TITLE
Support Bitbucket git provider in environment controller

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#3983]
### Summary 
I seems that at the moment the webhook events parsing is only implemented for GitHub. 

https://github.com/jenkins-x/jx/blob/a66284356f8cab094bdf096a4821e6c81eefbb53/pkg/jx/cmd/controller_enviornmentcontroller.go#L553

Extend the event parsing also for Bitbucket to enable Bitbucket Cloud provider for environment controller. 

Bitbucket event format documentation:
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by polothy** [comment]
@jstrachan would environment controller be updated with lighthouse?

**Comment by jstrachan** [comment]
@polothy exactly; the plan is to switch the environment controller to reuse lighthouse then it can support all git providers OOTB
