### ISSUE TITLE
Superfluous deploy to Nexus in Maven builds

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#3984]
### Summary 

Pipelines for building applications using maven (https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/tree/master/packs/maven) deploys the application jar-file to nexus. This is unnecessary; it's enough it's put in the image. This means that the persistent volume of Nexus fills up for no reason.

### Steps to reproduce the behavior

Import a repo into Jenkins-X for an application built with maven.

### Expected behavior

Nexus is only used to speed up download of dependencies.

### Actual behavior

The resulting jar is deployed to Nexus.

**Comment by tomhobson** [comment]
This is now deprecated. This repo is now defunct so going to close this.

Thanks for the issue!
