### ISSUE TITLE
jx step env apply uses default values for secrets

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#3988]
### Summary 

Versions after 2.0.118 of jx silently fails to get any values files with secrets from vault and thus the default values are used. This means for example that the jenkins password is reset to the default and number of other problems.

The culprit is PR #3902 that changes jx to use new paths in the requests to vault. I am running vault 0.11.6 (the default in Jenkins-X when I installed the cluster 2 months ago) and jx now fails in getting the secrets from vault. To make it worse jx doesn't realise the problem and just goes ahead with no secrets fetched:

```
Fetching secrets from vault into directory "/.../env"
Ignoring templates/committer-role.yaml
```

At the very least jx should fail preventing the dev environment from getting a faulty configuration. Preferably it should handle older vault versions.

**Comment by ccojocar** [comment]
@msvticket Closing this since the secrets are now handled in a different way with boot.
