### ISSUE TITLE
investigate using ECR on AWS for container registry

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#399]

**Comment by ysaakpr** [comment]
IS there anyone who did this setup?. I would also like to setup AWS ECR for my Org.

**Comment by andrewwippler** [comment]
FYI - for this to work, the cluster needs to have `--cloud-provider=aws` on the kubelet. Kops and EKS should already have this turned on and configured correctly.

**Comment by andrewwippler** [comment]
The `kubelet` is the primary “node agent” that runs on each node. You can find all of its configuration variables here: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ 

The official documentation describes the requirements needed here: https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry
Most notably:
- nodes must be AWS EC2 instances.
- kubelet is running with `--cloud-provider=aws`.

I am not sure how Jenkins-x internals work quite yet (haven't had time to play with it after installing a few days ago), but the docker tag should define what registry it should be pushed to.

I was able to get a vanilla kubernetes cluster working with AWS ECR by running this gist (Ubuntu 16.04):
https://gist.github.com/andrewwippler/3f031536ef7d761792b8fce1fd967aef

Your mileage may vary, but I also had to give my single node's IAM role access to my registry.

**Comment by jstrachan** [comment]
BTW I’ve been working on making it easier to switch to any docker registry; we’ve made lots of progress so I’m hoping soon we’ll be able to show how to use ECR/GCR/ACR/harbor etc. 

there’s going to be a few things to do this:

* enable the docker registry in your cloud provider - we’re thinking the simplest thing here is use Terraform to configure all your cloud & infrastructure resources. We hope to have demos soon...
* configure the docker registry host via helm. This bit is done though not yet released; the 2.0 branch of the build packs now use the `DOCKER_REGISTRY` env var that you can specify in helm or manually configure in the Jenkins UI
* setup the `jenkins-docker-cfg` secret to contain the required `config.json` to be able to use your docker registry. Again we could try automate this & the helm setting via Terraform or we could add a CLI command to help.

Will update this issue once we’ve released it...

**Comment by ysaakpr** [comment]
How are the credential-helper binaries planned to get integrated ? Will it be part of the builder-base...I was trying to the things as you @jstrachan  mentioned, but was getting docker-credential-ecr-login error, since its not found in the PATH.. What would be the proposed way of using this binary

**Comment by ysaakpr** [comment]
@jstrachan @andrewwippler it will be helpful if someone can explain the process of having different docker-credential-helper integration. what is the write way to extend the builder-base, if builder-base cant support requirements like this what is the suggested way to use the jenkins agents.

**Comment by jstrachan** [comment]
Something like this should do the trick:
```
kubectl delete secret  jenkins-docker-cfg
kubectl create secret generic jenkins-docker-cfg --from-file=./config.json
```

**Comment by jstrachan** [comment]
more docs here: https://jenkins-x.io/architecture/docker-registry/

**Comment by ysaakpr** [comment]
https://github.com/awslabs/amazon-ecr-credential-helper, as per this this method for ECR require a binary to be present in the PATH.. Either I have to ensure the pod template that used is having this binary, or the default builder-base should have it. Can you confirm the suggested way to use it. I don't think mounting this binary file as a secret is the right option

**Comment by ysaakpr** [comment]
@jstrachan,  What is your opinion, on adding cloud registry helpers to the builder-base ?
https://github.com/docker/docker-credential-helpers

**Comment by cat-turner** [comment]
did anyone get this to work, up and running? curious.

**Comment by jstrachan** [comment]
Yeah, ECR is now enabled OOTB on AWS and EKS. Sorry i forgot to close this issue ;)
