### ISSUE TITLE
investigate using Google Container registry on GKE

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#400]

**Comment by jstrachan** [comment]
so if you edit the `DOCKER_REGISTRY` environment variable in the Jenkins console `jx console` then go to `Manage Jenkins -> Configure System` you can point this to your GCR registry server. e.g. `gcr.io` or `eu.gcr.io`.

Then to update the `config.json` secret generate a file called `config.json` like this:
```json
{
    "credHelpers": {
        "gcr.io": "gcloud",
        "us.gcr.io": "gcloud",
        "eu.gcr.io": "gcloud",
        "asia.gcr.io": "gcloud",
        "staging-k8s.gcr.io": "gcloud"
    }
}
```
Then ensure that the `ORG` in your `Jenkinsfile` and `skaffold.yaml` files is the name of your GKE project.

Now the pipelines will try use GCR; though we still need to update the Jenkins `ServiceAccount` so it has karma to be able to push to the GCR registry

**Comment by jstrachan** [comment]
The main thing missing now is how to setup the IAM stuff so that build pods in Jenkins X can write to the `gcr.io` repository. Anyone know how we should do that? :)

**Comment by dlorenc** [comment]
k8schain should be your friend here: https://github.com/google/go-containerregistry/tree/master/pkg/authn/k8schain

**Comment by jjouanno** [comment]
Hello,

I tried a lot of things for pushing my image to gcr.io.

Updating the corresponding kubernetes secret don't work.
Call gcloud command don't work
...


Only one way work for me:

1. Installing Jenkins plugins [Google OAuth](https://plugins.jenkins.io/google-oauth-plugin) and [Google Container Registry Auth](https://plugins.jenkins.io/google-container-registry-auth)
2. Create a new credential of type "Google Service Account From private key" and use the json authentication file with the correct project name
3. And in the Jenkinsfile use (remark: prefixed credential id by gcr)
``` 
steps {
    container('jx-base') {
        script { 
	    myImage = docker.build("gcr.io/$ORG/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER")
            docker.withRegistry("https://gcr.io", "gcr:cred-id") { 
                myImage.push("SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER")
	         }
            }
        }
    }
```

I have respected recommandation for ORG: is the project id in google console.

I hope this help you.

Regard

**Comment by mikaelmh** [comment]
Are there any updates or progress on this @jstrachan ? Would be fantastic to use Google Container registry for all our images, including the jenkins-x ones. Thanks a lot!

**Comment by dlorenc** [comment]
I got this working awhile ago by changing the skaffold.yaml to use GCB: https://github.com/dlorenc/golang-http/blob/master/skaffold.yaml

and making sure my cluster nodes had the correct IAM scopes to call GCB.

**Comment by mikaelmh** [comment]
@dlorenc awesome! thanks for sharing your configurations. Will give this a try!

**Comment by mikaelmh** [comment]
@dlorenc I have followed your first steps and reconfigured the skaffold (also installed setup Google OAuth and Google Container Registry Auth on Jenkins as was hinted above).

How did you make sure your cluster nodes had the correct IAM scopes to call GCR? ( the cluster/nodes is under the same project as the GCR)

I keep getting;

```time="2018-10-16T00:12:43Z" level=fatal msg="build step: building [gcr.io/project/demo]: pushing: denied: Access denied."```

Thanks!

**Comment by bryanlarsen** [comment]
This is listed in the current sprint, which kind of implies that somebody is working on this.   Is it close?  https://jenkins-x.io/faq/issues/#http-server-gave-http-response-to-https-client mentions that GCR is the preferred solution when running on GKE, so it'd be nice to have some good instructions on how to get that to work.

**Comment by bryanlarsen** [comment]
This is listed in the current sprint, which kind of implies that somebody is working on this.   Is it close?  https://jenkins-x.io/faq/issues/#http-server-gave-http-response-to-https-client mentions that GCR is the preferred solution when running on GKE, so it'd be nice to have some good instructions on how to get that to work.

**Comment by bryanlarsen** [comment]
I finally got it to work.   I made a large number of changes which were probably ineffectual, but what probably did work was to add the storage-full scope to the nodes in the cluster.   https://medium.com/google-cloud/updating-google-container-engine-vm-scopes-with-zero-downtime-50bff87e5f80

**Comment by jtnord** [comment]
imported as PLAT-45

**Comment by garethjevans** [comment]
using the latest skaffold (0.19.0) I've got this to work on a repo, next steps it to work out the best way of integrating this into the `jx create cluster` process.

Repo: https://github.com/garethjevans-test/kankio-test01

**Comment by ccojocar** [comment]
@garethjevans I think we can close this issue since now the GCR is supported.
