### ISSUE TITLE
FATAL: initialise build packs failed: git output: There is no tracking information for the current branch.

### ISSUE THREAD

**Issue by malingxin** [jenkins-x/jx#4001]
### Summary 
jx install error
### Steps to reproduce the behavior
run jx install error
### Expected behavior
install jx
### Actual behavior
FATAL: initialise build packs failed: git output: There is no tracking information for the current branch.
### Jx version

```
jx version
NAME               VERSION
jx                 2.0.128
Kubernetes cluster v1.10.5-tke.4
kubectl            v1.10.5-tke.4
helm client        Client: v2.10.0+g9ad53aa
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.5.1804 (Core)
The output of `jx version` is:
```

### Operating system / Environment

```
# jx install
? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Setting the dev namespace to: jx
Using helmBinary helm with feature flag: template-mode
Context "master" modified.
? Cloud Provider kubernetes
Enabling helm template mode in the TeamSettings
Git configured for user: malingxin and email ***
Using helm2
Skipping tiller
Using helmBinary helm with feature flag: template-mode
Initialising Helm 'init --client-only'
helm installed and configured
FATAL: initialise build packs failed: git output: There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master: failed to run 'git pull' command in directory '/root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes', output: 'There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master'
```

**Comment by garethjevans** [comment]
Hi @malingxin, can you take a look at ``~/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/` and possible run a `git remote -v` & `git pull` in that directory?

As a workaround, you may be able to remove that folder and allow the install to reclone it.

**Comment by garethjevans** [comment]
possible duplicate of #3897

**Comment by garethjevans** [comment]
As a possible workaround, can you try:

```
cd ~/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes
git branch --set-upstream-to=origin/master master
```

**Comment by sandoxas** [comment]
> Hi @malingxin, can you take a look at ``~/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/`and possible run a`git remote -v` & `git pull` in that directory?
> 
> As a workaround, you may be able to remove that folder and allow the install to reclone it.

When executing "$ git pull" inside the folder "/root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes", its gives the same output as before with the "jx install" command.

**Comment by weiwc** [comment]
l also meet this issue.   
This is my Jx version:
```
NAME               VERSION
jx                 2.0.368
Kubernetes cluster v1.15.0
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                git version 2.22.0
Operating System   "CentOS Linux release 7.6.1810 (Core) "
```
I try your method and they are valuable.
```
# cd ~/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes
# git remote -v
origin	https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git (fetch)
origin	https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git (push)
# git checkout master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Already on 'master'
# git branch
* master
# git branch --set-upstream-to=origin/master master
Branch 'master' set up to track remote branch 'master' from 'origin'.
# jx install ...
...
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /root/.jx/jenkins-x-versions
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Compressing objects: 100% (10/10), done.
Total 1803 (delta 1), reused 3 (delta 0), pack-reused 1793
...
```
Now my problem has been solved.I think part of the reason may be that git's version is too low.The original version of my git was 1.8.3, and then manually updated to the latest version（2.22.0）.I think maybe the version of git must be over 2.0.

Thank you for your  help.@garethjevans

I hope my situation will be useful to other.

**Comment by dgozalo** [comment]
I've tried to reproduce this error without any luck (I even downgraded my git version to the one specified in the issue). I've only been able to get that error by checkout out to a branch other than Master before performing the install.

My understanding is that, this problem being 2 months old, we've already changed something in our git code that solves this.

However, I'm thinking about executing `git checkout master` and `git branch --set-upstream-to=origin/master master` when dealing with the buildpack repo, just in case.

What do you think @garethjevans?

**Comment by dgozalo** [comment]
Taking a look at the code, a new `Clone` function was added 3 months ago which added  the `set-upstream-to` command. 

My guess is that it's possible that the repositories that are throwing this error were cloned before that change and they are fixed by doing `set-upstream-to`. So for new clones, it should work.

However, I think executing that command before a pull should solve this for older repository clones.
