### ISSUE TITLE
Release pipeline fails

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#4019]
### Summary 

On a newly installed cluster, builds fail on the release pipeline.

### Steps to reproduce the behavior
1. jx import
2. git push
3. merge PR

### Expected behavior
The build should pass

### Actual behavior
The build fails with the error:

```
! [rejected]        v0.0.58                 -> v0.0.58  (would clobber existing tag)
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.137
Kubernetes cluster v1.13.5-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
GKE manually created

### Operating system / Environment

MAC OSX

**Comment by langleyd** [comment]
Also seeing this:
```
jx                 2.0.112
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.11.9-dispatcher
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.9 (stretch)
```

**Comment by langleyd** [comment]
Was also able to work around it by creating a promote pre-step(`git fetch --tags --all --prune -f`)  as outlined by @heroic in slack.

**Comment by jwtodd** [comment]
fails for me as well on jx v2.0.119, osx, gke --tekton

**Comment by jwtodd** [comment]
after applying the suggested work-around the promote-jx-promote step succeeds but now the promote-helm-promote step fails

> Was also able to work around it by creating a promote pre-step(`git fetch --tags --all --prune -f`) as outlined by @heroic in slack.

error: Failed to post chart to http://jenkins-x-chartmuseum:8080/api/charts due to response 409: {"error":"file already exists"}

thoughts?

**Comment by warrenbailey** [comment]
This may be fixed in the latest version of jx, @heroic any chance you could retry it?

**Comment by iftachsc** [comment]
hitting this also. anybody knows how to workaround this with running jx step tag --version before the release?

**Comment by hoangmnsd** [comment]
I'm getting same issue, and add step `git fetch --tags --all --prune -f` cannot solve problem. Any ideas?
