### ISSUE TITLE
discussion: should we disable issues on all jenkins-x repos apart from jx?

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#4032]
### Summary 

Dealing with issues in multiple repos/orgs can cumbersome.  Should we disable issues on all other repositories so they get created here?

**Comment by hferentschik** [comment]
>  Should we disable issues on all other repositories

What do you understand w/ all? All under the jenkins-x org or even repos under say jenkins-x-apps?
I agree it can be cumbersome to track issues, but I fear using the jx issue tracker for everything makes things worse.

> so they get created here?

So how do I reference an issue from another repo then? How would change log creation work? Would you have to mirror issues in jx in the affected repo?

**Comment by hferentschik** [comment]
I think something like ZenHub or CodeTree might give us a bit more transparency since it allows to filter and search issues across all configured repos.

**Comment by garethjevans** [comment]
That's a great point @hferentschik, maybe apps would need to be managed separately.  This suggestion came from a conversation with @deanesmith about the use of ZenHub/CodeTree and how they weren't quite suited to multiple orgs/repos.  Let me do some analysis of where the open issues are and I'll post it on here.

**Comment by hferentschik** [comment]
> That's a great point @hferentschik, maybe apps would need to be managed separately. 

I don't have full insight into the various repos under jenkins-x. Maybe there it might make sense to close some issue trackers and use jx. I would decide on a case by case basis depending on how the repo relates to jx. I have a feeling there also quite a few unused repos there.

Regarding jenkinx-x-apps, I feel quite strongly that they should be managed separately.

> Let me do some analysis of where the open issues are and I'll post it on here.

+1

**Comment by garethjevans** [comment]
Ok, the number of open issues by org are:

jenkins-x - 922
jenkins-x-charts - 13
jenkins-x-apps - 20
jenkins-x-buildpacks - 15
jenkins-x-images - 0
jenkins-x-quickstarts - 3

**Comment by garethjevans** [comment]
In a bit more detail

```
jenkins-x - 921
	exposecontroller - 39
	jx-release-version - 12
	charts - 2
	jenkins-x-platform - 46
	jenkins-x-website - 1
	jenkins-x-image - 9
	old-draft-repo - 1
	jx - 697
	default-environment-charts - 2
	updatebot - 15
	chyle - 1
	jx-docs - 20
	exposecontroller-service - 1
	vscode-jx-tools - 10
	terraform-provider-jx - 1
	bdd-jx - 6
	sso-operator - 3
	jx-tutorial - 5
	prow-config - 2
	jenkins-x-extensions - 10
	jenkins-x-serverless - 6
	jenkins-x-builders - 8
	dev-env - 3
	jenkins-x-serverless-filerunner - 12
	jenkins-x-versions - 4
	cloud-environments - 2
	environment-tekton-mole-dev - 2
	prow-config-tekton - 1
jenkins-x-charts - 13
	nexus - 5
	knative-build - 2
	vault-operator - 2
	environment-controller - 2
	tekton - 1
	environment-seedbog-staging - 1
jenkins-x-apps - 20
	jx-app-jacoco - 6
	jx-app-istio - 1
	jx-app-cheese - 8
	jx-app-sonarqube - 1
	jx-app-test-lifecycle - 3
	jx-app-sso - 1
jenkins-x-buildpacks - 15
	jenkins-x-classic - 5
	jenkins-x-kubernetes - 10
jenkins-x-images - 0
jenkins-x-quickstarts - 3
	golang-http - 1
	rust-http - 1
	angular-io-quickstart - 1
```

**Comment by garethjevans** [comment]
actually, this number includes open pull requests too, will see if I can filter them out

**Comment by garethjevans** [comment]
an updated list

```
jenkins-x - 831
	exposecontroller - 36
	jx-release-version - 8
	jenkins-x-platform - 37
	jenkins-x-website - 1
	jenkins-x-image - 5
	jx - 680
	default-environment-charts - 1
	updatebot - 12
	jx-docs - 15
	exposecontroller-service - 1
	vscode-jx-tools - 10
	bdd-jx - 1
	sso-operator - 3
	jx-tutorial - 3
	jenkins-x-extensions - 10
	jenkins-x-serverless - 2
	jenkins-x-builders - 2
	dev-env - 3
	jenkins-x-serverless-filerunner - 1
jenkins-x-charts - 7
	nexus - 4
	knative-build - 2
	vault-operator - 1
jenkins-x-apps - 11
	jx-app-jacoco - 6
	jx-app-cheese - 3
	jx-app-test-lifecycle - 2
jenkins-x-buildpacks - 6
	jenkins-x-classic - 3
	jenkins-x-kubernetes - 3
jenkins-x-quickstarts - 0
```

**Comment by hferentschik** [comment]
Right, so there are quite a few repos, but what are the pain points we would try to address by closing the issue tracker for all these repos except one?

If the main concern is that issues gets overlooked, I think CodeTree might be able to help. It lets you aggregate over multiple repositories and you can slice and dice the view with various sort and search filters. On top of that, we could then use milestones (CodeTree milestones which sync/reflect to GitHub milestones) to track sprints. If you create a milestone/sprint in CodeTree the same milestones is created in all linked repos.

**Comment by ccojocar** [comment]
I am closing this since now we a way to track PRs with SDM across multiple repositories.
