### ISSUE TITLE
Prometheus Addon Works Only With jx Namespace

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#4033]
### Summary 

It seems that the Prometheus addon works only if Jenkins X is installed in the `jx` Namespace.

### Steps to reproduce the behavior

```bash
kubectl get ns
```

```
NAME            STATUS   AGE
cd              Active   34m
cd-production   Active   24m
cd-staging      Active   25m
default         Active   35m
istio-system    Active   8m31s
kube-public     Active   35m
kube-system     Active   35m
```

```bash
jx create addon prometheus
```

### Expected behavior

Prometheus is installed

### Actual behavior

```
error: cannot create secret prometheus-ingress in target namespace jx: namespaces "jx" not found
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.145
jenkins x platform 2.0.276
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [X] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by vfarcic** [comment]
@carlossg is this one of yours?

**Comment by vfarcic** [comment]
I just noticed that there is the argument `--namespace`. Still, it might be misleading to assume that Prometheus is installed in jx while other addons (e.g., Istio) run in their own namespace and hence do not need to know where `jx` is running.

**Comment by carlossg** [comment]
All addons have the `--namespace` option, only special ones like istio are installed on their own.
