### ISSUE TITLE
jx install fails to install on EKS

### ISSUE THREAD

**Issue by vishalraina** [jenkins-x/jx#4039]
### Summary 
jx install unable to complete install on existing EKS cluster 
### Steps to reproduce the behavior
Run the following the command to install Jenkins x with both serverless or static
jx install --verbose --provider=eks --exposer=LoadBalancer
### Expected behavior
FInish install successfully and return URL for jenkins x
### Actual behavior
Removing Kubernetes resources from older releases using selector: jenkins.io/chart-release=jenkins-x,jenkins.io/version!=2.0.330 from all pvc configmap release sa role rolebinding secret
Removing Kubernetes resources from older releases using selector: jenkins.io/chart-release=jenkins-x,jenkins.io/version!=2.0.330,jenkins.io/namespace=jx from clusterrole clusterrolebinding
WARNING: waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx
Configuring the TeamSettings for ImportMode Jenkinsfile

        ********************************************************

             NOTE: Your admin password is:XXXXXXXXXXX

        ********************************************************

        
Configure Jenkins API Token
WARNING: 
retrying after error:creating Jenkins Auth configuration: unable to find external URL annotation on service jenkins in namespace jx

WARNING: 
retrying after error:creating Jenkins Auth configuration: unable to find external URL annotation on service jenkins in namespace jx

error: configuring Jenkins: creating Jenkins API token: after 3 attempts, last error: creating Jenkins Auth configuration: unable to find external URL annotation on service jenkins in namespace jx

Configure Jenkins API Token
WARNING: 
retrying after error:creating Jenkins Auth configuration: unable to find external URL annotation on service jenkins in namespace jx

WARNING: 
retrying after error:creating Jenkins Auth configuration: unable to find external URL annotation on service jenkins in namespace jx

error: configuring Jenkins: creating Jenkins API token: after 3 attempts, last error: creating Jenkins Auth configuration: unable to find external URL annotation on service jenkins in namespace jx

### Jx version

The output of `jx version` is:

```
WARNING: Failed to retrieve team settings: failed to create the jx client: Unauthorized - falling back to default settings...
WARNING: Failed to find helm installs: running helm list --all --namespace : failed to run 'helm list --all --namespace ' command in directory '', output: 'Error: Unauthorized'
WARNING: Failed to get Kubernetes server version: the server has asked for the client to provide credentials
WARNING: Failed to get kubectl version: Command failed 'kubectl version --short': Client Version: v1.14.1
error: You must be logged in to the server (the server has asked for the client to provide credentials) exit status 1

WARNING: Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.12.0+gd325d2a
Error: Unauthorized'
NAME             VERSION
jx               2.0.151
git              git version 2.20.1 (Apple Git-117)
Operating System Mac OS X 10.14.5 build 18F132

```

### Jenkins type

Tried all the options resulting into same issue
- [X ] Next Generation (Tekton + Prow)
- [ X] Classic Jenkins
- [ X] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

EKS cluster

### Operating system / Environment

Operating System Mac OS X 10.14.5 build 18F132

**Comment by YuTingLiu** [comment]
@hferentschik Same issue, have you found any solution yet?

**Comment by thephw** [comment]
What is your cluster size? Instance type and number of nodes?

**Comment by thephw** [comment]
https://github.com/cncf/k8s-conformance/tree/master/v1.13/eks

Had some updates I need to make to my cluster in the security groups and number of nodes to have enough network interfaces for the default installation.

**Comment by deanesmith** [comment]
Hi @vishalraina,  

I do believe recent improvements for AWS support and Tekton pipelines will resolve your issue for serverless deployments though you should be aware that static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
