### ISSUE TITLE
Move user facing instuctions from README.md to jenkins-x.io

### ISSUE THREAD

**Issue by bitwiseman** [jenkins-x/jx#404]
Where possible there should be one source of truth for install and setup.  The instructions in install and setup should be removed from the https://github.com/jenkins-x/jx#getting-started and replaced with a pointer to http://jenkins-x.io/getting-started/ .   

The instructions on the website are significantly less detailed than the README.  Either both need to be kept in-sync and up-to-date or the information should be kept in one place - the official website.

**Comment by michaelneale** [comment]
+1 - move to website I think. There are many repos that make up JenkinsX, but the website is where people will look I guess? it gets my vote.

**Comment by rawlingsj** [comment]
@jstrachan did this earlier, closing with this commit https://github.com/jenkins-x/jx/commit/0e3703dde684a6b9a483535ed2ceae379a5abe87 

The [readme](https://github.com/jenkins-x/jx/blob/master/README.md) is looking much much better and links off to the website, nice one @jstrachan!
