### ISSUE TITLE
jx delete application failure

### ISSUE THREAD

**Issue by amulobaev-aurea** [jenkins-x/jx#4074]
### Summary 

I have an issue with command 'jx delete application'. It throws an error 'error: deleting application: 500 Server Error' without any details

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.172
Kubernetes cluster v1.10.13-eks-g484b8
kubectl            v1.14.2
git                git version 2.1.4
Operating System   Debian 8.0 based distribution
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by amulobaev-aurea** [comment]
Hi. Any update?

**Comment by Markus-ipse** [comment]
I'm having the same problem:

NAME               VERSION
jx                 2.0.666
jenkins x platform 2.0.951
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.13.7
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.1+g5270352
git                2.19.1
Operating System   Mac OS X 10.14.6 build 18G87
