### ISSUE TITLE
Add support for k3s

### ISSUE THREAD

**Issue by gbonnefille** [jenkins-x/jx#4085]
### Summary 

It would be great to support [k3s](https://k3s.io/) just like minishift or minikube.

### Kubernetes cluster

K3s

### Operating system / Environment

Linux

**Comment by Lohann** [comment]
+1

**Comment by em-jones** [comment]
/remove-lifecycle stale

> Issues go stale after 90d of inactivity.
> Mark the issue as fresh with `/remove-lifecycle stale`.
> Stale issues rot after an additional 30d of inactivity and eventually close.
> If this issue is safe to close now please do so with `/close`.
> Provide feedback via https://jenkins-x.io/community.
> /lifecycle stale

**Comment by ankitm123** [comment]
This is already supported: https://jenkins-x.io/v3/admin/platforms/k3s/
/close
