### ISSUE TITLE
Pipelines not starting

### ISSUE THREAD

**Issue by cdbkr** [jenkins-x/jx#4087]
### Summary 
Jenkins-x Serverless pipelines seem not running and PODS are stuck in Pending state. 

### Steps to reproduce the behavior
Install a Cluster with Jenkins-x Serverless on GKE (standard setup)

### Expected behavior
Whenever a PR is being merged or a general commit is pushed to master, pipelines get started normally and steps are executed.

### Actual behavior
Whenever a PR is being merged or a general commit is pushed to master, pipelines are stuck and waiting for a container to start.

Pods:
```
my-node-project-master-3-from-build-pack-bjpmg-pod-cf423b           0/12    Pending     0          16m
my-node-project-master-release-2-from-build-pack-889lt-pod-7f45b6   0/12    Pending     0          16m
my-rust-project-master-1-from-build-pack-c7kkd-pod-ef705a           0/12    Pending     0          16m
```

jx get build logs

```
waiting for pod my-node-project-master-3-from-build-pack-bjpmg-pod-cf423b container build-step-credential-initializer-sffhw to start...
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.167
jenkins x platform 2.0.330
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Jenkins X Status:
 WARNING: Jenkins X installed for Cluster(...us-east1...): 2 nodes, memory 33% of 11556272Ki, cpu 100% of 3860m.
needs more free compute

### Operating system / Environment

Mac OS X 10.14.5 build 18F132

**Comment by warrenbailey** [comment]
hi @cdbkr is this a tekton or JenkinsFileRunner based cluster? 

I created a Tekton cluster today and this all works for me. Is it still an issue for you?

Also looks like your cluster is maxed out on cpu? Have you tried increasing the clusters resources?

**Comment by cdbkr** [comment]
Hi @warrenbailey , thanks, it was a tekton based cluster.
Please, let me try recreating the cluster with a newer jx version + increasing the resources. I am double checking it.

**Comment by cdbkr** [comment]
I have tried to re-create the cluster with 
```
jx                 2.0.219
jenkins x platform 2.0.330
Kubernetes cluster v1.12.7-gke.10
```
and it seems a problem related to resources. 
Indeed it doesn't work properly with
`... --min-num-nodes 1 --max-num-nodes 3`

but it does work properly with 
`...--min-num-nodes 3 --max-num-nodes 5`

So compared to the Static version, it requires more resources.

**Comment by warrenbailey** [comment]
On a static Jenkins master installation there's a single pod with Jenkins installed, whereas in a Next generation enabled cluster there are more components installed (i.e. tekton, prow etc) which provides a richer experience. Hence the needs for more resources.

I generally tend to run with the defaults (min 3 nodes, max 5). Let me try it with a min of 1 and max of 3.

**Comment by warrenbailey** [comment]
I've just tried with a min/max of 1/3 nodes using n1-standard-2 machine types and it still worked for me. Though granted 3 nodes were spun up.

I'm going to close this issue as it's due to low cluster resources rather than a Jenkins X issue

/close
