### ISSUE TITLE
Remove Minishift/Minikube cluster options

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#4088]
### Summary 

Running Jenkins-X on Minishift/Minikube does not seem to be terribly useful given that these single node clusters won't be reachable from the outside, meaning that webhooks et all won't work.

There are also resource constraints. A full Jenkins-X install with all its components just takes too many resources for such a single node cluster.

Last but not least, Minishift is now in maintenance mode. It won't work with OpenShift 4 anymore.

**Comment by dennisnewel** [comment]
not sure how entangled the code is, but could this possibly be handled in two phases? phase one would remove any mention of minishift/-kube from documentation and CLI, and the second phase would remove the now redundant code?

actually, Phase 0 would probably be to call it out in the docs that this approach is deprecated?
