### ISSUE TITLE
Typo: Snapshpt

### ISSUE THREAD

**Issue by bitwiseman** [jenkins-x/jx#409]
Multiple projects in jenkins-x have the same typo: "snapshpt" 

https://github.com/search?q=org%3Ajenkins-x+snapshpt&type=Code

**Comment by rawlingsj** [comment]
Great thanks. Any chance you could send the PRs and we’ll get them merged? Thanks.

**Comment by bitwiseman** [comment]
Opened PR's for all of these typos.

**Comment by rawlingsj** [comment]
great thanks!
