### ISSUE TITLE
jx create terraform fails when using terraform 0.12.0

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#4090]
### Summary 

When running `jx create terraform` using terraform 0.12.0 the command fails with multiple errors.

It seems there is validation in the latest version of terraform which means the terraform variables need to be defined upfront.

### Steps to reproduce the behavior
run `jx create terraform`

### Expected behavior
Command should run successfully

### Actual behavior
Command fails with:

error: failed to run 'terraform plan -var-file=/Users/warrenbailey/.jx/organisations/organisation-pumaglen/clusters/warren-dev/terraform/terraform.tfvars -var credentials=/Users/warrenbailey/.jx/organisations/organisation-pumaglen/clusters/warren-dev/jx-pumaglen-warren-dev.key.json /Users/warrenbailey/.jx/organisations/organisation-pumaglen/clusters/warren-dev/terraform' command in directory '', output: 'Acquiring state lock. This may take a few moments...

Warning: Value for undeclared variable

  on /Users/warrenbailey/.jx/organisations/organisation-pumaglen/clusters/warren-dev/terraform/terraform.tfvars line 4:
   4: organisation = "pumaglen"

The root module does not declare a variable named "organisation". To use this
value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.

Warning: Value for undeclared variable

  on /Users/warrenbailey/.jx/organisations/organisation-pumaglen/clusters/warren-dev/terraform/terraform.tfvars line 5:
   5: provider = "gke"

The root module does not declare a variable named "provider". To use this
value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.

Error: Unsupported block type

  on .jx/organisations/organisation-pumaglen/clusters/warren-dev/terraform/main.tf line 56, in resource "google_container_cluster" "jx-cluster":
  56:   resource_labels {

Blocks of type "resource_labels" are not expected here. Did you mean to define
argument "resource_labels"? If so, use the equals sign to assign it a value.
'

### Jx version
The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.182
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by garethjevans** [comment]
Closing this as its now implemented

**Comment by warrenbailey** [comment]
Fixed in https://github.com/jenkins-x/jx/pull/4121
