### ISSUE TITLE
Regression: Need to open jenkins to copy and paste the API token

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#411]
For the last few weeks when setting up a new cluster this was not required. 

However today (building from master) I noted every time (on new create cluster) I had to open jenkins and copy and paste. This is quite a cumbersome experience considering it was transparent before. 

Any reason why this is back to the old way it was?

**Comment by jstrachan** [comment]
So that’s all my fault sorry. I was trying to get the install to work on AWS where there is no chrome browser installed.

There is a cli argument to use the browser to generate the API token. Maybe we should default to checking if we can find chrome on the PATH first and if so use that?

**Comment by michaelneale** [comment]
this is still happening on the latest version v1.1.9 on a fresh cluster.

**Comment by michaelneale** [comment]
hold... I may be testing the wrong thing...

**Comment by michaelneale** [comment]
nope - my mistake. I was cleverly running a local build on my $PATH that I had not updated, despite updating from brew...

**Comment by liuxiaopiao** [comment]
so do we need to have chrome and configure it in $PATH? If we use the jx command in one docker container, do we need to enable vnc for the container?
