### ISSUE TITLE
jx install/jx create cluster minikube/minishift fails on fault creation even when 

### ISSUE THREAD

**Issue by lachaib** [jenkins-x/jx#4118]
### Summary 
When trying to install jenkins on my minishift or minikube cluster, either via install or create cluster, it fails at vault creation, as not supported on these providers.

### Steps to reproduce the behavior

jx install --git-provider-kind bitbucketserver --git-provider-url https://**** --git-username lchaib --ng=true --remote-environments=true --environment-git-owner=lchaib --long-term-storage=false **--vault=false**

### Expected behavior

Somehow a successful jx installation

### Actual behavior

Setting the dev namespace to: jx
Using helmBinary helm with feature flag: none
? Cloud Provider minishift
Storing the kubernetes provider minishift in the TeamSettings
Enabling helm template mode in the TeamSettings
Git configured for user: lchaib and email *****@****.com
Using helm2
Skipping tiller
Using helmBinary helm with feature flag: template-mode
Initialising Helm 'init --client-only'
helm installed and configured
Not installing ingress as using OpenShift which uses Route and its own mechanism of ingress
You can now configure a wildcard DNS pointing to the new Load Balancer address 192.168.99.110

If you do not have a custom domain setup yet, Ingress rules will be set for magic DNS nip.io.

Once you have a custom domain ready, you can update with the command jx upgrade ingress --cluster

If you don't have a wildcard DNS setup then setup a DNS (A) record and point it at: 192.168.99.110 then use the DNS domain in the next input...
? Domain 192.168.99.110.nip.io
Enabling anyuid for the Jenkins service account in namespace jx
scc "anyuid" added to: ["system:serviceaccount:jx:jenkins"]
scc "hostaccess" added to: ["system:serviceaccount:jx:jenkins"]
scc "privileged" added to: ["system:serviceaccount:jx:jenkins"]
scc "anyuid" added to: ["system:serviceaccount:jx:default"]
**error: creating the system vault: system vault is not supported for minishift provider**

### Jx version

The output of `jx version` is:

```
WARNING: Failed to find helm installs: running helm list --all --namespace : failed to run 'helm list --all --namespace ' command in directory '', output: 'Error: could not find tiller'
WARNING: Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.14.0+g05811b8
Error: could not find tiller'
NAME               VERSION
jx                 2.0.186
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.10.11
git                git version 2.20.1
Operating System   Mac OS X 10.13.6 build 17G7024
```

### Jenkins type

Not yet to this point

### Kubernetes cluster

Minikube or minishift

### Operating system / Environment

MacOS

**Comment by lachaib** [comment]
Added --no-gitops-vault and it went further, though seems counter intuitive, maybe the condition should be reworked in vault.go

**Comment by warrenbailey** [comment]
Agreed, it sounds like the condition to disable vault needs looking at.

**Comment by lachaib** [comment]
`if options.Flags.GitOpsMode && !options.Flags.NoGitOpsVault || options.Flags.Vault {`

I don't know enough Go to know how this expression is resolved, but most languages I master more would complain to have parentheses to waive ambiguity

**Comment by warrenbailey** [comment]
Actually I think the problem here is the use of --ng=true and --vault=false. The ng flag enables all next generation features including vault and overrides the value of the vault flag.

**Comment by warrenbailey** [comment]
Based on operator precedence that if statement will evaluate the && first and then the ||

https://golang.org/ref/spec#Operator_precedence

**Comment by warrenbailey** [comment]
@macox I think we could tackle this under https://github.com/jenkins-x/jx/issues/3915 

Might be worth adding some validation or a warning if you try to enable --ng but disable --vault

**Comment by warrenbailey** [comment]
@lachaib can you try removing the --ng flag and adding --tekon instead?

**Comment by lachaib** [comment]
Well, this goes further even though I can't get it to work in minikube/minishift, but that'll be another issue to be opened maybe.
