### ISSUE TITLE
Only release the jx binary once versions has fully passed

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4120]
Right now we release the jx binary on every PR. We should make these "pre-releases" and do the final release once versions has passed. This will need to update github, chocolatey, the website, brew dockerhub and dev-env

**Comment by garethjevans** [comment]
This should help fix #4115

**Comment by cagiti** [comment]
Approach:
- [ ] #4364 
- [ ] #4365 
- [ ] #4366

**Comment by cagiti** [comment]
- [ ] Investigate upgrade cli so that users aren't able to install pre-release versions
- [ ] Merge in PR associated with #4365 

Assumptions, I can read the jx version within jenkins-x-versions repo from dependency-matrix file (matrix.md)

**Comment by deanesmith** [comment]
After discussing with @pmuir, determined the urgency can be reduced in favor of other issues.

**Comment by cagiti** [comment]
Completed 🎉
