### ISSUE TITLE
Unofficial image used for GitMergeImage in steps

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#4131]
See https://github.com/jenkins-x/jx/blob/master/pkg/tekton/syntax/pipeline.go#L29 - I don't know why we're using this and not a normal released image, but it should be fixed.

cc @rawlingsj

**Comment by rawlingsj** [comment]
Agreed, it was originally mine because we needed it to release the change itself.  Chicken / Egg style.  PR above should sort it.

**Comment by abayer** [comment]
Nice! I'm just going through a list of things that confused me or were unclear that I've accumulated and opening tickets for 'em. =)
