### ISSUE TITLE
Document how a new jx binary release gets into an actual fresh install

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#4134]
This is a constant source of frustration for me: it's extremely non-obvious to a novice when a merged change to `jx` actually will end up in a fresh install of a cluster. Tracing where that merged change gets picked up downstream, where those downstream changes get picked up, etc, is basically a manual process that requires knowing how all the pieces fit together.

We should really document this (or if it's already documented, make it easier to find!): what gets triggered by a new `jx` binary release, how a new release of, say, builders corresponds to which `jx` binary release, etc.

**Comment by garethjevans** [comment]
@abayer - I've got some illustrations of the dependencies involved in this - have you got a suggestion as to where I should put them?

**Comment by abayer** [comment]
That's a good question...I'd guess somewhere in https://jenkins-x.io/contribute/development/, though that feels like it probably should be broken up into multiple pages. @pmuir, @rawlingsj - does it seem reasonable to add things like code review policy, test/coverage expectations, and maybe a quick guide to what's where in both `jx` and the various other repositories there?
