### ISSUE TITLE
jx import fails with 500 server error

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#414]
> Using:
> NAME        VERSION
> jx          1.1.5
> Jenkins X   0.0.348
> Kubernetes  v1.9.3-gke.0
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

Install jx on developer machine and use gcloud to connect to kubernetes cluster.
Change to the directory of an existing git project.

```
➜ jx import
existing charts folder found so skipping 'draft create' step
Everything up-to-date
error: error creating jenkins credential jenkins-x-chartmuseum 500 Server Error
```

**Comment by rawlingsj** [comment]
It looks like we don't try and ask for the jenkins auth details when they're missing and importing a project.  I'll take a look.

**Comment by rawlingsj** [comment]
I just tested deleting my `~/.jx/jenkinsAuth.yaml` file and running `jx import` I was prompted for the API token correctly.

I wonder if there was another entry in `~/.jx/jenkinsAuth.yaml` for that URL and an old API token?

**Comment by tdcox** [comment]
Yes, it it related to having existing credentials, but running against a fresh cluster. I see it with gke and minikube regularly. At the point this fails, it really requires killing the cluster and starting again because `jx install` can’t resume and the steps to revert the cluster back to a clean state manually require specialist knowledge of the install workflow.

**Comment by carlossg** [comment]
I had the same issue and yes, I had existing credentials for the same url in `~/.jx/jenkinsAuth.yaml`
After deleting them and running `jx uninstall` then `jx install` succeeded

**Comment by rawlingsj** [comment]
The uninstall command was fixed by this PR https://github.com/jenkins-x/jx/pull/979
