### ISSUE TITLE
golang-http quickstart is out of date

### ISSUE THREAD

**Issue by derrickburns** [jenkins-x/jx#4160]
### Summary 
```
$ jx get activity -f jenkinsx-test-project -w
STEP                                                 STARTED AGO DURATION STATUS
tidepool-org/jenkinsx-test-project/master #1               1m19s     1m9s Failed
  from build pack                                          1m19s     1m9s Failed
    Credential Initializer 25bkc                           1m19s       0s Succeeded
    Working Dir Initializer F52w7                          1m16s       0s Succeeded
    Place Tools                                            1m14s       0s Succeeded
    Build Container Build                                    19s       8s Failed
    Build Make Build                                         22s       9s Succeeded
    Build Post Build                                         18s       7s Succeeded
    Git Merge                                                22s       0s Succeeded
    Git Source Tidepool Org Jenkinsx Test Proj Kv7t5       1m11s       0s Succeeded https://github.com/tidepool-org/jenkinsx-test-project
    Promote Changelog                                        18s       7s Succeeded
    Promote Helm Release                                     18s       8s Succeeded
    Promote Jx Promote                                       17s       7s Succeeded
    Setup Jx Git Credentials                                 22s       0s Succeeded
```

```
$ make skaffold-run
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags '' -o bin/jenkinsx-test-project main.go
skaffold run -p dev
WARN[0000] config version (skaffold/v1beta2) out of date: upgrading to latest (skaffold/v1beta11)
Generating tags...
 - tidepool-org/jenkinsx-test-project -> WARN[0000] {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are deprecated, image digest will now automatically be appended to image tags
<no value>/tidepool-org/jenkinsx-test-project:_DEPRECATED_DIGEST_HEX_
Tags generated in 412.771µs
Starting build...
Building [tidepool-org/jenkinsx-test-project]...
FATA[0000] build failed: building [tidepool-org/jenkinsx-test-project]: build artifact: docker build: Error response from daemon: invalid reference format
make: *** [skaffold-run] Error 1
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.209
jenkins x platform 2.0.330
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.1
helm client        Client: v2.14.0+g05811b8
git                git version 2.20.1
Operating System   Mac OS X 10.14.5 build 18F13
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by warrenbailey** [comment]
I've just tried this and it works for me using the latest jx on an next generation cluster.

warrenbailey/jenkinsx-test-project/master #3               3m22s    3m19s Succeeded Version: 0.0.1
  from build pack                                          3m22s    3m19s Succeeded
    Credential Initializer Zdlbb                           3m22s       0s Succeeded
    Working Dir Initializer 9r96b                          3m20s       0s Succeeded
    Place Tools                                            3m18s       0s Succeeded
    Build Container Build                                  1m56s      19s Succeeded
    Build Make Build                                       1m59s      15s Succeeded
    Build Post Build                                       1m56s      20s Succeeded
    Git Merge                                              1m59s       0s Succeeded
    Git Source Warrenbailey Jenkinsx Test Proj M6c2r       3m17s       1s Succeeded https://github.com/warrenbailey/jenkinsx-test-project
    Promote Changelog                                      1m56s      27s Succeeded
    Promote Helm Release                                   1m56s      32s Succeeded
    Promote Jx Promote                                     1m56s    1m53s Succeeded
    Setup Jx Git Credentials                               1m59s       1s Succeeded
  Promote: staging                                          1m9s     1m6s Succeeded
    PullRequest                                             1m9s     1m6s Succeeded  PullRequest: https://github.com/cb-kubecd/environment-warren-1-staging/pull/1 Merge SHA: acbdcbf2965abf30c2303a42243e76d5a81a81ed
    Update                                                    3s       0s Succeeded

➜  jenkinsx jx version
NAME               VERSION
jx                 2.0.210
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F203

**Comment by warrenbailey** [comment]
It actually looks like you have a problem with the docker build.

Could you give me more information on your setup? Which type of Jenkins are you using? and the output of 'jx version' ?

**Comment by derrickburns** [comment]
Done. See above.

**Comment by warrenbailey** [comment]
/remove-priority/awaiting-more-evidence

**Comment by cyrilzh** [comment]
I got the same issue.

`time="2019-07-15T14:11:43Z" level=warning msg="config version (skaffold/v1beta2) out of date: upgrading to latest (skaffold/v1beta11)"
Generating tags...
 - cyrilzhou@hotmail.com/jxdemo08 -> czak8s01.azurecr.io/cyrilzhou@hotmail.com/jxdemo08:0.0.1
Tags generated in 107.701µs
Starting build...
Building [cyrilzhou@hotmail.com/jxdemo08]...
Complete in 11.292853mso Docker daemon  525.8kB
time="2019-07-15T14:11:43Z" level=fatal msg="build failed: building [cyrilzhou@hotmail.com/jxdemo08]: build artifact: docker build: Error response from daemon: invalid reference format"`

My environment: 
NAME               VERSION
jx                 2.0.257
jenkins x platform 2.0.822
Kubernetes cluster v1.13.5
kubectl            v1.10.3
helm client        Client: v2.14.1+g5270352
git                git version 2.14.2.windows.3
Operating System   Windows Server 2016 Datacenter 1607 build 14393
