### ISSUE TITLE
Wrong annotation from flag --ingress-class

### ISSUE THREAD

**Issue by szprutamich** [jenkins-x/jx#4173]
### Expected behavior
Add annotation to generated ingresses:
kubernetes.io/ingress.class: PROVIDED_CLASS

### Actual behavior
Added annotation to ingresses:
nginx.ingress.kubernetes.io/ingress.class: PROVIDED_CLASS

### Jx version
The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.165
jenkins x platform 2.0.330
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.2
helm client        Client: v2.12.3+geecf22f
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS
WARNING: 
A new jx version is available: 2.0.217
```

### Kubernetes cluster

EKS

**Comment by angelofdeauth** [comment]
+1
My cluster is kops deployed (AWS based).
I noticed the ingress class arg for the controller is `--ingress-class=nginx` (not what I specified) as well after install

**Comment by david-ecc** [comment]
same problem here:
`jx install --provider=kubernetes --on-premise ... --ingress-class='traefik'` creates these annotations on ingress: 

```
"kubernetes.io/ingress.class": "nginx",
"nginx.ingress.kubernetes.io/ingress.class": "traefik"
```
