### ISSUE TITLE
vault substitution fails in env

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#4183]
### Summary 

Vault substitution does not work in staging/production env. It does work in dev env.

### Steps to reproduce the behavior

1. jx install -ng
2. create a secret in the vault
3. use the secret in dev values.yaml, and staging values.yaml

### Expected behavior

Both values.yaml should get the actual value from vault

### Actual behavior

Only dev env gets the value, staging value comes out to be ""

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.217
Kubernetes cluster v1.13.6-gke.0
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE manually

### Operating system / Environment

MacOSX

**Comment by warrenbailey** [comment]
I've noticed this too, it's something that would be good to add it

/kind bug
/priority important-soon

**Comment by sharepointoscar** [comment]
Any idea when this might get  fixed?

**Comment by pmuir** [comment]
This was fixed
