### ISSUE TITLE
Base image for PHP buildpack is missing

### ISSUE THREAD

**Issue by pzheng64** [jenkins-x/jx#4189]
### Summary 
PHP/composer base image is not available in the path "https://github.com/jenkins-x/jx/Dockerfile.builder-php".
When github event is triggered, php or composer command is not found.

### Steps to reproduce the behavior
- Import PHP repo
- Add custom steps to `jenkins-x.yml` for `composer install`.
- Make changes to your repo (Push, Create PR or Merge to master)

### Expected behavior
PHP buildpack should use a PHP/Composer image as a base image.

### Actual behavior
PHP buildpack is using `jx-base` as the base image.
https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/php/pipeline.yaml#L6
So, when a Webhook is triggered for Push, PR or Merge, it fails at the step for `composer install`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.228
jenkins x platform 2.0.330
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.2
git                git version 2.1.4
Operating System   Debian 8.0 based distribution
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

It is an AWS cluster created by the team, I'm just using through devspaces.

### Operating system / Environment
CentOS 7

Dev

**Comment by marlovil** [comment]
Hi Team. Do you have an estimation when the base image for PHP will be available?
Thanks!
