### ISSUE TITLE
msbuild plugin

### ISSUE THREAD

**Issue by snahmad** [jenkins-x/jx#4194]
Try to build C# unit test dll.

Try msbuild plugin
1- C:\Nuget\nuget.exe restore xunit_githib_test.sln
2-  try running msbuild  my solution file. 

roject "C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.sln" (1) is building "C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.csproj.metaproj" (2) on node 1 (default targets).
C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.csproj.metaproj : warning MSB4078: The project file "xunit_githib_test.csproj" is not supported by MSBuild and cannot be built.
Done Building Project "C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.csproj.metaproj" (default targets).
Done Building Project "C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.sln" (default targets).

Build succeeded.

"C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.sln" (default target) (1) ->
"C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.csproj.metaproj" (default target) (2) ->
(Build target) -> 
  C:\Jenkins\workspace\test_C_sharp_tests\xunit_githib_test.csproj.metaproj : warning MSB4078: The project file "xunit_githib_test.csproj" is not supported by MSBuild and cannot be built.

### Jx version
latest jenkins version.
```
### Jenkins type


### Operating system / Environment
on windows
<!--
In which environment are you running the jx CLI?
-->

**Comment by warrenbailey** [comment]
@snahmad is this a defect for Jenkins X or Jenkins?

**Comment by warrenbailey** [comment]
Please could add some more detail i.e. the output of `jx version` and the kubernetes cluster you're running on.

**Comment by warrenbailey** [comment]
Still awaiting information so I'm closing this issue. @snahmad please reopen with more information if you're still having issues.

/close

**Comment by snahmad** [comment]
ok, close it for now.
