### ISSUE TITLE
Create cluster gke broken since 2.0.232 

### ISSUE THREAD

**Issue by devalnor** [jenkins-x/jx#4195]
### Summary 

I followed the GKE cluster creation guide from https://jenkins-x.io/getting-started/create-cluster/
But it stop after region selection:

> ERROR: error creating cluster A tenannt-service URL is required to use this option
> error: A tenannt-service URL is required to use this option

I think the issue is related to the commit https://github.com/jenkins-x/jx/commit/3516600a59a1cc19f3c58ab730324b2616bbb39d

### Steps to reproduce the behavior

```jx create cluster gke --skip-login --verbose```

```
> jx create cluster gke --skip-login --verbose
? Google Cloud Project: rnd-2019
Updated property [core/project].
Let's ensure we have container and compute enabled on your project
No apis need to be enable as they are already enabled: container compute
No cluster name provided so using a generated one: dropglaze
Defaulting to cluster type: Zonal
? Google Cloud Zone: europe-west1-b
ERROR: error creating cluster A tenannt-service URL is required to use this option
error: A tenannt-service URL is required to use this option
```

### Jx version

```
> jx --version
2.0.233
> brew info jx
jenkins-x/jx/jx: stable 2.0.233
A tool to install and interact with Jenkins X on your Kubernetes cluster.
https://jenkins-x.github.io/jenkins-x-website/
/usr/local/Cellar/jx/2.0.233 (5 files, 171.7MB) *
  Built from source on 2019-06-06 at 20:49:01
From: https://github.com/jenkins-x/homebrew-jx/blob/master/Formula/jx.rb
```

The output of `jx version` is:

```
NAME             VERSION
jx               2.0.233
git              git version 2.21.0
Operating System Mac OS X 10.14.5 build 18F132
```

**Comment by devalnor** [comment]
I confirm there is no issue when running release **v2.0.230**

**Comment by cdbkr** [comment]
I have the same issue with 2.0.235

**Comment by sdoxsee** [comment]
And I with 2.0.237

**Comment by warrenbailey** [comment]
This was accidentally broken in that version, I'm pretty sure this has been resolved now.

/kind bug
/prority critical
/assign cagiti
