### ISSUE TITLE
Actuator health path dependent upon Spring-Boot version

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#421]
When using `jx create spring -t <release version>` the probePath may be set incorrectly in values.yaml.

For Spring-Boot 2.0.0-RELEASE, this is /actuator/health
However, for Spring-Boot 1.5.x-RELEASE, It appears that this should be /health 

This results in Pods that deploy, but then stop working after a short period of time. This is likely to be an issue for some time as dependencies like Camel are not expected to support Spring-Boot 2.0.0 for a while yet.

**Comment by rawlingsj** [comment]
yeah that's a good point the java draft pack is hardcoded to use the  /actuator/health endpoint for liveness and readiness checks - https://github.com/jenkins-x/draft-packs/blob/master/packs/java/charts/values.yaml#L23 jx or draft could check is the pom is a springboot and alter the values.yaml based on that.

**Comment by jtnord** [comment]
looks like this is still the case.  https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/2fbf4375860db1c3e19e0e5c7e447b60d389f9d9/packs/maven/charts/values.yaml#L24
