### ISSUE TITLE
Kubernetes logs filling up with warning events

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#423]
Using:
> NAME        VERSION
> jx          1.1.7
> Jenkins X   0.0.368
> Kubernetes  v1.9.3-gke.0
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

Looking at the event log for my GKE cluster, I am seeing hundreds of the following errors:
```
googleapi: Error 400: Invalid value for field 'namedPorts[0].port': '0'
```
This seems to relate to the default Service Type being set to `ClusterIP` rather than `NodePort` as detailed here: https://github.com/kubernetes/kubernetes/issues/29709

**Comment by jtnord** [comment]
@tdcox I could not see this in our cluster so am presuming it is fixed.  please re-open if it is still an issue for you
