### ISSUE TITLE
Docs to create custom builder are ineffective

### ISSUE THREAD

**Issue by orbsfoc** [jenkins-x/jx#4238]
### Summary 
The guides for creating a custom Builder are here: 
https://jenkins-x.io/getting-started/create-custom-builder/

"Install the Builder
You can now install your builder either when you install Jenkins X or upgrade it.

Create a myvalues.yaml file in your ~/.jx/ folder"

This is very vague, does it only work on an install? Does the upgrade command force a helm upgrade to pass the new config? 

### Steps to reproduce the behavior
On an existing jenkinsx system.

Create above file in above location.

Run:
jx upgrade platform

### Expected behavior
A new kubernetes pod template should appear in the jenkins config corresponding to the new builder

### Actual behavior
(⎈ |kubernetes-admin@kubernetes:jx)]$ jx upgrade platform
Using provider 'kubernetes' from team settings
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /home/build/.jx/jenkins-x-versions
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Compressing objects: 100% (4/4), done.
Total 1695 (delta 1), reused 6 (delta 1), pack-reused 1688
using stable version 2.0.330 from charts of jenkins-x/jenkins-x-platform from /home/build/.jx/jenkins-x-versions
Already installed platform version 2.0.330. Skipping upgrade process.

No additional configuration in Jenkins.

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.263
jenkins x platform 2.0.330
Kubernetes cluster v1.14.0
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

on-premise / kubeadm

### Operating system / Environment
 Ubuntu 18.04.2 LTS

**Comment by garethjevans** [comment]
Hi, when using static jenkins, the changes need to be applied via helm - currently the only way of doing this is to create a `myvalues.yaml` file and either use the `jx install` or `jx upgrade platform` to apply this.

**Comment by orbsfoc** [comment]
Does there actually need to be an upgraded Jenkins chart to apply or will the jx upgrade platform command upgrade config alone?

The use case that i'm planning to add custom builders 1 at a time, as i update various projects, doesn't seem especially uncommon. If re installing the system or waiting for component changes was the only way to add through the jx cli, maybe add a note that adding them manually to directly to Jenkins is a temporary work around if config only updates cant be applied

**Comment by garethjevans** [comment]
`jx upgrade platform` has an `--always-upgrade` flag you can use to force the update.

**Comment by orbsfoc** [comment]
thanks that worked, when combined with a restart of jenkins
