### ISSUE TITLE
Machine Learning use-case requires per-step options in Pipeline

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4244]
In order to train Machine Learning models with GPU cards as part of the build process, it is necessary to be able to set containerOptions on individual build steps.

For example, a cluster will have a limited number of GPU instances and will require at least one to be allocated to a container in order to run a CUDA-based training script. If the GPU is allocated at the builder config level, then Kubernetes sees the build TaskRun as a request for multiple concurrent GPU instances (one for each container step) and if this exceeds the available GPU count, the Pod becomes unschedulable.

Similarly, it will be necessary to set CPU, memory and to mount volumes against the individual training step within the build, so as to optimise resource demand.

@abayer

**Comment by tdcox** [comment]
I have attempted to work around by using a multi-stage pipeline, as discussed on Slack, using this pipeline:

https://github.com/tdcox/jenkins-x-kubernetes/blob/ml-6/packs/ml-python-gpu-training/pipeline.yaml

**Comment by tdcox** [comment]
The build log is here:

https://gist.github.com/tdcox/3647b03a8ee6a2677a09d4b699e7e5c7

**Comment by tdcox** [comment]
The pipeline is here:

https://gist.github.com/tdcox/02d3a876a0b84f991371ddbb92c00958

**Comment by tdcox** [comment]
The training pod description is here:

https://gist.github.com/tdcox/1e67145925a30d69b4d27c59730455d4

**Comment by pmuir** [comment]
Is this still needed @tdcox

**Comment by tdcox** [comment]
We have a usable solution at the moment by putting the training step as a very long single-step command in its own stage but the problem would arise again in the future if we were to require multi-step training builds.
