### ISSUE TITLE
GoogleCloud account seems closed project of charts.

### ISSUE THREAD

**Issue by blademainer** [jenkins-x/jx#4252]
### Summary 
https://storage.googleapis.com/charts/jx-app-jenkins-0.0.15.tgz returns 403 status. Request this url returns:
```xml
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 785005500244 is disabled in state absent
</Details>
</Error>
```
GoogleCloud account seems closed project of charts. 

```bash
jx add app jx-app-jenkins
error: failed to run 'helm fetch -d /var/folders/m2/47ngr7jd4mdcrzzdc_g084n40000gn/T/jx-helm-fetch-jx-app-jenkins-474213448 --untar jx-app-jenkins --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Failed to fetch https://storage.googleapis.com/charts/jx-app-jenkins-0.0.15.tgz : 403 Forbidden'
```

### Steps to reproduce the behavior
```bash
jx add app jx-app-jenkins
```

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by madwyn** [comment]
This still persist, is there any solution or workaround?

**Comment by AdrianPadilla** [comment]
it seems that the url is wrong, https://storage.googleapis.com/charts/jx-app-jenkins-0.0.15.tgz says that billing account has being disabled, but this other url seems to be working fine https://storage.googleapis.com/chartmuseum.jenkins-x.io/charts/jx-app-jenkins-0.0.15.tgz
