### ISSUE TITLE
Teardown and rebuild the prod cluster on a regular cadence

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4254]
### Summary 
Enables us to validate that installs and upgrades fully support configuration not running state. Also validates disaster recovery.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by jstrachan** [comment]
[velero](https://velero.io) looks super handy in this effort.

we could maybe investigate something like:

* toggle lighthouse into `record` mode where webhooks are just turned into CRDs in a `replay` namespace
* we wait for all the tekton pipelines to complete in a cluster - killing some after some timeout
* perform a velero backup of all the CRDS
* `jx boot` the new cluster - which should then restore any missing resources (e.g. any missing `PipelineActivity` resources from the backup)

**Comment by babadofar** [comment]
This would help to improve MTTR, as in the Accelerate book https://jenkins-x.io/docs/concepts/
