### ISSUE TITLE
Move CLI logic in to libraries

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#4263]
A good deal of logic is implemented directly in many CLI commands.  Ideally, this logic can be abstracted out of the actual CLI commands in to libraries.  The purpose of this Issue is to create-through-example a repeatable pattern for moving logic out of commands and in to libraries where CLI-specific concerns are not relevant.

**Comment by hferentschik** [comment]
I think this describes the requires badly. Closing.

/close
