### ISSUE TITLE
Delete Jenkins X extensions

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4268]
### Summary 

We can delete all the code for this now, and the repos.

@davidcurrie  are you using this at all any more>

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by davidcurrie** [comment]
No - delete away!
