### ISSUE TITLE
feature: jx open should take --env

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#427]
If you try to run `jx open demo` from the defautl environment, it errors out with a cryptic messages about namespaces. you have to shift to the staging environment (say) - to make it work. 

Should it possible take a --env argument or be a little smarter?

**Comment by jstrachan** [comment]
you can already use `jx open --env staging`

another option is to try `jx get apps -u` though I kinda like the idea that the `-u` should not be required https://github.com/jenkins-x/jx/issues/424

I wonder what the default behaviour should be if you try `jx open demo` in the dev environment? Should it try look in the staging environment?

**Comment by michaelneale** [comment]
good Q about staging - I think a hint is fine. 

jx get apps showing url would also be nice to have. 

jx open --env staging demo
error: Could not find URL for service demo in namespace jx

I still see that - but if I switch environment it does work... so the --env seems to be ignored right now?

**Comment by jstrachan** [comment]
I think this is all fixed ow
