### ISSUE TITLE
Hook and Tide pods in CrashLoopBack - Credentials Error - EKS 1.11 - Gitlab

### ISSUE THREAD

**Issue by danifernandezs** [jenkins-x/jx#4272]
### Summary 

Trying to install/deploy JX on EKS (Amazon Kubernetes Flavour) with gitlab has Git Provider

May be the same issue as: #3392 

### Steps to reproduce the behavior

Fresh EKS Cluster (Version 1.11.8 and eks.3)

````
jx install --git-provider-url='https://gitlab.PRIVATEDOMAIN.com' --git-provider-kind='gitlab' --provider='eks' --domain='jenkinsx.PRIVATEDOMAIN.com' --no-default-environments --verbose='true' --git-username='GITLAB_USER' --git-api-token='GITLAB_USER_TOKEN' 
````

Also try 
````
jx install --git-provider-url='https://gitlab.PRIVATEDOMAIN.com' --git-provider-kind='gitlab' --provider='eks' --domain='jenkinsx.PRIVATEDOMAIN.com' --no-default-environments --verbose='true' --git-username='GITLAB_USER' --git-api-token='GITLAB_USER_TOKEN' --prow='true' --tekton
````
### Expected behavior

Correct deploy and start to configure pipelines

### Actual behavior

Hook and Tide pods in CrashLoopBack

Log of the tide pod, same in hook ones
````
{"component":"tide","error":"error getting bot name: fetching bot name from GitHub: status code 401 not one of [200], body: {\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}","level":"fatal","msg":"Error getting Git client.","time":"2019-06-11T17:15:31Z"}
````

After 2 hours the jx install command messages

````
WARNING: waiting for install to be ready, if this is the first time then it will take a while to download images
WARNING: deployment hook failed to become ready in namespace jx
````

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.274
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [x] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

AWS EKS Cluster
EKS version 1.11.8 and eks.3
AMI image: amazon-eks-node-1.11-v20190329
Instance type: m4.xlarge

### Operating system / Environment

Bastion Host: Ubuntu 18.04.2 LTS

**Comment by garethjevans** [comment]
Currently Prow does not support GitLab, this is something we are working on but are unable to give you an ETA.  To use Jenkins-X with GitLab you'll need to use the `--static-jenkins` flag.

**Comment by danifernandezs** [comment]
@garethjevans 

Adding the `--static-jenkins` i have a Classic Jenkins Runnig

The command

````
jx install --git-provider-url='https://gitlab.PRIVATE_DOMAIN.com' \
--git-provider-kind='gitlab' --provider='eks' --domain='PRIVATE_DOMAIN.com' \
--no-default-environments --verbose='true' --static-jenkins \
--ingress-namespace='INGRESS_NAMESPACE' --namespace='NAMESPACE'
--long-term-storage='false'
````

I can see any detailed state in the roadmap? (https://jenkins-x.io/contribute/roadmap/)
