### ISSUE TITLE
jx create cluster gke failing

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4276]
### Summary 
`jx create cluster gke` fails at the point where it tries to set up web hooks:
```
Waiting for helm post-upgrade hook Job expose to complete before removing it
Deleting helm hook sources from file: /var/folders/2n/n92yy0vd2pvfj1r8r3_ntp700000gn/T/helm-template-workdir-764474615/jenkins-x/helmHooks/env/charts/jenkins-x-platform/charts/expose/templates/job.yaml
job.batch "expose" deleted
Removing Kubernetes resources from older releases using selector: jenkins.io/chart-release=jenkins-x,jenkins.io/version!=0.0.1 from all pvc configmap release sa role rolebinding secret
Removing Kubernetes resources from older releases using selector: jenkins.io/chart-release=jenkins-x,jenkins.io/version!=0.0.1,jenkins.io/namespace=jx from clusterrole clusterrolebinding
Environment applied in namespace jx
WARNING: Querying webhooks on Bootstrap-Jersey/environment-d39-production: GET https://api.github.com/repos/Bootstrap-Jersey/environment-d39-production/hooks: 404 Not Found []
Creating GitHub webhook for Bootstrap-Jersey/environment-d39-production for url http://hook.jx.34.76.125.117.nip.io/hook
Registered environment production
WARNING: Querying webhooks on Bootstrap-Jersey/environment-d39-staging: GET https://api.github.com/repos/Bootstrap-Jersey/environment-d39-staging/hooks: 404 Not Found []
Creating GitHub webhook for Bootstrap-Jersey/environment-d39-staging for url http://hook.jx.34.76.125.117.nip.io/hook
Registered environment staging
WARNING: Querying webhooks on Bootstrap-Jersey/environment-d39-dev: GET https://api.github.com/repos/Bootstrap-Jersey/environment-d39-dev/hooks: 404 Not Found []
Creating GitHub webhook for Bootstrap-Jersey/environment-d39-dev for url http://hook.jx.34.76.125.117.nip.io/hook
Registered environment dev
ERROR: error creating cluster setting up GitOps post installation: [registering environment "production": POST https://api.github.com/repos/Bootstrap-Jersey/environment-d39-production/hooks: 404 Not Found [], registering environment "staging": POST https://api.github.com/repos/Bootstrap-Jersey/environment-d39-staging/hooks: 404 Not Found [], registering environment "dev": POST https://api.github.com/repos/Bootstrap-Jersey/environment-d39-dev/hooks: 404 Not Found []]
error: setting up GitOps post installation: [registering environment "production": POST https://api.github.com/repos/Bootstrap-Jersey/environment-d39-production/hooks: 404 Not Found [], registering environment "staging": POST https://api.github.com/repos/Bootstrap-Jersey/environment-d39-staging/hooks: 404 Not Found [], registering environment "dev": POST https://api.github.com/repos/Bootstrap-Jersey/environment-d39-dev/hooks: 404 Not Found []]
```

### Steps to reproduce the behavior
```
jx create cluster gke \
--cluster-name='d39' \
--default-admin-password='xxxxxxxxxx' \
--default-environment-prefix='d39' \
--environment-git-owner='Bootstrap-Jersey' \
--enable-autoupgrade=true \
--git-api-token='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
--git-username='bootsbot' \
--git-private=false \
--labels='demo=true' \
--machine-type='n1-standard-8' \
--max-num-nodes='3' \
--min-num-nodes='1' \
--ng=true \
--project-id='xxxxxxxx' \
--skip-login=true \
--zone='europe-west1-d'
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.274
Kubernetes cluster v1.12.8-gke.6
kubectl            v1.14.2
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by abayer** [comment]
Looks to me like this was a GitHub issue? Is it still happening?

**Comment by tdcox** [comment]
Just tried it again and it is still failing but now I am getting `502 Unexpected problem serving your request` which looks like a bad gateway. This is to be expected from GitHub, so the installer should really be retrying rather than just bombing out after a 20 minute installation, I guess.

**Comment by tdcox** [comment]
Actually, I think that is also a red herring. I have just run another set of tests and am back to the 404 Not Found errors. Probing `https://api.github.com/repos/Bootstrap-Jersey/environment-<my-cluster-name>-dev/hooks` gets some interesting results:

If I query a repo from my existing cluster by passing in the token for my bot account or the token I just created for the local account during my last, I get a list of hooks.

If I query a repo from the cluster I just set up by passing in the token for the local account I just set up, I get a blank list (which is correct, because no hooks have been set up).

If I query a repo from the cluster I just set up by passing in the token for the bot account which I passed in as a parameter to jx create cluster gke, I get the 404 error which is an obfuscated 'Not Authorised' response.

So, we appear to have a situation where there are two valid tokens but one of the tokens is only accepted for use on certain repos in the same organisation.

I'm not clear on the implications of this because I don't know if tokens are meant to be generic, or if jx registers them against a repo during setup in some way? The first test above implies that they are generic since I am able to access an old repo using a new token from a different cluster.

**Comment by tdcox** [comment]
Ok, here is what is happening to create the symptoms:

I am using two github accounts, 'tdcox' and 'bootsbot' and an organisation 'Bootstrap-Jersey'. 
'tdcox' is the owner of the organisation and 'bootsbot' is a member of the organisation.
The organisation uses the default 'read' privilege for all members.

The implication of this is that if 'tdcox' creates a repo in the organisation, it is admin for that repo and 'bootsbot' can only read the repo unless added explicitly as a collaborator with write privileges. 

If 'bootsbot' creates a repo in the organisation, it is admin for that repo and 'tdcox' is also admin by virtue of being owner of the org, so both have write priviliges.

The intention is that 'tdcox' is the developer account to use on the local machine and 'bootsbot' is the bot account for CI/CD operations. As such, I am invoking `jx create cluster` passing in `--git-username='bootsbot'` and `--git-api-token='<token for bootsbot account>'`

This is where it gets confusing.

When invoked in this way, the survey asks the following questions which are both open to interpretation and may also not be working as intended:
```
Set up a Git username and API token to be able to perform CI/CD
? Do you wish to use bootsbot as the local Git user for GitHub server: Y/N
Select the CI/CD pipelines Git server and user
? Do you wish to use GitHub as the pipelines Git server: Y/N
```

If I interpret this as being "which git account is to be used by the developer on the local machine?", then I answer 'no' and add the name and token for 'tdcox'. What then happens is that the installation goes on to create the environments using the 'tdcox' account but then attempts to create the webhooks using the 'bootsbot' account, which fails because if 'tdcox' is the owner of the repos then bootsbot only has default 'read' privileges.

If I run this again and interpret it to mean "which git account do you want to run local to the server?" then I accept the default of 'bootsbot' and the installer creates the environments using the 'bootsbot' account and succeeds in also creating the webhooks so the installation completes. However, if I then create a project as 'tdcox' and run a build, the 'jx promote automatically merged promotion PR' on the staging environment is executed as 'tdcox'.

If I run the install without `--git-username='bootsbot'` etc, I am asked the same "Set up a Git username and API token to be able to perform CI/CD" question but am never asked to provide a pipeline git user.

There used to be an explicit question:
```
? Do you wish to use tdcox as the GitHub username for CI/CD pipelines: No
? GitHub username for CI/CD pipelines: bootsbot
```
Am I correct in assuming that the current question asking for a "local Git user" is actually a poorly reworded version of the previous survey question and that setting up the developer account has been deferred to `jx create quickstart`?

If so, why isn't that account being used for server activities?

**Comment by deanesmith** [comment]
@tdcox since the move to boot I see this is resolved while there are still related issues.  It appears this is somewhat related to https://github.com/jenkins-x/jx/issues/5836.
