### ISSUE TITLE
error: Jenkins X platform helm chart is not installed.

### ISSUE THREAD

**Issue by charles-d-burton** [jenkins-x/jx#4280]
### Summary 
Unable to run jx upgrade platform
### Expected behavior
Command runs and completes
### Actual behavior
```using stable version 2.0.634 from charts of jenkins-x/jenkins-x-platform from /Users/charles.burton/.jx/jenkins-x-versions
error: Jenkins X platform helm chart is not installed.```

```
jenkins-x                      	1       	Thu Apr  4 12:47:43 2019	DEPLOYED	jenkins-x-platform-0.0.3734  	                   	jx```

## Jx version
```
NAME               VERSION
jx                 2.0.278
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

EKS Created with Terraform

### Operating system / Environment
OSX

**Comment by chrisduong** [comment]
You probably try to run `jx` in the Jenkins-X namespace so that it can find the Helm chart. I faced the same problem, I switched to the correct namespace, then it worked.
