### ISSUE TITLE
Move verify-generation-complete into its own pipeline

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#4282]
Currently, the `lint` status check takes a lot of time completing even after the integration and bdd tests. 

One would expect that the linting check finishes quickly. This also gives fast feedback for the submitter of the pull request in order to make simple style fixes.

The reason the `lint` pipeline takes so long is that it also runs the verify-generation-complete which is not really a linting task per se. I'd recommend creating a dedicated config for verify-generation-complete. I think this makes things a bit easier to understand.

@pmuir WDYT?

**Comment by pmuir** [comment]
For me it takes least time normally. But yes, more parallelism sounds good.
