### ISSUE TITLE
Default ingress namespace should not be kube-system

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/jx#429]
https://github.com/jenkins-x/jx/blob/8144e2bbd6949ac6be3d271c27eb8d8f3c09bbe2/pkg/jx/cmd/init.go#L110

`ingress-nginx` could be a better default? 
https://github.com/kubernetes/ingress-nginx/blob/master/deploy/namespace.yaml

or detected depending on the cloud provider

**Comment by jstrachan** [comment]
ah good point yeah. IIRC its 'kube-system' on minikube; but yeah whatever makes the most sense to on each cloud provider

**Comment by citywander** [comment]
by default, ingress-nginx is deployed in ingress-nginx now. Maybe the namespace can be specified.

**Comment by Tabrizian** [comment]
Any status update on this issue?

**Comment by carlossg** [comment]
ingress-nginx is deployed in ingress-nginx now
