### ISSUE TITLE
Switch step_create_task's interpret mode to step_syntax_effective optionally generating a shell script

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#4314]
The new interpret mode for `step_create_task` allows for executing the steps in a pipeline locally - but the better way to do this would be to have `step_syntax_effective` optionally generate a shell script containing those steps, keeping `step_create_task` simpler.

**Comment by hferentschik** [comment]
I think with `jx boot` there to stay, this becomes really important. How the interpret mode is currently implemented is not ideal. It is somehow mixed into the current code. There should be a clear separation of concerns.
