### ISSUE TITLE
Environment Controller deployment exit status 1 in multi-cluster setup.

### ISSUE THREAD

**Issue by skord** [jenkins-x/jx#4316]
### Summary 
Following instructions at https://jenkins-x.io/getting-started/multi-cluster/ leads to the installation of the environment controller not working properly. Log message from pod:

```error: failed to create git provider for git URL https://github.com/myorg/environment-mine-staging kind github: Running in batch mode and no default API token found```. 

This is also referenced here: https://github.com/jenkins-x-charts/environment-controller/issues/64 and there have been similar reports in slack. 

### Steps to reproduce the behavior

1. Create a new cluster in GKE (or any provider) for a new environment
2. Create envctl addon: 
```
jx create addon envctl -s https://github.com/myorg/env-production.git --project-id myproject --docker-registry gcr.io --cluster-rbac true --user mygituser --token mygittoken -
```
3. Deployment starts, but exits status 1 with the error message in the summary, then goes into a crash backoff loop. 

### Jx version
2.0.294

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [X] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Initial cluster created with ```--remote-environments``` flag, the cluster for the additional environment was created with GKE UI defaults.

### Operating system / Environment

OSX 10.14.3

**Comment by aomega08** [comment]
I can reproduce this trivially.

After a day of debugging, I've found a workaround. Run:

`kubectl edit deployment environment-controller`

and make sure that the `GIT_KIND` environment variable is not set or has no value. That will make the code take a branch that will lead to successful loading of git credentials. Not great, but 🤷‍♂
