### ISSUE TITLE
add a flexible GitOps install/upgrade process using a Jenkins X Pipeline

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#4326]
when installing/upgrading things like CRDs, ingress, externaldns, cert manager then actual applications like Jenkins X and additional Apps it would be handy to define the install/upgrade process in a single pipeline we can use to bootstrap an installation from an empty cluster; or perform upgrades on merges to master of the dev git repository. It would be awesome to also modify this configuration to try things out on a staging cluster on Pull Requests to test upgrades will work before the production installation of Jenkins X is upgraded.

Right now the current [GitOps installation/management mechanism of Jenkins X itself](https://jenkins-x.io/getting-started/manage-via-gitops/) e.g. via `jx create cluster gke --gitops` cheats a little bit in that it installs the Ingress controller + vault first; then uses that to populate the git repository for the dev environment.

It would be nice to start from a completely empty Kubernetes cluster with the cloud resources (buckets / service accounts + associated secrets) created (via Terraform / CloudFormation or whatever) - then run a canonical install/upgrade pipeline thats capable of setting up whatever infrastructure in the cluster (ingress, externaldns, cert manager, fluentd, datadog, istio/gloo/knative or whatever), then installing your actual environment (e.g. Jenkins X / Tekton / Prow) and then any [Apps](https://jenkins-x.io/apps/).

Then folks can do the Terraform / Cloud Formation / setup of cloud resources however they want; then run a canonical pipeline using GitOps. 

This also helps folks incrementally make changes; e.g. start with http, get things working, then change the configuration to enable HTTPS, then change to use custom domains, maybe use externaldns etc. Right now today its not easy to change the ingress / vault configurations via GitOps - really everything should be either cloud infrastructure via Terraform or a similar tool - then a Jenkins X GitOps pipeline.

**Comment by jstrachan** [comment]
initial spike at docs and an implementation https://github.com/jstrachan/environment-simple-tekton/blob/master/README.md still progressing though

**Comment by jstrachan** [comment]
docs for using `jx boot` here: https://jenkins-x.io/getting-started/boot/

**Comment by afirth** [comment]
This is super exciting to me. Frankly I think that jx has no business starting clusters and configuring ingress controllers, we have so many tools for that. I'm stoked to have this kind of solution, where I can be reasonably sure that it's going to be a repeatable process. Thanks for all the hard work, I'm giving it a go today on GKE.

**Comment by jstrachan** [comment]
@afirth thanks! 

I'm gonna close this top level issue for now and open separate issues as we start improving 'jx boot': https://jenkins-x.io/getting-started/boot/
