### ISSUE TITLE
support Prow integration

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#434]
[Prow](https://github.com/kubernetes/test-infra/tree/master/prow) is a kubernetes native handler of webhooks from events from GitHub to perform actions, builds and jobs. Its pretty awesome!

It would be nice to be able to use Jenkins X with Prow as the webhook handler triggering Jenkins X pipelines. In particular this would mean we could use Prow's [commands](https://prow.k8s.io/command-help.html) on Pull Requests - and extend them with commands to approve/enable [Preview Environments](http://jenkins-x.io/about/features/#preview-environments)

**Comment by rawlingsj** [comment]
A big +1 from me - I'm happy to have a crack at this unless you wanted to @jstrachan?

**Comment by jstrachan** [comment]
@rawlingsj sounds good to me :) I guess we need to figure out how that looks like.

Am wondering if we need a way to detect the `Jenkinsfile` and figure out what docker image / Kubernetes Job is required to run the PR / release pipeline. I was wondering if we needed a go lang `Jenkinsfile` parser that could look at things like the `agent` header in a declarative `Jenkinsfile` and figure out what the `PodTemplate` is required to implement that pipeline and then run a one shot master Jenkins pod to implement the pipeline. Or depending on how advanced we get; we could have a simple PodTemplate for pipelines which don't need any Jenkins plugins and are mostly just bash scripts? Longer term we could even look at using an Argo workflow too; particularly for promotion.

**Comment by jstrachan** [comment]
I guess a first simple solution would be use Prow to trigger the current existing Jenkins pipelines in the Jenkins master for each team - then over time we could get more advanced or use more optimal cloud footprints for organisations with multiple teams?

**Comment by rawlingsj** [comment]
> I guess a first simple solution would be use Prow to trigger the current existing Jenkins pipelines in the Jenkins master for each team

Yeah that's what I was thinking too - shouldn't be too hard

**Comment by ysaakpr** [comment]
https://github.com/jenkins-x/jx/issues/434#issuecomment-374157155
I guess it should not parse the Jenkins file, because there can be high level of customisation possible on jenkins file. In our case we use shared libraries(though not in environment repo). I believe a simple webhook executor bash(or python or any generic scripting language) would be great.

**Comment by ysaakpr** [comment]
IS there a official integration for prow from other git providers like Bitbucket or AWS CodeCommit. What would be the plan to include that. I find that, prow have been made very much inclined to use with git hub.

**Comment by rawlingsj** [comment]
Correct - once things are working with GitHub we'll look to contribute support for other git providers.

**Comment by jstrachan** [comment]
btw see the `--prow` CLI option on `jx create cluster` and `jx install`

**Comment by jglick** [comment]
BTW there is a 404 in the issue description. I think you meant [this link](https://prow.k8s.io/command-help).

**Comment by jstrachan** [comment]
am gonna mark this as closed as its generally working. 
we can raise the separate issues for different git providers either here or on Prow itself
