### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by angelofdeauth** [jenkins-x/jx#4340]
### Summary 
Jenkins X should have an easily available feature compatibility matrix per version that shows which features are compatible together. It is exceedingly frustrating to sift through documentation to find that certain providers or feature sets are incompatible together.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by cagiti** [comment]
Thanks @angelofdeauth, this is something we're currently working at improving and at present we're simplifying a lot of the command options. If there's more information you can provide on this then that would be appreciated 👍
