### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by angelofdeauth** [jenkins-x/jx#4341]
### Summary 

I know you're already asking "why god why" but I'd like to know if there are any explicit compatibility issues with jx and FreeBSD. When I build without changing anything I hit some snags on os-specific stuff.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by cagiti** [comment]
Hey @angelofdeauth, thanks for raising this... I'm guessing this is support for FreeBSD for the host machine executing `jx`? Any more information that you think would be helpful would be great... such as versions and packages you've installed. Thanks
