### ISSUE TITLE
jx install defaults choice to use long term log storage

### ISSUE THREAD

**Issue by GingerBuffalo** [jenkins-x/jx#4353]
### Summary 
Running jx install on an oke cluster, after supplying DNS value, the next choice is whether or not to "enable long term log storage". Previously this offers a n/Y choice, and I would choose no. In the latest version of jx it seems this choice now defaults to "Yes", and then immediately fails the install with error "error: configuring Long Term Storage: long term storage is not yet supported for provider oke". 

### Steps to reproduce the behavior
1. Run jx install to install jenkins x onto an oke cluster. 
2. Supply a dns value for the installation and click return to continue the install. 

### Expected behavior
The next choice should allow a response of "N", not to use long term log storage. 

### Actual behavior
jx install automatically fills this value in, generates the error mentioned above, and fails. 

### Jx version

The output of `jx version` is:

jx                 2.0.307
Kubernetes cluster v1.12.7-3+1a4d39a9763d23
kubectl            v1.13.4
helm client        Client: v2.13.0+g79d0794
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

OKE, created on the OCI portal. 

### Operating system / Environment

MacOS Mojave

**Comment by anub1s187** [comment]
Also getting the same issue

**Comment by macox** [comment]
I think this may be fixed now @GingerBuffalo, it will default to "n" unless you're using a gke cluster
