### ISSUE TITLE
unify Jenkins X jx related deployments to use builders-jx docker image

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#4356]
Currently jx uses a variety of different images for the controllers and builders it runs. We should unify on a single release of the builders to enable us to have a single release of jx in use at any one time.

/kind fox

**Comment by warrenbailey** [comment]
I think this will be a bunch of PRs

https://github.com/jenkins-x/jx/pull/4607

**Comment by warrenbailey** [comment]
Updated in these PRs

https://github.com/jenkins-x/jx/pull/4623
https://github.com/jenkins-x/jx/pull/4607

I've covered the majority of cases now, so closing this issue
