### ISSUE TITLE
metapipeline: prow needs to treat both the CRD generator and actual execution PipelineRuns as one job

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#4361]
When the metapipeline work that @hferentschik is doing (see #4320) is done, we're going to want to change prow to wait for both the metapipeline `PipelineRun` (which will create the Tekton CRDs for the actual execution) and the actual execution `PipelineRun` to complete. I'm not sure how we'll do that. At first glance, I wonder if we should be propagating the `prowJobName` label to both `PipelineRun`s and then change https://github.com/jenkins-x/test-infra/blob/pipelinerunner/prow/cmd/pipeline/controller.go#L342-L363 to handle multiple `PipelineRun`s, marking the `ProwJob` as successful if all the `PipelineRun`s are complete and successful, and marking it as failed if any of the `PipelineRun`s are complete and a failure?

@ccojocar, @wbrefvem, @hferentschik - thoughts?

**Comment by ccojocar** [comment]
>When the metapipeline work that @hferentschik is doing (see #4320) is done, we're going to want to change prow to wait for both the metapipeline PipelineRun (which will create the Tekton CRDs for the actual execution) and the actual execution PipelineRun to complete.

Is it meant that the meta-pipeline runs before the actual pipeline? How I understand from this comment there isn't any order of execution.

> I wonder if we should be propagating the prowJobName label to both PipelineRuns and then change https://github.com/jenkins-x/test-infra/blob/pipelinerunner/prow/cmd/pipeline/controller.go#L342-L363 to handle multiple PipelineRuns, marking the ProwJob as successful if all the PipelineRuns are complete and successful, and marking it as failed if any of the PipelineRuns are complete and a failure?

The main role of prow's pipeline controller is to keep the `ProwJob`'s status in sync with the `PipelineRun`'s status. In general, it would be recommended that only the prow's pipeline controller modifies the status of the `ProwJob` - having multiple controllers modifying the status can lead to complications. 

A simple approach in case the order of execution doesn't matter would be:
- All `PipelineRuns` (meta-pipeline + actual-pipeline) can be labeled with the prowjob name
- The number of started `PeipelineRuns` is returned to prow's pipeline controller by the pipelinerunner service in the REST response
- prow's controller can use a label selector to ensure that the number of PipelineRuns succeeds or otherwise propagate the status of first failed PipelineRun into the `ProwJob`'s status.

**Comment by abayer** [comment]
@ccojocar Oh, yeah, they are ordered. The "actual pipeline" will never exist/run if the metapipeline fails.

**Comment by ccojocar** [comment]
@abayer How is the order ensured? Is there any support to set a condition on a pipeline input parameter?

**Comment by abayer** [comment]
@ccojocar I'm not sure what you mean? The metapipeline is the one that Prow will kick off, so it'll obviously be the *first* one to run?

**Comment by ccojocar** [comment]
I am trying to understand from #4320 how the `pipelinerunner` starts the metapipeline and then the actual pipeline.  Maybe @hferentschik can illuminate me.

**Comment by ccojocar** [comment]
> I'm not sure what you mean? The metapipeline is the one that Prow will kick off, so it'll obviously be the first one to run?

prow's pipeline controller only does a REST request into the `pipelinerunner` service with the prowjob as a payload. The pipelinerunner kicks off the `PipelineRun`.

**Comment by hferentschik** [comment]
> how the pipelinerunner starts the metapipeline and then the actual pipeline. Maybe @hferentschik can illuminate me.

Right now the pipeline runner is creating and executing a `StepCreateTaskOption`, eventually, it will create a `StepCreateMetapipelineOption` (name to be discussed) which generates and applies the Tekton CRDs for the meta pipeline. The last step/task in the meta pipeline is then executing the current step create task. Most of these things are in place in PR #4320

**Comment by abayer** [comment]
Preliminary work up at https://github.com/abayer/test-infra/tree/metapipeline-support

**Comment by abayer** [comment]
Images up at gcr.io/abayer-jx-experiment/prow/ as well.

**Comment by hferentschik** [comment]
> Preliminary work up at https://github.com/abayer/test-infra/tree/metapipeline-support

So are these the changes which have to be integrated into the project @wbrefvem extracts from Prow?
Do we have already a repo for this new controller?

**Comment by abayer** [comment]
Yup, though it may make sense to update our existing prow fork image to use this until the new approach is ready.
