### ISSUE TITLE
metapipeline: PipelineActivity and jx get build logs need to treat generator and execution PipelineRuns as one pipeline

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#4362]
`PipelineActivity` and `jx get build logs` currently assume every Tekton build has one and only one `PipelineRun` - but that's not going to be the case once the metapipeline (see #4320 and #4361) comes along. We're going to need to modify `PipelineRunInfo` and related code to treat both the CRD generator `PipelineRun` and the resulting actual execution `PipelineRun` as a single build, with proper ordering and results. The user shouldn't need to know that these are technically two separate "builds" behind the scenes - in fact, if the generator `PipelineRun` succeeds, we may not even want to bother exposing it in `PipelineActivity`? In any case, we need to figure this out. =)

cc @hferentschik @joseblas @dgozalo

**Comment by deanesmith** [comment]
@abayer If this is not addressed in reasonable time, is the only risk here that in the event of a metapipeline execution only a portion of log data becomes available?

**Comment by abayer** [comment]
Yeah, basically. That said, I don't think this will be *too* hard.
