### ISSUE TITLE
Perform full release of jx on master build of jenkins-x-versions

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#4367]
Once we have a pre-release of jx, we then need to trigger bdd tests to validate the release and publish it as a full release if the tests are successful.
Contributes towards #4120

**Comment by rawlingsj** [comment]
I'm not sure we should run the BDD tests again on a prerelease because they must have passed for the initial PR to be merged.  I think if we're adding more BDD tests then we could add them as extra contexts and run on PRs pre merge to master?

Just my thoughts at least.

**Comment by cagiti** [comment]
> I'm not sure we should run the BDD tests again on a prerelease because they must have passed for the initial PR to be merged. I think if we're adding more BDD tests then we could add them as extra contexts and run on PRs pre merge to master?
> 
> Just my thoughts at least.

On reflection I agree, I was following on from the way in which the release stage of jx executes the slow integration tests.

**Comment by abayer** [comment]
@cagiti - this is done, right?

**Comment by cagiti** [comment]
Completed
