### ISSUE TITLE
Tekton CRD not able to deal with names longer than 63 chars

### ISSUE THREAD

**Issue by dcanadillas** [jenkins-x/jx#4370]
### Summary 
Promotion into staging is not able merge the Pull Request in the staging repo environment because pipelinerunner is failing due to a Tekton CRD error (not able to handle labels of more than 63 characters)

### Steps to reproduce the behavior
On a previous installed cluster:
```
$ jx create spring
...
$ jx get build logs
[...]
Received 201 response: {"saved":true}
getting the log for build dcanadillas/demo/master #1 stage from build pack and container build-step-promote-jx-promote
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
Promoting app demo version 0.0.1 to namespace jx-staging
Created Pull Request: https://github.com/dcanadillas-kube/environment-gketerraform-dcanadillas-jx-staging/pull/15

```

Go to `https://github.com/dcanadillas-kube/environment-gketerraform-dcanadillas-jx-staging/pull/15` and see that `promotion-build`check fails.

```
jx logs pipelinerunner
[...]
{"level":"error","msg":"failed to apply Tekton CRDs: there was a problem reconciling batch build data: there was a problem listing all activities to reconcile a batch build: unable to parse requirement: invalid label value: \"dcanadillas-kube-environment-gketerraform-dcanadillas-jx-staging\": must be no more than 63 characters failed to apply Tekton CRDs: there was a problem reconciling batch build data: there was a problem listing all activities to reconcile a batch build: unable to parse requirement: invalid label value: \"dcanadillas-kube-environment-gketerraform-dcanadillas-jx-staging\": must be no more than 63 characters","time":"2019-06-21T10:50:12Z"}
{"level":"error","msg":"failed to apply Tekton CRDs: there was a problem reconciling batch build data: there was a problem listing all activities to reconcile a batch build: unable to parse requirement: invalid label value: \"dcanadillas-kube-environment-gketerraform-dcanadillas-jx-staging\": must be no more than 63 characters","time":"2019-06-21T10:50:12Z"}
```
And `hook` logs outputs same error:
```
$ jx logs hook
[...]
{"component":"hook","context":"promotion-build","event-GUID":"bc959520-93fb-11e9-8617-f54595651f95","event-type":"status","id":7050102822,"level":"info","msg":"Status description unexpected response from pipeline runner service: 400 Bad Request,  ... rraform-dcanadillas-jx-staging\": must be no more than 63 characters.","org":"dcanadillas-kube","repo":"environment-gketerraform-dcanadillas-jx-staging","sha":"e3a5471c6f66ff1bd5c9587b31b36e64876be252","state":"error","time":"2019-06-21T08:08:22Z"}
[...]
```

### Expected behavior
The initial pipeline should finish correctly and promotion to staging should merge and deploy.

### Actual behavior
Pull request in Staging environment fails, so first pipeline execution does not finish correctly and application is not deployed.

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.252
jenkins x platform 2.0.634
Kubernetes cluster v1.11.8-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
WARNING:
A new jx version is available: 2.0.314
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE created with terraform generated by `jx create terraform ...`
Then JX installed by `jx install --provider gke ...`

### Operating system / Environment

MacOS 10.14.5

**Comment by dcanadillas** [comment]
Seems that this is a Kubernetes requirement to not deal with longer labels.

https://github.com/kubernetes/kubernetes/pull/1830

So, should labels be truncated also in Jenkins X like Tekton does when longer than 63 chars ? This can happen when a cluster long name is created with `jx create cluster ...`

**Comment by abayer** [comment]
Looks like at a minimum we should be truncating labels passed in the same way we truncate for Pipeline, Task, step, etc names.

**Comment by brec** [comment]
hi @abayer @dcanadillas I am running into the same error while importing gitlab projects - details here. https://github.com/jenkins-x/jx/issues/6827

Was there a workaround discovered for this ?
