### ISSUE TITLE
applications deployed with knative do not have expected custom domain

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#4375]
### Summary 
Applications deployed with _knative_ do not respect the _domain_ configured in _jx_. 

### Steps to reproduce the behavior
- have a jx --ng cluster setup that used a custom domain (something other than [IP].nip.io).
- create any quickstart (I'm using nodeJS)
- run `jx edit deploy`
- choose _knative_ option
- when app has deployed, run `jx get application`
- note, application URL's do NOT have the expected domain 

Optional additional steps:
- run `jx edit deploy` on the same project
- choose _default_ option
- when app has deployed, run `jx get application`
- note, application URL's DO have the expected domain 

### Expected behavior
Applications deployed with _knative_ should respect the _domain_ configured with _jx_.

### Actual behavior
Applications deployed with _knative_ always use [IP].nip.io domain.

### Jx version

The output of `jx version` is:

```
jx version

NAME               VERSION
jx                 2.0.314
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G7024
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE created with `jx create cluster gke --op`
### Operating system / Environment

OSX

**Comment by haysclark** [comment]
Workaroud: Manually set up the _knative_ custom domain. https://knative.dev/docs/serving/using-a-custom-domain/

**Comment by jstrachan** [comment]
@haysclark thanks for figuring all this out. 

in general knative owns the configuration of custom domains for knative apps; so its knative's issue rather than Jenkins X per se. I've added a FAQ: https://jenkins-x.io/faq/develop/#how-do-i-change-the-domain-of-serverless-apps
