### ISSUE TITLE
applications deployed with knative do not have expected TLS setup 

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#4376]
### Summary 
Applications deployed with _knative_ do not respect the site-wide TLS configuration.

### Steps to reproduce the behavior
- have a jx --ng cluster setup that used a custom domain with site-wide TLS enabled.
- create any quickstart (I'm using nodeJS)
- run `jx edit deploy`
- choose _knative_ option
- when app has deployed, run `jx get application`
- note, application URL's is NOT using https

Optional additional steps:
- run `jx edit deploy` on the same project
- choose _default_ option
- when app has deployed, run `jx get application`
- note, application URL's is using https

### Expected behavior
Applications deployed with _knative_ should respect the TLS settings configured with _jx_.

### Actual behavior
Applications deployed with _knative_ are always using HTTP.

### Jx version

The output of `jx version` is:

```
jx version

NAME               VERSION
jx                 2.0.314
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G7024
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE created with `jx create cluster gke --op`
### Operating system / Environment

OSX

**Comment by jstrachan** [comment]
see https://jenkins-x.io/faq/develop/#how-do-i-change-the-domain-of-serverless-apps you need to manage domains for knative via knative
