### ISSUE TITLE
Jenkins X stuck on installing jenkins-x-platform

### ISSUE THREAD

**Issue by tomvmac** [jenkins-x/jx#4380]
### Summary 
I have tried to create a new kubernetes cluster and split the create and install process into two steps, but both fail with the following error:

error: installing the Jenkins X platform: failed to wait for jenkins-x chart installation to be ready: Unauthorized

### Steps to reproduce the behavior
Method 1: 
$jx create cluster eks --cluster-name jx-eks --region us-east-2 --node-type t2.small

Method 2: 
$jx create cluster eks --cluster-name jx-eks --region us-east-2 --node-type=t2.small --skip-installation
$jx install --provider=eks --cluster-name jx-eks --no-tiller

### Expected behavior
1. EKS cluster is created
2. Jenkins Platform created

### Actual behavior
1. EKS cluster is created
2. Jenkins Platform installation hangs and eventually produces the following error:

error: installing the Jenkins X platform: failed to wait for jenkins-x chart installation to be ready: Unauthorized

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 2.0.317
jenkins x platform 2.0.672
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.0
helm client        Client: v2.14.1+g5270352
git                git version 2.21.0.windows.1
Operating System   Windows 10 Home 1809 build 17763
```
COPY OUTPUT HERE
```

### Jenkins type

- [ X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

I created the EKS cluster with the following command via jx:
$jx create cluster eks --cluster-name jx-eks --region us-east-2 --node-type t2.small

### Operating system / Environment

Windows 10 Home

**Comment by jstrachan** [comment]
see this FAQ entry to help diagnose your issue: https://jenkins-x.io/faq/issues/#jenkins-x-does-not-startup

also this step may help: https://jenkins-x.io/commands/jx_step_verify_install/

**Comment by tomvmac** [comment]
@jstrachan ,

Thanks for your suggestion.  The troubleshooting page was helpful.  Through some trial and error I found out the reason why my cluster was not working.  It appeared that I was using a node type of t2.small instead of the recommended m2.large found at the following page:

https://jenkins-x.io/getting-started/install-on-cluster/

I was finally able to get a jenkins x platform successfully installed with the following commands:

$ jx create cluster eks --cluster-name jx-eks --region us-west-2 --node-type m5.large --skip-installation
$ jx install --provider=eks --no-tiller

Although, now I have some build failures as a result of issuing:
$ jx create spring

I will continue to troubleshoot that.  Hopefully it won't be as confusing as this issue.

Thanks for your help.

Tom

**Comment by jstrachan** [comment]
@tomvmac many thanks for your feedback!
