### ISSUE TITLE
failed to apply Tekton CRDs: failed to create/update PipelineResource

### ISSUE THREAD

**Issue by chaoyangnz** [jenkins-x/jx#4385]
### Summary 

pipeline-runner errors:

> failed to apply Tekton CRDs: failed to create/update PipelineResource test-quickstart-m in namespace jx: failed to get PipelineResource test-quickstart-m with pipelineresources.tekton.dev "test-quickstart-m" not found after failing to create a new one: Internal error occurred: failed calling webhook "webhook.tekton.dev": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) failed to apply Tekton CRDs: failed to create/update PipelineResource test-quickstart-m in namespace jx: failed to get PipelineResource test-quickstart-m with pipelineresources.tekton.dev "test-quickstart-m" not found after failing to create a new one: Internal error occurred: failed calling webhook "webhook.tekton.dev": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.317
jenkins x platform 2.0.672
Kubernetes cluster v1.13.6-gke.13
kubectl            v1.13.6
helm client        Client: v2.14.1+g5270352
git                git version 2.11.0
Operating System   Debian GNU/Linux 9.9 (stretch)
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Existing cluster in GKE - 1.13.6-gke.13

**Comment by jstrachan** [comment]
I've seen this before - killing the tekton pods fixed it; not sure why tekton got in this odd state though

**Comment by jstrachan** [comment]
@abayer you seen a related tekton issue for this?

**Comment by abayer** [comment]
Can't say I have. It'd be worth seeing the `tekton-pipelines-webhook` log.

**Comment by chaoyangnz** [comment]
> Can't say I have. It'd be worth seeing the `tekton-pipelines-webhook` log.

there is nothing to say the POST request is received in tekton-pipelines-webhooks log. 

I tried to debug the issue by executing `curl` within pipeline-runner pod, and tekton-pipelines-webhooks will print some logs to indicate the request is received.

**Comment by chaoyangnz** [comment]
> I've seen this before - killing the tekton pods fixed it; not sure why tekton got in this odd state though

no luck. killed `tekton-pipelines-controller` and `tekton-pipelines-webhook`

**Comment by bbhuston** [comment]
> > I've seen this before - killing the tekton pods fixed it; not sure why tekton got in this odd state though
> 
> no luck. killed `tekton-pipelines-controller` and `tekton-pipelines-webhook`

I was hitting this issue after creating a fresh jenkins GKE cluster via the `jx` cli.  Deleting just the tekton pods did resolve the issue, however, delete all the jx pods did -- a la `kubectl -n jx delete pods --all`.  I am using the next Tekton/Prow setup, so I don't have a `tekton-pipeline-webhook` pod running on cluster.

Clearly, deleting all the pods is overkill, but I haven't identified precisely which ones need to be restarted in addition to the tekton-controller.  My jenkins x environment is listed below

```
NAME               VERSION
jx                 2.0.1094
Kubernetes cluster v1.14.7-gke.23
kubectl            v1.17.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0
Operating System   Mac OS X 10.12.6 build 16G2136
```

**Comment by srehmanproov** [comment]
I am getting same issue with fresh GKE install and just following quick-start example. is there any solution for this other than killing all pods?

**Comment by manuelwallrapp** [comment]
I have the exactely same issue. 
JenkinsX:
Version        2.1.150
Commit         c038751
Build date     2020-09-26T19:20:02Z
Go version     1.13.8
Git tree state clean

Openshift V 4.6.2
