### ISSUE TITLE
Document full list of IAM permissions needed when using EKS

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#4388]
### Summary 
Update the docs to include a full list IAM permissions required when installing on EKS.

### Acceptance Criteria
- Document review from team member/PM
- CJXD first then update OSS

**Comment by deanesmith** [comment]
Using IAM roles for service accounts with policies of our definition, start creating cluster with no permissions and iterate until all use cases work.

**Comment by dgozalo** [comment]
IAM permissions document: https://docs.google.com/document/d/18OATf9QD_kFGtvc724XcrEOVbeVrxjquK85G7qk9u4U/edit?usp=sharing

**Comment by ccojocar** [comment]
@dgozalo I have just reviewed the doc and it looks awesome! Thanks for writing everything down. Please feel free to close this issue when the doc is published.
