### ISSUE TITLE
bitnami/monocular-api is missing

### ISSUE THREAD

**Issue by sparty02** [jenkins-x/jx#4398]
### Summary 
```bash
Warning  Failed     3m16s (x4 over 4m35s)  kubelet, aks-nodepool1-27245411-1  Failed to pull image "bitnami/monocular-api:v0.7.3": rpc error: code = Unknown desc = Error response from daemon: pull access denied for bitnami/monocular-api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Oddly, https://hub.docker.com/r/bitnami/monocular-ui is stilil there, but https://hub.docker.com/r/bitnami/monocular-api is gone.  Did bitnami intentionally remove this?

### Steps to reproduce the behavior
jx create cluster

### Expected behavior
Cluster installs fine, including pulling the image for the monocular-api

### Actual behavior
Error message from summary

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.323
jenkins x platform 2.0.672
Kubernetes cluster v1.12.8
kubectl            v1.15.0
helm client        Client: v2.9.1+g20adb27
git                git version 2.21.0
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ x] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

AKS via `jenkins create cluster aks

### Operating system / Environment

Ubuntu (via WSL)

**Comment by InfiniteEcco** [comment]
### Jenkins type
 * [ x]  Next Generation (Tekton + Prow)
 * [ ]  Classic Jenkins
 * [ x] Serverless Jenkins (JenkinsFileRunner + Prow)

Naturally, having same issue with _Next Generation (Tekton + Prow)_.

**Comment by haysclark** [comment]
_Next Generation (Tekton + Prow)_ has the same issue.

### Jenkins type
 * [ x]  Next Generation (Tekton + Prow)
 * [ ]  Classic Jenkins
 * [ x] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by haysclark** [comment]
https://github.com/jenkins-x/jenkins-x-platform/pull/5647

**Comment by chaoyangnz** [comment]
+1

**Comment by jstrachan** [comment]
see https://jenkins-x.io/about/status/#25th-june-2019-missing-image-bitnami-monocular-api

new release now out with monocular removed
