### ISSUE TITLE
Platform update issues

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4401]
### Summary 
I updated client and platform last night and this morning I am seeing some issues:

Firstly, I now have a jenkins container that is attempting to start up but which is failing with a CreateContainerConfigError. This is a Next Generation install and previously did not have a jenkins pod running.

Secondly, I now have multiple instances of jenkins-x-gcactivities, jenkins-x-gcpods, jenkins-x-gcpreviews, jx-gcpreviews which are all errored out.

### Jx version

The output of `jx version` is:

```
jx                 2.0.319
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by tdcox** [comment]
The jenkins pod is failing due to `Error: Couldn't find key docker.registry in ConfigMap jx/jenkins-x-docker-registry`

**Comment by tdcox** [comment]
env/jenkins/values.yaml in the dev environment repo is still set to `enabled: false`

**Comment by tdcox** [comment]
@jstrachan Just upgraded a fresh cluster to 2.0.718 and the GitOps promotion build has failed and I'm back with another unwanted Jenkins pod. The build error is:
```
unable to decode "/tmp/helm-template-workdir-922360716/jx/output/env/charts/jenkins-x-platform/charts/jenkins/templates/pod-template-configs.yaml": Object 'Kind' is missing in '{"metadata":{"annotations":{"jenkins.io/chart":"env"},"labels":{"jenkins.io/chart-release":"jx","jenkins.io/version":"15"}}}'
unable to decode "/tmp/helm-template-workdir-922360716/jx/output/env/charts/jenkins-x-platform/templates/jenkins-x-pod-templates.yaml": Object 'Kind' is missing in '{"metadata":{"annotations":{"jenkins.io/chart":"env"},"labels":{"jenkins.io/chart-release":"jx","jenkins.io/version":"15"}}}'
```

**Comment by tdcox** [comment]
This issue seems to be getting worse. If I run `jx upgrade platform` on an instance that is less than a week old, I get an unwanted and broken Jenkins pod, plus the above error AND the build pipeline stops responding to events, rendering the cluster completely unusable.

**Comment by warrenbailey** [comment]
I'm struggling to replicate this on my cluster. I did an install with the platform version set to 2.0.178 (https://github.com/warrenbailey/jenkins-x-versions/blob/517ac280448c9900e0511fd3c9873f32ce71e981/charts/jenkins-x/jenkins-x-platform.yml#L2) and then ran a `jx upgrade platform` to bring it up to version `2.0.822`. This seemed to work for me and I didn't get the error in the jenkins pods

**Comment by warrenbailey** [comment]
I'll try it again later with a downgraded jx client as well

**Comment by tdcox** [comment]
I had a successful upgrade of a cluster created this morning to 2.0.822 this afternoon and that is the first that has worked for a while. I still have an older cluster that hasn’t been able to update so I will try that and see if it fails with 822.

**Comment by warrenbailey** [comment]
Thanks @tdcox, i'll try again now with an older client and older upgrade. Hopefully it's something that is now fixed.

**Comment by tdcox** [comment]
I have also been able to perform multiple successful upgrades today.
