### ISSUE TITLE
Add BDD tests to cover missing scenarios

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4403]
Currently the BDD tests cover a number of scenarios but we may be missing some.

Take the list of current scenarios (TODO add link) and add tests (or better map existing tests) make sure we have coverage of 100% of critical scenarios.

**Comment by pmuir** [comment]
We should add a bit of tooling to

(1) generate a html report from ginkgo (already supported by ginkgo, just needs enabling)
(2) somehow create a stable `latest` link in GCS to make it easy to link to the latest released report. GCS doesn't support symlinks, so perhaps just make a copy in the `latest` folder when a release pipe runs? Or invest in doing this properly in the UI?

**Comment by fiunchinho** [comment]
Added `jx import` scenarios https://github.com/jenkins-x/bdd-jx/pull/43
