### ISSUE TITLE
Set the --prefix= argument on the Jenkins command line when using exposecontroller $PATH.

### ISSUE THREAD

**Issue by alexanderrtaylor** [jenkins-x/jx#4409]
### Summary 
When using the exposecontroller flag and setting a `$PATH` the --prefix= argument should also be set to include that same path inside of Jenkins

### Steps to reproduce the behavior
Use the `--exposecontroller-pathmode=path --domain=myhost.testing.com`, the expected URL is as expected and the Nginx ingress recognizes the URL prefix, however Jenkins does not. This is creating a myvalue.yaml file that sets "jenkins.Master.JenkinsUriPrefix: /jx/jenkins"

### Expected behavior
The URI prefix also gets set with the same path

### Kubernetes cluster
local

**Comment by judahgreenblatt** [comment]
Issue https://github.com/jenkins-x/jx/issues/1664 looks to be related.

**Comment by alexanderrtaylor** [comment]
/remove-lifecycle stale

Removing label because this is still relevant but people have just not gotten to the fix
