### ISSUE TITLE
JenkinsX install without full root access

### ISSUE THREAD

**Issue by alexanderrtaylor** [jenkins-x/jx#4410]
### Summary 
I would like to be able to install jenkins-x without full root access. Obviously some things will require root access but I would like to be able to sudo only those options rather than the full install process

### Steps to reproduce the behavior
1. Be non-root
2. Try to install jenkins-x

### Expected behavior
I would expect it to install everything it can with my current permissions and then try to progress

### Actual behavior
It fails almost instantly

### Kubernetes cluster
local

**Comment by judahgreenblatt** [comment]
To clarify:  'jx install' doesn't require root access to run.  But it is launching Docker containers that run processes as root and that is what I want to avoid.  Specifically, my Kubernetes Volumes are on NAS servers that block root access.  So any processes that write to Volumes (such as the JENKINS_HOME directory) need to run as a specific non-root user who has write access to the NAS file system.  The same user ID can be used for all services (Jenkins, Nexus, MongoDB, ChartMuseum).  That user may not be in the /etc/passwd file inside the various Docker containers, so the user must be specified by UID, not by name.

**Comment by alexanderrtaylor** [comment]
/remove-lifecycle stale

@abayer could I ask if I can help provide more evidence here or is it just pending investigation?
