### ISSUE TITLE
Allow for the default storage class to be kubernetes.io/no-provisioner. 

### ISSUE THREAD

**Issue by alexanderrtaylor** [jenkins-x/jx#4411]
### Summary 
I would like to be able to use `no-provisioner` or local storage inside of my kubernetes cluster for Jenkins-X

### Kubernetes cluster
local created using kubeadmin

**Comment by judahgreenblatt** [comment]
Using no-provisioner for the default StorageClass seems to work.  All PODs are left PENDING until you manually create PersistentVolume (PV) objects for each generated PersistentVolumeClaim (PVC).   Timeouts cause 'jx install' to fail if you aren't fast enough, so I end up running 'jx install' once to capture the list of PVCs, then uninstall JX, create the PVs, and 'jx install' again.

**Comment by jstrachan** [comment]
you can setup the `StorageClass` to be whatever you want before you install Jenkins X right? Not sure what else we need to do...

**Comment by judahgreenblatt** [comment]
You're right, this can be closed as "not a problem".
A Storage Class that can automatically allocate local file systems would be nice, but that's a Kubernetes issue, not Jenkins-X.

**Comment by alexanderrtaylor** [comment]
Closing due to this actually working
