### ISSUE TITLE
Provide a nice way to debug failed Jenkins X Pipelines

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#4439]
it would be awesome if there was an easy way to `kubectl exec` into failed pipelines after the tekton pod has failed and been removed (the pod terminates pretty quickly on failure).

if the `PVC + PipelineRun + Task` CRDs are still around we could have a `jx pipeline debug` step which could recreate the task pod in `pause` mode reusing the PVC and `kubectl exec` into the failed step & `cd` into the working directory then folks could have a look around at the file system + try re-run or modify commands to figure out what went wrong.

Even cooler would be a `jx get build logs --debug` option to watch a pipeline and if it failed flip into debug mode; forcing the tekton controller into keeping around the build pod so we can kubectl exec - then automatically `kubectl exec`'ing into the failed container. 

From an implementation perspective it might be easier to do this option - maybe we could add some kind of label to the task pod to tell the tekton controller to not aggressively GC the pod if it fails? Then we can easily `kubectl exec` into the container of the pod if a step fails? We'd then need a way to really GC the failed pods later on; we can then have a CLI to be able to clear them down again when the debugging is over. Or we could always just keep them around for X hours or whatever unless we explicitly keep updating the 'keep until' label or something? 

Another implementation option which doesn't require a change to tekton (when we can add 'on failure' logic to a pipeline) - is add an explicit wait step on failure. Then we could `jx start pipeline --debug` to trigger a pipeline in debug mode which would add the 'on failure wait` command that would just not terminate the pod; then `jx` could do the `jx get build logs` logic then if a step fails, do the `kubectl exec -it` into the failed pod/container and `cd $workingDir`.

**Comment by hferentschik** [comment]
Depends on issue #4660
