### ISSUE TITLE
automated PR on the jenkins-x-repo never updates charts

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#4441]
for some reason whenever we run the [jx step create version pr](https://jenkins-x.io/commands/jx_step_create_version/) command inside the `jenkins-x-platform` pipeline:
```
  jx step create version pr -f "jenkins-x/*" --images
```
it creates a PR on the versions repo just fine but it never ever detects any updated charts; it only ever changes docker versions. It seems the `helm repo update` command either hasn't added or chart repo or it can't find new versions or something?

e.g. this was generated yesterday - 8 files changed (only the local pipeline yaml files) - no charts listed in the comment
https://github.com/jenkins-x/jenkins-x-versions/pull/303

this was generated on my laptop - 27 files changed - see the changed charts in the comments:
https://github.com/jenkins-x/jenkins-x-versions/pull/302

**Comment by garethjevans** [comment]
@jstrachan I wonder if its anything to do with the `jenkins-x/*`, could it be trying to expand this somewhere when running as part of the downstream build?  We saw something similar with updatebot doing this before.

**Comment by jstrachan** [comment]
@garethjevans great idea! I was hoping strings in make don't get expanded...
https://github.com/jenkins-x/jenkins-x-platform/blob/master/Makefile#L63

I just added a `helm repo list` to be totally sure the repo is in there. Looks like the step fails...

```
** step create version pr -f "jenkins-x/*" -b --images
the latest builder image version is 0.1.537
cloned fork of versions repository https://github.com/*************/jenkins-x-versions to /tmp/create-version-pr685220012
updating helm repositories to find the latest chart versions...
failed to find latest version of jenkins-x/dex: no version found for chart jenkins-x/dex
failed to find latest version of jenkins-x/exposecontroller-service: no version found for chart jenkins-x/exposecontroller-service
failed to find latest version of jenkins-x/exposecontroller: no version found for chart jenkins-x/exposecontroller
failed to find latest version of jenkins-x/jenkins-x-platform: no version found for chart jenkins-x/jenkins-x-platform
failed to find latest version of jenkins-x/**-build-templates: no version found for chart jenkins-x/**-build-templates
failed to find latest version of jenkins-x/knative-build: no version found for chart jenkins-x/knative-build
failed to find latest version of jenkins-x/prow-knative: no version found for chart jenkins-x/prow-knative
failed to find latest version of jenkins-x/prow: no version found for chart jenkins-x/prow
failed to find latest version of jenkins-x/sso-operator: no version found for chart jenkins-x/sso-operator
failed to find latest version of jenkins-x/tekton: no version found for chart jenkins-x/tekton
failed to find latest version of jenkins-x/vault-operator: no version found for chart jenkins-x/vault-operator
found existing PullRequest: https://github.com/jenkins-x/jenkins-x-versions/pull/303
force pushing to remote branch upgrade-chart-versions-f8fa6ce6-9798-11e9-b239-96a724a465c9
force pushed new pull request change to: https://github.com/jenkins-x/jenkins-x-versions/pull/303
error: failed to add message to PR https://github.com/jenkins-x/jenkins-x-versions/pull/303: POST https://api.github.com/repos/jenkins-x/jenkins-x-versions/issues/303/comments: 422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body cannot be blank
```

aha - I think we may need to add a remote repo called `jenkins-x` :)

**Comment by jstrachan** [comment]
yay!!! https://github.com/jenkins-x/jenkins-x-versions/pull/305
