### ISSUE TITLE
failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io'

### ISSUE THREAD

**Issue by Booooooger** [jenkins-x/jx#4442]
### Summary 
I am try to create jx cluster locally with minikube.  I have install minikube successfully, but i always failure by helm repo connection or some unclear reason. 

**by the way, I am in China**

### Steps to reproduce the behavior

`jx install --provider='minikube' `

### Expected behavior

jx create cluster successfully

### Jx version
The output of `jx version` is:

NAME               VERSION
jx                 2.0.324
Kubernetes cluster v1.12.6-aliyun.1
kubectl            v1.15.0
helm client        v2.14.1+g5270352
helm server        v2.11.0+g2e55dbe
git                git version 2.21.0.windows.1
Operating System   Windows 10 Pro 1903 build 18362

### COPY OUTPUT HERE
>
 FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: dial tcp 172.217.24.16:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Create with command `minikube start`

### Operating system / Environment

Operating System   Windows 10 Pro 1903 build 18362

**Comment by jstrachan** [comment]
can you run this command on your laptop:
```
https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml
```
might also be worth trying inside your minikube VM. Might be firewall / network issues?

**Comment by Booooooger** [comment]
@jstrachan  You are right!! It's real cause by network mistake. By the way ,is there any helm repo for china? Or, how can i customize one repo?

**Comment by Booooooger** [comment]
@jstrachan 
I want to use ` http://chartmuseum.jenkins-x.io/` 
what should i do ?

**Comment by cheerego** [comment]
I meet this problem , too.
In China, we cant access google service domain.
@jstrachan

**Comment by Booooooger** [comment]
@cheerego 

这个问题的原因是因为有些镜像在海外服务器上，所以国内如果不借助工具的话，就无法下载所需镜像。
解决办法有两种思路
1. 挂代理直接翻墙拉取镜像
2. 搬运镜像

我用的是第二种方式：
- 在阿里云香港分区临时租用一台ECS，然后在这台ECS上下载镜像。将下载后的镜像push到自己的镜像仓库（Docker仓库建议也直接用阿里云的容器镜像服务吧，或者用Docker hub，但是网络可能就会慢些了）
- 因为我用的minikube作为k8s ，所以在minikube 从自己的镜像仓库去拉取镜像
- 拉取完成后，记得使用 docker tag 重新为镜像打标签

### 所需镜像列表（仅供参考）

1. gcr.io/jenkinsxio/builder-go:0.1.542
2. gcr.io/jenkinsxio/nexus:0.1.7 
3. k8s.gcr.io/heapster:v1.5.2
4. k8s.gcr.io/addon-resizer:1.7 
5 gcr.io/jenkinsxio/exposecontroller:2.3.111

因为每个人的网络情况可能不一样，如果你发现某个pod 的状态是`镜像获取失败` 。查看这个pod所需镜像，然后在海外服务器上下载并传输到国内，再重新tag即可

我所知道就这么多。 期待有一天有个代理地址可以让我们跳过GFW

**Comment by cheerego** [comment]
@Booooooger 
嗯，镜像问题我是用 gcr.azk8s.cn 解决的。

但是helm的jenkins-x源是有问题的，这个不知道怎么解决，服务器翻墙很难受

**Comment by Booooooger** [comment]
@cheerego 可以简单分享下gcr.azk8s.cn解决的操作嘛。

**Comment by Booooooger** [comment]
@cheerego 可以分享下 gcr.azk8s.cn解决步骤嘛

**Comment by cheerego** [comment]
@Booooooger  
```
docker pull gcr.azk8s.cn/jenkinsxio/prow/crier:v20190510-3f2c8d788
```

然后打tag

**Comment by Booooooger** [comment]
@cheerego  tag 怎么打 😂

**Comment by cheerego** [comment]
`gcr.io/jenkinsxio/prow/crier:v20190510-3f2c8d788` 这个镜像我们是下载不下来的。
然后`gcr.azk8s.cn`这个源是gcr.io 的镜像。

```
docker pull gcr.azk8s.cn/jenkinsxio/prow/crier:v20190510-3f2c8d788
docker tag gcr.azk8s.cn/jenkinsxio/prow/crier:v20190510-3f2c8d788 gcr.io/jenkinsxio/prow/crier:v20190510-3f2c8d788
```

**Comment by YuTingLiu** [comment]
@cheerego 非常感谢你的分享，有个疑问，这个操作是在集群管理终端执行，还是需要ssh到节点上执行，在管理终端执行貌似没有用啊。
