### ISSUE TITLE
support Gitlab and Bitbucket integration

### ISSUE THREAD

**Issue by vietwow** [jenkins-x/jx#445]
Hi,

Jenkins looks very promising. I have watched Jenkins X works great with Github in the video demo. How about other (private and cloud) git repository like Gitlab and bitbucket ? Gitlab and Bitbucket is uniquitous so I think it would be great if Jenkins X support integrating with two both. Thanks.

Best Regards,
VietNC

**Comment by jstrachan** [comment]
Thanks for the issue.

‪It’s on our roadmap to support github enterprise, bitbucket & gitlab 
http://jenkins-x.io/contribute/roadmap/ 

gitea is currently close.‬

**Comment by kennydee** [comment]
@jstrachan gitea ? :)

**Comment by tuananh** [comment]
but gitea before gitlab ... why :(

**Comment by jstrachan** [comment]
@tuananh gitea small, lightweight, written in go and is very super easy to install on kubernetes.

Though we've started BitBucket and Gitlab integration if you fancy helping test it out?

**Comment by tuananh** [comment]
I would love to help testing out gitlab integration.

**Comment by jstrachan** [comment]
Here’s how to add a git server http://jenkins-x.io/developing/git/

It might be worth a try, then seeing if you can create a new repo via, say, ‘jx create spring’

**Comment by jstrachan** [comment]
BTW GitHub Enterprise is working great. BitBucket Cloud is almost there apart from an issue with credentials when updating commit/PR build status:https://github.com/jenkins-x/jx/issues/665 and gitea is in a similar state - so we're making progress.

Hopefully someone can jump in and help on gitlab support too now all the multi-git provider gremlins are worked out

**Comment by nigelcharman** [comment]
I see #665 is now closed. Does that mean that Bitbucket Cloud is now working? Have any tests been done on Bitbucket on-prem?

**Comment by jstrachan** [comment]
@nigelcharman we think BitBucket Cloud is now working though there is still work to do on BitBucket Server

**Comment by Sam123ben** [comment]
Is there any doc or updates related to the bitbucket cloud integration with jenkins-X.

```➜  vof_orch_proto git:(feature/cmt-103.0-pom-creation) ✗ jx import
✘ Sorry, your reply was invalid: "samyakr" is not a valid answer, please try again.
? Do you wish to use srout as the git user name: No
? git user name: samyakr
? GitHub user name: (samyakr) ```

**Comment by jstrachan** [comment]
@Sam123ben see https://jenkins-x.io/developing/git/

**Comment by josiahp** [comment]
Hello,

I know that Bitbucket Server integration is in-progress according the roadmap, but I have some feedback on the "create environment" feature. I'm not sure if it's ready for use with Bitbucket Server, but I am receiving an error when I try. Here are some relevant details with specific information redacted:

```
$ jx get git 
Name                    Kind            URL
servername bitbucketserver https://servername/bitbucket

$ jx create environment ci
? Label: Ci
? Namespace: jx-ci
? Domain: xx.xxx.xx.xx.nip.io
? Cluster URL: 
? Promotion Strategy: Never
? We will now create a Git repository to store your ci environment, ok? : Yes
Using git provider servername at https://servername/bitbucket/
? Do you wish to use josiahp as the git user name? Yes


About to create repository environment-jx-ci on server https://servername/bitbucket/ with user josiahp
? Which organisation do you want to use? josiahp
? Enter the new repository name:  environment-jx-ci


Creating repository josiahp/environment-jx-ci
Creating git repository josiahp/environment-jx-ci
error: Status: 404 , Body: <!DOCTYPE html><html lang="ja"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>指定のものが見つかりませんでした - Bitbucket</title><script>
```

The error in the 404 response is, predictably, "The specified page was not found."

If opening a separate ticket would be helpful then I would be happy to do that. If these kinds of reports are not helpful at this time then I would be equally happy to wait patiently for this integration.

**Comment by gabeduke** [comment]
The gitlab integration seems to be having trouble promoting to an environment from a private repo. Could this error be an indicator of an incorrect configuration or is this connector not complete yet?

_error:_
```
+ jx promote -b --all-auto --timeout 1h --version 0.0.8
Promoting app dippy-fork version 0.0.8 to namespace jx-staging
Created Pull Request: https://gitlab.com/gabeduke/environment-jx-staging/merge_requests/7

Failed to query the Pull Request last commit status for https://gitlab.com/gabeduke/environment-jx-staging/merge_requests/7 ref [ref] could not find a status for repository [rep] with ref [ref]
```

**Comment by ccojocar** [comment]
I opened this issue related to this https://github.com/jenkinsci/gitlab-plugin/issues/827. The commit status is not automatically updated by the Gitlab plugin, it must be explicitly defined in the Jenkinsfile.

**Comment by benday280412** [comment]
My working example uses the following Jenkins file:

`pipeline {
  options {
    disableConcurrentBuilds()
    gitLabConnection('Gitlab')
  }
  agent {
    label "jenkins-maven"
  }
  post {
    failure {
        updateGitlabCommitStatus name: 'state', state: 'failed'
    }
    success {
        updateGitlabCommitStatus name: 'state', state: 'success'
    }
  }
  environment {
    DEPLOY_NAMESPACE = "jx-dev1"
  }
  stages {
    stage('Validate Environment') {
      steps {
        container('maven') {
          dir('env') {
            sh 'jx step helm build'
          }
        }
      }
    }
    stage('Update Environment') {
      when {
        branch 'master'
      }
      steps {
        container('maven') {
          dir('env') {
            sh 'jx step helm apply'
          }
        }
      }
    }
  }
}`

You will also need to configure the GitLab connection in Jenkins.

**Comment by jtnord** [comment]
seems like this "catch all" ticket can be closed.  there are plenty of specifics that exist for each of the providers.
https://github.com/jenkins-x/jx/issues?utf8=%E2%9C%93&q=is%3Aissue+bitbucket
https://github.com/jenkins-x/jx/issues?utf8=%E2%9C%93&q=is%3Aissue+gitlab

**Comment by ccojocar** [comment]
@jstrachan @wbrefvem Can we close this issue?

**Comment by vietwow** [comment]
@ccojocar I see on the link https://jenkins-x.io/contribute/roadmap/ looks like that it's still in-progress

**Comment by wbrefvem** [comment]
@ccojocar Yeah, I think it might make sense. Bitbucket support is there (Cloud & Server), although I'm not so sure about Gitlab.

@vietwow I think it makes sense at this point to have an issue that tracks Gitlab support and then issues for individual bugs and feature requests that arise in Bitbucket Cloud and Bitbucket Server, since they're both basically done.

**Comment by atomicleads** [comment]
Can't make gitlab to work. Provisioning stucks on getting commit statuses from gitlab, but that code not even implemented in gitlab.go file. Webhooks work fine, merge request is created properly.

**Comment by wbrefvem** [comment]
@atomicleads Yeah, gitlab support is not quite there yet. We're always looking for contributors if you're  interested. :)

**Comment by briantopping** [comment]
Apologies that I haven't had time to contribute the Jira code I mentioned to @jstrachan that I'd try to take on.

**Comment by TonyNoble** [comment]
Quite happy to  volunteer to help with GitLab testing if this helps speed things up (my Go skills are meagre at best, so can't promise anything regarding development).  Jenkins-x is very much on the roadmap for my organisation, but github.com isn't an option for SCM.

**Comment by blademainer** [comment]
> Thanks for the issue.
> 
> ‪It’s on our roadmap to support github enterprise, bitbucket & gitlab
> http://jenkins-x.io/contribute/roadmap/
> 
> gitea is currently close.‬

@jstrachan  This page is 404 status, why?

**Comment by connorads** [comment]
@blademainer judging by the `git log` it looks like the roadmap/futures page might have been removed when the new docs site work was done in September 2019?
@dennisnewel might know more

**Comment by dennisnewel** [comment]
@blademainer the roadmap page hadn't been updated in quite a while when we updated the docs site, so it was deleted at that point. The plan was to replace it with an updated version, but we haven't gotten to that yet.

Bitbucket and GitLab is (experimentally) supported by the new Lighthouse component and we (as in CloudBees) will look to stabilize and productize Lighthouse in the coming months. The goal is to get Lighthouse to a point where we can offer official, commercial support for it; that involves a lot of testing which is why it'll take us a bit to get there :)
