### ISSUE TITLE
Move out of Prow fork for Tekton and productise the Jenkins X prow pipeline controller

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#4452]
### Summary 

We are currently using a fork of prow to trigger the Jenkins X(Tekton) pipeline which is built manually (https://github.com/ccojocar/test-infra/tree/combined-pipelines). In fact, we are able now to move out of this fork. The steps required to do so are:
- Get  the PR https://github.com/kubernetes/test-infra/pull/13199 merged into upstream prow (done)
- Move out the Jenkins X pipeline controller in a stand-alone project which can have dependencies to prow packages. The controller https://github.com/ccojocar/test-infra/tree/combined-pipelines/prow/cmd/pipeline should be moved in a stand-alone repository (done)
- Import the project into the Jenkins X production cluster and setup a pipeline which is able to build an publish the docker image
- Replace the `prowjobv1.TektonAgent` with `projobv1.JenkinsXAgent` throughout the controller: https://github.com/ccojocar/test-infra/blob/8eb599fe789a7900860272c121887bff94e7cc61/prow/cmd/pipeline/controller.go#L365 (done)
- Update the prow chart to use the upstream images for all components except the pipeline controller  https://github.com/jenkins-x-charts/prow/blob/a0965fd18c6812bf72378d09a2739d9bd5875494/prow/values.yaml#L240 which should use our custom docker image
- Update the agent name from `tekton` to `jenkins-x` in the [prow-config](https://github.com/jenkins-x/prow-config-tekton/blob/6714a75c3065ed66281fa868216e54632e1cad3e/prow/config.yaml#L226)

Nice to have the PR https://github.com/kubernetes/test-infra/pull/12583 merged into upstream prow or an alternative solution in order to be able to run multiple instances of prow per cluster. 

cc @wbrefvem @deanesmith @pmuir @hferentschik @rawlingsj @jstrachan

**Comment by wbrefvem** [comment]
Work has begun here: https://github.com/jenkins-x/prow-pipeline-controller

**Comment by hferentschik** [comment]
So we abandoned this for good now? Should this be closed in this case?
