### ISSUE TITLE
`jx update webhooks` doesn't create new web hooks if there are webhooks

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#4470]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by afirth** [comment]
Do I understand correctly the behaviour you're seeing is that if another webhook exists (e.g. for another app) then jx won't make any hooks? I'm seeing this too on 2.0.357
workaround?
