### ISSUE TITLE
"jx import --branches" failed to create org folder in Jenkins if org folder already existing

### ISSUE THREAD

**Issue by sonyali03** [jenkins-x/jx#4480]
### Summary 
jx import --branches failed to create org folder in Jenkins with error "500 Server Error" if org folder already exist
### Steps to reproduce the behavior
1. git clone -b jx https://github.com/orgname/projectname.git
2. cd projectname
3. jx import --branches='jx'
4. import successfully
5. try to git clone another branch in different folder using 'git clone -b jxtest https://github.com/orgname/projectname.git' 
6. jx import --branches='jxtest'
### Expected behavior
successfully to import and use existing orgname folder created before.
### Actual behavior
failed with error: retrying after error:Failed to create the orgname folder in Jenkins: 500 Server Error
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.215
jenkins x platform 2.0.330
Kubernetes cluster v1.13.2
kubectl            v1.14.0
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

 Classic Jenkins

**Comment by jstrachan** [comment]
you only import a project once into Jenkins. Once the project is in Jenkins if you want to modify the set of branches supported, use the Jenkins UI to edit the project configuration
