### ISSUE TITLE
`jx` uses `os.Rename()` and fails with "invalid cross-device link" when moving files between devices

### ISSUE THREAD

**Issue by jody-frankowski** [jenkins-x/jx#449]
`jx` uses `os.Rename()` and fails with "invalid cross-device link" when moving files between devices.

[Relevant code](https://github.com/jenkins-x/jx/blob/279d28405eb63436ca7e871f7814f530497f07f1/pkg/jx/cmd/create_quickstart.go#L187)
[Golang discussion](https://groups.google.com/forum/#!topic/golang-dev/5w7Jmg_iCJQ)

I have stumbled upon this when doing `jx create quickstart`:
```
$ strace -e file -f jx create quickstart
[pid  7212] renameat(AT_FDCWD, "/tmp/jx-source-825151559/golang-http-master", AT_FDCWD, "/home/me/test/jx/golang-http") = -1 EXDEV (Invalid cross-device link)
error: Failed to rename temp dir /tmp/jx-source-825151559/golang-http-master to /home/me/test/jx/golang-http: rename /tmp/jx-source-825151559/golang-http-master /home/me/test/jx/golang-http: invalid cross-device link
```

I don't think that's the only place that shouldn't use `os.Rename()`.

**Comment by rawlingsj** [comment]
Ok thanks for reporting, will fix up!

**Comment by rawlingsj** [comment]
@jody-frankowski jx 1.1.14 is available with this fix - would you mind checking it works ok for you please?

**Comment by jody-frankowski** [comment]
It seems to work fine so far. Thank you very much!

**Comment by rawlingsj** [comment]
Excellent!
