### ISSUE TITLE
How does jx promote solve multiple applications continuously published to the demo environment, repo will conflict

### ISSUE THREAD

**Issue by fangchao117** [jenkins-x/jx#4495]
When jx promote pushes multiple applications to the environment, the environment MR on gitlab will conflict. I want to know if there is any way to avoid it.

For example, I have released 4 services first.
![图片](https://user-images.githubusercontent.com/20237080/60351857-3cf36000-99f9-11e9-8ac6-f6d815ef9939.png)

When I merge a service, I will prompt a conflict when I merge the other 3 services.
![图片](https://user-images.githubusercontent.com/20237080/60351986-7e840b00-99f9-11e9-9cbb-9cc4ce77b188.png)

Is my way of using jx wrong, or is jx designed like this?

**Comment by jstrachan** [comment]
the generation of the PR should keep rebasing if there's a merge conflict

**Comment by fangchao117** [comment]
There will be conflicts in the continuous release of 4 services, is there any way to make the environment repo automatically merge?

**Comment by fangchao117** [comment]
Same scenario, same problem
[https://github.com/jenkins-x/jx/issues/428](url)
