### ISSUE TITLE
Add syntax to allow reusing a string in multiple places in jenkins-x.yml

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#4499]
We don't want to go down the road of full-blown templating in `jenkins-x.yml`, but in #4497 I found myself really wishing I could just say "here's the builder version, use it in all these places". I'm not sure what this would look like yet, but it feels reasonable to add.

**Comment by cagiti** [comment]
Once the platform is in a sane place we shouldn't need to use version numbers

**Comment by abayer** [comment]
For the specific case I mentioned, yeah, but in general, string reuse is something that will come up elsewhere.
