### ISSUE TITLE
Brew upgrade failing

### ISSUE THREAD

**Issue by Wizofgoz** [jenkins-x/jx#4503]
### Summary 
Running brew upgrade fails with a checksum mismatch error
### Steps to reproduce the behavior
run `brew upgrade jx`
### Expected behavior
jx is updated to the latest release
### Actual behavior
fails with following error:
```
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 46b8fbb6166cc1ba4a29d2f386bf91104d6d0b24771a684f0d13d472095cb353
  Actual: 31def64bc583ceee767b463d414d12af25e4aa2ad62db08c169935ec707bb11b
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.328
jenkins x platform 2.0.708
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.0
helm client        Client: v2.9.1+g20adb27
git                git version 2.16.3
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
EKS

### Operating system / Environment
MacOS

**Comment by helletheone** [comment]
i have the same problem

**Comment by cagiti** [comment]
Checksums have changed where they're stored, they're now collected into 1 file and reference by their platform.

**Comment by cagiti** [comment]
I'm manually updating the checksum until a fix goes out

**Comment by Wizofgoz** [comment]
@cagiti The issue seems to be fixed for me. I just tried the upgrade and succeeded for v2.0.372
