### ISSUE TITLE
Deploying jenkins x serverless on AWS cluster with tekton/prow quickstart fails

### ISSUE THREAD

**Issue by h-philipp** [jenkins-x/jx#4517]
### Summary 
After installing jenkins x on new created AWS cluster even the quickstart project fails to deploy. No pipeline got triggered and app not reachable in nip.io url.
Also tried before with aws domain but not working too.

Maybe related to : https://github.com/jenkins-x/jx/issues/4385

### Steps to reproduce the behavior

1. create aws cluster
2. install jenkins x serverless on cluster
3. jx create quickstart (angular, nodejs, aspnet)
4. try to deploy -> will not get pod ready in RUNNING state -> stuck in completed (logs attached)

### Expected behavior
Jenkins x start page reachable under nip.io url and start working.

### Actual behavior
Nothing deployed no app, no pipeline.

### Jx version
2.0.329

The output of `jx version` is:
jx                 2.0.329
jenkins x platform 2.0.718
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                git version 2.14.3 (Apple Git-98)
Operating System   Mac OS X 10.12.6 build 16G29

The output of `kubectl get nodes` is:
ip-192-168-5-36.eu-central-1.compute.internal     Ready    <none>   4d1h   v1.12.7
ip-192-168-72-142.eu-central-1.compute.internal   Ready    <none>   4d1h   v1.12.7

The output of `kubectl get pods` is:
crier-749f96fb4d-zz6s8                         1/1     Running     0          4d1h
deck-696f77d746-gjj4k                          1/1     Running     0          4d1h
deck-696f77d746-ljfwf                          1/1     Running     0          4d1h
hook-6d9859bb47-kcrzf                          1/1     Running     0          4d1h
hook-6d9859bb47-pvt2z                          1/1     Running     0          4d1h
horologium-6bc57b5f9-gknx5                     1/1     Running     0          4d1h
jenkins-x-chartmuseum-75d45b6d7f-zq8md         1/1     Running     0          4d1h
jenkins-x-controllerbuild-6ddb75f89d-ms7hg     1/1     Running     0          4d1h
jenkins-x-controllerrole-5b6d489775-dx4lr      1/1     Running     0          4d1h
jenkins-x-controllerteam-6c67c985cd-rtqx4      1/1     Running     0          4d1h
jenkins-x-docker-registry-6d555974c7-jrxcf     1/1     Running     0          4d1h
jenkins-x-gcactivities-1561971600-d86jc        0/1     Completed   0          145m
jenkins-x-gcactivities-1561973400-srgtx        0/1     Completed   0          115m
jenkins-x-gcpods-1561971600-w4r2f              0/1     Completed   0          145m
jenkins-x-gcpods-1561973400-tp72r              0/1     Completed   0          115m
jenkins-x-gcpreviews-1561971600-9t5l6          0/1     Completed   0          145m
jenkins-x-heapster-86b4944f56-4tc5q            2/2     Running     0          4d1h
jenkins-x-nexus-6ccd45c57c-lbpmt               1/1     Running     0          4d1h
pipeline-5f85b8df5b-v5l5c                      1/1     Running     0          4d1h
pipelinerunner-5546ffd8b-wlfrt                 1/1     Running     0          4d1h
plank-8849d9d67-l95bq                          1/1     Running     0          4d1h
sinker-85ff54bd9b-44wz9                        1/1     Running     0          4d1h
tekton-pipelines-controller-687cfbcc89-ld2mc   1/1     Running     0          4d1h
tekton-pipelines-webhook-7fd7f8cdcc-9rgcd      1/1     Running     0          4d1h
tide-5f8fb5964c-9fmhj                          1/1     Running     0          4d1h

jenkins-x-gcpods and -gcactivities where running the first time but now only in completed state

after creating quickstart and running the build pipeline also new pods appeared but got stuck in completed state logs attached. (kubectl describe po/<podid>)

### Jenkins type
- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
AWS EKS cluster - jx create cluster eks --cluster-name=<name> --skip-installation=true

### Operating system / Environment
Mac OS X 10.12.6 build 16G29
[JenkinsX_AWSDeploy.zip](https://github.com/jenkins-x/jx/files/3345271/JenkinsX_AWSDeploy.zip)

**Comment by mby-che** [comment]
hi, could you provide link with tutorial used to install jenkins x, prow, tekton please !
