### ISSUE TITLE
get build logs -b is never finding logs

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#4518]
### Summary 
`jx get build logs -b name-of-the-build` is never  finding logs.

### Steps to reproduce the behavior

1. Run a pipeline
2. Run `jx get build logs -b name-of-the-build`

### Expected behavior
You should see your pipeline logs

### Actual behavior
Pipeline is never found

### Diagnostic
[This change](https://github.com/jenkins-x/jx/pull/3258/files#diff-88a655068fa6bd90e8016b5a9642d098L243)  is responsible for this issue.
@jstrachan  @abayer `buildMap` is not initialized anymore in the case of `jx get build logs -b name-of-the-build` 
`(len(args) != 0)` so https://github.com/jenkins-x/jx/pull/3258/files#diff-88a655068fa6bd90e8016b5a9642d098R269 equals nil.

I'm happy to submit a PR but I'm not sure what was the error fixed by this PR, I guess I can not just revert this part of the code so if you can give me a bit more info I can propose a fix.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.372
Kubernetes cluster v1.12.7-gke.25
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [*] Next Generation (Tekton + Prow)

### Kubernetes cluster
GKE

### Operating system / Environment
Mac OS

**Comment by abayer** [comment]
I can't entirely remember why I moved that out myself - it seems like we probably could just move the relevant lines before the `if`.

**Comment by romainverduci** [comment]
@abayer Thanks, I will propose a PR so we can discuss it and run some tests eventually ;)

**Comment by abayer** [comment]
#4475 =)
