### ISSUE TITLE
Cannot access list of JX commands without K8s configured

### ISSUE THREAD

**Issue by SarrahV** [jenkins-x/jx#4526]
### Summary 

I want to view a list of the CLI Commands for JX. I installed JX locally and ran: 

`$ jx help > jx_commands.txt`

I get this in return:  `Unable to load managed plugins because unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`

It seems strange to me that I need to have a cluster configured just to access the list of commands.

### Steps to reproduce the behavior

Install JX locally and do not set up a Kubernetes host or server. Attempt to access a list of JX commands,

### Expected behavior

I should see the following:

<img width="976" alt="java" src="https://user-images.githubusercontent.com/8724083/60453451-35050d00-9bff-11e9-851a-1f643e0743be.png">

### Actual behavior

I receive this error message: 

`Unable to load managed plugins because unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`

### Jx version

The output of `jx version` is:

```
jx               2.0.372
git              git version 2.20.1 (Apple Git-117)
Operating System Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

None - n/a

### Operating system / Environment

Mac OS X 10.14.5 build 18F203

**Comment by deanesmith** [comment]
If you do not have a cluster configured but just enter `jx`, is that sufficient?
