### ISSUE TITLE
cannot access https://storage.googleapis.com/chartmuseum.jenkins-x.io/charts/jenkins-x-platform-2.0.744.tgz from China

### ISSUE THREAD

**Issue by Booooooger** [jenkins-x/jx#4530]
### Summary 
I am trying to create new jx cluster , unfortunately it is fail

Are there any proxy address repo for china ???

The output of `jx version` is:

>
ERROR: error creating cluster installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm fetch -d C:\Users\yombo\AppData\Local\Temp\helm-template-workdir-785713662\jenkins-x\chartFiles --untar jenkins-x/jenkins-x-platform --version 2.0.744' command in directory '', output: 'Error: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/charts/jenkins-x-platform-2.0.744.tgz: dial tcp 172.217.27.144:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [- ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
Minikube

### Operating system / Environment
jx                 2.0.324
Kubernetes cluster v1.14.3
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                git version 2.21.0.windows.1
Operating System   Windows 10 Pro 1903 build 18362

**Comment by jstrachan** [comment]
so this looks like the GCP bucket we use to store helm charts cannot be accessed from China...
