### ISSUE TITLE
jx upgrade platform fails due to invalid assumption about vault name

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4531]
### Summary 
`jx upgrade platform` creates a job called `jenkins-x-jenkinstokenjob` which fails and respawns repeatedly because it assumes that vault was deployed using http rather than tls.

The error reported is:
```
error: creating Jenkins Auth configuration: no 'jx-vault-coda-01' vault found in namespace 'jx'
could not find vault jx-vault-coda-01 in namespace jx due to: vaults.vault.banzaicloud.com "jx-vault-coda-01" is forbidden: User "system:serviceaccount:jx:jenkins-x-jenkinstokenjob" cannot get resource "vaults" in API group "vault.banzaicloud.com" in the namespace "jx"
```

This is due to the secret actually being named `tls-jx-vault-coda-01`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.372
Kubernetes cluster v1.12.7-gke.25
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G2307
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by frazergibsonntt** [comment]
Hi @tdcox, how did you resolve this?
