### ISSUE TITLE
Jenkins X uses incorrect ELB endpoint for creating R53 record

### ISSUE THREAD

**Issue by ishantanu** [jenkins-x/jx#4534]
### Summary 

`jx` tries to use the ELB endpoint which does not exist for creating a wildcard DNS entry.

### Steps to reproduce the behavior

1. Setup the `jx` installation on existing Kubernetes cluster (AWS).
2. Remove `jx` installation. This DOES NOT cleanup ELB and associated R53 endpoint.
3. Delete ELB endpoint manually.
4. Fresh setup of `jx` with command:
     ```
     ❯ jx install --provider aws \
           --git-provider-kind bitbucketserver \
           --git-provider-url https://dev.xyz.com
    ```
5. `jx` prompts for DNS name for adding wildcard entry. After this, it shows the same ELB associated with it which does not exist.

### Expected behavior

`jx` should know that the past ELB endpoint does not exist anymore and should create a new endpoint.

Or, `jx uninstall` should delete the ingress deployment. Currently, there is no way for the user to know whether the ingress deployment of the old `jx` installation still exists. 

### Actual behavior

`jx` keeps on using the same ELB endpoint. Even after reinstalling `jx` binary, it somehow picks the same ELB endpoint.

### Jx version

The output of `jx version` is:

```
❯ jx version
NAME               VERSION
jx                 2.0.372
Kubernetes cluster v1.11.2
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

Kops created cluster on AWS

### Operating system / Environment

MacOS

**Comment by ozdemirkan** [comment]
This is a blocker issue for me too.
