### ISSUE TITLE
jx start pipeline does not work with PR branches

### ISSUE THREAD

**Issue by ajp-lqx** [jenkins-x/jx#4542]
### Summary 
When using `jx start pipeline` to manually trigger a pipeline, only the `/master` branches are available for starting. If `jx start pipeline org/proj/PR-1234` is provided, the command fails.

### Steps to reproduce the behavior
Run `jx start pipeline` with an argument pointing to a PR branch of your project.

### Expected behavior
The pipeline starts.

### Actual behavior
```error: no prow config build spec found for org/proj/PR-1234```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.381-dev+799c1f2f2
Kubernetes cluster v1.13.5
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1
Operating System   Ubuntu 19.04
```

### Jenkins type
- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
AKS

### Operating system / Environment
Ubuntu 19.04

**Comment by ajp-lqx** [comment]
Will be taking a closer look at this throughout the week

**Comment by savealive** [comment]
Update jx please and try again. It may be related to https://github.com/jenkins-x/jx/pull/4345
Works fine for me on latest jx version:
```
$ jx start pipeline Org/Platform/PR-70
Started build of Org/Platform/PR-70 at https://jenkins.jx.org.com/job/Org/job/Platform/job/PR-70/3/
view the log at: https://jenkins.jx.org.com/job/org/job/Platform/job/PR-70/3/console
```

**Comment by ajp-lqx** [comment]
Temporary fix: if you `kubectl edit cm config` in your jx namespace, you can add whichever PR branches to the branches array in what postsubmit job you're working with.

**Comment by iftachsc** [comment]
for us it work but the branch is unknown... and build fails
jx start pipeline org/app/PR-33994

PipelineActivity for org-app-**unknown**-1
upserted PipelineResource meta-org-app-**unknown**-d7vj2 for the git repository https://github.com/hibobio/hibob.git
upserted Task meta-org-app-**unknown**-d7vj2-meta-pipeline-1
upserted Pipeline meta-org-app-**unknown**-d7vj2-1
created PipelineRun meta-org-app-**unknown**-d7vj2-1
created PipelineStructure meta-org-app-**unknown**-d7vj2-1

**Comment by cristi-vlad** [comment]
Is there any fix in order to be able to run pipelines on branches  ? 
What i want to do is to have PR's between branches or release on a certain branch
