### ISSUE TITLE
PR build failing

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#455]
Using:

> NAME        VERSION
> jx          1.1.9
> Jenkins X   0.0.376
> Kubernetes  v1.9.3-gke.0
> Helm Client v2.8.2+ga802316
> Helm Server v2.8.2+ga802316
> Git         git version 2.14.3 (Apple Git-98)

Actions:
Submit pull request on branch.
Build fails with `Error: exposecontroller chart not found in repo https://chartmuseum.build.cd.jenkins-x.io`

```
echo "  version: 0.0.0-SNAPSHOT-PR-2-1" >> requirements.yaml
helm dependency build
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "chartmuseum" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: exposecontroller chart not found in repo https://chartmuseum.build.cd.jenkins-x.io
make: *** [preview] Error 1
```

**Comment by rawlingsj** [comment]
related to https://github.com/jenkins-x/jx/issues/455

**Comment by rawlingsj** [comment]
related to https://github.com/jenkins-x/jx/issues/456 - closing this issue and will give updates on the other
