### ISSUE TITLE
JX TLS termination on AWS EKS ( jx upgrade ingress)

### ISSUE THREAD

**Issue by MohanKumarHG** [jenkins-x/jx#4550]
### Summary 
i configured my k8's cluster with 2-worker node and EKS master node
installed jenkins-x by using the below command
jx install --provider=eks --domain=abcd.com --default-environment-prefix=terraform-eks-demo --no-tiller

the output is :
Jenkins X installation completed successfully

        ********************************************************

             NOTE: Your admin password is: cFtB0s7=y6IKFv.G8YFY

        ********************************************************

Your Kubernetes context is now set to the namespace: jx
To switch back to your original namespace use: jx namespace default
Or to use this context/namespace in just one terminal use: jx shell
For help on switching contexts see: https://jenkins-x.io/developing/kube-context/
To import existing projects into Jenkins:       jx import
To create a new Spring Boot microservice:       jx create spring -d web -d actuator
To create a new microservice from a quickstart: jx create quickstart
[root@ip-10-0-1-136 eks]# jx get urls
NAME                  URL
jenkins               http://jenkins.jx.danaher-digital.com
jenkins-x-chartmuseum http://chartmuseum.jx.danaher-digital.com
nexus                 http://nexus.jx.danaher-digital.com

i could able to get the jenkins UI with http but not https

so i ran the below command
jx upgrade ingress --namespaces=jx --skip-certmanager=true --wait-for-certs=false
output error: Certificate issuer letsencrypt-staging does not exist. Creating...
error: creating the ingress rules: creating the cert-manager issuer jx/letsencrypt-staging: creating cert-manager issuer "letsencrypt-staging": the server could not find the requested resource (post issuers.certmanager.k8s.io)

then i installed the cert-manager manually and agiain i ran the same command
jx upgrade ingress --namespaces=jx --skip-certmanager=true --wait-for-certs=false

this time its showing different error
Certificate issuer letsencrypt-staging does not exist. Creating...
error: creating the ingress rules: creating the cert-manager issuer jx/letsencrypt-staging: creating cert-manager issuer "letsencrypt-staging": Issuer.certmanager.k8s.io "letsencrypt-staging" is invalid: []: Invalid value: map[string]interface {}{"kind":"Issuer", "apiVersion":"certmanager.k8s.io/v1alpha1", "metadata":map[string]interface {}{"generation":1, "uid":"2905321f-9d53-11e9-b867-0ab0841a1992", "name":"letsencrypt-staging", "creationTimestamp":"2019-07-03T05:26:50Z", "namespace":"jx"}, "spec":map[string]interface {}{"acme":map[string]interface {}{"server":"https://acme-staging-v02.api.letsencrypt.org/directory", "privateKeySecretRef":map[string]interface {}{"name":"letsencrypt-staging", "key":""}, "http01":map[string]interface {}{}, "email":"mohan.kumar@danaherdigital.com"}}, "status":map[string]interface {}{"conditions":interface {}(nil)}}: validation failure list:
status.conditions in body must be of type array: "null"

### Steps to reproduce the behavior
once the eks cluster is up and running then install the cert-manger manually using the below command
# Create a namespace to run cert-manager in
kubectl create namespace cert-manager

# Disable resource validation on the cert-manager namespace
kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true

# Install the CustomResourceDefinitions and cert-manager itself
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml

once the cert-manager is installed. 
try with the below command 
[root@ip-10-0-1-136 eks]# jx upgrade ingress --namespaces=jx --skip-certmanager=true --wait-for-certs=false
? Expose type Ingress
? Domain: xzy.com
? If your network is publicly available would you like to enable cluster wide TLS? Yes

If testing LetsEncrypt you should use staging as you may be rate limited using production.
? Use LetsEncrypt staging or production? staging
? Email address to register with LetsEncrypt: abc@xzy.com
? UrlTemplate (press <Enter> to keep the current value): "{{.Service}}.{{.Namespace}}.{{.Domain}}"
? Using config values abc@xzy.com letsencrypt-staging false Ingress "{{.Service}}.{{.Namespace}}.{{.Domain}}" true}, ok? Yes

Certificate issuer letsencrypt-staging does not exist. Creating...
error: creating the ingress rules: creating the cert-manager issuer jx/letsencrypt-staging: creating cert-manager issuer "letsencrypt-staging": Issuer.certmanager.k8s.io "letsencrypt-staging" is invalid: []: Invalid value: map[string]interface {}{"kind":"Issuer", "apiVersion":"certmanager.k8s.io/v1alpha1", "metadata":map[string]interface {}{"generation":1, "uid":"2905321f-9d53-11e9-b867-0ab0841a1992", "name":"letsencrypt-staging", "creationTimestamp":"2019-07-03T05:26:50Z", "namespace":"jx"}, "spec":map[string]interface {}{"acme":map[string]interface {}{"server":"https://acme-staging-v02.api.letsencrypt.org/directory", "privateKeySecretRef":map[string]interface {}{"name":"letsencrypt-staging", "key":""}, "http01":map[string]interface {}{}, "email":"abc@xzy.com"}}, "status":map[string]interface {}{"conditions":interface {}(nil)}}: validation failure list:
status.conditions in body must be of type array: "null"

### Expected behavior
it should enable the HTTPS connection for my jenkins UI

### Actual behavior
Certificate issuer letsencrypt-staging does not exist. Creating...
error: creating the ingress rules: creating the cert-manager issuer jx/letsencrypt-staging: creating cert-manager issuer "letsencrypt-staging": Issuer.certmanager.k8s.io "letsencrypt-staging" is invalid: []: Invalid value: map[string]interface {}{"kind":"Issuer", "apiVersion":"certmanager.k8s.io/v1alpha1", "metadata":map[string]interface {}{"generation":1, "uid":"2905321f-9d53-11e9-b867-0ab0841a1992", "name":"letsencrypt-staging", "creationTimestamp":"2019-07-03T05:26:50Z", "namespace":"jx"}, "spec":map[string]interface {}{"acme":map[string]interface {}{"server":"https://acme-staging-v02.api.letsencrypt.org/directory", "privateKeySecretRef":map[string]interface {}{"name":"letsencrypt-staging", "key":""}, "http01":map[string]interface {}{}, "email":"abc@xzy.com"}}, "status":map[string]interface {}{"conditions":interface {}(nil)}}: validation failure list:
status.conditions in body must be of type array: "null"

### Jx version

The output of `jx version` is:

```
[root@ip-10-0-1-136 eks]# jx version
NAME               VERSION
jx                 2.0.270
jenkins x platform 2.0.744
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.3
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.21.0
Operating System   Red Hat Enterprise Linux Server release 7.6 (Maipo)
WARNING:
A new jx version is available: 2.0.394
? Would you like to upgrade to the new jx version? No
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ .] Classic Jenkins

**Comment by CobraFlow** [comment]
This also happens on on-premise install. It looks as though the format of the issuer has changed. A workaround is to create the two issuers prior to issuing the `jx upgrade ingress` command. jx detects that the issuers exist and skips on to the next stage.
