### ISSUE TITLE
After installing gloo addon, knative is not the default deployment type.

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#4559]
### Summary 

After installing gloo addon, knative is not the default deployment type.

### Steps to reproduce the behavior

Create a tekton-based Jenkins X cluster.

```bash
jx create addon gloo

jx create quickstart \
    --language go \
    --project-name jx-knative \
    --batch-mode
```

```
...
Setting the team deploy kind to: knative
```

```bash
cat charts/jx-knative/values.yaml
```

```
...
knativeDeploy: false
...
```

### Expected behavior

The `knativeDeploy` value should be set to `true`

### Actual behavior

The `knativeDeploy` value should be set to `false`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.387
jenkins x platform 2.0.744
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by gurushub** [comment]
This is reproducible... 
[root@ov.helm]# jx create addon gloo
using external IP of gloo LoadBalancer: 52.XXX.XX.42
Setting the team deploy kind to: knative
[root@ov .helm]# jx-knative
-bash: jx-knative: command not found
[root@o .helm]# jx edit deploy
error: could not find a helm chart values.yaml in the charts folder /root/.helm/

**Comment by gurushub** [comment]
area/knative

**Comment by deanesmith** [comment]
@vfarcic Knative support will be deprecated at a random date after Feb 1 2020 from Jenkins-X in favor of Tekton pipelines.
