### ISSUE TITLE
jx upgrade platform failing

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#456]
Using:

> NAME        VERSION
> jx          1.1.14
> Jenkins X   0.0.376
> Kubernetes  v1.9.3-gke.0
> Helm Client v2.8.2+ga802316
> Helm Server v2.8.2+ga802316
> Git         git version 2.14.3 (Apple Git-98)

Actions:
```
➜ jx upgrade platform
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "releases" chart repository
...Successfully got an update from the "jenkins-x" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
Error: failed to download "jenkins-x/jenkins-x-platform"
Error: Command failed  helm upgrade jenkins-x jenkins-x/jenkins-x-platform
error: exit status 1
```

**Comment by rawlingsj** [comment]
We are currently upgrading all infrastructure and jenkins x, we hit a slight issue which is being resolved, we expect things to be sorted within the hour.

**Comment by rawlingsj** [comment]
I think the lesson here is to not change the PV sizes we have now in jenkins-x-platform, if these need changing then do it as a custom values.yaml or provide steps on data backup, PV delete and restoration.

**Comment by jtnord** [comment]
@rawlingsj there is a leassons learned here, other than comminucating this (dev docs?) is there anything else to do here?

**Comment by gurushub** [comment]
Any update to this issue? I am still facing this issue. area/jenkins
