### ISSUE TITLE
Patch git auth token usage

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#4563]
### Summary 

Currently during install we sometimes mix up the local user git token with the pipeline user git token. There is a refactor underway to fix this.

Investigate if it is possible to improve the git auth token detection in the short term while we wait for #4425 to be completed.

Notes:
Leaking token issue is repaired by boot - priority 1
BDD test implications
Environment variables to enable strict mode for prod whereas less strict for test

**Comment by msvticket** [comment]
/triage duplicate
because #3593
/close

**Comment by deanesmith** [comment]
jx boot usage addresses immediate concerns.  Closing since this is now a duplicate for long term concerns
