### ISSUE TITLE
Improve coverage of jx boot post and pre install validation

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#4568]
### Summary 

```jx boot``` supports post and pre install validation checks. See https://jenkins-x.io/getting-started/boot/#about-jx-boot for details. 

Improve the install experience by expanding the validation to include important checks.

**Comment by deanesmith** [comment]
@macox please add detail around the specific checks and parse out in to smaller issues if needed.

**Comment by pmuir** [comment]
There are quite a few validations now, let's open issues for specifics as needed
