### ISSUE TITLE
pipelinerunner doesnot support github domain other than "github.com"

### ISSUE THREAD

**Issue by rokii** [jenkins-x/jx#4588]
### Summary 
My enterprise github is like "github.xxx.xxx.com".
Current pipelinerunner only supports "github.com" which is hard-coded.
[controller_pipelinerunner](https://github.com/jenkins-x/jx/blob/master/pkg/cmd/controller/pipelinerunner.go#L282)

### Expected behavior

By introducing new cmd option `--git-provider-url=xx.xxx.com`,  github domain can be set.
And the clone operation is successful.

### Actual behavior
When the app is created by `jx create  --git-provider-url=xx.xxx.com`, 
pipelinerrunner pod will exit and be restarted due to checkout error for more than 3 times.

### Jenkins type

- [+ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by rokii** [comment]
If this is acceptable and there is no conflict task related to this, I can work out  a PR.

**Comment by hferentschik** [comment]
> If this is acceptable and there is no conflict task related to this, I can work out a PR.

Contributions are always welcome :-)
