### ISSUE TITLE
Donot kill a running pod which acts as http server

### ISSUE THREAD

**Issue by rokii** [jenkins-x/jx#4593]
My pipelinrunner pod exits due to this https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/step_create_task.go#L1026-L1036 and when it gets restarted there is no log showing why the container was killed. It seems the `k logs <pod>` only outputs the new pod's log.

A good design should be that the pod is stateless and it does not need to be killed to recover.

And what's worser is it will stop another running goroutine  handling other request which should be succeed

**Comment by hferentschik** [comment]
I agree this is very bad design/code. I think this was a bandage for the fact that in some cases the controller is not able anymore to connect to GitHub and cloning operations fail. Really one would need to find out what the underlying issue is and how to fix it or recover from it in a better way.

**Comment by hferentschik** [comment]
This might be related since the error message in these cases are similar https://github.com/jenkins-x/jx/issues/3897

**Comment by hferentschik** [comment]
It is also worth mentioning that the pipelinerunner shortly will be merged with [prow-pipeline-controller](https://github.com/jenkins-x/prow-pipeline-controller)

**Comment by hferentschik** [comment]
I am going to close this issue for multiple reasons. First, per default the meta pipeline is enabled now (#4992) which does not clone the repository to build in the pipelinerunner pod anymore.

Second, the underlying cause for the panic was resolved by increasing the memory limit of the pipelinerunner (see https://github.com/jenkins-x-charts/prow/issues/975 and https://github.com/jenkins-x/jx/issues/4862.

Third, the actual panic call is still in the code, but will be removed once the meta pipeline approach is more tested and we remove the obsolete code.
