### ISSUE TITLE
error: user x-0 

### ISSUE THREAD

**Issue by lvcz** [jenkins-x/jx#4603]
### Summary 
Hi, I'm using Jenkins X in a bitbucketcloud repo, and a local  kubernetes cluster, But, every (second) time I run any pipeline I get this error: 
```
+ jx preview --app my app --dir ../..
Creating a preview
error: users.jenkins.io "x-0" already exists
script returned exit code 1
```

### Steps to reproduce the behavior
``` 
jx start pipeline -t
....
Finished: SUCCESS
jx start pipeline -t
error: users.jenkins.io "x-0" already exists
script returned exit code 1
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.202
jenkins x platform 2.0.768
Kubernetes cluster v1.14.2
kubectl            v1.14.2
helm client        Client: v2.14.1+g5270352
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster
Local cluster:
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment
ubuntu 18

**Comment by alexvolsh** [comment]
The same for:
`jx                 2.0.466
jenkins x platform 0.0.3832
Kubernetes cluster v1.14.3
kubectl            v1.15.0
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.22.0
Operating System   Mac OS X 10.15 build 19A501i`

**Comment by lvcz** [comment]
Tried to force the user delete, but even with --yes=true the prompt waits for a confirmation
``` 
steps {
        container('jx-base') {
           sh "jx delete user x-0 --yes=true"
```

the pipeline wait for stdin and stall.

**Comment by IgorGerasimov** [comment]
@lvcz 
```
          dir('./charts/preview') {
            sh "make preview"
            sh "kubectl delete user x-0 || true" ### MAGIC row
            sh "jx preview --app $APP_NAME --dir ../.."
          }
```

**Comment by lvcz** [comment]
I missed this shell class college, lol. 
Thanks, but is still a turnaround.

**Comment by lvcz** [comment]
> @lvcz
> 
> ```
>           dir('./charts/preview') {
>             sh "make preview"
>             sh "kubectl delete user x-0 || true" ### MAGIC row
>             sh "jx preview --app $APP_NAME --dir ../.."
>           }
> ```

Tryed and does not work

**Comment by okgolove** [comment]
@IgorGerasimov 
`kubectl delete user x-0 --ignore-not-found=true`
