### ISSUE TITLE
better feedback when cluster is low on resources and pods can't start

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#461]
It seems the most issues that have been reported so far is when a cluster is low on resources and a build pod fails to start.

We should provide better visability, checks, logging and ways to investigate this problem.

I wonder if the kubernetes-plugin could check the events of a build pod as it's schedules and print them in the job console?  But that's only for build pods, we also need this for when apps get deployed to staging and prod, could also do with a `jx diagnose` cli or something?

any other ideas?

**Comment by rajdavies** [comment]
I'll add a quick jx discribe

**Comment by rawlingsj** [comment]
> I'll add a quick jx discribe

yay!

**Comment by jtnord** [comment]
given there are monitoring tools available that people would want to use to monitor their instances and we have (a somewhat broken `jx diagnose`) I think we can close this now.  WDYT @rawlingsj ?

/cc @oswaldohp @jennbriden

**Comment by ccojocar** [comment]
I am closing this issue since the user can get more feedback from a monitoring tool such as Prometheus + Grafana.
