### ISSUE TITLE
add a gradle quickstart

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#462]

**Comment by jstrachan** [comment]
ok I've got a pipeline going using the `builder-gradle` image
https://github.com/jstrachan/spring-boot-web-gradle/blob/master/Jenkinsfile

if I can get this working I'll turn it into a quickstart and add it to the build pack.

Current issues:

* not sure how to enable mvn proxying to the local nexus
* whats the gradle version of `mvn versions:set -DnewVersion=1.2.3` to update the versions?

**Comment by jstrachan** [comment]
PR added to jx binary, in a day or so we'll merge the PR for the build packs and we should have gradle support (once the new cloud-environments PR is merged) too
 https://github.com/jenkins-x/draft-packs/pull/9

**Comment by ehirsch** [comment]
Setting environment specific “things” is done with init scripts in gradle. See https://docs.gradle.org/current/userguide/init_scripts.html for more information.
Basically you would create a file `~/.gradle/init.gradle` oder `~/.gradle/init.d/*.gradle`
And in there you would add 
```groovy
allprojects {
    repositories {
        maven {
            url http…
        }
    }
}
```

**Comment by Cervator** [comment]
Bump - can probably close this with https://github.com/jenkins-x-quickstarts/spring-boot-http-gradle in place

**Comment by ehirsch** [comment]
I would think so.

**Comment by rawlingsj** [comment]
great - thanks!
