### ISSUE TITLE
Switch to using semantic releases

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4624]
### Summary 
Currently we always just increment the patch release number of the latest tag in the repo. Switching to semantic release (see https://github.com/semantic-release/semantic-release#how-does-it-work for how it works, but note that is the nodejs impl, not the go impl!) will allow us to increment the version number "semantically", controlling the type of increment via commit message.

Motivation for this change is to allow us to go back and do hot fixes on old releases without having to invent deeper levels of version numbers, as new features should always result in a new minor version.

**Comment by pmuir** [comment]
On hold as we need an update to pipeline runner etc.

**Comment by axsaucedo** [comment]
This would be quite useful for us as well. We are currently triggering releases manually, which means that we have to manually delete the tags that are automatically generated. Something that would really help us in the immediate term is to be able to just disable the automated tag creation upon a new PR merge. Is there any way to do this as a quickfix at the moment? (e.g. something like overriding the tag process in the jenkins-x.yml file?)
