### ISSUE TITLE
Knative applications are not reported properly

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#4635]
### Summary

When importing existing repositories or creating new applications with `create quickstart`, the applications are not reported properly with `jx get applications`.

### Steps to reproduce the behavior

```bash
jx edit deploy \
    --team \
    --kind knative \
    --batch-mode

jx create quickstart \
    --language go \
    --project-name jx-knative \
    --batch-mode

# Wait until it is deployed to staging

jx get applications --env staging
```

The output:

```
APPLICATION STAGING PODS URL
knative     svtns
```

### Expected behavior

It should be reported as `jx-knative`, not `knative`.

### Actual behavior

It is reported with a generic name `knative`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.418
jenkins x platform 2.0.424
Kubernetes cluster v1.13.6-gke.13
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by deanesmith** [comment]
@vfarcic Knative support will be deprecated at a random date after Feb 1 2020 from Jenkins-X in favor of Tekton pipelines.
