### ISSUE TITLE
error: Environment staging already exists!

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#464]
when installing on AWS

Carlos spotted it on slack

**Comment by carlossg** [comment]
when re-installing after several failed attempts to install

**Comment by jstrachan** [comment]
ah - the issue is the `Environment` resource already existing; not the git repo

**Comment by carlossg** [comment]
I have managed to reinstall deleting the git repos and with 

    kubectl delete job/expose; helm del --purge jenkins-x; kubectl delete environments --all; jx install --domain example.com

**Comment by jtnord** [comment]
@carlossg any steps to reproduce this?

**Comment by carlossg** [comment]
now the full namespace is deleted on uninstall, right ? then it shouldn't be a problem anymore
