### ISSUE TITLE
Meta pipeline and execution pipeline need to share the same volume

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#4660]
Following up on issue #3342, we still need to make sure that the meta pipeline and execution pipeline share the same data volume. This is essential in order for the execution pipeline to see any changes to resources an App made, eg enhance the pipeline config, but also any other file.

This is also a precondition for #4439.

**Comment by abayer** [comment]
Preliminary PR up at https://github.com/tektoncd/pipeline/pull/1087

**Comment by hferentschik** [comment]
@abayer what's the latest on this?

**Comment by abayer** [comment]
No news that I'm aware of. Will ask around.

**Comment by hferentschik** [comment]
> No news that I'm aware of. Will ask around.

Ok
