### ISSUE TITLE
jx get build logs fails to get some logs due to missing credentials

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4661]
### Summary 
I have just run a master build on one project and a PR build to preview on another project.

`jx get build logs` returns the logs for the master build but fails to find the completed PR build or any other logs with the error:
```
error: failed to open bucket <redacted>: google: could not find default credentials.
``` 
### Jx version

The output of `jx version` is:

```
2.0.438
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by tdcox** [comment]
@dgozalo

**Comment by dgozalo** [comment]
Hi, there's currently a PR open to fix this #4658. We will be switching to the `gsutil` CLI to access the GCS buckets and retrieve the stored log files.

**Comment by dgozalo** [comment]
To add more context: The Master build is probably running, that's why you can see the logs, the PR build probably got its build pods garbage collected and the logs have been stored in a GCS bucket.

This issue is only present for stored logs.

**Comment by dgozalo** [comment]
There is a workaround to this issue until the PR gets merged:
By executing: `gcloud auth application-default login` you are going to generate application-default credentials. This will enable you to get the build logs from the buckets.
