### ISSUE TITLE
jx create pullrequest returns an error if PR already exists

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4662]
### Summary 
As a part of the ML builds, I am currently calling `jx create pullrequest --push -b --title 'New model trained' --body 'feat: New model trained'`. This happens every time the training build runs and pushes an updated model to the associated service project. If the training is not good enough, the user may relaunch the master pipeline for the training build and push a fresh model into the same PR. Under these circumstances, `jx create pullrequest` is then invoked against a repo with an existing PR and now fails with the following error.

```
error: failed to create PR for base master and head branch syncmodel: creating pull request with arguments Title: New model trained; Body: feat: New model trained; Head: syncmodel; Base: master; Labels: ; Git Repo: https://github.com/project-coda/test006-service: POST https://api.github.com/repos/project-coda/test006-service/pulls: 422 Validation Failed [{Resource:PullRequest Field: Code:custom Message:A pull request already exists for project-coda:syncmodel.}]
```
Since this returns an error code to the shell script, the training build fails.

In this use-case, the pre-existence of a PR is not actually an error condition, since we actually want the build to run under an existing PR if there is one.

The question then is "should we treat the discovery of an existing PR as an error?"

If the answer is ,"Yes, sometimes", then perhaps we need a flag to indicate that we are OK with there being an existing PR so the action completes without error.

### Jx version

The output of `jx version` is:

```
2.0.438
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by tdcox** [comment]
@pmuir

**Comment by pmuir** [comment]
Did this previously rebase an existing PR?

**Comment by tdcox** [comment]
In the simple use case I have, the system is just iterating over replacing the same set of files each time until they find an outcome that is good enough to be worth promoting to staging.
