### ISSUE TITLE
JX install does not create A record on Route53 for provider EKS

### ISSUE THREAD

**Issue by aligx** [jenkins-x/jx#4688]
### Summary 
Using `jx install` on `EKS` with a custom domain name and A record is need to route requests to `hook.jx.custom.domain.com` and so on to the load balancer created by JX. 

### Steps to reproduce the behavior
Create an EKS cluster and install jenkins-x using this command:

```
jx install --provider=eks --git-api-token='yyyy' --git-username='cd@mydomain.com' --prow=true --tekton=true --no-default-environments --long-term-storage=false  --default-admin-password='xxx' --default-environment-prefix='mydomain' --on-premise --verbose=true --domain build.mydomain.com
```

### Expected behavior
An `A` record of `*.build.mydomain.com` should be created as an alias to the load balancer.

### Actual behavior
A `CNAME` record created for `*.build.mydomain.com`

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               2.0.427
git              git version 2.21.0
Operating System Mac OS X 10.14.5
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
AWS EKS

### Operating system / Environment

maxOS 10.14.5 terminal.

**Comment by daveconde** [comment]
Can you please check that the AWS user you are using has IAM permissions for Route53?

**Comment by aligx** [comment]
yes, I have full access IAM permissions on this AWS console.
