### ISSUE TITLE
local chart repository failing

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#469]
Trying a cluster I launched a few days ago, I was unable to promote a build. The staging environment pipeline failed: 

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "releases" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "jenkins-x" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: Can't get a valid version for repositories exposecontroller, exposecontroller. Try changing the version constraint in requirements.yaml
make: *** [build] Error 1
```

Any ideas?

**Comment by jstrachan** [comment]
Yeah, this is an effect of the CI/CD cluster being upgraded; it got recreated & we lost the old chart versions. If you update the exposecontroller versions in your environments git repo it should work again

**Comment by jstrachan** [comment]
Try ..56
https://monocular.build.cd.jenkins-x.io/charts/chartmuseum/exposecontroller

**Comment by michaelneale** [comment]
how did it get recreated? Not sure what I did? So in a new cluster this shouldn't happen?

**Comment by jstrachan** [comment]
should not be an issue in a new cluster - if you recreate your environment git repos. Its a gremlin caused by our CI/CD infrastructure being recreated and we lost the old chart versions basically. Am hoping we can switch to using long term persistence for released charts!

**Comment by liuxiaopiao** [comment]
Found another issue and will refer to that https://github.com/jenkins-x/jx/issues/493.  
Please ignore my questions here.

**Comment by bamb00** [comment]
@jstrachan Can you elaborate on how to update the exposecontroller versions in the git repo?

**Comment by jstrachan** [comment]
@bamb00 edit your `env/requirements.yaml` file in the git repo for your environment. e.g. like this one: 
* https://github.com/jstrachan/environment-fingertyphoon-staging/blob/master/env/requirements.yaml#L3
* https://github.com/jstrachan/environment-fingertyphoon-staging/blob/master/env/requirements.yaml#L7

try version `2.3.58`

**Comment by faheemjmi** [comment]
I am also facin gthiss issue while promoting to production with latest jx cli.
Error: pp chart not found in repo http://jenkins-x-chartmuseum:8080'

is there any fix for this ?
