### ISSUE TITLE
jx boot cannot revert from tls to http

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4692]
### Summary 
Setting tls: enabled: false when it was previously true and running `jx boot` does not successfully return the cluster to using http. It appears that the service configuration returns to http but the browser is redirected to https and fails with:
```
An error occurred during a connection to tide-jx.kill-9.uk. Peer reports it experienced an internal error. Error code: SSL_ERROR_INTERNAL_ERROR_ALERT 
```

The tls secrets are not removed.

**Comment by tdcox** [comment]
Clearing the cached data in ./env doesn't help.

According to the log, the secrets are deleted but they must subsequently be re-created.
```
STEP: clean-cert-manager command: /bin/sh -c kubectl delete issuers.certmanager.k8s.io,certificates.certmanager.k8s.io,challenges.certmanager.k8s.io,orders.certmanager.k8s.io --all in dir: .

issuer.certmanager.k8s.io "letsencrypt-prod" deleted
certificate.certmanager.k8s.io "tls-kill-9-uk-p" deleted
```
Hmmm, nope. According to K8S, they have been around for hours...
```
➜ k get secrets
NAME                                    TYPE                                  DATA   AGE
--8<--
tls-kill-9-uk-p                         kubernetes.io/tls                     3      5h13m
tls-kill-9-uk-s                         kubernetes.io/tls                     3      5h28m
```

**Comment by rawlingsj** [comment]
I'm fairly confident this could be a browser caching issue TBH.  When I've been testing this I was having to close down chrome, as even sometimes switch to using safari when switching back.  I've just tested again and it seems to work.  Can you try `curl` or a different browser to check?

FWIW I was expecting the secrets to still be in cluster, just not used.  It reduces the risk of being rate limited by lets encrypt, also helps with speed when you want to switch between http and https.

/assign rawlingsj
/area boot

**Comment by tdcox** [comment]
Yes, you are correct. When tls is enabled, the proxy sends a 308 Permanent Redirect message that is cached permanently by the browser. You can test by opening a private browser window which won't touch the cache but that doesn't stop the problem in the main browser.

You can clear the entire cache, but that will impact all other sites you visit so the best process for firefox is to open up the history browser, find the URL right click on it and select 'Forget this site'.
