### ISSUE TITLE
Preview activities failing intermittantly

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4700]
### Summary 
I created a preview build with the intention of testing the changes I made to the setup for post preview jobs but I am instead hitting an unexpected error deriving from a part of the code that I didn't touch...
```
Updating PipelineActivities bootstrap-labs-test292-pr-1-1 which has status Running
error: error checking if preview application http://test292.jx-bootstrap-labs-test292-pr-1.kill-9.uk is available: Get http://test292.jx-bootstrap-labs-test292-pr-1.kill-9.uk: dial tcp: lookup test292.jx-bootstrap-labs-test292-pr-1.kill-9.uk on 10.31.240.10:53: no such host
```
This is the correct URL and the service is visible on that URL from outside the platform but it killed the build.

Restarting the build results in a successful deployment second time around.

Can someone confirm whether this code will have been executing in an environment that was recently moved to Alpine as part of https://github.com/jenkins-x/jx/issues/4481 activities, please?

I ask because this looks very much like the symptoms of the intermittant DNS resolution failure problem that we have had with Alpine in the past.
 
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.450
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hferentschik** [comment]
@tdcox, afaik we have not come out of the discussion phase regarding moving to a smaller base image.

**Comment by okgolove** [comment]
Having the same problem.
