### ISSUE TITLE
Make Environment Controller work with private repo

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#4701]
### Summary 

Environmental controller doesn't manage to setup builds of private repos

### Steps to reproduce the behavior

Create an environmental repo using `jx create environment --remote`.

Make the repo private.

Create an environmental controller using the instructions here https://jenkins-x.io/getting-started/multi-cluster/#installing-environment-controller

`jx create addon envctl -s https://github.com/myorg/env-production.git --project-id myproject --docker-registry gcr.io --cluster-rbac true --user mygituser --token mygittoken`

### Expected behavior

The build succeeeds.

### Actual behavior

The build fails on fetching the code.
Excerpt from `jx get build logs`:

```
Showing logs for build deniedboarding/environment-jx-core-staging/master #4 stage from-build-pack and container build-step-git-source-deniedboarding-environment-jx-c-wnjx7-4rm
{"level":"warn","ts":1562939179.430739,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/backport-container-name-fix\" is not a valid GitHub commit ID"}
{"level":"error","ts":1562939179.8615935,"logger":"fallback-logger","caller":"git-init/main.go:40","msg":"Error running git [fetch --depth=1 --recurse-submodules=yes origin v0.0.6]: exit status 128\nfatal: could not read Username for 'https://github.com': No such device or address\n","stacktrace":"main.run\n\t/Users/abayer/go/src/github.com/knative/build-pipeline/cmd/git-init/main.go:40\nmain.main\n\t/Users/abayer/go/src/github.com/knative/build-pipeline/cmd/git-init/main.go:89\nruntime.main\n\t/usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201"}
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.447
Kubernetes cluster v1.13.7-eks-c57ff8
kubectl            v1.14.1
helm client        Client: v2.14.1+g5270352
git                git version 2.16.2
Operating System   Mac OS X 10.14.5 build 18F132
```

### Work around

I got it to work by following these instructions https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-git
 to create a new secret (with the existing secret jx-pipeline-git-github as a base) and changed the tekton-bot service account to make use of the secret.

**Comment by msvticket** [comment]
There are other issues that might be related: #626, #4502 and #3885

**Comment by iftachsc** [comment]
im still seeing this
NAME               VERSION
jx                 2.0.1162
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.14.10
helm client        Client: v2.14.3+g0e7f3b6
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F203

**Comment by iftachsc** [comment]
still hitting this on:
NAME               VERSION
jx                 2.0.1275
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.14.10
helm client        2.16.5
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F203
