### ISSUE TITLE
Tracking issue for resolving updatebot/release problems

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4712]
### Summary 

Just an issue to track state of repositories in updatebot graph:

| Repo | Inbound Updatebot PRs | Outboud Updatebot PRs | Changelog | No double tagging | Release build success | 
| ----- | ---- | ------------------------ | ------------------- | ---------------------- | --- |
| jenkins-x/jx | N/A | X | X | X | X |
| jenkins-x/jenkins-x-builders | X | X | X | X | X |
| jenkins-x/jenkins-x-platform | X | X | X | X | X |
| jenkins-x/jenkins-x-serverless | X | X | X | | X |
| jenkins-x-charts/jx-build-templates | X | N/A | N/A |N/A | X |
| jenkins-x/jenkins-x-versions | | |
| jenkins-x-charts/environment-controller | X | N/A | X | V | X |
| jenkins-x-charts/prow | X | N/A | X | V | X |
| jenkins-x-charts/jx-tutorials | X | N/A | N/A | N/A | N/A |
| jenkins-x-charts/jx-docs | #4761 | N/A | X | X | X |
| jenkins-x-charts/homebrew | X | N/A | X | X | X | 
| jenkins-x-charts/dev-env-base | X | X |  X | X | X |
| jenkins-x/jenkins-x-builders-base | | | | | |
| jenkins-x/exposecontroller | | | | | |
| jenkins-x/jx-java-client | | | | | |
| jenkins-x/jenkins-x-image | | | | | |
| jenkins-x-charts/nexus | | | | | |
| jenkins-x-apps/jx-app-sonarqube | | | | | |

* X - Complete
* V - Requires Version update
* N/A - not applicable

**Comment by pmuir** [comment]
Also, list of issues I found during the checking, some more or less urgent:

* https://github.com/jenkins-x/jx/issues/4713
* https://github.com/jenkins-x/jx/issues/4714 (almost certainly related to #4713, I suspect the title just isn't being updated)

**Comment by abayer** [comment]
#4771 is related too.
