### ISSUE TITLE
jx install for AKS assumes container registry is always within same Subscription

### ISSUE THREAD

**Issue by chrismellard** [jenkins-x/jx#4719]
### Summary 

When a new install is performed for an AKS cluster specifying an existing Azure Container Registry the installation assumes these resources exist within the same Azure subscription

### Steps to reproduce the behavior

1. Create an AKS cluster under one subscription
1. Create an ACR repository under a different subscription
1. Install jx via `jx install --provider=aks --docker-registry=myreg.azurecr.io`

### Expected behavior

Installation correctly identifies the existing registry and proceeds with installation

### Actual behavior

Installation falls over with as `az acr list ...` returns an empty array.

```
Failed to create ACR  in resource group 
error: configuring the docker registry: configure cloud provider docker registry: getting registry configuration from Azure: failed to run 'az acr create -g  -n  --sku Standard --admin-enabled --query id -o tsv' command in directory '', output: 'usage: az acr create [-h] [--verbose] [--debug]
                     [--output {json,jsonc,table,tsv,yaml,none}]
                     [--query JMESPATH] --name REGISTRY_NAME --resource-group
                     RESOURCE_GROUP_NAME --sku
                     {Classic,Basic,Standard,Premium} [--location LOCATION]
                     [--storage-account-name STORAGE_ACCOUNT_NAME]
                     [--admin-enabled [{true,false}]]
                     [--default-action {Allow,Deny}]
                     [--subscription _SUBSCRIPTION]
az acr create: error: Parameter 'resource_group_name' must have length greater than 1.'
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.461
Kubernetes cluster v1.12.8
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

Azure Kubernetes Service
Typical way with `az aks create -n <clustername> -g <resource-group>` etc.

### Operating system / Environment

`Mac OS X 10.14.5`

**Comment by chrismellard** [comment]
I'm happy to submit a PR for this. My thoughts are to simply query for the ACR resource group with the az cli rather than defaulting this to the same resource group as cluster.

**Comment by chrismellard** [comment]
Something different than what I initially thought going on here. Closing while I have a bit more time to analyse and restructure the issue

**Comment by chrismellard** [comment]
Issue is related to cluster existing in different subscription to container registry. We typically run our production workloads in isolated subscriptions from our development ones. We do however share a container registry between both these environments which means cross subscription access between cluster and registry.

Couple of options sprint to mind

1. Parameterise the install command with subscription ids for cluster, registry or both (could assume the current `az account show` subscription represents the cluster and omit this parameter).
1. Cycle through the subscriptions the az cli has access to in order to interrogate them to determine which subscription the ACR registry is contained within.

A knock-on consequence of this change will be to retrieve the ACR credentials from the right subscription also.

Going to proceed down option 2 until someone pipes up ;)

**Comment by chrismellard** [comment]
Thoughts @yuwzho ?

**Comment by yuwzho** [comment]
When installation, JX grant your AKS with ACR pull access, currently it searches the ACR in the current subscription you Az CLI logined with, then gets the resource ID of ACR to grant acess to AKS.

I suggest resource ID to be passed as parameters rather than looping all subscriptions, since it will times the search time according to how many subscriptions you have.

**Comment by chrismellard** [comment]
@yuwzho  There's no looping. It is accepting the subscription id as a command line flag. Resource Id isn't enough - needs the subscription Id to pin it down to a particular `az acr` query.
