### ISSUE TITLE
Add support for IBM Cloud

### ISSUE THREAD

**Issue by fabriziocucci** [jenkins-x/jx#472]
I was looking at the [roadmap](http://jenkins-x.io/contribute/roadmap/) and I noticed that there is no plan to actually integrate with [IBM Cloud](https://console.bluemix.net/) (old Bluemix).  I was wondering if a contribution for such support is something you may be interested into.

**Comment by rawlingsj** [comment]
Yeah!  I've not used IBM cloud myself but it [looks like you can create Kubernetes clusters](https://console.bluemix.net/docs/containers/container_index.html#container_index), as long as they're at least kubernetes version 1.7 we should be able to install Jenkins X.  

Do you know if RBAC is enabled? It's easier for Jenkins X if it is.

As a start it might be worth creating a cluster and running `jx install kubernetes`  and see what happen :) we're on the Kubernetes slack channel if you'd like more of a chat http://jenkins-x.io/community/

**Comment by fabriziocucci** [comment]
> Do you know if RBAC is enabled? It's easier for Jenkins X if it is.

As discussed in the [#jenkins-x-user](https://kubernetes.slack.com/messages/C9MBGQJRH) Slack channel, we should be fine with RBAC [given the Kubernetes versions supported by IBM Cloud](https://console.bluemix.net/docs/containers/cs_versions.html#cs_versions):

> Latest: 1.9.3
> Default: 1.8.8
> Supported: 1.7.4
> Deprecated: 1.5.x, unsupported 4 April 2018

**Comment by jstrachan** [comment]
@fabriziocucci I wonder if you fancy creating a kubernetes cluster on IBM cloud by hand and then trying:
```
jx install --provider=kubernetes
```
and seeing how that goes? If that works then we know IBM Cloud is supported ;) We could then try figure out the CLI commands to create a k8s cluster with IBM Cloud and add a `jx create cluster ibm` command too.

**Comment by fabriziocucci** [comment]
Sorry guys, I've been quite busy unfrotunately!

Just reporting here the results of running `jx install kubernetes` on a _free_ cluster (i.e. single worker node). During the installation there is branch point where I got two different output depending on the chosen option:

```
No existing ingress controller found in the kube-system namespace, shall we install one? [? for help] (Y/n)
```

### ...? Yes

The output coming after a `Yes` answer is:

```
$ jx install kubernetes
...
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
ingress init failed: service jxing-nginx-ingress-controller never became ready
error: service jxing-nginx-ingress-controller never became ready
```

From the Kubernetes dashboard the following event is logged:

```
Error on cloud load balancer a6b10a0972ddc11e89da34289ea6f812 for service kube-system/jxing-nginx-ingress-controller with UID 6b10a097-2ddc-11e8-9da3-4289ea6f8120: Failed to get available cloud provider IPs for load balancer services: Clusters with one node must use services of type NodePort. See https://console.ng.bluemix.net/docs/containers/container_index.html for details.
```

I will give it a try on a _paid_ cluster but a couple of things to be noted:

* the cluster is now in a _dirty_ state and running `jx uninstall` results in the following error:
```
$ jx uninstall
? Are you sure you wish to remove the Jenkins X platform from the 'jx' namespace on cluster 'https://158.175.76.2:31688'? : Yes
Error: release: "jenkins-x" not found
Error: Command failed  helm delete --purge jenkins-x
error: exit status 1
```

* unless there is a workround for the issue reported above, it seems that it's not possible to install jenkins-x on a free cluster because of the limitations of the free tier (?).

### ...? No

The output coming after a `No` answer is:

```
$ jx install kubernetes
...
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.393 --values=/Users/fabriziocucci/.jx/gitSecrets.yaml --values=/Users/fabriziocucci/.jx/adminSecrets.yaml --values=/Users/fabriziocucci/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: Job failed: BackoffLimitExceeded
make: *** [install] Error 1
Error: Command failed  make ARGS=--values=/Users/fabriziocucci/.jx/gitSecrets.yaml --values=/Users/fabriziocucci/.jx/adminSecrets.yaml --values=/Users/fabriziocucci/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2
```

I've tryied the clean-up also in this case (out of curiosity) and this is the result:

```
$ jx uninstall
? Are you sure you wish to remove the Jenkins X platform from the 'jx' namespace on cluster 'https://158.175.76.2:30356'? : Yes
release "jenkins-x" deleted
error: the server could not find the requested resource (delete environments.jenkins.io)
```

**Comment by rawlingsj** [comment]
OK thanks this is a great start.  Ok so sounds like we could try and switch to nodeport when using a single node on the free tier, hopefully the paid tier can provision an external loadbalancer on IBM cloud.

So in the single node scenario this might work `jx install kubernetes --exposer=NodePort`

On the uninstall command, yeah I think we should add logic to optionally cleanup an ingress controller and only attempt to remove the jenkins -x helm release if one exists.

**Comment by kitch** [comment]
The paid tier for IKS (IBM Cloud Kubernetes Service) does support external Load Balancers and Ingress! I haven't poked around jx much yet, but will see if there is something we can do to help here.

**Comment by bkuschel** [comment]
This can be closed as IBM Cloud (IKS) is now supported.

**Comment by jtnord** [comment]
closing as per above comment
