### ISSUE TITLE
jx boot export

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#4721]
### Summary 
Create a `jx boot --export` to allow existing installs to be converted into reproducible jx boot installs.

### Steps to reproduce the behavior
NA

### Expected behavior
Should create a jx-requirements.yaml to be used with jx-boot

### Actual behavior
No such command

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.459
Kubernetes cluster v1.13.6-gke.13
kubectl            v1.15.0
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

MacOSX

**Comment by jstrachan** [comment]
see https://jenkins-x.io/docs/labs/boot/getting-started/repository/#upgrading-an-existing-cluster
