### ISSUE TITLE
switch Jenkins configuration over to configuration as code

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#474]
would be great to switch to this plugin:
https://github.com/jenkinsci/configuration-as-code-plugin

then the configuration for Jenkins would be a simple YAML which would work great inside our helm charts

**Comment by jstrachan** [comment]
this would be quite handy https://github.com/jenkinsci/configuration-as-code-plugin/issues/76 so that changes to the `ConfigMap` would just reload on the fly ASAP.

Though this issue is the current thing holding us back from adopting it really: https://github.com/jenkinsci/configuration-as-code-plugin/issues/65

without being able to easily generate the config-as-code YAML from a running Jenkins its hard/scary to know what the YAML needs to look like ;) So please [vote on this issue](https://github.com/jenkinsci/configuration-as-code-plugin/issues/65)

**Comment by icereed** [comment]
Link: https://github.com/jenkins-x/jenkins-x-image/issues/34

**Comment by icereed** [comment]
Hi @jstrachan,
looks like this issue is resolved. Do you think it's worth a try now?

Regards,
icereed

**Comment by jstrachan** [comment]
@icereed definitely! I'm a bit snowed on a few other things for a week or so but its worth a try for sure. The main thing to do is use the latest version - [this PR](https://github.com/jenkins-x/jenkins-x-image/pull/33) has generated an image we can use to test it out: `jenkinsxio/jenkinsx:SNAPSHOT-PR-33-3` then we can export the current configuration from a running cluster.

Then we need to hack the jenkins helm template for the ConfigMap:
https://github.com/jenkins-x/charts/blob/jenkins/stable/jenkins/templates/config.yaml

to generate the `jenkins.yml` and ensure that the Jenkins server uses it. 

We could go the whole hog and just embed the actual config-as-code yaml inside the `values.yaml` file in the jenkins-x-platform: https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L196-L864

though there's a few issues we'll need to fix up if we do that - e.g. making it easy to override the dockerpath easily https://github.com/jenkins-x/charts/blob/jenkins/stable/jenkins/templates/config.yaml#L52 - dunno if there's a way to do that nicely for all pod templates in the configuration-as-code yaml.

Also if we change the structure of this YAML: https://github.com/jenkins-x/charts/blob/jenkins/stable/jenkins/templates/config.yaml#L52 we'll have to make similar changes to the `jx` code as we override some of these values when we install jenkins X - plus we modify the `ConfigMap` when we add/remove git servers. 

So its a non-trivial change - but definitely something that would be lovely to do and it'd greatly simplify the configuration of Jenkins

**Comment by icereed** [comment]
Generating the yaml or maybe even an CRD could be a nice use case for helm 3 as we could use a more programmatic approach. Probably that still will take a while until helm 3 is available. Until then we could support two approaches: Define values of the yaml or overwrite the whole yaml if desired by the user. This could be interesting for those having their own environment defined.

**Comment by torstenwalter** [comment]
I opened a PR to support configuration as code plugin as part of the official Jenkins chart: https://github.com/helm/charts/pull/10174

Maybe that helps. So far it triggers a redeploy on configuration change (via checksum of the config).
