### ISSUE TITLE
Failed to create system vault in namespace jx due to no "jx-vault-kubernetes" vault found in namespace "jx"

### ISSUE THREAD

**Issue by leestorm** [jenkins-x/jx#4758]
### Summary 
jx install process is stuck when below warning appears:
WARNING: failed to create system vault in namespace jx due to no "jx-vault-kubernetes" vault found in namespace "jx"
### Steps to reproduce the behavior
jx install --install-dependencies=true --provider=kubernetes --on-premise --git-username=******* --git-api-token=**********
### Expected behavior
If this is just a warning, installing process should go on, if this is error, it should show the detailed error message.
Even using the command : jx create vault jx-vault-kubernetes -n jx
It cannot create any vault and no any shows too.

### Jx version

The output of `jx version` is:

NAME                      VERSION
jx                              2.0.466
jenkins x platform    2.0.822
Kubernetes cluster   v1.15.0
kubectl                     v1.15.0
helm client               Client: v2.14.2+ga8b13cc
git                            git version 1.8.3.1
Operating System   CentOS Linux release 7.2.1511 (Core) 

### Jenkins type

- [x] Classic Jenkins

### Kubernetes cluster

Kuberrnetes Cluster v1.15.0  created by kubeadm 

### Operating system / Environment

Single Cent OS 7.2 machine 

### Error

? Select Jenkins installation type: Static Jenkins Server and Jenkinsfiles
Context "kubernetes-admin@kubernetes" modified.
Git configured for user: ********and email ********
WARNING: 
retrying after error:failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: read tcp ********:40006->********:443: read: connection reset by peer'
helm installed and configured
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: *********
You can now configure a wildcard DNS pointing to the new Load Balancer address *********
If you don't have a wildcard DNS setup then create a DNS (A) record and point it at: *********, then use the DNS domain in the next input...

If you do not have a custom domain setup yet, Ingress rules will be set for magic DNS nip.io.
Once you have a custom domain ready, you can update with the command jx upgrade ingress --cluster
? Domain y
nginx ingress controller installed and configured
Set up a Git username and API token to be able to perform CI/CD
? Do you wish to use leestorm as the local Git user for GitHub server: Yes
Select the CI/CD pipelines Git server and user
? Do you wish to use GitHub as the pipelines Git server: Yes
Setting the pipelines Git server https://github.com and user name leestorm.
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreating with latest: Yes
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
Enumerating objects: 1436, done.
Total 1436 (delta 0), reused 0 (delta 0), pack-reused 1436
? Defaulting workload build pack: Kubernetes Workloads: Automated CI+CD with GitOps Promotion
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
Installing jx into namespace jx
Installing jenkins-x-platform version: 2.0.822
**WARNING: failed to create system vault in namespace jx due to no "jx-vault-kubernetes" vault found in namespace "jx"**

**Comment by RenzHoly** [comment]
same warning message, did not stuck but missing jenkinsx service after install
jx version 2.0.474

**Comment by MaxDesiatov** [comment]
Reproducible for me with `jx --version` 2.0.474

**Comment by gurushub** [comment]
Reproducible

**Comment by gurushub** [comment]
Reproducible & also impeding acr pull operations.

**Comment by stewartbryson** [comment]
What is the effect of this error? Is the basic functionality still available?

**Comment by faucherb94** [comment]
Happening to me too. `jx --version` 2.0.576.

**Comment by Zougi** [comment]
same error with jx cli version `2.0.581` and server platform `2.0.942`. The effect of the error is simply that the install wizard hangs forever

**Comment by StevenPG** [comment]
I was unable to follow the fix specified by @Zougi, I still get the issue when answering `n` and setting a custom domain. 

Same issue as OP
```
NAME               VERSION
jx                 2.0.581
jenkins x platform 2.0.951
Kubernetes cluster v1.14.3
kubectl            v1.15.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0.windows.1
Operating System   Windows 10 Pro 1809 build 17763
```

**Comment by sbuvaneshkumar** [comment]
I am getting the same error.
```
student@ubuntu:~$ jx version
NAME               VERSION
jx                 2.0.971
Kubernetes cluster v1.13.1
kubectl            v1.13.1
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

**Comment by forhire** [comment]
Similar issue here ...

$   jx get secrets
error: retrieving the vault client: no "jx-vault-arn-aws-eks-e" vault found in namespace "jx"

$ jx version
NAME               VERSION
jx                 2.0.1258
jenkins x platform 2.0.2083
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.16.8
helm client        2.16.4
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
