### ISSUE TITLE
add a `jx create` wizard/quickstart for lile

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#476]
this looks a nice fast way to create golang gRPC services
https://github.com/lileio/lile

might be nice to have a `jx create lile` or `jx create quickstart lile` wizard?

**Comment by maniankara** [comment]
Hi @jstrachan! whats the idea behind this?
The challenge is, `lile` itself is a generator. I can see two options:
1. Add a new entry with pre-generated values of `lile` to [here](https://github.com/jenkins-x-quickstarts)
```
.
├── server
│   ├── server.go
│   └── server_test.go
├── subscribers
│   └── subscribers.go
├── app1
│   ├── cmd
│   │   ├── root.go
│   │   └── up.go
│   └── main.go
├── app1.proto
├── client.go
├── Makefile
├── Dockerfile
└── .gitignore
```
Then any updates to `lile` generator mainstream does not come automatically.
2. Make a way to run `lile` with jx. 
In that case, more information is needed on how to implemented.

**Comment by jstrachan** [comment]
I was thinking of option 2 - run `lile` from the command line to generate a new project source then effectively run `jx import` on the generated source. That is kinda what `jx create spring` & `jx create quickstart ` do today; a wizard to generate a project source - then is imported (creating a git repo, adding the build pack etc).

Maybe the code of those 2 commands might act as a base for creating `create_lile.go`?

**Comment by jstrachan** [comment]
eg https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_spring.go

a first cut could be to run `lile` to create the project then call the import function like the last line in the above  go file

**Comment by maniankara** [comment]
@jstrachan I didnt manage to write any unit test for these. Let me know if needed.
