### ISSUE TITLE
AWS S3 Stroage for logs - MissingRegion

### ISSUE THREAD

**Issue by jason-deland** [jenkins-x/jx#4770]
### Summary 
Config Command: jx edit storage -c logs --bucket='management-jenkins-logs' --bucket-kind='s3' --bucket-url='s3://management-jenkins-logs'

Controller Logs: {"level":"warning","msg":"failed to collect build log for pod jason-deland-docker-ruby-pr-2-s-2vgmc-3-from-build-pack-4ghj2-pod-f1145a in namespace jx: failed to write to bucket jenkins-x/logs/jason-deland/docker-ruby/PR-2/3.log: blob: MissingRegion: could not find region configuration","time":"2019-07-17T17:13:42Z"}

### Steps to reproduce the behavior
Create an EKS cluster
Install jenkinsx serverless
Configure an S3 bucket for log storage and edit the storage config

### Actual behavior
MissingRegion reported in the build controller logs

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.480
Kubernetes cluster v1.13.7-eks-c57ff8
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Terraform scripts

### Operating system / Environment

Ubuntu 18.04

**Comment by marubinotto** [comment]
Specifying a region as a query parameter (like `s3://my-bucket?region=us-west-1`) solved the issue in my case.

https://gocloud.dev/howto/blob/#s3

**Comment by deanesmith** [comment]
@jason-deland I believe this concern is reasonable well documented now via recent improvements to support cluster creation (and provisioning) leveraging Terraform - https://jenkins-x.io/docs/getting-started/setup/create-cluster/eks/.  Running `jx boot` on a Terraform based EKS cluster is reasonably well supported now including the buckets.  Please generate a new issue if there are additional problems.
