### ISSUE TITLE
Incorporate prow build into CI/CD process

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#4772]
### Summary 
We need an automated process for building, testing, and delivering prow. This hasn't been done yet due to various complications and competing priorities. This will allow us to ship hotfixes to prow with confidence, both under the current configuration and with the refactored pipeline controller and upstream prow (cf https://github.com/jenkins-x/jx/issues/4452).

**Comment by abayer** [comment]
@wbrefvem What's left for this? Feels like we should have BDD tests running against the PR build's images, which I know will be a hassle due to getting the right tags on them (thx bazel).

**Comment by wbrefvem** [comment]
@abayer Here's what's left in no particular order:
1) Bump image tag in prow chart
2) Run BDD tests against latest
3) Configure some sort of snapshot image tag for PRs

**Comment by abayer** [comment]
Cool! Sounds good.

**Comment by wbrefvem** [comment]
@abayer 

Looks like 2 is failing due to something similar to https://github.com/jenkins-x/jx/issues/4897.

And I assigned you to a PR for 1.
