### ISSUE TITLE
Feature: dynamically setting env vars in pipelines

### ISSUE THREAD

**Issue by sboardwell** [jenkins-x/jx#4774]
### Summary

This is a feature request to allow the dynamic setting of environment variables in Jenkins pipelines. The original discussion with @pmuir and @abayer can be found here in the [slack channel thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1563366726351700). 

Basically the use-case in question discusses how to best incorporate the values from `jx step pr labels -b` into a running pipeline. The step returns 
```
PR_LABELS_A_LABEL='a label'
PR_LABELS_SIZE_L='size/L'
```

For use inside a shell you would need to add the `export ...` prefix (`jx step pr labels | sed 's/^/export /g'`) giving you:
```
export PR_LABELS_A_LABEL='a label'
export PR_LABELS_SIZE_L='size/L'
```
* put the output in a file and source the file with every shell command
* use some hack such as putting them in a `$WORKSPACE/.envars` and appending `[ -f $WORKSPACE/.envvars ] && . $WORKSPACE/.envvars` to the users official `$HOME/.profile`

Using the values in a Jenkinsfile mean you need a scripted answer something like:
```
def labelsStr = sh(returnStdout: true, script: "jx step pr labels -b")
def props = new Properties()
props.load(new StringReader(labelsStr))
properties.stringPropertyNames().each {
    env.it = properties.getProperty(it))
}
```

Possible solutions have been mentioned in the slack channels such as [adding a `--format` option to outputs](https://kubernetes.slack.com/archives/C9LTHT2BB/p1563395351379500?thread_ts=1563387099.378800&cid=C9LTHT2BB) - this might well be a separate solution in it's own right since would help Jenkinsfile scripting.

A more comprehensive solution for tekton builds suggested by @jstrachan [here](https://kubernetes.slack.com/archives/C9LTHT2BB/p1563423661382300?thread_ts=1563386909.375100&cid=C9LTHT2BB)

**Comment by vacri** [comment]
I struggled with setting env vars dynamically today, and finally found this, which worked a treat for me: https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#setting-environment-variables-dynamically
