### ISSUE TITLE
create_jenkins_token does not work in 2.176.2+ unless a system property is set

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#4779]
Not yet confirmed, but [this change](https://jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626) likely means that https://github.com/jenkins-x/jx/blob/5a9355204322cf4fe1be7f8588ad99ba1ca4e337/pkg/cmd/create/create_jenkins_token.go#L405-L442 will not work any more.

**Comment by daniel-beck** [comment]
https://github.com/jenkins-x/jenkins-x-image/pull/75/files#diff-3254677a7917c6c01f55212f86c57fbfR16

**Comment by jglick** [comment]
> any random Jenkins could now present problems

OK, adjusted description accordingly.

**Comment by ccojocar** [comment]
@jglick What's the status of this issue? Have you had a chance to reproduce it? Does it require validation? Thanks!

**Comment by jglick** [comment]
I have not tried to reproduce it; requires validation.
