### ISSUE TITLE
Support multiple clusters with 'jx boot'

### ISSUE THREAD

**Issue by sdoxsee** [jenkins-x/jx#4784]
### Summary 
I know that multiple clusters is supported for `jx install` (see https://github.com/jenkins-x/jx/issues/479) but, based on there only being one key for 'cluster' in jx-requirements.yaml, I imagine it isn't yet supported for `jx boot`. I'd love to see feature parity for multiple clusters in `jx boot`

Ref: https://kubernetes.slack.com/archives/C9MBGQJRH/p1563481423267600

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.474
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.0
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

OSX

**Comment by sdoxsee** [comment]
I think the ability to put an environment in a separate cluster (e.g. production separate from dev) at minimum. From a GKE perspective, I'd like to use a separate "project" for a production environment so that permissions on the prod cluster/GCP can be much more locked down.

**Comment by sdoxsee** [comment]
Similar to the current multicluster support--with the possibility of hosting an environment in a completely different cloud provider's cluster for would be fantastic.

**Comment by AndreasKnapp1812** [comment]
Is there any progress on this? `jx boot` is really cool and I think a lot of people separate their environments with separate clusters, at least having the production environment separate from dev, staging etc.

**Comment by coderadi** [comment]
Hey, any updates on this? Are we going to pick this anytime soon?

**Comment by romenrg** [comment]
Also interested on this here. It would be great to have the multi-cluster capability with `jx boot`.

Also, it might also be a good idea to include a note in "https://jenkins-x.io/getting-started/multi-cluster/" stating that jx boot currently does not support it, to avoid confusion.

**Comment by mkeith-eir** [comment]
Even the command line tool barks and tells me that jx boot is "strongly recommended" when performing a jx upgrade platform.

I'd love to upgrade, but we have multiple clusters.  

Any updates?

**Comment by mkeith-eir** [comment]
"Command "platform" is deprecated, it will be removed on 01-02-2020. We now highly recommend you use upgrade boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details."

Will boot support multi-cluster deployments before our ability to update is removed?

**Comment by Knappek** [comment]
I am also looking forward to this. I think it is a very crucial feature in jx boot. Can please somebody provide any update on this?

**Comment by TimJones** [comment]
Also needing this feature before I can move our cluster to jenkins x

**Comment by bakuppus** [comment]
Team,  jx boot supports multi-cluster?  Did anyone have solution?

**Comment by sfynx** [comment]
I think this feature removal date should be postponed, it is quite risky to assume that the current pain points of `jx boot` like multi-cluster, boot upgrade conflicts, and proper TLS will be fixed and sufficiently tested in just one month. Imagine running it in production and features you rely on are gone suddenly without any viable upgrade path.
That said my short term goal at work will be to learn Golang and try to understand the JX project better and perhaps contribute fixes since it is an awesome project that aligns with our goals.

**Comment by jstrachan** [comment]
we should have an implementation soon...

**Comment by jstrachan** [comment]
here's documentation https://github.com/jenkins-x/enhancements/tree/master/proposals/2/docs - note its still experimental but we're hoping to get it more solid real soon...

**Comment by jstrachan** [comment]
here's the [updated documentation for using multiple clusters](https://jenkins-x.io/docs/labs/boot/multi-cluster/) with [boot with helm3](https://jenkins-x.io/docs/labs/boot/)
