### ISSUE TITLE
Enable gitops for dev env for jx boot

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4789]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by jstrachan** [comment]
@pmuir is this related to the gitops flag? https://github.com/jenkins-x/jx/blob/master/pkg/config/install_requirements.go#L155-L157

**Comment by pmuir** [comment]
More generally that jx boot isn't well integrated with the dev env gitops workflows - e.g. it doesn't fork the upstream for you, it doesn't make PRs against it as it goes, it sets the wrong URL in the team settings, that flag is off by default. 

Right now the only way I could see to make it work was to manually fork the upstream repo, clone it locally, cd into the directory and then run `jx boot` there and then create PRs against that repo by hand.

**Comment by pmuir** [comment]
I wasn't sure what your intent was here so we've worked around it using instructions for now.

**Comment by pmuir** [comment]
It's the manual fork thing that's the critical bit I think, the PRs are less so.
