### ISSUE TITLE
failed to find external URL of service hook in namespace jx

### ISSUE THREAD

**Issue by Wayne-Liu** [jenkins-x/jx#4790]
### Summary 
I have installed jx from bare-metal kubernetes，now jx install success!

I do the demo ,I execute  jx create spring -d web -d actuator

after set github account, it report errors:

error: failed to find external URL of service hook in namespace jx

### Steps to reproduce the behavior
this is my kubernetes status
![image](https://user-images.githubusercontent.com/43626914/61525644-6a0cbe80-aa4b-11e9-90e0-9e8377d9a6a5.png)

![image](https://user-images.githubusercontent.com/43626914/61525679-78f37100-aa4b-11e9-9017-c12c33367a98.png)

### Jx version

The output of `jx version` is:

```
root@ubuntu:~# jx version
NAME               VERSION
jx                 2.0.450
jenkins x platform 2.0.822
Kubernetes cluster v1.12.0
kubectl            v1.12.0
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

[ ] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

bare-metal
jx install --provider=kubernetes --on-premise

**Comment by Wayne-Liu** [comment]
I find the error code is here
![image](https://user-images.githubusercontent.com/43626914/61525785-b22be100-aa4b-11e9-91f5-db85fc34189f.png)

my kubernetes environment don't have public ip, is this reason?
github couldn't hook this jx service?

thanks

**Comment by AdrianPadilla** [comment]
Having the same issue, any idea how to work around it?

**Comment by survivant** [comment]
same error for me.  I use this command to create the cluster : 
`jx install --provider=kubernetes --on-premise --advanced-mode=true --default-admin-password=admin --git-provider-url=http://10.1.3.23:7990 --git-api-token=ODE1NzI2NTQ2MTQ3OgHa6/tUF5x2Qp70ON8VigJe2j3u --git-provider-kind=bitbucketserver --git-username=admin --static-jenkins --verbose                                                   
`

```
root@test-pcl113:~/test/jenkinsxtest# jx import
error: unable to find external URL of service jenkins in namespace jx

```
