### ISSUE TITLE
Not all Ingress are upgraded

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#4802]
### Summary

When executing `jx upgrade ingress --cluster true`, some Ingresses are skipped.

### Steps to reproduce the behavior

```bash
jx upgrade ingress --cluster true --domain play-with-jx.com
```

The output:

```
? Existing ingress rules found in the cluster.  Confirm to delete all and recreate them Yes
? Expose type Ingress
? Domain: play-with-jx.com
? If your network is publicly available would you like to enable cluster wide TLS? Yes

If testing LetsEncrypt you should use staging as you may be rate limited using production.
? Use LetsEncrypt staging or production? production
? Email address to register with LetsEncrypt: vfarcic@farcic.com
? UrlTemplate (press <Enter> to keep the current value):
? Using config values {vfarcic@farcic.com play-with-jx.com letsencrypt-prod false Ingress  true}, ok? Yes

Looking for "cert-manager" deployment in namespace "cert-manager"...
Deleting ingress vfarcic/chartmuseum
Deleting ingress vfarcic/nexus
Deleting ingress vfarcic-vfarcic-go-demo-6-pr-119/go-demo-6
Deleting ingress vfarcic-vfarcic-jx-prow-pr-2/jx-prow
Deleting ingress vfarcic-staging/jx-go
Deleting ingress vfarcic-cb-staging/jx-go-cb
Deleting ingress vfarcic/deck
Deleting ingress vfarcic/docker-registry
Deleting ingress vfarcic/hook
Deleting ingress vfarcic/tide
Expecting certificates: [vfarcic/tls-tide vfarcic/tls-deck vfarcic/tls-hook vfarcic/tls-chartmuseum vfarcic/tls-docker-registry vfarcic/tls-nexus vfarcic-cb/tls-hook vfarcic-cb/tls-chartmuseum vfarcic-cb/tls-tide vfarcic-cb/tls-deck vfarcic-cb/tls-docker-registry vfarcic-cb/tls-nexus vfarcic-cb-staging/tls-jx-go-cb vfarcic-production/tls-go-demo-6 vfarcic-staging/tls-go-demo-6 vfarcic-staging/tls-jx-go vfarcic-staging/tls-jx-prow vfarcic-vfarcic-go-demo-6-pr-119/tls-go-demo-6 vfarcic-vfarcic-jx-prow-pr-1/tls-jx-prow vfarcic-vfarcic-jx-prow-pr-2/tls-jx-prow]
Certificate issuer letsencrypt-prod does not exist. Creating...
...
WARNING: Following TLS certificates are not ready:
WARNING: vfarcic-vfarcic-go-demo-6-pr-119/tls-go-demo-6
WARNING: vfarcic/tls-chartmuseum
WARNING: vfarcic-cb/tls-nexus
WARNING: vfarcic-cb/tls-deck
WARNING: vfarcic-cb-staging/tls-jx-go-cb
WARNING: vfarcic-vfarcic-jx-prow-pr-1/tls-jx-prow
WARNING: vfarcic/tls-docker-registry
WARNING: vfarcic/tls-nexus
WARNING: vfarcic-cb/tls-docker-registry
WARNING: vfarcic-staging/tls-jx-prow
WARNING: vfarcic-vfarcic-jx-prow-pr-2/tls-jx-prow
WARNING: vfarcic/tls-deck
WARNING: vfarcic-cb/tls-chartmuseum
WARNING: vfarcic-cb/tls-hook
WARNING: vfarcic-cb/tls-tide
WARNING: vfarcic-production/tls-go-demo-6
WARNING: vfarcic-staging/tls-go-demo-6
WARNING: vfarcic-staging/tls-jx-go
WARNING: vfarcic/tls-tide
WARNING: vfarcic/tls-hook
```

There are three applications in the staging (Namespace `vfarcic-staging`) but only one of those was upgraded.

```bash
jx get applications --env staging
```

The output:

```
APPLICATION STAGING PODS URL
go-demo-6   1.0.293 3/3  http://go-demo-6.vfarcic-staging.34.74.139.228.nip.io
jx-go       0.0.1   1/1  https://jx-go.vfarcic-staging.play-with-jx.com
jx-prow     0.0.4   1/1  http://jx-prow.vfarcic-staging.34.74.139.228.nip.io
```

### Expected behavior

All three applications should have been upgraded to TLS/HTTPS.

### Actual behavior

Only one application was upgraded.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.491
jenkins x platform 2.0.861
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by thephw** [comment]
@vfarcic There should be a step where you select the environment need to do it once for production and again for staging.

**Comment by vfarcic** [comment]
@thephw  If you check the output I posted you'll see that only one of three applications I have in staging were updated. That's all in the same environment.

**Comment by thephw** [comment]
Dunno why the one has https (maybe after a different update), but the command was run with prod as per your output above. Would not expect it to update any of the staging environments.
```
? Use LetsEncrypt staging or production? production
...
Using config values {vfarcic@farcic.com play-with-jx.com letsencrypt-prod false Ingress  true}, ok? Yes
...
Certificate issuer letsencrypt-prod does not exist. Creating...
```

**Comment by vfarcic** [comment]
I was convinced that refers to staging or production API of Let's Encrypt. Are you saying that's not the case and that the question refers to `jx` environments? If I add a third `jx` environment (e.g., `pre-production`), then I'd have to select among three choices? Also, what is the purpose of `--namespaces` in that case? Is it redundant? I would assume that we'd need to remove both `--namespaces` and `--cluster` arguments if the namespaces/environments that are updated are controlled by that question.

**Comment by thephw** [comment]
Hrmm think you are correct regarding LetsEncrypt staging vs production. I would ensure it is working with staging first (no rate limiting on the LetsEncrypt staging API). Just now switching between the two I locked out the prod API via rate limiting. Also the default option is suppose to wait for certs without re-running the command, but I didn't have any luck with that option working and had to wait until the certs were ready and then re-run the command.

```
Waiting for TLS certificates to be issued...
WARNING: Following TLS certificates are not ready:
WARNING: jx/tls-chartmuseum
WARNING: jx/tls-deck
WARNING: jx-staging/tls-testjx
WARNING: jx/tls-hook
WARNING: jx/tls-nexus
WARNING: jx/tls-tide
error: not all TLS certificates are ready
```
**error: not all TLS certificates are ready** I think should not occur it should hang in the terminal until the certificates are ready.

**Comment by thephw** [comment]
I would venture `--namespaces=[]` is to help avoid requesting too many new certs and the command failing from a timeout.

**Comment by thephw** [comment]
Try running:
```
jx upgrade ingress --services=go-demo-6,jx-prow
```
