### ISSUE TITLE
create eks fails silently on permission isuses

### ISSUE THREAD

**Issue by arciisine** [jenkins-x/jx#4804]
### Summary 
When creating an EKS cluster via jx, I originally had a user configuration for a separate task, that did not have admin access.  This in turn caused the create process to fail, but silently, (even with verbosity enabled).

### Steps to reproduce the behavior
Establish AWS credentials for a user with limited access, e.g. Readonly access to S3.
Attempt to run `jx create cluster eks --name test --verbose`

### Expected behavior
The output of the process should indicate that eks-ctl failed and hopefully present stdout or stderr.

### Actual behavior
```bash
$  jx --verbose=true create cluster eks --cluster-name=test
DEBUG: eksctl is already available on your PATH at $HOME/.jx/bin/eksctl
DEBUG: aws-iam-authenticator is already available on your PATH at /usr/local/bin/aws-iam-authenticator
DEBUG: Dependencies to be installed: 
DEBUG: kubectl is already available on your PATH at /usr/local/bin/kubectl
DEBUG: helm is already available on your PATH at $HOME/.jx/bin/helm
error: exit status 1
```

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               2.0.491
git              git version 2.17.1
Operating System Ubuntu 18.04.2 LTS
```

### Jenkins type
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins
- [X] N/A  -- Didn't get that far

### Kubernetes cluster
Attempting to create eks cluster

### Operating system / Environment
Ubuntu 18.04.2

**Comment by AntonSalnikov** [comment]
I have the same issue with eks. I was managed to proceed further just removing "--cluster-name" option from command line. But in this case cluster with randomly generated name is created. It is not what I really want to achieve.

`
$ jx create cluster eks --cluster-name=test-k8s --skip-installation=true --profile=staging-admin --region=eu-west-1 --verbose
DEBUG: eksctl is already available on your PATH at /home/anton/.jx/bin/eksctl
DEBUG: aws-iam-authenticator is already available on your PATH at /home/anton/.jx/bin/aws-iam-authenticator
DEBUG: Dependencies to be installed: 
DEBUG: kubectl is already available on your PATH at /usr/local/bin/kubectl
DEBUG: helm is already available on your PATH at /home/anton/.jx/bin/helm
error: exit status 1

`
