### ISSUE TITLE
docker image for jx

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#481]
rather than jx being added to the base builder image after each release and all builder images then being re-released, we could have a scratch docker image for jx and add that as a container in each podTemplate - like jnlp https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L200-L201

every Jenkinsfiles would need to be updated to switch `container('jx'){...}`

I think that's all that's needed and it would dramatically reduce the number of releases needed after a change to jx.

One drawback is quota I guess as an extra container in each build pod takes extra resources but as long as there's no silly minimum cluster quota set it should be fine.

**Comment by jstrachan** [comment]
It would be nice having all the tools like helm / jx / skaffold in a separate image - then folks could use any mvn/gradle/go  image

**Comment by rawlingsj** [comment]
Yeah like the client-builder image we had in fabric8.  Originally in jx I thought it would be handy if they were in a base image but now we have a few language builder images it's not making sense.
