### ISSUE TITLE
Build counter for a repository doesn't seem to reset on new PRs and sometimes jumps a few positions

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#4827]
### Summary 
While working on a repository, I created a PR and started pushing commits. The build number would increase normally but sometimes it would skip exactly 10 numbers, so for example it went from 20 to 30.

Also, after finishing that PR and creating a new one, the build number of the first pipeline run wasn't 1 but the next number after the closed PR.

So the first execution of that PR had build number 50.

It also skipped 10 positions when it reached 61 and went up to 72.

### Steps to reproduce the behavior
Create a PR on a repo, add a few commits, close it and open a new one.

### Expected behavior
The new PRs should start with build number 1 and don't skip 10 positions randomly.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
Pretty sure this is fixed. Reopen if needed.
