### ISSUE TITLE
something about jx install

### ISSUE THREAD

**Issue by zjj2wry** [jenkins-x/jx#4838]
### Summary 
I can quickly install jenkins-x using jx install now. But I encounter two problems when I use it.

1. jenkins-x chart address hardcode In the code (https://storage.googleapis.com/chartmuseum.jenkins-x.io), Chinese users are unable to access storage.googleapis.com in their cloud provider, so we need to import the chart into own repository and modify the image name to use it. i think this should be configurable.
2. The versions of jx, kubectl, and helm seem to have a corresponding relationship. I failed when I first executed jx install. I deleted my local kubectl and helm solved this problem.

Are we considering providing a image for user? we can do some preconditions in the image to ensure the correspondence of the version.
Example
```
FROM raarts/netutils

RUN mkdir -p ~/.jx/bin
RUN export PATH=$PATH:~/.jx/bin
RUN echo 'export PATH=$PATH:~/.jx/bin' >> ~/.bashrc
RUN curl -L https://github.com/jenkins-x/jx/releases/download/v2.0.468/jx-linux-amd64.tar.gz | tar xzv -C ~/.jx/bin

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

RUN curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.14.2-linux-amd64.tar.gz
RUN tar -xzvf helm-v2.14.2-linux-amd64.tar.gz
RUN mv ./linux-amd64/helm ~/.jx/bin
RUN mv ./linux-amd64/tiller ~/.jx/bin

# install git
RUN apt-get update
RUN apt-get -y install git


RUN ~/.jx/bin/helm init --client-only
RUN ~/.jx/bin/helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io
RUN ~/.jx/bin/helm repo update

CMD ["/bin/bash","-l"]
```
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by warrenbailey** [comment]
You could use the Jenkins X Developer environment https://github.com/jenkins-x/dev-env this comes with the correct versions of all the dependencies you'll need

**Comment by zjj2wry** [comment]
https://storage.googleapis.com/chartmuseum.jenkins-x.io can be a configuration item, helm install should have a parameter --upgrade to decide whether to execute helm fetch
