### ISSUE TITLE
jx boot not installing with vault

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4856]
### Summary 
jx boot fails to install using vault and tls with external-dns:

```
Creating Vault...
Vault jx-vault-d60 created in cluster d60
Exposing Vault...
error: exposing vault: configure exposecontroller: issuer config value must not be empty
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault' command in directory 'systems/vault', output: ''
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.513
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

**Comment by renatoaraujoc** [comment]
I can confirm this bug. Has anyone been able to install with jx-boot with Vault?

**Comment by deanesmith** [comment]
Adding to sprint to investigate the configuration that reproduced this.  Identify potential solutions.

**Comment by pmuir** [comment]
Attempting to create reproduction for this:

1) `jx create cluster gke --skip-installation`
2) `jx boot` - accept defaults, and use the `muirp` org for environments
3) edit `jx-requirements.yaml` and set
