### ISSUE TITLE
503 Service unavailable for a sample java project when staged via Jenkins X

### ISSUE THREAD

**Issue by gurushub** [jenkins-x/jx#4860]
### Summary 
When JenkinsX is deployed via AKS and a sample java project is imported (via quick start), the build is successful and gets promoted to Stage (all green). Jenkins X deployment is successful (jx step verify install all OK)

The endpoints url when hit are returning 503 error. 
### Steps to reproduce the behavior
1. JX Install with aks
2. Import a java or go based quick start project. 
3. Build and promote to stage (automated)
4. jx get applications
5. Access the URL of the application as mentioned. 
6. Returns 503 Error
### Actual behavior
APPLICATION      STAGING PODS URL
test-movies-java 0.0.4        http://test-movies-java.peteam-staging.104.XXX.XX.XX.nip.io
test-spring-java 0.0.1        http://test-spring-java.peteam-staging.104.XXX.XX.XX.nip.io

Upon hitting the URL ABOVE Returns:
503 Service Temporarily Unavailable

Jenkins X is accessible without any issues. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
jx                 2.0.512
jenkins x platform 2.0.880
Kubernetes cluster v1.13.7
kubectl            v1.13.2
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.22.0
Operating System   CentOS Linux release 7.6.1810 (Core) 

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ *] Classic Jenkins

### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->

### Operating system / Environment

<!--
In which environment are you running the jx CLI?
-->

**Comment by funkypenguin** [comment]
Does the pod die with an OOMKiller error? (See my #4876 for details). If so, editing `chart/values.yaml` to increase the memory limit is a temporary fix...
