### ISSUE TITLE
Error: Looks like "http://chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.jenkins-x.io/index.yaml : 503 Service Unavailable

### ISSUE THREAD

**Issue by YuTingLiu** [jenkins-x/jx#4861]
### Summary 
Error: Looks like "http://chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.jenkins-x.io/index.yaml : 503 Service Unavailable
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.368
jenkins x platform 2.0.861
Kubernetes cluster v1.12.8
kubectl            v1.12.8
helm client        Client: v2.14.0+g05811b8
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Operating system / Environment

Link: “http://chartmuseum.jenkins-x.io” can be openned by chrome, is there any solution to async this chart to my chartmuseum pod in k8s?
jenkins-c67754df7-9zddm                         2/2     Running            0          6d18h
jenkins-x-chartmuseum-75d45b6d7f-mf6nd          2/2     Running            0          2d20h
jenkins-x-controllerrole-6b878c94f6-xssmq       1/1     Running            0          6d19h
jenkins-x-controllerteam-57bf77566b-rpjmr       1/1     Running            4          6d19h
jenkins-x-controllerworkflow-6cd47b49bc-gr9lb   1/1     Running            0          6d19h

**Comment by blademainer** [comment]
same issues

**Comment by YuTingLiu** [comment]
@blademainer Have you solved this issue yet?
