### ISSUE TITLE
jx boot is no longer reentrant

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4864]
### Summary 
It is no longer possible to run `jx boot` repeatedly as the second invocation fails with:
`Service "jxing-nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable'`

### Jx version

The output of `jx version` is:

```
jx                 2.0.513
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030```

**Comment by pmuir** [comment]
You can work around this by deleteing the `jxing-...` services from the `kube-system` namespace 

```kubectl delete svc --namespace=kube-system jxing-nginx-ingress-controller jxing-nginx-ingress-default-backend```

**Comment by jstrachan** [comment]
its due to a bug in the old versions of the ingress chart I think - you only have to do that `kubectl delete svc` once then when you're on the new ingress chart its re-entrant again

**Comment by jstrachan** [comment]
am gonna close this one for now - AFAIK that one time manual workaround is enough. Let us know if this ever comes back once you've upgraded to a more recent nginx-ingress version (like the one in the current version stream)
