### ISSUE TITLE
Upgrade add on prow fails on GitOps cluster

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#4870]
### Summary 

When running `jx upgrade add on prow` on a cluster with gitops enabled the following error appears:

➜ jx upgrade addon prow
Installing tekton into namespace jx
WARNING:
retrying after error:currently GitOps mode is only supported using the local file system for install time use only
error: failed to install Tekton: after 2 attempts, last error: currently GitOps mode is only supported using the local file system for install time use only

More details here:
https://kubernetes.slack.com/archives/C9LTHT2BB/p1564126740062200

Related to https://github.com/jenkins-x/jx/issues/3392

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by tdcox** [comment]
I have reproduced this on a second cluster so it is failing consistently.

**Comment by tdcox** [comment]
It looks like there have been a number of significant changes within the prow/tekton area that may not have been picked up by users. I have a test cluster that I was able to fix by just updating the pipelinerunner image from 560 to 605 manually, but my main cluster is back on 464 and trying the same trick just results in admission webhook errors.
