### ISSUE TITLE
Jenkins X install using private docker repository

### ISSUE THREAD

**Issue by VincenzoDo** [jenkins-x/jx#4871]
Hello,

I would like to install Jenkins X on a private Kubernetes cluster, which has no direct access to docker registries such as gcr.io, docker hub, quay etc.. Is there any way to tell "jx install" where to fetch all the images needed for the Jenkins X ecosystem (eg from my private registry)? Otherwise I simply end up with no pods running due to the fact that it can't fetch the needed images.

Best regards,
Vincenzo

**Comment by hervelemeur** [comment]
AFAIK, you can use the `--docker-registry` command line parameter to specify your own registry.

**Comment by jstrachan** [comment]
with `jx boot` you can specify `cluster.registry` in your `jx-requirements.yml` to point at your container registry host
