### ISSUE TITLE
tide doesn't respond to all bot commands

### ISSUE THREAD

**Issue by funkypenguin** [jenkins-x/jx#4877]
### Summary 

I get inconsistent results trying to interact with a PR using comments.

### Steps to reproduce the behavior

1. Go to https://github.com/fpjx/t21/pull/1
2. Add a comment with a command available to anyone, from https://prow.k8s.io/command-help (i.e., /meow)

### Expected behavior

Tide takes an action (assigning a label for my approval, adding a shrug picture, etc)

### Actual behavior

Results are inconsistent. When I tried to `/approve`, I got no response. A non-owner tried to approve, and tide at least responded to him.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.521
jenkins x platform 2.0.880
Kubernetes cluster v1.14.2
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Kube 1.14 built using kubeadm on bare-metal

### Operating system / Environment

Ubuntu 1804

**Comment by funkypenguin** [comment]
I had better luck after a re-install. This time, I could /approve the PR, and even /meow worked. But /shrug and /bark didn't. Am I still getting intermittent results, or are only a subset of the documented commands available? PR illustrating my efforts is https://github.com/fpjx/t24/pull/1

**Comment by tomfrenken** [comment]
Had the same issue occur to me, though `/approve` did never work in my case.
