### ISSUE TITLE
cannot install apps without a vault when using GitOps for your dev environment

### ISSUE THREAD

**Issue by blademainer** [jenkins-x/jx#4884]
### Summary 
I type: `jx add app monocular` and returns:
> cannot install apps without a vault when using GitOps for your dev environment

### Steps to reproduce the behavior
jx add app monocular

### Expected behavior
add ui

### Actual behavior
error  happened

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.518
jenkins x platform 2.0.718
Kubernetes cluster v1.11.5
kubectl            v1.14.2
helm client        Client: v2.14.1+g5270352
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

v1.11.5

### Operating system / Environment

macOS

**Comment by nassercarlos19** [comment]
I have this same error when upgrading platform, is there a solution to this? What is the error?

**Comment by ccojocar** [comment]
GitOps is only supported with Vault and boot. I am going to close this issue. Fee free to open an other issue if you encounter the same problem.

**Comment by michaeljohnbennett** [comment]
so how do you solve the problem? I have the same thing happening to me using AKS and bitbucketcloud for git. When I try to install an app or even upgrade them I get the same error.

Is there some part of the documentation that outlines how to fix this that I have missed otherwise I don't think this issue is closed?
