### ISSUE TITLE
Adding missing Helm repo: storage.googleapis.com-0 https://storage.googleapis.com/chartmuseum.jenkins-x.io error: failed to add chart repositories: failed to add the Helm repository with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io': failed to add the repository 'storage.googleapis.com-0' with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io': failed to run 'helm repo add storage.googleapis.com-0 https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '.', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: unexpected EOF'

### ISSUE THREAD

**Issue by YuTingLiu** [jenkins-x/jx#4889]
### Summary 
How to avoid this in jx environment.
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.368
jenkins x platform 2.0.861
Kubernetes cluster v1.12.8
kubectl            v1.12.8
helm client        Client: v2.14.0+g05811b8
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster
kops

**Comment by pmuir** [comment]
what command are you running? where do you see this error?

**Comment by YuTingLiu** [comment]
@pmuir This error was reported by jenkins console when pipeline was activated.
![阿里旺旺图片20190809094158](https://user-images.githubusercontent.com/8286904/62748119-faa64f80-ba89-11e9-80cc-30f16c284d37.jpg)

**Comment by pmuir** [comment]
Is this due to storage.googleapis.com being blocked in China?

**Comment by YuTingLiu** [comment]
@pmuir Yes, I havn't watch this repo for a long time, is there any solution for this issue?
