### ISSUE TITLE
`jx create environment` doesn't allow selection of repo location for single organization users

### ISSUE THREAD

**Issue by drewterry** [jenkins-x/jx#489]
When running `jx create environment`, the prompt to select an organization/user location doesn't appear if the git user is only a member of a single organization.  In this case, it automatically chooses the organization, preventing the user from using their personal account for the repo.

I was able to verify this behavior by creating a dummy organization for myself (bringing my organization membership to 2) at which point the prompt to select an organization (or my username) appeared.

Note: this also applies to `jx create cluster minikube`.

**Comment by jstrachan** [comment]
@drewterry thanks for the heads up @drewterry. This was recently spotted in another part of the CLI: https://github.com/jenkins-x/jx/issues/450

there should be a fix in 1.1.26 for this: https://github.com/jenkins-x/jx/releases - I wonder if you could double check its now working for you?

**Comment by drewterry** [comment]
Fixed with 1.1.26, thanks!
