### ISSUE TITLE
jx create cluster / jx install broken due to ingress chart issue

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4898]
### Summary 
Installations are currently broken due to the following issue:
```
ERROR: Failed to install ingress chart: failed to run 'helm fetch -d /var/folders/2n/n92yy0vd2pvfj1r8r3_ntp700000gn/T/helm-template-workdir-369374684/jxing/chartFiles --untar stable/nginx-ingress --version 1.11.4' command in directory '', output: 'Error: chart "nginx-ingress" matching version "1.11.4" not found in stable index. (try 'helm repo update'). No chart version found for nginx-ingress-1.11.4'
FATAL: ingress init failed: deployments.apps "jxing-nginx-ingress-controller" not found
```
### Steps to reproduce the behavior
```
jx create cluster gke \
--advanced-mode \
--cluster-name='d61' \
--default-admin-password='xxxxxxxx' \
--default-environment-prefix='d61' \
--environment-git-owner='Bootstrap-Jersey' \
--enable-autoupgrade=true \
--git-api-token='xxxxxxxxxxxxxxxxxxxxxxxx' \
--git-username='bootsbot' \
--git-private=false \
--labels='demo=true' \
--machine-type='n1-standard-8' \
--max-num-nodes='3' \
--min-num-nodes='1' \
--ng=true \
--project-id='jx-mar19' \
--skip-login=true \
--zone='europe-west1-d'
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.518
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by jiangytcn** [comment]
@tdcox  have you installed the stable helm repo ? 

```
$  helm repo list                                                                                                                        ‹ruby-2.6.3›  /home/jiangytcn
NAME     	URL                                                    
stable   	https://kubernetes-charts.storage.googleapis.com       
local    	http://127.0.0.1:8879/charts                           
jenkins-x	https://storage.googleapis.com/chartmuseum.jenkins-x.io

~/github.com/jx-pipelines devbox ⌚ 20:16:50
$ helm search nginx-ingress                                                                                                              ‹ruby-2.6.3›  /home/jiangytcn
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                                 
jenkins-x/nginx-ingress	0.21.1       	0.14.0     	An nginx Ingress controller that uses ConfigMap to store ...
stable/nginx-ingress   	1.11.4       	0.25.0     	An nginx Ingress controller that uses ConfigMap to store ...
stable/nginx-lego      	0.3.1        	           	Chart for nginx-ingress-controller and kube-lego  
```

**Comment by heavyengineer** [comment]
I had the same problem this morning with this out of date version of the nginx/ingress repo:

➜ helm search nginx-ingress 
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                                 
jenkins-x/nginx-ingress	0.21.1       	0.14.0     	An nginx Ingress controller that uses ConfigMap to store ...
stable/nginx-ingress   	1.11.0       	0.25.0     	An nginx Ingress controller that uses ConfigMap to store ...
stable/nginx-lego      	0.3.1        	           	Chart for nginx-ingress-controller and kube-lego 

running ```helm upgrade repo```  incremented the version and it's now installing OK.

**Comment by kenwoodjw** [comment]
same issue

**Comment by jtfogarty** [comment]
I'm having this issue as well

**Comment by jtfogarty** [comment]
is there a status on this issue?  It seem to me that the /tmp/values.yaml file is not being created.

This is very intermittent, 8/17 this was working fine

'Error: failed to parse /tmp/values.yaml579551686: error converting YAML to JSON: yaml: mapping values are not allowed in this context' FATAL: ingress init failed: deployments.apps "jxing-nginx-ingress-controller" not found

**Comment by tdcox** [comment]
IIRC, this was due to an update to the ingress version with a jx upgrade platform leading to a situation where the client-side helm repo status was out of sync. Not sure if this has been addressed to mitigate future occurrances?
