### ISSUE TITLE
Trailing Slash in Helm3 Repo-Url missing

### ISSUE THREAD

**Issue by InsOpDe** [jenkins-x/jx#4902]
### Summary 
In previous versions of helm trailing slashes could be omitted. Not with the current version 3 of helm. This results in the repo-flag to be ignored as described in this [issue](https://github.com/helm/helm/issues/6113) . This then results to helm-charts cant be installed anymore due to incorrect repo-urls.

### Steps to reproduce the behavior
` jx add app tekton`

### Expected behavior
Tekton should be added

### Actual behavior
```
error: failed to run 'helm fetch tekton --untardir /tmp/jx-helm-fetch-tekton-804244063 --untar --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: failed to fetch https://storage.googleapis.com/charts/tekton-0.0.42.tgz : 403 Forbidden'
```
You see that it incorrectly tries to get `https://storage.googleapis.com/charts/tekton-0.0.42.tgz` when it actually should be `https://storage.googleapis.com/chartmuseum.jenkins-x.io/charts/tekton-0.0.42.tgz`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.528
Kubernetes cluster v1.12.8
kubectl            v1.15.1
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type
- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
aks

### Operating system / Environment
Ubuntu 18.04

**Comment by jstrachan** [comment]
here is the current helm 3 implementation 
https://jenkins-x.io/docs/labs/boot/

Note that it’s currently alpha though
