### ISSUE TITLE
jx boot cluster environments ingress broken when using dns & tls

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#4906]
### Summary 

When configuring a jx cluster using boot with DNS & TLS the environments (preview/staging...) aren't setup with the correct URL template and certificates (plus secrets propagation) to view applications.

### Steps to reproduce the behavior
Install cluster using `jx boot`

### Expected behavior
The url template should match services deployed to the `jx` namespace. Perhaps the Ingress for each service/application should be templated from the boot config so that the tls configuration can be updated if tls is enabled.

### Actual behavior

The ingress configuration is set to tls in the config map and the application deployed does not have tls configuration in its ingress and therefore fails. The domain is not using the standard url template so the tls certificate does not apply to the domain allocated for these environments.

### Jx version

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.528
kubectl            v1.15.0
git                git version 2.22.0
Operating System   Alpine Linux 3.10.1
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Revisit design and will add short term/workaround in the meantime

**Comment by ccojocar** [comment]
I think this a duplicate of https://github.com/jenkins-x/jx/issues/4906. @cagiti Can we close it? Thanks!

**Comment by ccojocar** [comment]
Closing this as a duplicate of #5310.
