### ISSUE TITLE
‘Jenkins’ doesn’t have label ‘jenkins-maven’

### ISSUE THREAD

**Issue by demoawsgaurav** [jenkins-x/jx#4912]
### Summary 

My EKS cluster is up and running, when i am trying to create a spring boot app, getting the error while running the Jenkins pipeline.

### Steps to reproduce the behavior

Run "jx create spring", go up to starting the Jenkins pipeline

### Expected behavior

It should run the pipeline and deploy the app.

### Actual behavior

Started by user admin
15:30:18 Connecting to https://api.github.com using demoawsgaurav/****** (API Token for acccessing https://github.com Git service inside pipelines)
Obtained Jenkinsfile from 6781e53c894a0c6f2879609fc6757cc14cb2d0ed
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
‘Jenkins’ doesn’t have label ‘jenkins-maven’
Running on Jenkins in /var/jenkins_home/workspace/emoawsgaurav_StackExpress_master@2
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
using credential jx-pipeline-git-github-github
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/demoawsgaurav/StackExpress.git
 > git init /var/jenkins_home/workspace/emoawsgaurav_StackExpress_master@2 # timeout=10
Fetching upstream changes from https://github.com/demoawsgaurav/StackExpress.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials API Token for acccessing https://github.com Git service inside pipelines
 > git fetch --no-tags --force --progress https://github.com/demoawsgaurav/StackExpress.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/demoawsgaurav/StackExpress.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/demoawsgaurav/StackExpress.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/demoawsgaurav/StackExpress.git
using GIT_ASKPASS to set credentials API Token for acccessing https://github.com Git service inside pipelines
 > git fetch --no-tags --force --progress https://github.com/demoawsgaurav/StackExpress.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision 6781e53c894a0c6f2879609fc6757cc14cb2d0ed (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6781e53c894a0c6f2879609fc6757cc14cb2d0ed
Commit message: "revert"
 > git rev-list --no-walk 972d5b225b8ac08333747e620d8ad481ce1dbf39 # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withCredentials
Masking only exact matches of $CHARTMUSEUM_CREDS or $CHARTMUSEUM_CREDS_USR or $CHARTMUSEUM_CREDS_PSW
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (CI Build and push snapshot)
Stage "CI Build and push snapshot" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] container
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Environments)
Stage "Promote to Environments" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: Node is not a Kubernetes node: 
Finished: FAILURE

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

**Comment by demoawsgaurav** [comment]
Please help!

**Comment by mar-rih** [comment]
I have the same issue
