### ISSUE TITLE
jx boot does not install missing binaries

### ISSUE THREAD

**Issue by codebryo** [jenkins-x/jx#4917]
### Summary 
`kubectl` dependency does not automatically get installed on the OS

### Steps to reproduce the behavior
- Do not have `kubectl` installed on your system
- Download or install jx (I downloaded the exec and move it to `usr/local/bin` manually to have it in the path.
- Run all the `jx` magic like boot :)
- Mess up some config values and try to remove ecverything from the GKE cluster
- Realize you do not have `kubectl` installed

### Expected behavior
As `kubectl` is a binary dependency, it should get installed through jx right away

### Actual behavior
`jx boot` does not install missing binaries

### Jx version

The output of `jx version` is:

```
jx                 2.0.521
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.1
git                git version 2.15.1
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE - following jx create cluster documentation

### Operating system / Environment
macOS

**Comment by pmuir** [comment]
It would be good to roll this into working out how we manage binary versions between different version streams and clusters
