### ISSUE TITLE
JenkinsX gitea issue

### ISSUE THREAD

**Issue by AjithPulakkazhy** [jenkins-x/jx#4922]
### Summary 
I was trying out jenkinsx and while installing, it tries to install addon gitea and it fails.
### Steps to reproduce the behavior
'jx install' and after selecting the cloud provider and github credentials
### Expected behavior
Installing jx into namespace jx
Installing jenkins-x-platform version: 2.0.880
### Jx version
The output of `jx version` is:
jx                 2.0.474
jenkins x platform 2.0.880
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.13.2
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.22.0.windows.1
Operating System   Windows 10 Enterprise 1809 build 17763
### COPY OUTPUT HERE
WARNING: waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx
Configuring the TeamSettings for ImportMode YAML
Installing addon gitea
WARNING: could not find a stable version from charts of jenkins-x/gitea from C:\Users\user\.jx\jenkins-x-versions
For background see: https://jenkins-x.io/architecture/version-stream/
Please lock this version down via the command: jx step create version pr -k charts -n jenkins-x/gitea
error: installing the Jenkins X Addons: failed to install addon gitea: failed to run 'kubectl apply --recursive -f C:\Us
ers\user\AppData\Local\Temp\helm-template-workdir-261727881\gitea\output\namespaces\gitea -l jenkins.io/chart-release
=gitea --namespace gitea --validate=false' command in directory '', output: 'Error from server (NotFound): error when cr
eating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-261727881\\gitea\\output\\namespaces\\gitea\\cha
rts\\gitea-cleanup\\templates\\part0-role.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\gitea-cleanup\\templates\\part0-serviceaccount.yaml": namespaces "gitea"
 not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\gitea-expose\\templates\\part0-role.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\gitea-expose\\templates\\part0-serviceaccount.yaml": namespaces "gitea"
not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-deployment.yaml": namespaces "gitea" not fo
und
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-pvc.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-secrets.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-svc.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\templates\\part0-configmap-tcp.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\templates\\part0-configmap.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\templates\\part0-deployment.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\templates\\part0-pvc.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\templates\\part0-secrets.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-26172
7881\\gitea\\output\\namespaces\\gitea\\templates\\part0-service.yaml": namespaces "gitea" not found'

C:\Users\user\AppData\Local\Google\Cloud SDK>jx create addon gitea
WARNING: failed to create system vault in namespace jx due to no "jx-vault-sightjelly" vault found in namespace "jx"
WARNING: could not find a stable version from charts of jenkins-x/gitea from C:\Users\user\.jx\jenkins-x-versions
For background see: https://jenkins-x.io/architecture/version-stream/
Please lock this version down via the command: jx step create version pr -k charts -n jenkins-x/gitea
error: failed to run 'kubectl apply --recursive -f C:\Users\user\AppData\Local\Temp\helm-template-workdir-072416383\g
itea\output\namespaces\gitea -l jenkins.io/chart-release=gitea --namespace gitea --validate=false' command in directory
'', output: 'Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-
workdir-072416383\\gitea\\output\\namespaces\\gitea\\charts\\gitea-cleanup\\templates\\part0-role.yaml": namespaces "git
ea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\gitea-cleanup\\templates\\part0-serviceaccount.yaml": namespaces "gitea"
 not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\gitea-expose\\templates\\part0-role.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\gitea-expose\\templates\\part0-serviceaccount.yaml": namespaces "gitea"
not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-deployment.yaml": namespaces "gitea" not fo
und
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-pvc.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-secrets.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\charts\\postgresql\\templates\\part0-svc.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\templates\\part0-configmap-tcp.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\templates\\part0-configmap.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\templates\\part0-deployment.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\templates\\part0-pvc.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\templates\\part0-secrets.yaml": namespaces "gitea" not found
Error from server (NotFound): error when creating "C:\\Users\\user\\AppData\\Local\\Temp\\helm-template-workdir-07241
6383\\gitea\\output\\namespaces\\gitea\\templates\\part0-service.yaml": namespaces "gitea" not found'

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
gke

### Operating system / Environment
windows

**Comment by ccojocar** [comment]
The recommend way to install Jenkins X now is boot instead of install. I am going to close this. Thanks!
