### ISSUE TITLE
jx boot update-webhooks fails to config git auth service correctly

### ISSUE THREAD

**Issue by chrismellard** [jenkins-x/jx#4933]
### Summary 

When `jx boot` runs `jx update webhooks` the Git auth service is incorrectly configured from the Git secrets stored on the cluster.

### Steps to reproduce the behavior

1. Run `jx boot`
2. Provide some git user and token as part of parameter prompt step
3. Watch as the `jx update webhooks` command hangs

### Expected behavior

1. Webhooks are correctly created

### Actual behavior

1. They're not.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.399-dev+d8fd7d9db
Kubernetes cluster v1.12.8
kubectl            v1.14.2
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203

```

Seems to be due to the fact that there is some code here

https://github.com/jenkins-x/jx/blob/1b164610bfeeb53ea9788f9990bd0139a052ec13/pkg/cmd/clients/factory.go#L346-L358

preventing the correct formation of the auth service as isCDPipeline is false when this executes. Not entirely sure what this guard is seeking to achieve - function doesn't seem super useful is isCDPipeline is false

**Comment by chrismellard** [comment]
Was planning on submitting a PR for this where we specify a factory with isCDPipeline set to true. But it's gone midnight so I'll take a look tomorrow unless someone not in GMT+12 wants to take a look ;)

**Comment by ccojocar** [comment]
related to https://github.com/jenkins-x/jx/issues/5114

**Comment by ccojocar** [comment]
The code mentioned here was refactored to handle the secrets sources in a more generic way. I am going to close it for now. Thanks for reporting it!
