### ISSUE TITLE
Build logs are currently confusing

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4936]
### Summary 
The new log format is confusing and very difficult for developers to interpret accurately. There appear to be a number of issues. For example, in the following log we can see several problems:
https://gist.github.com/terrycoda/0c5652fa05a9e3069e377b410e3b5b76

Firstly, the ultimate problem that terminates the build is here: https://gist.github.com/terrycoda/0c5652fa05a9e3069e377b410e3b5b76#file-gistfile1-txt-L53 however the log contains spurious output that implies that 8 subsequent steps executed but produced no log output. Logging should have terminated at line 54.

The message `WARNING: pod project-coda-coda-han-0004-trai-bj6bj-14-build-2kh4n-pod-131710 has failed` is not a warning, it's an ERROR as execution is terminated.

That, combined with the issue that log monitoring with `jx get build logs` does not terminate, implies that subsequent pipeline stages are still in progress, but are silent.

Even more confusingly, these warnings start to appear at line 33: https://gist.github.com/terrycoda/0c5652fa05a9e3069e377b410e3b5b76#file-gistfile1-txt-L33
This is prior to the output from several earlier steps in the pipeline being displayed, making the actual point of failure indeterminate.

Worse, these warnings are colorized and the actual errors are not.

As a result, it is almost impossible for anyone who does not understand how the pipelines are implemented under the hood to work out where in the pipeline their specific error occurred. I would suggest that this should not be required knowledge for the average user of the platform.

We should probably remove all but one ERROR showing the failure of the build and this should occur after the actual point of failure. All subsequent log output should be suppressed and monitoring should terminate.

Furthermore, this build has been executed 14 times and the only log output recorded in the LTS bucket is from the final container of the last stage of the first execution of the build.

**Comment by dgozalo** [comment]
Giving you a small update @tdcox.

I've been working on solving this, everything should be more clear now, I removed the warnings and the stream of logs should stop once a failed step has been found. 

Stored logs should now also have the very same format as the running build logs, this should help understand them better.
What I haven't been able to reproduce is your last problem:

`urthermore, this build has been executed 14 times and the only log output recorded in the LTS bucket is from the final container of the last stage of the first execution of the build.`

But I'll try testing and see if I can catch anything.
