### ISSUE TITLE
The step Validate Git fails on the master build of a fresh jx boot dev environment

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#4943]
### Summary 

After successfully creating a fresh jx boot cluster in GitOps mode, the dev environment will execute its master branch build.
This build fails on the step `Validate Git` due to: 

`error: No Git user.name is defined. Please run the command: git config --global --add user.name "MyName"` 

### Steps to reproduce the behavior
Create a new cluster, add an app or quickstart, see the master build of the dev environment.

### Expected behavior
The step shouldn't fail. 

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by cagiti** [comment]
@dgozalo is this only an issue for clusters created with `gitops: true`?

**Comment by dgozalo** [comment]
@cagiti yes, only in GitOps mode we execute the dev environment pipelines. I'll update the initial description.

**Comment by macox** [comment]
Now that the possibility of failure has been removed it would be good to configure the correct git user (bot user) when the pipeline is run in cluster, and not default to jenkins-x-bot

**Comment by garethjevans** [comment]
Is this still the case @macox? am hoping that once the fix has propagated through the builders and we get jenkins-x-versions releasing properly that this will go away
