### ISSUE TITLE
We are creating webhooks before the pipelinerunner service is active on a boot installation

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#4944]
### Summary 
On a fresh jx boot installation, we are creating a the webhooks on our environment repositories before the `pipelinerunner` service starts running.

When we make the first Pul Request with updates on the dev environment repository, the service is still not running and the first two events sent by GitHub fail to reach us.

### Steps to reproduce the behavior

Create a new cluster with jx boot, check that the dev environment repository has been created.

### Expected behavior

The first Pull Request of the dev environment should be automatically merged after passing the  Pull Request job.

### Actual behavior

As github sends events to the webhook's endpoint before `pipelinerunner`is active, the first build never runs.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by pmuir** [comment]
Workaround: run `/retest` on the PR after `jx boot` is complete

**Comment by dgozalo** [comment]
I'm closing this. We are no longer creating the first configuration PR and we are directly pushing to the repo.
