### ISSUE TITLE
Applications does not seem to be completely removed from jenkins-x/prow

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#4958]
### Summary 

Remove an application with `jx delete application <app-name>`. After the application was successfully removed create a PR with some changes for this application. Jenkins X/prow still keep adding the labels and building the application.

### Steps to reproduce the behavior

Issue was found on boot.

### Expected behavior

The application should be completely removed from Jenkins X. Jenkins X/prow shouldn't keep building the application whenever a pull request is opened into that application.

### Actual behavior

Jenkins X/prow keeps building that application.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by pmuir** [comment]
It looks as though it managed to:

1) delete the source repository
2) delete the pre and post-submits from the prow config
3) not delete the tide config (hence the messages still being posted)

further, there is no gitops support, but that I will raise a RFE for.
