### ISSUE TITLE
Define deprecation and experimental policy for features

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4960]
### Problem

It's important to flag features as, in some way, experimental so that people using Jenkins X have a realistic expectation of the level of completeness and stability of the feature.

We also should flag deprecated features clearly so that users can know they need to plan to move off them at some point

### Requirements

* Experimental and deprecated features need to be really obvious to users, this is particularly challenging as we don't have a graphical UI. This means that, for example, just putting this info a matrix on the website, might not be sufficient.

* Consistency matters - if you adopt a non-experimental feature you should be able to expect a certain level of quality

**Comment by jstrachan** [comment]
we can annotate cobra commands btw https://github.com/spf13/cobra/blob/master/command.go#L80-L82 we could add a quality annotation with alpha/beta/ga or something - then let folks filter by quality?

**Comment by jstrachan** [comment]
guess we need to decide what the names are; e.g. `alpha, beta, ga, deprecated`?

**Comment by jstrachan** [comment]
once we have annotations for alpha/beta/ga/deprecated (even partial annotations) we should be able to easily filter out commands from `jx help` based on the profile folks have defined. Then we can default to GA + hide experimental / preview stuff.

**Comment by jstrachan** [comment]
folks can then switch the profile via: https://jenkins-x.io/commands/jx_profile/

**Comment by jstrachan** [comment]
might be nice to try annotate commands as being tested in the BDD tests + on different platforms etc so folks can filter on features tested on a certain platform etc

**Comment by warrenbailey** [comment]
Happy to have a look at this

**Comment by dennisnewel** [comment]
re. naming, i've tried to come up with naming and definition as part of the docs work i've been looking at (https://github.com/jenkins-x/jx/issues/5157) and have been thinking Experimental, Stable, Production, and Deprecated. I don't mind going with alpha, beta, ga, deprecated though i feel alpha/beta/ga can be a bit ambiguous; not everyone views Beta as the same thing :)  

As for definitions, here's what i've been thinking:

Deprecated - "This will be removed at a later date. Don't use"
Experimental - "Initial version of a feature. Likely to change in terms of usage, implementation, scope, etc. Documentation is probably light, and it might not have been fully tested in all scenarios. 
Use at your own risk"
Stable - "Stabilized feature, but could still have some rough edges. Minimal documentation is available, as well as automated tests"
Production - "Stable, well documented feature that does what it says on the box. Safe to use in production environments"

**Comment by pmuir** [comment]
The differentiation between Stable and Production seems artificial to me @dennisnewel

**Comment by dennisnewel** [comment]
Maybe that could have been written more clearly. I was thinking that "stable" is feature complete, but likely not fully documented or fully covered by automated tests. 
A production level feature should have full documentation and should be well covered by automated tests.

**Comment by dennisnewel** [comment]
added suggestion in the form of a PR to the docs :) expecting a lot of feedback!

**Comment by dennisnewel** [comment]
created a google sheet to keep track of each of the features and where we've updated documentation: https://docs.google.com/spreadsheets/d/13iBctKqSWKoa0_zGAXkiVUWkTJyFz3cTsKzGRoUsyTQ/edit#gid=0. The idea behind this sheet is mostly just for data gathering; the docs should be updated asap and serve as the single source of truth
