### ISSUE TITLE
Ingress failure when executing the Master pipeline on a boot environment repository

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#4965]
### Summary 

After executing a PullRequest pipeline on an environment repository created by Boot on GitOps mode, getting it merged and starting the master pipeline, I get an error in the `Helm Cluster Values` step.

``` 
Showing logs for build dgozalo/environment-shakerboulder-dev/master #1 promotion stage release and container step-helm-cluster-values

Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: services "jxing-nginx-ingress-controller" not found
``` 

### Steps to reproduce the behavior
Create a cluster with boot, add an app or a quickstart, wait for the master pipeline of the environment repository to start.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by cagiti** [comment]
@dgozalo: is this a gitops cluster? thanks

**Comment by dgozalo** [comment]
@cagiti Yes, I'll update the description

**Comment by cagiti** [comment]
Thanks

**Comment by cagiti** [comment]
@dgozalo : just following your steps to recreate and I don't get an error at present. However, I'm wondering whether you've merged the dgozalo/environment-shakerboulder-dev PR that gets created during install?

**Comment by dgozalo** [comment]
@cagiti Yes, that's one of the issues with cluster creation, I merged the first PR manually.

There's been a new release of the versions stream since I tried this, maybe it got fixed in the newer builders?

**Comment by cagiti** [comment]
possibly, I'm about to try building the dev environment repo now

**Comment by cagiti** [comment]
The PR build failed with:
```
Showing logs for build cagiti-org/environment-coops-test-dev/pr-1 #1 promotion-build stage release and container step-helm-build
rm -rf charts
rm -rf requirements.lock
helm init --client-only
Creating /builder/home/.helm 
Creating /builder/home/.helm/repository 
Creating /builder/home/.helm/repository/cache 
Creating /builder/home/.helm/repository/local 
Creating /builder/home/.helm/plugins 
Creating /builder/home/.helm/starters 
Creating /builder/home/.helm/cache/archive 
Creating /builder/home/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /builder/home/.helm.
Not installing Tiller due to 'client-only' flag having been set
helm repo add jenkins-x http://chartmuseum.jenkins-x.io
"jenkins-x" has been added to your repositories
helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
helm repo add stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories
jx step helm build --boot --provider-values-dir=../kubeProviders
Error: unknown flag: --boot
```

**Comment by cagiti** [comment]
possibly related to #4984

**Comment by cagiti** [comment]
Upon trying recreating this issue I ended up getting #4943

**Comment by pmuir** [comment]
@dgozalo can you see if this is still a problem please?

**Comment by deanesmith** [comment]
@dgozalo to verify

**Comment by dgozalo** [comment]
I verified and it's working properly now. I'm closing it.
