### ISSUE TITLE
jx boot duplicates the secrets stored in vault in kubernetes secrets

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#4967]
### Summary 

jx boot duplicates the secrets stored in vault in Kubernetes secrets, the same like the old installer. Some of the secrets stored in vault such as basic auth, pipeline token should not be duplicated in k8s secrets.  

`$kubectl get secrets -n jx`
```
x-basic-auth                              Opaque                                1         4m34s
jx-pipeline-git-github-github              Opaque                                2         4m20s
knative-git-user-pass                      kubernetes.io/basic-auth              2         4m24s
```
### Expected behavior

Do not duplicate secrets in k8s secrets when vault is enabled. Use Vault when it is enabled.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by ccojocar** [comment]
We need to check if it is possible to reduce the duplication of basic auth secret. The pipeline secret issue is handled by #5114.

**Comment by deanesmith** [comment]
Tasks:
- Research where secret (jx-basic-auth) is used
- Modify cli to use Vault when enabled
- Do not create the secret when Vault is enabled
- Add test if possible

**Comment by ccojocar** [comment]
This is partially fixed. There still some secrets for prow and lighthouse which are duplicated in secrets when vault is enabled.
