### ISSUE TITLE
Improve jx uninstall 

### ISSUE THREAD

**Issue by zeusro** [jenkins-x/jx#4969]
### Steps to reproduce the behavior

 jx uninstall 

### Expected behavior

clean the resource 

### Actual behavior

kubectl delete namespace xx

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.517
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Operating system / Environment

I still remember, I ran the command ` jx uninstall `  on 2019-07-19 16:54 on a namespace which we used for produce.

It made a disaster and took our team for over 6 hours to repair .

the ` jx uninstall ` is terrible ,it delte the namespace  directly .

I wish the ` jx uninstall `  command will be improved,add the alert message ,tell the user that it will rm the  namespace or something.

**Comment by warrenbailey** [comment]
The `jx uninstall` command will attempt to remove all jx related components, secrets, configs and **namespaces**  including any environment specific namespaces. This is as intended, however I take your point that it should be more informative as to what it will do.

I'll update the command with some warnings and confirmations regarding the namespace deletion.

**Comment by zeusro** [comment]
> The `jx uninstall` command will attempt to remove all jx related components, secrets, configs and **namespaces** including any environment specific namespaces. This is as intended, however I take your point that it should be more informative as to what it will do.
> 
> I'll update the command with some warnings and confirmations regarding the namespace deletion.

OK,thank you for your work !
