### ISSUE TITLE
Define interface for meta pipeline generation

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#4971]
In order to avoid triggering the meta pipeline generation via `StepCreatePipelineOptions.Run` we want to extract an interface, eg `MetaPipelineGenerator` which defines all functions needed to create the meta pipeline. There already exist already `CreateMetaPipelineCRDs(params CRDCreationParameters)` in metapipeline.go, but there is still some pre-processing `step_create_meta_pipeline`.

The new interface should allow to create the meta pipeline by just passing the required parameters and it should be independent from from `jx step create pipeline` .  `jx step create pipeline` will itself call this new interface. Another potential client is Lighthouse - see https://github.com/jenkins-x/lighthouse/issues/61

This issue includes:

* Creation of interface
* Definition of required inputs 
* (optional) Extracting metapipline code/interface into a top level _metapipeline_ package in order to be able to easier consume meta pipeline as a dependency

**Comment by deanesmith** [comment]
Approved but waiting for production cluster overhaul.
