### ISSUE TITLE
PipelineActivity GC too aggressive

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#4974]
### Summary 

The garbage collection of PipelineActivities it is too aggressive, it clean up all the builds for existing pipelines. At least it should leave the last one around. 

A long term strategy for historical builds should be provided as well. 

### Steps to reproduce the behavior
default behaviour

### Expected behavior
at least the last PipelineActivity for a pipeline should be available at all times

### Actual behavior
all pipeline activities are cleaned up. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
So things are a _bit_ smarter now - #5293 had been around for a while, resulting in, by default, release pipelines only being kept for 2 days and PR pipelines being kept for 30 days, the reverse of what was intended. I just fixed that today, so once that's in `jenkins-x-versions` and you upgrade the platform, the five most recent release pipelines for a project will be kept for thirty days. If you set `--release-age=180d` or something, then the five most recent release pipelines for a project would be kept for 180 days, etc.
