### ISSUE TITLE
Configure the path that `jx preview` uses to check that the app is up and running

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#4979]
### Summary 

Add an arg to jx preview like `--check-path <>` to allow the deployment check to test to see if that url is up.

For spring boot apps this could be set to an actuator url

**Comment by garethjevans** [comment]
would be nice to be able to configure the expected response code too

**Comment by CarpathianUA** [comment]
+1

**Comment by aweis89** [comment]
+1
