### ISSUE TITLE
'ERROR: validation error: Parameter 'registry_name' must have length greater than 5.'

### ISSUE THREAD

**Issue by th3w4y** [jenkins-x/jx#4981]
### Summary 
jx install fails to create acr on pre-existing AKS cluster with cluster name < 5 letters

### Steps to reproduce the behavior
jx install on existing AKS cluster with 3 letters long rg-name and 3 letters long cluster-name
### Expected behavior
success
### Actual behavior
Failed to create ACR k8s in resource group k8s
error: configuring the docker registry: configure cloud provider docker registry: getting registry configuration from Azure: failed to run 'az acr create -g k8s -n k8s --sku Standard --admin-enabled --query id -o tsv' command in directory '', output: 'ERROR: validation error: Parameter 'registry_name' must have length greater than 5.'
✘-1 ~ 
### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 2.0.521
Kubernetes cluster v1.14.3
kubectl            v1.15.1
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G87
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

AKS

### Operating system / Environment
MacOS

**Comment by th3w4y** [comment]
Workaround mentioned at https://github.com/jenkins-x/jx/issues/2884#issuecomment-487386615 is valid
```
jx install --provider aks --docker-registry=nameofacr.azurecr.io
```

**Comment by mb-lyrical** [comment]
Isn't this a restriction on the Azure side  and nothing really JX can do about it?

**Comment by th3w4y** [comment]
@mb-lyrical as mentioned "existing AKS cluster with 3 letters long rg-name and 3 letters long cluster-name" thus the restriction is not on Azure side.
