### ISSUE TITLE
jx upgrade addons downgrades vault-operator

### ISSUE THREAD

**Issue by asdwsda** [jenkins-x/jx#4988]
### Summary 
Calling `jx upgrade addons` downgrades vault-operator from 0.4.16 to version 0.2.1, which is no longer available.

### Steps to reproduce the behavior
1. `jx create addon vault-operator`
```
$ kubectl get pod vault-operator-589647bfd4-rtkzc -o "jsonpath={$.spec.containers[0].image}"
banzaicloud/vault-operator:0.4.16
```
2. `jx upgrade addons`
```
$ kubectl get pod vault-operator-8477f4cf4b-sz7fc
NAME                              READY   STATUS             RESTARTS   AGE
vault-operator-8477f4cf4b-sz7fc   0/1     ImagePullBackOff   0          73m

$ kubectl get pod vault-operator-8477f4cf4b-sz7fc -o "jsonpath={$.spec.containers[0].image}"
banzaicloud/vault-operator:0.2.1
```

### Expected behavior

vault-operator should be upgraded

### Actual behavior

vault-operator downgraded to `banzaicloud/vault-operator:0.2.1`

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.554
jenkins x platform 2.0.905
Kubernetes cluster v1.14.2
kubectl            v1.15.1
helm client        Client: v2.13.0+g79d0794
git                git version 2.22.0
Operating System   Mac OS X 10.14.6 build 18G84
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

[Banzai Cloud PKE](https://github.com/banzaicloud/pke) cluster

### Operating system / Environment

Mac OS X 10.14.6 build 18G84

**Comment by warrenbailey** [comment]
I've confirm on version 2.0.561. Interestingly it doesn't delete the old pod, just creates a new one with the old version.

**Comment by warrenbailey** [comment]
It seems that the `jx create add on vault-operator` command overrides the docker version of the vault-operator defined in the chart, hence why you get the 0.4.16 version (which is the correct version)

However the `jx upgrade addon` command doesn't do that, so it gets the version defined in the chart, in this case 0.2.1.

It also looks like the vault-operator chart wasn't releasing correctly, I've corrected that and updated to the latest versions. 

I should then be able to update jenkins-x-versions to the correct version of the vault operator.

**Comment by warrenbailey** [comment]
https://github.com/jenkins-x/jenkins-x-versions/pull/396

**Comment by warrenbailey** [comment]
That seems to fix the problem, I just want to look into whether we can remove the overriding of the docker image version now. Otherwise we may get this issue again in the future.
