### ISSUE TITLE
How to use external Chartmuseum/Helm Repository

### ISSUE THREAD

**Issue by InsOpDe** [jenkins-x/jx#4994]
### Summary 
I would like to outsource the helm repository to an external resource like Azure's Container Registry but can't find any install-parameter for it.

Because at the moment I receive
```bash
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.553
jenkins x platform 2.0.905
Kubernetes cluster v1.12.8
kubectl            v1.15.1
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS

```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by madhu1992blue** [comment]
In jx-requirements.yml, you can add a key called "chartRepository: <External Chart Museum Repo>" under "cluster".
`cluster: 
    chartRepository: <external chart museum url>
`

**Comment by deanesmith** [comment]
Hi @InsOpDe, was the solution identified by @madhu1992blue sufficient?  If so, could you please close the issue.

**Comment by InsOpDe** [comment]
Sorry we decided not to use jx in production yet
