### ISSUE TITLE
Add label to Tekton CRDs to differentiate between meta and execution pipeline

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5007]
Atm there is no clear way to differentiate between the CRDs created for the meta pipeline vs the CRDs creates for the execution pipeline. This makes some part of the code, for example getting the combined logs of meta and execution pipeline, tricky to write. To mitigate this, we could add an additional label to the various Tekton resources created to be able to explicitly differentiate between meta and execution pipeline CRDs.

See also https://github.com/jenkins-x/jx/pull/5001/files#r311431930

**Comment by daveconde** [comment]
cc @cagiti

**Comment by hferentschik** [comment]
Labels for distinguishing between meta- and buildpipeline have been introduced as part of #5455
