### ISSUE TITLE
create spring boot application issue

### ISSUE THREAD

**Issue by zhouzhengde** [jenkins-x/jx#501]
Hi,
When I create spring boot project with use 'jx create spring -d web -d actuator' command, the console occur an error!

error: no JENKINS_URL environment variable is set nor could a Jenkins service be found in the current namespace!

My env:
localhost:jx-demo bond$ jx version
NAME           VERSION
jx             1.1.29
Kubernetes     v1.9.4
Helm Client    v2.8.2+ga802316
Helm Server    v2.8.2+ga802316
Kubectl Client v1.9.6
Git            git version 2.10.1 (Apple Git-78)

**Comment by jstrachan** [comment]
@zhouzhengde you had installed Jenkins X on that kubernetes cluster right? As James said above, I wonder if you were in the wrong namespace? I wonder what the output of this command was:
```
jx ns -b
```

**Comment by zhouzhengde** [comment]
Tonight, I will check. tks




| |
zzdjavajob
邮箱：zzdjavajob@163.com
|

签名由 网易邮箱大师 定制

On 03/27/2018 16:52, James Strachan wrote:

@zhouzhengde you had installed Jenkins X on that kubernetes cluster right? As James said above, I wonder if you were in the wrong namespace? I wonder what the output of this command was:

jx ns -b

**Comment by jstrachan** [comment]
this looks a similar issue to #477 though the causes may be different ;)

**Comment by zhouzhengde** [comment]
Use 'kubectl get po --all-namespaces' to show namespace, but don't see any about 'jx' namespace. Before, I don't use 'jx create cluster minikube' to create cluster, now I use 'jx create cluster minikube' to recreate cluster can fix the problem, thanks for your help.
