### ISSUE TITLE
Cannot access jenkins X on browser after installing on GKE using jx install a

### ISSUE THREAD

**Issue by chiragthaker** [jenkins-x/jx#5012]
At the end of the installation it just stucks at this line 

waiting up to 0s for the Jenkins server to be healthy at URL http://jenkins.jx.url/login

all pods are running ok it seems 

jenkins-956c58866-4w5b9                        1/1     Running     0          97m
jenkins-x-chartmuseum-75d45b6d7f-kvvzz         1/1     Running     0          97m
jenkins-x-controllerrole-d64cbd686-lq58r       1/1     Running     0          97m
jenkins-x-controllerteam-6c4cb5854d-xb4hc      1/1     Running     0          97m
jenkins-x-controllerworkflow-675c7bfb4-c4vrd   1/1     Running     0          97m
jenkins-x-docker-registry-6d555974c7-2pwtr     1/1     Running     0          97m
jenkins-x-gcactivities-1565179200-lf5rc        0/1     Completed   0          50m
jenkins-x-gcactivities-1565181000-kpwd6        0/1     Completed   0          20m
jenkins-x-gcpods-1565179200-25kbh              0/1     Completed   0          50m
jenkins-x-gcpods-1565181000-sg6b5              0/1     Completed   0          20m
jenkins-x-gcpreviews-1565179200-4jj9q          0/1     Completed   0          50m
jenkins-x-heapster-7777b7d7d8-dxfwr            2/2     Running     0          95m
jenkins-x-nexus-6ccd45c57c-xfj2b               1/1     Running     0          97m

need to understand the exact cause as we need to fix it.

**Comment by michalchochol** [comment]
exactly the same issue during installation on custom kubernetes cluster on AWS
----
Jenkins X deployments ready in namespace jx
Configuring the TeamSettings for ImportMode Jenkinsfile
Configure Jenkins API Token
waiting up to 0s for the Jenkins server to be healty at URL http://jenkins.jx.223.255.255.255.nip.io/login
----

All pods looks good:

NAME                                            READY   STATUS      RESTARTS   AGE
jenkins-99cfc9887-4vsg4                         1/1     Running     0          3d10h
jenkins-x-chartmuseum-75d45b6d7f-qnqvn          1/1     Running     0          3d10h
jenkins-x-controllerrole-79c8cd9579-hw6zq       1/1     Running     0          3d10h
jenkins-x-controllerteam-6cb46c68f5-kzpzr       1/1     Running     0          3d10h
jenkins-x-controllerworkflow-796cb6bbb9-xbf9w   1/1     Running     0          3d10h
jenkins-x-docker-registry-6d555974c7-n7npk      1/1     Running     0          3d10h
jenkins-x-gcactivities-1565600400-rzlhn         0/1     Completed   0          42m
jenkins-x-gcactivities-1565602200-gdq9w         0/1     Completed   0          12m
jenkins-x-gcpods-1565600400-shphq               0/1     Completed   0          42m
jenkins-x-gcpods-1565602200-llxxb               0/1     Completed   0          12m
jenkins-x-gcpreviews-1565600400-kjcwk           0/1     Completed   0          42m
jenkins-x-heapster-5877d8c876-ftk4j             2/2     Running     0          3d10h
jenkins-x-nexus-6ccd45c57c-44zdq                1/1     Running     0          3d10h

**Comment by david-ecc** [comment]
Same problem here.

**Comment by vfarcic** [comment]
I had the same problem. I'm running static Jenkins X in EKS and the issue does not seem to be limited to Jenkins. I also couldn't access ChartMuseum from outside the cluster.

In my case, it turned out that the issue was with eksctl. Once I updated it to the latest, everything started working correctly.

I'm not sure whether that's your case @chiragthaker ...

**Comment by shencan** [comment]
I had the same problem, the Jenkins server  port is 8080, why check 80 port? i request http://domain:8080/login can open jenkins

**Comment by shencan** [comment]
kubectl edit svc jenkins and change `port: 8080` to `port: 80` can fix

**Comment by ivnet** [comment]
> exactly the same issue during installation on custom kubernetes cluster on AWS
> 
> Jenkins X deployments ready in namespace jx
> Configuring the TeamSettings for ImportMode Jenkinsfile
> Configure Jenkins API Token
> waiting up to 0s for the Jenkins server to be healty at URL http://jenkins.jx.223.255.255.255.nip.io/login
> 
> All pods looks good:
> 
> NAME READY STATUS RESTARTS AGE
> jenkins-99cfc9887-4vsg4 1/1 Running 0 3d10h
> jenkins-x-chartmuseum-75d45b6d7f-qnqvn 1/1 Running 0 3d10h
> jenkins-x-controllerrole-79c8cd9579-hw6zq 1/1 Running 0 3d10h
> jenkins-x-controllerteam-6cb46c68f5-kzpzr 1/1 Running 0 3d10h
> jenkins-x-controllerworkflow-796cb6bbb9-xbf9w 1/1 Running 0 3d10h
> jenkins-x-docker-registry-6d555974c7-n7npk 1/1 Running 0 3d10h
> jenkins-x-gcactivities-1565600400-rzlhn 0/1 Completed 0 42m
> jenkins-x-gcactivities-1565602200-gdq9w 0/1 Completed 0 12m
> jenkins-x-gcpods-1565600400-shphq 0/1 Completed 0 42m
> jenkins-x-gcpods-1565602200-llxxb 0/1 Completed 0 12m
> jenkins-x-gcpreviews-1565600400-kjcwk 0/1 Completed 0 42m
> jenkins-x-heapster-5877d8c876-ftk4j 2/2 Running 0 3d10h
> jenkins-x-nexus-6ccd45c57c-44zdq 1/1 Running 0 3d10h


For my custom AWS setup, first time installation is happening properly. When i uninstall and then install again, this issue is coming up. 
Any solution?

**Comment by prashankprince** [comment]
> exactly the same issue during installation on custom kubernetes cluster on AWS
> 
> Jenkins X deployments ready in namespace jx
> Configuring the TeamSettings for ImportMode Jenkinsfile
> Configure Jenkins API Token
> waiting up to 0s for the Jenkins server to be healty at URL http://jenkins.jx.223.255.255.255.nip.io/login
> 
> All pods looks good:
> 
> NAME READY STATUS RESTARTS AGE
> jenkins-99cfc9887-4vsg4 1/1 Running 0 3d10h
> jenkins-x-chartmuseum-75d45b6d7f-qnqvn 1/1 Running 0 3d10h
> jenkins-x-controllerrole-79c8cd9579-hw6zq 1/1 Running 0 3d10h
> jenkins-x-controllerteam-6cb46c68f5-kzpzr 1/1 Running 0 3d10h
> jenkins-x-controllerworkflow-796cb6bbb9-xbf9w 1/1 Running 0 3d10h
> jenkins-x-docker-registry-6d555974c7-n7npk 1/1 Running 0 3d10h
> jenkins-x-gcactivities-1565600400-rzlhn 0/1 Completed 0 42m
> jenkins-x-gcactivities-1565602200-gdq9w 0/1 Completed 0 12m
> jenkins-x-gcpods-1565600400-shphq 0/1 Completed 0 42m
> jenkins-x-gcpods-1565602200-llxxb 0/1 Completed 0 12m
> jenkins-x-gcpreviews-1565600400-kjcwk 0/1 Completed 0 42m
> jenkins-x-heapster-5877d8c876-ftk4j 2/2 Running 0 3d10h
> jenkins-x-nexus-6ccd45c57c-44zdq 1/1 Running 0 3d10h

For my custom AWS setup, first time installation is happening properly. When i uninstall and then install again, this issue is coming up.
Any solution?
