### ISSUE TITLE
Add brew install in README

### ISSUE THREAD

**Issue by saturnism** [jenkins-x/jx#502]
For some reason, I ended up on instruction to download `jx` binary and put in the `PATH`, and was linked to the GitHub releases page. However, I later found the [Getting Started](http://jenkins-x.io/getting-started/install/) page that has brew instruction.

**Comment by michaelneale** [comment]
Is there somewhere that it says that - https://github.com/jenkins-x/jx#installing just has a link to the brew way

**Comment by jstrachan** [comment]
@saturnism I wonder if you saw an old README - I can't find the download jx docs any more? 

We've instructions on installing on the releases page too https://github.com/jenkins-x/jx/releases
