### ISSUE TITLE
jx boot gitops dev env OWNERS file contains jx developers

### ISSUE THREAD

**Issue by macox** [jenkins-x/jx#5035]
### Summary 

After creating a fresh jx boot cluster in GitOps mode, the dev environment repo is created but contains an OWNERS file that contains the jx developers (I assume it is copied from the jenkins-x-boot-config) repo.  This results in these jx devs having a high prow privileges on other peoples dev environments.

### Steps to reproduce the behavior

Create a new cluster using gitops. The dev environment repo is created with pre populated OWNERS file.

### Expected behavior

Maybe instead of copying the OWNERS file we should create one, which contains only the bot user that is specified during the `jx boot` process.

**Comment by abayer** [comment]
Resolving this as a duplicate of #6457 since I'm technically fixing it under that issue.
