### ISSUE TITLE
Support upgrades when using jx boot

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#5036]
### Summary 

Since the introduction of `jx boot`, applying upgrades is a very manual process. A simple upgrade process to apply upgrades to a Jenkins X install that was created using `jx boot` is required.

### Problems: 

1) `jx upgrade platform` does not currently work with `jx boot` based installs
2) Applying updates to boot config to a dev environment created via `jx boot` requires manual merging from the upstream boot config repository
3) It is not obvious to users that upgrades are available 
4) The upgrade process is not clearly documented
5) There is no way to do a data & schema upgrade
6) Secrets are not handled (see #5058)
7) `jx upgrade platform` does not work with gitops

### User Flow:

1) A new version of a Jenkins X component is released to the version stream.
2) The Jenkins X Administrator is notified of the update by a pull request with the updates being created against the development environment git repository used to manage Jenkins X.
3) The user merges the pull request to accept the updates.
4) The update is automatically applied to the cluster.

### Acceptance Criteria:

1) After a change is released to a version stream a PR is opened containing updates against the Jenkins X dev environment for the user
2) The pull request should contain a change log, release notes of proposed changes including a dependency matrix that would be applied
3) The patch set that is generated against the boot repo should be as small as possible and not contain Jenkins X implementation details 
4) The upgrade process should be optional
5) The upgrade process only needs to work for gitops based installs
6) It should be possible for the user to specify how often to check for updates
7) It should be possible for the user to opt (in/out) to auto apply updates
8) A full audit log of changes should be provided to the user after the upgrade has completed
9) The solution should be pull rather than push
10) The upgrade must not cause any downtime to the user's Jenkins X install

### Proposed Solution:

TODO

**Comment by ccojocar** [comment]
This is also related to this https://github.com/jenkins-x/jx/issues/5058

**Comment by macox** [comment]
Reducing the scope of the acceptance criteria of this ticket by moving the following to subsequent work:

- A full audit log of changes should be provided to the user after the upgrade has completed
- The upgrade must not cause any downtime to the user's Jenkins X install
- The patch set that is generated against the boot repo should be as small as possible and not 
   contain Jenkins X implementation details.
- It should be possible for the user to opt (in/out) to auto apply updates

**Comment by macox** [comment]
needs #5235

**Comment by macox** [comment]
needs #5236

**Comment by macox** [comment]
needs cloudbees/cloudbees-jenkins-x-distro#9

**Comment by macox** [comment]
needs #5329

**Comment by macox** [comment]
needs #5330

**Comment by macox** [comment]
needs #5332
