### ISSUE TITLE
Provide short-term fix/workaround for pipeline bot token

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#5037]
### Summary 
A fix/workaround for https://github.com/jenkins-x/jx/issues/4196 is needed
### Steps to reproduce the behavior
https://github.com/jenkins-x/jx/issues/4196

**Comment by ccojocar** [comment]
This will require fist a resolution for https://github.com/jenkins-x/jx/issues/5114 in order to be able to separate the pipeline secret from local secret.

**Comment by daveconde** [comment]
Closing as captured in #5114
