### ISSUE TITLE
Provide a way for developers to develop against Jenkins-X using external DNS

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5038]
To test non nip.io scenarios we need a way for developers to setup a test environment.

**Comment by hferentschik** [comment]
This is required to investigate issues like #4865

**Comment by pmuir** [comment]
@hferentschik could you outline the user experience you would like to see here. I can make a guess but...

**Comment by hferentschik** [comment]
> could you outline the user experience you would like to see here. I can make a guess but...

Sure.

I think the issue is twofold:

1. How do we get hold of a domain? Do we have some shared development domain under which we create subdomains, should I create a new domain, do I even need to use my own private domain. 

    Related to this issue, it would be nice to have a couple of say gcloud commands I can run to create such a (sub)domain. 

1.  Document what else in terms of configuration is needed to make use of this domain when booting

**Comment by pmuir** [comment]
@hferentschik preview of docs available at http://jx-docs.jx-jenkins-x-jx-docs-pr-1832.infra.jrawlings.co.uk/contribute/contribute_dns/ - can you please review?

**Comment by pmuir** [comment]
@hferentschik ok, docs are up at https://jenkins-x.io/contribute/contribute_dns/ - if there are changes required let me know, otherwise can you close the issue?

**Comment by hferentschik** [comment]
LGTM
