### ISSUE TITLE
Cannot create vault

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#5039]
### Summary 

When running `jx boot`, the process fails when trying to create a Vault bucket.

The last lines of the `jx boot` output:

```
...
Downloading service account key
Error creating bucket: Creating gs://jx-vault-jx-rocks-bucket/...
ServiceException: 409 Bucket jx-vault-jx-rocks-bucket already exists., failed to run 'gsutil mb -l us-east1 -p devops-26 gs://jx-vault-jx-rocks-bucket' command in directory '', output: 'Creating gs://jx-vault-jx-rocks-bucket/...
ServiceException: 409 Bucket jx-vault-jx-rocks-bucket already exists.'
error: creating vault: creating Vault GCS data bucket: creating Vault GCS bucket: failed to run 'gsutil mb -l us-east1 -p devops-26 gs://jx-vault-jx-rocks-bucket' command in directory '', output: 'Creating gs://jx-vault-jx-rocks-bucket/...
ServiceException: 409 Bucket jx-vault-jx-rocks-bucket already exists.'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault' command in directory 'systems/vault', output: ''
```

I tried creating the storage manually by executing `gsutil mb -l us-east1 -p devops-26 gs://jx-vault-jx-rocks-bucket` and that failed as well with the following message.

```
Creating gs://jx-vault-jx-rocks-bucket/...
ServiceException: 409 Bucket jx-vault-jx-rocks-bucket already exists.
```

The strange thing is that the bucket cannot be found in my GCP account.

```bash
gsutil ls
```

The output:

```
gs://jx-rocks-logs-9215a5c9-1c6a-4314-b6c0-f92f6c691cbb/
gs://jx-rocks-reports-36046064-c9d7-47f8-899e-ae691ee5d3d8/
gs://jx-rocks-repository-5b185a66-9086-4879-a5d0-c9a03b66a9f/
```

Now, I understand that is a problem with GCP. However, the problem would not exist in the first place if vault storage is created with a unique name or if there would be an option to specify storage just as with other storages (e.g., logs).

### Expected behavior

Vault storage uses a unique name or allows us to specify it.

### Actual behavior

Vault storage is using a hard-coded pattern.

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               2.0.574
git              2.20.1 (Apple Git-117)
Operating System Mac OS X 10.14.6 build 18G87
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by ccojocar** [comment]
@vfarcic is this still an issue? It seems to be fixed? Can we close it?

**Comment by vfarcic** [comment]
It works
