### ISSUE TITLE
allow a docker registry to be configured at a Team level

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#504]
e.g. so a team may wish to use a private container registry somewhere or one provided by Google/AWS/Azure.

It might be nice to parameterise the docker registry with an env var inside the Jenkinsfiles; then it'd be easy to switch the docker registry.

Maybe we can store at a team level the docker registry to use? Then it can be defaulted in to any project imported/generated in that team?

**Comment by grifonas** [comment]
Hi,
I hope it's OK to ask about this here. Considering this is where the progress's going to be tracked. 

Could you please clarify where the env. var. `JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST` is set?
I need this in order to replace the value with my private registry.

I know I can simply set the value in the Jenkinsfile, and Bob's your uncle, but I was hoping to understand the default setup first.
Thank you!

**Comment by jstrachan** [comment]
kubernetes generates environment variables so you can access the IP and port of each `Service`.
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

so `JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST` just refers to the `jenkins-x-docker-registry` kubernetes Service.

Am thinking we should maybe refactor slightly the `Jenkinsfiles` to use a single environment variable for the docker registry expression; so its easy to replace it with another `Service` or a separate URL completely

**Comment by grifonas** [comment]
Thanks, @jstrachan. Very silly of me not to have guessed that it's a K8S variable. Makes sense. 
Thank you!

**Comment by rawlingsj** [comment]
yeah - we had something similar in fabric8 which made it easy to configure external docker registries.  I wonder if a jx step would work, which could write a configfile that the pipeline then runs `sh 'source jx-pipeline-config.yaml'`  to set env vars?  Not sure if that will work but I don't think the jx step could set env vars in go for the other steps to use?  

Or maybe there's a better way?

**Comment by Markus-ipse** [comment]
In the latest[ release notes](https://github.com/jenkins-x/jx/releases/tag/v1.3.1032) there's bug fix mentioning "allow the docker registry org to be specified at a team level". Does this mean this issue can be closed, and if so, is there any documentation on how to set the docker registry on a team level?

**Comment by jstrachan** [comment]
this issue is now fixed with `jx boot` as we store the docker registry inside the requirements YAML in the team in `cluster.registry`
