### ISSUE TITLE
Meta pipeline helm build command not present within builder-jx jx version

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#5040]
### Summary 
The helm build command fails in the PR build of the dev environment when using a GitOps cluster setup using `jx boot`. 

This predominantly isn't as big an impact to a user executing jx locally, as they have the option to upgrade the cli (however not ideal). But when a command is added to the meta-pipeline in the `jenkins-x-boot-config` it's difficult to verify whether the version of jx or the version of jx within the builders image.

### Steps to reproduce the behavior
Create cluster and install `jx` using `jx boot` with gitops enabled , this will create a dev environment repository. Once the installation is complete, navigate to the PR on the dev environment which should have been created. Execute the promotion build test by adding the following comment to the pull request:
```
/test this
```

### Expected behaviour
The build succeeds 

### Actual behaviour
The build fails due to a missing option on a command. Error is:
```
WARNING: pod cagiti-org-environment-coops-te-kfrlf-1-release-kqjt4-pod-874aa4 has failed
Showing logs for build cagiti-org/environment-coops-test-dev/pr-1 #1 promotion-build stage release and container step-helm-build
rm -rf charts
rm -rf requirements.lock
helm init --client-only
Creating /builder/home/.helm 
Creating /builder/home/.helm/repository 
Creating /builder/home/.helm/repository/cache 
Creating /builder/home/.helm/repository/local 
Creating /builder/home/.helm/plugins 
Creating /builder/home/.helm/starters 
Creating /builder/home/.helm/cache/archive 
Creating /builder/home/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /builder/home/.helm.
Not installing Tiller due to 'client-only' flag having been set
helm repo add jenkins-x http://chartmuseum.jenkins-x.io
"jenkins-x" has been added to your repositories
helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
helm repo add stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories
jx step helm build --boot --provider-values-dir=../kubeProviders
Error: unknown flag: --boot


Aliases:
build, 
Examples:
  # builds the helm chart in the env directory
  jx step helm build --dir env
Options:
      --clone-https=true: Clone the environment Git repo over https rather than ssh which uses `git@foo/bar.git`
  -d, --dir='.': The directory containing the helm chart to apply
      --git-provider='github.com': The Git provider for the environment Git repository
  -r, --recursive=false: Build recursively the dependent charts
      --remote=false: If enabled assume we are in a remote cluster such as a stand alone Staging/Production cluster
Usage:
  jx step helm build [flags] [options]
Use "jx options" for a list of global command-line options (applies to all commands).

make: *** [build] Error 1
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by cagiti** [comment]
Hopefully once a full release of `jenkins-x-versions` is cut this issue will be resolved

**Comment by hferentschik** [comment]
@cagiti is this still an issue? The problem is/was that the build image contains a `jx` version which was not up to date, right?

**Comment by pmuir** [comment]
This is working on the prod cluster so I believe it is resolved.
