### ISSUE TITLE
failed to create system vault in namespace

### ISSUE THREAD

**Issue by Damien9527** [jenkins-x/jx#5046]
### Summary 

I merge a pull request  to my repo ,and then jenkins  build it in the staging repo ,but  the`  jx step helm apply`  see not work well .   I can't get  app  info after the build success .

### Expected behavior

 jx get app :    can  get app .

### Actual behavior

Run :  

~]# jx get app
No Apps found

I  get nothing , but run # jx get applications
APPLICATION STAGING PODS URL
test18      0.0.3   1/1  http://test18.jx-staging.35.241.104.49.nip.io

### Steps to reproduce the behavior
     the staging repo master branch build 

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 2.0.569
jenkins x platform 2.0.942
Kubernetes cluster v1.15.1
kubectl            v1.15.2
helm client        Client: v2.14.2+ga8b13cc
git                2.7.3
Operating System   CentOS Linux release 7.6.1810 (Core)

```
COPY OUTPUT HERE

+ jx step helm apply
Modified file /home/jenkins/workspace/ment-gamblertabby-staging_master/env/Chart.yaml to set the chart to version 7
Copying the helm source directory /home/jenkins/workspace/ment-gamblertabby-staging_master/env to a temporary location for building and applying /tmp/jx-helm-apply-696958103/env
Applying helm chart at /tmp/jx-helm-apply-696958103/env as release name jx to namespace jx-staging
**WARNING: failed to create system vault in namespace jx due to could not find the system vault name in namespace "jx"**
verifying the helm requirements versions in dir: . using version stream URL:  and git ref: 
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /home/jenkins/.jx/jenkins-x-versions
Ignoring templates/.gitignore
Wrote chart values.yaml /tmp/jx-helm-apply-696958103/env/values.yaml generated from directory tree
generated helm /tmp/jx-helm-apply-696958103/env/values.yaml

PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 35.241.104.49.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system
prow: {}

Using values files: /tmp/jx-helm-apply-696958103/env/values.yaml
Applying Apps chart overrides
Applying chart overrides


[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Finished: SUCCESS
```

### Jenkins type
 Classic Jenkins

### Kubernetes cluster
existing  cluster ok GKE

### Operating system / Environment
centos7

**Comment by pmuir** [comment]
This looks like correct behavior to me. What behavior were you expecting?

**Comment by pmuir** [comment]
`jx get apps` is not related to `jx get applications` (which is what should show your application you have built).

**Comment by Damien9527** [comment]
> This looks like correct behavior to me. What behavior were you expecting?

em,  after the pipeline finish  ,    I  run  helm list --all , but can get nothing,   apps not deploy by  `helm  install `?

**Comment by ccojocar** [comment]
This is because `jx step helm apply` is using helm only for templating and `kubectl apply` to install the resources. 

You need to use the the `jx get applications` to list the installed applications. 

I am going to close this one for now since the behaviour is as expected from Jenkins X perspective.
