### ISSUE TITLE
Pull request review guidelines need to include security review

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#5049]
### Summary 

The [pull request guidelines](https://jenkins-x.io/contribute/pullrequestreview/) do not include checking the PR for security issues. 

### Required Fix

1) Define the minimum security checks required for code being contributed to Jenkins X
2) Update the [pull request guidelines](https://jenkins-x.io/contribute/pullrequestreview/) to include the security checks from above

**Comment by ccojocar** [comment]
Yes. We can close it.
