### ISSUE TITLE
jx promote  failed 

### ISSUE THREAD

**Issue by Damien9527** [jenkins-x/jx#5052]
### Summary 
jx promote  failed ！ 

### Steps to reproduce the behavior
   step1 :   jx create quickstart -l go 
             all goes well ,I can acces my app in staging env . 
    step2: 
       when I want to promote my staging application to  production ,I run 
        # jx promote test001 --version 0.0.1  --env production 
    but failed ...

### Expected behavior
       jx promote staging app to production . 

### Actual behavior
      can't promote 

### Jx version

The output of `jx version` is:
[root@instance-1 test001]# jx version
NAME               VERSION
jx                 2.0.581
jenkins x platform 2.0.942
Kubernetes cluster v1.15.1
kubectl            v1.15.2
helm client        Client: v2.14.2+ga8b13cc
git                2.9.5
Operating System   CentOS Linux release 7.6.1810 (Core)

```
COPY OUTPUT HERE
[root@instance-1 test001]# jx promote test001 --version 0.0.1  --env production  --ignore-local-file=true
Promoting app test001 version 0.0.1 to namespace jx-production
pipeline daemin9527/test001/master
error: pulling environment repo https://github.com/daemin9527/environment-gamblertabby-production.git into /root/.jx/environments: git output: usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear: failed to run 'git stash push' command in directory '/root/.jx/environments/production', output: 'usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear'

```

### Jenkins type
Classic Jenkins

### Kubernetes cluster
   local cluster 

### Operating system / Environment
 centos7

**Comment by pmuir** [comment]
This is caused by an old git image in the builder image I think.

**Comment by Damien9527** [comment]
> This is caused by an old git image in the builder image I think.
Yes,I have two  project on my machine ,Maybe this is the problem.
If this  means  I can only  build  one project  on the single machine ?

**Comment by pmuir** [comment]
I'm sorry, it looks like you are running `jx promote` manually. If so, make sure you have at lesat git 1.15 installed.

**Comment by doc-olliday** [comment]
Hi,
I've got a similar problem with manual `jx promote`.
git-provider is https://gitlab.com

jx version gives:
```
NAME               VERSION
jx                 2.0.675
jenkins x platform 2.0.1098
Kubernetes cluster v1.13.10
kubectl            v1.15.2
helm client        Client: v2.14.1+g5270352
git                2.23.0
Operating System   "openSUSE Tumbleweed"
```
Giving the command `jx promote --version v0.0.1 --env production --no-wait=true --no-poll=true --verbose`
ends up in:
```
DEBUG: Using helmBinary helm with feature flag: template-mode
Promoting app springtest version v0.0.1 to namespace jx-production
pipeline hbxdevgroup/springtest/master
DEBUG: finding service url for jenkins in namespace jx
DEBUG: found service url http://jenkins.jx.xx.yy.zz.abc.nip.io
DEBUG: finding service url for jenkins in namespace jx-staging
DEBUG: finding service url for jenkins in namespace jx
DEBUG: found service url http://jenkins.jx.xx.yy.zz.abc.nip.io
DEBUG: Using pipeline: hbxdevgroup/springtest/master build: #1
DEBUG: merging pipeline secrets with local secrets
error: pulling environment repo https://gitlab.com/hbxgitops/environment-unicornplatinum-production.git into /home/gradol/.jx/environments: fetching origin promote-springtest-v0.0.1: git output: remote: The project you were looking for could not be found.
fatal: Repository 'https://gitlab.com/hbxgitops/environment-unicornplatinum-production.git/' nicht gefunden.: failed to run 'git fetch origin promote-springtest-v0.0.1' command in directory '/home/gradol/.jx/environments/production', output: 'remote: The project you were looking for could not be found.
fatal: Repository 'https://gitlab.com/hbxgitops/environment-unicornplatinum-production.git/' nicht gefunden.'
```
(Sorry for the mix up with German message.)

Having a look at `~/.jx/environments/` you can see a subfolder `hbxgitops` which holds the correct clones of the environment repos from gitlab.com. `git remote -v` show the correct URLs for origin (with credentials in it!)
But alongside of the `hbxgitops` folder the promote command has created a subfolder `production`. When you look at this folder with the command `git remote -v` you find the URLs of origin configured without any credentials. So, maybe that would be the reason, why it expects a public environment repo?

Is there any suggestion or a fix?
Btw. auto-promote to an environment works, as it uses the hbxgitops folder.

**Comment by siddharthkaushal90** [comment]
@doc-olliday are you able to promote the code to production for the first time?
