### ISSUE TITLE
boot: vault support for Azure

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5057]
### Summary 

Ensure that Vault can be provisioned using the Azure backend when using `jx boot` command.

A number of resources needs to be created for vault backend:
- storage bucket
- KMS/KeyVault key 

See the AWS integration for more details https://github.com/jenkins-x/jx/issues/5055.

**Comment by michaeljohnbennett** [comment]
is anyone working on this?

**Comment by hferentschik** [comment]
Some references which might be useful:

- https://banzaicloud.com/blog/vault-operator/
- https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-azure.yaml
