### ISSUE TITLE
Add kaniko image version to version stream

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5063]
We hardcode the default Kaniko image and version in the code currently. That's kinda silly when we've got this whole version stream thing here. =) So let's add a Kaniko version to the version stream, and then update the logic in the CRD translation to use that.

**Comment by ar-qun** [comment]
Hello @abayer ,

We have some issues using the old Kaniko image, specifically with chown/COPY related issues. How can we upgrade to the latest release v0.16.0 of Kaniko?

Thanks in advance.

**Comment by abayer** [comment]
Whoops, sorry, this is done.
