### ISSUE TITLE
Unable to set the default docker-registry for PKS during installation

### ISSUE THREAD

**Issue by laikw** [jenkins-x/jx#5073]
### Summary 
Installing Jenkins X to a PKS cluster with --docker-registry does not change the default docker registry: jx install --docker-registry harbor.pks.abc.com

### Steps to reproduce the behavior
Installed Jenkins X a PKS 1.4.1 cluster with a custom docker registry. Created a golang-http quickstart application and the step "Build Container Build" failed.

jx get build logs returns: error pushing image: failed to push to destination harbor.corp.local/*****/**-go:0.0.2: Get http://harbor.corp.local/v2/: dial tcp: lookup harbor.corp.local on 10.100.200.2:53: no such host

### Expected behavior
The image should be pushed to the docker registry "harbor.pks.abc.com" which is specified during installation.

### Actual behavior
The image got pushed to the default docker registry for PKS, "harbor.corp.local".

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.589
jenkins x platform 2.0.942
Kubernetes cluster v1.13.5
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

Note that in Classic Jenkins, the --docker-registry is able to set the default docker registry.

### Kubernetes cluster

Created using PKS 1.4.1. The kubernetes cluster version is v1.13.5.

### Operating system / Environment

Ubuntu 16.04.6 LTS

**Comment by pmuir** [comment]
This may be a bug in serverless install or in PKS. Do you know?

**Comment by laikw** [comment]
I do not know but my guess would be this is a bug in serverless JX since it is the one pushing the image to the docker registry.

**Comment by laikw** [comment]
Seems like this issue is caused by PKS rather than JX. Closing this issue.
