### ISSUE TITLE
Installing CJXD with an existing jenkinx-x-versions repo in jenkins home doesn't override it with the correct one

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5075]
### Summary 
When executing `jx boot` using the CJXD Release 1 binary while having an existing `jenkins-x-versions` repository in `.jx` results in boot using the existing repository without checking if it's a CJXD repository.

I had this happening when creating a brand new CJXD cluster without deleting `.jx`, resulting in CJXD using the versions stream master branch of `jenkins-x-versions` instead of `cloudbees-jenkins-x-versions`.

I found out because metapipelines were enabled by default. 

### Steps to reproduce the behavior

Create a cluster using `jx boot` with the `oss` profile enabled, it will download `jenkins-x-versions`. Then enable the `cloudbees` profile and attempt to do the same.

### Expected behavior
It should use the versions defined in `cloudbees-jenkins-x-versions`

### Actual behavior
Uses whatever versions are defined in the local `jenkins-x-versions` repository, without checking whether it's the correct one or not.

### Jx version
CJXD Release 1:

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.521
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```
### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by pmuir** [comment]
Workaround is to delete your `.jx` directory first.

**Comment by abayer** [comment]
I _think_ #5110's logic would fix this - PR incoming.
