### ISSUE TITLE
Promoting with `--no-merge` will fail the build

### ISSUE THREAD

**Issue by cpwc** [jenkins-x/jx#5081]
### Summary 
Having a `jx promote -b --no-merge --env production --timeout 1h` will cause the build to fail after the defined timeout. Likely to be stuck at `waitForGitOpsPullRequest`. 

### Steps to reproduce the behavior
I have a build pipeline that promotes to both `staging` and `production` but will not merge on `production` as it has prow to wait for team members to review with `approve` and `lgtm` labels before proceeding to merge.

### Expected behavior
Should skip `waitForGitOpsPullRequest` if `--no-merge` is defined.

### Jx version

The output of `jx version` is:

```
jx                 2.0.561
jenkins x platform 2.0.942
Kubernetes cluster v1.12.9
kubectl            v1.15.0
helm client        Client: v2.14.1+g5270352
git                2.19.1
Operating System   Mac OS X 10.14 build 18A391
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

AWS + KOPS

**Comment by pmuir** [comment]
Why wouldn't you also just specify `--no-wait` rather than overload the semantics of `--no-merge`?

**Comment by cpwc** [comment]
@pmuir `--no-wait` still caused the build to fail.

```sh
Pipeline failed on stage 'from-build-pack' : container 'step-promote-jx-promote-production'. The execution of the pipeline has stopped.[0m
```

Could potentially use `no-poll` instead to skip the whole `waitForGitOpsPullRequest ` function trigger.

**Comment by pmuir** [comment]
fair enough, then I think your approach is valid - I just wanted to check we weren't missing the obvious!

**Comment by cpwc** [comment]
@pmuir while digging thru the codes I saw that if `--no-poll` were to be given it will also skip the whole `waitForGitOpsPullRequest` function. Which is what we are looking for. Should we do an implicit `--no-poll` if `--no-merge` is defined? It will be cleaner in a way?

**Comment by pmuir** [comment]
or maybe just add to the help that you should specify both?

**Comment by cpwc** [comment]
@pmuir sounds good! I'll proceed close my PR.
