### ISSUE TITLE
Error creating preview environments

### ISSUE THREAD

**Issue by marlovil** [jenkins-x/jx#5083]
### Summary 
When a PR is created to merge a branch, a preview environment is created but with the content of master branch instead of branch updates

### Steps to reproduce the behavior
Create a branch, do some changes, create a PR to merge the branch.

### Expected behavior
Preview environment of the PR with the branch changes to be merged

### Actual behavior
Preview environment with master branch content

### Jx version
```
NAME               VERSION
jx                 2.0.525
jenkins x platform 2.0.942
Kubernetes cluster v1.12.10-eks-2e569f
kubectl            v1.14.2
helm client        Client: v2.14.3+g0e7f3b6
git                git version 2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) and multiple cluster config
- [ ] Classic Jenkins

### Kubernetes cluster

EKS cluster up and running created with Cloudformation

### More information and logs

- Private repository in GitHub
- Multiple cluster jx installation (dev, staging and prod clusters)

In the PR build logs I can see:
```
{"level":"warn","ts":1565776648.715676,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1565776649.5922465,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/xxx/**qsapp.git @ master in path /workspace/source"}
```
and

```
Creating a preview
Commit author email is empty for: 00a84d534b046b3d721ee554cf3d8212a9577078
Looking for commits in: /workspace/source/
WARNING: Commit not found: 00a84d534b046b3d721ee554cf3d8212a9577078
Commit author email is empty for: 48041cbe57b5f03b30ac28f1bdc35faac5c7840a
Looking for commits in: /workspace/source/
WARNING: Commit not found: 48041cbe57b5f03b30ac28f1bdc35faac5c7840a
Created environment xxx-**qsapp-pr-1
Namespace **-xxx-**qsapp-pr-1 created 
```
The two commit IDs are the ones created in the branch we want to merge to master.

Thanks in advance for you support! :)

**Comment by pmuir** [comment]
Please provide the entire PR build log log.

**Comment by pmuir** [comment]
Likely to be a dupe of #5024 @hferentschik

**Comment by marlovil** [comment]
Hi Pete!

Thanks for your response and sorry for the delay. Please find attached the entire PR log.

[PR.log](https://github.com/jenkins-x/jx/files/3508334/PR.log)

**Comment by marlovil** [comment]
Hi @pmuir!

Have you been able to reproduce this? Please, let me know if you need more information.

**Comment by marlovil** [comment]
Hi again!

I've updated jx cli and jx platform, now:
> NAME               VERSION
> jx                 2.0.628
> jenkins x platform 2.0.983
> Kubernetes cluster v1.12.10-eks-2e569f
> kubectl            v1.14.2
> helm client        Client: v2.14.3+g0e7f3b6
> git                2.17.1
> Operating System   Ubuntu 18.04.3 LTS

And occurs exactly the same. Please, take a look at this log file.
[pr-2.log](https://github.com/jenkins-x/jx/files/3549724/pr-2.log)

cf888f0 is master
a4eb8d7 is the commit ID of the branch/PR

Do you have any clue about that?  Sorry for pushing you guys. We need to deploy jx on production ASAP and we would like to solve this before that.

Many thanks for your patience!

**Comment by pmuir** [comment]
That log looks correct to me - it looks like it's building the commit of the branch.

```Creating a preview
Commit author email is empty for: a4eb8d7f8ffe5e8a9143ef62833d4b48a99e2814
```

**Comment by marlovil** [comment]
Thanks for you response Pete. You mean that not having the author email causes this behavior and this warning (two lines after):

`WARNING: Commit not found: a4eb8d7f8ffe5e8a9143ef62833d4b48a99e2814`

And therefore all is a misconfiguration issue?

Thanks!

**Comment by marlovil** [comment]
Anyway, the author email (who created the commit) is configured in Git local settings (checked with `git config --list` command). There is something wrong?

**Comment by marlovil** [comment]
The issue is solved on a fresh Jenkins X install...
