### ISSUE TITLE
Use branch for version stream but resolve to tag if possible

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5087]
### Summary 

Previously we used a branch to reference a version stream. We partially switched to GitHub releases but this is problematic (as releases aren't really a stream but a series of unrelated fixed points) and also prone to breakage (as it requires us to create a release).

Instead we will use the branch as a stream but try to resolve to a tag using `git describe` if possible and if not reference the SHA.

**Comment by pmuir** [comment]
Still needs tests so slipping to sprint 13

**Comment by daveconde** [comment]
Should we put this in to the next sprint or park it for now?

**Comment by deanesmith** [comment]
@wbrefvem

**Comment by pmuir** [comment]
Had to revert https://github.com/jenkins-x/jx/pull/5870
