### ISSUE TITLE
Create BDD test for building dev env in pipeline

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5093]
There have been quite a few bugs recently around boot based clusters not being able to run in a pipeline. It would be good to ensure we don't have regressions here.

**Comment by hferentschik** [comment]
I think this depends on https://github.com/jenkins-x/bdd-jx/pull/65. IMO we need to refactor and cleanup the BDD framework first before investing in more tests.

**Comment by pmuir** [comment]
See #5340

**Comment by daveconde** [comment]
Closing as we now test this
