### ISSUE TITLE
Replicate Jenkins Chuck Norris Epic Plugin in JX

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#5098]
### Summary 
The Chuck Norris Jenkins Plugin was awesome, we should have something similar in JX. Maybe even in the JX cli tool. 

### Expected behavior
![best-plugin-ever](https://user-images.githubusercontent.com/271966/63133387-e4146280-bf79-11e9-8660-a23236d85372.png)
### Actual behavior

No Chuck Norris 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by cagiti** [comment]
I believe @rawlingsj has dabbled with this, the service which returns Chuck Norris quotes can return some unsavoury responses

**Comment by garethjevans** [comment]
He has, I think he was looking at it from a prow plugin / chatops thing
