### ISSUE TITLE
jx boot outputs numerous WARNING messages when templating

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#5104]
### Summary 
During installation of Jenkins X numerous WARNING messages are displayed when templating, however the installation appears to complete successfully

### Steps to reproduce the behaviour
- Create a cluster
- Install Jenkins X using `jx boot`

### Expected behaviour
The frequency of the WARNING messages are reduced or removed unless it will impact the installation of Jenkins X

### Jx version

The output of `jx version` is:

```
🙅 developer ~/go-workspace()$ jx version
NAME               VERSION
jx                 2.0.597
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.22.0
Operating System   Alpine Linux 3.10.1
WARNING: 
A new jx version is available: 2.0.598
? Would you like to upgrade to the new jx version? [? for help] (Y/n) 
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hferentschik** [comment]
Something I reacted to as well. I also think per default we a too verbose, but maybe we should have a different issue for that.

**Comment by pmuir** [comment]
I'll try to fix it as this is a distraction
