### ISSUE TITLE
Update vault-operator and bank-vault to version 0.5.0 

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5113]
### Summary 

vault-operator and bank-vault images should be updated to version 0.5.0 to get the vault provisioning properly working with AWS. 

See the original issue reported on https://github.com/banzaicloud/bank-vaults/issues/616.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by dgozalo** [comment]
needs #5434
