### ISSUE TITLE
jx boot mixes up secrets from vault with k8s secrets

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5114]
### Summary 

It seems that `jx boot` mixes up the secrets from vault with k8s secrets e.g. for GitHub pipeline token. 

For instance when disabling the `gh-secret` from boot templates when vault is active, the installation process starts to fail when the environments are created because the `auth config` is not properly set in vault. 

```
creating environment production git repository for URL: https://github.com/ccojocar/environment-cosmin-dev-production.git to namespace jx-production
error: no auth server found for git server https://github.com from gitURL https://github.com/ccojocar/environment-cosmin-dev-production.git
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''
```
This means that the create environment is using the duplicated github token from k8s secret instead of using the one from vault :disappointed: . Unfortunately the secrets are quite mixed up by boot. 

We need to properly configure the auth in a boot step before creating the environments (verify-env step).

Also the GitHub token seems to be duplicated in 5 places during the installation:

![image](https://user-images.githubusercontent.com/591127/63213618-b876b100-c10e-11e9-902c-5c24cdabf62d.png)

This will definitely make secrets rotation very difficult. 

### Expected behavior

jx should use in the pipeline the secrets from vault for git provider authentication. 

### Actual behavior

jx is using the secrets duplicated in k8s secret `jx-pipeline-git-github-github` when vault is configured.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment

ACs:
- When vault is enabled when using boot the value of the pipeline git secret should only be in vault and not in jx-pipeline-github-github
- When vault is disabled the pipeline git secret should be available in jx-pipeline-github-github

**Comment by ccojocar** [comment]
Block until https://github.com/jenkins-x/jx/issues/5190 is done.

**Comment by pmuir** [comment]
@ccojocar is this unblocked now?

**Comment by ccojocar** [comment]
Yes, it still blocked by https://github.com/cloudbees/cloudbees-jenkins-x-distro/issues/15 which needs https://github.com/jenkins-x/jx/issues/5310.

**Comment by ccojocar** [comment]
We need to get the BDD test passing with the current version before stating to do any more refactorings in the boot. See this PR https://github.com/jenkins-x/jenkins-x-boot-config/pull/53

**Comment by daveconde** [comment]
Closing as captured in #5037

**Comment by hferentschik** [comment]
See discussion around git authentication on this PR as well https://github.com/jenkins-x/jx/pull/5850#issuecomment-543137745
