### ISSUE TITLE
we should probably not recreate the `~/.jx/cloud-environments` but git pull?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#512]
its maybe safer if folks have made local changes?

**Comment by chaseconey** [comment]
Just my 2 cents, but I did find it odd until I realized what that question meant (the "do you want the latest environment changes, etc" question). I was modifying the `myvalues.yaml` and it kept getting wiped out and I couldn't find the proper way to make changes other than possibly just making my own environment fork and putting them in there. I like the idea of `git pull`ing them instead :)
