### ISSUE TITLE
Support for other cloud providers?

### ISSUE THREAD

**Issue by nippip** [jenkins-x/jx#513]
I see that jenkins-x is working best on GKE and will be on AKS and EKS soon.  Does this mean that we won't be able to use it on other providers like DigitalOcean and Oracle Cloud Infrastructure until support is available?  I am wondering if the same would apply for the DIY K8s deployments out there, would some support be needed to run jenkins-x in these other k8s deployments?

**Comment by michaelneale** [comment]
@nippip I expect support for anything is possible. In theory jx install could work in any suitable environment. The `jx create cluster` command is mostly sugar+tested stuff to ensure it works and makes a cluster for you. 

I am sure @jstrachan or @rajdavies could comment and hopefully agree with me

**Comment by rajdavies** [comment]
Jenkins X should run on any Kubernetes compliant cluster - you can use the jx install command - see http://jenkins-x.io/getting-started/install-on-cluster/ for more details.

**Comment by jstrachan** [comment]
Our aim is to support any Kubernetes cluster & to make Jenkins X  as easy to use as possible without the user needing much Kubernetes knowledge. So we should polish the docs to make it more clear you can try install Jenkins X on any Kubernetes cluster - though it can be challenging ensuring users get a good experience on any cluster as they can be quite different. 

This is why we nudge users to the ‘jx create cluster ...’ commands as we then know it’s creating a good cluster that’s likely to work. I’d love to see more ‘jx create cluster ...’ commands for other clouds like Digital Ocesn, Oracle cloud, Alibaba, CloudFoundry  etc 

Given any cluster, ‘jx install —provider=kubernetes’ should hopefully work if...
* RBAC is enabled on the cluster (it’s on by default in 1.9 IIRC)
* insecure docker registry is enabled for kubernetes service IPs so we can default to running a docker registry inside the cluster
^ there is enough compute, memory & disc to run everything

**Comment by nippip** [comment]
Thanks gang!  That is what I was looking for.

**Comment by jstrachan** [comment]
I guess we can close this now - let us know if you want to reopen
