### ISSUE TITLE
Install vault in to a different namespace by default

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5131]
Install vault in to a different namespace by default to make recovery easier.

**Comment by pmuir** [comment]
This means if the jx ns is compromised, vault is not affected. Same for a `jx uninstall`.

**Comment by ccojocar** [comment]
This will also provide better security. In the current setup, vault is installed in the `jx` namespace where there is also the service account used for vault backend, this means any POD running in `jx` namespace with get secrets permissions will also be able to retrieve secrets from bucket and decrypt them using the cloud KMS.
