### ISSUE TITLE
jx get build logs looses pipeline logs sometimes with meta pipeline

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5139]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
I know things are crazy, but do you have any more details on this?

**Comment by pmuir** [comment]
Fixed by https://github.com/jenkins-x/jx/pull/5144/commits/0388b2a65bdbc1f94adb09bc5d52afcc9d7c6aba
