### ISSUE TITLE
Jenkins-X pods do not start due to 'container has runAsNonRoot and image will run as root' message

### ISSUE THREAD

**Issue by aruder77** [jenkins-x/jx#5155]
### Summary 
I just installed Jenkins-X for the first time, but the pods do not come up and remain in a 'CreateContainerConfigError' error state. None of the pods except the jenkins pod itself do come up, a describe to any of the pods says 'container has runAsNonRoot and image will run as root' .

### Steps to reproduce the behavior
 jx install --provider=kubernetes --skip-ingress --on-premise --external-ip=x.x.x.x --domain=mydomain.net --no-default-environments --git-provider-url='https://mybitbucket.net/bitbucket'

### Expected behavior
Jenkins-X pods to be running and ready

### Actual behavior
All Jenkins-X pods except the jenkins pod itself remain in 'CreateContainerConfigError' state with message 'container has runAsNonRoot and image will run as root'

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.172
jenkins x platform 2.0.951
Kubernetes cluster v1.13.5
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                git version 2.15.0
Operating System   Mac OS X 10.13.6 build 17G8030
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

### Kubernetes cluster

On premise own kubernetes cluster 1.13.5 set up with kubespray.

### Operating system / Environment
Mac OS 10.13.6

**Comment by pmuir** [comment]
Have you run `jx compliance`? Did it pass?

**Comment by pmuir** [comment]
I think as a workaround you can enable running containers as root (Jenkins X requires it)
