### ISSUE TITLE
enable a 'plugin' approach for commands so they can live outside of the main jx repo

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#517]
so that new commands can be implemented in different binaries by any addon and the `jx` would download the binary on the fly if required and invoke it invisibly to the user.

Similarly `jx upgrade cli` would upgrade any other dependent binaries

**Comment by rawlingsj** [comment]
already done by @jstrachan

**Comment by jstrachan** [comment]
we've plugins for git + issue trackers - but not plugins yet to extend the CLI itself

**Comment by ccojocar** [comment]
This seems to be implemented by the `jx plugin`, therefore I am closing this issue.
