### ISSUE TITLE
Enforce git version as we are seeing a lot of confusion here

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5174]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by pmuir** [comment]
Minimum is 2.15

**Comment by pmuir** [comment]
See #5052

**Comment by jstrachan** [comment]
I've just merged the git range check back into the version stream + tested it locally + it seems to work fine https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/git.yml

**Comment by siddharthkaushal90** [comment]
@jstrachan I tried upgrading platform using https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/git.yml but its skipping upgrade
```
jx upgrade platform --versions-repo https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/git.yml
Using provider 'gke' from team settings
Already installed platform version 2.0.1247. Skipping upgrade process.
```

```
My git version is 2.11.0
jx version
NAME               VERSION
jx                 2.0.762
jenkins x platform 2.0.1247
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.13.9-2+4a03651a7e7e04
helm client        Client: v2.14.1+g5270352
git                2.11.0
Operating System   Debian GNU/Linux 9.11 (stretch)


verifying packages
error: package git is an old version 2.11.0. The version stream requires at least 2.15.0
```

**Comment by jstrachan** [comment]
look like your git version is too old - we require `2.15.0` or later

**Comment by siddharthkaushal90** [comment]
@jstrachan how do I upgrade it?

**Comment by jstrachan** [comment]
@siddharthkaushal90 see https://confluence.atlassian.com/bitbucketserver/installing-and-upgrading-git-776640906.html

**Comment by siddharthkaushal90** [comment]
@jstrachan I tried updating git, but its saying git is already the newest version.
I am using gcloud.

**Comment by siddharthkaushal90** [comment]
@jstrachan I have updated git version in the gcloud container and enforced that.
But now when I am trying to install jenkins-x it is throwing me below error:
```
helm installed and configured
FATAL: initialise build packs failed: failed to fetch master from https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git in directory /home/siddharthkaushal90/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes: git output: fatal: Unable to find remote helper for 'https': failed to run 'git fetch origin master' command in directory '/home/siddharthkaushal90/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes', output: 'fatal: Unable to find remote helper for 'https''
```
```
jx version
NAME               VERSION
jx                 2.0.668
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.13.9-2+4a03651a7e7e04
helm client        Client: v2.14.1+g5270352
git                2.15.1
Operating System   Debian GNU/Linux 9.11 (stretch)
```

**Comment by jstrachan** [comment]
is there a firewall or something? can you run `git clone https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git` in a temp dir?

**Comment by siddharthkaushal90** [comment]
no there is no firewall
I tried running git clone https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
but it throws below error:
```
fatal: Unable to find remote helper for 'https'
```

**Comment by jstrachan** [comment]
sounds like something is seriously messed up with your git install
https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone

**Comment by siddharthkaushal90** [comment]
I used below steps in dockerfile to install git
sudo apt-get update
sudo apt install
wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.15.1.tar.gz
tar -zxf git-2.15.1.tar.gz
cd git-2.15.1
make configure
./configure --prefix=/usr
sudo make install

**Comment by jstrachan** [comment]
see the link I posted - looks like you need to install curl before you build git

**Comment by siddharthkaushal90** [comment]
okay thanks, let me check
