### ISSUE TITLE
Documentation for Vault is missing

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx#5179]
As raised in the office hours on Thursday Aug 22nd, there are currently no documentation around how to use Vault.

We'd need documentation around

* installing Vault as part of Jenkins X installation
* Configuring Vault (esp around enabling HTTPS)
* Which secrets are stored in Vault post install
* How to use Vault secrets in pipelines

**Comment by dennisnewel** [comment]
We're allowed to use/copy the content from https://go.cloudbees.com/docs/cloudbees-jenkins-x-distribution/vault/
As the CloudBees Jenkins X Distribution currently only focuses on GKE, we'd still need to add documentation for other cluster options.

**Comment by unalterable** [comment]
please can someone let me know how to use Vault secrets in pipelines

**Comment by dennisnewel** [comment]
Vault documentation is being added as part of https://github.com/jenkins-x/jx-docs/pull/1930

**Comment by dennisnewel** [comment]
documentation is up here: https://jenkins-x.io/docs/reference/components/vault/

@unalterable does this ^ answer your question

**Comment by ccojocar** [comment]
@dennisnewel Can we close this issue since the documentation was added?

**Comment by dennisnewel** [comment]
oh, right. I'll close it
