### ISSUE TITLE
add a jx CLI to automate updating a preview chart with apps / services in another environment

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#519]
Chatting to @kzantow on slack, it would be nice to have some jx UX that updates an apps preview environment with apps from another environment.  

Perhaps offing a selection that folks can opt in/out of?

**Comment by kzantow** [comment]
Yeah. Just thinking about working with a microservice-heavy environment, most microservices shouldn't need or have typical dependencies to the UI applications, but from a QA perspective, the PRs against those are much less useful without the corresponding UIs available, updated to the PR versions in test.

**Comment by jstrachan** [comment]
relates to #573
