### ISSUE TITLE
Pull image from AWS ECR registry

### ISSUE THREAD

**Issue by matiashaller** [jenkins-x/jx#5197]
### Summary 
In Dockerfile calls a docker image from private ECR registry.

### Steps to reproduce the behavior
In Docker file 
`FROM <Accout ID>.dkr.ecr.us-east-1.amazonaws.com/<image:tag>`

### Expected behavior
Download image from repository

### Actual behavior
Authetication error

`Step 1/6 : FROM <Accout ID>.dkr.ecr.us-east-1.amazonaws.com/<image:tag>
Complete in 22.840020298s
time="2019-08-23T12:54:58Z" level=fatal msg="build failed: building [<GitORG>/<GitRepo]: build artifact: Get https://<Accout ID>.dkr.ecr.us-east-1.amazonaws.com/v2/<image:tag>: no basic auth credentials"`

### Jx version

The output of `jx version` is:
NAME                    VERSION
jx                            2.0.598
jenkins x platform   2.0.951
Kubernetes cluster v1.12.10-eks-2e569f
kubectl                    v1.13.2
helm client              Client: v2.14.1+g5270352
git                           2.20.1
Operating System  Ubuntu 19.04

```
COPY OUTPUT HERE
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster
EKS

### Operating system / Environment
Operating System  Ubuntu 19.04

**Comment by faucherb94** [comment]
@matiashaller Have you found a workaround for this? @MarckK?

**Comment by matiashaller** [comment]
Hi Ben,

I re installed all cluster and stared working just fine. If this is not an
option for you, check this link may be useful
https://medium.com/@damitj07/how-to-configure-and-use-aws-ecr-with-kubernetes-rancher2-0-6144c626d42c

**Comment by ccojocar** [comment]
@dgozalo Does this work now with a boot based installation?
