### ISSUE TITLE
jx step create pr versions doesn't update an existing PR

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5200]
At least not for me. =)

Using `jx` `v2.0.623`, the most recent build, and running `jx step create pr versions -f '*' --images --excludes jetstack/cert-manager`, I see it checking out `master` in its temp clone of `jenkins-x-versions`, making changes to that clone, claiming it's updating the existing PR, but not actually doing anything to the PR. I saw this in the cronjob too. Closing the existing PR and running the same command did create a new PR correctly.

**Comment by abayer** [comment]
I'm wondering if this is due to different users creating the PRs? https://github.com/jenkins-x/jenkins-x-versions/pull/417 was created by @pmuir, but the PRs created after I closed that were created by `jenkins-x-bot`.

**Comment by abayer** [comment]
I'm gonna leave https://github.com/jenkins-x/jenkins-x-versions/pull/420 open to see if it gets updated by the cronjob tonight.

**Comment by abayer** [comment]
clarifying based on what I just saw with the cronjob- if there’s an existing PR from a different user, it won’t be updated, and a new one won’t be created. If the existing pr is from the same user, it will be updated.

**Comment by pmuir** [comment]
That's correct @abayer - we don't update PRs from other users as it get's very complex in terms of pushing commits etc. But it looks like it's not creating a new PR either?
