### ISSUE TITLE
`jx upgrade addon prow` removes ingress configurations

### ISSUE THREAD

**Issue by alexvolsh** [jenkins-x/jx#5206]
### Summary 
`jx upgrade addon prow` removes ingress configurations for hook, deck and tide services.

### Steps to reproduce the behavior
1. run `jx upgrade ingress`, setup TLS and custom UrlTemplate (e.g. "{{.Service}}.{{.Domain}}")
2. run `jx upgrade addon prow`

### Expected behavior
Prow and its services upgraded with custom configurations.

### Actual behavior
Prow and its services upgraded but ingress configurations are deleted.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.627
jenkins x platform 2.0.979
Kubernetes cluster v1.15.3
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.15 build 19A536g
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Self-created with kubespray

### Operating system / Environment

Running the CLI on my MacBook Pro (OS X)

**Comment by pmuir** [comment]
What happens if you rerun `jx upgrade ingress` after upgrading prow?

**Comment by alexvolsh** [comment]
Sorry for delay with answer, I was waiting for next JX release. So the result of the rerun `jx upgrade ingress` is error:
```
error: getting the webhook endpoint: getting ingress for service "hook" in namespace razomer: ingresses.extensions "hook" not found
```

**Comment by alexvolsh** [comment]
Works correctly on:
```
NAME               VERSION
jx                 2.0.1040
jenkins x platform 2.0.1695
Kubernetes cluster v1.15.6
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.0
Operating System   Mac OS X 10.15.2 build 19C46a
```
