### ISSUE TITLE
jx get build logs (and other things using logs) doesn't order stages properly

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5207]
At least not completed stages - if you start `jx get build log` while the first stage (or metapipeline) is running, the logs always turn out right, but once the first stage or metapipeline has finished, you get the ordering as Stage 2 and then Stage 1 (or Actual Build Pipeline Stage and then Metapipeline Stage).

I've also seen some probably related weirdness with parallel stages - `jenkins-x-builders` PR builds have 9 parallel stages, and `jx get build logs` used to go from `batch-one` to `batch-nine` (yes, we someday need a better answer for logging parallel stages, but that's a separate matter), but now it goes from `batch-nine` to `batch-one`.

I'm assuming this is down to https://github.com/jenkins-x/jx/pull/5144/commits/4012a150441fb7a32a60d0739429cb165684b1f8, but we should probably revisit this whole logic. Combining `PipelineActivity` (which should let us see which of the metapipeline and actual pipeline started first...which admittedly we know intuitively, but yeah) and `PipelineStructure` (to see the order in which a pipeline's stages are meant to run, or in the case of parallel stages, the order in which they're declared), we can probably do this better.

**Comment by hferentschik** [comment]
I think we should combine this with #5007. I think we can simplify the logic in `tekton_logging.go` considerably if one can explicitly select the pods/resources. The code becomes more direct.
