### ISSUE TITLE
Meta pipeline explicitly sets JX_LOG_FORMAT to JSON for build pipeline

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5211]
The meta pipeline sets `JX_LOG_FORMAT=json` for each pipeline step. See https://github.com/jenkins-x/jx/blob/a91424056c7d4c7cffd368b36eef65bc272730e3/pkg/tekton/metapipeline/metapipeline.go#L271.

The idea was to have more structured logging in the pipeline. Right now there are several issues with that. The output of `jx get build log` gets messy when JSON is used and displayed unprocessed/unfiltered and using JSON breaks BDD tests which rely on specific log output.

Generally having a richer log format would be beneficial and using an approach as described in this comment - https://github.com/jenkins-x/jx/pull/5201/files#r317356639 - could solve the `jx get build log` problem. However, `JX_LOG_FORMAT=json`only applies for `jx` (step) commands in the pipeline. Other pipeline steps (eg a make execution) would still be non JSON.

**Comment by hferentschik** [comment]
Interestingly all logs are already written per default as JSON on the node, however, there is no option to retrieve then as JSON via Kube's `GetLogs` API.

**Comment by hferentschik** [comment]
One thing one can do is to retrieve the log timestamps as well, but that's a different question. For now, it might be best to remove `JX_LOG_FORMAT`.

**Comment by hferentschik** [comment]
See https://github.com/jenkins-x/jx/issues/5208

**Comment by abayer** [comment]
Actually fixed this in #5209.
