### ISSUE TITLE
Provide mechanism which allows safe CRD evolution

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5222]
Over time we will need to change/evolve our CRDs and need a way which allows safe upgrades for existing users.

Example:
```go
type TeamSettings struct {
...
	GitPrivate          bool                 `json:"gitPrivate,omitempty" 
...
}
```

From a API point of view and a security perspective it would be better if this field would be called `GitPublic` in order to avoid accidentally creating public repositories. See also issue #5186.

The question is how such a change in the structure of an existing CRD can be made whilst allowing existing users to safely upgrade.

**Comment by jstrachan** [comment]
FWIW k8s/apimachinery already supports this - its just a case of writing a parser for the old + new configuration. 

e.g. we did this for`User.User` -> `User.Spec`

https://github.com/jenkins-x/jx/blob/09d481e253e7da8df469ce2802ec030447d63600/pkg/apis/jenkins.io/v1/types_users.go#L74

**Comment by jstrachan** [comment]
we need to be careful `false` isn't omitted from the json/yaml which would make loading the old + new fields harder

**Comment by polothy** [comment]
Any ideas on how to do this per team namespace?  We have a lot of teams and manually editing each env CRD sounds painful.  All of our repositories are private if that makes it easier.

**Comment by polothy** [comment]
Oh, maybe this is just for the dev environment... not as bad, but would like a one liner anyways.  I'll look but thoughts are always appreciated.

**Comment by polothy** [comment]
Maybe maybe... `kubectl get environment -oyaml dev | yq d - spec.teamSettings.gitPrivate | yq w - spec.teamSettings.gitPublic false`
