### ISSUE TITLE
`jx upgrade cli` fails during rename operation

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x/jx#5230]
### Summary 

`jx upgrade cli` from version `2.0.598` to version `2.0.635` fails during the rename:
![jx_upgrade](https://user-images.githubusercontent.com/8556522/63836576-18c0ea80-c97a-11e9-9c09-cc8f6a4fb895.png)

### Steps to reproduce the behavior

Attempt to upgrade the command line tool: `jx upgrade cli`

### Expected behavior

`jx` is upgraded to the latest version.

### Actual behavior

Original `jx` command is removed prior to the upgrade failing during the rename operation (e.g. `bash: /home/ansible/.jx/bin/jx: No such file or directory` after the upgrade attempt).

### Jx version

The output of `jx version` is:
![jx_version](https://user-images.githubusercontent.com/8556522/63837481-db5d5c80-c97b-11e9-8fc7-cd6461463730.png)

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE cluster installed using `jx cluster create` (with some hackity-hack-hack to get it all working, e.g. uninstalled / re-installed `jx` several times after the cluster creation).

### Operating system / Environment

I build an ops docker image based on `ubuntu:18.04` with all the things for day to day tasks (`ansible`, `docker`, `jx`, `helm`, `skaffold`, ... - minimal issue for myself, e.g. just a rebuild).

**Comment by pmuir** [comment]
I'll try to reproduce this in cloudshell but I suspect this is a side effect of your environment

**Comment by masseybradley** [comment]
Hi! Thanks. Would be a first but I wouldn’t exclude it as a possibility. No one else reported it as far as I can tell and I just rebuilt a new image tbh. Can close directly if you want (if anyone else encounters the issue they can drop a message).

**Comment by pmuir** [comment]
Yeah, I can't reproduce it. What is your `JX_HOME` env var set as?

**Comment by masseybradley** [comment]
Hi. I never set `JX_HOME` - using `$HOME/.jx`. Does look like an environment issue, somehow managed to restore my volume (mounted to `$HOME/.jx`) with incorrect permissions, can reproduce with the `$HOME/.jx` folder owned by `0`:`0` and all files under the `$HOME/.jx` folder owned by normal user (`1000`:`1000`) - set the correct permissions and managed to upgrade to `2.0.665`. Thanks.
