### ISSUE TITLE
Allow to revive `jx install` when it fails

### ISSUE THREAD

**Issue by vgallissot** [jenkins-x/jx#524]
I had some issues with `jx install` which failed for various reasons.
So far, I cannot see how to keep going a `jx install` without removing everything with `rm -Rf ~/.jx ; helm del --purge jenkins-x` + removing all jx github repos.

For example:

* install fails after github staging repo creation
* load it again:
```
$ jx install --provider=gke
...
Creating default staging and production environments
error: Environment staging already exists!
```

**Comment by jstrachan** [comment]
@vgallissot good point, we definitely need to polish things much more in that area. 

If `jx install` gets as far as creating the environments; then you don't really need to try installing again; you can add/remove environments at any time via `jx create env` etc

**Comment by vgallissot** [comment]
Yes indeed, I did that for simplicity at startup.
I'll now on keep using `jx install` once my pods are up & running

thanks

**Comment by ccojocar** [comment]
This issue seems to be fixed.
