### ISSUE TITLE
Staging and prod repos have unsolicited contributors using quickstart

### ISSUE THREAD

**Issue by angoothachap** [jenkins-x/jx#5252]
### Summary 
jx create quickstart spring-boot-rest-prometheus adds default contributors from git history
### Steps to reproduce the behavior
`jx create quickstart`
Choose `spring-boot-rest-prometheus`
Check the staging, production repositories; additional default contributors are added. 
### Expected behavior
Only the owner from the OWNERS file should be added as a contributor.
### Actual behavior
All committers from git history are added as default contributors
### Jx version
jenkins-x 2.0.581
The output of `jx version` is:

```
2.0.581
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE, jx create cluster

### Operating system / Environment

Windows

**Comment by jstrachan** [comment]
minor correction - it’s not quickstarts - it’s the environment repos which we fork currently so they are easier to keep in sync with changes in the environment pipelines. This isn’t an issue for Jenkins X pipelines though
