### ISSUE TITLE
Why JSON log to console? Very hard to read. 

### ISSUE THREAD

**Issue by mateodelnorte** [jenkins-x/jx#5253]
### Summary 

Why do various commands like `jx get build logs` print both readable plain text as well as JSON logs. This is very hard to read. Should this not just print plain text?

### Steps to reproduce the behavior

`jx get build logs`

### Expected behavior

print logs in either plain text or json. not both. 

### Actual behavior

mixed json and plain text logs.

**Comment by jstrachan** [comment]
`jx get build logs` shows the build log - each container step in a pipeline can output anything it wants to; its up to it really. I guess we could detect json logs and format them nicer maybe?

we could try disable json logging for certain steps in the pipeline? ideally json is nice for logs as its easier to query/analyse for observability; but most pipeline commands don't create json

**Comment by abayer** [comment]
Actually, we switch off the hardcoded setting of logs for builds kicked off by the metapipeline to be in JSON a couple days ago, so I'm gonna close this. =) See #5211
