### ISSUE TITLE
jx delete addon sso - does not delete any resources

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx#5268]
### Summary 
I have installed the SSO addOn via `jx create addon sso`, all works fine.  But when I delete it, the resources are all still in the cluster.

### Steps to reproduce the behavior

1. Install addon via `jx create addon sso`
2. When it comes time to delete the addon using `jx delete addon sso`
I get success message as follows:

```
 jx delete addon sso
sso addon was succesfully deleted.
```

Furthermore, if I execute this command, I see all the resources, confirming nothing was deleted.

```
➜ kubectl get all -n sso
NAME                                                READY   STATUS    RESTARTS   AGE
pod/jx-sso-dex-dex-fb4597567-c6c82                  1/1     Running   0          2d22h
pod/jx-sso-operator-sso-operator-5bf64ccd55-cpfxt   1/1     Running   0          2d22h


NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
service/dex            ClusterIP   10.59.245.239   <none>        80/TCP,5000/TCP   2d22h
service/sso-operator   ClusterIP   10.59.252.138   <none>        80/TCP            2d22h


NAME                                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jx-sso-dex-dex                 1         1         1            1           2d22h
deployment.apps/jx-sso-operator-sso-operator   1         1         1            1           2d22h

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/jx-sso-dex-dex-fb4597567                  1         1         1       2d22h
replicaset.apps/jx-sso-operator-sso-operator-5bf64ccd55   1         1         1       2d22h
```

### Expected behavior
I am expecting that all resources related to the addOn such as Deployments, Services, Pods are deleted. But they are not.

### Actual behavior
All resources still exist in the cluster

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.598
jenkins x platform 2.0.951
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.3
helm client        Client: v2.13.1+g618447c
git                2.21.0
Operating System   Mac OS X 10.14.3 build 18D42
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Running GKE.

### Operating system / Environment

In which environment are you running the jx CLI?

OS X

**Comment by ccojocar** [comment]
sso addon was removed from Jenkins X and it is now migrated to https://github.com/jenkins-x-apps/jx-app-sso `jx-app-sso` app. I am going to close this issue.
