### ISSUE TITLE
kube context was nil for vault install in the gitops pipeline

### ISSUE THREAD

**Issue by skhedim** [jenkins-x/jx#5273]
### Summary 

During a pipeline on the gitops repo  I have an error on the install vault step indicating that kube context is nil to configure the name of the vault.

I didn't encounter this problem when doing a jx boot

### Steps to reproduce the behavior

Fresh install on a GKE cluster and jx boot, then the pipeline in the cluster will fail on the vault-install

### Expected behavior

Continue the pipeline

### Actual behavior

the gitops pipeline stops because it can't find vault name.

error: building the system vault name from cluster name: retrieving the cluster name: kube context was nil

Pipeline failed on stage 'release' : container 'step-install-vault'. The execution of the pipeline has stopped.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.648
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.14.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE cluster deployed from the GCP console. Version 1.13.7

### Operating system / Environment

Fedora

**Comment by pmuir** [comment]
There have been fixes put in for this. Please retry with a newer jx. Reopen if still an issue.
