### ISSUE TITLE
jx boot dev pipeline fails

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#5279]
### Summary 

After executing `jx boot`, a few files were changed in the local copy of the `dev` repository. After pushing those changes to GitHub, a new activity is executed and it fails.

### Steps to reproduce the behavior

```bash
PROJECT=[...]

CLUSTER_NAME=[...]boot)

gcloud auth login

gcloud container clusters \
    create $CLUSTER_NAME \
    --project $PROJECT \
    --region us-east1 \
    --machine-type n1-standard-2 \
    --enable-autoscaling \
    --num-nodes 1 \
    --max-nodes 2 \
    --min-nodes 1

kubectl create clusterrolebinding \
    cluster-admin-binding \
    --clusterrole cluster-admin \
    --user $(gcloud config get-value account)

GH_USER=[...]

open "https://github.com/jenkins-x/jenkins-x-boot-config.git"

# Fork it

git clone \
    https://github.com/$GH_USER/jenkins-x-boot-config.git \
    environment-$CLUSTER_NAME-dev

cd environment-$CLUSTER_NAME-dev

cat jx-requirements.yml

cat jx-requirements.yml \
    | sed -e \
    "s@clusterName: \"\"@clusterName: \"$CLUSTER_NAME\"@g" \
    | tee jx-requirements.yml

cat jx-requirements.yml \
    | sed -e \
    "s@nvironmentGitOwner: \"\"@nvironmentGitOwner: \"$GH_USER\"@g" \
    | tee jx-requirements.yml

cat jx-requirements.yml \
    | sed -e \
    "s@project: \"\"@project: \"$PROJECT\"@g" \
    | tee jx-requirements.yml

ZONE=[...] # e.g., us-east1

cat jx-requirements.yml \
    | sed -e \
    "s@zone: \"\"@zone: \"$ZONE\"@g" \
    | tee jx-requirements.yml

jx boot

git push

jx get activities --watch

# Wait until the new activity is finished. It will fail.

jx get build logs
```

The last entries of the output of the last command are as follows.

```
Showing logs for build vfarcic-environment-jx-boot-dev-1 stage release and container step-helm-populate-params
defaulting to secret storage scheme local found from requirements file at /workspace/source/**-requirements.yml
defaulting to secret base path to the cluster name **-boot found from requirements file at /workspace/source/**-requirements.yml

Jenkins X Admin Username ***** [Automatically accepted existing value]
error: asking questions for schema: EOF
? Jenkins X Admin Password [? for help]

Pipeline failed on stage 'release' : container 'step-helm-populate-params'. The execution of the pipeline has stopped.
```

### Expected behavior

1. Pushing the changes created by `jx boot` and already applied to the server should not create an activity.
2. The activity should not fail

### Actual behavior

The opposite of the expected.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.649
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.3
helm client        Client: v2.14.1+g5270352
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G87
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE created with `gcloud`

### Operating system / Environment

macOS

**Comment by pmuir** [comment]
Is this still an issue @vfarcic ? If so, please can you add the `priority/critical` label?

**Comment by macox** [comment]
@pmuir I have just encountered this issue when using local storage (rather than vault). My in cluster jx version is 2.0.656

**Comment by vfarcic** [comment]
This is still happening. Apart from fixing the issue, I believe that `jx boot` should push the changes it does to that local copy of the repo before creating the webhook. Otherwise, if we push the changes that will always execute the second build even though `jx boot` already processed everything.

**Comment by vfarcic** [comment]
This seems to be fixed in the latest release. I run it a couple of times and it works. Whatever the change was, it fixed it.
