### ISSUE TITLE
OpenShift 4 exposes internal registry in different service/namespace

### ISSUE THREAD

**Issue by rgordill** [jenkins-x/jx#5296]
### Summary 

When installing to an OpenShift 4 cluster, a default configuration is created, like

/home/rgordill/.jx/cloud-environments/env-openshift/myvalues.yaml

```
  Global:
    EnvVars: 
      DOCKER_REGISTRY: "docker-registry.default.svc:5000"
```
but the new internal registry service should be:
```
  Global:
    EnvVars: 
      DOCKER_REGISTRY: "image-registry.openshift-image-registry.svc:5000"
```
### Steps to reproduce the behavior

Installing in an OCP 4 cluster:

`jx install --provider=openshift --domain=<domain_route> --no-tiller --tekton`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.658
jenkins x platform 2.0.1028
Kubernetes cluster v1.14.0+a91f2ac
kubectl            v1.15.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0
Operating System   "Fedora release 30 (Thirty)"
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

OpenShift 4.1

### Operating system / Environment

Fedora 30

**Comment by pmuir** [comment]
Needs a new cloud environment creating based on the openshift one probably. See https://github.com/jenkins-x/cloud-environments/blob/master/env-openshift/myvalues.yaml
