### ISSUE TITLE
Log handling and historical data needs to be redesigned

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5297]
JX's log handling is problematic - there are issues with how we display logs, lack of metadata around the log lines (timestamps, for example), performance issues due to requiring a `PipelineActivity` in the cluster for each build that can have its logs viewed, related historical data issues since logs and activity isn't available to users for any builds that have had their `PipelineActivity` deleted (which we have to do regularly to keep `jx get build logs` performance from becoming unworkable), long term storage logs are for the whole pipeline without anything for individual steps, etc. 

In general, we need to revisit how logs and build history work in Jenkins X. The first step is defining what we want the behavior/available data/etc to be for users, and then we need to determine the optimal way to implement that. This is not something we can expect to "fix" in the short term with tweaks around the edges - the entire system for logging and build history needs to be reevaulated and redesigned.

**Comment by abayer** [comment]
cc @hferentschik @dgozalo

**Comment by codebryo** [comment]
Just had a convo with @daveconde about this. I actually made a design that I mostly intended for the UI team of things and wanted to verify if we are on the same track - https://whimsical.com/QdCozbq3C4UszvgycM2DR
On that node, CodeShip has a ton of Go Code around logs. We bascially spent a year in building a logging infrastructure and streaming servicem so I would expect there is stuff to salvage.

**Comment by msavy** [comment]
@abayer Not sure if this is a function of the issues you're describing, but with the latest jx tekton gitops, there seems to be no way via UI such as Prow (or even the PR bot) to view the jx build logs in the browser in the same way that you would via Jenkins classic build system web interface.  

Prow just has very basic status info - no logs, AFAICT.

Happy to write up a feature request ticket for this if it is not obviously already encapsulated by this. Do let me know.
