### ISSUE TITLE
Docker registry repository name error

### ISSUE THREAD

**Issue by marlovil** [jenkins-x/jx#5322]
### Summary 
We've imported a new Github repo with name design.mycompany.com and a docker registry repo called 
xxxx.dkr.ecr.eu-west-1.amazonaws.com/mycompany/design-mycompany-com is created. We use ECR docker registry AWS service. 

The logs of the jx import command are:
```
...
Let's ensure that we have an ECR repository for the Docker image mycompany/design-mycompany-com
Created ECR repository: xxx.dkr.ecr.eu-west-1.amazonaws.com/mycompany/design-mycompany-com
...
```
But when jx is deploying the image in staging, the pod is failing to be created with the following error:
```
Events:
  Type     Reason     Age                From                                                 Message
  ----     ------     ----               ----                                                 -------
  Normal   Scheduled  61s                default-scheduler                                    Successfully assigned jx-staging/jenkins-x-design-mycompany-com-5d565b94c6-h42k9 to ip-10-101-45-65.eu-west-1.compute.internal
  Normal   Pulling    18s (x3 over 60s)  kubelet, ip-10-101-45-65.eu-west-1.compute.internal  pulling image "xxx.dkr.ecr.eu-west-1.amazonaws.com/mycompany/design.mycompany.com:0.0.4"
  Warning  Failed     18s (x3 over 60s)  kubelet, ip-10-101-45-65.eu-west-1.compute.internal  Failed to pull image "xxx.dkr.ecr.eu-west-1.amazonaws.com/mycompany/design.mycompany.com:0.0.4": rpc error: code = Unknown desc = Error response from daemon: repository xxx.dkr.ecr.eu-west-1.amazonaws.com/mycompany/design.mycompany.com not found
  Warning  Failed     18s (x3 over 60s)  kubelet, ip-10-101-45-65.eu-west-1.compute.internal  Error: ErrImagePull
  Normal   BackOff    6s (x4 over 59s)   kubelet, ip-10-101-45-65.eu-west-1.compute.internal  Back-off pulling image "xxx.dkr.ecr.eu-west-1.amazonaws.com/mycompany/design.mycompany.com:0.0.4"
  Warning  Failed     6s (x4 over 59s)   kubelet, ip-10-101-45-65.eu-west-1.compute.internal  Error: ImagePullBackOff

```
It tries to get the image from mycompany/design.mycompany.com (wrong) instead of mycompany/design-mycompany-com (correct) docker repo.

### Steps to reproduce the behavior
Import repo and wait until after the first build is deployed in staging env.

### Expected behavior
Pull an image with the correct name of the docker registry repo created by jx import command.

### Workaround
I did a workaround replacing dots by dashes in chart deployment yaml:
```
image: "{{ .Values.image.repository | replace "design.mycompany.com" "design-mycompany-com" }}:{{ .Values.image.tag }}"
```
This works, but IMHO this should be fixed.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.666
jenkins x platform 2.0.1053
Kubernetes cluster v1.12.10-eks-825e5d
kubectl            v1.14.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) and multiple cluster installation
- [ ] Classic Jenkins

### Kubernetes cluster
EKS cluster created with Cloudformation

Thanks for your support!

**Comment by mrageh** [comment]
@marlovil we've fixed this issue and it should no longer be a problem for you on the latest version of JX

**Comment by marlovil** [comment]
Great! Thanks @mrageh. :)
