### ISSUE TITLE
retrying after error:Failed to create the XXXX folder in Jenkins: 308 Permanent Redirect

### ISSUE THREAD

**Issue by russellrobinson** [jenkins-x/jx#5326]
### Summary 
jx create environment always fails with this error

### Steps to reproduce the behavior
I'm following the instructions left by a former employee who setup Jenkins X under Kubernetes for us.

The command is:
jx create environment bdd --git-provider-url=https://bitbucket.org --pull-secrets=company-registry'

### Expected behavior
No errors, and the new environment is created.

### Actual behavior
After answering all the questions to the best of my knowledge, I get the following message repeated 9 times:
retrying after error:Failed to create the XXXX folder in Jenkins: 308 Permanent Redirect

And, the environment is not created in the Jenkins X web portal.

### Jx version
2.0.581

The output of `jx version` is:
```
2.0.581
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

### Kubernetes cluster

I don't know what "kinds" there are.

```
az aks create ...
```

### Operating system / Environment

Linux

**Comment by benmullin333** [comment]
This seems to happen when I upgraded the ingress to TLS and then try to create the app.. jx tries to connect to jenkins without `https`

**Comment by russellrobinson** [comment]
Thanks for the reply.

Any idea how to fix it?

I'm happy to jump into some file to do it, but I have no idea where to start since JX is all tied up with k8s.

**Comment by benmullin333** [comment]
I'm not sure.  I was able to get past it by looking at the errors on the jenkins console output.  There were issues with registry access and registry names.
