### ISSUE TITLE
Trying to install Jenkins-X on Kubernetes / Docker / MacOSX High Sierra

### ISSUE THREAD

**Issue by eldontc** [jenkins-x/jx#534]
I am trying to adapt the instructions to install jenkins-x on K8S over a macOSX (High Sierra). I've installed a k8s via Docker Edge [https://blog.docker.com/2018/01/docker-mac-kubernetes/].

I installed a jx CLI and helm. After that, I tried to execute a jx install. After answers some questions, including entering with the GitHub token for my account, the following error occurs: 

> ? GitHub user name: eldontc
> ? API Token: ****************************************
> Cloning the Jenkins X cloud environments repo to /Users/eldontc/.jx/cloud-environments
> Counting objects: 397, done.
> Compressing objects: 100% (4/4), done.
> Total 397 (delta 0), reused 1 (delta 0), pack-reused 393
> Generated helm values /Users/eldontc/.jx/extraValues.yaml
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
> Error: Command failed  make ARGS=--values=/Users/eldontc/.jx/gitSecrets.yaml --values=/Users/eldontc/.jx/adminSecrets.yaml --values=/Users/eldontc/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
> error: exit status 1
> 

The complete interactive execution of the command jx install is:

```
eldontc$ jx install
Context "docker-for-desktop" modified.
? Cloud Provider kubernetes
Initialising helm using ServiceAccount tiller in namespace kube-system
Creating /Users/eldontc/.helm
Creating /Users/eldontc/.helm/repository
Creating /Users/eldontc/.helm/repository/cache
Creating /Users/eldontc/.helm/repository/local
Creating /Users/eldontc/.helm/plugins
Creating /Users/eldontc/.helm/starters
Creating /Users/eldontc/.helm/cache/archive
Creating /Users/eldontc/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /Users/eldontc/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
$HELM_HOME has been configured at /Users/eldontc/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
"jenkins-x" has been added to your repositories
helm installed and configured
Cloning into '/Users/eldontc/.jx/draft/packs/github.com/jenkins-x/draft-packs'...
remote: Counting objects: 259, done.
remote: Compressing objects: 100% (145/145), done.
remote: Total 259 (delta 143), reused 217 (delta 103), pack-reused 0
Receiving objects: 100% (259/259), 39.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (143/143), done.
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
NAME:   jxing
LAST DEPLOYED: Fri Mar 30 16:14:34 2018
NAMESPACE: kube-system
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                                                  READY  STATUS             RESTARTS  AGE
jxing-nginx-ingress-controller-bc46854d-7lngl         0/1    ContainerCreating  0         0s
jxing-nginx-ingress-default-backend-6f4ff5fcbc-bfrhs  0/1    ContainerCreating  0         0s

==> v1/ConfigMap
NAME                            DATA  AGE
jxing-nginx-ingress-controller  1     0s

==> v1beta1/ClusterRole
NAME                 AGE
jxing-nginx-ingress  0s

==> v1beta1/ClusterRoleBinding
NAME                 AGE
jxing-nginx-ingress  0s

==> v1/Service
NAME                                 TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)                     AGE
jxing-nginx-ingress-controller       LoadBalancer  10.101.143.82  localhost    80:31760/TCP,443:31643/TCP  0s
jxing-nginx-ingress-default-backend  ClusterIP     10.102.68.135  <none>       80/TCP                      0s

==> v1beta1/PodDisruptionBudget
NAME                                 MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
jxing-nginx-ingress-controller       1              N/A              0                    0s
jxing-nginx-ingress-default-backend  1              N/A              0                    0s

==> v1/ServiceAccount
NAME                 SECRETS  AGE
jxing-nginx-ingress  1        0s

==> v1beta1/Role
NAME                 AGE
jxing-nginx-ingress  0s

==> v1beta1/RoleBinding
NAME                 AGE
jxing-nginx-ingress  0s

==> v1beta1/Deployment
NAME                                 DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jxing-nginx-ingress-controller       1        1        1           0          0s
jxing-nginx-ingress-default-backend  1        1        1           0          0s


NOTES:
The nginx-ingress controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace kube-system get services -o wide -w jxing-nginx-ingress-controller'

An example Ingress that makes use of the controller:

  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: example
    namespace: foo
  spec:
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                serviceName: exampleService
                servicePort: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.example.com
          secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
External loadbalancer created
The Ingress address localhost is not an IP address. We recommend we try resolve it to a public IP address and use that for the domain to access services externally.
? Would you like wait and resolve this address to an IP address and use it for the domain? No
WARNING: Still not managed to resolve address localhost into an IP address. Please try figure out the domain by hand
You can now configure a wildcard DNS pointing to the new loadbalancer address localhost
? Domain localhost
nginx ingress controller installed and configured
Lets set up a git username and API token to be able to perform CI / CD

To be able to create a repository on GitHub we need an API Token
Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook

Then COPY the token and enter in into the form below:

? GitHub user name: eldontc
? API Token: ****************************************
Cloning the Jenkins X cloud environments repo to /Users/eldontc/.jx/cloud-environments
Counting objects: 397, done.
Compressing objects: 100% (4/4), done.
Total 397 (delta 0), reused 1 (delta 0), pack-reused 393
Generated helm values /Users/eldontc/.jx/extraValues.yaml
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Command failed  make ARGS=--values=/Users/eldontc/.jx/gitSecrets.yaml --values=/Users/eldontc/.jx/adminSecrets.yaml --values=/Users/eldontc/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 1
```

**Comment by wbrefvem** [comment]
You may need to install Xcode command line tools: `xcode-select --install`.

But even if you fix that, you'll likely encounter other errors because k8s on Docker Edge for Mac isn't a supported way to get started with Jenkins X. The easiest supported way is to [create a cluster on jx using GKE](http://jenkins-x.io/getting-started/create-cluster/).

**Comment by eldontc** [comment]
Thank you for your quick response. Good to know that your solution works better with public cloud services like GKE and AWS. Although, I think it's a little bit restrictive for enterprises or individual developers. Some enterprises, like where I've been working, a federal government institution in Brazil, don't use a public cloud service, we've been using a Rancher/K8S on premise. Do you think that this environment, Rancher over K8S, is supported by Jenkins-X?

**Comment by wbrefvem** [comment]
Right now the focus is on the cloud. There are certainly many organizations that are hesitant to go all in with the cloud, but my feeling (and I don't speak for anyone but myself here) is that they will eventually come around. 

In the US, the entities with the greatest security needs -- and thus the greatest hesitance to rely on the public cloud -- tend to be federal agencies and financial services institutions, and there are many examples of both types of organizations that have gone to the cloud without compromising security.

The goal of Jenkins X is to make cloud-native application development more accessible. Hopefully the folks you're talking to will see this as a reason to give the cloud a second look.

**Comment by jstrachan** [comment]
We should eventually be able to support most ways of installing kubernetes- though it’s going to take some work to test them all. Using kops for example was pretty straightforward. The hardest platform seems to be laptops - docker / minikube due to the virtualization, networking & dependencies etc

Hopefully the Xcode tools mentioned above get you further along - at least helm is working!

**Comment by rawlingsj** [comment]
Just to add to that we initially focus on public clouds as we can also create them from scratch in a way that Jenkins X recognises.  Things like networking, loadbalancers and storage are all set up correctly and why we've focused on GKE, AKS and AWS in the docs, demos and blogs so far.  That said it should be possible to install Jenkins X on any working Kubernetes cluster that has RBAC enabled.

```
jx install --kubernetes
```
There are flags to disable installing an ingress controller and setting your own domain for ingress rules too although a few attempts to get edge on OSX working have failed so far.  It would be great to get it working and have some docs for it though - let us know how you get on!

**Comment by ccojocar** [comment]
@eldontc I am going to close this issue. It seems to be quite old and maybe outdated. Feel free to open another issue.
