### ISSUE TITLE
Cert Manager Compatibility before November 2019

### ISSUE THREAD

**Issue by polothy** [jenkins-x/jx#5353]
### Summary 

Got this email from Let's Encrypt:

```
We've been working with Jetstack, the authors of cert-manager, on a
series of fixes to the client. Cert-manager sometimes falls into a
traffic pattern where it sends really excessive traffic to Let's
Encrypt's servers, continuously. To mitigate this, we plan to start
blocking all traffic from cert-manager versions less than 0.8.0 (the
current semver minor release), as of November 1, 2019. Please upgrade
all of your cert-manager instances before then.

We're sending this email because this is the contact address of your
cert-manager instance at:

REMOVED

Version 0.8.0 is much better but we still observe excessive traffic in
some cases. We're working with Jetstack to improve these cases. As new
versions of cert-manager are released, we will add the non-current
versions to our block list after 3 months. We strongly encourage
cert-manager users to stay up-to-date with new versions.

Also, there is an opportunity to help both Jetstack and Let's Encrypt.
Once you've upgraded, please check the logs for your cert-manager
instances from time to time. Are they making excessive requests to Let's
Encrypt (more than, say, 10 per day over multiple days)? If so, please
share details at https://github.com/jetstack/cert-manager/issues/1948

Thanks,
Let's Encrypt Team
```

I believe JX is currently using 0.6 and this suggests using 0.8 at a minimum, but also warns that future versions might be blocked.  We currently manage the our install of `cert-manager`, but we want to make sure JX is compatible with future versions of it.

You can review releases here:
https://github.com/jetstack/cert-manager/releases

You can see upgrade steps/actions for each release under here:
http://docs.cert-manager.io/en/latest/tasks/upgrading/index.html

### Steps to reproduce the behavior

N/A

### Expected behavior

JX is compatible with latest versions of `cert-manger` (at _least_ 0.8).

### Actual behavior

JX is using `cert-manger` 0.6.

### Jx version

N/A

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

AWS via KOPS

### Operating system / Environment

N/A

**Comment by polothy** [comment]
My initial pass on the release notes mostly has changes on how `cert-manager` is installed (EG: Helm chart and manifests have moved).  The upgrade to [0.8](http://docs.cert-manager.io/en/latest/tasks/upgrading/upgrading-0.7-0.8.html) mentions changes to the ACME Issuer which I think JX uses, but to a section in the spec that JX doesn't use (spec -> acme -> solvers).

Upgrading to 0.9 and 0.10 doesn't seem to mention anything regarding spec/CRDs/etc.  Just some tasks you need to do for the upgrade itself.

**Comment by ccojocar** [comment]
The new installation process using boot relies on version stream which is using cert-manager 0.9.1 https://github.com/jenkins-x/jenkins-x-versions/blob/d809eb56048afe4be18a8c40c03b2202fe322021/charts/jetstack/cert-manager.yml#L2. 

I believe this is related to the old installation mode which has a different cert-manger integration.

**Comment by polothy** [comment]
Ah, that is good news!  I was looking here:

https://github.com/jenkins-x/jx/blob/ae0c16ca03873c53f8924d0ab1c68eab0574bde9/pkg/cmd/opts/cert_manager.go#L49

Which I think is using `stable/cert-manager` chart which is deprecated and stuck on `0.6`.

So, it sounds like it is safe to say that JX is compatible with cert-manager 0.8-0.9.1?

**Comment by deanesmith** [comment]
@polothy Can you please verify the fix in your environment?  Any release after 2.0.753 should do it.
Thank you.

**Comment by abayer** [comment]
I had to roll back the upgrade - it didn’t work for a number of reasons.
