### ISSUE TITLE
`jx boot` suggests old jx version for some reason

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#5371]
### Summary 

WARNING: A different jx version 2.0.592 is available in the version stream. We highly recommend you upgrade to it.

### Steps to reproduce the behavior

`jx boot`

### Expected behavior

Don't suggest old version

### Actual behavior

Suggests 2.0.592 while I have 2.0.689

### Jx version

The output of `jx version` is:

```
jx                 2.0.689
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.15.3
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Created by `eksctl`

### Operating system / Environment

Mac OS X 10.14.6 build 18G95

**Comment by stepanselyuk** [comment]
Btw may be better to have `jx issue` command to open new GitHub issue page already filled with required details?

**Comment by cagiti** [comment]
@stepanselyuk we use the version stream (https://github.com/jenkins-x/jenkins-x-versions as the source of truth for all dependencies and their versions used by Jenkins X. `jx` is therefore recommending the the most recent 'tested' version. For more information see https://jenkins-x.io/architecture/version-stream

**Comment by stepanselyuk** [comment]
@cagiti so suggested version of `jx` binary should be the same version from there https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/jx.yml ?

**Comment by cagiti** [comment]
@stepanselyuk the jx version is derived using the dependency matrix. The `jx` dependency version is here:
https://github.com/jenkins-x/jenkins-x-versions/blob/0c61c25471072d0cad75a8e8883d3163ee630314/dependency-matrix/matrix.yaml#L8-L41
and the `jx` version is defined within line 40.

I'm not what uses https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/jx.yml  and to be honest should be nuked :)

**Comment by pmuir** [comment]
Closing as behavior is correct.
