### ISSUE TITLE
`jx boot` Some ingress resources were not upgraded

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#5375]
### Summary 

I started with CJXD distribution but used terraform/jx boot to create the cluster which got me not necessarily using CJXD versions. I had meta pipelines and was told that's not a part of CJXD. I initially set up the cluster using nip.io.

After a couple of weeks, I came across a bug around `dir` in jenkins-x.yaml pipelines and tried to upgrade and couldn't because `jx boot` resulted in errors.

(dir bug - which I'm still encountering despite it being closed - https://github.com/jenkins-x/jx/issues/4966)

I've now gotten past this.

To do so I had to:
1. Buy a domain
2. In terraform - add external-dns service account, key, rolebindings, and kubernetes secret
3. Change jx boot config to enable externaldns, set the domain, and enable tls (first with staging)
4. Apply'd that - update failed near the end because vault didn't have https yet
5. Waited for dns to propagate
6. change boot config to use LE prod
7. Apply jx boot
8. It failed again this time it told me it couldn't find something, so I assumed that meant my version stream was updated
9. Update version stream
10. Apply jx boot again

And that final run succeeded... however, I am still seeing a bit of weirdness as two ingress routes did not get updated...

```
➜  ~ k get ingress --all-namespaces               
NAMESPACE                         NAME                     HOSTS                                                              ADDRESS         PORTS     AGE
jx-xgh-dashboard-2-pr-9   dashboard-2              dashboard-2.jx-xgh-dashboard-2-pr-9.105.111.11.1.nip.io   105.111.11.1   80        9d
jx-staging                        dashboard-2              dashboard-2.jx-staging.xdev.com                            105.111.11.1   80, 443   16h
jx                                chartmuseum              chartmuseum-jx.xdev.com                                    105.111.11.1   80, 443   15d
jx                                deck                     deck-jx.105.111.11.1.nip.io                                       105.111.11.1   80        15d
jx                                hook                     hook-jx.xdev.com                                           105.111.11.1   80, 443   15d
jx                                jx-vault-x-dev   vault-jx.xdev.com                                          105.111.11.1   80, 443   15d
jx                                nexus                    nexus-jx.xdev.com                                          105.111.11.1   80, 443   15d
jx                                tide                     tide-jx.105.111.11.1.nip.io                                       105.111.11.1   80        15d
server-2-pr-1                     server-2                 server-2.server-2-pr-1.xdev.com                            105.111.11.1   80        10h
```

see `deck` and `tide` are still using nip.io address?

See here for more context:

https://github.com/jenkins-x/jenkins-x-boot-config/commit/b6aba273eb4d46e4a66d77732c12c6f905f6ec79#diff-b31df235e8aee38fd08600c353af2b52

### Steps to reproduce the behavior

Not sure if this would reproduce, because time had passed between the initial set up of jx boot + changes to the upstream config... but.

1. Create cluster with terraform
2. clone default jx boot config
3. `jx boot` and use nip.io
4. add domain to boot config and `jx boot` again

### Expected behavior

All ingress resources get updated.

### Actual behavior

Some ingress resources got updated.

### Jx version

The output of `jx version` is:

```
➜  ~ jx version                                         
NAME               VERSION
jx                 2.0.686
Kubernetes cluster v1.13.7-gke.19
kubectl            v1.15.0
helm client        Client: v2.13.0+g79d0794
git                2.19.1
Operating System   Mac OS X 10.14.5 build 18F203


verifying packages
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with revision v1.0.51
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE - terraform
```
export ORGANIZATION_NAME='patrickleet'
jx create terraform --organisation-name=$ORGANIZATION_NAME --skip-terraform-apply=true
```

Then plan & apply

Then
```
jx boot
```

### Operating system / Environment

Mac

**Comment by garethjevans** [comment]
Hi @patrickleet, i think you'll need https://github.com/jenkins-x/jenkins-x-boot-config/pull/57 - I've not had a chance to test it in great detail (apart from a single cluster install which seemed to work).

**Comment by patrickleet** [comment]
Upgraded to latest boot config/version stream today and this worked
