### ISSUE TITLE
jx boot not creating private environment dev repository when specified

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#5376]
### Summary 
When using environmentGitPrivate to create private environment git repositories only the staging and production environment repositories are created.

### Steps to reproduce the behaviour
A paid bot account `jenkins-x-bot-test` is being used as GIT_OWNER and PIPELINE_GIT_USER

### Expected behaviour
A private environment dev repository is created

### Actual behavior
Only the environment staging and production repositories are created as private, the environment dev repository doesn't seem to have been created at all.

### Jx version

The output of `jx version` is:

```
2.0.656
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment
alpine 3.10 linux

**Comment by garethjevans** [comment]
@cagiti I'm also seeing this when the git private flag is not set, staging & production are fine, but the dev repo never gets created (even with gitops:true), i think we have a regression here

**Comment by pmuir** [comment]
Is this now sorted @garethjevans @cagiti

**Comment by carlosrodlop** [comment]
I suffered from the same issue

```
NAME               VERSION
jx                 2.0.643
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.0
git                2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

**Comment by abayer** [comment]
Is this still the case since @hferentschik's change to make private the default?

**Comment by deanesmith** [comment]
Assumed to now be resolved.  Requires testing.
