### ISSUE TITLE
TLS certificates issuing timeout

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#5377]
### Summary 

Every time I do `jx install` (on a new cluster), and if I specify I want to use helm-tls, I face with this issue:

```
Ingress rules recreated
Waiting for TLS certificates to be issued...
WARNING: Following TLS certificates are not ready:
WARNING: jx/tls-vault
error: creating the system vault: exposing vault: not all TLS certificates are ready
```

As I feel timeout around 3m20s, how it can be increased?

### Steps to reproduce the behavior

```
jx install \
  --provider=eks \
  --install-dependencies \
  --aws-auto-create=true \
  --aws-s3-region=us-west-2 \
  --default-admin-password="$JENKINS_ADMIN_PASSWORD" \
  --default-environment-prefix=cdp \
  --domain=redacted.com \
  --git-private \
  --git-username=redacted-jenkins \
  --gitops \
  --helm-tls \
  --verbose
```

### Expected behavior

Certificates issued and `jx` continue the process. An overall thing for `jx`: it does not allow to wait, retry or fix an issue. It simply dies with an error (it is okay in case of unattended install, but not in interactive mode). Like "Reached timeout for waiting for TLS certs, what you want to do: wait 3 minutes more; continue without TLS; cancel installation". Or yesterday I got an error: "Cannot create github repo", and `jx` died with an error. But it can be just an issue with network or github. Ability to retry and timeout is a good thing for such a distributed system.

Another example:
with option `--advanced-mode`. Question from the jx: "Would you like to enable long term logs storage? A bucket for provider eks will be created". Ok `Yes` (I know it is not supported, but if asked...). Result: `error: configuring Long Term Storage: long term storage is not yet supported for provider eks`. No option to recover from the error, just immediate hard die. 

Last two days and around 10 attempts to install Jenkins. I started with --ng and ServerLess, now I'm more submissive and trying to install static one. Every time I kill and recreate EKS cluster. The installation process is like an exam with the death penalty if I miss every single question :-)

In this particular case if I restart `jx install` it sees the TLS certificate issued well. So maybe issue not with a timeout, but with the way of checking of the certificate issued.

But I actually don't know if I can run `jx install` again (with the same flags and options choose), is behavior idempotent?

### Actual behavior

Dies with an error.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.695
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.15.3
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

Created by eksctl.

### Operating system / Environment

Operating System   Mac OS X 10.14.6 build 18G95

**Comment by pmuir** [comment]
We are working on adding support for EKS with TLS and vault via `jx boot` which should give you more success in the future.

**Comment by ccojocar** [comment]
EKS is not supported when using the boot installation with Tekton but not classic Jenkins.

**Comment by ccojocar** [comment]
I am going to close this issue for now. Please feel free to open it. It would be great if you could give boot a try.
