### ISSUE TITLE
Prow always thinks the build number is 1 (for build link) with metapipeline enabled

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5394]
Most likely something's awry in the `pipeline` controller in Prow - it's not looking at the right place for the build number or something.

**Comment by ccojocar** [comment]
I think the build id used to be a pram in the pipeline run https://github.com/jenkins-x/test-infra/blob/4c8472f4b7cf38055a850a3e4b3bb438f4ac9c84/prow/cmd/pipeline/controller.go#L943
