### ISSUE TITLE
chart.yaml is missing

### ISSUE THREAD

**Issue by mdh69-github** [jenkins-x/jx#5398]
### Summary 
After spring aplication creation, the file Chart.yaml is missing

### Steps to reproduce the behavior
Just create spring boot application via
$ jx create spring -d web -d actuator

### Expected behavior
Chart.yaml created and initialized

### Actual behavior
Chart.yaml is missing
### Jx version

The output of `jx version` is:
### $ jx version
NAME               VERSION
jx                 2.0.699
jenkins x platform 2.0.1125
Kubernetes cluster v1.13.4
kubectl            v1.13.3
helm client        Client: v2.12.1+g02a47c7
git                2.7.4
Operating System   Ubuntu 16.04.5 LTS

```
COPY OUTPUT HERE
```
error: failed to build dependencies for chart from directory '.': failed to build the dependencies of chart '.': failed to run 'helm dependency build' command in directory '.', output: 'Error: chart metadata (Chart.yaml) missing'

### Jenkins type

- [X ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Nutanix Karbon
### Operating system / Environment
Centos

Ubuntu under W10

**Comment by daveconde** [comment]
Can you please include the steps to reproduce this along with the logs from ` jx create spring -d web -d actuator`

**Comment by mdh69-github** [comment]
I apalogize for this issue but I am not able to reproduce.
