### ISSUE TITLE
Unable to access jenkins from outside browser

### ISSUE THREAD

**Issue by murali741** [jenkins-x/jx#5401]
### Summary 

Hi

I have installed Jenkins X on one of my local VM. Installed is fine and I able to access from command line using "firefox http://jenkins.jx.192.168.39.62.nip.io" but I am unable to access this URL from outside browser on same network. 

can somebody please help me to resolve this issue as soon as possible.

Thanks

### Expected behavior
Able to access jenkins server from outside
### Actual behavior
Not able access jenkins from outside
### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.0.699
Kubernetes cluster v1.15.2
kubectl            v1.15.3
git                2.21.0
Operating System   CentOS Linux release 7.6.1810 (Core)

### Jenkins type

- [ ] Classic Jenkins

### Kubernetes cluster

created using jx create cluster.

**Comment by jstrachan** [comment]
this sounds like a VM networking issue rather than anything Jenkins X specific. You need a way to setup your VM so it uses IP address ranges you can see from your laptop via some kind of network bridge

**Comment by jstrachan** [comment]
if you are struggling using VMs and networking you might find using Google GKE / Amazon EKS easier?

**Comment by murali741** [comment]
How can I change the IP for minikube VM. It has the 192.168.X.X IP. I want to change it to my accessible network IP.


Thanks
Murali Medi
