### ISSUE TITLE
Improve check for whether the user is running pipeline during boot

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#5412]
### Summary 
The logic in https://github.com/jenkins-x/jx/pull/5397 attempts to only create the PR if the user is runnign `jx boot` (rather than the pipeline running in cluster). Unfortunately `o.isInCDPipeline()` will return true even in interpretive mode, so this doesn't help. Find a better way to determine this

**Comment by garethjevans** [comment]
@pmuir could we use the env variables PULL_BASE_REF or JOB_NAME to determine this?

**Comment by pmuir** [comment]
Yeah, that's exactly the kind of thing I was thinking of. I was wondering about setting `JOB_TYPE` to `jx/boot` if it's been launched by boot (it's used for `postsubmit`, `presubmit`, `batch` etc. otherwise)

**Comment by pmuir** [comment]
@jstrachan points out we already have `JX_INTERPRET_PIPELINE=true` set in an interpreted pipeline
