### ISSUE TITLE
jx boot failed with unable to parse kubernetes as <project id>_<zone>_<cluster name>

### ISSUE THREAD

**Issue by bnerDY** [jenkins-x/jx#5418]
### Summary 
unable to parse kubernetes as <project id>_<zone>_<cluster name>

### Steps to reproduce the behavior
```bash
root@k8s-node1:~/jenkins-x-boot-config/env# jx boot
WARNING: there was a problem obtaining the boot config repository git configuration, falling back to defaults
No Jenkins X pipeline file jenkins-x.yml found. You are not running this command from inside a Jenkins X Boot git clone
To continue we will clone https://github.com/jenkins-x/jenkins-x-boot-config.git @ 1.0.13 to jenkins-x-boot-config
? Do you want to clone the Jenkins X Boot Git repository? No

error: Please run this command again inside a git clone from a Jenkins X Boot repository
root@k8s-node1:~/jenkins-x-boot-config/env# jx boot
WARNING: there was a problem obtaining the boot config repository git configuration, falling back to defaults
No Jenkins X pipeline file jenkins-x.yml found. You are not running this command from inside a Jenkins X Boot git clone
To continue we will clone https://github.com/jenkins-x/jenkins-x-boot-config.git @ 1.0.13 to jenkins-x-boot-config
? Do you want to clone the Jenkins X Boot Git repository? Yes

Cloning https://github.com/jenkins-x/jenkins-x-boot-config.git @ 1.0.13 to jenkins-x-boot-config
booting up Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /root/jenkins-x-boot-config/env/jenkins-x-boot-config/env

Git configured for user: xxx and email xxx@xxx.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall in dir: /root/jenkins-x-boot-config/env/jenkins-x-boot-config/env

error: : unable to parse kubernetes as <project id>_<zone>_<cluster name>
error: failed to interpret pipeline file /root/jenkins-x-boot-config/env/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall' command in directory '/root/jenkins-x-boot-config/env/jenkins-x-boot-config/env', output: ''
```

### Expected behavior
boot success
### Actual behavior
boot failed
### Jx version
The output of `jx version` is:

```bash
root@k8s-node1:~/jenkins-x-boot-config/env# jx version
NAME               VERSION
jx                 2.0.696
jenkins x platform 2.0.1059
Kubernetes cluster v1.15.0
kubectl            v1.15.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.7.4
Operating System   Ubuntu 16.04.6 LTS

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

The cluster is created by ansible
jx install --provider=kubernetes --on-premise

### Operating system / Environment

```bash
root@k8s-node1:~/jenkins-x-boot-config/env# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

```

**Comment by garethjevans** [comment]
try changing the provider in jx-requirements.yaml to kubernetes? It defaults to GKE

**Comment by bnerDY** [comment]
@garethjevans thanks for your help. One more question, I am following the guide. git clone https://github.com/jenkins-x/jenkins-x-boot-config.git my-jx-config

but i can't find the values.yaml. Any suggestion would be very helpful

**Comment by prashankprince** [comment]
Any help here, even i am getting same error- 
 
$ sudo jx boot
booting up Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: env

Git configured for user: XXX and email XXX@XXX.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: .

error: : unable to parse kubernetes as <project id>_<zone>_<cluster name>
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '.', output: ''


$ jx version

NAME               VERSION
jx                 2.0.905
Kubernetes cluster v1.14.8
kubectl            v1.14.0
helm client        v2.15.0+gc244026
helm server        v2.15.0+gc244026
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

**Comment by prashankprince** [comment]
> Any help here, even i am getting same error-
> 
> $ sudo jx boot
> booting up Jenkins X
> 
> STEP: validate-git command: /bin/sh -c jx step git validate in dir: env
> 
> Git configured for user: XXX and email [XXX@XXX.com](mailto:XXX@XXX.com)
> 
> STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: .
> 
> error: : unable to parse kubernetes as
> error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '.', output: ''
> 
> $ jx version
> 
> NAME VERSION
> jx 2.0.905
> Kubernetes cluster v1.14.8
> kubectl v1.14.0
> helm client v2.15.0+gc244026
> helm server v2.15.0+gc244026
> git 2.17.1
> Operating System Ubuntu 18.04.3 LTS

Changing provider in jx-requirements.yaml to kubernetes  did resolve the error

**Comment by jstrachan** [comment]
sounds like the workaround is to use `provider: kubernetes` in the `jx-requirements.yml`

**Comment by cannibal-kush** [comment]
I get this from a clean install. Not very friendly to get this at 

`jx boot`

Not a good look.

**Comment by curx** [comment]
@cannibal-kush 
try: aks =>  Jenkins X Boot configuration for Azure Container Engine
`jx boot --provider=aks ...` or at the set jx-requirements.yml provider to aks"

**Comment by sureshpalemoni** [comment]
jx boot has only been validated on GKE and EKS, we'd love feedback and contributions for other Kubernetes providers ??

**Comment by bitsofinfo** [comment]
well it definitely doesn't work w/ aks! i get the same error.

**Comment by sbussard** [comment]
It doesn't work with DigitalOcean ¯\_(ツ)_/¯

**Comment by collabnix** [comment]
If you are deploying it for EKS, instead of Kubernetes, use eks under jx-requirement.xml file.

**Comment by davidmoshal** [comment]
for Linode Kubernetes Engine, this error is discussed here:  
- https://www.linode.com/docs/guides/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/
