### ISSUE TITLE
Failure when eksctl asks for MFA Token Code when creating an EKS cluster with an MFA secured user / role

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5425]
### Summary 
When attempting to create a cluster, your user or assumed role may have MFA activated.

When `eksctl` asks you for your token code,  `jx` fails because we are not expecting user input.

This maybe be a problem when using boot as we will need to ask for this token in a few places.

Ideally the user should have a session token that lasts for a while so he doesn't have to input the code every time, but we should be prepared to accept it otherwise. 
  
### Steps to reproduce the behavior
Attempt to create an EKS cluster with an user / assumed role that has MFA active.

### Expected behavior
It should halt the execution and ask the user to input the token code.

### Actual behavior
It fails because we are not expecting user input.
### Kubernetes cluster

EKS

**Comment by miguelaustro** [comment]
As a quick workaround, get the token with awscli: 
$ aws <some_resource> --profile <your_profile> --region <region>
(Type your MFA code)

jx will works, until the token is expired.

**Comment by dgozalo** [comment]
I opened this issue back then when I started working on EKS support but I don't think this actually makes sense anymore.

Jenkins X should not be expecting user input in places where it interacts withs AWS as it breaks the whole unified flow of Jenkins X Boot.

Users will have to sort out their permissions and sessions before calling Jenkins X so any execution of the AWS CLI is already authenticated.
