### ISSUE TITLE
Show a better message when you are unauthorized by AWS

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5431]
### Summary 
Right now, if you are assuming a role and have a temporal access that ran out or your user doesn't have enough permissions to perform an operation, we are just showing the message:

`error: Unauthorized`

This doesn't provide enough information to determine the missing authorization and we need to be more clear.

### Steps to reproduce the behavior

Do `jx create cluster eks` with a read-only user or an expired temporal token.

### Expected behavior
We should show what operation we were trying to perform and what authorization we are missing.

**Comment by deanesmith** [comment]
Terraform is now recommended for cluster creation in AWS.
