### ISSUE TITLE
Modify the EKS Vault installation to avoid creating an IAM User

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5434]
### Summary 
Right now, we are attempting to create Vault with a CloudFormation stack.

This stack describes every necessary resource for Vault to work.

We are assuming that every user will be allowed to create IAM Users, which is not always the case. In fact, we ourselves can't do this in our AWS accounts as we have a restriction on user creation.

We should find an alternative to the User creation or add a way to provide an existing User with enough privileges to complete the stack creation.

The error is: `API: iam:CreateUser User: arn:aws:iam::<snip>:user/<snip> is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::<snip>:user/vault_<region>-18f431c6` 

### Steps to reproduce the behavior
Attempt to create a cluster with Vault enabled.

**Comment by dgozalo** [comment]
cc @ccojocar

**Comment by ccojocar** [comment]
Agree. We need to configure the user for CloudFormation. 

The service account used for vault service needs to have enough permissions to create IAM users (see https://www.vaultproject.io/docs/secrets/aws/index.html#iam_user).

**Comment by dgozalo** [comment]
This could be another alternative: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by ccojocar** [comment]
Yeah, this is excellent! I think it only works with 1.14 (https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html), but probably this is the current version on EKS. 

We have to check if the default credentials configured by AWS in the pod deployed  with a service account which has a IAM role are picked by the vault storage backend (https://www.vaultproject.io/docs/configuration/storage/dynamodb.html#dynamodb-parameters).

**Comment by msvticket** [comment]
IAM service accounts work in 1.13 as well, as long as it was created/upgraded after September 3rd.
