### ISSUE TITLE
Metapipeline should be removed from PipelineActivity and logs once the generated pipeline starts

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5455]
We should remove the metapipeline from the `PipelineActivity` (and no longer include it in `jx get build logs` or in the long term storage logs) once it's passed and the generated pipeline has started. There's no point in continuing to show the metapipeline info if it passed - it just clutters logs/the UI/etc.

**Comment by hferentschik** [comment]
Just so that we are on the same line here, this is a temporary measure, right? I agree that right now the meta pipeline logs might not be so important, but once we have #4660 and the ability write "proper" apps, they become important for sure.
