### ISSUE TITLE
Prow Config repo added without organisation

### ISSUE THREAD

**Issue by langleyd** [jenkins-x/jx#5456]
### Summary 
Prow Config repo added without organisation. `/repo` added rather than `org/repo`

E.g. error:
```
"error":"tide query (index 0) is invalid: repos[0]: \"/upswing\" is not of the form \"org/repo\
```

Effect of it is that pipelines fail to run. 

### Steps to reproduce the behavior
Saw this in a couple of instances usually after an `jx import.`
Schenario I was running was to uninstall jx but keep permanent envs operational:
1. Install via `jx boot`
2. Run import
3. `jx uninstall --keep-environments`
4. `jx boot`
5. `jx imort`

### Expected behavior
Bad entry not added to prow config, pipelines continue to function.

### Actual behavior
 You get the error in the logs and pipelines don't fire.

Tried Work around:

Use `jx step scheduler config apply` to change the prow config and remove the bad entry. 

got an error about git conflicts on dev repo.

Then in prow-build was seeing:
```
failed to reconcile default/jx/1e1ecc8e-d55c-11e9-8a8e-9e7982e2494a: get build default/jx/1e1ecc8e-d55c-11e9-8a8e-9e7982e2494a: context not found
```

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.0.719
Kubernetes cluster v1.14.3-gke.11
kubectl            v1.14.0
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE with `jx boot`

### Operating system / Environment

OSX

**Comment by abayer** [comment]
Fixed by https://github.com/jenkins-x/jx/pull/5791
