### ISSUE TITLE
Disk size prompt/option should be provided when creating a minikube cluster

### ISSUE THREAD

**Issue by gtseres** [jenkins-x/jx#546]
It would be useful to provide a prompt to specify the minikube VM disk size (as it is already done with the memory and CPUs). It will provide flexibility to create a larger minikube VM, if needed by the user. Currently (as of jx 1.1.42) there is no such option either via a prompt or an option in the `jx create cluster minikube` command and the disk that is used is of 20GB size. This could be kept as a default value.

I guess the https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_cluster_minikube.go#L56 could be enhanced for that and then propagate the argument to minikube using the `--disk-size` option.

**Comment by gtseres** [comment]
If you agree that this could be a nice enhancement, I could take care of it.

**Comment by rawlingsj** [comment]
@gtseres yeah that would be great if you fancy taking care if it.  Exposing the `--disk-siz` flag makes sense.
