### ISSUE TITLE
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.

### ISSUE THREAD

**Issue by alexvolsh** [jenkins-x/jx#5472]
### Summary 
Warning message appeared after Jenkins X CLI upgrade.

### Steps to reproduce the behavior
```
brew update
brew upgrade
jx version
```

### Expected behavior
```
NAME               VERSION
jx                 2.0.731
jenkins x platform 2.0.1094
Kubernetes cluster v1.15.3
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.15 build 19A558d
```

### Actual behavior
```
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
NAME               VERSION
jx                 2.0.731
jenkins x platform 2.0.1094
Kubernetes cluster v1.15.3
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.15 build 19A558d


verifying packages
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
WARNING: GitPrivate specified in TeamSettings. GitPrivate is deprecated use GitPublic instead.
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.731
jenkins x platform 2.0.1094
Kubernetes cluster v1.15.3
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.15 build 19A558d
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Self-created with kubespray

### Operating system / Environment

Running the CLI on my MacBook Pro (OS X)

**Comment by hferentschik** [comment]
Have you explicitly enabled private git repositories? If so the warning seems legit, but it should of course not appear so often. Or maybe not at all, since the code handles this transparently.

**Comment by alexvolsh** [comment]
Yes, I have explicitly enabled private git repositories on install step. So, if I understand correctly, private git repositories will be default install behaviour? If so, how I should change this option on existing environment?

**Comment by hferentschik** [comment]
> Yes, I have explicitly enabled private git repositories on install step.

Fair enough

> So, if I understand correctly, private git repositories will be default install behaviour? 

Yes. 

> If so, how I should change this option on existing environment?

```
$ kubectl edit env dev
```

and change `gitPrivate: true` to `gitPublic: false`. Or you can remove the setting altogether.

**Comment by alexvolsh** [comment]
Change environment option to `gitPublic: false` and now no warning messages. @hferentschik thank you.
