### ISSUE TITLE
Unable to uninstall Jenkins X

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5479]
### Summary 

Error during uninstall of Jenkins-X

### Steps to reproduce the behavior

```
$ jx --verbose uninstall
? Uninstall JX - this command will remove all JX components and delete all namespaces created by Jenkins X. Do you wish to continue? Yes

? Enter the current context name to confirm uninstallation of the Jenkins X platform from the jx namespace: jx
error: The context 'jx' must match the current context to uninstall
```

Despite entering `jx` which is my current context, the uninstall aborts.

### Expected behavior

Uninstall continues 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.399-dev+65479d4f0
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1
Operating System   Mac OS X 10.14.6 build 18G95
```

**Comment by daveconde** [comment]
This is looking for the kube config context, you can see this by running `jx context` Maybe we should also display the context name in the output above to make it easier for people.

**Comment by navin89** [comment]
error: invalid configuration: no configuration has been provided
