### ISSUE TITLE
aspnet-app quickstart is missing the charts/preview folder

### ISSUE THREAD

**Issue by andyhopp** [jenkins-x/jx#5487]
### Summary 
The Jenkinsfile for aspnet-app refers to a charts/preview folder for test-driving PR builds. However, this folder is missing.

### Steps to reproduce the behavior
1. jx create quickstart
2. choose aspnet-app
3. Examine charts folder, note that preview folder is missing.

### Expected behavior
Find the preview folder

### Actual behavior
It's not there.

### Jx version

The output of `jx version` is:

```
jx                 2.0.712
jenkins x platform 2.0.1165
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.14.6
helm client        Client: v2.14.2+ga8b13cc
git                2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G8030
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster
EKS

### Operating system / Environment
MacOS

**Comment by deanesmith** [comment]
@andyhopp Can you please post the logs from the quickstart?

**Comment by andyhopp** [comment]
First: OMG!!! Hi, Deane! It's Andy Hopper from waaaay back when at Ipswitch!

Second: here's the output from the command (is there somewhere else I should look for detailed logs?)
```
186590cd924f:~ andyhopp$ jx create quickstart
? select the quickstart you wish to create  [Use arrows to move, space to select,? 
aspnet-app
Using Git provider GitHub at https://github.com
? Do you wish to use andyhopp as the Git user name? Yes
? Which organisation do you want to use?  [Use arrows to move, space to select, t? Which organisation do you want to use? andyhopp
? Enter the new repository name:  aspnet-app4
Creating repository andyhopp/aspnet-app4
Generated quickstart at /Users/andyhopp/aspnet-app4
### NO charts folder /Users/andyhopp/aspnet-app4/charts/aspnet-app
Created project at /Users/andyhopp/aspnet-app4
The directory /Users/andyhopp/aspnet-app4 is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
performing pack detection in folder /Users/andyhopp/aspnet-app4
--> Draft detected SVG (67.960973%)
--> Could not find a pack for SVG. Trying to find the next likely language match...
--> Draft detected csharp (22.293823%)
selected pack: /Users/andyhopp/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/csharp
replacing placeholders in directory /Users/andyhopp/aspnet-app4
app name: aspnet-app4, git server: github.com, org: andyhopp, Docker registry org: andyhopp
skipping directory "/Users/andyhopp/aspnet-app4/.git"
Pushed Git repository to https://github.com/andyhopp/aspnet-app4
Let's ensure that we have an ECR repository for the Docker image andyhopp/aspnet-app4
Created ECR repository: 982831078337.dkr.ecr.us-east-1.amazonaws.com/andyhopp/aspnet-app4
Created Jenkins Project: http://jenkins.jx.andyhoppatamazon.com/job/andyhopp/job/aspnet-app4/

Watch pipeline activity via:    jx get activity -f aspnet-app4 -w
Browse the pipeline log via:    jx get build logs andyhopp/aspnet-app4/master
You can list the pipelines via: jx get pipelines
When the pipeline is complete:  jx get applications

For more help on available commands see: https://jenkins-x.io/developing/browsing/

Note that your first pipeline may take a few minutes to start while the necessary images get downloaded!

Creating GitHub webhook for andyhopp/aspnet-app4 for url http://jenkins.jx.andyhoppatamazon.com/github-webhook/
```

**Comment by deanesmith** [comment]
Thanks @andyhopp.  I've never used that quickstart but will give it a try with the Tekton pipeline and see if it behaves differently

**Comment by deanesmith** [comment]
@andyhopp Question - Have you tried with using the Tekton pipeline or are you committed to leveraging static masters?

**Comment by andyhopp** [comment]
Hi, @deanesmith ! I must confess I'm new to how JenkinsX works. We're using the AWS/EKS provider; is that compatible with Tekton?

**Comment by deanesmith** [comment]
Absolutely!  In fact, at CloudBees we're currently moving through a large epic to solidify Jenkins-X on EKS to help us with our support statement for the CloudBees Jenkins-X Distribution.  Currently we only officially support GKE, but not for long.  I recommend using CJXD and noting the expanded EKS support over the next 2 months.  Next release is at the end of the month and it will have an exciting new feature I think you'll like.
