### ISSUE TITLE
Install Jenkins X with jx boot on gke, in cloudshell, results in git version conflict

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx#5488]
### Steps to reproduce the behavior
1. `jx create cluster gke --skip-installation --skip-login -n k`
2. `jx boot`
### Expected behavior
Jenkins X is installed on the cluster `k`
### Actual behavior
The install didn't complete.

<img width="1344" alt="Screenshot 2019-09-13 at 22 30 54" src="https://user-images.githubusercontent.com/15032115/64896004-367a9900-d676-11e9-958a-4d0612e279ec.png">

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.734
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.13.9-2+4a03651a7e7e04
git                2.11.0
Operating System   Debian GNU/Linux 9.11 (stretch)
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Created on GKE in cloudshell.
`jx create cluster gke --skip-installation --skip-login -n k`

<img width="681" alt="Screenshot 2019-09-13 at 22 37 55" src="https://user-images.githubusercontent.com/15032115/64896284-2616ee00-d677-11e9-837e-66d7576da09a.png">

<img width="846" alt="Screenshot 2019-09-13 at 22 38 51" src="https://user-images.githubusercontent.com/15032115/64896323-4777da00-d677-11e9-93db-d5ad318d19b1.png">

### Operating system / Environment

Debian GNU/Linux 9.11

**Comment by deanesmith** [comment]
@MarckK This is a known issue and we're looking in to it.

**Comment by deanesmith** [comment]
@jstrachan any chance we could shim in an updated version of git on these CloudShell images?

**Comment by chaoyangnz** [comment]
please fix it, it is really frustrating when one newcomer wants to try jx.

**Comment by MarckK** [comment]
The git version conflict is an ongoing known issue.

We have raised an issue with Cloud Shell requesting that they update the git version provided, but until that happens the Cloud Shell tutorials won't work. 

Until this is resolved, mention of the Cloud Shell tutorials should not appear in the docs.

Instead of the Cloud Shell tutorials, we suggest that users follow [the Getting Started instructions](https://jenkins-x.io/docs/getting-started/).

**Comment by MarckK** [comment]
fwiw, [this issue](https://issuetracker.google.com/issues/148284057) was raised.
