### ISSUE TITLE
Enable gloo as part of jx-requirements.yaml jx boot

### ISSUE THREAD

**Issue by rudolph9** [jenkins-x/jx#5489]
### Summary 
How do you enable gloo when configuring a cluster via `jx boot`?

**Comment by deanesmith** [comment]
@jstrachan Can you provide some insight?

**Comment by jstrachan** [comment]
we'd need to add a flag into `jx-requirements.yml` and then modify the https://github.com/jenkins-x/jenkins-x-boot-config to conditionally include gloo
