### ISSUE TITLE
None of default credentials are working

### ISSUE THREAD

**Issue by NickitaX** [jenkins-x/jx#549]
After installation of JenkinsX and creating a stock NodeJS base via `jx create quickstart` none of default credentials was successful. Solution is:

`kubectl get secrets --all-namespaces=true` to check all credentials and dependent namespaces.

In JenkinsX namespace will be `jx`.

And to get credentials use:

`kubectl get secret jenkins-x-mongodb --namespace=jx -o yaml`

Example above will output credentials of jenkins-x-mongodb with jx namespace.

Username and password will be in Base64, therefore should be decoded.

Issue: Would be easier to match with described default credentials ('admin'/'admin') straight out of the box.

**Comment by jstrachan** [comment]
@NickitaX sorry to hear that. Am just wondering what credentials in particular has issues - did the pipeline of the quickstart fail? Which part failed?

**Comment by rawlingsj** [comment]
I'm pretty sure there should be no more default admin/admin username passwords used now. At the end of `jx create cluster` or `jx install` the generated default admin password used for Jenkins, Nexus and Chartmuseum should be printed in the terminal console.  

If you don't have that terminal session anymore you can check in the jx local config files for the admin password.  e.g. `cat ~/.jx/jenkinsAuth.yaml`.

**Comment by NickitaX** [comment]
@jstrachan thanks for response! As @rawlingsj stated, default admin password has been printed in terminal. However, I'm wondering is there any way to pass password while executing `jx create`? This would simplify all inconvenience with default passwords. Thanks.

**Comment by rawlingsj** [comment]
There's a `default-admin-password` flag you can use.

e.g.
```
jx create cluster gke --default-admin-password foo
```
I'm pretty sure that should work as you'd expect.

**Comment by NickitaX** [comment]
Great, thanks a lot @rawlingsj! It solves my issue 👍 Can close this one.

**Comment by rawlingsj** [comment]
Excellent - thanks @NickitaX!
