### ISSUE TITLE
ServiceException: 409 Bucket <BUCKET_NAME> already exists.'

### ISSUE THREAD

**Issue by fai555** [jenkins-x/jx#5491]
### Summary 
When creating a brand new cluster in GKE with the command 

jx create cluster gke \
--advanced-mode \
--no-gitops-vault \
--no-tiller \
--verbose

then throws the error.

In the middle of the setup process, asks for the project name.

Then tries to create a bucket with the name 
gs://jx-vault-<CLUSTER_NAME>-bucket/...

But GCS buckets are universally unique, this throws the already exists error.  

### Steps to reproduce the behavior
run the command 

jx create cluster gke \
--advanced-mode \
--no-gitops-vault \
--no-tiller \
--ng \
--verbose

and when the prompt asks for cluster name, give `jenkins-x`

### Expected behavior
Successful creation of cluster

### Actual behavior
Throws the error
ServiceException: 409 Bucket <BUCKET_NAME> already exists.'

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.739
jenkins x platform 2.0.1182
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.14.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95


verifying packages

```

### Jenkins type

- [*] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
@fai555 Would you be able to attempt but with using jx boot - https://jenkins-x.io/getting-started/boot ?  You should be prompted for buckets during the boot process not during cluster creation.

**Comment by ccojocar** [comment]
We recommend no to use `boot` command instead of `install --ng` options for installing serverless Jenkins X.
