### ISSUE TITLE
Developer builds failing to promote

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#550]
When developers are importing projects against a shared server, we are seeing 401 errors creating the pull request against staging. 

```
[promote-demodelete-0.0.6 b3fafb5] Promote demodelete to version 0.0.6
 1 file changed, 3 insertions(+)
To https://github.com/DVSJersey/environment-dvs-dev-11-staging.git
 * [new branch]      HEAD -> promote-demodelete-0.0.6
error: POST https://api.github.com/repos/DVSJersey/environment-dvs-dev-11-staging/pulls: 401 Bad credentials []

```

**Comment by jstrachan** [comment]
my guess is the secret `jenkins-x-git` has an API token that is no longer valid for the staging git repo or maybe its been revoked?

**Comment by tdcox** [comment]
The token is still showing as valid and appears to have full control over repos.

Have GitHub made yet another breaking API change?

**Comment by tdcox** [comment]
Just checked and I don't appear to have a secret `jenkins-x-git` on the server. Did you change a secret name at some point?

**Comment by rawlingsj** [comment]
it should be a credential in Jenkins

**Comment by tdcox** [comment]
Ah, OK. It exists as a username/password credential in Jenkins. Should the password field hold the same value as the apitoken field in .jx/gitAuth.yaml or is it encoded?

**Comment by tdcox** [comment]
I guess a better question is what is the safest way to recreate?

**Comment by rawlingsj** [comment]
> Ah, OK. It exists as a username/password credential in Jenkins. Should the password field hold the same value as the apitoken field in .jx/gitAuth.yaml or is it encoded?

Yes the password credential should contain the git token that was used when the initial `jx create cluster` / `jx install` ran and created the environment jenkins pipelines.

> I guess a better question is what is the safest way to recreate?

To recreate you can edit the credential in Jenkins and replace the password value with the user / bot git token that has karma for the environment repos.

**Comment by tdcox** [comment]
jx create spring is still able to create projects in github using the token in gitAuth.yaml, so I would assume that implies that the token is still good.

**Comment by jstrachan** [comment]
I think the `jx create spring / quickstart` and `jx import` lazily recreates the `jenkins-x-git` credential in Jenkins - I wonder if someone overwrote the credential in Jenkins with a bad API token?

**Comment by tdcox** [comment]
Same error, so the Jenkins version was not corrupted. Looks like you can create a project repo with the token but you can't create a PR any longer. This is now also broken for projects I created and which were previously deploying, so something seems to have changed externally.

**Comment by jstrachan** [comment]
Wonder its to do with the user for the API token that Jenkins is using no longer having write access to the staging git repo?

**Comment by tdcox** [comment]
That user is Admin for the repo and the Team all have Write access.

**Comment by jstrachan** [comment]
have you tried updating the `jenkins-x-git` credential in the Jenkins UI to ensure its setup with the correct user/pwd? I wonder if its been overwritten with a bad token

**Comment by tdcox** [comment]
Yes, that's what I just did above. 

I have just done a `jx upgrade platform` and all appears to be working again. Looks like there was a release that was failing to pass the credentials correctly or similar.

**Comment by jstrachan** [comment]
btw the `jx upgrade platform` doesn't manage the Jenkins credential yet - you have to reset it manually in the Jenkins UI (we will move to using real Secrets + the helm chart soon for that)

**Comment by jstrachan** [comment]
if you set the `jenkins-x-git` credential to a user+api token that you know works and the `jx promote` cannot create a PR then I'm at a total loss really ;) - maybe attach the `Jenkinsfile` in case there's a missing `credential` there?

**Comment by tdcox** [comment]
Ok. In this case, the credential in Jenkins was good. Looks like the GitHub API returns `401 Bad credentials` if you fail to send a credential as well as if the credential is bad, so it may have been that I had a bad intermediate build of something on the server side, or an in memory copy of something got trashed.

**Comment by jstrachan** [comment]
so is it working again now? Wondering what we can do to avoid these kind of issues hitting folks

**Comment by tdcox** [comment]
The GitHub API error is no longer showing up. My pull requests are now failing for another reason but at least they are being triggered. Not sure what the underlying issue was but I didn't have a bad token so I am assuming that something was failing to pass it in one call for a while.
