### ISSUE TITLE
Kubectl: exec format error

### ISSUE THREAD

**Issue by nicholasmparker** [jenkins-x/jx#551]
I'm in Ubuntu 17.10 and trying to create a new cluster using:

jx create cluster gke

I get through sign in and environment configuration and then getting the following error after "creating cluster..........." with the table with the name, location, master version, etc...

> error creating cluster fork/exec /home/nick/bin/kubectl: exec format error
> error: fork/exec /home/nick/bin/kubectl: exec format error

At which point the application exits.

**Comment by jstrachan** [comment]
Did you install `/home/nick/bin/kubectl` yourself or was it installed by `jx`? It looks like the binary is of the wrong format. I wonder if removing it and trying again helps? 

```
rm  /home/nick/bin/kubectl
jx create cluster gke
```

If the binary is downloaded by `jx` there could be a bug in it not finding the correct binary for ubuntu when it tries to install `kubectl`

**Comment by nicholasmparker** [comment]
The binary was downloaded by jx.  I do already have kubectl installed as well.

**Comment by jstrachan** [comment]
@nicholasmparker can you run

```
/home/nick/bin/kubectl version
```
OK? Am wondering if this is an issue with the ubuntu install process of the `kubectl` binary

**Comment by nicholasmparker** [comment]
Ok - did that, and there was nothing at

/home/nick/bin/kubectl

although it was linked to

/home/nick/snap/kubectl

I removed kubectl using apt-get and installed it using snap.

The version snap installed was 1.9, which caused the same error.

Then I removed it from snap, installed again via apt, and created a link from

/home/nick/bin/kubectl to kubectl as installed via apt and it worked.

**Comment by ccojocar** [comment]
Closing this since the problem was the wrong kubectl binary.
