### ISSUE TITLE
Add support for custom helm repository

### ISSUE THREAD

**Issue by eladh** [jenkins-x/jx#5512]
### Summary 
Hi :-)

Is there any option to support for custom helm repository in the same pattern used allowing us to use custom Docker registry ? 

looking[ at the code ](https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/helm/step_helm_release.go) now its support ChartMuseum only 

Best,
Elad

### Expected behavior
Add support for custom helm repository

### Actual behavior
Only support ChartMuseum

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

**Comment by masseybradley** [comment]
The [ReleaseChartMuseumUrl](https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/helm/step_helm_release.go#L106) looks for the [`CHART_REPOSITORY`](https://github.com/jenkins-x/jx/blob/master/pkg/cmd/opts/helm.go#L971) environment variable. Should be possible to override the `CHART_REPOSITORY` environment variable if I'm not mistaken.

**Comment by eladh** [comment]
@masseybradley  ,[ see this line](https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/helm/step_helm_release.go#L140) -  adding /api/charts is only relevant to [chartmuseum](https://github.com/helm/chartmuseum#api) 

10x

**Comment by eladh** [comment]
@deanesmith- do you think it's documentation issue ?  is there any official way to support it ? 

10x
