### ISSUE TITLE
Booting from a Dev environment's repository after it failed to generate the update PR skips its creation

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5514]
### Summary 

After attempting to boot for the first time, when I got to the creation of the first update PR on the dev environment's repository, it failed because I didn't have enough permissions.

After I fixed the permissions issue and tried to boot again, this time from the Dev environment's repository which I cloned locally, it got to the point where it previously failed but it never attempted to create the PR again, probably because at this time, it just checks if the environment repository is already created.

### Steps to reproduce the behavior
Attempt to boot into an organization where you are not an owner or have permissions to create PRs.

See it fail when attempting to create the first PR on the dev environment.

Give your user the necessary permissions.

Clone the dev environment's repository and boot again.

### Expected behavior
It should attempt to create the PR again and be successful. 

### Actual behavior
It skips the creation of the updates PR and you are left with an outdated `jx-requirements.yml` file and no `env/parameters.yaml`.

**Comment by deanesmith** [comment]
@dgozalo Have you seen this lately?

**Comment by dgozalo** [comment]
We are not generating this PR anymore as we are directly pushing any changes to Master. 

We can close this issue.
