### ISSUE TITLE
dependency-matrix `matrix.yaml` and `matrix.md` dependency `kind`

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x/jx#5516]
### Summary 

The `dependency-matrix/matrix.yaml` and `dependency-matrix/matrix.md` files lack a `kind` (i.e. `docker`, `charts`, etc).

`jx step create pr docker` updates the `dependency-matrix` files and the `Dockerfile` `ENV` instruction however `jx step get stream -k docker` reports the version of an artifact from `version-stream/docker/registry/image`. Would be legit imho to be able to query the `dependency-matrix` directly for the version of a dependency by i.e.:
1. adding the `kind` for each dependency
2. adding a `matrix` kind to the `jx step get stream` to load the dependency matrix
3. adding a sub-type to specify the `kind` from the stream i.e.: `jx step get stream -k matrix -s docker ...`.

The `dependency-matrix/matrix.yaml` can be loaded using the [LoadDependencyMatrix](https://github.com/jenkins-x/jx/blob/master/pkg/dependencymatrix/matrix.go#L125) method. The method is called in `jx/pkg/cmd/opts/install.go` to get the latest version of `jx` (don't see it being used anywhere else at the time of this writing).

### Steps to reproduce the behavior

Check the `dependency-matrix/matrix.yaml` structure:
```
dependencies:
- host: github.com
  owner: my-org
  repo: my-repo
  url: https://github.com/my-org/my-repo
  version: 0.0.1
  versionURL: ""
```
### Desired behavior

Have the `kind` for each version recorded in the `dependency-matrix/matrix.(*)`.

### Actual behavior

No `kind` in the dependency-matrix files.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.721
Kubernetes cluster v1.13.7-gke.19
kubectl            v1.15.3
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE installed with `jx`.

### Operating system / Environment

Ubuntu 18.04 / `docker`.

**Comment by deanesmith** [comment]
@pmuir

**Comment by pmuir** [comment]
Sounds like a good idea to me!

**Comment by pmuir** [comment]
If someone wants to contribute I can help out with how to do it. Ping me on slack or here.

**Comment by rajibmitra** [comment]
@pmuir I would love to do it.
