### ISSUE TITLE
Deployment with cloud provider kubernetes

### ISSUE THREAD

**Issue by bigloupe** [jenkins-x/jx#552]
"jx install"  doesn't work with provider kubernetes

Please find the messages in the console 

```
 Cloud Provider kubernetes
Tiller Deployment is running in namespace kube-system
Already up-to-date.
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
ingress init failed: service jxing-nginx-ingress-controller never became ready
error: service jxing-nginx-ingress-controller never became ready
```

I think loadbalancer should be replaced by NodePort.

**Comment by jstrachan** [comment]
@bigloupe what kind of kubernetes cluster were you installing on? It sounds like helm couldn't deploy the ingress controller chart; I guess something is broken with your cluster? Is there enough capacity?

In the `kube-system` namespace it'd be good to try figure out whats wrong.

e.g.  could you append the output of these commands:

```
jx ns kube-system
kubectl get deploy
kubectl describe deploy jxing-nginx-ingress-controller
kubectl describe deploy jxing-nginx-ingress-default-backend
```

**Comment by bigloupe** [comment]
@jstrachan 
Thanks for the reply

I tested a deployment with jx version 1.1.44 for GKE and everything works. First deployment was indeed an issue concerning VCPU. You need almost 4 vCPU to deploy correctly in GKE.

![image](https://user-images.githubusercontent.com/3832232/38296030-598fc26a-37f0-11e8-8e7a-41dd9648d61a.png)

But for my on-premise installation, i've no message in error and VMs seem to have enough capacity.

![image](https://user-images.githubusercontent.com/3832232/38300451-1c6951fa-37fd-11e8-8bd4-66e15d5fbe65.png)

Please find the results of the different command. But I see nothing in error.


```
$ jx ns kube-system
Now using namespace 'kube-system' on server 'https://192.168.1.20:6443'.
```

```
$ kubectl get deploy
NAME                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
jxing-nginx-ingress-controller        1         1         1            1           16h
jxing-nginx-ingress-default-backend   1         1         1            1           16h
kube-dns                              2         2         2            2           1d
kubedns-autoscaler                    1         1         1            1           1d
kubernetes-dashboard                  1         1         1            1           1d
tiller-deploy                         1         1         1            1           16h
```

```
$ kubectl describe deploy jxing-nginx-ingress-controller
Name:                   jxing-nginx-ingress-controller
Namespace:              kube-system
CreationTimestamp:      Tue, 03 Apr 2018 17:30:25 +0200
Labels:                 app=nginx-ingress
                        chart=nginx-ingress-0.12.3
                        component=controller
                        heritage=Tiller
                        release=jxing
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=nginx-ingress,component=controller,release=jxing
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=nginx-ingress
                    component=controller
                    release=jxing
  Annotations:      checksum/config=8dab152492f0b9a65133720af5ad909ddb8e54cedc90f4c688807f1c1923ca6c
  Service Account:  jxing-nginx-ingress
  Containers:
   nginx-ingress-controller:
    Image:       quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.12.0
    Ports:       80/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --default-backend-service=kube-system/jxing-nginx-ingress-default-backend
      --election-id=ingress-controller-leader
      --ingress-class=nginx
      --configmap=kube-system/jxing-nginx-ingress-controller
    Liveness:   http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:        (v1:metadata.name)
      POD_NAMESPACE:   (v1:metadata.namespace)
    Mounts:           <none>
  Volumes:            <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   jxing-nginx-ingress-controller-547979cfb9 (1/1 replicas created)
Events:          <none>
```

```
$ kubectl describe deploy jxing-nginx-ingress-default-backend
Name:                   jxing-nginx-ingress-default-backend
Namespace:              kube-system
CreationTimestamp:      Tue, 03 Apr 2018 17:30:25 +0200
Labels:                 app=nginx-ingress
                        chart=nginx-ingress-0.12.3
                        component=default-backend
                        heritage=Tiller
                        release=jxing
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=nginx-ingress,component=default-backend,release=jxing
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=nginx-ingress
           component=default-backend
           release=jxing
  Containers:
   nginx-ingress-default-backend:
    Image:        k8s.gcr.io/defaultbackend:1.3
    Port:         8080/TCP
    Host Port:    0/TCP
    Liveness:     http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   jxing-nginx-ingress-default-backend-6f4ff5fcbc (1/1 replicas created)
Events:          <none>
```

**Comment by wjcaitu** [comment]
I have the same issue.
my cluster is based kubernetes 1.8. Is there any update for this issue, should we do any further configuration for ingress deployment?

**Comment by jstrachan** [comment]
@Ian-T-Price agreed! We're having lots of trouble removing old clusters on GCE ourselves. I think we need a nice 'delete cluster' command for GCE. 

I've been told by some googlers that the best option is to remove all the namespaces in a cluster one by one first - then there's more chance of GCE actually removing stuff like load balancers + firewalls

**Comment by cvila84** [comment]
Hello, I experience the same issue with a K8S cluster I have installed on Ubuntu with kubeadm.

jx is waiting for the ingress-controller-service to be ready. I guess that such a service (LoadBalancer type) is flagged ready as soon as an external IP is provided, which will never happen in this situation as we have not declared/configured any cloud provider.

I agree with @bigloupe : the service type should be NodePort instead of LoadBalancer

I tried to update the service to NodePort by myself but unfortunately, jx is still waiting for the service to be ready, I need to take a look in the code to understand what test is made at this point.

**Comment by cvila84** [comment]
Hello,

After checking the code, the service readiness is done watching the status.loadBalancer.ingress field of the service which is filled by K8S when the external load balancer gives an IP. Giving an externalIP by yourself in the service in using the externalIP field won't work so it will wait until timeout :-(

I tried to remove this test in the code and give the domain name with jx install --domain x.x.x.x.nip.io (x.x.x.x is the IP of your K8S master for example) and it works well !

I think we should either:
- say that using provider 'kubernetes' requires to have a cloud controller manager (that handles the externalIP provisioning), e.g. say that it is when you want to use a cloud provider not supported yet
- say that using provider 'kubernetes' is for bare metal K8S installation and then remove the test that waits for the externalIP to be given by an external entity, e.g. we can provide the externalIP by ourselves at installation time

**Comment by jstrachan** [comment]
@cvila84 awesome work thanks! 

So we should definitely support passing in the `--external-ip` as a CLI argument so you can bypass the wait.

I wonder if we should have an `--on-premise` flag on the CLI which if specified it defaults the `external-ip` to being the K8S master IP?

**Comment by cvila84** [comment]
@jstrachan If I had to choose, I would take the `--on-premise` that would get the IP from where the jx install is launched and build a domain name x.x.x.x.nip.io unless `--domain` is set

**Comment by jstrachan** [comment]
@cvila84 sounds good - have a PR on its way that lets you specify the exact `--external-ip` or lets you specify `--on-premise` which means default the external IP to the k8s master ip...

**Comment by jstrachan** [comment]
PR: https://github.com/jenkins-x/jx/pull/1054

**Comment by jstrachan** [comment]
the new `1.2.136` release is out with this fix. To upgrade try:
```
jx upgrade cli
```
then here's the docs on how to use it:
https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise

**Comment by cvila84** [comment]
Just tried.

--external-ip is working well !
--on-premise needs a fine tuning because the computed external IP still have the protocol (https://)

I guess this code needs a small update

`idx := strings.LastIndex(host, ":")
externalIP = host
if idx > 0 {
  externalIP = host[0:idx]
}`

**Comment by jstrachan** [comment]
@cvila84 great catch thanks. I've added a bit better implementation to try figure out the host name/ip address. e.g. here's the test case: https://github.com/jenkins-x/jx/blob/master/pkg/util/urls_test.go#L14-L31

I've just cut `1.2.137` which should hopefully have the fix so that `--on-premise` works. BTW I added a little warning as well if folks are using the `kubernetes` provider and not specifying `--external-ip` or `--on-premise` to give folks a hint they should try it

**Comment by cvila84** [comment]
@jstrachan That's just perfect. Many thanks !!

**Comment by jstrachan** [comment]
@cvila84 great, thanks for all your help!

**Comment by vivekthangathurai** [comment]
Hello, 
`jx boot` fails with below error
`waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output: ''`

**Comment by mahendrans** [comment]
@vivekthangathurai 
Duplicate of # 5496

please refere the above issue

you have to use ignoreLoadBalancer in your jx-requirements.yml

**Comment by zzguang520** [comment]
I have same issue now:
 jx install —provider=kubernetes
Command "install" is deprecated, it will be removed on Jun 1 2020. We now highly recommend you use jx boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details.
? Configured Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Context "kubernetes-admin@kubernetes" modified.
? Cloud Provider kubernetes
Git configured for user: zzguang520 and email zzguang520@sina.com
Helm installed and configured
? No existing ingress controller found in the kube-system namespace, installing one: Yes

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
FATAL: ingress init failed: service jxing-nginx-ingress-controller never became ready

jx version
NAME               VERSION
jx                 2.1.10
jenkins x platform 2.0.2171
Kubernetes cluster v1.18.1
kubectl            v1.16.9
helm client        2.16.6
git                2.18.4
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"


verifying packages

and not found  the deploy of ingress:

 kubectl get deploy
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
jenkins-x-controllerrole   1/1     1            1           33h
jenkins-x-nexus            0/1     1            0           33h

 kubectl describe deploy jxing-nginx-ingress-controller
Error from server (NotFound): deployments.apps "jxing-nginx-ingress-controller" not found

but I found pod of ingree is running:
kubectl get pod -A|grep ingress
kube-system            jxing-nginx-ingress-controller-78546fb8c8-9f754        1/1     Running     0          33h
kube-system            jxing-nginx-ingress-default-backend-5f8759b676-xg9d8   1/1     Running     0          33h

kubectl describe deploy jxing-nginx-ingress-controller
