### ISSUE TITLE
JX import fails to import Bitbucket repo

### ISSUE THREAD

**Issue by ocni-dtu** [jenkins-x/jx#5527]
### Summary 
I try to `jx import` a repo, which lies on Bitbucket, but jx cannot run the pipeline, because it looks on Github for the repo.
I have configured both Github and Bitbucket as git servers
```
$ jx get git
Name      Kind           URL
GitHub    github         https://github.com
BitBucket bitbucketcloud https://bitbucket.org
```

### Steps to reproduce the behavior
```
jx import --git-provider-kind=bitbucketcloud --git-provider-url=https://bitbucket.org
? Which Git service do you wish to use https://bitbucket.org
WARNING: No username defined for the current Git server!
? Do you wish to use christian_procedural as the Git user name: Yes
error: failed to start pipeline build
```

### Expected behavior
jx import should create and start a pipeline

### Actual behavior

```
my-react-project$ jx start pipeline my-org/my-react-project/master --verbose
DEBUG: getting vault name for namespace jx
DEBUG: system vault name from config jx-vault
DEBUG: finding service url for jx-vault in namespace jx
DEBUG: found service url http://jx-vault.nip.io
DEBUG: Connecting to vault on http://jx-vault.nip.io
DEBUG: merging pipeline secrets with local secrets
error: getting branch master on my-org/my-react-project: getting branch master on my-org/my-react-project: GET https://api.github.com/repos/my-org/my-react-project/branches/master: 404 Not Found []
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.757
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.13.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```

### Jenkins type
- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

jx create cluster gke --ng

### Operating system / Environment

Ubuntu 18.04 LTS

**Comment by deanesmith** [comment]
Hi @ocni-dtu Did you set up your environments accordingly as mentioned [here](https://jenkins-x.io/developing/git/)

**Comment by ocni-dtu** [comment]
@deanesmith yeah I used: `jx create git server`

**Comment by deanesmith** [comment]
@ocni-dtu, ok, I see you're using the nextgen (Tekton) pipeline.  Based on the note at the top of this [doc](https://jenkins-x.io/developing/git/), expanded SCM support will arrive as [Lighthouse](https://github.com/jenkins-x/lighthouse) evolves.  Happy to leave this issue open and labeled appropriately and will follow up when Lighthouse is ready, or you can close it out.

**Comment by ocni-dtu** [comment]
@deanesmith thanks for the explanation. I must have missed that note.
Do you know when Lighthouse will be shipped with the expanded support?

**Comment by deanesmith** [comment]
Leaving open but given limitations with Bitbucket API and functionality, this will be a much longer term effort.
