### ISSUE TITLE
Resulting build logs bucket linked in PR results

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#5529]
### Summary 
When setting up Jenkins X, any jobs that run provide completion status and error code result (i.e. whether job succeeded or failed), but do not provide a link to the resulting long term bucket with the logs. In #3334 there is a mention that could be relevant, and it seems that there may be some configuration required to be added in order for Prow to know what URL to use. 

My questions/issues are:
* Is there a way to configure the jenkins-x deployment to know what base-url to use to point to the right buckets through the standard "`Details`" url?
* Is this supposed to be done by default or is it a known feature that is to be added?

It's worth mentioning that the bucket is updated with the new logs as a new job runs, it just doesn't get linked.

### Steps to reproduce the behavior
Create a cluster in GKE with `jx create cluster gke --default-admin-password=$JX_PASSWORD -n $JX_CLUSTER_NAME --ng=true --skip-login=true --git-username $JX_USER --git-api-token $GIT_TOKEN`.

Then import repo with a `jenkins-x.yaml` file using `jx import --no-draft=true`. Once a PR is created, the tests in the Jenkins-x file will run but the logs from the resulting bucket will not be linked.

### Expected behavior
The resulting bucket to be linked through the "Details" link of the job as a PR runs the Jenkins X tasks.

### Actual behavior
The pipeline runs, and shows whether it succeeds or fails, but does not provide a link to the bucket. 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.679
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by axsaucedo** [comment]
For the sake of explicitness, the links also don't appear if the default storage is set to be the gh-pages branch in the main repo.

**Comment by axsaucedo** [comment]
@abayer thank you for adding it to the backlog. It seems that implicitly this answered my question that it's not currently a feature that is set up automatically. However given that when seeing some of the builds in the JX repo, the jobs that seem to run on jenkins X have links to the logs - what would be the way to manually configure the builds to point to the bucket? Or how was it achieved in this repo? Thank you @abayer

**Comment by axsaucedo** [comment]
We've added it to our pipeline, it may be worth adding to the documentation as it's something that probably would be quite a common request https://github.com/SeldonIO/seldon-core/blob/master/ci/add-pr-build-comment
/reopen

**Comment by abayer** [comment]
Reopen isn't working quite yet. =) https://github.com/jenkins-x/lighthouse/pull/733

**Comment by axsaucedo** [comment]
Haha fair enough! Thanks @abayer ! 

MAybe this could be something added to FAQ for now?

**Comment by infra-cicd** [comment]
@axsaucedo we came up with a similar solution to you, both for our build logs and also for our test reports. The only down side is that you have a few more comments added to the PR, especially if you have multiple parallel pipelines running. Being able to override the Details/Link would be much nicer as then all the failure logs/reports could be viewed in one place - right at the end of the PR.

**Comment by paul-g1** [comment]
@axsaucedo we came up with a similar solution to you, both for our build logs and also for our test reports. The only down side is that you end up with several comments added to the PR, especially if you have multiple parallel pipelines running. Being able to override the Details/Link would be much nicer as then all the failure log/report links could be viewed in one place - right at the end of the PR.

**Comment by tomhobson** [comment]
Closing as this is a v2/v1 issue and those versions are no longer maintained. Thanks for the issue!
