### ISSUE TITLE
Regression of #3897: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by irasnyd** [jenkins-x/jx#5534]
### Summary 

Issue #3897 was never fixed, or has regressed. It still occurs with the latest version of Jenkins X.

### Steps to reproduce the behavior

```
$ jx install
```

### Expected behavior

I expected to be able to install Jenkins X.

### Actual behavior

Jenkins X installation failed completely.

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.762
jenkins x platform 2.0.1247
Kubernetes cluster v1.14.6
kubectl            v1.15.0
helm client        Client: v2.14.3+g0e7f3b6
git                1.8.3.1
Operating System   "CentOS Linux release 7.6.1810 (Core) "


verifying packages
error: failed to parse semantic version for current version 1.8.3.1 for package git: Invalid character(s) found in patch number "3.1"
```

**NOTE**: I have also tried version 2.0.761, which has the same problem.

### Git version

```
$ git version
git version 1.8.3.1
```
```
$ rpm -qi git
Name        : git
Version     : 1.8.3.1
Release     : 20.el7
Architecture: x86_64
Install Date: Tue 04 Dec 2018 11:41:48 AM PST
Group       : Development/Tools
Size        : 23232282
License     : GPLv2
Signature   : RSA/SHA256, Tue 20 Nov 2018 12:34:30 PM PST, Key ID 24c6a8a7f4a80eb5
Source RPM  : git-1.8.3.1-20.el7.src.rpm
Build Date  : Mon 19 Nov 2018 08:13:01 AM PST
Build Host  : x86-01.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://git-scm.com/
Summary     : Fast Version Control System
Description :
Git is a fast, scalable, distributed revision control system with an
unusually rich command set that provides both high-level operations
and full access to internals.

The git rpm installs the core tools with minimal dependencies.  To
install all git packages, including tools for integrating with other
SCMs, install the git-all meta-package.


```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

```
$ minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
```

### Operating system / Environment

```
$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
```

### Command Output

First I cleaned up everything from any previous runs of `jx`:

```
$ rm -rf ~/.jx
```

Then I tried to install Jenkins X:

```
$ jx install 
? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Context "minikube" modified.
set exposeController Config Domain 192.168.39.151.nip.io
Git configured for user: Ira W. Snyder and email isnyder@lco.global
helm installed and configured
FATAL: initialise build packs failed: failed to reset hard to master in directory /home/isnyder/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]': failed to run 'git reset --hard origin/master' command in directory '/home/isnyder/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes', output: 'fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```

There is a `/home/isnyder/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes` directory with these contents:

```
$ ls -la /home/isnyder/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes
total 0
drwxr-xr-x 3 isnyder domainusers  17 Sep 18 15:33 ./
drwxr-xr-x 3 isnyder domainusers  33 Sep 18 15:33 ../
drwxr-xr-x 7 isnyder domainusers 128 Sep 18 15:33 .git/
$ cd /home/isnyder/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
  Push  URL: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
  HEAD branch: master
  Remote branches:
    1.0.0             new (next fetch will store in remotes/origin)
    master            new (next fetch will store in remotes/origin)
    rawlingsj-patch-1 new (next fetch will store in remotes/origin)
```

The problem can be fixed with the workaround in the comments of #3897:
```
$ git fetch origin
From https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes
 * [new branch]      1.0.0      -> origin/1.0.0
 * [new branch]      master     -> origin/master
 * [new branch]      rawlingsj-patch-1 -> origin/rawlingsj-patch-1
 * [new tag]         v1.0.0     -> v1.0.0
```

But then it just all falls over again later in the installation process with a similar error:

```
$ jx install 
? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Context "minikube" modified.
set exposeController Config Domain 192.168.39.151.nip.io
Git configured for user: Ira W. Snyder and email isnyder@lco.global
helm installed and configured
nginx ingress controller already enabled
Set up a Git username and API token to be able to perform CI/CD
Creating a local Git user for GitHub server
? GitHub username: irasnyd
To be able to create a repository on GitHub we need an API Token
Please click this URL and generate a token 
https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter it below:

? API Token: ****************************************
Select the CI/CD pipelines Git server and user
? Do you wish to use GitHub as the pipelines Git server: Yes
Creating a pipelines Git user for GitHub server
To be able to create a repository on GitHub we need an API Token
Please click this URL and generate a token 
https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter it below:

? API Token: ****************************************
Setting the pipelines Git server https://github.com and user name irasnyd.
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /home/isnyder/.jx/jenkins-x-versions
Cloning the Jenkins X cloud environments repo to /home/isnyder/.jx/cloud-environments
Enumerating objects: 1440, done.
Total 1440 (delta 0), reused 0 (delta 0), pack-reused 1440
Updating Secret jx-install-config in namespace jx
Setting up prow config into namespace jx
Installing tekton into namespace jx

Installing Prow into namespace jx
with values file /home/isnyder/.jx/cloud-environments/env-minikube/myvalues.yaml

? Defaulting workload build pack: Kubernetes Workloads: Automated CI+CD with GitOps Promotion
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
Installing jx into namespace jx
Installing jenkins-x-platform version: 2.0.1247


WARNING: waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx
Configuring the TeamSettings for ImportMode YAML
Creating default staging and production environments
? Select the organization where you want to create the environment repository: irasnyd
Using Git provider GitHub at https://github.com
? Using Git user name: irasnyd
? Using organisation: irasnyd
Creating repository irasnyd/environment-slothshade-staging
Creating Git repository irasnyd/environment-slothshade-staging
error: creating the environments: failed to create staging environment in namespace jx: creating environment git repository: cloning the forked environment "https://github.com/jenkins-x/default-environment-charts.git" into "/home/isnyder/.jx/environments/irasnyd/environment-slothshade-staging": failed to reset hard to master in directory /home/isnyder/.jx/environments/irasnyd/environment-slothshade-staging: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]': failed to run 'git reset --hard origin/master' command in directory '/home/isnyder/.jx/environments/irasnyd/environment-slothshade-staging', output: 'fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```

I can't repeat the workaround, because Jenkins X chooses a different random name each time I run it. The `environment-slothshade-staging` will become a different random name.

I tried using the `jx install --default-environment-prefix=slothshade` to try and get it to reuse the existing repository, but that doesn't work either. Instead, Jenkins X decides to try to use `environment-slothshade-staging1`. I was unable to find a way to prevent Jenkins X from continually incrementing a digit on the end of my first repository.

**Comment by hfrazon** [comment]
Same problem here!!! I can`t create environments.

jx = 2.0.515
jenkins x platform = 2.0.1182

**Comment by deanesmith** [comment]
Hi @irasnyd, can you update the local version of git and let us know if that addressed the issue?

**Comment by irasnyd** [comment]
> Hi @irasnyd, can you update the local version of git and let us know if that addressed the issue?

I am already using the latest version of git available in CentOS 7's package repositories. I have the "base", "updates", and "extras" repositories enabled. I regularly use this machine to work with Github without any problems; this version of git is working fine.

**Comment by klw0539** [comment]
Hi, @irasnyd , I faced same issue in in my PC, version is below:
➜  jenkins-x-boot-config git:(master) ✗ jx version
NAME               VERSION
jx                 2.0.800
Kubernetes cluster v1.14.6+IKS
kubectl            v1.13.6
helm client        v2.14.0+g05811b8
helm server        v2.14.3+g0e7f3b6
git                1.8.3.1
Operating System   "CentOS Linux release 7.6.1810 (Core) "


verifying packages
error: failed to parse semantic version for current version 1.8.3.1 for package git: Invalid character(s) found in patch number "3.1"

And the error is below:
error: failed to clone git URL https://github.com/jenkins-x/jenkins-x-boot-config.git to directory: jenkins-x-boot-config: failed to reset hard to master in directory jenkins-x-boot-config: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
=======
➜  ~ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
=======
➜  ~ git version
git version 1.8.3.1

Could you please do me a favor?

**Comment by withlin** [comment]
same problem!
```
[root@localhost jenkins-x-kubernetes]# jx version
NAME               VERSION
jx                 2.0.842
Kubernetes cluster v1.15.3
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core) 

```

**Comment by zhouguangming** [comment]
same problem!

```xml
NAME               VERSION
jx                 2.0.858
Kubernetes cluster v1.13.2
kubectl            v1.13.2
helm client        v2.15.0-rc.1+g288a957
helm server        v2.15.0-rc.1+g288a957
git                1.8.3.1
Operating System   CentOS Linux release 7.4.1708 (Core)
```

**Comment by wgku** [comment]
same problem !
`jx version
NAME               VERSION
jx                 2.0.881
jenkins x platform 2.0.1473
Kubernetes cluster v1.15.2
kubectl            v1.15.2
helm client        Client: v2.14.1+g5270352
git                1.8.3.1
Operating System   CentOS Linux release 7.4.1708 (Core)

verifying packages
error: failed to parse semantic version for current version 1.8.3.1 for package git: Invalid character(s) found in patch number "3.1" `
==============
`Creating Git repository gmiot/environment-lizardcurse-staging
error: creating the environments: failed to create staging environment in namespace jx: creating environment git repository: cloning the forked environment "https://github.com/jenkins-x/default-environment-charts.git" into "/root/.jx/environments/gmiot/environment-lizardcurse-staging": failed to reset hard to master in directory /root/.jx/environments/gmiot/environment-lizardcurse-staging: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]': failed to run 'git reset --hard origin/master' command in directory '/root/.jx/environments/gmiot/environment-lizardcurse-staging', output: 'fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''`

**Comment by IcedSoul** [comment]
same problem!
```
NAME               VERSION
jx                 2.0.966
jenkins x platform 2.0.1582
Kubernetes cluster v1.16.0
kubectl            v1.16.0
helm client        Client: v2.16.0+ge13bc94
git                1.8.3.1
Operating System   CentOS Linux release 7.7.1908 (Core)
```
```
'git <command> [<revision>...] -- [<file>...]': failed to run 'git reset --hard origin/master' command in directory '/root/.jx/environments/IcedSoul/environment-chargerrose-staging', output: 'fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.

```
But I found that the Git 1.8.3 we are using is not the latest version, so I try to install a new version of git on CentOS:
```
# downlod source code
wget https://github.com/git/git/archive/v2.24.0.tar.gz
tar -zxvf v2.24.0.tar.gz
# Install compilation tool
yum install curl-devel expat-devel gettext-devel openssl-devel zlib-devel gcc perl-ExtUtils-MakeMaker
yum remove git
cd git-2.24.0/
make prefix=/usr/local/git all
make prefix=/usr/local/git install

cd ..
rm -rf v2.24.0.tar.gz
rm -rf git-2.24.0/

vi /etc/profile

# add git path on at the bottom
export PATH=$PATH:/usr/local/git/bin
# save and exit
source /etc/profile

```
Now execute `jx version`:
```
jx                 2.0.966
jenkins x platform 2.0.1582
Kubernetes cluster v1.16.0
kubectl            v1.16.2
helm client        Client: v2.16.0+ge13bc94
git                2.24.0
Operating System   CentOS Linux release 7.7.1908 (Core)

```
Then execute `jx uninstall` and re-execute `jx install` to successfully install Jenkins X.

I hope this helps.

**Comment by deanesmith** [comment]
Thanks @IcedSoul, spot on.  I'm having difficulty getting the same result on Ubuntu.

**Comment by IcedSoul** [comment]
I don't have a kubernetes cluster installed on ubuntu, so I can't verify it.

But since the latest version of git installed with yum on CentOS is always 1.8.3, and we usually don't have any problems with this version of git, maybe jx uses some new features that git 1.8.3 doesn't have, so we all get this error. Perhaps the problem can be solved by automatically executing the corresponding git statement based on the recognized git version, or by reminding in the installation documentation to use the official latest version of git instead of the latest version provided by the Linux system.

> RHEL and derivatives typically ship older versions of git. You can download a tarball and build from source, or use a 3rd-party repository such as the IUS Community Project to obtain a more recent version of git.

https://git-scm.com/download/linux
