### ISSUE TITLE
Cannot push container to ECR: 'no basic auth credentials'

### ISSUE THREAD

**Issue by tilted** [jenkins-x/jx#5535]
### Summary 
When attempting to build and deploy the "spring-boot-http-gradle" quickstart example the build fails when trying to push the container to ECR with the following error:

```
time="2019-09-18T23:36:51Z" level=fatal msg="build failed: build failed: building [gitname/project]: build artifact: no basic auth credentials"

```

This thread looked promising: https://github.com/jenkins-x/jx/issues/4501

but after adding the jenkins-docker-cfg the problem still persists.

The only thing that seems to have helped is executing:
```
jx create docker auth --host "XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com" --user "ecr-login"
```
which unblocked me from a previous problem of not even being able to query the ECR repo. Although I shouldn't have to use that command for anything, right?

### Steps to reproduce the behavior
Try to build and deploy "spring-boot-http-gradle" quickstart example via jennkins x on an AWS-managed cloud. 

I am using clusters set-up through kops. I am not using EKS.

### Expected behavior
Successful build and deployment

### Actual behavior
Build failure during:
 export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
```
++ cat VERSION

+ export VERSION=0.0.10

+ VERSION=0.0.10

+ skaffold build -f skaffold.yaml

Generating tags...

 - gitname/project-> XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/gitname/project:0.0.10

Tags generated in 145.479µs

Checking cache...

 - gitname/project: Not found. Building

Cache check complete in 41.005383ms

Starting build...

Building [gitname/project]...

Sending build context to Docker daemon  528.9kB
Sending build context to Docker daemon   13.9MB
Sending build context to Docker daemon  18.35MB

Step 1/8 : FROM openjdk:8-jdk-slim

 ---> c019fea7a4ad

Step 2/8 : ENV PORT 8080

 ---> Using cache

 ---> 2487ccc8cef0

Step 3/8 : ENV CLASSPATH /opt/lib

 ---> Using cache

 ---> 2030e8c0f39a

Step 4/8 : EXPOSE 8080

 ---> Using cache

 ---> 786296b237d3

Step 5/8 : COPY pom.xml target/lib* /opt/lib/

 ---> 6fbb7fc126e7

Step 6/8 : COPY target/*.jar /opt/app.jar

 ---> f1ea8caff4a3

Step 7/8 : WORKDIR /opt

 ---> Running in 68d05c735ecc

 ---> 39921189451a

Step 8/8 : CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-jar", "app.jar"]

 ---> Running in 00e236fe309c

 ---> 5ed6bcee5bdd

Successfully built 5ed6bcee5bdd

Successfully tagged XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/gitname/project:0.0.10

The push refers to repository [XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/gitname/project]

7d1502f864c6: Preparing

f5a21b174409: Preparing

be5d22cd9d08: Preparing

4bb8e1819413: Preparing

00bcabc31815: Preparing

2db44bce66cd: Preparing

2db44bce66cd: Waiting

time="2019-09-18T23:36:51Z" level=fatal msg="build failed: build failed: building [gitname/project]: build artifact: no basic auth credentials"

script returned exit code 1
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.749
jenkins x platform 2.0.1247
Kubernetes cluster v1.12.10
kubectl            v1.13.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.14.5

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

AWS -backed cluster using kops. (EKS not used)

### Operating system / Environment

Amazon Linux
```
Operating System   Unkown Linux distribution Linux version 4.14.123-86.109.amzn1.x86_64 (mockbuild@koji-pdx-corp-builder-64004) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC)) #1 SMP Mon Jun 10 19:44:53 UTC 2019
```

**Comment by kuflink-tech** [comment]
I have also encountered this issue, when modifying my config.json, as per suggestions on issue #4501

**Comment by tilted** [comment]
I have continued to dig deep into this but have not come up with a solution. Any suggestions or feedback?

**Comment by tilted** [comment]
Ok - so the solution here was basically #4501 - **BUT** I had to execute the deletion/creation of the secret within the pod that was executing the gradle build (recall I am trying to deploy the spring-boot-http gradle' quickstart project.) 
Here is the catch. That pod is transient. It is only created for a build and it is destroyed after the build completes or fails. So what I needed to do was trigger a build somehow (code change or new project will work) and then monitor all of the pods that are running. Use the following command on the kubernetes master node:
```
kubectl get pods -n jx
```
Keep executing this command until you see the "gradle-XXXX" pod. At that point you can execute the following command to get a command line within that pod:
```
kubectl exec -it gradle-XXXX --namespace jx -- /bin/bash
```
**NOW** you can execute the kubectl secret delete/create commands specified in #4501. You only need to have the "credHelpers" stanza in the config.json.

That's it! If you did it fast enough then the build should complete! It will take about 51-20 mins in total (At least it did for me on my small cluster). If your connection to the pod is killed then you didn't act fast enough. Try again or you can be clever and add in a wait to the jenkinsfile.

Finally - after the build is completed you can execute the following to get your ingress address:
```
kubectl get ing -n jx-staging
```

Here is what is interesting - even though the pod is transient you only need to perform this operation once. All of the gradle build pods that are created after this will have the correct credentials. Good luck and happy hunting!
