### ISSUE TITLE
'jx create cluster' should not install Jenkins X

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5537]
### Summary 

At the moment `jx create cluster` creates a cluster and installs directly Jenkins X. For me, this is a bit unexpected, especially since there is a dedicated `jx install` which is now superseded` by `jx boot`.

I'd rather have to type in two clear commands:

```bash
> jx create ...
> jx install ...
```

Also, with `jx boot` you need to explicitly skip the installation if you want to use boot over install:

```
> jx create cluster --skip-installation ...
```

My understanding is that moving forward `jx install` gets deprecated and `jx boot` becomes the default. With `jx boot` it should also be possible to just bring your own cluster. So `jx create cluster` becomes more of a convenient method.

I recommend removing the direct Jenkins X installation behaviour from `jx create cluster`. Nothing wrong imo to type in two commands if needed.

**Comment by MarckK** [comment]
I like this enhancement. Having cluster creation and Jenkins X installation as two separate commands makes the process conceptually clearer for the user (and potentially more flexible), while maintaining ease of use.

**Comment by hferentschik** [comment]
Another advantage is that we can slim down considerably on the command-line options for `jx create cluster`. If the command does not do the installation anymore we can remove all the options which are "just" carry through options for the installation. All install options are mirrored atm into create cluster.

**Comment by mrageh** [comment]
I've been bitten by this for so long, very frustrating that it tries to install by default!
