### ISSUE TITLE
promotion of code fails from stage to deployment

### ISSUE THREAD

**Issue by siddharthkaushal90** [jenkins-x/jx#5542]
### Summary 
jx promote failed

### Steps to reproduce the behavior
1. import a project
2. it gets promoted to stage env
3. then try promoting to prod env, it gets successful
4. make some changes in the code and pipeline will trigger to deploy the code to stage env and it gets successful.
5. but when I try to promote to prod env it fails with error.

### Expected behavior
code should get promoted to prod env

### Actual behavior
error: pulling environment repo https://github.com/***********/environment-spikestar-production.git into /home/************/.jx/environments: git output: usage:

```
error: pulling environment repo https://github.com/*********/environment-spikestar-production.git into /home/**********/.jx/environments: git output: usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
                       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear: failed to run 'git stash push' command in directory '/home/***********/.jx/environments/production', output: 'usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
                       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear'
```
### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 2.0.762
jenkins x platform 2.0.1247
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.13.9-2+4a03651a7e7e04
helm client        Client: v2.14.1+g5270352
git                2.11.0
Operating System   Debian GNU/Linux 9.11 (stretch)


verifying packages
error: package git is an old version 2.11.0. The version stream requires at least 2.15.0
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)

### Operating system / Environment
Ubuntu

**Comment by pmuir** [comment]
The last message on `jx version` is the cause of this - you need a newer version of git locally.

**Comment by siddharthkaushal90** [comment]
@pmuir I have configured jenkins-x using gke and when I configure the cluster it gets git version 2.11.0.
When I tried to update it to the latest version, using **"sudo apt-get install git"** it is saying that you are on the latest version.
any idea how to update the git version in cloud shell?
