### ISSUE TITLE
Failed to inspect image

### ISSUE THREAD

**Issue by rudolph9** [jenkins-x/jx#5544]
### Summary
Using the go-http quickstart I recieve the following error while the pipeline is running 
`Failed to inspect image "gcr.io/jenkinsxio/builder-go:0.1.778": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument: ImageInspectError`

### Steps to reproduce the behavior

run a master pipeline on an application

### Expected behavior

No `ImageInspectError`

### Actual behavior

An `ImageInspectError`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.757
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.15.3
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

gke created with `jx create cluster gke --skip-installation`

### Operating system / Environment

```
Operating System   Ubuntu 18.04.3 LTS
```

### Other Notes

Also created ticket here https://github.com/jenkins-x/jenkins-x-builders/issues/778

**Comment by jstrachan** [comment]
I just tried updating the `ConfigMap jenkins-x-pod-template-go` to use the exact same builder image: `gcr.io/jenkinsxio/builder-go:0.1.778` and re-ran my go quickstart and the pipelines all worked fine and it promoted the new version to staging which worked. I can't reproduce the error.

So I'm guessing its nothing to do with the builder image or Jenkins X version - but more that the node you are using is maybe in a bad state - e.g. maybe its ran out of disk and failed to download an image layer or something? I wonder if recreating the node or rerunning the pipeline a few times; so the build pods get scheduled on other nodes results in a different result?

**Comment by rudolph9** [comment]
Yes did rolling replace on all my gcp nodes and that seems to have fixed my issue.
