### ISSUE TITLE
`jx install` should also install dependencies like `jx create cluster`

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#555]
e.g. checking things like kubectl + helm is installed etc

**Comment by rajdavies** [comment]
ServiceAccount expose + cleanup also need to be added

**Comment by jstrachan** [comment]
@rajdavies yeah I think thats coming in a new exposecontroller version + PR:
https://github.com/jenkins-x/exposecontroller/pull/121

**Comment by rajdavies** [comment]
does not set the domain for minikube - so install fails
