### ISSUE TITLE
Can't install jx server part on AWS eks?

### ISSUE THREAD

**Issue by Stephanzf** [jenkins-x/jx#5564]
### Summary 
It tries to connect a non-existing subnet.

### Steps to reproduce the behavior
$jx install 
produces errors and can't continue

### Expected behavior
It should install jx server side

### Actual behavior
$ jx install
[Use arrows to move, space to se? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Error creating commitstatuses.jenkins.io: Post https://2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp: lookup 2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com on 192.168.1.1:53: no such host### Jx version

The output of `jx version` is:
$ jx version
Unable to connect to the server: dial tcp: lookup 2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com on 192.168.1.1:53: no such host
``
COPY OUTPUT HERE
```[Use arrows to move, space to se? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Error creating commitstatuses.jenkins.io: Post https://2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp: lookup 2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com on 192.168.1.1:53: no such host
Error creating commitstatuses.jenkins.io: Post https://2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp: lookup 2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com on 192.168.1.1:53: no such host
Error creating commitstatuses.jenkins.io: Post https://2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp: lookup 2D3CB4338D382C51285A5E5249A28774.gr7.us-west-2.eks.amazonaws.com on 192.168.1.1:53: no such host
### Jenkins type
jenkins-x latest
<!--
Select which installation type are you using. 
-->
- [ *] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
eks
<!--
What kind of Kubernetes cluster are you using & how did you create it?
terraform-eks-demo on github
-->

### Operating system / Environment
MacOS
<!--
In which environment are you running the jx CLI?
-->

**Comment by deanesmith** [comment]
@Stephanzf  Looks like a network related issue.  Are you installing on a new cluster or a pre-existing one?  Were you supplying any flags to the `jx install` command?
