### ISSUE TITLE
Core Infrastructure Initiative (CII) 🔒

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx#5565]
The Best Practices Badge is an open source secure development maturity model. Projects having a CII badge will showcase the project’s commitment to security. Open source project maintainers answer a short questionnaire to be awarded a “Best Practices Badge”. 

https://bestpractices.coreinfrastructure.org/en

The Linux Foundation (LF) Core Infrastructure Initiative (CII) Best Practices badge is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this web application to explain how they follow each best practice.

Jenkins X should partake in this programme.

Nice set of FOSS projects are engaged with this initiative: https://bestpractices.coreinfrastructure.org/en/projects

**Comment by MarckK** [comment]
😃@ccojocar 🎉

**Comment by ccojocar** [comment]
I completed the CII Best Practices `passing` level criteria, and it seems that we reached 98%. 

There are also `silver` and `gold` level criteria which we might consider to fill up later but they have more strict requirements.

Also I will create a bug for what we are missing.

**Comment by ccojocar** [comment]
Crated https://github.com/jenkins-x/jx/issues/5679 for missing requirement.
