### ISSUE TITLE
upgrade boot should try to use a tag instead of master

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5581]
### Summary 

upgrade boot command should try to determine the latest version from a tag instead of master when checking that an update is available in boot config repository.

See the review comment https://github.com/jenkins-x/jx/pull/5280#discussion_r327606066

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
I fixed this a couple weeks ago in #5977.
