### ISSUE TITLE
Should the initial `jx boot` be run incluster?

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#5592]
### Summary 

We have a number of issues around helm/git/jx versions being out of sync, as well as issues connecting to vault when the letsencrypt staging server is selected.  So I'd like to open a discussion on whether the initial `jx boot` command could/should be run as a Job inside the cluster?

* Would need to work out what to do with secrets
* jx-requirements.yml
* would remove the interactive nature of jx boot
* could stop exposing vault to the public

**Comment by abayer** [comment]
This feels like a good idea to me. We could keep using interpret mode for now, but we might be able to switch to having a Job spec as an alternative output for translating from jenkins-x.yml syntax...
