### ISSUE TITLE
Use the jx version in the version of the jenkins-x-builders

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#5595]
### Summary 
It's not easy to detect what version of jx is within a builders image by looking at the version of the builder. Would be excellent to version the builders based off the jx version, something like:
jx version: `1.2.3`
builders version: `1.2.3-<builders_build_number>`

**Comment by abayer** [comment]
Need to figure out how we can override the next version logic in `pipelinerunner`/the metapipeline to let us update the whole version/tag based on the `jx` version and an incrementing build number.

**Comment by abayer** [comment]
Looks like if we set `pipelineConfig.pipelines.release.setVersion`, we can change the `jx step next-version` call to use `--version (something)`, where `(something)` would need to include the `jx` version...

**Comment by abayer** [comment]
@cagiti Do you know if we have some convenient way of extracting a version for something from `dependency-matrix/matrix.yaml`? The "new" `jx` version is in there, so that seems like the best place to pull it from.

**Comment by cagiti** [comment]
> @cagiti Do you know if we have some convenient way of extracting a version for something from `dependency-matrix/matrix.yaml`? The "new" `jx` version is in there, so that seems like the best place to pull it from.

Not as far as I know, I've used some crude `sed` command for the interim, feels like we should write a step for that to read the yaml version.

**Comment by abayer** [comment]
Exactly what I just decided. =)

**Comment by axsaucedo** [comment]
@cagiti @abayer is it possible to stop the tag being set alltogether? My objective is to stop the tags from being pushed to the github repo with:
```
      setVersion:
        steps:
        - name: next-version
          sh: echo "ignoring..."
```
However when running  a pipeline with this, it would still error out with the following:
```
error: failed to set the version on release pipelines: failed to read file /workspace/source/VERSION
```
I have tried just creating the file to see if that would be enough but it still errors out if the file is empty, and if it has any value it will push a release with that tag. It would be very useful for us to be able to supress the tag being pushed without the error.
