### ISSUE TITLE
Push the jx update to jenkins-x-platform through the builders

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#5596]
### Summary 
Both the `jx` and `jenkins-x-builders` releases update `jenkins-x-platform` independently. It would be good if the `jx` update to the `jenkins-x-platform` was performed by the `jenkins-x-builders` release. This should reduce the chance of differing `jx` versions of `jenkins-x-builders` (containing a different `jx` version) and `jx` within the `jenkins-x-platform.`

**Comment by abayer** [comment]
Probably depends on #5595, which I'm tackling first anyway.
