### ISSUE TITLE
App installation requires Jenkins X with Vault installed

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5597]
```go
if o.GetSecretsLocation() != secrets.VaultLocationKind {
    return fmt.Errorf("cannot install apps without a vault when using GitOps for your dev environment")
}
```

See https://github.com/jenkins-x/jx/blob/03315ab3960ffd11909595696b3842a958cb65ed/pkg/cmd/add/add_app.go#L168

This means if you install Jenkins X w/o Vault which in turn requires TLS, you cannot install Apps. This is problematic for the default "evaluation" mode using nip.io.

**Comment by ccojocar** [comment]
This checked has been removed. The vault client is created optionally only when the vault is enabled. I am going to close this issue as fixed.
