### ISSUE TITLE
Failed to start jenkins-x-controllerbuild pod

### ISSUE THREAD

**Issue by jiangytcn** [jenkins-x/jx#5600]
### Summary 
Failed to start the controllerbuild pod in openshift environment. 

```
$ oc logs po/jenkins-x-controllerbuild-9c5c95887-9dr8h                                                                                                    ‹ruby-2.6.3›  /home/jiangytcn
error: Failed to set the git username to jenkins-x-bot: git output: error: could not lock config file //.gitconfig: Permission denied: failed to run 'git config --global --add user.name jenkins-x-bot' command in directory '', output: 'error: could not lock config file //.gitconfig: Permission denied'
```
### Steps to reproduce the behavior
 jx install  --provider=openshift --git-provider-url='https://github.foo.com'  --domain='192.168.2.103.nip.io' --no-default-environments=true --git-username=xxx  --gitops=false

### Expected behavior

cluster running 

### Actual behavior
failed to start cntrollerbuild 
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.784
jenkins x platform 2.0.1296
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                1.8.3.1
Operating System   "RHEL 7.7"

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

openshift, oc cluster up 

### Operating system / Environment
RHEL

**Comment by pmuir** [comment]
Note that support for OpenShift is still experimental. If you are able to help us improve OpenShift support, please give us a shout on Slack and we can help you out.

**Comment by jiangytcn** [comment]
thanks @pmuir  I made it running in Openshift with lighthouse with the help from Slack.
