### ISSUE TITLE
Cannot push image to an external Harbor registry - https://harbor.corp.local/v2/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by riazvm** [jenkins-x/jx#5602]
### Summary 
My quickstart sample build works fine but fails on pushing the image to my external registry because of  x509: certificate signed by unknown authority. I have the certificate but how do i have jx use this certificate to push it. I can push an image to the registry from my local machine

### Steps to reproduce the behavior
Set up harbor as the DOCKER_REGISTRY under environment variables. Harbor is configured to use SSL. Delete the existing jenkins-docker-cfg secret under the jx namespace. Run the following command kubectl create secret docker-registry jenkins-docker-cfg --docker-server="harbor.corp.local" --docker-username="admin" --docker-password="test123" --docker-email="youremail@xxx.com" --namespace=jx to create the the secret. Run a quickstart sample build, everything works until the point where jx pushes the image into the registry with an error
Successfully tagged harbor.corp.local/jenkisxgit/jenkinsxgit:0.0.3
The push refers to repository [harbor.corp.local/jenkisxgit/jenkinsxgit]
time="2019-09-25T20:17:47Z" level=fatal msg="build failed: build failed: building [jenkisxgit/jenkinsxgit]: build artifact: Get https://harbor.corp.local/v2/: x509: certificate signed by unknown authority"

### Expected behavior
The image build should be pushed into the harbor registry

### Actual behavior
Errors out with the following error The push refers to repository [harbor.corp.local/jenkisxgit/jenkinsxgit]
time="2019-09-25T20:17:47Z" level=fatal msg="build failed: build failed: building [jenkisxgit/jenkinsxgit]: build artifact: Get https://harbor.corp.local/v2/: x509: certificate signed by unknown authority"
### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 2.0.730
jenkins x platform 2.0.1182
Kubernetes cluster v1.12.4
kubectl            v1.12.4
helm client        Client: v2.12.3+geecf22f
git                2.7.4
Operating System   Ubuntu 16.04.5 LTS

### Jenkins type
 Classic Jenkins

### Kubernetes cluster
PKS

### Operating system / Environment
Operating System   Ubuntu 16.04.5 LTS

**Comment by pmuir** [comment]
This is really the responsibility of your cloud provider - you need to follow their docs to add certificates to the VMs.

**Comment by pmuir** [comment]
I'm going to close this for now but if you are stuck please follow up on slack and perhaps someone who knows PKS can help you.
