### ISSUE TITLE
Error creating bucket during Vault setup

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5605]
### Summary 

An error during Vault initialization can occur when the initial `jx boot` failed, but some of the Vault related resources are already created, eg the bucket to store the data.

In successive attempts to run `jx boot`, the user gets an error along these lines:

```
Error creating bucket: Creating gs://jx-vault-acmecluster1-bucket/...
ServiceException: 409 Bucket jx-vault-acmecluster1-bucket already exists., failed to run 'gsutil mb -l us-west1 -p acmecorp-one gs://jx-vault-acmecluster1-bucket' command in directory '', output: 'Creating gs://jx-vault-acmecluster1-bucket/...
ServiceException: 409 Bucket jx-vault-acmecluster1-bucket already exists.'
error: creating vault: creating Vault GCS data bucket: creating Vault GCS bucket: failed to run 'gsutil mb -l us-west1 -p acmecorp-one gs://jx-vault-acmecluster1-bucket' command in directory '', output: 'Creating gs://jx-vault-acmecluster1-bucket/...
ServiceException: 409 Bucket jx-vault-acmecluster1-bucket already exists.'
```

At this stage, it is not quite clear to the user what to do next.

The issue is that Vault initialization never completed and hence per default an attempt is made to create a new bucket with a name derived from the cluster name. 

The user could:

* use a different cluster
* provide an explicit vault bucket name
* set the recreate bucket flag

Once the Vault initialization succeeded, bucket creation is skipped when `jx boot` runs.

### Expected behaviour

The case that the bucket already existed should be caught in order to create a better error message to the user pointing into the right direction to resolve the issue. For example by referencing the Vault config struct or similar.

**Comment by ccojocar** [comment]
As a workaround, the vault and the cloud resources provisioned for it can be deleted with:

```
jx delete vault -r -n jx <vault-name>
```

This command will remove vault and all its cloud resources.

**Comment by duemir** [comment]
Isn't the problem that the bucket name is not unique enough? 
https://cloud.google.com/storage/docs/naming#requirements
If one person `jx boot` an `acmecluster1` which creates the `jx-vault-acmecluster1-bucket` no other person will be able to successfully do the same because the bucket creation is going to fail. Isn't that the case?
