### ISSUE TITLE
jx add app uses same cache directory for multiple clusters

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5609]
In gitops mode `jx add app` uses the directory _$JX_HOME/environment/dev_ as a cache directory for creating the pull requests against the development repository.

This causes issues when the user has more than two Jenkins X cluster he connects to. 

Since the same directory is used for different environment repositories you end up with errors of the form:

```bash
$ jx add app foo
error: adding app fooversion  with alias  using gitops: creating pr for foo: pulling environment repo https://github.com/hf-bee-bot/environment-hardy-dev-dev.git into /Users/hardy/.jx/environments: fetching origin add-app-foo-0.0.46: git output: From https://github.com/hf-bee-bot/environment-hardy-dev-dev
 ! [rejected]        add-app-foo-0.0.46 -> origin/add-app-foo-0.0.46  (non-fast-forward): failed to run 'git fetch '...'
```

The cache directory should be specific to the cluster. Other parts of the code already use a cache directory which is keyed by cluster name, apps does not yet do that.

**Comment by salaboy** [comment]
From James: 
```
basically we should generally remove .EnvironmentDir() from the code and use an ioutil.TempDir() instead 

https://github.com/jenkins-x/jx/blob/26a8209fe56f7a541be92425b0139ac483682b73/pkg/cmd/deletecmd/delete_application.go#L386
pkg/cmd/deletecmd/delete_application.go:386
    environmentsDir, err := o.EnvironmentsDir()

```

**Comment by tomhobson** [comment]
Closing as this is a v2/v1 issue and those versions are no longer maintained. Thanks for the issue!
