### ISSUE TITLE
Customize Helm Chart Used for static Jenkins master pod

### ISSUE THREAD

**Issue by faucherb94** [jenkins-x/jx#5614]
### Summary

I'd like to be able to customize the helm chart yaml used by `jx install` for creating the static Jenkins master pod. I have to go through a whole bunch of manual configuration every time I create a new jx instance, or even just restart the Jenkins master pod.

I've found where the helm chart is: https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml#L889, I just don't how this file is used by `jx install` or where it lives on my local system.

Is this already possible?

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.679
jenkins x platform 2.0.1247
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.0
helm client        Client: v2.13.1+g618447c
git                2.23.0
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

Ubuntu 16.04.6 LTS

**Comment by pmuir** [comment]
You should be able to change `~/.jx/myvalues.yaml` and override keys from the platform. There is an example, for another scenario, at https://jenkins-x.io/docs/managing-jx/common-tasks/create-custom-builder/#install-the-builder which you may be able to use to help you...

**Comment by pmuir** [comment]
I'll close for now, but please do ask on slack if you can't make it work

**Comment by faucherb94** [comment]
Ah wonderful, thank you @pmuir!
