### ISSUE TITLE
Hitting disk capacity limit in Tekton builds

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5622]
### Summary 
Within our Machine Learning builds, we are importing a number of external dependencies as part of the training step in our pipelines. This appears to be filling up the image when step-source-copy-project-xxxx runs after our training step.

The error is during the operation `cp -r /workspace/source/. /pvc/training/workspace` and reports `write error: No space left on device` multiple times.

### Jx version

```
2.0.775
```

@abayer

**Comment by abayer** [comment]
So the issue here is the size of the workspace volume? I'm pretty sure that's configurable, just not sure off the top of my head where.

**Comment by abayer** [comment]
Ah, there it is - specifying 

```
pvc:
  size: 10Gi
```

or whatever in `env/tekton/values.tmpl.yaml` in your dev env repo should do the trick. The default is `5Gi`.
