### ISSUE TITLE
`jx stop pipeline` doesn't display build numbers when listing available pipelines to cancel

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5626]
You just get:
```
? Which pipeline do you want to stop:   [Use arrows to move, space to select, type to filter]
> jenkins-x/jenkins-x-versions/PR-542-boot-vault
  jenkins-x/jx/PR-5617-integration
  jenkins-x/jx/PR-5617-integration
  jenkins-x/jx/PR-5617-tekton
```

Which is, y'know, not ideal.

**Comment by abayer** [comment]
This basically means changing the output in `pkg/cmd/stop/pipeline.go` to include build numbers in the list of pipelines to choose from and the confirmation dialogue.

**Comment by sladyn98** [comment]
@abayer Hey I could maybe take a swing at this issue ?

**Comment by abayer** [comment]
@sladyn98 That'd be great!

**Comment by sladyn98** [comment]
https://github.com/jenkins-x/jx/blob/d77b79cdbe8c7994ac7de3783c7c0bcf5b2f3631/pkg/cmd/stop/stop_pipeline.go#L190

The build option should be displayed here right ?

**Comment by jstrachan** [comment]
@sladyn98 yeah that sounds good. We could maybe use the Jenkins style output of  
```name := fmt.Sprintf("%s/%s/%s #%s", owner, repo, branch, buildNumber) ``` 
so they appear as `foo/bar/master #123`?

**Comment by mrageh** [comment]
@sladyn98 are you still working on this, if not I'd be happy to jump on and get this shipped :)

**Comment by sladyn98** [comment]
@mrageh yeah sure go ahead, I wanted to solve this in order to get a bit familiar with Jenkins x. Not a problem I will find a different issue. Thanks
