### ISSUE TITLE
Hitting ctrl-c at the "cancel pipeline ... ?" prompt on `jx stop pipeline`...stops the pipeline.

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5627]
Responding with `n` works as expected, but I sure would assume that ctrl-c would just cancel, not act the same as if you'd hit enter (to confirm the default of `Y`) or responded with `y`. =)

**Comment by jstrachan** [comment]
we've got the Ctrl-C issue in a few other `jx` commands  too I think. its a survey library issue IIRC - capturing `ctrl-c` key strokes and interpreting it as the current / default selection
