### ISSUE TITLE
Make external-dns optional in jx boot with GKE and custom domain

### ISSUE THREAD

**Issue by AndreasKnapp1812** [jenkins-x/jx#5634]
### Summary 
If custom domain is configured and working with GKE, external-dns will be set to true automatically: https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/step_create_install_values.go#L135-L136 . There should be a flag on the `jx-requirements.yml` to specify that you already have an external dns installation to disable that logic. We need that logic so things still work in a totally empty cluster. I discussed this already with @jstrachan [on slack](https://kubernetes.slack.com/archives/C9MBGQJRH/p1569592245325600).

### Steps to reproduce the behavior
Create a GKE cluster and then run `jx boot` with a custom domain and external-dns disabled on the `jx-requirements.yml`.

### Expected behavior
If external-dns is disabled, an existing installation of external-dns can be used.

### Actual behavior
If working with GKE and providing a custom domain, having external-dns disabled will enable it automatically.

### Jx version
The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.795
Kubernetes cluster v1.14.6-gke.2
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.6 build 18G103
``` 

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE cluster created with Terraform using https://github.com/terraform-google-modules/terraform-google-kubernetes-engine

**Comment by pmuir** [comment]
This should be implementable using a pointer in the json unmarshaling
