### ISSUE TITLE
Decrease image sizes for all builders

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#5639]
## Summary

The image size for builders is close to 4Gb, we need to reduce the size of these images.

**Comment by deanesmith** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Discovery - Reduce builder image size #5644](https://github.com/jenkins-x/jx/issues/5644) | N/A | daveconde | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Prepare CJXD V4 Release #63](https://github.com/cloudbees/cloudbees-jenkins-x-distro/issues/63) | N/A | daveconde | Open


###### do-not-edit-end-codetree-epic-issues
