### ISSUE TITLE
Discovery - Reduce builder image size

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#5644]
## Summary

The builder image size is over 4Gb. This is a place holder issue to track we need a discovery around reducing builder image sizes.  Details TBC

**Comment by abayer** [comment]
We've probably optimized the size as much as we can without actively removing things from images, so at this point, the discovery I think should be more focused on "how do we restructure build packs in particular to use more granular images".

**Comment by abayer** [comment]
Also, as of this weekend, the biggest of the non-ml images is `builder-go-maven`, I believe, at ~3.7gb. @cagiti and I made some big improvements there. =)
