### ISSUE TITLE
Enable IRSA and hardcode the default mapped permissions to ServiceAccounts

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5645]
### Summary 
For now we will just enable IRSA (https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) when installing Jenkins-X and enable a list of hardcoded permissions to service accounts so we can keep implementing features.

After we are done with this, we can work on https://github.com/jenkins-x/jx/issues/5642 to make it more dynamic.

**Comment by Larzack** [comment]
STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall in dir: env

jx boot has only been validated on GKE, we'd love feedback and contributions for other Kubernetes providers
? Continue execution anyway? Yes

Enter the cluster you want to jx boot
verifying the kubernetes cluster before we try to boot Jenkins X in namespace: yousoon
we will try to lazily create any missing resources to get the current cluster ready to boot Jenkins X
attempting to lazily create the deploy namespace yousoon
Namespace yousoon created 
setting the local kubernetes context to the deploy namespace yousoon
Now using namespace 'yousoon' on server 'https://0E8F88B335310C49A692297EB7217E90.sk1.eu-west-1.eks.amazonaws.com'.
verifying the CLI packages
verifying the CLI package using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: master
using version 2.0.845 of jx
the CLI packages seem to be setup correctly kubectl, git, helm

NAME               VERSION
jx                 2.0.845
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.1
helm client        v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
WARNING: Your requirements have not enabled cloud storage for logs - we recommend enabling this for kubernetes provider eks
WARNING: Your requirements have not enabled cloud storage for reports - we recommend enabling this for kubernetes provider eks
WARNING: Your requirements have not enabled cloud storage for repository - we recommend enabling this for kubernetes provider eks
WARNING: Your requirements have not enabled cloud storage for backup - we recommend enabling this for kubernetes provider eks
the storage looks good
helm installed and configured
helm client is setup
ensure we have the helm repository https://storage.googleapis.com/chartmuseum.jenkins-x.io
attempting to lazily create the IAM Role for Service Accounts permissions
Enabling IRSA for cluster yousoon associating the IAM Open ID Connect provider
[ℹ]  using region eu-west-1
[ℹ]  (plan) would create IAM Open ID Connect provider for cluster "yousoon" in "eu-west-1"
[!]  no changes were applied, run again with '--approve' to apply the changes
error: error creating the IRSA managed Service Accounts: there was a problem creating the policies stack and returning the template values: open eks/templates/jenkinsx-policies.yml: no such file or directory
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall' command in directory 'env', output: ''

**Comment by Larzack** [comment]
If I try the command using CLI

```iMac:jenkins-x-boot-config jmorgado$ eksctl utils associate-iam-oidc-provider --name jemoco --region eu-west-1 --approve
[ℹ]  using region eu-west-1
[✖]  fetching cluster status to determine operability: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: jemoco.
	status code: 404, request id: 3df545be-6713-4bd8-becb-272843375b1a```
<img width="1001" alt="Capture d’écran 2019-10-09 à 20 54 25" src="https://user-images.githubusercontent.com/16376505/66511319-038dbe80-ead7-11e9-96da-77988e248bf3.png">
