### ISSUE TITLE
private free github repositories for apps/environments break ChatOps

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#5648]
our current default in [jx boot](https://jenkins-x.io/docs/getting-started/setup/boot/) and [creating new quickstartst](https://jenkins-x.io/docs/getting-started/first-project/create-quickstart/) is to use a personal private git repository.

However the github REST API does not support querying PRs on private personal repositories (it works for GitHub Team + GHE though) which means ChatOps breaks on the repository in prow/lighthouse.

We should maybe only use private repos if not using personal owners to avoid setting users up for a fail? Specifically creating quickstarts which then get no ChatOps on PRs

**Comment by jstrachan** [comment]
this REST API returns 404 when using a private personal git repo versus a public one: https://developer.github.com/v3/pulls/#get-a-single-pull-request

**Comment by hferentschik** [comment]
> However the github REST API does not support querying PRs on private personal repositories (it works for GitHub Team + GHE though)

You mean this is not at all supported or is this an authentication issue?

> We should maybe only use private repos if not using personal owners to avoid setting users up for a fail? 
 
That's a possibility. So far we avoided explicit checks like _IsUser_ vs _IsOrg_ and just print some generic messages. Maybe we need to dig a bit deeper here and determine the "type" of owner and act accordingly or at least print even more specific messages.

**Comment by hferentschik** [comment]
* Verify the limitation on the GitHub API
* If limitation is real add some additional warnings

**Comment by hferentschik** [comment]
> this REST API returns 404 when using a private personal git repo versus a public one: https://developer.github.com/v3/pulls/#get-a-single-pull-request

Are you sure this is not an authentication issue? You are getting a 404 when you are trying to get pull request for a private repo you don't have permissions for.

When I  `curl` for pull request like this 

```bash
$ curl -u <user>:<token>  https://api.github.com/repos/<user>/<repo>/pulls
```
against a repo I have access to I get a valid response. If I try the same request against a private repo I don't have access to I get a 404.

**Comment by jstrachan** [comment]
apologies - this was pilot error in my unit test; using the wrong token!

**Comment by hferentschik** [comment]
Closing this issue since it was caused by a wrong token. The API works as expected.
