### ISSUE TITLE
Issue promoting to environment stable chart prometheus-operator

### ISSUE THREAD

**Issue by rousl4n** [jenkins-x/jx#5654]
### Summary 
Helm charts not deploying properly using the Promotion to Staging with JX & Helm Install.

### Steps to reproduce the behavior

Not working solution:
```
jx promote -f stable/prometheus-operator --env staging
```

### Expected behavior

Expecting the same behavior than the command:
```
helm install --name myprometheus --namespace staging stable/prometheus-operator
```
& helm upgrade works perfectly after the first install.

### Actual behavior

Deployment stuck in kind of pending state with no updates. If you plan to push another commit to staging the deployment will fail systematically mentionning PVC issue but it's not the case if using helm directly without going through Jenkins.

### Jx version

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.803
jenkins x platform 2.0.1296
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.15.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS cluster created using terraform scripts.

### Operating system / Environment

MacOS : 10.14.6 (18G103)

**Comment by pmuir** [comment]
Can you provide the logs for the staging environment PR and release builds.

**Comment by rousl4n** [comment]
> Can you provide the logs for the staging environment PR and release builds.

the logs for the initial promotion :
`Push event to branch master
Connecting to https://api.github.com using rousl4n/****** (API Token for acccessing https://github.com Git service inside pipelines)
Obtained Jenkinsfile from 68836fe677ae9cf5aaad198e3f18675cec306ccc
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
Agent maven-0qrrg is provisioned from template Kubernetes Pod Template
---
apiVersion: "v1"
kind: "Pod"
metadata:
  annotations: {}
  labels:
    jenkins: "slave"
    jenkins/jenkins-maven: "true"
  name: "maven-0qrrg"
spec:
  containers:
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    env:
    - name: "MAVEN_OPTS"
      value: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
    - name: "DOCKER_CONFIG"
      value: "/home/jenkins/.docker/"
    - name: "GIT_AUTHOR_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "GIT_COMMITTER_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "GIT_COMMITTER_NAME"
      value: "jenkins-x-bot"
    - name: "_JAVA_OPTIONS"
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true\
        \ -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4\
        \ -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m"
    - name: "GIT_AUTHOR_NAME"
      value: "jenkins-x-bot"
    - name: "XDG_CONFIG_HOME"
      value: "/home/jenkins"
    - name: "JENKINS_URL"
      value: "http://jenkins:8080"
    image: "gcr.io/jenkinsxio/builder-maven:0.1.815"
    imagePullPolicy: "IfNotPresent"
    name: "maven"
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/.docker"
      name: "volume-2"
      readOnly: false
    - mountPath: "/root/.m2"
      name: "volume-1"
      readOnly: false
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins/.gnupg"
      name: "volume-3"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - args:
    - "********"
    - "maven-0qrrg"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "jenkins-agent:50000"
    - name: "GIT_AUTHOR_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "GIT_COMMITTER_NAME"
      value: "jenkins-x-bot"
    - name: "GIT_AUTHOR_NAME"
      value: "jenkins-x-bot"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "XDG_CONFIG_HOME"
      value: "/home/jenkins"
    - name: "MAVEN_OPTS"
      value: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
    - name: "DOCKER_CONFIG"
      value: "/home/jenkins/.docker/"
    - name: "JENKINS_AGENT_NAME"
      value: "maven-0qrrg"
    - name: "GIT_COMMITTER_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "_JAVA_OPTIONS"
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true\
        \ -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4\
        \ -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m"
    - name: "JENKINS_NAME"
      value: "maven-0qrrg"
    - name: "JENKINS_URL"
      value: "http://jenkins:8080"
    image: "jenkinsci/jnlp-slave:3.26-1-alpine"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      privileged: false
    tty: false
    volumeMounts:
    - mountPath: "/home/jenkins/.docker"
      name: "volume-2"
      readOnly: false
    - mountPath: "/root/.m2"
      name: "volume-1"
      readOnly: false
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins/.gnupg"
      name: "volume-3"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  nodeSelector: {}
  restartPolicy: "Never"
  serviceAccount: "jenkins"
  volumes:
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-0"
  - name: "volume-2"
    secret:
      secretName: "jenkins-docker-cfg"
  - name: "volume-1"
    secret:
      secretName: "jenkins-maven-settings"
  - emptyDir: {}
    name: "workspace-volume"
  - name: "volume-3"
    secret:
      secretName: "jenkins-release-gpg"

Running on maven-0qrrg in /home/jenkins/agent/workspace/ironment-gagarine-staging_master
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
using credential jx-pipeline-git-github-github
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/distribe/environment-gagarine-staging.git
 > git init /home/jenkins/agent/workspace/ironment-gagarine-staging_master # timeout=10
Fetching without tags
Checking out Revision 68836fe677ae9cf5aaad198e3f18675cec306ccc (master)
Fetching upstream changes from https://github.com/distribe/environment-gagarine-staging.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials API Token for acccessing https://github.com Git service inside pipelines
 > git fetch --no-tags --progress -- https://github.com/distribe/environment-gagarine-staging.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/distribe/environment-gagarine-staging.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/distribe/environment-gagarine-staging.git # timeout=10
Fetching upstream changes from https://github.com/distribe/environment-gagarine-staging.git
using GIT_ASKPASS to set credentials API Token for acccessing https://github.com Git service inside pipelines
 > git fetch --no-tags --progress -- https://github.com/distribe/environment-gagarine-staging.git +refs/heads/master:refs/remotes/origin/master
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 68836fe677ae9cf5aaad198e3f18675cec306ccc
Commit message: "prometheus added"
 > git rev-list --no-walk 296f898b0650491d978f09d4984f353074819989 # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Validate Environment)
[Pipeline] container
[Pipeline] {
[Pipeline] dir
Running in /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env
[Pipeline] {
[Pipeline] sh
+ jx step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Update Environment)
[Pipeline] container
[Pipeline] {
[Pipeline] dir
Running in /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env
[Pipeline] {
[Pipeline] sh
+ jx step helm apply
Modified file /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env/Chart.yaml to set the chart to version 2
Copying the helm source directory /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env to a temporary location for building and applying /tmp/jx-helm-apply-919686446/env
Applying helm chart at /tmp/jx-helm-apply-919686446/env as release name jx to namespace jx-staging
verifying the helm requirements versions in dir: . using version stream URL:  and git ref: 
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /root/.jx/jenkins-x-versions
Ignoring templates/.gitignore
Wrote chart values.yaml /tmp/jx-helm-apply-919686446/env/values.yaml generated from directory tree
generated helm /tmp/jx-helm-apply-919686446/env/values.yaml

PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 120.10.167.105.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: 591630454704.dkr.ecr.us-west-2.amazonaws.com
        TILLER_NAMESPACE: kube-system
prometheus-operator:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  coreDns:
    enabled: true
  grafana:
    adminPassword: *********
    grafana.ini:
      server:
        domain: grafana-stg.jx.120.10.167.105.nip.io
        http_port: 3000
        root_url: http://grafana-stg.jx.120.10.167.105.nip.io:80
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      enabled: true
      hosts:
      - grafana-stg.jx.120.10.167.105.nip.io
      tls:
      - hosts:
        - grafana-stg.jx.120.10.167.105.nip.io
        secretName: grafana-stg-tls
    persistence:
      accessModes:
      - ReadWriteOnce
      enabled: true
      size: 10Gi
  kubeDns:
    enabled: false
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
prow: {}

Using values files: /tmp/jx-helm-apply-919686446/env/values.yaml
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Applying Apps chart overrides
Applying chart overrides














WARNING: Could not wait for hook resource to complete as it is kind ClusterRole and name jx-prometheus-operator-admission for phase pre-upgrade
WARNING: Could not wait for hook resource to complete as it is kind ClusterRoleBinding and name jx-prometheus-operator-admission for phase pre-upgrade
WARNING: Could not wait for hook resource to complete as it is kind PodSecurityPolicy and name jx-prometheus-operator-admission for phase pre-upgrade
WARNING: Could not wait for hook resource to complete as it is kind Role and name jx-prometheus-operator-admission for phase pre-upgrade
WARNING: Could not wait for hook resource to complete as it is kind RoleBinding and name jx-prometheus-operator-admission for phase pre-upgrade
WARNING: Could not wait for hook resource to complete as it is kind ServiceAccount and name jx-prometheus-operator-admission for phase pre-upgrade








WARNING: Could not wait for hook resource to complete as it is kind ClusterRole and name jx-prometheus-operator-admission for phase post-upgrade
WARNING: Could not wait for hook resource to complete as it is kind ClusterRoleBinding and name jx-prometheus-operator-admission for phase post-upgrade
WARNING: Job jx-prometheus-operator-admission-patch has not yet terminated for helm hook phase post-upgrade due to: job jx-prometheus-operator-admission-patch never terminated so removing it anyway
WARNING: Could not wait for hook resource to complete as it is kind PodSecurityPolicy and name jx-prometheus-operator-admission for phase post-upgrade
WARNING: Could not wait for hook resource to complete as it is kind Role and name jx-prometheus-operator-admission for phase post-upgrade
WARNING: Could not wait for hook resource to complete as it is kind RoleBinding and name jx-prometheus-operator-admission for phase post-upgrade
WARNING: Could not wait for hook resource to complete as it is kind ServiceAccount and name jx-prometheus-operator-admission for phase post-upgrade
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result`



And the build logs after an additional push : 

`Push event to branch master
Connecting to https://api.github.com using rousl4n/****** (API Token for acccessing https://github.com Git service inside pipelines)
Obtained Jenkinsfile from f0ec8496f0e95f9a59ae3909a404537e2d1dd370
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
Agent maven-2cv05 is provisioned from template Kubernetes Pod Template
---
apiVersion: "v1"
kind: "Pod"
metadata:
  annotations: {}
  labels:
    jenkins: "slave"
    jenkins/jenkins-maven: "true"
  name: "maven-2cv05"
spec:
  containers:
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    env:
    - name: "MAVEN_OPTS"
      value: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
    - name: "DOCKER_CONFIG"
      value: "/home/jenkins/.docker/"
    - name: "GIT_AUTHOR_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "GIT_COMMITTER_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "GIT_COMMITTER_NAME"
      value: "jenkins-x-bot"
    - name: "_JAVA_OPTIONS"
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true\
        \ -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4\
        \ -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m"
    - name: "GIT_AUTHOR_NAME"
      value: "jenkins-x-bot"
    - name: "XDG_CONFIG_HOME"
      value: "/home/jenkins"
    - name: "JENKINS_URL"
      value: "http://jenkins:8080"
    image: "gcr.io/jenkinsxio/builder-maven:0.1.815"
    imagePullPolicy: "IfNotPresent"
    name: "maven"
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/.docker"
      name: "volume-2"
      readOnly: false
    - mountPath: "/root/.m2"
      name: "volume-1"
      readOnly: false
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins/.gnupg"
      name: "volume-3"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - args:
    - "********"
    - "maven-2cv05"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "jenkins-agent:50000"
    - name: "GIT_AUTHOR_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "GIT_COMMITTER_NAME"
      value: "jenkins-x-bot"
    - name: "GIT_AUTHOR_NAME"
      value: "jenkins-x-bot"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "XDG_CONFIG_HOME"
      value: "/home/jenkins"
    - name: "MAVEN_OPTS"
      value: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
    - name: "DOCKER_CONFIG"
      value: "/home/jenkins/.docker/"
    - name: "JENKINS_AGENT_NAME"
      value: "maven-2cv05"
    - name: "GIT_COMMITTER_EMAIL"
      value: "jenkins-x@googlegroups.com"
    - name: "_JAVA_OPTIONS"
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true\
        \ -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4\
        \ -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m"
    - name: "JENKINS_NAME"
      value: "maven-2cv05"
    - name: "JENKINS_URL"
      value: "http://jenkins:8080"
    image: "jenkinsci/jnlp-slave:3.26-1-alpine"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      privileged: false
    tty: false
    volumeMounts:
    - mountPath: "/home/jenkins/.docker"
      name: "volume-2"
      readOnly: false
    - mountPath: "/root/.m2"
      name: "volume-1"
      readOnly: false
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins/.gnupg"
      name: "volume-3"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  nodeSelector: {}
  restartPolicy: "Never"
  serviceAccount: "jenkins"
  volumes:
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-0"
  - name: "volume-2"
    secret:
      secretName: "jenkins-docker-cfg"
  - name: "volume-1"
    secret:
      secretName: "jenkins-maven-settings"
  - emptyDir: {}
    name: "workspace-volume"
  - name: "volume-3"
    secret:
      secretName: "jenkins-release-gpg"

Running on maven-2cv05 in /home/jenkins/agent/workspace/ironment-gagarine-staging_master
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
using credential jx-pipeline-git-github-github
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/distribe/environment-gagarine-staging.git
 > git init /home/jenkins/agent/workspace/ironment-gagarine-staging_master # timeout=10
Fetching upstream changes from https://github.com/distribe/environment-gagarine-staging.git
 > git --version # timeout=10
Fetching without tags
Checking out Revision f0ec8496f0e95f9a59ae3909a404537e2d1dd370 (master)
using GIT_ASKPASS to set credentials API Token for acccessing https://github.com Git service inside pipelines
 > git fetch --no-tags --progress -- https://github.com/distribe/environment-gagarine-staging.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/distribe/environment-gagarine-staging.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/distribe/environment-gagarine-staging.git # timeout=10
Fetching upstream changes from https://github.com/distribe/environment-gagarine-staging.git
using GIT_ASKPASS to set credentials API Token for acccessing https://github.com Git service inside pipelines
 > git fetch --no-tags --progress -- https://github.com/distribe/environment-gagarine-staging.git +refs/heads/master:refs/remotes/origin/master
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f0ec8496f0e95f9a59ae3909a404537e2d1dd370
Commit message: "prometheus added"
 > git rev-list --no-walk 68836fe677ae9cf5aaad198e3f18675cec306ccc # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Validate Environment)
[Pipeline] container
[Pipeline] {
[Pipeline] dir
Running in /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env
[Pipeline] {
[Pipeline] sh
+ jx step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Update Environment)
[Pipeline] container
[Pipeline] {
[Pipeline] dir
Running in /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env
[Pipeline] {
[Pipeline] sh
+ jx step helm apply
Modified file /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env/Chart.yaml to set the chart to version 3
Copying the helm source directory /home/jenkins/agent/workspace/ironment-gagarine-staging_master/env to a temporary location for building and applying /tmp/jx-helm-apply-536263586/env
Applying helm chart at /tmp/jx-helm-apply-536263586/env as release name jx to namespace jx-staging
verifying the helm requirements versions in dir: . using version stream URL:  and git ref: 
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /root/.jx/jenkins-x-versions
Ignoring templates/.gitignore
Wrote chart values.yaml /tmp/jx-helm-apply-536263586/env/values.yaml generated from directory tree
generated helm /tmp/jx-helm-apply-536263586/env/values.yaml

PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 120.10.167.105.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: 591630454704.dkr.ecr.us-west-2.amazonaws.com
        TILLER_NAMESPACE: kube-system
prometheus-operator:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  coreDns:
    enabled: true
  grafana:
    adminPassword: *******#
    grafana.ini:
      server:
        domain: grafana-stg.jx.120.10.167.105.nip.io
        http_port: 3000
        root_url: http://grafana-stg.jx.120.10.167.105.nip.io:80
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      enabled: true
      hosts:
      - grafana-stg.jx.120.10.167.105.nip.io
      tls:
      - hosts:
        - grafana-stg.jx.120.10.167.105.nip.io
        secretName: grafana-stg-tls
    persistence:
      accessModes:
      - ReadWriteOnce
      enabled: true
      size: 10Gi
  kubeDns:
    enabled: false
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
prow: {}

Using values files: /tmp/jx-helm-apply-536263586/env/values.yaml
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Applying Apps chart overrides
Applying chart overrides












error: upgrading helm chart '.': failed to run 'kubectl apply --recursive -f /tmp/helm-template-workdir-256725836/jx/output/namespaces/jx-staging -l jenkins.io/chart-release=jx --namespace jx-staging --wait --validate=false' command in directory '/tmp/jx-helm-apply-536263586/env', output: 'role.rbac.authorization.k8s.io/cleanup configured
rolebinding.rbac.authorization.k8s.io/cleanup configured
serviceaccount/cleanup configured
configmap/exposecontroller configured
role.rbac.authorization.k8s.io/expose configured
rolebinding.rbac.authorization.k8s.io/expose configured
serviceaccount/expose configured
clusterrole.rbac.authorization.k8s.io/jx-grafana-clusterrole configured
clusterrolebinding.rbac.authorization.k8s.io/jx-grafana-clusterrolebinding configured
configmap/jx-grafana-config-dashboards configured
configmap/jx-grafana configured
deployment.apps/jx-grafana configured
ingress.extensions/jx-grafana configured
podsecuritypolicy.extensions/jx-grafana configured
role.rbac.authorization.k8s.io/jx-grafana configured
rolebinding.rbac.authorization.k8s.io/jx-grafana configured
secret/jx-grafana configured
service/jx-grafana configured
serviceaccount/jx-grafana configured
configmap/jx-grafana-test configured
podsecuritypolicy.extensions/jx-grafana-test configured
role.rbac.authorization.k8s.io/jx-grafana-test configured
rolebinding.rbac.authorization.k8s.io/jx-grafana-test configured
serviceaccount/jx-grafana-test configured
clusterrole.rbac.authorization.k8s.io/jx-kube-state-metrics configured
clusterrolebinding.rbac.authorization.k8s.io/jx-kube-state-metrics configured
deployment.apps/jx-kube-state-metrics configured
podsecuritypolicy.policy/jx-kube-state-metrics configured
clusterrole.rbac.authorization.k8s.io/psp-jx-kube-state-metrics configured
clusterrolebinding.rbac.authorization.k8s.io/psp-jx-kube-state-metrics configured
service/jx-kube-state-metrics configured
serviceaccount/jx-kube-state-metrics configured
daemonset.extensions/jx-prometheus-node-exporter configured
clusterrole.rbac.authorization.k8s.io/psp-jx-prometheus-node-exporter configured
clusterrolebinding.rbac.authorization.k8s.io/psp-jx-prometheus-node-exporter configured
podsecuritypolicy.extensions/jx-prometheus-node-exporter configured
service/jx-prometheus-node-exporter configured
serviceaccount/jx-prometheus-node-exporter configured
alertmanager.monitoring.coreos.com/jx-prometheus-operator-alertmanager configured
clusterrole.rbac.authorization.k8s.io/jx-prometheus-operator-alertmanager configured
clusterrolebinding.rbac.authorization.k8s.io/jx-prometheus-operator-alertmanager configured
podsecuritypolicy.policy/jx-prometheus-operator-alertmanager configured
secret/alertmanager-jx-prometheus-operator-alertmanager configured
service/jx-prometheus-operator-alertmanager configured
serviceaccount/jx-prometheus-operator-alertmanager configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-alertmanager configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-coredns configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-apiserver configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-kube-controller-manager configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-kube-etcd configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-kube-proxy configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-kube-scheduler configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-kube-state-metrics configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-kubelet configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-node-exporter configured
configmap/jx-prometheus-operator-grafana-datasource configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-grafana configured
clusterrole.rbac.authorization.k8s.io/jx-prometheus-operator-prometheus configured
clusterrolebinding.rbac.authorization.k8s.io/jx-prometheus-operator-prometheus configured
prometheus.monitoring.coreos.com/jx-prometheus-operator-prometheus configured
clusterrole.rbac.authorization.k8s.io/jx-prometheus-operator-prometheus-psp configured
clusterrolebinding.rbac.authorization.k8s.io/jx-prometheus-operator-prometheus-psp configured
podsecuritypolicy.policy/jx-prometheus-operator-prometheus configured
service/jx-prometheus-operator-prometheus configured
serviceaccount/jx-prometheus-operator-prometheus configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-prometheus configured
mutatingwebhookconfiguration.admissionregistration.k8s.io/jx-prometheus-operator-admission configured
validatingwebhookconfiguration.admissionregistration.k8s.io/jx-prometheus-operator-admission configured
clusterrole.rbac.authorization.k8s.io/jx-prometheus-operator-operator configured
clusterrolebinding.rbac.authorization.k8s.io/jx-prometheus-operator-operator configured
deployment.apps/jx-prometheus-operator-operator configured
clusterrole.rbac.authorization.k8s.io/jx-prometheus-operator-operator-psp configured
clusterrolebinding.rbac.authorization.k8s.io/jx-prometheus-operator-operator-psp configured
podsecuritypolicy.policy/jx-prometheus-operator-operator configured
service/jx-prometheus-operator-operator configured
serviceaccount/jx-prometheus-operator-operator configured
servicemonitor.monitoring.coreos.com/jx-prometheus-operator-operator configured
The PersistentVolumeClaim "jx-grafana" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims'
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE`
