### ISSUE TITLE
jx get activity does not allow to specify the build number in the filter

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5657]
### Summary 

```bash
> jx get activity --filter  "hf-bee-bot/environment-foo-dev/master #10"
```

does not work, even though the same filter works for getting the build logs:

```bash
> jx get build logs --filter  "hf-bee-bot/environment-foo-dev/master #10"
```

On the other hand, the following works for activities:

```bash
> jx get activity --filter  "hf-bee-bot/environment-foo-dev/master" --build 10
```

but not for build logs. See also #5656 

The --filter and --build options need to be fixed and aligned between commands.

**Comment by abayer** [comment]
I have been having a craving to completely rework arguments to `jx get activity`. It's too heavy-handed for how I'd like to use it. We should really be able to pass things like owner/repo/branch in without having to do so via `--filter`, IMO.
