### ISSUE TITLE
jx boot upgrade: PR pipeline needs to use upgraded builder

### ISSUE THREAD

**Issue by macox** [jenkins-x/jx#5658]
## Summary

During the `jx upgrade boot` process a PR is created containing all the upgrade commits. The PR pipeline can fail as the builder it's using is the existing version, but it actually needs to use the version that we are upgrading to,  ensuring compatibility with changes in the PR.

## Acceptance Criteria
- During the run of the upgrade pipeline the builder image that is in the version stream that is specified in the jx-requirements.yaml should be used

**Comment by daveconde** [comment]
@abayer I would love your thoughts on the best approach to make sure the correct builder image is used here, I think ideally we don't commit a specific builder version in to the dev env repository.

**Comment by abayer** [comment]
So there’s a chicken and the egg problem here - we can’t rely on the logic that will pick up the builder version from the version stream until we’re using the new version stream! My first instinct is that committing the new builder version is fine - if this is part of `jx boot upgrade` execution, it’ll always get updated properly when we run it again in the future. The alternatives that come to mind all involve somehow special casing the resolution of the builder image for boot upgrades, which seems like an excess layer of complexity.
