### ISSUE TITLE
jx boot upgrade: Vault operator uses existing version stream from team settings

### ISSUE THREAD

**Issue by macox** [jenkins-x/jx#5660]
## Summary

During the build pipeline for the PR created by the upgrade process the vault operator fails as version stream ref in the team settings is updated after the vault operator is updated.

## Acceptance Criteria
- When upgrading in a boot pipeline the version stream ref should be updated in the team settings before the vault operator is update.

**Comment by ccojocar** [comment]
This should be fixed by https://github.com/jenkins-x/jx/pull/5741

**Comment by dgozalo** [comment]
Reopened because we still need to update the team settings with the latest ref of the versions stream in the dev environment.
