### ISSUE TITLE
jx step verify pod ready cannot be use in the pipelines

### ISSUE THREAD

**Issue by jnsvd** [jenkins-x/jx#5662]
### Summary 

The command `jx step verify pod ready` can't be used as a step in the pipeline, because the build pod is running in the `jx` namespace and it's impossible to change context in the pipeline (`jx ns jx-staging` results in `there is no context defined in your Kubernetes configuration - we may be inside a test case or pod?`).

### Steps to reproduce the behavior

In the Jenkinsfile of an environment repository `environment-jx-staging`, add line:

```
sh "jx step verify pod ready -w 30s"
```

### Expected behavior

Verification that the pods in namespace `jx-staging` are ready (wait up to 30s).

### Actual behavior

Verification that the pods in namespace `jx` are ready.

### Proposed fix

Add a parameter to run the command in a given namespace, e.g. `jx step verify pod ready -n jx-staging -w 30s`

### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 2.0.424
jenkins x platform 2.0.768
Kubernetes cluster v1.13.10
kubectl            v1.14.6
helm client        v2.12.1+g02a47c7
helm server        v2.14.1+g5270352
git                git version 2.21.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

Azure AKS

### Operating system / Environment

Mac OS X 10.14.6 build 18G95

**Comment by vvijayalakshmi21** [comment]
Hi, I am Outreachy applicant looking to contribute
Kindly let me know if this issue is still open and if yes, can you please assign to me?
