### ISSUE TITLE
[REQUEST][DEVPOD ISSUE] Update skaffold.yaml files in the Jenkins X Kubernetes Build Packs to work with Skaffold version 0.38.0

### ISSUE THREAD

**Issue by kdevu** [jenkins-x/jx#5664]
Hi,

Correct me if I'm wrong anywhere.

I see this merge request https://github.com/jenkins-x/jenkins-x-builders-base/commit/8262a41f9b9dda0eb93510ab229dfbceb63a4d90 that upgraded skaffold to version 0.38.0 for the base builder. 

I also see this commit https://github.com/jenkins-x/jenkins-x-builders/commit/4addfc93b70c97b7382eb0d3d932ec672364fd7c that bumps versions up, so all the other builder should now use the changes implemented in the above merge request. So all the builders now use skaffold version 0.38.0(?).

But I can see that there have been no updates to the `skaffold.yaml` files in the [Jenkins X Kubernetes Build Packs](https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/maven/skaffold.yaml).  For example, this is the link to the `maven` build pack. 

Skaffold version 0.38.0 does not work with the current `skaffold.yaml` file in those build packs, **so would it be possible for all the kubernetes build packs with `skaffold.yaml` files to be updated to work with Skaffold version 0.38.0?**

---

**For clarity, this is an issue directly related to using devpods**, and for further context, I've been using the devpods and decided to upgrade the skaffold version in the devpod to version 0.38.0.

Skaffold version 0.38.0 does not work with the following `skaffold.yaml` file. This is the same `skaffold.yaml` file in the `maven` build pack that I linked above.  

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: org/serviceName
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: serviceName
        chartPath: charts/serviceName
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
```

When I run the the `./watch.sh` script in the devpod, with the above `skaffold.yaml` file. I get the following error in the logs.

```bash
$ ./watch.sh

...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.681 s
[INFO] Finished at: 2019-10-01T11:22:36Z
[INFO] ------------------------------------------------------------------------
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead. 
Generating tags...
 - org/serviceName -> FATA[0000] failed to build: generating tag for org/serviceName: {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are deprecated, image digest will now automatically be appended to image tags 
 ```

The script freezes there. With version 0.37.0 `FATA` (at the end of the log above) would be `WARN` and the script would continue. But with version 0.38.0 the`./watch` script will not work as intended.

---

I made an issue about this in the Skaffold repository and someone was kind enough to suggest these actions to get the `skaffold.yaml` file in sync with the Skaffold version being used. This is the [link](https://github.com/GoogleContainerTools/skaffold/issues/2923#issuecomment-534229529) to that suggestion.

**Comment by tdcox** [comment]
Just run into this problem here.

**Comment by garethjevans** [comment]
@tdcox can you try and run a local `skaffold fix --overwrite` to update the skaffold.yaml to the local schema version?

**Comment by garethjevans** [comment]
https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/pull/73 should help fix this

**Comment by craft-de-jet** [comment]
> @tdcox can you try and run a local `skaffold fix --overwrite` to update the skaffold.yaml to the local schema version?

this did not work!

**Comment by craft-de-jet** [comment]
> [jenkins-x-buildpacks/jenkins-x-kubernetes#73](https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/pull/73) should help fix this

this did not work.

every time the branch returns to `master` and same issue comes up

can you tell how to use your fix please...

**Comment by craft-de-jet** [comment]
### Summary 
`sh ./watch.sh` is failing in `devpod` due to deprecated `skaffold.yaml` stanza.
```bash
Generating tags...
 - `<my-project-name>` -> FATA[0000] failed to build: generating tag for
       `<my-project-name>`: {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are
       deprecated, image digest will now automatically be appended to image tags
```

### Steps to reproduce the behavior
- create a `spring` project

  `jx create quickstart -f spring`

- create a `devpod`
  `jx create devpod --sync`

- run `watch.sh` inside `devpod`
  `sh ./watch.sh`

### Expected behavior
`dev` image should be created and deployed inside developer's `namespace`

### Actual behavior
got `skaffold` build error
```bash
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
Generating tags...
 - `<my-project-name>` -> FATA[0000] failed to build: generating tag for `<my-project-name>`: {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are
 deprecated, image digest will now automatically be appended to image tags
```

### Jx version

The output of `jx version` is:
```bash
$ jx version
NAME               VERSION
jx                 2.1.58
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Kubernetes cluster

cluster provider: `gke`

cluster created using `terraform`

```bash
$ cat main.tf              
module "jx" {
  source = "jenkins-x/jx/google"

  gcp_project = "gke-project"
  
  cluster_name = "org-gke"

  dev_env_approvers = ["git-org]

  git_owner_requirement_repos = "git-org"
}
```
```bash
terraform init                                                                                                                                                                                              
terraform apply
```

### Operating system / Environment
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by jatikuma29iv** [comment]
### Summary 
`sh ./watch.sh` is failing in `devpod` due to deprecated `skaffold.yaml` stanza.
```bash
Generating tags...
 - `<my-project-name>` -> FATA[0000] failed to build: generating tag for
       `<my-project-name>`: {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are
       deprecated, image digest will now automatically be appended to image tags
```

### Steps to reproduce the behavior
- create a `spring` project

  `jx create quickstart -f spring`

- create a `devpod`
  `jx create devpod --sync`

- run `watch.sh` inside `devpod`
  `sh ./watch.sh`

### Expected behavior
`dev` image should be created and deployed inside developer's `namespace`

### Actual behavior
got `skaffold` build error
```bash
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
WARN[0000] Using SKAFFOLD_DEPLOY_NAMESPACE env variable is deprecated. Please use SKAFFOLD_NAMESPACE instead.
Generating tags...
 - `<my-project-name>` -> FATA[0000] failed to build: generating tag for `<my-project-name>`: {{.DIGEST}}, {{.DIGEST_ALGO}} and {{.DIGEST_HEX}} are
 deprecated, image digest will now automatically be appended to image tags
```

### Jx version

The output of `jx version` is:
```bash
$ jx version
NAME               VERSION
jx                 2.1.58
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Kubernetes cluster

cluster provider: `gke`

cluster created using `terraform`

```bash
$ cat main.tf              
module "jx" {
  source = "jenkins-x/jx/google"

  gcp_project = "gke-project"
  
  cluster_name = "org-gke"

  dev_env_approvers = ["git-org]

  git_owner_requirement_repos = "git-org"
}
```
```bash
terraform init                                                                                                                                                                                              
terraform apply
```

### Operating system / Environment
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```
