### ISSUE TITLE
jx delete application failing with merge conflict

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5670]
### Summary 
`jx delete application` still seems very brittle. git merge operations are currently failing with Merge Conflict errors on the copy of the environment repo cached in ~/.jx

### Jx version

The output of `jx version` is:

```
2.0.775
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
https://github.com/jenkins-x/jx/issues/5609
