### ISSUE TITLE
jx delete application needs an environment selector

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5671]
### Summary 
Currently, `jx delete application` removes the selected applications from all environments. Typically, it would be necessary to be able to remove applications selectively from some production or staging environments but leave them running in others so it would be helpful to both warn the user what is going to happen and to provide a filter to permit selected environments to be included/excluded.

Ideally, we would have a review and sign-off process around this activity as well.

### Jx version

The output of `jx version` is:

```
2.0.775
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by mauromorales** [comment]
Implementation will depend on resolution of #6069
