### ISSUE TITLE
jx boot TLS not enabled warning

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5683]
### Summary 
During the jx boot setup, the following error is issued:
```
WARNING: TLS is not enabled so your webhooks will be called using HTTP. This means your webhook secret will be sent to your cluster in the clear. See https://jenkins-x.io/architecture/tls for more information
? Do you wish to continue?
```

That is effectively saying "We are going to do a complicated bad thing as our default behaviour! Would you like us to carry on, or would you prefer to abandon this and try someone else's product?"

TLS should be the default, with an exception process for creating insecure demo clusters as an explict choice.

### Jx version

The output of `jx version` is:

```
2.0.808
```

**Comment by tdcox** [comment]
If you answer 'No' to this request to continue, you actually get a bunch of errors:
```
error: cannot continue because TLS is not enabled.
error: failed to interpret pipeline file /Users/terry/Documents/code/jxtesting/d63/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall' command in directory '/Users/terry/Documents/code/jxtesting/d63/jenkins-x-boot-config/env', output: ''
```

**Comment by deanesmith** [comment]
Since a domain is required for TLS there are complexities with establishing TLS as the default.  This is a long term initiative.  In the meantime we'll improve the messaging.

**Comment by ccojocar** [comment]
@tdcox @deanesmith Can we close this issue since the warning message was improved quite a bit? I think that now we provide a default `jx-requirements.yml` file at least with CJXD which enables TLS by default for GCP/GKE or AWS/EKS.
