### ISSUE TITLE
Vault still not working with jx boot 

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5687]
### Summary 
jx boot fails when trying to install with vault enabled:
```
STEP: install-vault command: /bin/sh -c jx step boot vault in dir: systems/vault

error: failed to load vault ingress template file vault-ing.tmpl.yaml: failed to execute Ingress template: vault-ing.tmpl.yaml: template: vault-ing.tmpl.yaml:7:24: executing "vault-ing.tmpl.yaml" at <.Requirements.cluster.vaultName>: map has no entry for key "vaultName"
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault' command in directory 'systems/vault', output: ''
```

### Jx version

The output of `jx version` is:

```
2.0.808
```

**Comment by tdcox** [comment]
Setting cluster.vaultName manually allows the setup to continue. Vault is installed but never becomes accessible because the DNS entry is never created by external DNS.

The error is:
```
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
error: creating system vault URL client: wait for vault to be initialized and unsealed: reading vault health: Get https://vault-jx.kill-9.uk/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup vault-jx.kill-9.uk on 192.168.50.1:53: no such host
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create values --name parameters' command in directory 'env', output: ''
```

**Comment by deanesmith** [comment]
@tdcox does an updated boot config help?

**Comment by hongfei-zhou** [comment]
Having the same issue here, @deanesmith what is the updated boot config?

**Comment by tdcox** [comment]
@deanesmith Could you be more specific, please?

**Comment by deanesmith** [comment]
@tdcox and @hongfei-zhou just curious if this the plain (default) boot config or were there extensive customizations?

**Comment by deanesmith** [comment]
@hongfei-zhou you also on 2.0.808 or thereabouts?

**Comment by hongfei-zhou** [comment]
@deanesmith Sorry for missing that info, here the output of `jx version`

NAME               VERSION
jx                 2.0.845
Kubernetes cluster v1.13.6-gke.13
kubectl            v1.14.2
git                2.23.0
Operating System   Mac OS X 10.15 build 19A583

**Comment by deanesmith** [comment]
Thank you.  That helps.

**Comment by hongfei-zhou** [comment]
I found that the error is from the external DNS part where I didn't have the zone set in cloud DNS for the subdomain I used. After adding the zone and recreate the cluster, the error was gone.

**Comment by deanesmith** [comment]
Looks like bucket zone also needs to be consistent with the cluster zone.    Also, we're finding if buckets weren't removed from a previous cluster, and the zones aren't consistent, it can error out. We're going to add some better handling here for sure.

**Comment by tdcox** [comment]
No longer seeing this problem in `2.0.1103`
