### ISSUE TITLE
A few problems with jx init - No JenkinsFile

### ISSUE THREAD

**Issue by nicholasmparker** [jenkins-x/jx#569]
I'm on Ubuntu 17.10
I tried doing jx import with a C# app, and it seemed to work, except it did not create a JenkinsFile.  

I originally had a Dockerfile in the project, so I started fresh, deleted that and did another import.  It created charts and Dockerfile, but no JenkinsFile.

I tried the same with the golang quickstart using:
jx create quickstart
and selecting golang-http

It created the Dockerfile with the csharp template instead of the go template, and did not create a JenkinsFile

**Comment by nicholasmparker** [comment]
Update - I updated jx to the latest version and was able to create the go quickstart, although the JenkinsFile still isn't created for importing an existing project.

**Comment by nicholasmparker** [comment]
One more - let me know if I should create a new issue.  When going through quickstart on golang, I'm getting this on build:

WARNING: Failed to query the Pull Request last commit status for https://github.com/****/environment-cubchip-staging/pull/2 ref c4b4871ece84ab7a8dfb865242d14bc4519237ab Could not find a status for repository ****/environment-cubchip-staging with ref c4b4871ece84ab7a8dfb865242d14bc4519237ab

It timed out after an hour.

**Comment by jstrachan** [comment]
Btw we have not yet added a Jenkinsfile to the C# build pack. See https://github.com/jenkins-x/jx/issues/561
