### ISSUE TITLE
Multiple source repos updated by separate create pr calls in a single PR doesn't update matrix markdown correctly

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5690]
See https://github.com/jenkins-x/jenkins-x-platform/pull/6266 for an example - in the first commit, `jenkins-x-builders` is updated properly (https://github.com/jenkins-x/jenkins-x-platform/pull/6266/commits/f13bbb5e0efaef27b39e959c7bc2d7bbb5941e7d#diff-988ada887aee469f31a9e1b44314e571R8), but in the final commit, `jx` is updated and `jenkins-x-builders` is reverted (https://github.com/jenkins-x/jenkins-x-platform/pull/6266/commits/4bc1f3e3ca21f37f5aa5effbdb91dd4070a26326#diff-988ada887aee469f31a9e1b44314e571R8-R9).

This is happening because the markdown is generated during the `jx step create pr` call _before_ rebasing the changes on top of the existing PR. That means that the dependency matrix only contains changes from the current `jx step create pr` call vs `master`. In practice, the `matrix.yaml` updates correctly, since that's just diffs to the marshaled YAML, but the markdown isn't. 

In this case, we're calling `jx step create pr` multiple times with different source repos in one repo's release process, but the same thing would happen if, say, `jx` and `jenkins-x-builders` both called `jx step create pr` independently but pushed to the same destination PR.

It feels like we should probably be checking for an existing PR earlier in the process of `jx step create pr`, or waiting to generate the markdown until after we've potentially rebased on an existing PR.

**Comment by abayer** [comment]
cc @cagiti and @pmuir to see if there's something obvious I'm missing. =)

**Comment by cagiti** [comment]
I'm wondering whether the markdown should be generated as a release pipeline step?

**Comment by abayer** [comment]
Hmm...maybe. #5033 would probably fix it too, since the idea there is to work off a local clone of target repos for multiple `jx step create pr` calls and only push after they're all done.
