### ISSUE TITLE
jx boot failed "at error: generating Prow config: No source repository resources were found"

### ISSUE THREAD

**Issue by onewsch** [jenkins-x/jx#5698]
### Summary 
When using "jx boot" on an existing OKE cluster, it failed at
"
STEP: apply-pipeline-schedulers command: /bin/sh -c jx step scheduler config apply --direct=true in dir: prowConfig

error: generating Prow config: No source repository resources were found
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step scheduler config apply --direct=true' command in directory 'prowConfig', output: ''
"
Even in jx-requirements.yml i set "webhook: lighthouse"
### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.808
Kubernetes cluster v1.13.5-5+270f968ee96a91
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.5 build 18F132


verifying packages```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
OKE cluster, using Oracle Cloud Inrastructure console
-->

### Operating system / Environment

<!--
In which environment are you running the jx CLI?
MacOS
-->

**Comment by onewsch** [comment]
After further debug, I found out the issue is from :
"$ kubectl logs tide-78f99c5dc8-tzqz7
using JSON formatter!
{"component":"tide","file":"/go/src/github.com/jenkins-x/lighthouse/pkg/prow/config/config.go:781","func":"github.com/jenkins-x/lighthouse/pkg/prow/config.Path","level":"warning","msg":"defaulting to /etc/config/config.yaml until 15 July 2019, please migrate","time":"2019-10-03T05:24:32Z"}
{"component":"tide","fields.level":"info","file":"/go/src/github.com/jenkins-x/lighthouse/pkg/prow/config/config.go:994","func":"github.com/jenkins-x/lighthouse/pkg/prow/config.parseProwConfig","level":"info","msg":"setting the log level","time":"2019-10-03T05:24:33Z"}
using driver: bitbucketserver and serverURL: https://bitbucket.oci.oraclecorp.com
{"component":"tide","fields.level":"info","file":"/go/src/github.com/jenkins-x/lighthouse/pkg/prow/config/config.go:994","func":"github.com/jenkins-x/lighthouse/pkg/prow/config.parseProwConfig","level":"info","msg":"setting the log level","time":"2019-10-03T05:24:34Z"}
{"component":"tide","error":"unable to clone version dir: unable to clone version stream and checking out branch/tag: Cloning into '.'...\nfatal: unable to access 'https://github.com/jenkins-x/jenkins-x-versions.git/': Failed to connect to github.com port 443: Operation timed out: failed to run 'git clone --depth 1 --branch master https://github.com/jenkins-x/jenkins-x-versions.git .' command in directory '/tmp/jx-version-repo-534668805', output: 'Cloning into '.'...\nfatal: unable to access 'https://github.com/jenkins-x/jenkins-x-versions.git/': Failed to connect to github.com port 443: Operation timed out'","file":"/go/src/github.com/jenkins-x/lighthouse/cmd/tide/main.go:179","func":"main.main","level":"fatal","msg":"Error getting Kubernetes client.","time":"2019-10-03T05:26:42Z"}
CHESHI-MAC:prowConfig cheshi$ kubectl describe tide-78f99c5dc8-tzqz7
error: the server doesn't have a resource type "tide-78f99c5dc8-tzqz7""

Since we are working behind a corporate proxy, to run git clone for github project we have to set proxy environment variables for POD, however I did not see currently "jx boot" provides such option.
One workaround we tried is using https://kubernetes.io/docs/tasks/inject-data-application/podpreset/ setting environment variable of proxy for label app=tide beforehand, however sooner we found that our k8s cluster does not support alpha feature and there is no way to change it.
Appreciate any suggestions! Thanks

**Comment by onewsch** [comment]
After I choose to use a cluster in public network, I still fail at the same step but for a different reason
STEP: apply-pipeline-schedulers command: /bin/sh -c jx step scheduler config apply --direct=true in dir: prowConfig

error: generating Prow config: No source repository resources were found
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step scheduler config apply --direct=true' command in directory 'prowConfig', output: ''
CHESHI-MAC:jenkins-x-boot-config cheshi$ kubectl get pod
NAME                                           READY   STATUS              RESTARTS   AGE
crier-6f75989446-g6c46                         0/1     ContainerCreating   0          15m
deck-6d844b55cb-855r8                          0/1     ContainerCreating   0          15m
deck-6d844b55cb-vxvvk                          0/1     ContainerCreating   0          15m
hook-756489b884-sgv2g                          0/1     ContainerCreating   0          15m
hook-756489b884-tlk4s                          0/1     ContainerCreating   0          15m
horologium-698fff5495-smjjz                    0/1     ContainerCreating   0          15m
jenkins-x-chartmuseum-67f75c4884-v2cdz         1/1     Running             0          15m
jenkins-x-controllerbuild-9b856b84b-56s2q      1/1     Running             0          15m
jenkins-x-controllerrole-69dcbc4c46-5lq6l      1/1     Running             0          15m
jenkins-x-heapster-66754b8fc5-fcwj6            2/2     Running             0          2m28s
jenkins-x-nexus-57c8447c4-pqtg5                1/1     Running             0          15m
pipeline-5d47c95bcd-9zk9v                      0/1     ContainerCreating   0          15m
pipelinerunner-646c85c7fd-9r67j                1/1     Running             0          15m
plank-84b96f69fc-f5lnm                         0/1     ContainerCreating   0          15m
prow-build-d857bc9bb-rd996                     0/1     ContainerCreating   0          15m
tekton-pipelines-controller-65fff67458-sqkpg   1/1     Running             0          15m
tide-56458c768c-djn6m                          0/1     ContainerCreating   0          15m
CHESHI-MAC:jenkins-x-boot-config cheshi$ kubectl logs tide-56458c768c-djn6m
Error from server (BadRequest): container "tide" in pod "tide-56458c768c-djn6m" is waiting to start: ContainerCreating
CHESHI-MAC:jenkins-x-boot-config cheshi$ kubectl describe pod tide-56458c768c-djn6m
Name:           tide-56458c768c-djn6m
Namespace:      jx
Priority:       0
Node:           10.0.10.3/10.0.10.3
Start Time:     Thu, 03 Oct 2019 11:04:23 -0700
Labels:         app=tide
                pod-template-hash=56458c768c
Annotations:    ad.datadoghq.com/tide.logs: [{"source":"prow","service":"tide"}]
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/tide-56458c768c
Containers:
  tide:
    Container ID:
    Image:         gcr.io/jenkinsxio/prow/tide:v20191001-b0861a4
    Image ID:
    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      --dry-run=false
      --github-endpoint=https://api.github.com
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  256Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Liveness:     http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/config from config (ro)
      /etc/github from oauth (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from tide-token-nlvkk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  oauth:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  oauth-token
    Optional:    false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config
    Optional:  false
  tide-token-nlvkk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tide-token-nlvkk
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                  From                Message
  ----     ------       ----                 ----                -------
  Normal   Scheduled    16m                  default-scheduler   Successfully assigned jx/tide-56458c768c-djn6m to 10.0.10.3
  Warning  FailedMount  2m1s (x15 over 16m)  kubelet, 10.0.10.3  MountVolume.SetUp failed for volume "config" : configmaps "config" not found
  Warning  FailedMount  39s (x7 over 14m)    kubelet, 10.0.10.3  Unable to mount volumes for pod "tide-56458c768c-djn6m_jx(3b12c654-e608-11e9-bd3c-0a580aed7619)": timeout expired waiting for volumes to attach or mount for pod "jx"/"tide-56458c768c-djn6m". list of unmounted volumes=[config]. list of unattached volumes=[oauth config tide-token-nlvkk]

**Comment by deanesmith** [comment]
@onewsch looks like you're using Bitbucket?  As Lighthouse begins to support additional SCM's we can follow up.

**Comment by katemarshall96** [comment]
I am also experiencing this same issue! Despite selecting lighthouse as webhook of choice in jx-requirements, I fail at 
`error: generating Prow config: No source repository resources were found`
I am using a GHE repository.

**Comment by doc-olliday** [comment]
Hi,
I'm facing the same issue, using `jx boot` with **gitlab.com** as SCM provider and `lighthouse` as webhook configured in jx-requirments.yml.

**Comment by jstrachan** [comment]
I think this error appears if you have no `cluster.clusterName` setup in `jx-requirements.yml` and so it doesn't bother trying to create any environments; which leads to no `SourceRepository` resources which then leads to broken prow config
