### ISSUE TITLE
SSO addon has multiple problems

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5703]
### Summary 
Looks like the SSO addon is incompatible with jx boot environments as it expects cert-manager to have a different name and installs a second instance of cert-manager for itself. This in turn seems to break the issuing of certificates so TLS connections end up with the default dummy K8S cert. I guess that we need to test which install is being used so that both can be supported.

I suspect that this is also incompatible with externalDNS since proxy instances don't seem to acquire DNS entries when deployed.

Finally, the oauth2_proxy tags should be `v3.1.0` rather than `3.1.0` otherwise the proxies fail to deploy with an ImagePullErr.

### Jx version

The output of `jx version` is:

```
2.0.808
```

**Comment by hferentschik** [comment]
SSO addon is deprecated. The SSP app should be used instead.

**Comment by tdcox** [comment]
@hferentschik The SSO app currently has a number of issues that are more serious than the ones the addon is suffering from.
