### ISSUE TITLE
First Pull Request on the Dev Environment after booting with local secrets storage fails

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5705]
### Summary 
After booting with GKE using local secrets storage, the Dev Environment's first PR's pipeline, with the updated configuration, fails with the following line:
```
error: generating values.yaml for tree from .: failed to convert secret URLs in parameters file parameters.yaml: replacing vault paths in adminUser:
  password: local:dg-boot-jx-gke1/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dgozalo@cloudbees.com
  token: local:dg-boot-jx-gke1/pipelineUser:token
  username: dgozalo
prow:
  hmacToken: local:dg-boot-jx-gke1/prow:hmacToken
: reading dg-boot-jx-gke1/adminUser from vault: local vault file does not exist: /builder/home/.jx/localSecrets/dg-boot-jx-gke1/adminUser.yaml
```
### Steps to reproduce the behavior

- Create a GKE cluster.
- Boot without changing the `jx-requirements.yml` file.
- Wait until boot finishes, close and re open the first PullRequest with the updated config.
- Watch the logs

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hferentschik** [comment]
It is not supported to run gitops with local storage. This should be validated and prevented in the verify step.

**Comment by axsaucedo** [comment]
I can confirm this is still present in `2.0.916`. @hferentschik is there a way to fix this manually at this point?

**Comment by axsaucedo** [comment]
Ok it is actually enough to just change `secretStorage: vault` in `jx-requirements.yaml` and re-run `jx boot`. Thanks!
