### ISSUE TITLE
"jx create cluster minikube" install fails with helm deployment errors

### ISSUE THREAD

**Issue by jeffkight** [jenkins-x/jx#5707]
### Summary 
"jx create cluster minikube" install fails with helm deployment errors

### Steps to reproduce the behavior
```
jx create cluster minikube
```

### Expected behavior
Clean install

### Actual behavior
```
ERROR: error creating cluster installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'kubectl apply --recursive -f /var/folders/pg/93pxn1pd5xv0qh89xr5ljtg40000gn/T/helm-template-workdir-615088976/jenkins-x/output/namespaces/jx -l jenkins.io/chart-release=jenkins-x --namespace jx --validate=false' command in directory '', output: 'persistentvolumeclaim/jenkins-x-chartmuseum created
```
```
unable to recognize "/var/folders/pg/93pxn1pd5xv0qh89xr5ljtg40000gn/T/helm-template-workdir-615088976/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/pg/93pxn1pd5xv0qh89xr5ljtg40000gn/T/helm-template-workdir-615088976/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/pg/93pxn1pd5xv0qh89xr5ljtg40000gn/T/helm-template-workdir-615088976/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/pg/93pxn1pd5xv0qh89xr5ljtg40000gn/T/helm-template-workdir-615088976/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/pg/93pxn1pd5xv0qh89xr5ljtg40000gn/T/helm-template-workdir-615088976/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/nexus/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.818
jenkins x platform 2.0.1376
Kubernetes cluster v1.16.0
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

minikube
```
$ jx create cluster minikube
? memory (MB) 8000
? cpu (cores) 2
? disk-size (MB) 20GB
? Select driver: hyperkit
```
[jx-create-cluster-minikube-fail.txt](https://github.com/jenkins-x/jx/files/3688068/jx-create-cluster-minikube-fail.txt)

### Operating system / Environment

- Mac OS X 10.14.6
- GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
- Used `brew` to install minikube, kubernetes-cli, kubernetes-helm
- Docker Desktop for Mac v2.1.0.3, stable, which provides Hyperkit

**Comment by jeffkight** [comment]
`jx` was updated this AM...  same error though with:
```
NAME               VERSION
jx                 2.0.821
jenkins x platform 2.0.1383
Kubernetes cluster v1.16.0
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```

**Comment by jeffkight** [comment]
Hmmmm... this could be related... https://github.com/helm/helm/issues/6374

**Comment by jeffkight** [comment]
Connected to deprecated APIs? https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by hferentschik** [comment]
We are in the process of deprecating Minishift/Minikube support, so we recommend to switch to GKE.

**Comment by jeffkight** [comment]
Would this be an issue with any K8s 1.16 implementation?

**Comment by jeffkight** [comment]
I forced k8s to v1.15.4 via a Minikube config command ( `minikube config set kubernetes-version v1.15.4` ), prior to the `jx create cluster`.
This allows jx to install correctly.

I expect that jx creation files have to change their api methods to work correctly on k8s v1.16

Check:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by jeffkight** [comment]
Already in process with issue #5675

https://github.com/jenkins-x/jx/issues/5675

**Comment by reversefold** [comment]
You're deprecating minikube support? Doesn't that mean there's no easy way to have a development environment? GKE *is* a paid cloud service, isn't it?

**Comment by jstrachan** [comment]
all clouds have a free tier so folks can try Jenkins X in a realistic environment for free

**Comment by sharepointoscar** [comment]
Why can't everyone understand that there is a **free** tier in every cloud these days?  Some software just won't work on your local machine, this is not a flaw.

**Comment by clarkmcc** [comment]
@jstrachan The free tier on GKE for example only works for a certain period of time or until the 365 day trial is up. Most of us (except for starters) have used up the trial. So for me and I imagine most other people, in order to test this out, or have a dev environment, we'll have to pay.
