### ISSUE TITLE
Provide a CLI option to change the Pipeline GitHub user

### ISSUE THREAD

**Issue by romenrg** [jenkins-x/jx#5711]
### Summary 

As discussed yesterday (Oct 3rd, 2019) in the "Office Hours" call, it would be nice to have a command to change the GitHub pipeline user to a new one. For instance, I might have used a token from my personal account when creating the cluster with Jx and now might be willing to change the pipeline GitHub user to be a bot, which seems like a better practice for automated actions performed by Jx on GitHub (like creating PRs, commenting,...). Unfortunately at the moment there is no easy way to perform that change via the Jx CLI.

### Expected behavior

It would be great if we had a command / option in the `jx` CLI that allows to change the "pipelines GitHub user". Maybe something like `jx update git user pipeline`?

### Current behavior

Nowadays changing the GitHub user that Jx uses for the execution of pipelines is tricky and requires manual changes in multiple places, which are not documented nor clearly known.

### Jx version

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.821
jenkins x platform 2.0.1358
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.13.11-dispatcher
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

**Comment by romenrg** [comment]
CC'ing @daveconde and @rawlingsj:
Here is the issue you asked me to create yesterday in the call :)

**Comment by danishprakash** [comment]
I'd like to take this up? cc @romenrg

**Comment by romenrg** [comment]
Sure @danishprakash. That's OK with me. Keep us posted.

**Comment by hongfei-zhou** [comment]
@romenrg Could you give some hints one how I can change the user manually for now? Thanks

**Comment by romenrg** [comment]
@hongfei-zhou according to my own experiments, I was able to change the pipeline user by changing the value of `pipelineusername` in the `gitAuth.yaml` file within my jx installation dir (typically `~/.jx`).

You probably also need to add an entry in the "servers", "users" section of that same file, adding the `apitoken` of your new pipeline user (following the same structure as the existing one ou should have there).

**Comment by jstrachan** [comment]
we have a solution for this if using helm 3
https://jenkins-x.io/docs/labs/boot/

though note it’s currently alpha.

You can run `jxl boot secrets edit -a` to modify the secrets at any time then run boot
https://jenkins-x.io/docs/labs/boot/getting-started/run/

**Comment by mgoltzsche** [comment]
what would need to happen here:
* change ~/.jx config
* change bot secret in vault
* grant new pipeline bot access to all repos that have been imported into jx previously
