### ISSUE TITLE
Docker-Registry ( EKS )

### ISSUE THREAD

**Issue by Larzack** [jenkins-x/jx#5719]
### Summary 

When I try to build , I have this error : 

```
{"component":"pipelinerunner","level":"info","msg":"error triggering the pipeline run: failed to create effective project configuration: Missing option: --docker-registry could not start pipeline: error triggering the pipeline run: failed to create effective project configuration: Missing option: --docker-registry","time":"2019-10-05T1 │
│ 8:29:41Z"}
```

I added full access to my cluster on my ECR Registry

### Steps to reproduce the behavior

Create a EKS cluster, launch a pipeline.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.0.827
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.6 build 18G103

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

OS X 10.14.6

**Comment by jstrachan** [comment]
this should be fixed now. Boot should default in the `cluster.registry` value in `jx-requirements.yml`. If not you can always manually specify it and re-run `jx boot`
