### ISSUE TITLE
Local minikube + GitHub = unreachable webhook

### ISSUE THREAD

**Issue by NickitaX** [jenkins-x/jx#572]
I'm not sure whether it is an issue or not, but when you create a new project with `jx create` on minikube and choose to set up repository on GitHub, it publishes unreachable local webhook. The only way to connect GitHub to Jenkins is by exposing Jenkins IP via ngrok or localtunnel. Since exposed links are generated randomly by these services, it is required to manually update webhooks when exposed URLs changed. Just personal experience.

**Comment by jstrachan** [comment]
we may be able to add a polling plugin in jenkins to mimic webhooks when using minikube

**Comment by NickitaX** [comment]
Thanks, @jstrachan! As I mentioned, it is not really a bug/issue, but just an overview from personal experience running JenkinsX from local Minikube (I suppose majority of users would try to run it locally for test-drive before considering moving to production/stage). Appreciate your fast response 👍

**Comment by jstrachan** [comment]
@NickitaX thanks for the feedback! Hopefully we can keep improving the features & usability of Jenkins X

**Comment by jstrachan** [comment]
https://github.com/jenkins-x/jx/issues/650

**Comment by jstrachan** [comment]
this is now fixed along with #674 - release should be out in an hour
