### ISSUE TITLE
Modifying ingress url template on a multi cluster setup

### ISSUE THREAD

**Issue by seangal2** [jenkins-x/jx#5723]
### Summary 

Hi, I created a multi-cluster setup with 3 clusters:
 - dev which includes jx,
 - staging
 - prod

I want to change the domains of the applications in production to be `{{service-name}}.domain.com` instead of `{{service-name}}.jx-prod.domain.com`.
I tried running `jx upgrade ingress --cluster` but it fails with `error: getting the webhook endpoint: finding the service hook in namespace default: services "hook" not found`.

### Steps to reproduce the behavior

Explained above

### Expected behavior

`jx upgrade ingress --cluster` to work on a different production cluster.

### Actual behavior

It fails because it tries to do stuff relevant only to a dev cluster.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.827
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.13.11-dispatcher
helm client        Client: v2.14.1+g5270352
git                2.20.1
Operating System   Debian GNU/Linux 9.11 (stretch)


verifying packages
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Using a multi-cluster setup that was created using the terraform quickstart.

### Operating system / Environment

Google Cloud Shell

**Comment by zhaochunqi** [comment]
Facing the same error

**Comment by zhaochunqi** [comment]
I rerun the `jx create envctl` command solved this problem

**Comment by zhaochunqi** [comment]
You may need to specify `--skip-resource-creation`

**Comment by seangal2** [comment]
I don't see a flag `--skip-resource-creation`, and when I used `--skip-resources-update` it deleted all of the ingresses and didn't create new ones.

**Comment by zhaochunqi** [comment]
yeah, that's a known issue https://github.com/jenkins-x/jx/issues/5800

**Comment by jstrachan** [comment]
for multi cluster we recommend you use the new helm 3 based boot https://jenkins-x.io/docs/labs/boot/ which uses boot for `dev`, `staging` and `production` whether sharing a local cluster or using multiple cluster.

see https://jenkins-x.io/docs/labs/boot/multi-cluster/

for configuring ingress on a per environment or app basis see: https://jenkins-x.io/docs/labs/boot/faq/#how-do-i-configure-the-ingress-domain-in-dev-staging-or-production

**Comment by majuansari** [comment]
@jstrachan  Any tentative dates on merging multi-cluster support to the stable branch?
