### ISSUE TITLE
users.jenkins.io "<user>" already exists

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5727]
### Summary 

Creating a preview can fail with:

```
users.jenkins.io "foo" already exists
```

This happens when there is already a User CRD with the name `foo` and `GitUserResolver.Resolve` fails tries to create a new User CRD with the same name.

**Comment by hferentschik** [comment]
The problem is that GitHub user names are case sensitive, but our CRD is  lowercased, hence this code to generate a unique id does not work:

```go
		new := r.GitUserToUser(gitUser)
		id = gitUser.Login
		// Check if the user id is available, if not append "-<n>" where <n> is some integer
		for i := 0; true; i++ {
			_, err := r.JXClient.JenkinsV1().Users(r.Namespace).Get(id, v1.GetOptions{})
			if k8serrors.IsNotFound(err) {
				break
			}
			id = fmt.Sprintf("%s-%d", gitUser.Login, i)
		}
		new.Name = naming.ToValidName(id)
		return id, possibles, new, nil
```

**Comment by hferentschik** [comment]
It might be as easy as moving `naming.ToValidName(id)` higher up.

**Comment by khansaAmrouni** [comment]
Hi! I am an outreachy applicant, can i take this issue to be my first contribution and work on ?

**Comment by khansaAmrouni** [comment]
or can we use strings.ToLower() and render github username lower case !!

**Comment by mrageh** [comment]
@khansaAmrouni are you still working on this issue? If not I'd be happy to jump on it

**Comment by khansaAmrouni** [comment]
@mrageh Yes ! Go a head 
good luck 👍
