### ISSUE TITLE
add a `service linking` chart for reuse in Preview Environments

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#573]
when working on large collections of microservices, it can be painful deploying a massive system in each Preview Environment - so it'd be nice to use _service linking_ to link the preview build of one microservice to a bunch of other services in `Staging` or `Production`

So it'd be nice to have a helm chart we can use as a hook in the Preview chart to do service linking; so that Kubernetes Services are created in the Preview namespace that links to the same services running in some persistent namespace like `Staging` or `Production`.

We could add extra configuration properties for patterns of services to include/exclude.

A similar thing for istio service mesh might be nice so that services inside `Staging` or `Production` could invoke back into a Preview environment for a particular kind of traffic / user / feature flag

**Comment by jstrachan** [comment]
one way to start to implement this would be to create a new step command to service link things between namespaces. 
e.g. something like
```
jx step link services --from-namespace jx-staging 
```
which would link all the services in the `jx-staging` namespace to the current namespace. We could let folks add includes/excludes filters on the service names and provide an explicit `--to-namespace` argument (which can default to the current namespace). e.g.

```
jx step link services --from-namespace foo --to-namespace bar --includes * --excludes cheese*
```


We have a helper function to filter names using includes/excludes and wildcard `*` values btw `util. StringMatchesAny(text, includes, excludes)` there's the tests here: https://github.com/jenkins-x/jx/blob/master/pkg/util/strings_pattern_test.go#L17

Then in terms of implementation, its a case of using kubeClient to list all `Service` objects in the target namespace...
```
serviceList, err := kubeClient.CoreV1().Services(fromNs).List(metav1.ListOptions{})
...
for _, svc := range serviceList.Items { 
   if util.StringMatchesAny(svc.Name, o.Includes, o.Excludes)  {
     // TODO create a Service resource if one does not exist with `svc.Name` in namespace toNs with an external name pointing to this service 
   }
}
```

**Comment by jstrachan** [comment]
BTW if you wanna try create a unit test for this, here's a sample of something similar - we setup a fake k8s cluster:
https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/step_envrolebinding_test.go#L60

with some starting resources then do stuff and assert that the resource we expect to be there are there

**Comment by angoothachap** [comment]
@jstrachan Would you assign this issue to me please?

**Comment by angoothachap** [comment]
Related PRs: #1227 #1268 #1365 #1433 merged

**Comment by msvticket** [comment]
To use a service you typically need a secret with the credentials as well. You aught to be able to acheive that with something like:
`kubectl get secret messaging --namespace=jx_staging --export -o yaml | kubectl apply --namespace=$PREVIEW_NAMESPACE  -f -`
But maybe another step similiar to `jx step link services` is needed: `jx step copy secrets`
