### ISSUE TITLE
sso-operator configured incorrectly when deployed with 'add app'

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5738]
### Summary 
The sso-operator doesn’t seem to work when installed using `jx add app jx-app-sso` rather than `jx create addon sso`. 

Originally, deployment was to a new namespace `sso` but in the new form, sso-operator and dex are installed by default in the `jx` namespace.

In the chart values.yaml, sso-operator has a hard-coded grpcHost address of `dex.sso`. As a result, all attempts to create proxy instances fail with:

```
error syncing key (jx-staging/sso-test299): creating the OIDC client 'sso-test299' in dex: failed to create the OIDC client: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup dex.sso on 10.23.240.10:53: no such host\"
```

@ccojocar

**Comment by ccojocar** [comment]
Maybe for a quick fix try:

```
jx add app jx-app-sso -n sso
```

The value can be override on https://github.com/jenkins-x-apps/jx-app-sso/blob/master/jx-app-sso/values.yaml:
```yaml
sso-operator:
  dex:
    grpcHost: dex.<dex-namespace>
```

 It doesn't seem to be parameterised in the app https://github.com/jenkins-x-apps/jx-app-sso/blob/master/jx-app-sso/values.schema.json.

**Comment by tdcox** [comment]
```
> jx add app jx-app-sso -n sso
error: Invalid option: --namespace sso
unable to specify --namespace when using GitOps for your dev environment
```

**Comment by tdcox** [comment]
The values.yaml workaround enables sso-operator to create a proxy container.
