### ISSUE TITLE
OAuth redirection fails due to broken vault substitution

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5739]
### Summary 
When using jx-app-sso to provide proxy authentication via Dex and GitHub, the redirect to GitHub to sign in fails due to a broken URL:

```
https://github.com/login/oauth/authorize?client_id=vault%3AgitOps%2FBootstrap-Jersey%2Fenvironment-d69-dev%2Fdex-connectors-github-config%3AclientID&response_type=code&scope=user%3Aemail+read%3Aorg&state=vykfo5qc6kq3or4hwi5wrgt6m
```

This appears to be passing the Vault URL for the clientID instead of substituting the actual clientID secret from Vault...

### Jx version

The output of `jx version` is:

```
jx                 2.0.821
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by ccojocar** [comment]
Is it the value which you are proving stored in vault?

**Comment by tdcox** [comment]
@ccojocar `jx add app jx-app-sso` takes the Client ID and Client Secret values from the CLI survey and stores them in Vault then puts the link in the values.yaml for the jx-app-sso chart in the environment.

**Comment by daveconde** [comment]
@tdcox When you look in the jenkins-x-dex secret do the clientId and clientSecret properties contain the vault URL or the values from vault?

**Comment by tdcox** [comment]
The vault url.

**Comment by daveconde** [comment]
Can you please try adding the sso app again with a new binary version?

**Comment by daveconde** [comment]
@tdcox Can you please try adding the sso app again with a new binary version?

**Comment by deanesmith** [comment]
Hi @tdcox Do you have any update on this one?

**Comment by ccojocar** [comment]
@tdcox I am closing this. Feel free to reopen it if it is still an issue. Thanks!
