### ISSUE TITLE
jx install v1.1.48 creates 2 differents Ingresses: jxing and jenkins-x but only jxing is usable

### ISSUE THREAD

**Issue by vgallissot** [jenkins-x/jx#574]
After several cluster installs, `jx install` on GKE now says `existing ingress controller found, no need to install a new one` but no ingress controler exists (fresh cluster + rm -Rf ~/.jx/)

Then, pods get created by `jx install` with a new public IP, but not the one jx is aware of:

`You can now configure your wildcard DNS foo.bar to point to 123.123.123.123`

But this is not the correct IP:
```
$ kubectl get ing   
NAME              HOSTS                            ADDRESS          PORTS     AGE
chartmuseum       chartmuseum.jx.foo.bar       231.231.231.231   80        2m
docker-registry   docker-registry.jx.foo.bar   231.231.231.231   80        2m
jenkins           jenkins.jx.foo.bar           231.231.231.231   80        2m
monocular         monocular.jx.foo.bar         231.231.231.231   80        2m
nexus             nexus.jx.foo.bar             231.231.231.231   80        2m
```

**Comment by vgallissot** [comment]
My Bad, this wasn't a fresh cluster install.

This is the ingress created by first install.
It is not removed via: `helm del --purge jenkins-x`
One should use the following command to remove it:
```
$ kubectl delete -n kube-system HorizontalPodAutoscaler,Service,Deployment,ReplicaSet,Ingress -l 'release=jxing'
service "jxing-nginx-ingress-controller" deleted
service "jxing-nginx-ingress-default-backend" deleted
deployment "jxing-nginx-ingress-controller" deleted
deployment "jxing-nginx-ingress-default-backend" deleted
```

But still, if an existing ingress is used, the `jx install --provider=gke` will create a new ingress with ephemeral IP different from the one kube-system is using.

**Comment by ccojocar** [comment]
This seems to be an outdated issue.
