### ISSUE TITLE
jx-app-sso using insecure version of OAuth2_Proxy

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5743]
### Summary 
Current public release of OAuth2_Proxy is at v4.0.0 and includes fixes for several security issues including root privileges in docker. jx-app-sso is still on v3.1.0.

**Comment by ccojocar** [comment]
@tdcox Have you tried to use oauth_proxy v.4.0.0 in the SSO CRD. You can update the image tag in this field https://github.com/jenkins-x/sso-operator/blob/afd07cdca39c5eac8150f6874b62c0d69c52c649/examples/sso.yaml#L20?
