### ISSUE TITLE
Move the jx-requirements.yaml contents from the jx-requirements-config ConfigMap to the Dev Environment's TeamSettings

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5746]
### Summary 
Right now, we are saving the current state of the `jx-requirements.yaml` file into the `jx-requirements-config` `ConfigMap` when executing the `veify-preinstall` step.

https://github.com/jenkins-x/jx/blob/0a7aa85d79a5c66e032ad3a0abc00928ee2dbfeb/pkg/cmd/step/verify/step_verify_preinstall.go#L242-L245

and

https://github.com/jenkins-x/jx/blob/0a7aa85d79a5c66e032ad3a0abc00928ee2dbfeb/pkg/cmd/step/verify/step_verify_preinstall.go#L440-L455

We need to move this to the Dev `Environment` `TeamSettings`, marshaled into a string so we don't have to modify the fields in the CRD evey time we modify the `jx-requirements.yaml` file.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
Reopening since that turned out not to work. Working on it further in #5760
