### ISSUE TITLE
Ask for Cloud provider during 'jx boot'

### ISSUE THREAD

**Issue by Larzack** [jenkins-x/jx#5754]
### Summary 

Actually when we install `Jx boot`, the default provider is GKE and we have to install with GKE, then it fails and we change `cluster.provider: gke` to `cluster.provider: **MyProvider**` and restart the boot.

There is nothing in the CLI to specify the Cloud Provider.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.0.842
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.6 build 18G103

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment

OS X 10.14.6

**Comment by jstrachan** [comment]
I think this is just a matter of removing this value: https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/jx-requirements.yml#L5

**Comment by Larzack** [comment]
If a remove the value, I have this error : 

"Error : missing propety: provider in file jx-requirements.yml "

**Comment by Larzack** [comment]
Up

**Comment by jstrachan** [comment]
we have a solution now for this issue usung helm 3
https://jenkins-x.io/docs/labs/boot/

though note it’s currently alpha
