### ISSUE TITLE
`jx import` not creating webhooks on GitLab for projects that have been renamed

### ISSUE THREAD

**Issue by kdevu** [jenkins-x/jx#5757]
### Summary 
I ran into a problem using Jenkins X with Gitlab. **The problem being a webhook not being created when I run `jx import` on a project that I have renamed (using the gitlab web GUI)**. Resulting in pipelines not being created whenever I push my changes to the `master` branch.

To clarify a webhook is successfully created when I run `jx import` on a project that hasn't been renamed. But when I run `jx import` on a project that has been renamed, no webhook is created. 

I've solved this issue by simply renaming the project back to its original name. But I'm wondering if this is a bug (webhooks not being created for projects that have been renamed on gitlab)? 

Given that the webhooks are created by LightHouse (`hook-jx.CUSTOM_DOMAIN`), I'm thinking it may be an issue with LightHouse.

### Steps to reproduce the behavior

1. Create a project on gitlab 
2. `Git clone` the project
3. Go to the new projects Settings page 
4. Change the project's name
5. Run `jx import`
6. Check the project's integration page to see if the webhook was created `https://gitlab/group/project-repo/settings/integrations` 
7. See no webhook has been created

### Expected behavior

In step 7, I expect to see that a webhook has been created.

### Actual behavior

In step 7, I see that no webhook has been created.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.837
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.0
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

I'm using a GKE cluster. I created it manually using the GCP web GUI.

**Comment by daveconde** [comment]
Does this work as expected if you re clone the repository after renaming and then reimport?

**Comment by KDvu** [comment]
No, I get the same result.

If it's helpful

Before renaming
```
$ git clone https://GITLAB_DOMAIN/group/project.git
```

After renaming
```
$ git clone https://GITLAB_DOMAIN/group/project.git
```

So the URL used as the arg for `git clone` remains unchanged, despite the fact I renamed the project.
