### ISSUE TITLE
auto-merge not working for 'jx add app'

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#5761]
### Summary 

When executing `jx add app` with the `--auto-merge` argument, the PR created by the process is not merged automatically.

### Steps to reproduce the behavior

Install Jenkins X with `jx boot`.

```bash
jx add app gloo \
    --repository https://storage.googleapis.com/solo-public-helm \
    --auto-merge
```

The output:

```
Read credentials for https://storage.googleapis.com/solo-public-helm from vault helm/repos
Adding missing Helm repo: storage.googleapis.com-0 https://storage.googleapis.com/solo-public-helm
Read credentials for https://storage.googleapis.com/solo-public-helm from vault helm/repos
Successfully added Helm repository storage.googleapis.com-0.
Created Pull Request: https://github.com/vfarcic/environment-jx-boot-dev/pull/23
Added label updatebot to Pull Request https://github.com/vfarcic/environment-jx-boot-dev/pull/23
Added app via Pull Request https://github.com/vfarcic/environment-jx-boot-dev/pull/23
```

### Expected behavior

The PR is merged automatically.

### Actual behavior

The PR is NOT merged automatically, even though the `updateboot` label was added to it.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.842
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.15.3
helm client        Client: v2.14.1+g5270352
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by garethjevans** [comment]
It looks like the default env-scheduler does not have the configuration to allow updatebot to merge this repo - https://github.com/jenkins-x-charts/jxboot-resources/blob/master/jxboot-resources/templates/env-scheduler.yaml
