### ISSUE TITLE
externalDNS not working

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#5763]
### Summary 

After enabling `externalDNS`, `jx boot` fails.

### Steps to reproduce the behavior

1. Purchase a domain through Google (GCP).
2. Change `jx-requirements` to something similar to:

```yaml
ingress:
  domain: play-with-jx-gke.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: "viktor@farcic.com"
    enabled: true
    production: true
```

3. Push the changes to the dev repository.
4. Output the logs of the dev activity (`jx get build logs`).

The last lines of the logs is as follows.

```
...
Showing logs for build vfarcic/environment-jx-boot-dev/master #19 promotion stage release and container step-create-install-values
using a custom domain and GKE so enabling external dns, you can also now enable TLS
validating the external-dns secret in namespace jx
attempting to lazily create the external-dns secret jx
Unable to find service account jx-boot-dn, checking if we have enough permission to create
error: creating the ExternalDNS GCP Service Account: creating the ExternalDNS GCP Service Account: creating the service account: failed to run 'gcloud iam list-testable-permissions //cloudresourcemanager.googleapis.com/projects/devops-26 --filter resourcemanager.projects.setIamPolicy' command in directory '', output: 'ERROR: (gcloud.iam.list-testable-permissions) PERMISSION_DENIED: Request had insufficient authentication scopes.'

Pipeline failed on stage 'release' : container 'step-create-install-values'. The execution of the pipeline has stopped.
```

### Expected behavior

The domain is registered correctly.

### Actual behavior

The process fails.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.842
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.15.3
helm client        Client: v2.14.1+g5270352
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by daveconde** [comment]
Can you please check the permissions of the account you are using to run `jx boot` with? `PERMISSION_DENIED: Request had insufficient authentication scopes.` Seems to suggest your account does not have enough permissions

**Comment by vfarcic** [comment]
It's a personal account with admin permissions. However, I might be missing something I'm not aware of. Here's the command.



```bash
gcloud iam list-testable-permissions //cloudresourcemanager.googleapis.com/projects/devops-26 --filter resourcemanager.projects.setIamPolicy
```

The output:

```
---
name: resourcemanager.projects.setIamPolicy
stage: GA
```

That was from my laptop so I guess that the cluster doesn't have the permissions. The user that created it (me) does have them. Is there anything else I can run to help debug the issue?

**Comment by martijnburger** [comment]
Same problem here.

**Comment by anthony-pastor** [comment]
Same issue.

**Comment by deanesmith** [comment]
This issue is outdated.  With the recent adoption of Terraform, this appears to be remedied - https://jenkins-x.io/docs/getting-started/setup/create-cluster/gke/

**Comment by hrvolapeter** [comment]
@deanesmith I'm having this same problem for GKE + Terraform on JX3 but the final part is `ERROR: gcloud crashed (MetadataServerException): HTTP Error 400: Bad Request`
