### ISSUE TITLE
helm --tls option is not supported

### ISSUE THREAD

**Issue by teruz** [jenkins-x/jx#577]
Hi, I've found that when jx install into existing Kubernetes cluster, though some Kubernetes implementation such as IBM Cloud Private forces helm install with --tls option, jx install cannot pass --tls option to helm install command.

```
$ jx install --provider=kubernetes
...
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "jenkins-x" chart repository
Update Complete. ? Happy Helming!?
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.507 --values=/home/teru/.jx/gitSecrets.yaml --values=/home/teru/.jx/adminSecrets.yaml --values=/home/teru/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: transport is closing
```

I'd like to set --tls option with helm command, but there is no resort to tell jx command to set any helm options.

**Comment by teruz** [comment]
aa

aaaaaaaaaaaaa

Some Kubernetes forces --tls option.
ex)

$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Error: cannot connect to Tiller

$ helm version --tls
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2+icp", GitCommit:"d41a5c2da480efc555ddca57d3972bcad3351801", GitTreeState:"dirty"}

**Comment by teruz** [comment]
@jstrachan thank you for your quick response. I've looked your commit.
it seems that --helm-tls option is actually added to jx install command, but maybe there is no logic appending --tls flag to "helm install", while added in "helm version" code. we also need --tls with "helm install".

**Comment by teruz** [comment]
@jstrachan yeah, I've also be looking for some workaround with env or config file.. but i cannot find it out.

**Comment by jstrachan** [comment]
@teruz I spotted `TILLER_TLS_ENABLE` environment variable in the source, I wonder if that helps enable TLS on the helm CLI?

**Comment by teruz** [comment]
@jstrachan thank you for your suggestion. I've checked helm source and unfortunately I've found TILLER_TLS_ENABLE env var is defined but not used in helm source...

defined but not used:

![image](https://user-images.githubusercontent.com/31103008/38407682-699140c8-39b5-11e8-8d8f-5c64fbba1ab9.png)

**Comment by jstrachan** [comment]
I've raised this to see if anyone in the helm community has any better ideas https://github.com/kubernetes/helm/issues/3841

**Comment by teruz** [comment]
@jstrachan thanks a lot. it seems some pull requests are raised and not merged on helm repo.
I'll wait patiently it to be merged :-)

**Comment by khell** [comment]
This is still an issue. Running `jx install --helm-tls` I thought would work, but it fails on installing Jenkins X chart because it does not pass `--tls` flag to `helm upgrade`. Fortunately `TILLER_TLS_ENABLE` environment variable does work... as does `--no-tiller`.

**Comment by jstrachan** [comment]
here is a workaround for now (just avoid tiller completely which is way more secure and avoids side-stepping k8s RBAC completely): https://jenkins-x.io/news/helm-without-tiller/

**Comment by jstrachan** [comment]
I'd actually say avoiding tiller completely is a much better solution than enabling TLS on it https://jenkins-x.io/news/helm-without-tiller/ - as tiller basically disables fine grained RBAC - anyone who can access the tiller endpoint has effectively cluster-admin
