### ISSUE TITLE
Cannot add two apps based on the same repository

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#5782]
### Summary 

When trying to add two apps based on the same repository, `helm dependency build` error occurs.

### Steps to reproduce the behavior

```bash
jx add app istio-init \
    --repository https://storage.googleapis.com/istio-release/releases/1.3.2/charts/

jx add app istio \
    --repository https://storage.googleapis.com/istio-release/releases/1.3.2/charts/
```

### Expected behavior

Both apps were added

### Actual behavior

Only the first app was added. The second command throws the following error.

```
error: building dependencies for istio: failed to run 'helm dependency build' command in directory '/var/folders/73/94ypm_917397bvg1y3f7phkc0000gn/T/jx-helm-fetch279217584', output: 'Error: chart metadata (Chart.yaml)missing'
```

I tried it both in static and serverless (tekton) Jenkins X both with and without Boot. It's always the same result.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.845
jenkins x platform 2.0.1429
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

GKE, EKS, AKS

### Operating system / Environment

macOS

**Comment by hferentschik** [comment]
@daveconde, @vfarcic - we are talking about plain Helm charts for Istio here, right? Is that really supported? My understanding was that the `app` commands circle around Jenkins X extensions which contain their own metadata as well. 

Is that a valid usecase of `jx add app`?

**Comment by vfarcic** [comment]
In my case, adding any app as a Helm chart works fine and is a very useful feature. The only problem that I could find is that it gets confused if more than one app is based on the same charts repo.
