### ISSUE TITLE
 jx step boot upgrade not available from CLI

### ISSUE THREAD

**Issue by etavela** [jenkins-x/jx#5785]
### Summary 

` jx step boot upgrade` doesn't seem to be supported from the CLI though the current docs state that this is the method to perform manual platform upgrades for `jx boot` based installations.

### Steps to reproduce the behavior

Invoke `jx step boot upgrade` via the command line within the environment project directory created via `jx boot`.

### Expected behavior

Platform is upgraded.

### Actual behavior

Receive usage message indicating that only `jx step boot vault` is supported:

```
environment-alevat-dev git:(master)  jx step boot upgrade
boot [command]

Available Commands:
  step boot vault This step boots up Vault in the current cluster if its enabled in the 'jx-requirements.yml' file and is not already installed

Usage:
  jx step boot [flags] [options]
  ...
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.856
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.14.6
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G87


verifying packages
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

GKE Kubernetes cluster created with command:
```
gcloud container clusters \
      create alevat \
      --project $GCP_PROJECT \
      --region us-east4 \
      --machine-type n1-standard-2 \
      --enable-autoscaling \
      --num-nodes 1 \
      --max-nodes 2 \
      --min-nodes 1 \
      --scopes=gke-default,https://www.googleapis.com/auth/cloud-platform.read-only
      --preemptible
```

### Operating system / Environment

macOS Mojave (v 10.14.6)

**Comment by etavela** [comment]
In case it's helpful, top of `jx-requirements.yml` reads:

```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config
```

**Comment by daveconde** [comment]
The upgrade process has been changed, we need to remove the docs for that command. https://jenkins-x.io/docs/managing-jx/faq/boot/ should help

**Comment by ccojocar** [comment]
You can use now the `jx upgrade boot` command to upgrade your boot config. There is some bit of documentation here https://jenkins-x.io/docs/managing-jx/faq/boot/#how-do-i-upgrade-boot. 

I am closing this for now. Thanks for reporting it.
