### ISSUE TITLE
jx create mlquickstart broken by changes to quickstart behaviour

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5821]
### Summary 
Running `jx create mlquickstart` fails with the message:
```
error: No quickstarts match filter
```
after a machine-learning quickstart has been selected.

It appears that changes to the `quickstarts` model now prevent any third party quickstarts from being loaded from anywhere other than in the quickstarts version stream.

If you add a new quickstart location, no quickstarts from that location are shown in the survey.

If you attempt to use `jx create quickstart --machine-learning=true`, the machine-learning quickstarts are not listed in the survey as they should be.

### Jx version

The output of `jx version` is:

```
jx   2.0.866
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by jstrachan** [comment]
whats the output of `kubectl get env dev -oyaml`

**Comment by abayer** [comment]
Guessing this may be due to #5304? @tdcox, is this something that just showed up recently? If so, it may not be due to #5304, since that's over a month old...

**Comment by tdcox** [comment]
I'm not sure when this started. We only upgraded this cluster a couple of weeks back and it's possible that we haven't created a new ML project since then.

**Comment by tdcox** [comment]
More data:

I have just created a fresh test cluster using `jx boot` and `jx create mlquickstart` does work correctly on that cluster, so this must be related to a problem with upgrading legacy Tekton-based instances in some way. I will try upgrading the cluster to the latest platform version and see what happens.

**Comment by tdcox** [comment]
Note that `jx create quickstart --machine-learning=true` is also working on the `jx boot` cluster.

**Comment by tdcox** [comment]
I have just updated the client, platform and prow to the latest release (jx 2.0.871) and I am still seeing the same error.

**Comment by tdcox** [comment]
I'm noticing a mismatch between the CRD and the Dev Environment config. The CRD has gitPublic: but no gitPrivate: and the actual environment still has gitPrivate: true and no gitPublic value.

**Comment by tdcox** [comment]
Ok, I tried comparing the Dev environment config from my legacy cluster and the new 'boot' cluster and discovered that the old cluster file I had saved from yesterday stores filters in the form `[ML-*]` in Team Settings whereas the new cluster stores them as `ML-*`. These are auto-generated when you run `jx create mlquickstart` so should record whatever the system set.

This is where it gets weird.

I went to edit the config on the legacy cluster and found that there were no quickstart locations set, other than the default one. OK, so I upgraded the cluster yesterday afternoon and I guess they aren't carried over. However, I tested the upgrade last night by running `jx create mlquickstart` and this should have recreated the entry for 'machine-learning-quickstarts'.

So, I ran `jx create mlquickstart` again and this morning the quickstarts are working properly on this cluster!

Here is the console log which shows the test last night failing and the test this morning passing:
```
➜ jx create mlquickstart
Adding the default ml quickstart repo https://github.com/machine-learning-quickstarts
Using Git provider GitHub at https://github.com
? Git user name? terrycoda
? Who should be the owner of the repository? project-coda
? Enter the new repository name:  test17
Creating repository project-coda/test17
? select the quickstart you wish to create machine-learning-quickstarts/ML-python-pytorch-cpu
error: No quickstarts match filter

➜ jx create mlquickstart
Adding the default ml quickstart repo https://github.com/machine-learning-quickstarts
Using Git provider GitHub at https://github.com
? Git user name? terrycoda
? Who should be the owner of the repository? project-coda
? Enter the new repository name:  test17
Creating repository project-coda/test17
? select the quickstart you wish to create machine-learning-quickstarts/ML-python-pytorch-cpu
Generated quickstart at /Users/tcox002/Documents/code/codify/smoketest/test17-service
### NO charts folder /Users/tcox002/Documents/code/codify/smoketest/test17-service/charts/ML-python-pytorch-cpu-service
Created project at /Users/tcox002/Documents/code/codify/smoketest/test17-service

Git repository created
trying to use draft pack: ml-python-service
```
Note that the first one (last night) shows the statement `Adding the default ml quickstart repo https://github.com/machine-learning-quickstarts`, which it only does if it can't find the entry in the Team Settings, but there was no equivalent entry set in the config this morning. After this morning's run, there IS an entry for 'machine-learning-quickstarts' in the team settings and it is now in the new `ML-*` format.

**Comment by tdcox** [comment]
I'm going to close this one as it appears to be an artefact of the general problem of keeping cluster state valid when upgrading platform instances rather than a general bug.

**Comment by galaxyNeha** [comment]
Hey! I am facing issues with mlquickstart filters.
`Username for 'https://github.com': galaxyNeha 
Password for 'https://galaxyNeha@github.com': 
Where would you like to put this project?
The name you enter will be used as the prefix when creating your ML repos. For example: mymlproject-service and mymlproject-training.
? git owner: galaxyNeha
? git repository name: test1
Creating repository galaxyNeha/test1
? select the quickstart you wish to create: machine-learning-quickstarts/ML-python-tensorflow-mnist-cpu
error: No quickstarts match filter`
