### ISSUE TITLE
Installation documentation is not providing enough information 

### ISSUE THREAD

**Issue by wawelover** [jenkins-x/jx#5865]
The official installation documentation is not helpful, please elaborate on the installation steps, not a sentence

**Comment by wawelover** [comment]
What we want to see is instructive documentation, which is not helpful for installation and deployment

**Comment by hferentschik** [comment]
Which documentation are you referring to? Have you looked at https://jenkins-x.io/docs/getting-started/setup/?

**Comment by hferentschik** [comment]
It would help to know which documentation you are referring to and what's not working.
