### ISSUE TITLE
'step boot vault' should update the vault CRD when there are changes

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5867]
### Summary 

The vault CRD is programatically created by `step boot vault` but when a vault exists the command just skips and exists. It that case, it should check if there are any changes to the vault CRD (e.g. the docker image version update or some default settings enabled) and update the CRD.  

There is currently an issue during the boot update process when the vault version gets updated. This new version doesn't get propagated into the vault CRD.

### Expected behavior

The vault CRD should be updated when there are any changes.

**Comment by hferentschik** [comment]
So what's the game plan on this one? If a Vault deploy exist we should retrieve its CRD and diff it against the newly created one and if there are any differences we write the latest version? Or does one not even have to do a diff and just update with the generated CRD regardless?

Is there anything which needs to be done on top of that?

**Comment by ccojocar** [comment]
I think updating a CRD with the same values shouldn't trigger any change in the operator but we would need to check this. 

It would be nice to not trigger any update if there aren't any changes to avoid disruptions.
