### ISSUE TITLE
Move the BDD test for vault with TLS from jenkins-x-boot to jenkins-x-versions

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5868]
### Summary 
 
We should move the BDD tests for vault with TLS from jenkins-x-boot to jenkins-x-versions to catch any possible issues when the jx gets updated. 

https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/jenkins-x-bdd-vault.yml
https://github.com/jenkins-x/jenkins-x-boot-config/tree/master/bdd/boot-vault

It will probably require more domains to be registered to avoid cert-manager rate limits. At the moment, there are 12 domains which are rotated every hour. Maybe 24 domains rotated every 30 minutes might be a good start.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
How do we get more domains?

**Comment by ccojocar** [comment]
We need to extend the list of domains in this script for boot13-boot24 https://github.com/jenkins-x/jenkins-x-boot-config/blob/3cf675366e77efe3964c5d93c93498414ca4e4a5/bdd/upsert_bdd_domains.sh#L5 and then run it against the bdd3 project.

Also the the domain delegation needs to be configured for new domains boot13-boot25, here https://console.cloud.google.com/net-services/dns/zones/jenkins-x-rocks?project=jenkins-x-rocks&folder&organizationId.
