### ISSUE TITLE
jx ng (tekton) should allow mounting of docker.sock 

### ISSUE THREAD

**Issue by msavy** [jenkins-x/jx#5871]
### Summary 

I am using the tekton-based jx (jx boot, gitops). My particular application build needs docker-compose to launch 3 containers, and then runs tests against them, then terminates. 

I defined a custom builder that extends `gcr.io/jenkinsxio/builder-nodejs10x` simply to add docker-compose.

https://github.com/msavy/jx-builder-nodejs10-compose/blob/master/Dockerfile

With classic jx, the docker sock would be mounted to the builder container, and you could apply various customisations through ~/.jx/myvalues.yaml. This allowed you to do "docker out of docker" (DooD!)

I also tried making my own buildpack, but this doesn't seem to allow have any config that would you to specify mounts or any specific config to mount/expose docker sock?

You can theoretically do docker-in-docker (DinD), but this requires privileged=true which does not appear to be set, either.

As an example of the script I would want to run 

```
 $ npm test-ci (called by buildpack or similar)

   #!/bin/bash
   docker-compose build
   docker-compose up & # background
   # Code that waits for compose setup to finish starting
   ./wait-until-ready.sh
   # Run tests
   npm test
```

### Expected behavior

It should somehow be possible to launch docker images using docker-compose with the tekton/ng jx pipeline.

It would be fantastic to have some clearly documented way to solve this issue.

### Actual behavior

This appears not to be possible as sock is not mounted.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.866
Kubernetes cluster v1.12.9-gke.15
kubectl            v1.16.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

jx boot on GKE

### Operating system / Environment

Ubuntu Linux 18.04

**Comment by msavy** [comment]
Useful references: 
- https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker/33003273#33003273
- https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#the-solution

**Comment by ccojocar** [comment]
Jenkins X uses kaniko (https://github.com/GoogleContainerTools/kaniko) to build docker images in daemon-less mode which doesn't require to mount the docker socket, also it support multi-stage Dockerfiles. Mounting the docker socket is a well-known security issue - see https://stackoverflow.com/questions/40844197/what-is-the-docker-security-risk-of-var-run-docker-sock.

I am wondering why aren't you using a Kubernetes deployment for your 3 containers instead of using a compose file. You can deploy them in a preview environment out of the box and run any tests agains them.

**Comment by ccojocar** [comment]
@msavy Are you fine if we close this issue? This feature is not quite in our scope for now. As I mentioned above that the main reason for using kaniko was to be able to do rootless builds. Thanks again for reporting it.
