### ISSUE TITLE
jx upgrade platform disrupts tls config

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5873]
### Summary 
Following on from upgrading a cluster with `jx upgrade platform` I noticed that deployments were no longer being configured with TLS enabled as expected. Checking the exposecontroller ConfigMap in the jx environment showed TLS set to false.

I then executed `jx upgrade ingress --cluster` again and discovered that the exposecontroller ConfigMap had been removed and replaced with a new map called ingress-config.

So, it appears that `upgrade` is not managing significant parts of the upgrade process where config has been changed between releases.

### Jx version

The output of `jx version` is:

```
2.0.871
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by tdcox** [comment]
Everything else seems to follow the pattern `config-<subject>` so this is inconsistent as well as new. :)

**Comment by daveconde** [comment]
Was this cluster created using boot or jx install?

**Comment by tdcox** [comment]
@daveconde jx install
