### ISSUE TITLE
Creation of gitops cluster fails

### ISSUE THREAD

**Issue by unalterable** [jenkins-x/jx#5889]
### Steps to reproduce the behaviour

`jx create cluster gke --gitops`
(i'm selected a static jenkins server and otherwise default options)

### Expected behavior

- I am prompted for github creds 
- I get a cluster 
- I get 3 new gitops repos (dev, staging, and prod)

### Actual behaviour

- there's no prompt - and i just get an error:
```
ERROR: error creating cluster configuring the git auth: creating the git auth config service: getting team settings from namespace default: unable to find development environment in default to get team settings
error: configuring the git auth: creating the git auth config service: getting team settings from namespace default: unable to find development environment in default to get team settings
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.894
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.13.7
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS
```
BBBBBBUUUUUUUUUUUUTTTTTTTTTT - if i roll back to `2.0.650` the error goes away and i get the prompt again!

### Jenkins type

- [X] Classic Jenkins

### Kubernetes cluster

N/A - i'm trying to create a cluster using `jx create cluster`

### Operating system / Environment

Ubuntu

**Comment by hferentschik** [comment]
Have you tried `jx boot` - https://jenkins-x.io/docs/getting-started/setup/boot/? It is the recommended path to install Jenkins X now. 

`jx install` which is called by `jx create cluster` will eventually be deprecated.
