### ISSUE TITLE
JNLP Container fails to start

### ISSUE THREAD

**Issue by faucherb94** [jenkins-x/jx#5893]
### Summary

Every time I start a build, the build pod fails to get created because the JNLP container encounters an error and terminates.

I remember encountering this error a week or two ago; I don't remember how I got past it, I think I had to just reinstall jenkins x entirely :upside_down_face:

I've tried changing the workdir on the JNLP container as suggested here: https://github.com/KostyaSha/yet-another-docker-plugin/issues/184#issuecomment-322996960 with the same result.

I tried updating the JNLP image used by the container to the latest, 3.35-5-alpine, same result.

### Steps to reproduce the behavior

Starting a build

### Expected behavior

Pod creates successfully and build runs

### Actual behavior

JNLP Container terminates with error:

```
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Warning: SECRET is defined twice in command-line arguments and the environment variable
Warning: AGENT_NAME is defined twice in command-line arguments and the environment variable
Oct 21, 2019 8:58:10 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: gradle-70rs9
Oct 21, 2019 8:58:10 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Oct 21, 2019 8:58:10 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3.26
Exception in thread "main" java.io.IOException: The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins/agent
        at org.jenkinsci.remoting.engine.WorkDirManager.verifyDirectory(WorkDirManager.java:249)
        at org.jenkinsci.remoting.engine.WorkDirManager.initializeWorkDir(WorkDirManager.java:202)
        at hudson.remoting.Engine.startEngine(Engine.java:251)
        at hudson.remoting.Engine.startEngine(Engine.java:227)
        at hudson.remoting.jnlp.Main.main(Main.java:228)
        at hudson.remoting.jnlp.Main._main(Main.java:223)
        at hudson.remoting.jnlp.Main.main(Main.java:189)
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.894
jenkins x platform 2.0.1496
Kubernetes cluster v1.14.7-eks-e9b1d0
kubectl            v1.16.2
helm client        Client: v2.15.0+gc244026
git                2.23.0
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS v1.14.7 via custom creation scripts.

### Operating system / Environment

Ubuntu 16.04 and macOS 10.14

**Comment by faucherb94** [comment]
This seemed to be fixed by reverting the jx platform to v2.0.1099.

**Comment by pavlops** [comment]
This is still happening on:

NAME               VERSION
jx                 2.0.1029
jenkins x platform 2.0.1673
Kubernetes cluster v1.13.12-eks-c500e1
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.13.6 build 17G7024

**Comment by deanesmith** [comment]
Hi @faucherb94,

We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
