### ISSUE TITLE
jx-docs build is failing with "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx#5903]
### Summary 

A build on `jx-docs` is failing with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbe67d2]
goroutine 145 [running]:
github.com/gohugoio/hugo/hugofs.(*fileInfoMeta).IsDir(0xc0075e01e0, 0xc0073f7f80)
    <autogenerated>:1 +0x32
github.com/spf13/afero.IsDir(0x1c57b40, 0xc0001d19c0, 0xc0073f7f80, 0x27, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/github.com/spf13/afero@v1.2.2/util.go:279 +0x85
github.com/spf13/afero.(*CopyOnWriteFs).Open(0xc0006270a0, 0xc0073f7f80, 0x27, 0x187825e, 0x7, 0xc0020d2f40, 0x1f)
    /root/go/pkg/mod/github.com/spf13/afero@v1.2.2/copyOnWriteFs.go:232 +0xb6
github.com/gohugoio/hugo/hugofs.(*languageCompositeFs).Open(0xc0004c64c0, 0xc0073f7f80, 0x27, 0xc0073f7f80, 0x27, 0x0, 0x0)
    /hugo-0.58.3/hugofs/language_composite_fs.go:43 +0x46
...
```

The build details are here: https://dashboard-jx.jenkins-x.live/teams/jx/projects/jenkins-x/jx-docs/PR-2130/2

The code builds fine locally (using docker-compose etc.) and other builds today have been fine

### Steps to reproduce the behavior

* Open a PR on jx-docs
* Trigger a build, e.g. via '/ok-to-test'

### Expected behavior

* Build finished without any issues

### Actual behavior

* Build failed

### Jx version

don't know

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by dennisnewel** [comment]
Affected PR: jenkins-x/jx-docs#2130

**Comment by mauromorales** [comment]
Issue is related to missing files see follow up on PR https://github.com/jenkins-x/jx-docs/pull/2130#issuecomment-546092461
