### ISSUE TITLE
jx get applications command doesn't return any application deployed by environment controller

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5905]
### Summary 

In a multi-cluser setup when running the `jx get applications` command against the production cluster, it should returned the list of applications deployed using the `environment controller + tekton pipeline`. 

The command doesn't return currently any application. 

### Expected behavior

The command should return the list of applications deployed in the `jx-production` namespace. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
@ccojocar in a multi-cluster env, this may just have to be a caveat.
