### ISSUE TITLE
Jx boot creating environments in wrong GitHub org

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5907]
### Summary 
Unable to use `jx delete application` to remove an application from the staging environment of a cluster created by `jx boot`. The symptoms are:

```
➜ jx delete application test301-service
regenerated Prow configuration
Removing application test301-service from environment Staging
WARNING: Waiting for the fork of tdcox/environment-d70-staging to appear...
Forked Git repository to https://github.com/tdcox/environment-d70-staging
Created Pull Request: https://github.com/bootsbot/environment-d70-staging/pull/2
Waiting for pull request https://github.com/bootsbot/environment-d70-staging/pull/2 to merge
WARNING: Failed to query the Pull Request last commit status for https://github.com/bootsbot/environment-d70-staging/pull/2 ref 681bc7c6c3528816d2aa7e58cc718ac470a8e30d Could not find a status for repository bootsbot/environment-d70-staging with ref 681bc7c6c3528816d2aa7e58cc718ac470a8e30d
WARNING: Failed to query the Pull Request last commit status for https://github.com/bootsbot/environment-d70-staging/pull/2 ref 681bc7c6c3528816d2aa7e58cc718ac470a8e30d Could not find a status for repository bootsbot/environment-d70-staging with ref 681bc7c6c3528816d2aa7e58cc718ac470a8e30d
error: deleting application: deleting application test301-service from environment staging: Timed out waiting for pull request https://github.com/bootsbot/environment-d70-staging/pull/2 to merge. Waited 1h0m0s
```

Looking at the PR, it says `I'm waiting for a bootsbot member to verify that this patch is reasonable to test. If it is, they should reply with /ok-to-test on its own line.`

It seems that the problem is actually that `jx boot` has created the environments under the personal git account of the bot user rather than under the desired organisation. This then prevents team members from performing activities against the environments since they cannot collaborate automatically against the environment repos.

Looking more closely, it is unclear how we are intended to specify a bot user and a GitHub organisation as part of the configuration?

### Jx version

The output of `jx version` is:

```
jx                 2.0.871
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

jx boot

**Comment by garethjevans** [comment]
Hi @tdcox, the organisation that the environments use can be configured in the `jx-requirements.yml` - https://github.com/jenkins-x/environment-tekton-weasel-dev/blob/master/jx-requirements.yml#L3
