### ISSUE TITLE
When I install jenkinsX, there are the following errors ：jx install error: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by yindejie** [jenkins-x/jx#591]
[root@k1 bin]# jx install
error: invalid configuration: no configuration has been provided

before  installing, I have installed kubernetes

**Comment by jstrachan** [comment]
I've never seen that one before. I wonder can your terminal use kubernetes? I wonder if there's no `~/.kube/config` created as part of using your kubernetes installation.

e.g. whats the output of

```
kubectl get namespaces
```

in the same command line terminal? I suspect the error may be related to your CLI not being able to talk to kubernetes as there's no `~/.kube/config` available? 

I freely admit the error message is very cryptic ;) will try make it a bit more clear.

**Comment by yindejie** [comment]
Sorry, no detailed information is provided. 
message:
[root@k1 .kube]# ls
cache  config  http-cache  schema
[root@k1 .kube]# kubectl get namespaces
NAME          STATUS    AGE
default       Active    87d
kube-public   Active    87d
kube-system   Active    87d
[root@k1 .kube]#

**Comment by jstrachan** [comment]
just out of interest, what kind of kubernetes cluster and operating system are you using?

**Comment by yindejie** [comment]
kubernetes cluster:1.8.5    operating system :centos7.2

**Comment by rawlingsj** [comment]
I think I've seen that error message before when git operations fail.  Can you check the username and apitoken are valid in the `~/.jx/gitAuth.yaml` file?

**Comment by jstrachan** [comment]
thanks - and just to be clear, the only output is:
```
[root@k1 bin]# jx install
error: invalid configuration: no configuration has been provided
```
right?

BTW we've a pending issue to validate that things like helm are also installed: https://github.com/jenkins-x/jx/issues/555 - I wonder if this is a cryptic error if there's no `helm` installed?

I wonder if you could try:
```
jx version
``` 

and post the output here please?

**Comment by yindejie** [comment]
@rajdavies jx install error, have no .jx directory
@jstrachan 
jx version output:

[root@k1 ~]# helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
[root@k1 ~]# jx version
WARNING: Failed to find helm installs: exit status 1
WARNING: Failed to connect to kubernetes: invalid configuration: no configuration has been provided
NAME           VERSION
jx             1.1.42
Helm Client    v2.8.2+ga802316
Helm Server    v2.8.2+ga802316
Kubectl Client v1.8.5
Git            git version 1.8.3.1
[root@k1 ~]#

**Comment by jstrachan** [comment]
I'm a bit at a loss why `helm` works from the command line but not when triggered via `jx`. Thats kinda wacky - sounds like golang can't find `helm` on the PATH.

Similarly I don't grok how `kubectl` works from the command line but `jx` cannot seem to connect to kubernetes.

I wonder what this outputs:
```
echo $KUBECONFIG
which helm
```
I wonder if we don't yet support custom `KUBECONFG` environment variables. Also if `jx` can't seem to be able to find the `helm` executable for some reason

**Comment by jstrachan** [comment]
I've just added some more diagnostics into the execution of `jx version` which should be released shortly to display more helpful information if `helm list` fails - which should explain why you get `WARNING: Failed to find helm installs: exit status 1`.

I also tested locally using a custom `KUBECONFIG` with `jx version` and found we do support it just fine.

So I'm still at a loss why `kubectl` can connect to kubernetes, but `jx` seems to think there's no kubernetes configuration in `~/.kube/config` or `$KUBECONFIG`

**Comment by yindejie** [comment]
@jstrachan 
Maybe there's some problem when kubernetes installing(another person installed)
now, I'll reinsall kubernetes 、helm and kubectl,
I'll output the results here
thx

**Comment by jstrachan** [comment]
@yindejie thanks for all your help on this issue BTW - we want to make the `jx install` just work and give meaningful errors when something is wrong. 

Version `1.1.60` should be out with the next hour here: https://github.com/jenkins-x/jx/releases 

BTW recent `jx` distributions let you check if you are on the latest `jx` and if not upgrade via typing `jx install`

**Comment by jstrachan** [comment]
@yindejie btw you were using the same shell and user to run `kubectl helm & jx` commands right? Just checking to be sure - as I'm a little confused right now ;)

**Comment by yindejie** [comment]
@jstrachan The problem has been solved:Incorrect installation of kubernate ,
Thank you for your guidance

**Comment by McDingl** [comment]
i have the same err:
1.first i install on my master k8s ，not have the err ,when i enter : jx uninstall ,and then  re-install by :jx install,the err found ；

below is ~/.kube/config ：

  name: kubernetes
contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: default
- context:
    cluster: kubernetes
    namespace: jx
    user: admin
  name: kubernetes
current-context: default
