### ISSUE TITLE
Vault unable to reuse storage bucket if cluster zone changes

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5913]
### Summary 

If you create a cluster in zone x, then delete it and finally create a new cluster with the same name in a different zone, Vault is not able to install.

The reason is that the cluster deletion does not delete the Vault bucket. When the new cluster is then provisioned the Vault setup tries to re-use the existing bucket, but won't be able to read from it, since it is in a different cluster and not multi zonal. 

As user you will see:
```
generated schema file /Users/hardy/tmp/boot/hardy-dev/jenkins-x-boot-config/env/parameters.schema.json from template /Users/hardy/tmp/boot/hardy-dev/jenkins-x-boot-config/env/parameters.tmpl.schema.json
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
```

and in the end, you get a timeout error.

We should be adding some checks whether the zones of the cluster and the bucket match or check whether the bucket is readable.

**Comment by dineshmistry** [comment]
I am getting the same error as above but I did not delete and recreate this is a brand new setup. I created the cluster and then used 'jx boot'.

It appears the cluster is set up in us-east4-c and the buckets were created in us-east4 (Northern Virginia) and I am still getting:

Waiting for vault to be initialized and unsealed...
error: creating system vault URL client: wait for vault to be initialized and unsealed: reading vault health:

**Comment by srehmanproov** [comment]
I see same issue
