### ISSUE TITLE
helm Error: transport is closing

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/jx#592]
Putting this here for reference mostly.

This error is fixed in helm 2.9.0-rc1
https://github.com/kubernetes/helm/issues/3409
https://github.com/kubernetes/helm/pull/3482

I upgraded helm from https://kubernetes-helm.storage.googleapis.com/helm-v2.9.0-rc3-darwin-amd64.tar.gz
and upgraded tiller with 

    helm init --upgrade

then cleaned up before installing jx again

    helm delete --purge jenkins-x; kubectl delete -n jx job/expose

```
Update Complete. ⎈ Happy Helming!⎈
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.507 --values=/Users/csanchez/.jx/gitSecrets.yaml --values=/Users/csanchez/.jx/adminSecrets.yaml --values=/Users/csanchez/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: transport is closing
make: *** [install] Error 1
Error: Command failed  make ARGS=--values=/Users/csanchez/.jx/gitSecrets.yaml --values=/Users/csanchez/.jx/adminSecrets.yaml --values=/Users/csanchez/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2
```

**Comment by jstrachan** [comment]
ah great - we should upgrade to the latest helm. 

I'm just adding a helper command to help validate the versions of things like helm & jx to help folks detect if they need to upgrade as well as tools to automatically upgrade - e.g. `jx version` does that now for `jx`.

As soon as we've better validation & upgrade tooling in place we can more aggressively move to a Continuous Delivery model around tools like `jx` and `helm` keeping track with the latest known good versions

**Comment by ccojocar** [comment]
This is fixed. Helm version was updated.
