### ISSUE TITLE
jx boot failing from clean cluster

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5921]
### Summary 
Running `jx boot` in an empty folder with a clean cluster context results in an immediate error:

```
➜ jx boot
WARNING: there was a problem obtaining the boot config repository git configuration, falling back to defaults. Error: there was a problem obtaining the remote Git URL of directory .: failed to unmarshal  due to no GitConfDir defined
No Jenkins X pipeline file jenkins-x.yml or no jx boot requirements file jx-requirements.yml found. You are not running this command from inside a Jenkins X Boot git clone
? A local Jenkins X versions repository already exists, pulling the latest: Yes
error: failed to create version resolver: : pulling the latest: non-fast-forward update
```

Previously, this would bootstrap itself by installing whatever was necessary.

### Jx version

The output of `jx version` is:

```
2.0.905
```

**Comment by tdcox** [comment]
The problem can be worked around by deleting ~/.jx/environments/

We seem to be back to the age-old problem of developers presupposing that there will only ever be one cluster associated with one instance of a workstation. I would suggest that it is essential that the architecture make it explicit that this is always going to be a many-to-many relationship in practice. A single user may be maintaining many clusters and many users may be jointly responsible for maintaining individual cluster instances.

All local caching must be isolated under a tree structure that respects the individual kubernetes context or project/cluster name. Note that cluster-name is only unique within the scope of a project and a user can be expected to participate in multiple projects.

**Comment by babadofar** [comment]
also "jx context" , which switches the context, switches context "globally" - all open terminals get the same context. Which can be a little surprising when you believe you are working on separate clusters.

**Comment by EnziinSystem** [comment]
Not exist "~/.jx/environments/"
```
kevin@Kevin-PC:~$ ls -la ~/.jx
total 24
drwxr-----  6 kevin kevin 4096 Dec 31 09:08 .
drwxr-xr-x 52 kevin kevin 4096 Dec 31 09:09 ..
drwxr-----  2 kevin kevin 4096 Dec 24 11:39 bin
drwxr-----  2 kevin kevin 4096 Dec 26 07:08 debug
drwxr-----  3 kevin kevin 4096 Dec 31 09:08 draft
drwxr-----  9 kevin kevin 4096 Dec 24 11:39 jenkins-x-versions
kevin@Kevin-PC:~$ 
```

**Comment by david-ecc** [comment]
`jx boot` does not work for me, too. It prints a warning and eats 100% CPU then, until it is terminated (CTRL-C)

```
PS C:\dev\jx> jx --version
2.0.1116
PS C:\dev\jx> jx boot
WARNING: there was a problem obtaining the boot config repository git configuration, falling back to defaults. Error: there was a problem obtaining the remote Git URL of directory .: failed to unmarshal  due to no GitConfDir defined
```
