### ISSUE TITLE
jx version out of sync in boot version stream

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5922]
### Summary 
`brew upgrade jx` is currently installing `2.0.905` however `jx boot` is asking the user to 'upgrade' to `2.0.902`.
```
WARNING: A different jx version 2.0.902 is available in the version stream. We highly recommend you upgrade to it.
```
```
➜ which jx
/usr/local/bin/jx
(base)
jenkins-x-boot-config on  master [⇕!] via 🅒 base
➜ jx --version
2.0.905
```

**Comment by abayer** [comment]
Hmm, that's weird - `jenkins-x-versions` has `2.0.905` in it. Feels like you've somehow got a stale `~/.jx/jenkins-x-versions`. I'm guessing this happened during the `jx step verify preinstall` execution?

**Comment by tdcox** [comment]
I have run this several times today and get the same message each time. I note that `versionStream:` has been updated from `master` to `v1.0.154` in my jx-requirements.yml so I'm guessing it gets pinned at a point in time and not revised subsequently?

**Comment by tdcox** [comment]
Yeah, just put it back to master and it got updated to `v1.0.155' and no more warning message.

In this case, I had started an install, paused to update my jx-requirements.yml and then restarted so this is another race condition where a jx release can happen during an install and put things out of step.

**Comment by abayer** [comment]
Yeah, I'm legitimately not sure what we should do in that situation.

**Comment by tdcox** [comment]
Maybe just not prompt people to upgrade jx during an install?
