### ISSUE TITLE
jx install CMD stuck on Installing jenkins-x-platform all day and no response

### ISSUE THREAD

**Issue by 474846718** [jenkins-x/jx#5940]
C:\Users\Administrator>jx install

Then

WARNING: waiting for install to be ready, if this is the first time then it will take a while to download images
WARNING: deployment deck failed to become ready in namespace jx
WARNING: deployment hook failed to become ready in namespace jx
WARNING: deployment horologium failed to become ready in namespace jx
WARNING: deployment jenkins-x-chartmuseum failed to become ready in namespace jx
WARNING: deployment jenkins-x-controllerbuild failed to become ready in namespace jx
WARNING: deployment jenkins-x-controllerrole failed to become ready in namespace jx
WARNING: deployment jenkins-x-docker-registry failed to become ready in namespace jx
WARNING: deployment jenkins-x-heapster failed to become ready in namespace jx
WARNING: deployment jenkins-x-nexus failed to become ready in namespace jx
WARNING: deployment pipeline failed to become ready in namespace jx
WARNING: deployment pipelinerunner failed to become ready in namespace jx
WARNING: deployment plank failed to become ready in namespace jx
WARNING: deployment sinker failed to become ready in namespace jx
WARNING: deployment tekton-pipelines-controller failed to become ready in namespace jx
WARNING: deployment tekton-pipelines-webhook failed to become ready in namespace jx
WARNING: deployment tide failed to become ready in namespace jx
Jenkins X deployments ready in namespace jx
error: configuring ImportMode in team settings: failed to create the jx Dev namespace: Failed to create Namespace jx Post https://kubernetes.docker.internal:6443/api/v1/namespaces: read tcp 127.0.0.1:55516->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by 474846718** [comment]
I don't know where to start to find the problem.

**Comment by deanesmith** [comment]
Hi @474846718, can you provide more information about the Kubernetes platform you're using, logs, flags on the command?  We believe this may be related to a bug in Windows but need more evidence.
