### ISSUE TITLE
Unable to create new jx install based clusters after running jx boot on shared workstation

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5947]
### Summary 
Following a number of experiments with `jx boot`, I subsequently went back to creating a cluster via the `jx install` path and discovered that this now reliably fails at the following point with the following error:

```
Vault 'jx-vault-d76' exposed
System vault created named jx-vault-d76 in namespace jx.
Set up a Git username and API token to be able to perform CI/CD
ERROR: error creating cluster configuring the git auth: creating the git auth config service: getting team settings from namespace default: unable to find development environment in default to get team settings
error: configuring the git auth: creating the git auth config service: getting team settings from namespace default: unable to find development environment in default to get team settings
```
I am wondering if something else has become corrupted in my `~/.jx` folder?

It's important that legacy and new install mechanisms can co-exist on the same workstation for a period of time or it will very difficult and risky for customers to migrate across...

### Jx version

The output of `jx version` is:

```
2.0.905
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Ref https://github.com/jenkins-x/jx/issues/5921

**Comment by deanesmith** [comment]
Backing off priority in favor of other boot-related efforts.
