### ISSUE TITLE
Importing repo with jx import doesn't trigger on pull requests or chatops for specific repo

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#5953]
### Summary 

We had a working CI Jenkins X setup with our [seldon-core](https://github.com/SeldonIO/seldon-core/blob/master/jenkins-x.yml) repository. We upgraded to the latest version, and now releases / PRs creations / ChatOps don't trigger any pipeline actions - the release pipeline only gets triggered once on creation.

### Steps to reproduce the behavior

Cluster first gets created with:
`jx create cluster gke --skip-installation -n jx-production-cluster --skip-login=true`

Then jx is initialised with `jx boot`, using [seldonio](https://github.com/seldonio/) as organisation user, and [seldondev](https://github.com/seldondev/) as bot. 

Permissions for the access token from the seldondev bot user are correctly set with the permissions requested, and seldondev has access to the organisation (this can be confirmed as all environment-jx-production-cluster- repos are created correctly).

After modifying the OWNERS file to have all the relevant users, nothing gets triggered when creating a PR or running master.

I can confirm that it can be reproduced as I've created a clean installation + clean cluster multiple times from scratch.

### Expected behavior

Pipeline gets created with an existing `jenkins-x.yaml` file containing PR steps which gets triggered when new PR is added.

### Actual behavior

When new PR is added or ChatOps are triggered, a new pipeline is triggered

### Diagnosing

I can confirm the hooks are reaching the server, as I can see the hooks in the logs. I tried killing the controller but that didn't make a difference (there are no logs when comments are added).

I have tried creating a clean cluster multiple times, by deleting the ~/.jx and environment-jx-production-cluster- repositories created for the environments without success.

The OWNERS file is correctly configured with all the relevant users in there (including the user that created the PR). 

Also when creating PRs on the environment-jx-production-cluster- repos, nothing happens. And when actually adding another commit to master (to trigger a release) nothing happens.

### Jx version

The output of `jx version` is:

```
jx                 2.0.916
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS


verifying packages

```

Also failed with 2.0.913

### Jenkins type

- [ x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE, created with `jx create cluster gke --skip-installation -n jx-production-cluster --skip-login=true`

### Operating system / Environment

Ubuntu 18

**Comment by axsaucedo** [comment]
What is even more strange, is that I have just tested it in our [Seldon Core JX test repository](https://github.com/SeldonIO/jenkins-x-seldon-core-sandbox) which we use as a mirror jenkins X sandbox, which has an older version of the codebase and it seems to import it correctly, and PRs in that repository do trigger the bot to comment and the pipelines to execute...

Permissions for the seldondev bot user are configured the same across both repositories.

The test repository has a much older version of Seldon core - basically the older version doesn't have our Go operator in the same repo - but this shouldn't make a difference. 

I have identified an error which may not be related but could be worth pointing out. When running `jx import` in the older repo, it seems to work without issues, but when running `jx import` (both without --no-draft), it tries to create all the draft files, and then errors out with the following error:

```
ERROR: Could not find pack: none going to try detect which pack to use
performing pack detection in folder /home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core
--> Draft detected Jupyter Notebook (53.172345%)
--> Could not find a pack for Jupyter Notebook. Trying to find the next likely language match...
--> Draft detected JSON (10.421034%)
--> Could not find a pack for JSON. Trying to find the next likely language match...
--> Draft detected YAML (9.521049%)
--> Could not find a pack for YAML. Trying to find the next likely language match...
--> Draft detected Python (7.477258%)
selected pack: /home/alejandro/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/python
replacing placeholders in directory /home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core
app name: seldon-core, git server: github.com, org: seldonio, Docker registry org: seldon-core-ops
skipping directory "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/.git"
skipping ignored file "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/components/outlier-detection/seq2seq-lstm/models/preprocess_seq2seq.pickle"
skipping ignored file "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/components/outlier-detection/seq2seq-lstm/models/seq2seq.pickle"
skipping ignored file "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/components/outlier-detection/vae/models/preprocess_vae.pickle"
skipping ignored file "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/components/outlier-detection/vae/models/vae.pickle"
skipping symlink file "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/monitoring/prometheus/prometheus-config.yml"
skipping symlink file "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/monitoring/prometheus/rules"
skipping directory "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/seldon-core/.git"
skipping directory "/home/alejandro/Programming/kubernetes/seldon/seldon-core-master/seldon-core/testing/scripts/proto"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/denormal/go-gitignore.NewPattern(0xc0003a85a8, 0x0, 0x1, 0x1, 0x1)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/pattern.go:57 +0x29e
github.com/denormal/go-gitignore.(*parser).path(0xc00067d410, 0xc00097de00, 0xc00097d720, 0xc00097de00, 0x0, 0x0)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/parser.go:207 +0x88
github.com/denormal/go-gitignore.(*parser).build(0xc00067d410, 0xc00097de00, 0x0, 0x0, 0x0, 0x0)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/parser.go:154 +0x84
github.com/denormal/go-gitignore.(*parser).Next(0xc00067d410, 0x5922020, 0xc00097ddb0)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/parser.go:98 +0x14a
github.com/denormal/go-gitignore.(*parser).Parse(0xc00067d410, 0xc00067d410, 0x1000, 0xc0002f2000)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/parser.go:49 +0x6a
github.com/denormal/go-gitignore.New(0x58a8ec0, 0xc0003a8570, 0xc001e78b00, 0x6d, 0xc000b56620, 0x0, 0x0)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/gitignore.go:73 +0x116
github.com/denormal/go-gitignore.NewWithErrors(0xc001e78b00, 0x78, 0xc0003ae250, 0x0, 0x0)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/gitignore.go:153 +0x3fc
github.com/denormal/go-gitignore.NewWithCache(0xc001e78b00, 0x78, 0x58ca920, 0xc0003ae260, 0xc0003ae250, 0x0, 0xc00156eeca)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/gitignore.go:190 +0x124
github.com/denormal/go-gitignore.(*repository).Relative(0xc00014e380, 0xc001e78a4d, 0x2b, 0x0, 0xc001e78a4d, 0x2b)
        /workspace/go/pkg/mod/github.com/denormal/go-gitignore@v0.0.0-20180713143441-75ce8f3e513c/repository.go:240 +0x293
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).skipPathForReplacement(0xc000530a00, 0xc001e78a00, 0x78, 0x5933720, 0xc00195e750, 0x5932b80, 0xc00014e380, 0xc00156f128, 0x471f2a, 0x470ffb)
        /workspace/source/pkg/cmd/importcmd/import.go:1095 +0xcc
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).ReplacePlaceholders.func1(0xc001e78a00, 0x78, 0x5933720, 0xc00195e750, 0x0, 0x0, 0x496bda, 0xc00195e750)
        /workspace/source/pkg/cmd/importcmd/import.go:1067 +0x97
path/filepath.walk(0xc001e78a00, 0x78, 0x5933720, 0xc00195e750, 0xc00072e570, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:358 +0x426
path/filepath.walk(0xc001430380, 0x6d, 0x5933720, 0xc00195e680, 0xc00072e570, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.walk(0xc001cd1bc0, 0x51, 0x5933720, 0xc00195e5b0, 0xc00072e570, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.walk(0xc00005a054, 0x4c, 0x5933720, 0xc001934a90, 0xc00072e570, 0x0, 0x30)
        /usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.Walk(0xc00005a054, 0x4c, 0xc00072e570, 0x8, 0xc00197b600)
        /usr/local/go/src/path/filepath/path.go:404 +0xff
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).ReplacePlaceholders(0xc000530a00, 0xc0006df468, 0xa, 0xc000cf6a40, 0xf, 0x0, 0xc000b37760)
        /workspace/source/pkg/cmd/importcmd/import.go:1066 +0x687
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).DraftCreate(0xc000530a00, 0xb, 0xc0006dfb00)
        /workspace/source/pkg/cmd/importcmd/import.go:540 +0x3b8
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).Run(0xc000530a00, 0x0, 0x0)
        /workspace/source/pkg/cmd/importcmd/import.go:376 +0xb27
github.com/jenkins-x/jx/pkg/cmd/importcmd.NewCmdImport.func1(0xc000530c80, 0xa35ba10, 0x0, 0x0)
        /workspace/source/pkg/cmd/importcmd/import.go:145 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc000530c80, 0xa35ba10, 0x0, 0x0, 0xc000530c80, 0xa35ba10)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000331900, 0xc000515a80, 0x58d5060, 0xc00000e010)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc000681f88, 0xc0000ba058)
        /workspace/source/cmd/jx/app/jx.go:19 +0x185
main.main()
        /workspace/source/cmd/jx/jx.go:11 +0x32
```

**Comment by axsaucedo** [comment]
At this point the only visible difference in config I can see is when running `jx get pipeline`:
```
Name                                                         URL LAST_BUILD STATUS DURATION
SeldonIO/jenkins-x-seldon-core-sandbox/master                N/A N/A        N/A    N/A
axsaucedo/seldon-core/master                                 N/A N/A        N/A    N/A
seldonio/environment-jx-production-cluster-dev/master        N/A N/A        N/A    N/A
seldonio/environment-jx-production-cluster-production/master N/A N/A        N/A    N/A
seldonio/environment-jx-production-cluster-staging/master    N/A N/A        N/A    N/A
seldonio/seldon-core/master                                  N/A N/A        N/A    N/A
```

**Comment by axsaucedo** [comment]
Oh wow, it was actually the capitalisation (or related to). It seems I ran into #341 briefly when trying to install in 2.0.912, but then in 2.0.916 it seems to change a capitalised org name into smaller cases (i.e. SeldonIO -> seldonio) in the `jx-requirements.yml` file itself. This seems to result in the change for the capitalisation in the name of the pipelines as above, which seems to cause the issues (and not trigger anything).

I managed to overcome this by importing the repo using `jx import --no-draft=true --url=https://github.com/SeldonIO/seldon-core.git` which actually imports the repo from URL. 

Now when I run `jx get pipelines` I get the following:
```
Name                                                         URL LAST_BUILD STATUS DURATION
SeldonIO/jenkins-x-seldon-core-sandbox/master                N/A N/A        N/A    N/A
SeldonIO/seldon-core/master                                  N/A N/A        N/A    N/A
axsaucedo/seldon-core/master                                 N/A N/A        N/A    N/A
seldonio/environment-jx-production-cluster-dev/master        N/A N/A        N/A    N/A
seldonio/environment-jx-production-cluster-production/master N/A N/A        N/A    N/A
seldonio/environment-jx-production-cluster-staging/master    N/A N/A        N/A    N/A
```

And now the pipelines are actually triggered on PRs and commits in master. The rest of the repos are still not working however (I assume due to this capitalisation).

**Comment by deanesmith** [comment]
@axsaucedo a recent change to address this is unfortunately not backward compatible.

**Comment by deanesmith** [comment]
@pmuir FYI, possible regression

**Comment by axsaucedo** [comment]
Thanks @deanesmith. By the way, one thing that may be worth mentioning is that when I ran this in `2.0.912`, if an fresh installation is ran through the CLI and the interactive param for the organisation is provided with capital letters it would still fail (even though this seemed to have been fixed when initialised with the jx-requirements.yaml. I am not sure if this was explicitly addressed in 2.0.916, but I want to raise it as it may be another thing to consider when making this change.

**Comment by axsaucedo** [comment]
@deanesmith this issue may have been fixed. We just had to uninstall the cluster and re-install it to fix #6291, and now it seems that our repo, which has capitalisations in the name, is now working. Was there any changes that addressed this issue?

**Comment by deanesmith** [comment]
@axsaucedo, there were a couple related PR's that may have addressed your issue, but I am thinking possibly this one - https://github.com/jenkins-x/jx/pull/6420.

**Comment by deanesmith** [comment]
@axsaucedo Please re-open if you encounter it again.  Thank you for your help!
