### ISSUE TITLE
Generating Terraform code with jx create terraform

### ISSUE THREAD

**Issue by CarpathianUA** [jenkins-x/jx#5956]
Hey guys,
Is there any plans to deliver the same functionality for generating Terraform code as for GKE provider?
It will be really useful to do all the required things with one awesome tool - `jx`
Thanks in advance!

**Comment by deanesmith** [comment]
@CarpathianUA can you be more specific?  Are you looking for Terraform code for another particular provider?

**Comment by CarpathianUA** [comment]
Hi @deanesmith ,
I know that `jx create terraform` can generate Terraform codebase only for GKE. What I asking here is there any plans in the future to have the same functionality not only limited to GKE, but for EKS, for example.

**Comment by deanesmith** [comment]
Thank you @CarpathianUA.  We are currently hardening EKS support for Jenkins X using `jx boot`. Terraform code for EKS is not a primary concern right now but I'm interested in better understanding your use case.  Would be care to elaborate?  The simplicity of what you're interested in may be established with boot.

**Comment by CarpathianUA** [comment]
Hi @deanesmith, thanks for the answer!
So my main purpose here that usually new EKS clusters are spawned up with Terraform configurations and/or modules. My proposition here is to have a simplified flow for teams who want to bootstrap EKS cluster not only with `jx create cluster` but with dedicated Terraform codebase, generated with `jx create terraform`

**Comment by fabstu** [comment]
/remove-lifecycle stale

This would be nice to have!

**Comment by nukarajusundeep** [comment]
https://jenkins-x.io/blog/2019/04/03/terraform-jenkins-x/

jx create terraform command not working

**Comment by nukarajusundeep** [comment]
Available Commands

Available Commands:
  create addon      Creates an addon
  create branchpattern Create a git branch pattern for your team
  create chat       Creates a chat server resource
  create cluster    Create a new Kubernetes cluster
  create devpod     Creates a DevPod for running builds and tests inside the cluster
  create docker     Create/update Docker auth for a given host and user in the config.json file
  create docs       Creates the documentation files
  create domain     Create a domain in a managed DNS service provider
  create environment Create a new Environment which is used to promote your Team's Applications via Continuous Delivery
  create etc-hosts  Creates a new Git server URL
  create git        Creates a Git resource
  create gke-service-account Creates a GKE service account
  create issue      Create an issue on the git project for the current directory
  create jenkins    Creates a Jenkins resource
  create mlquickstart Create a new machine learning app from a set of quickstarts and import the generated code into Git and Jenkins for CI/CD
  create post       Create a job which is triggered after a Preview is created
  create project    Create a new Project by importing code, using a Quickstart or custom wizard for Spring
  create pullrequest Create a Pull Request on the git project for the current directory
  create quickstart Create a new app from a Quickstart and import the generated code into Git and Jenkins for CI/CD
  create quickstartlocation Create a location of quickstarts for your team
  create spring     Create a new Spring Boot application and import the generated code into Git and Jenkins for CI/CD
  create step       Creates a step in the Jenkins X Pipeline
  create team       Create a new Team which is then provisioned later on
  create token      Creates a new user token for a service
  create tracker    Creates an issue tracker resource
  create user       Create a new User which is then provisioned by the user controller
  create variable   Creates an environment variable in the Jenkins X Pipeline
  create vault      Create a new Vault using the vault-operator

**Comment by nukarajusundeep** [comment]
How should I create terraform code using jx

**Comment by fabstu** [comment]
hmm I didnt know they were [deprecated](https://jenkins-x.io/commands/deprecation/).

**Comment by garethjevans** [comment]
The recommended way of using terraform with JX is by using the terraform modules e.g. https://jenkins-x.io/docs/install-setup/create-cluster/gke/

The `jx create terraform` command has been removed in favour of this.
