### ISSUE TITLE
jx import error creating jenkins credential jenkins-x-chartmuseum with TLS ingress

### ISSUE THREAD

**Issue by vgallissot** [jenkins-x/jx#597]
I modified the default ingresses to use TLS.
`jx import` doesn't follow 308 permanent redirect:

```
± jx import --dry-run=true --no-draft=true --verbose=true
? Do you wish to use jenkins-x as the git user name Yes
Everything up-to-date
error: error creating jenkins credential jenkins-x-chartmuseum 308 Permanent Redirect
```

I patched chartmuseum ingress with:
```
spec:
  tls:
  - hosts:
    - chartmuseum.jx.foo.bar
    secretName: secret-wildcard.jx.foo.bar
```

With that patch, all http requests are redirected to https via 308 HTTP code.

**Comment by vgallissot** [comment]
EDIT: the error is linked to jenkins ingress in TLS.
Moving back jenkins ingress to HTTP removes that error.

**Comment by stormmore** [comment]
This is tripping us up at the moment.
