### ISSUE TITLE
jx gc fails for multiple reasons

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#5972]
### Summary 

I have a situation where Helm releases for the preview environments already removed. I had an emergency where nodes don't have space. I've drained the nodes and done `docker system prune` on them. Then tried to upgrade jenkins-x and so on. So now I have some remains in `jx get previews` which I cannot remove.

```
jx gc previews -b                                                                                                                                     
WARNING: Can not get pull request 27, skipping: GET https://api.github.com/repos/my-corp/27/pulls/27: 404 Not Found []
WARNING: Can not get pull request 29, skipping: GET https://api.github.com/repos/my-corp/29/pulls/29: 404 Not Found []
Deleting helm release: jx-my-corp-cdp-web-pr-9
error: failed to delete preview environment my-corp-cdp-web-pr-9: failed to run 'helm delete --purge jx-my-corp-cdp-web-pr-9' command in directory '', output: 'Error: release: "jx-my-corp-cdp-web-pr-9" not found'
```

The first two somehow related #5898 and anyway I don't have Helm releases for them.
Third: also I don't have the Helm release for it (modified Jenkinsfile and altered `PREVIEW_NAMESPACE` env variable that time).

What to do in this situation? Where details about the previews located?

### Expected behavior

Garbage collector remove remains anyway.

### Actual behavior

Garbage collector crashes.

### Jx version

The output of `jx version` is:

```
jx version                                                                                                                                             
NAME               VERSION
jx                 2.0.912
jenkins x platform 2.0.1520
Kubernetes cluster v1.14.7-eks-e9b1d0
kubectl            v1.16.2
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.15 build 19A602
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS created via eksctl

### Operating system / Environment

Operating System   Mac OS X 10.15 build 19A602

**Comment by jeffkhull** [comment]
May be the same as, or related to, https://github.com/jenkins-x/jx/issues/5797

**Comment by stepanselyuk** [comment]
@jeffkhull I think reasons may be different, but the solution should be one: `jx gc previews` should not simply crash if it cannot find Helm chart or something other - it should actually clean things. Maybe with `--force` flag.

**Comment by pmuir** [comment]
try running `kubectl get env`, locating the one causing you problems, and then `kubectl delete env <name>` where `<name>` is the name of the one you think causes problems, then re-run the gc.

**Comment by stepanselyuk** [comment]
@pmuir thank you, it works.
