### ISSUE TITLE
Regression in `--semantic-release` flag for `jx step next-version --semantic-release --filename package.json`

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#5975]
### Summary 

I was previously using `jx step next-version --semantic-release --filename package.json` successfully, but after an upgrade to the latest version, the `--semantic-release` flag results in an error.

```
> jx step next-version --semantic-release --filename package.json

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c3e971]

goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).String(0x0, 0x0, 0xc0009869f0)
        /workspace/go/pkg/mod/github.com/!masterminds/semver@v1.4.2/version.go:113 +0x51
github.com/jenkins-x/jx/pkg/cmd/step.(*StepNextVersionOptions).Run(0xc000729560, 0x0, 0x0)
        /workspace/source/pkg/cmd/step/step_next_version.go:123 +0x23c
github.com/jenkins-x/jx/pkg/cmd/step.NewCmdStepNextVersion.func1(0xc00094b400, 0xc00097e300, 0x0, 0x3)
        /workspace/source/pkg/cmd/step/step_next_version.go:90 +0x71
github.com/spf13/cobra.(*Command).execute(0xc00094b400, 0xc00097e2d0, 0x3, 0x3, 0xc00094b400, 0xc00097e2d0)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00044a500, 0xc000650480, 0x58eecc0, 0xc00000e010)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0008f9f88, 0xc00005a0b8)
        /workspace/source/cmd/jx/app/jx.go:19 +0x185
main.main()
        /workspace/source/cmd/jx/jx.go:11 +0x32
```

Running without the `--semantic-release` flag works correctly, but obviously in a more naive manner:

```
> jx step next-version --filename package.json 

created new version: 1.0.38 and written to file: ./VERSION
```

It seems JX is behind on versions for github.com/Masterminds/semver.

It is using 1.4.2, though 1.5.0 and 3.x are now available as well. Given that the library was set to 1.4.2 months ago it seems more likely that the arguments being provided to the function invocation are incorrect.

### Steps to reproduce the behavior

In a node project run `jx step next-version --semantic-release --filename package.json`

### Expected behavior

A VERSION file is written with a semantically calculated version number

### Actual behavior

`[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c3e971]`

### Jx version

The output of `jx version` is:

```
jx version                                                         
NAME               VERSION
jx                 2.0.923
Kubernetes cluster v1.13.9-gke.3
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0
Operating System   "Fedora release 30 (Thirty)"
```

My colleague was running `2.0.521` locally still, and it worked for him. I saw errors in `2.0.912` as well.

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE - Terraform with JX Boot

### Operating system / Environment

Fedora 30 - though seeing same error in build logs from kubernetes.

**Comment by abayer** [comment]
I think the problem is on the jx side, not the semver side - the version struct we're calling `NewVersion()` on is nil, apparently.

Could you run `git for-each-ref --sort=creatordate --format=%(objectname)%00%(refname:short) --count=1 refs/tags` in a directory you can reproduce the `jx step next-version` error in? I wanna try reproducing things against that version.

**Comment by patrickleet** [comment]
@abayer just saw this now. Thanks for looking into this! 

Here's that command's results:

```
> git for-each-ref --sort=creatordate --format=%(objectname)%00%(refname:short) --count=1 refs/tags
zsh: missing end of string
```

and in bash:

```
$ git for-each-ref --sort=creatordate --format=%(objectname)%00%(refname:short) --count=1 refs/tags
bash: syntax error near unexpected token `('
```

Removing the format works but maybe not what you need?

```
$ git for-each-ref --sort=creatordate --count=1 refs/tags
b02e9f2c4057adce51083ff4bf25820977a52790 commit refs/tags/1.0.0
```

**Comment by patrickleet** [comment]
ah - think I got it - surrounding that format in quotes:

```
✗ git for-each-ref --sort=creatordate --format='%(objectname)%00%(refname:short)' --count=1 refs/tags
b02e9f2c4057adce51083ff4bf25820977a527901.0.0
```

**Comment by svilenvul** [comment]
@abayer, we also want to move to semantic versioning and use this feature into our pipeline and we faced the same issue. Please let me know if I can assist you with more information.

**Comment by haysclark** [comment]
I ran into this issue on my GCP cluster after updating too `jx 2.1.62` and then `jx 2.1.88`; however, the issue resolved itself after I scaled down my cluster (`gcloud container clusters resize CLUSTER_NAME --num-nodes=0`) and scaled it back up a day later (`gcloud container clusters resize CLUSTER_NAME --num-nodes=3`).

Thus, it clearly was a unique environment related issue; however, I wanted to take the time to mention this incase others encounter the issue.  For debugging sake, I did update my projects `jenkins-x.yaml` with the following (which still might need to be tweaked to see the output in `jx get build logs`):

```
buildPack: javascript
pipelineConfig:
  pipelines:
    release:
      setVersion:
        replace: true
        steps:
          - name: debugging--git-for-each-ref
            sh: git for-each-ref --sort=creatordate --format='%(objectname)%00%(refname:short)' --count=1 refs/tags
            comment: debug output of offending git status
          - name: next-version
            sh: jx step next-version --semantic-release --tag --filename='package.json'
            comment: set the version number in package.json using semantic-release and create a new release tag
```
