### ISSUE TITLE
Prow fork used by Jenkins X hasn't been rebased since March,2019

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5979]
### Summary 

The Jenkins X's prow fork shipped in both Jenkins X OSS/ CJXD hasn't been rebased since March, 2019. 

https://github.com/jenkins-x/test-infra/commits/master?after=dfba2f3fb0ec9af1c4b4e19b7af4658236bed06a+34

There seems to be many changes across the two repositories:
https://github.com/jenkins-x/test-infra/compare/master...kubernetes:master

Overall there is a difference of `5246` commits.

It is especially important that we take over the changes from `hook`, `deck` and `tide`. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by rudolph9** [comment]
Non-official response, from what I hear they are focusing effort on _lighthouse_ which support more than just github and a replacement for _prow_.
