### ISSUE TITLE
Implement EKS IRSA for Vault

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#5982]
### Summary 
Right now, we will ask the users for a pre creacted IAM User in order to extract the secret keys and use them to authenticate the Vault pod against AWS.

The right approach should be using IRSA so we can let the pod assume a Role instead of having to create (and handle) AWS Secret Keys.

We'll have to wait for  https://github.com/hashicorp/vault/issues/7450 to be fixed before we can implement this.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by sppwf** [comment]
Hi Guys, 

Do you think you have an ETA for this?

Thanks
