### ISSUE TITLE
Discovery on making JX_HOME better support multiple contexts

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5983]
We've seen a number of reported issues and discussions around problems with `~/.jx` and multiple `jx` contexts, different `jenkins-x-versions` versions, `environments` conflicts, etc. We should do some research and design around coming up with a solution for better supporting the ability to manage/provision/boot multiple `jx` contexts on a single workstation.

**Comment by deanesmith** [comment]
Backing off priority in favor of other activity.
