### ISSUE TITLE
Validate that helm3 works properly with boot and the rest of Jenkins X(quickstarts, environments, etc.)

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5985]
### Summary 

It seems that helm3 is soon on its way out. We should validate that boot and the rest of Jenkins X works properly with helm3. 

https://github.com/helm/helm/releases

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by cloudtagger** [comment]
helm 3 is not working for me. I get 
`failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'`
for jx boot even tho I have version 3 and helm3 is set in helmbin.

**Comment by xwlee** [comment]
Does anyone have a solution? can we downgrade `Helm` to v2?

**Comment by deanesmith** [comment]
Ref https://github.com/jenkins-x/jx/issues/6124, https://github.com/jenkins-x/jx/issues/6181

**Comment by jstrachan** [comment]
we have a solution now for helm 3 https://jenkins-x.io/docs/labs/boot/

though note it’s currently alpha
