### ISSUE TITLE
Chartmuesum is not behind any authentication

### ISSUE THREAD

**Issue by saadshahd** [jenkins-x/jx#5990]
### Summary 
Chartmuesum is publicly accessible and not behind any authentication, not even the basic-auth the deck and nexus have,

### Steps to reproduce the behavior
I just installed jx on my cluster.

### Expected behavior
Chartmuesum to be secured.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.721
jenkins x platform 2.0.1505
Kubernetes cluster v1.14.7-gke.10
kubectl            v1.16.0
helm client        Client: v2.13.1+g618447c
git                2.23.0
Operating System   Ubuntu 18.04.6 LTS
```

### Jenkins type
- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

### Operating system / Environment
Ubuntu 18.04

**Comment by ccojocar** [comment]
closing this as a dup of https://github.com/jenkins-x/jx/issues/5072
