### ISSUE TITLE
jx install fails with error "out of memory"

### ISSUE THREAD

**Issue by alfsender** [jenkins-x/jx#5996]
### Summary 
jx install fails with error "out of memory".

Command: "jx install --provider=aws --no-default-environments --default-admin-username=admin --default-admin-password=admin"

### Steps to reproduce the behavior
Using helm values file: /tmp/ing-values-105895725
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /home/ec2-user/.jx/jenkins-x-versions
WARNING: failed to create system vault in namespace jx due to no "jx-vault-arn-aws-eks-u" vault found in namespace "jx"
ERROR: Failed to install ingress chart: failed to update repository: failed to run 'helm repo update' command in directory '', output: 'Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x18aaed4, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc00c000000, 0x4000000, 0x2c10178)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x2bf1280, 0x5e000, 0x2bf1290, 0x2f)
        /usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x2bf1280, 0x2f, 0x0)
        /usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x2bf1280, 0x2f, 0x2c10188, 0x2bf1288)
        /usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x2bf1280, 0x2f, 0x7fd0b0dc0101, 0x7fd0b0dc24c0)
        /usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x2bf1280, 0x2f, 0x7fd0b1010101, 0x7fd0b0dc2430)
        /usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x5cdda, 0x450101, 0x7fd0b0dc2430)
        /usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

goroutine 35 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc0002fb100 sp=0xc0002fb0f8 pc=0x4572d0
runtime.mallocgc(0x5cdda, 0x1627fe0, 0x403901, 0xc0002fb1d8)
        /usr/local/go/src/runtime/malloc.go:949 +0x872 fp=0xc0002fb1a0 sp=0xc0002fb100 pc=0x40c002
runtime.makeslice(0x1627fe0, 0x5cdda, 0x5cdda, 0xc0002fb2d8)
        /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc0002fb1d0 sp=0xc0002fb1a0 pc=0x4424cc
bytes.makeSlice(0x5cdda, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:232 +0x6d fp=0xc0002fb200 sp=0xc0002fb1d0 pc=0x46e00d
bytes.(*Buffer).grow(0xc00826c0e0, 0x40, 0xc000428cb0)
        /usr/local/go/src/bytes/buffer.go:145 +0x16f fp=0xc0002fb250 sp=0xc0002fb200 pc=0x46d94f
bytes.(*Buffer).WriteString(0xc00826c0e0, 0xc000ba3180, 0x40, 0x0, 0xc0002fb2f0, 0xc00bfd6800)
        /usr/local/go/src/bytes/buffer.go:187 +0xe7 fp=0xc0002fb280 sp=0xc0002fb250 pc=0x46dd77
encoding/json.(*encodeState).string(0xc00826c0e0, 0xc000ba3180, 0x40, 0xc000ba3101)
        /usr/local/go/src/encoding/json/encode.go:953 +0x463 fp=0xc0002fb2e0 sp=0xc0002fb280 pc=0x5e2113
encoding/json.stringEncoder(0xc00826c0e0, 0x1627d20, 0xc007df1ca0, 0x98, 0xc007df0100)
        /usr/local/go/src/encoding/json/encode.go:611 +0xd9 fp=0xc0002fb388 sp=0xc0002fb2e0 pc=0x5df579
encoding/json.(*encodeState).reflectValue(0xc00826c0e0, 0x1627d20, 0xc007df1ca0, 0x98, 0xc007df0100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc0002fb3c0 sp=0xc0002fb388 pc=0x5dd622
encoding/json.interfaceEncoder(0xc00826c0e0, 0x1675600, 0xc00bfd6890, 0x94, 0xc00bfd0100)
        /usr/local/go/src/encoding/json/encode.go:620 +0xad fp=0xc0002fb408 sp=0xc0002fb3c0 pc=0x5df94d
encoding/json.mapEncoder.encode(0x194afe8, 0xc00826c0e0, 0x167c680, 0xc00b560f60, 0x15, 0x1670100)
        /usr/local/go/src/encoding/json/encode.go:702 +0x352 fp=0xc0002fb550 sp=0xc0002fb408 pc=0x5e03d2
encoding/json.mapEncoder.encode-fm(0xc00826c0e0, 0x167c680, 0xc00b560f60, 0x15, 0xc00b560100)
        /usr/local/go/src/encoding/json/encode.go:678 +0x64 fp=0xc0002fb590 sp=0xc0002fb550 pc=0x5ebdf4
encoding/json.(*encodeState).reflectValue(0xc00826c0e0, 0x167c680, 0xc00b560f60, 0x15, 0xc00b560100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc0002fb5c8 sp=0xc0002fb590 pc=0x5dd622
encoding/json.interfaceEncoder(0xc00826c0e0, 0x1675600, 0xc00b4fd800, 0x194, 0x1670100)
        /usr/local/go/src/encoding/json/encode.go:620 +0xad fp=0xc0002fb610 sp=0xc0002fb5c8 pc=0x5df94d
encoding/json.arrayEncoder.encode(0x194afe8, 0xc00826c0e0, 0x15e05a0, 0xc00b590dc0, 0x97, 0x5d0100)
        /usr/local/go/src/encoding/json/encode.go:787 +0xd6 fp=0xc0002fb668 sp=0xc0002fb610 pc=0x5e10f6
encoding/json.arrayEncoder.encode-fm(0xc00826c0e0, 0x15e05a0, 0xc00b590dc0, 0x97, 0xc000140100)
        /usr/local/go/src/encoding/json/encode.go:780 +0x64 fp=0xc0002fb6a8 sp=0xc0002fb668 pc=0x5ebef4
encoding/json.sliceEncoder.encode(0xc00026cd30, 0xc00826c0e0, 0x15e05a0, 0xc00b590dc0, 0x97, 0x15e0100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x90 fp=0xc0002fb6f0 sp=0xc0002fb6a8 pc=0x5e0d60
encoding/json.sliceEncoder.encode-fm(0xc00826c0e0, 0x15e05a0, 0xc00b590dc0, 0x97, 0xc00b590100)
        /usr/local/go/src/encoding/json/encode.go:756 +0x64 fp=0xc0002fb730 sp=0xc0002fb6f0 pc=0x5ebe74
encoding/json.(*encodeState).reflectValue(0xc00826c0e0, 0x15e05a0, 0xc00b590dc0, 0x97, 0xc00b590100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc0002fb768 sp=0xc0002fb730 pc=0x5dd622
encoding/json.interfaceEncoder(0xc00826c0e0, 0x1675600, 0xc00bea67d0, 0x94, 0xc00bdf0100)
        /usr/local/go/src/encoding/json/encode.go:620 +0xad fp=0xc0002fb7b0 sp=0xc0002fb768 pc=0x5df94d
encoding/json.mapEncoder.encode(0x194afe8, 0xc00826c0e0, 0x167c680, 0xc00a535620, 0x15, 0x1670100)
        /usr/local/go/src/encoding/json/encode.go:702 +0x352 fp=0xc0002fb8f8 sp=0xc0002fb7b0 pc=0x5e03d2
encoding/json.mapEncoder.encode-fm(0xc00826c0e0, 0x167c680, 0xc00a535620, 0x15, 0xc00a530100)
        /usr/local/go/src/encoding/json/encode.go:678 +0x64 fp=0xc0002fb938 sp=0xc0002fb8f8 pc=0x5ebdf4
encoding/json.(*encodeState).reflectValue(0xc00826c0e0, 0x167c680, 0xc00a535620, 0x15, 0xc00a530100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc0002fb970 sp=0xc0002fb938 pc=0x5dd622
encoding/json.interfaceEncoder(0xc00826c0e0, 0x1675600, 0xc00bdf58c0, 0x94, 0xc00bdf0100)
        /usr/local/go/src/encoding/json/encode.go:620 +0xad fp=0xc0002fb9b8 sp=0xc0002fb970 pc=0x5df94d
encoding/json.mapEncoder.encode(0x194afe8, 0xc00826c0e0, 0x167c680, 0xc00a5355f0, 0x15, 0x1670100)
        /usr/local/go/src/encoding/json/encode.go:702 +0x352 fp=0xc0002fbb00 sp=0xc0002fb9b8 pc=0x5e03d2
encoding/json.mapEncoder.encode-fm(0xc00826c0e0, 0x167c680, 0xc00a5355f0, 0x15, 0xc0002f0100)
        /usr/local/go/src/encoding/json/encode.go:678 +0x64 fp=0xc0002fbb40 sp=0xc0002fbb00 pc=0x5ebdf4
encoding/json.(*encodeState).reflectValue(0xc00826c0e0, 0x167c680, 0xc00a5355f0, 0x15, 0x1710100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc0002fbb78 sp=0xc0002fbb40 pc=0x5dd622
encoding/json.(*encodeState).marshal(0xc00826c0e0, 0x167c680, 0xc00a5355f0, 0x1670100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:306 +0xee fp=0xc0002fbbc0 sp=0xc0002fbb78 pc=0x5dd0ce
encoding/json.Marshal(0x167c680, 0xc00a5355f0, 0xc0002fbb68, 0x167c680, 0xc00a5355f0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:160 +0x52 fp=0xc0002fbc38 sp=0xc0002fbbc0 pc=0x5dc6f2
k8s.io/helm/vendor/github.com/ghodss/yaml.yamlToJSON(0xc002e00000, 0x508191, 0x7ffe00, 0xc0002fbd40, 0x194d4a0, 0x17eeb20, 0x46e001, 0x1000001627fe0, 0x38, 0x48)
        /go/src/k8s.io/helm/vendor/github.com/ghodss/yaml/yaml.go:123 +0xff fp=0xc0002fbc88 sp=0xc0002fbc38 pc=0x66492f
k8s.io/helm/vendor/github.com/ghodss/yaml.Unmarshal(0xc002e00000, 0x508191, 0x7ffe00, 0x1745840, 0xc000722000, 0x0, 0x0, 0x0, 0x58a56d, 0xc0000e4e48)
        /go/src/k8s.io/helm/vendor/github.com/ghodss/yaml/yaml.go:37 +0x10e fp=0xc0002fbd68 sp=0xc0002fbc88 pc=0x6641de
k8s.io/helm/pkg/repo.loadIndex(0xc002e00000, 0x508191, 0x7ffe00, 0xc002e00000, 0x508191, 0x7ffe00)
        /go/src/k8s.io/helm/pkg/repo/index.go:285 +0x96 fp=0xc0002fbe18 sp=0xc0002fbd68 pc=0x9b6856
k8s.io/helm/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc00021c0c0, 0xc000319110, 0x25, 0x2, 0x2)
        /go/src/k8s.io/helm/pkg/repo/chartrepo.go:134 +0x215 fp=0xc0002fbec8 sp=0xc0002fbe18 pc=0x9b3205
main.updateCharts.func1(0xc0002f4ad0, 0xc0002f4ac8, 0x1af7720, 0xc00000e018, 0xc00003eb60, 0x14, 0xc0002f4ac0, 0xc00021c0c0)
        /go/src/k8s.io/helm/cmd/helm/repo_update.go:109 +0xfe fp=0xc0002fbfa0 sp=0xc0002fbec8 pc=0x1514a2e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0002fbfa8 sp=0xc0002fbfa0 pc=0x459221
created by main.updateCharts
        /go/src/k8s.io/helm/cmd/helm/repo_update.go:101 +0x182

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0002f4ad8)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0002f4ad0)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
main.updateCharts(0xc00021c280, 0x5, 0x8, 0x1af7720, 0xc00000e018, 0xc00003eb60, 0x14, 0x0, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/repo_update.go:122 +0x1af
main.(*repoUpdateCmd).run(0xc0004394a0, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/repo_update.go:89 +0x2c8
main.newRepoUpdateCmd.func1(0xc00030e780, 0x2c0de18, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/repo_update.go:62 +0x49
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc00030e780, 0x2c0de18, 0x0, 0x0, 0xc00030e780, 0x2c0de18)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:762 +0x465
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000419680, 0x2, 0x2, 0xc000419680)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /go/src/k8s.io/helm/cmd/helm/helm.go:171 +0x7a

goroutine 5 [chan receive]:
k8s.io/helm/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x2bea5a0)
        /go/src/k8s.io/helm/vendor/k8s.io/klog/klog.go:943 +0x8b
created by k8s.io/helm/vendor/k8s.io/klog.init.0
        /go/src/k8s.io/helm/vendor/k8s.io/klog/klog.go:403 +0x6c

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 33 [running]:
        goroutine running on other thread; stack unavailable
created by main.updateCharts
        /go/src/k8s.io/helm/cmd/helm/repo_update.go:101 +0x182

goroutine 52 [IO wait]:
internal/poll.runtime_pollWait(0x7fd0b1830d68, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00040b398, 0x72, 0xe200, 0xe2e2, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00040b380, 0xc00057a000, 0xe2e2, 0xe2e2, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00040b380, 0xc00057a000, 0xe2e2, 0xe2e2, 0x203000, 0x420b65, 0xc000771900)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000158110, 0xc00057a000, 0xe2e2, 0xe2e2, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000771900, 0xc00057a000, 0xe2e2, 0xe2e2, 0xc0005cf200, 0x3, 0xc0000e39e0)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00014f058, 0x1af5100, 0xc000771900, 0x409b85, 0x16ce280, 0x1830a00)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00014ee00, 0x1af7300, 0xc000158110, 0x5, 0xc000158110, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00014ee00, 0x1951900, 0xc00014ef38, 0xc0000e3c68)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00014ee00, 0xc0004e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc000083a40, 0xc0007a0738, 0x9, 0x9, 0xc00014ee00, 0xc0004b3000, 0x11)
        /usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x1af4ee0, 0xc000083a40, 0xc0007a0738, 0x9, 0x9, 0x9, 0x1000, 0x3, 0xc000050570)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0007a0738, 0x9, 0x9, 0x1af4ee0, 0xc000083a40, 0x0, 0x0, 0xc000bfc000, 0xc0000e3dd0)
        /usr/local/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc0007a0700, 0xc000bfc000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc0000e3fb8, 0x1951260, 0xc0004797b8)
        /usr/local/go/src/net/http/h2_bundle.go:8102 +0x8f
net/http.(*http2ClientConn).readLoop(0xc00015af00)
        /usr/local/go/src/net/http/h2_bundle.go:8030 +0x76
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:7093 +0x637

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0x7fd0b1830af8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00046bc18, 0x72, 0xdd00, 0xdd58, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00046bc00, 0xc001130000, 0xdd58, 0xdd58, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00046bc00, 0xc001130000, 0xdd58, 0xdd58, 0x203000, 0x420b65, 0xc0007a2640)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000158118, 0xc001130000, 0xdd58, 0xdd58, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0007a2640, 0xc001130000, 0xdd58, 0xdd58, 0xc0005bc780, 0x3, 0xc0000e29e0)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00014f3d8, 0x1af5100, 0xc0007a2640, 0x409b85, 0x16ce280, 0x1830a00)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00014f180, 0x1af7300, 0xc000158118, 0x5, 0xc000158118, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00014f180, 0x1951900, 0xc00014f2b8, 0xc0000e2c68)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00014f180, 0xc0004b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc000083740, 0xc0007a0578, 0x9, 0x9, 0xc00014f180, 0xc000579000, 0x11)
        /usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x1af4ee0, 0xc000083740, 0xc0007a0578, 0x9, 0x9, 0x9, 0x1000, 0x3, 0xc000050570)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0007a0578, 0x9, 0x9, 0x1af4ee0, 0xc000083740, 0x0, 0x0, 0xc000b7e020, 0xc0000e2dd0)
        /usr/local/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc0007a0540, 0xc000b7e020, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc0000e2fb8, 0x1951260, 0xc00005dfb8)
        /usr/local/go/src/net/http/h2_bundle.go:8102 +0x8f
net/http.(*http2ClientConn).readLoop(0xc00015ad80)
        /usr/local/go/src/net/http/h2_bundle.go:8030 +0x76
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:7093 +0x637

goroutine 66 [IO wait]:
internal/poll.runtime_pollWait(0x7fd0b1830c98, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00046b818, 0x72, 0x7d00, 0x7d96, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00046b800, 0xc000570000, 0x7d96, 0x7d96, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00046b800, 0xc000570000, 0x7d96, 0x7d96, 0x203000, 0x3d6c, 0xc0003ba180)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e0b0, 0xc000570000, 0x7d96, 0x7d96, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0008aa660, 0xc000570000, 0x7d96, 0x7d96, 0x200, 0x7fd0b1a8bfff, 0xc0005cd9e0)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0003ba258, 0x1af5100, 0xc0008aa660, 0x409b85, 0x16ce280, 0x1830a00)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0003ba000, 0x1af7300, 0xc00000e0b0, 0x5, 0xc00000e0b0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0003ba000, 0x1951900, 0xc0003ba138, 0xc0005cdd58)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0003ba000, 0xc0004fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc000152ae0, 0xc000806118, 0x9, 0x9, 0x4063f4, 0xc000152b40, 0xc0005cdd58)
        /usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x1af4ee0, 0xc000152ae0, 0xc000806118, 0x9, 0x9, 0x9, 0x1af5340, 0xc00099c3e0, 0xc00004c050)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc000806118, 0x9, 0x9, 0x1af4ee0, 0xc000152ae0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc0008060e0, 0xc00075ab70, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc0005cdfb8, 0x1951260, 0xc0004797b8)
        /usr/local/go/src/net/http/h2_bundle.go:8102 +0x8f
net/http.(*http2ClientConn).readLoop(0xc0005bc900)
        /usr/local/go/src/net/http/h2_bundle.go:8030 +0x76
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:7093 +0x637

goroutine 32 [IO wait]:
internal/poll.runtime_pollWait(0x7fd0b1830bc8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00046b618, 0x72, 0x11f00, 0x11f76, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00046b600, 0xc000856000, 0x11f76, 0x11f76, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00046b600, 0xc000856000, 0x11f76, 0x11f76, 0x203000, 0x420b65, 0xc000813080)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000158108, 0xc000856000, 0x11f76, 0x11f76, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000813080, 0xc000856000, 0x11f76, 0x11f76, 0xd, 0xc00085600d, 0xc0000e69e0)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00014e258, 0x1af5100, 0xc000813080, 0x409b85, 0x16ce280, 0x1830a00)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00014e000, 0x1af7300, 0xc000158108, 0x5, 0xc000158108, 0xc00004e000)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00014e000, 0x1951900, 0xc00014e138, 0xc0000e6d58)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00014e000, 0xc000578000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc0000832c0, 0xc0007a0498, 0x9, 0x9, 0x4063f4, 0xc000083320, 0xc0000e6d58)
        /usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x1af4ee0, 0xc0000832c0, 0xc0007a0498, 0x9, 0x9, 0x9, 0x1af5340, 0xc0006e4000, 0xc00004c050)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0007a0498, 0x9, 0x9, 0x1af4ee0, 0xc0000832c0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc0007a0460, 0xc000965830, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc0000e6fb8, 0x1951260, 0xc00005dfb8)
        /usr/local/go/src/net/http/h2_bundle.go:8102 +0x8f
net/http.(*http2ClientConn).readLoop(0xc00015a480)
        /usr/local/go/src/net/http/h2_bundle.go:8030 +0x76
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:7093 +0x637'
FATAL: ingress init failed: deployments.apps "jxing-nginx-ingress-controller" not found

### Expected behavior
jx install should complete successfully.

### Actual behavior
jx install fails with error "FATAL: ingress init failed: deployments.apps "jxing-nginx-ingress-controller" not found"

### Jx version
2.0.597
2.0.933

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

**Comment by daveconde** [comment]
What OS are you using and how much free memory is available when running jx?

**Comment by alfsender** [comment]
Bastion host where I am running "jx install" is t3.nano instance, which has 0.5GB memory and 2vCPU. But I have one worker node in my cluster which is m5.xlarge 4vCPU & 16GB memory. Both are using amazon linux ami.

**Comment by alfsender** [comment]
It worked after I increased size of my bastion host machine. Thank you all help @daveconde.
