### ISSUE TITLE
jx boot throws up on <.Requirements.repository> 

### ISSUE THREAD

**Issue by rudolph9** [jenkins-x/jx#6011]
### Summary 
The follow error is introduced by https://github.com/jenkins-x/jenkins-x-boot-config/releases/tag/v1.0.39

```
$ jx boot
.
.
.
? A local Jenkins X versions repository already exists, pulling the latest: Yes                                    
error: generating values.yaml for tree from /tmp/jx-helm-apply-609452780/env: failed to execute Secrets template: /tmp/jx-helm-apply-609452780/env/bucketrepo/values.tmpl.yaml: template: values.tmpl.yaml:1:23: executing "values.tmpl.yaml" at <.Requirements.repository>: map has no entry for key "repository"
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

### Steps to reproduce the behavior

`jx boot` with environment-clustername-dev repo based on https://github.com/jenkins-x/jenkins-x-boot-config/releases/tag/v1.0.39

### Expected behavior
No error

### Actual behavior

The error described in the summary

### Jx version

The output of `jx version` is:

```
$ jx --version
2.0.937
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

gke create with `jx create cluster gke`
### Operating system / Environment

Ubuntu 18.04

**Comment by abayer** [comment]
Ha! We hit this ourselves in our version stream tests last night, and I got a fix up - it should get merged today. Sorry for the hassle!

**Comment by sfynx** [comment]
I still get this error unless I explicitly add `repository: nexus` in my requirements file (it is not by default in the boot repo).

**Comment by abayer** [comment]
Yeah, it's fixed in the latest pre-release `jx` binary, but that won't get promoted to released until our comprehensive version stream tests run tonight. So if you update your `jx` binary tomorrow, you should be good. Sorry again for the inconvenience!
