### ISSUE TITLE
Helm version too new on macOS when installing Jenkins X into cluster

### ISSUE THREAD

**Issue by sfynx** [jenkins-x/jx#6018]
### Summary 

When using `jx boot` on a fresh GKE cluster I get this error:

```
error: package helm is using version 2.15.2+g8dce272 which is too new. The version stream requires a version earlier than 2.15.0
```

### Steps to reproduce the behavior

- Make sure you have no Helm installed
- Run `jx create cluster gke` (probably also happens with other clusters)
- When asked to install dependencies, select `helm`
- Optionally `jx boot` if you used `--skip-installation` at the cluster creation command.

### Expected behavior

Helm works as expected

### Actual behavior

It is reported that the Helm version is too new.

I suspect this happens because the `kubernetes-helm` brew package is quite new, and this now breaks fresh installations.

### Jx version

v2.0.941 on macOS installed through Homebrew. `jx version` not yet available because Jenkins X is not yet installed in cluster.

### Jenkins type

Not chosen, Jenkins X is not yet installed in cluster.

### Kubernetes cluster

GKE, using `jx create cluster gke` command

### Operating system / Environment

macOS 10.14.6

**Comment by sfynx** [comment]
Ok, I see this is intended: https://github.com/jenkins-x/jenkins-x-versions/commit/a1358a229c6aab83f144ae19d05d80957fde9fd2

Would be nice if we can figure out a way to auto-install the latest 1.14 release in this case so nw installs do not break.

**Comment by mbakker2000** [comment]
I have the same issue OSX with in a minikube environment, is there a work around for this issue?

**Comment by sfynx** [comment]
> I have the same issue OSX with in a minikube environment, is there a work around for this issue?

You can simply install Helm 2.14.3 yourself and put it into your search path, e.g. by downloading their GitHub release directly: https://github.com/helm/helm/releases/tag/v2.14.3
Then `jx boot` will use that one and won't offer to to install it from another source.

Changing `jx boot` so that it downloads this specific Helm release this way would fix this issue.

**Comment by TonyNoble** [comment]
Reproduced on Ubuntu 18.  jx boot downloads a version of helm that is too new (2.16) to use on subsequent runs.
Worked around by manual install of helm 2.14.3 as above, but not particularly ideal.

**Comment by deanesmith** [comment]
This has been addressed here - https://github.com/deanesmith/jx/commit/88ac8f282908a89b8788ac390b220408682b44e9.  Helm 3 updates coming soon.
