### ISSUE TITLE
`jx step next-version` can not find correct chart

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#6025]
### Summary 

Seeing the same behavior in #2661 which the chart.yaml file does not get updated with the correct version, and therefore the helm release command fails.

I believe it is because we have three charts in our server project - `initdb-test`, `preview`, and `server`

The command `jx step next-version` incorrectly updates the version in `initdb-test` instead of `server` even when the `--dir ./charts/server` flag is provided.

### Steps to reproduce the behavior

Create a third chart in the charts folder that comes alphabetically before the preview and actual chart, then run `jx step next-version`

jx just bumps the first folder found instead of the folder that needs to be released

### Expected behavior

The correct chart.yaml file is updated so the chart can be released

### Actual behavior

the first folder found is updated instead of the one that needs to be

### Jx version

The output of `jx version` is:

```
~ jx version       
NAME               VERSION
jx                 2.0.923
Kubernetes cluster v1.13.9-gke.3
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0
Operating System   "Fedora release 30 (Thirty)"


verifying packages
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

terraform + jx boot

### Operating system / Environment

happens locally on fedora, on mac, and in build pod

**Comment by patrickleet** [comment]
ok - so, actually, I think this is because the project is actually named

`orgname_server` and the chart name is `server` because that was superfluous. Still I'd expect passing the `dir` flag to allow one to specify, which doesn't seem to be the case.

**Comment by patrickleet** [comment]
it does seem that it just grabs the first folder that isn't preview based on a few more tests

**Comment by patrickleet** [comment]
I fixed my issue by renaming `initdb-test- to `test-db-initializer`

**Comment by ccojocar** [comment]
See also https://github.com/jenkins-x/jx/issues/6076

**Comment by patrickleet** [comment]
Yea I looked it up in the source code out of curiosity - seems that it just uses glob to find `Chart.yaml`'s and then just matches the first one it finds that isn't `preview`

https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/step_tag.go#L273-L288

Was thinking more appropriate logic would be either:

1) instead of grabbing first one, keep an array of all matches

and then find the one that matches the project name

or

update all of the matches instead of just one - though this is less technically correct, it happens in CI and would have worked in my case without hurting anything

**Comment by patrickleet** [comment]
also, seems like the `--charts-dir` flag might have been an option as a workaround - I think I mistakenly tried `--dir` only
