### ISSUE TITLE
Implement clusters garbage collection for EKS BDD tests

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#6038]
### Summary 
Right now there's no cluster garbage collection for EKS so we can run BDD tests and clean them up when they finish / fail.

We should make use of the implementation for EKS from https://github.com/jenkins-x/jx/issues/5578 so we can start separating implementations by provider.

Acceptance Criteria

Have a way to garbage collect EKS cluster after BDD tests have run.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
label area/provider/aws

**Comment by deanesmith** [comment]
/area/provider/aws

**Comment by deanesmith** [comment]
/area/provider aws
