### ISSUE TITLE
use GitOps for the developer environment too

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#604]
internally we're using GitOps for our production CI/CD environment (see https://github.com/jenkins-x/cloud-environments/tree/master/env-jx-infra) and we use GitOps for the `Staging` and `Production` environments; but we don't yet do the same for the development environment.

The extra use of GPG keys and encrypted secrets make things a bit harder though; but we should try make it easy for folks to opt into GitOps for the development environment too.

Mostly its a simpler way to manage addons & secrets really: https://github.com/futuresimple/helm-secrets  everything else is in a chart or chart configuration (`values.yaml`) file.

**Comment by rawlingsj** [comment]
I wonder if the `gitSecrets.yaml`,  `adminSecrets.yaml` and `extraValues.yaml` should be added to a secret that we get, decrypt and use during `jx upgrade platform` too?  That way folks dont need to integrate with Vault or encrypted secrets in git repos?  

The cluster will then have all the initial config and secrets that was used to install first time, so upgrades can reuse them.  We could then build tooling that helps modify these secrets.

**Comment by jstrachan** [comment]
@rawlingsj great idea! I was wondering how we can make the GitOps for the development environment kinda painless really and something folks can incrementally adopt - so its easy to start out. That sounds good to me really!

**Comment by jstrachan** [comment]
along similar lines we should make the `jx install` / `jx create cluster ....` do a git pull in `~/.jx/cloud-environments` rather than deleting it - so folks can easily work of their own forks etc

**Comment by rawlingsj** [comment]
> along similar lines we should make the jx install / jx create cluster .... do a git pull in ~/.jx/cloud-environments rather than deleting it - so folks can easily work of their own forks etc

yeah on that - I've had issues if there's local uncommitted changes, so that's why I originally went with a clean `~/.jx/cloud-environments` to cut down folks running into issues during the install.  It might need to do more that a `git pull` and check for local uncommitted changes and `stash` / `unstash` maybe?

**Comment by jstrachan** [comment]
yeah; maybe we need a generic helper function `gitPullAndOptionallyStash` where we try to `git pull` and if that breaks with a conflict/error log a warning and give the user an option to stash their previous work or ignore the git pull error? (In batch mode we probably default to just ignore and log a warning?)

**Comment by jstrachan** [comment]
relates to https://github.com/jenkins-x/jx/issues/512

**Comment by jstrachan** [comment]
ideally we'd move to Configuration as Code plugin for Jenkins so that it can be completely configured in the `values.yaml` file in YAML which can then be stored in git etc #474

**Comment by jstrachan** [comment]
I guess this issue can be closed once the terraform stuff is working: https://github.com/jenkins-x/jx/issues/845

**Comment by jstrachan** [comment]
a few more thoughts on how this might look. 

We want to promote reusing the helm packaging and templating for the Jenkins X platform and extensions. So a git repo could look like...

```
extensions/
  someExtension/
    values.yaml - optional custom values to override
  anotherExtension/
    values.yaml - optional custom values to override
jenkins-x-platform/
    values.yaml - local configuration overrides
    flags.yaml - optional CLI arguments effectively passed into `jx install ....` maybe?
    templates/
       staging-env.yaml - the YAML of the staging environment
       production-env.yaml - the YAML of the production environment
```

Then some simple `jx step dev apply` or something would apply the `jenkins-x-platform` first (treating it a little special initially while we have the custom logic in `jx install ....` until we make it pure helm some day?) then iterate through all the extensions and apply them.

To be able to know what versions of each chart (platform + extensions) to use we could use `requirements.yaml` to list the app names, chart repo URL + version?

**Comment by rawlingsj** [comment]
Yeah this is what I had in mind and started chatting to @garethjevans about it this morning.  

I'm not totally sure yet on having 
```
    templates/
       staging-env.yaml - the YAML of the staging environment
       production-env.yaml - the YAML of the production environment
```
in the same git repo though, I was thinking they'd be in each individual environments git repo

**Comment by jstrachan** [comment]
@rawlingsj if the Staging `Environment` CRD is in another git repo, how does the platform know where it is to setup the webhooks? :)

**Comment by jstrachan** [comment]
the Dev environment contains CRDs like `GitService` and `Environment` so I figured all the CRDs in the dev environment would live in the dev git repo?

**Comment by rawlingsj** [comment]
ah that's the CRD, I read `staging-env.yaml` as the custom environment values.yaml!

so yes agree with all a that :)

**Comment by jstrachan** [comment]
btw am trying out generating a git repo for the dev environment which looks like the staging + production git repositories from a helm perspective - lets see how this goes...

**Comment by jstrachan** [comment]
this is mostly complete now - we just need to add support for the vault operator so we can store the `secrets.yaml` in Vault

**Comment by msvticket** [comment]
Today I've tried  `jx install  --no-tiller --prow --gitops --no-gitops-vault --provider=eks --namespace=core`. (`--no-gitops-vault` since I bumped into #2527.)

But it doesn't seem to work to combine Prow with GitOps. The namespaces are not created when Prow is installed. Of some reason Prow gets installed in namespace default. 

`Installing Prow into namespace default`

Then further along the installation fails with:

`error: creating the environments: failed to create staging environment in namespace core: failed to add repo deniedboarding/environment-ore-staging to Prow config in namespace core-staging: namespaces "core" not found`

**Comment by ccojocar** [comment]
A `gitops` mode is supported in the install command for dev environments, but It seems that the webhooks are not created after the dev environment installation.

**Comment by warrenbailey** [comment]
FIxed 

/close

**Comment by gazal-k** [comment]
Can the gitops option be added to an existing jenkins-x? I can only see the option in `jx create` or `jx install`
