### ISSUE TITLE
jx create addon cloudbees command gives invalid argument...

### ISSUE THREAD

**Issue by krunaladdweb** [jenkins-x/jx#6041]
### Summary 
jx create addon cloudbees
error: Invalid argument: cloudbees
Possible values: ambassador, anchore, flagger, gitea, grafana, istio, jx-build-templates, jx-prow, jx-sso-dex, jx-sso-operator, knative-build, kubeless, prometheus, tekton, vault-operator
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
If you’re trying to install the UI, follow the directions at https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/user-interface/

**Comment by deanesmith** [comment]
Hi @krunaladdweb, Is @abayer's answer satisfactory?  We have deprecated the 'cloudbees' addon in favor of the jx ui app.

**Comment by ccojocar** [comment]
This addon was removed from Jenkins X. You can use the `jx-app-ui` instead following these steps https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/user-interface/install. 

I am going to close this issue. Thanks!
