### ISSUE TITLE
jx import fails to import quickstart-made directory

### ISSUE THREAD

**Issue by zarbis** [jenkins-x/jx#6046]
### Summary 

`jx` fails to import directory created via `jx quickstart`.

### Steps to reproduce the behavior

0) create cluster and `jx boot` it.
1) create project via `jx quickstart` and verify that pipelines are running
2) tear down cluster and repeat step 0
3) try to `jx import` project from step 1

### Expected behavior
Project is imported into new installation of JX.

### Actual behavior
JX tries to create directories that already exist and fails:
```
$ jx import
WARNING: No username defined for the current Git server!
? Do you wish to use zarbis as the Git user name: Yes
trying to use draft pack: go
selected pack: /home/zarbis/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/go
WARNING: Failed to apply the build pack in 
/home/zarbis/github/zarbis/jx-quickstart due to mkdir 
/home/zarbis/github/zarbis/jx-quickstart/charts/preview: file exists
error: error renaming 
/home/zarbis/github/zarbis/jx-quickstart/charts/golang to 
/home/zarbis/github/zarbis/jx-quickstart/charts/jx-quickstart, 
failed to copy source dir 
/home/zarbis/github/zarbis/jx-quickstart/charts/golang to 
/home/zarbis/github/zarbis/jx-quickstart/charts/jx-quickstart: destination already exists
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.927
Kubernetes cluster v1.14.8-gke.2
kubectl            v1.16.2
helm client        Client: v2.15.1+gcf1de4f
git                2.20.1
Operating System   Ubuntu 19.10

```

### Jenkins type

Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

GKE cluster created via web console.

**Comment by zarbis** [comment]
If I remove `charts` directory and let jx do it's thing - it succeeds. Jx re-creates exactly the same chart directory (`git diff` is zero) and manages to import it.

**Comment by vfarcic** [comment]
@zarbis I had the same problem a few minutes ago. Removing `charts/golang` was enough. That directory shouldn't be there anyways.

**Comment by garethjevans** [comment]
Can you try using the `--no-draft` flag, this should stop attempting to create the Dockerfile & the helm charts dir.

**Comment by zarbis** [comment]
@garethjevans yep, `--no-draft` indeed works. Is it the intended way to re-import JX projects?
