### ISSUE TITLE
A short video demo would be very useful

### ISSUE THREAD

**Issue by karthikeaswaran** [jenkins-x/jx#6049]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @karthikeaswaran, can you be more specific?  What topic? @sharepointoscar

**Comment by sharepointoscar** [comment]
@karthikeaswaran have you checked out the Jenkins X YouTube Channel?  We have multiple playlists including a Tutorial Series at https://www.youtube.com/playlist?list=PLr_PmC4W69dIucoKAklFDC-WMW6o-EpNV

I also recommend you checkout https://jenkins-x.io/docs/getting-started/demos-talks-posts/

Please do tell what specifics you are looking for in a video tutorial.

**Comment by karthikeaswaran** [comment]
Ok. I haven't checked out these video tutorials. Let me take a look at it.

**Comment by deanesmith** [comment]
@karthikeaswaran, could you please close this issue if you are satisfied with the response?  Thank You.

**Comment by karthikeaswaran** [comment]
Thank you
