### ISSUE TITLE
Ensure output of git commands is in English

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#6052]
Currently, we have some git helper functions which rely on the textual output of some git error cases. See also issue #6051.

Ideally, these functions should be removed, but for now, we can make sure that invocations of git force the English locale.

See PR https://github.com/jenkins-x/jx/pull/5962

**Comment by abayer** [comment]
Hahaha, yeah, I hit this at one point because of a weird IntelliJ on Macs bug where git run from a test run through IntelliJ insisted on using the second language I had configured on the system, so everything came up in French for me. Good times.
