### ISSUE TITLE
Specify node size in AKS cluster

### ISSUE THREAD

**Issue by pnosovets-sc** [jenkins-x/jx#606]
Is it possible to specify VM size in 'jx create cluster aks' command? 
Default Standard DS1 v2 (1 vcpu, 3.5 GB memory) size is very limited.

**Comment by rajdavies** [comment]
You can resize the VMs for a resource group - would be good to be able to specify a default size for a resource group - though not clear from the docs if that is possible. As an Azure noob - any help greatly appreciated!

**Comment by tomconte** [comment]
You can specify the VM size to use for the AKS nodes using the `[--node-vm-size]` argument.

Reference: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

**Comment by tomconte** [comment]
I believe this issue was fixed by https://github.com/jenkins-x/jx/pull/863 and can be closed now!

**Comment by ccojocar** [comment]
This issued seems to be already fixed.
