### ISSUE TITLE
Boot upgrade from local to vault fails

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6066]
### Summary 

The process fails when trying to upgrade `jx` installation with `jx boot` by changing `secretStorage` from `local` to `vault`.

### Steps to reproduce the behavior

1. Install Jenkins X with `jx boot` and with `secretStorage` set to `local`.
2. Change `secretStorage` from `local` to `vault`
3. Re-run `jx boot`

### Expected behavior

The process works.

### Actual behavior

The process fails. 

The last few lines from the output:

```
Modified file /Users/vfarcic/code/environment-vfarcic-dev/env/Chart.yaml to set the chart to version 1
? A local Jenkins X versions repository already exists, pulling the latest: Yes
error: generating values.yaml for tree from /var/folders/73/94ypm_917397bvg1y3f7phkc0000gn/T/jx-helm-apply-875679917/env: failed to execute Secrets template: /var/folders/73/94ypm_917397bvg1y3f7phkc0000gn/T/jx-helm-apply-875679917/env/lighthouse/values.tmpl.yaml: template: values.tmpl.yaml:7:26: executing "values.tmpl.yaml" at <.Parameters.prow.hmacToken>: map has no entry for key "hmacToken"
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.974
Kubernetes cluster v1.14.7-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G1012
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

MacOS

**Comment by deanesmith** [comment]
@vfarcic we don't yet have the capabilities to support this change and likely won't until Feb/Mar 19 timeframe.

**Comment by deanesmith** [comment]
Capability now exists but need documentation.

**Comment by jiangytcn** [comment]
hi @deanesmith I have the similar request from local to external vault. however, I didn't find the docs about such migration, can you point me that ? thanks
