### ISSUE TITLE
extensions/v1beta1 deprecated in K8s 1.16

### ISSUE THREAD

**Issue by ginosubscriptions** [jenkins-x/jx#6068]
### Summary 
As per the article https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ apiVersion extensions/v1beta1 is deprecated (among others for K8s Deployment resources). Jenkins X seems to still use this with no easy (configurable) way to use the (correct) "apps/v1" apiVersion.

### Steps to reproduce the behavior
Just install jx (I used: jx create cluster) in a 1.16 (or higher) version of K8s. The install will fail with errors like:
unable to recognize "<some path>\\helm-template-workdir-525909041\\jenkins-x\\output\\namespaces\\jx\\jenkins-x-platform\\charts\\chartmuseum\\templates\\part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1".
And yes, I'm on Windows and working with minikube, but still, the fact remains that a Deployment resources now sits in the K8s's 'apps/v1' apiVersion.
You can work around this by updating the deployment YAML files and manually create the deployment resources (and than manually generate the ingress entries from the expose job.yaml). However, once installed, a command like 'jx get applications' will still fail, as (if I'm reading the code correctly) also seems to refer to the old beta1v1 apiVersion (cf: https://github.com/jenkins-x/jx/blob/master/pkg/cmd/get/get_applications.go).

### Expected behavior
On K8s 1.16 or higher.
Not failing install and creating all resources in the correct apiVersion (maybe depending on the K8s version), but also, once installed take, have the jx commands correctly take into account the 'apps/v1' apiVersion.

### Actual behavior
Not working on K8s 1.16 or higher.

### Jx version
The output of `jx version` is:
2.0.916

### Jenkins type
Classic Jenkins

### Kubernetes cluster
Minikube with jx create cluster minikube

### Operating system / Environment
Windows 10

**Comment by hervelemeur** [comment]
/remove-lifecycle rotten

Still an issue, many other issues on the same subject have been open since:
https://github.com/jenkins-x/jx/issues/6079
https://github.com/jenkins-x/jx/issues/6232
https://github.com/jenkins-x/jx/issues/6786
https://github.com/jenkins-x/jx/issues/6900
https://github.com/jenkins-x/jx/issues/6957

The workaround in #6232 and #5675 require to get access to the master node, which is impossible on AKS for example, and other providers.

Trying to determine where/in which repository the charts are "templated" from, does anyone have a hint?

**Comment by hervelemeur** [comment]
There is also https://github.com/jenkins-x/jx/issues/6358

The errors I still got:
```
unable to recognize "/var/folders/m4/ytp3wjnn1hlbrxt27d64jc3c0000gn/T/helm-template-workdir-455690984/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/m4/ytp3wjnn1hlbrxt27d64jc3c0000gn/T/helm-template-workdir-455690984/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/m4/ytp3wjnn1hlbrxt27d64jc3c0000gn/T/helm-template-workdir-455690984/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/m4/ytp3wjnn1hlbrxt27d64jc3c0000gn/T/helm-template-workdir-455690984/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

**Comment by ankitm123** [comment]
I will take a look and make a PR to fix it.

**Comment by zzguang520** [comment]
Same issues here, 
`unable to recognize "/tmp/helm-template-workdir-810386484/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-810386484/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-810386484/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-810386484/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'`

`jx version
NAME               VERSION
jx                 2.1.10
jenkins x platform 2.0.2171
Kubernetes cluster v1.18.1
kubectl            v1.16.9
helm client        2.16.6
git                2.18.4
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"


verifying packages`

have tried to add "--runtime-config=apps/v1beta1=true,extensions/v1beta1/deployments=true
" to /etc/kubernetes/manifests/kube-apiserver.yaml in k8s master, but still same issues

**Comment by jiangytcn** [comment]
@zzguang520 I don't have the jx environment at hand, but I think its some sub components issue other than the `jx` itself.  one workaround for this is making your own customization like I did in http://www.ystacks.com/2020/01/01/Jenkins-X-Development-101/

**Comment by zzguang520** [comment]
> @zzguang520 I don't have the jx environment at hand, but I think its some sub components issue other than the `jx` itself. one workaround for this is making your own customization like I did in http://www.ystacks.com/2020/01/01/Jenkins-X-Development-101/

@jiangytcn The k8s version is too high, reduce it then will work

**Comment by ankitm123** [comment]
This should be working now.

/close
