### ISSUE TITLE
JX Boot errors when GitHub owner name contains capital letters

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx#6070]
### Summary 
Adding Jenkins X to cluster with `jx boot` (using latest CloudBees Jenkins X Distribution) errors due to `a DNS-1123 subdomain must consist of lower case alphanumeric characters`

### Steps to reproduce the behavior
Create new Kubernetes cluster;
`jx profile cloudbees`;
`jx boot`;
set `Git Owner` to a GitHub org account, the name of which contains capital letters
### Expected behavior
Jenkins X added to cluster.
### Actual behavior
Errors:
<img width="1631" alt="Screenshot 2019-11-11 at 15 19 11" src="https://user-images.githubusercontent.com/15032115/68598591-06455000-0497-11ea-9510-82d70edc4d26.png">

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.974
Kubernetes cluster v1.13.11-gke.9
kubectl            v1.15.3
helm client        Client: v2.14.1+g5270352
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE
`jx create cluster gke --skip-installation`

### Operating system / Environment
Mac OS

**Comment by MarckK** [comment]
Note, just to add that same failure, for the same reasons when using latest version of jx.

Steps to reproduce:
Create new Kubernetes cluster;
`jx boot`;
set `Git Owner` to a GitHub org account, the name of which contains capital letters

Errors with:
<img width="1635" alt="Screenshot 2019-11-11 at 19 00 08" src="https://user-images.githubusercontent.com/15032115/68612998-add17b00-04b5-11ea-8250-040d7bb3991c.png">

The output of jx version is:
```
NAME               VERSION
jx                 2.0.974
Kubernetes cluster v1.13.11-gke.9
kubectl            v1.15.3
helm client        Client: v2.14.1+g5270352
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F132
```

**Comment by deanesmith** [comment]
@mrageh, this would be great to investigate.

**Comment by abayer** [comment]
I fixed this a few weeks ago and didn't even realize this issue existed. =)
