### ISSUE TITLE
Support a force option for jx step tag

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#6071]
### Summary 

`jx step tag` fails if a tag already exists. Support force pushing the tag.

**Comment by hferentschik** [comment]
Is that really such a good idea? Will that not cause trouble for people who already have pulled the old tags?

**Comment by daveconde** [comment]
My need was to be able to re-push a tag for a failed build, for now I have removed the need by always generating a unique build number. Closing this out :)
