### ISSUE TITLE
`jx step next-version` increments the version of an unrelated helm chart in the repository

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#6076]
### Summary 

It seems that the meta-pipeline `step-create-tekton-crds` increase the version of an application unrelated helm chart from a project repository when running the release pipeline. This chart is only used for testing purposes and is not the application related chart. 

It is even located in `test-resources/helm/` folder not `charts`.

See the logs:

```
Showing logs for build jenkins-x/jx-release-version/master #2 release stage meta-pipeline and container step-create-tekton-crds
? A local Jenkins X versions repository already exists, pulling the latest: Yes
running command: jx step next-version --use-git-tag-only --tag
created new version: 1.0.19 and written to file: ./VERSION
Updating chart version in test-resources/helm/Chart.yaml to 1.0.19
Tag v1.0.19 created and pushed to remote origin
```

This chart should be skipped from version updates. `jx` should only increase the version of the charts placed into the `./charts` folder.  

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Awaiting 2020 upgrqde of meta pipeline @abayer

**Comment by abayer** [comment]
@deanesmith Nope, this is unrelated to Tekton. It’s an issue with `jx step next-version`.

**Comment by deanesmith** [comment]
Indeed, but some discussion has ensued ( @hferentschik ) that this Tekton update would help address the matter.
