### ISSUE TITLE
Increase default cluster size for GKE

### ISSUE THREAD

**Issue by schottsfired** [jenkins-x/jx#608]
I've had a "vanilla" jx cluster running on GKE for about 2 weeks now, and am still using the sample(s) created by ```jx create spring boot```. A few commits have been made, a few PRs have been built, and unfortunately the cluster has become slow and unresponsive.

I've traced down a maven agent that fails to start due to ```Waiting for Pod to be scheduled (31/100): maven-25z2f```, and the output of ```k describe po maven-25z2f -n jx``` is ```No nodes are available that match all of the predicates: Insufficient cpu (3).```.

So, what I'm thinking is that to prevent this from happening in the future, we could bump up the default instance size suggested by ```jx create cluster gke```.

Thanks for listening.

**Comment by rawlingsj** [comment]
I've not tried the auto scaling yet mind, worth a go!  Wonder if you can enable it on the existing cluster in the GKE console https://console.cloud.google.com/kubernetes/list ?

**Comment by schottsfired** [comment]
Great suggestion @rawlingsj - I'll give it a try and report my findings. After posting this issue and hunting down where the default is set in code, I was thinking to myself.. "why not just increase the number of nodes?" :-)

**Comment by rawlingsj** [comment]
Ok great, good luck and let us know :)  If it works we can probably enable it by default via the CLI with flag to disable it.

**Comment by schottsfired** [comment]
Things are working much better with autoscaling enabled and max nodes set at 5. I was quickly scaled up to 4 nodes after submitting a PR on the demo repo, then up to 5 during promotions to staging & production. While typing this, the cluster scaled down to 4, and I expect it to arrive at the minimum (3) in the next few minutes.

**Comment by schottsfired** [comment]
Deleting preview environments also should help.. I had a few (~4-6) lingering around when I hit the original issue.
