### ISSUE TITLE
Override dnsPolicy / dnsConfig for step in jenkins-x.yml

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#6080]
### Summary 

It would be useful to be able to support dnsPolicy / dnsConfig on a pod level for stages (perhaps in the `options` attribute. 

This would allow for cluster dns to be overriden in order to not use ClusterFirst. This would be especially useful when running KIND tests using Jenkins X.

**Comment by deanesmith** [comment]
@abayer, FYI, it is suggested newer versions of Tekton could help better support this sort of enhancement.  WDYT?

**Comment by hferentschik** [comment]
@axsaucedo, thanks for the issue. Could you please expand on this a bit explaining what you try to achieve. I am not quite sure I am following.

**Comment by axsaucedo** [comment]
@hferentschik I am currently using KIND to run end to end tests, and ran into a few issues. Currently the best practices when running KIND tests in a cluster it's advised to set the networking accordintly (as per https://github.com/kubernetes-sigs/kind/issues/303), however this requires an override of the `dnsPolicy` and `dnsConfig` accordingly (which is why this request then came in as I couldn't do it in the jx pipeline definition).
