### ISSUE TITLE
Explain the purpose of each pod that gets created on installation in docs

### ISSUE THREAD

**Issue by kpritam** [jenkins-x/jx#609]
After jx installation, i could see following pods running but not sure why some of the pods are there .

It would be great if explanation of each pod (whats it for) is added in the docs.

```
NAMESPACE     NAME                                            READY     STATUS              RESTARTS   AGE
jx            jenkins-58bb76cd94-fbk5l                        1/1       Running             0          1h
jx            jenkins-x-chartmuseum-7b95b777b-gspcg           1/1       Running             0          1h
jx            jenkins-x-docker-registry-6786bc55b7-pls49      1/1       Running             0          1h
jx            jenkins-x-heapster-96bd95dcf-zw45f              2/2       Running             0          1h
jx            jenkins-x-mongodb-6c84f866dc-qsvmx              1/1       Running             0          1h
jx            jenkins-x-monocular-api-5f9f84ff59-29sql        1/1       Running             1          1h
jx            jenkins-x-monocular-prerender-6d8897856-fj6x2   1/1       Running             0          1h
jx            jenkins-x-monocular-ui-69b4b898c4-hdqmm         1/1       Running             0          1h
jx            jenkins-x-nexus-7fbd9c8f4b-sfbxc                1/1       Running             0          1h
```

**Comment by rawlingsj** [comment]
Agreed.  We're in the process of doing exactly this in a blog which should go out this week, we'll also reuse parts and improve our docs once published.

**Comment by rawlingsj** [comment]
FWIW this is part of the blog which hopefully helps for now:

In the dev environment we have installed a number of core applications we believe are required at a minimum to start folks off with CI/CD on Kubernetes. We can easily add to these core apps using Jenkins X addons but for now lets focus on the core apps. Jenkins X comes with configuration that wires these services together meaning everything works together straight away. This dramatically reduces the time to get started with Kubernetes as all the passwords, environment variables and config files are all setup up to work with each other.

1. __Jenkins__  — provides both CI and CD automation. There is an effort to decompose Jenkins over time to become more cloud native and make use of Kubernetes concepts around CRDs, storage and scaling for example.
2. __Nexus__ — acts as a dependency cache for Nodejs and Java applications to dramatically improve build times. After an initial build of a SpringBoot application the build time is reduced from 12 mins to 4. We have not yet but intend to demonstrate swapping this with Artifactory soon.
3. __Docker registry__  — an in cluster docker registry where our pipelines push application images, we will soon switch to using native cloud provider registries such as Google Container Registry, Azure Container Registry or Amazon Elastic Container Registry (ECR) for example.
4. __Chartmuseum__ — a registry for publishing Helm charts
5. __Monocular__  — a UI used for discovering and running Helm charts

**Comment by jstrachan** [comment]
@rawlingsj we should probably pop that somewhere in the docs as a markdown file here somewhere: https://github.com/jenkins-x/jx-docs/tree/master/content

**Comment by jstrachan** [comment]
I've added the above content to an Architecture section of the website and tried to add a little more detail. 
http://jenkins-x.io/architecture/components/

Would be good to link to your blogs too ;)
