### ISSUE TITLE
jx get application needs to return user applications not Kuberenetes deployments

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#6099]
ATM, `jx get application` returns Kubernetes deployments per environment. These are not "applications" in the sense of its new definition. 

What should be returned are the users applications configured in Jenkins X. 

Currently this is determined by what is configured in Prow, but the aim is to have a better, more direct way to determine applications. 

For example, we already have a `SourceRepository` CRD instance created for each imported repository. However, SourceRepository instances are also created for things like environment repositories. We need to be able to differentiate between different type of SourceRepositories in this case.

**Comment by hferentschik** [comment]
relates to #6103

**Comment by mauromorales** [comment]
`SourceRepositories` have a function to check if they are env repos: https://github.com/jenkins-x/jx/blob/f7599d222133b9826b06c1a0de3e68370793c2aa/pkg/kube/sourcerepositories.go#L180
