### ISSUE TITLE
Extend SourceRespository CRD with a repository type attribute

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#6103]
The idea is to differentiate between for example environment source repositories and application source repositories. 

This would make it simpler to filter source repositories. 

An alternative would be to create a new Application CRD which in turn contains/references a SourceRepository. This might be a better option in case we can think of additional attributes which differentiate an Application from a SourceRepository. Another advantage might be to give the user more clarity on Jenkins X data model. High level concepts like an "application" would get a matching CRD representation.

@pmuir, @jstrachan, @ccojocar - WDYT?

Notes:
Being able to distinguish between the 3 types of objects relevant to the discussion, then only handle "Applications".
- Environments
- Apps/Addons (but don't worry about this right now)
- Applications

**Comment by ccojocar** [comment]
I think `Type` sounds good, maybe `ContentType` seems more clear looking at the existing fields of the CRD., because `Type` alone makes me think that is `git`.
