### ISSUE TITLE
After import master build fails because of missing make target

### ISSUE THREAD

**Issue by seubert** [jenkins-x/jx#611]
I imported a Go project which successfully added a `charts` directory and `Jenkinsfile`, but the Jenkins pipeline failed because it was missing the `make` target for `tag`. It's unclear to me what step I missed or what I need to manually resolve at this point.

**Comment by rawlingsj** [comment]
I wonder if there was an issue with the search and replace code in jx.  Can you copy or link to the Jenkinsfile that was added?

**Comment by seubert** [comment]
@rawlingsj 
[Jenkinsfile](https://github.com/jenkins-x/jx/files/1896180/Jenkinsfile.txt)

**Comment by rawlingsj** [comment]
Ah yes I can see that the placeholder replacement seems to have failed for some reason.  There are multiple places where the git org and repo name should have been replaced.  Are you using Github?  Is there anything odd about the steps you used to create it?  Just `jx create quickstart` and select golang?

I can use a gist and point to all the places you can edit the Jenkinsfile to add in the missing values but I'd still like to know why this has happened.  I'll also try a quickstart in the morning to see if I can recreate it.

The Git organisation name
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L6

The Git repository name
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L8

These need to be replaced to include the Git org and repo name using the pattern
`/home/jenkins/go/src/YOUR_GIT_ORG_NAME/YOUR_GIT_REPO_NAME/beacon-people`
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L25
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L33
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L47
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L52
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L60
https://gist.github.com/rawlingsj/987bfa775efc2556f5b1c839fa3b0578#file-gistfile1-txt-L75

**Comment by rawlingsj** [comment]
I just recreated the error, will work on a fix.

**Comment by rawlingsj** [comment]
@seubert thanks for raising the issue, the fix will be available in 1.1.68 which should be available in around half an hour.

**Comment by jstrachan** [comment]
@seubert ah, looks like its getting the 2 remote URLs confused - though it looks like it did try to treat the fork differently:
```
No branch pattern specified and this repository appears to be a fork so defaulting the branch patterns to run CI / CD on to: master```
```
I wonder if you clone your fork and do `jx import` inside the dir of the `git clone` it works any better? It could just be a gremlin in the `--url` handling code maybe? If so lets move this to a separate issue?

**Comment by seubert** [comment]
I'll give that a try and report back.

**Comment by seubert** [comment]
Hmm, doing more investigation and I'm even more confused than I was before. After doing `jx import --url https://github.com/seubert/beacon-people.git` in my `$GOPATH/src/github.com/seubert/beacon-people` directory I have a `beacon-people1` directory at the root of the repo that is untracked by git and has a different Jenkinsfile where `ORG` and `GIT_PROVIDER` are still wrong.
