### ISSUE TITLE
jx step helm apply can result in a full removal of the chart if the helm pre-upgrade hook fails

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#6121]
Requires investigation.

To reproduce the issue, make a hook that fails.

**Comment by deanesmith** [comment]
@pmuir, @ccojocar, any idea what the solution would entail?

**Comment by daveconde** [comment]
First step here is to attempt to reproduce the issue to better understand the cause, initial thinking is that it is related to multiple runs of the dev env release pipeline at the same time.
