### ISSUE TITLE
jx sync - ksync init no longer working after ksync org change

### ISSUE THREAD

**Issue by markus512** [jenkins-x/jx#6123]
The following code in https://github.com/jenkins-x/jx/blob/7335c1680bdb98c3294d0107eba02d04842e32ba/pkg/cmd/sync/sync.go

// Deal with https://github.com/vapor-ware/ksync/issues/218
err = o.RunCommandInteractive(true, "ksync", "init", "--upgrade", "--image",
	fmt.Sprintf("vaporio/ksync:%s", version))

should be replaced with:
err = o.RunCommandInteractive(true, "ksync", "init", "--upgrade")

as vaporio/ksync is now ksync/ksync and image version is no longer the same as ksync release version (release 0.4.0 for example has this corresponding image: ksync/ksync:git-dcb80e9)

**Comment by ankitm123** [comment]
The problem with that approach is that if ksync exists already, then there will be no way to download the same version of ksync for the docker image. I have the fix, just writing some tests, will open the PR soon.
