### ISSUE TITLE
`jx edit env ENV_NAME --remote=false` does not clear previous cluster url value.

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#6127]
### Summary 
If a user has attempted to set up Multi-Cluster environment using: `jx edit env staging --remote=true --cluster=MY_CLUSTER_IP`, the cluster value will be correctly set; however, running `jx edit env staging --remote=false` does not revert the environment to a non-Multi-Cluster setup, due to the Cluster URL value persisting.

### Steps to reproduce the behavior
Follow the [Getting Started: Multiple Clusters](https://jenkins-x.io/getting-started/multi-cluster/) docs.

- Run ```jx edit env staging --remote ``` and set a Cluster IP.
- verify the changes via ```jx get env```

output:
```
NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER      SOURCE                                                                REF    PR
staging    Staging     Permanent   Auto    jx-staging    100   MY_CLUSTER_IP      https://github.com/org/environment-clustername-staging.git    master 
```

- Run ```jx edit env staging --remote=false``` and set a Cluster IP.
- Run ```jx get env``` to see if Cluster value has been cleared
- Note: Cluster URL remains

output:
```
NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER      SOURCE                                                                REF    PR
staging    Staging     Permanent   Auto    jx-staging    100   MY_CLUSTER_IP       https://github.com/org/environment-clustername-staging.git    master 
```

### Expected behavior
```jx edit env ENV_NAME --remote=false``` should clear any Cluster values, thus returning the environments cluster to the default `dev` cluster.

Expected output:
```
NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER      SOURCE                                                                REF    PR
staging    Staging     Permanent   Auto    jx-staging    100         https://github.com/org/environment-clustername-staging.git    master 
```

### Actual behavior
Cluster URL persists.

### Jx version

The output of `jx version` is:
```
2.0.992
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE, created via `jx boot`.

### Operating system / Environment

Tested with both OSX and Linux

**Comment by jstrachan** [comment]
for multi cluster we recommend you use the new helm 3 based boot https://jenkins-x.io/docs/labs/boot/ which uses boot for `dev`, `staging` and `production` whether sharing a local cluster or using multiple cluster.

see https://jenkins-x.io/docs/labs/boot/multi-cluster/

this is a replacement for the `jx edit env` command; the environments are then configured via GitOps via the `jx-requirements.yml` file in your dev environment git repository
