### ISSUE TITLE
add a jx CLI that displays CVE vulnerabilities for jx apps

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#613]
Using anchore-engine we can add images to be analysed in both CI and CD pipelines.  It would be handy if a jx CLI queried the anchore engine REST API and displayed any known vulnerabilities.

Perhaps to start with we have a new command?
```
jx get vulnerabilities # full command name
jx get vuln
jx get vuln --app foo
jx get vuln --app foo --version 1.0.0
jx get vuln --app foo --env staging # returns the vulnerabilities for a given app in a given environment
jx get vuln --env staging # returns a list of vulnerabilities for all apps in the given environment
```
There's plenty more we can do with anchore but this might be a good start?  Then we could also add vulnerabilities to other commands like `jx get apps` if it makes sense?

**Comment by gtseres** [comment]
There is also [Clair](https://github.com/coreos/clair) for static analysis of vulnerabilities.

**Comment by jstrachan** [comment]
@rawlingsj can this be closed now?
