### ISSUE TITLE
Update documentation when marking commands/features as deprecated

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx#6136]
As we go through and mark commands/features as deprecated in the code and CLI, we also need to update the corresponding documentation pages.

Please follow instructions outlined here: https://jenkins-x.io/about/maturity/#deprecated-features

the code to insert a deprecation block is 
```
{{% alert color="warning" %}}
Deprecated in jx since 2.0.134. Will be removed on 2nd December 2019.
{{% /alert %}}
```

**Comment by haysclark** [comment]
Related to #6120
