### ISSUE TITLE
jx create archetype catalog cache

### ISSUE THREAD

**Issue by zhangzhang** [jenkins-x/jx#6138]
### Summary 
jx create archetype keep using the cached archetype catalog

### Steps to reproduce the behavior
1. run jx create archetype command, it will try go to retrieve the default catalog from: http://central.maven.org/maven2/archetype-catalog.xml
2. run jx create archetype --catalog command to point to a different catalog url

### Expected behavior
jx create archetype --catalog should trash the cache and read the catalog from the new url specified by --catalog.

### Actual behavior
jx create archetype --catalog command still loads the catalog from default catalog

Workaround: Go to the cache folder and manually delete the archetype-catalog.xml file.

### Jx version
2.0.976
The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.976
jenkins x platform 2.0.1599
Kubernetes cluster v1.15.5
kubectl            v1.15.5
helm client        Client: v2.14.3+g0e7f3b6
git                2.24.0
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

**Comment by deanesmith** [comment]
@zhangzhang, we will be deprecating this command in an upcoming release.  The recommendation is to leverage `jx create quickstart` for similar use cases.  It would be great to know if your use case has no other reasonable workaround.

**Comment by MarckK** [comment]
@zhangzhang please see issue #6120 for a list of jx commands being considered for deprecation and to contribute to the discussion around that process.

**Comment by zhangzhang** [comment]
@deanesmith @MarckK When I look through the jx create quickstart documentation, I don't find an option to specify an archetype. Seems like this use case is missing in the jx create quickstart. What I would like to achieve is to use jx command to create a project based on an archetype from my private archetype catalog.
I hope we could merge this function into the jx create quickstart command before we deprecate it.

**Comment by deanesmith** [comment]
@zhangzhang it does seem that would be a more appropriate option.

**Comment by zhangzhang** [comment]
@deanesmith  Thanks.
