### ISSUE TITLE
jx uninstall does not delete customresourcedefinitions littering `kubectl api-resources`

### ISSUE THREAD

**Issue by cbdchang** [jenkins-x/jx#6142]
### Summary 
Using JenkinsX creates a lot of new resources, i.e. buildpacks, apps, environments, etc. which doesn't get deleted after uninstalling JenkinsX.

### Steps to reproduce the behaviour
`jx uninstall`
`kubectl api-resources` produces a list of resources including custom resources that *should* be deleted on uninstalling.

### Expected behavior
`kubectl api-resources` after `jx uninstall` should show all JenkinsX resources removed.

### Actual behavior
I have to manually delete all the customresourcedefinitions.

 kubectl delete CustomResourceDefinition apps.jenkins.io
 kubectl delete CustomResourceDefinition buildpacks.jenkins.io
 kubectl delete CustomResourceDefinition commitstatuses.jenkins.io
 kubectl delete CustomResourceDefinition environmentrolebindings.jenkins.io
 kubectl delete CustomResourceDefinition environments.jenkins.io
 kubectl delete CustomResourceDefinition facts.jenkins.io
 kubectl delete CustomResourceDefinition gitservices.jenkins.io
 kubectl delete CustomResourceDefinition pipelineactivities.jenkins.io
 kubectl delete CustomResourceDefinition pipelinestructures.jenkins.io
 kubectl delete CustomResourceDefinition plugins.jenkins.io
 kubectl delete CustomResourceDefinition releases.jenkins.io
 kubectl delete CustomResourceDefinition schedulers.jenkins.io
 kubectl delete CustomResourceDefinition sourcerepositories.jenkins.io
 kubectl delete CustomResourceDefinition sourcerepositorygroups.jenkins.io
 kubectl delete CustomResourceDefinition teams.jenkins.io
 kubectl delete CustomResourceDefinition users.jenkins.io
 kubectl delete CustomResourceDefinition workflows.jenkins.io
 kubectl delete CustomResourceDefinition extensions.jenkins.io

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.643
Kubernetes cluster v1.16.2
kubectl            v1.16.2
git                2.21.0
Operating System   Mac OS X 10.15.1 build 19B88
```

### Jenkins type

Classic Jenkins

### Kubernetes cluster

Single-node cluster (followed Kubernetes in 10 minutes - Alex Ellis)

### Operating system / Environment

MacOS

**Comment by nklkarthi** [comment]
Having the same issues with jx
