### ISSUE TITLE
Broken python builder 

### ISSUE THREAD

**Issue by pod2metra** [jenkins-x/jx#6143]
### Summary 
On latest image https://console.cloud.google.com/gcr/images/jenkinsxio/GLOBAL/builder-python@sha256:6b79c1d8fea07e3b0f9e6d84c79aa2e4cddb2d191b8ce7e9a2cb4a4dc0ed40ab/details?tab=info python builder is broken.
### Steps to reproduce the behavior
add in pipeline any python install step for example pip install docker-compose  
### Expected behavior
docker-compose installed successfully 
### Actual behavior
Instal failed with error 
```
    _posixsubprocess.c:16:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```
### Jx version

```
jx                 2.0.998
jenkins x platform 2.0.1619
Kubernetes cluster v1.14.6-eks-5047ed
kubectl            v1.16.2
helm client        Client: v2.13.1+g618447c
git                2.23.0
Operating System   Mac OS X 10.15 build 19A602
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS v1.14.6

### Operating system / Environment

Mac OS X 10.15 build 19A602

**Comment by abayer** [comment]
I've reproduced this. I think I have a fix.

**Comment by pod2metra** [comment]
@abayer What can it be?

**Comment by abayer** [comment]
Oh, wait, the `builder-python` image doesn't actually make any changes to the `/usr/bin/python` that comes with the system - it instead installs python 3.6 to `/usr/bin/python3`. So `pip3 install docker-compose` works fine, but `pip install docker-compose` does not. I'm not enough of a python person to know what we should be doing in terms of `pip` and `python` pointing to the 2.7 or 3.6 versions...

**Comment by pod2metra** [comment]
@abayer Thank you, switch on pip3 fix that issue. But `pip` works correctly on `gcr.io/jenkinsxio/builder-python:2.0.974-310` image. So, looks like something was changed.

**Comment by abayer** [comment]
Interesting - we haven't made any explicit changes to the builder or the images it's based on in that timeframe, but the base image was rebuilt. It's possible that some dependencies that get installed via `yum` differed. I'll leave this open.
