### ISSUE TITLE
helm tiller install fails when helm client is locally compiled

### ISSUE THREAD

**Issue by jeff-knurek** [jenkins-x/jx#615]
I guess this is a rare situation to occur, but the helm client version could probably easily be checked before the install begins, and avoid the user being stuck in a broken state

or, probably just be more specific with the helm init command: 
`helm init --tiller-image=gcr.io/kubernetes-helm/tiller:v2.8.2`

-------
**Steps**:
- install helm client locally from source (your helm client version should be something like `SemVer:"v2.8+unreleased"`
- run `jx install`

**Actual**:
- install fails with:
```
Error: error when upgrading: current Tiller version is newer, use --force-upgrade to downgrade
Error: Command failed  helm init --upgrade --service-account tiller --tiller-namespace kube-system
retrying after error:exit status 1
retrying after error:existing tiller deployment found but not running, please check the kube-system namespace and resolve any issues
helm init failed: after 3 attempts, last error: existing tiller deployment found but not running, please check the kube-system namespace and resolve any issues
error: after 3 attempts, last error: existing tiller deployment found but not running, please check the kube-system namespace and resolve any issues
```
describing the tiller shows this error:
```
  Warning  Failed                 14s (x4 over 1m)  kubelet, gke-jx-default-pool-5b37043b-ftvg  Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.8": rpc error: code = Unknown desc = Error: Status 405 trying to pull repository kubernetes-helm/tiller: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"
  Warning  FailedSync             1s (x9 over 1m)   kubelet, gke-jx-default-pool-5b37043b-ftvg  Error syncing pod
  Normal   BackOff                1s (x5 over 1m)   kubelet, gke-jx-default-pool-5b37043b-ftvg  Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.8"
```
which is referenced here: https://github.com/kubernetes/helm/issues/3569#issuecomment-372742911

-------
**Solution**:
- delete the tiller deployment
- install the latest official helm client that aligns with the version `jx` uses
- run the install again

**Comment by ccojocar** [comment]
This seems to be a helm issue not a jx. jx installs a helm binary on client side which is compatible with the tiller version from the cluster.
