### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#6163]
### Summary 
It'll be very helpful if `jx` could support i18n. After that, `jx` could generate different languages document.

I'd love to take the initiative to do it.

**Comment by deanesmith** [comment]
@deanesmith Add globalization label

**Comment by LinuxSuRen** [comment]
Hi @deanesmith, I didn't catch up with your ideas which about the services. Would do you mind give more details to me. Thanks. I've added the i18n support in [jcli](https://github.com/jenkins-zh/jenkins-cli/pull/245/files#diff-bf3c636c393aa480afe9aecb08f83b7fR32).

**Comment by deanesmith** [comment]
@LinuxSuRen Is your proposal to translate the JX CLI?

**Comment by LinuxSuRen** [comment]
@deanesmith Yes. I've achieved it for [jcli](https://github.com/jenkins-zh/jenkins-cli). I18n message file is [here](https://github.com/jenkins-zh/jenkins-cli/blob/master/app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po)
