### ISSUE TITLE
Failure during 'jx boot' - failed to replace missing versions in the requirements.yaml

### ISSUE THREAD

**Issue by zhangxpp** [jenkins-x/jx#6164]
### Summary 
failed to jx boot 
### Steps to reproduce the behavior
jx boot 
### Expected behavior
boot successfully.

### Actual behavior
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/zhangxpp/jenkins-x-boot-config.git and git ref: master
error: failed to replace missing versions in the requirements.yaml in dir /tmp/jx-helm-apply-208941221/velero: failed to replace missing versions in file /tmp/jx-helm-apply-208941221/velero/requirements.yaml: the helm repository https://kubernetes-charts.storage.googleapis.com does not have an associated prefix in in the 'charts/repositories.yml' file the version stream, so we cannot default the version in file /tmp/jx-helm-apply-208941221/velero/requirements.yaml
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --no-vault --name velero' command in directory 'systems/velero', output: ''
### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 2.0.1005
Kubernetes cluster v1.16.2
kubectl            v1.16.2
helm client        v2.16.0+ge13bc94
git                2.24.0

```
COPY OUTPUT HERE
```

### Jenkins type

- [V ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
kubernetes installed by kubeadm 
 3 master and 3 worker nodes 

### Operating system / Environment
CentOS Linux release 7.7.1908 (Core)  3.10.0-1062.4.1.el7.x86_64

**Comment by zhangxpp** [comment]
One update , when I use "jx install", the issue is gone, but another error is here.  

unable to recognize "/tmp/helm-template-workdir-109953493/tekton/output/namespaces/jx/tekton/templates/part0-controller.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "/tmp/helm-template-workdir-109953493/tekton/output/namespaces/jx/tekton/templates/part0-webhook.yaml": no matches for kind "Deployment" in version "apps/v1beta1"'

**Comment by ccojocar** [comment]
I think this issue was fixed. This is specific to Kubernetes v1.16 which expects `apps/v1` instead of `apps/v1beta1`

@zhangxpp Are you still facing the same issue with boot? Thanks!
