### ISSUE TITLE
'Could not find any user auths for jenkins server' during garbage collection 

### ISSUE THREAD

**Issue by carlosrodlop** [jenkins-x/jx#6165]
### Summary 

jenkins-x-gcactivities pods are not created

```
jenkins-x-gcactivities-1574078400-227nt      0/1     Error               0          112m
jenkins-x-gcactivities-1574078400-24bs6      0/1     Error               0          116m
jenkins-x-gcactivities-1574078400-24kf4      0/1     Error               0          89m
...
jenkins-x-gcactivities-1574080200-2k4qw      0/1     Error               0          78m
jenkins-x-gcactivities-1574080200-2qt6f      0/1     ContainerCreating   0          1s
jenkins-x-gcactivities-1574080200-2s7lh      0/1     Error               0          31m
...
jenkins-x-gcactivities-1574080200-zzld9      0/1     Error               0          2m54s
```

Looking at jenkins-x-gcactivities logs 

```
$> kubectl logs jenkins-x-gcactivities-1574080200-zzld9
error: Could not find any user auths for jenkins server http://jenkins.xxx.xx.xx.xx.xx.nip.io.io has server URLs
```
### Steps to reproduce the behavior

The issue was exposed and we don't have steps to reproduce the issue.

### Expected behavior

jenkins-x-gcactivities pod should be created 

### Actual behavior

jenkins-x-gcactivities pod are not created 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.979
jenkins x platform 2.0.1619
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.13.2
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS

### Workaround

* The kubernetes jenkins secret was missing the field : jenkins-admin-api-token
* Edited the secret manually to add this field with token value found in http://jenkins.nos.34.74.59.50.nip.io/me/configure

It has been inspired by https://github.com/jenkins-x/jx/issues/5000

**Comment by deanesmith** [comment]
@daveconde add to sprint 20

**Comment by hectoralicea** [comment]
I have the same issue.  kc log gives the following output.
```
$ kc logs -n jx jenkins-x-gcactivities-1578346200-5j87z
error: creating auth config service for Jenkins: no auth config found for secret "jenkinsAuth.yaml"

```

**Comment by bnerDY** [comment]
i have the same issue

**Comment by anilkumarpasupuleti** [comment]
@deanesmith, i have the same issue. is it fixed now?

**Comment by mcabrito** [comment]
I have the same:
# oc logs -f jenkins-x-gcactivities-1580830200-887ff
error: creating auth config service for Jenkins: no auth config found for secret "jenkinsAuth.yaml

**Comment by laurent-theglue** [comment]
I have the same issue and the workaround that works for me is to add the verb `list` for resources `secrets` in the role `gcactivities`. 
```
- apiGroups:  
  - ""      
  resources:    
  - secrets
  - services
  verbs:
  - get  
  - list  <-- to be added
- apiGroups:
  - apps       
```

**Comment by polothy** [comment]
The fix provided by @lcaille worked for us.

**Comment by deanesmith** [comment]
Hi @polothy, Given that static masters are no longer supported on 2.1.x versions of Jenkins X and that you were able to address the matter, are you alright with closing the issue?

**Comment by polothy** [comment]
Oh, had no idea if gcactivities was still a thing in Tekton world.  If not, then I guess you cannot fix this anyways.

**Comment by Vijaygoud** [comment]
> The fix provided by @lcaille worked for us.

Could you please let me know, where exactly the changes were made. 

Thanks in advance.

**Comment by karthickvelu90** [comment]
> The fix provided by @lcaille worked for us.

Hello @polothy , could you please mention, where exactly the changes are to made.  Thanks

**Comment by infa-ddeore** [comment]
> I have the same issue and the workaround that works for me is to add the verb `list` for resources `secrets` in the role `gcactivities`.
> 
> ```
> - apiGroups:  
>   - ""      
>   resources:    
>   - secrets
>   - services
>   verbs:
>   - get  
>   - list  <-- to be added
> - apiGroups:
>   - apps       
> ```

this worked for me.

@karthickvelu90 you need to edit role `kubectl edit role -n jx gcactivities` and add `list` permission as mentioned
