### ISSUE TITLE
External DNS Pod on EKS doesn't Start

### ISSUE THREAD

**Issue by thomasburst** [jenkins-x/jx#6173]
### Summary 
When applying External DNS on EKS, the pod "exdns-external-dns" fails to start with the following errors:

> MountVolume.SetUp failed for volume "google-service-account" : secret "external-dns-gcp-sa" not found

> Unable to mount volumes for pod "exdns-external-dns-698c9757b-6j6zs_jx(6bb38c32-0f17-11ea-ad20-02c54b9503f2)": timeout expired waiting for volumes to attach or mount for pod "jx"/"exdns-external-dns-698c9757b-6j6zs". list of unmounted volumes=[google-service-account]. list of unattached volumes=[google-service-account exdns-external-dns-token-ggqvs]

**NOTE:** Erroring Pod does not get deleted after resetting "externalDNS" to "false" but running "jx boot" does re-generate an internal DNS to use and deploys successfully. Therefore effectively reverting the issue.

### Steps to reproduce the behavior
Edit jx-requirements.yml:
```
ingress:
  domain: <CUSTOM DOMAIN>
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
```

### Expected behavior
Jenkins X deploys to EKS successfully and environments are reachable at the DNS specified in jx-requirements.yml

### Actual behavior
Jenkins X fails to deploy, "exdns-external-dns" pod fails to start after waiting for 30 minutes.
Errors:
> MountVolume.SetUp failed for volume "google-service-account" : secret "external-dns-gcp-sa" not found

> Unable to mount volumes for pod "exdns-external-dns-698c9757b-6j6zs_jx(6bb38c32-0f17-11ea-ad20-02c54b9503f2)": timeout expired waiting for volumes to attach or mount for pod "jx"/"exdns-external-dns-698c9757b-6j6zs". list of unmounted volumes=[google-service-account]. list of unattached volumes=[google-service-account exdns-external-dns-token-ggqvs]

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1011
Kubernetes cluster v1.14.8-eks-b7174d
kubectl            v1.16.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Ran "jx create cluster eks -n jenkins-x --skip-installation"
Cloned "jenkins-x-boot-config"
Edited jx-requirements.yml and set "provider" to "eks" 
Ran "jx boot"

Deployment was successful following these steps but not after turning External DNS on.

### Operating system / Environment

Ubuntu for Windows: Ubuntu 18.04.2 LTS

**Comment by babadofar** [comment]
probably related to this https://github.com/jenkins-x/jx/issues/5521
