### ISSUE TITLE
Improve the error message when using helm v3

### ISSUE THREAD

**Issue by cvanballegooijen** [jenkins-x/jx#6181]
### Summary 
Helm v3 came out recently and I updated my helm version to v3.
When using jx create cluster .... I received the following 
WARNING: retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
WARNING:
retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'

### Steps to reproduce the behavior
On macOS brew install helm

### Expected behavior
An error message that helm v3 is not supported yet and that one need to install helm v2.

### Actual behavior
WARNING: retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
WARNING:
retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'

### Jx version

The output of `jx version` is:

~ $ jx version
NAME               VERSION
jx                 2.0.881
jenkins x platform 2.0.1642
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.0
Operating System   Mac OS X 10.15.1 build 19B88

verifying packages

WARNING: jx version 2.0.1011 is available in the version stream. We highly recommend you upgrade to it.

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GCP

### Operating system / Environment

macOS

**Comment by rawlingsj** [comment]
Agreed - we could have some validation as we don't support Helm 3 today and it likely wont be soon so a nicer error message would rock.

**Comment by deanesmith** [comment]
Helm3 is automatically downloaded and installed if there is no version locally.  Ensure proper version is downloaded and make boot fail out if Helm3 is detected.

**Comment by deanesmith** [comment]
Ref https://github.com/jenkins-x/jx/issues/6124
