### ISSUE TITLE
Documentation link not correct in CloudBees Web UI 

### ISSUE THREAD

**Issue by cvanballegooijen** [jenkins-x/jx#6183]
### Summary 
See the documentation link in the web ui is not correct 

### Steps to reproduce the behavior
1 - Set profile to cloudbees with jx profile cloudbees
2 - Install the web ui with jx add app ui
3 - after installation start web ui with jx cloudbees

### Expected behavior
The See the documentation link should point to https://jenkins-x.io/docs/getting-started/first-project/create-quickstart/
### Actual behavior
Link to the documentation is https://jenkins-x.io/developing/create-quickstart/ which generates a 404
see 
### Jx version

The output of `jx version` is:

~ $ jx version
NAME               VERSION
jx                 2.0.881
jenkins x platform 2.0.1642
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.0
Operating System   Mac OS X 10.15.1 build 19B88

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GCP

### Operating system / Environment

macOS Catalina
<img width="1557" alt="Screenshot 2019-11-25 at 15 00 39" src="https://user-images.githubusercontent.com/40221816/69546831-c1d8aa80-0f94-11ea-99da-27c6f192f3ff.png">

**Comment by abayer** [comment]
I've opened a tracking issue for this on the internal issue tracker for the UI. Thanks for the report!
