### ISSUE TITLE
Quickstart for pipeline with 'sidecars'`

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#619]
Asked on slack by `vanetix` was how to do sidcar style builds (in this case for an elixir quickstart). A side car means to run the test, for example, one may start up a postgres server as part of the build pod so it can test DB access. 

I assume this is possible with build pods, but not sure about the config in the Jenkinsfile myself. Perhaps a quickstart showing this would do the trick?

**Comment by angoothachap** [comment]
Related PRs: #1227 #1268 #1365 #1433. All these have been merged.

**Comment by jnsvd** [comment]
Looking for something similar, we need a pod that uses `initContainers`, i.e. we want to build an additional image (ideally code is separated, is tested,...). I'm sure it's possible but I can't find a good example.
As a workaround, I can spin up an `initContainer` that runs the same application as the main container, but with a different entrypoint such that it exits after a specific operation was performed successfully.

**Comment by i5okie** [comment]
Same as @michaelneale, need a sidecar with postgres.
Looks like Tekton now supports sidecars: https://github.com/tektoncd/pipeline/commit/14425d17468cb45ac87240a7ceae8c6e7b3b0aa1

Any developments on this?
modifying `jenkins-x.yml` file isn't documented well. At least I have not been able to find examples of `jenkins-x.yml` file.

Please help

**Comment by michaelneale** [comment]
@abayer - I hear you were looking at something like this?

**Comment by michaelneale** [comment]
hey @i5okie apparently this is being looked at, but the tekton support still needs to mature a bit more. So ... soon.

**Comment by i5okie** [comment]
Any update on this?
