### ISSUE TITLE
Pods Error on IBM Cloud

### ISSUE THREAD

**Issue by wofish2** [jenkins-x/jx#620]
Hi, 

I tried this on IBM Cloud, it seems working well, but four pods crashed. (related to #472 )
`jx install --provider=kubernetes`

pod status:
![screen shot 2018-04-12 at 12 14 21](https://user-images.githubusercontent.com/366618/38654609-3396e870-3e4b-11e8-9410-6d3066139a24.png)

Volume status:
![screen shot 2018-04-12 at 12 14 30](https://user-images.githubusercontent.com/366618/38654845-70daedb6-3e4c-11e8-8507-ff7629b5f9ce.png)

- Jenkins

Error message on Kubernete Dashboard:
`Readiness probe failed: Get http://172.30.157.109:8080/login: dial tcp 172.30.157.109:8080: getsockopt: connection refused`

pod logs :
`Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Apr 12, 2018 2:58:11 AM Main deleteWinstoneTempContents
WARNING: Failed to delete the temporary Winstone file /tmp/winstone/jenkins.war
Apr 12, 2018 2:58:11 AM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @527ms to org.eclipse.jetty.util.log.JavaUtilLog
Apr 12, 2018 2:58:11 AM winstone.Logger logInternal
INFO: Beginning extraction from war file`

- mongodb

Error message on Kubernete Dashboard:

`Readiness probe failed: MongoDB shell version v3.4.9 connecting to: mongodb://127.0.0.1:27017 2018-04-12T02:38:32.771+0000 W NETWORK [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused 2018-04-12T02:38:32.779+0000 E QUERY [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed : connect@src/mongo/shell/mongo.js:237:13 @(connect):1:6 exception: connect failed
Back-off restarting failed container
Error syncing pod`

pod logs :
`Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com
nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '4294967294' not found`

- monocular-api

Error message on Kubernete Dashboard:
`Back-off restarting failed container
Error syncing pod`

pod logs :
`time="2018-04-12T02:54:19Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-04-12T02:54:19Z" level=info msg="Configuration file found!" 
time="2018-04-12T02:54:19Z" level=info msg="Loading CORS from config file" 
time="2018-04-12T02:54:19Z" level=info msg="Loading repositories from config file" 
time="2018-04-12T02:54:19Z" level=info msg="Configuration bootstrap finished" 
time="2018-04-12T02:54:29Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017" 
`

- nexus

Error message on Kubernete Dashboard:
`Exec lifecycle hook ([/opt/sonatype/nexus/postStart.sh]) for Container "nexus" in Pod "jenkins-x-nexus-6f6dd547b7-7n8lb_jx(3df59ce7-3dfa-11e8-b743-a66e160a17c0)" failed - error: command '/opt/sonatype/nexus/postStart.sh' exited with 137: , message: "."
Error syncing pod
Back-off restarting failed container`

pod logs :
`mkdir: cannot create directory '../sonatype-work/nexus3/log': Permission denied
mkdir: cannot create directory '../sonatype-work/nexus3/tmp': Permission denied
Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to No such file or directory
Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
Unable to update instance pid: Unable to create directory /nexus-data/instances
/nexus-data/log/karaf.log (No such file or directory)
Unable to update instance pid: Unable to create directory /nexus-data/instances`

What is wrong with my pods?

**Comment by rawlingsj** [comment]
Odd as chartmuseum seems to have started ok and therefore must be able to write to it's PV.  This almost looks like issues we used to see with OpenShift where processes ran as a random user and didn't have permission to write to PVs.  I'm not familiar with IBM Cloud, do you know if there's anything special we need to do in a Dockerfile so we can write to mounted PVs?

**Comment by wofish2** [comment]
With IBM Cloud, dynamic volume provisioning would assign "nobody" user to volumn mount path.
"nobody" user has less permission than "root" user. Maybe that is the reason.

![untitled 2](https://user-images.githubusercontent.com/366618/38847144-0bdf8190-423b-11e8-9b2c-20d394d2d4f4.png)

Maybe in Dockerfile, create a "Jenkins" user and assign it with full permisson to volumn mount path may solve this.

ex.
Sample Dockerfile
```
FROM registry.<region>.bluemix.net/ibmliberty:latest
RUN groupadd --gid 1010 jenkins
RUN useradd --uid 1010 --gid 1010 -m --shell /bin/bash jenkins
ENV MY_USER=jenkins
COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh
EXPOSE 22
ENTRYPOINT ["/sbin/entrypoint.sh"]
```

script entrypoint.sh
```
#!/bin/bash
set -e
MOUNTPATH="/mnt/myvol"
MY_USER=${MY_USER:-"jenkins"}
create_data_dir() {
  usermod -aG root $MY_USER
  chmod 775 $MOUNTPATH
  su -c "mkdir -p ${MOUNTPATH}/mydata" -l $MY_USER
  su -c "chmod 700 ${MOUNTPATH}/mydata" -l $MY_USER
  ls -al ${MOUNTPATH}
  deluser $MY_USER root
  chmod 755 $MOUNTPATH
  echo "Created Data directory..."
}
create_data_dir
tail -F /dev/null
```


https://console.bluemix.net/docs/containers/cs_storage.html#nonroot

However, I solved this by creating PV myself, rather than using default storage class and dynamic volume provisioning. 

Close this issue.

**Comment by allen-servedio** [comment]
Check to see if there is a default storage class defined (`kubectl get sc`). We had to [set a default storage class](https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/) for Mongo to install properly.
