### ISSUE TITLE
Cannot find a valid baseurl for repo

### ISSUE THREAD

**Issue by bakuppus** [jenkins-x/jx#6200]
### Summary 
Jenkins job logs error : Cannot find a valid baseurl for repo: amzn2-core/2/x86_64

Generating tags...
 - balafiverr/amazonlinux -> 768230297472.dkr.ecr.us-east-2.amazonaws.com/balafiverr/amazonlinux:0.0.1
Checking cache...

 - balafiverr/amazonlinux: Not found. Building
Building [balafiverr/amazonlinux]...
Sending build context to Docker daemon  2.048kB

Step 1/6 : FROM amazonlinux:latest
latest: Pulling from library/amazonlinux
17282fad1a5e: Pulling fs layer

17282fad1a5e: Verifying Checksum
17282fad1a5e: Download complete

17282fad1a5e: Pull complete
Digest: sha256:5aa0460abffafc6a76590f0070e1b243a93b7bbe7c8035f98c1dee2f9b46f44c
Status: Downloaded newer image for amazonlinux:latest
 ---> 6ef285e58e33
Step 2/6 : RUN yum install httpd -y

 ---> Running in 1de29846cbf4
Loaded plugins: ovl, priorities
[91m

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
[0mCould not retrieve mirrorlist http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list error was
14: curl#6 - "Could not resolve host: amazonlinux.default.amazonaws.com"
time="2019-11-26T13:39:01Z" level=fatal msg="build failed: build failed: building [balafiverr/amazonlinux]: build artifact: unable to stream build output: The command '/bin/sh -c yum install httpd -y' returned a non-zero code: 1"
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Environments)
Stage "Promote to Environments" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done

### Steps to reproduce the behavior

Using below Docker file and run jx import
Dockerfile 
```
FROM amazonlinux:latest
RUN yum install httpd -y
RUN echo "Jenkins Docker Build and Publish " > /var/www/html/index.html
CMD ["sh", "-c", "tail -f /dev/null"]
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
EXPOSE 80
```

### Expected behavior

Docker build should resolve DNS 

### Actual behavior

Docker build failed to resolve DNS 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1003
jenkins x platform 2.0.1642
Kubernetes cluster v1.14.8-eks-b7174d
kubectl            v1.14.8
helm client        Client: v2.9.1+g20adb27
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

### Kubernetes cluster

 EKS

### Operating system / Environment

 Ubuntu

**Comment by hmacias** [comment]
In case someone comes across this same error message while using docker within docker on an AWS EKS cluster. The error message is a somewhat misleading in my case since my pod did have outbound internet access (ping 1.1.1.1 worked fine) and DNS resolution worked fine. Somehow the problem is related to networking on EKS node and I worked around this issue by using `--network=host` with docker build as in:

 `docker build --network=host --no-cache=true -t my-image .`

**Comment by bistoco** [comment]
In my case the problem was not dns, but the default timeout configured in yum.
I was able to find that yum requests took 5+ seconds to respond using curl to the urls that failed.
```
# RUN curl http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list
# RUN curl https://cdn.amazonlinux.com/2/core/2.0/x86_64/8dedd598ee5b14342cf2d7b1b54eaf359f8ea7d3142b843668245366a6ddb6c7
```
So the default timeout in `/etc/yum.conf` of 5 seconds (`timeout=5`) was being reach always.
When changing the default to 10 or 20 seconds before doing any yum operations, calls take some time but they work.

```
RUN cat /etc/yum.conf | grep timeout
RUN sed -i 's;timeout=5;timeout=20;g' /etc/yum.conf
RUN cat /etc/yum.conf | grep timeout
```
