### ISSUE TITLE
Interactive selection of storage classifier in 'jx edit storage' is not working

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#6226]
When running `jx edit storage` and interactively selecting the classifier for which to change the storage should be changed, the following error occurs:

```
jx edit storage
? Pick the content classification name tests
error: Missing option: --classifier
```

Specifying the classifier directly works:

```
jx edit storage --classifier tests
```

**Comment by shrutisheoran** [comment]
Hey @hferentschik I would like to work on this issue. Is it available?
