### ISSUE TITLE
jx add app failed in a bdd test because PipelineRun name not unique

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#6240]
A bdd test trying to install an app using `jx add app` failed because of the following: 

```
PipelineActivity for cb-kubecd-environment-pr-1050-5-bdd-frontend-dev-master-1
Applying changes 
upserted PipelineResource cb-kubecd-environment-pr-1050-5 for the git repository https://github.com/cb-kubecd/environment-pr-1050-5-bdd-frontend-dev.git
upserted Task cb-kubecd-environment-pr-1050-5-release-1
upserted Pipeline cb-kubecd-environment-pr-1050-5-1
error: failed to apply Tekton CRDs: failed to create the pipelineRun in namespace jx: Failed to create PipelineRun cb-kubecd-environment-pr-1050-5-1: pipelineruns.tekton.dev "cb-kubecd-environment-pr-1050-5-1" already exists
Pipeline failed on stage 'meta-pipeline' : container 'step-create-tekton-crds'. The execution of the pipeline has stopped.
```

There is some work to do to better uniquify the names for bdd tests.

**Comment by abayer** [comment]
Nah, either there's another bug here that I'm not seeing off the top of my head or we need to improve the uniqueness of `PipelineRun`s. I'll dig. =)

**Comment by abayer** [comment]
Waiting for this to happen again to see what exactly is going on...specifically, if anyone sees this happen again, please check what repo is now specified in the upserted `Pipeline`'s labels and in the already-existing `PipelineRun`'s labels.

**Comment by romainverduci** [comment]
This seems to happen quite often now, it happened at least 3 times since last week.
The problem is that it happens for me during a bdd test when it's trying to install an app and I don't have access to the bdd test cluster to get more info...
