### ISSUE TITLE
Misleading DEV environment context

### ISSUE THREAD

**Issue by NickitaX** [jenkins-x/jx#625]
As far as I understood, there are three environments out of the box:
-dev
-staging
-production
Staging and production have their own repositories and can be promoted into.
It feels like dev exists only for scope of JX services, but nothing else. 
I may be wrong, but maybe it would be better to call it "tools" or "jx-services" instead?
Thanks!

**Comment by jstrachan** [comment]
@oatesp yeah, though the only confusing thing is there will be builds in all environments & operations in all namespaces I suspect?

**Comment by jstrachan** [comment]
naming is hard :)

**Comment by rawlingsj** [comment]
Yeah I guess out of the suggestions proposed `operations` might help but TBH I still prefer `dev`.  I'm almost waiting for someone to propose `devops` ;)

I agree that `Developer Tools` is too long, `tools`, `services` and `builds` are all overloaded terms.

Maybe we find a term that centres around the `team` aspect?

**Comment by rawlingsj** [comment]
How about `home`? 
every team would have a team home environment which maps to a namespace `cheese_home`?

so `jx get env` would list:
- home
- staging
- production

**Comment by NickitaX** [comment]
`home` sounds very good! At least it doesn't confuse with `dev`, that's for sure 😃

**Comment by ccojocar** [comment]
Closing this since the are not planning to rename the `dev` environment.
