### ISSUE TITLE
Running jx get apps throws a git error

### ISSUE THREAD

**Issue by lhennerley** [jenkins-x/jx#6251]
### Summary 

Yesterday I did a quickstart of `node-http`. I did my first branch and then proceeded to merge this, in the mean time I noticed `jx ui`, while everything was running on my free GKE environment I added jx ui.

Since then, running `jx get apps` (as per the youtube video on home page) results in the following:

```
$ jx get apps
Attempting to cherry pick commits that were on master but not yet pushed
error: couldn't pull the environment repository from dev: Unable to cherry-pick 77573ae0f4eae1236b695c3b28140b27ff0d9b40: git output: error: commit 77573ae0f4eae1236b695c3b28140b27ff0d9b40 is a merge but no -m option was given.
fatal: cherry-pick failed: failed to run 'git cherry-pick 77573ae0f4eae1236b695c3b28140b27ff0d9b40' command in directory '/Users/lhennerley/.jx/environments', output: 'error: commit 77573ae0f4eae1236b695c3b28140b27ff0d9b40 is a merge but no -m option was given.
fatal: cherry-pick failed'
```

### Steps to reproduce the behavior

I am not 100% sure how I have managed to get into this state, as I mentioned I did install the UI app while a build was running on a branch.

**UPDATE**

I have replicated this a second time and figured out what it's down to. I downgraded helm yesterday after seeing this issue when trying to do `jx boot`.

https://github.com/jenkins-x/jx/issues/6124

I then ran:

```
$ jx add app jx-app-ui                                                                        
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (jenkins-x/jx, homebrew/core and homebrew/cask).
==> Updated Formulae
jenkins-x/jx/jx ✔                        drafter

==> Downloading https://homebrew.bintray.com/bottles/helm-3.0.0.mojave.bottle.ta
Already downloaded: /Users/lhennerley/Library/Caches/Homebrew/downloads/6df0c1bd724e60bc4f6a9314f6b7906e2e338f088c476b15dea619879a39e7a3--helm-3.0.0.mojave.bottle.tar.gz
==> Pouring helm-3.0.0.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/helm
Target /usr/local/bin/helm
already exists. You may want to remove it:
  rm '/usr/local/bin/helm'

To force the link and overwrite all conflicting files:
  brew link --overwrite helm

To list all files that would be deleted:
  brew link --overwrite --dry-run helm

Possible conflicting files are:
/usr/local/bin/helm
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/helm/3.0.0: 7 files, 40.6MB
ERROR: Error: Command failed  brew install kubernetes-helm
error: failed to ensure that helm is present: failed to install Helm: exit status 1
```

### Expected behavior

I should be able to list apps

### Actual behavior

I get a git error to do with cherry picking a specific hash

### Jx version

The output of `jx version` is:

```
2.0.1029
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE through Google cloud console

### Operating system / Environment

Mac OSX

**Comment by deanesmith** [comment]
Hi @lhennerley, what version of Helm did you downgrade to?  Once you downgraded, was this matter addressed?

**Comment by hferentschik** [comment]
Caused by the same issue as #5772

**Comment by tomfrenken** [comment]
@hferentschik tried it with the latest binary and now it works, can be closed I guess

**Comment by hferentschik** [comment]
@tomfrenken sweet :-)
