### ISSUE TITLE
spring boot health check for preview pr

### ISSUE THREAD

**Issue by pioneerlabs** [jenkins-x/jx#6263]
### Summary 
When I push a PR for  a spring boot app, if the app doesn't come app it retries for 10 minutes.

Updating PipelineActivities xxxxxx
WARNING: preview application http://xxxxxx not available, error was 502 502 Bad Gateway, delaying for: 703.186876ms

### Steps to reproduce the behavior

Just create a spring boot app with actuator but without any web or another server

### Expected behavior

I'd like to set a failure threshold to 1 so it doesn't retry for 10 minutes

### Actual behavior

During the build phase it tries 7 or 8 times

### Jx version

NAME               VERSION
jx                 2.0.971
jenkins x platform 2.0.1597
Kubernetes cluster v1.14.8-eks-b7174d
kubectl            v1.11.7-dispatcher
helm client        Client: v2.12.2+g7d2b0c7
git                2.20.1

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x ] Classic Jenkins

### Kubernetes cluster

aws eks

### Operating system / Environment

mac os

**Comment by deanesmith** [comment]
@pioneerlabs does your application surface specific endpoints?

**Comment by pioneerlabs** [comment]
the application expose some hateso apis and actuator endpoints. if the application doesn't start for any reason the problem mentioned above happens
