### ISSUE TITLE
Introduce new Jenkins X build context for running unit tests only

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#6269]
ATM we only run the `integration` test context which will run the integration tests as well as the unit tests (unit test == tests which don't connect to the cluster or other external resources).

Naming wise this is very confusing and not what one expects from an `integration` context. Also, it allows for potential issues with the tests where a unit test does open a cluster connection w/o being explicitly marked as an integration test. If we are able to properly separate unit from integration tests, we can enforce that unit tests don't create a cluster connection (e.g. by setting a dummy KUBECONFIG).

Another benefit of having a unit test context is to have a quickly passing test context. By just running the unit tests and also skipping coverage generation the test execution time can be considerably reduced.

**Comment by hferentschik** [comment]
Alternative names for _unit_ tests could be _smoke_ tests or _L0_ tests. Just in case we are getting into a philosophical discussion about "unit_ tests.

**Comment by tdcox** [comment]
In the context of Kubernetes, people may expect ‘smoke tests’ to refer to deployment validation checks that run in production environments to verify successful deployment.
