### ISSUE TITLE
jx should have create cluster option with baremetal cluster

### ISSUE THREAD

**Issue by thatsk** [jenkins-x/jx#629]
Jx command line should have option to configure from scratch in private cluster

**Comment by jstrachan** [comment]
The `create cluster aws` is mostly a thin facade over using `kops` to create a cluster - maybe we need to refactor out the AWS specific stuff so folks can use `jx create kops`?

**Comment by ccojocar** [comment]
No plans to support baremetal cluster creation. The cluster can be created outside of `jx` and the `jx install` command can be use to install the jx into that cluster.
