### ISSUE TITLE
jx promote can mistakenly use latest version of another app that has a prefix equals to the service being promoted

### ISSUE THREAD

**Issue by iftachsc** [jenkins-x/jx#6306]
### Summary 
i have two applications: demo and demo-users.
when running jx promote demo-users --env production all works fine and latest version is updated in the requirements.yaml file of the production env git. 
when doing the same for application demo - the same version is updated for the demo app in the req'.yaml file even thows the version in jx get application are far from each other and different on the major version. so its clearley doing a regular helm search and finds demo-users for being demo.

search should be with a regexp like we do with helm: helm search --regexp '\vAPP_NAME\v'

### Steps to reproduce the behavior
see above
### Expected behavior
the app will be identified properly

### Actual behavior
promoting the wrong version.
### Jx version

The output of `jx version` is:

```
jx                 2.0.1022
jenkins x platform 2.0.1733
Kubernetes cluster v1.14.8-eks-b7174d
kubectl            v1.14.3
helm client        Client: v2.12.1+g02a47c7
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

### Kubernetes cluster
EKS

### Operating system / Environment

Mac OSX

**Comment by deanesmith** [comment]
Proposed to remove dependency on Helm for this purpose.

**Comment by iftachsc** [comment]
> Proposed to remove dependency on Helm for this purpose.

can u elaborate?
