### ISSUE TITLE
Handle undeployed applications in get applications command

### ISSUE THREAD

**Issue by mauromorales** [jenkins-x/jx#6309]
### Summary 

During our refactoring of the applications command (see #6097), it was decided to use SourceRepositories to identify applications and map them to deployments. These get then displayed when executing e.g. `get applications`. There is one case which I identified while struggling with #6270, that it is possible to create an application i.e. SourceRepository get's created but for some reason deployment fails. It Should be possible to display this applications either as a default or by requesting them with a flag.

Relates to #6308

**Comment by hferentschik** [comment]
> it is possible to create an application i.e. SourceRepository get's created but for some reason deployment fails. It Should be possible to display this applications 

+1 seems reasonable. @mauromorales, was there a reason we did not do this per default?

**Comment by mauromorales** [comment]
@hferentschik only that this was breaking one of the BDD tests for the SaaS team see #6308
