### ISSUE TITLE
jx create spring isn't setting up git credentials or verifying git provider host keys

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#631]
`jx create spring` creates a pipeline that fails ~~in the `Promote to Environments step`~~ the multibranch pipeline scan due to a host key verification fail:

```
 > git ls-remote --symref git@bitbucket.org:wbrefvem/create-spring-demo.git # timeout=10
ERROR: [Mon Apr 16 18:05:28 UTC 2018] Could not update folder level actions from source 3ee777bd-6590-4b97-ac65-1ab01e7062ad
hudson.plugins.git.GitException: Command "git ls-remote --symref git@bitbucket.org:wbrefvem/create-spring-demo.git" returned status code 128:
stdout: 
stderr: Host key verification failed.
fatal: Could not read from remote repository.
```

~~Doing a key scan on the git provider host and then parsing the host key fingerprint should do the trick.~~

The same pipeline gets setup correctly in `jx import`, so it would seem that `jx create spring` isn't setting up credentials the same way.

**Comment by ccojocar** [comment]
@wbrefvem Is this still an issue? Please could you validate it? Thanks

**Comment by wbrefvem** [comment]
@ccojocar No, this doesn't appear to be an issue anymore.
