### ISSUE TITLE
jx create addon envctl create failed

### ISSUE THREAD

**Issue by bakuppus** [jenkins-x/jx#6310]
### Summary 
? A local Jenkins X versions repository already exists, pulling the latest: Yes
WARNING: could not find a stable version from charts of environment-controller from /root/.jx/jenkins-x-versions
For background see: https://jenkins-x.io/docs/concepts/version-stream/
Please lock this version down via the command: jx step create pr versions -k charts -n environment-controller
error: failed to run 'helm fetch -d /tmp/helm-template-workdir-583013842/jxet/chartFiles --untar environment-controller --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Failed to fetch https://storage.googleapis.com/charts/environment-controller-0.0.570.tgz : 403 Forbidden'
root@ip-172-31-90-231:~# 
### Expected behavior
Addon should install

### Actual behavior

Failed helm repo fetch with 403 Forbidden

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.0.1063
Kubernetes cluster v1.14.8-eks-b8860f
kubectl            v1.14.8
helm client        Client: v2.9.1+g20adb27
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ x] Classic Jenkins

### Kubernetes cluster

AWS EKS
### Operating system / Environment

Ubuntu

**Comment by jstrachan** [comment]
if you want to setup multi cluster you might want to try: https://jenkins-x.io/docs/labs/boot/multi-cluster/
