### ISSUE TITLE
jx create step deprecation

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6324]
### Summary 

When executing `jx create step` the following warning pops up:

```
Command "step" is deprecated, it will be removed on 01-02-2020. This will be renamed to edit pipeline command.
```

However, `jx edit pipeline` command does not exist. Is that a typo in the warning and the command is different, or it is missing altogether?

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Change the message to be "Command "step" is deprecated, it will be removed on Feb 1 2020."
