### ISSUE TITLE
How to for jenkins-x

### ISSUE THREAD

**Issue by severino42** [jenkins-x/jx#6325]
### Summary 
How do I access the Jenkins instance?
Kubernetes instance?
docker containers?

### Steps to reproduce the behavior
install jenkins-x

### Expected behavior
URLs provided to access resources

### Actual behavior
Install something, no explanation

### Jx version

The output of `jx version` is:

```
$ jx version 
NAME               VERSION
jx                 2.0.1065
jenkins x platform 2.0.1737
Kubernetes cluster v1.15.2
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @severino42, how about ```jx get urls```?  Does that help?
