### ISSUE TITLE
Jenkins fail to create a service account on google cloud if the cluster is two character name

### ISSUE THREAD

**Issue by shaharl-ia** [jenkins-x/jx#6334]
When installing jenkins-x on a two character name cluster on gke, it fail to create the service account because the it name must have at least 6 characters.

so for 'ci', the name will be 'ci-ko'

I don't really have the time to reproduce the issue for the console output, but it's pretty straight forward.

**Comment by deanesmith** [comment]
Service accounts must have between 6 and 36 chars.  Are you using ```jx boot``` for your cluster?  It should have warned you.

**Comment by shaharl-ia** [comment]
@deanesmith Thank you for the reply.
I use jenkins boot on a cluster named ci.
It fails because jenkins cannot create the service account named ci-ko which is a five letters sa.

**Comment by deanesmith** [comment]
@shaharl-ia, thank you.  Will ensure a pre-check exists in the future.

**Comment by metonymic-smokey** [comment]
@deanesmith is this issue still up for grabs?
New to Jenkins X and was looking for an easy issue to start with.

Thanks!

**Comment by metonymic-smokey** [comment]
@deanesmith is this issue still up for grabs?
New to Jenkins X and was looking for an easy issue.

Thanks!

**Comment by shaharl-ia** [comment]
Hi Aditi,
I am not sure since i am not using it yet.

**Comment by deanesmith** [comment]
@metonymic-smokey, yes, it would be great to have the `jx boot` validate this nuance as part of the verification process and raise an informative message accordingly.  We are catching this far too late at the moment.

**Comment by metonymic-smokey** [comment]
@deanesmith could creating a condition check in `naming.go` in `pkg/cloud/gke` fix this?
The service account name for a given cluster will be created only if the cluster name and the service account name  are greater than 6 characters.

Would love your inputs on the same.
Thanks!
