### ISSUE TITLE
tekton_logging.go#L584 instantiates a new factory rather than using the current factory

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#6337]
### Summary 

See https://github.com/jenkins-x/jx/blob/master/pkg/logs/tekton_logging.go#L584 - this is instantiating a new, default factory rather than using the one that called the method

**Comment by hferentschik** [comment]
the problem is that the factories (i.e. the jxClient and ns in this case are created with default values, not the ones that the command was called with. This happens if you programatically reuse this code and create a custom jxClient (e.g. with impersonation)
