### ISSUE TITLE
jx import should check the version of `maven-deploy-plugin` and if none is specified add a recent one

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#634]
had an issue of this project https://github.com/jenkins-x-test-projects/test-vertx-app not importing correctly as it was using 2.7 of the maven deploy plugin which for some reason decides to try use the snapshot rather than release nexus repo.

So we maybe should have a little maven plugin to check for the versions of plugins and tweak them if required

**Comment by Salaboy** [comment]
Did you find a workaround for this one? which version is the correct one?

**Comment by jstrachan** [comment]
2.8.2 seems to work nicely

**Comment by Salaboy** [comment]
👍 it is working now.. just in case others hit this problem. Adding this to the build->plugins sections of your pom file will solve the problem:
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>2.8.2</version>
      </plugin>
```

**Comment by mikaelmh** [comment]
There seems to be an issue with pulling the (newest?) `io.jenkins.updatebot` to check/update to maven-deploy-plugin 2.8.2, leading to `jx import` for spring projects to fail. 

The error message;
```
selected pack: /Users/mikaelmh/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/maven
existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step
error: Failed to update maven plugin: Command failed 'mvn io.jenkins.updatebot:updatebot-maven-plugin:RELEASE:plugin -Dartifact=maven-deploy-plugin -Dversion=2.8.2': [INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.opneditor:ms-schema2pojo:jar:1.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.mylyn.github:org.eclipse.egit.github.core:jar -> duplicate declaration of version 2.1.5 @ line 237, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.442 s
[INFO] Finished at: 2018-08-31T09:29:35-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin io.jenkins.updatebot:updatebot-maven-plugin:RELEASE or one of its dependencies could not be resolved: Failure to find io.jenkins.updatebot:updatebot-maven-plugin:jar:1.1.19 in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException exit status 1
 output: 

```
Not able to re-import our old projects. Is this issue related to a new version of `io.jenkins.updatebot @jstrachan ? Thanks!

**Comment by jstrachan** [comment]
its certainly there http://central.maven.org/maven2/io/jenkins/updatebot/updatebot-maven-plugin/1.1.19/

I guess your `pom.xml` has added a custom `<pluginRepository>` for https://repo.spring.io/libs-release but disabled maven central?  wonder if you need to add  a`<pluginRepository>` for maven central - i.e. http://central.maven.org/maven2

**Comment by mikaelmh** [comment]
@jstrachan thanks! Our `pom.xml` hadn't changed so hadn't thought to look there. Also, forgot that I ad recently upgraded maven locally so ended up clean installing, and it worked after restarting. I guess that made it include the maven central again. Thank you again!
