### ISSUE TITLE
jx deploy deprecation

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6340]
### Summary 

When executing `jx edit deploy` it output a warning saying that `Command "deploy" is deprecated, it will be removed on 01-02-2020.` Does that mean that it'll be removed completely or that specifying the replacement is missing from the message?

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @vfarcic - this command is going away.  Confirmed.

**Comment by vfarcic** [comment]
If that command is removed, there is no way to have new projects run as serverless from the start. We'd need to create "default" projects first, and then convert them to serverless by changing the `knativeDeploy` value to `true`. If this command is removed, I think we'd need a mechanism to set Helm values during `jx create quickstart`. Maybe the addition pf `--value` argument would be a good idea. I believe that would be useful for other cases as well.
