### ISSUE TITLE
Git submodules are not pulled

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#6341]
When pulling the repository in the pipeline, git submodules are not pulled. This is not available in the currently used tekton version (`v0.5.1`) but apparently available in the recent versions. https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1alpha1/git_resource.go#L60

pipeline steps can be added to solve them problem:
```bash
jx create step -p pullrequest -l setup -m replace -c "git submodule update --init"
jx create step -p release -l setup -m replace -c "git submodule update --init"
```

**Comment by abayer** [comment]
I’m going to be bumping our Tekton dependency in the next week or two.

**Comment by deanesmith** [comment]
Addressed.
