### ISSUE TITLE
Pipeline exection failed on the step export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml

### ISSUE THREAD

**Issue by nandar999** [jenkins-x/jx#6342]
When I build pipeline using jenkins x on AWS EKS cluster, I found the following error:
-build artifact: docker build: error during connect: 
-creating docker context: getting relative tar paths: file pattern [repositories] must match at least one file

How could I solve this issue?

**Comment by deanesmith** [comment]
Hi @nandar999, can you supply the contents of your skaffold.yaml?

**Comment by nandar999** [comment]
> Hi @nandar999, can you supply the contents of your skaffold.yaml?

Hi @deanesmith,
Below is my skaffold.yaml. Please check. 
Thanks
   

apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: test/test
    context: .
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: test
        chartPath: charts/test
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
