### ISSUE TITLE
jx boot fails configuring custom nexus settings

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx#6348]
### Summary 
using `jx boot` on `eks`, I need to set the disk size up from the tiny 8Gi to something more usable.
Adding the parameters in `env/nexus/values.tmpl.yaml` has no effect
### Steps to reproduce the behavior
configure custom nexus config in env/nexus/values.tmpl.yaml

```{{- if  or (eq .Requirements.repository "nexus") (eq .Requirements.repository "") }}
enabled: true
persistence:
  storageSize: 80Gi
  annotations:
    babadofar: fisk23
{{- else }}
enabled: false
{{- end }}
```
### Expected behavior
The configuration changes are visible using command 
 ` k get pvc jenkins-x-nexus  -oyaml   `
### Actual behavior
no change from default
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1076
Kubernetes cluster v1.14.8-eks-b8860f
kubectl            v1.16.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.18.0
Operating System   Mac OS X 10.14.6 build 18G1012```
```
### Kubernetes cluster

EKS, created using `jx create cluster eks --cluster-name=md-jx-sandbox --skip-installation=true --ng --tekton=true --prow=true --vault=true
`

**Comment by ccojocar** [comment]
@babadofar nexus is installed as part of the `jenkins-x-platform`. You need to add the custom values in https://github.com/jenkins-x/jenkins-x-boot-config/blob/d964d3698509982c06db743b8478b47525880ed3/env/jenkins-x-platform/values.tmpl.yaml#L24. Also the nexus helm chart was recently updated to the latest version.

**Comment by ccojocar** [comment]
I think we can do a better job to merge the values from `env/nexus` with the `env/jenkins-x-platform`.

**Comment by babadofar** [comment]
I cannot make this work, using jx boot versionstream 1.0.423  

    nexus:
      defaultAdminPassword: "{{ .Parameters.adminUser.password }}"
      persistence:
         storageSize: 100Gi

error message 

    The PersistentVolumeClaim "jenkins-x-nexus" is invalid: spec.resources.requests.storage: 
     Forbidden: field can not be less than previous value'
     error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''

**Comment by babadofar** [comment]
@dgozalo @ccojocar Any idea on how this can be handled? This makes problems when running jx boot - Either I have to upgrade the nexus disk manually,  - then I can't run jx boot. 
Alternatively keep cleaning up nexus. Or, perhaps the ultimate solution - stop coding. :)

**Comment by gcontini** [comment]
Me too i stumbled on this error even if i'm on a different environment. I'm on version stream 1.0.452 on GKE.
My `jenkins-x-nexus` pvc was recreated as 8GB that's on the "small" size for my project.
I fixed it like this:
in `env/jenkins-x-platform/values-tmpl.yaml`
```
nexus:
  defaultAdminPassword: "{{ .Parameters.adminUser.password }}"
  persistence:
     size: 100Gi
```
I see multiple problems here:
1. no documentation at all. It took me half a day to figure out how to configure this parameter.
2. no tests on jenkins-x side. Nexus configuration is broken and nobody noticed it.
3. More than 5 months of fixing time for a configuration that's shipped as default.
scary...

**Comment by babadofar** [comment]
Thanks for sharing  @gcontini   I tried using "storageSize" - since that's what it's named in the Nexus helm chart last I looked at it. Now it works my end.
