### ISSUE TITLE
Extending build process via metapipeline

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6349]
### Summary 
I have been working on an App to extend the build process via the mechanism in Metapipeline and wanted to share some challenges.

Firstly, using the plugin mechanism, there is currently no way to specify when in the build process your plugin will be invoked. At minimum, this needs to support the ability to inject functionality before and after the codebase is built, but ideally needs to allow detailed control over the injection point, plus some mechanism to reconcile multiple plugins attempting to insert at the same point.

Plugins are invoked for every build. In many cases, you don't want the additional functionality of your plugin in all the places it will be invoked, such as during promotion of code to an environment. Often, your code will fail if invoked during these types of build since it may expect to operate upon files that don't exist during those phases. At the present, that means that your plugin code has to understand the whole build lifecycle, work out where it is in that cycle and potentially disable itself when not required. This is tricky, since there are no available indicators that reliably show which cycle of which type of build pipeline you are in at the point that your plugin has been invoked. We could add some environment variables to mark this out more clearly, but architecturally it would be better to encapsulate this so it is hidden from the user and instead offer a way for a plugin to nominate points in the build where it would like to be invoked.

It is very likely that build plugins will need configuration in the form of environment variables, secrets, config maps or volume mounts to enable them to invoke other secure services. Right now, these plugins are invoked in the context of a build and there doesn't seem to be a mechanism to inject appropriate config, other than as command line parameters to the shell session that is invoked.

We would benefit from having a quickstart for Apps that extend Jenkins-X, since their build pipeline needs to be somewhat different from a conventional user Application.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1011
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G1012
```

**Comment by abayer** [comment]
cc @hferentschik

**Comment by deanesmith** [comment]
We are bumping the version of Tekton in a couple weeks (~Jan 1 2020).  At that point some of requirements we need for meta-pipeline extensions will become unblocked.
