### ISSUE TITLE
Delete app fails with cherry-pick error

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6350]
### Summary 
Attempting to delete an App using `jx delete app` fails under some circumstances due to a cherry pick error.

### Steps to reproduce the behavior
```
➜ jx delete app jx-app-fossa
Attempting to cherry pick commits that were on master but not yet pushed
error: couldn't pull the environment repository from dev: Unable to cherry-pick a155412b72bd8ca8123a8e3b0993a5bd49ca577d: git output: error: commit a155412b72bd8ca8123a8e3b0993a5bd49ca577d is a merge but no -m option was given.
fatal: cherry-pick failed: failed to run 'git cherry-pick a155412b72bd8ca8123a8e3b0993a5bd49ca577d' command in directory '/Users/terry/.jx/environments', output: 'error: commit a155412b72bd8ca8123a8e3b0993a5bd49ca577d is a merge but no -m option was given.
fatal: cherry-pick failed'
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.1011
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G1012
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by seanpianka** [comment]
Under `~/.jx/environments`, there seems to be local changes made to this repository, and the cherry-pick for merging these commits with remote is failing. 

See [these lines under pkg/gits/helpers.go](https://github.com/jenkins-x/jx/blob/master/pkg/gits/helpers.go#L594-L630).

**Comment by hferentschik** [comment]
Caused by the same issue as #5772

**Comment by tdcox** [comment]
Looking at the commits referenced in a recent repeat of this problem, it appears that the system is trying to refresh ~/.jx/environments with a commit that is already in ~/.jx/environments/dev and git is refusing to create the ensuing Inception nesting.

**Comment by abayer** [comment]
Ok, just verified that if you have a fresh boot cluster with gitops enabled and run `jx add app ...`, it will create `~/.jx/environments` (that may already exist, not 100% sure, but if it does, it's empty at this point) and then clone the dev env into `~/.jx/environments/dev`. But then if you run `jx delete app ...` afterwards, it ends up cloning the dev env again into `~/.jx/environments` directly - well, technically it runs `git init .; git fetch ...; git checkout ...` in `~/.jx/environments`. Not sure yet if that's specific to running `jx delete app ...` or would happen for `jx add app ...` after the first call, and not sure yet why it's happening.

**Comment by abayer** [comment]
Verified that it is specifically running `jx delete app ...`, and that it's not an ordering thing. `jx delete app ...` just does...weird things. Working on it.

**Comment by abayer** [comment]
Ah-ha, it's actually the logic behind `jx get apps` to blame - it's always using `~/.jx/environments` and initing/fetching to that directory, and that logic gets called as part of `jx delete app`.

**Comment by abayer** [comment]
Actually, why the heck is `jx get apps` doing a `ForkAndPullRepo` in the first place?!?

**Comment by abayer** [comment]
Sooooo yeah. `jx add app` and `jx delete app` use `~/.jx/environments/dev` with `ForkAndPullRepo`, which makes no sense. And `jx get apps` is using `ForkAndPullRepo` to clone to `~/.jx/environments` but not to create a PR or anything. This is goofy. Reworking.
