### ISSUE TITLE
Jenkins X pulling in a container that is NOT in the pod specification template

### ISSUE THREAD

**Issue by chris1248** [jenkins-x/jx#6353]
### Summary 
Jenkins X pulling in a container that is NOT in the pod specification template

### Steps to reproduce the behavior
Our Jenkinsfile has a pod specification template that is in a separate file:

```
pipeline {
  agent {
    kubernetes {
      label 'online-services-gradle5'
      defaultContainer 'jnlp'
      yamlFile 'Jenkinsfilepods.yaml'
    }
  }
...
```
And the yaml file started with 3 containers.
I added another, fourth container, for something I wanted to do. But Jenkins would just hang (I had to kill the build).
Then I removed the container specification from the pod file, and recommitted.

### Expected behavior
The POD should start up with 3 containers

### Actual behavior
The POD starts up with 4 containers

It includes the container that we previously removed from the pod template file.
So, what didn't get cleaned out? This totally screwed up our builds, and we have no idea where this magical cache is to be found?

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1082
Kubernetes cluster v1.12.10
kubectl            v1.17.0
helm client        v2.15.1+gcf1de4f
helm server        v2.14.3+g0e7f3b6
```

### Jenkins type
- [ ] Classic Jenkins

### Kubernetes cluster

KOPS

### Operating system / Environment

Operating System   Mac OS X 10.14.6 build 18G1012

**Comment by deanesmith** [comment]
Hi @chris1248, not sure why this would be.  Are you running as admin?  @garethjevans
