### ISSUE TITLE
Set namespaceSubDomain: -jx. for devpods and addons

### ISSUE THREAD

**Issue by sstubbs** [jenkins-x/jx#6362]
### Summary 
When using jx boot all environments I have tested so far are using the `namespaceSubDomain: -jx.` correctly that I've set in jx-requirements.yml except for devpods and the two addons prometheus and grafana which seem to default to `.jx.` This causes issues with a wildcard certificate that I'm currently using.

Ingress and dns entries can be changed manually but this is not ideal especially for devpods which are created and destroyed frequently.

### Steps to reproduce the behavior
`jx boot`
add `namespaceSubDomain: -jx.`  to all environments
`create devpod`
`jx create addon prometheus`
`jx create addon grafana`

### Expected behavior
Prefix to be -jx.

### Actual behavior
Prefix is .jx.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1076
Kubernetes cluster v1.14.9-gke.2
kubectl            v1.17.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
jx create cluster gke --skip-installation

### Operating system / Environment
MacOS Catalina

**Comment by deanesmith** [comment]
@sstubbs, very soon we'll be migrating the 2 addons to the newer "app" framework and they will be overhauled.  For devpods, this can be handled separately.

**Comment by sstubbs** [comment]
Ok thanks for the info. Will the current addons break when this change happens? If so I'll rather use the helm charts for the time being.
