### ISSUE TITLE
Lock the gcloud version 

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#6369]
### Summary 

It seems that we don't lock the gcloud version. It always installs latest on MacOS: 

https://github.com/jenkins-x/jx/blob/8a4dac4e0bc5882e91d2d66d371a16c6f97485ee/pkg/cmd/opts/install.go#L778

See for instance eksctl is locked: 
https://github.com/jenkins-x/jenkins-x-versions/blob/bdab4d2a65b04658d30707877a9072f05738ba9d/packages/eksctl.yml#L1

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
@ccojocar, what version do you recommend we lock in at?

**Comment by ccojocar** [comment]
Probably we can pick the latest from here https://cloud.google.com/sdk/docs/release-notes. I am not sure if there are any backward compatibility issues.

**Comment by sladyn98** [comment]
I could take a shot at this. https://cloud.google.com/sdk/docs/release-notes The latest version from this sounds cool  ?

**Comment by deanesmith** [comment]
@sladyn98 Contributions are strongly encouraged and this is quite valuable.

**Comment by ccojocar** [comment]
@sladyn98 You can lock first the version in the `gcloud.yml` file similarly with the other CLIs https://github.com/jenkins-x/jenkins-x-versions/tree/master/packages, and then you can change the jx to download this specific version for gcloud in this method: https://github.com/jenkins-x/jx/blob/cdcf046be3172cc8b398c2a6f85f570226d3663f/pkg/cmd/opts/install.go#L779 You can use as an example the `InstallKustomize`: https://github.com/jenkins-x/jx/blob/cdcf046be3172cc8b398c2a6f85f570226d3663f/pkg/cmd/opts/install.go#L226

**Comment by deanesmith** [comment]
Thank you @sladyn98  for your contribution.

**Comment by hervelemeur** [comment]
@hferentschik any reason for reopening this issue while the PR made by @sladyn98 has been merged?
