### ISSUE TITLE
JX Boot configuration for the kubernetes namespace format of environments

### ISSUE THREAD

**Issue by bkempe** [jenkins-x/jx#6372]
### Summary 

`jx boot` is missing a feature to configure the _kubernetes namespace_ format of environments.

Also, `jx boot` overwrites the existing environment kubernetes namespace.

Example:
We would like our environment namespaces be `stag` and `prod`.

### Steps to reproduce the behavior

1) install the cluster via JX Boot and configure the environments in `jx-requirements.yaml`:
```
NAME       LABEL       KIND        PROMOTE NAMESPACE          ORDER CLUSTER SOURCE                                                         REF    PR
dev        Development Development Never   jx                 100           https://github.com/abctest01/environment-abctest01abc-dev.git  master
production Production  Permanent   Manual  jx-production      100           https://github.com/abctest01/environment-abctest01abc-prod.git master
staging    Staging     Permanent   Auto    jx-staging         100           https://github.com/abctest01/environment-abctest01abc-stag.git master
```

2) `jx edit env` to change the namespaces to `stag` and `prod`:
```
NAME       LABEL       KIND        PROMOTE NAMESPACE ORDER CLUSTER SOURCE                                                         REF    PR
dev        Development Development Never   jx        100           https://github.com/abctest01/environment-abctest01abc-dev.git  master
production Production  Permanent   Manual  prod      100           https://github.com/abctest01/environment-abctest01abc-prod.git master
staging    Staging     Permanent   Auto    stag      100           https://github.com/abctest01/environment-abctest01abc-stag.git master
```

3) When we run the `dev` JX Boot pipeline, the namespaces get reverted to 1), always using the `jx-` prefix and the environment _name_

### Expected behavior

Be able to configure the environment kubernetes namespace to be `stag` and `prod` in JX Boot and not have JX Boot overwrite the namespace.

### Actual behavior

Environment kubernetes namespaces get overwritten.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1090
Kubernetes cluster v1.14.9-eks-ba3d77
kubectl            v1.17.0
helm client        Client: v2.12.2+g7d2b0c7
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G2022
```

**Comment by msvticket** [comment]
After the merge of jenkins-x-charts/jxboot-resources#20 you can now upgrade the platform and then configure the namespaces of staging and production in `env/jxboot-resources/values.tmpl.yaml`.

**Comment by iftachsc** [comment]
hitting the same. i did not understand how to work with env/jxboot-resources/values.tmpl.yaml so they namespaces of each env will persist
