### ISSUE TITLE
Received 409 response: {"error":"file already exists"}

### ISSUE THREAD

**Issue by bakuppus** [jenkins-x/jx#6373]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @bakuppus, Can you please provide more information and answer the template questions in the issue?
