### ISSUE TITLE
jx edit buildpack does not update the dev repo

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6374]
### Summary 

After executing `jx edit buildpack` to use a forked repo, the changes are not reflected in the `dev` repo created with `jx boot`.

### Steps to reproduce the behavior

* Enter into the `dev` repo

```bash
jx edit buildpack \
    --url https://github.com/[REPLACE_WITH_YOUR_GITHUB_USER]/jenkins-x-kubernetes \
    --ref master \
    --batch-mode
```

### Expected behavior

The change of the buildpack address is stored in the `dev` repo.

### Actual behavior

The change of the buildpack address is NOT stored in the `dev` repo.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1093
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.17.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G2022
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Any

### Operating system / Environment

Any

**Comment by hervelemeur** [comment]
Following [our Slack discussion](https://kubernetes.slack.com/archives/C9MBGQJRH/p1588181950110200?thread_ts=1588089186.068200&cid=C9MBGQJRH), I've also tried to configure jenkins-x with custom buildpacks, but it didn't work, no change at all.

```
$ jx edit buildpack -u https://github.com/my-org/jenkins-x-kubernetes
? Defaulting workload build pack: Kubernetes Workloads: Automated CI+CD with GitOps Promotion
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
```

JX version:
```
NAME               VERSION
jx                 2.0.1284
Kubernetes cluster v1.15.7
kubectl            v1.17.3
helm client        2.16.3
git                2.21.1 (Apple Git-122.3)
Operating System   Mac OS X 10.15.3 build 19D76
```
On AKS cluster, manually created.

@vfarcic FYI

/remove-lifecycle rotten

**Comment by vfarcic** [comment]
I think that those are different issues, but still related. In my case, when I opened this ticket, the command worked, but it did not store the change in the `dev` repo. In your case it's worse since it doesn't do anything (if I understood it correctly).

**Comment by hervelemeur** [comment]
> I think that those are different issues, but still related. In my case, when I opened this ticket, the command worked, but it did not store the change in the `dev` repo. In your case it's worse since it doesn't do anything (if I understood it correctly).

Yes, correct. Do you want I open a new issue?
