### ISSUE TITLE
Velero crashing in fresh jx boot install

### ISSUE THREAD

**Issue by sstubbs** [jenkins-x/jx#6384]
### Summary 
Velero crashes on initial install

### Steps to reproduce the behavior
jx create cluster gke --skip-installation
add
```
storage:
  backup:
    enabled: true
    url: gs://bucket-name
velero:
  namespace: velero
```
to jx-requirements.yaml
### Expected behavior
pod to start normally

### Actual behavior
pod crashes with the following:
```
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": unable to locate ObjectStore plugin named velero.io/gcp
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.1094
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

### Operating system / Environment
MacOS Catalina

**Comment by masseybradley** [comment]
Possibly related to [this issue](https://github.com/vmware-tanzu/velero/issues/1363).

**Comment by jstrachan** [comment]
@sstubbs  doesn downgrading your `kubectl` to 1.14-1.15 help?

**Comment by bbhuston** [comment]
@jstrachan I hit the exact same issue as the OP.  I tried downgrading kubectl from 1.17.x to 1.16 (and then 1.15),  then deleting/reinstalling velero (via `jx step helm delete velero --purge --namespace velero` etc).  However, velero is still throwing the exact same error.

I actually also tried updating the velero `backupStorageLocation` custom resource directly and adding a `provider: velero.io/gcp` field, as suggested by @masseybradley linked issue, but this changed nothing either.

Anyone else following this issue any additional suggestions or hunches?

**Comment by masseybradley** [comment]
@bbhuston I tested with `v1.15` as well and no dice, same error. I ended up installing `velero` outside of `jx` (https://github.com/vmware-tanzu/velero-plugin-for-gcp) for the time being.

**Comment by bbhuston** [comment]
> @bbhuston I tested with `v1.15` as well and no dice, same error. I ended up installing `velero` outside of `jx` following their [doc](https://github.com/vmware-tanzu/velero-plugin-for-gcp) for the time being. Started hitting this error towards the end of this [thread](https://kubernetes.slack.com/archives/C9MBGQJRH/p1578998986427200).

@masseybradley  Thanks for the tips and the slack tread.  Will give the separate install a try.

**Comment by abayer** [comment]
Hi @bbhuston - I think we do now have better velero support - have you tried recently?

**Comment by bbhuston** [comment]
Yes, the issue appears to be fixed now!  I have done two fresh installs on
GKE and velero worked out of the box.  Thanks!

**Comment by deanesmith** [comment]
Closing per last comment
