### ISSUE TITLE
jx boot failed on eks existing cluster

### ISSUE THREAD

**Issue by omerlh** [jenkins-x/jx#6388]
### Summary 
I have an existing EKS cluster, created using `eksctl`. I tried to run `jx boot`, but the command failed with:
```
error: You are not currently connected to a cluster, please connect to the cluster that you intend to jx boot
Alternatively create a new cluster using jx create cluster
```
Looking at the code, it looks like like it trying to run `kubectl get ns`, which failed for an unclear reason (the error is not printed, and I wasn't able to compile the code and check it). When running `kubectl get ns` from the same terminal, I was able to get all the namespaces correctly.

### Steps to reproduce the behavior
1. Provision a cluster with `eksctl`
2. Run `jx boot`

### Expected behavior
Jenkins x boot correctly.

### Actual behavior
Jenkins x failed to boot

### Jx version

The output of `jx version` is:

```
Unable to connect to the server: dial tcp: i/o timeout 🤷‍♂ 
```

I just installed it today with brew... so I guess latest...

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

### Operating system / Environment

MacOS

**Comment by deanesmith** [comment]
Hi @omerlh, can you share the output here of running ```jx version```?

**Comment by dgozalo** [comment]
Can you get any output from `kubectl` executed outside of Jenkins X? For example, can you execute `kubectl get nodes` and make it work?

**Comment by omerlh** [comment]
Yeah, kubectl get nodes works as expected - return the expected results without any issue. As I wrote on the issue, even running `jx version` resulted in an error.

**Comment by heyMP** [comment]
@omerlh I'm having the same issue.  Running `jx version` results in an error.  I'm getting the following error.

```bash
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
FATAL: Your current helm version v3 is not supported. Please downgrade to helm v2.
```

Do you have Helm version 3 installed?

**Comment by omerlh** [comment]
Not at the time I had this issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by q13117god** [comment]
Did you try to run 'jx step verify preinstall' before running 'jx boot'?

**Comment by omerlh** [comment]
Pretty sure that in my case all commands fail with the same error...

**Comment by vivekthangathurai** [comment]
I am facing the same issue. any solution for this? The cluster is already provisioned
