### ISSUE TITLE
failed to add new git provider after boot

### ISSUE THREAD

**Issue by jiangytcn** [jenkins-x/jx#6391]
### Summary 
deploy jx with ghe, but failed to add extra git provider with 

jx create git server -k gitea -u http://github.192.168.1.12.nip.io -n abc

### Steps to reproduce the behavior
1. deploy gitea
1. deploy jx with boot and ghe setting
2. add new git provider with `gitea`
jx create git server -k gitea -u  _git_provider_url_ -n localgit

### Expected behavior
successfully add new git provder

### Actual behavior
failed with 
`error: failed to save GitAuthConfigService: current user for "http://github.192.168.1.12.nip.io" server is empty
`
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1094
Kubernetes cluster v1.16.3-k3s.2
kubectl            v1.17.0
helm client        Client: v2.14.2+ga8b13cc
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

k3s

### Operating system / Environment
VERSION="18.04.3 LTS (Bionic Beaver)"

**Comment by deanesmith** [comment]
Hi @jiangytcn, This is an interesting and challenging request.  We would like to understand the use case that would warrant multiple git providers.  Could you elaborate?
