### ISSUE TITLE
jx create quickstart fails with bitbucket

### ISSUE THREAD

**Issue by valiksb** [jenkins-x/jx#6395]
### Summary 
Trying to create a new quickstart project fails when using bitbucketcloud

### Steps to reproduce the behavior
`jx create quickstart --pack gradle --git-provider-url https://bitbucket.org --org zebrathings`

### Expected behavior
repo created locally and pushed to remote and pipelines started

### Actual behavior
repo created locally and pushed to remote, but it fails on one of the pipelines
What is strange is that it tries to find a list of PR requests on the wrong organization

**jenkinsx-cto-si/environment-bna-on-prem-jenkins-x-dev** instead of using **zebrathings/environment-bna-on-prem-jenkins-x-dev**

`? select the quickstart you wish to create spring-boot-http-gradle
Using Git provider bs at https://bitbucket.org
? Do you wish to use valiks as the Git user name? Yes
? Using organisation: zebrathings
? Enter the new repository name:  bna-test-1
Creating repository zebrathings/bna-test-1
Generated quickstart at /Users/user/Documents/zebra/incubation/bitbucket/bna-test-1
 NO charts folder /Users/user/Documents/zebra/incubation/bitbucket/bna-test-1/charts/spring-boot-http-gradle
Created project at /Users/user/Documents/zebra/incubation/bitbucket/bna-test-1
The directory /Users/user/Documents/zebra/incubation/bitbucket/bna-test-1 is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
trying to use draft pack: gradle
selected pack: /Users/user/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/gradle
replacing placeholders in directory /Users/user/Documents/zebra/incubation/bitbucket/bna-test-1
app name: bna-test-1, git server: bitbucket.org, org: zebrathings, Docker registry org: bna-on-prem-jenkins-x
skipping directory "/Users/user/Documents/zebra/incubation/bitbucket/bna-test-1/.git"
Pushed Git repository to https://bitbucket.org/zebrathings/bna-test-1
error: failed to create Pull Request on the development environment git repository https://bitbucket.org/zebrathings/environment-bna-on-prem-jenkins-x-dev.git: unable to create pull request: failed to create PR for base master and head branch bump-resource-version-4debe482-2bac-11ea-bcf9-acde48001122 from temp dir /var/folders/zs/t3g323s13x1dj86xw7lx8nkxz78dwc/T/create-pr391683225: finding existing PRs using filter updatebot on repo /environment-bna-on-prem-jenkins-x-dev: listing open pull requests on /environment-bna-on-prem-jenkins-x-dev: failed to find repository jenkinsx-cto-si/environment-bna-on-prem-jenkins-x-dev: Status: 404 Not Found, Body: {"type": "error", "error": {"message": "Repository jenkinsx-cto-si/environment-bna-on-prem-jenkins-x-dev not found"}}`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1094
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.15.2
helm client        Client: v2.13.1+g618447c
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

GKE

`jx create cluster gke --verbose -n jenkins-x-cluster --zone us-central1-a --machine-type n1-standard-2 --min-num-nodes 3 --max-num-nodes 5 --skip-installation`

### Operating system / Environment

MacOsX

**Comment by valiksb** [comment]
addiitional note I tried with ` jx import --git-provider-url https://bitbucket.org --org zebrathings` got exactly same result

**Comment by sanigo** [comment]
Similar error with gitea.

**Comment by wuestkamp** [comment]
same with gitlab

**Comment by oonyeje-bside** [comment]
+1

**Comment by michaeljohnbennett** [comment]
I see something similar but I can get this to install with bitbucketcloud for a quickstart but when it runs it fails:

```
> jx get activity -f quickstart-spring-boot -w

xxxx/quickstart-spring-boot/master #1                     4m20s     4m9s Failed
  meta pipeline                                                  4m20s      45s Succeeded
    Credential Initializer Vstzz                                 4m20s       0s Succeeded
    Working Dir Initializer 9xc2g                                4m20s       1s Succeeded
    Place Tools                                                  4m19s       1s Succeeded
    Git Source Meta xxxx Quickstart Spr L7zl8 Gq864       4m18s       8s Succeeded https://bitbucket.org/xxxx/quickstart-spring-boot.git
    Git Merge                                                    4m10s       0s Succeeded
    Merge Pull Refs                                              4m10s       1s Succeeded
    Create Effective Pipeline                                     4m9s      21s Succeeded
    Create Tekton Crds                                           3m48s      13s Succeeded
  from build pack                                                3m32s    3m21s Failed
    Credential Initializer Kq5lq                                 3m32s       0s Succeeded
    Working Dir Initializer Bx2vv                                3m32s       1s Succeeded
    Place Tools                                                  3m31s       1s Succeeded
    Git Source xxxx Quickstart Spring B 9pbbd 7rxrb       3m30s    1m36s Succeeded https://bitbucket.org/xxxx/quickstart-spring-boot.git
    Git Merge                                                    1m54s       1s Succeeded
    Setup Jx Git Credentials                                     1m53s       0s Succeeded
    Build Gradle Build                                           1m53s    1m34s Succeeded
    Build Container Build                                          19s       6s Failed
    Build Post Build                                               13s       1s NotExecuted
    Promote Changelog                                              12s       0s NotExecuted
    Promote Helm Release                                           12s       1s NotExecuted
    Promote Jx Promote                                             11s       0s NotExecuted
```

and then when I run the logs to see whats going on I see this:

```
>jx get build logs xxxx/quickstart-spring-boot/master

error: there was a problem obtaining the log file from the github pages URL https://raw.githubusercontent.com/xxxx/quickstart-spring-boot/gh-pages/jenkins-x/logs/xxxx/quickstart-spring-boot/master/1.log:

status 404 Not Found when performing GET on https://raw.githubusercontent.com/xxxx/quickstart-spring-boot/gh-pages/jenkins-x/logs/xxxx/quickstart-spring-boot/master/1.log
```

I'm not using github so why is it thinking my logs should be there?

I can raise this a separate Issue if you think this is another problem.

**Comment by johnamac7** [comment]
I'm using a local gitlab instance for my code repo, so also find it strange that logs are somewhere else....

I'm trying to find out why the Build Container is failing, from the activity output

 ../jx/build/jx get activity -f jmc-new-qt-proj -w
STEP                                                       STARTED AGO DURATION STATUS
tester/jmc-new-qt-proj/master #1                              47h44m8s    1m10s Failed
  meta pipeline                                               47h44m8s      32s Succeeded
    Credential Initializer Dwk7z                              47h44m8s       0s Succeeded
    Working Dir Initializer Q9tmt                             47h44m8s       1s Succeeded
    Place Tools                                               47h44m7s       1s Succeeded
    Git Source Meta Tester Jmc New Qt Proj Mas Vps7w Jkk6p    47h44m6s       3s Succeeded http://dungloe.jnpr.belfast/tester/jmc-new-qt-proj.git
    Git Merge                                                 47h44m3s       2s Succeeded
    Merge Pull Refs                                           47h44m1s       1s Succeeded
    Create Effective Pipeline                                 47h44m0s      14s Succeeded
    Create Tekton Crds                                       47h43m46s      10s Succeeded
  run make                                                   47h43m34s      26s Succeeded
    Credential Initializer Dnjm2                             47h43m34s       0s Succeeded
    Working Dir Initializer G2dvn                            47h43m34s       1s Succeeded
    Place Tools                                              47h43m33s       1s Succeeded
    Create Dir Workspace 2rkfl                               47h43m32s       4s Succeeded
    Git Source Tester Jmc New Qt Proj Master Txd42 Z9cqf     47h43m28s       0s Succeeded http://dungloe.jnpr.belfast/tester/jmc-new-qt-proj.git
    Git Merge                                                47h43m28s       2s Succeeded
    Setup Jx Git Credentials                                 47h43m26s       1s Succeeded
    Build Make Build                                         47h43m25s      15s Succeeded
    Source Mkdir Tester Jmc New Qt Proj Master Txd42 Cqdzf   47h43m10s       1s Succeeded
    Source Copy Tester Jmc New Qt Proj Master Txd42 Nzg56     47h43m9s       1s Succeeded
  everything else                                             47h43m7s       9s NotExecuted
    Credential Initializer 2tnh9                              47h43m7s       0s Succeeded
    Working Dir Initializer Dktqt                             47h43m7s       1s Succeeded
    Place Tools                                               47h43m6s       1s Succeeded
    Create Dir Workspace Rw75b                                47h43m5s       4s Succeeded
    Source Copy Workspace Pw5nv                               47h43m1s       1s Succeeded
    Build Container Build                                     47h43m0s       1s Failed
    Build Post Build                                         47h42m59s       0s NotExecuted
    Promote Changelog                                        47h42m59s       0s NotExecuted
    Promote Helm Release                                     47h42m59s       0s NotExecuted
    Promote Jx Promote                                       47h42m59s       1s NotExecuted

but when I attempt to get the logs, there is an error status 404 returned...

 ../jx/build/jx get build logs tester/jmc-new-qt-proj/master
error: there was a problem obtaining the log file from the github pages URL https://raw.githubusercontent.com/tester/jmc-new-qt-proj/gh-pages/jenkins-x/logs/tester/jmc-new-qt-proj/master/1.log: status 404 Not Found when performing GET on https://raw.githubusercontent.com/tester/jmc-new-qt-proj/gh-pages/jenkins-x/logs/tester/jmc-new-qt-proj/master/1.log

**Comment by abayer** [comment]
So we've tweaked the logic here for log retrieval - there's still a problem with GitLab (#7216), and I'm verifying whether BitBucket Server log retrieval works correctly. But actual import/execution does work for both GitLab and BitBucket Server with current jx (i.e., v2.1.42) and Lighthouse (i.e., v0.0.605).

**Comment by abayer** [comment]
Yup, `jx get build logs` with BitBucket Server works, so I'm closing this - follow #7216 for GitLab.

**Comment by abayer** [comment]
argh, no, I'm wrong. I'll work on this today.

**Comment by abayer** [comment]
Actually, I'm gonna close this since everything _but_ log retrieval works, and I've opened #7217 for that.
