### ISSUE TITLE
In jenkins PR job `jx preview --app spring-boot-http-gradle --dir ../..` leading to Error: ImagePullBackOff

### ISSUE THREAD

**Issue by hectoralicea** [jenkins-x/jx#6396]
### Summary 
In an AKS instance of Jenkins-X the prior build of master worked great, but when I went to make a simple change to test out the PR, i get the following pod error for the preview build.

```
  Type     Reason   Age                     From                               Message
  ----     ------   ----                    ----                               -------
  Normal   BackOff  17m (x4601 over 17h)    kubelet, aks-enttest05-23301334-0  Back-off pulling image "enttestaks05.azurecr.io/hectoralicea/spring-boot-http-gradle:0.0.0-SNAPSHOT-PR-1-2"
  Normal   Pulling  7m38s (x210 over 17h)   kubelet, aks-enttest05-23301334-0  Pulling image "enttestaks05.azurecr.io/hectoralicea/spring-boot-http-gradle:0.0.0-SNAPSHOT-PR-1-2"
  Warning  Failed   2m39s (x4666 over 17h)  kubelet, aks-enttest05-23301334-0  Error: ImagePullBackOff
```

### Steps to reproduce the behavior
`jx create quickstart` and deploy the app spring-boot-http-gradle
make a change to the code and initiate a pull request.
PR job should work

### Expected behavior
PR job should work

### Actual behavior
```
Updating PipelineActivities hectoralicea-spring-boot-http-gradle-pr-1-2 which has status Running

WARNING: preview application http://spring-boot-http-gradle.jx-hectoralicea-spring-boot-http-gradle-pr-1.XXX.XXX.XXX.XXX.nip.io not available, error was 503 503 
```
`kubectl describe pod` of the preview pod give the following error
```
Events:
  Type     Reason   Age                     From                               Message
  ----     ------   ----                    ----                               -------
  Normal   Pulling  14m (x210 over 17h)     kubelet, aks-enttest05-23301334-0  Pulling image "enttestaks05.azurecr.io/hectoralicea/spring-boot-http-gradle:0.0.0-SNAPSHOT-PR-1-2"
  Warning  Failed   9m52s (x4666 over 17h)  kubelet, aks-enttest05-23301334-0  Error: ImagePullBackOff
  Normal   BackOff  4m46s (x4688 over 17h)  kubelet, aks-enttest05-23301334-0  Back-off pulling image "enttestaks05.azurecr.io/hectoralicea/spring-boot-http-gradle:0.0.0-SNAPSHOT-PR-1-2"
```

### Jx version

The output of `jx version` is:

```
MacBook-Air:spring-boot-http-gradle hector$ jx version
NAME               VERSION
jx                 2.0.1094
jenkins x platform 2.0.1795
Kubernetes cluster v1.14.8
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.0
Operating System   Mac OS X 10.14.6 build 18G1012
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

Created AKS cluster using terraform script.  Appears Jenkins-X build, built the azure container registry which is having issues.

### Operating system / Environment

MacOS Mojave 10.14.6 (18G1012)

**Comment by hferentschik** [comment]
Hi @hectoralicea, how did you configure the Docker registry and is it a private registry? Could you also supply your Terraform script? This would help us to understand/debug the problem better.

**Comment by hectoralicea** [comment]
I was able work around this issue by creating the AKS using az CLI rather than terraform.  When I move this to terraform again, I will see if I run into this issue again and provide more info.
