### ISSUE TITLE
`jx version` fails because it tries to access IP Address 10.213.2.100

### ISSUE THREAD

**Issue by Vaccano** [jenkins-x/jx#6398]
### Summary 
Running `jx version` fails with the following message:

>Unable to connect to the server: dial tcp 10.213.3.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Steps to reproduce the behavior
1. Open PowerShell running as an admin
2. Run `choco install jenkins-x`
3. Run `jx version`

### Expected behavior

That the version will be listed.  

(And that it would not need to call any kind of IP address just to show the version.)

### Actual behavior

An error message stating:

>Unable to connect to the server: dial tcp 10.213.3.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Jx version

The output of `jx version` is:

Well, the `choco install jenkins-x` says the version is ```v2.0.1094```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
None at this point.  (I am attempting to make one using `jx`.

### Operating system / Environment
Windows 10 

### Additional Notes ###
I am running behind my companies firewall.  I don't know what the 10.213.3.100 IP address is, but it is possible it is blocked.  

Most of our internal/private IP addresses start with 10, so I it is possible that it is not allowing this address to be looked for on the internet.

**Comment by tdcox** [comment]
This relates to https://github.com/jenkins-x/jx/issues/5908

The jx client now assumes that there is always an active jx cluster associated with the current context however this assumption is invalid. As a result, even simple invocations such as `jx -h` will attempt to make a server connection, hang for a period of time and then fail.

**Comment by hferentschik** [comment]
To determine the version of `jx` you want to run `jx --version` which just prints the version of the `jx` binary.

**Comment by deanesmith** [comment]
Hi @Vaccano, does the above comment address your concern?
