### ISSUE TITLE
JX Upgrade Boot to detect and PR any app versions using the version stream

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#6403]
### Summary
`jx upgrade boot` should _detect_ and _PR_ any app versions using the version stream.  Ideally, the functionality would replace the legacy `jx upgrade addons` command with more elegant and consistent user experience.

```
~ jx upgrade boot -h
This command creates a pr for upgrading a jx boot gitOps cluster, incorporating changes 
to the boot config and version stream ref

Examples:
  # create pr for upgrading a jx boot gitOps cluster
  jx upgrade boot
Options:
  -d, --dir='': the directory to look for the Jenkins X Pipeline and requirements
      --latest-release=false: upgrade to latest release tag
      --upgrade-version-stream-ref='master': a version stream ref to use to upgrade to
Usage:
  jx upgrade boot [flags] [options]
Use "jx options" for a list of global command-line options (applies to all commands).
```

### References

 - [Slack thread on the topic.](https://kubernetes.slack.com/archives/C9MBGQJRH/p1578005662224300)

**Comment by macox** [comment]
If an app version has changed within the version stream and that version of the version stream has been released then `jx upgrade boot` should pick it up. Is this not the case?
