### ISSUE TITLE
github webhook last delivery was not successful failure when receiving data from the peer

### ISSUE THREAD

**Issue by sushil10jadhav** [jenkins-x/jx#6404]
I'm trying to set up webhook between jenkins instlalled on AWS instance and github but always getting error ->
github webhook last delivery was not successful failure when receiving data from the peer

Can  you advice ?

**Comment by hferentschik** [comment]
Are you using a classic Jenkins setup? Are you even using Jenkins X (Tekton)? 
This is very little information to reproduce the issue. We need more context ;-)
