### ISSUE TITLE
Non-interactive jx boot

### ISSUE THREAD

**Issue by TarekAS** [jenkins-x/jx#6406]
I create my clusters using Terraform in a CI Pipeline. I want Terraform to automatically install jx inside a cluster after creating it. But since ```jx boot``` is interactive, this is not possible.

Is there some recommended way to achieve this?

**Comment by deanesmith** [comment]
Related to https://github.com/jenkins-x/jx/issues/4683

**Comment by hferentschik** [comment]
Provided you have a boot config with the required fields already filled out, you should be able to boot non-interactively via `jx -b boot`.
