### ISSUE TITLE
error: no auth config found for secret "gitAuth.yaml"

### ISSUE THREAD

**Issue by scaratec** [jenkins-x/jx#6414]
### Summary 
When I run `jx import` I get the following error message:
```
error: no auth config found for secret "gitAuth.yaml"
```
The file `gitAuth.yaml` is not there and I don't know what to do. I've already tried providing username, token, url, git kind etc. via command line flag. Without success.

### Steps to reproduce the behavior
Run `jx import` ... but I assume I have a local issue here that can't be simply reproduced ...

### Expected behavior
Import my project

### Actual behavior
Exits with the error message:
```
error: no auth config found for secret "gitAuth.yaml"
```
### Jx version

The output of `jx version` is:

```
jx                 2.0.1102
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.13.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

Using gitlab with lighthouse here.

### Kubernetes cluster

I'm using a GKE cluster installed via:
```
jx create cluster gke \
--cluster-name='jx-demo' \
--skip-installation \
--preemptible
```

### Operating system / Environment

Ubuntu 18.04.3 LTS

**Comment by deanesmith** [comment]
You might need to elevate your permissions - `sudo jx import`

**Comment by deanesmith** [comment]
Hi @scaratec, did `sudo jx import` allow you to import your project?

**Comment by scaratec** [comment]
@deanesmith 

Now I'm getting this:

```
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /root/.jx/jenkins-x-versions
error: failed to load quickstarts: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```
