### ISSUE TITLE
jx does not respect `PipelineSecrets` from myvalues.yaml

### ISSUE THREAD

**Issue by tycoonm** [jenkins-x/jx#6416]
### Summary 
jx boot does not respect `PipelineSecrets.DockerConfig`, `PipelineSecrets.MavenSettingsSecurityXML` and `PipelineSecrets. MavenSettingsXML`properties in myvalues.yaml. The mentioned properties are not updated in `jenkins-docker-cfg` and `jenkins-maven-settings` secrets accordingly.

### Steps to reproduce the behavior
```
cat <<EOF > myvalues.yaml 
PipelineSecrets:
  DockerConfig: |-
    {
        "auths": {
            "nexus.fluxtop.local": {
                "auth": "XXXXX="
            }
        }
    }
  MavenSettingsSecurityXML: |-
    <settingsSecurity>
       <master>{XXXXX}</master>
    </settingsSecurity>
  MavenSettingsXML: |-
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
   </settings>
EOF
```

### Expected behavior
Secrets `jenkins-docker-cfg` and `jenkins-maven-settings` are updated.

### Actual behavior
Secrets aren't being updated

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.1102
Kubernetes cluster v1.17.0
kubectl            v1.17.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.14.6 build 18G103


verifying packages

```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

On-Premise

### Operating system / Environment

macOS Mojave
Version: 10.14.6

**Comment by garethjevans** [comment]
Hi @tycoonm, `jx boot` is designed to be a complete declarative install, with this in mind we expect all config to be defined inside the dev environment repository (where `jx boot` is run from).  As far as I know, local `myvalues.yaml` files are not supported in `jx boot` - I'd suggest you make the required change here - https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/jenkins-x-platform/values.tmpl.yaml instead.

**Comment by tycoonm** [comment]
Thank you very much. It did work.
