### ISSUE TITLE
Namespace and Service deployment is left behind after PR has been merged

### ISSUE THREAD

**Issue by ichekrygin** [jenkins-x/jx#642]
### Overview
Note: I am not sure if this is intended functionality.

#### Steps to repro:
- create a PR against a GitHub project (fork) 
- observe `jx` to build and deploy a PR version of the service into PR a dedicated namespace: 
  - `jx-myorg-golang-http-pr-1   Active    1d`
- merge the PR and delete the brach
- observe `jx` build and deploy a new version into `staging` environment

#### Expectation
- `jx-myorg-golang-http-pr-1` namespace and deployments removed

#### Actual
- `jx-myorg-golang-http-pr-1` is left behind

**Comment by jstrachan** [comment]
this is a duplicate of https://github.com/jenkins-x/jx/issues/420 - hopefully we can fix it very soon.

For now the workaround is: `jx delete env nameOfPreviewEnv`

**Comment by ichekrygin** [comment]
Closing as duplicate
