### ISSUE TITLE
jx import is not respecting the gitlab username

### ISSUE THREAD

**Issue by scaratec** [jenkins-x/jx#6421]
### Summary 
When I import a project from gitlab, `jx import` uses the users full name from the gitlab profile instead of the actual username. This causes the following error message:

```
Command run was `jx import -u https://gitlab.scaratec.com/jx-demo/website.git --no-draft`; Head: bump-resource-version-e28dea65-30ab-11ea-bfeb-a0a4c5cc9f11; Base: master; Labels: updatebot; Git Repo: : GET https://gitlab.scaratec.com/api/v4/users/Randy Gupta/projects: 404 {message: 404 User Not Found}
```
The API call to the gitlab server is the targeting the worng URL.

### Steps to reproduce the behavior
Change the full name of the gitlab user to something different than the gitlab username.

### Expected behavior
Use the gitlab username and not the full name.

### Actual behavior
Make the API call to the full name which breaks the URL and target to the wrong resource.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1102
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.13.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
I think the problem is most likely in the `go-gitlab` library we use for Gitlab API calls. There are long-term plans to move everything to use `go-scm` instead, but there may be a workaround that can be done in the shorter term.

**Comment by abayer** [comment]
Hmm, might not be the `go-gitlab` library. It may actually be a problem in what we're storing as the username...but I'm not entirely clear on where we're storing that, let alone how we're determining what to store!

**Comment by tdcox** [comment]
`kubectl get users -o yaml` returns some odd data here, with partially filled fields.

**Comment by deanesmith** [comment]
https://github.com/jenkins-x/jx/issues/6209
