### ISSUE TITLE
builds fail (quickstarts, springboot) on fresh cluster with org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: jenkins-x-git

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#643]
I created a fresh cluster, wiped out ~/.jx etc. 

Running `jx quickstart` for nodejs, or creating the spring boot app results in a failed master pipeline run (see below). The actual reported reason is 

```
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
```

But I think that is indicative that the post build action is actually invalid (the cleanup workspace) and would never work, but the actual error is 
`org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: jenkins-x-git`

note that `jx status` is all ok and other things seem reasonable. 

```
jx version
NAME               VERSION
jx                 1.1.73
jenkins x platform 0.0.624
kubernetes cluster v1.8.8-gke.0
kubectl            v1.10.0
helm client        v2.8.2+ga802316
helm server        v2.8.2+ga802316
git                git version 2.14.1
```

Full log below: 

```
First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: jenkins-x-git
	at org.jenkinsci.plugins.pipeline.modeldefinition.model.CredentialsBindingHandler.forId(CredentialsBindingHandler.java:119)
	at org.jenkinsci.plugins.pipeline.modeldefinition.model.CredentialsBindingHandler$forId.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:19)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:385)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.callClosureForMapEntry(CpsDefaultGroovyMethods:5226)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2107)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:383)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:70)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:492)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.checkoutAndRun(jar:file:/var/jenkins_home/plugins/pipeline-model-extensions/WEB-INF/lib/pipeline-model-extensions.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/agent/CheckoutScript.groovy:63)
```

**Comment by jstrachan** [comment]
I wonder if there is a credential called `jenkins-x-git` in your Jenkins? Is there a `jenkins-x-git` secret also?

We've made a few changes to try make things more flexible for using different git repositories and something may have broken. Am about to do a bit more testing and release a new version thats hopefully a little better...

**Comment by jstrachan** [comment]
@michaelneale I wonder if a quick workaround is....

    jx delete git token -n GitHub myusername
    jx create git token -n GitHub myusername

(the name for github could be `github` in the above - depends on the contents of your `~/.jx/gitAuth.yaml`)

then re-import your project again? There should be a `Secret/Credential` created called `jx-pipeline-git-github-github` which should then be referenced as the credential name in the imported multi branch project (if you look in the `.../config.xml` file you should see the credentialid

**Comment by michaelneale** [comment]
@jstrachan no there is no credential called `jenkins-x-git` -  which makes sense according to the error. 

Maybe something went wrong creating it - ~/.jx/gitAuth.yaml has the right stuff in it. 

I ran the above, and no change. There is still only one credential in the system for `jenkins-x-chartmuseum` at the global level. I can see the (multibranch) job is configured for something else however, but not sure what it's id is. 
```
jx create git token -n GitHub michaelneale
Created user michaelneale API Token for git server GitHub at https://github.com
```

**Comment by jstrachan** [comment]
@michaelneale thanks - you're using the latest jx right? 
```
jx version
```

**Comment by michaelneale** [comment]
yes (version in description - 1.1.73 - brand new as of today). 

I checked the config.xml: 

```
<source class="org.jenkinsci.plugins.github_branch_source.GitHubSCMSource" plugin="github-branch-source@2.3.1">
<id>b50ee5d4-cb45-42de-9140-d79330bab9ac</id>
<credentialsId>jx-pipeline-git-github-github</credentialsId>
<repoOwner>michaelneale</repoOwner>
<repository>demo</repository>
<traits>
<org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
<strategyId>1</strategyId>
</org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
<org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
<strategyId>1</strategyId>
</org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
<org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
<strategyId>1</strategyId>
<trust class="org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustContributors"/>
</org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
<jenkins.scm.impl.trait.RegexSCMHeadFilterTrait plugin="scm-api@2.2.6">
<regex>master|PR-.*|feature.*</regex>
</jenkins.scm.impl.trait.RegexSCMHeadFilterTrait>
</traits>
</source>
```

**Comment by jstrachan** [comment]
ah great - so its using the new credentials `jx-pipeline-git-github-github` object - great! so not sure why the build is failing with missing `jenkins-x-git` credential being missing?

**Comment by michaelneale** [comment]
@jstrachan oh - so where is the actual credential stored? I couldn't see it on any scope I looked at from the GUI. 

Also = I think the issue may be in the Jenkinsfile in the quickstarts/packs: 

https://github.com/michaelneale/demo/blob/master/Jenkinsfile

Note that it refers to the incorrect id - what should it be?

**Comment by jstrachan** [comment]
Doh! yeah, we don't need that stuff in the `Jenkinsfile` any more with the new `Secrets` + the kubernetes-credentials-provider supplying credentials from Secrets etc.

BTW there's a bug in the current `kubernetes-credentials-provider` plugin that doesn't show Secret based Credentials in the UI - should be fixed now in 0.0.9.

Am just testing out the latest platform + build packs which remove that use of `jenkins-x-git` credential; if this works I'll push it out which should hopefully fix all this stuff once and for all...

**Comment by jstrachan** [comment]
As a workaround while the next release is out you could try remove this line:
https://github.com/michaelneale/demo/blob/master/Jenkinsfile#L8

also these lines https://github.com/michaelneale/demo/blob/master/Jenkinsfile#L10-L11

**Comment by jstrachan** [comment]
@michaelneale new release is out with new platform + build packs that no longer use the `jenkins-x-git` credential. Am just testing here to make sure things are all OK but if you're feeling brave you could try create a new cluster?

This should come with `skaffold` too as an added bonus

**Comment by michaelneale** [comment]
update works. 

This may cause people some confusion, but if they do get stuck: 

delete all `GIT_*` variables from the `environment {` section.
