### ISSUE TITLE
Configuration changes not reflected in static Jenkins

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#6433]
### Steps to reproduce the behavior

1. Install Jenkins-X with `jx boot` and have `webhook: jenkins`.

1. Change Jenkins-X configuration of Jenkins and run `jx boot`.

Examples of such configuration are changes in pod templates coming from `jx upgrade boot` and changing `cluster.registry` in  `jx-requirements.yml`.

### Expected behavior

Jenkins is updated with the new configuration. Probably through a restart.

### Actual behavior

Jenkins is not updated.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1084
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.16.2
helm client        Client: v2.14.1+g5270352
git                2.16.2
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

**Comment by hferentschik** [comment]
Any chance you can provide a concrete example of the change you are making?

**Comment by msvticket** [comment]
I have given 2 examples.
