### ISSUE TITLE
Documentation Feedback - Relationship of "create" vs "install jx" vs "boot" vs "import"

### ISSUE THREAD

**Issue by GLStephen** [jenkins-x/jx#6435]
I think that the current documentation fundamentally misses conveying the relationship of the following activities. Mind you, this is from a person taking a completely greenfield look at Jenkins X, Kubernetes/Docker, etc. to replace our testing and code deployment process. I'm learning all of these together, but I have a lot of development experience. So, take this feedback with that grain of salt.

1. Create the *cluster* on the *host*
2. Install JX on the *client* machine
2. Boot the JX *environments* into the *cluster* from the *client* machine
3. Import application code *from x,y,z* into the JX *dev environment*

I think this first sequence and a few other high level, abstract, not technology (gke, aws, etc.) specific loops need to be better outlined earlier in the docs.  Currently it takes consuming and understanding the entire documentation set to see this whole end to end process. Which is fine if you have a good context of understanding and you're just swapping out a piece for another (which I suspect many are in the Jenkins space).

In addition, a description of what would exist at the end of this would be nice. i.e.: After doing 1,2,3 and 4 you'll have x, y and z in each of the environments.

Then a very high level description of two things:

1. Moving/promoting *cluster* config changes through the *environments*
2. Moving/promoting code changes through the *environments*

Then each of these 3 high level sequences and loops should be the backbone of the terms and such. This makes the docs more task oriented.

The whole space of kubernetes and cloud infra has major issues with switching the context from which docs are coming from and leading to confusion I think there is a bit of this in the current docs related to the above. The rigor with which terms are disambiguated and used properly in other contexts is really key, but it's understandably very hard to identify.

**Comment by deanesmith** [comment]
@dgozalo can you make note of this for the EKS docs updates?
