### ISSUE TITLE
Give proper user feedback when try to import project using git ssh

### ISSUE THREAD

**Issue by guitcastro** [jenkins-x/jx#6438]
### Summary 

It seems that import a project when git remotes are configured to use ssh keys fail with `error: failed to start pipeline build`. We should verify if git remotes are configured to use `https` and display a proper feedback if not. 

### Summary 
When trying to import my spring boot project to a fresh install of jenkins-x I got the following error: 

```
➜  blu-api git:(develop) jx import --verbose
? Which Git service do you wish to use https://gitlab.com
WARNING: No username defined for the current Git server!
? Do you wish to use guitcastro as the Git user name: Yes
trying to use draft pack: docker
selected pack: /Users/guilhermecastro/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/docker
replacing placeholders in directory /Users/guilhermecastro/Documents/blu-api
app name: blu-api, git server: gitlab.com, org: blubybs2, Docker registry org: blubybs2
skipping ignored file "/Users/guilhermecastro/Documents/blu-api/.DS_Store"
skipping directory "/Users/guilhermecastro/Documents/blu-api/.git"
skipping directory "/Users/guilhermecastro/Documents/blu-api/.gradle"
skipping directory "/Users/guilhermecastro/Documents/blu-api/.idea/dataSources"
skipping ignored file "/Users/guilhermecastro/Documents/blu-api/.idea/dataSources.local.xml"
skipping ignored file "/Users/guilhermecastro/Documents/blu-api/.idea/gradle.xml"
skipping ignored file "/Users/guilhermecastro/Documents/blu-api/.idea/workspace.xml"
skipping directory "/Users/guilhermecastro/Documents/blu-api/build"
skipping directory "/Users/guilhermecastro/Documents/blu-api/out"
skipping directory "/Users/guilhermecastro/Documents/blu-api/postgres"
DEBUG: Finding service url for hook in namespace jx
DEBUG: Couldn't find service url, attempting to look up via ingress
DEBUG: found service url http://hook-jx.blubybs2.com
DEBUG: have SourceRepository: blubybs2-blu-api
regenerated Prow configuration
DEBUG: creating meta pipeline client
DEBUG: cloning version stream url: https://github.com/jenkins-x/jenkins-x-versions.git ref: v1.0.287 into /var/folders/3q/9m2j4w1x47j980hh6djhn2f80000gn/T/jx-version-repo-052707947
error: failed to start pipeline build
```

### Steps to reproduce the behavior

just use ` jx import`

### Expected behavior

Successfully run the pipeline 

### Actual behavior

The pipeline fails

### Jx version

The output of `jx version` is:

```
jx                 2.0.1104
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.14.8
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.1 build 19B77a
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE cluster, manually created. 

### Operating system / Environment
Mac OS X 10.15.1 build 19B77a

**Comment by guitcastro** [comment]
Ok, I figure out. I was in develop branch change to master give this error: 

`output: 'remote: GitLab: You are not allowed to push code to protected branches on this project.`

**Comment by guitcastro** [comment]
I figure out.

My git remote was configured to use ssh instead of https. 

It would be nice to check remove-URL if ssh is not supported and give proper feedback for users.

**Comment by deanesmith** [comment]
@guitcastro thank you for the update.  Closing.

**Comment by guitcastro** [comment]
@deanesmith I would leave this open until a proper feedback message is not implemented.

**Comment by deanesmith** [comment]
@guitcastroWould you mind then rewording the issue title and describing the desired functionality/messaging you are recommending?
