### ISSUE TITLE
jenkins-x-docker-registry deployment & pvc are being created although custom docker registry is used

### ISSUE THREAD

**Issue by tycoonm** [jenkins-x/jx#6440]
### Summary 
I've configured custom docker registry and use kaniko to build images, but jenkins-x-registry deployment and pvc are still being created.

### Steps to reproduce the behavior
Set cluster.registry in jx-requirements.yml to some docker registry url and run `jx boot`

### Expected behavior
jenkins-x-docker-registry deployment & pvc are not created

### Actual behavior
jenkins-x-docker-registry deployment & pvc are created

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.1107
Kubernetes cluster v1.17.0
kubectl            v1.17.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.14.6 build 18G103


verifying packages
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

On-Premise

### Operating system / Environment

Mac OS X 10.14.6 build 18G103

**Comment by mcabrito** [comment]
I'd try this too.
