### ISSUE TITLE
Make devEnvApprovers field required in jx-requirements.yml

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6465]
Followup to #6457 and its initial fix on #6461 - we'll start with the new `devEnvApprovers` field as optional, prompting for it when not run in batch mode, but we'll want to move to it being mandatory. Doing so will require making changes to a bunch of BDD tests and a couple other places, once #6461 has released. Staging the change like this keeps us from running into the hell of a new field in `jx-requirements.yml` that's required from right away, because that would break everything downstream until they updated, but adding the field as optional initially gives us a window after it's released to update everything downstream to have `- devEnvApprovers: []`, and _then_ make it mandatory.

**Comment by abayer** [comment]
Just realized we’re almost certain to eventually hit cherry pick errors in `OWNERS` as soon as the upstream one has changes and someone runs `jx boot upgrade`. We always want to keep the downstream version of `OWNERS` in that scenario. There’s logic in `jx boot upgrade` to exclude upstream changes to `OWNERS`, but only after the cherry picking is complete, so the errors will still show up. I’m thinking about doing something like what’s described in https://stackoverflow.com/a/930495 (with `true` as the driver, or something equivalent for Windows) to make cherry picking just ignore the `OWNERS` file completely. I think we do need to address this before making the field mandatory, and probably before making any changes to upstream boot config’s `OWNERS`.

**Comment by hferentschik** [comment]
I am not sure whether _ devEnvApprovers_ should even be in the requirements file. I think we should revisit this, in particular making it a required field.
