### ISSUE TITLE
Secure the IDE exposed by devpods

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#6475]
### Summary 

The IDE that runs as part of a `jx create devpod` is exposed via a public ingress. Unauthorised access to the IDE should be prevented.

One possible solution to lock down access to the devpod IDE would be to front the IDE URL by http basic auth.

**Comment by ccojocar** [comment]
It is recommended to not create any DevPods until a security patch is ready to avoid exposing the Jenkins X infrastructure and related assets to unauthorised parties.

**Comment by ccojocar** [comment]
Adding basic authentication to the exposed IDE endpoint, it will also require TLS enabled to properly secure it. This will make TLS a requirement for DevPods. I think in a first stage we should not publicly exposed the IDE, and then later we can only expose it with a basic auth password when TLS is enabled. 

I would suggest that we stop exposing the web IDE endpoint by not creating the ingress resource. The service can be exposed by using `kubectl port-forward` command.
