### ISSUE TITLE
Endless loop while promoting to staging post build

### ISSUE THREAD

**Issue by sauravdevops** [jenkins-x/jx#648]
**What is happening**

- Tried creating a quickstart project for node using `jx create quickstart  -f http`
- Choose `node-http`
- Build Release stage completes sucessfully
- Promote to environments (Staging) keeps on waiting with this warning
```
WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300
```
- I can see the PR created and waiting to be merged.

**Error step from the below command**
The timeout is for an hour, so stopped the process manually after waiting for 10 mins ...
```
jx promote -b --all-auto --timeout 1h --version $(cat ../../VERSION)
```

**Error Logs for the stage**
```
[node-http] Running shell script

++ cat ../../VERSION

+ jx promote -b --all-auto --timeout 1h --version 0.0.1

Promoting app node-http version 0.0.1 to namespace jx-staging

Using pipeline: ssendemo/node-http/master build: #1

Cloning into '/home/jenkins/.jx/environments/ssendemo/environment-songrainbow-staging'...

Found remote branch names master, HEAD -> origin/master, master, promote-demo-golang-http-0.0.1, promote-demo-golang-http-0.0.2

Switched to branch 'promote-node-http-0.0.1'

[promote-node-http-0.0.1 c7d5fab] Promote node-http to version 0.0.1

 1 file changed, 3 insertions(+)

To https://github.com/ssendemo/environment-songrainbow-staging.git

 * [new branch]      HEAD -> promote-node-http-0.0.1

Created Pull Request: https://github.com/ssendemo/environment-songrainbow-staging/pull/5

Using pipeline: ssendemo/node-http/master build: #1

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300

WARNING: Failed to query the Pull Request last commit status for https://github.com/ssendemo/environment-songrainbow-staging/pull/5 ref c7d5fabdce48818b239b0a661fc09aba8d274300 Could not find a status for repository ssendemo/environment-songrainbow-staging with ref c7d5fabdce48818b239b0a661fc09aba8d274300
.....
```

**JX version**

```
▶ jx version
NAME               VERSION
jx                 1.2.1
jenkins x platform 0.0.683
kubernetes cluster v1.8.7
kubectl            v1.9.3
helm client        v2.8.2+ga802316
helm server        v2.8.2+ga802316
git                git version 2.15.1 (Apple Git-101)
```

**Closing notes**

- Earlier today did not have this problem when creating a spring boot sample using `jx create spring -d web -d actuator`
- Tried the quickstart for `go-http` and again the above issue was there.
- I had to upgrade jenkins x when I tried running quickstart for the first time, the build failed and asked me to upgrade jenkins X
```
jx upgrade platform
jx upgrade cli
```

**Comment by rawlingsj** [comment]
Are you running on minikube or another kubernetes cluster that doesn't have public network access?  It looks like the PR was raised https://github.com/ssendemo/environment-songrainbow-staging/pull/5 but the CI job never triggered so suggests an issue with the webhook on that repo not getting to Jenkins.  

Can you check the webhook event statuses on that repo to see if any failed?  Go to 

https://github.com/ssendemo/environment-songrainbow-staging/settings/hooks and select the webhook then scroll now to Recent Deliveries to check the statuses if they were successful or not.

**Comment by sauravdevops** [comment]
My cluster is running on AWS.
@rawlingsj right on, my aws security groups have been updated :/
Thankyou for pointing out to the webhooks, yes you are right again, they are failing.

I will whitelist Githubs IP's and try again, will update here shortly

**Comment by rawlingsj** [comment]
excellent - fingers crossed that sorts it!

**Comment by jstrachan** [comment]
for cases when webhooks are borked we could manually trigger the pipeline from inside the promote loop: https://github.com/jenkins-x/jx/issues/650

**Comment by sauravdevops** [comment]
**Solved**
As rightly mentioned by @rawlingsj github was not able to reach to my jenkins.

**Fix**
- Get the Github IP's from here : https://api.github.com/meta
- Whitelist the IP's mentioned under `hooks` 
- Two security groups need to be updated
   - Security group for api ELB
   - Security group for api ELB

**Comment by rawlingsj** [comment]
Many thanks for posting back the steps you used to update the security groups!

I think we can close this and leave #650 open to cover improvements when webhooks events cannot reach Jenkins.

**Comment by jstrachan** [comment]
this is now fixed along with #674 - release should be out in an hour

**Comment by agentgonzo** [comment]
We're seeing this again now

**Comment by amuniz** [comment]
I think this is workarounded by https://github.com/jenkins-x/jx/pull/2418 (and tracked for a better fix as https://github.com/jenkins-x/jx/issues/2410)

**Comment by amuniz** [comment]
Also, this only happens when prow is enabled. So I'd say this issue should be re-closed (as it was about static Jenkins installations).
