### ISSUE TITLE
 Timed out  for pod [maven-bcvxg] in namespace [jx].

### ISSUE THREAD

**Issue by pioneerlabs** [jenkins-x/jx#6480]
### Summary 

We are getting all the time 

 Timed out waiting for [100000] milliseconds for [Pod] with name:[maven-bcvxg] in namespace [jx].

We restarted also jenkins but nothing.

### Steps to reproduce the behavior

We have 4 projects. One with 20 branches.
Now even  a simple project gets the same error.

### Jx version

The output of `jx version` is:

```
2.0.1113
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ x] Classic Jenkins

### Kubernetes cluster

AWS EKS

### Operating system / Environment

mac os 10.14.6 (18G95)

**Comment by hferentschik** [comment]
Could you provide some more information on how to reproduce this?
