### ISSUE TITLE
We should not modify skaffold(or any) step

### ISSUE THREAD

**Issue by guitcastro** [jenkins-x/jx#6486]
### Summary 

I installed Jenkins-x this week, and I spent days trying to figure out why kaniko was being executed instead of the Scaffold step defined in the [pack](https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/v1.0.0/packs/gradle/pipeline.yaml). After a lot of research I found out, that this [commit](https://github.com/jenkins-x/jx/commit/684902d9fbbe5a4316da01a4bef2a3331150a505) is deliberating modifying the command defined in the pipeline.

And worse, I dig deeper into the docs and couldn't find out any mention about this. 

### Steps to reproduce the behavior

Just install Jenkins-x and use any build pack with the scaffold.

### Expected behavior

It's expected that the commands specified in the pipeline are respected and not magic change, difficulting a lot the debug processing if anything goes wrong.

### Actual behavior

The pipeline step is being modified without my consent.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1104
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.14.8
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.1 build 19B77a
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by garethjevans** [comment]
Hi @guitcastro, the reason we modify the step is that the current skaffold integration with kaniko causes a new pod to be created - but provides no way for us to configure that pod (e.g. set limits or mount volumes/secrets or run with a non default service account).

It's a bit messy at the moment, but until skaffold supports these features we took the decision to replace the step with a kaniko step.

**Comment by guitcastro** [comment]
Hi @garethjevans, Thanks for the clarification, is there an issue/roadmap where I can follow scaffold to know when those limitations are gonna be fixed? 

I understand that if this is a temporary hack, although to be justified, we should at last document and have some ETA for the proper fix.
