### ISSUE TITLE
Override a value in a version stream

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#6490]
### Summary 

I'd like to have an easy way of overriding a value (or multiple values) in a version stream so I can test out changes on a cluster.

The types of changes I'd like to be able to test out is:

* Builder changes
* Binary dependency changes
* Helm Dependency changes

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
Are you talking about overriding in boot config or in a running cluster? In boot config, you can override the version stream for helm dependencies in `env/requirements.yaml`, but only the top level dependencies, so far as I can tell, so you can override the version of, say, the Tekton chart, but not the version of the nexus chart used in the `jenkins-x-platform` chart. And of course that’s of no use for builders or binaries...
