### ISSUE TITLE
STEP: install-jenkins-x error

### ISSUE THREAD

**Issue by dlstonedl** [jenkins-x/jx#6493]
### Summary 

When attempting to install the environment with cli I was met with an error.

### Steps to reproduce the behavior
jx boot --verbose

### Expected behavior
jenkins-x succeed

### Actual behavior

error: generating values.yaml for tree from /var/folders/pp/3z4_chx13l5_g_l5yb__n03r0000gy/T/jx-helm-apply-320176738/env: failed to execute Secrets template: /var/folders/pp/3z4_chx13l5_g_l5yb__n03r0000gy/T/jx-helm-apply-320176738/env/jenkins-x-platform/values.tmpl.yaml: template: values.tmpl.yaml:9:92: executing "values.tmpl.yaml" at hashPassword: wrong type for value; expected string; got float64
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''

![image](https://user-images.githubusercontent.com/40499007/72199393-4a90a480-3476-11ea-8fbf-17ae7f11fd09.png)

### Jx version

WARNING: Failed to find helm installs: running helm list --all --namespace jx: failed to run 'helm list --all --namespace jx' command in directory '', output: 'Error: could not find tiller'
WARNING: Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.16.1+gbbdfe5e
Error: could not find tiller'
NAME               VERSION
jx                 2.0.1116
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.17.0
git                2.17.1
Operating System   Mac OS X 10.13.6 build 17G65

### Jenkins type

 Classic Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

macOS

### Other

my jenkins password: 123456

if jenkins password = admin, the install is ok

file location:  **/jenkins-x-boot-config/env/jenkins-x-platform/values.tmpl.yaml
code location: 
JXBasicAuth: "{{ .Parameters.adminUser.username }}:{SHA}{{ .Parameters.adminUser.password | hashPassword }}"
if the password is number may has error

**Comment by abayer** [comment]
So the problem here is that when we write the parameters, we're not quoting non-string values like `123456` - we should be doing that. You can probably work around this by editing the `parameters.yaml` file (I think it's in the root of the boot clone, but it could be in `env`) and putting quotes around the password there.
