### ISSUE TITLE
Document and share development steps required to support Jenkins X on Kubernetes providers

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6503]
### Summary 
JX Boot support for Jenkins X is largely focused on GKE and EKS.  Moving forward additional Kubernetes provider platforms should be supported, particularly larger platforms delivered via cloud providers.  In an effort to encourage community contributions and ongoing maintenance for various Kubernetes provider support, documentation needs to be produced and maintained providing detailed instructions on areas where code needs to be enhanced for further platform proliferation.  

As platform support is extended, detailed documentation guiding users through cloud provider nuances must also be provided.  This document should also guide contributors through the steps needed to ensure proper documentation is put in place to support their contributions.

Acceptance Criteria:
Rough draft document is shared and reviewed by stakeholders
Once reviewed, final copy is shared with community

Notes:
Reference and enhance document as AKS support for JX Boot is established
Publish to [JX docs](https://jenkins-x.io/docs/) web site in contributing section

**Comment by dgozalo** [comment]
Resulting document: https://docs.google.com/document/d/1_w5L-rC1sw4cE7N5q2YsV8S2FQmHJVokEr8ua-SKp7k/edit?usp=sharing
