### ISSUE TITLE
jx pipeline step: step-setup-jx-git-credentials fails for devEnvApprovers field

### ISSUE THREAD

**Issue by DerPauli** [jenkins-x/jx#6504]
### Summary 
I had to specify a devEnvApprovers field in jx-requirements.yml file (as prompted by `jx boot`). When creating a quickstart application (node-http), the pipeline for the application will fail on the stage: `from-build-pack`

### Steps to reproduce the behavior
Run `jx create quickstart` and use the `node-http` project with
```
...
cluster:
    devEnvApprovers:
      - some_approver
...
```

section in the jx-requirements.yml file.
Cluster is run on AWS EKS against GitLab (Cloud) server with lighthouse.

You can find the jx-requirements.yml file here: https://gist.github.com/DerPauli/2cf9f63115cc33e23c317b9437364e11

Run `jx get build logs <org>/<project>/master`

### Expected behaviour
Git credentials will be created and pipeline step succeeds.

### Actual behaviour
Pipeline crashes with following build log:

```
Showing logs for build cz-sandbox/jx-node/master #3 stage from-build-pack and container step-setup-jx-git-credentials
error: error getting Requirements from TeamSettings to determine if in GitHub app mode: validation failures in requirements from team settings:
cluster: Additional property devEnvApprovers is not allowed

Pipeline failed on stage 'from-build-pack' : container 'step-setup-jx-git-credentials'. The execution of the pipeline has stopped.
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1117
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.14.8
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.15 build 19A582a
```

### Jenkins type
- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Note**: Project is setup with Gitlab (Cloud) server and lighthouse configured.

### Kubernetes cluster
Kubernetes on AWS (EKS). Created with Terraform. Setup kubectl (to connect jx to cluster) and set `terraform: true` flag

### Operating system / Environment
Operating system: `macOS Catalina, Version 10.15 (19A582a)`

uname -a: ```Darwin pauls-mbp.home 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 21:13:50 PDT 2019; root:xnu-6153.11.26~4/RELEASE_X86_64 x86_64```

**Comment by abayer** [comment]
Hmm - what is the builder image version used in the pod that's having this error? Looks like something is out of sync.

**Comment by DerPauli** [comment]
@abayer Problem solved! I don't know why, but just waiting some time solved the problem.
Pipeline runs successfully and build succeeds.

**Comment by abayer** [comment]
I am not shocked. =) The `devEnvApprovers` field is pretty new, so I had a feeling that the cluster was still using builders with an earlier version. Anyway, glad to hear it's working now! I'll close this, but feel free to reopen if needed!
