### ISSUE TITLE
Application not visible

### ISSUE THREAD

**Issue by kdufourbe** [jenkins-x/jx#6509]
### Summary 

I am playing around with a custom build pack in order to extend the possibilities of our custom needs. Everything seems to be working fine, but I cannot see the application using "jx get applications".

### Steps to reproduce the behavior

- Activate the custom Build Pack 
```
jx edit buildpack -r master -u https://github.com/XXXXX/jenkins-x-kubernetes.git -b
```
- Import the project
```
jx import -u https://github.com/XXXXX/XXXXXXXXXX.git --pack MyCustomPack
```
- Wait for the pipeline to be completed

### Expected behavior
```
kdufour@kdu  ~  jx get applications
APPLICATION
DETAILS ABOUT THE APPLICATION
```

### Actual behavior
```
 kdufour@kdu  ~  jx get urls -n jx-staging
NAME               URL
camperfriendsadmin https://camperfriendsadmin-jx-staging.dcin.xyz
 kdufour@kdu  ~  jx get applications
APPLICATION
 kdufour@kdu  ~  jx delete application
? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter]
> [ ]  kriske83/CamperFriendsAdmin
error: deleting application: interrupt
 ✘ kdufour@kdu  ~  jx get applications
APPLICATION
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1120
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.14.6 build 18G1012


verifying packages
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE set-up created with jx boot

### Operating system / Environment

OS X

**Comment by kriske83** [comment]
![Screenshot 2020-01-14_10-26-34-524](https://user-images.githubusercontent.com/883849/72334556-c7fa2600-36bd-11ea-9647-e9ab03aca569.png)

**Comment by kriske83** [comment]
@vfarcic : As discussed at the Jenkins X workshop in Brussels. You can find my buildpack here: https://github.com/kriske83/jenkins-x-kubernetes the pack itself is called Xojo.

**Comment by kriske83** [comment]
@vfarcic : As discusses during the JX Workshop @ Brussels. Could you please have a look to this issue. You can find the buildpack at: https://github.com/kriske83/jenkins-x-kubernetes and the pack itself is called Xojo.

PS. I know there is sensitive data in there and it should be cleaned up and more secure and I should be slapped for that, but for now it will work out for now as it is going through a VPN.

**Comment by kriske83** [comment]
I've found why this issue occurred. The imported project contained uppercase characters as well. I renamed everything to lowercase and the issue did not show up again.

**Comment by vfarcic** [comment]
Maybe this issue should remain open so that a warning about uppercase letters is added to the project. Otherwise, others might be having the same issue without having a clue about the cause.

**Comment by 524119574** [comment]
Is this issue expecting a fix? Or just a warning message added in the CLI?

**Comment by Ubermensch01** [comment]
This is still pretty much an issue.
