### ISSUE TITLE
Fix the version range of kubectl that is supported by jx

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#6511]
### Summary 

The version stream currently specifies that we support up to version 2.0 of kubectl. We have seen breaking changes introduced when kubectl 1.17 was released. We should lock down the upper limit that we support to prevent future breaking changes.

### Acceptance Criteria

- The version stream contains an upper limit for the kubectl binary which we know works with jx
- The builders contain a version of kubectl which falls in to the working range for jx

#### Notes:

- kubectl is automatically updated to latest stable release in the builders https://github.com/jenkins-x/jenkins-x-builders-base/blob/master/builder-base/Dockerfile.common#L43. We need to make sure we are using a jx compatible version
- The version of kubectl is specified in the version stream [here](https://github.com/jenkins-x/jenkins-x-versions/blob/master/packages/kubectl.yml)

**Comment by mrageh** [comment]
What version of Kubectl do we want to make the upper limit?

**Comment by daveconde** [comment]
1.14 would be a good versionto bundle in the builders for the Kubernetes versions we are supporting at the moment. With a max in the version stream of 1.17

**Comment by mrageh** [comment]
How about 1.17 in both the version stream and in the builders?

**Comment by masseybradley** [comment]
Possibly related to [this issue](https://github.com/jenkins-x/jx/issues/6384) if in fact the `velero` installation is broken given the version of `kubectl`.
