### ISSUE TITLE
Can't create addon gitea

### ISSUE THREAD

**Issue by yahavi** [jenkins-x/jx#652]
I'm trying to run `jx create addon gitea`.
The command failed with:
> Waiting for pods to be ready for deployment gitea-gitea
error: deployment gitea-gitea never became ready

The pod has config error:
> $ kubectl get pod
> NAME                                            READY     STATUS                       RESTARTS   AGE
> gitea-gitea-6b6f66bd8-9s87x                     0/1       **CreateContainerConfigError**   0          7m
> gitea-postgresql-7d8b9b9c65-pzrs2               1/1       Running                      0          7m
> jenkins-5f9988f569-l8p4k                        1/1       Running                      0          27m
> ...

Environment
=========
MacOS High Sierra 10.13.4

> $ jx version
> jx                 1.2.2
> jenkins x platform 0.0.678
> kubernetes cluster v1.9.4
> kubectl            v1.10.1
> helm client        v2.8.2+ga802316
> helm server        v2.8.2+ga802316
> git                git version 2.17.0

**Comment by jstrachan** [comment]
it looks like gitea can't create. Not sure why. This might give a bit more information:

    kubectl describe pod gitea-gitea-6b6f66bd8-9s87x

**Comment by jstrachan** [comment]
I'm not quite sure - I've not yet hand chance to try gitea on minikube; its working great on GKE though. I'll try get chance to test it on minikube

**Comment by yahavi** [comment]
Solved by using Minikube 0.26.1 and thanks to that fix: https://github.com/jenkins-x/jx/commit/ba17de154083301192b695238f2f7b3ce7cf8d57.
Thanks you!
