### ISSUE TITLE
Boot upgrade without jx namespace in kube config

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6529]
### Summary 

When executing `jx upgrade boot` with kube config NOT pointing to the `dev` (e.g., `jx`) Namespace, the output is as follows.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x22766da]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits.(*GitCLI).CreateAuthenticatedURL(0xc0009aea98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /workspace/source/pkg/gits/git_cli.go:581 +0x6a
github.com/jenkins-x/jx/pkg/cmd/upgrade.(*UpgradeBootOptions).cloneDevEnv(0xc00054ae40, 0x0, 0x0)
        /workspace/source/pkg/cmd/upgrade/upgrade_boot.go:488 +0x1b5
github.com/jenkins-x/jx/pkg/cmd/upgrade.(*UpgradeBootOptions).Run(0xc00054ae40, 0x0, 0x0)
        /workspace/source/pkg/cmd/upgrade/upgrade_boot.go:83 +0xad3
github.com/jenkins-x/jx/pkg/cmd/upgrade.NewCmdUpgradeBoot.func1(0xc000806280, 0xb162868, 0x0, 0x0)
        /workspace/source/pkg/cmd/upgrade/upgrade_boot.go:64 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc000806280, 0xb162868, 0x0, 0x0, 0xc000806280, 0xb162868)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a8000, 0xc000309c00, 0x6608560, 0xc00000e010)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0006f9f88, 0xc0000a0058)
        /workspace/source/cmd/jx/app/jx.go:19 +0x185
main.main()
        /workspace/source/cmd/jx/jx.go:11 +0x32
```

### Steps to reproduce the behavior

Change the namespace in kube config to something other than Jenkins X `dev` namespace. Execute `jx upgrade boot`

### Expected behavior

An user-friendly message that tells that the problem is that kube config does not point to the `dev` Namespace.

### Actual behavior

`panic`

### Jx version

```
NAME               VERSION
jx                 2.0.1126
Kubernetes cluster v1.14.8-gke.17
kubectl            v1.17.1
git                2.23.0
Operating System   Mac OS X 10.12.6 build 16G2136
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Any

### Operating system / Environment

Mac OS

**Comment by ankitm123** [comment]
The issue is that no error is returned when the dev  environment is not found, instead nil is returned.
https://github.com/jenkins-x/jx/blob/master/pkg/kube/env.go#L1061-L1063
I can submit a PR to fix it. Is there a reason why an error should not be returned?

**Comment by ankitm123** [comment]
On looking at the codebase, it seems the issue is because of unhandled errors, I have the code change, just writing few tests, will open a PR soon.
