### ISSUE TITLE
jx-app-sso doesn't respect URL form for jx namespace under boot

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6537]
### Summary 
jx-app-sso creates a dex instance which must be exposed externally to support OIDC conversations. When installing under boot, this service does not respect the naming convention for service URLs as defined in the boot config but instead deploys at dex.jx.<your domain>

### Steps to reproduce the behavior
`jx add app jx-app-sso`

### Expected behavior
Default boot config suggests `dex-jx.someurl.com`

### Actual behavior
Service instead deploys to `dex.jx.someurl.com`

### Jx version

The output of `jx version` is:

```
x                 2.0.1123
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.0
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by ccojocar** [comment]
I think we need to define the URL template here for the ingress instead of using the default https://github.com/jenkins-x/dex/blob/bfe82191c396ddb5954c764ab46fb08e271bd144/charts/dex/values.yaml#L14, such that  it can be configured.
