### ISSUE TITLE
Multiple Clusters Documentation Page

### ISSUE THREAD

**Issue by dineshmistry** [jenkins-x/jx#6541]
### Summary 

Is the multi-cluster documentation page still relevant and up to date? 

https://jenkins-x.io/docs/reference/multi-cluster/

There is a reference to removing the `postsubmit `setting in your Prow configuration it is either no longer relevant or difficult to understand.

**Comment by dineshmistry** [comment]
Just found this in - https://github.com/jenkins-x/jx/issues/479

So it seems like the documentation might need to be updated slightly?

I'm gonna mark this one as closed now as we now disable the release pipelines of remote clusters via the --remote-environments flag when installing Jenkins X: https://jenkins-x.io/getting-started/multi-cluster/ and we automate configuring the setup of the external chart museum URL in the staging/production git repository so that promotions work fine in the remote clusters without any custom steps.we also have a simple way to enable ingress on remote clusters if required: https://jenkins-x.io/getting-started/multi-cluster/#installing-ingress-controller
--

**Comment by jstrachan** [comment]
@dineshmistry I'm going to update the page once the experimental support for multi-clusters is released. Also see https://github.com/jenkins-x/jx/issues/4784

**Comment by jstrachan** [comment]
here's documentation https://github.com/jenkins-x/enhancements/tree/master/proposals/2/docs - note its still experimental but we're hoping to get it more solid real soon...

**Comment by jstrachan** [comment]
ok -[documentation](https://jenkins-x.io/docs/reference/multi-cluster/) updated to reference the new helm 3 boot: https://jenkins-x.io/docs/labs/boot/ e.g. https://jenkins-x.io/docs/labs/boot/multi-cluster/
