### ISSUE TITLE
jx boot upgrade replaces OWNERS with OWNERS from jenkins-x-boot-config

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x/jx#6543]
### Summary

Forked repo's `OWNERS` configuration is replaced with the `OWNERS` configuration from the `jenkins-x-boot-config` repository during an upgrade from `v1.0.69` to `v1.0.71` with the commit: "chore: exclude files from upgrade" (i.e. https://github.com/yields-io/environment-k8s-dev/pull/5).

### Steps to reproduce the behavior

Upgrade environment using `jx upgrade boot`.

### Expected behavior

`OWNERS` file created with the values from the `jx-requirements.yml` > `devEnvApprovers` during the initial `jx boot` shouldn't be touched during an upgrade.

### Actual behavior

`OWNERS` file is replaced with the `OWNERS` file from the `jenkins-x-boot-config` repository. I'm currently not an approver / reviewer in the `jenkins-x-boot-config` repository hence I can't approve the PR created for the upgrade nor would I want to given the `OWNERS` modifications. Similar to [this issue](https://github.com/jenkins-x/jx/issues/5035): "This results in these jx devs having a high prow privileges on other peoples dev environments."

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1123
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.17.0
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE: `jx create cluster gke --skip-installation --cluster-name k8s`

### Operating system / Environment

Ubuntu 18.04

**Comment by abayer** [comment]
I conveniently already have a PR up that fixes this over at #6502. =)
