### ISSUE TITLE
lets automatically install `lile` if the user types `jx create lile` and its not already installed

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#655]

**Comment by rawlingsj** [comment]
Wonder if we just vendor lile instead of getting downloading a binary?

**Comment by jstrachan** [comment]
I figure its probably easier to keep lile separate and let it upgrade itself independently?

**Comment by rawlingsj** [comment]
Fair enough, it just seemed to work a bit better when we did that for Draft.  But no worries.
