### ISSUE TITLE
Document envars VAULT_AWS_ACCESS_KEY_ID and VAULT_AWS_SECRET_ACCESS_KEY for jx boot

### ISSUE THREAD

**Issue by TarekAS** [jenkins-x/jx#6553]
To be able to install vault on AWS using jx boot, these environment variables need to be set:
VAULT_AWS_ACCESS_KEY_ID
VAULT_AWS_SECRET_ACCESS_KEY

However, this appears nowhere in the docs.

**Comment by dgozalo** [comment]
We will be releasing new documentation very shortly and this will be covered in a section specific to Vault.
