### ISSUE TITLE
local secrets in boot parameters.yaml not interpolated in dev env repo pipeline runs

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6559]
I'm seeing this error:
```
Showing logs for build dev1/environment-pr-470-6-lh-bdd-ghe-dev/pr-1 #1 promotion-build stage pr-checks and container step-verify-parameters
error: resolve the secrets URIs: replacing secrets URIs: replacing vault paths in adminUser:
  password: local:pr-470-6-lh-bdd-ghe/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: local:pr-470-6-lh-bdd-ghe/pipelineUser:token
  username: dev1
prow:
  hmacToken: local:pr-470-6-lh-bdd-ghe/prow:hmacToken
: unable to find "password" in secret at "pr-470-6-lh-bdd-ghe/adminUser"
```

That's on a PR to the dev env.

cc @ccojocar - any ideas?

**Comment by ccojocar** [comment]
Is the `adminUser` created in the parameters? I think is that's the stage when the values are stored even in the local secrets storage.

**Comment by abayer** [comment]
This was a BDD test run, so it just did...whatever it normally does?

**Comment by abayer** [comment]
So yes, `parameters.yaml` is created as it shows up in the log snipped I pasted above. Seems like the `local:` secrets aren't being interpolated properly.

**Comment by abayer** [comment]
So dev env gitops isn't supposed to work or be used with local secret storage in general. Closing this. =)
