### ISSUE TITLE
Helm Documentation is All Over the Place

### ISSUE THREAD

**Issue by GLStephen** [jenkins-x/jx#6563]
As we move to a production we are creating greenfield installs, making notes against published docs for internal user and discovering a few inconsistencies.

The docs here:

https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/install-guide/

Seem to assume that Helm is installed, and don't mention the requirement explicitly. In other words, following these docs leads to the somewhat cryptic error in GKE of when doing a jx boot -r jx-requirements-gke.yml it appears to result in an issue like this:

```
error: initializing helm with config: {jx true false true false  }: failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: open /home/stephenj/.helm/repository/cache/jenkins-x-index.yaml: permission denied' error: failed to interpret pipeline file /mnt/c/Users/sjohnston/Documents/Development/jxtest2/cloudbees-jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '/mnt/c/Users/sjohnston/Documents/Development/jxtest2/cloudbees-jenkins-x-boot-config', output: ''
```

But the requirement is more clear here:

```
https://docs.cloudbees.com/docs/cloudbees-core/latest/gke-install-guide/installing-gke-using-helm
```

Further exploration ends up with HELM 3 not supported, a recommendation of --no-tiller usage an issue indicating that 2.16.1 the latest HELM may not work. Helm seems critical here, the status of it needs to be centralized and documented properly.

None of which ultimately seems to solve the above issue.

**Comment by hferentschik** [comment]
This is not only a documentation issue but also a bug in code. The error should be much clearer and we should in fact install and use our dedicated version of Helm.

**Comment by jstrachan** [comment]
fwiw we do try, in the `jx step verify preinstall` to verify which version of helm is installed and if it matches the known range https://github.com/jenkins-x/jx/blob/2ea94d9cc7f6a6bd8d60315b221fb6c0247ba2cf/pkg/cmd/step/verify/step_verify_preinstall.go#L188

but its sounding like some other logic is kicking in earlier on before we get to the helm version range validation
