### ISSUE TITLE
Feature: Migrate jx-app-fossa to jenkins-x-apps org

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6567]
### Summary 
I have put together an App that extends the metapipeline to provide open source licence checking with FOSSA (https://fossa.com). If someone would like to test this out and then fork it into jenkins-x-apps, that would be great! It will need some changes to fit with the jx build structure and to refer to images from the appropriate docker repo.

Because it requires a public docker image to install an App, you will have to build your own version and reference that image to test it prior to publication in the official repo. I have tried to keep the build process in line with existing apps, so it should be just a case of modifying the image registry.

You can fork from: https://github.com/Bootstrap-Jersey/jx-app-fossa

BE AWARE! Pipeline plugins can break your builds, including environment releases! If you encounter a problem during testing, you may need to execute `kubectl delete App jenkins-x-jx-app-fossa` in order to continue with corrective builds.

**Comment by abayer** [comment]
Forked to https://github.com/jenkins-x-apps/jx-app-fossa, updated to (I think) work, PR to get it built by the prod cluster is up at https://github.com/jenkins-x/environment-tekton-weasel-dev/pull/374

**Comment by tdcox** [comment]
Looks ok, other than you might want to synchronise the builder image version in the Dockerfile with whatever is current.

**Comment by abayer** [comment]
Opened https://github.com/jenkins-x-apps/jx-app-fossa/pull/1 to simplify the `jenkins-x.yml` and switch the Dockerfile to just use `latest` (which is whatever the most recent release build is).
