### ISSUE TITLE
controllerbuild can't list config maps and so can't get git credentials

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6568]
With the `jx-auth-config` map logic added, the build controller isn't able to list config maps due to not having permissions to do so, and therefore can't actually get git credentials (via `jx step git credentials`), because when `jx-auth-config` is created, the relevant secrets aren't created. This breaks LH reporting and gh-pages log archiving.

**Comment by abayer** [comment]
Ok, so there are more permissions needed than I thought - I'm pretty sure it needs `configmaps`, `ingresses`, and presumably `bank-vaults`, but...that doesn't seem to be enough. @ccojocar, help?

**Comment by abayer** [comment]
fwiw, without any additional permissions, it just ends up with an empty file when it runs `jx step git credentials`. When I add configmaps, it gets messages about vault not being exposed. So I added ingresses, and got back to an empty file. Pipeline pods can run `jx step git credentials` just fine, but I just can't figure out what's missing for the build controller.

**Comment by abayer** [comment]
Ah, it needs serviceaccounts too...wow, so many permissions...

**Comment by ccojocar** [comment]
I think it needs `serviceaccounts` because it has to authenticate against vault. We should get rid of this when this issue is fixed https://github.com/jenkins-x/jx/issues/5862.
