### ISSUE TITLE
dex authrequests.dex.coreos.com crd objects not being garbage collected causing cluster network issues

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/jx#6578]
### Summary 
When using dex within a jenkins-x cluster there are scenarios where thousands of `authrequests.dex.coreos.com` crds are created, this can be within a short space of time. It's not known what causes this to happen as yet. Without crd object count monitoring or resource quotas set it can go unnoticed and lead to cluster issues. The cluster issues present themselves as network latency, timeouts and closed connects, which occur due to back pressure  the apiserver experiences waiting on requests to/from etcd (_it seems_). It's worth noting that `dex` is deployed alongside the sso-operator which might be contributing to this issue.

If an issue needs to be raised with https://github.com/dexidp/dex we can copy details from this ticket.

### Steps to reproduce the behavior
Create a lot of `authrequests.dex.coreos.com` crd objects (upwards of 300, 000)

### Expected behavior
The old `authrequests.dex.coreos.com` objects should be removed when no longer required.

### Actual behavior
Applications become unavailable, volume mounts fail and failure to write secrets...

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
I feel like adding a GC cronjob to the dex chart would make sense here.

**Comment by hferentschik** [comment]
Well, I say we first need to know why so many CRDs are getting created. Adding a garbage collection job w/o knowing what's causing the issue would be just covering things up.
