### ISSUE TITLE
Application deployments cause merge conflicts on dev environment

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6582]
### Summary 
Deploying more than one application into a staging environment causes a merge conflict on the dependency matrix files in the Dev repo.

### Jx version

The output of `jx version` is:

```
2.0.1139
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - Boot
- [ ] Classic Jenkins

**Comment by abayer** [comment]
What were the files changed in the two PRs besides the conflicting ones? Trying to make sure I understand what drove creating the PRs in the first place.

**Comment by tdcox** [comment]
I think one was a `jx create quickstart' and the other a `jx import` but there seem to be multiple branches getting modified.

**Comment by tdcox** [comment]
Hmmm, It looks like the import was actually merged on a branch that was used to delete an app rather that on its own branch.

**Comment by abayer** [comment]
That last part doesn't shock me - in theory, it's supposed to use an existing open PR from the same user if one exists. Were both the quickstart and import run by the same user?

**Comment by tdcox** [comment]
No, different users. And the import / delete were initiated by different people.
