### ISSUE TITLE
JX Quickstart is unable to post the image to the docker registry

### ISSUE THREAD

**Issue by devc0n** [jenkins-x/jx#6592]
### Summary 
after I have created a cluster on amazon using the elastic containers, I wanted to deploy an application on the cluster. But the pipeline fails because Jenkins is unable to push to the registry.

### Steps to reproduce the behavior

Create a merge request on the `jx create spring` application.

### Expected behavior

The application has been deployed on a pull request environment.

### Actual behavior

>  - devc0n/spring-quickstart: time="2020-01-23T09:44:30Z" level=warning msg="error checking cache, caching may not work as expected: getting hash for artifact devc0n/spring-quickstart: getting dependencies for devc0n/spring-quickstart: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (openjdk:8-jdk-slim) for ONBUILD triggers: getting remote config: getting image: error getting credentials - err: exit status 1, out: `2020-01-23T09:44:30Z [ERROR] Error parsing the serverURL: https://index.docker.io/v1/, error: docker-credential-ecr-login can only be used with Amazon Elastic Container Registry.\ncredentials not found in native keychain`"

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1143
jenkins x platform 2.0.1889
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

I have a Kubernetes cluster on AWS with EKS. I created this using the following command.

`jx create cluster eks`

### Operating system / Environment

the development environment I suppose?

**Comment by ethangj** [comment]
Hey, there - are you deploying JX for the first time or moving/reinstalling an existing installation?

**Comment by devc0n** [comment]
It's my first time using JX. so I am not sure what happens everywhere exactly. But when I do a jx import on an existing project this problem magically disappears for some reason.

**Comment by ethangj** [comment]
It might be worth pinging this issue in the community Slack channels inside the Kubernetes Slack project.

**Comment by jstrachan** [comment]
I'd recommend using tekton rather than a jenkins server which uses kaniko for building and pushing the container images, avoids using the docker daemon directly and has been tested to work great with `jx boot` and EKS - it defaults to using ECR for the container registry

**Comment by jstrachan** [comment]
see https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/
