### ISSUE TITLE
Permissions issue updating webhooks

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6599]
### Summary 
Under our new boot-based cluster, new projects created locally and existing projects imported from a previous instance are hitting a permissions error when trying to update the webhook:
```
Updating webhooks for Owner: project-coda and Repository: testx001 in git server: https://github.com
Checking hooks for repository project-coda/testx001 with user *********
WARNING: Querying webhooks on project-coda/testx001: GET https://api.github.com/repos/project-coda/testx001/hooks: 404 Not Found []
Creating GitHub webhook for project-coda/testx001 for url https://hook-**.ab.ai-coda.com/hook
WARNING: failed to update webhooks for Owner: project-coda and Repository: testx001 in git server: https://github.com: creating the webhook "https://hook-**.ab.ai-coda.com/hook" on repository 'project-coda/testx001': unable to create webhook for project-coda/testx001 - permission denied: POST https://api.github.com/repos/project-coda/testx001/hooks: 404 Not Found []
```

We are using the same user and bot accounts as we were on the previous cluster

### Jx version

The output of `jx version` is:

```
2.0.1143
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - Boot
- [ ] Classic Jenkins

**Comment by garethjevans** [comment]
@tdcox can you confirm that the bot account does have `admin` permission on the repository?

**Comment by tdcox** [comment]
@garethjevans Previously, bot accounts only required `write` permission on individual repos. If boot has widened this to `admin`, it needs to be raised as a security vulnerability.

**Comment by garethjevans** [comment]
Webhooks have always required admin permission to be created/updated so there should be a change there.  Its possible that with `jx boot` we update the webhooks as part of the pipeline and that will use the pipeline user rather than the local user so there may be a change in requirements there.  I'd have to look into it in more detail

**Comment by ccojocar** [comment]
Doesn't only require the following permissions to be able to update the hook:
```
 write:repo_hook Write repository hooks
 read:repo_hook Read repository hooks
```
on the `admin:repo_hook Full control of repository hooks`

These seems to work for me. 

@tdcox Is the issue occurring when you create the quickstart and then the project is imported in jx?

**Comment by tdcox** [comment]
I’m seeing it at the end of the boot log.

**Comment by ccojocar** [comment]
Did you tried to use only the permissions mentioned above on the hook instead of full admin? They seem to work for me.

**Comment by tdcox** [comment]
This seems unrelated to the permissions on the web token as these were already set.

**Comment by ccojocar** [comment]
Is the ` project-coda` the same organisation where you have the Jenkins X environments repositories? If it is a different org, you need to make sure that the Jenkins X bot user is a collaborator on that.

**Comment by tdcox** [comment]
They are in the same org.

**Comment by stepanselyuk** [comment]
> Did you tried to use only the permissions mentioned above on the hook instead of full admin? They seem to work for me.

I tried, but it did not work before I assigned admin permissions on the repository to the CICD user.
