### ISSUE TITLE
`jx import` imports wrong charts repository

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6604]
### Summary 
`jx import` creates the wrong `/charts/<repo-name>` when used on non-git repositories, when you specify a different name to initialize it.

### Steps to reproduce the behavior
1) Create a new repository without git (mkdir new-repo)
2) use `jx import`
3) choose a different name then the suggest default to initialize the repository
4) look in the `/charts/` repository, the name of the created repository won't match the name of the actual git repository, but will have the one of the local repository
5) Check the logs for the now occuring error

### Jx version

The output of `jx version` is:

```
jx                 2.0.1150
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @tomfrenken, Can you please supply the specific error.  FYI, @mrageh

**Comment by tomfrenken** [comment]
Sure, as you see here it searches for `charts/will-crash` but the wrong folder has been created, with the name of the local folder `charts/example` , instead of the initialized folder in git

```
Showing logs for build tomfrenken/will-crash/master #2 release stage from-build-pack and container step-promote-changelog
/bin/sh: line 0: cd: /workspace/source/charts/will-crash: No such file or directory

Pipeline failed on stage 'from-build-pack' : container 'step-promote-changelog'. The execution of the pipeline has stopped.
```

**Comment by supra08** [comment]
Hi @deanesmith, I would to work on this issue.

**Comment by deanesmith** [comment]
@supra08, that is great.  If you could, please supply a link to this issue in the PR comment.  Thank you.

**Comment by srv-twry** [comment]
@deanesmith Hi, I am looking to get started with contributing to this project and would like to take this up. It doesn't look like this is being actively worked at.

**Comment by Tazminia** [comment]
Hello, is this still a thing ?
