### ISSUE TITLE
Feature Request: Better custom build-pack support in `jx import`

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6606]
### Summary 
Today I wanted to create a new build-pack and therefore followed the suggested way of forking the current build-pack repository and adding your own build-pack in there step-by-step.

Currently there are many hurdles to actually use your custom build-pack, which could be optimized (maybe?) in a rather simple way.

As of today, you have to copy the new build-pack in your local repo, use `jx import --pack <your-pack>`, change the jenkins-x.yml to use the right URL and then re-run it.

The better way would be something like `jx import --pack <my-pack> --pack-url <my-pack-url>`
so the `--pack-url` flag would already write the url into the `jenkins-x.yml` this would prevent the need to change it manually and re-running it.

Additionally, with this flag the build-pack wouldn't have to be cloned manually into the local packs folder, but could instead be cloned in there automatically, which would make the use of custom build-packs super easy, since I wouldn't have to clone my build-pack every time manually into the local `~/.jx` folder.

### Steps to reproduce the behavior
1. Fork build-pack repo
2. Create `your-buildpack`
3. copy it to `~/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/`
4. Use `jx import --pack <your-pack>`
5. Watch it fail
6. Change `jenkins-x.yml` and add `buildPackGitURL: <your-url>`
7. Watch it work

### Jx version

The output of `jx version` is:

```
jx                 2.0.1150
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by tomfrenken** [comment]
I would suggest adding the same flag to `jx create quickstart`, as there the same issue occurs when running `jx create quickstart --pack <custom-buildpack> -g <git-organisation>`.

**Comment by abayer** [comment]
cc @jstrachan - this is the issue your #6628 duplicated, as best as I can tell.

**Comment by jstrachan** [comment]
@tomfrenken btw any flags added to `jx import` also appear on `jx create quickstart`
