### ISSUE TITLE
root folder name of a DevPod does not match the root folder name of a PR or Release Build

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#6614]
### Summary 
There is a discrepancy between the root path of BuildPods, (`/workspace/[project-git-repo-name]`), and the root path of a Release build (`/workspace/source`).

TLDR;
I agree with the _Best Practices_, stating that one should NOT assume the name of a Git repo's root folder, especially when it comes to Build systems; it is still an easy pitfall that Users might experience.

### Proposed solutions / improvements
- output `pwd` to a step in the all _BuildPacks_ (ease the debugging process)
- add a flag to `jx create devpod` that would clone the Git repo into a `/workspace/source'
- update _DevPod_ or additional documentation to note this discrepancy.

#### Check DevPod root
- create a DevPod from an existing project
- run `pwd` inside the DevPod.

#### Check Release and PR Build
- echo 'pwd' within a Custom Build step, or in a projects _make_ file
- check in code and look at Build logs (`jx get build log`)

### Expected behavior
Root folder in the build system to match Git repo's name.

#### Output from DevPod
```
[root@user-go project-name]# pwd
/workspace/project-name
```

#### Output from Release build
```
// Modified 'make release' with 'echo "Path: $(shell pwd)"'
// Output:
Path: /workspace/source
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1139
Kubernetes cluster v1.15.7-gke.2
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.1
Operating System   CentOS Linux release 7.7.1908 (Core)
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

### Operating system / Environment
OSX 10.13.6 (High Sierra)

**Comment by abayer** [comment]
I'd lean towards making devpods match up with pipeline pods, but others may disagree.
