### ISSUE TITLE
error: Failed to create repository arif/jkn due to: unexpected end of JSON input

### ISSUE THREAD

**Issue by arfiqbal** [jenkins-x/jx#6621]
### Summary
When i am trying to create  a quickstart using "jx create quickstart" i am gettting below error
 jx create quickstart
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /home/arif/.jx/jenkins-x-versions
select the quickstart you wish to create jenkins-quickstart
Using Git provider gitea.XXXX.com at http://gitea.xxxx.com
Do you wish to use arif as the Git user name? Yes
Who should be the owner of the repository? arif
Enter the new repository name:  jkn
Creating repository arif/jkn
Generated quickstart at /home/arif/jkn
Created project at /home/arif/jkn
The directory /home/arif/jkn is not yet using git
Would you like to initialise git now? Yes
Commit message:  test

Git repository created
selected pack: /home/arif/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/jenkins
replacing placeholders in directory /home/arif/jkn
app name: jkn, git server: gitea.xxxx.com, org: arif, Docker registry org: arif
skipping directory "/home/arif/jkn/.git"
WARNING: Remote repository creation failed. In order to retry consider adding '--no-draft' option.
error: Failed to create repository arif/jkn due to: unexpected end of JSON input
 
### Jx version
NAME               VERSION
jx                 2.0.1152
jenkins x platform 2.0.1910
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.11.0+d4cacc0
helm client        Client: v2.12.2+g7d2b0c7
git                2.25.0
Operating System   Ubuntu 16.04.5 LTS

verifying packages
error: package kubectl is an old version 1.11.0+d4cacc0. The version stream requires at least 1.13.2

### Jenkins type
Classic Jenkins

**Comment by arfiqbal** [comment]
@abayer Can you let me know what was the issue and does lighthouse support gitea ?

**Comment by abayer** [comment]
No, Lighthouse doesn’t support Gitea at this time, and since you’re using static Jenkins masters, Lighthouse isn’t relevant anyway. I don’t know exactly what the issue here is, I just put the appropriate labels on it.
