### ISSUE TITLE
error: updating credentils "http://git.xxx.com" in Jenkins: creating credentials "http://git.xxx.com" in Jenkins: 401 Invalid password/token for user: jenkins-admin

### ISSUE THREAD

**Issue by arfiqbal** [jenkins-x/jx#6622]
### Summary
jx create spring -d web -d actuator
Command "spring" is deprecated, it will be removed on Feb 1 2020. We now highly recommend you use jx create quickstart instead. Please check https://jenkins-x.io/docs/getting-started/first-project/create-quickstart/ for more details.
Using Git provider git.xxx.com at http://git.xxx.com
? Do you wish to use arif as the Git user name? Yes
? Who should be the owner of the repository? arif
? Enter the new repository name:  test
Creating repository arif/test
? Language: java
? Group: com.example
Created Spring Boot project at /home/arif/test
The directory /home/arif/test is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
selected pack: /home/arif/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/maven
replacing placeholders in directory /home/arif/test
app name: test, git server: git.xxx.com, org: arif, Docker registry org: arif
skipping directory "/home/arif/test/.git"
skipping ignored file "/home/arif/test/HELP.md"
Apache Maven is not installed so lets download: https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.4/apache-maven-3.5.4-bin.zip

downloadFile
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.4/apache-maven-3.5.4-bin.zip to /home/arif/.jx/mvn.zip...
Downloaded /home/arif/.jx/mvn.zip

util.Unzip

ReadDir
Apache Maven is installed at: /home/arif/.jx/maven
Pushed Git repository to http://git.xxx.com/arif/test
error: updating credentils "http://git.xxx.com" in Jenkins: creating credentials "http://git.xxx.com" in Jenkins: 401 Invalid password/token for user: jenkins-admin
 

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.0.1152
jenkins x platform 2.0.1911
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.11.0+d4cacc0
helm client        Client: v2.12.2+g7d2b0c7
git                2.25.0
Operating System   Ubuntu 16.04.5 LTS

verifying packages
error: package kubectl is an old version 1.11.0+d4cacc0. The version stream requires at least 1.13.2

COPY OUTPUT HERE
```

### Jenkins type

- [ ] Classic Jenkins

### Kubernetes cluster
Openshift cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->
arif@infra-vm-ubuntu:~$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

jx install --provider='openshift' --on-premise --domain="xxxxx" --git-provider-kind="gitlab" --git-provider-url="http://git.xxx.com" --git-username="arif"

### Operating system / Environment

<!--
In which environment are you running the jx CLI?
-->

**Comment by retr0h** [comment]
I'm having the same issue when copying my ~/.jx/ directory to my replacement system.

**Comment by retr0h** [comment]
> I'm having the same issue when copying my ~/.jx/ directory to my replacement system.

Figured it out.  I was running a much newer version of the jx binary.

**Comment by arfiqbal** [comment]
@retr0h  thanks it worked 
but now i am facing different issue 
When i try to run "jx create quickstart"
it shows error: No quickstarts match filter

I am using --git-provider-kind='gitlab'
