### ISSUE TITLE
jx import should allow build pack URL to be passed

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6628]
if you want to import a library (java/node/go) which is not going to be a container image / helm chart it would be nice to be able to specify a `--pack-url` argument to default the `buildPackURL` value in the generated `jenkins-x.yml` file.

e.g. if you wanted to import a java library it'd be nice to be able to do...

```jx import --pack-url https://github.com/jenkins-x-buildpacks/jenkins-x-classic.git```

and have the following `jenkins-x.yml` generated for you if there's no file in the git repo:

```yaml
buildPack: maven
buildPackURL: https://github.com/jenkins-x-buildpacks/jenkins-x-classic.git
```

**Comment by abayer** [comment]
Duplicate of #6606
