### ISSUE TITLE
Installing jx using terraform fails with node health check on GKE

### ISSUE THREAD

**Issue by srehmanproov** [jenkins-x/jx#6632]
### Summary .
 Using terraform created with jx create and trying to apply it to GKE fails health checks

### Steps to reproduce the behavior . 
Follow steps https://jenkins-x.io/blog/2019/04/03/terraform-jenkins-x/ . terraform apply fails with "All cluster resources were brought up, but: only 0 nodes out of 1 have registered"

### Expected behavior 
Jenkins cluster is up and running.

### Actual behavior: 
All cluster resources were brought up, but: only 0 nodes out of 1 have registered

### Jx version . 2.0.1142

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type serverless Jenkins

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster
GKE
 Using terraform

### Operating system / Environment
GCP

GKE

**Comment by garethjevans** [comment]
Hi @srehmanproov, the blog post you're referring to is out of date with the `jx create terraform` command being deprecated/removed shortly.  If you'd like to use terraform to create a JX cluster on GKE I'd suggest you take a look at https://github.com/jenkins-x/terraform-google-jx, this is a terraform module to create all the required infrastructure that you need for JX.  It's still a work in progress but we're using this internally.

**Comment by srehmanproov** [comment]
@garethjevans  👍
