### ISSUE TITLE
Boot in EKS resources

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6659]
### Summary 

An attempted to use Boot in EKS failed due to quota limitations.

There is no documentation specifying which resources will be created and which quotas we might need to check and, potentially, increase.

### Steps to reproduce the behavior

* Use an AWS account without increasing quotas.
* Use Boot to install Jenkins X in two separate clusters.

### Expected behavior

It works.

### Actual behavior

The last lines from the output from the second installation:

```
Creating secret access keys
error: unable to create/update Vault: unable to set cloud provider specific Vault configuration: unable to apply cloud provider config: an error occurred while creating the vaultCRD resources: generating the vault CloudFormation template failed: unable to create access key: LimitExceeded: Cannot exceed quota for AccessKeysPerUser: 2
        status code: 409, request id: 4b550153-c214-4470-b8d3-b5515d7089b9
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders' command in directory 'systems/vault', output: ''
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1162
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.17.0
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G2022
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

macOS

**Comment by deanesmith** [comment]
@vfarcic Can you describe the workaround, how you were able to get past the matter?

**Comment by vfarcic** [comment]
This fixed it:

```bash
echo "vault:
  aws:
    autoCreate: true
    iamUserName: \"$IAM_USER\"
  disableURLDiscovery: true" \
    | tee -a jx-requirements.yml

cat jx-requirements.yml \
    | sed -e \
    's@zone@region@g' \
    | tee jx-requirements.yml
```

However, after that, and on my second attempt, if failed because of https://github.com/jenkins-x/jx/issues/6659. It takes 30 days until a KMS is deleted, and I believe that the default limit is 2 (both created with the initial attempt to run `jx boot`.

The problem with both this and the other issue is that there is no documentation on how to use Boot in EKS (beyond "just change the `provider` and run it").

I'll try again on Friday and report back how far I got.
