### ISSUE TITLE
jx import :  error creating jenkins credential jenkins-x-chartmuseum 500 Server Error

### ISSUE THREAD

**Issue by vgallissot** [jenkins-x/jx#666]
Can't import project, it fails on error: `error: error creating jenkins credential jenkins-x-chartmuseum 500 Server Error`

My project was already imported in a previous jx installation that I just cleaned and re-installed with `helm del --purge jenkins-x` + `jx install --domain='foo.bar' --git-provider-url='https://github.foo.bar' --git-username='jenkinsx' --git-api-token='xxx' --provider=gke`.

My project already contains Dockerfile, Jenkinsfile and necessary charts.

```
± jx import --no-draft=true --verbose=true     
? Do you wish to use jenkinsx as the git user name: Yes
Everything up-to-date
error: error creating jenkins credential jenkins-x-chartmuseum 500 Server Error
```

I have no log regarding an error for chartmuseum or jenkins. (`kubectl log $podName`)  
`~/.jx/chartmuseumAuth.yaml` contains credentials different from `~/.jx/jenkinsAuth.yaml`

```
± jx version
NAME               VERSION
jx                 1.2.3
jenkins x platform 0.0.678
kubernetes cluster v1.9.6-gke.0
kubectl            v1.9.3
helm client        v2.8.1+g6af75a8
helm server        v2.8.1+g6af75a8
git                git version 2.14.3
```

Same problem with older version of `jx`

**Comment by rawlingsj** [comment]
I wonder if there's and old password in the `~/.jx/jenkinsAuth.yaml` for your Jenkins server URL.

I wonder if deleting the jenkins and chartmuseum auth yamls first helps when they're recreated by the install?

```
helm del --purge jenkins-x
rm ~/.jx/jenkinsAuth.yaml
rm ~/.jx/chartmuseumAuth.yaml
jx install --domain='foo.bar' --git-provider-url='https://github.foo.bar' --git-username='jenkinsx' --git-api-token='xxx' --provider=gke
```
works any better?

**Comment by vgallissot** [comment]
It works now, thanks!

I added the step `jx delete env` to delete all envs too, as we discussed on slack ;)

I could reinstall my jx cluster + import my project.

Tested this morning with `jx version 1.2.6`

**Comment by rawlingsj** [comment]
yay - and phew :) thanks for reporting back, I think we need to add a flag to the `jx uninstall` command  which does everything you did.  I'll raise a separate issue for that.

**Comment by rawlingsj** [comment]
raised https://github.com/jenkins-x/jx/issues/678
