### ISSUE TITLE
Very large amount of security warnings retuned by the static analysis of the Go source code

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#6662]
### Summary 

I ran a security scan against the latest master version of the source code and it returned __494 warnings__. See the attached report. 

[jx-go-security-scan.txt](https://github.com/jenkins-x/jx/files/4133729/jx-go-security-scan.txt)

### Steps to reproduce the behavior

Run the following command at the top of the source code:

`gosec -fmt=yaml -out=sec-scan-report.yaml ./...`

### Expected behavior

Fix the warnings and run continuously the security scan.  It seem that the current https://github.com/jenkins-x/jx/blob/master/jenkins-x-lint.yml pipeline doesn't scan for all warnings or doesn't use a recent version of gosec tool.

#6656 is related to this.

### Actual behavior

Fix warnings when they occur during the normal build.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by madchap** [comment]
@ccojocar can this scan be automated and ingested in defectdojo to start gathering a baseline?

**Comment by ccojocar** [comment]
It's should be automated over the `jenkins-x-lint` pipeline which calls this lint script https://github.com/jenkins-x/jx/blob/e4d57d59efaa11e33b09f33c36ee2c91ededffdb/hack/linter.sh#L26, where gosec is enable but somehow doesn't seem to have a very recent versions or some rules are disabled.

**Comment by ccojocar** [comment]
Definitely can be ingested in defectdojo, `gosec` supports the following report formats:
```
-fmt string
        Set output format. Valid options are: json, yaml, csv, junit-xml, html, sonarqube, golint or text (default "text")
```
I am not sure if defectdojo exposes any endpoint to ingest reports, but it should be achievable.
