### ISSUE TITLE
Automate CVE scans of container images

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6665]
### Summary 
Some containers produced from quickstarts seem to rely upon relatively out of date base images with high numbers of security vulnerabilities. We need a process to monitor and alert on this so that buildpacks are being updated appropriately.

It would also be useful to be able to package this as an Addon so that the same capability can be used to monitor containers produced for customer applications.

**Comment by ccojocar** [comment]
I think this a dup of https://github.com/jenkins-x/jx/issues/5349.

**Comment by tdcox** [comment]
Agreed. Wonder why that didn’t come up in my search?
