### ISSUE TITLE
Monocular UI does not display charts

### ISSUE THREAD

**Issue by gabeduke** [jenkins-x/jx#667]
Attempting to access monocular via ingress displays the UI but the charts section just shows a spinning icon. There is an error in console `GET http://monocular.jx.staging.riskbasedsecurity.net/api/auth/verify 404 (Not Found)`. What steps do I need to take in order to authenticate with the api?

Notes: I created the quickstart golang app and it built successfully and I see the package in the chartmuseurm index.yaml

**Comment by rawlingsj** [comment]
I just tested here and I can see the charts in monocular just fine.

<img width="1680" alt="screen shot 2018-04-18 at 16 01 50" src="https://user-images.githubusercontent.com/1457180/38940381-e70e5340-4321-11e8-8ff3-263152393f5e.png">

Monocular uses a single ingress rule but multiple backend services so the UI can talk to the api pod by rewriting traffic directed to `/api/` to `/`, these are done with nginx ingress annotations.

<details>
 <summary>result</summary>
<p>
{
  "data": [
    {
      "attributes": {
        "description": "A Helm chart for Kubernetes",
        "home": null,
        "maintainers": null,
        "name": "golang-issue-667",
        "repo": {
          "URL": "http://jenkins-x-chartmuseum:8080",
          "name": "chartmuseum",
          "source": "https://github.com/jenkins-x/jenkins-x-platfrom"
        },
        "sources": null
      },
      "id": "chartmuseum/golang-issue-667",
      "links": {
        "self": "/v1/charts/chartmuseum/golang-issue-667"
      },
      "relationships": {
        "latestChartVersion": {
          "data": {
            "app_version": null,
            "created": "2018-04-18T14:57:43.082367586Z",
            "digest": "8000b4abb8aec9f6ca97110e747183a96ed431c156b425df5209a978219aaec2",
            "icons": [
              {
                "name": "160x160-fit",
                "path": "/assets/chartmuseum/golang-issue-667/0.0.1/logo-160x160-fit.png"
              }
            ],
            "readme": "/assets/chartmuseum/golang-issue-667/0.0.1/README.md",
            "urls": [
              "charts/golang-issue-667-0.0.1.tgz"
            ],
            "version": "0.0.1"
          },
          "links": {
            "self": "/v1/charts/chartmuseum/golang-issue-667/versions/0.0.1"
          }
        }
      },
      "type": "chart"
    },
    {
      "attributes": {
        "description": "A Helm chart for Kubernetes",
        "home": null,
        "maintainers": null,
        "name": "my-demo-a1",
        "repo": {
          "URL": "http://jenkins-x-chartmuseum:8080",
          "name": "chartmuseum",
          "source": "https://github.com/jenkins-x/jenkins-x-platfrom"
        },
        "sources": null
      },
      "id": "chartmuseum/my-demo-a1",
      "links": {
        "self": "/v1/charts/chartmuseum/my-demo-a1"
      },
      "relationships": {
        "latestChartVersion": {
          "data": {
            "app_version": null,
            "created": "2018-04-17T08:36:47.482082954Z",
            "digest": "1ba13e67c7a2b77b27ab8a2ae23c10e6a8c86866626bc7cdb3e6b3d16f3653d2",
            "icons": [
              {
                "name": "160x160-fit",
                "path": "/assets/chartmuseum/my-demo-a1/0.0.1/logo-160x160-fit.png"
              }
            ],
            "readme": "/assets/chartmuseum/my-demo-a1/0.0.1/README.md",
            "urls": [
              "charts/my-demo-a1-0.0.1.tgz"
            ],
            "version": "0.0.1"
          },
          "links": {
            "self": "/v1/charts/chartmuseum/my-demo-a1/versions/0.0.1"
          }
        }
      },
      "type": "chart"
    }
  ]
}
</p>
</details>

When I try with your URL I get `404 page not found`

Are you running on GKE, AKS, DIY installation?  I wonder if you're using your own ingress controller that maybe doesn't work with these annotations on the monocular ingress rule.

One thing to check is if you can access the monocular charts API from inside another pod, say nexus.  Notice I'm curl'ing a URL without `/api/` in the subpath:
```
jx rsh nexus
curl http://jenkins-x-monocular-api/v1/charts
```
Does that return results?

**Comment by gabeduke** [comment]
I'm deployed to aws with kops and I'm using the addon [ingress controller](https://github.com/kubernetes/kops/tree/master/addons/ingress-nginx). Since I can curl the API from the nexus pod, the ingress controller must not be recognizing the extra annotations. I'll give a shot with the jx ingress controller. Thanks!

**Comment by gabeduke** [comment]
Closing: I was unable to find why the existing ingress controller was unable to work with jx annotations but deploying the jx ingress controller did fix the issue.

**Comment by rezmuh** [comment]
Hi, apologies for reopening this since I'm having the same issue so I think it would be better to just use this one rather than creating a new one.

Anyway, I've experienced this since the first time I installed jx a few months ago. I'm on AWS and I haven't gotten jx running smoothly 100% yet. But i thought i'd try by removing (or at least reporting) one issue at a time :D

Here's my current environment

jx version:
```
NAME               VERSION
jx                 1.3.221
jenkins x platform 0.0.2267
kubernetes cluster v1.10.5
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0
```
The command I used to create the cluster:

```
jx create cluster aws \
--kubernetes-version 1.10.5 \
--cluster-name cdub.tech \
--domain cdub.tech \
--http false \
--tls-acme true \
--zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c \
--master-size m4.large \
--nodes 2 \
--node-size m4.large
```
My monocular UI url: `https://monocular.jx.cdub.tech/`
 
The output of `curl http://jenkins-x-monocular-api/v1/charts` is:

```
[root@jenkins-x-nexus-75dd6d4446-ptq6k /]# curl http://jenkins-x-monocular-api/v1/charts
{
  "data": null
}
```

**Comment by athilaelhuno** [comment]
I have the issue relate with this:
1.- https://monocular.jx.efermin.ml/ . ---> . default backend - 404
2.- https://monocular.jx.efermin.ml/api/v1/charts 
`  |  
-- | --
data |  
0 |  
attributes |  
description | "A Helm chart for Kubernetes"
home | null
maintainers | null
name | "reactive01"
repo |  
URL | "http://jenkins-x-chartmuseum:8080"
name | "chartmuseum"
source | "https://github.com/jenkins-x/jenkins-x-platform"
sources | null
id | "chartmuseum/reactive01"
links |  
self | "/v1/charts/chartmuseum/reactive01"
relationships |  
latestChartVersion |  
data |  
app_version | null
created | "2019-01-08T18:23:13.417766552Z"
digest | "123d35128569dde4689e91c0c29110e20e5973a8596ef30520037bfb71b2f6e2"
icons |  
0 |  
name | "160x160-fit"
path | "/assets/chartmuseum/reac….1/logo-160x160-fit.png"
readme | "/assets/chartmuseum/reactive01/0.0.1/README.md"
urls |  
0 | "charts/reactive01-0.0.1.tgz"
version | "0.0.1"
links |  
self | "/v1/charts/chartmuseum/reactive01/versions/0.0.1"
type | "chart"
`
My ingress 

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    fabric8.io/generated-by: exposecontroller
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ingress.class: nginx
"/var/folders/h4/m3hv0ldj2cd72bqr8pk5bkqw0000gn/T/kubectl-edit-esds4.yaml" 48L, 1344C
metadata:
  annotations:
    fabric8.io/generated-by: exposecontroller
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: "2019-01-08T16:42:59Z"
  generation: 18
  labels:
    provider: fabric8
  name: monocular
  namespace: jx
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: jenkins-x-monocular-ui
    uid: 74423e62-1364-11e9-8366-02ba048a5f42
  - apiVersion: v1
    kind: Service
    name: jenkins-x-monocular-api
    uid: 743eadd2-1364-11e9-8366-02ba048a5f42
  resourceVersion: "767897"
  selfLink: /apis/extensions/v1beta1/namespaces/jx/ingresses/monocular
  uid: 7574a7ac-1364-11e9-af53-0ab6cbcd3206
spec:
  rules:
  - host: monocular.jx.efermin.ml
    http:
      paths:
      - backend:
          serviceName: jenkins-x-monocular-api
          servicePort: 80
        path: /api/
  tls:
  - hosts:
    - monocular.jx.efermin.ml
    secretName: tls-monocular`
Any ideas?

**Comment by VinodEgallapati** [comment]
@athilaelhuno , Did you happen to get any resolution. I am exactly facing the same issue.

1.- https://monocular.jx.efermin.ml/ . ---> . default backend - 404
2.- https://monocular.jx.efermin.ml/api/v1/charts - I have response

**Comment by athilaelhuno** [comment]
@VinodEgallapati, I reinstalled the Jenkins X but nothing I have the same behavior, I changed the domain name but nothing https://monocular.jx.efermin.cf. I don't know what is happening 

When I go to inside the UI container and execute 

`jx rsh jenkins-x-monocular-ui`

`curl http://jenkins-x-monocular-api/v1/charts`

```
{
  "data": [
    {
      "attributes": {
        "description": "A Helm chart for Kubernetes",
        "home": null,
        "maintainers": null,
        "name": "microservice01",
        "repo": {
          "URL": "http://jenkins-x-chartmuseum:8080",
          "name": "chartmuseum",
          "source": "https://github.com/jenkins-x/jenkins-x-platform"
        },
        "sources": null
      },
      "id": "chartmuseum/microservice01",
      "links": {
        "self": "/v1/charts/chartmuseum/microservice01"
      },
      "relationships": {
        "latestChartVersion": {
          "data": {
            "app_version": null,
            "created": "2019-01-18T00:23:40.186851802Z",
            "digest": "1420f2a95317f5dbbd27cb6e6d0630d8cd0e8e62bfecfdad509710b2d48f2a68",
            "icons": [
              {
                "name": "160x160-fit",
                "path": "/assets/chartmuseum/microservice01/0.0.4/logo-160x160-fit.png"
              }
            ],
            "readme": "/assets/chartmuseum/microservice01/0.0.4/README.md",
            "urls": [
              "charts/microservice01-0.0.4.tgz"
            ],
            "version": "0.0.4"
          },
          "links": {
            "self": "/v1/charts/chartmuseum/microservice01/versions/0.0.4"
          }
        }
      },
      "type": "chart"
    }
  ]
}
```

For some reason the UI is not showing the charts.

If any person has a solution for this issue please let me know

**Comment by QincaiLiu** [comment]
![image](https://user-images.githubusercontent.com/45627838/52628371-d2151280-2eb7-11e9-9ba7-4e83b9072daf.png)
I have the spinning icon as well, no more, probably the connection between k8s and github?
where does monocular fetch these charts?

**Comment by leechungkyu** [comment]
@QincaiLiu I am in the same situation. 
$ jx --version
1.3.891

**Comment by dimmel82** [comment]
@leechungkyu: The addition of ingress rule for jenkins-x-monocular-api service worked for me too

**Comment by romil-punetha** [comment]
> @leechungkyu: The addition of ingress rule for jenkins-x-monocular-api service worked for me too
Can you show what that ingress rule looks like?

**Comment by dimmel82** [comment]
> Can you show what that ingress rule looks like?

`kubectl get ingress monocular -n jx -o yaml` shows:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    fabric8.io/generated-by: exposecontroller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: "2019-03-06T17:54:49Z"
  generation: 25
  labels:
    provider: fabric8
  name: monocular
  namespace: jx
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: jenkins-x-monocular-api
    uid: ee163aee-4038-11e9-b7e3-005056946184
  - apiVersion: v1
    kind: Service
    name: jenkins-x-monocular-ui
    uid: ee1837ab-4038-11e9-b7e3-005056946184
  resourceVersion: "5413216"
  selfLink: /apis/extensions/v1beta1/namespaces/jx/ingresses/monocular
  uid: efcaec1d-4038-11e9-b7e3-005056946184
spec:
  rules:
  - host: monocular.jx.myhost.nip.io
    http:
      paths:
      - backend:
          serviceName: jenkins-x-monocular-api
          servicePort: 80
        path: /api/
  - host: monocular.jx.myhost.nip.io
    http:
      paths:
      - backend:
          serviceName: jenkins-x-monocular-ui
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - ip: myhost
```

**Comment by savealive** [comment]
I managed to fix it by changing following in ingress resource:
```nginx.ingress.kubernetes.io/rewrite-target: / => nginx.ingress.kubernetes.io/rewrite-target: /$1```
```path: / => path: /?(.*)```
```path: /api/ => path: /api/?(.*)```
