### ISSUE TITLE
PR pipelines to run `helmfile diff`

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6672]
it would be awesome if PRs on a helmfile based environment git repository would run `helmfile diff` and post the results to the PR as a comment. Then folks could see the effect of PRs before merge

**Comment by vbehar** [comment]
FYI in our current setup based on `helmfile`, we are running the following steps for each PR:
- `helmfile deps`
- `helmfile lint --skip-deps`
- `helmfile diff --skip-deps --suppress-secrets`
- `helmfile template --skip-deps | kubectl apply --dry-run -f -`

**Comment by jstrachan** [comment]
logging the diff in the master pipeline would be handy too for diagnostics
