### ISSUE TITLE
bulk promote for helmfile

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6674]
we have a single simple file, `jx-apps.yml` that defines all the apps in an environment; we should be able to create a batch promote command to create a PR on, say, Production based on the current versions in Staging by diff’ing the 2 files.

We could add CLI arguments to filter apps & include/exclude adds/updates/deletes etc

**Comment by ankitm123** [comment]
@jstrachan, should I work off this PR https://github.com/jenkins-x/jx/pull/6660?

**Comment by jstrachan** [comment]
yeah, thats probably the simplest for now. Hopefully we can get that PR merged in a little while
