### ISSUE TITLE
Not able to boot Jenkins X with local changes

### ISSUE THREAD

**Issue by srehmanproov** [jenkins-x/jx#6685]
### Summary 
Not possible to use jx boot from local cloned repo

### Steps to reproduce the behavior
Cloned a repo locally and make some changes. Merge this changes to master of local clone.
Run jx boot command
o version for https://github.com/local/environment-jenkinsx-dev-dev found in version stream https://github.com/jenkins-x/jenkins-x-versions.git, defaulting to master
Local boot clone is out of date. It is based on v0.0.7, but the version stream is using origin/master. The clone will now be updated to origin/master.
Stashing any changes made in local boot clone.
Booting Jenkins X
### Expected behavior
Jenkins x should boot with local clone
### Actual behavior
Jenkins stashes local changes.
### Jx version
2.0.1177
The output of `jx version` is:
jx                 2.0.1177
Kubernetes cluster v1.13.11-gke.23
kubectl            v1.15.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57

### Jenkins type
Server-less 

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE
terraform 
### Operating system / Environment
GKE

MacOS

**Comment by deanesmith** [comment]
Hi @srehmanproov, there are a couple of things you could do that I am aware of, and I'm sure other people will have much better ideas, but you could fork https://github.com/jenkins-x/jenkins-x-versions.git and clone your own.  Or, do `jx boot -r your-own-jx-requirements-file.yml`, though you will still clone and https://github.com/jenkins-x/jenkins-x-versions.git separately, but it will incorporate your configuration.

**Comment by srehmanproov** [comment]
@deanesmith thanks for suggestions,  seems Jenkins X gitOps bit flaky I have cloned jenkins-x-boot-config but sometimes things go horribly wrong. I worked it around be deleting local clone and re cloning it..

**Comment by deanesmith** [comment]
@srehmanproov thank you for the update.  There are a number of improvements with boot arriving in the coming weeks and months, some of them address this gitops matter directly - https://github.com/jenkins-x/jx/issues/6442.  If you are comfortable closing this issue please do.

**Comment by srehmanproov** [comment]
🥇 thanks @deanesmith
