### ISSUE TITLE
jx boot fails to install Vault

### ISSUE THREAD

**Issue by brec** [jenkins-x/jx#6687]
### Summary 
During `jx boot`  **STEP: install-vault**  with secrets config set to `secretStorage: vault` , `jx boot` fails to install Vault.

Error:

```
Creating vault resources with following values, us-east-1, Jenkins-x-dev-vault, vault-data, jenkins-x-vault-store
error: unable to create/update Vault: unable to set cloud provider specific Vault configuration: unable to apply cloud provider config: an error occurred while creating the vaultCRD resources: executing the Vault CloudFormation : unable to create vault prerequisite resources: MissingRegion: could not find region configuration
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders' command in directory 'systems/vault', output: ''
```

### Steps to reproduce the behavior

`export VAULT_AWS_SECRET_ACCESS_KEY=<secret access key of service user created for jx>`
`export VAULT_AWS_ACCESS_KEY_ID=<access key ID of service user created for jx>`

`jx edit requirements --terraform=true`
`jx boot`

Vault configuration:
```
vault:
  aws:
    autoCreate: true
    dynamoDBRegion: us-east-1
    dynamoDBTable:****
    iamUserName: ****
    kmsKeyId: ****
    kmsRegion: us-east-1
    s3Bucket: ****
    s3Region: us-east-1
```

provider configuration:
` provider: eks`

### Expected behavior
jenkins-x installs vault

### Actual behavior
jenkins-x fails to install vault

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1171
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.17.2
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.2+ga8b13cc
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [ X ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @brec.  Does [this](https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/install-guide/vault-eks) help at all?  Some recent EKS changes have not been captured in the OSS docs yet.

**Comment by brec** [comment]
hi @deanesmith I get a 404 "This page could not be found" when I attempt to visit that link.

**Comment by deanesmith** [comment]
@brec Sorry, it looks like the URL changed a bit since posting - https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/eks-install-guide/vault-eks

**Comment by brec** [comment]
hi @deanesmith  disabling `autoCreate` fixed the issue. I pre-configured the vault requirements, so in retrospect this makes sense, although I wasn't sure if disabling autoCreate would skip features I needed. This documentation cleared that up. I think providing a clear error message for this issue, along the lines of the resources are already created (or consider disabling `autoCreate`, would help as well.

thanks

**Comment by deanesmith** [comment]
FYI @brec, the document is now properly upstream here and as always contributions are welcome - https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/
