### ISSUE TITLE
Fails to query the Pull Request for repository in GitLab

### ISSUE THREAD

**Issue by DhruvM1994** [jenkins-x/jx#6689]
### Summary 
While trying to perform ```jx create quickstart``` using a GitLap repository the pipline fails.
However, the repositories "environment-production", "environment-staging" and the quickstart ("python-http") are created in GitLab.

### Steps to reproduce the behavior
1. Using kubernetes cluster in AKS with two nodes
2. ```jx install``` (using GitLab credentials)
3. ``` jx create quickstart --git-provider-url <gitlab_url> --git-username <gitlab_name> --git-api-token <GitLab_token>```

### Expected behavior
Pipeline should build project.

### Actual behavior
Pipeline fails to query repository.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1176
jenkins x platform 2.0.1961
Kubernetes cluster v1.14.8
kubectl            v1.15.5
helm client        Client: v2.16.1+gbbdfe5e
git                2.12.2.windows.2
Operating System   Windows 10 Enterprise 1809 build 17763
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster
- Using Kubernetes cluster in AKS (Azure)
``` az provider register -n Microsoft.ContainerService```
```az provider register -n Microsoft.Network```
```az group create --name <resource_group_name> --location <location>```
```az aks create --resource-group <resource_group_name> --name <context_name> --node-count 2 --generate-ssh-keys```
```az aks get-credentials --resource-group <resource_group_name> --name <context_name>```

### Operating system / Environment
```Windows 10 Enterprise 1809```

**Comment by abayer** [comment]
What's the error you're getting?

**Comment by DhruvM1994** [comment]
I am getting the following output in the web console:
```"Failed to query the Pull Request last commit status for https://gitlab.com/environment-staging/-/merge_request/1"```

**Comment by arfiqbal** [comment]
Even i am getting the same error in gitlab

**Comment by arfiqbal** [comment]
@DhruvM1994 you need to merge the PR from Gitlab

**Comment by srehmanproov** [comment]
Even after PR is merged to master, I am still getting this error on GitHub, is there any solution for this? Its stoping the CD to work at all.

**Comment by DhruvM1994** [comment]
@arfiqbal I merged the PR in GitLab but the pipeline stucks at: ```Merge commit has not yet any statuses on repo <repository_name> merge <sha>
