### ISSUE TITLE
create a wizard to create new scala/akka projects

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#669]
it looks like there's a nice web based wizard for creating new projects based on akka/scala: https://developer.lightbend.com/start/?group=akka

I wonder how hard it'd be to create a `jx create lightbend` command for creating new projects using scala/akka and then automatically setup in the CI/CD pipeilnes and promotion via GitOps so we can spin up projects like this demo:
http://jenkins-x.io/demos/create_spring/

**Comment by ccojocar** [comment]
There seems to be a quickstart for scala/akka https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/tree/master/packs/scala
