### ISSUE TITLE
Prometheus exporter needed to expose CI metrics from jx builds

### ISSUE THREAD

**Issue by rjaiwal5139** [jenkins-x/jx#6691]
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @rjaiwal5139, would you be able to further describe the use case you are looking to address?  It would be good to run through the desired state as well in greater detail.

**Comment by rjaiwal5139** [comment]
@deanesmith  I need to monitor the Jenkins X CI/CD and collect metrics like Launch Velocity (Time take for a pull request merged to reach Production), Number of deployments managed through pipelines, Number of deployments passed/failed and Total number of unit tests executed, passed/failed etc. 

These metrics represent how the build system is performing. Jenkins has a Prometheus plugin that collects some of these metrics. I was referring to having something similar for JenkinsX/Tekton builds.

**Comment by deanesmith** [comment]
Thank you @rjaiwal5139.  Jenkins X has an apps framework platform that is still evolving.  There is a Prometheus app here - https://github.com/jenkins-x-apps/jx-app-prometheus

**Comment by rjaiwal5139** [comment]
Thanks @deanesmith Can you describe the purpose of this app? Is it meant to scrape JenkinsX for metrics? Are these CI/Cd metrics?

**Comment by deanesmith** [comment]
@rjaiwal5139 Right now it appears to be not much more than a Prometheus deployment chart that will operate in the `jx apps` framework.  @rawlingsj could elaborate more on the intent, but the stage might be set reasonably well to further this a bit to accomplish what you like.
