### ISSUE TITLE
Release versioning control from pipelines is failing

### ISSUE THREAD

**Issue by marlovil** [jenkins-x/jx#6701]
### Summary 
I'm trying to implement release control from pipeline configuration.

I've added a Makefile file with `VERSION := 2.0.0` in the first line. After doing this, if I run `jx-release-version` I get the desired release (2.0.0).

But when I commit to master and JX build the new release I get the 'old' release (1.2.45) instead of the version defined in Makefile `VERSION` variable.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1126
jenkins x platform 2.0.1865
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.14.7-eks-1861c5
helm client        Client: v2.16.1+gbbdfe5e
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
EKS

**Comment by marlovil** [comment]
@vfarcic adding you as we talked. Many thanks! :)

**Comment by vfarcic** [comment]
@marlovil Can you let me know which buildpack you're using and whether it is one of the community maintained and as-is or a modified version?

**Comment by marlovil** [comment]
@vfarcic We are using the default php buildpack with some extensions as follows:

```
buildPack: php
pipelineConfig:
  agent:
    label: jenkins-maven
    container: maven
  pipelines:
    pullRequest:
      build:
        preSteps:
        - name: unit-tests
          agent:
            image: php:7.4-fpm-alpine
          command: |
            apk update
            apk add --virtual build-dependencies git
            cd app
            curl -sS https://getcomposer.org/installer | php -- --filename=composer.phar
            php composer.phar install
            php vendor/bin/phpunit --order-by=random --filter=Unit
```

**Comment by vfarcic** [comment]
I think that Maven might be a problem since it expects version to be set in `pom.xml`, even though you're using PHP. Can you please do a quick test with a new quickstart that is without those changes in the pipeline? That way, we'll be able to see whether the issue is in the additional entries or somewhere else. We'll be able to narrow the scope.

**Comment by marlovil** [comment]
I've deleted the agent section to leave it as default (using jx-base agent). We did this change as a workaround to face this issue https://github.com/jenkins-x/jx/issues/6603.

Without Maven agent, we are still having the same behavior. As expected, the patch number increases automatically but in the same `major.minor` previous version (`1.2.xx`). 

Just to make sure: we've created the Makefile in the root directory of the repo (at the same level as jenkins-x.yml file).

**Comment by abayer** [comment]
The agent as `maven` isn't going to be a problem - that logic only kicks in when using the Maven build pack.

What's happening here is that the default `setVersion` behavior in https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/php/pipeline.yaml#L27-L30 is just looking at the previous release tag to determine the next version. You can override that by adding:

```
    release:
      setVersion:
        steps:
        - sh: jx step next-version --filename Makefile --tag
          name: tag-with-new-version
```

after the `pullRequest` section in your `jenkins-x.yml`.

**Comment by marlovil** [comment]
Great! Many thanks @abayer and @vfarcic for your help.
