### ISSUE TITLE
AWS Parameters for Vault not created for Provider AWS with jx boot.

### ISSUE THREAD

**Issue by jweaver-personal** [jenkins-x/jx#6707]
### Summary 
AWS Parameters do not appear to be created from config for Vault under provider AWS, causing vault installation to fail for that provider with

error: unable to create/update Vault: aws selected as kube provider, but no aws specific parameters provided

See https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/boot/step_boot_vault.go around line 167.

### Steps to reproduce the behavior
Select AWS Provider, and vault for secretsStorage, add AWS options to jx-requirements.yml for Vault.

jx boot

### Expected behavior
AWS Parameters from jx-requirements.yml are used.
### Jx version

The output of `jx version` is:
```
2.0.1182
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
Rancher provisioned on AWS.

### Operating system / Environment
Ubuntu 18

**Comment by simisoz** [comment]
Hi is there a workaround to fix this error?
