### ISSUE TITLE
OWNERS file get automatically replaced with default during upgrade

### ISSUE THREAD

**Issue by anthony-pastor** [jenkins-x/jx#6712]
### Summary 
During CJXD upgrade (to 0.0.27 version), the OWNERS files get overwritten with default values.

### Steps to reproduce the behavior

- Create a PR on the Dev env to customize the OWNERS file with your own approvers and reviewers.
- Merge it and wait for the PR & release pipelines to complete.
- `jx upgrade boot`
You may observe an automatic change in the PR to be created.

### Jx version

in our case we were upgrading from/to:
```
-appVersion: 2.0.1005+cjxd.5
+appVersion: 2.0.1139+cjxd.6
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)

**Comment by abayer** [comment]
What was the `jx` binary's version when you ran `jx upgrade boot`?

**Comment by anthony-pastor** [comment]
@abayer Before upgrade I was using: `2.0.1005+cjxd.5`

**Comment by abayer** [comment]
Sorry for the late response - this was fixed in jx about a week after the version used for CJXD 5. It should be in CJXD 6 and all future releases. Sorry again!
