### ISSUE TITLE
Pipeline build can not be started

### ISSUE THREAD

**Issue by mighani** [jenkins-x/jx#6714]
### Summary 
I created a one node kubernetes cluster and installed jenkins x onto the cluster with following command:
```
jx install \
--provider $PROVIDER \
 --external-ip $LB_IP \
 --domain $DOMAIN \
 --default-admin-password admin \
 --ingress-namespace $INGRESS_NS \
 --ingress-deployment $INGRESS_DEP \
 --default-environment-prefix jx-rocks \
 --git-public=true
```
I used the serverless version of jenkins x. The installation was successfull. Now, I try to install a quickstart (golang and spring). the command creates the git repo for the project and installs a webhook. But after this I receive the following error:
......
Pushed Git repository to https://github.com/mighani/jx-go
Creating GitHub webhook for mighani/jx-go for url http://hook.jx.k8s.skillbyte.de/hook
**error: failed to start pipeline build:** creating prowjob the server could not find the requested resource: 404 page not found

### Expected behavior
The build should be triggered 

### Actual behavior
build can not be triggered

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1186
jenkins x platform 2.0.1971
Kubernetes cluster v1.15.9
kubectl            v1.17.2
helm client        Client: v2.13.1+g618447c
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

One Node Cluster on Digital Ocean (Droplet)  installed with Rancher

### Operating system / Environment
Ubuntu 18.04.3 LTS

MacOS

**Comment by abayer** [comment]
Please try again with `jx boot`, and open a new issue if you reproduce the issue there. `jx install` is more-or-less deprecated at this point, so its behavior, particularly when going through a path that `jx boot` should support, may be hard to deal with. Thanks!
