### ISSUE TITLE
Enable integrated testing of the jx stack for PRs spanning multiple repositories

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6726]
Currently, there is no way to effectively run BDD tests for jx for a combination of PRs from multiple repositories, short of manually spinning up a cluster and running the BDD tests by hand. Given the number of cases where a PR to jx has a corresponding PR to jenkins-x-boot-config (or other repos, but that's the combination that's most common), and we can't really test one without the other. The result is that one of the PRs can be made to pass the repo-specific BDD tests without the other, basically by not actually exercising the changed/new behavior, and we don't discover the problems with that PR until it's merged and made it into the version stream and the other PR can actually be tested. This is painfully inefficient, and leads to issues slipping through.

Therefore, we need a way to test PRs against multiple repositories together.

We're going to target a relatively small number of repositories in the initial scope, primarily because these are the repositories that most often require such cross-repo changes:
* https://github.com/jenkins-x/jx
* https://github.com/jenkins-x/jenkins-x-boot-config
* https://github.com/jenkins-x/jenkins-x-versions
* https://github.com/jenkins-x/jenkins-x-platform

Once those are in place, we'll see what other repositories (such as https://github.com/jenkins-x-charts/jxboot-resources and https://github.com/jenkins-x/jenkins-x-boot-helmfile-config) make sense to incorporate next.

**Comment by jstrachan** [comment]
@abayer sounds good to me.

Incidentally whenever the helmfile stuff merges, to do the same kinda thing with helmfile/helm 3 we won't need to do custom builds of `jenkins-x-platform` (as its no longer used) and don't need a custom fork/PR of `jenkins-x-boot-config` as there's nothing version specific in there any more. So we could just use a custom version stream + custom builder images (which we already have) + the jx PR.

BTW I hit an issue recently with builder images not being used in lighthouse for metapipeline client; so we maybe wanna figure out a way to parameterise that image a little easier too. We shouldn't need to do a new lighthouse release or anything; just figure out a way to modify its builder image used inside the metapipeline client. Hopefully the `jenkins-x-versions` changes above fixes that too?

Whether using helm 2 / helm 3; it might be nice to verify all images used in all pods throughout the bdd tests too; just in case something goes a bit wonky in the helm charts / values files etc. Its so easy for you to think you've swapped an image out and a different one sneaks in ;)
