### ISSUE TITLE
reusable context pipelines

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6727]
it would be nice to be able to have reusable pipelines in the build pack which can be applied to any git repository without having to modify the repositories source code.

e.g. if we added a file `contexts/go-lint/jenkins-x.yml` to the build pack git repository and configured `go-lint` as a context in the `Scheduler` of a few `SourceRepository` repositories it would be awesome to be able to type `/test go-lint` (or have it automatically build)

Then we can modify the `jx step effective pipeline` that if a context is being built and there's no local `jenkins-x.yml` file we look in the build pack first

**Comment by jaybatra26** [comment]
Hi! I am aspiring for GSOC and would like to contribute. Can I pick this up?
Are there any necessary links I could make use of ?
