### ISSUE TITLE
AWS Automate recordset creation for Preview environments

### ISSUE THREAD

**Issue by sauravdevops** [jenkins-x/jx#673]
**Feature Request**
- Can we automate the RecordSet creation to point to the loadbalancer.
- This is to have custom or your own orgs domain name rather than using the .nip.io local dns mapping

**Why the request**
If I am choosing my own domain name, which is my public hosted zone in AWS. I have to manually go and create the recordset to point to the DNS Name.
This is fine for a one time activity for environments like (Dev, Stating, Production)

Preview Environments which get created on the PR to the application, have a dynamic environment generated. Its very cumbersome to go and create a recordset to be able to test the application.

**Comment by rawlingsj** [comment]
That sounds like a very good idea.  I'm not as familiar with AWS as I am GKE, I don't suppose you know if this can be done via CLI?  A quick google found me this https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-creating.html
but it looks like a manual UI step is needed.  If you have any hints or ideas we should hopefully be able to add in to jx easily enough.

**Comment by sauravassuritynz** [comment]
You can do it with the AWS CLI https://docs.aws.amazon.com/cli/latest/reference/route53/change-resource-record-sets.html

**Comment by rajboruah** [comment]
This will help a lot ! In fact, I got in to log this issue. Any url that comes out due to application deployment or the dns recordset that points to the ELB duriing jenkins-x installation should possibly be automatically created in Route53.
