### ISSUE TITLE
Improve documentation for EKS support using JX Boot

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6732]
### Summary 
There are a great deal of steps required to ensure EKS based JX clusters are created properly when using `jx boot`.  These steps are captured well in CloudBees Jenkins X Distribution documentation but not yet properly represented upstream.  It is imperative that upstream documentation be the source of truth for common concerns.    

This issue is to recommend and perform the following steps:

1) Copy and edit the content from https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/eks-install-guide/aws-iam-permissions to this page https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/ in a new section for configuring permissions.  Index the page and add anchors for each section.

2) Copy and edit the content from https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/eks-install-guide/vault-eks to this page https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/ in a new section for configuring Vault.  Index the page and add an anchor for this section.

3) Copy and edit the content from https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/eks-install-guide/eks-dns-tls to https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/ in a new section for configuring TLS and DNS.  Index the page and add an anchor for this section.

### Jenkins type
- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
EKS

**Comment by vfarcic** [comment]
It would be very helpful to provide a script (in whichever format) that would create a sample set of resources. More often than not, exploring the requirements through a script is easier than through text.

**Comment by deanesmith** [comment]
Thanks @vfarcic, script samples are included.
