### ISSUE TITLE
Install JX UI with JX Boot by default or provide an option

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#6733]
### Summary 
JX UI needs to be installed after jx boot. that doesn't make any sense. 

### Expected behavior
JX UI comes with or can be selected in JX Boot
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
@corinnekrych FYI, this is something we have been discussing to do soon.
