### ISSUE TITLE
GKE cluster created with terraform code and jenkins with jx boot promotion fails

### ISSUE THREAD

**Issue by srehmanproov** [jenkins-x/jx#6735]
### Summary 
GKE cluster created with terraform code and jenkins with jx boot promotion fails
### Steps to reproduce the behavior
GKE cluster created with terraform code, and using jx boot to install jenkinsX server-less, promotion to staging is broken. When I created cluster with this command line all seems to work fine?  jx create cluster gke --cluster-name <cluster-name> --project-id $PROJECT  --region europe-west1-c -m n1-standard-2 --min-num-nodes 3  --max-num-nodes 6 --default-admin-password=admin  --default-environment-prefix tekton --git-provider-kind github  --prow --tekton --git-public true
### Expected behavior
The promotion to staging should work
### Actual behavior
Promotion fails and staging env is not created at all
### Jx version
2.0.1180
The output of `jx version` is:
jx                 2.0.1180
jenkins x platform 2.0.1984
Kubernetes cluster v1.13.11-gke.23
kubectl            v1.15.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.3 build 19D76
```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

### Operating system / Environment
MacOs

MacOs

**Comment by garethjevans** [comment]
Hi @srehmanproov, can you give us some guideance on how you created the cluster? e.g. via `jx create terraform` or via the `terraform-google-jx` module?

**Comment by srehmanproov** [comment]
@garethjevans I tried both methods, same result for each of these methods.

**Comment by srehmanproov** [comment]
@garethjevans @cagiti any progress on this? Its blocking us moving to Jenkins X as CI/CD solution.
