### ISSUE TITLE
jx boot for on-premise kubernetes

### ISSUE THREAD

**Issue by arfiqbal** [jenkins-x/jx#6741]
How do i use jx boot for on-premise kubernetes

Below is my jx-requirements.yml
`autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://mygithub-enterprise.com/githubadmin/jenkins-x-boot-config
cluster:
  gitKind: github
  gitName: github
  gitServer: https://mygithub-enterprise.com
  namespace: jenkinsx
  project: jenkinsx
  provider: kubernetes
environments:
- ingress:
    domain: k8sapp.xxxxxx.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
- ingress:
    domain: k8sapp.xxxxxx.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
- ingress:
    domain: k8sapp.xxxxxx.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
gitops: true
ingress:
  domain: k8sapp.xxxxxx.com
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
`
`
arf@master1:~/jenkins-x-boot-config$ jx boot
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config from https://github.com/jenkins-x/jenkins-x-versions.git
Booting Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /home/arif/jenkins-x-boot-config/env

Git configured for user: arif and email arf.@xxx.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /home/arif/jenkins-x-boot-config

jx boot has only been validated on GKE and EKS, we'd love feedback and contributions for other Kubernetes providers
`

jx version
--------------------
NAME               VERSION
jx                 2.0.1180
jenkins x platform 2.0.1965
Kubernetes cluster v1.16.6
kubectl            v1.16.0
helm client        Client: v2.12.2+g7d2b0c7
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

**Comment by ankitm123** [comment]
I tried `jx boot` on Linode Kubernetes Engine, which is basically on-prem as far as jx is concerned, and it worked. You just need to continue, after you get that message 
(`jx boot has only been validated on GKE and EKS, we'd love feedback and contributions for other Kubernetes providers`). 
What is the error message you are seeing? @arfiqbal

**Comment by ravenchilde** [comment]
@daveconde  - I'm using it on an on-prem install on VMs using RHEL7.5, and it works fine except it won't accept or add CA for self-signed certs for Bitbucket Server.

**Comment by 2020testuser** [comment]
Is this issue resolved? I also ran into self-signed certs error. Any info. would be very useful.

**Comment by infa-ddeore** [comment]
is there an `jx install --on-premise` equivalent option in `jx-requirements.yml` ? 

`jx boot` fails on minukube while waiting on external ingress, there is an option to use jx install command instead with --on-premise but [document](https://jenkins-x.io/docs/resources/guides/managing-jx/old/install-on-cluster/) comes under deprecated section.

```
STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /Users/test/tmp/tekton/jenkins-x-boot-config/env

Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
If you are installing Jenkins X on premise you may want to use the '--on-premise' flag or specify the '--external-ip' flags. See: https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output: ''
```

**Comment by ravenchilde** [comment]
Fixed by installing gitlab. /close
