### ISSUE TITLE
jx boot fails with existing resource conflict Environment dev

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx#6746]
### Summary 
jx boot fails with:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: Environment, namespace: jx, name: dev'
```

### Steps to reproduce the behavior

```
$ run jx boot
```

### Expected behavior
it should work

### Actual behavior
it fails at step install-jenkins-x because the jx namespace is created by default and it feels like the dev anv is added by default by the jx cli or by previous step.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1192
Kubernetes cluster v1.15.2
kubectl            v1.17.0
git                2.21.1

```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
on premise using kubespray

### Operating system / Environment

fedora 30

**Comment by hferentschik** [comment]
Is this the first time you are running boot? Are you running against a newly created cluster? If so how did you create it?

The error seems to indicate that the _dev_ environment seems to already exist which would imply that there was a previous Jenkins X install, is that correct?

Can you paste more of the log / error message?

**Comment by yelhouti** [comment]
The k8s cluster is on bare metal server installed using kubespray as written in the issue.

Before running jx boot I delete the namespace jx, this should therefore not happen.
When debugging I found that when I run jx boot, at the very beginning before starting the `install-jenkins-x` step the namespace is recreated and the env is added. maybe with helm2 it is overridden without a problem, but with helm 3 It can't override it due to a difference of version or something.

**Comment by yelhouti** [comment]
@hferentschik can i help you with anything else?
