### ISSUE TITLE
BDD tests fail if run in debug/verbose mode

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#6749]
### Summary 

When running the bdd tests, there are a few areas where we take the output of a `jx` command, parse and evaluate it. If the env variable JX_LOG_LEVEL is set to debug, then this fails.  We should handle this scenario and strip all DEBUG prefix lines from evaluation

### Steps to reproduce the behavior

Run the bdd tests with JX_LOG_LEVEL set to debug

**Comment by hferentschik** [comment]
Generally, I think we should try to not depend output of the `jx` command in this form. This will always be fragile. There are probably some cases where we need it, but there are several where there are other ways to verify a specific state.

Another thing we should consider is the introduction of a `machine-readable` flag or similar. Several CLIs (eg `git`, `vagrant`, etc) have this concept. The idea is to have an easy machine-readable output which you consider part of the API. Scripts should depend on this output as opposed to the standard user output. Parsing becomes easier for the caller of the command and one has more flexibility improving the UX.
