### ISSUE TITLE
Run jx with GIT_TRACE=true

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#6750]
### Summary 

If I run `jx` with GIT_TRACE=true, jx hides all of the output and then fails when we try to capture gits output.  It would be nice if we could enable this feature as its really handy when debugging why commands are failing

### Steps to reproduce the behavior

export GIT_TRACE=true
any jx command

**Comment by hferentschik** [comment]
I looked into this once, but there was a reason why it was not trivial to achieve. 
If you use the `--verbose` flag for `jx`, all git commands are logged which is already very helpful.
