### ISSUE TITLE
jx boot stuck on Creating boot config with defaults

### ISSUE THREAD

**Issue by sawujul** [jenkins-x/jx#6752]
### Summary 
While going through the getting-started documentation/tutorial, including allowing jx to create a new cluster on gke, on jx boot it gets stuck on "Creating boot config with defaults, as not in an existing boot directory with a git repository." and never progresses even after 20+ minutes.

### Steps to reproduce the behavior
Install jx (using chocolatey in my case) on win 10 Pro
run jx create cluster gke, all default settings with existing Github user
run jx boot

### Expected behavior
Whatever is supposed to happen when you run jx boot (according to https://jenkins-x.io/docs/getting-started/setup/boot/ )

### Actual behavior
Command line logs "Creating boot config with defaults, as not in an existing boot directory with a git repository." and then does nothing until manually cancelled.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1194
jenkins x platform 2.0.1984
Kubernetes cluster v1.14.10-gke.17
kubectl            v1.15.5
helm client        Client: v2.14.2+ga8b13cc
git                2.25.0.windows.1
Operating System   Windows 10 Pro 1903 build 18362
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Google Kubernetes Engine with default settings from jx

### Operating system / Environment

Win 10 Pro version 1903

**Comment by l0stmylife** [comment]
Did you solve this issue? I'm having the exact same issue right now.

**Comment by sawujul** [comment]
No I didn't, and I didn't know I had closed this. Still an issue, but I'm not actively attempting to resolve it anymore on my part as a colleague was able to continue on his Linux machine.

**Comment by l0stmylife** [comment]
Issue seems to be the jx boot not cloning the https://github.com/jenkins-x/jenkins-x-boot-config repository. You can solve this by manually cloning the repository and completing the jx-requirements.yml file. Posting this for people having the same issue.
