### ISSUE TITLE
Retrieve logs even when PipelineActivity is garbage collected

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#6759]
At the moment we rely on the log URL from the PipelineActivity to retrieve the logs. Since PipelineActivities get garbage collected you often end up trying to access logs (eg when looking at . pull request after a couple of days) which cannot be retrieved this way. In the UI you get the message "no build logs available". 

The build logs are, however, available, it is just that the PipelineActivity is garbage collected. In this case, we should construct the URL for the logs dynamically and try to retrieve the logs directly. All necessary information should be available.

**Comment by abayer** [comment]
The UI is still dependent on `PipelineActivity` for step listings, etc, so I'm not sure if it would really benefit from this.

**Comment by hferentschik** [comment]
> The UI is still dependent on PipelineActivity for step listings, etc, so I'm not sure if it would really benefit from this.

ahh, I was not aware of this part. That might put a break into this idea. It might be a point for the re-design of the logging service thought. In a perfect world where the logs contain all the metadata, it should really the logging service which provides you with the steps.
