### ISSUE TITLE
Cloud provider on boarding improvements

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#6763]
# Summary
The current cloud providers integrations are scattered across many files throughout the jx source code and boot configuration. This makes it quite difficult to integrate Jenkins X with new cloud providers and also to maintain the existing integrations. 

Furthermore, various cloud resources are dynamically created by Jenkins X using the cloud providers CLI functionality.  Many users would rather prefer to maintain their cloud configuration as code instead of relying on jx to create these cloud resources during the boot process. One of the big advantages of using tools such as terraform for cloud configuration management is that the configuration is kept in sync with the real cloud resources state, and it can be re-applied in an idempotent fashion without deleting and recreating cloud resources.   

# Some of the implications of this problem are:
- It makes the extensibility and maintainability of Jenkins X in regards to cloud providers difficult.
- It can easily lead to regressions in other cloud providers when changes are done to a cloud provider not related to them. 
- It makes running Jenkins X with various cloud provider related features turned off quite difficult. 
- Separating the cloud resources management from cloud provider integration is not that clear (creating cloud resources vs effective cloud provider API calls). Also following practices like configuration as code for cloud resources is sometimes cumbersome.  
- It also leads to duplication of effort when introducing new features. 
- The cloud providers contributors have a high barrier to entry.

**Comment by hferentschik** [comment]
Closing this epic in favor of #6855
