### ISSUE TITLE
Add method to pass in sslVerify paramter with value to PipelineResource CRD, or add CA cert to metapipeline git container

### ISSUE THREAD

**Issue by ravenchilde** [jenkins-x/jx#6774]
### Summary 
Git servers with self-signed or self-CA signed certificates do not work in Jenkins-X (internal respository server in corp, as an example). Tekton supports turning off sslVerify, but Jenkins-X does not document a method to use this feature of TektonPipelines.

Would be good to have a way to pass key "sslVerify" with value "false" to PipelineResource CRD Objects (type: git). 

### Steps to reproduce the behavior
Add a repository with self-signed certificate on a machine with the correct CA. Everything will install properly, but when a commit triggers Jenkins-X build, the git pull will fail with an errror message about the SSL certificate.

I modified the CRD Object and poked Jenkins-X and was able to complete one build, but the next build created a new PipelineResource object for git and it no longer worked. Need a way to get the flag into the thing that creates the PipelineResource object.

### Expected behavior
A way to pass sslVerify false to the PipelineResource CRD git type objects (in jenkins-x.yml or elsewhere? In the environment? in jx-requirements.yml under environments? in gitAuth.yml?), during the Meta Pipeline creation.

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  creationTimestamp: '2020-02-20T21:06:29Z'
  generation: 2
  name: meta-ana-test-repo-master-k9z86
  namespace: jx
  ownerReferences:
    - apiVersion: jenkins.io/v1
      kind: PipelineActivity
      name: ana-test-repo-master-4
      uid: 38875f29-eb61-424b-89bd-90942f9ea0bb
  resourceVersion: '608646'
  selfLink: >-
    /apis/tekton.dev/v1alpha1/namespaces/jx/pipelineresources/meta-ana-test-repo-master-k9z86
  uid: 2f6643d1-5d69-49ec-82c0-a082e17f6805
spec:
  params:
    - name: revision
      value: master
    - name: url
      value: 'https://bitbucket.xxxx.ad/scm/ana/test-repo.git'
    **- name: sslVerify
      value: 'false'**
  type: git
### Actual behavior
Objects are created like:
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  creationTimestamp: '2020-02-20T21:06:29Z'
  generation: 2
  name: meta-ana-test-repo-master-k9z86
  namespace: jx
  ownerReferences:
    - apiVersion: jenkins.io/v1
      kind: PipelineActivity
      name: ana-test-repo-master-4
      uid: 38875f29-eb61-424b-89bd-90942f9ea0bb
  resourceVersion: '608646'
  selfLink: >-
    /apis/tekton.dev/v1alpha1/namespaces/jx/pipelineresources/meta-ana-test-repo-master-k9z86
  uid: 2f6643d1-5d69-49ec-82c0-a082e17f6805
spec:
  params:
    - name: revision
      value: master
    - name: url
      value: 'https://bitbucket.xxxx.ad/scm/ana/test-repo.git'
  type: git
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1200
Kubernetes cluster v1.15.5
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.19.2
Operating System   Mac OS X 10.15.3 build 19D76
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Lighthouse)

### Kubernetes cluster

Minikube. Docker for Mac's kubernetes implementation.

### Operating system / Environment
MacOS Catalina

**Comment by ravenchilde** [comment]
Related to https://github.com/tektoncd/pipeline/issues/1328 it seems. @jstrachan

**Comment by daveconde** [comment]
@ccojocar it would be good to get your thoughts on this from a security point of view

**Comment by ccojocar** [comment]
I am not sure if disabling the certificate verification is the best option, because this is more or less similar with tuning TLS off. 

I would rather prefer to have an option to install a custom certificate in Jenkins X but still keep the TLS verification on (e.g. add the certificate to the trusted chain).  This will prevent Man in the Middle attacks.

**Comment by ravenchilde** [comment]
@ccojocar - Installing a cert is fine, although I'm not sure you need to hold folks hands with enforcing security (Tekton has already opted not to). You aren't wrong, of course you are right about the security danger, and your proposed method is better, but I'm not sure you need to enforce certs and security. 

Either way, I'll be watching the project to see when you enable injecting the CA chain we use to self-sign the repo cert. 

Appreciate you looking into it.
