### ISSUE TITLE
Create vanilla AKS terraform Template

### ISSUE THREAD

**Issue by helayoty** [jenkins-x/jx#6780]
### Summary

The ask is to create a terraform script to create a vanilla AKS cluster.

### Steps to reproduce the behavior

NA

### Expected behavior

AKS cluster is running first and has all permissions needed so JX can run 

### Actual behavior

_jx boot_ cli creates the AKS cluster and we need to decouple the k8s cluster creation and jx  

### Jx version Latest

The output of `jx version` is:

NA

### Jenkins type N/A

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster 

AKS cluster using terraform script

### Operating system / Environment

Windows/lunix

**Comment by dgozalo** [comment]
Hello @helayoty, I created an issue in the new provisioners repository as we'd like to keep all the Terraform scripts related work in there.

It's this one: https://github.com/jenkins-x/jx-cloud-provisioners/issues/21.

Do you mind closing this one and focusing on the new one please?

**Comment by helayoty** [comment]
no problem
