### ISSUE TITLE
Delete resources

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6781]
### Summary 

`jx boot` creates quite a few resources. Depending on the provider, they might be scattered all over. How can we delete those resources after deleting the cluster? If there is a command that creates something (e.g., `jx boot`), there must be a command that deletes those same resources.

**Comment by hferentschik** [comment]
Correct. Most likely there won't be a fix for this, however, in the current form of `jx boot`. We are working on separating the cloud resource creation from the Jenkins X install. Managing cloud resources will fall outside the direct Jenkins X responsibilities. See also https://github.com/jenkins-x/enhancements/pull/13

The idea is to provide a set of Terraform scripts for the case where one does not want to manage the resources manually. With Terraform you would then, for example, be able to do a `terraform destroy`.
