### ISSUE TITLE
Weird dev repo setting

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#6784]
### Summary 

When executing `git pull` from inside a `dev` repo, the following output appears.

```
error: error loading TeamSettings to determine if in GitHub app mode: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io)
```

Is that something that was added by accident to the "original" `dev` repo or ...?

**Comment by hferentschik** [comment]
Are you connected to the dev cluster when you run this. The dev repo is using `jx` as a git credential helper to get to the password to `git push|pull`.

What's the output of `git config --local -l` within the dev repo?
