### ISSUE TITLE
Does't Jx support Kubernetes v1.17.2?

### ISSUE THREAD

**Issue by fhchina** [jenkins-x/jx#6786]
### Summary 

unable to recognize "/tmp/helm-template-workdir-852893260/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1

### Steps to reproduce the behavior
jx boot

### Expected behavior

As far as I know, Kubernetes 1.16 has removed "extensions/v1beta1", so please use apiVersion: apps/v1

### Actual behavior

unable to recognize "/tmp/helm-template-workdir-852893260/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 2.0.1202
Kubernetes cluster v1.17.2
kubectl            v1.16.7
helm client        Client: v2.16.3+g1ee0254
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```
COPY OUTPUT HERE
```

### Jenkins type
jx boot

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

naked Kubernetes cluster, created by kubeadm

### Operating system / Environment
Ubunut 18.04

**Comment by ram4444** [comment]
As a work around:
open /etc/kubernetes/manifests/kube-apiserver.yaml 

add the following line to somewhere like it
- --runtime-config=apps/v1beta1=true,extensions/v1beta1/deployments=true

**Comment by ankitm123** [comment]
@fhchina @ram4444 can you try again with the latest version of jx? and use the latest versionstream in the jx-requirements.yml?

**Comment by ram4444** [comment]
@ankitm123 I have tried the latest, but the problem remains the same.
I think if they are not going to resolve the version dependency of kubernetes it will still goes on.

I am not willing to fallback my on-prem kubernetes since the dev team should keep up with GKE/EKS version upgrade, but you can try.

**Comment by ram4444** [comment]
@ankim123 My last try is v1.0.452. Seems they try to get it works on 1.16.8 in #6957

**Comment by ankitm123** [comment]
@ram4444 that is pretty old. You need to try atleast `v1.0.479` (This will have the newer chart versions). The latest version can be found here: https://github.com/jenkins-x/jenkins-x-versions/releases

**Comment by ram4444** [comment]
Just upgrade to 1.0.489 but the problem remains the same. If I dont added a line to kube-apiserver.yaml

error: unable to recognize "/tmp/helm-template-workdir-856122830/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'

**Comment by ankitm123** [comment]
Static Jenkins master is not supported in jx anymore, so if you disable that, you should be able to boot (It's the only chart which has not been upgraded). There is an issue to remove left over jenkins code from the codebase #7232

**Comment by ram4444** [comment]
After several work-around I can successfully jx boot, but the issue remains the same when the jx create quickstart ends. I am still not able to promote the spring gradle to jx-stagging. Is It related to static Jenkins Master issue and how to resolve it?

![image](https://user-images.githubusercontent.com/6932068/83968550-9e57ca80-a8fc-11ea-82ec-faa1c91c63fc.png)

**Comment by ankitm123** [comment]
I am not sure, I will take a look and come back to you. I feel it's not related to the static jenkins master issue, but I will have a better answer once I close that issue. 

Thanks for trying jx boot in v1.17.2 btw :)

**Comment by ankitm123** [comment]
Jx should work on 1.17.2

/close
