### ISSUE TITLE
Add cross-repo PR testing context to jx

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6805]
From #6736:

* Trying to deal with `jenkins-x-platform` is a pain, so I'm just going to target combining `jx`, `jenkins-x-boot-config`, and `jenkins-x-versions` for the moment. I believe the overwhelming majority of cases will be covered by those three, particularly by `jx`+`jenkins-x-boot-config`, so this will provide real value without requiring any changes to how things actually function normally.
* A new repo (gonna go with `jenkins-x/jx-cross-repo-test-configuration` if no one has a better name) will be created, to contain `pr-1234.yml` files, where `1234` is the number of a `jx` PR. These YAML files will contain one or both of `jenkins-x-boot-config: 567` and `jenkins-x-versions: 890` (or `pr-567` - the logic will be able to handle either and won't be case sensitive), pointing to PRs in the other repos that should be pulled in for cross-repo testing of `jx` PR `1234`.
* When you run `/test cross-repo` (a new, optional context), a new BDD test context will run. In its `ci.sh`, it will look for the `pr-1234.yml` in the config repo mentioned above, and if the file exists, it'll get pulled down and the values, if set, for `jenkins-x-boot-config` and `jenkins-x-versions` will be fetched. This will be done _before_ building the binary to be used in the BDD tests.
  * Comments will be left on the relevant `jenkins-x-boot-config` and `jenkins-x-versions` PRs linking back to the `jx` PR, stating that a cross-repo PR test is running. (Eventually, I'd like to have Lighthouse actually create/update statuses for the cross-repo PR on the other PRs, but that's not in scope for the near-term.)
  * The values for the other repos will be used, if set, to bake in the default version stream and default boot config repo and branch in the build of the binary. (note - I am not 100% sure on this part, since it would make upgrade testing difficult at best, so I may walk this back.)
  * After building the binary and test images, the boot config PR, assuming it's specified, will be cloned/checked out rather than the boot config release from the version stream.
  * If a version stream PR is specified, it will be used for getting the boot config release to use (if no boot config PR is specified), and the `jx-requirements.yml` we'll use to boot with will have its version stream ref set to use the version stream PR.
  * We will then boot as normal from there.
* A full battery of tests will be run in a standard GKE/boot/vault/gitops/Prow (until Lighthouse is the default in boot config) configuration. At a minimum, this set of tests will include the following targets from `bdd-jx`'s `Makefile`:
  * `test-create-spring` (for adding a repo, releasing, going to staging, opening a PR, verifying the preview, merging the PR, promoting to production)
  * `test-single-import` for `node-http` (verifying import with something other than a golang quickstart)
  * `test-quickstart-golang-http` (verifying the full quickstart suite with the fastest quickstart to test that we've got)
  * `test-import-golang-http-from-jenkins-x-yml` (verifying more advanced Tekton syntax behavior, such as multi-stage)
  * `test-app-lifecycle` (which in the gitops case will install the UI and make sure it is serving properly, and then will remove the UI)
* Upon completion, the `jx` PR will have its status updated as normal, and the `jenkins-x-boot-config` and `jenkins-x-versions` PRs, if specified, will have comments added to them linking to the context's result. (Again, down the road, I'd like to have standard GH statuses on the other PRs.)

Alongside actually implementing that, I'll also be creating a task for identifying things we _should_ be testing in BDD that aren't being tested currently. As further tests are added to `bdd-jx`, those tests will be invoked by the cross-repo test as well.

Additional areas we may want to be testing with existing tests but that may be a hassle to incorporate into this test context for various reasons:
* Upgrade testing. This will probably require initially booting with the standard values for default boot config/version stream repo/version, then rebuilding the binary with our custom values, so may take some work. If that work is sizable enough, adding upgrade testing will be done after the initial "release".
* TLS. The challenge here is entirely around domain assignment - we would need a separate pool of domains from those used in `jenkins-x-versions`'s `boot-vault-tls` context, and we'd need to ensure that multiple PRs could run the cross-repo context without domain collision, so this will also be a follow-up task.
* Lighthouse. Obviously, when we switch the default from Prow to Lighthouse in boot config, we will be testing against the latest Lighthouse release in the version stream we're testing against automatically, but I think there probably would be real value in being able to test against a Lighthouse PR. That will be more complicated than the boot config or version stream PRs since we'll need to pick up the charts/images from the Lighthouse PR, so this needs more thinking.

Acceptance Criteria:
Able to run a BDD test for a PR in JX + PR in `jenkins-x-boot-config`  + a PR in `jenkins-x-versions`. 
 Demonstrate via screenshots, demo, test output.  Documentation on how to configure it.

**Comment by deanesmith** [comment]
Removed from sprint in favor of Lighthouse concerns.
