### ISSUE TITLE
Tracking issue for functionality not covered by BDD tests that should be

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6806]
Stemming from #6736, this is an issue for tracking functionality that is not currently covered by BDD tests but should be, which will then have issues created for actually implementing the needed testing.

**Comment by abayer** [comment]
* `/retest` - see #6796. More chatops to test, basically.
* Lighthouse context on jx repo to catch things like #6817

**Comment by abayer** [comment]
Here's a big one - we're not testing tide handling merging PRs.

**Comment by garethjevans** [comment]
* UI Links from status updates on the PR
* Preview comments on a PR

**Comment by abayer** [comment]
It probably would make sense to have BDD coverage for some of the more complicated scenarios we have in jx-related repos (like https://github.com/jenkins-x/lighthouse/issues/542), particularly for Lighthouse stuff.

**Comment by abayer** [comment]
`/override` isn't tested, nor is batch build/reconciliation.

**Comment by abayer** [comment]
We don't have any tests of multiple pipeline contexts (and as a result, we don't have coverage for `/test (name of context)`).
