### ISSUE TITLE
Improve JX boot GKE documentation

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6807]
### Summary 
The documentation for running `jx boot` on a GKE cluster is lacking details and examples for advanced configurations - https://jenkins-x.io/docs/getting-started/setup/boot/clouds/google/.

The purpose of this issue to enhance the document by lifting CJXD content and applying upstream in sections with a TOC at the top, similar to - https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/

https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/gke-install-guide/boot
https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/gke-install-guide/dns-tls

Additional tasks:
Remove kops reference from boot document "Basic Configuration" sections in AWS document.

**Comment by jha-cloudbees** [comment]
Done
* Converted CJXD GKE installation content from Asciidoc to markdown
* Stripped content of `CJXD` references and/or replaced with `Jenkins X`where appropriate

To Do
* Consolidating/editing to one page to match EKS content in OSS docs.

**Comment by jha-cloudbees** [comment]
PR created: https://github.com/jenkins-x/jx-docs/pull/2535

**Comment by deanesmith** [comment]
Closed due to Terraform implementation.
