### ISSUE TITLE
Conditional pipelines with dependencies

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#6808]
### Summary 

This is a request for a new feature: have dependencies between pipelines.

### Use case

- 1 pipeline to deploy the preview environment
- 1 pipeline to run the integration tests (on the preview env)

Why 2 different pipelines?
- the preview-env can use a build-pack that's common for multiple apps
- the integration tests one can be a custom pipeline on each repository
- it's easy to replay only 1 pipeline, for example to redeploy the preview env, or just rerun the tests

### Issue

With the current jx features, we need to add a first step in the integration tests to wait for the preview env to be available, "wasting resources"

### Proposed feature

Have a way to say that the integration tests pipeline should only run if the preview-env one is successful. Meaning it won't be triggered by a push event, but by the result of another pipeline.

**Comment by hervelemeur** [comment]
How about adding a final step into the preview pipeline to start the integration pipeline?
In that case, the integration pipeline would be launched only if the previous steps in the preview pipeline are successful.

**Comment by vbehar** [comment]
yes, that would work too
