### ISSUE TITLE
git provider URL

### ISSUE THREAD

**Issue by TreverW** [jenkins-x/jx#681]
I attempted to specify a GitHub Enterprise URL when creating an AWS cluster and this is what happened near the end of the cluster creation.  I expected it to use my GHE URL, username, and token for the GitHub portion of the setup.  

`jx create cluster aws -n jenkinsx-dev --domain=jenkinsx-dev.mydomain.org --git-provider-url=http://github.enterprise.mydomain.com --git-username=my-user --git-api-token=githubenterpriseapitoken --nodes=3 --zones=us-east-1a,us-east-1b,us-east-1c`

`Creating default staging and production environments
Using git provider GitHub at https://github.com
error: Server https://github.com has no user auths defined!`

**Comment by jstrachan** [comment]
@TreverW sorry about that! The installer isn't yet awesome at dealing with different git providers. Ideally it'd let you just add new git providers on the fly really - am hoping we can polish this ASAP to ease things.

One option is to install Jenkins X without any environments; then add git servers/tokens then create the environments afterwards. 

Another thing to try is to just register your GitHub Enterprise server URL first before you try create a cluster - then it should at least appear in the list of possible git servers to pick from? 

e.g. try...

```
jx create git server github https://github.foo.com -n GHE
jx create cluster aws -n jenkinsx-dev --domain=jenkinsx-dev.mydomain.org --nodes=3 --zones=us-east-1a,us-east-1b,us-east-1c
```
then the CLI should hopefully prompt you for which git service to user and let you configure the token on the fly etc?

**Comment by jstrachan** [comment]
I think this is working now: https://jenkins-x.io/developing/git/

we're looking at simplifying the install experience with different git providers via Terraform: https://github.com/jenkins-x/jx/issues/845

**Comment by mnuttall** [comment]
I'm still seeing this issue today on jx 1.3.154. The workaround does not work. Even when I create a git server first, and invoke `jx install --git-provider-url=https://my.github.enterprise`, jx install fails with, 
```
...
Using git provider GitHub at https://github.com


About to create repository environment-hisseroil-staging on server https://github.com with user mnuttall


Creating repository mnuttall/environment-hisseroil-staging
Creating git repository mnuttall/environment-hisseroil-staging
error: failed to create staging environment: Failed to create repository /environment-hisseroil-staging due to: POST https://api.github.com/user/repos: 401 Bad credentials []
```
`jx install` starts by prompting for an api token on the correct git server, but then switches back to api.github.com and so fails the installation.
