### ISSUE TITLE
Tekton controller is not respecting namespace's scope

### ISSUE THREAD

**Issue by cdbkr** [jenkins-x/jx#6816]
### Summary 
At the moment Tekton Controller deployed in the Jenkins-x namespace is not scoped to the related namespace but it is watching over other Tekton resources in other namespaces too.

### Steps to reproduce the behavior
Install Jenkins-x in 2 different namespaces

### Expected behavior
Tekton controller is watching and reacting to Tekton CRDs in the same namespace only

### Actual behavior
Tekton controller is reacting to Tekton CRDs deployed in other namespaces too (duplicating build pods)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1202
Kubernetes cluster v1.14.10+IKS
kubectl            v1.15.2
helm client        Client: v2.14.1+g5270352
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G87
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

 v1.14.10+IKS - JX boot

### Operating system / Environment

Mac OS

**Comment by abayer** [comment]
So this is https://github.com/tektoncd/pipeline/issues/2111 - gonna see if I can fix it (and backport it to our Tekton 0.8.0 fork) later this week.

**Comment by fraenkel** [comment]
@abayer I have a potential fix which I haven't tested. You might want to give it a go and see if it does in fact fix this issue.
https://github.com/fraenkel/pipeline/commit/064045d996a9a79d40d8b2d426720ce7a547a5b0

**Comment by abayer** [comment]
That feels right to me - mind opening a PR against Tekton? =)

**Comment by abayer** [comment]
I'm gonna try to backport this to our 0.8.0-derived weirdo of a branch soon - relevant (merged upstream) PR is https://github.com/tektoncd/pipeline/pull/2144
