### ISSUE TITLE
jx boot fails when using helm3 due to jx trying to run helm init

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx#6818]
### Summary 
jx boot fails when using helm3 due to jx trying to run helm init. To fix this we just need to check the helm version and if it's < v3 not run helm init.
this is the main reason helm3 is not working (there are other small quirks and than can be worked around without touching the code).

workaround: edit jenkins-x.yml and add `--disable-verify-helm` in step verify-preinstall
### Steps to reproduce the behavior
```
export JX_HELM3=true
jx boot
# fill/fix jx-requirements.yml the rerun boot
cd ./jenkins-x-boot-config/
jx boot
```

### Expected behavior
It should try to run helm init as per: https://helm.sh/blog/helm-v3-beta/#notable-changes-since-helm-v2 :
> The helm init command has been removed. It performed two primary functions. First, it installed Tiller. This is no longer needed. Second, it setup directories and repositories where Helm configuration lived. This is now automated. If the directory is not present it will be created.
### Actual behavior
```
error: initializing helm with config: {jx true false true false  }: failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
```
### Jx version

The output of `jx version` is:

```
jx                 2.0.1202
Kubernetes cluster v1.15.2
kubectl            v1.17.0
git                2.21.1
Operating System   "Fedora release 30 (Thirty)"

```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hferentschik** [comment]
> there are other small quirks and than can be worked around without touching the code

What are these? Maybe we could address them as well?
