### ISSUE TITLE
Wrong token generation URL for Bitbucket Server

### ISSUE THREAD

**Issue by AntoineFr** [jenkins-x/jx#6819]
### Summary 

When I use the command `jx create quickstart` after the installation, it asks me my git username, then provides an URL to generate a git token.  
The URL that is presented to generate this token works well for GitHub but not for BitBucket Server.

### Steps to reproduce the behavior

Install Jenkins X with BitBucket Server :

```
cluster:
  gitKind: bitbucketserver
  gitName: bitbucket
  gitServer: https://git.xxx.fr
```

Then try to create a repository with `jx create quickstart`.

### Expected behavior

The correct URL to generate a token is displayed. I think it should be `https://git.xxx.fr/plugins/servlet/access-tokens/add`

### Actual behavior

The wrong URL is displayed (it uses the same format as GitHub).

```
? select the quickstart you wish to create php-helloworld
Using Git provider git.xxx.fr at https://git.xxx.fr
? git.xxx.fr username: xxx
To be able to create a repository on git.xxx.fr we need an API Token
Please click this URL and generate a token 
https://git.xxx.fr/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter it below:
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1202
Kubernetes cluster v1.17.2
kubectl            v1.16.0
helm client        Client: v2.16.3+g1ee0254
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

On premise

### Operating system / Environment

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by httpete** [comment]
I am hitting the same thing. If someone could point me to where this is in the code I could try to fix it.

**Comment by abayer** [comment]
So what's happening here is that it's not realizing the appropriate git kind and is falling back on GitHub. We've got the right URL configured, it just doesn't know to use it.
