### ISSUE TITLE
jx start pipeline seems to ignore the context option

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#6820]
### Summary 

The `jx start pipeline` command seems to ignore the context option. 

### Steps to reproduce the behavior

Run the command:
```
jx start pipeline --context='somecontext' ccojocar-org/nodejs-prodsec/master
```
It will start the pipeline without any context, effectively the context is set to "", which is the default context.

### Expected behavior

The command should start the `jenkins-x-somecontext.yml` pipeline instead. 

### Actual behavior

The command starts the default `jenkins-x.yml` pipeline. 

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by grahammather** [comment]
This is pretty important to us. Without a UI, the easiest way to restart a build is to use "jx start pipeline" and it doesn't kick off the correct build. What used to be simple in Jenkins Blue Ocean is now really hard. I'm trying to explain how to restart a build to our devs and I'm going to have to make them jump through hoops.

**Comment by hervelemeur** [comment]
> This is pretty important to us. Without a UI, the easiest way to restart a build is to use "jx start pipeline" and it doesn't kick off the correct build. What used to be simple in Jenkins Blue Ocean is now really hard. I'm trying to explain how to restart a build to our devs and I'm going to have to make them jump through hoops.

For pul requests your devs can type `/retest`, and for the releases, they can push a dummy commit to the master branch. Not like an UI but still two easy workarounds.
