### ISSUE TITLE
jx fails to import a project because of a 63 character limitation of metadata.labels.

### ISSUE THREAD

**Issue by brec** [jenkins-x/jx#6827]
### Summary 
While importing a *Gitlab* project, `jx import` will fail to import the project with this error:

```
error: failed to start pipeline build: unable to apply Tekton CRDs: failed to apply Tekton CRDs: PipelineActivity.jenkins.io "jenkins-x-test-import-jx-import-4-master-1" is invalid: metadata.labels: Invalid value: "git-gitlab-<companyname>-com-jenkins-x-test-import-jx-import-4-git": must be no more than 63 characters
```

This looks like its related to this issue : https://github.com/jenkins-x/jx/issues/4370

Is there a way to truncate this label ? This prevents us from importing our projects.

### Steps to reproduce the behavior

Run `jx import` on a project that hits the 63 character limit. The project does not have to be especially long (yes, this is relative, but its going to depend on how  long the base + group path is) , especially in cases where there are nested groups.

### Expected behavior

`jx import` doesn't fail to import projects because of their path length. 

### Actual behavior

`jx import` fails because of the path length

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1200
Kubernetes cluster v1.14.9-eks-c0eccc
kubectl            v1.15.10
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203


verifying packages
```

### Jenkins type

- [X ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hervelemeur** [comment]
@brec this issue seems to be resolved by https://github.com/jenkins-x/jx/pull/7075
