### ISSUE TITLE
jx upgrade platform should reuse the `~/.jx/cloud-environments` configuration

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#683]
to preserve any local changes or add new local changes if folks edit `~/.jx/cloud-environments`.

We'd also need to preserve - via a `ConfigMap` maybe - which provider kind is being installed to know which folder in  `~/.jx/cloud-environments` to look for any `myvalues.yaml` customisation

**Comment by ccojocar** [comment]
`myvalues.yaml` file is now loaded from cloud environment folder.
