### ISSUE TITLE
jx create quickstart fail to push image when step-build-container-build

### ISSUE THREAD

**Issue by ram4444** [jenkins-x/jx#6831]
### Summary 
Fail to push docker registry to docker hub, after setting up according to
https://jenkins-x.io/docs/reference/components/docker-registry/#using-docker-hub
adding base64 string to kubectl edit secret jenkins-docker-cfg

docker hub repo with same name has already created
docker hub token has been generated

### Steps to reproduce the behavior
jx create quickstart
selecting spring-boot-gradle http

### Expected behavior
push the docker image to dockerhub

### Actual behavior
Showing logs for build ram4444/test12/master #1 stage from-build-pack and container step-build-container-build
INFO[0000] Downloading base image openjdk:8-jdk-slim
INFO[0001] Error while retrieving image from cache: <empty transport.Error response>
INFO[0001] Downloading base image openjdk:8-jdk-slim
error building image: <empty transport.Error response>

Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.

### Jx version
NAME               VERSION
jx                 2.0.1188
Kubernetes cluster v1.16.7
kubectl            v1.16.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.1
Operating System   Unknown Linux distribution Linux version 5.5.5-arch1-1 (linux@archlinux) (gcc version 9.2.1 20200130 (Arch Linux 9.2.1+20200130-2)) #1 SMP PREEMPT Thu, 20 Feb 2020 18:23:09 +0000

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

On-Prem Single Node with taint

### Operating system / Environment

Arch Linux

If I put nothing to config.json, the base image can be pull but then fail to push the image by showing up UNAUTHORIZED

**Comment by michaeljohnbennett** [comment]
I'm getting the same issues

**Comment by ram4444** [comment]
What have mentioned in the documentation is wrong.
https://jenkins-x.io/docs/reference/components/docker-registry/#using-docker-hub
Instead of:
{
    "auths": {
        "https://index.docker.io/v1/": {
            "auth": "MyDockerHubToken",
            "email": "myemail@acme.com"
        }
    }
}

Please use docker login to generate a config.json in your /home/directory/.docker
You will know the difference
encode it in BASE64 and put to jenkins-docker-cfg
kubectl edit secret jenkins-docker-cfg

This have cost me for a whole week to work.......

**Comment by deanesmith** [comment]
@ram4444 Do you believe the documentation should be supplemented to address this matter?  If so, would you be willing to make a contribution?
