### ISSUE TITLE
jx tries to retrieve the logs from raw.githubusercontent no matter the provider

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx#6834]
### Summary 
jx tries to retrieve the logs from raw.githubusercontent no matter the git provider

### Steps to reproduce the behaviour
clone a project from gitlab or bitbucket
```
jx import
jx get build log
```

### Expected behavior
logs should be retieved from https://gitlab.com/<org>/<project>/-/raw/gh-pages/jenkins-x/logs/

### Actual behavior
jx fails to retrieved logs since it 's checking in the wrong location

### Jx version

The output of `jx version` is:

```
jx                 2.0.1202
Kubernetes cluster v1.15.2
kubectl            v1.17.0
git                2.21.1
Operating System   "Fedora release 30 (Thirty)"
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hferentschik** [comment]
@yelhouti, thanks for the bug report. Are the logs stored properly? Is it just the retrieval which fails? Is anything published to Gitlab gh-pages branch? Is there an error printed as well?

Also, how to you install Jenkins X? `jx install` or `jx boot`?

**Comment by yelhouti** [comment]
@hferentschik yes the branch is created and contains all the logs, I installed using jx boot.

**Comment by abayer** [comment]
Yup, it’s hardcoded - https://github.com/jenkins-x/jx/blob/c2b03cc144068f448953a4a6ce7fe8b934223fd7/pkg/collector/git_collector.go#L161. We should definitely fix this.

**Comment by yelhouti** [comment]
oups!

**Comment by yelhouti** [comment]
Unless it's an urgent matter for someone, I will try to fix it in few days

**Comment by hferentschik** [comment]
Ok, thanks. So then there is somehow a bug in the retrieval logic. Most likely hard coding some GitHub base URL.

**Comment by abayer** [comment]
@hferentschik Yup, see the contents of the function I linked above. =)

**Comment by deas** [comment]
Just getting started on Gitlab and this issue hits me. Is it just that we don't get to see the build logs and other functionality should be there?

Currently seeing

```
➜  ~ jx get activity -f jx-golang-sample -w
STEP                                                       STARTED AGO DURATION STATUS
SteffanAnd/jx-golang-sample/master #1                        44h13m17s    3m30s Failed 
  meta pipeline                                              44h13m17s    3m30s Failed 
    Credential Initializer Hh6l8                             44h13m17s       0s Succeeded 
    Working Dir Initializer Gp6lp                            44h13m17s       4s Succeeded 
    Place Tools                                              44h13m13s       3s Succeeded 
    Git Source Meta Steffanand Jx Golang Sampl 4rsvj Ctlrx   44h13m10s      10s Succeeded https://***/SteffanAnd/jx-golang-sample.git
    Git Merge                                                 44h13m0s      31s Succeeded 
    Merge Pull Refs                                          44h12m29s       1s Succeeded 
    Create Effective Pipeline                                44h12m28s    2m40s Failed 
    Create Tekton Crds                                        44h9m48s       1s NotExecuted
```
Was wondering if this issue here is related and where to find more details about the failed execution.
