### ISSUE TITLE
LoadBalancer on bare metal cluster

### ISSUE THREAD

**Issue by CobraFlow** [jenkins-x/jx#685]
I have a bare metal cluster (1.10) working fine.

I run `jx install --provider kubernetes`

I am trying to create the ingress using the defaults.

It waits with
`Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace`

I update the externalIPs with kubectl adding my ip address expecting it to continue...

What else do I need to do?

**Comment by bbcrgoliveira** [comment]
What worked for me was to ensure the `jx context` is pointing to my bare metal cluster and then run
`jx install--exposer='Ingress' --verbose=true --domain='your domain' --provider=minikube`
Hopefully there's a better way to do this....

**Comment by CobraFlow** [comment]
...thanks for that. I am not using minikube.
I think that --exposer defaults to 'Ingress'.
I need to 'kick' the system into thinking that the external loadbalancer has allocated the ExternalIP.
I thought that just patching the nginx-controller service's ExternalIPs entry would have done it. There must be something else I need to do on top of this...

**Comment by rawlingsj** [comment]
yeah sounds like we need a step in the create cluster wizard that prompts for the external ip and skips waiting if not on a public cloud which automatically creates the external LB.

Something here https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/init.go#L473-L474

Did you want to try a patch?  If not I can probably take a look in an couple of hours.

**Comment by rawlingsj** [comment]
@bbcrgoliveira thanks, yeah the `--provider=minikube` skips waiting for the external LB [here](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/init.go#L473) which is probably why that works

**Comment by CobraFlow** [comment]
What does https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/init.go#L479 actually do as I AM setting an external ip with 
`kubectl patch service jxing-nginx-ingress-controller -n kube-system -p '{"spec":{"externalIPs":["'$ip'"]}}'`

...as I said, there must be something else...

**Comment by CobraFlow** [comment]
...Ok, I'm learning the Go stuff on the fly...

I've found the code and now understand the problem.

Cheers

**Comment by rawlingsj** [comment]
yay!  great stuff! go is pretty awesome and sometimes the best way to learn things is to dive right in ;)

ask away here if you have questions or find us in the #jenkins-x-dev or #jenkins-x-user rooms in the kubernetes slack http://jenkins-x.io/community/

**Comment by CobraFlow** [comment]
...just a naive question...

Would just checking for an existing ExternalIP not work?

**Comment by CobraFlow** [comment]
@jpds I am aiming at using https://github.com/kubernetes/contrib/tree/master/keepalived-vip to provide the 'LoadBalancer'.
If I had metallb set up, would it update the service to provide the status.loadBalancer.ingress{} required?

**Comment by jpds** [comment]
@CobraFlow Yes.
