### ISSUE TITLE
BDD tests that merge test PRs manually should let Tide do the merging instead

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6850]
Stemming from #6806 and Lighthouse work in general - we should be relying on Tide to merge PRs created by our tests, not manually merging them. We only open and merge PRs in the boot upgrade, UI, and apps-when-on-boot tests, so we don't have to worry about Tide not being around to do the merging when those tests are run.

**Comment by hferentschik** [comment]
+1
