### ISSUE TITLE
When no webhooks can we speed up promotion?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#687]
Eg wait 10 seconds and if no build is running, trigger it inside `jx promote`? 

As right now on a cluster with no webhooks - eg minikube / minishift & github it can take 22 minutes to promote!

**Comment by ethiebaut** [comment]
This issue is closed and the code is available, but it has never been merged in...
Is there a plan to create a PR/merge this in? Builds are still extremely slow...
