### ISSUE TITLE
`jx step changelog` throws a warning of "User.jenkins.io "x-0" is invalid"

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#6879]
### Summary 
Running `jx step changelog ` causes this warning:
```
Associating user x-0 in users.jenkins.io with email REDACTED to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit f69d4ded2d13051ead805450e22f9bf2e6592e7c with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
```

**Comment by hervelemeur** [comment]
Related/duplicate: https://github.com/jenkins-x/jx/issues/4603
This already old issue seems to delay the changelog step quite a bit.

**Comment by jcarsique** [comment]
Note that this also happens on regular users:
```
$ jx step changelog --update-release false --verbose true -b false -v v0.0.16 
Associating user jcarsique in users.jenkins.io with email REDACTED to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user jcarsique in users.jenkins.io
WARNING: Failed to enrich commit ... with issues: User.jenkins.io "jcarsique" is invalid: metadata.labels: Invalid value: "-0" ...
```

In addition to the warning, all or most of the changelog is missing and not published.
A very few commits are still properly reported to the GitHub release changelog, regardless the commit author.

 I tried some workarounds without success:
- set correct data in the user `x-0`
- delete the user `x-0`
- set the missing label `jenkins.io/git-github-userid` on users.jenkins.io/jcarsique but the preset id is ignored and removed by `jx step changelog`
- delete and recreate the users with `jx create user`
- ...

**Comment by jstrachan** [comment]
this PR https://github.com/jenkins-x/jx/pull/7447 should improve things greatly; it should help properly resolve cases where the is a git user name but no login from the git provider REST call. Plus errors resolving a user on an issue/commit to a CRD name fails we just log warnings but not fail the changelog.
