### ISSUE TITLE
Remove Minikube from Jenkins X

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6889]
### Summary 
Based on the CLI command deprecation schedule published in in December of 2019 (https://jenkins-x.io/commands/deprecation/), Minikube support remains in Jenkins X despite passing the deprecation date.  The purpose of this issue is to perform the following tasks

1) If `jx boot` is able to detect that a cluster is running on Minikube, alert the user that this platform is not supported. (Do not proceed with boot?)

2) Remove Minikube as an option from `jx create cluster`.  Refer to https://github.com/jenkins-x/jx/issues/4088

3) Delete Minikube code from the jx cli 

4) Update documentation appropriately

5) Close open issues that are specific to Minikube
https://github.com/jenkins-x/jx/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fminikube

**Comment by mrageh** [comment]
Fixed in https://github.com/jenkins-x/jx/pull/6899
