### ISSUE TITLE
Skaffold with 'No Manifest' fails in certain cases

### ISSUE THREAD

**Issue by gabeduke** [jenkins-x/jx#690]
Skaffold will fail to deploy in the following two cases:

1. If there are more than 1 dockerfile defined according to [this](https://github.com/GoogleContainerTools/skaffold/issues/413) issue. This will hopefully be solved soon. However it may be useful to provide a version to skaffold in case breaking changes are introduced again. This is currently forcing me to modify the Jenkinsfile to run skaffold twice with custom file paths, which is not ideal as I would prefer to stick with the jx workflow.
2. In cases where the docker image has a port defined, Skaffold will fail to deploy
    - Although skaffold indicates that no manifest is needed, it will actually generate a basic deployment an apply via kubectl according to the docs [here](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/no-manifest)
    - This can cause issues because the port defined in skaffold's generated deployment includes the protocol as a string which does not jive with certain versions of the k8s api (as far as I can tell). I'm on v1.9.7 & running into this issue. Error below...

(at deploy step in skaffold)
```
Starting deploy...
time="2018-04-21T18:51:59Z" level=info msg="No manifests specified. Generating a deployment."
time="2018-04-21T18:51:59Z" level=debug msg="Found port 80/tcp in base image"
time="2018-04-21T18:51:59Z" level=debug msg="Applying manifest: apiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  labels:\n    run: skaffold\n  name: skaffold\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      run: skaffold\n  strategy: {}\n  template:\n    metadata:\n      labels:\n        run: skaffold\n    spec:\n      containers:\n      - image: 100.67.120.8:5000/riskbasedsecurity/vulnagg/vulnagg_nginx:0.0.0-SNAPSHOT-PR-2-18\n        name: app\n        ports:\n        - containerPort: 80/tcp\n"
time="2018-04-21T18:51:59Z" level=debug msg="Running command: [kubectl --context  apply -f -]"
time="2018-04-21T18:52:00Z" level=debug msg="Command output: stdout , stderr: error: error validating \"STDIN\": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[0].containerPort): invalid type for io.k8s.api.core.v1.ContainerPort.containerPort: got \"string\", expected \"integer\"; if you choose to ignore these errors, turn validation off with --validate=false\n, err: exit status 1"
Error: running skaffold steps: deploy: deploy step: deploying manifest: running kubectl apply: stdout:  stderr: error: error validating "STDIN": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[0].containerPort): invalid type for io.k8s.api.core.v1.ContainerPort.containerPort: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false
 err: exit status 1: exit status 1
```

**Comment by jstrachan** [comment]
I did raise this https://github.com/GoogleContainerTools/skaffold/issues/330 but thought the empty manifest list was a good enough workaround - it appears not ;)

Btw did listing an explicit Dockerfilepath in the skaffold.yml help on the other issue?

**Comment by gabeduke** [comment]
@jstrachan so defining an explicit dockerfilePath has not been a problem, the issue is that skaffold will not allow the user to define two dockerfilePaths with the no manifest option.

cmd: `skaffold run`

Dockerfile
```
FROM: busybox
```

skaffold.yaml
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: busybox
    workspace: .
  - imageName: busybox2
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
```

**Comment by gabeduke** [comment]
I also have realized that it is the nginx image that is causing issues. This can be recreated by using the following Dockerfile & skaffold.yaml in an empty directory:

cmd: `skaffold run`

Dockerfile
```
FROM: nginx
```

skaffold.yaml
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: nginx
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
```

**Comment by gabeduke** [comment]
It looks there is a [solution](https://github.com/jenkins-x/jx/issues/907) in the works

#907

**Comment by jstrachan** [comment]
unfortunately there's a regression in 0.8.0 so need to wait for a workaround for https://github.com/GoogleContainerTools/skaffold/issues/741

**Comment by jstrachan** [comment]
@gabeduke wanna try `jx upgrade cli` and `jx upgrade platform` then retry? You will be on the latest 0.9.0 of upstream skaffold

**Comment by gabeduke** [comment]
This works great now :)
