### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1" .....

### ISSUE THREAD

**Issue by survivant** [jenkins-x/jx#6900]
### Summary 
 jx install --provider=kubernetes --advanced-mode=true  produce this error at the end
```
unable to recognize "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

```

```
Error from server (Invalid): error when creating "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": Deployment.apps "jenkins-x-chartmuseum" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"chartmuseum", "release":"jenkins-x"}: `selector` does not match template `labels`]
Error from server (Invalid): error when creating "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": Deployment.apps "jenkins-x-docker-registry" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"docker-registry", "release":"jenkins-x"}: `selector` does not match template `labels`]
Error from server (Invalid): error when creating "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": Deployment.apps "jenkins-x-heapster" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"jenkins-x-heapster"}: `selector` does not match template `labels`]
```

### Steps to reproduce the behavior

I edited those files
```
/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml
/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml
/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml
/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml
```

and replace 
```
From apiVersion: extensions/v1beta1
To: apiVersion: apps/v1
```

and launch the command again

`kubectl apply --recursive -f /tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx -l jenkins.io/chart-release=jenkins-x --namespace jx --validate=false
`

### Expected behavior

should be able to work

### Actual behavior

Error from server (Invalid): error when creating "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": Deployment.apps "jenkins-x-chartmuseum" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"chartmuseum", "release":"jenkins-x"}: `selector` does not match template `labels`]
Error from server (Invalid): error when creating "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": Deployment.apps "jenkins-x-docker-registry" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"docker-registry", "release":"jenkins-x"}: `selector` does not match template `labels`]
Error from server (Invalid): error when creating "/tmp/helm-template-workdir-427692994/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": Deployment.apps "jenkins-x-heapster" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"jenkins-x-heapster"}: `selector` does not match template `labels`]

### Jx version

The output of `jx version` is:

```
root@test-pcl113:~/test/jenkinsxtest# jx version
NAME               VERSION
jx                 2.0.1234
jenkins x platform 2.0.2054
Kubernetes cluster v1.17.3
kubectl            v1.17.3
helm client        2.16.3
git                2.17.1
Operating System   Ubuntu 18.04.1 LTS

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

### Kubernetes cluster
 jx install --provider=kubernetes --advanced-mode=true

### Operating system / Environment

Operating System   Ubuntu 18.04.1 LTS

**Comment by ram4444** [comment]
Please try my comment in this issue as workaround, but another problems will stills go on.. 
https://github.com/jenkins-x/jx/issues/6786#issue-569703354
