### ISSUE TITLE
JX UI - logs become unavailable upon pipeline completion

### ISSUE THREAD

**Issue by mathieusama** [jenkins-x/jx#6907]
### Summary 

In JX UI, as soon as a pipeline completes, its log becomes unavailable and an error message is displayed instead (see below).

NOTE: This appears to be a JX UI issue, as logs are still available via `jx get build logs`.

### Steps to reproduce the behavior

- Start a pipeline
- Launch JX UI
- Access pipeline's log: OK
- Navigate away
- Wait for pipeline to complete
- Access pipeline's log: Error (see below)

### Expected behavior

Logs remain accessible via JX UI for as long as they remain accessible via `jx get build logs`.

### Actual behavior

Log panel displays this error message:

```
(HTTP 500)
An error occurred attempting to load the provided log.
Please check the URL and ensure it is reachable.
/api/v1/teams/jx/repositories/MyOrg/environment-mycluster-stg/branches/master/builds/21/log
```

### Jx version

```
NAME               VERSION
jx                 2.0.1192+cjxd.7
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Jenkins type

Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

AWS/EKS

eksctl create cluster \
  --name $CLUSTER \
  --version 1.14 \
  --region $ZONE \
  --nodegroup-name standard-workers \
  --node-type t3.medium \
  --nodes 3 \
  --nodes-min 3 \
  --nodes-max 3 \
  --managed

### Operating system / Environment

ubuntu:bionic

**Comment by dgozalo** [comment]
Hello, 

The UI's `Service Account` should be configured through IRSA (IAM Roles for Service Accounts) as shown here:

https://github.com/cloudbees/cloudbees-jenkins-x-boot-config/blob/master/kubeProviders/eks/templates/irsa.tmpl.yaml#L47-L52

Can you check that the `jxui` `ServiceAccount` has an annotation like `eks.amazonaws.com/role-arn` and the role it points to exists and has the `S3FullAccess` Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess?

**Comment by mathieusama** [comment]
I don't seem to have a resource of type `ClusterConfig` in my cluster:

```
$ kubectl get clusterconfig
error: the server doesn't have a resource type "clusterconfig"
```

However, the `jxui` `ServiceAccount` does exist, has the proper annotation pointing to a role that does exist in IAM with the proper policy.

**Comment by vfarcic** [comment]
Keeping this thread alive...

**Comment by RickyRajinder** [comment]
I am experiencing this issue as well and I am using Github for storage.
