### ISSUE TITLE
refactor : ShouldInstallBinary function checking binary on $PATH, not behaving as expected.

### ISSUE THREAD

**Issue by nehagup** [jenkins-x/jx#6912]
### Summary 
ShouldInstallBinary function is currently checking presence of binary on the $PATH variable and returning false if not present there (while it's present on JX/bin). 

### Expected behavior

It should be checking at JX/bin for the binary, if not present should return false.

**Comment by 524119574** [comment]
Is there anyone working on this? If not I can take on this issue?
