### ISSUE TITLE
JX boot failure with complex password

### ISSUE THREAD

**Issue by tomhobson** [jenkins-x/jx#6916]
### Summary 

Cannot accept a jenkins admin password that contains symbols

### Steps to reproduce the behavior
jx boot.
For jenkins-x admin password use a password containing a colon(:) or a dash(-).

### Expected behavior

the password is handled fine

### Actual behavior

jx boot crashes out with env/parameters.yaml not being parsed correctly

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1240
Kubernetes cluster v1.14.10-gke.17
kubectl            v1.16.7
helm client        2.16.3
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.15.3 build 19D76


verifying packages

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [] Classic Jenkins

### Kubernetes cluster

GKE with terraform

### Operating system / Environment

macos
linux
WSL (Windows Sub-system for Linux)

**Comment by cagiti** [comment]
@tomhobson are you able to confirm whether you've tried on both jenkins types (_I can see you've selected both, just wanted to double check)? Thanks

**Comment by tomhobson** [comment]
@cagiti No, I didn't try with traditional jenkins. I just assumed. I'll remove the tag if required.

**Comment by tomhobson** [comment]
Removed the tag.
