### ISSUE TITLE
--default-environments false gets ignored on AWS

### ISSUE THREAD

**Issue by sauravdevops** [jenkins-x/jx#692]
**What is happening**

When passing the optional parameters to disable the default environments on AWS, its ignoring the `false` boolean value.

```
jx create cluster aws \
--cluster-name jxtest \
--domain tools.something.co.nz \
--default-environments false \
--git-username sauravdevops \
--nodes 3
```

**Workaround**
As suggested by @rawlingsj in the slack channel #jenkins-x-user used an `=` and its working!!
Created an Issue here if anyone else is facing similar issue or if it can be looked into or replicated for other platforms.
```
--default-environments=false 
```

**Comment by jstrachan** [comment]
I guess this is a quirk of the CLI parser; it treats `--default-environments` as being a true flag - so it interprets `--deafult-environments false` as being `--deafult-environments=true false` - i.e. the `false` is treated as a CLI argument.

So maybe we should avoid having true default value options to avoid this kind of confusion? e.g. add a `--no-default-environments` instead?
