### ISSUE TITLE
PipelineActivities do not get updated correctly

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#6920]
### Summary 

The `status` field of the pipeline activity CRD never appears to be updated. e.g.

```
kubectl get pa <name> -oyaml
```

The status field is shown as `status: {}`, this should be updated according to kubernetes best practises.

Am also seeing instance where we have PAs in Running state for over 100 days, this is stopping the GC process from clearing these down as we only GC those in a completed state (success/failed)

**Comment by abayer** [comment]
Yeah, we currently do nothing with status and just set things in the spec, which is an anti-practice. We need to revisit that for sure, and how we update PAs in general.

**Comment by garethjevans** [comment]
I was wondering if we should clear out PAs that are running over X days, am not sure what that value would be, or at least mark them as failed.

**Comment by abayer** [comment]
Yeah, something like that would make sense.
