### ISSUE TITLE
allow Argo to be used for promotion workflows

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#694]
currently we keep around a Jenkins pipeline and a build pod while waiting for approval before promoting applications.

It would be much more cloud native and efficient to trigger an Argo workflow for promotion: https://applatix.com/open-source/argo/ we can then terminate the pipeline build pod and use Argo's efficient long running workflows to manage the promotion workflow

**Comment by jstrachan** [comment]
we've found our own workflow engine worked simpler as we really don't need to orchestrate lots of separate pods; its more a case of detecting when promotion PRs / pipelines complete and to see if we need to move promotion forward

**Comment by jglick** [comment]
This is still listed on the [roadmap](https://jenkins-x.io/contribute/roadmap/).
