### ISSUE TITLE
About preview environment and multirepo opinion

### ISSUE THREAD

**Issue by valdestron** [jenkins-x/jx#6948]
The thing is that JenkinsX clearly states an opinion of Multirepo approach because Monorepo sounds and looks monolithic. With that in mind I try to design an example of lets say 10-15 splitted microservices from monorepo to multirepo. And I am struggling to imagine sophisticated use cases of Preview environment as part of CICD.

Lets say I have to release 2 or more services in one batch, you'll get two or more preview environments. 
Helm provides service linking or dependencies, which is fine for third party services, what about other preview namespace services. Theoretically it looks like you can link service to some dynamic environment that is currently on PR. But then you will have to fix code before merge ? I had similar case in my previous project and it was nightmare to maintain.

Unless I am building monolith 1 backend 1 fronted (still batch deployment is not possible), I am failing to understand how preview environments can be maintainable.

Alternative - have a feature toggling or backwards and forwards compatible API - too much work!

Another alternative, monorepo, you can deploy batches, you can build dynamic environments, and truly experience Continuous Deployment - have to implement custom pipeline, charts, jenkins x is not very friendly for this because it does not have an opinion for this!

And yet another alternative, Jenkins X could provide some convention how to link pull requests and deploy them in one preview environment.

Can someone share how to handle spanning change deployment using preview environment, multiple service repositories and experience continuous deployment?

**Comment by jstrachan** [comment]
see https://jenkins-x.io/docs/using-jx/faq/#how-do-i-add-other-services-into-a-preview for how to add dependencies to a Preview

one option is to use `latest` of your dependencies to add the other dependent services to each preview chart. If thats not good enough you could just use Staging as a preview (before production) though it does mean you need to assume the change is good and merge to master

**Comment by valdestron** [comment]
I am sorry for not getting it, maybe I am not very sharp in helm charts and I might be wrong. But If there is only one service to release I can of course use latest tags on dependency services in my chart and everything is perfect. The problem is with interdependent previews, how to "merge" how to preview multiple repo changes in one preview environment? If I am forced to have approvement step in some preprod(staging) environment, I can not have continuous deployment, which is what I am seeking with JX!.
