### ISSUE TITLE
jx create cluster minishift on infinite loop on windows

### ISSUE THREAD

**Issue by gomesp** [jenkins-x/jx#695]
Thanks for the great tool team.

I was excited to test jx with minishift (#435) and downloaded it on my Windows 10 box.

When I type ``` jx create cluster minishift ``` (using Git Bash for Windows) what happens is that I am prompted to install the required dependencies:

? Missing required dependencies, deselect to avoid auto installing:  [Use arrows to move, type to filter]
❯ ◉  minishift
  ◉  oc
  ◉  helm

What happens next is that my system prints this question on an infinite loop, instead of waiting for the user input.

**Comment by jstrachan** [comment]
@gomesp ah sorry to hear that! I guess there's something wrong with the [Survey library](https://github.com/AlecAivazis/survey/) on windows. Pressing enter/return doesn't help I take it?  I thought this was fixed https://github.com/AlecAivazis/survey/issues/52

Until we figure out this gremlin a workaround is to install `minishift` and `oc` by hand first maybe. e.g. 
* [install minishift](https://docs.openshift.org/latest/minishift/getting-started/installing.html)
* [install oc](https://docs.openshift.com/enterprise/3.1/cli_reference/get_started_cli.html#installing-the-cli)

**Comment by jstrachan** [comment]
though TBH it sounds like terminal input won't work in general on your Windows machine so lots of other commands will be broken too.

BTW is there anything special about the shell/terminal you're using? Vanilla `cmd.exe` right?

**Comment by gomesp** [comment]
@jstrachan The vanilla cmd.exe works fine (except for downloading the client tools, as you mentioned in your first comment - and I'm installing them manually already). 

I was just trying it with [Git Bash](https://git-scm.com/download/win) as it's my git CLI as well and noticed that behaviour.

**Comment by ccojocar** [comment]
The issue seems to be specific to Git Bash on Windows. It seems to work on cmd.
