### ISSUE TITLE
GA Jenkins x for AKS 

### ISSUE THREAD

**Issue by georgejoel** [jenkins-x/jx#6962]
Hey Jenkinsx Team , 

Wanted to see if there is a update on when support for AKS will be generally available . Really appreciate the help . 

Thanks,
Joel George

**Comment by ethangj** [comment]
Hey, there - we're working on this now! Would you be in the community Slack to chat more about it by chance?

**Comment by deanesmith** [comment]
The work-in-progress is reasonably well tracked here - https://github.com/orgs/jenkins-x/projects/9
The backlog of known issues/tasks is here - https://github.com/jenkins-x/jx/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Faks

**Comment by deanesmith** [comment]
Closing this issue since it is not representative of a specific AKS concern.
