### ISSUE TITLE
invalid input resources: Task''s declared required resources are missing from the TaskRun: [workspace]

### ISSUE THREAD

**Issue by rvdven123** [jenkins-x/jx#6979]
### Summary 

The meta pipeline TaskRun does not execute because it does not provide the workspace input parameter definited by the Task.

### Steps to reproduce the behavior

Run > jx create quickstart 
Select > spring-boot-http-gradle

### Expected behavior

jx get activity -f jx-spring-gradle -w will show me the pipeline steps after a while.

I also expect the taskrun manifest to provide a git resourceSpec value 
[task.yaml.txt](https://github.com/jenkins-x/jx/files/4399113/task.yaml.txt)
[taskRun.yaml.txt](https://github.com/jenkins-x/jx/files/4399114/taskRun.yaml.txt)

for the task workspace input parameter.

### Actual behavior

The pipeline runner fails with the indicated message.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1258
Kubernetes cluster v1.15.7
kubectl            v1.16.8
helm client        2.16.5
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

AKS, I created it with Terraform

### Operating system / Environment

I'm running the cli in a Ubuntu 18.04 docker image.

**Comment by feczo** [comment]
Having the same issue here. It looks to be independent of the environment as Im running GKE not AKS and also no matter which quickstart you select you end up with the same issue. One example


❯ jx version
NAME               VERSION
jx                 2.1.38
Kubernetes cluster v1.15.11-gke.13
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS


~
❯ jx create quickstart
? select the quickstart you wish to create jenkins-quickstart
Using Git provider github.com at https://github.com
? Do you wish to use feczo as the Git user name? Yes
? Who should be the owner of the repository? feczo
? Enter the new repository name:  jenkins-quickstart
Creating repository feczo/jenkins-quickstart
Generated quickstart at /home/sub/jenkins-quickstart
Created project at /home/sub/jenkins-quickstart
The directory /home/sub/jenkins-quickstart is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
selected pack: /home/sub/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/jenkins
replacing placeholders in directory /home/sub/jenkins-quickstart
app name: jenkins-quickstart, git server: github.com, org: feczo, Docker registry org: possum
skipping directory "/home/sub/jenkins-quickstart/.git"
Draft pack jenkins added
Pushed Git repository to https://github.com/feczo/jenkins-quickstart
Creating GitHub webhook for feczo/jenkins-quickstart for url https://hook.jx.sierraforce.com/hook
Updated Pull Request: https://github.com/feczo/possum-dev/pull/2
Added label updatebot to Pull Request https://github.com/feczo/possum-dev/pull/2
created pull request https://github.com/feczo/possum-dev/pull/2 on the development git repository https://github.com/feczo/possum-dev.git
regenerated Prow configuration
PipelineActivity for feczo-jenkins-quickstart-master-1
upserted PipelineResource meta-feczo-jenkins-quickstart-m-6jqz8 for the git repository https://github.com/feczo/jenkins-quickstart.git
upserted Task meta-feczo-jenkins-quickstart-m-6jqz8-meta-pipeline-1
upserted Pipeline meta-feczo-jenkins-quickstart-m-6jqz8-1
created PipelineRun meta-feczo-jenkins-quickstart-m-6jqz8-1
created PipelineStructure meta-feczo-jenkins-quickstart-m-6jqz8-1

Watch pipeline activity via:    jx get activity -f jenkins-quickstart -w
Browse the pipeline log via:    jx get build logs feczo/jenkins-quickstart/master
You can list the pipelines via: jx get pipelines
When the pipeline is complete:  jx get applications

For more help on available commands see: https://jenkins-x.io/developing/browsing/


❯ tkn tr list
NAME                                                          STARTED         DURATION   STATUS
meta-feczo-jenkins-quickstart-m-6jqz8-1-meta-pipeline-mn2wm   2 minutes ago   ---        Failed(TaskRunValidationFailed)
meta-feczo-possum-dev-pr-2-prom-66x4n-3-meta-pipeline-n82mc   3 minutes ago   ---        Failed(TaskRunValidationFailed)

/tmp
❯ tkn tr describe meta-feczo-jenkins-quickstart-m-6jqz8-1-meta-pipeline-mn2wm
Name:              meta-feczo-jenkins-quickstart-m-6jqz8-1-meta-pipeline-mn2wm
Namespace:         jx
Task Ref:          meta-feczo-jenkins-quickstart-m-6jqz8-meta-pipeline-1
Service Account:   tekton-bot
Timeout:           240h0m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 branch=master
 build=1
 jenkins.io/pipelineType=meta
 jenkins.io/task-stage-name=meta-pipeline
 owner=feczo
 repository=jenkins-quickstart
 tekton.dev/pipeline=meta-feczo-jenkins-quickstart-m-6jqz8-1
 tekton.dev/pipelineRun=meta-feczo-jenkins-quickstart-m-6jqz8-1
 tekton.dev/pipelineTask=meta-pipeline
 tekton.dev/task=meta-feczo-jenkins-quickstart-m-6jqz8-meta-pipeline-1

🌡️️   Status

STARTED         DURATION    STATUS
3 minutes ago   ---         Failed(TaskRunValidationFailed)

Message

invalid input resources: Task's declared required resources are missing from the TaskRun: [workspace]
