### ISSUE TITLE
make build failure due to invalid pseudo-version

### ISSUE THREAD

**Issue by leonardge** [jenkins-x/jx#6980]
### Summary 
When I run `make build` it fails due to invalid pseudo version.
```bash
$ go version
go version go1.14 darwin/amd64
```

### Steps to reproduce the behavior
`make build`

### Expected behavior
It should just build.

### Actual behavior
```bash
go: github.com/antham/chyle@v1.4.0 requires
	github.com/spf13/cobra@v0.0.0-00000000000000-c46add8a6528: invalid pseudo-version: malformed time "00000000000000"
```

### Jx version
`commit cf02c42efcd4d7228d5f31b419641e6172f8dfc6`

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment
Mac OS

I fixed the issue by adding to the `go.mod`
```
replace github.com/spf13/cobra => github.com/spf13/cobra v0.0.7
```
So I am just wondering should this be added to the repository?

**Comment by deanesmith** [comment]
Please use Golang v 1.12, you should not have any issues.
