### ISSUE TITLE
DevPods: No snapshot available

### ISSUE THREAD

**Issue by diethardsteiner** [jenkins-x/jx#6981]
### Summary 

DevPods: Release created but no snapshot.
I followed the instructions of the "The DevOps 2.6 Toolkit: Jenkins X" and the result is not as described in the book.

### Steps to reproduce the behavior

I followed [these instructions](https://gist.github.com/vfarcic/50fac90cc10ebc67b36ea07687e8df75#file-07-dev-sh)

### Expected behavior

There is both a snapshot and release available.

### Actual behavior

```
go-demo-6 % jx get applications                                                (master)go-demo-6
APPLICATION STAGING PODS URL
go-demo-6   1.0.479 1/1  http://go-demo-6.jx-staging.35.190.145.60.nip.io
```

The book states:
"We can see that the go-demo-6 application is available as a SNAPSHOT as well as a specific release in the STAGING environment (e.g., 0.0.159 ). SNAPSHOT is the release running in our personal development environment (DevPod)."

There is only the release showing up but not the snapshot.

### Jx version

```
brew info jx                                                   (master)code-examples
jenkins-x/jx/jx: stable 2.0.1236
A tool to install and interact with Jenkins X on your Kubernetes cluster.
https://jenkins-x.io/
/usr/local/Cellar/jx/2.0.1150 (8 files, 218.2MB) *
  Built from source on 2020-01-24 at 09:41:25
From: https://github.com/jenkins-x/homebrew-jx/blob/master/Formula/jx.rb
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GCP 

### Operating system / Environment

MacOS

**Comment by deanesmith** [comment]
@vfarcic Do you have any background on this?

**Comment by vfarcic** [comment]
`jx get applications` did show snapshots in the past. Now I'm not sure whether that was intentionally removed (without a deprecation notice) or it a bug caused by some other changes.

**Comment by dmaljovec** [comment]
@vfarcic I have been going through your book and have to start by saying thank you. It is a great resource for our team as we try to get a handle on JenkinsX and how we can use it at our company.

I also ran into this issue. I don't know if it is related, but as I was walking through the steps, I did note something else anomalous, and I don't know if it is related? One thing that was suspicious earlier on was I did not see the `exposecontroller-service-...` running in my devpod when I was asked to run `kubectl -n $SKAFFOLD_DEPLOY_NAMESPACE get pods` inside the devpod at around [line 91](https://gist.github.com/vfarcic/50fac90cc10ebc67b36ea07687e8df75#file-07-dev-sh-L91)  in the associated gist. Mine looks more like:

```
NAME                                  READY   STATUS    RESTARTS   AGE
go-demo-6-go-demo-6-...   1/1     Running   0          12h
go-demo-6-go-demo-6-db-arbiter-0      1/1     Running   0          12h
go-demo-6-go-demo-6-db-primary-0      1/1     Running   0          12h
go-demo-6-go-demo-6-db-secondary-0    1/1     Running   0          12h
```

Maybe this is related, maybe this is a red herring? 🤷‍♂ 

Thanks again for such a thorough and well thought out resource!

**Comment by vfarcic** [comment]
@dmaljovec I updated the book soon after this issue was created. If you have eBook from LeanPub or Amazon, you should be able to download the updated version. Please send me a private message to Twitter (@vfarcic), LinkedIn, or anywhere else, and I'll send you a free coupon from LeanPub so that you can have the latest update.
