### ISSUE TITLE
Build failing because it is looking for a chart with a capital letter

### ISSUE THREAD

**Issue by dorrab** [jenkins-x/jx#6985]
### Summary 
Build failing because it is looking for a chart with a capital letter### Steps to reproduce the behavior

### Expected behavior
build pass 
### Actual behavior

Showing logs for build dorrab-test33-master-9xfnz-1 stage from-build-pack and container step-promote-changelog
/bin/sh: line 0: cd: /workspace/source/charts/Test33: No such file or directory
## Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
Beat you to it with #6983. =)
