### ISSUE TITLE
Helm issue during JenkinsX install

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/jx#6986]
### Summary
Hi, I'm installing JenkinsX on an existing on-premise Kubernetes cluster using the jx command. I'm running the below command from my local machine as my kubectl has been configured to use the Kubernetes cluster. I'm getting " x509: certificate signed by unknown authority" error.
I tried both helm2 and helm3 and have the same issue.

### Steps to reproduce the behavior
1. Run the below command.
 jx install --provider=kubernetes  --on-premise=true --git-provider-kind=github  --git-api-token=<xxxxxxx> --skip-setup-tiller=false  --static-jenkins=false --helm-tls=false --ng=true --helm3=false --helm-client-only=true --local-cloud-environment=false  --register-local-helmrepo=true —-no-tiller=true —-tekton=true --skip-setup-tiller  --install-dependencies=true  --register-local-helmrepo=true

### Expected behavior
The JenkinsX installation must be successful.
### Actual behavior
WARNING: 
retrying after error:failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: x509: certificate signed by unknown authority'
WARNING: 
retrying after error:failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: x509: certificate signed by unknown authority'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1192+cjxd.7
Kubernetes cluster v1.16.8
kubectl            v1.14.7
helm client        Client: v2.16.3+g1ee0254
git                2.20.1 (Apple Git-117)
```

### Jenkins type

- [yes ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Using Kubernetes cluster 1.16.x which was installed by the Kubernetes Admin. I'm using the jx command to install jenkins on top of the  Kubernetes Cluster.

### Operating system / Environment

MAC Laptop (Local environment)

**Comment by garethjevans** [comment]
Hi @2020testuser are you running from behind a proxy? 

I'd also not that `jx install` is deprecated and is going to be removed quite soon.  I'd take a look at `jx boot` instead.

**Comment by 2020testuser** [comment]
@garethjevans - Revisiting this issue now. With jx boot , I'm getting the below error. I'm trying to do JenkinsX testing to promote its use. Unable to proceed further, because of this issue.
`FATAL: Your current helm version v3 is not supported. Please downgrade to helm v2.
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '.', output: ''`

Is there any argument that I can either pass or set in yaml to downgrade to helm2? Thanks!

**Comment by 2020testuser** [comment]
@garethjevans - I got past that error after downgrade and now I'm getting the below error. 
`WARNING:
retrying after error:failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: x509: certificate signed by unknown authority'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: x509: certificate signed by unknown authority
 `
Any idea on how to get the issue resolved? Thanks!

**Comment by ankitm123** [comment]
This is most probably a cert issue/something with your network. For instance this: https://github.com/helm/helm/issues/4228.
