### ISSUE TITLE
email address on project page not working

### ISSUE THREAD

**Issue by barry-schneider** [jenkins-x/jx#699]
I am getting an error when using this message

jenkins-dev@googlegroups.com

The response from the remote server was:550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser q42-v6si609644qtc.0 - gsmtp
--

Final-Recipient: rfc822; jenkins-dev@googlegroups.com
Action: failed
Status: 5.1.1
Remote-MTA: dns; gmr-smtp-in.l.google.com. (2607:f8b0:400c:c0e::e, the server
 for the domain googlegroups.com.)
Diagnostic-Code: smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try
 550-5.1.1 double-checking the recipient's email address for typos or
 550-5.1.1 unnecessary spaces. Learn more at
 550 5.1.1  https://support.google.com/mail/?p=NoSuchUser q42-v6si609644qtc.0 - gsmtp
Last-Attempt-Date: Fri, 20 Apr 2018 06:49:04 -0700 (PDT)

**Comment by jstrachan** [comment]
ah sorry about that! we switched it back to the main Jenkins developer mailing list as there was so little traffic and folks tended to use github issues or slack for most feedback: http://jenkins-x.io/community/ - its also a way of trying to get more Jenkins X activity seen by traditional Jenkins developers etc.
