### ISSUE TITLE
FRE: Remote environments in the dev cluster

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#7005]
We should be able to list all the remote environments (clusters) from the dev cluster through `jx get env`

**Comment by nodece** [comment]
We can call `kubectl config get-clusters` to list the clusters `kubectl` knows about. 

Is it like this?

**Comment by vfarcic** [comment]
The goal is to be able to have JX environments in different clusters, so `jx get env` executed from the `dev` cluster (the only one currently supported in JX) should display those in other clusters.

Please note that this RFE is part of a bigger effort to create full support for remote environments running in different clusters and it is based on the work done in Jenkins X labs. A more concrete proposal will follow. This and all other issues marked with the label `remote-envs` is a way to break that work into separate features.
