### ISSUE TITLE
Step's invalid image doesnt fail pipeline

### ISSUE THREAD

**Issue by iftachsc** [jenkins-x/jx#7016]
### Summary 
If a step is defined with an invalid image tag and the pod fails on ErrImagePull the pipeline on the UI apears as it is still running  and thus like that forever. 
there is no pipeline run to stop via jx stop pipeline command.

### Steps to reproduce the behavior
have a step with an invalid image

### Expected behavior
UI should indicate that there pipeline is not running any more.

### Actual behavior
the left image of the pipeline indicates it is still running
### Jx version
jxl                0.0.158
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.14.10
helm client        3.0.3
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F203

The output of `jx version` is:

```
jxl                0.0.158
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.14.10
helm client        3.0.3
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F203```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

<!--
EKS
-->

### Operating system / Environment

<!--
MAC OSX
-->

**Comment by deanesmith** [comment]
Hi @iftachsc, could you please create an issue in the Jenkins-X-Labs repo for this `jxl` issue?

**Comment by iftachsc** [comment]
just so i understand (because i am going to start contribute soon) - why is this belongs there? because we it is a jenkins-x/tekton pipeline and not classical Jenkins? i want to understand the seperation between the two

**Comment by deanesmith** [comment]
@iftachsc JXL is fast, cutting edge, experimental technology.  JX is production capable, stable, and slower moving.  Features surfaced in JXL will likely find their way to JX.  Both JXL and JX leverage Tekton pipelines.  Classic Jenkins (static masters) is going to be removed from JX next week.  Does that help?
