### ISSUE TITLE
 couldn't access jenkins server

### ISSUE THREAD

**Issue by stevenbill** [jenkins-x/jx#7018]
i cant  create  new  project  and when i run  jx  install show to  me  (y)
please  see my  pic 
![Screenshot from 2020-04-06 13-26-37](https://user-images.githubusercontent.com/29622827/78553931-6c49bf80-780a-11ea-9368-cafe5020024c.png)
![Screenshot from 2020-04-06 13-26-09](https://user-images.githubusercontent.com/29622827/78553936-6d7aec80-780a-11ea-9af9-b1bb66ca055d.png)

**Comment by deanesmith** [comment]
Hi @stevenbill, are you looking to run a static master Jenkins server?

**Comment by stevenbill** [comment]
yea  on  my  localhost  with  local  kubernetes

**Comment by deanesmith** [comment]
@stevenbill,  in a week static master support in Jenkins X will be removed in favor of focusing on Tekton pipelines exclusively.  For reference - https://jenkins-x.io/blog/2020/03/11/tekton/
