### ISSUE TITLE
How to disable ingress for a jx service like Chart Museum?

### ISSUE THREAD

**Issue by mathieusama** [jenkins-x/jx#7022]
### Summary

For security reasons, we want to disable the Ingress for Chart Museum, but can't figure how to do that.

When I look at its chart: http://chartmuseum.jenkins-x.io/charts/chartmuseum-1.1.7.tgz I see that the Ingress resource is conditional to `.Values.ingress.enabled`, so in my dev repo’s `/env/chartmuseum/values.tmpl.yaml` I put this:

```
ingress:
  enabled: false
```

but that didn’t prevent the Ingress from being created. I also tried to put that config directly in `env/values.tmpl.yaml` :

```
chartmuseum:
  ingress:
    enabled: false
```

but that didn’t work either. So I also tried putting this in `env/jenkins-x-platform/values.tmpl.yaml`:

```
chartmuseum:
  service:
    annotations:
      fabric8.io/expose: "false"
      fabric8.io/exposeUrl: "false"
```

These annotations successfully get applied to the service resource in cluster, but exposecontroller still creates the ingress.

What do I need to do to prevent it from creating the Ingress?

### Jx version

```
NAME               VERSION
jx                 2.0.1192+cjxd.7
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Jenkins type

- Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

AWS/EKS

```
eksctl create cluster
  --name $CLUSTER
  --version 1.14
  --region $ZONE
  --nodegroup-name standard-workers
  --node-type t3.medium
  --nodes 3
  --nodes-min 3
  --nodes-max 3
  --managed
```

### Operating system / Environment

ubuntu:bionic

**Comment by rawlingsj** [comment]
That is odd.  I dont have a running environment ATM but can do next week and look to reproduce the issue.  

Personally I've been avoiding using `exposecontroller` and instead adding the ingress.yaml resources directly into the applications helm chart `templates` or my environment repo `templates` folder.  Then remove exposecontroller from the environment repo `requirements.yaml`.  

I dont think this approach has been validated but if you're looking for something to try before we can reproduce the issue I'd try this approach as then you only expose the services you have ingress.yaml for.

**Comment by rawlingsj** [comment]
BTW for an example of avoiding `exposecontroller` like the suggestion above, here's a link to a helm chart we add in our dev environment repo chart of Jenkins X own infrastructure cluster.  This also includes the ingress rules I was mentioning so we avoid exposecontroller too  https://github.com/jenkins-x-charts/jxboot-resources/tree/master/jxboot-resources/templates

So you could create your own chart or just add them to your `environment-foo-dev/env/templates/` dir and remove `exposecontroller`  from the `requirements.yaml`.

**Comment by mathieusama** [comment]
That would work, but at the moment we would prefer selectively disabling exposecontroller on specific services.
