### ISSUE TITLE
How to add custom annotations to any arbitrary ingress?

### ISSUE THREAD

**Issue by mathieusama** [jenkins-x/jx#7023]
### Summary 

We're trying to add custom annotations to the ingress of an application service.

Previously, we had to do something similar for a service in the jx/dev env and the way we finally achieved it was to create a custom Ingress template with same name/namespace and with only the extra annotations we wanted. Then, it appears that exposecontroller would not overwrite the Ingress, but instead merge with it, leaving the annotations we wanted.

However, that approach does *not* appear to work for services in staging and prod.

What is the recommended way to add custom annotations to any arbitrary ingresses?

### Jx version

```
NAME               VERSION
jx                 2.0.1192+cjxd.7
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.16.0
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Jenkins type

- Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

AWS/EKS

```
eksctl create cluster
  --name $CLUSTER
  --version 1.14
  --region $ZONE
  --nodegroup-name standard-workers
  --node-type t3.medium
  --nodes 3
  --nodes-min 3
  --nodes-max 3
  --managed
```

### Operating system / Environment

ubuntu:bionic

**Comment by rawlingsj** [comment]
There's an annotation that exposecontroller uses to add custom annotations to the generated ingress, here's an example https://github.com/jenkins-x/jenkins-x-platform/blob/ecb17bb46f46bd51c943a2e5bbf53d300d5b3545/jenkins-x-platform/values.yaml#L964. Does something like that help?

**Comment by mathieusama** [comment]
Excellent, we confirm that this works for us! Thanks! 👍

**Comment by rawlingsj** [comment]
great to hear!
