### ISSUE TITLE
jx boot fails on Windows

### ISSUE THREAD

**Issue by ACB1337** [jenkins-x/jx#7035]
### Summary
When running jx boot on Windows it tries to execute /bin/sh in step validate-git. This obviously fails.

### Steps to reproduce the behavior
execute jx boot on Windows in powershell

### Expected behavior
set up jenkins x

### Actual behavior
```
Booting Jenkins X
WARNING: failed to load ConfigMap jenkins-x-docker-registry in namespace jx: failed to get configmap jenkins-x-docker-registry in namespace jx, configmaps "jenkins-x-docker-registry" not found
WARNING: failed to load ConfigMap jenkins-x-docker-registry in namespace jx: failed to get configmap jenkins-x-docker-registry in namespace jx, configmaps "jenkins-x-docker-registry" not found

STEP: validate-git command: /bin/sh -c jx step git validate in dir: E:\dev\environment-test-dev\workspace\source\workspace\source\env

error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step git validate' command in directory 'workspace\source\workspace\source\env', output: ''
```
### Jx version

The output of `jx version` is:

```
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
NAME               VERSION
jx                 2.0.1274
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.5
git                2.19.0.windows.1
Operating System   Windows 10 Pro 1809 build 17763
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE cluster tried with jx create gke --skip-install and manual creation

### Operating system / Environment
Windows 10/Powershell

**Comment by nodece** [comment]
I need install `sh` into `Windows`.

**Comment by nodece** [comment]
You need install `sh` into `Windows`.

**Comment by nodece** [comment]
Assume installed `bash` or `sh` into `Windows`.

The following is working in `Windows 10/Powershell`:  

```
bash
jx create gke --skip-install 
```

**Comment by ACB1337** [comment]
if you execute bash in Powershell you are starting WSL. So no it is not working on Windows it is working on Linux.

**Comment by nodece** [comment]
Sorry @ACB1337 , I provide a wrong message.

We cannot run `/bin/sh` in `Windows`. Need to consider the `Windows` platform.

I will to fix it.

**Comment by nodece** [comment]
What do you think that run `sh` in `Windows`?

**Comment by mdcme** [comment]
im also getting this issue.

**Comment by nodece** [comment]
I would submit a PR.

**Comment by nodece** [comment]
I submitted a PR to fix it in #7096.

**Comment by deanesmith** [comment]
Hi @ACB1337, were you able to try this fix?

**Comment by vbottu** [comment]
I am also getting the same issue in windows 10 with jenkins bootconfig version 1.0.85

**Comment by nodece** [comment]
@vbottu Is using the latest jx? You need run it in `sh/bash`.

**Comment by Woland2k** [comment]
still getting the same error running jx 2.1.24, which should just call sh command and not /bin/sh

`error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step git validate' command in directory 'workspace\source\workspace\source\env', output: ''`

**Comment by nodece** [comment]
@Woland2k Could you create a new issue for the question?

**Comment by Woland2k** [comment]
@nodece it is exactly the same error as described, but ok, I can create a new issue
