### ISSUE TITLE
Fork jx-app-sonar-scanner into jenkins-x-apps organization

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#7037]
### Summary 
I am happy to announce that the `jx-app-sonar-scanner` SonarQube add-on for Jenkins-X is now ready for public consumption!

Please could someone fork [https://github.com/Bootstrap-Jersey/jx-app-sonar-scanner](https://github.com/Bootstrap-Jersey/jx-app-sonar-scanner) into `jenkins-x-apps` and tweak the build to fit the JX build process?

Attention should be given to the Makefile and skaffold config to set versions and retarget the image to the official image registry...

Note that `jx-app-sonar-scanner` is configured to scan itself with SonarQube, so, once you have an initial version of the plugin installed, it can verify its own quality as part of the build.

@abayer 
@hferentschik 
@jstrachan

**Comment by deanesmith** [comment]
Hi @tdcox, Thank you!  If nobody else gets to it, I'm happy to give it a shot.

**Comment by deanesmith** [comment]
Forked and added to apps repo.  Meeting May 18 to add to production.

**Comment by kerthcet** [comment]
what's the result now. is jenkinsx support sonar yet?
