### ISSUE TITLE
Creating A Community Forum on Jenkins-X.io

### ISSUE THREAD

**Issue by Dgiordano33** [jenkins-x/jx#7044]
### Mission
To provide a hosted, consolidated, open forum specifically for the Jenkins X community, located at [https://discussion.jenkins-x.io](https://discussion.jenkins-x.io)

While there are many places to look for Jenkins X questions and answers, the Jenkins X Community Forum is meant to be the definitive source for answers on Jenkins X.

### Current State

There are many different mediums of communicating and collaborating today about the Jenkins X OSS project. Below is a list of places, their primary use cases, and possible workflows. They almost form formal levels of triage!

**Slack**
Today, the Kubernetes community has an active Slack group with a Jenkins X channel for relevant discussions on all things Jenkins X. There are two main problems with today’s Slack group: 
* Slack isn’t a great medium for async, long-form discussions between users and engineers 
* Answers in Slack are unable to be seen or searched by non-users. We significantly limit the number of people who can participate in discussions and learning 

Slack will still be used going forward for Jenkins-X related news, fun findings, and as a communication vehicle in the K8s community. But if a user asks a question or prods a long-form discussion - they should be directed to the Discourse Community.

**NEW: Jenkins X Community Forum**
The Discourse Community is meant to be the place users post questions to get answered and often-times actual solutions are thought up and discussed. This is where discussions are to be formed - as it provides an open historical record of all communication in an easy-to-use format.

The Discourse Community is also great for conveying news and announcements in an asynchronous pattern. 

### Technology
We will use an open-source license of Discourse.

**GitHub Issues**
GitHub Issues is the official place to create tickets and reports bugs for the Jenkins X project. If a longer discussion needs to be had about the source of the problem or the path for the solution, this should be communicated via the Discourse Community. 
This is not the place to ask questions or post that “pain in the neck issue I can’t get around right now”. If that “pain in the neck issue” is found to be an actual bug on the Discourse Community, a GitHub Issue can then be raised.

**Jenkins-X.io Documentation**
The official location for Jenkins X documentation, tutorials, and how-tos. The end state of discussions and Q&A’s found in other mediums like GitHub Issues and Discourse end up here in the form of official documentation.

**Comment by MarckK** [comment]
This is great @Dgiordano33! 

I've already heard good feedback on this initiative. :)

**Comment by MarckK** [comment]
We've set up Discourse! 
Join the Jenkins X discourse here: https://jenkinsx.discourse.group/

Closing this as issue resolved. :)
