### ISSUE TITLE
Add support for Digital Ocean

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#705]
I notice that kops recently added support for Digital Ocean
https://github.com/kubernetes/kops/blob/master/docs/tutorial/digitalocean.md

So we should be able to create a `jx create cluster do` for using kops on DO - the current `jx create cluster aws` uses kops under the covers to spin up the kubernetes cluster - so we’ve hopefully done the heavy lifting already

**Comment by akeating** [comment]
I notice DO Kubernetes is now in _Limited Availability_ which I understand is a prelude to _GA_.

**Comment by balazs-pinter** [comment]
Can you please update us on the current status of DO?

**Comment by zetaron** [comment]
DO Kubernetes is now in *General Availability* and managed clusters can be created using eg. the official [doctl kubernetes cluster create <name>](https://github.com/digitalocean/doctl/blob/master/commands/kubernetes.go) command, much like what's currently done for Amazons EKS with its [eksctl](https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_cluster_eks.go#L191).

**Comment by solarsoft0** [comment]
any progress on this

**Comment by thakkarsagar12** [comment]
any progress on this

???

**Comment by VanThanhThai** [comment]
any one looking into this?
