### ISSUE TITLE
jx create quickstart failed as - X Sorry, your reply was invalid: GET http://****/api/v3/repos/***/test: 410  []

### ISSUE THREAD

**Issue by violin8668** [jenkins-x/jx#7050]
### Summary 
jx 2.0.1177
kubernetes 1.17.3
git 2.23.0

gitlab v11+

jx installed successfully. And I can it used api v4 in update-webhooks step.

However, when I exec the command `jx create`, it failed.
root@bootstrapper [ ~/jenkins-x-boot-config ]# jx create spring
Command "spring" is deprecated, it will be removed on Mar 1 2020. We now highly recommend you use jx create project instead. Please check https://jenkins-x.io/commands/jx_create_project/ for more details.
Using Git provider xxx at http://xxx
? Do you wish to use xxx as the Git user name? Yes
? Who should be the owner of the repository? xxx
X Sorry, your reply was invalid: GET http://xxx/api/v3/repos/xxx/test: 410  []
? Enter the new repository name: 

### Expected behavior
jx create quickstart/spring successfully.

### Actual behavior
fail

### Jx version
2.0.1177
The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1177
Kubernetes cluster v1.17.3
kubectl            v1.16.4+vmware.1
helm client        v2.16.5+g89bd14c
git                2.23.0
```

### Jenkins type

- [ v] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by hallliu1984831** [comment]
@violin8668 , What's your git repo info? I got the same issue since I do not use github as source code repo, use company setup gitlab instance instead.
I am not sure whether gitlab has that URL "http://xxx/api/v3/repos/xxx/test" or not, but I tried to access that URL and got "{"error":"API V3 is no longer supported. Use API V4 instead."}" error.

Please kindly help

**Comment by httpete** [comment]
go to ~/.jx/gitAuth.yml the kind: field will be blank make it gitlab.
