### ISSUE TITLE
Change the CHART REPOSITY to use Nexus HELM REPO error in step helm release

### ISSUE THREAD

**Issue by mcabrito** [jenkins-x/jx#7052]
### Summary 
I’m trying to use a Chart Repository by external Nexus, but I’d a problem in pipeline when I’m using the command:

```jx step helm release```

When this command do the upload chart file, my $CHART_REPOSITORY is changing and including the /api/charts

```
+ jx step helm release --verbose
DEBUG: Using helmBinary helm with feature flag: template-mode
DEBUG: Initialising Helm 'init --client-only'
DEBUG: getting vault name for namespace jx
DEBUG: system vault name from config 
DEBUG: Vault name generated: 
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
DEBUG: getting vault name for namespace jx
DEBUG: system vault name from config 
DEBUG: Vault name generated: 
Adding missing Helm repo: <nexus-repo-helm> https://<nexus-repo-helm-URL>/repository/repo-helm
Successfully added Helm repository element.basis.com.br.
DEBUG: getting vault name for namespace jx
DEBUG: system vault name from config 
DEBUG: Vault name generated: 
Adding missing Helm repo: <nexus-repo-helm>-0 https://<nexus-repo-helm-URL>/repository/repo2-helm
Successfully added Helm repository <nexus-repo-helm>-0.
Running helm dependency build in .
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "<nexus-repo-helm>-0" chart repository
...Successfully got an update from the "<nexus-repo-helm>" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "storage.googleapis.com" chart repository
Update Complete.
Saving 1 charts
Downloading common from repo https://<nexus-repo-helm-URL>/repository/repo-helm/
Deleting outdated charts
Uploading chart file app-packege-0.0.89-dev.tgz to https://<nexus-repo-helm-URL>/repository/repo-helm/api/charts
Received 404 response
```

In my Nexus repo helm doesn’t have the api/charts.

We fount on the step_helm_release.go this input code:

```u := util.UrlJoin(chartRepo, "/api/charts")```

[step_helm_release.go line](https://github.com/jenkins-x/jx/blob/044e9b49bf8215dbe10e88820b9702ab6d6cd94c/pkg/cmd/step/helm/step_helm_release.go#L143)

**How we could use the Nexus to all Helm Repo for upload or download charts?

Is there a way to use my local mirror completely?**

### Steps to reproduce the behavior
Create a Nexus Helm Repo and use as a chat_repository

```
CHARTMUSEUM_CREDS = credentials(‘jenkins-x-chartmuseum’)
CHART_REPOSITORY = ‘https://<nexus-repo-helm-URL>/repository/repo-helm/’
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1268
jenkins x platform 2.0.2120
Kubernetes cluster v1.15.9
kubectl            v1.17.0
helm client        2.9.0
git                2.16.6
Operating System   "CentOS Linux release 7.7.1908 (Core)
```

### Jenkins type

- [X] Classic Jenkins
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

rke 2

### Operating system / Environment

Linux

**Comment by reison007** [comment]
Having the same issue here.

**Comment by sladyn98** [comment]
So If I understand correctly  Nexus repo helm doesn’t have the api/charts, and we would like to add an option to use local mirrors so that the charts can be picked up ?
CC @deanesmith @mcabrito @reison007

**Comment by mcabrito** [comment]
Yes! Simple that.
We would like to have an option to use an external repo like Nexus repo helm.

**Comment by Tazminia** [comment]
can't we just use the plain url and leave it up to administrator and users to configure the url, including or excluding the api/charts part ?

**Comment by deanesmith** [comment]
The ongoing strategy for JX provisioning is to divest in resource creation/management in favor of bring-your-own, but with improved documentation.  Nexus will be part of this effort and we welcome contributions/discussions to help determine the best way to go about it.

**Comment by sladyn98** [comment]
@deanesmith I would love to contribute, could you guide me a bit more on how I can get involved ?

**Comment by deanesmith** [comment]
Hi @sladyn98, based on the feedback here a step in the right direction would be to allow for the ability to have an option to be more flexible with the chart repo URL but without breaking the current happy path.
