### ISSUE TITLE
Bitbucket pull request update doesn't trigger pipeline execution

### ISSUE THREAD

**Issue by salvag-ntt** [jenkins-x/jx#7055]
### Summary 
With bitbucket server, when a project is successfully imported using `jx create project`, for each pull request created a pipeline is kicked off and if the executions succeeds a comment is added to the PR saying that everything was ok and gives the preview env url. 
When the pipeline fails and the developer updates the PR with fixes, the pipeline doesn't seem to be triggered, and I am not even able to trigger it manually with `jx start pipeline` because it only list the master pipelines available.
I am not entirely sure but it might be a problem related to webhooks for bitbucket

### Steps to reproduce the behavior
1) Have a project ready in a folder with maven and java11 so that the build pack is matched with maven-java11 (not sure if this is essential as I haven't tried with other applications). I guess even a simple hello world would do so long as you have a pom.xml and a actuator/health dependency to check the liveness/readyness of the application when deployed. Note that this step might not be essential as you might be able to repro with other languages and technologies.
2) Make sure that your project is available in a bitbucket repository. In my case I am using bitbucket server so I haven't checked if this applies also with bitbucket cloud version. I would be interesting to test that as well
3) Run `jx create project` from the root of your project and import the project from that directory
4) Once the project has been imported observe the master pipeline running successfully (hopefully).
5) Branch from master, make a change, commit, push and create a PR from bitbucket. 
6) Once the PR has been created observe the a pipeline is created with the id number of your PR and see whether it runs successfully.
7) Let's say that regardless of the result you want to update something, you go ahead and on the same branch you make a change, commit and push.

### Expected behavior
The pipeline that references that PR should be executed again (maybe using an increment number) 
### Actual behavior
The pipeline that references that PR is not executed 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1278
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.14.0
helm client        2.16.1
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
So this is... “fixed”. Sorta. https://github.com/jenkins-x/lighthouse/issues/511 - the fix on our side is in, but the underlying problem is that BitBucket Server before 7.0 wasn’t sending any webhook event for new commits. With https://jira.atlassian.com/browse/BSERV-10279 done in 7.0, BitBucket Server has added the needed webhook, but there’s no solution for earlier versions.
