### ISSUE TITLE
Jenkin X CLI messes with global .gitconfig

### ISSUE THREAD

**Issue by achedeuzot** [jenkins-x/jx#7063]
### Summary 
`jx` CLI implicitly changes `~/.gitconfig` settings without warnings or confirmation leading to subtle wrong author issue in unrelated git repositories

### Steps to reproduce the behavior
After installing jx, I wanted to setup a particular cluster with a CI dedicated user and jx CLI updated my `~/.gitconfig` file without asking or warnings. 
After a few days, I found out that I had pushed commits with the wrong user to some shared repos and that my commits weren't signed anymore because of that change.

My `~/.gitconfig` is like this:

    [includeIf "gitdir:~/workspace/corp/"]
      path = .gitconfig-corp
    [includeIf "gitdir:~/workspace/open-source/"]
      path = .gitconfig-open-source
    [includeIf "gitdir:~/workspace/personal/"]
      path = .gitconfig-personal

What jenkins X CI auto-appended at the end of my `~/.gitconfig` was the following:

    [user]
      email = ci-bot-service@corp.example.com
      name = ci-bot

The values set here were overriding the directory-specific git configurations I had in place and messing with my commits resulting in a need to rewrite shared branches histories and have every dev re-clone a fresh copy to remove all the wrong authored commits.

If I removed that `[user]` block config from the `~/.gitconfig`, jx could not complete operations that use git under the hood because it clones repos into temporary directories outside of my home directory which then makes jx see an empty/invalid git user.

### Expected behavior
At least some form of warning or confirmation that it's going to change settings in the global git config and not specific to the repo I'm using jenkins X in. I have multiple users / use-cases with different git accounts so I can't have a global git config for everything, especially when setting up a dedicated user for jenkins X.

### Actual behavior
Updating my global `~/.gitconfig` without notice or warnings.

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.1245+cjxd.8
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.5
helm client        2.16.5
git                2.24.1 (Apple Git-126)
Operating System   Mac OS X 10.15.4 build 19E287
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Basic k8s GCP cluster created with `jx create cluster gke --skip-installation -n sandbox-cluster`

### Operating system / Environment

Mac OS X 10.15.4
Fish shell 3.1.0
git 2.24.1 (Apple Git-126)

**Comment by deanesmith** [comment]
Hi @achedeuzot, thanks for the report.  We'll look at it soon.

**Comment by achedeuzot** [comment]
Could we keep this ? :x
