### ISSUE TITLE
Openshift 3.11 Support

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#7064]
This epic will contain the issues that will need to be addressed to make Jenkins X properly support Openshift v1.13 with limited permissions.

Most of the changes will be on the charts that we install as part of the booting process which repositories are not added to CodeTree.

There will be minimal code changes to the Jenkins X codebase.

**Comment by Asgoret** [comment]
Ok, I'll start...
1) Doesn't support for openshift cli (`oc`)
2) Through I set `strictPermissions: true` in config file jx tries to do something in kube-system

cc @dgozalo @jstrachan

**Comment by Asgoret** [comment]
Command:
`jx boot`
Error:
```
....
 must only have "properties", "required" or "description" at the root if the status subresource is enabled
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c kubectl apply --wait --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml' command in directory '.', output: ''
```
