### ISSUE TITLE
How to add new environments using jx boot

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx#7066]
### Summary 
It should be easy to add new environments
### Steps to reproduce the behavior
add a new key under "environments" in jx-requirements.yml

    environments:
        key:  fishing

### Expected behavior

The environment is created, just like staging and production

### Actual behavior
Nothing happens

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1284
Kubernetes cluster v1.15.10-eks-bac369
kubectl            v1.16.2
helm client        2.14.3
git                2.18.0
Operating System   Mac OS X 10.14.6 build 18G3020
```

### Kubernetes cluster
EKS, kubernetes 1.15

**Comment by babadofar** [comment]
The current way to do this is described here, https://jenkins-x.io/docs/managing-jx/faq/boot/#how-do-i-add-new-environments

**Comment by deanesmith** [comment]
@babadofar as part of the migration to boot, this one was never really finalized.  We will look at it and you should be aware of upcoming remote clusters.

**Comment by romenrg** [comment]
Note that I've linked a related issue I reported (https://github.com/jenkins-x/jx/issues/7281) asking to enhance the "jx delete environment" so that it also removes the associated GitHub repository.

Probably something to consider when implementing the equivalents in jx boot.

**Comment by jstrachan** [comment]
here's the first PR towards a fix to this for `jx boot` https://github.com/jenkins-x-charts/jxboot-resources/pull/42

once that is merged we'll need a change in https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/jxboot-resources/values.tmpl.yaml
