### ISSUE TITLE
Velero backups, repository, reports do not store to aws s3

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx#7067]
### Summary 
The s3 buckets for repository, backup and reports are all empty. 
Maybe related - inspecting the velero namespaces, there are no pods in there. 

Hard to say if this is expected behaviour, as the documentation on velero/backups is a little thin :)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1284
Kubernetes cluster v1.15.10-eks-bac369
kubectl            v1.16.2
git                2.18.0
Operating System   Mac OS X 10.14.6 build 18G3020```

**Comment by vfarcic** [comment]
@deanesmith ^^^

**Comment by hferentschik** [comment]
@babadofar, how did you install Jenkins X? There should be a Velero pod running in the velero namespace. 

You could run:

```bash
> kubectl get -n velero schedule
> kubectl get -n velero backup
```

to see whether there is a backup schedule and/or any backups, but most likely there won't be anything. I think the key is to find out how you install Jenkins X and where things go wrong. Are you able to reproduce this?

**Comment by babadofar** [comment]
Oh sorry, I forgot to mention it  - I use Jx boot, versionstream  v1.0.424 , on AWS EkS, using kubernetes 1.15 
The result of  
`kubectl get -n velero schedule `
`error: the server doesn't have a resource type "schedule"`

**Comment by babadofar** [comment]
Will be fixed by https://github.com/jenkins-x/terraform-aws-eks-jx/pull/109
