### ISSUE TITLE
Can't install app

### ISSUE THREAD

**Issue by bobbyz-dk** [jenkins-x/jx#7082]
### Summary 
I can't install the ui app.

### Steps to reproduce the behavior
jx add app jx-app-ui --version 0.1.49

### Expected behavior
App installed

### Actual behavior
```
$ jx add app jx-app-ui --version 0.1.49
error: Invalid option: --namespace xxxx
unable to specify --namespace when using GitOps for your dev environment
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1245+cjxd.8
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.15.11
helm client        2.16.5
git                2.26.0
Operating System   Ubuntu 16.04.4 LTS
```

### Jenkins type
JX BOOT

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - lighthouse
- [ ] Classic Jenkins

### Kubernetes cluster

Kubernetes 1.15

jx create cluster eks

### Operating system / Environment

Ubuntu 16.04.4 LTS

**Comment by bobbyz-dk** [comment]
Solution: Switch to jx namespace before installing the ui app.
`jx ns jx`

**Comment by bobbyz-dk** [comment]
Please add to documentation

**Comment by jha-cloudbees** [comment]
@deanesmith PR that should fix this issue:

https://github.com/cloudbees/docsite-cloudbees-jenkins-x-distro/pull/21

**Comment by jha-cloudbees** [comment]
The namespace instruction has been prepended to the list for installing the UI and is now live on the documentation website:
https://docs.cloudbees.com/docs/cloudbees-jenkins-x-distribution/latest/user-interface/install
