### ISSUE TITLE
Jenkins X installation is failing in on permises kubernetes Cluster

### ISSUE THREAD

**Issue by sanrum21** [jenkins-x/jx#7086]
### Summary 
Hi All, 
   I am facing simlar kind of issue , i installed jenkins x in already existing on premises k8s cluster  and found that tide,hook,nexus and pipelinerunner pods are crashing. 

crier-5945df9987-b9qpz                         1/1     Running            0          20m
deck-c554d4f8f-mn9ct                           1/1     Running            0          20m
deck-c554d4f8f-zgnnq                           1/1     Running            0          20m
hook-fcb784985-9bfhw                           0/1     CrashLoopBackOff   9          20m
hook-fcb784985-wdspz                           0/1     CrashLoopBackOff   11         20m
horologium-9cb787cd8-pwqw9                     1/1     Running            0          20m
jenkins-x-chartmuseum-67f75c4884-gsv7t         1/1     Running            0          20m
jenkins-x-controllerbuild-69d77dbfb7-jdnzx     1/1     Running            0          20m
jenkins-x-controllerrole-777546f5c-d7vlm       1/1     Running            0          20m
jenkins-x-docker-registry-589d4d79c4-87bbj     1/1     Running            0          20m
jenkins-x-heapster-66754b8fc5-psrw8            2/2     Running            0          20m
jenkins-x-nexus-5d7f85c5c5-84rk5               0/1     CrashLoopBackOff   7          20m
jenkins-x-nexus-67ffc76bc7-dpd6p               0/1     CrashLoopBackOff   7          17m
pipeline-5ddf8d5979-vgh96                      1/1     Running            0          20m
pipelinerunner-7c7b666998-zlj2b                0/1     CrashLoopBackOff   9          20m
plank-85f78549d8-tpkvt                         1/1     Running            0          20m
sinker-65c4b9b567-s7npn                        1/1     Running            0          20m
tekton-pipelines-controller-84c476bb4d-9zm28   1/1     Running            0          21m
tekton-pipelines-webhook-dc78bb98f-qfk2k       1/1     Running            0          21m
tide-667ff77444-fg9l8                          0/1     CrashLoopBackOff   11         20m

**Hook pod error :**
 Warning  Unhealthy  20m (x8 over 22m)     kubelet, cdf-worker1.hpeswlab.net  Liveness probe failed: Get http://172.16.72.173:8888/: dial tcp 172.16.72.173:8888: connect: connection refused
  Warning  Unhealthy  13m (x16 over 22m)    kubelet, cdf-worker1.hpeswlab.net  Readiness probe failed: Get http://172.16.72.173:8888/: dial tcp 172.16.72.173:8888: connect: connection refused
  Normal   Pulled     8m16s (x8 over 21m)   kubelet, cdf-worker1.hpeswlab.net  Container image "gcr.io/jenkinsxio/prow/hook:v20200107-aaa0608" already present on machine
  Warning  BackOff    3m21s (x70 over 19m)  kubelet, cdf-worker1.hpeswlab.net  Back-off restarting failed container

**Nexus pod error:**
 Warning  FailedPostStartHook  14m (x4 over 15m)   kubelet, cdf-worker1.hpeswlab.net  Exec lifecycle hook ([/opt/sonatype/nexus/postStart.sh]) for Container "nexus" in Pod "jenkins-x-nexus-5d7f85c5c5-84rk5_jx(e9e07bf3-8325-11ea-9159-005056be56c3)" failed - error: command '/opt/sonatype/nexus/postStart.sh' exited with 137: , message: ".."
  Normal   Killing              14m (x4 over 15m)   kubelet, cdf-worker1.hpeswlab.net  Killing container with id docker://nexus:FailedPostStartHook
  Warning  BackOff              41s (x77 over 15m)  kubelet, cdf-worker1.hpeswlab.net  Back-off restarting failed container

**Pipelinerunner pod error:**
 Warning  Unhealthy  23m (x2 over 23m)     kubelet, cdf-worker1.hpeswlab.net  Readiness probe failed: Get http://172.16.72.170:8080/ready: dial tcp 172.16.72.170:8080: connect: connection refused
  Normal   Pulled     23m (x3 over 23m)     kubelet, cdf-worker1.hpeswlab.net  Container image "gcr.io/jenkinsxio/builder-maven:2.0.1286-625" already present on machine
  Normal   Created    23m (x4 over 24m)     kubelet, cdf-worker1.hpeswlab.net  Created container
  Normal   Started    23m (x4 over 24m)     kubelet, cdf-worker1.hpeswlab.net  Started container
  Warning  Unhealthy  22m (x3 over 23m)     kubelet, cdf-worker1.hpeswlab.net  Liveness probe failed: Get http://172.16.72.170:8080/health: dial tcp 172.16.72.170:8080: connect: connection refused
  Warning  BackOff    4m46s (x97 over 23m)  kubelet, cdf-worker1.hpeswlab.net  Back-off restarting failed container

**tide pod error:**
Warning  Unhealthy  24m (x6 over 24m)     kubelet, cdf-worker2.hpeswlab.net  Liveness probe failed: Get http://172.16.39.146:8888/: dial tcp 172.16.39.146:8888: connect: connection refused
  Normal   Created    24m (x3 over 25m)     kubelet, cdf-worker2.hpeswlab.net  Created container
  Normal   Killing    24m (x2 over 24m)     kubelet, cdf-worker2.hpeswlab.net  Killing container with id docker://tide:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled     24m (x2 over 24m)     kubelet, cdf-worker2.hpeswlab.net  Container image "gcr.io/jenkinsxio/prow/tide:v20200107-aaa0608" already present on machine
  Normal   Started    24m (x3 over 25m)     kubelet, cdf-worker2.hpeswlab.net  Started container
  Warning  Unhealthy  5m36s (x32 over 24m)  kubelet, cdf-worker2.hpeswlab.net  Readiness probe failed: Get http://172.16.39.146:8888/: dial tcp 172.16.39.146:8888: connect: connection refused
  Warning  BackOff    31s (x92 over 22m)    kubelet, cdf-worker2.hpeswlab.net  Back-off restarting failed container

**output of jx version** 

### Steps to reproduce the behavior
  Install  jenkins X on on premises K8s cluter with external github and artifactory as docker registry
### Expected behavior
  Jenkins x should get installed successfully and all related pods should come up 
### Actual behavior
 few of the pods are not coming up 

crier-5945df9987-b9qpz                         1/1     Running            0          20m
deck-c554d4f8f-mn9ct                           1/1     Running            0          20m
deck-c554d4f8f-zgnnq                           1/1     Running            0          20m
hook-fcb784985-9bfhw                           0/1     CrashLoopBackOff   9          20m
hook-fcb784985-wdspz                           0/1     CrashLoopBackOff   11         20m
horologium-9cb787cd8-pwqw9                     1/1     Running            0          20m
jenkins-x-chartmuseum-67f75c4884-gsv7t         1/1     Running            0          20m
jenkins-x-controllerbuild-69d77dbfb7-jdnzx     1/1     Running            0          20m
jenkins-x-controllerrole-777546f5c-d7vlm       1/1     Running            0          20m
jenkins-x-docker-registry-589d4d79c4-87bbj     1/1     Running            0          20m
jenkins-x-heapster-66754b8fc5-psrw8            2/2     Running            0          20m
jenkins-x-nexus-5d7f85c5c5-84rk5               0/1     CrashLoopBackOff   7          20m
jenkins-x-nexus-67ffc76bc7-dpd6p               0/1     CrashLoopBackOff   7          17m
pipeline-5ddf8d5979-vgh96                      1/1     Running            0          20m
pipelinerunner-7c7b666998-zlj2b                0/1     CrashLoopBackOff   9          20m
plank-85f78549d8-tpkvt                         1/1     Running            0          20m
sinker-65c4b9b567-s7npn                        1/1     Running            0          20m
tekton-pipelines-controller-84c476bb4d-9zm28   1/1     Running            0          21m
tekton-pipelines-webhook-dc78bb98f-qfk2k       1/1     Running            0          21m
tide-667ff77444-fg9l8                          0/1     CrashLoopBackOff   11         20m
### Jx version

The output of `jx version` is:

```
# jx version
NAME               VERSION
jx                 2.0.1282
jenkins x platform 2.0.2152
Kubernetes cluster v1.13.10
kubectl            v1.13.10
helm client        2.14.0
git                2.16.6
Operating System   Unknown Linux distribution Linux version 3.10.0-1062.9.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Dec 6 15:49:49 UTC 2019
```

### Jenkins type
Serverless Jenkins X Pipelines (Tekton + Prow)

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
on premises kubernetes  cluster

### Operating system / Environment
 Centos 7

**Comment by deanesmith** [comment]
Hi @sanrum21, what specific flavor of Kubernetes are you using?

**Comment by sanrum21** [comment]
Hi @deanesmith ,  i have used kubeadm to install k8s cluster and its version is 

Kubernetes cluster v1.13.10. 

If you want any other information  , please let me know.

**Comment by deanesmith** [comment]
Thank you @sanrum21.  At this point we don't have a good story around JX on raw Kubernetes yet given how flexible various environments can be.  There will likely be some improvements here in the future.  For Nexus, there is a file mount that is essential to postStart.sh among other things...at first glance it appears to be networking related.

**Comment by sanrum21** [comment]
@deanesmith  , Thanks for your response , With respect to Nexus, docker, chartmuseum  pod, i have created the persistence volume and post that pods started coming up . But Only incase of Nexux pod, we are getting error saying podstart.sh script exit with the code 137. 

Our  environment is behind proxy and i have put proxy environment variable in Nexus deployment manifest file and recreated the pod. but still error is same.
