### ISSUE TITLE
jx boot failed with git Enterprise

### ISSUE THREAD

**Issue by roxxette** [jenkins-x/jx#7087]
### Summary 
jx boot failed with git Enterprise
### Steps to reproduce the behavior
Follow https://jenkins-x.io/docs/getting-started/setup/boot/#github-enterprise
I updated jx-requirements.yml as following:
..
gitServer: https://github.gsissc.myatos.net
..
webhook: lighthouse

### Expected behavior
jx boot will finish successfully

### Actual behavior
jx boot failed with following output:
[environment-gke-cluster-1-dev.zip](https://github.com/jenkins-x/jx/files/4507654/environment-gke-cluster-1-dev.zip)
...

Storing the requirements in team settings in the dev environment
Validating git repository for dev environment at URL https://github.gsissc.myatos.net/FR-BEZ-MSFT-TAXCUS/environment-cluster-1-dev.git
error: handle dev environment repository: creating remote for dev environment environment-cluster-1-dev: duplicating https://github.gsissc.myatos.net/FR-BEZ-MSFT-TAXCUS/environment-gke-cluster-1-dev to FR-BEZ-MSFT-TAXCUS/environment-cluster-1-dev: getting repo for https://github.gsissc.myatos.net/FR-BEZ-MSFT-TAXCUS/environment-gke-cluster-1-dev: failed to get repository FR-BEZ-MSFT-TAXCUS/environment-gke-cluster-1-dev due to: GET https://api.github.com/repos/FR-BEZ-MSFT-TAXCUS/environment-gke-cluster-1-dev: 401 Bad credentials []
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1286
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.14.10
helm client        2.16.3
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

gke 1.14.10

### Operating system / Environment

wsl2 Ubuntu 18.04.3 LTS

**Comment by abayer** [comment]
Can you provide your jx-requirements.yml file, please?

**Comment by roxxette** [comment]
The jx-requirements.yml is included in the attached zip file.

**Comment by roxxette** [comment]
Tried with latest versin jx 2.1.4, same issue
