### ISSUE TITLE
Buildpack resolver not recursive correctly

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx#7088]
### Summary 
I have my own buildpack that extends kubernetes (which extends classic).
LoadPipelineConfig fails file since the resolver is not updated after import

workaround: import everything parents import (stupid yeah...)

### Steps to reproduce the behavior
clone https://github.com/elhoutico/jenkins-x-jhipster
remove the classic import
jx step syntax effective

### Expected behavior
It should work

### Actual behavior
It fails

### Jx version

The output of `jx version` is:

```
2.1.4
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
You need to define all the build pack repos involved, so this is as intended.
