### ISSUE TITLE
Allow for using existing HashiCorp Vault with Jenkins X

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#7090]
### Summary 
If I have created my own new Vault instance or have a pre-existing Vault instance, I want to be able to leverage it for managing Jenkins X secrets.  

Notes:
- Specify Vault instance in the `jx-requirements.yml` file 
- Provide meaningful feedback during pre-check if there is an issue with the specified Vault instance and halt the boot process
- Would need to add/enable Kubernetes Authenticator for Vault
- Provide rich documentation to describe how to do this

**Comment by hferentschik** [comment]
There are several aspects to this issue which I try to outline in the following comments. Basically the following areas need to be looked at.

1. `jx boot` and the ability to specify an external Vault instance in general
1. The runtime behaviour, in particular how we create Vault clients in _factory.go_ (`CreateVaultClient` and `CreateSystemVaultClient`). The factory needs to be able to distinguish between the different Vault types (internal vs external) and create the clients accordingly. The existing client already uses Vault's Kubernetes authentication and it also uses ingresses, so adjusting this part is straight forward
1. General integration into Vault related commands. There is for example `jx get secrets`, `jx get vault config`, etc which are geared towards internally managed Vault instances. It needs to be determined on how to handle the external Vault instance in these cases.

**Comment by hferentschik** [comment]
**Integration with `jx boot`**

I order to integrate with Boot, we are going add two new properties to `RequirementsConfig`:

```go
type VaultConfig struct {
	// ExternalURL specifies the URL of an external Vault instance to use for secret storage.
	// Needs to be specified together with the Service Account to use for connecting to Vault.
	// All other settings needs to be nil.
	ExternalURL string `json:"externalURL,omitempty"`

	// SecretPrefix is thee secret prefix to be used for writing data into the KV engine of Vault.
	// If not specified the cluster name is used.
	SecretPrefix string
}

We need a way to specify the URL of the external Vault instance, plus an optional prefix path for the secrets.

In YAML this will look like:

```yaml
...
vault:
  externalURL: http://my-vault-url
  serviceAccount: vault-service-account
  secretPrefix: /acme/jenkins-x
...
```

`jx step boot vault` needs to handle the different scenarios for the Vault configuration and store enough information in the `jx-install-config` ConfigMap` to allow the client factory to instantiate the appropriate Vault client. In particular, we need to store whether we have an internal vs external Vault instance.

**Comment by hferentschik** [comment]
**Client factory**

In the client factory (`factory.go`) we need to use the additional information from `jx-install-config` to create the appropriate Vault client. The entry point is `CreateSystemVaultClient` which should transparently create the appropriate Vault client. The current `CreateVaultClient` will be renamed to `CreateInternalVaultClient` and a new `CreateExternalVaultClient` will be introduced. 

Currently, independent auth and config services will make use of the Vault client created by the factory. These services write to the root of the secret path (see _vault/constants.go_). For example, `createAuthConfigServiceVault` which will write to the secret path `/auth`. We need to make sure that this code transparently handles the `secretPrefix` which can be configured as part of an external Vault setup. The idea is to handle this transparently in the Vault client by inspecting the secret path and depending on the configuration appending an additional prefix. This will ensure backwards compatibility.

**Comment by hferentschik** [comment]
**Other**

We need to think about what to do with the commands like `jx get secrets` and `jx get vault config`. There is also `jx add vault` and `jx delete vault`. For the former, I suggest removing the commands as part of this issue. For the latter, we probably want to deprecate them first. We don't want to be managing Vault instances as part of Jenkins X.
