### ISSUE TITLE
can't boot new cluster

### ISSUE THREAD

**Issue by turbokernel** [jenkins-x/jx#7102]
I have downloaded jx binary file,and run jx boot command .After then, jx print out some error: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"'
May be the provider setting is wrong, i think. But when i enter the directory jenkins-x-boot-config and modify the jx-requirements.yml file and run the jx boot command again, jx tell me that unable to load jx-requirements.yml: jx-requirements.yml file not found.
What i can do ?

**Comment by deanesmith** [comment]
Hi @turbokernel, are you on Windows by any chance?  The error is similar to one that exists already.  https://github.com/jenkins-x/jx/issues/7035

**Comment by turbokernel** [comment]
> Hi @turbokernel, are you on Windows by any chance? The error is similar to one that exists already. #7035

no,my os is linux(centos)

**Comment by deanesmith** [comment]
Hi @turbokernel, I'd recommend starting with a local jx-requirements.yml file.  `jx boot -r my-jx-requirements.yml` with your specific configuration.

**Comment by deanesmith** [comment]
Hi @turbokernel, were you able to make any progress?
