### ISSUE TITLE
Remove RequirementsConfig#Terraform

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#7105]
jx-requirements.yml contains a Terraform flag which usage is not clear. See also https://github.com/jenkins-x/jx-docs/issues/1819.

We are not setting this flag when creating `jx-requirements.yml` in the Terraform modules and the only usage in code of this flag is around secret creation:

```go
func (c *RequirementsConfig) IsLazyCreateSecrets(flag string) (bool, error) {
	if flag != "" {
		if flag == "true" {
			return true, nil
		} else if flag == "false" {
			return false, nil
		} else {
			return false, util.InvalidOption("lazy-create", flag, []string{"true", "false"})
		}
	} else {
		// lets default from the requirements
		if !c.Terraform {
			return true, nil
		}
	}
	// default to false
	return false, nil
}
```

The flag might have been introduced for the SaaS where there is still a JX_REQUIREMENT_TERRAFORM environment variable passed to `jx boot`, but afaict this variable is never bound with `jx`. 

I think we should remove RequirementsConfig#Terraform altogether.

**Comment by garethjevans** [comment]
I wouldn't remove it, deprecation may be a better option.

**Comment by hferentschik** [comment]
> I wouldn't remove it, deprecation may be a better option.

We can investigate our options. I think removal is possible in a backwards-compatible way, but I am also fine with deprecation.
