### ISSUE TITLE
Environment Controller init contianers fails in jx step helm apply.  

### ISSUE THREAD

**Issue by karthickvelu90** [jenkins-x/jx#7106]
### Summary 
Deployment to remote cluster fails in environment controller init container build steps. 
This is not a new setup, previously deployment was working perfectly but all of sudden something breaks.  

<img width="1647" alt="Screenshot 2020-04-23 at 8 21 20 PM" src="https://user-images.githubusercontent.com/42056574/80113623-2ded2800-85a0-11ea-821d-c00fcdbe55d1.png">

### Expected behavior
Application deployment yaml gets updated and new image pods spins up. 

### Actual behavior
Github get updated with latest versions but kubernetes deployment isn't getting the update and new version is not spinning up.  

### Jx version

The output of `jx version` is:

```
karthickk:Manual Deployment karthickk$ jx --version
2.0.1275-dev+5e75321e4
```

### Jenkins type

- [ ] Classic Jenkins

### Operating system / Environment

**Helm version**

karthickk:Manual Deployment karthickk$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

**Environment controller init-container pod logs**

build-step-credential-initializer-rj25g {"level":"warn","ts":1586948444.849433,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata │
│  failed: \"ref: refs/heads/backport-container-name-fix\" is not a valid GitHub commit ID"}                                                                                          │
│ build-step-credential-initializer-rj25g {"level":"info","ts":1586948444.8507454,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}       │
│ build-step-git-source-jx-environment-environment-ctrl-6mc2t {"level":"warn","ts":1586948445.8446712,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub  │
│ commit ID from kodata failed: \"ref: refs/heads/backport-container-name-fix\" is not a valid GitHub commit ID"}                                                                     │
│ build-step-git-source-jx-environment-environment-ctrl-6mc2t {"level":"info","ts":1586948446.0583987,"logger":"fallback-logger","caller":"git-init/main.go:99","msg":"Successfully c │
│ loned \"https://git.devops.quickplay.com/jx-environment/environment-ctrl-plane-staging\" @ \"v0.0.507\" in path \"/workspace/source\""}                                             │
│ build-step-git-merge WARNING: no SHAs to merge, falling back to initial cloned commit                                                                                               │
│ build-step-setup-jx-git-credentials Generated Git credentials file /builder/home/git/credentials                                                                                    │
│ build-step-build-helm-apply Modified file /workspace/source/env/Chart.yaml to set the chart to version 538                                                                          │
│ build-step-build-helm-apply error: fail to acquire the lock: 0 pods found for this job (owner=jx-environment,repository=environment-ctrl-plane-staging,branch=master,build=538,jenk │
│ ins.io/pipelineType=build)                                                                                                                                                          │
│ build-step-build-helm-apply {"component":"entrypoint","error":"wrapped process failed: exit status 1","level":"error","msg":"Error executing test process","time":"2020-04-15T11:01 │
│ :17Z"}

**Below error displayed in jenkins logs :**

+ jx step helm apply

Modified file /home/jenkins/agent/workspace/irstlight-jx-cicd-staging_master/env/Chart.yaml to set the chart to version 11
WARNING: no REPO_OWNER provided
error: fail to acquire the lock: no REPO_OWNER provided
script returned exit code 1

**Comment by karthickvelu90** [comment]
Can someone help on this please. or whom can i connect to get it clarified.

**Comment by daveconde** [comment]
@karthickvelu90  This looks like a recent change to prevent concurrent pipeline runs for a release pipeline is causing an issue, I'll have a PR up shortly

**Comment by karthickvelu90** [comment]
First of all, Thanks a lot team for working on this. Highly appreciated. 
Will validate this PR changes and update this thread sooner.
