### ISSUE TITLE
JX Import --url fails

### ISSUE THREAD

**Issue by stephenlavery** [jenkins-x/jx#7107]
### Summary 

When I run jx import --url git@github.com:{repo path} I get the following error:

error: updating credentials "https://github.com" in Jenkins: creating credentials "https://github.com" in Jenkins: 308 Permanent Redirect.

I tried this on my existing version and then did upgrade also, error was different but behaviour was the same

### Steps to reproduce the behavior

Run jx import as above

### Expected behavior

Repo is imported in JX 

### Actual behavior

Error: updating credentials "https://github.com" in Jenkins: creating credentials "https://github.com" in Jenkins: 308 Permanent Redirect

I'm not even sure why updating the credentials is necessary as these are working correctly with our existing projects.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.1.8
jenkins x platform 2.0.2169
Kubernetes cluster v1.10.6
kubectl            v1.13.2
git                2.17.0
Operating System   Mac OS X 10.15.4 build 19E287

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by deanesmith** [comment]
Hi @stephenlavery, are you able to do it using an https URL?

**Comment by deanesmith** [comment]
Thanks @stephenlavery.  If there remains to be a problem please open a new issue as this one will no longer be monitored.
