### ISSUE TITLE
highlighting "stuff" is showing garbage rather than what the ascii escape sequence is supposed to be doing.

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#711]
The log entries at warnign level print with yellow, but other things that do not use the log but use `util.ColorInfo` produce garbage characters.

see example.
![image](https://user-images.githubusercontent.com/494726/39254148-56ad1644-48a1-11e8-87f5-d641f2df8bdf.png)

obviously windows releated.

```
C:\Users\jnord>jx version
NAME               VERSION
jx                 [32m1.2.20[0m
jenkins x platform [32m0.0.784[0m
kubernetes cluster [32mv1.8.8-gke.0[0m
kubectl            [32mv1.9.6[0m
helm client        [32mv2.7.2+g8478fb4[0m
helm server        [32mv2.7.2+g8478fb4[0m
git                [32mgit version 2.16.2.windows.1[0m
```

**Comment by darthcabs** [comment]
Colors should be able to be disabled in all platforms, not only Windows, be it through a global flag `--no-colours` or at least in batch mode. I'm trying to work out `jx` with `expect` to automate some loads, but because of the colours things get real ugly real quickly :(

**Comment by jtnord** [comment]
see https://github.com/fatih/color/issues/91

**Comment by agentgonzo** [comment]
I thought it would be a simple change from `os.Stdout` to `color.Output`, but alas that breaks the up/down in the selections for `survey` :-(

**Comment by martijnburger** [comment]
In Windows 10 (>build 1511) you can enable VT processing which solves this. Read the SO answers here: https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences

**Comment by jtnord** [comment]
@martijnburger I do not think it is as straight forward as that as you can see in the screenshot colours already work.  It is just when the colours are in the table output that they do not.  (and some other places which is a bug in jx).

![image](https://user-images.githubusercontent.com/494726/49370912-93135580-f6ed-11e8-9511-9e0daac77b16.png)

**Comment by martijnburger** [comment]
That's strange. For me it works:
![image](https://user-images.githubusercontent.com/6529303/49794904-f67a3480-fd38-11e8-9ccf-0759b71e1599.png)

**Comment by ccojocar** [comment]
@jtnord Is this still an issue? Can we close it? Thanks

**Comment by jtnord** [comment]
still an issue, in fact it almost seems to be getting worse as the logger used in the code is not possible to "colourize" correctly

**Comment by jtnord** [comment]
@martijnburger I would like to understand how it works for you.  we appear to have the same windows version and @agentgonzo sees the same when using `git-bash`.

I have tried without autorun enabled ([clink](https://github.com/mridgers/clink/) - so it is no that.
Do you have some local ansi driver installed (conemu etc?) (rather than the using `cmd.exe`'s built in ansi)?support)?

**Comment by martijnburger** [comment]
No special ansi drivers, just enable VT processing.

**Comment by jtnord** [comment]
@martijnburger thanks - that pushed me in the right direction, had not realised before now that the parts that where correctly coloured had been converted to specific windows calls before rendering and thus the remaining ones had not been converted and hence why they where not displaying correctly.

![image](https://user-images.githubusercontent.com/494726/54551519-2d01c400-49a6-11e9-9c8f-10d633acbf66.png)
