### ISSUE TITLE
install issues from jx

### ISSUE THREAD

**Issue by zzguang520** [jenkins-x/jx#7111]
### Summary 
An error was encountered during installation. The error message is as follows：
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'
### Steps to reproduce the behavior
run the command: jx install --provider kubernetes --on-premise
### Expected behavior
install successfully
### Actual behavior
 jx install --provider kubernetes --on-premise
Command "install" is deprecated, it will be removed on Jun 1 2020. We now highly recommend you use jx boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details.
? Configured Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Context "kubernetes-admin@kubernetes" modified.
Git configured for user: zzguang520 and email zzguang520@sina.com
Helm installed and configured
? No existing ingress controller found in the kube-system namespace, installing one: Yes

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: master.iocc-test.test.com
The Ingress address master.iocc-test.test.com is not an IP address. We recommend we try resolve it to a public IP address and use that for the domain to access services externally.
? Would you like wait and resolve this address to an IP address and use it for the domain? Yes

Waiting for master.iocc-test.test.com to be resolvable to an IP address...
master.iocc-test.test.com resolved to IP 192.168.160.58
You can now configure a wildcard DNS pointing to the new Load Balancer address 192.168.160.58
If you don't have a wildcard DNS setup then create a DNS (A) record and point it at: 192.168.160.58, then use the DNS domain in the next input...

If you do not have a custom domain setup yet, Ingress rules will be set for magic DNS nip.io.
Once you have a custom domain ready, you can update with the command jx upgrade ingress --cluster
? Domain 192.168.160.58.nip.io
nginx ingress controller installed and configured
Set up a Git username and API token to be able to perform CI/CD
? Do you wish to use zzguang520@sina.com as the local Git user for github.com server: Yes
Select the CI/CD pipelines Git server and user
? Do you wish to use github.com as the pipelines Git server: Yes
Setting the pipelines Git server https://github.com and user name zzguang520@sina.com.
? A local Jenkins X cloud environments repository already exists, recreating with latest: Yes
Enumerating objects: 1440, done.
Total 1440 (delta 0), reused 0 (delta 0), pack-reused 1440
Updating Secret jx-install-config in namespace jx
? Defaulting workload build pack: Kubernetes Workloads: Automated CI+CD with GitOps Promotion
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
Installing jx into namespace jx
Installing jenkins-x-platform version: 2.0.2171
error: installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'kubectl apply --recursive -f /tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx -l jenkins.io/chart-release=jenkins-x --namespace jx --validate=false' command in directory '', output: 'persistentvolumeclaim/jenkins-x-chartmuseum unchanged
secret/jenkins-x-chartmuseum configured
service/jenkins-x-chartmuseum unchanged
role.rbac.authorization.k8s.io/cleanup unchanged
rolebinding.rbac.authorization.k8s.io/cleanup unchanged
serviceaccount/cleanup unchanged
clusterrole.rbac.authorization.k8s.io/controllerrole-jx unchanged
clusterrolebinding.rbac.authorization.k8s.io/controllerrole-jx unchanged
deployment.apps/jenkins-x-controllerrole unchanged
release.jenkins.io/controllerrole-2.1.10 configured
role.rbac.authorization.k8s.io/controllerrole unchanged
rolebinding.rbac.authorization.k8s.io/controllerrole unchanged
serviceaccount/jenkins-x-controllerrole unchanged
configmap/jenkins-x-docker-registry-config unchanged
persistentvolumeclaim/jenkins-x-docker-registry unchanged
secret/jenkins-x-docker-registry-secret configured
service/jenkins-x-docker-registry unchanged
configmap/exposecontroller unchanged
role.rbac.authorization.k8s.io/expose unchanged
rolebinding.rbac.authorization.k8s.io/expose unchanged
serviceaccount/expose unchanged
clusterrole.rbac.authorization.k8s.io/gcactivities-jx unchanged
clusterrolebinding.rbac.authorization.k8s.io/gcactivities-jx unchanged
cronjob.batch/jenkins-x-gcactivities unchanged
release.jenkins.io/gcactivities-2.1.10 configured
role.rbac.authorization.k8s.io/gcactivities unchanged
rolebinding.rbac.authorization.k8s.io/gcactivities unchanged
serviceaccount/jenkins-x-gcactivities unchanged
cronjob.batch/jenkins-x-gcpods unchanged
release.jenkins.io/gcpods-2.1.10 configured
role.rbac.authorization.k8s.io/gcpods unchanged
rolebinding.rbac.authorization.k8s.io/gcpods unchanged
serviceaccount/jenkins-x-gcpods unchanged
clusterrole.rbac.authorization.k8s.io/gcpreviews-jx unchanged
clusterrolebinding.rbac.authorization.k8s.io/gcpreviews-jx unchanged
cronjob.batch/jenkins-x-gcpreviews unchanged
release.jenkins.io/gcpreviews-2.1.10 configured
role.rbac.authorization.k8s.io/gcpreviews unchanged
rolebinding.rbac.authorization.k8s.io/gcpreviews unchanged
serviceaccount/jenkins-x-gcpreviews unchanged
clusterrolebinding.rbac.authorization.k8s.io/jenkins-x-heapster unchanged
role.rbac.authorization.k8s.io/jenkins-x-heapster-pod-nanny unchanged
rolebinding.rbac.authorization.k8s.io/jenkins-x-heapster-pod-nanny unchanged
service/heapster unchanged
serviceaccount/jenkins-x-heapster unchanged
configmap/jenkins unchanged
persistentvolumeclaim/jenkins unchanged
service/jenkins-agent unchanged
service/jenkins unchanged
configmap/jenkins-x-git-kinds unchanged
configmap/jenkins-pod-xml-dlang unchanged
clusterrolebinding.rbac.authorization.k8s.io/jenkins-jx-role-binding unchanged
secret/jenkins configured
serviceaccount/jenkins unchanged
configmap/jenkins-tests unchanged
configmap/jenkins-pod-xml-dotnet unchanged
configmap/jenkins-pod-xml-maven-nodejs unchanged
configmap/jenkins-pod-xml-python37 unchanged
configmap/jenkins-pod-xml-maven unchanged
configmap/jenkins-pod-xml-promote unchanged
configmap/jenkins-pod-xml-php5x unchanged
configmap/jenkins-pod-xml-jx-base unchanged
configmap/jenkins-pod-xml-nodejs12x unchanged
configmap/jenkins-pod-xml-swift unchanged
configmap/jenkins-pod-xml-newman unchanged
configmap/jenkins-pod-xml-ruby unchanged
configmap/jenkins-pod-xml-maven-graalvm unchanged
configmap/jenkins-pod-xml-python unchanged
configmap/jenkins-pod-xml-php7x unchanged
configmap/jenkins-pod-xml-go unchanged
configmap/jenkins-pod-xml-machine-learning unchanged
configmap/jenkins-pod-xml-nodejs8x unchanged
configmap/jenkins-pod-xml-terraform unchanged
configmap/jenkins-pod-xml-nodejs unchanged
configmap/jenkins-pod-xml-rust unchanged
configmap/jenkins-pod-xml-maven-java11 unchanged
configmap/jenkins-pod-xml-python2 unchanged
configmap/jenkins-pod-xml-machine-learning-gpu unchanged
configmap/jenkins-pod-xml-packer unchanged
configmap/jenkins-pod-xml-aws-cdk unchanged
configmap/jenkins-pod-xml-gradle unchanged
configmap/jenkins-pod-xml-nodejs10x unchanged
configmap/jenkins-pod-xml-scala unchanged
configmap/nexus unchanged
deployment.apps/jenkins-x-nexus configured
persistentvolumeclaim/jenkins-x-nexus unchanged
secret/nexus configured
service/nexus unchanged
role.rbac.authorization.k8s.io/committer unchanged
secret/jenkins-docker-cfg unchanged
configmap/jenkins-x-devpod-config unchanged
configmap/jenkins-x-docker-registry configured
configmap/jenkins-x-extensions unchanged
configmap/jenkins-x-pod-template-dlang unchanged
secret/jx-basic-auth configured
role.rbac.authorization.k8s.io/jx-view unchanged
secret/jenkins-maven-settings configured
secret/jenkins-npm-token unchanged
role.rbac.authorization.k8s.io/owner unchanged
secret/jenkins-release-gpg unchanged
secret/jenkins-ssh-config unchanged
role.rbac.authorization.k8s.io/viewer unchanged
configmap/jenkins-x-pod-template-dotnet unchanged
configmap/jenkins-x-pod-template-maven-nodejs unchanged
configmap/jenkins-x-pod-template-python37 unchanged
configmap/jenkins-x-pod-template-maven unchanged
configmap/jenkins-x-pod-template-promote unchanged
configmap/jenkins-x-pod-template-php5x unchanged
configmap/jenkins-x-pod-template-jx-base unchanged
configmap/jenkins-x-pod-template-nodejs12x unchanged
configmap/jenkins-x-pod-template-swift unchanged
configmap/jenkins-x-pod-template-newman unchanged
configmap/jenkins-x-pod-template-ruby unchanged
configmap/jenkins-x-pod-template-maven-graalvm unchanged
configmap/jenkins-x-pod-template-python unchanged
configmap/jenkins-x-pod-template-php7x unchanged
configmap/jenkins-x-pod-template-go unchanged
configmap/jenkins-x-pod-template-machine-learning unchanged
configmap/jenkins-x-pod-template-nodejs8x unchanged
configmap/jenkins-x-pod-template-terraform unchanged
configmap/jenkins-x-pod-template-nodejs unchanged
configmap/jenkins-x-pod-template-rust unchanged
configmap/jenkins-x-pod-template-maven-java11 unchanged
configmap/jenkins-x-pod-template-python2 unchanged
configmap/jenkins-x-pod-template-machine-learning-gpu unchanged
configmap/jenkins-x-pod-template-packer unchanged
configmap/jenkins-x-pod-template-aws-cdk unchanged
configmap/jenkins-x-pod-template-gradle unchanged
configmap/jenkins-x-pod-template-nodejs10x unchanged
configmap/jenkins-x-pod-template-scala unchanged
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/docker-registry/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-524069734/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'
### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 2.1.10
jenkins x platform 2.0.2171
Kubernetes cluster v1.18.1
kubectl            v1.16.9
helm client        2.16.6
git                2.18.4
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"

verifying packages

### Jenkins type

- [- ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Kubernetes Cloud, Set up k8s cluster environment independently
### Operating system / Environment

linux redhat7.7

**Comment by zzguang520** [comment]
I have try to used jx boot to install,but show other issues:
command:  jx boot —provider=kubernetes
Creating boot config with defaults, as not in an existing boot directory with a git repository.
No Jenkins X pipeline file jenkins-x.yml or no jx boot requirements file jx-requirements.yml found. You are not running this command from inside a Jenkins X Boot git clone
To continue we will clone https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
? Do you want to clone the Jenkins X Boot Git repository? Yes

Cloning https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
fetching branch master
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config.git from https://github.com/jenkins-x/jenkins-x-versions.git
Current HEAD v1.0.84 in /root/jenkins-x-boot-config is not an ancestor of v1.0.83, the boot config version from the version stream.
Proceeding with current HEAD.
Booting Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /root/jenkins-x-boot-config/env

Git configured for user: zzguang520 and email zzguang520@sina.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /root/jenkins-x-boot-config

error: : unable to parse kubernetes as <project id>_<zone>_<cluster name>
error: failed to interpret pipeline file /root/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '/root/jenkins-x-boot-config', output: ''

**Comment by deanesmith** [comment]
Hi @zzguang520, we cannot comfortably support v1.18.1 of Kubernetes right now.  We expect that is the cause of your issue.

**Comment by zzguang520** [comment]
> Hi @zzguang520, we cannot comfortably support v1.18.1 of Kubernetes right now. We expect that is the cause of your issue.

Thanks @deanesmit, I can reduce the version of k8s to avoid this error. But the other question I want to ask you is what version of k8s and helm  is required for the most stable jx release today.

**Comment by deanesmith** [comment]
@zzguang520, 1.14 should be ok.

**Comment by 2020testuser** [comment]
@zzguang520 - If  you got jenkinsx working on on-prem kubernetes , could you please share your jx-requirements.yml (with host,id etc. using dummy text)? I'm unable to get it installed successfully. Thanks!
