### ISSUE TITLE
Nexus chart can't upgrade via `jx upgrade boot` due to using the same PVC

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#7115]
If you upgrade the Nexus chart, it...well, doesn't work, because the old and new deployments both try to mount the same PVC. Since the old deployment won't go away until the new one is online, and the new one can't come online until it can mount the PVC the old one has mounted, it'll never actually upgrade.

**Comment by babadofar** [comment]
While you are looking at Nexus -  can you verify if it is possible to change the nexus configuration somehow? I've been struggling with this for a while: https://github.com/jenkins-x/jx/issues/6348
