### ISSUE TITLE
Move nexus and chartmuseum requirements from jenkins-x-platform to jenkins-x-boot-config (and version stream)

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#7123]
The nexus and chartmuseum charts are handled a bit weird - they're explicitly specified in `jenkins-x-platform`'s `requirements.yaml`, while almost everything else third-party-ish (the most noteworthy exceptions are the legacy docker registry chart and the heapster chart) has a version specified in `jenkins-x-versions` and is in `jenkins-x-boot-config`'s `requirements.yaml`. As a result of this setup, it's basically impossible to test changes to the nexus or chartmuseum charts until they're already released and going into `jenkins-x-platform`. This means that we end up having to make changes to the nexus chart, merge, watch `jenkins-x-platform` get updated, and then wait until the next `jenkins-x-versions` update to see if it actually works. This is bad.

If we move these charts to instead have their versions managed through `jenkins-x-versions` and be in `jenkins-x-boot-config`'s `requirements.yaml`, we can do BDD tests against nexus/chartmuseum chart PRs like we do with the Tekton chart.

**Comment by deanesmith** [comment]
Once this is completed, I'd like to propose "bring-your-own-nexus" is fully supported/documented.  I see now where Nexus is needed for some quickstarts, but doesn't necessarily reflect enterprise working environments.
