### ISSUE TITLE
Creating a new environment via jx-boot not working

### ISSUE THREAD

**Issue by majuansari** [jenkins-x/jx#7134]
### Summary 
I tried the method here for creating a new env https://jenkins-x.io/docs/faq/boot/#how-do-i-add-new-environments. But it's not triggering the release pipeline and not creating the application pods.
### Steps to reproduce the behavior
https://jenkins-x.io/docs/faq/boot/#how-do-i-add-new-environments
kubectl get env staging -oyaml > env/templates/myenv.yaml
kubectl get sr XXX -oyaml > env/templates/myenv-sr.yaml
### Expected behavior
Environments need to be created and release pipelines should work (just like when we use jx create env)
### Actual behavior
Envrionments are getting created, but it's not triggering the release pipeline and not creating the application pods.
### Jx version

The output of `jx version` is:

```
jx                 2.0.1286
Kubernetes cluster v1.15.10
kubectl            v1.13.2
helm client        2.14.3
git                2.15.1
Operating System   Mac OS X 10.14 build 18A391```

### Kubernetes cluster
<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->
AKS - 1.15. Created via jx-boot

**Comment by garethjevans** [comment]
Hi, How are you promoting applications to these new environments?

**Comment by majuansari** [comment]
Promotion is automatic

**Comment by hferentschik** [comment]
Can you provide some more context? What kind of cluster are you using? On which cloud provider? Can you give us steps to reproduce the issue?

**Comment by majuansari** [comment]
@hferentschik I am on AKS. 2 nodes basic freebie cluster. 

I was able to reproduce the issue with the following steps only with a fresh aks cluster

> https://jenkins-x.io/docs/faq/boot/#how-do-i-add-new-environments
> kubectl get env staging -oyaml > env/templates/myenv.yaml
> kubectl get sr XXX -oyaml > env/templates/myenv-sr.yaml
