### ISSUE TITLE
Can't use ACR with Kaniko

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/jx#7135]
### Summary 

Can't use ACR with Kaniko, using acr credential helper (the default)
The ACR Docker credential helper writes a file to `.docker/acr`, in jx it is `/home/jenkins/.docker/acr` but because `/home/jenkins/.docker` is the `volume-0` mount it does not have permission to write there.
The secret should only mount `/home/jenkins/.docker/config.json` and not the whole dir

Requires https://github.com/jenkins-x/jenkins-x-boot-config/pull/153

### Steps to reproduce the behavior

Create a new quickstart in AKS with kaniko enabled

### Actual behavior

```
Error creating credential store helper: Failed to create secondary file store dir /home/jenkins/.docker/acr
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "**rocks.azurecr.io/********/**-golang:0.0.2": resolving authorization for **rocks.azurecr.io failed: error getting credentials - err: exit status 1, out: ``
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.20
Kubernetes cluster v1.15.10
kubectl            v1.16.3
helm client        2.13.1
git                2.26.2
Operating System   Mac OS X 10.15.4 build 19E287
```

### Kubernetes cluster

AKS

### Operating system / Environment

OSX

**Comment by chrismellard** [comment]
@carlossg  Just taking a look at this now. Having looked at what the `acr-docker-credential-helper` is up to I don't fully understand your comment 

> The secret should only mount `/home/jenkins/.docker/config.json` and not the whole dir

The credential helper appears to always attempt to work with a directory, either by creating one if it doesn't exist or if a file entry does exist at that mount point it tests it for it being a directory in order to move forward successfully... Snippets of the helper code here

```
configdir := filepath.Dir(config.Filename)
secondarydir := filepath.Join(configdir, "acr")
var fileInfo os.FileInfo
var secondaryConfig *configfile.ConfigFile
if fileInfo, err = os.Stat(secondarydir); err != nil {
	if os.IsNotExist(err) {
		err = os.Mkdir(secondarydir, 0777)
		if err != nil {
			return nil, fmt.Errorf("Failed to create secondary file store dir %s", secondarydir)
		}
		secondaryConfig = getEmptyConfig(secondarydir)
	} else {
		return nil, fmt.Errorf("Failed to stat dir %s", secondarydir)
	}
} else {
	if !fileInfo.IsDir() {
		return nil, fmt.Errorf("Failed to create secondary file store dir %s, a file already exist in its location", secondarydir)
	}
	secondaryConfig, err = cliconfig.Load(secondarydir)
	if err != nil {
		_, statError := os.Stat(filepath.Join(secondarydir, "config.json"))
		if os.IsNotExist(statError) {
			secondaryConfig = getEmptyConfig(secondarydir)
		} else {
			return nil, fmt.Errorf("Failed to load existing config from %s, error: %s", secondarydir, err)
		}
	}
}
```

I don't have the answer yet but I'm just checking my understanding as I'm pretty new to the codebase

**Comment by carlossg** [comment]
jx is mounting the kaniko secret under `/home/jenkins/.docker`, that means the whole directory is read only

the ACR credential helper tries to write to `/home/jenkins/.docker/acr` and fails because it is read only.

jx should just mount the secret in `/home/jenkins/.docker/config.json` and not in `/home/jenkins/.docker`

**Comment by chrismellard** [comment]
But looking at the acr helper above doesn't that just mean this line of code gets hit and it throws an error?

```	
if !fileInfo.IsDir() {
	return nil, fmt.Errorf("Failed to create secondary file store dir %s, a file already exist in its location", secondarydir)
}
```

**Comment by chrismellard** [comment]
Anyway. I'll try the fix you suggest and stop debugging by eyeballing the code ;)

**Comment by chrismellard** [comment]
The penny finally dropped. Folder becomes writeable if you're only mounting the file inside pod. d'oh.
