### ISSUE TITLE
jx boot wait for vault to be initialized and unsealed error

### ISSUE THREAD

**Issue by pancudaniel7** [jenkins-x/jx#7140]
### Summary 
run jx boot with jx-requirements.yaml after terraform apply finished without error on gks cluster and I receive:
`error: creating system vault URL client: wait for vault to be initialized and unsealed: reading vault health: Get https://vault-jx.codesquad-x.com/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup vault-jx.codesquad-x.com on 192.168.1.1:53: no such host`
### Expected behavior
jx boot finish without errors
### Actual behavior
I get:
`error: creating system vault URL client: wait for vault to be initialized and unsealed: reading vault health: Get https://vault-jx.codesquad-x.com/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup vault-jx.codesquad-x.com on 192.168.1.1:53: no such host`
### Jx version
2.1.20
The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.20
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.5
git                2.24.1
Operating System   Mac OS X 10.14.6 build 18G3020
```

**Comment by deanesmith** [comment]
Hi @pancudaniel7, it would seem there is a local DNS issue maybe?  Are you indeed deploying a cluster on GKE?

**Comment by daveconde** [comment]
@pancudaniel7 Did you get passed this issue?

**Comment by andrewhoplife** [comment]
I have this issue with https://github.com/jenkins-x/terraform-aws-eks-jx using a hosted route 53 zone. The apex domain seems fine but the subdomain zone does not resolve as it should and I am unclear on what troubleshooting steps should occur.

**Comment by pancudaniel7** [comment]
@daveconde @andrewhoplife Guys for me this was a dns problem comming from the Domain provider not from cloud provider. After I've discussed with the support team from the Domain provider they fixed my problem. So yea as @deanesmith said it was a DNS problem.

**Comment by deanesmith** [comment]
Thank you for the follow-up @pancudaniel7.  Would you mind closing this issue then?

**Comment by andrewhoplife** [comment]
Getting this error:

```
Using eth0 for VAULT_CLUSTER_ADDR: https://10.0.2.188:8201
telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
Error initializing storage of type dynamodb: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: V895OFUGCG1LCJ63EH31EM7T0JVV4KQNSO5AEMVJF66Q9ASUAAJG
```

**Comment by deanesmith** [comment]
Hi @andrewhoplife, it appears this is a different matter you're experiencing and I recommend opening a new issue.  Have you seen these similar issues? https://github.com/hashicorp/vault/issues/5965
https://github.com/hashicorp/vault/issues/5045

**Comment by cristi-vlad** [comment]
> happening to me too when running terraform-aws-eks-jx. Getting this error:



> This issue is happening to me too when running terraform-aws-eks-jx. Getting this error:
> 
> `kubectl logs jx-vault-jx-0 -c vault `
> 
> ```
> Using eth0 for VAULT_CLUSTER_ADDR: https://10.0.2.188:8201
> telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
> Error initializing storage of type dynamodb: UnrecognizedClientException: The security token included in the request is invalid.
> 	status code: 400, request id: V895OFUGCG1LCJ63EH31EM7T0JVV4KQNSO5AEMVJF66Q9ASUAAJG
> ```

I have same issue. Have you found a way to solve it ?
