### ISSUE TITLE
Create MLOps Quickstart BDD Test

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#7151]
### Summary 
Expand Jenkins X BDD test coverage to include an mlquickstart as surfaced by `jx create mlquickstart`.  Verify that it is possible to successfully create, build, and deploy an mlquickstart application.  The desired level of testing should be basic and on par with other quickstart BDD tests but it is not required to run on every single build.

The preferred quickstart for the test is to select any CPU quickstart from here - https://github.com/machine-learning-quickstarts.  

For questions or additional guidance consult with @tdcox.

**Comment by abayer** [comment]
How do we verify this? The same kind of flow we have for other BDD tests (create quickstart, master build succeeds, promote to staging, create a PR, verify a preview exists, promote to production)? How do we verify that the promotions have worked? That all is what I'm not clear on.

cc @tdcox

**Comment by tdcox** [comment]
The -training project doesn’t release anything but if it succeeds, it will create a PR on the -service project to add the model it trained. You then need to LGTM that PR and verify the successful rerelease of the -service project in the normal way.

**Comment by tdcox** [comment]
Run one manually and `jx get build logs` on both builds. You will see what happens.

**Comment by abayer** [comment]
Any chance you can give me a step-by-step list of what should be done in the test and what we should be checking along the way?

**Comment by tdcox** [comment]
It’s just two normal quickstarts running in parallel but one makes a PR on the other and terminates without creating an image. Should be clear from the pipeline in the buildpacks.

**Comment by abayer** [comment]
Ok...so what's the interaction when running in parallel? We don't do any testing of concurrent quickstarts currently, so I need to figure out how to fit that in. What's the exact order of creating the quickstarts? Is there any documentation? I really do need a step-by-step guide to get this going.

**Comment by michaelneale** [comment]
https://jenkins-x.io/docs/guides/mlops/mlquickstarting/

**Comment by michaelneale** [comment]
OK some notes: 

* Current quickstarts are tested via the BDD suite <a href="https://github.com/jenkins-x/bdd-jx/blob/master/Readme.md">here</a>
* quickstart specific helper code is <a href="https://github.com/jenkins-x/bdd-jx/blob/master/test/suite/quickstart/helpers.go#L52">here</a>
* The supported quickstarts are mentioned by name <a href="https://github.com/jenkins-x/bdd-jx/blob/8a9fc07b94d0b8ca4441fa6a9975b6c5e515d1c6/Makefile#L71">here</a>.
* the JX quickstart repos are in this github org: https://github.com/jenkins-x-quickstarts

ML quickstarts however use a separate mechanism. You can read how they work here: 
https://jenkins-x.io/docs/resources/guides/mlops/mlquickstarting/

Basically: 
* 2 pipelines created
* 2 repos imported/projects
* 1 project is the "service" that responds to HTTP requests (this is closer to a normal quickstart)
* The other project  "trains" the model. It does not produce an image, but instead produces a binary "model", which is then provided to the "service" project as a pull request to its repo (so you can change data, change the training, hyper parameters etc, and it will trigger a new training run and you get previews etc). 

So very similar to a classical quickstart, but there are 2 repos, 2 pipelines, and 1 of them serves http (a service/training pair, always). 

So it could be tested in a similar fashion, run the ml-quickstart just like a normal one, but expect 2 pipelines, 2 repos, and wait for one http service to respond successfully (it will take longer usually, as the service will come up with no model provided, and training can take some time, before the service is redeployed with a model running and working end to end). 

Perhaps the quickstart suite stuff above should be extended for the ml-quickstart command?

An example ML quickstart training repo is here: https://github.com/machine-learning-quickstarts/ML-python-sklearn-rfc-cpu-training - with the magic in the ML buildpack.
