### ISSUE TITLE
jx version git fetch error

### ISSUE THREAD

**Issue by pancudaniel7** [jenkins-x/jx#7152]
### Summary 
jx version command run gives git fetching error

### Steps to reproduce the behavior
Run: `jx version`

### Expected behavior
Display versions content
```
NAME               VERSION
jx                 2.1.13+cjxd.9
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.5
helm client        2.16.6
git                2.24.1
Operating System   Mac OS X 10.14.6 build 18G3020
```

### Actual behavior
**Git fetch error display under versions content**
### Jx version
```
NAME               VERSION
jx                 2.1.13+cjxd.9
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.5
helm client        2.16.6
git                2.24.1
Operating System   Mac OS X 10.14.6 build 18G3020


verifying packages
error: : failed to git fetch origin v1.0.444 for repo: https://github.com/cloudbees/cloudbees-jenkins-x-versions.git in dir /Users/pancudaniel/.jx/jenkins-x-versions: failed to run 'git fetch origin v1.0.444' command in directory '/Users/pancudaniel/.jx/jenkins-x-versions', output: 'fatal: couldn't find remote ref v1.0.444'
```

### Kubernetes cluster
Kubernetes cluster was created using jx google terraform 
and jx boot -r [jx-requirements.yml generated by terraform process]

### Operating system / Environment

osx -> Darwin Kernel Version 18.7.0

**Comment by deanesmith** [comment]
Hi @pancudaniel7, we don't have a good explanation but it appears you may be using upstream jx and maybe switched to CJXD (or vice versa).  Recommended to blow away contents of the .jx directory.  Clean out your local working directory and give it another shot.  Ensure which one you're using and that the versions reference is correct.

**Comment by pancudaniel7** [comment]
Thanks @deanesmith I will try again to clean everything and install again
