### ISSUE TITLE
Enable to skip availability check for `jx preview`

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#7155]
### Summary 

When running `jx preview`, `jx` would try to find the service or ingress and try it with an HTTP request. There is currently no way to configure this behavior (see #7112). If the request keeps failing, `jx preview` would fail. It could fail if the service doesn't reply correctly to `GET /` request, or if the service is not HTTP.

Adding a `--skip-availability-check` flag would at least prevent this behavior

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1243
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.17.0
helm client        2.14.3
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Comments

As @hferentschik underlined it, this is in general a problem with what preview should be used to.

**Comment by deanesmith** [comment]
Closing, pull request merged.
