### ISSUE TITLE
Remove content irrelevant to user when setting up initial  jenkins-x-boot-config

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#7157]
When creating the _jenkins-x-boot-config_ for booting a cluster, we are forking https://github.com/jenkins-x/jenkins-x-boot-config. This repository contains content which is irrelevant to the function of the boot config for the newly created cluster. This is confusing to the user and clutters the repository. 

Content which should not be included:

- _bdd_ directory
- .pre-commit-config.yaml
- .secrets.baseline
- clearcluster.sh
- jenkins-x-bdd-*.yml
- jenkins-x-release.yml

_prowConfig_ can probably be deleted now as well (even in the upstream repo itself)

**Comment by deanesmith** [comment]
PR https://github.com/jenkins-x/jenkins-x-boot-config/pull/159 will create issues with the Jenkins-X build process and upgrades.  Discussing in triage, it may be a better to filter items?  Fork and pull process is overall problematic and over complicated.  Please hold.

**Comment by hferentschik** [comment]
Added a comment on the PR - https://github.com/jenkins-x/jenkins-x-boot-config/pull/159#issuecomment-628827757

For reference, here is my current thinking on how this could be addressed:

> there should be a method like "cleanBddFiles" (or something like that) to add after the "writeOwnersFile" one (or somewhere in the jx boot procedure), that's what you mean?

yeah some sort of function is needed in jx, maybe not cleanBddFiles since they are not all BDD related. Most of them, but not all. Maybe cleanRepo or filterRepo. The question is not so much how this particular function is called, but how it works. The most simplistic way would be to hard code the files and directories to delete in jx, but that seems not very flexible. Maybe we need some special ignore file in this repo which lists the files and directories we need to exclude when we fork and prepare the new environment directory. Within jx we would be looking for this file, delete all matches and the file itself. At least that's my current thinking around that. Any better ideas?

**Comment by hferentschik** [comment]
`.forkIgnore` comes to mind as a name.
