### ISSUE TITLE
Imported project always got '503 Service Temporarily Unavailable' error after building

### ISSUE THREAD

**Issue by wangzhenzhe** [jenkins-x/jx#7183]
### Summary 
I installed Jenkins-X on a newly created cluster on EKS. Then I imported an existing Java Spring Boot project from Github.com. That was created from Jenkins-X command line 'jx create project' before and it worked well before.
Everything seemed going well until the building pipeline completed. I always got '503 Service Temporarily Unavailable' error. I checked the application with 'jx get application', it existed but the 'PODS' field showed nothing. And I could not find any clue from 'kubectl get pod'
I also tried to create a new project from the newly created JeninsX, it worked.

### Steps to reproduce the behavior
Install Jenkins-X on a newly created cluster and import an existing Java Spring Boot project.
After building pipeline completed, check the application url.

### Expected behavior
The imported project worked as before and the application is available for viewing after pipeline completed.

### Actual behavior
The imported project was not available for viewing after building pipeline completed.

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 2.1.35
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS

### Kubernetes cluster
AWS EKS
Created from terraform and install jx with 'jx boot'
The content of main.tf was as below
module "eks-jx" {
  source  = "jenkins-x/eks-jx/aws"
  vault_user= "jx-vault-user"
  region  = "ap-northeast-1"
  node_machine_type = "t3a.medium"
}

### Operating system / Environment
Ubuntu 18.04.4 LTS

**Comment by deanesmith** [comment]
Hi @wangzhenzhe, without knowing which service was an issue it is tough to understand the problem.  Do you have logs?

**Comment by wangzhenzhe** [comment]
> Hi @wangzhenzhe, without knowing which service was an issue it is tough to understand the problem. Do you have logs?

Thank you for your replying. What log will you want to take a log?
I am sorry that I had not enabled the log groups for EKS. So if you mean EKS logs, I do not have it.
I have the logs of jx building pipeline. I attached the latest building logs.
[4.txt](https://github.com/jenkins-x/jx/files/4628340/4.txt)

If you mean some other logs, please give me some instructions to collect it. Thanks.

By the way, I tried to remove the project with 'jx delete application' and import it again. It looked still having this problem.

**Comment by wangzhenzhe** [comment]
I had just start another build. Here is the latest pipeline log of staging env.
[1 (2).txt](https://github.com/jenkins-x/jx/files/4628467/1.2.txt)

**Comment by wangzhenzhe** [comment]
I found another issue might have relation with this.
When I use 'jx get application', the two application will all be shown on screen. The 'hellospringx' was the imported one that has problem and it showed empty under PODS field. The 'helljenkinsx' was a new project created from the newly installed jx. It had no problem.

ubuntu@ip-172-31-33-118:~$ jx get application
APPLICATION   STAGING PODS URL                                                  PRODUCTION PODS URL
hellojenkinsx 0.0.6   1/1  http://hellojenkinsx-jx-staging.18.181.41.205.nip.io 0.0.6      1/1  http://hellojenkinsx-jx-production.18.181.41.205.nip.io
hellospringx  0.0.13       http://hellospringx-jx-staging.18.181.41.205.nip.io  0.0.11          http://hellospringx-jx-production.18.181.41.205.nip.io

But when I try to delete the application using 'jx delete application', only the imported 'hellospringx' was shown as choice and I also could remove it by 'jx delete application HelloSpringX'.

ubuntu@ip-172-31-33-118:~$ jx delete application
? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter]
> [x]  wangzhenzhe/HelloSpringX
error: deleting application: interrupt
ubuntu@ip-172-31-33-118:~$ jx delete application HelloSpringX
regenerated Prow configuration
Removing application HelloSpringX from environment Staging
WARNING: No changes made to the source code in /tmp/create-pr326143408. Code must be up to date!
Removing application HelloSpringX from environment Production
WARNING: No changes made to the source code in /tmp/create-pr262826831. Code must be up to date!
Deleted Application(s): HelloSpringX
ubuntu@ip-172-31-33-118:~$ jx delete application HelloSpringX
error: deleting application: There are no Applications in Jenkins

Then I type 'jx delete application' again, the jx reported error and said there are no Applications in Jenkins. But the 'jx get application' will report the correct result and the newly created project 'hellojenkinsx' is still active.

ubuntu@ip-172-31-33-118:~$ jx delete application
error: deleting application: There are no Applications in Jenkins
ubuntu@ip-172-31-33-118:~$ jx get application
APPLICATION   STAGING PODS URL                                                  PRODUCTION PODS URL
hellojenkinsx 0.0.6   1/1  http://hellojenkinsx-jx-staging.18.181.41.205.nip.io 0.0.6      1/1  http://hellojenkinsx-jx-production.18.181.41.205.nip.io

It seemed the application in JX do not have correct state. Does it concern with the 'No POD ready' problem. Thanks.

**Comment by wangzhenzhe** [comment]
@deanesmith 
Here is my staging pod yaml output. I am not sure if this was the log could help. Thanks.
[staging-pod.yaml.txt](https://github.com/jenkins-x/jx/files/4631670/staging-pod.yaml.txt)
