### ISSUE TITLE
Example boxes in the documentation are unreadable

### ISSUE THREAD

**Issue by ascotti-beyond** [jenkins-x/jx#7186]
### Summary 
Example boxes in the documentation are unreadable

### Steps to reproduce the behavior
Open a page that contains an example, for example:
https://jenkins-x.io/docs/reference/components/pod-templates/

Go to the section "Referring to Pod Templates".

Check the boxed example.

### Expected behavior

The text in the example box should be readable.

### Actual behavior

The text in the example box is not readable because it contains very light text on a white background.

![Screen Shot 2020-05-14 at 16 05 40](https://user-images.githubusercontent.com/63477740/81944282-d40adb80-95fc-11ea-912d-67b77d835d61.png)

### Jx version

N/A

### Kubernetes cluster

N/A

### Operating system / Environment

Tested on Mac OS X with Chrome, Safari and Firefox.

**Comment by hervelemeur** [comment]
I suggest you to reopen this issue here: https://github.com/jenkins-x/jx-docs

**Comment by ascottix** [comment]
Ok, will do. Thanks!
