### ISSUE TITLE
Metapipeline environment variables (http_proxy)

### ISSUE THREAD

**Issue by deas** [jenkins-x/jx#7194]
### Summary
Metapipeline execution fails (`connect timeout`) for me because I am forced to access the internet through a proxy:

```
Showing logs for build meta-steffanand-jx-golang-sampl-4rsvj-1 stage meta-pipeline and container step-create-effective-pipeline
WARNING: failed to discover alpha commands from github: failed to get YAML from https://raw.githubusercontent.com/jenkins-x-labs/**l/master/alpha/plugins.yml: Get https://raw.githubusercontent.com/jenkins-x-labs/**l/master/alpha/plugins.yml: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: : failed to clone repository: https://github.com/jenkins-x/jenkins-x-versions.git to dir /builder/home/.**/jenkins-x-versions: failed to fetch master from https://github.com/jenkins-x/jenkins-x-versions.git in directory /builder/home/.**/jenkins-x-versions: git output: fatal: unable to access 'https://github.com/jenkins-x/jenkins-x-versions.git/': Failed connect to github.com:443; Connection timed out: failed to run 'git fetch origin master' command in directory '/builder/home/.**/jenkins-x-versions', output: 'fatal: unable to access 'https://github.com/jenkins-x/jenkins-x-versions.git/': Failed connect to github.com:443; Connection timed out'

Pipeline failed on stage 'meta-pipeline' : container 'step-create-effective-pipeline'. The execution of the pipeline has stopped.
```

I assume that setting the usual proxy environment suspects would solve this problem. However, I did not find a way to do this for the metapipeline.

### Steps to reproduce the behavior
`jx import ...`

### Expected behavior
Metapipeline execution succeeding

### Actual behavior
Metapipeline execution fails

### Jx version
```
2.1.14
```

### Kubernetes cluster
n/a

### Operating system / Environment
n/a

**Comment by deas** [comment]
@abayer @daveconde Been checking the code a bit and was wondering about how to implement this. I might want to try and fix this properly. Can we have a quick chat on Slack?

If we expect a proper implementation to take long, I would also be fine with some sort of quick hack in the meantime. Was considering `PodPreset`, but unfortunately, this is not available on our environment. Appreciating suggestions here.

**Comment by pow-devops2020** [comment]
Following. Was also thinking about PodPreset to add proxy to pods created by tekton, but failed due to its alpha version not being supported by eks.
