### ISSUE TITLE
Installing Jenkins-X in an on-prem environment

### ISSUE THREAD

**Issue by ofekinger** [jenkins-x/jx#7196]
I heard about this project recently and I'm ready to implement it in my environment, but there's no documentation regarding how to install jx in an offline environment.
It seems as if I should clone the entire GitHub organization and manually tweak things to work in my environment. Is that the case?

Thanks in advance!

**Comment by daveconde** [comment]
Looping in @vfarcic for further comment

**Comment by vfarcic** [comment]
We are working on making JX work better in on-prem environments. The main issue is that there are too many permutations. In some, it works as-is, while in other it needs some tweaks. How about we have a conference call and see what you need (what are your restrictions)? If that sounds as a good idea, please send me an email to vfarcic@cloudbees.com and I'll schedule a talk.

**Comment by 2020testuser** [comment]
@vfarcic - Any info. on this? I'm also trying to install JenkisX on my on-prem Kubernetes Cluster and looking for details? Could you please share whatever info. you have ?  Thanks!
