### ISSUE TITLE
Enforce that each pull request references an issue

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#7202]
We want to enforce that each pull request references an issue.

It needs to be discussed whether the reference needs to be in the commit message, pull request message or both.

Prow/Lighthouse might already have something like this. Needs to be investigated.

**Comment by hervelemeur** [comment]
Is it for jx PR or for any PR?

If it's for any PR, it might be problematic as it's not part of everyone workflow. (It's not mandatory for our at least, even more so we don't use github issues but only Jira)
