### ISSUE TITLE
Docker auth is reset after jx boot

### ISSUE THREAD

**Issue by AntoineFr** [jenkins-x/jx#7203]
### Summary 

When I use `jx boot` to update my existing installation to a new jx version, the `jenkins-docker-cfg` secret is reset to `{}`.

### Steps to reproduce the behavior

1. Run `jx boot` once and use a custom Docker registry
1. Add credentials to connect to this registry using `jx create docker auth`
1. -> A secret `jenkins-docker-cfg` is created containing all the information
1. Re-run `jx boot`
1. The secret `jenkins-docker-cfg` is back to `{}`

### Expected behavior

Keep the existing secret and its data.

### Actual behavior

The secret is reset to `{}`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.39
Kubernetes cluster v1.17.4
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Kubernetes cluster

On premise

### Operating system / Environment

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by AntoineFr** [comment]
By looking at the code I also found that if you don't specify a secret in the CLI, you are prompted to enter one after but this value will never be user.

https://github.com/jenkins-x/jx/blob/0082d6445f3b305896732d34b15bf5402bb9a0c3/pkg/cmd/create/create_docker_auth.go#L91-L100

I think these should use `secret` instead of `o.Secret`.

https://github.com/jenkins-x/jx/blob/0082d6445f3b305896732d34b15bf5402bb9a0c3/pkg/cmd/create/create_docker_auth.go#L127

https://github.com/jenkins-x/jx/blob/0082d6445f3b305896732d34b15bf5402bb9a0c3/pkg/cmd/create/create_docker_auth.go#L135

**Comment by deanesmith** [comment]
@AntoineFr, thank you for the issue.  Do you want to make a submission for the change?  Not sure it will remedy the situation entirely.

**Comment by AntoineFr** [comment]
@deanesmith I can make a pull request for the small changes I found in my comment but I think it's unrelated to the main problem I described in this issue and therefore it won't fix it.

**Comment by deanesmith** [comment]
Thank you @AntoineFr.  If a separate issue is needed that better represents your PR, please feel free to enter one and you can also reference this issue which we will keep open.
