### ISSUE TITLE
Make JXL and Innovation Open

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#7207]
### Summary 

I want to express my concerns and discontent about the announcement made here: https://jenkins-x.io/blog/2020/05/15/helm3/#why-isnt-this-all-more-open

I’ve created a blog post that covers all the negative points for the community members of the Jenkins X project. https://salaboy.com/2020/05/19/why-isnt-jenkins-xs-future-more-open/ Please upvote if you would like to see JXL innovation happen in the open.

**Comment by babadofar** [comment]
It's not hard to understand that there is a lot of work involved in switching to helm 3, and making JX more stable. But why does development have to happen outside of open source? Why not try to get all the feedback that you can? I really hope this period of secrecy will be short

**Comment by cdbkr** [comment]
A transparent roadmap is a critical point IMHO.

**Comment by anilkumarpasupuleti** [comment]
All the points you have made are noteworthy. Good that you brought them out . I do see that its been quite from core team for last couple of months, i hope the project will be continued as it was before, more open and interactive way.

**Comment by igdianov** [comment]
I noticed the channel has gone really quiet since the devs have started closed development in March. I liked the community interaction and direct feedback from @rawlingsj  @jstrachan. Hopefully, they will be back soon.

**Comment by rawlingsj** [comment]
Sorry for the delay in acknowledging this issue and replying.  Just wanted to say a big thanks to @salaboy and everyone else for sharing their thoughts, this is how an OSS community can grow and it has helped.

First off from myself and James Strachan we want everyone to know that we love Jenkins X and the OSS developer community that we started with + awesome folks that have joined along the way and continue to be involved in the project.  At CloudBees we are all working hard to get alignment on how we go forward.  Like anything as sensitive as this it can take time but we all want to get it right.

It must be said that there are lots of folks at CloudBees working on Jenkins X; so there are lots of open source contributions going on from CloudBees folks; such as improvements for Azure, OpenShift, Terraform and Lighthouse. You can find out more about the latest CJXD release [here](https://docs.cloudbees.com/docs/release-notes/latest/cloudbees-jenkins-x-distribution/v10).

We will give more updates soon and aim to hold an open session possibly at an office hours once things are more clear.

Thanks again to everyone for their continued commitment, passion and involvement with Jenkins X.

**Comment by salaboy** [comment]
@rawlingsj great stuff,  I will look forward to getting the full update on this topic. An open session will be great. It will be great to have you guys back on other issues as well and on design sessions, back in the open.

**Comment by tracymiranda** [comment]
Thank you all for bearing with us, please see https://jenkins-x.io/blog/2020/07/08/jxopeninnovation/

**Comment by rawlingsj** [comment]
> Thank you all for bearing with us

Agreed - and thanks to everyone for your involvement and feedback.  It has helped give the project more clarity + provide open source values that will aid building a healthy and active developer community.

If you can please try and join us next Tuesday for the office hours where we can start to plan the next steps together https://jenkins-x.io/community/#office-hours

**Comment by rawlingsj** [comment]
I think we can close this issue given the updates outlined in the blog.
