### ISSUE TITLE
jx add app jx-app-ui triggered task fails on the cluster with resources are missing from the TaskRun: [workspace]'

### ISSUE THREAD

**Issue by feczo** [jenkins-x/jx#7215]
### Summary 
Unable to install the jx ui due to tasks are created without workspace definition

### Steps to reproduce the behavior

fresh install of jenkinsx
run ❯ jx add app jx-app-ui
Approve Pull Request
Observe Tekton pipelines to see the tasks spinning up and failing after lighthouse callback

### Expected behavior

Install the UI 

### Actual behavior

Installation task failing with 

status:
  conditions:
  - lastTransitionTime: "2020-05-20T11:59:51Z"
    message: 'invalid input resources: Task''s declared required resources are missing
      from the TaskRun: [workspace]'
    reason: TaskRunValidationFailed
    status: "False"

### Jx version

NAME               VERSION
jx                 2.1.38
Kubernetes cluster v1.15.11-gke.13
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS

### Kubernetes cluster

jx boot on GKE using with tekton using the requirements file attached

### Operating system / Environment

"Ubuntu 18.04.2 LTS"

 jx add app jx-app-ui
WARNING: No secrets found on "helm/repos" due: reading the secret "helm/repos" from vault: no secret "helm/repos" not found in vault
Read credentials for http://chartmuseum.jenkins-x.io from vault helm/repos
Preparing questions to configure jx-app-ui. If this is the first time you have installed the app, this may take a couple of minutes.
Questions prepared.
Installing UI in single-user mode
Created Pull Request: https://github.com/user/myproject-dev/pull/3
Added app via Pull Request ...

tkn tr describe meta-user-project-dev-pr-3-prom-hash-1-meta-pipeline-hash -o yaml>failingtask.yaml.txt

[failingtask.yaml.txt.txt](https://github.com/jenkins-x/jx/files/4656785/failingtask.yaml.txt.txt)

[jx-requirements-reducted.yml.txt](https://github.com/jenkins-x/jx/files/4656755/jx-requirements-reducted.yml.txt)

**Comment by hervelemeur** [comment]
You have to specify the version, execute the command as it's written in the doc:
`jx add app jx-app-ui --version 0.1.49`

**Comment by feczo** [comment]
Exact same ultimate problem with the taskRun after specifying the version, also tried to reinstall the cluster from scratch resulted in the exact same issue yet again

$ jx add app jx-app-ui --version 0.1.49
WARNING: No secrets found on "helm/repos" due: reading the secret "helm/repos" from vault: no secret "helm/repos" not found in vault
Read credentials for http://chartmuseum.jenkins-x.io from vault helm/repos
Preparing questions to configure jx-app-ui. If this is the first time you have installed the app, this may take a couple of minutes.
Questions prepared.
Installing UI in single-user mode
Created Pull Request: https://github.com/user/project-dev/pull/1
Added app via Pull Request https://github.com/user/project-dev/pull/1

❯ tkn p list
NAME                                      AGE              LAST RUN                                  STARTED          DURATION    STATUS
meta-feczo-possum-dev-master-pr-xssv2-1   20 seconds ago   meta-feczo-possum-dev-master-pr-xssv2-1   20 seconds ago   1 second    Failed(PipelineValidationFailed)
meta-feczo-possum-dev-pr-1-prom-rcxpt-1   54 seconds ago   meta-feczo-possum-dev-pr-1-prom-rcxpt-1   54 seconds ago   0 seconds   Failed(PipelineValidationFailed)


status:
  conditions:
  - lastTransitionTime: "2020-05-20T16:09:00Z"
    message: 'invalid input resources: Task''s declared required resources are missing
      from the TaskRun: [workspace]'
    reason: TaskRunValidationFailed
    status: "False"

**Comment by abayer** [comment]
Could you share the `TaskRun` as well? And by any chance do you have a different Tekton version installed in your cluster besides/instead of the one Jenkins X installs itself?
