### ISSUE TITLE
fail to acquire the lock: no REPO_OWNER provided

### ISSUE THREAD

**Issue by ytree-admin** [jenkins-x/jx#7221]
### Summary 
I am using Jenkins X Classic. I am getting Error `error: fail to acquire the lock: no REPO_OWNER provided
` which is failing environment-clustername-staging build.
I tried with the latest jx version (for classic jenkins) which works with Classic Jenkins 2.0.1286. 
### Steps to reproduce the behavior
Pushing new code to github for any Jenkins job,
project builds fine but it waits for PR status,
it shows warning as follows:
`
+ jx step helm apply

Modified file /home/jenkins/agent/workspace/ironment-montrose-staging_master/env/Chart.yaml to set the chart to version 2

WARNING: no REPO_OWNER provided

error: fail to acquire the lock: no REPO_OWNER provided

script returned exit code 1`
### Expected behavior
environment-clustername-staging should be built
### Jx version
2.01139
The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1139
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.16.9
helm client        Client: v2.16.6+gdd2e569
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95```

### Kubernetes cluster
jj
<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->
Kubernetes Version 1.15
EKS Cluster
I have created by using Terraform
### Operating system / Environment
EKS
<!--
In which environment are you running the jx CLI?
-->

**Comment by hferentschik** [comment]
Classic/Static Jenkins is not supported anymore. Closing this issue.
