### ISSUE TITLE
Preview link not shown in comment

### ISSUE THREAD

**Issue by amorrortu** [jenkins-x/jx#7223]
### Summary 
When deploying a project with Knative, after a PR is created and the preview become available the comment wont show the link to it.
### Steps to reproduce the behavior
Deploy a project with Knative.
### Expected behavior
The comment telling that the preview is available has the link on it.
### Actual behavior
The comment telling that the preview is available does not have the link
![imagen](https://user-images.githubusercontent.com/41525205/82556541-366a5b80-9b6a-11ea-9559-3ee3918b7128.png)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.40
Kubernetes cluster v1.15.11-gke.9
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Kubernetes cluster

GKE cluster

**Comment by deanesmith** [comment]
Hi @amorrortu, there are occasional issues where the link doesn't show up but without quite a bit of additional insight we don't have a diagnosis.

**Comment by amorrortu** [comment]
Hi @deanesmith! Thanks for the reply. 
What information do you need?

**Comment by hervelemeur** [comment]
@amorrortu  I had a similar issue on a deficient jx installation, there were some related errors shown in the build logs, check if it's the same for you.

**Comment by deanesmith** [comment]
@amorrortu - looking over build logs including promotion builds might be helpful.  Posting appropriate errors or warnings here would be beneficial.
