### ISSUE TITLE
Flagger addon with gloo

### ISSUE THREAD

**Issue by mike-sirs** [jenkins-x/jx#7226]
### Summary 
Do we have possibility to use flagged with gloo while install flagged by jx?
here `pkg/cmd/create/create_addon_flagger.go` I see hardcoded istio without any options.

**Comment by deanesmith** [comment]
Hi @mike-sirs, can you elaborate on the use case a bit.  This is not something we're actively addressing but might make a good jx app. https://github.com/jenkins-x-apps

**Comment by mike-sirs** [comment]
> Hi @mike-sirs, can you elaborate on the use case a bit. This is not something we're actively addressing but might make a good jx app. https://github.com/jenkins-x-apps
I was just trying setup cluster with canary strategy using flagger and lightweight gloo instead of istio

**Comment by deanesmith** [comment]
@mike-sirs we're progressively removing "addons" from code and generating new "apps" (https://github.com/jenkins-x-apps) as part of the process.  Leaving this issue open and would greatly appreciate your contribution.
