### ISSUE TITLE
create addon istio doesn't work

### ISSUE THREAD

**Issue by mike-sirs** [jenkins-x/jx#7227]
### Summary 
`jx create addon istio` doesn't work
since v 1.5 istio moved to operator so no folder `install/kubernetes/helm/istio`

### Steps to reproduce the behavior
jx create addon istio

### Output
Istio package already downloaded: /Users/msirs/.jx/cache/istio-1.6.0-osx.tar.gz
error: Could not find folder install/kubernetes/helm/istio inside istio clone at /Users/msirs/.jx/cache/istio-1.6.0
### Jx version

The output of `jx version` is:
```
jx                 2.1.40
Kubernetes cluster v1.15.11-gke.13
kubectl            v1.13.2
helm client        2.12.2
git                2.24.1
Operating System   Mac OS X 10.15.4 build 19E287
```

**Comment by nodece** [comment]
Could you using  v1.5.4? 
```sh
jx create addon istio -v 1.5.4
```

**Comment by mike-sirs** [comment]
it isn't a solution =) We have istio 1.6 and we shouldn't expect istio put back old helm chart in future versions.
For now we can use the manual setup

**Comment by nodece** [comment]
We are migrating Addon to App for simpler operation.

:( Currectly it can only be installed manually.

If have any progress, I can append comments here.

**Comment by deanesmith** [comment]
Hi @mike-sirs, we don't actively maintain it but you could try `jx add app jx-app-istio`.  https://github.com/jenkins-x-apps/jx-app-istio

**Comment by sanyam1997** [comment]
hey is this issue still available @deanesmith, I am the first timer for open source contribution.

**Comment by nodece** [comment]
Hi @sanyam1997 , I'm working on migrate addons to apps. I have a look  https://github.com/jenkins-x-apps/jx-app-istio, it seems to be an empty repository. I have added the `jx-app-istio` into my plan.
