### ISSUE TITLE
[question] how to view jenkins-x pipeline's status

### ISSUE THREAD

**Issue by runzexia** [jenkins-x/jx#7228]
### Summary 

![image](https://user-images.githubusercontent.com/31230341/82748906-2657b380-9dd8-11ea-94af-7b5cfe883d0a.png)
I want to see the status of the running pipeline of jx to learn more about jx, but I found that I don't have permission to see it. How do I need to operate to see the running status of the pipeline

**Comment by ankitm123** [comment]
Are you referring to the pipeline status when you open a PR? If yes, then it's not available at the moment. There are some secrets that needs to be cleaned before it can be made public. I raised this issue during the office hours, but seems like there is no ETA yet, but will be eventually done 🤞

**Comment by deanesmith** [comment]
Hi @runzexia, the Jenkins X Project Build Dashboard requires authentication due to the nature of log messages.  Is there a specific log that someone can provide for you.

**Comment by runzexia** [comment]
> the Jenkins X Project Build Dashboard requires authentication due to the nature of log messages. Is there a specific log that someone can provide for you.

I don't have a special log to watch. I want to learn jenkins x through pipeline logs. 👀

**Comment by deanesmith** [comment]
@runzexia, I'd strongly recommend the [Getting Started Guide](https://jenkins-x.io/docs/getting-started/) and provisioning your own cluster.  Strong Kubernetes skills are not needed if you're leveraging Google Cloud Platform and even Amazon.
