### ISSUE TITLE
feat: add jx-app-kubeless to jx

### ISSUE THREAD

**Issue by nodece** [jenkins-x/jx#7233]
### Summary 

The chart for the Kubeless for Jenkins X.

Chart repo: https://github.com/nodece/jx-app-kubeless

Hi @MarckK , Here.

**Comment by MarckK** [comment]
Thank you, @nodece, for the app (and the issue). 😃

**Comment by deanesmith** [comment]
Hi @nodece, thank you for your contribution.  We can add the app to the apps repo appropriately.  After a formal code review we can also add it to the default chart repository.

**Comment by nodece** [comment]
Helm can not install kubeless from https://kubernetes-charts.storage.googleapis.com, I've fix it :(

I forgot  sync my repo to github :(

**Comment by nodece** [comment]
published
