### ISSUE TITLE
jx dependencies missing in builder images

### ISSUE THREAD

**Issue by mgoltzsche** [jenkins-x/jx#7238]
### Summary 
After upgrading `gcr.io/jenkinsxio/builder-go-nodejs` from version `2.0.1245` to `2.1.46-678` I get the following error when running `jx bdd` or rather `jx create cluster`:
```
running command: ** create cluster gke --project-id=jenkins-x-bdd3 -m=n1-standard-2 --min-num-nodes=3 --max-num-nodes=5 -z=europe-west1-c --skip-login --skip-installation --cluster-name pr-1491-69-bdd-frontend --batch-mode --labels cluster=bdd-frontend,branch=pr-1491 --git-provider-url https://github.com --versions-repo https://github.com/jenkins-x/jenkins-x-versions.git --versions-ref master --git-username c**d-bot-test --environment-git-owner cb-kubecd --git-public=false --git-api-token **************¬ --default-*****-password **************¬
error: run without batch mode or manually install missing dependencies [kubectl helm]
```

This is weird because on the one hand the image contains both `kubectl` and `helm` and they're in the `PATH` and on the other hand I'd expect a builder image to contain fully functional builder dependencies.

### Steps to reproduce the behavior
Run `jx bdd` or rather `jx create cluster` within a jx builder image.

### Expected behavior
Run `jx bdd` or rather `jx create cluster` within a jx builder image should work.

### Actual behavior
see error above

### Jx version
2.1.46-678

The output of `jx version` is:
```
$ docker run -ti --rm -v $HOME/.kube:/root/.kube gcr.io/jenkinsxio/builder-go-nodejs:2.1.46-678 jx version
Unable to connect to the server: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
```

### Kubernetes cluster
mole

### Operating system / Environment
Ubuntu 18.04

### Workaround
Run `jx install dependencies --all`.  
(Older jx versions don't support the `--all` option yet. Therefore one needs to make sure to use a newer builder image. When using `latest` tag for images one needs to either use the concrete new tag or at some point pull the latest version of that tag on all nodes - otherwise it may or may not work depending on the node you hit.)

### Improvement ideas
* Ship all dependencies with the builder images.

Regarding `latest` image references:
* While pinning and continuously updating builder image versions in all pipeline steps is more reliable than using `latest` it is also quite cumbersome. Instead, a jx controller could resolve the `latest` tag so that it is passed to the cluster as a digest image reference before execution.
* Alternatively a job could apply a DaemonSet to the cluster that pulls the latest images on all nodes regularly.

**Comment by daveconde** [comment]
Binary dependencies are included in JX_HOME/bin in builder base and jx now looks there by default. Quite a lot of our BDD tests change JX_HOME, is this the reason you are seeing the binaries are not available?

**Comment by mgoltzsche** [comment]
true, in my case `JX_HOME` is set to a temporary directory. That explains it. However I wonder why `JX_HOME` affects the lookup of binaries in the `PATH`.

**Comment by daveconde** [comment]
We have isolated most of the binaries that jx depends on so they are now treated more as an internal detail of jx. JX now looks in JX_HOME/bin by default for most binaries. This change was to prevent cases of users having an incorrect versions available on their path to reduce some friction for them. I'll get some details on this in to the docs so that its clearer for everyone :)

**Comment by daveconde** [comment]
I like the idea for future integrations where possible we aim to integrate at an API / library level instead of binary execution.
