### ISSUE TITLE
secrets "hmac-token" not found after executing jx boot

### ISSUE THREAD

**Issue by pancudaniel7** [jenkins-x/jx#7241]
### Summary 
secrets "hmac-token" not found after executing jx boot
### Steps to reproduce the behavior
- terraform apply (GKE)
- jx boot
### Expected behavior
Finish with GOOD status as always
### Actual behavior
Get this error:

<img width="776" alt="Screenshot 2020-05-27 at 15 51 41" src="https://user-images.githubusercontent.com/9675142/83021272-703bd600-a032-11ea-8392-d0647dfdde6f.png">
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.13+cjxd.9
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.16.6-beta.0
helm client        2.16.6
git                2.24.1
Operating System   Mac OS X 10.14.6 build 18G3020
verifying packages
```

**Comment by abayer** [comment]
Is this a new cluster? Since you're using CJXD 9, it shouldn't be upgrading to Lighthouse yet (which is what results in the `hmac-token` secret getting deleted). Newer `jx` binary versions handle this correctly by using the `lighthouse-hmac-token` when appropriate, but your cluster is still on the CJXD 9 release, which doesn't have that.

**Comment by pancudaniel7** [comment]
@abayer thank you. I've changed lighthouse with prow. I've installed kubernetes cluster on GKS using **jx-google-terraform** module version **1.3.2** and it generated for me **jx-requirements.yml** with **lighthouse**

**Comment by abayer** [comment]
Ok, we just released CJXD 10 which should handle this fine when you download the new binary and run `jx upgrade boot’, but if that doesn’t work, make a copy of the `lighthouse-hmac-token` secret named `hmac-token` and rerun boot.

**Comment by pancudaniel7** [comment]
<img width="1537" alt="Screenshot 2020-05-30 at 12 19 23" src="https://user-images.githubusercontent.com/9675142/83324715-d5c8d600-a26f-11ea-9a5f-c505b969b03c.png">
I receive that when I am trying to run ```bash jx upgrade boot```

**Comment by abayer** [comment]
Try `rm -rf ~/.jx/jenkins-x-versions` - it's trying to find the CJXD version but using the OSS repository.

**Comment by abayer** [comment]
So the problem here is that the user has a CJXD binary but created their cluster using the OSS Terraform module, getting everything mixed up. We need to figure out how to deal with this case.
