### ISSUE TITLE
JX UI app doesn't work if you specify URLTemplate in jx-requirements.yaml

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#7248]
### Summary 

JX UI app doesn't work if you specify URLTemplate in jx-requirements.yaml

### Steps to reproduce the behavior

If you set a URL Template in an environment it is overwritten by updates to jx boot. This was fixed as described here: https://github.com/jenkins-x/jx/issues/6648#issuecomment-600708365

Problem is, if you use that fix of putting the urlTemplate in jx-requirements, the jx-ui backend pod won't start.

Here are the logs:

```
> kubectl logs -n jx jenkins-x-jxui-76cc79f68b-4vdmm  jxui-backend
error: error getting Requirements from TeamSettings to determine if in GitHub app mode: validation failures in requirements from team settings:
environments.2: Additional property urlTemplate is not allowed
```

### Expected behavior

UI doesn't break when you use a URL Template for an environment.

### Actual behavior

UI doesn't work if you use a URL template, meaning you need to choose between production having the right URLs and accessing a UI.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.37
Kubernetes cluster v1.15.9-gke.24
kubectl            v1.16.3
helm client        2.16.3
git                2.24.3 (Apple Git-128)
Operating System   Mac OS X 10.15.4 build 19E287
```

### Kubernetes cluster

GKE - terraform

### Operating system / Environment

Error happens on pod in GKE

**Comment by patrickleet** [comment]
This is version from jx-app-ui version website from website:

```
- name: jx-app-ui
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.49
```

**Comment by patrickleet** [comment]
I opened up your helm chart index file to track down newer versions... Found `0.1.138`, and that seems to  work

**Comment by deanesmith** [comment]
Hi @patrickleet, take a look at https://github.com/jenkins-x/jx/pull/7249.  There may be some additional effort needed to achieve the desired result.
