### ISSUE TITLE
jx upgrade platform should upgrade jx everywhere

### ISSUE THREAD

**Issue by kzantow** [jenkins-x/jx#725]
After doing a `jx upgrade platform`, the version of jx used by Jenkins and in containers should be upgraded to the same version as what was used to run the upgrade platform command.

Perhaps, given different environments, this might not be possible to solve in all cases, so documentation on best practices to accomplish this may suffice.

At least, using the quickstarts/etc. should probably configure the clusters and environments such that this works by default.

**Comment by kzantow** [comment]
Right, I mostly just wanted to put something to track this, whatever the solution - even if it's "just fix your build scripts".

**Comment by mikecirioli** [comment]
having the ability to do `jx upgrade all`, which will iteratively run through `platform`, `addons`, etc would be nice
