### ISSUE TITLE
Jenkinsx on Kubernetes

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/jx#7250]
### Summary 
The link 'Install Jenkinsx on existing Kubernetes  Cluster' - https://jenkins-x.io/docs/managing-jx/old/install-on-cluster/ is not working.

### Steps to reproduce the behavior
1. Go to https://github.com/jenkins-x/jx
2. Under Getting Started, select "'Install Jenkinsx on existing Kubernetes  Cluster"
3. You get "Not found" error page
### Expected behavior
The link should open the correct page.
### Actual behavior
An error page appears
### Jx version
2.1.x

### Kubernetes cluster

Using Kubernetes version 1.16. 
### Operating system / Environment
Linux OS

Kubernetes on Linux OS and using jenkinsx commands from MAC

**Comment by hervelemeur** [comment]
@2020testuser you should open this issue [in the documentation repository](https://github.com/jenkins-x/jx-docs) instead ;)

**Comment by 2020testuser** [comment]
Sorry for not posting  in the documentation repository.  Are the instructions to install JenkinsX on top of on-prem Kubernetes in the[ link ](https://jenkins-x.io/docs/install-setup/installing/boot/clouds/on-premise/) ?  Thanks!
