### ISSUE TITLE
Remove deprecated K8s api versions

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#7251]
### Summary 
In some places in the code base, we use deprecated apis to query the kubernetes cluster for information about deployments. For example
```
d, err := client.ExtensionsV1beta1().Deployments(namespace).Get(name, options)
```
This would not work for kubernetes 1.16+. They should be changed. 
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
The newer apiVersions are available since Kubernetes 1.10, so this can be done safely.
Related to #6957

**Comment by mazika90** [comment]
> ### Summary
> In some places in the code base, we use deprecated apis to query the kubernetes cluster for information about deployments. For example
> 
> ```
> d, err := client.ExtensionsV1beta1().Deployments(namespace).Get(name, options)
> ```
> 
> This would not work for kubernetes 1.16+. They should be changed.
> https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
> The newer apiVersions are available since Kubernetes 1.10, so this can be done safely.
> Related to #6957
