### ISSUE TITLE
Stop using quay.io for nginx-ingress-controller image

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#7256]
For various reasons, largely around Kubernetes versioning, we're sticking on version 0.30.0 of `nginx-ingress-controller` for the foreseeable future. Given that and how frequently quay.io has outages, it'd be nice if we could use gcr.io/jenkinsxio/nginx-ingress-controller:0.30.0 instead of the default quay.io one. I've pushed that tag - found a copy of the image on Docker Hub, verified that the image sha is the same as the one we're running in weasel, so it's the right image.

I believe we can do this via adding `image.repository` and `image.tag` under `nginx-ingress.controller` in https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/systems/jxing/values.tmpl.yaml, overriding the defaults, but the question then becomes what we do if/when we actually upgrade the chart again.

**Comment by hferentschik** [comment]
>  but the question then becomes what we do if/when we actually upgrade the chart again.

what do we do?

**Comment by k8s42** [comment]
We deployed quite a few of our NGINX ingress controllers using Helm and I see those image paths listed as follows:

`quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0`

How would we go about updating NGINX ingress controller to v1.2.0 so the image gets pulled from `k8s.gcr.io/ingress-nginx/controller` without any issues?
