### ISSUE TITLE
Resource label naming incorrect?

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx#7257]
### Summary 
In reviewing all the resources that get created on a fresh Kubernetes cluster, I found that all resources deployed have a label, which may be misleading.  They currently use `jenkins.io` as part of the labeling.

Should this change?
### Steps to reproduce the behavior
Just view the resources and their metadata.

### Expected behavior
Potentially all labels for resources deployed when installing Jenkins X should be `jenkins-x.io`?

### Actual behavior
![image](https://user-images.githubusercontent.com/1544014/83174337-1b9a6880-a0cf-11ea-8c09-0d6a4b7eba5d.png)

**Comment by ankitm123** [comment]
I think it should be jenkinsx.io (or something similar) to avid confusion.
