### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/jx#7259]
### Summary 
I'm getting a certificate error while trying to install jenkinsx on an on-premise Kubernetes cluster.
### Steps to reproduce the behavior
Install JenkinsX on a remote Kubernetes Cluster  from your local machine.
### Expected behavior
Successful JenkinsX installation.

### Actual behavior
JenkinsX installation fails with a certificate error.
Error message is below.
`WARNING:
retrying after error:failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: x509: certificate signed by unknown authority'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://storage.googleapis.com/chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml: x509: certificate signed by unknown authority'
 `
### Kubernetes cluster

On-prem Kubernetes Cluster v 1.16

### Operating system / Environment

on MAC OS

**Comment by stepanselyuk** [comment]
@2020testuser try to run alpine container on the cluster, install curl in it and reach the repository url.

```
kubectl run --generator=run-pod/v1 -i --tty alpine --image=alpine --restart=Never -- sh

apk add curl --no-cache
curl -vvv https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml
```

E.g. on `microk8s` single-node cluster DNS resolution is not working before I installed addon `dns`.

**Comment by 2020testuser** [comment]
@stepanselyuk - Thanks!
Tried the above commands and getting an error when I ran the curl command.
Is there any other way to resolve this error? Thanks!

`
/ # curl -vvv https://storage.googleapis.com/chartmuseum.jenkins-x.io/index.yaml
*   Trying xxx.xx.xxx:portno...
* TCP_NODELAY set
* Connected to storage.googleapis.com (xxx.xx.xxx) port no (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.`

**Comment by stepanselyuk** [comment]
@2020testuser try to install ca-bundle `apk add ca-certificates`

**Comment by 2020testuser** [comment]
@stepanselyuk - Thanks!  
Still no luck. 
One step forward but getting an error on velero.
`
Modified file /Users/<msid>/Documents/jx/jenkins-x-boot-config/systems/velero/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.475
error: failed to build the dependencies of chart '/var/folders/4g/3hf_zjt31dzjrjyv20j/T/jx-helm-apply-510512547/velero': failed to run 'helm dependency build' command in directory '/var/folders/4g/3hf_zjt31dzjrjyv20j/T/jx-helm-apply-510512547/velero', output: 'Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:portno/charts):
	Get http://127.0.0.1:portno/charts/index.yaml: dial tcp 127.0.0.1:portno: connect: connection refused
...Successfully got an update from the "jenkins-x" chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	open /Users/<ms-id>/.helm/repository/cache/~/.helm/repository/cache/stable-index.yaml: no such file or directory
Update Complete. ⎈Happy Helming!⎈
Error: velero chart not found in repo https://kubernetes-charts.storage.googleapis.com'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --no-vault --name velero' command in directory 'systems/velero', output: ''
`

**Comment by stepanselyuk** [comment]
@2020testuser here is weird: 
```
open /Users/<ms-id>/.helm/repository/cache/~/.helm/repository/cache/stable-index.yaml: no such file or directory
```
but:
/Users/<ms-id>/.helm/repository/cache/
~/.helm/repository/cache/

are present the same path, and why two paths concatenated. Try to remove  ~/.helm so reset the cache and so on. Jenkins X cannot find `velero` in the "stable" chart repository because of the error above.

**Comment by 2020testuser** [comment]
@stepanselyuk - Thanks! One step forward. I deleted the entire ./helm directory (not sure where the ~/.helm/repository/cache/ coming from) and reran jx boot. 
I got past that error. Now getting an ingress error.
Do I need to make any changes in the yaml file? Also, since, I'm installing jenkinsx on top of on-prem Kubernetes cluster, is there anything that I need to do additionally? Thanks for all your help !

==============================================
`Jenkins X CRDs upgraded with success.

STEP: install-velero command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero

Modified file /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.475

STEP: install-velero-backups command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero-backups in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero-backups

Modified file /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero-backups/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Ignoring templates/default-backup.yaml
No requirements file: /var/folders/4g/p0450fv3hf_zjt31dzjrjyv20j/T/jx-helm-apply-401436607/velero-backups/requirements.yaml so not checking for missing versions

STEP: install-nginx-controller command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name jxing in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/systems/jxing

Modified file /Users/myid/Documents/jx/jenkins-x-boot-config/systems/jxing/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.475

STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/env

Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
If you are installing Jenkins X on premise you may want to use the '--on-premise' flag or specify the '--external-ip' flags. See: https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output: ''
`

**Comment by 2020testuser** [comment]
@stepanselyuk - Thanks for your help! I got the issue resolved when I tried with jx boot. Will close this issue.
