### ISSUE TITLE
jx boot fails with msg - velero chart not found in repo.

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/jx#7260]
### Summary 
Installing JenkinsX using jx boot.

### Steps to reproduce the behavior
1. Install JenkinsX on top of an on-prem remote Kubernetes cluster using the jx boot command from a local MAC OS machine.

### Expected behavior
Successful install of JenkinsX using jx boot command.
### Actual behavior
Installation fails with the below error msg.
`
STEP: install-velero command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero

Modified file /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.475
error: failed to build the dependencies of chart '/var/folders/4g/prh490450fv3hf_zjt31dzjrjyv20j/T/jx-helm-apply-071077216/velero': failed to run 'helm dependency build' command in directory '/var/folders/4g/prh490450fv3hf_zjt31dzjrjyv20j/T/jx-helm-apply-071077216/velero', output: 'Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:portno/charts):
	Get http://127.0.0.1:portno/charts/index.yaml: dial tcp 127.0.0.1:portno: connect: connection refused
...Successfully got an update from the "jenkins-x" chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	open /Users/myid/.helm/repository/cache/~/.helm/repository/cache/stable-index.yaml: no such file or directory
Update Complete. ⎈Happy Helming!⎈
Error: velero chart not found in repo https://kubernetes-charts.storage.googleapis.com'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --no-vault --name velero' command in directory 'systems/velero', output: ''
`
### Versions

The components versions are

```
NAME               VERSION
jx                 2.1.49
Kubernetes cluster v1.16.8 (on-prem remote cluster)
kubectl            v1.16.6-beta.0
git                2.20.1 (Apple Git-117) 

```

Running jxboot from local MAC machine. 

Thanks!

**Comment by ankitm123** [comment]
Can you check if .helm directory exists in the home folder? Not sure why that got removed ...

**Comment by 2020testuser** [comment]
@ankitm123 - Sorry for my delayed response. I do see the  /Users/<myid>/.helm repository and I also directories under it. 
I believe the problem is because of local-index.yaml under  `/Users/<myid>/.helm/repository/cache/repository/cache/ `gets automatically symlinked to  `/Users/<myid>/.helm/repository/local/index.yaml` as I see the below when I list the files under the directory 
`/Users/<myid>/.helm/repository/cache`.

` local-index.yaml -> /Users/<myid>/.helm/repository/local/index.yaml`

I'm not sure from which file it is pulling the below location. As this location is not there (because of ~), it gives an error.

`open /Users/<myid>/.helm/repository/cache/~/.helm/repository/cache/stable-index.yaml: no such file or directory`

I believe my helm local is not setup properly. Could you please let me know if I can run any additional checks/commands for this? Thanks!

**Comment by 2020testuser** [comment]
@ankitm123 - Could you let me know whether you find any info. to resolve the issue from the above directories?
Thanks in advance!

**Comment by 2020testuser** [comment]
Can anyone help me on the above? I'm trying to install Jenkinsx from my MAC  on top of  remote on-prem Kubernetes cluster. Thanks in advance

**Comment by 2020testuser** [comment]
@ankitm123 - I uninstalled Helm and that resolved the issue. Looks like my helm was broken. 
However, I'm getting a different error now. Will open as a new issue.
Thanks for your help!

**Comment by ankitm123** [comment]
@2020testuser can you show the contents of `.helm/repository/cache`?
