### ISSUE TITLE
Proposal: deprecate jx upgrade cli

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#7266]
### Summary 
Currently we have a command `jx upgrade cli` to check and upgrade the cli binary version. I think it might be better to deprecate and eventually remove this command.

We have documentation about installing jx cli in different OS using the package managers (and plain curl in linux). We are not getting any additional benefit from having an upgrade cli command.

We should check the latest version available in github when someone runs a jx version and display the link to the installation page in the documentation website (https://jenkins-x.io/docs/install-setup/).

We could probably ask in the community slack channel what they think about having this command (If lot of users use this and see value in keeping it, then it makes sense to keep it - :+1: if they want to keep it or :-1: if they dont see any value in keeping it)
Thoughts?

**Comment by garethjevans** [comment]
I'd love to get @hferentschik's view on this.  There was a thought that we do the reverse of this, remove the OS package manager support (brew etc) and only allow `jx upgrade cli` as it allows us to sync versions with the version stream.  

Could be a great topic for the office hours.

**Comment by ankitm123** [comment]
Closing this after the  discussion during the `jx office hours`. This command can be refactored, and will be helpful in managing different jx binaries in different clusters.
