### ISSUE TITLE
jenkinsx install on on-prem

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/jx#7271]
### Summary 
Installing JenkinsX  using jxboot in an on-prem Kubernetes cluster results in an error. Could anyone  please let me know whether I need to update for any setting in the requirements file? Thanks!

### Steps to reproduce the behavior
Install  JenkinsX using jxboot in an on-prem , remote Kubernetes cluster results in an error from your local MAC machine.
### Expected behavior
Successful JenkinsX installation
### Actual behavior
JenkinsX installation fails.

### Version Info.

NAME               VERSION
jx                 2.1.49
Kubernetes cluster v1.16.8 (on-prem remote cluster)
kubectl            v1.16.6-beta.0
git                2.20.1 (Apple Git-117) 

Error Msg:
`STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/env

Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
If you are installing Jenkins X on premise you may want to use the '--on-premise' flag or specify the '--external-ip' flags. See: https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output:`

Thanks!

**Comment by ankitm123** [comment]
What is the output of:
```
kubectl get svc -n kube-system
```

**Comment by 2020testuser** [comment]
@ankitm123 - Thanks!
Below is the output of 
`kubectl get svc -n kube-system
`
I removed the CLUSTER-IP column and AGE  column below.
`
NAME                                                    TYPE            EXTERNAL-IP         PORT(S)                      
jxing-nginx-ingress-controller        LoadBalancer     <pending>        80:30401/TCP,443:30346/TCP   
jxing-nginx-ingress-default-backend  ClusterIP         <none>            80/TCP                     
kube-dns                                              ClusterIP          <none>           53/UDP,53/TCP,9153/TCP  
`     

I also added the ignoreLoadBalancer to true and still the same error.
`No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: `

Thanks,

**Comment by ankitm123** [comment]
Makes sense that the type loadbalancer is shown as pending, on-prem kubernetes will not support it out of the box afaik (It's cloud provider specific). See: https://stackoverflow.com/a/44112285
Mind posting the contents of jx-requirements.yml (remove any thing sensitive). Honestly more interested in the ingress section of the requirements file.

**Comment by ankitm123** [comment]
Also this is a useful reference: https://kubernetes.github.io/ingress-nginx/deploy/baremetal/

**Comment by 2020testuser** [comment]
@ankin123 - Thanks for the immediate reply. Below is the requirements yaml. The bold text gets added automatically when I run the jx boot command.

======================================

`
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
cluster:
  clusterName: xxx-cluster
  devEnvApprovers:
  - myid
  environmentGitOwner: myid
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: kubernetes
environments:
- ingress:

    domain: xxx.xx.xx.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-hostname-dev
- ingress:
    domain: ""
    externalDNS: false
    ignoreLoadBalancer: true
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-hostname-staging
- ingress:
    domain: ""
    externalDNS: false
    ignoreLoadBalancer: true
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-hostname-production
**ingress:
  domain: ""
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false**
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.475
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse

`

**Comment by ankitm123** [comment]
A bit confused 😕 . Why there are so many ingress entries (probably a better question is why is jx adding new ingress entries), or may be I am not reading this properly? Can you clear up all of the ingress entries, and only keep the one with `ignoreLoadBalancer: true`

PS: Would help a lot if you can format the requirements yaml a bit more in the comments to make it more readable :)

**Comment by deanesmith** [comment]
Hi @2020testuser, for on-prem Kubernetes folks are largely on their own.  Following up on @ankitm123 response, the excessive amount of ingress entries is unusual.

**Comment by 2020testuser** [comment]
@ankitm123 - I removed the excess ingress entries which got generated by Kubernetes extension in VSCode (disabled it). With one ingress, I get the same error. Could you  please let me know whether anything is missing in the yaml now? Thanks!

jx-requirements.yaml:

`
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
cluster:
  clusterName: host.com
  devEnvApprovers:
  - myid
  environmentGitOwner: myid
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: kubernetes
ingress:
  domain: ""
  externalDNS: false
  ignoreLoadBalancer: true
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.475
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
`

Error Msg:
`
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
If you are installing Jenkins X on premise you may want to use the '--on-premise' flag or specify the '--external-ip' flags. See: https://jenkins-x.io/getting-started/install-on-cluster/#installing-jenkins-x-on-premise
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output: ''
`

**Comment by 2020testuser** [comment]
@deanesmith - It would be really good if there is a complete documentation for JenkinsX on on-prem. We are using  tekton pipeline and using JenkinsX for on-prem Kubernetes, would be really useful for us. It would be useful if  on-prem documentation be set as a priority or if someone can work with me to help resolve the issues. I'll document and provide installation details for JenkinsX on on-prem once I get it working. 
Thanks in advance!

**Comment by kingdonb** [comment]
I think it's still fair to say the JenkinsX On Premise documentation is kind of light:

https://jenkins-x.io/docs/install-setup/boot/clouds/on-premise/

> We recommend starting with the most simple possible installation and get that working, then gradually try to be more complex. e.g. start off by ignoring these features:
> 
> - vault
> - DNS
> - TLS / certificates
> - cloud storage for artifacts
> 
> Then once you have something working, incrementally try enabling each of those in turn.

This leaves quite a bit up to the imagination, I have just tried once, twice, three times and failed all three, I'll keep trying, but this issue ought not be closed automatically. (Let someone close it manually if this shall remain permanently unsupported.)
