### ISSUE TITLE
Confused versions

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#7274]
### Summary 

I'm trying to upgrade my cluster with `jx boot upgrade`.

Early on, it asks me the following:

```
WARNING: jx version specified in the version stream /Users/vfarcic/.jx/jenkins-x-versions is 2.0.1202. You are using 2.1.56. We highly recommend you upgrade to it.
```

Should I upgrade from `2.1.56` to `2.0.1202`?

**Comment by ankitm123** [comment]
Seems like an issue with verifyJXVersion function, it seems to check if the current version is equal to the current one, and then regardless prints this warning message.
