### ISSUE TITLE
Switch jx to use lighthouse-config library for "Prow" config

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#7280]
We'll be using that library in Lighthouse as well, so this lets us make changes to the config for jobs without needing to do circular dependency hell.

**Comment by hferentschik** [comment]
> We'll be using that library in Lighthouse as well, so this lets us make changes to the config for jobs without needing to do circular dependency hell.

Could _lighthouse-config_ not be part of lighthouse as independent consumable API package? Will _lighthouse-config_ ever evolve change outside of the scope of lighthouse? I am concerned about the additional repository we have to manage. Also, unless I am missing something here, having an API  package would be the more natural choice. Or could it be part of the _pkg_ structure of lighthouse? See https://github.com/golang-standards/project-layout/tree/master/pkg.
