### ISSUE TITLE
'jx delete environment'  doesn't delete the corresponding repositories

### ISSUE THREAD

**Issue by romenrg** [jenkins-x/jx#7281]
### Summary 

When deleting an environment, via `jx delete environment` I would expect that the corresponding environment repo in GitHub is also deleted. However, that is not the case.

### Steps to reproduce the behavior

Create a Jx environment and then delete it

### Expected behavior

Apart from the Kubernetes objects, the corresponding GitHub repository should be deleted

### Actual behavior

The Kubernetes objects are deleted, but the GitHub repository is not

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1192+cjxd.7
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.14.7
git                2.21.1 (Apple Git-122.3)
Operating System   Mac OS X 10.15.4 build 19E287
```

### Kubernetes cluster

GKE, created with Jx create cluster

### Operating system / Environment

MacOS

**Comment by hferentschik** [comment]
Maybe we can have an option to include repository deletion. Doing it per default seems dangerous.

In this context, we need to also verify whether this command actually supports/work with Boot.

**Comment by romenrg** [comment]
Including repository deletion as an option sounds like a good idea, @hferentschik .

Regarding the Boot support, that is probably the way to go, indeed. I was talking to @vfarcic about this and pointed me to https://github.com/jenkins-x/jx/issues/7066. If we go through the Boot route (potentially making this `jx create/delete environment` approaches obsolete), then my only comment would be, taking the "delete GH repo" part into account for the boot equivalent
