### ISSUE TITLE
Failed to query the Pull Request last commit status 

### ISSUE THREAD

**Issue by mmugabo-rockhs** [jenkins-x/jx#7292]
I am getting: "**Failed to query the Pull Request last commit status for....**" when I create an app with "**jx create quickstart**" and during promote to staging env, that is when this error happens.

This is my environment:

**NAME               VERSION
jx                 2.1.46+cjxd.10
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G95**

I have created my set up using the following:
- Created my GKE cluster thru the console
- Forked the Cloudbees jenkins-x-config set up repo
- I have TLS enabled with my domain.
- I have everything else set up such as Github Org, bot account, etc...
- I changed lighthouse to prow, might want to revert to lighthouse if this could be the issue

Please let me know how to move on this..
Thanks

_Originally posted by @mmugabo-rockhs in https://github.com/jenkins-x/jx/issues/6532#issuecomment-639707348_

**Comment by mmugabo-rockhs** [comment]
I went back to the most basic jx boot config and then I did a step by step adding advanced configurations one at a time (doing a fresh install every time) to be able to single out the issue. And that led to me to my TLS, the whole CI/CD works perfectly if I do not enable TLS. When I have it enabled, I can't get an application promoted to staging (after jx create quickstart), I get into an infinite loop with this error:

`got git provider status pending from PR rockhs-org/environment-core-cluster-staging#1`

Do you know what logs to look into in this scenario?
By enabling TLS I mean b4 running jx boot, in my jx-requirement.yaml I set the following ingress props:

```
ingress:
  domain: core.MYDOMAIN.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: EMAIL@MYDOMAIN.com
    enabled: true
    production: true
```
Thanks.

**Comment by abayer** [comment]
Did you change from Lighthouse to Prow during the run of the promotion? If so, that would explain the commit status never being updated.

**Comment by mmugabo-rockhs** [comment]
No I did not do that. I kept lighthouse.
Thanks

**Comment by gswallow** [comment]
Seems to be a pattern of unresolved issues going stale and being closed out by jenkins-x-bot.
