### ISSUE TITLE
Jx get activity does not report activities after upgrade

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx#7293]
### Summary 
I have been using the command ` jx get act -w -s `  in a console to see continuous updates to our cluster,  which is very useful. After some upgrade lately, it doesnt't work anymore, it just outputs the name of the main pipeline started, and no details. 

### Steps to reproduce the behavior
Hmm. not sure. Upgraded jx boot from an earlier version. 
### Expected behavior
Activities with details from each pipeline step being output continuously
### Actual behavior

It outputs the name of the main pipeline only, no details.
Additionally, when I start it up, it outputs really old stuff, like this
   
     PullRequest    1222h12m44s     2m31s Failed      PullRequest: https://github.com/xxx

### Jx version

The output of `jx version` is:
jx boot versionstream v1.0.441
```
jx                 2.1.56
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.16.2
helm client        2.14.3
git                2.18.0
Operating System   Mac OS X 10.14.6 build 18G3020```

### Kubernetes cluster
EKS
### Operating system / Environment
OSX

**Comment by abayer** [comment]
Huh, this is weird - I'm not able to reproduce with the 2.1.56 binary against our dogfood cluster, which itself is on Kubernetes 1.14. I'm still getting the same output as always. I wonder if there's bad/old stale `PipelineActivity`s in your cluster? Has your `jenkins-x-gcactivities` cronjob been running, and, just to check because I seem to remember this being set wrong until recently, what's the version of the `builder-jx` image used in it?

**Comment by babadofar** [comment]
- k get cronjobs jenkins-x-gcactivities -oyaml 
  lastScheduleTime: "2020-06-09T07:30:00Z"
 image: gcr.io/jenkinsxio/builder-jx:0.1.658
- k describe  cronjobs jenkins-x-gcactivities 
  Normal  SuccessfulCreate  36m    cronjob-controller  Created job jenkins-x-gcactivities-1591686000
  Normal  SawCompletedJob   36m    cronjob-controller  Saw completed job: jenkins-x-gcactivities-1591686000, status: Complete
  Normal  SuccessfulDelete  36m    cronjob-controller  Deleted job jenkins-x-gcactivities-1591680600
  Normal  SuccessfulCreate  6m45s  cronjob-controller  Created job jenkins-x-gcactivities-1591687800
  Normal  SawCompletedJob   6m35s  cronjob-controller  Saw completed job: jenkins-x-gcactivities-1591687800, status: Complete
  Normal  SuccessfulDelete  6m35s  cronjob-controller  Deleted job jenkins-x-gcactivities-1591682400

**Comment by abayer** [comment]
Ok, yeah, your `jenkins-x-gcactivities` cronjob is stale - try going to `env/jenkins-x-platform/values.tmpl.yaml` in your dev env repo, and looking for the `gcactivities` cronjob's image tag. If you just remove the tag entry, it'll use the latest version in the version stream, and will be much better about cleanup.

**Comment by babadofar** [comment]
unfortunately,the `jx get activites` is now back to showing just the pipeline name. It seems the change of image tag impacted only a few runs, and now its back to the old behaviour.
Any other ideas what I can do?
