### ISSUE TITLE
Pullrequest pipeline fails at preview environment step

### ISSUE THREAD

**Issue by pancudaniel7** [jenkins-x/jx#7296]
### Summary 
Pullrequest pipeline fails ta preview environment step with 503 but Google dns works and is propagated. 
### Steps to reproduce the behavior
- create a pr
- check the jx ui
### Expected behavior
Pipeline should finish with the last step for creating the preview environment
### Actual behavior
Pipeline fails at **Promote jx preview** step with: **error was 503 503 Service Temporarily Unavailable** but the Google dns cloud works correctly

<img width="1680" alt="Screenshot 2020-06-07 at 17 52 32" src="https://user-images.githubusercontent.com/9675142/83972409-a60d7400-a8e8-11ea-8b83-1b11f4db17f0.png">

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.46+cjxd.10
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.24.1
Operating System   Mac OS X 10.14.6 build 18G3020
```

**Comment by hferentschik** [comment]
Could you provide a bit more context? For example the status/health check of the application Pod in the preview environment.

you can run:

```
# to find the right environment namespace
jx ns

# locate the app preview Pod
kubectl get pods -n <env-namespace>

# get some more information about the pod
kubectl describe pod <preview-app-pod>
```

**Comment by pancudaniel7** [comment]
Hi @hferentschik 
logs for pr-preview:
<img width="1294" alt="Screenshot 2020-06-08 at 17 06 02" src="https://user-images.githubusercontent.com/9675142/84039880-90f91980-a9aa-11ea-8da8-f7b7a7bddde4.png">

And description of the pod:
<img width="1675" alt="Screenshot 2020-06-08 at 17 06 43" src="https://user-images.githubusercontent.com/9675142/84039915-9c4c4500-a9aa-11ea-9dab-5509f0a4c4bc.png">
