### ISSUE TITLE
jx-app-sonar-scanner ImagePullBackOff

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#7298]
### Summary 
The image for jx-app-sonar-scanner is not accessible:

```
Failed to pull image "gcr.io/jenkins-x-infra/jx-app-sonar-scanner:0.0.49": rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jenkins-x-infra/jx-app-sonar-scanner, repository does not exist or may require 'docker login'
```
@deanesmith

**Comment by hferentschik** [comment]
Most likely the image is pushed to the wrong repo. It should _gcr.io/jenkinsxio_

**Comment by tdcox** [comment]
There is an IMAGE reference in the Makefile that hasn't been updated but I'm not sure why it is defaulting to `jenkins-x-infra` unless that value gets overridden somewhere in the build environment?

**Comment by abayer** [comment]
I can't find anything anywhere for `jenkins-x-infra` in the repo, so I am very confused.
