### ISSUE TITLE
Jenkins-x marking the master pipeline as success build even though the staging pipeline is still in progress

### ISSUE THREAD

**Issue by reddybhavaniprasad** [jenkins-x/jx#7308]
### Summary 
I am trying to build & deploy a maven application in jenkins-x. So when the build is triggered from the master branch of that application it successfully builds the application and triggers the staging pipeline.

While the staging pipeline is still in progress then master pipeline of maven application marks the build as success without worrying about the status of the staging pipeline.

### Steps to reproduce the behavior

Create a multi branch pipeline in jenkins-x for a service.
Raise a pull request for that service.
Merge the pull request into master branch.

### Expected behavior

The current pipeline build should wait for the staging pipeline to finish and then mark the current build status based on the staging pipeline build status.

### Actual behavior

The build shows as "success" status even though the pipeline "http://jenkins-jx.router.default.svc.cluster.local/job/ms/job/environment-ms-staging/job/master/21/display/redirect" is still in progress.

    + jx promote -b --all-auto --timeout 1h --version 0.0.11
    WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
    Promoting app ne-manager version 0.0.11 to namespace jx-staging
    Created Pull Request: http://rtx-swtl-git.fnc.net.local/projects/MS/repos/environment-ms-staging/pull-requests/19
    WARNING: Adding labels not supported on bitbucket server yet for repo automation/environment-ms-staging issue 19 labels [updatebot]
    Added label updatebot to Pull Request http://rtx-swtl-git.fnc.net.local/projects/MS/repos/environment-ms-staging/pull-requests/19
    Pull Request http://rtx-swtl-git.fnc.net.local/projects/MS/repos/environment-ms-staging/pull-requests/19 is merged at sha 8bef1cf6800bdc281bcb5ba9debcdcf23c0165b6
    Merge commit has not yet any statuses on repo automation/environment-ms-staging merge sha 8bef1cf6800bdc281bcb5ba9debcdcf23c0165b6
    merge status: in-progress for URL http://jenkins-jx.router.default.svc.cluster.local/job/ms/job/environment-ms-staging/job/master/21/display/redirect with target: http://jenkins-jx.router.default.svc.cluster.local/job/ms/job/environment-ms-staging/job/master/21/display/redirect description: The tests have started...
    WARNING: merge status: failure URL: http://jenkins-jx.router.default.svc.cluster.local/job/ms/job/environment-ms-staging/job/master/21/display/redirect description: There was a failure building this commit

### Jx version

The output of `jx version` is: 2.0.785

```
NAME               VERSION
jx                 2.0.785
jenkins x platform 2.0.2270
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.11.0+d4cacc0
helm client        Client: v2.12.0+gd325d2a
git                2.22.0
Operating System   "CentOS Linux release 7.7.1908 (Core)"
```

### Kubernetes cluster

I am using a 4 node Openstack cluster with centos - 7 and OKD installed in it

### Operating system / Environment

Centos - 7/OKD

**Comment by daveconde** [comment]
The static Jenkins functionality has been removed from the latest versions of Jenkins X. We suggest moving to a tekton / boot based install.
