### ISSUE TITLE
How to handle nodeports in multiple environments of Jenkins-x

### ISSUE THREAD

**Issue by reddybhavaniprasad** [jenkins-x/jx#7310]
### Summary 
I am building and deploying a **spring-boot** application in **Jenkins-x** environment. When a Pull request is being raised then the build and deployment happens in **Preview** environment in some namespace which is using **32104** as **nodeport**.

When the Pull Request is merged then the build and deployment happens in the **jx-staging** namespace which tries to expose the service in **32104** port.

### Steps to reproduce the behavior

Create a Jenkins pipeline for a **spring-boot** application which exposes the service in some **nodeport** and create a pull request for the same application and then merge the pull request into **master** branch.

### Expected behavior
Once the Pull Request is merged to master all the resources associated with the Preview deployment should be vanished.

### Actual behavior
The master pipeline build fails with nodeport conflict since it is already being used by the preview deployment.

### Jx version

The output of `jx version` is: 2.0.785

```
NAME               VERSION
jx                 2.0.785
jenkins x platform 2.0.2270
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.11.0+d4cacc0
helm client        Client: v2.12.0+gd325d2a
git                2.22.0
Operating System   "CentOS Linux release 7.7.1908 (Core)"
```

### Kubernetes cluster

I am using a 4 node Openstack cluster with centos - 7 and OKD installed in it

### Operating system / Environment

Centos - 7/OKD

**Comment by daveconde** [comment]
I'd recommend using ingress instead of node ports if possible, the use of node ports will limit you to a single pod of that type running on a single node. this creates issues around deployment strategies other than recreate. Preview environments are garbage collected by a cronjob called jenkins-x-gcpreviews.
