### ISSUE TITLE
jx get vault-config fails

### ISSUE THREAD

**Issue by joostvdg** [jenkins-x/jx#7315]
### Summary 

Running `jx get vault-config` fails.

### Steps to reproduce the behavior

Have an existing cluster with Vault installed via `jx boot`, and a recent `jx` CLI `2.1.x`+.

### Expected behavior

```shell
Downloading https://releases.hashicorp.com/vault/1.4.2/vault_1.4.2_darwin_amd64.zip to /Users/joostvdg/.jx/bin/vault.zip...
Downloaded /Users/joostvdg/.jx/bin/vault.zip
export VAULT_ADDR=https://vault-jx.dev.jxgke.kearos.net
export VAULT_TOKEN=s.XXXXXXXXXXXXXXX
```

I'll ignore the downloading of the binary, which is a different topic - not expected at all, but not the current issue.
The above output is from the CJXD 10 binary:

```
jx                 2.1.46+cjxd.10
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.16.7
helm client        2.16.1
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.5 build 19F96
```

### Actual behavior

```shell
error: unable to parse Vault configuration from ConfigMap jx-install-config: service account name cannot be empty
```

### Jx version

The output of `jx version` is:

```
**FATAL: Your current helm version v3 is not supported. Please downgrade to helm v2.**
```

Right, sorry for that.

Cluster A.

```
NAME               VERSION
jx                 2.1.62
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.16.7
helm client        2.16.1
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.5 build 19F96


verifying packages
```

Cluster B, installed via `jx boot` with CJXD 6 or 7 I believe.

```
jx                 2.1.62
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.16.7
helm client        2.16.1
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.5 build 19F96


verifying packages
```

### Kubernetes cluster

* Cluster A: GKE cluster, created via Jenkins X Terraform GKE
* Cluster B: GKE cluster, created via jx create (I believe)

### Operating system / Environment

```
Mac OS X 10.15.5 build 19F96
```

**Comment by daveconde** [comment]
Are you using a newer version of the jx binary against an older version of jx in cluster? Ideally the versions would match. We need to make this easier for users via #5971

**Comment by hferentschik** [comment]
Another workaround is to run `jx boot` with the new binary. This will update the ConfigMap. That said, this is a bug and @cagiti is working on a fix.

The issue is how the command tries to create the system Vault client. It has it's own `systemVaultClient` function opposed to calling `factory.CreateSystemVaultClient` which had the same issue originally, but got already fixed.
