### ISSUE TITLE
I am getting below error while while running jx install --provider=kubernetes --on-premise

### ISSUE THREAD

**Issue by SahuBhaskar** [jenkins-x/jx#7316]
### Summary 
2 pvc are terminating while running jx install --provider=kubernetes --on-premise

### Expected behavior
auocreated PVC should be mounted with concern pods and pods should running state as i have defined default storage class.
### Jx version
root@Kube-01:~# jx version
NAME               VERSION
jx                 2.1.65
Kubernetes cluster v1.15.11
kubectl            v1.13.2
helm client        2.12.2
git                2.27.0
Operating System   Ubuntu 16.04.6 LTS

verifying packages

The output of `jx version` is:

```
COPY OUTPUT HERE

Modified file /root/jenkins-x-boot-config/env/Chart.yaml to set the chart to version 1
Ignoring templates/.gitignore
Applying the kubernetes overrides at ../kubeProviders/kubernetes/values.tmpl.yaml
error: failed to build the dependencies of chart '/tmp/jx-helm-apply-135587492/env': failed to run 'helm dependency build' command in directory '/tmp/jx-helm-apply-135587492/env', output: 'Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "charts.jetstack.io" chart repository
...Successfully got an update from the "charts.bitnami.com" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "jenkins-x" chart repository
...Successfully got an update from the "chartmuseum.jenkins-x.io" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 6 charts
Downloading jxboot-resources from repo http://chartmuseum.jenkins-x.io
Downloading tekton from repo http://chartmuseum.jenkins-x.io
Downloading prow from repo http://chartmuseum.jenkins-x.io
Downloading lighthouse from repo http://chartmuseum.jenkins-x.io
Save error occurred:  could not download http://chartmuseum.jenkins-x.io/charts/lighthouse-0.0.635.tgz: Get http://chartmuseum.jenkins-x.io/charts/lighthouse-0.0.635.tgz: dial tcp: lookup chartmuseum.jenkins-x.io on 8.8.8.8:53: read udp 192.168.122.154:53471->8.8.8.8:53: i/o timeout
Deleting newly downloaded charts, restoring pre-update state
Error: could not download http://chartmuseum.jenkins-x.io/charts/lighthouse-0.0.635.tgz: Get http://chartmuseum.jenkins-x.io/charts/lighthouse-0.0.635.tgz: dial tcp: lookup chartmuseum.jenkins-x.io on 8.8.8.8:53: read udp 192.168.122.154:53471->8.8.8.8:53: i/o timeout'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''



### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->

### Operating system / Environment

<!--
In which environment are you running the jx CLI?
-->

**Comment by SahuBhaskar** [comment]
root@Kube-01:~# jx install --provider=kubernetes --on-premise
Command "install" is deprecated, it will be removed on Jun 1 2020. We now highly recommend you use jx boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details.
? Configured Jenkins installation type: Serverless Jenkins X Pipelines with Tekton

Context "kubernetes-admin@kubernetes" modified.
Git configured for user: CI-CD-jenkinsx-kubernetes and email bhaskar467@gmail.com
Helm installed and configured
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Using external IP: 192.168.122.154
You can now configure a wildcard DNS pointing to the new Load Balancer address 192.168.122.154
If you don't have a wildcard DNS setup then create a DNS (A) record and point it at: 192.168.122.154, then use the DNS domain in the next input...

If you do not have a custom domain setup yet, Ingress rules will be set for magic DNS nip.io.
Once you have a custom domain ready, you can update with the command jx upgrade ingress --cluster
? Domain 192.168.122.154.nip.io
nginx ingress controller installed and configured
Set up a Git username and API token to be able to perform CI/CD
? Do you wish to use SahuBhaskar as the local Git user for github.com server: Yes
Select the CI/CD pipelines Git server and user
? Do you wish to use github.com as the pipelines Git server: Yes
Setting the pipelines Git server https://github.com and user name SahuBhaskar.
Enumerating objects: 1440, done.
Total 1440 (delta 0), reused 0 (delta 0), pack-reused 1440
Updating Secret jx-install-config in namespace jx
? Defaulting workload build pack: Kubernetes Workloads: Automated CI+CD with GitOps Promotion
Setting the team build pack to kubernetes-workloads repo: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git ref: master
Installing jx into namespace jx
Installing jenkins-x-platform version: 2.0.2271

WARNING: waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx
Configuring the TeamSettings for ImportMode Jenkinsfile
Configure Jenkins API Token
waiting up to 0s for the Jenkins server to be healthy at URL http://jenkins.jx.192.168.122.154.nip.io/login

**Comment by SahuBhaskar** [comment]
Its sucking here since last 2 hours...

**Comment by daveconde** [comment]
What version of jx are you using?

**Comment by SahuBhaskar** [comment]
Can any one tell me 

> What version of jx are you using?

root@Kube-01:~# jx version
NAME               VERSION
jx                 2.1.62
jenkins x platform 2.0.2271
Kubernetes cluster v1.15.11
kubectl            v1.13.2
helm client        2.12.2
git                2.27.0
Operating System   Ubuntu 16.04.6 LTS


verifying packages

**Comment by SahuBhaskar** [comment]
> What version of jx are you using?

root@Kube-01:~# jx version
NAME               VERSION
jx                 2.1.65
Kubernetes cluster v1.15.11
kubectl            v1.13.2
helm client        2.12.2
git                2.27.0
Operating System   Ubuntu 16.04.6 LTS


verifying packages
