### ISSUE TITLE
move the jx APIs (crds) to a separate git repository

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#7326]
it would be awesome to move the apis package https://github.com/jenkins-x/jx/tree/master/pkg/apis/jenkins.io into a separate git repository so its super easy for any git repository to reuse the structs with a flexible set of go + go module versions and dependencies.

thankfully the apis package has pretty minimal dependencies; though the extensions code brings in lots of stuff:
https://github.com/jenkins-x/jx/blob/master/pkg/apis/jenkins.io/v1/types_extensions.go

it'd be good to move the extensions functions into a separate package in jx so that folks can consume a tiny minimal go package for the jx CRDs

**Comment by garethjevans** [comment]
This would be great to do, would you see us generating the clients in there too?  Am also wondering if we should include the boot install requirements, as these are depended on by the teamSettings crd.

**Comment by hferentschik** [comment]
Would this include structs like `RequirementsConfig` as well? Should that become a CRD anyways?

**Comment by hferentschik** [comment]
A few more thoughts/questions:

- where do we do the go client generation in this case? As part of the new repo, so that the go-client is then coming in via the dependency to this new repository
- how are we going to version/evolve CRDs then?
- can we until we are able to control version numbers better switch to a manual release of this library

**Comment by jstrachan** [comment]
I wonder if we put the client generation in the new repository & try it out?

To start with I wondered if we just did `apis` and then thought about the `ProjectConfig` / `RequirementsConfig ` later on?

Maybe eventually we can make a real CRD kind for `Requirements` and `ProjectConfig` in this APIs repository & move most of the structs there?

In terms of release numbers how about we start at 1.0.0 and do automated CI/CD releases at 1.0.1, 1.0.2 etc for now? We can always manually bump the releases to minor/major versions at a later date?

**Comment by garethjevans** [comment]
Starting with https://github.com/jenkins-x/jx-client/pull/1, will add the client generation tomorrow

**Comment by garethjevans** [comment]
Client generation is working nicely, although the dependency versions don't play nicely with JX at the moment

We need https://github.com/jenkins-x/jx/pull/7313 to merge before we can integrate this with JX.
