### ISSUE TITLE
unable to install Jenkins X on already available cluster in AWS

### ISSUE THREAD

**Issue by vivekthangathurai** [jenkins-x/jx#7329]
### Summary 
I am trying to install Jenkins x on a on-prem cluster already created  using `jx boot` and receiving an error.

### Steps to reproduce the behavior
     cluster is already present in AWS
     run ```jx boot```
### Expected behavior

    jx should start installing Jenkins X

### Actual behavior
```
error: You are not currently connected to a cluster, please connect to the cluster that you intend to jx boot
Alternatively create a new cluster using jx create cluster
```
### Jx version
The output of `jx version` is:

```
2.1.35
```

### Kubernetes cluster

AWS Kube cluster. It was created before using terraform.

### Operating system / Environment
Mac OS Catalina 10.15.4

**Comment by nodece** [comment]
Could you try `jx boot -r jx-requirements.yml`?

**Comment by vivekthangathurai** [comment]
No, It did not work.
Note:  `kubectl get ns` works  and also the cluster uses azure authentication so my user id has access to it. I am not sure how jx connects, maybe can I pass the authentication?

**Comment by nodece** [comment]
@vivekthangathurai Could you set context by `jx context`?

**Comment by vivekthangathurai** [comment]
@nodece No, does not work. I get the same error.

**Comment by ankitm123** [comment]
Can you paste the output of `kubectl config get-contexts` and your jx-requirements.yml file?

**Comment by vivekthangathurai** [comment]
@ankitm123 
context output:
```
*         crashburn.infra.use1                          crashburn.infra.use1                          appdirect-crashburn.io                        default
          docker-desktop                                docker-desktop                                docker-desktop                                
          docker-for-desktop                            docker-desktop                                docker-desktop                                
          gke_futureci_us-central1-a_jenkins-1          gke_futureci_us-central1-a_jenkins-1          gke_futureci_us-central1-a_jenkins-1          jx
          gke_futureci_us-central1-c_jenkinsx           gke_futureci_us-central1-c_jenkinsx           gke_futureci_us-central1-c_jenkinsx           jx
          gke_futureci_us-central1-c_jenkinsx-cluster   gke_futureci_us-central1-c_jenkinsx-cluster   gke_futureci_us-central1-c_jenkinsx-cluster   jx
          gke_jenkinsx-277315_us-central1-a_jenkinsx    gke_jenkinsx-277315_us-central1-a_jenkinsx    gke_jenkinsx-277315_us-central1-a_jenkinsx    
          gke_jenkinsx-278806_us-central1-a_jenkinsx    gke_jenkinsx-278806_us-central1-a_jenkinsx    gke_jenkinsx-278806_us-central1-a_jenkinsx    jx
```

**Comment by ankitm123** [comment]
Your cluster name is set to jenkinsx? Should match the real cluster name, right?
Also add `terraform: true` since the cluster was created using terraform.

**Comment by vivekthangathurai** [comment]
No, even after using the correct cluster name an/or `terraform: true` . it does not work, fails with same error.

**Comment by ankitm123** [comment]
I have very limited idea about azure (Is it azure AD?), if you can point me to some docs, I can take a look.
Also, you should change this from `provider: kubernetes` to `provider: aws` and remove this line:
`project: jenkinsx-128806`

PS: Did you something special for kubectl to talk to your cluster?

**Comment by vivekthangathurai** [comment]
yes, Azure AD. 
I tried with the log level and get the same error, no extra information.
Yes, we did a configuration, btw azure AD has problems with lower verison of kubectl clients so we have latest `1.18.2` and the configuration involved 

- adding a configuration to `$HOME/.kube/some.config` 
```
apiVersion: v1

clusters:
- cluster:
    certificate-authority-data: 
    server: https://xxxxx
  name: cluster-name

- context:
    cluster: cluster-name
    namespace: default
    user: azure-user-group
  name: cluster-name

kind: Config
preferences: {}
users:
- name: azure-user-group
  user:
    auth-provider:
      config:
        apiserver-id: xxxx
        client-id: xxxxx
        tenant-id: xxxxx
      name: azure
```
-  while trying a command, it asks to setup the account with microsoft authenticator.

once the above steps are done, it is just one time. I am able to access kubectl.
I can try to get more information on how authentication happens from the team which set it up.

**Comment by ankitm123** [comment]
Even if you get past the connection issue, kubectl 1.18.2 is not going to work with jx (internally it uses 1.13.2 version).

**Comment by vivekthangathurai** [comment]
yes, maybe. I understand jx uses its own kubectl client version. first, we need to understand this issue of failing to connect to the cluster?

**Comment by ankitm123** [comment]
It would be nice to get some information about the authentication, I can take a look after that.

**Comment by vivekthangathurai** [comment]
@ankitm123 I have some information.
when I use `kubectl` it is read-only on the cluster we have. we use `kubectl sudo` to do admin commands. 
so kubectl command would look like `kubectl --as=foo --as-group=system:masters some admin command`, here `foo` is a user.
Does jx handle this kind of command? how can we do it using jx?

**Comment by vivekthangathurai** [comment]
@ankitm123 I was able to identify the issue related to azure auth. a plugin for kube client was missing that is the reason for the error. I ran into another issue for which I need to impersonate the user and group for the Kube client, otherwise I am seeing authorize error while creating namespaces and other resources. is there a way to impersonate user and group in jx ?
