### ISSUE TITLE
RequirementsConfig#OverrideRequirementsFromEnvironment populates nil values 

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#7331]
Despite defining some structs in `RequirementsConfig` as pointers and setting the _omitempty_ property, the final `jx-requirement.yml` after running `jx boot` contains empty values for all possible struct even if not specified.

The cause lies in `RequirementsConfig#OverrideRequirementsFromEnvironment` which in turn calls `err := envconfig.InitWithOptions(&c, envconfig.Options{AllOptional: true})` which is responsible for the population of the empty structs.

This behaviour makes it hard to evolve the requirements in a backwards-compatible manner by introducing new pointer-based configuration options.

**Comment by hferentschik** [comment]
relates to #7288

**Comment by abayer** [comment]
Well, that's bonkers.
