### ISSUE TITLE
GH Webhooks never reach lighthouse. "Failure when receiving data from the peer"

### ISSUE THREAD

**Issue by Vilsol** [jenkins-x/jx#7332]
### Summary 

My Github webhooks are failing to be delivered. But I am able to curl the URL without payload without any issues (receiving errors about missing webhook headers).

At first I was using the default nip.io dns forwarder. I considered that it could be the issue so I switched to a custom domain (and made sure that nginx ingress controllers update) and that did not resolve the issue.

I have also tested with and without a reverse proxy (Cloudflare) and that was not the cause of the issue.

### Steps to reproduce the behavior

Completely fresh `jx boot`. Then using the quickstart node-http example.

### Expected behavior

For webhook to reach lighthouse and be processed.

### Actual behavior

Error from Github webhook logs: "We couldn’t deliver this payload: Failure when receiving data from the peer"

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.65-dev+22dc07818
Kubernetes cluster v1.18.3
kubectl            v1.13.2
helm client        2.12.2
git                2.25.1
Operating System   Ubuntu 20.04 LTS
```

### Kubernetes cluster

I am using an on-prem cluster. It was created with `jx boot`. With very few hiccups I have got it running basically out of the box. This is the only issue I'm unsure how to debug.

### Operating system / Environment

Ubuntu 20.04 LTS

**Comment by aaomidi** [comment]
Running into the same issue here.

**Comment by abayer** [comment]
What if anything are you seeing in the `lighthouse-webhook` deployment’s pods’ logs?

**Comment by Vilsol** [comment]
Sorry, completely my mistake. I investigated further and found that the call never even reaches the cluster. It ended up being a misconfigured firewall.
