### ISSUE TITLE
jx delete application doesnt remove application resources

### ISSUE THREAD

**Issue by joostvdg** [jenkins-x/jx#7336]
### Summary 

Deleting an application from Jenkins X leaves application resources behind in the namespaces of the environments it ran in.

### Steps to reproduce the behavior

* create cluster via JX GCP Terraform
* install JX via JX Boot
* create custom environment with `jx create env`
* create new quickstart (go) with `jx create quickstart` ( `jx-go-demo-01`)
* delete application via `jx delete applications jx-go-demo-01`

### Expected behavior

After all environments are updated, the application doesn't run in any of them anymore.

### Actual behavior

The application is removed from the `env/requirements.yaml` files, but still runs in the cluster.

#### JX Get Applications

```sh
APPLICATION    STAGING PODS URL                                                        PRODUCTION PODS URL
jx-go-demo-01  0.0.2   1/1  https://jx-go-demo-01-jx-staging.staging.jxgke.kearos.net
```

#### Deletion output

```sh
Removing application jx-go-demo-01 from environment Production
WARNING: No changes made to the source code in /var/folders/f_/mpwdv8s16r7_zt43r3r7k20w0000gn/T/create-pr803674921. Code must be up to date!
Removing application jx-go-demo-01 from environment Staging
Created Pull Request: https://github.com/joostvdg/env-jxgke-staging/pull/13
Waiting for pull request https://github.com/joostvdg/env-jxgke-staging/pull/13 to merge
Request https://github.com/joostvdg/env-jxgke-staging/pull/13 is merged!
Removing application jx-go-demo-01 from environment Testenv-01
WARNING: No changes made to the source code in /var/folders/f_/mpwdv8s16r7_zt43r3r7k20w0000gn/T/create-pr194170691. Code must be up to date!
Deleted Application(s): jx-go-demo-01
```

#### Kubectl get pods

```sh
NAME                                READY   STATUS    RESTARTS   AGE
jx-jx-go-demo-01-77656686b4-9vpmx   1/1     Running   0          7m30s
```

### Jx version

```
NAME               VERSION
jx                 2.1.65
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.16.7
helm client        2.16.1
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.5 build 19F96
```

### Kubernetes cluster

GKE cluster running `v1.14.10-gke.36`, created via Jenkins X's terraform module for GCP.

### Operating system / Environment

```sh
Operating System   Mac OS X 10.15.5 build 19F96
```

**Comment by cagiti** [comment]
@joostvdg : would you be able to share information when executing the command with verbose logging? Thanks
