### ISSUE TITLE
Rename Buildpacks because they aren't Buildpacks

### ISSUE THREAD

**Issue by jkutner** [jenkins-x/jx#7343]
### Summary 

I work on the Cloud Native Buildpacks project (https://buildpacks.io), and I'd like to talk to someone about [jenkins-x buildpacks](https://jenkins-x.io/docs/create-project/build-packs/)--specifically about naming because they are a different thing. We're interested in doing some integration of our buildpacks with Jenkins, but this could get very confusing for users. 

I also started [a conversation on Slack](https://kubernetes.slack.com/archives/C9LTHT2BB/p1575917745215800), and I'm happy to discuss there if it's better.

The alternative names proposed in the thread are:

* pipeline libraries
* app templates
* boilerplate
* language packs
* framework packs
* BuildStrategy
* BuildPolicy

**Comment by cagiti** [comment]
another alternative name: `pipeline resources`

**Comment by deanesmith** [comment]
Hi @jkutner, to what extent would the renaming need to be?  None of it is entirely simple but certainly possible and scope establish how impactful this would be.

**Comment by jkutner** [comment]
@deanesmith These are the main places I've seen the term used:

* https://github.com/jenkins-x-buildpacks
* https://jenkins-x.io/docs/resources/guides/extending-jx/buildpacks/
* https://jenkins-x.io/docs/create-project/build-packs/

So I think the Github repo will need to be renamed, and then the documentation updated (possible including some history on the renaming and an explanation). 

Please let me know what I can do to help make the transition smoother.

**Comment by jkutner** [comment]
Hi, i wanted to bump this to see if there's anything I can do to help move it forward. Thanks!

/cc @deanesmith @cagiti @garethjevans

**Comment by MarckK** [comment]
Hi @jkutner, thank you for raising this issue.
We understand your concern regarding potential confusion over Buildpacks as Jenkins X uses the term and Cloud Native Buildpacks, especially as integrations with Jenkins are created. To help clarify the difference, we will change the name, within the Jenkins X documentation, of the Buildpacks in Jenkins X to 'Jenkins X Buildpacks'.

As Jenkins X evolves, the way Jenkins X enables users to transform source code into an application which can be deployed on Kubernetes will change. As Jenkins X evolves the functionality currently provided by Buildpacks that feature/functionality will be renamed entirely.

**Comment by jkutner** [comment]
@MarckK That's definitely not what I was hoping to hear. The "Jenkins X Buildpacks" name is likely to confuse end-users of both [Buildpacks](https://buildpacks.io) and Jenkins-x. It also complicates our path to creating a proper buildpack<>jenkins-x integration.

Even a change as simple as "Jenkins X Packs" would go a long way to helping the community understand these concepts.

If you decide to continue using the "buildpack" name for things that are not buildpacks, **can you please include a footnote in the documentation that explains the difference?**

**Comment by jkutner** [comment]
Was the name changed? "Jenkins X Buildpacks" aren't Buildpacks.

**Comment by deanesmith** [comment]
FYI @MarckK

**Comment by MarckK** [comment]
Hi @jkutner, for Jenkins X 3, we are no longer using the term Buildpacks in any way. Therefore, closing this issue.

We’ve moved what used to be called build packs to a [pipeline catalog](https://github.com/jenkins-x/jx3-pipeline-catalog) which contains pipelines, dockerfiles and charts that get sync’d into users application git repos using kpt.
