### ISSUE TITLE
How set namespace for app when using GitOps

### ISSUE THREAD

**Issue by nodece** [jenkins-x/jx#7347]
### Summary 
jx supports set namespace for app,  but It doesn't support set namespace in GitOps environment.  I don't know how to resolve.

### Steps to reproduce the behavior
```
kubectl create ns kubeless 
jx add app jx-app-kubeless -n kubeless
```

### Expected behavior
It works fine.

### Actual behavior
unable to specify --kubeless when using GitOps for your dev environment 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.62
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.24.3 (Apple Git-128)
Operating System   Mac OS X 10.15.5 build 19F101
```

### Diagnostic information

The output of `jx diagnose --show=version` is:

```
Running in namespace: jx

Jenkins X Version:
NAME               VERSION
jx                 2.1.62
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.13.2
helm client        2.12.2
git                2.24.3 (Apple Git-128)
Operating System   Mac OS X 10.15.5 build 19F101


verifying packages

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

Using terraform to create GKE.

The cluster on GKE created with Terraform v0.12.26

### Operating system / Environment

 Mac OS X 10.15.5 build 19F101

**Comment by nodece** [comment]
`jx namespace` can  meet my needs. But I'm not sure if have better way to resolve the namespace.

**Comment by jstrachan** [comment]
the way we install charts with `jx add app` doesn't let us use a different namespace per app. Though we hope to have a way to fix this via different mechanisms later on (e.g. helm 3)
