### ISSUE TITLE
Webook on git says : We couldn’t deliver this payload: Failure when receiving data from the peer

### ISSUE THREAD

**Issue by Jas659** [jenkins-x/jx#7360]
Below is webook url with public ip of jenkins:

http://10.236.6.30:8080/github-webhook/

Jobs are not triggering on Jenkins 

My git repo configured on jenkins is https://github.com/Jas659/Jaspreet.git

Need to help to fix the above issue

**Comment by daveconde** [comment]
Hi @Jas659 Are you using Jenkins or Jenkins X?

**Comment by Jas659** [comment]
I have found the issue. I was using the public github  to connect to the jenkins on the private network which will not work
I will configure correctly now
