### ISSUE TITLE
Using 'jx delete branch ...' returns 'error: No servers available!`

### ISSUE THREAD

**Issue by lukaszlenart** [jenkins-x/jx#7361]
### Summary 

I want to remove merged branches from env repository. I've connected to our k8s cluster using `aws eks ...` and then switched to a proper namespace using `jx ns jx-development`.

Running `jx delete branch ...` always issue the same error message.

### Steps to reproduce the behavior

Use
```
jx delete branch -o <org> -n <env repo> -f <bot name> -a --merged
```

### Actual behavior

```
error: No servers available!
```

### Jx version

The output of `jx version` is:

```
Version        2.1.75
Commit         4a33617
Build date     2020-06-18T20:24:05Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose --show=version` is:

```
Flag --show has been deprecated, use jx diagnose <object> instead. This will be removed on July 1, 2020
Running in namespace: jx-development
Version        2.1.75
Commit         4a33617
Build date     2020-06-18T20:24:05Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.14.9-eks-f459c0
kubectl (installed in JX_BIN) v1.16.3
git                           2.26.0
Operating System              Mac OS X 10.15.5 build 19F101

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

EKS, it was created by our DevOps (but left the project), I assume he used Jenkins X documented approach

### Operating system / Environment

macOS, K8s on AWS, multiple namespaces

**Comment by lukaszlenart** [comment]
I will answer myself, switch to `jx` namespace using `jx ns jx`

**Comment by deanesmith** [comment]
@lukaszlenart was there an improvement to the command or the documentation that would have assisted you with finding the answer?

**Comment by lukaszlenart** [comment]
We have three environments: Development, Staging and Demo (Production to come). Jenkins X is using a term `Dev` environment which was confusing for me. Maybe because I'm not a DevOps guy and didn't create our cluster from scratch. I think mentioning that the `Dev` env by default is the `jx` namespace would help.
