### ISSUE TITLE
jx boot stops after configuring non default docker registry

### ISSUE THREAD

**Issue by fakoe** [jenkins-x/jx#7364]
### Summary 
I'm just starting to understand Openshift, Kubernetes and Jenkins / Jenkins X.
I created an Openshift cluster on a local Ubuntu 18.04 VM for myself, beeing able to learn and test.
I used the simple command 'oc cluster up', to create the local cluster. 

I followed the recommendations to fork the git and clone it. 
I changed the provider in the jx-requirements.yaml to 'openshift' and ran jx boot

After I entered a non default docker registry (I pulled one locally) the boot process is interrupted with the following error message(s):

```
Do you want to configure non default Docker Registry? true [Automatically accepted existing value]
Docker Registry Url http://127.0.0.1:5000/v2 [Automatically accepted existing value]
Docker Registry username admin [Automatically accepted existing value]
Docker Registry password *** [Automatically accepted existing value]
Docker Registry email somename@lobster.de [Automatically accepted existing value]
error: error enabling access to an external docker registry: failed to convert secret URLs in parameters file /root/jenkins-x-boot-config/env/parameters.yaml: replacing vault paths in adminUser:
  password: local:127-0-0-1:8443/adminUser:password
  username: admin
docker:
  email: somename@lobster.de
  password: local:127-0-0-1:8443/docker:password
  url: http://127.0.0.1:5000/v2
  username: admin
enableDocker: true
pipelineUser:
  email: somename@lobster.de
  token: local:127-0-0-1:8443/pipelineUser:token
  username: fakoe
prow:
  hmacToken: local:127-0-0-1:8443/prow:hmacToken
: cannot parse "127-0-0-1:8443/adminUser:password" as path:key
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create values --name parameters' command in directory 'env', output: ''
```

### Steps to reproduce the behavior

- VMware Ubuntu 18.04 vm
- Follow https://computingforgeeks.com/how-to-setup-openshift-origin-on-ubuntu/ for setting up the openshift cluster
- oc cluster up
- login as admin, then system admin
- oc adm policy add-cluster-role-to-user cluster-admin admin
- oc adm policy add-scc-to-group anyuid system:authenticated

- Create local docker registry:
```
 docker run -d \
  -p 5000:5000 \
  --restart=always \
  --name registry \
  -v /mnt/registry:/var/lib/registry \
  registry:2
```

- fork git  .../jenkins-x/jenkins-x-boot-config and clone
- change into folder and edit jx-requirements.xml => provider: openshift
- run jx boot
- follow instructions
- declare local docker registry

### Expected behavior

jx boot finishes its installation

### Actual behavior

 jx boot got interrupted right after declaring the local docker repository

### Jx version

The output of `jx version` is:

```
Version        2.1.75
Commit         4a33617
Build date     2020-06-18T20:24:05Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose --show=version` is:

```
Running in namespace: jx
Version        2.1.75
Commit         4a33617
Build date     2020-06-18T20:24:05Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.11.0+d4cacc0
kubectl (installed in JX_BIN) v1.13.2
helm client                   2.12.2
git                           2.17.1
Operating System              Ubuntu 18.04.4 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

Locally installed Openshift cluster
I used the following instructions to create it:
https://computingforgeeks.com/how-to-setup-openshift-origin-on-ubuntu/

### Operating system / Environment

Ubuntu 18.04 VM on VMware Workstation 15

**Comment by daveconde** [comment]
@hferentschik Can you have a look at this one please
