### ISSUE TITLE
TriggerPipelineTime option

### ISSUE THREAD

**Issue by hekonsek** [jenkins-x/jx#737]
Hi,

I see that you guys have worked on `TriggerPipelineTime` option which allows to specify for how long jx should wait for GitOps webhooks to be invoked before proceeding with promotion. Unfortunately you reverted it [1] due to some bugs.

When do you plan to bring it back to life again? This webhook issue is a huge pain for minikube users :( . 

[1] https://github.com/jenkins-x/jx/commit/51512fd94af295cc4fd9714be3ecc9d275b8f9d6

**Comment by jstrachan** [comment]
yeah - I've no idea why that patch broke things on GKE yet ;) would be good to try noodle my crappy code and see if we can spot what could be causing the problem maybe? we can definitely take another attempt at fixing it

**Comment by hekonsek** [comment]
@rawlingsj Good to see you as well guys! ;)

I think that @jstrachan idea sounds like a good plan. I will restore this commit locally and see if I can see why it breaks GKE.

**Comment by hekonsek** [comment]
FYI This issue has become a lower priority for me now for a while, so I won't be working on this now. I'd like to focus more on deploying Spring and Vert.x applications into AWS-based JX cluster. Then I will probably return to this one.
