### ISSUE TITLE
fatal: ambiguous argument '${env.GIT_COMMIT}': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by pawan22sfdl** [jenkins-x/jx#7375]
### Summary 

I am doing a differential deployment in salesforce using jenkins. So i wrote a groovy script but its throwing some errors which i cannot able to solve.

### Steps to reproduce the behavior
My Groovy Script below :-

![image](https://user-images.githubusercontent.com/63653027/85381399-d6365300-b535-11ea-939d-a46cf26c9a1b.png)

### Expected behavior

It should run the code and make a folder with changed files.

### Actual behavior
throwing error
diffBuilderWithGitCommit:
   [delete] Deleting directory C:\Program Files (x86)\Jenkins\workspace\GitDiff\deploy-sf
    [mkdir] Created dir: C:\Program Files (x86)\Jenkins\workspace\GitDiff\deploy-sf
     [echo] Current GIT Commit : ${env.GIT_COMMIT}
     [echo] Previous Known Successful GIT Commit : ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}
     [exec] Result: 128
     **[echo] fatal: ambiguous argument '${env.GIT_COMMIT}': unknown revision or path not in the working tree.
     [echo] Use '--' to separate paths from revisions, like this:
     [echo] 'git <command> [<revision>...] -- [<file>...]'**

**Comment by garethjevans** [comment]
Hi @pawan22sfdl, Can you open this as a defect against Jenkins (rather than Jenkins X)?

**Comment by pawan22sfdl** [comment]
@garethjevans can you please tell me how to do that , as i am not finding jenkins option?
