### ISSUE TITLE
JX Apps get stale

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#7379]
So I've been using JX app replicator for a while - with more use the liveness probe starts to fail and then secrets don't get replicated and things start to fail as they are missing secrets. Perhaps upgrading to the latest version of replicator will help?

It seems the app replicator is quite far behind the repo it was originally forked from.

![image](https://user-images.githubusercontent.com/474827/85422450-9d9d7600-b543-11ea-85ff-0bfdb5f3e362.png)

I'd love to try the latest version but looking at the commit differences makes it seem like it may be a bit of an undertaking.

For backups, the velero chart that is being used is not even active anymore and has moved to an entirely different repository.

![image](https://user-images.githubusercontent.com/474827/85422565-c02f8f00-b543-11ea-857c-e94a13f89f44.png)

Granted, deprecating a chart and moving it somewhere else is an uncommon scenario. It seems the biggest problem with apps, IMO, is they are quickly wrapped and then not kept up to date for many months at a time.

They are really useful in getting things running quickly, but over time they start to become stale and missing the fixes, features, and updates that are available in the main repos or charts.

Given these apps are in the JX docs and have integrations with JX of varying degrees I understand locking them down at a specific version, though at the same time there are plenty of reasons for wanting to make sure new bug and security fixes make it into the apps.

Perhaps some level of automation could help - for example, using something like renovate or dependabot would keep simple charts like prometheus up to date by making PRs to update the [requirements.yaml](https://github.com/jenkins-x-apps/jx-app-prometheus/blob/master/jx-app-prometheus/requirements.yaml) file

Also curious of what level of integration testing apps go through - especially ones that are brought up in the JX docs such as backups and replicator.

**Comment by deanesmith** [comment]
Same problem applies to quickstarts.  Definitely worthy of looking in to a solution.
