### ISSUE TITLE
Placeholder for Discussion: Helm 3

### ISSUE THREAD

**Issue by ethangj** [jenkins-x/jx#7380]
This is an issue for community discussion and input on the roadmap, regarding helm 3.

Please provide all thoughts, opinions, and input on this issue and we will take it up further as an enhancement proposal as we progress towards working on it.

**Comment by deanesmith** [comment]
It would be good to know specific use cases for Helm 3.

**Comment by searsaw** [comment]
[Helm 2's EOL is coming quickly](https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan). I believe it will be this coming November. Upgrading to Helm 3 is important.

**Comment by MarckK** [comment]
This under active discussion as an enhancement proposal. 

Closing in favour of https://github.com/jenkins-x/enhancements/issues/34.
