### ISSUE TITLE
Placeholder for Discussion: Tekton Catalog

### ISSUE THREAD

**Issue by ethangj** [jenkins-x/jx#7381]
This is an issue for community discussion and input on the roadmap, regarding integration with the Tekton catalog.

Please provide all thoughts, opinions, and input on this issue and we will take it up further as an enhancement proposal as we progress towards working on it.

**Comment by MarckK** [comment]
This proposal has been added as a proposed enhancement to Jenkins X: https://github.com/jenkins-x/enhancements/issues/37

Closing this issue as discussion and planning for support of Tekton catalog is being brought forward with the above Jenkins X enhancement issue.

**Comment by jstrachan** [comment]
here's an implementation: https://jenkins-x.io/docs/v3/guides/pipeline-catalog/
