### ISSUE TITLE
Placeholder for Discussion: Custom pipeline catalogs

### ISSUE THREAD

**Issue by ethangj** [jenkins-x/jx#7382]
This is an issue for community discussion and input on the roadmap, regarding custom pipeline catalogs.

Please provide all thoughts, opinions, and input on this issue and we will take it up further as an enhancement proposal as we progress towards working on it.

**Comment by MarckK** [comment]
Closing as discussion on Jenkins X enhancement proposals are active in [jenkins-x/enhancements](https://github.com/jenkins-x/enhancements)
