### ISSUE TITLE
Placeholder for Discussion: Major component pluggability

### ISSUE THREAD

**Issue by ethangj** [jenkins-x/jx#7383]
This is an issue for community discussion and input on the roadmap, regarding major component pluggability.

Please provide all thoughts, opinions, and input on this issue and we will take it up further as an enhancement proposal as we progress towards working on it.

**Comment by MarckK** [comment]
Closing this issue, as discussion has moved on to the following enhancement proposal: https://github.com/jenkins-x/enhancements/issues/35
