### ISSUE TITLE
Placeholder for Discussion: Technical debt reduction / Improved architecture

### ISSUE THREAD

**Issue by ethangj** [jenkins-x/jx#7384]
This is an issue for community discussion and input on the roadmap, regarding technical debt reduction and improved architecture.

Please provide all thoughts, opinions, and input on this issue and we will take it up further as an enhancement proposal as we progress towards working on it.

**Comment by jstrachan** [comment]
this enhancement proposal looks like a good start: https://github.com/jenkins-x/enhancements/pull/31 see the [notes](https://github.com/garethjevans/enhancements/tree/decomposition/proposals/5)

**Comment by MarckK** [comment]
Closing as this discussion is happening on https://github.com/jenkins-x/enhancements/pull/31, based on the [notes](https://github.com/garethjevans/enhancements/tree/decomposition/proposals/5).
