### ISSUE TITLE
Add an option to print machine readable output from jx

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#7390]
### Summary 
It would be nice to have an option which can format the output from jx for use by other tools (Discussed in a PR with @hferentschik). A good example is the `o` flag of `kubectl`.
```
kubectl get pods -o json
``` 
Supported formats could include:
* json
* yaml
* toml

**Comment by sladyn98** [comment]
@ankitm123 Any ideas on how to begin with this
