### ISSUE TITLE
When using GitOps to remove a SourceRepository, it doesn't get removed from the cluster

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#7393]
### Summary 

This is something that has come out of the tekton-weasel rebuild.

### Steps to reproduce the behavior

* Remove `SourceRepository` from environment repo
* Run master build

### Expected behavior

* SourceRepository is removed from the cluster

### Actual behavior

* Currently it doesn't get deleted.

**Comment by patrickleet** [comment]
On the flipside, `jx delete application` removes it from the config, but not the GitOps repo
