### ISSUE TITLE
Evaluate available linters from golangci-lint

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#7403]
### Summary 
In addition to the linters we have enabled, we should evaluate some of the other [linters](https://golangci-lint.run/usage/linters/) that golangci-lint provides . At a minimum, we should enable staticcheck (a better version of govet), bodyclose, nakedreturn, dupl, golint and gocritic.

**Comment by garethjevans** [comment]
Enabling these extra linters brings in `229` issues.

**Comment by garethjevans** [comment]
Totally misread the output there, it brings inn `10982` issues

**Comment by ankitm123** [comment]
Yup, I can tackle it in a PR, or may be break it into multiple PRs.

**Comment by garethjevans** [comment]
bodyclose & nakedreturn are probably the easiest to start with.

**Comment by ankitm123** [comment]
Once ur PR is merged, I will start with mine :+1:
