### ISSUE TITLE
jx add app does not accept chart values when GitOps enabled

### ISSUE THREAD

**Issue by mgoltzsche** [jenkins-x/jx#7412]
### Summary 
`jx add app` does not accept values when GitOps enabled.
This stops one from installing any helm chart (which may not even have a `values.schema.json`) as app.
Instead one must install the chart with default values first and then apply the changes within the environment repo in a second step.

### Steps to reproduce the behavior
```
jx add app oauth2-proxy --alias=oauth2-proxy-jxui --repository=https://kubernetes-charts.storage.googleapis.com/ --version=2.2.2 --set mykey=myval
```

### Expected behavior
The app should be installed with values explicitly provided by the user.

### Actual behavior
`jx add app` output:
```
error: Invalid option: --set [mykey=myval]
unable to specify --set when using GitOps for your dev environment
```

### Jx version

The output of `jx version` is:

```
Version        2.1.79
Commit         9a5cb37
Build date     2020-06-22T16:31:09Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.79
Commit         9a5cb37
Build date     2020-06-22T16:31:09Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.14.10-gke.36
kubectl (installed in JX_BIN) v1.13.2
helm client                   2.12.2
git                           2.17.1
Operating System              Ubuntu 18.04.4 LTS
```

### Kubernetes cluster
v1.14.10-gke.36

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment
Ubuntu 18.04

**Comment by nodece** [comment]
I think this is a good idea, if the feature is approved by Jenkins X team, I will make a PR as soon.
