### ISSUE TITLE
jx step tag can edit the wrong chart file

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#7417]
### Summary 

`jx step tag` looks for any `*/*/Chart.yaml`, and thus may edit the wrong chart file.

See: https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/step_tag.go#L281

### Steps to reproduce the behavior

Create a project and add in the `charts` directory another directory with lower alphabetic order as the project name, with a `Chart.yaml` file inside. When deploying a new version, `jx step tag` will edit that `Chart.yaml`, thus not updating the version or the real chart. the built chart will then have version `0.1.0`.

### Expected behavior

`charts/<app_name>/Chart.yaml` should have the priority, as it will be the right chart in 99.9% of cases. Moreover, it should have a consistent behavior with the step calling `helm template`.

### Actual behavior

It just takes the first `*/*/Chart.yaml` (except `preview`), no matter how unlikely it is.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1243
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.17.0
helm client        2.14.3
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

**Comment by hferentschik** [comment]
thanks for the explicit error report :-)
