### ISSUE TITLE
unknown config: tls with own cert

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/jx#7420]
### Summary 

Have no idea how to get tls going with our own wildcard cert.
The documentation doesn't explain much anywhere: 
https://jenkins-x.io/docs/install-setup/boot/ingress/
https://jenkins-x.io/docs/resources/guides/managing-jx/common-tasks/tls/

### Steps to reproduce the behavior

On a new EKS cluster, after running `jx boot`, and then updating jx-requirements.yml 
with the following, and uploaded (wildcard *.domain.com) cert secrets in the jx and kube-system namespaces (to be sure).
```
ingress:
  domain: domain.com
  externalDNS: true
  ignoreLoadBalancer: true
  namespaceSubDomain: -jx.
  tls:
    email: user@sample.com
    enabled: true
    production: true
    secretName: domain-tls
```

At the very least, this is a documentation gap.

Additional issue:
I don't know if I should open a separate issue for this, but I also need IP whitelist annotations on the ingresses and haven't had any luck getting jx boot to succeed with that.

### Expected behavior

Use named tls secret for tls on all ingresses.

### Actual behavior

The result was that the hook and nexus ingresses were upgraded to use Let'sEncrypt
and nothing happened for jenkins, jenkins-x-chartmuseum or jenkins-x-registry.

Nor was the webhook updated on the Github side to change it to https (I did that manually).

### Jx version

The output of `jx version` is:

```
Version        2.1.93
Commit         729fc2b
Build date     2020-06-30T16:56:20Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
NAME                          VERSION
Kubernetes cluster            v1.15.11-eks-af3caf
kubectl (installed in JX_BIN) v1.15.12
helm client                   2.16.7
git                           2.25.1
Operating System              Ubuntu 20.04 LTS
```

### Kubernetes cluster

eks, using terraform

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment
Ubuntu 20.04 LTS

**Comment by dicolasi** [comment]
I have the same problem.
