### ISSUE TITLE
How do I customize the scheduler?

### ISSUE THREAD

**Issue by yejiayu** [jenkins-x/jx#7427]
### Summary 
I want to add various GitHub checks to my `PR` through a custom scheduler, but I have looked for a long time for documentation tutorials. There is no place to explain what I should do except to find the CRD document of the scheduler.

I tried to imitate the configuration [here](https://github.com/jenkins-x/environment-oss-weasel-dev/blob/master/env/templates/jx-scheduler.yaml) and wrote a custom scheduler. Unfortunately, although he can work, it will not be shown in Github PR.

So, what should I do to achieve this effect?
![image](https://user-images.githubusercontent.com/10446547/86533437-dbb37600-bf03-11ea-8889-89ccdbab29f9.png)

**Comment by boriscosic** [comment]
I couldn't get this working with lighthouse and had much better success with prow.

I exported the default scheduler via `kubectl get default-scheduler -o yaml > custom-scheduler.yaml`. Customized it and then imported back with `kubectl apply -f custom-scheduler.yaml` and ran `jx step scheduler config apply --direct`.

Make sure you import the project with new scheduler `jx import -s custom-scheduler`. Hope that helps.

**Comment by yejiayu** [comment]
Thanks!
