### ISSUE TITLE
JX UI fails helm lint (helm 2.16.9)

### ISSUE THREAD

**Issue by marsdalesa** [jenkins-x/jx#7437]
### Summary 

While running `jx boot` within a jenkins-x-boot-config repository, on an existing EKS cluster with jx installed and that has JX UI installed (0.1.211), the lint checks fail with the following:

```
STEP: install-jenkins-x command: /bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders in dir: <repository-path>/env
Modified file <repository-path>/env/Chart.yaml to set the chart to version 1
creating the lock configmap jx-lock-jx
lock configmap jx-lock-jx created
Ignoring templates/.gitignore
Applying the kubernetes overrides at ../kubeProviders/eks/values.tmpl.yaml
cleaning the lock configmap jx-lock-jx
error: failed to lint the chart '/tmp/jx-helm-apply-468929571/env': failed to run 'helm lint --set tags.jx-lint=true --set global.jxLint=true --set-string global.jxTypeEnv=lint' command in directory '/tmp/jx-helm-apply-468929571/env', output: '==> Linting .
[ERROR] templates/: render error in "env/charts/jx-app-ui/charts/jxui/templates/deployment.yaml": template: env/charts/jx-app-ui/charts/jxui/templates/deployment.yaml:164:13: executing "env/charts/jx-app-ui/charts/jxui/templates/deployment.yaml" at <(include "jxui.auth.type" .) "basic">: can't give argument to non-function include "jxui.auth.type" .
Error: 1 chart(s) linted, 1 chart(s) failed'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

### Steps to reproduce the behavior

1. Fresh install jx on an AWS EKS cluster (allowing jx boot to install helm 2.12.2)
2. Install jx-ui (`jx add app jx-app-ui --version 0.1.211`)
3. Upgrade local helm binary to 2.16.9
4. Run `jx boot`

### Expected behavior

Expect lint checks to pass.

### Actual behavior

Lint checks fail

### Jx version

The output of `jx version` is:

```
Version        2.1.98
Commit         a6747c4
Build date     2020-07-09T15:16:45Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.98
Commit         a6747c4
Build date     2020-07-09T15:16:45Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.16.8-eks-fd1ea7
kubectl (installed in JX_BIN) v1.13.2
helm client                   2.16.9
git                           2.25.1
Operating System              Ubuntu 20.04 LTS

```

### Kubernetes cluster
AWS EKS 1.16.8
Created using Terraform

### Kubectl version
The output of `kubectl version --client` is:

```
lient Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

Ubuntu 20.04 LTS

**Comment by babadofar** [comment]
I get this error as well, running jx boot pipeline on tekton in kubernetes. It works for my when I run jx boot locally, as I didn't upgrade helm.  
I have removed the jx app UI. Still get this error after upgrading to the latest jx boot, version stream 9c6173aac8d4279d7af5f581fc30f4df3be9fb20

**Comment by ankitm123** [comment]
It's a bit weird that you get this error after removing the jx ui charts. Let me check why it is pulling the ui charts.

**Comment by babadofar** [comment]
Forget it, somebody must have sprinkled angel dust in my cpu, it works for me now. After re-adding and removing jx -ui-app.

**Comment by pablocaceresz** [comment]
I think I found the problem, to solve the problem install the helm binary version to 2.12.3
downgrade 2.16.9 -> 2.12.3
What do you think
Regards?

**Comment by ankitm123** [comment]
You should not be using cloudbees jx UI, instead use octant-jx: https://github.com/jenkins-x/octant-jx
