### ISSUE TITLE
question: how set DockerRegistryOwner/DockerRegistryOrg in jx-requirements.yml

### ISSUE THREAD

**Issue by nodece** [jenkins-x/jx#7453]
### Summary 

issues: #7446 , #7397 

If we cannot set correct DockerRegistryOwner/DockerRegistryOrg, jx will cannot push image to docker registry.

This is the source of the above issues.

I know that jx supports add `dockerRegistryOwner` to `jenkins-x.yml`, but I want to know that how set DockerRegistryOwner/DockerRegistryOrg in `jx-requirements.yml`, so when we create a quickstart project, we don't need to add `dockerRegistryOwner` to `jenkins-x.yml`. 

The following is get docker  registry org code for us know how it work: 

```go
func (o *CommonOptions) GetDockerRegistryOrg(projectConfig *config.ProjectConfig, repository *gits.GitRepository) string {
	answer := ""
	if projectConfig != nil {
		answer = projectConfig.DockerRegistryOwner
	}
	if answer == "" {
		teamSettings, err := o.TeamSettings()
		if err != nil {
			log.Logger().Warnf("Could not load team settings %s", err.Error())
		} else {
			answer = teamSettings.DockerRegistryOrg
		}
		if answer == "" {
			answer = os.Getenv("DOCKER_REGISTRY_ORG")
		}
		if answer == "" && repository != nil {
			answer = repository.Organisation
		}
	}
	return strings.ToLower(answer)
}
```

**Comment by patrickleet** [comment]
related https://github.com/jenkins-x/jx/issues/7424

**Comment by patrickleet** [comment]
doesn't seem like it could work how it is now

https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/jxboot-resources/values.tmpl.yaml#L67-L71

**Comment by patrickleet** [comment]
I had to create a new docker hub account that matched my org's github name

**Comment by patrickleet** [comment]
once you get that working you'll find you can't pull - you'll need to set up a secret of type `kubernetes.io/dockerconfigjson` with the file `.dockerconfigjson`

I created this in terraform using the kubernetes provider, and use jx-app-replicator to make it available to different namespaces.

In each app's chart's deployment.yaml you then need to add:

```
    spec:
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
{{- end }}
      containers:
```

**Comment by patrickleet** [comment]
To create with terraform, in your terraform project after `jx boot` has succeeded...

```
kubectl get secret jenkins-docker-cfg -o jsonpath="{.data.config\.json}" | base64 -D >> secret/docker-config.json
```

.gitignore that /secret folder...

Then

```
resource "kubernetes_secret" "regcred" {
  metadata {
    name      = "regcred"
    namespace = "jx"
    annotations = {
      "replicator.v1.mittwald.de/replication-allowed"            = "true"
      "replicator.v1.mittwald.de/replication-allowed-namespaces" = "jx-*"
    }
  }

  data = {
    ".dockerconfigjson" = "${file("./secret/docker-config.json")}"
  }

  type = "kubernetes.io/dockerconfigjson"
}
```

**Comment by nodece** [comment]
This is my solution: https://github.com/jenkins-x/jx/issues/7446#issuecomment-660475003.

I see your solution: https://github.com/jenkins-x/jx/issues/7424#issuecomment-653563544, I think this is great.

By the way, the best way is allow user add dockerRegistryOrg to `jx-requirements.yml`.
