### ISSUE TITLE
Remove satori uuid package

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#7454]
### Summary 
See: https://github.com/satori/go.uuid/issues/84

Checking go.mod, looks like we use three packages for generating uuid.
github.com/pborman/uuid
github.com/satori/go.uuid
github.com/google/uuid v1.1.1

Seems like only the google package has been updated recently. We should remove the other two.

**Comment by garethjevans** [comment]
It would be worth thinking about banning the others in the linter config

**Comment by ankitm123** [comment]
Yes, that would be nice as it would prevent any accidental inclusion of those other packages. I should have a PR ready by the EOD for this issue.

**Comment by ankitm123** [comment]
Seems like [depguard](https://github.com/OpenPeeDeeP/depguard) is the package that can be used.
