### ISSUE TITLE
jx stop pipeline doesn't find pipeline

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/jx#7470]
### Summary 
After starting a pipeline and having it hang (or go unresolved in some way), trying to use `jx stop pipeline` doesn't work.

### Steps to reproduce the behavior
Start pipeline (either through webhook or `jx start pipeline owner/environment-staging-dev/master`)
Try to stop pipeline:
 ```
jx get pipeline
Name                                          URL LAST_BUILD STATUS DURATION
owner/environment-staging-dev/master        N/A N/A        N/A    N/A

jx stop pipeline owner/environment-staging-dev/master
error: no PipelineRun found for name owner/environment-staging-dev/master
```
### Expected behavior
pipeline aborts

### Actual behavior
Error seen above

### Jx version
The output of `jx version` is:
```
Version        2.1.93
Commit         729fc2b
Build date     2020-06-30T16:56:20Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.93
Commit         729fc2b
Build date     2020-06-30T16:56:20Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.11-eks-af3caf
kubectl (installed in JX_BIN) v1.15.12
helm client                   2.16.7
git                           2.25.1
Operating System              Ubuntu 20.04 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.

```

### Kubernetes cluster

AWS EKS, using terraform to create

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment
Ubuntu 20.04LTS

**Comment by ankitm123** [comment]
So this is the issue:
`jx get pipeline` returns the postsubmit part of the prowconfig (calls GetReleaseJobs), but `jx stop pipeline`  is designed to cancel  tekton pipelineruns, that explains why you see this error message
```
error: no PipelineRun found for name owner/environment-staging-dev/master
```
`owner/environment-staging-dev/master` is not a pipelinerun.
I will make a PR (by the EOD), so that jx get pipeline returns the tekton pipelineRun lists.

**Comment by arpad9** [comment]
@ankitm123 Thanks!  Out of curiosity, how would I see the tekton pipelines?  Because even if I look at `jx get activities`, I don't get anything I can feed to `jx stop` it seems.

**Comment by ankitm123** [comment]
So a workaround would be to use the tekton cli to view the pipelines (which is used internally by jx).
This link should help you: https://github.com/tektoncd/cli#linux-debs
Once installed use this command:
https://github.com/tektoncd/cli/blob/master/docs/cmd/tkn_pipelinerun_list.md

If that does not work, let me know.
