### ISSUE TITLE
Create quickstart uses wrong download url for Github private repositories

### ISSUE THREAD

**Issue by RoVernekar** [jenkins-x/jx#7471]
### Summary 

`jx create quickstart` fails when the quickstart is in a private Github repository because it tries to download the source zip from the wrong url.

It looks like the codeload url it tries to download the zip from is valid for public repositories but not for private repositories.

The format `jx` uses to formulate the download url seems to be something like this:
```
https://codeload.github.com/{owner}/{repo}/zip/{ref}
```

I believe this is the relevant code: https://github.com/jenkins-x/jx/blob/master/pkg/gits/github.go#L1366

It looks like Github has an API to get the archive download link so maybe jx should use this instead of formulating the download link itself: https://docs.github.com/en/rest/reference/repos#download-a-repository-archive

> Note: For private repositories, these links are temporary and expire after five minutes.

The download url retrieved from this API for a private repository looks something like this:
```
https://codeload.github.com/{owner}/{repo}/legacy.zip/{ref}?token={token}
```

### Expected behavior

An application is able to be created from a quickstart template that's in a private Github repository.

### Actual behavior

```bash
$ jx create quickstart --verbose
...
? Enter the new repository name:  bar
Creating repository foo/bar
DEBUG: Downloading Quickstart source zip from https://codeload.github.com/foo/bar/zip/abcd12345 with basic auth for user: baz
error: failed to unzip new project file /tmp/source.zip due to zip: not a valid zip file
```

The download url returns: `404: Not Found`

### Jx version

The output of `jx version` is:

```
Version        2.1.114
Commit         e2198a9
Build date     2020-07-23T15:20:47Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.114
Commit         e2198a9
Build date     2020-07-23T15:20:47Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.14.9
kubectl (installed in JX_BIN) v1.15.5
helm client                   2.16.1
git                           2.21.0 (Apple Git-122.2)
Operating System              Mac OS X 10.15.3 build 19D76

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

### Operating system / Environment

Mac OS X Catalina 10.15.3

**Comment by tomhobson** [comment]
Closing as this is a v2/v1 issue and those versions are no longer maintained. Thanks for the issue!
