### ISSUE TITLE
webhook: lighthouse won't install

### ISSUE THREAD

**Issue by jerome-morgado** [jenkins-x/jx#7474]
### Summary 

STEP: install-jenkins-x command: /bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders in dir: /Users/jmorgado/Git/sixense/dt/dtkube01/environment-dtkube01-dev/env

Modified file /Users/jmorgado/Git/sixense/dt/dtkube01/environment-dtkube01-dev/env/Chart.yaml to set the chart to version 1
creating the lock configmap jx-lock-jx
lock configmap jx-lock-jx created
cleaning the lock configmap jx-lock-jx
error: generating values.yaml for tree from /var/folders/n9/zgzflxtj0wdfrjnz91q8dbqm0000gn/T/jx-helm-apply-312329975/env: failed to execute Secrets template: /var/folders/n9/zgzflxtj0wdfrjnz91q8dbqm0000gn/T/jx-helm-apply-312329975/env/lighthouse/values.tmpl.yaml: template: values.tmpl.yaml:7:26: executing "values.tmpl.yaml" at <.Parameters.prow.hmacToken>: map has no entry for key "hmacToken"
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''

### Steps to reproduce the behavior

Set webhook: lighthouse in jx-requirements.yaml instead of webhook: prow

### Jx version

Version        2.1.114
Commit         e2198a9
Build date     2020-07-23T15:20:47Z
Go version     1.13.8
Git tree state clean

```
COPY OUTPUT HERE
```

### Diagnostic information

The output of `jx diagnose version` is:

```
COPY OUTPUT HERE
```

### Kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}

```
Copy output here
```

**Comment by garethjevans** [comment]
Was this cluster created with `prow` first, and then switched to `lighthouse`?

**Comment by jerome-morgado** [comment]
Yes I think, but I deleted the Namespace and re-installed it.
