### ISSUE TITLE
Jx not removing the old resources

### ISSUE THREAD

**Issue by majuansari** [jenkins-x/jx#7486]
### Summary 
jx step helm apply is not removing old resources 

Say I have a release x where I added a service s1 and in the release x +1 I removed the service. But I still can see the same service s1 exists in the cluster, even after the deployment of x +1 release.
### Steps to reproduce the behavior
I created testsvc.yaml with a simple service and committed the file. It got deployed and created the service testsvc
Then I commented the entire testsvc.yaml and committed. This time also deployment was a success but the service defined earlier is still there
I tried deleting the yaml and committed. But still, the service stays there even after deployment
### Expected behavior
Service testsvc should be deleted once the yaml file is removed
### Actual behavior
testsvc is not deleted
### Jx version

The output of `jx version` is:

```
Version        2.1.118
Commit         210f656
Build date     2020-07-27T23:02:58Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

``` 
Running in namespace: jx
Version        2.1.118
Commit         210f656
Build date     2020-07-27T23:02:58Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.12-gke.9
kubectl (installed in JX_BIN) v1.13.2
helm client                   2.12.2
git                           2.27.0
Operating System              Mac OS X 10.14 build 18A391

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

GCP cluster and create from GCP console

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
```

### Operating system / Environment

macosx

**Comment by majuansari** [comment]
Hi,

Any update on this ?

**Comment by msvticket** [comment]
This seems to be a regression of #7073 where "all" was removed from the list of resources to delete.
