### ISSUE TITLE
devopds not installing ksync correctly on macos

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#749]
Folling the instructions as per http://jenkins-x.io/developing/devpods/

```
jx sync
Downloading https://github.com/vapor-ware/ksync/releases/download/0.1.3/ksync_darwin_amd64 to /Users/michaelneale/.jx/bin/ksync.tmp...
Downloaded /Users/michaelneale/.jx/bin/ksync.tmp
Initialising ksync
Error: Command failed  ksync init --upgrade
error: exec: "ksync": executable file not found in $PATH
```

**Comment by michaelneale** [comment]
had to run 

`export PATH=$PATH:/Users/michaelneale/.jx/bin`

**Comment by michaelneale** [comment]
also - the pod was empty of code before I ran sync - is that expected ? (it surprised me, as it sounded like sync was optional the way the page is worded)

**Comment by michaelneale** [comment]
doc update: https://github.com/jenkins-x/jx-docs/pull/94

**Comment by jstrachan** [comment]
We could make the Dev pod clone git on startup so that the `jx sync` is optional

**Comment by michaelneale** [comment]
Yes, I think that would make most sense, if I understand correctly. A devpod is for an app you are working on vs just a blank slate to play with? I wasn’t sure, other than running dev tools, what I was meant to to do try it out one synced up there

**Comment by michaelneale** [comment]
I think this was fixed ages ago
