### ISSUE TITLE
Use allowlist and denylist in public documentation and the codebase

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx#7502]
### Summary 
Replace whitelist and blacklist with allowlist and denylist, as they more precisely describe the functions of these fields and variables without any use of colour to denote positive or negative. 

Initially, this should be done in the Jenkins X docs and `jx` codebase.

Currently these terms are not used widely in Jenkins X, but they are present and should be updated.

For future internal code and type names, we should avoid terms like "whitelist" and "blacklist" entirely and our contribution/style guides should be updated accordingly.

**Comment by abayer** [comment]
Sounds like a good change to me!
