### ISSUE TITLE
jenkins secrets not found

### ISSUE THREAD

**Issue by chiducaf** [jenkins-x/jx#7503]
when trying to create GKE cluster, at the final stage of cluster creation it throwing an error message:

`error: configuring Jenkins: creating Jenkins API token: after 3 attempts, last error: creating Jenkins Auth configuration: secrets "jenkins" not found`

can anyone help me to sort out the issue!!!!

**Comment by ankitm123** [comment]
Can you add some more details? Also, discourse is the right place to ask this question: https://jenkinsx.discourse.group/, instead of github issue.

**Comment by wy2249** [comment]
I got this error when trying jx install  --provider=kubernetes --on-premise. I can see the setup of jx namespace is almost done but cannot continue to finish installation process for this error. Plz help if anyone have encountered too

**Comment by ivanamat** [comment]
Hi,

 I have the same problem installing with "jx install --provider=kubernetes --on-premise" on minikube.

**Comment by retr0h** [comment]
Anyone able to get past this?

**Comment by sawyerwu** [comment]
I got this problem too.

**Comment by qiufanchao** [comment]
me toooooooooooooooooooooooooooooooooo

**Comment by timbortnik** [comment]
This could help:
```jx install  --tekton```

**Comment by gopi-devops1** [comment]
same error while using --> jx install --provider=kubernetes --on-premise

**Comment by chiducaf** [comment]
@timbortnik   If you use that command it will not give you the jenkins URL, but it will give you jenkins admin password

**Comment by saraswathicv** [comment]
Even I am facing the same issue when trying  jx install --provider=kubernetes --on-premise

**Comment by soulseen** [comment]
same issue +1

**Comment by retr0h** [comment]
> Even I am facing the same issue when trying jx install --provider=kubernetes --on-premise

Pretty sure `jx install` is deprecated now, and you should use `jx boot`

**Comment by chiducaf** [comment]
Hey anybody got solution about this???

**Comment by tomhobson** [comment]
Hey, as this is jx install, this is related to v2, which is no longer supported.

We now use this through a terraform apply, which IMHO is way more reliable.

Thanks for the issue, closing as a v2 issue.
