### ISSUE TITLE
s3 buckets should include options to create with kms encryption

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/jx#7524]
### Summary 
Currently, the AWS S3 buckets for logs, reports and repository are created with no encryption.

### Steps to reproduce the behavior
Run jx boot

### Expected behavior
Provide an option to specify a kms id and create the buckets with encryption.

### Actual behavior
Buckets are created with no encryption.

### Jx version

The output of `jx version` is:

```
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
WARNING: Failed to find helm installs: running helm list --all --namespace jx: failed to run 'helm list --all --namespace jx' command in directory '', output: 'Error: could not find tiller'
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.16.13-eks-2ba888
kubectl (installed in JX_BIN) v1.16.8
git                           2.25.1
Operating System              Ubuntu 20.04.1 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

AWS eks, made with Terraform

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

### Operating system / Environment

Ubuntu 20.04

**Comment by ankitm123** [comment]
@arpad9 This looks like it should be an issue in the terraform repo (so may be close it here, and open it in the terraform eks repo). 

This is a good suggestion. I have tfsec installed in there already, we can also turn on the rule to catch the case where the bucket is not encrypted.

**Comment by arpad9** [comment]
Closing in favor of https://github.com/jenkins-x/terraform-aws-eks-jx/issues/123
