### ISSUE TITLE
Installation requires curl, awscli, git

### ISSUE THREAD

**Issue by ryanwholey** [jenkins-x/jx#7532]
### Summary
When setting up my cluster for the first time via terraform and EKS, there are a set of [prerequisites](https://github.com/jenkins-x/terraform-aws-eks-jx#prerequisites).

```
wget
aws-iam-authenticator
kubectl
terraform
```

When following the readme instructions, 
`awscli`, `git` and `curl` are all required dependencies
 
example: 

When running `jx boot`, I receive an error that curl is not found

```
error: error installing helm: failed to run '/root/.jx/bin/helm plugin install https://github.com/futuresimple/helm-secrets' command in directory '', output: '/usr/bin/dpkg
/root/.helm/plugins/helm-secrets/install-binary.sh: line 54: curl: command not found
```

### Steps to reproduce the behavior

- Follow the [terraform instructions](https://github.com/jenkins-x/terraform-aws-eks-jx#prerequisites) from the jx module readme (add awscli as a prerequisite)
- Run jx boot from the [running jx boot instructions](https://github.com/jenkins-x/terraform-aws-eks-jx#running-jx-boot), (set the KUBECONFIG env var and add git as a dependency)
- via the jx prompts, set git account owner, set git account reviewers, confirm Y to the TLS request
- View error 

### Expected behavior

The prequesites listed in the project should cover the dependencies needed to run the instructions

### Actual behavior

curl, git and awscli should be listed as prerequisite dependencies

### Jx version

The output of `jx version` is:

```
Version        2.1.132
Commit         8d57ed4
Build date     2020-08-14T14:39:06Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'jx': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
WARNING: Failed to find helm installs: running helm list --all --namespace jx: failed to run 'helm list --all --namespace jx' command in directory '', output: 'Error: could not find tiller'
Version        2.1.132
Commit         8d57ed4
Build date     2020-08-14T14:39:06Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.11-eks-065dce
kubectl (installed in JX_BIN) v1.16.6-beta.0
git                           2.20.1
Operating System              Debian GNU/Linux 10 (buster)

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

debian buster

**Comment by ankitm123** [comment]
The pre-reqs listed in the eks terraform module are only to get the terraform stuff to work. Would be nice if you add the things you mentioned above in the readme of the jx repo.

**Comment by ryanwholey** [comment]
@ankitm123 that makes sense. In that light, seems like awscli is the one that should be added to the prerequisite list

**Comment by ankitm123** [comment]
You can add that to the readme for eks, please open an issue in that repo, and create a PR. Sounds good @ryanwholey?

**Comment by ryanwholey** [comment]
@ankitm123 you got it! Thanks for taking a look.
