### ISSUE TITLE
Unable to install postgres chart in env

### ISSUE THREAD

**Issue by heroic** [jenkins-x/jx#7549]
### Summary
Trying to add bitnami PostgreSQL into an env chart on a kubernetes cluster with kube version 1.16, the env cannot be applied and the pipeline fails.

### Steps to reproduce the behavior
Add these to the staging/production env requirements.yaml

```
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ~9.3.3
```
Install jx in a cluster running kube 1.16 and deploy the ENV above into the cluster. The pipeline fails.

### Expected behavior

The pipeline should work

### Actual behavior
The pipeline fails as the chart is not able to get the Kube version in the cluster, and hence fails to decide the correct "API" for the stateful chart.
### Jx version

The output of `jx version` is:

```
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.16.13-gke.1
kubectl (installed in JX_BIN) v1.16.6-beta.0
helm client                   2.16.9
git                           2.24.3 (Apple Git-128)
Operating System              Mac OS X 10.15.6 build 19G2021

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
amit@MacBook-Pro Thor % 

```

### Kubernetes cluster

GKE running 1.16 created manually.

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
```

### Operating system / Environment

MacOSX 10.15.6

**Comment by msvticket** [comment]
Duplicate of #7396
