### ISSUE TITLE
jx create spring - Extra '/' in repository name.

### ISSUE THREAD

**Issue by CobraFlow** [jenkins-x/jx#755]
The repository url and image names are being created with an extra '/'.
 xxx.xxx.xxx.xxx:5000/jenkinsx//demo. Note the double '/'.
There are three files that contribute -
skaffold.yaml (lines 6, 20 and 30)
charts/demo/Makefile (line 39)
charts/preview/Makefile (line 14)

What is the correct solution for this?

**Comment by CobraFlow** [comment]
After a bit of digging and figuring out how all this holds together, I found this change -
'https://github.com/jenkins-x/draft-packs/commit/dd33232a02b078b4229f3caf370422cec8e46670#diff-3092153d7c9b7cdf1040aafbba4aa490'

Is this correct? If so, how is the replacement now done?

**Comment by jstrachan** [comment]
@CobraFlow any chance you could include the fragment/file thats got the extra `//` in it? Tried a spring boot demo here and its all looking fine to me

The replacement of the organisation + repo/project names happen in the `jx import` code basically

**Comment by CobraFlow** [comment]
@jstrachan I am trying to see how this all works. I tear down the whole cluster each time!

I have created a Bare Metal (kubeadm) cluster with 1 master and 3 agents. All VMs have 4Gb memory, 1x 4 core CPU. I have provisioned 200Gb Rook storage, MetalLB and Weave network.

I deploy JenkinsX with provider 'kubernetes'

All I have done so far is create the spring app with `jx create spring -d web -d actuator` and repeatedly modify it to see how the workflows work.

I'm on my 9th reinstall at present, so will update you as I go...

**Comment by CobraFlow** [comment]
I do get the following on install, is this ok?

![image](https://user-images.githubusercontent.com/3617910/39618283-ebb73924-4f7a-11e8-977c-70dbf58e2a3a.png)

**Comment by jstrachan** [comment]
yeah - that seems an old warning - I get that too

**Comment by jstrachan** [comment]
if you hit this issue any chance you could attach the files that look wrong; say the `Makefile` or whatever that has the double `//` inside it.

BTW sorry to hear you're reinstalling so much!

**Comment by CobraFlow** [comment]
...I will do.
I like to do clean installs to make sure that I have not inadvertently broken something. I am also sure that I'm on the latest version of everything!
Is there a way to change the Jenkins version and update the plugins to the latest in the image as I have to do that every time!

**Comment by CobraFlow** [comment]
@jstrachan I have attached the demo project as-is straight after creation. The skaffold.yaml and the two Makefiles are incorrect.

[demo.zip](https://github.com/jenkins-x/jx/files/1973817/demo.zip)
