### ISSUE TITLE
Error detecting Perl language pack.

### ISSUE THREAD

**Issue by randymay** [jenkins-x/jx#756]
This morning, I installed Jenkins-X on a GKE cluster, and it created staging and production environments (as expected) in Jenkins and Github.  

Now, I have re-installed Jenkins-X on the cluster (this time using the `--no-default-environments=true` option to avoid the environment creation).  I am attempting to import those repositories that were just created this morning (using the `jx import` command), and I am receiving the following error:

```
--> Could not find a pack for Perl. Trying to find the next likely language match...
error: there was an error detecting the language using packs from /home/randy_may/.jx/draft/packs
```

I re-ran the install with the `--recreate-existing-draft-repos=true` option to recreate the language draft files, but still nothing.

Is this a problem with Jenkins-X, or my environment?  What would the steps be to figure out WHY there is an error.  I have looked at the code, and the cause of the error is never displayed.

Thanks in advance.

**Comment by randymay** [comment]
I forgot to mention that I am using the latest version of jx (1.2.46).

**Comment by jstrachan** [comment]
we should add one. There's docs on adding build packs here btw: https://jenkins-x.io/architecture/build-packs/

any chance you could find/create a little sample project we can use to get the build pack going?
