### ISSUE TITLE
Error in installing jx-app-ui

### ISSUE THREAD

**Issue by ziggy-star-dust** [jenkins-x/jx#7573]
### Summary
Error in installing jx-app-ui
### Steps to reproduce the behavior
jx add app jx-app-ui --version 0.1.211
### Expected behavior
jx-app-ui is installed
### Actual behavior
WARNING: No secrets found on "helm/repos" due: reading the secret "helm/repos" from vault: no secret "helm/repos" not found in vault
Read credentials for http://chartmuseum.jenkins-x.io from vault helm/repos
Checking if TLS is enabled in the cluster
error: asking questions for schema: cannot parse string {{ .Values.tlsInCluster }} as bool: strconv.ParseBool: parsing "{{ .Values.tlsInCluster }}": invalid syntax

### Jx version

The output of `jx version` is:

```
2.1.149
```

### Diagnostic information

The output of `jx diagnose version` is:

```
COPY OUTPUT HERE
```

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by haysclark** [comment]
+1  

I was successfully running `jx-app-ui 0.1.49` and ran into this issue when upgrading both `jx boot` and `jx-app-ui`.  I can confirm that both `jx version` `2.1.138` and `2.1.149` throw the same error if the `jx-app-ui 0.1.211` chart is installed. Currently, I've opted to deleting the app:

```bash
jx delete app jx-app-ui --auto-merge
```

**Comment by ziggy-star-dust** [comment]
Do you recall which combination of versions(jx.jx-app-ui/jx boot) worked for u?

**Comment by haysclark** [comment]
@ziggy-star-dust I'm looking at the Diffs... and I think I am wrong that the issue is related too upgrading `jx-app-ui`. I was happily running `jx 2.1.88` with `jx-app-ui 0.1.211`.

**Comment by pushpamsaxenafl** [comment]
I also observe the same issue with the Kubernetes cluster hosted on AKS.

`>jx version
Version        2.1.149
Commit         a5c2cb9
Build date     2020-09-21T11:50:59Z
Go version     1.13.8
Git tree state clean`

When I try to install the app -
`>jx add app jx-app-ui
Checking if TLS is enabled in the cluster
error: asking questions for schema: cannot parse string {{ .Values.tlsInCluster }} as bool: strconv.ParseBool: parsing "{{ .Values.tlsInCluster }}": invalid syntax`

**Comment by haysclark** [comment]
Here is some [feedback](https://kubernetes.slack.com/archives/C9MBGQJRH/p1601319659115200?thread_ts=1601318694.112100&cid=C9MBGQJRH) about this issue from the Slack channel.

> @jstrachan "we are transitioning to the octant-jx plugin as a general purpose UI for kubernetes, pipelines, apps etc https://github.com/jenkins-x/octant-jx and moving to use the OSS pipeline visualiser for viewing pipelines & logs (which is here right now https://github.com/dailymotion/jx-pipelines-visualizer but will soon be here... https://github.com/jenkins-x/jx-pipelines-visualizer"
