### ISSUE TITLE
jx install command on existing minikube using hyper-v error

### ISSUE THREAD

**Issue by no-stupid-questions** [jenkins-x/jx#758]
![image](https://user-images.githubusercontent.com/38955053/39585493-f54c9c4e-4ec2-11e8-8608-8c28659a86da.png)
![image](https://user-images.githubusercontent.com/38955053/39585513-011052d2-4ec3-11e8-8a07-a8a52de27d44.png)
I am having trouble with the jx install.
I could get the "jx create cluster minikube" with device "hyperv" selected, so I created an new virtual switch in Hyper-V manager and used the command ( minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch") to start up the VM.
Once running I then called the "jx install" which produced the errors : 
---------------------------------------------------------------------------------------------------------------
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Cloning the Jenkins X cloud environments repo to C:\Users\jdooley\.jx\cloud-environments
Counting objects: 529, done.
Total 529 (delta 0), reused 0 (delta 0), pack-reused 529
Generated helm values C:\Users\jdooley\.jx\extraValues.yaml
Installing Jenkins X platform helm chart from: C:\Users\jdooley\.jx\cloud-environments\env-minikube
process_begin: CreateProcess(NULL, uname, ...) failed.
The system cannot find the path specified.
The system cannot find the path specified.
helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
"jenkins-x" has been added to your repositories
rm -rf secrets.yaml.dec
process_begin: CreateProcess(NULL, rm -rf secrets.yaml.dec, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
Error: Command failed  make ARGS=--values=C:\Users\jdooley\.jx\gitSecrets.yaml --values=C:\Users\jdooley\.jx\adminSecrets.yaml --values=C:\Users\jdooley\.jx\extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2
---------------------------------------------------------------------------------------------------------------
shown in the images above.

I'm very new to this so any help would be appreciated.

Thanks!

**Comment by ccojocar** [comment]
This seems to be rather a minikube issue than `jx`.
