### ISSUE TITLE
Pipelines keep restarting until the corresponding prowJob is manually deleted

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#7600]
### Summary

After updating my Jenkins-X cluster, in an attempt to fix the recent `helm` bugs, the pipelines keep restarting, even if successful, until the corresponding prowJob is cleaned.
The Jenkins-X version is https://github.com/jenkins-x/jenkins-x-versions/tree/v1.0.608

I've identified the problem and sent a pull request for `prow-pipeline-controller` already https://github.com/jenkins-x/prow-pipeline-controller/pull/17

However, when I build the controller and use it, I have now the following problem: `prowjobv1.TektonAgent` is `"tekton-agent"`, whereas my prowJob agent is `"tekton"`. I suppose this is an update of the `k8s.io/test-infra` library, so needs to be careful that both `hook` and `prow-pipeline-controller` agree on that value, or make the condition more relaxed. https://github.com/jenkins-x/prow-pipeline-controller/blob/master/internal/controller/controller.go#L501

### Jx version

The output of `jx version` is:

```
Version        2.1.150
Commit         c038751
Build date     2020-09-26T19:20:02Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.150
Commit         c038751
Build date     2020-09-26T19:20:02Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.14.10-gke.50
kubectl (installed in JX_BIN) v1.16.6-beta.0
helm client                   2.16.9
git                           2.17.1
Operating System              Ubuntu 18.04.5 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

GKE

### Kubectl version
The output of `kubectl version` is:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.50", GitCommit:"bc01f00cf59008a36aa47f67c37c36b9d66db718", GitTreeState:"clean", BuildDate:"2020-09-09T03:06:32Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jstrachan** [comment]
this is fixed in v3: https://jenkins-x.io/v3/#administration
