### ISSUE TITLE
Need an example (please) of a more complex application

### ISSUE THREAD

**Issue by stevef1uk** [jenkins-x/jx#761]
I am looking for a Golang example, but one in any language would do as I would like to see how parameters can be passed through the config files to the actually running code e.g. for OpenShift the 
Golang template: (https://github.com/amsokol/openshift-golang-template) supports several configurable items that I need: GOPROJECT_CMD_ARGS which I used to set to --host=0.0.0.0

Also, I need a way to add go dependencies to the Go build system e.g. more go gets. The S2I did this for me before.

**Comment by ccojocar** [comment]
You can have a look at `https://github.com/jenkins-x/sso-operator` as an example. It is deployed with jx.
