### ISSUE TITLE
"Error: flag needs an argument: --commit-sha" using GitLab

### ISSUE THREAD

**Issue by ahlae** [jenkins-x/jx#7610]
### Summary
We are trying to set up Jenkins X together with GitLab on a vanilla Kubernetes cluster. Everything is running onprem. There seems to be an issue with merging PR on GitLab.

Following the installation steps as described in 

https://jenkins-x.io/v3/admin/platforms/on-premise/

seem to work without problems. After installation of Jenkins X importing projects results in the import pipeline on GitLab running indefinitely. Three pipelines are triggered on Jenkins X (2 in a verify context which succeed and 1 in a master context which fails). The failing master context pipeline outputs to the following error to the logs:

Error: flag needs an argument: --commit-sha.

### Steps to reproduce the behavior

1. Install Jenkins X on a vanilla Kubernetes cluster:
- Clone jx3-kubernetes.git:
git clone --depth 1 https://github.com/jx3-gitops-repositories/jx3-kubernetes.git

- Remove .git and adapt jx-requirements.yml
- Create empty jx3-kubernetes project on GitLab
- Initialize and push project to GitLab:
git init
git remote add origin https://...
git add .
git commit -m "Initial commit"
git push -u origin master

- Trigger the Jenkins X installation in the jx3-kubernetes git folder:
jx admin operator --username ... --token ... 

2. Import project
- Use the files of the Jenkins X nodejs http quickstart project and import them to GitLab:
git init
git remote add origin https://...
git add .
git commit -m "Initial commit"
git push -u origin master

- Import the project to Jenkins X using the GitLab Project ID since using the owner name doesn't work:
jx project import --git-kind gitlab -n 79 --verbose

### Expected behavior
The project should be imported to Jenkins X without errors. Comitting to the project should trigger the webhook and corresponding Jenkins X pipelines.

### Actual behavior
The import fails with the merge pipeline on GitLab running indefinitely and the Jenkins X master pipeline throwing the error "Error: flag needs an argument: --commit-sha"

### Jx version

The output of `jx version` is:

```
version: 3.1.160
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Error: unknown command "diagnose" for "jx"
Run 'jx --help' for usage.
```

### Kubernetes cluster

The Kubernetes cluster (v1.20.0) runs onprem and was created using kubeadm. It has 3 nodes and a HA control plane setup behind a haproxy loadbalancer.

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

jx is executed on Debian 10.7

**Comment by Kali-lightsaber** [comment]
Are you setting up tekton before jenkins X is deployed in k8s cluster?

**Comment by Kali-lightsaber** [comment]
Use option --import-commit-message 
`jx project import --git-kind gitlab --import-commit-message af143697bf81e93f1fe5d3308eb3a6bce641f34c`

**Comment by mcdonnell-john** [comment]
I got this as well, it only happens the master branch on the cluster repo hosted on Gitlab.

I suspect it's because `$PULL_BASE_SHA` is not populated but not sure how to get around this.

**Comment by jalonsoa** [comment]
Hi !
  we have the same issue. 

  The LightHouseJob created don't have the spec.refs.base_sha field so the tekton pipeline don't populate the PULL_BASE_SHA environment variable.

  What service create the LightHouseJob, the lighthouse-webhook or the lighthouse-keeper ?

**Comment by mcdonnell-john** [comment]
@jalonsoa I'm still stuck on this, you might have luck asking on the slack channel?

**Comment by jalonsoa** [comment]
Hi,
  I found the problem in the go-scm library. The lighthouse-webhook service create the LightHouseJob from the the push webhook. In the webhook, the after field is converted to the gitlab pushHook struct, but when the library convert the gitlab pushHook to the generic scm.PushHook they forgot add this "after" field. So, the LightHouseJob add the head reference empty.

  I try to prepare the pull request to the go-scm library, then we will request to lighthouse to upgrade to the new version.

**Comment by jalonsoa** [comment]
@mcdonnell-john I opened the PR -> jenkins-x/go-scm#242

**Comment by mcdonnell-john** [comment]
@jalonsoa Excellent thanks very much.

I'll admit, I was having a look around to see where `$PULL_BASE_SHA` but don't have experience with Go, and this was the first time looking around the JenkinsX sources...  I never got anywhere close to the go-scm library :(

**Comment by jalonsoa** [comment]
The pr in the go-scm library was merged. Now, we need that the PR in the lighthouse project (pending jenkins-x/lighthouse#1250) and then the PR in the jenkins-x-versions.

**Comment by jstrachan** [comment]
is this all fixed now?

**Comment by jalonsoa** [comment]
Hi !,
  yes for me

**Comment by Kali-lightsaber** [comment]
No it doesn't
