### ISSUE TITLE
How to deploy Jenkins X on a private k8s cluster？

### ISSUE THREAD

**Issue by TonyBian** [jenkins-x/jx#7612]
### Summary 
My k8s cluster is created by ansible, how can I deploy Jenkins X on it?

### Jx version

The output of `jx version` is:

```
Version        2.1.155
Commit         3fe0638
Build date     2020-12-24T15:07:42Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: default
```

### Kubernetes cluster

Private Kubernetes, I create it with ansible.

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

CentOS Linux release 7.6.1810 (Core)

**Comment by adrianiacob22** [comment]
Try Jenkins X 3. It worked fine for me.

**Comment by jstrachan** [comment]
see: https://jenkins-x.io/v3/admin/platforms/on-premise/
