### ISSUE TITLE
Quickstart: Spring Boot REST application with Prometheus instrumentation

### ISSUE THREAD

**Issue by hekonsek** [jenkins-x/jx#762]
Hi,

Can you guys consider adding this [1] quickstart to jenkins-x-quickstarts? This is a template for Prometheus-instrumented Spring Boot REST application.

My goal here is to provide quickstart which can be used easily used with conjunction with Prometheus add-on. So end users can execute something like...

```
jx create cluster aws
jx create addon prometheus
jx create quickstart spring-boot-rest-prometheus
```

...end immediately take advantage of Kubernetes cluster with Prometheus monitoring infrastructure up and running, and their REST application being instrumented and monitored.

[1] https://github.com/hekonsek/spring-boot-rest-prometheus

**Comment by jstrachan** [comment]
tried this quickstart and the pod never becomes ready in `Staging`; wonder if Prometheus needs to be in the Staging environment?

**Comment by hekonsek** [comment]
> tried this quickstart and the pod never becomes ready in Staging; wonder if Prometheus needs to be in the Staging environment?

Strange - it works on my local minikube. Do you see any particular error? Let's try to nail it.

Also you don't need Prometheus to make it running. Prometheus is pull based, so this quickstart just exposes HTTP endpoint with metrics which can be scraped by Prometheus server. If there is no Prometheus, the endpoint will not be scraped, but the application itself is gonna work anyway.

**Comment by hekonsek** [comment]
> I'd like to keep this issue open for a little while if I may - as I'd like to add a way for a quickstart to require an addon to be installed; so that if folks create it and the addon (e.g. prometheus in this case) - we prompt the user to add it.

>I'd love it to be simpler for folks to create complex quickstarts which have requirements on the Environments or addons in Jenkins X - and for things to just work really so developers have less things to worry about and stuff just works

It would be awesome to be able to define something like jenkinsx.yml file in the root of the quickstart. Then this jenkinsx.yml could contain a list of add-ons that should be installed by Jenkins-X before deploying application into environment. Like:

```
dependencies:
  addons:
    - prometheus
```

How do you envision this add-on dependencies feature?

**Comment by hekonsek** [comment]
BTW Right now in order to indicate that your app should be monitored by Prometheus, you have to indicate it via k8s annotation. For example:

    kubectl annotate pod skaffold-fc8c65fd6-dzhbs prometheus.io/scrape=true

This is how Prometheus Kubernetes service discovery works.

So right now in order to have your quickstart monitored via Prometheus, you need to execute the following steps:

```
jx create cluster aws
jx create addon prometheus
jx create quickstart -f spring-boot-rest-prometheus
kubectl annotate pod skaffold-fc8c65fd6-dzhbs prometheus.io/scrape=true
```

You would like to remove the add-on step as you mentioned, but ideally I'd like to be able to get rid of annotation step as well. In my ideal world, my envisioned `jenkinsx.yml` file could contain list of annotations that should be applied to my application. So for Prometheus app complete file could look like:

```
dependencies:
  addons:
    - prometheus
annotations:
  pod:
    - prometheus.io/scrape=true
```

All Prometheus-instrumented quickstarts could contain such `jenkinsx.yml` file, so end user can just create an app from quickstart and Jenkins-X will do all the heavy lifting, like installing Prometheus and annotating deployed pods. That would be so awesome!

**Comment by hekonsek** [comment]
FYI I've tested the quickstart on minikube again and it works like a charm:

```
[root@konsekranch spring-boot-rest-prometheus-app2]# jx get pipe
Name                                                  URL                                                                                                       LAST_BUILD STATUS  DURATION
hekonsek/environment-weaselmesquite-production/master http://jenkins.jx.192.168.39.96.nip.io/job/hekonsek/job/environment-weaselmesquite-production/job/master/ #1         SUCCESS 357.919µs
hekonsek/environment-weaselmesquite-staging/master    http://jenkins.jx.192.168.39.96.nip.io/job/hekonsek/job/environment-weaselmesquite-staging/job/master/    #2         SUCCESS 90.871µs
hekonsek/spring-boot-rest-prometheus-app2/master      http://jenkins.jx.192.168.39.96.nip.io/job/hekonsek/job/spring-boot-rest-prometheus-app2/job/master/      #1         SUCCESS 2.035628ms
[root@konsekranch spring-boot-rest-prometheus-app2]# jx get app
APPLICATION                      STAGING PODS URL                                                                                PRODUCTION PODS URL
spring-boot-rest-prometheus-app2 0.0.1        http://jx-staging-spring-boot-rest-prometheus-app2.jx-staging.192.168.39.96.nip.io 
```

I can also see Prometheus graph displaying custom metric used in quickstart. So everything works like a charm for me. Let me know if I can help you debug your issue with quickstart.

**Comment by hekonsek** [comment]
@jstrachan Any thoughts on how add-ons and kube annotations could be added to quickstarts? That would be a killer feature :) .

**Comment by hekonsek** [comment]
@jstrachan @rawlingsj Any chance to got this (https://github.com/jenkins-x-quickstarts/spring-boot-rest-prometheus/pull/1) merged? ;)

**Comment by ccojocar** [comment]
It seems to be fixed.
