### ISSUE TITLE
Allow a team to be configured to create private repos

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#763]
It would be nice to be able to configure a Team to use a default of repositories being private rather than public

**Comment by darthcabs** [comment]
Having `jx` alert that the repo is public, and instruct the user to go ahead and make it private (if possible) before deploying any apps. Once I put sensitive information as environment variables in values.yaml and commited before realising the repo was public. It wasn't terribly smart of me, I admit, but could happen to everyone of us haha
