### ISSUE TITLE
main or master ?!?

### ISSUE THREAD

**Issue by 6543** [jenkins-x/jx#7631]
It's not clear from CONTRIBUTING.MD, what branch a pull should target too!!!

ping @rawlingsj

**Comment by 6543** [comment]
I'll target master since this was done in the past - but it confuses me that main is now default branch :/

**Comment by 6543** [comment]
master -> v2
main -> v3

**Comment by rawlingsj** [comment]
Yeah sorry for the confusion, we're currently preparing for the v3 GA release so yes main = v3 and master has been renamed to v2. We will be actively focussing on v3 going forward.
