### ISSUE TITLE
docker pull ghcr.io/jenkins-x-plugins/jx-preview:0.0.177 failed

### ISSUE THREAD

**Issue by tryIdea** [jenkins-x/jx#7644]
`docker pull ghcr.io/jenkins-x-plugins/jx-preview:0.0.177`

Error response from daemon: Head https://ghcr.io/v2/jenkins-x-plugins/jx-preview/manifests/0.0.177: unauthorized

**Comment by jstrachan** [comment]
its now authorised, sorry about that it was a regression due to moving all the plugins into the plugins organisation
