### ISSUE TITLE
jx-pipelines-visualiser has a 'latest' tag

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#7706]
Should this be explicitly versioned?

**Comment by vbehar** [comment]
hum where do you see it? in the version stream, it has a versioned tag: https://github.com/jenkins-x/jx3-versions/blob/master/charts/jx3/jx-pipelines-visualizer/defaults.yaml

**Comment by tdcox** [comment]
![Screen Shot 2021-04-29 at 16 31 27](https://user-images.githubusercontent.com/15021932/116577865-c41d0200-a908-11eb-80ce-e43edf18fc8d.png)

This is what I see in Octant / Jenkins X / Apps

**Comment by vbehar** [comment]
oh I think it's the app version, not the chart version. we'll need to update it in the chart.yaml file https://github.com/jenkins-x/jx-pipelines-visualizer/blob/v1.4.0/charts/jx-pipelines-visualizer/Chart.yaml

I'm pretty sure that if you check the pod's image you'll get a versioned tag

**Comment by tdcox** [comment]
Yes, looks like the image is versioned.
