### ISSUE TITLE
jx create cluster minikube command not working

### ISSUE THREAD

**Issue by AshrayViswanath** [jenkins-x/jx#7712]
Hi my Jenkins x version is 3.2.55
And my minikube version is 1.18.1

When I run "jx create cluster minikube" I am getting the following:
Create one or more resources

Available Commands:
  create project alias for: jx project
  create pullrequest alias for: jx pullrequest
  create quickstart alias for: jx quickstart
  create spring alias for: jx spring

Usage:
  jx create TYPE [flags] [options]
Use "jx <command> --help" for more information about a given command.
Use "jx create options" for a list of global command-line options (applies to all commands).

Please help

**Comment by jstrachan** [comment]
we no longer use `jx create cluster` for 3.x

See the instructions for minikube: https://jenkins-x.io/v3/admin/platforms/minikube/
