### ISSUE TITLE
webhook internel errror

### ISSUE THREAD

**Issue by tryIdea** [jenkins-x/jx#7715]
{"Branch":"master","Clone":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11.git","ID":"46","Link":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11","Name":"spring-boot-rest-prometheus-v11","Namespace":"dufugang","Webhook":"push","level":"info","msg":"invoking Push handler","time":"2021-04-24T08:36:50Z"}
{"Branch":"master","Clone":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11.git","ID":"46","Link":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11","Name":"spring-boot-rest-prometheus-v11","Namespace":"dufugang","Webhook":"push","head":"8014a59408104212e47aba1f62d9c87994713bd7","level":"info","msg":"Push event.","org":"dufugang","ref":"refs/heads/master","repo":"spring-boot-rest-prometheus-v11","time":"2021-04-24T08:36:50Z"}
{"client":"git","level":"error","msg":"error creating a mirror clone: exit status 128 Cloning into bare repository '/var/tmp/gitcache344212088/jenkins-x/jx3-pipeline-catalog'...\nfatal: unable to access 'https://github.com/jenkins-x/jx3-pipeline-catalog/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream\n","org":"jenkins-x","repo":"jx3-pipeline-catalog","time":"2021-04-24T08:38:51Z"}
{"Branch":"master","Clone":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11.git","ID":"46","Link":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11","Name":"spring-boot-rest-prometheus-v11","Namespace":"dufugang","Webhook":"push","error":"failed to create agent: failed to calculate in repo config: failed to load trigger config for repository dufugang/spring-boot-rest-prometheus-v11 for ref : failed to load file .lighthouse/jenkins-x/triggers.yaml in dufugang/spring-boot-rest-prometheus-v11 with sha : failed to load source for presubmit pr: failed to unmarshal YAML file .lighthouse/jenkins-x/pullrequest.yaml in repo dufugang/spring-boot-rest-prometheus-v11 with sha : failed to inherit steps: failed to process uses steps: failed to resolve git URI jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream for step : failed to load URI jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream: failed to find file tasks/git-clone/git-clone-pr.yaml in repo jenkins-x/jx3-pipeline-catalog with sha 8932420ae4bc7ecd6f2b5ae0e410c83e11bda853: failed to create repo client: error creating a mirror clone: exit status 128 Cloning into bare repository '/var/tmp/gitcache344212088/jenkins-x/jx3-pipeline-catalog'...\nfatal: unable to access 'https://github.com/jenkins-x/jx3-pipeline-catalog/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream\n","head":"8014a59408104212e47aba1f62d9c87994713bd7","level":"error","msg":"Error creating agent for PushEvent.","org":"dufugang","ref":"refs/heads/master","repo":"spring-boot-rest-prometheus-v11","time":"2021-04-24T08:38:51Z"}
{"Branch":"master","Clone":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11.git","ID":"46","Link":"http://192.168.8.192/dufugang/spring-boot-rest-prometheus-v11","Name":"spring-boot-rest-prometheus-v11","Namespace":"dufugang","Webhook":"push","error":"Post \"http://cd-indicators.jx.svc.cluster.local/lighthouse/events\": dial tcp: lookup cd-indicators.jx.svc.cluster.local on 10.96.0.10:53: no such host","external-plugin":"cd-indicators","level":"warning","msg":"Error dispatching event to external plugin.","time":"2021-04-24T08:38:54Z"}

**Comment by tryIdea** [comment]
![image](https://user-images.githubusercontent.com/6367303/116051018-bd914f00-a6aa-11eb-9613-df24ae5afa76.png)

**Comment by jstrachan** [comment]
looks like a network / firewall issue? doesn't look like your lighthouse pod is able to git clone https://github.com/jenkins-x/jx3-pipeline-catalog - see: 
```
HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
```

**Comment by jstrachan** [comment]
to double check your network - try:

```bash
kubectl exec -it deploy/lighthouse-webhooks sh
```

then try: 

```bash
cd /tmp
git clone  https://github.com/jenkins-x/jx3-pipeline-catalog
``` 

and see if it works
