### ISSUE TITLE
error configuring jenkinsX using jx-admin-operator 

### ISSUE THREAD

**Issue by platof** [jenkins-x/jx#7729]
I'm trying to install Jenkins X on a physical server with Kubernetes cluster already configured.

Following the configuration of jenkins on premise from this link [https://jenkins-x.io/v3/admin/platforms/on-premise/](url)
After creating the clutser Git Repo based on the jx3-gitops-repositories/jx3-kubernetes template
I modified the jx-requirements.yml and modified the ingress.domain. I commited the change
and push back to github.
I installed the jx admin operator by specifying the gituser and gittoken.
This is meant to install the git operator and then trigger a job which installs jenkins x. 
I get 2 errors while jx-admin-operator command is running
first error
![image](https://user-images.githubusercontent.com/35527059/116877162-3ef65d80-ac26-11eb-969d-9a340909b0e3.png)

second error
![image](https://user-images.githubusercontent.com/35527059/116877327-77963700-ac26-11eb-97c3-184e22da8761.png)

kubectcl get pods command gives
![image](https://user-images.githubusercontent.com/35527059/116877447-a0b6c780-ac26-11eb-9414-1f3449284ed0.png)

Tried Fix:
I manually installed and helmfile and move it to /usr/bin/ directory but I still got same error

Is there a way around this? Thanks

**Comment by jstrachan** [comment]
I wonder if upgrading your cluster git repository helps? 
https://jenkins-x.io/v3/admin/setup/upgrades/cluster/

the helmfile issue looks odd; there's definitely a helmfile binary in the recent boot images. I wonder if you were unlucky and generated your git repository from jx3-kubernetes a few weeks ago when we had a temporary issue with helmfile not being in the image?

e.g. whats the version of `jx-boot` image in this file in your git repository: https://github.com/jx3-gitops-repositories/jx3-kubernetes/blob/main/versionStream/git-operator/job.yaml#L45

at the time of writing the latest is `3.2.77` which definitely has `helmfile` on the `$PATH` (in `/usr/bin`) - upgrading your cluster above should fix it.
