### ISSUE TITLE
ML-service pipeline complains about lack of git-lfs

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#7738]
```
Showing logs for build bootstrap-jersey/test329-service/master #4 release stage from-build-pack and container step-promote-changelog
\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.
```

Git LFS is needed by all the MLOps builds as models are typically too large to store as normal git data. There is an argument to include this by default in any jx images using git, since it may be needed by any customer building projects with large source files.

**Comment by rawlingsj** [comment]
So should adding this https://github.com/jenkins-x/jenkins-x-builders-ml/blob/10ae86b75bcedd32161d1452aca7f673c694cb54/builder-machine-learning/Dockerfile#L14-L21 to our new [CLI base image](v) fix this?

**Comment by rawlingsj** [comment]
would you like me to build a test image, push it to a container registry that you can use to override the `promote-changelog` step to validate?

**Comment by tdcox** [comment]
Yes, that should work fine. Thanks, let me know when I can test.

**Comment by tdcox** [comment]
@rawlingsj It looks like this is already in the Tekton git-init container, so if we could add to ghcr.io/jenkins-x/jx that would enable MLOps pipelines to pull and push large assets.

**Comment by tdcox** [comment]
Looks like there is a package for git-lfs that makes this easier now. Here's a PR...

https://github.com/jenkins-x/jx/pull/7764
