### ISSUE TITLE
ML-service release pipeline fails to publish

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#7739]
The promote step is failing, as follows:

```
Showing logs for build bootstrap-jersey/test329-service/master #4 release stage from-build-pack and container step-promote-step8
WARNING: no $GIT_SECRET_MOUNT_PATH environment variable set
releasing chart preview
error: failed to create chart release in dir charts/preview: failed to publish: failed to run 'curl --fail -sS -u admin:xxxxxxredactedxxxxxx --data-binary @preview-0.0.7.tgz http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080/api/charts' command in directory 'charts/preview', output: 'curl: (22) The requested URL returned error: 500'

Pipeline failed on stage 'from-build-pack' : container 'step-promote-step8'. The execution of the pipeline has stopped.
```

**Comment by tdcox** [comment]
Ah, this would seem to be a generic problem of not being able to import jx2 projects because the mechanisms for describing release and preview charts have changed.

If it is not possible to transform these old-style charts on import, perhaps we should detect them and throw an appropriate error so that people understand that they have to be manually changed?

**Comment by jstrachan** [comment]
we should make `jx gitops helm release` default to ignore `preview` charts
