### ISSUE TITLE
create an app for Eclipse Che

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#774]
so its super easy to install Che via `jx create addon che` then most importantly to align Che workspaces with Jenkins X [DevPods](https://jenkins-x.io/developing/devpods/) so that we can easily combine _terminals_ inside Che with the DevPods so they can use the same images/tools and we can edit inside the DevPod to avoid excessive syncing etc

**Comment by jstrachan** [comment]
though Theia is working great so far! https://jenkins-x.io/developing/devpods/#using-theia-ide

**Comment by jstrachan** [comment]
I'm gonna close this as we already support Theia which is kinda the new Che https://jenkins-x.io/developing/devpods/#using-theia-ide

**Comment by paulvi** [comment]
Eclipse Che is still shown as planned on https://jenkins-x.io/contribute/roadmap/

**Comment by jstrachan** [comment]
@paulvi thanks, I've updated the plan
