### ISSUE TITLE
jx create quickstart fails due to github transition from master -> main naming conventions

### ISSUE THREAD

**Issue by xenoglaux88** [jenkins-x/jx#7750]
When I run the `jx create quickstart` process, it fails due to the following error:
`fatal: couldn't find remote ref master`

Running above with -verbose shows this command:
`DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin master:<COMMIT HAS WAS HERE>`

Notice its trying to fetch master, all new projects created currently create via the main branch versus the master naming convention. 

Is there a way to force this with a command or does this require a code fix?
Will likely need to support both while there is convention transition.

**Comment by xenoglaux88** [comment]
jx version                                                                         
Version        2.1.155
Commit         3fe0638
Build date     2020-12-24T15:07:42Z
Go version     1.13.8

**Comment by jstrachan** [comment]
this is fixed in v3:  https://jenkins-x.io/v3/
