### ISSUE TITLE
Configuring and installing JenkinsX using jx-admin-operator

### ISSUE THREAD

**Issue by vincentkwok2021** [jenkins-x/jx#7771]
I'm trying to install Jenkins X on a on-premise Kubernetes cluster with an local gitlab.
I follow this [link](https://007ba7.us/howto/jx-install/) and modified the jx-requirements.yml for installing.
However, I get an error while installing jx through jx-admin-operator.
The error showed as below and cannot find the root cause of this error over Internet. 
I tried to update the jx and double check the configuration which cannot solve the issue.  Please kindly help on this issue. Thanks.
![jx error](https://user-images.githubusercontent.com/83381193/117935248-195c0900-b336-11eb-88b8-7a8a70a0d802.png)

The jx version: 3.2.89
The Kubernetes version: 1.20.5

**Comment by jstrachan** [comment]
looks like your `helmfiles/jx/helmfile.yaml` is invalid. Whats the output of `jx gitops lint`?

**Comment by jstrachan** [comment]
did you modify things at all from the default template repository? https://github.com/jx3-gitops-repositories/jx3-kubernetes

**Comment by jstrachan** [comment]
@vincentkwok2021 any idea?

**Comment by vincentkwok2021** [comment]
Sorry for late reply. I solve the duplication problem.
But I encounter problem with using on-prem gitlab and proxy setting.
As my K8S setup to the Internet needed to pass thru proxy but when I passed the proxy using params. It shows that it can load the environment variable but it stuck in loading boot job pod
![jx-1](https://user-images.githubusercontent.com/83381193/119620824-05d19780-be38-11eb-822e-e9e79c35c3b8.png)
The following shows the error log
![jx-2](https://user-images.githubusercontent.com/83381193/119620833-0702c480-be38-11eb-9edc-df3d05053627.png)

Any hints on the wrong setting? Thanks.

**Comment by jstrachan** [comment]
looks like the git operator isn’t able to work with git - could you post the log of the jx-git-operator pod in the namespace jx-git-operator

**Comment by jstrachan** [comment]
actually it’s looking like the git operator cannot use the k8s api server to list secrets which sounds like your http proxy is breaking any k8s pod that uses the k8s api server. Try modify your http proxy settings to avoid your proxy breaking kubernetes pods

**Comment by jstrachan** [comment]
ie exclude the k8s api server from your proxy

**Comment by msvticket** [comment]
This issue seem abandoned by reporter
