### ISSUE TITLE
jx create cluster aks fails "Error: Command failed  az login"

### ISSUE THREAD

**Issue by holmesb** [jenkins-x/jx#778]
```
user@ip-10-0-0-1.eu-west-1.compute.internal~$ date
Tue May  8 12:51:02 UTC 2018
user@ip-10-0-0-1.eu-west-1.compute.internal~$ az login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code blahblah to authenticate.
[
  {
    "cloudName": "AzureCloud",
...
user@ip-10-0-0-1.eu-west-1.compute.internal~$ jx create cluster aks
? location northeurope
? nodes 3

Error: Command failed  az login
error creating cluster exit status 1
user@ip-10-0-0-1.eu-west-1.compute.internal~$ date
Tue May  8 13:28:35 UTC 2018
```

I'm on a centos-based OS, does this only work with brew?  Feels like az login session is timing out.  I've also tried specifying the Azure subscription using cmd: az account set --subscription <sub_id>
Is there any way of viewing logs during cluster creation?  
I'm on jx 1.2.49, az 2.0.32, kubect 1.10.0, helm 2.9.0

**Comment by athilaelhuno** [comment]
This issue happened to me, any solution or suggestion for it I'm using OSX with latest versions of jx and  azure-cli.

**Comment by tomconte** [comment]
Same issue here on OS X: jx 1.2.67, azure-cli 2.0.32.

No logs in ~/.azure.

Adding `--debug` to the `az` command, it looks it is simply looping on `az login`, waiting for auth to happen.

This is strange: since `az login` is supposed to be interactive anyway, I think it is expected to block until the user actually logs in. Not sure what `jx` is expecting here.

**Comment by tomconte** [comment]
As a workaround you could try passing the user and password, this unblocked the process for me:

`jx create cluster aks -u user@domain.com -p 'password'`

**Comment by TheMightyCleft** [comment]
I have the same issue on macOS, latest version of jx cli and az cli. Tried @tomconte solution, but still doesn't work for me. I also the same problem when trying this on a windows 10 laptop. --verbose also not working making it hard to isolate the problem. Any other fixes?

**Comment by kumarinfo90** [comment]
I am trying to jx cluster on azure and i am getting the following error.

**error creating cluster failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.2789 --values /root/.jx/cloud-environments/env-aks/myvalues.yaml --values /root/.jx/cloud-environments/env-aks/secrets.yaml --values /root/.jx/gitSecrets.yaml --values /root/.jx/adminSecrets.yaml --values /root/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/root/.jx/cloud-environments/env-aks', output: 'Release "jenkins-x" does not exist. Installing it now.
Error: watch closed before Until timeout': exit status 1**

please give me a solution.

**Comment by ccojocar** [comment]
@holmesb I am going to close this issues sine the original bug was fixed. Thanks
