### ISSUE TITLE
Jenkins  recommended git tool is noe 

### ISSUE THREAD

**Issue by khaleel916** [jenkins-x/jx#7791]
The recommended git tool is: NONE
using credential 549dc4d4-afe2-4592-aaad-6251552628b8
 > C:\Program Files\Git\bin\git.exe rev-parse --resolve-git-dir C:\WINDOWS\system32\config\systemprofile\AppData\Local\Jenkins.jenkins\workspace\job1\.git # timeout=10
Fetching changes from the remote Git repository
 > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/khaleel916/ranirepo # timeout=10
Fetching upstream changes from https://github.com/khaleel916/ranirepo
 > C:\Program Files\Git\bin\git.exe --version # timeout=10
 > git --version # 'git version 2.29.2.windows.2'
using GIT_ASKPASS to set credentials github
 > C:\Program Files\Git\bin\git.exe fetch --tags --force --progress -- https://github.com/khaleel916/ranirepo +refs/heads/*:refs/remotes/origin/* # timeout=10
 > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > C:\Program Files\Git\bin\git.exe rev-parse "origin/master^{commit}" # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE

**Comment by jstrachan** [comment]
I'm afraid I've no idea what this issue means. Are you using Jenkins X? why are you running those git commands? what are you trying to achieve?

**Comment by khaleel916** [comment]
trying to get files from github

**Comment by jstrachan** [comment]
I don't think this issue has anything to do with Jenkins X; you're using git commands on your own windows machine on your own repository?

**Comment by kushwahvishal939** [comment]
Running as SYSTEM
Building in workspace C:\ProgramData\Jenkins\.jenkins\workspace\websitehost
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/kushwahvishal939/iCoderBootstrap.git
 > git.exe init C:\ProgramData\Jenkins\.jenkins\workspace\websitehost # timeout=10
Fetching upstream changes from https://github.com/kushwahvishal939/iCoderBootstrap.git
 > git.exe --version # timeout=10
 > git --version # 'git version 2.37.3.windows.1'
 > git.exe fetch --tags --force --progress -- https://github.com/kushwahvishal939/iCoderBootstrap.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git.exe config remote.origin.url https://github.com/kushwahvishal939/iCoderBootstrap.git # timeout=10
 > git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
Checking out Revision 44af823dde4b38b522d4c7605cdfb1bb6bf9796e (refs/remotes/origin/master)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 44af823dde4b38b522d4c7605cdfb1bb6bf9796e # timeout=10
Commit message: "ok"
First time build. Skipping changelog.
[websitehost] $ sh -xe C:\Windows\TEMP\jenkins1020656610144971264.sh
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Caused: java.io.IOException: Cannot run program "sh" (in directory "C:\ProgramData\Jenkins\.jenkins\workspace\websitehost"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at hudson.Proc$LocalProc.<init>(Proc.java:254)
	at hudson.Proc$LocalProc.<init>(Proc.java:223)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:997)
	at hudson.Launcher$ProcStarter.start(Launcher.java:509)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:144)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:92)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:816)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:524)
	at hudson.model.Run.execute(Run.java:1899)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by kushwahvishal939** [comment]
please find a problem

**Comment by kushwahvishal939** [comment]
please help me

**Comment by moh-nis** [comment]
I was also getting the same error, Because while configuring the Job in jenkins, I had given my commands in "Execute shell" instead of "Execute Windows batch command" in Build steps screen. If Windows OS, then the commands to be given in "Execute Windows batch command".

**Comment by kangqianglong** [comment]
using credential 6b6ed48b-3eca-453f-b4b4-264d73905252 > /usr/bin/git rev-parse --resolve-git-dir /var/jenkins_home/workspace/springboot_23/.git # timeout=10 Fetching changes from the remote Git repository

**Comment by D-1988** [comment]
**How the below issue will be resolved** ?
Started by user [Dipan Chandra Dutta](http://localhost:8080/user/admin)
Obtained Testing-master/JenkinsFile from git https://github.com/D-1988/Selenium_TestNG.git
[Pipeline] Start of Pipeline
[Pipeline] node
Running on [Jenkins](http://localhost:8080/computer/(built-in)/) in C:\ProgramData\Jenkins\.jenkins\workspace\PipelineJenkinsGit
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential 18be9721-144a-4ae8-b67a-1b2325edb51f
 > C:\Program Files\Git\bin\git.exe rev-parse --resolve-git-dir C:\ProgramData\Jenkins\.jenkins\workspace\PipelineJenkinsGit\.git # timeout=10
Fetching changes from the remote Git repository
 > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/D-1988/Selenium_TestNG.git # timeout=10
Fetching upstream changes from https://github.com/D-1988/Selenium_TestNG.git
 > C:\Program Files\Git\bin\git.exe --version # timeout=10
 > git --version # 'git version 2.49.0.windows.1'
using GIT_SSH to set credentials
