### ISSUE TITLE
Update the doc to mention that "Kubernetes Engine API" should be enabled in the google cloud project

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#780]
After I created a google cloud account and a valid project ID, I started the Jenkins-X installation. It failed citing that Kubernetes API wasn't enabled. I wonder if this can be mentioned in the docs, right where we mention that a valid project ID is required?

**Comment by jstrachan** [comment]
we now explicitly enable `compute` and `container` to avoid these errors
