### ISSUE TITLE
check-registry step is failing to auth with ECR

### ISSUE THREAD

**Issue by sudarshanababu** [jenkins-x/jx#7802]
Hello,

I have installed JX3 in an existing EKS cluster by following the recommended sequence of steps and repository templates. The JX3 resources are getting deployed and operational. However, when I added a new quick start project, the pull-request pipeline step "step-check-registry" fails with the following error message.

I am using default security accounts for the pipeline pods, and noticed that the tekton-bot sa has annotation for an IAM role and the iam-role has trust relationship OIDC. 

thanks in advance for help with this. 

error: failed to lazy create the ECR registry for golangdemo2: failed to check for repository with registry ID : operation error ECR: DescribeRepositories, failed to sign request: failed to retrieve credentials: failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, https response error StatusCode: 400, RequestID: xxxxxxxxxxxxxxxxxxxxx, api error InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-1.amazonaws.com/id/xxxxxxxxxxxxxxxxxxxxxx

**Comment by jstrachan** [comment]
I recommend using the Jenkins X terraform and creating a new EKS cluster; otherwise you'll hit many issues getting all of the cloud resources setup correctly for Cloud IAM and the like to be able to push images, charts, consume them, store logs in buckets and whatnot.

https://jenkins-x.io/v3/admin/platforms/eks/

**Comment by jstrachan** [comment]
otherwise you can go through the terraform by hand and manually replicate all the cloud resources in your existing cluster; or try import your existing resources: https://www.terraform.io/docs/cli/import/index.html
