### ISSUE TITLE
Why does LATEST point to 001 when I did 2 more releases (002, 003) after it?

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#781]
See https://github.com/junibutler/gojenx/releases/tag/v0.0.1. 

This is for the quickstart go application. Don't understand why 001 is latest.

**Comment by jstrachan** [comment]
if you expand the dots you'll see 3 tags. 
https://github.com/junibutler/gojenx/releases

though it looks like an error occurred in the pipeline generating the changelogs - e.g. only one changelog was created: https://github.com/junibutler/gojenx/releases/tag/v0.0.1

I wonder can we see the jenkins logs for 0.0.2?

**Comment by jstrachan** [comment]
@junibutler any chance of the Jenkins logs for build `0.0.2` or `0.0.3`? You can use the Jenkins UI for that `jx console` or use `jx get build logs`)

* https://jenkins-x.io/commands/jx_console/
* https://jenkins-x.io/commands/jx_get_build_log/

**Comment by junibutler** [comment]
Yes, I expanded the dots and saw the 3 tags at https://github.com/junibutler/gojenx/releases. 

I do see changelogs for 002 and 003, with missing information like GitHub user id ("junibutler" in this case):

https://github.com/junibutler/gojenx/releases/tag/v0.0.2
https://github.com/junibutler/gojenx/releases/tag/v0.0.3

Let me attach the build log that I got from "jx get build logs". 

cc: @rawlingsj

**Comment by junibutler** [comment]
[build.log](https://github.com/jenkins-x/jx/files/1985775/build.log)

**Comment by jstrachan** [comment]
@junibutler that build log looks to be the promotion job in production; not the build log of the `gojenx` master pipeline for versions 0.0.2 / 0.0.3. It looks like 0.0.4 and 0.0.5 worked fine though right?

**Comment by junibutler** [comment]
Yes 004 and 005 worked fine. Now it looks good at 008. What may have happened is that 002 and 003 had failed. 

I can't reproduce this at this time. Will open a new one if I see weird behavior in the future.
