### ISSUE TITLE
google-cloud-sdk failed to install as part of the packaged JenkinsX installation, and had to be installed separately

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#782]
Getting errors:

Error: No available formula with the name "google-cloud-sdk" 

==> Searching for a previously deleted formula (in the last month)...

Warning: homebrew/core is shallow clone. To get complete history run:

  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.

==> Searching for similarly named formulae...

==> Searching local taps...

Error: No similarly named formulae found.

==> Searching taps...

==> Searching taps on GitHub...

This formula was found in a tap:

caskroom/cask/google-cloud-sdk

To install it, run:

  brew install caskroom/cask/google-cloud-sdk

Error: Command failed  brew install google-cloud-sdk

error: error installing gcloud: exit status 1

bash-3.2$ brew install caskroom/cask/google-cloud-sdk

==> brew cask install caskroom/cask/google-cloud-sdk 

==> Creating Caskroom at /usr/local/Caskroom

==> We'll set permissions properly so we won't need sudo in the future

**Comment by junibutler** [comment]
Happened again today on a different laptop. 

Junis-Air:gojenx Juni$ jx create cluster gke
gcloud not found
kubectl not found
helm not found
? Missing required dependencies, deselect to avoid auto installing:  [Use arrows to move, ? Missing required dependencies, deselect to avoid auto installing: gcloud, kubectl, helm
Error: Command failed  brew install google-cloud-sdk
error: error installing gcloud: exit status 1

Running "brew install google-cloud-sdk" separately did not work either. 

Junis-Air:gojenx Juni$ brew install google-cloud-sdk
Error: No available formula with the name "google-cloud-sdk" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
This formula was found in a tap:
homebrew/cask/google-cloud-sdk
To install it, run:
  brew install homebrew/cask/google-cloud-sdk

Finally, this worked: brew install homebrew/cask/google-cloud-sdk.

**Comment by junibutler** [comment]
thank you @jstrachan. tried out the instructions on the google cloud shell, and things work fine. 

what do you want to do with this ticket then? close it. we still don't know whether everyone will use the cloud shell or local laptop, but the question is, is there anything else we can do about it?

**Comment by jstrachan** [comment]
it does look like brew is no longer mentioned on the google cloud SDK page any more so we should probably switch to just downloading a distro and running the install shell script like this https://cloud.google.com/sdk/docs/quickstart-macos

**Comment by i0n** [comment]
Hey @junibutler 

Looks like the command to install google-cloud-sdk was slightly wrong in our code. I've fixed it and added a pull request here: https://github.com/jenkins-x/jx/pull/1114

Because it's a binary install (not a computed or compiled installation) you have to use "brew cask" instead of regular "brew"

**Comment by junibutler** [comment]
thanks @i0n ! yeah, i had a similar hunch when this manual command "brew install homebrew/cask/google-cloud-sdk" worked.
