### ISSUE TITLE
minikube woes continued - can't tell what's happening between minikube, hyperkit and jenkinsx

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#783]
Please change "If you still want to try minikube then we recommend starting from scratch and letting jx create it for you by running..." to set the correct expectations that folks need to get minicube working first before trying jx.

**Comment by hekonsek** [comment]
Yes, it should indicate creating *cluster*, not minikube itself.

**Comment by hekonsek** [comment]
@junibutler Is it (https://github.com/jenkins-x/jx-docs/pull/109) better?

**Comment by hekonsek** [comment]
@jstrachan I propose to close this one as https://github.com/jenkins-x/jx-docs/pull/109 as been merged.
