### ISSUE TITLE
We couldn’t deliver this payload: failed to connect

### ISSUE THREAD

**Issue by shubhamsingh93** [jenkins-x/jx#7846]
Using Classic Jenkins deployed on a windows machine on port 9090. Used public_IP:9090/github-webhook/ but it always fails.
Tried installing Jenkins on a CentOS machine on Virtual box and tried the same this. Same issue.
Able to access Jenkins UI on a different machine - That works. So This should not be a port issue.
Any ideas?

**Comment by shubhamsingh93** [comment]
Sorry. Closed by mistake. The issue is still present.

**Comment by jstrachan** [comment]
sounds like this issue should be raised against Jenkins?

**Comment by hieunguyen847** [comment]
I'm facing a same issue too. Have you solved it yet?

**Comment by jstrachan** [comment]
please raise Jenkins issues against the Jenkins project
