### ISSUE TITLE
serviceaccount token error installing jx on existing K8s cluster

### ISSUE THREAD

**Issue by bladerunner512** [jenkins-x/jx#785]
bldr512@node055:~/jenkins-x$ ./jx install
error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

on-premise k8s v1.9
docker : 17.03.2-ce
OS/Arch: linux/amd64 (Ubuntu 16.04)

Certificate info in kube config file ~/.kube/config:

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxxxxxx
    server: https://xx.xxx.xx.xxx:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: xxx
    client-key-data: xxx

**Comment by rawlingsj** [comment]
Are you trying to run the `jx install` command from inside the cluster?  If so can you run it from outside the cluster from your dev machine after you've authenticated and can run `kubectl get nodes` for example?
