### ISSUE TITLE
Error in jx installation on minikube: no matches for kind "Ingress" in version "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by shubhamunthinkable** [jenkins-x/jx#7852]
I'm following the installation instruction for minikube. from here

link https://jenkins-x.io/v3/admin/platforms/minikube/

Getting the following error in install the git operator:

output of jx admin logs :

configmap/config-observability created
configmap/config-registry-cert created
validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.pipeline.tekton.dev created
configmap/feature-flags created
configmap/pipelines-info created
serviceaccount/tekton-bot created
deployment.apps/tekton-pipelines-controller created
rolebinding.rbac.authorization.k8s.io/tekton-pipelines-controller-leaderelection created
rolebinding.rbac.authorization.k8s.io/tekton-pipelines-controller created
role.rbac.authorization.k8s.io/tekton-pipelines-controller created
serviceaccount/tekton-pipelines-controller created
service/tekton-pipelines-controller created
rolebinding.rbac.authorization.k8s.io/tekton-pipelines-info created
role.rbac.authorization.k8s.io/tekton-pipelines-info created
role.rbac.authorization.k8s.io/tekton-pipelines-leader-election created
podsecuritypolicy.policy/tekton-pipelines created
deployment.apps/tekton-pipelines-webhook created
horizontalpodautoscaler.autoscaling/tekton-pipelines-webhook created
rolebinding.rbac.authorization.k8s.io/tekton-pipelines-webhook-leaderelection created
rolebinding.rbac.authorization.k8s.io/tekton-pipelines-webhook created
role.rbac.authorization.k8s.io/tekton-pipelines-webhook created
serviceaccount/tekton-pipelines-webhook created
service/tekton-pipelines-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.pipeline.tekton.dev created
secret/webhook-certs created
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.pipeline.tekton.dev created
unable to recognize "config-root/namespaces/jx/jx-pipelines-visualizer/jx-pipelines-visualizer-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
unable to recognize "config-root/namespaces/jx/jxboot-helmfile-resources/bucketrepo-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
unable to recognize "config-root/namespaces/jx/jxboot-helmfile-resources/hook-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
make[1]: *** [versionStream/src/Makefile.mk:288: kubectl-apply] Error 1
make[1]: Leaving directory '/workspace/source'
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:240: regen-check] Error 1

minikube version: v1.12.1
Server Version: v1.18.3
jx Version: 3.2.147

**Comment by jstrachan** [comment]
see bullet 3 here: https://jenkins-x.io/v3/about/changes/#breaking-changes 

upgrading minikube might be simplest to 1.19 of kubernetes

**Comment by jstrachan** [comment]
or try a more recent minikube - the one you are on is very old - eg https://github.com/kubernetes/minikube/releases/tag/v1.22.0 try at least 1.19
