### ISSUE TITLE
Support alicloud

### ISSUE THREAD

**Issue by HongjiangHuang** [jenkins-x/jx#7855]
I want to deploy `jenkins-x` with alicloud, I would like to offer some contributions to this.

Can anyone tell me what else I need to do besides providing a `terraform-alicloud-jx` like this?

**Comment by jstrachan** [comment]
Hi @HongjiangHuang - welcome!

Probably the simplest thing to do is start off by just creating your alicloud kubernetes cluster however you like; then trying to install Jenkins X via the on premise instructions:

https://jenkins-x.io/v3/admin/platforms/on-premises/

then see if there's anything you'd like to change in terms of configuration when on alicloud and let us know - via an issue or slack - and we can try create a new repository based on https://github.com/jx3-gitops-repositories/jx3-kubernetes such as a new repository, say, `jx3-alicloud`?

**Comment by HongjiangHuang** [comment]
Thanks @jstrachan
