### ISSUE TITLE
Jenkins pipeline view showing NaN* for stage duration

### ISSUE THREAD

**Issue by junibutler** [jenkins-x/jx#786]
![screen shot 2018-05-08 at 3 47 22 pm](https://user-images.githubusercontent.com/38925583/39787055-3ee974a8-52d8-11e8-9c93-1c74a500c4fd.png)

See the first stage "CI Build and push snapshot" in the screenshot and notice how the stage duration comes out to be NaN*. I introduced a bug in the default go app, and broke the pipeline. Then I fixed the issue. However, the UI remained broken.

**Comment by michaelneale** [comment]
@junibutler probably best for the stage view plugin, I don't think this is jenkins x - also if yoy look at the blue ocean view of this screen it wont' show NaN

**Comment by junibutler** [comment]
That stage is not executed due to a when conditional that's not being met. So this is the expected behavior. Most of the Jenkinsfiles in the JenkinsX draft packs have this conditional, and hence most of us have already seen this or will see this soon when running pipelines on branches that do not start with "PR-". I am on the master branch and hence see this. Doesn't look healthy for sure. 

@michaelneale could be best for the stage view plug-in, yes. please let me know where to file issues for that. and how to expedite the fix since the word is getting out for jenkinsx.

The BlueOcean view does not show the NaN, and is able to depict the bypass more gracefully. So we are good there.

**Comment by michaelneale** [comment]
@junibutler right - perhaps we can make it link to blue by default and this will naturally "go away" - is this possible to change the links @rawlingsj ? 

@junibutler https://wiki.jenkins.io/display/JENKINS/Pipeline+Stage+View+Plugin is the other plugin, but it is not heavily maintained now.

**Comment by michaelneale** [comment]
@junibutler no formal list like that, but the stage view has been expensive to maintain

**Comment by junibutler** [comment]
All right @michaelneale. All good then. At CBU, I raised this issue with people who can help - the issue being "how do we decide on which plugins to maintain, and which to not maintain". 

I also raised to folks that BlueOcean needs to be marketed more, so that people drop the other views. 

Other than that, for the purpose of this bug, we are good. So, closing out.

**Comment by michaelneale** [comment]
@junibutler thanks! Yes I think since this ticket was opened, most of the views direct to blue ocean for Jenkins X where possible so people are less likely to see this.

**Comment by junibutler** [comment]
Re-opening since BlueOcean is no longer my default view any more.

**Comment by junibutler** [comment]
@rajdavies did anything change?

**Comment by michaelneale** [comment]
@junibutler if this is a regression please open it as another ticket. The title/content of this one is confusing if the problem is some links aren't goign to the right place, the content here is mostly noise. I would open a new ticket.

**Comment by michaelneale** [comment]
@junibutler when I run "jx open jenkins" I get to /blue - are there specific cases, not sure what you mean by "default view"?

**Comment by junibutler** [comment]
@michaelneale you are right. "jx open jenkins" opens blue. when i log in from the UI, the classic view shows up. Is that what's expected? In any case, i am closing this issue as you suggested since the original problem reported was different.

**Comment by michaelneale** [comment]
@junibutler got it - yes there is no default-all to blue ocean (yet). There was a plugin attempted once but it had other side effects. I think the blue ocean team were going to look at a config option to make it default to blue when you go to the console directly (it can also be done with proxy - which Tyler does with ci.jenkins.io, so that could be a valid feature request for Jenkins X?) https://issues.jenkins-ci.org/browse/JENKINS-46706 is the blue ocean one

**Comment by michaelneale** [comment]
@junibutler follow on ticket: https://github.com/jenkins-x/jx/issues/1276 (has been asked for before, and jenkins X can probably trivially make this happen as a nice to have)
