### ISSUE TITLE
the path "config-root/customresourcedefinitions" does not exist 

### ISSUE THREAD

**Issue by bvboca** [jenkins-x/jx#7895]
1. fork the repo to https://github.com/bvboca
2. Intall jx on on-premise kubenetes 1.18
3. Install git operator

4. The jx boot job keeps failing with:
jx gitops git setup
setup git user  email jenkins-x@googlegroups.com
generated Git credentials file: /workspace/xdg_config/git/credentials with username: bvboca email: 
jx gitops apply
found last commit message: Merge pull request #1 from bvboca/ChangeNetworkVersion
Change network version
last commit was a merge pull request without changing an ExternalSecret so not regenerating
make regen-none
make[1]: Entering directory '/workspace/source'
make[1]: Nothing to be done for 'regen-none'.
make[1]: Leaving directory '/workspace/source'
using kubectl to apply resources
kubectl apply --force --prune -l=gitops.jenkins-x.io/pipeline=customresourcedefinitions -R -f config-root/customresourcedefinitions
error: the path "config-root/customresourcedefinitions" does not exist
make: *** [versionStream/src/Makefile.mk:287: kubectl-apply] Error 1

Console shows:

Change network version
last commit was a merge pull request without changing an ExternalSecret so not regenerating
make regen-none
make[1]: Entering directory '/workspace/source'
make[1]: Nothing to be done for 'regen-none'.
make[1]: Leaving directory '/workspace/source'
using kubectl to apply resources
kubectl apply --force --prune -l=gitops.jenkins-x.io/pipeline=customresourcedefinitions -R -f config-root/customresourcedefinitions
error: the path "config-root/customresourcedefinitions" does not exist
make: *** [versionStream/src/Makefile.mk:287: kubectl-apply] Error 1
boot Job pod jx-boot-0097a7b8-b96c-4005-8881-674f8d819bbd-5qzgp has Failed
boot Job jx-boot-0097a7b8-b96c-4005-8881-674f8d819bbd has Failed
error: failed to tail the Jenkins X boot Job pods: job jx-boot-0097a7b8-b96c-4005-8881-674f8d819bbd failed

**Comment by jstrachan** [comment]
I think there is another error earlier in the log. My guess is it’s the 1.18 version of k8s and Ingress v1 not being supported - as v1beta1 has been removed in 1.21.

see the third bullet here: https://jenkins-x.io/v3/about/changes/#breaking-changes

**Comment by bvboca** [comment]
thanks! upgraded to k8s 1.19, the issue is gone.
