### ISSUE TITLE
jx uninstall does not remove ingress controller

### ISSUE THREAD

**Issue by BrianChristie** [jenkins-x/jx#790]
When doing `jx install` in a cluster without an ingress-controller, the option is presented to install an nginx ingress-controller in the kube-system namespace.

After a `jx uninstall`, the following resources are left in the cluster:
Deployment & Service:
- jxing-nginx-ingress-controller
- jxing-nginx-ingress-default-backend

It may be problematic to remove these if they are being otherwise used in the cluster, but the uninstaller should note that they have not been removed.

Also, my understanding is that the `kube-system` namespace is strictly reserved for core Kubernetes components, so perhaps this ingress should go into another namespace? For example, on GKE, anything added to kube-system will trigger errors from the cluster watchdog service.

**Comment by nukepuppy** [comment]
Definitely on most of what was said.. except kube-system is commonly also used for ingress which .. this is
