### ISSUE TITLE
command doesn't work

### ISSUE THREAD

**Issue by dsharma1310** [jenkins-x/jx#7912]
an issue found in the documentation : https://jenkins-x.io/docs/install-setup/install-binary/

I have followed the command for Linux os, but when I run the command it gives:
 jx version --short
Error: unknown flag: --short

Options:
  -q, --quiet=false: uses the quiet format of just outputting the version number only
Usage:
  jx version [flags] [options]
Use "jx version options" for a list of global command-line options (applies to all commands).

**Comment by jstrachan** [comment]
I wonder if you have the 3.x binary and are using the old 2.x install instructions?
https://jenkins-x.io/v3/admin/
