### ISSUE TITLE
Error: unknown command "boot" for "jx"

### ISSUE THREAD

**Issue by kodekolli** [jenkins-x/jx#7918]
I followed the below document for jx binary install and created gke cluster. After that tried booting the k8 cluster using jx boot getting below error.
Document: https://jenkins-x.io/docs/install-setup/install-binary/  on ubuntu linux.
Error: unknown command "boot" for "jx"

**Comment by jstrachan** [comment]
those are the deprecated 2.x docs: try the 3.x docs instead:
https://jenkins-x.io/v3/admin/
