### ISSUE TITLE
jx log appears to be broken

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#794]
Using:
> NAME               VERSION
> jx                 1.2.51
> jenkins x platform 0.0.970
> kubernetes cluster v1.9.6-gke.1
> kubectl            v1.9.6
> helm client        v2.9.0+gf6025bb
> helm server        v2.9.0+gf6025bb
> git                git version 2.15.1 (Apple Git-101)

Actions:
Execute `jx log` and select a pod. Execution hangs after the following output and no logs are displayed:
```
➜ jx log
? Pick Deployment: jx-staging-calendar-api
Waiting for a running pod in namespace jx-staging with labels map[app:jx-staging-calendar-api draft:draft-app]
Found newest pod: jx-staging-calendar-api-648d7c69c4-499sl
```
Using `kubectl -n jx-staging logs ...` works fine.

**Comment by jstrachan** [comment]
wonder if its waiting for the pod to get ready before showing the log?

**Comment by tdcox** [comment]
@jstrachan No, it seems to be all pods including those in the jx namespace as well as those in staging.

**Comment by jstrachan** [comment]
damn, thanks for checking. Wonder if its the new verbose changes - does adding `-v` help?

**Comment by tdcox** [comment]
`Error: unknown shorthand flag: 'v' in -v`

**Comment by jstrachan** [comment]
yeah - its the verbose changes; PR on its way...

**Comment by tdcox** [comment]
Still the same problem here with 1.2.54
