### ISSUE TITLE
Unable to pull builder image from Google Container Registry

### ISSUE THREAD

**Issue by pradyuman** [jenkins-x/jx#7943]
We've started to get the following error during our builds today: `Cannot pull image 'gcr.io/jenkinsxio/builder-maven:2.1.155-778' from the registry.`

Seems like this image no longer exists (or we're no longer authorized to access it). What's the best way for us to work around this on our end?

**Comment by shanedownes-dmi** [comment]
[See here](https://jenkins-x.io/blog/2021/08/26/moving-v2-artifacts/#v2-users) for instructions

**Comment by ankitm123** [comment]
This can be closed, as @shanedownes-dmi's answer is sufficient.
