### ISSUE TITLE
chartmusem.jenkins-x.io not accesible

### ISSUE THREAD

**Issue by pedropena** [jenkins-x/jx#7946]
Currently is answering a 403:

<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message></Error>

**Comment by mow20** [comment]
Same here

**Comment by zubair-airborneapp** [comment]
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
error: failed to build dependencies for chart from directory '.': failed to add chart repositories: failed to add the Helm repository with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io': prompting for creds for https://storage.googleapis.com/chartmuseum.jenkins-x.io: asking for username: EOF

**Comment by dalwar23** [comment]
See #7942

**Comment by pedropena** [comment]
Ok, looks like it will be down forever. It has been migrated according to https://jenkins-x.io/blog/2021/08/26/moving-v2-artifacts/
