### ISSUE TITLE
step-check-registry failed

### ISSUE THREAD

**Issue by maiakhoa** [jenkins-x/jx#7952]
I got this error while running pipeline, anyone faced this issue

`error: failed to lazy create the ECR registry for : failed to check for repository with registry ID : operation error ECR: DescribeRepositories, failed to sign request: failed to retrieve credentials: failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, https response error StatusCode: 400, RequestID: 939065b8-bafd-40ce-9cac-xxxx, api error InvalidIdentityToken: No OpenIDConnect provider found in your account for`

**Comment by ankitm123** [comment]
Closing as this was resolved here: https://github.com/jx3-gitops-repositories/jx3-terraform-eks/issues/24
