### ISSUE TITLE
Hanging pipeline at Git Clone

### ISSUE THREAD

**Issue by maiakhoa** [jenkins-x/jx#7957]
Many pipeline was hanging at Git Clone step. Please help to advise!

![image](https://user-images.githubusercontent.com/1437050/133934618-6e78d223-eac5-4744-866a-e05aec3c9e01.png)

**Comment by ankitm123** [comment]
Best to describe the job pods, and see if something is off, most probably they are not getting scheduled because of missing secrets or node constraints ...

**Comment by ankitm123** [comment]
Closing this as it seems unrelated to Jenkins X, and probably some issue with the end user scripts.
/close
