### ISSUE TITLE
Cluster should take precedence over node-label while creating the Jenkins slave

### ISSUE THREAD

**Issue by kamuops** [jenkins-x/jx#7974]
We are running jenkins 2.289.1 running on k8s, and its configured with multiple pod templates and kubernetes clusters to deploy the slave pods. The problem which we are facing is , whenever we trigger the jenkins job the node-lable is taking precedence and pod is getting created on random  cluster not the exact cluster ( which we specified in the jenkinsfile).

**Comment by ankitm123** [comment]
Seems like this is related to Jenkins and not Jenkins X.
