### ISSUE TITLE
How to cleanup complete JX setup after successful installation????

### ISSUE THREAD

**Issue by vmasule** [jenkins-x/jx#8000]
This seems very stupid question but after installation using this doc [here](https://jenkins-x.io/v3/admin/platforms/on-premises/) I couldn't find how to cleanup whole setup and recreate it multiple times. I just can't find destroy commands in CLI reference guide.

How you would do it on production if required to recreate the whole setup????

**Comment by ankitm123** [comment]
Are u using v3? are u using eks/gke/azure?
Did u use terraform to provision the cluster where u are installing jx?
For just removing the jx specific components, this is what u need:
https://jenkins-x.io/v3/develop/faq/general/#how-do-i-uninstall-jenkins-x

**Comment by vmasule** [comment]
@ankitm123 Thanks, I will try this out next. Well, I was exploring the JenkinsX feature on local K8s setup only.

**Comment by ankitm123** [comment]
https://github.com/jenkins-x/jx-docs/pull/3486 -> This PR should make it much clearer for new users on how to uninstall JX.
