### ISSUE TITLE
The Makefile missing after running jx import on go project

### ISSUE THREAD

**Issue by phthaocse** [jenkins-x/jx#8005]
When I do `jx import` for my project that has my own Makefile existed, then the Makefile from the build pack wasn't imported. So I try to move my Makefile to another place then remove all files that come from the last import and run `jx import` again, but the Makefile from the build pack still missing. You can check this on https://github.com/thaophan-jx3/user-service-go/commit/9675adc09ad5d96811ba0899b57565f93bea6007 

After that I try to create from scratch a go project with only main.go and try to run `jx import` and the result is the same, no Makefile appear (check this https://github.com/thaophan-jx3/test/commit/9e4aaf05c08139bacde539f32f0f7fa4f365e920)

Finally, I experiment with the `jx project quickstart` and everythings is good, the Makefile has appeared (https://github.com/thaophan-jx3/test-go-jx/commit/4c1ac1989e113894383dcef3c39a9257f05a6d4b)

Can you guys have some explaination or solution for this ?

**Jx version 3.2.217**

**Comment by ankitm123** [comment]
jx project import uses the files from jx3-pipeline-catalog repo. So in ur case, it copies the files from packs/go which does not have a makefile: https://github.com/jenkins-x/jx3-pipeline-catalog/tree/master/packs/go.

jx project quickstart uses the golang-http repo inside the quickstart org: https://github.com/jenkins-x-quickstarts/golang-http, this has the makefile, hence u see the makefile.
