### ISSUE TITLE
Not all resources removed from repo are pruned

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#8024]
Pruning of the resources from a cluster that has been removed from its repo doesn’t work reliably.

# Steps to reproduce

1. Add a  HorizontalPodAutoscaler, for example by setting the helm value hpa.enable = true in for an application.
2. Verify that the hpa is created after the boot job has run.
3. Remove the hpa again, for example by setting hpa.enable = false

# Expected result

The hpa is removed by the boot job

# Actual result

The hpa still exists.

# Technical notes

The removal is supposed to be done by the `kubectl apply --prune...`  commands in [Makefile.mk](https://github.com/jenkins-x/jx3-versions/blob/master/src/Makefile.mk). The main problem is that only a select few resource types are applicable for pruning by default (see https://github.com/kubernetes/kubernetes/blob/b2b4cb17256de8d89d4d5fdbe8d19a2492e8152c/staging/src/k8s.io/kubectl/pkg/cmd/apply/prune.go#L177-L192; the list varies for different versions of kubectl).

You can override the default list with --prune-whitelist  options, but the question is how to assemble these options.

**Comment by msvticket** [comment]
A potential route to fix this is to change to using `kpt live apply`: https://kpt.dev/book/06-deploying-packages/

I'll note that if we go this route we want to upgrade kpt first since the way kpt stores the state in the cluster has changed since the version and it would be good to avoid the hassle of automating that upgrade. 
https://github.com/jenkins-x-plugins/jx-gitops/blob/1414e63a83a48bf5a9b227e09e8e6152737026f3/pkg/plugins/versions.go#L28

**Comment by msvticket** [comment]
Now I feel a bit silly... There is already support for a similar tool in Makefile.mk: kapp
Maybe we should make kapp-apply the default for KUBEAPPLY? I'll experiment a bit.

**Comment by ankitm123** [comment]
I think James and chris were looking at kapp before, and there were few issues with switching between kubectl apply and kapp. BUt we probably want to look at kapp controller, also it would be useful for drift detection. (There was a slack thread from James Rawlings about kapp controller)

**Comment by msvticket** [comment]
Yeah, I noticed that switching to kapp on an existing cluster didn't work. I tried to recreate the cluster but it still doesn't work. I don't understand why immediately and I need that cluster for other work. So I'll set this aside for now. 

Maybe `kpt live` is easier to get working. I think it can be used for drift detection as well.

**Comment by msvticket** [comment]
Ah, seems like kapp bailed out due to some error with some health check pods. With `--wait=false` it might have worked.
