### ISSUE TITLE
error in installation: jx-build-controller and nexus

### ISSUE THREAD

**Issue by BigFatDog** [jenkins-x/jx#8030]
Hello, could you please help me with this?

I'm installing jx3 on bare metal k8s v1.21.5 and find the following problems:
1. jx-build-controller uses incorrect git repo

I'm hosting operator on `gitee` other than `github`,  but `jx-build-controller` is still using github while the other pods are using `gitee`  url correctly:

The correct one:
```
https://${user}:${token}@gitee.com/exceeddata/jx4.git
```

but `jx-build-controller` pod shows errors of cloning code from a `github` repo:
```
https://${user}:${token}@github.com/exceeddata/jx4.git
```

How should I fix this?

2. I configured `jx-requirements.yaml` to use nexus as repo:
```
...
repository: nexus
...
```
Now I can see only nexus ingress in `jx` namespace, but no resources(svc, pods, etc) associated.

3. Other observations:
All other pods are running, all jobs in `jx-git-operator` succeeded.

**Comment by ankitm123** [comment]
Did u set the gitprovider to gitee? I know we dont support gitee yet though, see: https://github.com/jenkins-x/go-scm/issues/307

**Comment by BigFatDog** [comment]
i see. Thank you.
