### ISSUE TITLE
Error : failed to find Dev Environment: the server could not find requested resource (get environments.jenkins.io)

### ISSUE THREAD

**Issue by dupatvj** [jenkins-x/jx#8036]
When executing jx project , I am getting Error : failed to validate options : failed to find the dev environment the server could not find requested resource (get environments.jenkins.io) .

This Error is specific to GCP 

On on-premise minikube error is as follows : 
error : no spec.source.url for dev environment so cannot clone the version stream .

To setup Jenkins X followed instructions as per Jenkins X documentation . Please suggest to resolve this issues.

**Comment by ankitm123** [comment]
Did ur boot job succeed? Check the output of `jx admin log`

Also when u created the cluster using tf, did u use the quickstart template? https://jenkins-x.io/v3/admin/platforms/google/
