### ISSUE TITLE
Incorrect urls in official documentation

### ISSUE THREAD

**Issue by bartoliniii** [jenkins-x/jx#8043]
I'm trying to configure Jenkins X in my company and found some broken links.

Example of links:
- "trying out a quickstart first" on https://jenkins-x.io/v3/develop/create-project/
- "charts/jenkins-x/tekton/values.yaml.gotmpl" on https://jenkins-x.io/v3/develop/apps/
- "edit any pipeline in any git repository" on https://jenkins-x.io/v3/develop/pipelines/#add-new-taskspipelines-by-hand
- "add new pipelines to any git repository" on https://jenkins-x.io/v3/develop/pipelines/#add-new-taskspipelines-by-hand

**Comment by halloweed** [comment]
I found this on "good first issues" and, if no one has anything against it, would like to solve it as my very first task.

**Comment by bartoliniii** [comment]
@halloweed I found one more incorrect link:
- "charts/jenkins-x/tekton/values.yaml.gotmpl" in https://jenkins-x.io/v3/develop/apps/#customising-charts

**Comment by halloweed** [comment]
Hi Folks, I need to leave it, unfortunately.

**Comment by rajatgupta24** [comment]
Hey @ankitm123 @bartoliniii, Can I take this?
