### ISSUE TITLE
Feature Request: Artifactory support and documentation

### ISSUE THREAD

**Issue by StevenACoffman** [jenkins-x/jx#805]
I've heard in the forums that you plan to support Artifactory (vs. currently Nexus only AFAICT), but I don't see it on the roadmap or an issue, so I'd like to track it here. If this is the wrong spot, or there's already a duplicate, then apologies in advance.

Thanks for all your nice work!

**Comment by jstrachan** [comment]
thanks! We should probably refactor both nexus & artifactory to both be addons then they become peers; we can have a default but folks can enable/disable the addons they need

**Comment by yahavi** [comment]
@StevenACoffman,
I recently submitted the following three pull requests, which allow configuring your existing Artifactory instance while installing Jenkins X:
https://github.com/jenkins-x/jx/pull/1274
https://github.com/jenkins-x/jenkins-x-image/pull/32
https://github.com/jenkins-x/draft-packs/pull/50

**Comment by StevenACoffman** [comment]
So @yahavi what happened after jenkins-x/jx#1753 Did this get added as an application?

**Comment by StevenACoffman** [comment]
> As far as I know, no one took this initiative following our attempt to push this functionality.
