### ISSUE TITLE
Add a Git provider for VSTS 

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#809]
API documentation:
https://docs.microsoft.com/en-us/rest/api/vsts/git/?view=vsts-rest-5.0

**Comment by jstrachan** [comment]
I wonder if VSTS git providers has the idea of a CI build status on PRs / commits? We're using that right now for github/bitbucket etc so we can know if a PR passed its CI pipelines etc

**Comment by jstrachan** [comment]
there may be some git providers where there isn't this kind of feature supported; so we could maybe use CRDs for that use case?

**Comment by ccojocar** [comment]
It seems to be a PR status resource, which could be used to update the build status. At least in UI, it shows some build status.
https://docs.microsoft.com/en-us/rest/api/vsts/git/pull%20request%20statuses/get?view=vsts-rest-5.0#gitstatuscontext

**Comment by jstrachan** [comment]
@ccojocar ah great! should be fine then!

**Comment by AceHack** [comment]
Is there a VSTS provider/

**Comment by ccojocar** [comment]
No yet. The issue was closed by the lifecycle plugin.

**Comment by AceHack** [comment]
Are there any workarounds for using Jenkins X with VSTS git?

**Comment by ccojocar** [comment]
I am not aware of any workarounds.

**Comment by AceHack** [comment]
Where would I start if I wanted to code a VSTS provider, I'm looking for some provider abstraction I can add to.  Thanks.

**Comment by AceHack** [comment]
Please keep open

**Comment by AceHack** [comment]
Please keep this open and add a provider

**Comment by AceHack** [comment]
Please don't let this rot, we need VSTS/Azure DevOps support.

**Comment by AceHack** [comment]
Please keep this open
