### ISSUE TITLE
Show some diagnostics information to the user when the install fails

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#810]
It would be nice to collect some diagnostic information which can be displayed to the user when the installation fails. Currently, a helm timeout message or something similar is shown. 

I am thinking to have some message form the Kubernetes events related to the failed resource. Maybe investigate if [sonobuoy](https://github.com/heptio/sonobuoy) tool can do this job.

**Comment by jstrachan** [comment]
yeah - I'd love a way to verify the k8s cluster first for our known requirements (e.g. enough nodes, storage / storage classes, networking, disk etc) - maybe a sonobuoy report that can inform users what to do before even trying to install

**Comment by ccojocar** [comment]
Shell we add a command e.g. `jx conformance` which runs the sonobuoy and provide some information to the user if is good to proceed with the installation?

**Comment by jstrachan** [comment]
that would be amazing yeah!
