### ISSUE TITLE
"jx install" with minikube on windows 

### ISSUE THREAD

**Issue by no-stupid-questions** [jenkins-x/jx#813]
I am using hyper-V and minikube on windows, and trying to perform the "jx install" command. However I am receiving deployment errors with Jenkins and Jenkins-x-nexus. Also the link to get the API token from chromedp does not work

Output:
![image](https://user-images.githubusercontent.com/38955053/40019209-921b0548-578c-11e8-997a-3ca0ef767ccc.png)

Text:
waiting for install to be ready, if this is the first time then it will take a while to download images
deployment jenkins failed to become ready in namespace jx
deployment jenkins-x-nexus failed to become ready in namespace jx
Jenkins X deployments ready in namespace jx

        ********************************************************

             NOTE: Your admin password is: [32mflamemud[0m

        ********************************************************

        Getting Jenkins API Token
unable to automatically find API token with chromedp using URL http://jenkins.jx.172.16.22.210.nip.io/me/configure
Please go to [32mhttp://jenkins.jx.172.16.22.210.nip.io/me/configure[0m and click [32mShow API Token[0m to get your API Token
Then COPY the token and enter in into the form below:

? API Token: *****************
Created user [32madmin[0m API Token for Jenkins server [32mjenkins.jx.172.16.22.210.nip.io[0m at [32mhttp://jenkins.jx.172.16.22.210.nip.io[0m
Creating default staging and production environments
WARNING: Could not load config: %!s(<nil>)WARNING: The current user cannot query secrets in the namespace jx: Get https://172.16.22.210:8443/api/v1/namespaces/jx/secrets?labelSelector=jenkins.io%2Fkind%3Dgit: dial tcp 172.16.22.210:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 172.16.22.210:8443: connectex: No connection could be made because the target machine actively refused it.

Any help would be appreciated

**Comment by liuxiaopiao** [comment]
met the same problem. Any comments?

**Comment by ccojocar** [comment]
@no-stupid-questions I am going to close this issue since the minikube support has improved in the meantime. Fell free to open another issue if you are still facing this problem. Thanks
