### ISSUE TITLE
Fresh install on Openshift Error

### ISSUE THREAD

**Issue by EtizazKhan** [jenkins-x/jx#8132]
I am trying to install Jenkinsx on Openshift (using https://jenkins-x.io/v3/admin/platforms/openshift/) and I am running the following command to get the operator running.

`JX_LOG_LEVEL=debug jx admin operator --username myuser --token mytoken--url myurl`

The operator pod seems to be running fine however the jx-boot pods are showing the following issue in the logs. I have been following the documentation but I am unsure as to why this is appearing. Any help is greatly appreciated.

`Error from server (InternalError): error when creating "config-root/namespaces/tekton-pipelines/tekton-pipeline/feature-flags-cm.yaml": Internal error occurred: failed calling webhook "config.webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/config-validation?timeout=30s": no endpoints available for service "tekton-pipelines-webhook"
Error from server (InternalError): error when creating "config-root/namespaces/tekton-pipelines/tekton-pipeline/pipelines-info-cm.yaml": Internal error occurred: failed calling webhook "config.webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/config-validation?timeout=30s": no endpoints available for service "tekton-pipelines-webhook"
make[1]: *** [versionStream/src/Makefile.mk:290: kubectl-apply] Error 1
make[1]: Leaving directory '/workspace/source'
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:242: regen-check] Error 1`

**Comment by ankitm123** [comment]
Most likely an issue with ur node to node or node to control plane network traffic. May be some network policy is preventing access to the webhooks?

**Comment by EtizazKhan** [comment]
@ankitm123 I have tried to reinstall it however in the command line itself after running the 'jx admin operator' command I am seeing the following error:

`pod jx-boot-c64c3f51-213c-43fd-bea7-70079db33237-h6k9n has status Ready

tailing boot Job pod jx-boot-c64c3f51-213c-43fd-bea7-70079db33237-h6k9n

DEBUG: about to run: kubectl logs -n jx-git-operator -f -c job jx-boot-c64c3f51-213c-43fd-bea7-70079db33237-h6k9n
WARNING: failed to tail log: failed to run command: kubectl logs -n jx-git-operator -f -c job jx-boot-c64c3f51-213c-43fd-bea7-70079db33237-h6k9n: exec: "kubectl": executable file not found in $PATH
DEBUG: boot Job jx-boot-c64c3f51-213c-43fd-bea7-70079db33237 is not completed yet`

I'm guessing this is linked to the issue in the pod?
