### ISSUE TITLE
Github rest api issue

### ISSUE THREAD

**Issue by bkahlerventer** [jenkins-x/jx#8133]
running jx produces the following errors:

jx version
version: 3.2.293

jx boot
ERROR: failed to load plugin jx-boot: can't find latest version of plugin: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-the-latest-release"}

jx help
ERROR: failed to load plugin jx-help: can't find latest version of plugin: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-the-latest-release"}

It appear sgithub changed their APIs

**Comment by ankitm123** [comment]
Those are not valid subcommands, try `jx --help`

**Comment by bkahlerventer** [comment]
$ jx --help
Jenkins X 3.x command line

General:
  dashboard View the Jenkins X Pipelines Dashboard
  namespace View or change the current namespace context in the current Kubernetes cluster
  ui Views the Jenkins X UI (octant)
  upgrade Upgrades resources
  version Displays the version of this command
  add Adds one or more resources
  get Display one or more resources
  create Create one or more resources
  start Starts a resource
  stop Stops a resource
  import alias for: jx import

Other Commands:
  help Help about any command

Usage:
  jx [flags] [options]
Use "jx <command> --help" for more information about a given command.
$ jx help --help
ERROR: failed to load plugin jx-help: can't find latest version of plugin: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-the-latest-release"}

So the help command in  "Other Commands" section is not a command?

**Comment by ankitm123** [comment]
> So the help command in "Other Commands" section is not a command?

help is not a valid command, so you can do something like this
```
jx project --help
```
or
```
jx pipeline --help
```

but `jx help` is not a valid subcommand.

**Comment by nishantn3** [comment]
Hi @bkahlerventer 

Did the `jx boot` command work for you?

**Comment by ankitm123** [comment]
jx boot is v2 (unmaintained), please use v3.

**Comment by Godtrilla** [comment]
Any word on this issue? I'm trying to install on a GKE cluster.

**Comment by Godtrilla** [comment]
I have found a solution to this issue.  The problem is the jx plugin.  A quick clean up would be to install using brew.  
`brew install jenkins-x/jx/jx`
