### ISSUE TITLE
jx create cluster gke fails because nginx ingress crashes

### ISSUE THREAD

**Issue by ianwalter** [jenkins-x/jx#814]
Running
```fish
jx create cluster gke
```
fails with:
```fish
error creating cluster deployment jxing-nginx-ingress-controller never became ready
```
Pod log says:
```
F0514 20:52:57.975639 8 launch.go:118] no service with name kube-system/jxing-nginx-ingress-default-backend found: services "jxing-nginx-ingress-default-backend" is forbidden: User "system:serviceaccount:kube-system:default" cannot get services in the namespace "kube-system": Unknown user "system:serviceaccount:kube-system:default"
```
The Kubernetes version defaulted to 1.8.8 the first time but specifying `-v 1.9.7` yielded the same result.

**Comment by jstrachan** [comment]
I wonder if your user doesn't have karma to write to the `kube-system` namespace? 

You could try overriding the namespace used for ingress to something you can see via `jx create cluster gke --ingress-namespace cheese` 
https://jenkins-x.io/commands/jx_create_cluster_gke/

**Comment by ianwalter** [comment]
That worked. So it seems like a service account is not created for the ingress if a namespace is not specified? Because why would it be trying to use "system:serviceaccount:kube-system:default"?

Thanks for your help!

**Comment by jhendrick** [comment]
I have the same setup and I get the same issue here, but the suggestion mentioned by @jstrachan doesn't seem to work for me.  Getting:

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in cheese namespace
Note: this loadbalancer will fail to be provisioned if you have insufficient quotas, this can happen easily on a GKE free account. To view quotas run: gcloud compute project-info describe
ingress init failed: service jxing-nginx-ingress-controller never became ready
error creating cluster service jxing-nginx-ingress-controller never became ready
error: service jxing-nginx-ingress-controller never became ready

My quotas look to be ok, this is a new account.  When I check after the fact, the ingress pods actually appear to be running:

Joshuas-MBP:~ jhendrick$ kubectl --namespace=cheese get pods
NAME                                                 READY     STATUS    RESTARTS   AGE
jxing-nginx-ingress-controller-647f66fd5f-xglnj      1/1       Running   0          13m
jxing-nginx-ingress-default-backend-58688f7d-ht66m   1/1       Running   0          13m

Any ideas what could be going wrong?

**Comment by ccojocar** [comment]
This issue seems to be fixed. GKE cluster and nginx can be successfully installed.
