### ISSUE TITLE
expose does not seem to have the correct RBAC

### ISSUE THREAD

**Issue by ebalsumgo** [jenkins-x/jx#815]
I am trying to run jx install as follows:
`jx install --provider='kubernetes' --exposer='NodePort'` however the expose pods are failing with the following error `F0514 23:32:33.681440       1 exposecontroller.go:175] failed to create new strategy: failed to create node port expose strategy: failed to list nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope` seems the RBAC bits are not there for it to truly support NodePort?

**Comment by jstrachan** [comment]
BTW we're currently not supporting NodePort - see https://github.com/jenkins-x/jx/issues/682 for details - as its easier to use real URLs when working with apps across different environments

**Comment by ebalsumgo** [comment]
then what does --expose support / what is its function?

**Comment by jstrachan** [comment]
`Ingress / Route` are the main two implementations for kubernetes & openshift respectively

**Comment by jstrachan** [comment]
gonna mark this as fixed as we've no plans to support NodePort due to our reliance on ingress/routes
