### ISSUE TITLE
Install Questions

### ISSUE THREAD

**Issue by chrislovecnm** [jenkins-x/jx#8156]
Three questions:
1. Do we need a public ingress for hook?  I am thinking the answer is yes.  We are using GitLab.
2. Has anyone integrated oauth into the other UIs?  We would want google apps oauth.
3. Has anyone set the chart-museum, dashboard and previews to an internal ingress?

**Comment by babadofar** [comment]
Hi @chrislovecnm, did you get answers for your questions on slack? If so I think we should close this :)

**Comment by chrislovecnm** [comment]
Yes https://kubernetes.slack.com/archives/C9MBGQJRH/p1651345433275349
