### ISSUE TITLE
Implement cloud events webhook in lighthouse

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx#8180]
We need a generic way to accept incoming webhooks. This could be for some batch job that needs to start a pipeline at regular intervals, or as response to some event. My concrete need now is to allow  Pact broker to start a build pipeline that will [verify a contract](https://docs.pact.io/pact_broker/webhooks?utm_source=pact&utm_medium=client_library#the-contract-requiring-verification-published-event) 
Cloud events define a standard for [webhooks](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/http-webhook.md)
We should add support for this to [lighthouse](https://github.com/jenkins-x/lighthouse)
Would be added as another [SCM](https://github.com/jenkins-x/go-scm)

**Comment by msvticket** [comment]
If we where to implement support for a generic webhook it would rather be [CDEvents](https://cdevents.dev/)
