### ISSUE TITLE
Git error while promoting to environment

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#819]
jx promote -b --all-auto --timeout 1h --version v0.0.30

fatal: remote origin already exists.
No local changes to save
error: pathspec 'environment git url' did not match any file(s) known to git.

I get this error on every git promote.

Git Server is BitBucket
> jx                 1.2.60
> jenkins x platform 0.0.1008
> kubernetes cluster v1.9.3
> kubectl            v1.9.2
> helm client        v2.9.0+gf6025bb
> helm server        v2.9.0+gf6025bb
> git                git version 2.7.4

**Comment by jstrachan** [comment]
you get this error inside the pipelines right? whats the output of:
```
jx get env
```
I wonder? Never seen that error and not sure how to reproduce it

**Comment by jstrachan** [comment]
I wonder if its related to the contents of the environment git repository possibly; e.g. maybe there is not a file called `env/requirements.yaml` in your environment git repo (which should be referenced in the output of `jx get env`)

**Comment by jstrachan** [comment]
@ysaakpr any update on this?

**Comment by ysaakpr** [comment]
Looks like this issue never happened after  i upgraded to the latest release, We can close this.
