### ISSUE TITLE
Support showing messages on jx gitops upgrade

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#8214]
We currently have no way of informing users of potential issues with upgrades.

I'm suggesting that `jx gitops upgrade` would get support for showing such upgrade messages. From the same source we should also show these messages on the site.

**Comment by ankitm123** [comment]
May be the release notes should be descriptive enough so that the end user knows what is coming in 1.0.1 vs 1.0.0?
Also, testing on existing cluster will help solve many issues around upgrades imo. We only spin up a new cluster, which is not representative of real world upgrades.

**Comment by msvticket** [comment]
Which release notes?

**Comment by msvticket** [comment]
Oh, I fixed this myself in https://github.com/jenkins-x-plugins/jx-gitops/pull/933
