### ISSUE TITLE
Error when creating a dev pod in windows 7 with domain login username

### ISSUE THREAD

**Issue by liuhw99** [jenkins-x/jx#823]
I'm trying to create a dev pod in windows 7. I logged in as domain user CCNT\\liuhu and this error happens.
 
> $jx create devpod -l maven
> Creating a dev pod of label: maven
> error: Failed to create Namespace jx-edit-ccnt-liuhu Namespace "jx-edit-ccnt-liuhu" is invalid: metadata.labels: Invalid value: "CCNT\\liuhu": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

Seems like when creating the namespace for the dev pod,  the username with domain is to label the namespace (create_devpod.go) while the char '\\' is invalid in my case. 
```
        u, err := user.Current()
	if err != nil {
		return env, err
	}
	env, err = kube.EnsureEditEnvironmentSetup(kubeClient, jxClient, ns, u.Username)
```

**Comment by agentgonzo** [comment]
This probably affects more than just the above function. There are multiple calls to `user.Current()` throughout the codebase, all of which probably suffer the same issue.

**Comment by agentgonzo** [comment]
@jtnord - did you mention that something like this happened when you installed a cluster?

**Comment by jtnord** [comment]
My username had a capital in it so it tried to create a cluster with that.  @jstrachan or @rawlingsj said it just needs to be lower cased.  I guess the same here is sanitisation is needed.
The workaround for me was to not accept the default (which was my users full name JamesNord not my username) and to enter something lowercase.

**Comment by jtnord** [comment]
Fwiw that regexp looks wrong to me... Looks like it will pass the empty string.

**Comment by martijnburger** [comment]
Workaround is to specify the `--username myusername` parameter on `jx create devpod`. This leads however to another problem, because you cannot specify the username on `jx delete devpod`, see issue #2392
