### ISSUE TITLE
Issue with vault while setting up Jenkins X with k3s

### ISSUE THREAD

**Issue by rajatgupta24** [jenkins-x/jx#8257]
I tried the jx set up with k3s (internal vault) by following [this](https://jenkins-x.io/v3/admin/platforms/k3s/)

While running `jx admin operator --username $GIT_USERNAME --token $GIT_TOKEN --url <url of the cluster git repo>
` command, I got an error with internal vault
The logs from boot-job
```
JX_VAULT_ROLE=jx-vault JX_VAULT_MOUNT_POINT=kubernetes VAULT_ADDR=https://vault.jx-vault:8200 VAULT_NAMESPACE=jx-vault EXTERNAL_VAULT=false jx secret populate --secret-namespace jx-vault
waiting for vault pod vault-0 in namespace jx-vault to be ready...
pod vault-0 in namespace jx-vault is ready
verifying we have vault installed
about to run: /root/.jx/plugins/bin/vault-1.8.3 version
Vault v1.8.3 (73e85c3c21dfd1e835ded0053f08e3bd73a24ad6)
verifying we can connect to vault...
about to run: /root/.jx/plugins/bin/vault-1.8.3 kv list secret
No value found at secret/metadata
WARNING: could not connect to vault: failed to wait for vault to be available: failed to access vault. are you sure you are running the 'jx-secret vault portforward' command? command failed: /root/.jx/plugins/bin/vault-1.8.3 kv list secret: failed to run '/root/.jx/plugins/bin/vault-1.8.3 kv list secret' command in directory '', output: 'No value found at secret/metadata'
```

**kubernetes version** - v1.23.6+k3s1
**Jenkins X version** - 3.2.292
**vault-chart version** - 1.10.3

### Workaround
I downgraded the vault instance chart to version 1.8.4
I run this
```
helm install vault-instance jxgh/vault-instance -n jx-vault --version 1.0.25
```
instead of 
```
helm install vault-instance jxgh/vault-instance -n jx-vault
```

**Comment by ankitm123** [comment]
Would be good to create a custom image with vault 1.10, and see if that fixes it.

**Comment by ankitm123** [comment]
The error comes from: https://github.com/hashicorp/vault/blob/34214969c695371a402b1be5a42721237dd5c126/command/kv_list.go#L120

Seems like in newer version of vault, if no secrets exist, then `vault kv list secret` returns:
```
No value found at secret/metadata
```

Users installing jx will see this issue, but existing users of jx will be fine (as vault is already up).

A fix would be to not run this command, do something else when jx boot is waiting for internal vault to come up.
One command to run could be `vault status`.
