### ISSUE TITLE
`jx create cluster gke` fails when using bitbucket git provider 

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#826]
Cluster creation succeeds, and then fails here:

```
Created environment staging
Querying if the repo is a fork at https://bitbucket.org with kind bitbucket
Updated the Jenkins ConfigMap jenkins
Safe Restarted Jenkins server
error creating cluster Failed to create the wbrefvem folder in jenkins: 503 Service Unavailable
error: Failed to create the wbrefvem folder in jenkins: 503 Service Unavailable
```

**Comment by wbrefvem** [comment]
Incidentally @jstrachan this is blocking me from digging into #664

**Comment by jstrachan** [comment]
@wbrefvem sorry to hear that! 

I wonder if removing your `~/.jx/jenkinsAuth.yaml` helps? Then maybe removing anything in `~/.jx/gitAuth.yaml` you don't need

**Comment by jstrachan** [comment]
gonna try test bitbucket first thing tomorrow btw! (gotta run tonight...)

**Comment by wbrefvem** [comment]
@jstrachan I thought stale configs in `~/.jx` might be the culprit, so I blew away the whole thing and ran `jx create git server bitbucket http://bitbucket.org` before `jx create cluster gke` but still no joy.

I feel like this has gotta be a race condition where we're trying to create a pipeline before `svc/jenkins` is ready.

**Comment by jstrachan** [comment]
ah yeah - there's an issue with adding git servers; until we've `Configuration as Code` working and we can reload the Jenkins configuration on the fly - we have to bounce jenkins whenever we add a new git server. Though we could bake in github.com and bitbucket.org OOTB to avoid having to restart jenkins - but any other git provider that's not a SaaS we'll have to restart jenkins today
