### ISSUE TITLE
jx changelog create silently drops some types of commits from changelog

### ISSUE THREAD

**Issue by salomatu** [jenkins-x/jx#8277]
While in progress of adopting JX3 and Conventional Commits our team has noticed that:
* If a commit uses the form `feat!:` to denote a breaking change, it is silently dropped from the changelog.
* If a commit _is not_ formatted as conventional commit but contains a URL, it is silently dropped from the changelog.

Expected behavior:
* `feat!:` is included in the changelog _at least_ as a new feature.
* The non-conforming commit is included in the "Other" section.

Versions:
* jx: 3.2.388
* jx-changelog: 0.1.4

Maybe this generalizes to all unrecognized types of Conventional Commits being silently dropped, where the colon in the URL causes the parser to handle the message as such.

**Comment by msvticket** [comment]
This should be fixed in jx-changelog 0.3.0

/close
