### ISSUE TITLE
Upgrade Jenkins X repositories to go 1.18 [Starts July 18]

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#8283]
Golang supports only 2 major releases: https://endoflife.date/go
Go 1.19 is expected to be out in August 2022.
We should start the upgrade process to go 1.18, before go 1.17 becomes unsupported (expected in August 2022).

Follow this guide for information on how to upgrade: https://jenkins-x.io/community/maintainer_guide/go-upgrades/

Before upgrading , we need to upgrade the version of golang in the catalog repository: 
example (there are other files as well): https://github.com/jenkins-x/jx3-pipeline-catalog/blob/0f0f956d38ffe383ba38d93c1cfe7160a3bec93a/tasks/go/pullrequest.yaml#L37

This is the tentative list of repositories (list will be updated if we find any missing repositories) that we should upgrade:

- [x] ~[jx-kubeclient](https://github.com/jenkins-x/jx-kube-client) - no other jx dependencies~
- [x] [go-scm](https://github.com/jenkins-x/go-scm) - no other jx dependencies
- [x] [logrus-stackdriver-formatter](https://github.com/jenkins-x/logrus-stackdriver-formatter) - no jx dependencies
- [x] [lighthouse](https://github.com/jenkins-x/lighthouse)
  - go-scm
- [x] [jx-logging](https://github.com/jenkins-x/jx-logging):
  - logrus-stackdriver-formatter
- [x] [ secretfacade](https://github.com/jenkins-x-plugins/secretfacade)
  - jx-logging
- [x] [jx-api](https://github.com/jenkins-x/jx-api)
  - jx-logging
- [x] [jx-helpers](https://github.com/jenkins-x/jx-helpers)
  - github.com/jenkins-x/go-scm
  - github.com/jenkins-x/jx-api
  - github.com/jenkins-x/jx-kube-client
  - github.com/jenkins-x/jx-logging
- [x] [jx](https://github.com/jenkins-x/jx/)
  - jx-api
  - jx-helpers
  - jx-kube-client
  - jx-logging
- [x] [jx-git-operator](https://github.com/jenkins-x/jx-git-operator)
- [x] [bdd-jx3](https://github.com/jenkins-x/bdd-jx3)
- [x] [jx-gitops](https://github.com/jenkins-x-plugins/jx-gitops)
- [x] [jx-changelog](https://github.com/jenkins-x-plugins/jx-changelog)
- [x] [jx-secret](https://github.com/jenkins-x-plugins/jx-secret)
- [x] [jx-admin](https://github.com/jenkins-x-plugins/jx-admin)
- [x] [jx-preview](https://github.com/jenkins-x-plugins/jx-preview)
- [x] [jx-promote](https://github.com/jenkins-x-plugins/jx-promote)
- [x] [jx-pipeline](https://github.com/jenkins-x-plugins/jx-pipeline)
- [x] [jx-updatebot](https://github.com/jenkins-x-plugins/jx-updatebot)
- [x] [jx-scm](https://github.com/jenkins-x-plugins/jx-scm)
- [x] [jx-registry](https://github.com/jenkins-x-plugins/jx-registry)
- [x] [ jx-slack](https://github.com/jenkins-x-plugins/jx-slack)
- [x] [jx-release-version](https://github.com/jenkins-x-plugins/jx-release-version)
- [x] [jx-verify](https://github.com/jenkins-x-plugins/jx-verify)
- [x] [jx-application](https://github.com/jenkins-x-plugins/jx-application)
- [x] [jx-build-controller](https://github.com/jenkins-x-plugins/jx-build-controller)
- [x] [jx-test](https://github.com/jenkins-x-plugins/jx-test)

In the list, there are some packages which need multiple packages updated before we update them, for example: before upgrading jx-api we should upgrade jx-logging.

**NOTE: it's fine if you dont follow the order, the order is only there to limit the number of PRs we open as part of an upgrade effort**

We will this issue to keep track of which repositories have been upgraded.
If you are interested in contributing, please comment
```
I want to upgrade <repo-name>
```

When opening a PR in these repos to upgrade the go version, remember to include
```
related to #<issue-number>
```
Dont use `fixes` as that will close this issue once ur PR is merged.
Once your PR is merged, comment in this issue:
```
<reponame> has been upgraded to 1.18
```

If you encounter any issues when upgrading, please make a note of that issue and how you fixed in this PR, so that is helps other contributors. Remember to comment back the issue and fix in this PR, so others can see it.

There are a few repositories that need to be upgraded to 1.17, before we start working on this issue. Those are being tracked here: #8279 

We will start working on this issue from **July 18**.

**Comment by sshiv5768** [comment]
@ankitm123 I want to upgrade lighthouse or jx.

**Comment by sshiv5768** [comment]
When to start working on this?

**Comment by ankitm123** [comment]
> When to start working on this?

July 18, I need to update the order in which we can upgrade, and get few repos upgraded to 1.17 before that.

**Comment by rajatgupta24** [comment]
Hello @ankitm123, I want to upgrade the `go-scm`.

**Comment by sshiv5768** [comment]
Which are the files needs to be changed in ```lighthouse```?

**Comment by ankitm123** [comment]
I will update the jx documentation (with files and steps) and link it to this issue.
it's going to be go.mod file.

**Comment by Aju100** [comment]
Hi @rajatgupta24 I want to upgrade jx-admin

**Comment by ankitm123** [comment]
https://jenkins-x.io/community/maintainer_guide/go-upgrades/ -> This has some information around upgrading, I will update the go version in the catalog file: https://github.com/jenkins-x/jx3-pipeline-catalog/blob/0a52092fffa636bd7e6da1dbcb0aef38d2b314b9/tasks/go/pullrequest.yaml#L37 (This is one of the files)

**Comment by sshiv5768** [comment]
@ankitm123 I have created an issue(#8307) in `jx` repo. Is it good to go for upgrading process?

**Comment by joker00777** [comment]
HI @ankitm123 I want to upgrade jx-gitops.

**Comment by ankitm123** [comment]
> Is it good to go for upgrading process?

@sshiv5768 Yes, please go ahead.

**Comment by ankitm123** [comment]
I have updated the page with the order: https://jenkins-x.io/community/maintainer_guide/go-upgrades/. Hopefully this helps and let me know if anything is missing!

**Comment by ankitm123** [comment]
I want to upgrade `go-scm`, `jx-kubeclient` and `logrus-stackdriver-formatter`.

**Comment by sshiv5768** [comment]
@ankitm123 I am going to work with ``lighthouse`` one. I have to change that files only where commit ``refactor: upgrade to go-scm-1.11.18`` is there?

**Comment by sshiv5768** [comment]
refactor: update go version to 1.18.4 jenkins-x/lighthouse#1469

**Comment by sshiv5768** [comment]
refactor: update go version to 1.18.4  jenkins-x/lighthouse#1469

**Comment by sshiv5768** [comment]
hey, @ankitm123 I made a PR which i mentioned above. please check it.

**Comment by sshiv5768** [comment]
Hey, @ankitm123. I just made an PR ``jenkins-x-plugins/secretfacade`` check it. 
PR: jenkins-x-plugins/secretfacade#16

**Comment by rajatgupta24** [comment]
I want to upgrade **logrus stackdriver formatter**

**Comment by rajatgupta24** [comment]
I want to upgrade `jx-api`.

**Comment by rajatgupta24** [comment]
I want to upgrade `jx-git-operator`.

**Comment by rajatgupta24** [comment]
Keep in mind to upgrade the `k8s.io` version to `v0.22.15`.

**Comment by ankitm123** [comment]
I want to upgrade jx-build-controller.

**Comment by aahmed7** [comment]
Hi @ankitm123, I want to upgrade jx-verify

**Comment by ankitm123** [comment]
I want to update jx-updatebot

**Comment by ankitm123** [comment]
I want to update jx-slack

**Comment by ankitm123** [comment]
I want to update jx-test

**Comment by ankitm123** [comment]
This is complete, thanks everyone!
