### ISSUE TITLE
jx version shows commit sha which is not in main branch

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#8295]
```
(base) ➜  ~ jx version
version: 3.3.0
shaCommit: 7e8722c04c1d6f85173631ac671d76178736d507
buildDate: Fri Jul  8 16:24:34 UTC 2022
goVersion: 1.17.9
branch: main
gitTreeState: clean
```

commit sha `7e8722c04c1d6f85173631ac671d76178736d507` is not in the main branch.
![image](https://user-images.githubusercontent.com/6242296/178108289-b9d5b40b-c528-4409-8990-f12a7cb4689b.png)

it is created in the pipeline. So, it's incorrect that the branch says main. 
It should be fixed to show a commit in the main branch.

**Comment by ankitm123** [comment]
@osamamagdy

**Comment by osamamagdy** [comment]
Isn't the pipeline running the make build command which will get the correct sha commit?

**Comment by ankitm123** [comment]
The release pipeline uses GitHub actions (we will migrate off GitHub to pure jx soon) which uses goreleaser to build and upload the binary

**Comment by osamamagdy** [comment]
So in `.goreleaser.yaml`, modify `version.Rev` to be  `REV := $(shell git rev-parse --short HEAD 2> /dev/null || echo 'unknown')`

**Comment by osamamagdy** [comment]
This should get the commit sha of the main branch always

**Comment by osamamagdy** [comment]
It can be changed in this line
https://github.com/jenkins-x/jx/blob/366fb476158989cf1f12d9cbe6f722bca635cda6/.github/workflows/jenkins-x/upload-binaries.sh#L15
