### ISSUE TITLE
Kubernetes 1.22 related: jxboot-helmfile-resources has `networking.k8s.io/v1beta1` reference

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#8300]
I'm running the *jx* `3.3.2` and I noticed this message in my GKE console today (see Screenshot).
![image](https://user-images.githubusercontent.com/138324/178623202-c26e9e91-7edd-48a5-8528-9c86307411d4.png)

I rebuilt my cluster on the 9th and the issue has not happened again, so it's definitely `jx-boot` related... specifically `jxboot-helmfile-resources`.

I did a search for `networking.k8s.io/v1beta1` in my cluster repo and I noticed the following line in *config-root/namespaces/jx/jxboot-helmfile-resources/kapp-config-cm.yaml*. (source appears to be [jenkins-x-charts/jxboot-helmfile-resources](https://github.com/jenkins-x-charts/jxboot-helmfile-resources/blob/3f1ad0d334b03942ef90d928bc44b20174b043a5/charts/jxboot-helmfile-resources/templates/kapp-config.yaml))

```yaml
- apiVersionKindMatcher: {kind: Ingress, apiVersion: [networking.k8s.io/v1beta1](http://networking.k8s.io/v1beta1)}
```

**Comment by msvticket** [comment]
Fixed
