### ISSUE TITLE
creating ci/cd in jenkins for my python code failed with github credentials

### ISSUE THREAD

**Issue by upendraskillup** [jenkins-x/jx#8310]
Started by user [veera](http://sko-dev-ironwood.westus2.cloudapp.azure.com:8080/user/veera)
Running as SYSTEM
Building remotely on [QA-server](http://sko-dev-ironwood.westus2.cloudapp.azure.com:8080/computer/QA-server) (qaserver) in workspace /home/edx-root/jenkins/workspace/QA
The recommended git tool is: NONE
using credential 2109749a-af60-43dd-8d4d-3f8b60a01743
 > git rev-parse --resolve-git-dir /home/edx-root/jenkins/workspace/QA/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/SkillUpTech/Openedx-theme-ironwood.git # timeout=10
Fetching upstream changes from https://github.com/SkillUpTech/Openedx-theme-ironwood.git
 > git --version # timeout=10
 > git --version # 'git version 2.32.0'
using GIT_ASKPASS to set credentials jenkins-skillup pat token
 > git fetch --tags --force --progress -- https://github.com/SkillUpTech/Openedx-theme-ironwood.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/skilluponline^{commit} # timeout=10
Checking out Revision ccacf4de6d339cf07c066b86d188f8707d3f7907 (origin/skilluponline)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ccacf4de6d339cf07c066b86d188f8707d3f7907 # timeout=10
Commit message: "Microsoft Category Page US"
 > git rev-list --no-walk ccacf4de6d339cf07c066b86d188f8707d3f7907 # timeout=10
[QA] $ /bin/sh -xe /tmp/jenkins5919074991089816670.sh
+ sudo su -s /bin/bash edxapp
+ cd
+ cd /edx/app/edxapp/themes/Openedx-theme
+ git pull
fatal: could not read Username for 'https://github.com/': No such device or address
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by ankitm123** [comment]
Not related to Jenkins x, Jenkins is a separate project.
/close
