### ISSUE TITLE
add a jx command to recreate ingress rules and optionally ingress controller

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#835]
if a cloud LB is deleted and no static IP is reserved it would be useful to 

- recreate the ingress controller
- get the new external IP
- update the exposecontroller configmap
- recreate ALL ingress rules in

**Comment by kzantow** [comment]
Sorry if this is perhaps not the right spot for this comment, but perhaps there should, instead, be a command to just "fix" an environment? some sort of diff vs what it should be, which would include this stuff as part of it?

**Comment by ccojocar** [comment]
@rawlingsj I am closing this since now there is `jx upgrade ingress` command.
