### ISSUE TITLE
non-release builds use outdated jx version

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#836]
Releases get an updated version, but `jx` binaries produced by `make [install | build]` use the hard-coded `1.01`. This only becomes an issue in a few corner cases, like in a preview builder image when a pipeline has a `jx step validate` step that specifies a higher version.

One fix would be to always update `pkg/version/VERSION` to match the most recent release version tag.

**Comment by jstrachan** [comment]
one problem with that is doing a release would then commit code to master, which would create a release which then would.... ;)

But yeah, it'd be nice to make local builds of `jx` return a large jx version

**Comment by wbrefvem** [comment]
Yeah that's a good point. A better idea would be to query the GH API for the latest tag, or maybe try some `git describe` jiggery-pokery first and then fall back to the API.

**Comment by jstrachan** [comment]
yeah - or we could maybe just hard code the development version to something big - like `1.100-snapshot` or something

**Comment by ccojocar** [comment]
The version number is now updated to something like `1.3.683-dev+dbf8177c`, also for local jx builds.
