### ISSUE TITLE
Lighthouse hook fails to merge the PR

### ISSUE THREAD

**Issue by spaily** [jenkins-x/jx#8372]
Hi,
My On-Premises cluster is deployed in the local network which is not accessible from outside, so I've enabled the webhook by following https://jenkins-x.io/v3/admin/platforms/on-premises/webhooks/. The webhook is accessible from outside now. I'm using public github repository. 

I'm using `jx project quickstart` to create a demo golang-http project, PR is getting created successfully but did not merge automatically. When I looked at the lighthouse URL is pointing to `http://lighthouse-jx.192.168.1.80.nip.io/merge/status` which is local and continue to be on pending state `Lighthouse Merge Status Pending — Not mergeable. Needs approved label.`. 
I think that this is the reason why is not merging. Any idea, why is the lighthouse URL on the github pointing to the local/internal URL even though the webhook is exposed via ngrok?

**Comment by ankitm123** [comment]
Any logs in the lighthouse webhook and lighthouse keeper pods (in the jx namespace)? Also do you have some branch protection rules in github?
