### ISSUE TITLE
jx on kubernetes failed to install

### ISSUE THREAD

**Issue by mmshaikh88** [jenkins-x/jx#839]
I tried to install through jx and using kubernetes, I see following errors:

I donot have RBAC enabled and do not want to enable RBAC either.

```
? Missing required dependencies, deselect to avoid auto installing: helm
Downloading https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz to /root/.jx/bin/helm.tgz...
Downloaded /root/.jx/bin/helm.tgz
Did not set exposeController Config Domain
Trying to create ClusterRoleBinding kubernetes-admin-cluster-admin-binding for role: cluster-admin for user kubernetes-admin
Created ClusterRoleBinding kubernetes-admin-cluster-admin-binding
Created ServiceAccount tiller in namespace kube-system
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
Created ClusterRoleBinding tiller
Initialising helm using ServiceAccount tiller in namespace kube-system
Error: Command failed  helm init --service-account tiller --tiller-namespace kube-system
retrying after error:exec: "helm": executable file not found in $PATH
Initialising helm using ServiceAccount tiller in namespace kube-system
Error: Command failed  helm init --service-account tiller --tiller-namespace kube-system
retrying after error:exec: "helm": executable file not found in $PATH
Initialising helm using ServiceAccount tiller in namespace kube-system
Error: Command failed  helm init --service-account tiller --tiller-namespace kube-system
helm init failed: after 3 attempts, last error: exec: "helm": executable file not found in $PATH
error: after 3 attempts, last error: exec: "helm": executable file not found in $PATH
```

**Comment by mmshaikh88** [comment]
I have move the helm under /usr/local/bin/ to put it in the path, but now install stuck on 

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace

I don't have external loadbalancer, I will use nodeport to expose the web. But the jx installer do not move any further.

**Comment by mmshaikh88** [comment]
Can run uninstall either it fails:

root@kube1:~# jx uninstall
? Are you sure you wish to remove the Jenkins X platform from the 'jx' namespace on cluster 'https://192.168.7.4:6443'? : Yes
Error: Command failed  helm delete --purge jenkins-x
error: exit status 1
root@kube1:~#

**Comment by jstrachan** [comment]
@mmshaikh88 btw we don't support NodePort yet since we need to expose any web app / tool in any namespace easily via URLs in Jenkins X. See https://github.com/jenkins-x/jx/issues/682

Currently we require RBAC support too - which is a default in k8s from 1.9 anyways & is good practice when you want a team of users to share a cluster.

**Comment by ccojocar** [comment]
@jstrachan I think this issue can be closed.
