### ISSUE TITLE
error creating cluster exec: "minikube": executable file not found in $PATH

### ISSUE THREAD

**Issue by linbiqiu** [jenkins-x/jx#840]
``
![tim 20180518151705](https://user-images.githubusercontent.com/7385948/40221745-de6fb3f0-5aaf-11e8-82cb-c40a7fd01152.jpg)

**Comment by allsuper** [comment]
I assume the error is due to the fact, that you did not include the binaries in the folder  ~/.jx/bin in your path. You have to do  
```export PATH=$PATH:~/.jx/bin```
and run it again.

**Comment by McDingl** [comment]
it can not work ,output the same as yours

**Comment by ccojocar** [comment]
This seems to be a `minikube` issue not `jx`.
