### ISSUE TITLE
env option to jx pipeline start is ignored

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/jx#8419]
I created a pipeline where a step could use an environment variable. After triggering the pipeline I looking at the pod and the supplied environment variable was not supplied.

Looking at the source code I don't see that the option field CustomEnvs is used.

The `jx pipeline` command is built from the repository https://github.com/jenkins-x-plugins/jx-pipeline/

**Comment by PratikforCoding** [comment]
Hey @msvticket I wanna try this out. Can you provide some resources to learn and resolve this issue and some tips?

**Comment by msvticket** [comment]
Basically the environment parameter is received [here](https://github.com/jenkins-x-plugins/jx-pipeline/blob/58d9752f204515fef56f67d748c72bfcf436f1f1/pkg/cmd/start/start.go#L149) 

Then they should be added in the StepTemplates:

pr.Spec.PipelineSpec.Tasks[].TaskSpec.StepTemplate.Env
