### ISSUE TITLE
Biggest network problem for me, because of the GFW

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#843]
As the title, if the process of jx install can pull images from a register, that will be very good. And more Chinese people can learn and use JenkinsX.

**Comment by jstrachan** [comment]
is this because you cannot see docker hub? Is there another public docker registry we could mirror our images into?

**Comment by LinuxSuRen** [comment]
Some of the images are host in google. Because of the GFW, a lot of people can't visit it. But I already mirror most of the images that jx needs into aliyun.com. So if we can config these, that will be great.

**Comment by jstrachan** [comment]
I wonder if there's a way to configure docker daemons to always look at mirror sites like `aliyun.com` when looking for docker images?

**Comment by LinuxSuRen** [comment]
I don't know about that. Or we can add a prefix with image, when pulling a image. I don’t know witch way is better.

**Comment by LinuxSuRen** [comment]
Maybe we can set the images in charts as a var, when perform the install action, we can override.

**Comment by jstrachan** [comment]
docs on docker registry mirroring: https://docs.docker.com/registry/recipes/mirror/ here's an example:  https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring

**Comment by ccojocar** [comment]
Closing this since does not seems to be an issue in `jx`.

**Comment by datangliang** [comment]
@ccojocar I don't think so. Jenkins X use http://chartmuseum.jenkins-x.io  as chart repo. It was hosted on google's servers. The servers may be blocked by GFW.  Can you offer github hosted charts for me ? Thank you very much.

**Comment by wuyongdec** [comment]
gcr.io image pull problem in China ,please refer this:
https://ieevee.com/tech/2019/03/02/azure-gcr-proxy.html
