### ISSUE TITLE
Lighthouse jobs that have run_if_changed cannot be triggered manually

### ISSUE THREAD

**Issue by salomatu** [jenkins-x/jx#8477]
Hi, (likely) after a recent change in Lighthouse (https://github.com/jenkins-x/lighthouse/pull/1463), it is no longer possible to trigger a job manually via chat command if the job has a `run_if_changed` condition defined but the pattern is not present. Instead the job is skipped.

The expected behavior, I believe, would be that missing the match for `run_if_changed` did not _inhibit_ triggering the job via chat command. I believe the current behavior blocks a valid use-case and that this change in behavior was not intentional.

Versions affected:
* Lighthouse starting from v1.9.4 and onwards.

Additionally while investigating the issue, I came across with some peculiar error messages. It seems Lighthouse it attempting to update a status of "skipped" in the Github PR, but fails due to "Unprocessable Entity" at some point of the process. These are likely unrelated to the main issue, but I will mention these solely for the record.

**Comment by msvticket** [comment]
I'm pretty sure this was fixed with jenkins-x/lighthouse#1465.

**Comment by msvticket** [comment]
Nope, it was not fixed...
