### ISSUE TITLE
How to Update my GitHub Token in jenkins X

### ISSUE THREAD

**Issue by FranLucchini** [jenkins-x/jx#8483]
Hello,

My GitHub token expired recently, and our pipelines stopped working. I wanted to ask what steps I should follow to update the GitHub Bot's token. So far, we have re-applied the Terraform plan with the new token, but it didn't solve the issue. 

I checked issue #6613, and the recommendation is to delete Jx pods, so they pull the new token manually. Is that what we need to do?

**Comment by msvticket** [comment]
#6613 is old and concerns Jenkins X 2. I guess you are using Jenkins X 3. Since you initially set the bot token using terraform that would be the natural method of setting a new value. Did you try that?
