### ISSUE TITLE
How can I login into docker register created by Jenkins X

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#849]
When I use cmd `docker login docker-registry.jx.192.168.99.100.nip.io`
UserName is 'admin', the password is 'doomprong'
But get the error:
`
Error response from daemon: Get https://docker-registry.jx.192.168.99.100.nip.io/v2/: x509: certificate is valid for ingress.local, not docker-registry.jx.192.168.99.100.nip.io
`

**Comment by LinuxSuRen** [comment]
@jstrachan Thanks! I actually want to fix the problem what describe in #850

**Comment by luoyan35714** [comment]
@LinuxSuRen Hi, Have you resolved this problem?

**Comment by LinuxSuRen** [comment]
I just change 'https' to 'http'

**Comment by mcedica** [comment]
I tried to use the devPod but I get the same error from the devPod

**Comment by retr0h** [comment]
> OOTH we tend to use the docker registry purely locally within the cluster via a kubernetes Service only. You could try use a [DevPod](https://jenkins-x.io/developing/devpods/) to work with the docker daemon and the docker registry from inside a pod inside k8s to avoid the https/cert issue?

@jstrachan if that is the case then that assumes the docker daemon must always be setup for insecure registries, since skaffold cannot push to the https resource which is running http[1]. 

[1] https://github.com/GoogleContainerTools/skaffold/issues/1732
