### ISSUE TITLE
Is there one way to install jx in one k8s cluster?

### ISSUE THREAD

**Issue by liuxiaopiao** [jenkins-x/jx#851]
We have setup up one k8s cluster based on our own cloud environment and want to try the jx on this cluster. From https://jenkins-x.io/getting-started/install-on-cluster/ we can't find the provider for our cloud vendor and is there one way to install jx in the current k8s cluster manually without running "jx install"?

**Comment by jstrachan** [comment]
what cloud provider are you using?  If you can connect to your kubernetes cluster via `kubectl` then installing with `jx install --provider kubernetes` should do the trick.

Let us know if this doesn't work and we can reopen this issue and try diagnose what issues your cloud provider are causing
