### ISSUE TITLE
How to specify port for gitServer

### ISSUE THREAD

**Issue by ruschecker** [jenkins-x/jx#8512]
In jx-requirenments.yaml
there is a field  gitServer put it is not allowed to specify port there.
If you specify it there it returns error that column is not allowed there, but if I am not specifying it there it can't pull because i am using not standard port for http git. I am using gitea.
Any ideas how to fix it?

**Comment by ruschecker** [comment]
seems quotas around value helps, but it is not obvious in doc. Found sample here https://github.com/jenkins-x/jx/issues/7679

**Comment by msvticket** [comment]
Well, that quotes are needed is standard yaml and I think it's quite clear that file should be in yaml format
