### ISSUE TITLE
What is the release cycle of dependancy modules

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#852]
Hey, I am started using JX in my org...and its really wonderful.  But i found that jx tool is getting updated every day or very frequently..but the modules which depends on it is not getting updated that fast..For example...jenkins-x/builder-base is updated but not the language specific images, which are still on different versions..
What is the release cycle that jenkins-x platform following...Can we ensure that one new release is also creating new releases for other modules as well.

**Comment by jstrachan** [comment]
we found we were doing zillions of releases of all the builder images; so we tried to throttle it down a little so its daily releases. It looks like we just released about 3 hours ago all the builder-* images. 

I'll keep an eye on it over the next few days but I think this is working - its just there's up to 24 hours before the `builder-*` images come out after a `jx` release
