### ISSUE TITLE
After terraform -upgrade tekton pipeline are failing

### ISSUE THREAD

**Issue by valiksb** [jenkins-x/jx#8525]
I performed a terraform init -upgrade, then a terraform plan. At that moment I was informed that 3 resources would be deleted (assuming that was correct I continued), these are the resources that I got a warning after terraform apply

module.jx.module.cluster.google_compute_firewall.gke_master_allow_nginx_tekton_webhook[0]: Destruction complete after 12s
module.jx.module.cluster.google_compute_firewall.gke_master_allow_istio_webhook[0]: Destruction complete after 12s
module.jx.module.cluster.google_compute_firewall.gke_master_allow_certmanager_webhook[0]: Destruction complete after 12s

In lighthouse-keeper I get the following error every 30 seconds

{
  "insertId": "a6y6z5cyqglssc1n",
  "jsonPayload": {
    "message": "Error rerunning PipelineRuns failed by Tekton race condition: listing PipelineRuns in jx: conversion webhook for tekton.dev/v1beta1, Kind=PipelineRun failed: Post \"[https://tekton-pipelines-webhook.tekton-pipelines.svc:443/resource-conversion?timeout=30s](https://tekton-pipelines-webhook.tekton-pipelines.svc/resource-conversion?timeout=30s)\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)",
...
}

Some additional details can be found in here https://kubernetes.slack.com/archives/C9MBGQJRH/p1677857630789679

I would really appreciate any help as currently NONE of the pipelines are working

**Comment by msvticket** [comment]
The issue does not contain much detail but it seem like the problem was resolved in slack
