### ISSUE TITLE
Not listing all the organisation while using bitbucket

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#858]
While creating environment using git create env, even though its creating a env properly, the bitbucket organisation is not getting selected

About to create repository environment-jx-beta1 on server https://bitbucket.org with user vyshakhp
? Which organisation do you want to use?  [Use arrows to move, type to filter]
❯ vyshakhp

Is this is bug or any special permission issue ??

**Comment by elad-lachmi** [comment]
The issue might be that the `role` query string parameter to the `teams` endpoint is required, which is undocumented.

Currently the call to `TeamsApi.TeamsGet` passes `nil` as the second parameter and the `go-bitbucket` package doesn't provide a default, so the REST call to the Bitbucket API fails.

**Comment by elad-lachmi** [comment]
I confirmed this.
When passing in `map[string]interface{}{"role": "member"}` as the second parameter to `TeamsGet`, it works as expected.
I could just PR this, since I think it's the most relevant option of the three, but maybe this should be tied into the adding git server of kind BitBucket flow.

I'm new here, so would be happy for some guidance.

**Comment by ysaakpr** [comment]
jx import is broken from version 1.2.119 where this specific fix have done

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x16f859a]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).Run(0xc420105600, 0xc420453c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:218 +0x88a
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdImport.func1(0xc42046a280, 0xc42004b620, 0x0, 0x6)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:138 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc42046a280, 0xc42004b5c0, 0x6, 0x6, 0xc42046a280, 0xc42004b5c0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420083400, 0xc420406280, 0xc420464000, 0xc42040c500)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420083400, 0xc42017a9e0, 0x2898a40)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc420037f70, 0x1791d59)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
