### ISSUE TITLE
issue?

### ISSUE THREAD

**Issue by abhilash1786** [jenkins-x/jx#8581]
error: failed to run command /root/.jx3/plugins/bin/helm-3.6.2 upgrade --install --namespace jx-git-operator --create-namespace jxgo jxgh/jx-git-operator: failed to run '/root/.jx3/plugins/bin/helm-3.6.2 upgrade --install --namespace jx-git-operator --create-namespace jxgo jxgh/jx-git-operator' command in directory '', output: 'Release "jxgo" does not exist. Installing it now.

**Comment by msvticket** [comment]
Closing since there is no context whatsoever regarding what is attempted
