### ISSUE TITLE
The pipeline is getting failed and not able to identify where exactly it is getting failed 

### ISSUE THREAD

**Issue by nandan-dm** [jenkins-x/jx#8595]
Hi The jx pipeline most of the time keeps on failing and I am not able to see the logs of the pod because it gets terminated once the pod execution is done

<div class="logs-options" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; display: flex; flex-direction: row-reverse; background-color: var(--color-background); border-bottom: 1px solid var(--color-background-darker); padding: 5px; caret-color: rgb(102, 102, 102); color: rgb(102, 102, 102); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 14px;"><div class="raw-logs-options" style="box-sizing: border-box; margin: auto 5px;"><button class="option-button" id="toggle-steps" style="box-sizing: border-box; font-family: inherit; font-size: inherit; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: 16px; margin: 0px; overflow: visible; text-transform: none; appearance: button; touch-action: manipulation; border-radius: 0px; border: 1px solid var(--main-color); color: var(--main-color); padding: 8px; cursor: pointer; background-color: var(--color-background);">Toggle Steps</button><span class="Apple-converted-space"> </span><a class="option-button" href="https://dashboard-jx.m.tonline.aws.target.com.au/ns-jx/targetau/tonline-shop/PR-936/1/logs" target="_blank" style="box-sizing: border-box; background-color: var(--color-background); touch-action: manipulation; border: 1px solid var(--main-color); color: var(--main-color); padding: 8px; cursor: pointer; line-height: 16px; text-decoration: none;">View raw logs</a><span class="Apple-converted-space"> </span><a class="option-button" id="downloadLogs" download="targetau-tonline-shop-PR-936-1.txt" href="blob:https://dashboard-jx.m.tonline.aws.target.com.au/9fb53eeb-b506-42ab-b797-0cf3afb08edd" style="box-sizing: border-box; background-color: var(--color-background); touch-action: manipulation; border: 1px solid var(--main-color); color: var(--main-color); padding: 8px; cursor: pointer; line-height: 16px; text-decoration: none;">Download raw logs</a></div></div>

  |   |   |   | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container place-tools
-- | -- | -- | -- | --
  |   |   |   | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-init
  |   |   |   | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container place-scripts
  |   |   |   | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container working-dir-initializer
  |   |   | 3s | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-git-clone
  |   |   | 2s | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-git-merge
  |   |   | 4s | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-jx-variables
  |   |   | 1m29s | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-yarn-install
  |   |   | 3m9s | Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-typecheck-test-lint
  |   |   |   | unable to retrieve container logs for containerd://56c3b24fc2a353718e08a4c91860f214ebc84fb6251d5e91705a59e48d2c7222
  |   |   |   |  
  |   |   |   | Pipeline failed on stage 'test-and-lint' : container 'step-typecheck-test-lint'. The execution of the pipeline has stopped.

Toggle Steps [View raw logs](https://dashboard-jx.m.tonline.aws.target.com.au/ns-jx/targetau/tonline-shop/PR-936/1/logs) [Download raw logs](blob:https://dashboard-jx.m.tonline.aws.target.com.au/9fb53eeb-b506-42ab-b797-0cf3afb08edd)
Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container place-tools
Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-init
Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container place-scripts
Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container working-dir-initializer
3s	Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-git-clone
2s	Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-git-merge
4s	Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-jx-variables
1m29s	Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-yarn-install
3m9s	Showing logs for build targetau/tonline-shop/pr-936 #1 stage test-and-lint and container step-typecheck-test-lint
unable to retrieve container logs for containerd://56c3b24fc2a353718e08a4c91860f214ebc84fb6251d5e91705a59e48d2c7222
 Pipeline failed on stage 'test-and-lint' : container 'step-typecheck-test-lint'. The execution of the pipeline has stopped.

<img width="1728" alt="image" src="https://github.com/jenkins-x/jx/assets/129483254/d55b4b9c-9a34-406c-a439-918e0e9daa5d">

**Comment by msvticket** [comment]
If the pod fails and it or its logs disappear from Kubernetes before the logs have been persisted this is what you see. So you need to find out wha happened to the pod. Maybe you have prometheus mertrics you can look at.
