### ISSUE TITLE
jx install failures with: Did not set exposeController Config Domain

### ISSUE THREAD

**Issue by mmshaikh88** [jenkins-x/jx#860]
Failed to install with error:

```
# jx install
? Cloud Provider kubernetes
Did not set exposeController Config Domain
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
ingress init failed: deployments.extensions "jxing-nginx-ingress-controller" not found
error: deployments.extensions "jxing-nginx-ingress-controller" not found
#
```

**Comment by jstrachan** [comment]
Does `jx install -v` give more information?

Looks like probable RBAC problems. Your user probably can’t update the `kube-system` namespace. What kind of cluster is it? You could try use a different Ingress namespace. 

    jx install  --ingress-namespace myingress

See https://jenkins-x.io/commands/jx_install/

**Comment by jstrachan** [comment]
I've a PR to enable verbose output on all helm commands btw coming shortly.

maybe try 
```
kubectl create ns jenkinsingress
jx install --ingress-namespace jenkinsingress 
```
if the `kubectl` commands fails then  I guess you've not got karma to create namespaces. Is this a vanilla upstream kubernetes cluster right? How did you create the cluster? Is RBAC enabled?

**Comment by mmshaikh88** [comment]
Still see the same error:

```
[root@ifrs-master-1]# kubectl create ns jenkinsingress
namespace "jenkinsingress" created
[root@ifrs-master-1]# jx install  --ingress-namespace jenkinsingress
? Cloud Provider kubernetes
Did not set exposeController Config Domain
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the jenkinsingress namespace, shall we install one? Yes
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
ingress init failed: deployments.extensions "jxing-nginx-ingress-controller" not found
error: deployments.extensions "jxing-nginx-ingress-controller" not found

```

**Comment by jstrachan** [comment]
the new build is up `1.2.71` - wanna try `jx install  --ingress-namespace jenkinsingress` again - it should hopefully give a more meaningful error now. I'm assuming its RBAC related.

You can upgrade your `jx` binary via

   jx upgrade cli
   jx install  --ingress-namespace jenkinsingress

**Comment by mmshaikh88** [comment]
jx upgrade cli is failed with the error 

```
[root@ifrs-master-1]# jx upgrade cli
Downloading https://github.com/jenkins-x/jx/releases/download/v1.2.73/jx-linux-amd64.tar.gz to /root/.jx/bin/jx.tgz...

error: Unable to download file /root/.jx/bin/jx.tgz from https://github.com/jenkins-x/jx/releases/download/v1.2.73/jx-linux-amd64.tar.gz due to: unexpected EOF
[root@ifrs-master-1]#

```

**Comment by mmshaikh88** [comment]
I have manually downloaded 1.2.71 version of jx instead of 1.2.73 through jx upgrade command through wget  https://github.com/jenkins-x/jx/releases/download/v1.2.71/jx-linux-amd64.tar.gz

**Comment by mmshaikh88** [comment]
I see following error message after I ran the command to install for jenkinsingress.

```
# jx install  --ingress-namespace jenkinsingress
? Cloud Provider kubernetes
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the jenkinsingress namespace, shall we install one? Yes

E0523 01:33:08.591793    6385 portforward.go:331] an error occurred forwarding 36341 -> 44134: error forwarding port 44134 to pod 5d366a612b418053b3e2d0d85c723e3177c03867a234fc5ad5bcdba38d6ad016, uid : unable to do port forwarding: socat not found.
Error: transport is closing
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
E0523 01:33:11.207802    6415 portforward.go:331] an error occurred forwarding 44623 -> 44134: error forwarding port 44134 to pod 5d366a612b418053b3e2d0d85c723e3177c03867a234fc5ad5bcdba38d6ad016, uid : unable to do port forwarding: socat not found.
Error: transport is closing
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
E0523 01:33:13.990462    6427 portforward.go:331] an error occurred forwarding 43068 -> 44134: error forwarding port 44134 to pod 5d366a612b418053b3e2d0d85c723e3177c03867a234fc5ad5bcdba38d6ad016, uid : unable to do port forwarding: socat not found.
Error: transport is closing
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
E0523 01:33:16.648626    6459 portforward.go:331] an error occurred forwarding 38350 -> 44134: error forwarding port 44134 to pod 5d366a612b418053b3e2d0d85c723e3177c03867a234fc5ad5bcdba38d6ad016, uid : unable to do port forwarding: socat not found.
Error: transport is closing
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace jenkinsingress --set rbac.create=true
ingress init failed: deployments.extensions "jxing-nginx-ingress-controller" not found
error: deployments.extensions "jxing-nginx-ingress-controller" not found

```


By the way I am using CentOS 7 as:

```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by jstrachan** [comment]
I've never seen this error before: `E0523 01:33:08.591793    6385 portforward.go:331] an error occurred forwarding 36341 -> 44134: error forwarding port 44134 to pod 5d366a612b418053b3e2d0d85c723e3177c03867a234fc5ad5bcdba38d6ad016, uid : unable to do port forwarding: socat not found.` - I guess there's some firewall in place or something that is preventing helm from working?

**Comment by ccojocar** [comment]
@mmshaikh88 Do you still face this issue?

**Comment by anu11may** [comment]
sudo jx install --provider=kubernetes --external-ip 192.168.27.100
Using helmBinary helm, with noTiller false
Git configured for user: 
Using helm2
Configuring tiller
Tiller Deployment is running in namespace kube-system
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Using helmBinary helm, with noTiller false
Installing using helm binary: helm
Installing using helm binary: helm
Installing using helm binary: helm
Installing using helm binary: helm
Failed to install ingress chart: failed to run 'helm install --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true' command in directory '', output: 'E0920 16:30:23.405536   64581 portforward.go:331] an error occurred forwarding 52681 -> 44134: error forwarding port 44134 to pod ecf90d406251cc81dd335a2c6d18d0441e2d11ca19efb4a562cf5bed002ff077, uid : exit status 1: 2018/09/19 10:02:48 socat[30725] E write(5, 0x1910120, 8192): Connection reset by peer
Error: transport is closing': exit status 1
ingress init failed: deployments.apps "jxing-nginx-ingress-controller" not found

**Comment by ccojocar** [comment]
This issue seems to be rather related to the cluster configuration. The `nginx` can be successfully install e.g. for GKE.
