### ISSUE TITLE
jx-git-operator │ Error: context deadline exceeded

### ISSUE THREAD

**Issue by vlad-bura** [jenkins-x/jx#8619]
Hello all, I am trying to set up the infra using jenkins-x on AWS ( with asm) but I got blocked by the error below even in the configuration use_vault. is set to false and use_asm is true.  I am attaching also the configuration file, and for the cluster, I am using the default cluster setup https://github.com/vlad-bura/cluster-eaas-dev.  Thank you very much in advance.

 Warning: Helm release "jx-git-operator" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│   with module.eks-jx.module.cluster.helm_release.jx-git-operator[0],
│   on .terraform/modules/eks-jx/modules/cluster/charts.tf line 1, in resource "helm_release" "jx-git-operator":
│    1: resource "helm_release" "jx-git-operator" {
│ Error: context deadline exceeded
│   with module.eks-jx.module.cluster.helm_release.jx-git-operator[0],
│   on .terraform/modules/eks-jx/modules/cluster/charts.tf line 1, in resource "helm_release" "jx-git-operator":
│    1: resource "helm_release" "jx-git-operator" {
│  {

**what i see more**
k describe pod jx-git-operator-5f58976c54-925tq
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  48s   default-scheduler  **no nodes available to schedule pods**

**what i tried more:**
helm upgrade --install \
    --set url=https://github.com/vlad-bura/cluster-eaas-dev.git \
    --set username=vlad-bura \
    --set password=**** --namespace jx-git-operator --create-namespace jxgo jxgh/jx-git-operator
Error: Release "jxgo" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "jx-git-operator" in namespace "jx-git-operator" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "jxgo": current value is "jx-git-operator"'

**Comment by tgelpi** [comment]
@vlad-bura I suspect your issue has to do with the version of  "eks-jx" module you're using (1.21.5). As of K8S version 1.23, if you are using EBS volumes, you are required to use Amazon's EBS CSI driver. The eks-jx module has been updated recently  to 1.21.8 to accomodate this new requirement  and this module change should help correct the issue.  You can find details of the EBS CSI driver [here](https://github.com/jenkins-x/terraform-aws-eks-jx#ebs-csi-driver). The driver is implemented as an Amazon add-on.The EBS CSI Driver (aws-ebs-csi-driver) by default is disabled. To enable set  the following variables:
```
enable_ebs_addon = true
create_addon_role = true
ebs_addon_version = "v1.21.0-eksbuild.1"
```
To determine valid versions for variable `ebs_addon_version` use the command:
```
aws eks describe-addon-versions --addon-name "aws-ebs-csi-driver" | jq -r '.addons[].addonVersions[].addonVersion'
```
The EBS CSI Driver addon can be implemented successfully using **worker group launch templates.** The addon can be problematic when using the default **worker node groups** and is not recommended. For new installations set the following variables:
```
enable_worker_groups_launch_template = true
enable_worker_group = false
```
For existing installations where `enable_worker_groups = true` only set the variable:
```
enable_worker_groups_launch_template = true
```
Once the addon is installed,  then perform [Transitioning from Worker Groups to Worker Groups Launch Templates](#transitioning-from-worker-groups-to-worker-groups-launch-templates). When completed the variable `enable_worker_group = false`

**Comment by msvticket** [comment]
Since reporter hasn't responded I assume the issue is resolved
