### ISSUE TITLE
jx install failing on existing AWS cluster

### ISSUE THREAD

**Issue by elad-lachmi** [jenkins-x/jx#862]
I'm running jx locally using Ubuntu on Windows and installing to a cluster created with kops on AWS.

When I run `jx install --provider=aws` everything runs fine until creating the staging environment.

```bash
Created environment staging
Querying if the repo is a fork at https://bitbucket.org with kind bitbucket
Updated the Jenkins ConfigMap jenkins
Safe Restarted Jenkins server
error: Failed to create the <bitbucket_username> folder in jenkins: 503 Service Unavailable
```

It seems logical that if Jenkins is restarted, it could take a few seconds and it might also be kicked out of the NLB and will be readded in the next healthcheck cycle. I think the install procedure should wait for the Jenkins server to be available and not fail instantly.

Or maybe this is a different issue altogether?

**Edit:**
Just tried the latest release of `jx` and I see that it does wait for the Jenkins server to be available:
```bash
Created environment staging
Querying if the repo is a fork at https://bitbucket.org with kind bitbucket
Updated the Jenkins ConfigMap jenkins
Safe Restarted Jenkins server
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
Jenkins returned an error. Waiting for it to recover...
error: Failed to create MultiBranchProject job <branch_name> in folder <bitbucket_username> due to: 503 Service Temporarily Unavailable
```

I see that the folder is created, so `jx` can access Jenkins, but then fails to create the job with the same 503 error.

**Comment by jstrachan** [comment]
I wonder if this got fixed? Any chance you could retest please?

**Comment by ccojocar** [comment]
This issue might be fixed in the meantime. Closing this because the user haven't followed up.
