### ISSUE TITLE
Outdated jx version installed by brew

### ISSUE THREAD

**Issue by bartoliniii** [jenkins-x/jx#8628]
I've just type in Google "brew install jx" and I've found link to [homebrew-jx](https://github.com/jenkins-x/homebrew-jx) repository with instruction how to install jx by using brew.
Unfortunately, this project seems to be no longer supported and install outdated version of jx tool

I think it would be very useful to add info in readme.md file in [homebrew-jx](https://github.com/jenkins-x/homebrew-jx) with link to instruction how to install the newest version of jx tool and that the homebrew-jx project is not supported (for now)

**Comment by msvticket** [comment]
I added a cask and have updated the readme in [homebrew-jx](https://github.com/jenkins-x/homebrew-jx). Do check if this works for you!

**Comment by bartoliniii** [comment]
Yes, it works 👍
Great job!
