### ISSUE TITLE
503 Service Temporarily Unavailable when access jenkins server to get API token

### ISSUE THREAD

**Issue by liuxiaopiao** [jenkins-x/jx#864]
I am trying to install jx in one existing K8S cluster by the command "jx install  --provider=kubernetes" but when checking API token I met 503 error in web ui. 

root@0c79e968f57c:/# jx install  --provider=kubernetes
Did not set exposeController Config Domain
Trying to create ClusterRoleBinding user-c2tonjzmuyt-cluster-admin-binding for role: cluster-admin for user user-c2tonjzmuyt
Created ClusterRoleBinding user-c2tonjzmuyt-cluster-admin-binding
Tiller Deployment is running in namespace kube-system
Already up-to-date.
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
External loadbalancer created
? Domain 129.146.146.27.nip.io
nginx ingress controller installed and configured
Lets set up a git username and API token to be able to perform CI/CD
? Do you wish to use liuxiaopiao as the GitHub username for CI/CD pipelines: Yes
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environmentsth latest? (Y/n) Y
Counting objects: 545, done.
Compressing objects: 100% (4/4), done.
Total 545 (delta 0), reused 1 (delta 0), pack-reused 541
Generated helm values /root/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /root/.jx/cloud-environments/env-kubernetes
helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
"jenkins-x" has been added to your repositories
rm -rf secrets.yaml.dec
helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io
"jenkins-x" has been added to your repositories
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "jenkins-x" chart repository
Update Complete. ⎈ Happy Helming!⎈
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.1038 --values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000
NAME:   jenkins-x
LAST DEPLOYED: Tue May 22 14:21:24 2018
NAMESPACE: jx
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jenkins-x-chartmuseum          1        1        1           0          33s
jenkins-x-docker-registry      1        1        1           0          33s
jenkins-x-heapster             1        1        1           1          33s
jenkins                        1        1        1           0          33s
jenkins-x-mongodb              1        1        1           0          33s
jenkins-x-monocular-api        1        1        1           0          33s
jenkins-x-monocular-prerender  1        1        1           0          33s
jenkins-x-monocular-ui         1        1        1           0          33s
jenkins-x-nexus                1        1        1           0          33s
pipelinecontroller             1        1        1           1          33s

==> v1beta1/CustomResourceDefinition
NAME                  AGE
pipelines.jenkins.io  33s
runs.jenkins.io       33s

==> v1/Secret
NAME                              TYPE    DATA  AGE
jenkins-x-chartmuseum             Opaque  2     36s
jenkins-x-docker-registry-secret  Opaque  1     35s
jenkins                           Opaque  2     35s
jenkins-x-mongodb                 Opaque  2     35s
nexus                             Opaque  1     35s
jenkins-docker-cfg                Opaque  1     35s
jenkins-git-credentials           Opaque  1     35s
jenkins-hub-api-token             Opaque  1     35s
jenkins-git-ssh                   Opaque  2     35s
jx-basic-auth                     Opaque  1     35s
jenkins-release-gpg               Opaque  4     35s
jenkins-maven-settings            Opaque  1     35s
jenkins-npm-token                 Opaque  1     35s
jenkins-ssh-config                Opaque  1     35s

==> v1/ConfigMap
NAME                              DATA  AGE
jenkins-x-docker-registry-config  1     35s
exposecontroller                  1     35s
jenkins                           6     35s
jenkins-x-git-kinds               2     35s
jenkins-tests                     1     35s
jenkins-x-monocular-api-config    1     35s
jenkins-x-monocular-ui-config     1     35s
jenkins-x-monocular-ui-vhost      1     35s
jenkins-x-pod-templates           12    35s

==> v1/PersistentVolumeClaim
NAME                       STATUS   VOLUME                                                                             CAPACITY  ACCESS MODES  STORAGECLASS  AGE
jenkins-x-chartmuseum      Pending  oci                                                                                35s
jenkins-x-docker-registry  Bound    ocid1.volume.oc1.phx.abyhqljskjdyx2yyqgndaft5sgs2rt4ae2lkpvosy25ifvq5oln6il2ncuua  100Gi  RWO  oci  35s
jenkins                    Pending  oci                                                                                35s
jenkins-x-mongodb          Pending  oci                                                                                35s
jenkins-x-nexus            Pending  oci                                                                                35s

==> v1/ServiceAccount
NAME                SECRETS  AGE
cleanup             1        35s
expose              1        35s
jenkins             1        35s
pipelinecontroller  1        35s

==> v1/Role
NAME     AGE
cleanup  34s
expose   34s

==> v1/RoleBinding
NAME     AGE
cleanup  34s
expose   34s

==> v1/Pod(related)
NAME                                           READY  STATUS             RESTARTS  AGE
jenkins-x-chartmuseum-7b95b777b-jbrfw          0/1    Pending            0         33s
jenkins-x-docker-registry-6786bc55b7-sttb2     0/1    ContainerCreating  0         33s
jenkins-x-heapster-96bd95dcf-5x9hj             2/2    Running            0         33s
jenkins-684cdb56fc-hls8z                       0/1    Pending            0         33s
jenkins-x-mongodb-6c84f866dc-qc4zb             0/1    Pending            0         33s
jenkins-x-monocular-api-676c6b9bcf-9qmrk       0/1    Running            1         33s
jenkins-x-monocular-prerender-6d8897856-sb6qr  0/1    ContainerCreating  0         33s
jenkins-x-monocular-ui-69b4b898c4-jdpsc        0/1    ContainerCreating  0         33s
jenkins-x-nexus-57866468c9-ptzxq               0/1    Pending            0         33s
pipelinecontroller-5dbc96bbd4-x7v65            1/1    Running            0         33s

==> v1beta1/ClusterRoleBinding
NAME                  AGE
jenkins-role-binding  34s

==> v1/Service
NAME                           TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)    AGE
jenkins-x-chartmuseum          ClusterIP  10.96.226.33  <none>       8080/TCP   34s
jenkins-x-docker-registry      ClusterIP  10.96.73.196  <none>       5000/TCP   34s
heapster                       ClusterIP  10.96.3.109   <none>       8082/TCP   34s
jenkins-agent                  ClusterIP  10.96.22.40   <none>       50000/TCP  33s
jenkins                        ClusterIP  10.96.31.138  <none>       8080/TCP   33s
jenkins-x-mongodb              ClusterIP  10.96.90.253  <none>       27017/TCP  33s
jenkins-x-monocular-api        ClusterIP  10.96.241.96  <none>       80/TCP     33s
jenkins-x-monocular-prerender  ClusterIP  10.96.192.99  <none>       80/TCP     33s
jenkins-x-monocular-ui         ClusterIP  10.96.52.60   <none>       80/TCP     33s
nexus                          ClusterIP  10.96.154.22  <none>       80/TCP     33s

waiting for install to be ready, if this is the first time then it will take a while to download images
Jenkins X deployments ready in namespace jx

        ********************************************************

             NOTE: Your admin password is: cockatoomotley

        ********************************************************

        Getting Jenkins API Token
unable to automatically find API token with chromedp using URL http://jenkins.jx.129.146.146.27.nip.io/me/configure
Please go to http://jenkins.jx.129.146.146.27.nip.io/me/configure and click Show API Token to get your API Token
Then COPY the token and enter in into the form below:

? API Token:

Then I manually to access http://jenkins.jx.129.146.146.27.nip.io/me/configure but got 503 error. 
How can I figure out the root cause for this?  Thanks a lot!

**Comment by liuxiaopiao** [comment]
Found the root cause of this. The pods are not in ready status.

**Comment by jamesob131** [comment]
Could you elaborate more on this? I am having the same issue.

**Comment by luckielordie** [comment]
I too am having this issue, can we re-open this or post some resolution steps?

**Comment by faucherb94** [comment]
Also having this issue. Anyone figure it out?
