### ISSUE TITLE
jx open appends /blue to every application, not just Jenkins

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#865]
Using:

> NAME               VERSION
> jx                 1.2.72
> jenkins x platform 0.0.1039
> kubernetes cluster v1.9.7-gke.1
> kubectl            v1.9.6
> helm client        v2.9.0+gf6025bb
> helm server        v2.9.0+gf6025bb
> git                git version 2.15.1 (Apple Git-101)

Actions:

```
➜ jx open jenkins
jenkins: http://jenkins.jx.dvs.je/blue
```

```
➜ jx open nexus
nexus: http://nexus.jx.dvs.je/blue
```

```
➜ jx open monocular-ui
monocular-ui: http://monocular.jx.dvs.je/blue
```

Expected:

```
➜ jx open jenkins
jenkins: http://jenkins.jx.dvs.je/blue
```

```
➜ jx open nexus
nexus: http://nexus.jx.dvs.je
```

```
➜ jx open monocular-ui
monocular-ui: http://monocular.jx.dvs.je
```

**Comment by michaelneale** [comment]
fix works
