### ISSUE TITLE
Top Jenkins X Contributor Award 2024

### ISSUE THREAD

**Issue by tomhobson** [jenkins-x/jx#8651]
This issue is to receive nominations for the Top Jenkins X Contributor Award 2024.

This award recognizes excellence of technical contributions to Jenkins X. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

To nominate someone, reply to this issue with the following:

Full name of the person you’re nominating
Short description of their contributions to the Jenkins X and why they should win.

* Nominations open: Monday, January 22
* Nominations close: Sunday, February 19 at 11:59 PST
* Voting opens: Thursday, February 22
* Voting closes: Friday, March 22 at 11:59 PST
* Winners announced at cdCon: April 16–18, 2024

Please note: Last year's winner, Mårten Svantesson, cannot win the award for Top Contributor again this year.

Thanks to CDF for arranging these awards!

**Comment by tgelpi** [comment]
I would like to nominate the following four people:

1. Mahmoud N:  Node pool variables and autoscaling (Google)
2. Roberto Lopez:  The jx-git-operator upgrade and various other contributions. (AWS)
3. James Skeoch: Tekton pipeline migration (Lighthouse) 
4. Tom Hobson:  Removing kuberhealthy from the default install options, Tekton upgrade, and various other contributions.  (Azure/Google) 

If I can only submit one candidate I would have to go with Tom Hobson.

**Comment by msvticket** [comment]
@tgelpi You could nominate several persons. But since voting is made by reacting to a nomination comment you can only nominate one person in each comment. So I assume that the comment you made counts as a nomination for Tom.
