### ISSUE TITLE
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"~!!!

### ISSUE THREAD

**Issue by leilong123123** [jenkins-x/jx#8654]
"Local cluster installation Jenkins x 3.x"
kubernetes version == 1.26.9
jx version == 3.10.136

run  "jx admin operator --url = xxxx  -- username xxxx -- token xxxxx"
But pod/jx-boot has error log information.
How can i do for this error, please!

**POD LOG:**
using kubectl to apply resources
if [ -d config-root/customresourcedefinitions ]; then \
  kubectl apply --server-side=true --force-conflicts --prune -l=gitops.jenkins-x.io/pipeline=customresourcedefinitions -R -f config-root/customresourcedefinitions; \
fi
customresourcedefinition.apiextensions.k8s.io/environments.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/pipelineactivities.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/releases.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/sourcerepositories.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/previews.preview.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/lighthousebreakpoints.lighthouse.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/lighthousejobs.lighthouse.jenkins.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/externalsecrets.kubernetes-client.io serverside-applied
customresourcedefinition.apiextensions.k8s.io/clustertasks.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/customruns.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/pipelineresources.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/pipelineruns.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/pipelines.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/resolutionrequests.resolution.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/runs.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/taskruns.tekton.dev serverside-applied
customresourcedefinition.apiextensions.k8s.io/tasks.tekton.dev serverside-applied
resource mapping not found for name: "khchecks.comcast.github.io" namespace: "" from "config-root/customresourcedefinitions/kuberhealthy/kuberhealthy/khchecks.comcast.github.io-crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "khjobs.comcast.github.io" namespace: "" from "config-root/customresourcedefinitions/kuberhealthy/kuberhealthy/khjobs.comcast.github.io-crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "khstates.comcast.github.io" namespace: "" from "config-root/customresourcedefinitions/kuberhealthy/kuberhealthy/khstates.comcast.github.io-crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
make[1]: *** [versionStream/src/Makefile.mk:322: kubectl-apply] Error 1
make[1]: Leaving directory '/workspace/source'
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1 NEW_CLUSTER=false' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:269: regen-check] Error 1

**Comment by leilong123123** [comment]
I think, I have fixed it. thanks~!

**Comment by leilong123123** [comment]
I think, I have fixed it. thanks~!

**Comment by RileySeaburg** [comment]
> I think, I have fixed it. thanks~!

Can you please post the fix?

**Comment by ErikEngerd** [comment]
what was the fix?

**Comment by RileySeaburg** [comment]
> what was the fix?

Go back to Jenkins on Maven lol

**Comment by ErikEngerd** [comment]
I am using the jx3-kubernetes template. There is already an issue for this: https://github.com/jx3-gitops-repositories/jx3-kubernetes/issues/18

Looks like an issue with this template since support for k8s 1.22 which removed the v1beta1 version of CRD is already two years old.
