### ISSUE TITLE
Helm client version mismatch

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#866]
Using:

> NAME               VERSION
> jx                 1.2.72
> jenkins x platform 0.0.1039
> kubernetes cluster v1.9.7-gke.1
> kubectl            v1.9.6
> helm client        v2.9.0+gf6025bb
> helm server        v2.9.0+gf6025bb
> git                git version 2.15.1 (Apple Git-101)

Actions:
Whilst building the staging environment, I see debug output of:
```
+ make build
rm -rf requirements.lock
helm version

Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
helm init
```

Is something in the jx eco-system still using helm client v2.8.2?

**Comment by tdcox** [comment]
Ah, I see builder-base is installing 2.8.2

**Comment by ccojocar** [comment]
@tdcox I think this should be fixed.
