### ISSUE TITLE
Failing while building jenkins-parent version 2.319.2 using mvn clean install (org.jenkins-ci.main:jenkins-parent:2.319.2)

### ISSUE THREAD

**Issue by shivsrivastava** [jenkins-x/jx#8664]
Package artifact id: org.jenkins-ci.main

source code url: https://github.com/jenkinsci/jenkins/tree/jenkins-2.319.2

Issue Description: Failing while building jenkins-parent version 2.319.2 using mvn clean install (org.jenkins-ci.main:jenkins-parent:2.319.2)

JDK Version: 1.8

Build CMD: mvn clean install

MVN Version: 3.9.6

gradle version - NA

Error Log: 

[ERROR] Failures:
[ERROR]   FunctionsTest.printThrowable:544->assertPrintThrowable:567
Expected: is "p.Exc1\n\tat p.C.method1(C.java:17)\nCaused by: p.Exc2\n\tat p.C.method2(C.java:27)\n\t[CIRCULAR REFERENCE:p.Exc1]\n"
     but: was "p.Exc1\n\tat p.C.method1(C.java:17)\nCaused by: p.Exc2\n\tat p.C.method2(C.java:27)\nCaused by: [CIRCULAR REFERENCE: p.Exc1]\n"
[INFO]
[ERROR] Tests run: 3845, Failures: 1, Errors: 0, Skipped: 32

attachment: build log attached (jdk 1.8)
[Failed_jdk_8.txt](https://github.com/jenkins-x/jx/files/15158357/Failed_jdk_8.txt)

OS: windows 10

**Comment by shivsrivastava** [comment]
Please update on it.

**Comment by msvticket** [comment]
Jenkins X has nothing to do with Jenkins. See https://github.com/jenkinsci
