### ISSUE TITLE
Latest officially supported Kubernetes version will become EOL soon

### ISSUE THREAD

**Issue by nikki-quant** [jenkins-x/jx#8675]
Hi folks! Thanks for your work building JenkinsX.

The [admin guide](https://jenkins-x.io/v3/admin/guides/k8s-upgrades/) states that JenkinsX supports the Kubernetes versions 1.23-1.27. Kubernetes's end of life date for 1.27 is coming up on ([2024-06-28](https://kubernetes.io/releases/)). I wanted to ask what the plans is for JenkinsX support of later Kubernetes versions?

From what I can see in public documentation and discussion on the JenkinsX slack channels:

* There is not yet official JenkinsX support for Kubernetes versions post-1.27
* There is not a documented ETA for Kubernetes support of later versions
* Informally, many people operating JenkinsX have been running it on 1.28 without issues
* Informally, a smaller number of people report running 1.29 without issues 

I'd like to understand if the JenkinsX project has plans and capacity to keep up with the Kubernetes release cadence. The currently JenkinsX-supported versions will very soon not be officially supported by Kubernetes, and they'll incur a surcharge to run on AWS (and possibly other cloud providers). 

My team manages production workloads with JenkinsX currently and want to make Kubernetes versions upgrades in line with the officially supported releases for security & cost reasons.

While we do have an infrastructure testing cluster where we run upgrades on before making changes in our development and production environments, JenkinsX is complex and important enough to our workflow that it'd be useful to understand how it's tested against new k8s versions within the JenkinsX project itself so we can upgrade confidently.

**Comment by rupertgti** [comment]
Now I use 1.30 in my k8s test environment and working apparently without problems

**Comment by msvticket** [comment]
The admin guide states that the latest Kubernetes version supported is 1.30. That is the latest we know it works fine on, but we don't have any reason to believe there will be any particular problem with 1.31.
