### ISSUE TITLE
Add a .Net quickstart

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#868]

**Comment by rawlingsj** [comment]
This should be dotnet core

**Comment by jstrachan** [comment]
this might be a good quickstart to port someday:
https://github.com/dotnet-architecture/eShopOnWeb

**Comment by jstrachan** [comment]
this might be a simpler hello world: https://jonhilton.net/2016/07/18/your-first-net-core-web-application-using-nothing-but-the-command-line/

**Comment by jstrachan** [comment]
added an ASP.Net core quickstart https://github.com/jenkins-x-quickstarts/aspnet-app
