### ISSUE TITLE
builder-base and images are not triggering build from last two days

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#877]
There jx tools version update happening in the repo but no builds are getting triggered, Waiting for a new build from last two days.

**Comment by rawlingsj** [comment]
I just reenabled the job, it was supposed to be a CRON to cut down the number of releases to once per day, but that doesn't seem to be working so I've just enabled a release every merge to master again.

That's triggered now so should be ready in the next hour ish.  Sorry about that!
