### ISSUE TITLE
Install Jenkins plugin by CLI

### ISSUE THREAD

**Issue by yahavi** [jenkins-x/jx#882]
Is there an option in jx to install a Jenkins plugin through CLI?
If not, do you plan to add this feature?

Thanks.

**Comment by jstrachan** [comment]
just out of interest what kinds of plugins did you need?

**Comment by jstrachan** [comment]
we were thinking if folks needed extra plugins, we'd use GitOps and a quickstart that let you create a new Jenkins docker image with additional plugins that then generates a PR on your system environment git repo etc

**Comment by lamont** [comment]
@jstrachan I'm interested in managing the jenkins image (to auth against a github org) via GitOps, can you recommend where I should start? 

My specific need is to establish jenkins auth automatically against a github org, which I usually accomplish via the GitHub Authentication Plugin. I couldn't figure out where any of the jenkins services would be controlled via any of the generated git repos.  

Thank you.

**Comment by ccojocar** [comment]
The plugins are backed into the jenkins docker image. There are no plans to add a dedicated command which install additional plugins in the docker image.

**Comment by retr0h** [comment]
> The plugins are backed into the jenkins docker image

How would I install the ldap plugin @ccojocar ?

I have found I can install plugins, but once the pod is deleted and re-created the plugins are gone.
