### ISSUE TITLE
Add a react quickstart template

### ISSUE THREAD

**Issue by mkramb** [jenkins-x/jx#883]
Fork ```react-quickstart```
https://github.com/jenkins-x-apps/react-quickstart/

Example deployed app:
http://jx-staging-app-react-quickstart-2.jx-staging.104.155.55.199.nip.io/

**Comment by rawlingsj** [comment]
awesome - done! https://github.com/jenkins-x-quickstarts/react-quickstart

**Comment by rawlingsj** [comment]
<img width="588" alt="screen shot 2018-05-23 at 13 47 07" src="https://user-images.githubusercontent.com/1457180/40425268-d14dfe64-5e8f-11e8-8d13-5f01b210a2c3.png">
