### ISSUE TITLE
local repo name used by 'jx import'

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jx#898]
When I cloned my repo I also [renamed it](https://stackoverflow.com/a/651079/9705485) to give it a different name locally. Then when I did "jx import" from that directory the chart was given the same name as the directory. The pipeline that was created used the remote repo name but the app didn't get added to my environment.

**Comment by jstrachan** [comment]
I think this is now fixed; we properly use the chart name in the repo; not the folder/repo name
