### ISSUE TITLE
Error while running command jx install on Windows

### ISSUE THREAD

**Issue by piomin** [jenkins-x/jx#902]
I've got running kubernetes instance via minikube. When I'm running command jx install I get the following error. Do I have to install anything else on my laptop to be able to succesfully run the following command?
![jenkins-x](https://user-images.githubusercontent.com/2892502/40492468-cf0ef630-5f70-11e8-8095-3a40cb7d53e0.PNG)

**Comment by rawlingsj** [comment]
Unfortunately all of the core Jenkins X team don't have access to a windows machine and windows CI is not yet setup, however I wonder if you might try installing http://www.cygwin.com/ and running again from a cygwin terminal, as that should be able to run a Makefile?

**Comment by piomin** [comment]
Thanks for your quick response. Of course I can. I thought it is not required, and did something wrong. Now after running jx install command all the pods and services are installed on minikube. I only get the following error in the end of installation. Is it critical?
![jenkins-x](https://user-images.githubusercontent.com/2892502/40543329-274f447c-6024-11e8-992a-0e19c96aead3.PNG)

**Comment by piomin** [comment]
And one more thing.

![jenkins-x](https://user-images.githubusercontent.com/2892502/40549310-62a315c2-6037-11e8-903b-c444d287bc32.PNG)

**Comment by rawlingsj** [comment]
OK so we have a temporary way to automatically get the Jenkins API token using chrome, as that failed above we need to setup the auth.

So go to the URL above in jenkins  and hit `Show API Key` then run
```
jx create jenkins token admin --api-token [api token from jenkins]
```
