### ISSUE TITLE
error: namespaces "jx" not found when executing 'jx install'

### ISSUE THREAD

**Issue by chunmeiwu2018** [jenkins-x/jx#903]
Dear jx team,

When I run 'jx install' in ubuntu, I faced error namespaces "jx" not found.
-----------error----
root@k8s-master:~# jx install
? Cloud Provider kubernetes
Tiller Deployment is running in namespace kube-system
Already up-to-date.
? No existing ingress controller found in the kube-system namespace, shall we install one? No
Lets set up a git username and API token to be able to perform CI/CD

? Do you wish to use xxx as the GitHub username for CI/CD pipelines: Yes
? A local Jenkins X cloud environments repository already exists, recreate with latest? No
**error: namespaces "jx" not found**

-----------reproduce steps-----
curl -L https://github.com/jenkins-x/jx/releases/download/v1.2.83/jx-linux-amd64.tar.gz | tar xzv 
sudo mv jx /usr/local/bin
jx install

Appreciate if you can give me some feedback.

**Comment by chunmeiwu2018** [comment]
Can anyone give me some suggestion? I already spent 1 day on it, but still can't figure out the solution...

**Comment by chunmeiwu2018** [comment]
after using latest code not the latest release executable, i can over this issue, but faced another issue to start some pods:

Unable to mount volumes for pod "jenkins-x-chartmuseum-7b95b777b-htmwb_jx(d0ea550e-5fae-11e8-9709-1866daef59fc)": timeout expired waiting for volumes to attach/mount for pod "jx"/"jenkins-x-chartmuseum-7b95b777b-htmwb". list of unattached/unmounted volumes=[storage-volume]


just make comments here if someone faced same issue.

**Comment by jstrachan** [comment]
I thought we'd fixed the missing `jx` namespace issue. What was the output of `jx version` you were using?

**Comment by SeanKilleen** [comment]
I'm using Windows Subsystem for Linux (Ubuntu) on my Win10 machine.  Was able to get through `jx create cluster aws` and validating via `kops validate cluster`, but after that, attempting to run `jx create quickstart` failed with this same error:

> error: namespaces "jx" not found

`jx --version` reports `1.3.4`

**Comment by SeanKilleen** [comment]
@jstrachan apologies; I should have tried to reliably repro this first before commenting. The issue appeared to resolve itself, and I'm not sure how. But surely enough the namespace is there and I'm able to successfully use it now. If I can find a repro, I'll comment here again.

**Comment by jstrachan** [comment]
@SeanKilleen thanks for the heads up!
