### ISSUE TITLE
fix `jx init` so it works on non-MacOS

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#91]
right now we assume brew install to install helm, draft, minikube.

It'd be good to add support for downloading those binaries from github on non-Mac platforms

FWIW we had code to download things like kubectl and minikube in gofabric8: https://github.com/fabric8io/gofabric8/blob/master/cmds/install.go#L96

**Comment by jstrachan** [comment]
at least the code now tries to download the binaries for kubectl, helm, draft, minikube - though needs testing on windows + linux to see if it really works ;)

**Comment by rawlingsj** [comment]
think this is sorted now, there's another issue that explains about avoiding make so we can run on Windows https://github.com/jenkins-x/jx/issues/937
