### ISSUE TITLE
helm secrets dec secrets.yaml error,when jx install jx-infra.

### ISSUE THREAD

**Issue by becile** [jenkins-x/jx#915]
i try to install jx on play-with-k8s,avoid jenkins service use lb service(avoid waiting for lb service ok),i choose `jx install jx-infra`,then meeting error like that:
Update Complete. ⎈ Happy Helming!⎈
**helm secrets dec secrets.yaml**
Decrypting secrets.yaml
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  60A7EC7FE15D7141D8E8B274CD0A17A8AE9168E7: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Reading PGP message
      | failed: openpgp: incorrect key; GPG binary error: exit
      | status 2

  75AED3C871F4FCF6F732D8AFE1DB1DEE4B9D2792: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Reading PGP message
      | failed: openpgp: incorrect key; GPG binary error: exit
      | status 2

  013A54369DF417691DC2DFC61A19F92D632E80D4: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Reading PGP message
      | failed: openpgp: incorrect key; GPG binary error: exit
      | status 2

**Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.**
Error: plugin "secrets" exited with error

so,i use secrets.yaml replaceing secrets.yaml.dec will work
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.1038 --values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000

[secrets.txt](https://github.com/jenkins-x/jx/files/2041466/secrets.txt)

**Comment by becile** [comment]
sorry for submit a invalid issue,and thank you.
rigthnow i use [](https://labs.play-with-k8s.com) to play.there is not public network ip and lb supported k8s service typed lb(where the jenkins svc will not created.).
maybe it's stupid method. i will try to install jx with gce.

**Comment by rawlingsj** [comment]
No worries about submitting issues - feel free to keep raising questions or reporting problems :)

Yeah TBH if you have access to Google Container Engine then that's the certainly the best experience for Jenkins X to date.  Google Container Engine does a free tier max $300 I think so it's a great way to kick the types.
