### ISSUE TITLE
Kube Install process is strange and I don't trust it

### ISSUE THREAD

**Issue by sokoow** [jenkins-x/jx#918]
Hey, fair play to you for an interesting and ambitious project, but I got couple of strange questions about install.

So I'm trying to install it on my own independant cluster (non-gke/eks/aks) and:

1. 1st thing that can scare people a bit is that you ... permanently modify kube config file by adding namespace: jx somewhere there. Change is permanent and can flip out some users - it scared me a bit when I suddenly didn't see all my pods :D Took me a moment to figure it out. Why would you want to do it this way ?

2. What about people that just want to install using standalone helm chart or just plain yaml file to deploy jx on their own clusters ? Do you have the helm chart or yaml deployment files exposed somewhere ? Why I'm asking for it ? Because of the fact that some people already have some stateful layers (storage/DBs) setup, and would like to plug it into jx.

Greetings and nice project once again, respect.

**Comment by krogon** [comment]
1. Probably due to the [environment](https://jenkins-x.io/about/features/#environments) feature. An Environment = kubernetes cluster + namespace. https://github.com/jenkins-x/jx#switching-environments

2. jx installer in facts invoke chart deployment. There is a dedicated repo for managing those charts. https://github.com/jenkins-x/jenkins-x-platform.

**Comment by michaelneale** [comment]
not sure if this is a bug per se - but perhaps with some answers this could evolve into a FAQ/addition to the FAQ?

**Comment by jstrachan** [comment]
Maybe for 1 the installer could mention that it is switching to the namespace `jx` and that you can easily switch back to any other namespace via `jx ns`. The namespace to install jenkins x can be specified via the `--namespace foo` argument too so you could use the `default` namespace if you want - but we purposely went with a separate namespace so its easier to remove
https://jenkins-x.io/commands/jx_install/

as @krogon says we use a helm chart internally but there are a number of configuration options you'd have to manage by hand (such as ingress, domain, jenkins API token, git repos for environments etc) so we've made an installer to make things easier to install.

**Comment by sokoow** [comment]
Okay, let's step back a bit :) I'm interested in all of the charts that jx install command generates or use, or in it's yaml deployment output - is it possible to see it somewhere ? I want to see all of the deployments/components that it installs, so I can cherry pick and configure them myself, skipping state related layers (postgres etc) that I already have somewhere else.
