### ISSUE TITLE
Addon for OWASP ZA Proxy scanner (baseline scan)

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#919]
One handy thing that could be done, and I am not sure at what stage in the pipeline, but probably on a preview app, and probably as an addon, is the OWASP "Zed Attack Proxy" scanner that looks for common vulnerabilities. https://github.com/zaproxy/zaproxy/ in particular: https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan (a more dangerous active scan could also be done on preview environments possible)

This can be quite simple to run. It can be stateless (one shot) or if you mount a volume it could keep sessions (in reality we will probably want to compare a PR with staging environment - to see if it makes things worse, vs sessions). Ie if a change makes more errors than existed before, or warnings, perhaps fail the build. 

eg to run a baseline test against any URL: 

`docker run -t owasp/zap2docker-stable zap-baseline.py -t https://jenkins.io`
(this could be a preview app) will generate results like: 

```
docker run -t owasp/zap2docker-stable zap-baseline.py -t https://jenkins.io
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
May 28, 2018 9:41:54 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Total of 1048 URLs
PASS: Cookie No HttpOnly Flag [10010]
PASS: Cookie Without Secure Flag [10011]
PASS: Content-Type Header Missing [10019]
PASS: Information Disclosure - Sensitive Informations in URL [10024]
PASS: Information Disclosure - Sensitive Information in HTTP Referrer Header [10025]
PASS: HTTP Parameter Override [10026]
PASS: Information Disclosure - Suspicious Comments [10027]
PASS: Viewstate Scanner [10032]
PASS: Weak Authentication Method [10105]
PASS: Absence of Anti-CSRF Tokens [10202]
PASS: Private IP Disclosure [2]
PASS: Session ID in URL Rewrite [3]
PASS: Script Passive Scan Rules [50001]
PASS: Insecure JSF ViewState [90001]
PASS: Charset Mismatch [90011]
PASS: Application Error Disclosure [90022]
PASS: Loosely Scoped Cookie [90033]
WARN-NEW: Incomplete or No Cache-control and Pragma HTTP Header Set [10015] x 480 
	https://jenkins.io/
	https://jenkins.io
	https://jenkins.io/sitemap.xml
	https://jenkins.io/projects/
	https://jenkins.io/projects/blueocean/
WARN-NEW: Web Browser XSS Protection Not Enabled [10016] x 479 
	https://jenkins.io/
	https://jenkins.io/robots.txt
	https://jenkins.io
	https://jenkins.io/projects/
	https://jenkins.io/projects/blueocean/
```

without any config (there is obviously a lot more). 
It seems like preview apps is the right place? 

If so, does an addon make sense, can @rawlingsj point in a direction of how this may happen? (could also just be part of the PR pipeline, which is then added to all build packs etc, perhaps as an additional stage?). Although given the nature of this, it would be similar to the Anchore based image scan results, where you may want to know if things are worse/better/different etc. 

The baseline test https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan
and https://github.com/zaproxy/zaproxy/wiki/ZAP-API-Scan are relevant

**Comment by rawlingsj** [comment]
Yeah that sounds great.  What we did for Anchore was add a `jx post build` step to the draft packs Jenkinsfile after the image was built and pushed to the registry.  This means going forward we can add additional post build actions without having to pull request on every users repo to update their Jenkinsfile, instead we just add it to `jx` and folks get the updates when the upgrade the platform. 

I.e. right now the [post build step](https://github.com/jenkins-x/draft-packs/blob/master/packs/maven/Jenkinsfile#L27) is always performed but images are only added to anchore via `jx` if there is an anchore service available  https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/step_post_build.go#L100-L104

I think we can do something similar for this issue and add a `jx post deployment` step where we detect the `OWASP` addon is enabled and any others that come in the future and invoke them. 

Is therte I'd start by adding a an `addon` this the the anchore one https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_addon_anchore.go, if there's not an existing helm chart for it let me know and I'll help put one together.  Once done we can add the `post deployment` step and take it from there?

**Comment by michaelneale** [comment]
@rawlingsj I dont' think there would be a helm chart - also this doesn't have to be a persistent service or anything, just a discrete command that uses docker (it could be added directly to the packs possibly, assuming there is a way to get the URL of the preview app to point it against) and run right from the build pod? (maybe that isnt' best idea though)

**Comment by rawlingsj** [comment]
Ah sorry - I see now, yeah I wonder if we can just add a release of ZA Proxy https://github.com/zaproxy/zaproxy/releases to our base builder image https://github.com/jenkins-x/builder-base/blob/master/Dockerfile.apt

**Comment by michaelneale** [comment]
@rawlingsj not sure if it is best put in there - it needs to run against a preview app ideally, so would be best as a stage in a Jenkinsfile/step somewhere IMO - I think it is best if it uses the published docker version of it if that is possible? ie someone could add this today, but I am not sure how to get the URL of the preview app in the Jenkinsfile

**Comment by michaelneale** [comment]
@rawlingsj https://github.com/michaelneale/rails-shopping-cart/blob/master/Jenkinsfile#L29 - so when it calls `jx preview` - how can I programmatically get the URL the preview app is on? I can't even work it out from the command line (jx get preview only shows names, for one)

**Comment by rawlingsj** [comment]
Looks like this is how we do it when we create the preview https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/preview.go#L424-L431

**Comment by jstrachan** [comment]
we may wanna use something like exposecontroller/configmapcontroller to inject the Preview URL maybe? Then we could create an owasp helm chart thats pretty generic and is configured via helm parameters what URLs to query?

**Comment by michaelneale** [comment]
@jstrachan right - it can be a pretty simple stateless service (in reality would ideally want to compare the result with say the staging environment). 
@rawlingsj and I were thinking this could be run in parallel with anchore image scan one way or another - this just needs the public URL of the preview environment to point at (and possibly could be in the Jenkinsfile, or hidden in a step?)

We were also thinking that if that a run makes things worse than *staging* fail the pipe. Otherwise, can output it as a min report to the pull request. 

Still working out how to get the URL of the preview environment, or a URL of the app in staging etc... 

```
	url := ""
	appNames := []string{o.Application, o.ReleaseName, o.Namespace + "-preview", o.ReleaseName + "-" + o.Application}
	for _, n := range appNames {
		url, err = kube.FindServiceURL(kubeClient, o.Namespace, n)
		if url != "" {
			break
		}
	}
```
I gather it is something like that? ie iterate through the service URLs (seems a bit brute-forcey?) 



Would a helm chart be better/more general? (I don't really know anything about it)

(I am still working out how to best drive OWASP, and what it can do, but it seems pretty simple, just needs a thing to point at)

**Comment by michaelneale** [comment]
see PR above to make the URL available...

**Comment by michaelneale** [comment]
ok some progress, I have made this run successfully as a step after `jx preview`

```
sh 'docker run -t owasp/zap2docker-stable zap-baseline.py -t $(cat ../../.previewUrl) || if [ $? -eq 1 ]; then exit 1; else exit 0; fi' 
```

The shell script shenanigans at the end are due to it returning a 2 response code in the case of warnings as per https://github.com/davevs/zaproxy-minishift/blob/master/zap-baseline.py (but we only really care about failures, so that only fails if there is a real failure).

**Comment by michaelneale** [comment]
so @rawlingsj we could either add this type of check to the buildpacks, and if we do we could do something like: 

<img width="624" alt="screen shot 2018-06-20 at 7 31 45 pm" src="https://user-images.githubusercontent.com/14976/41650456-6ea3a3f2-74c1-11e8-9e9e-6335e9f30a44.png">

while we are in there, breaking apart stages a bit more? (if Anchore was in there, should it show up) - OR perhaps your idea of having a `post preview` or post deploy step (post deploy would be ideal - as ideally you want to run the OWASP thing ANYTIME there is a deployment, it is safe to). This may not show up on the pipeline that I can work out (maybe doesn't matter). 

Thoughts @jstrachan ? In any case - we can now do OWASP baseline checks on every commit as simple as: 


```
sh 'docker run -t owasp/zap2docker-stable zap-baseline.py -t $(cat ../../.previewUrl) || if [ $? -eq 1 ]; then exit 1; else exit 0; fi' 
```

and it works!

**Comment by michaelneale** [comment]
https://github.com/jenkins-x/draft-packs/pull/42 has this for the golang buildpack (if we go the buildpack way)

**Comment by michaelneale** [comment]
ok folks, if we don't get a helm pack + post preview step + add on for owasp - consider https://github.com/jenkins-x/draft-packs/pull/44 this a plan B. Simple enough and works. It would be a shame to not have this available and "on by default" hence I thought it is worth while even if it has to go into the pipeline itself.

**Comment by michaelneale** [comment]
In theory can be done with https://github.com/jenkins-x/jx/issues/1176

**Comment by psiinon** [comment]
Great to hear you're working on this. Let me know if you need and advice about best using ZAP and or the baseline.
One thing that might be useful is an option to select which docker instance to use? We have 3 relevant ones: stable, weekly and live https://github.com/zaproxy/zaproxy/wiki/Docker :)

**Comment by michaelneale** [comment]
@psiinon thanks!

BTW confirmed this now works with: 

```jx create post preview job --name owasp --image owasp/zap2docker-live:latest -c "zap-baseline.py" -c "-I" -c "-t" -c "\$(JX_PREVIEW_URL)" 
 ```

On a per team (my change only made it in to the live, weekly next week). 

Next: 
* Document this somewhere
* Possibly make an add-on command to sugar it up

**Comment by michaelneale** [comment]
Done.
