### ISSUE TITLE
error: jx not found

### ISSUE THREAD

**Issue by steinKo** [jenkins-x/jx#920]
> I  recive the error message: error creating cluster namespaces "jx" not found
>error: namespaces "jx" not found when I  run the jx create clusteer gke. How could I fixed the error? 

Steins-MacBook-Pro-2:ProductProject stein$ jx create cluster gke
? Google Cloud Project: helloworldgcp-203114
No cluster name provided so using a generated one: foepineapple
? Google Cloud Zone: europe-west1-b
? Google Cloud Machine Type:  [Use arrows to move, type to filter, ? for more he? Google Cloud Machine Type: n1-standard-2
? Minimum number of Nodes 3
? Maximum number of Nodes 5
Creating cluster...
Initialising cluster ...
Trying to create ClusterRoleBinding gke-helloworldgcp-203114-europe-west1-b-foepineapple-cluster-admin-binding for role: cluster-admin for user gke-helloworldgcp-203114-europe-west1-b-foepineapple
Created ClusterRoleBinding gke-helloworldgcp-203114-europe-west1-b-foepineapple-cluster-admin-binding
Created ServiceAccount tiller in namespace kube-system
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
Created ClusterRoleBinding tiller
Initialising helm using ServiceAccount tiller in namespace kube-system
helm installed and configured
Cloning into '/Users/stein/.jx/draft/packs/github.com/jenkins-x/draft-packs'...
remote: Counting objects: 602, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 602 (delta 8), reused 12 (delta 5), pack-reused 583
Receiving objects: 100% (602/602), 90.31 KiB | 451.00 KiB/s, done.
Resolving deltas: 100% (363/363), done.
? No existing ingress controller found in the kube-system namespace, shall we install one? Yesfor help] (Y/n) Y
NAME:   jxing
E0525 14:40:09.645963   34650 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:55693->127.0.0.1:55696: write tcp4 127.0.0.1:55693->127.0.0.1:55696: write: broken pipe
LAST DEPLOYED: Fri May 25 14:40:08 2018
NAMESPACE: kube-system
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/ClusterRoleBinding
NAME                 AGE
jxing-nginx-ingress  0s

==> v1beta1/Role
NAME                 AGE
jxing-nginx-ingress  0s

==> v1beta1/PodDisruptionBudget
NAME                                 MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
jxing-nginx-ingress-controller       1              N/A              0                    0s
jxing-nginx-ingress-default-backend  1              N/A              0                    0s

==> v1/Pod(related)
NAME                                                  READY  STATUS             RESTARTS  AGE
jxing-nginx-ingress-controller-7c4bd99845-4f9rp       0/1    ContainerCreating  0         0s
jxing-nginx-ingress-default-backend-66c54ff74b-fgjrp  0/1    ContainerCreating  0         0s

==> v1/ConfigMap
NAME                            DATA  AGE
jxing-nginx-ingress-controller  1     0s

==> v1/ServiceAccount
NAME                 SECRETS  AGE
jxing-nginx-ingress  1        0s

==> v1beta1/ClusterRole
NAME                 AGE
jxing-nginx-ingress  0s

==> v1beta1/RoleBinding
NAME                 AGE
jxing-nginx-ingress  0s

==> v1/Service
NAME                                 TYPE          CLUSTER-IP    EXTERNAL-IP  PORT(S)                     AGE
jxing-nginx-ingress-controller       LoadBalancer  10.7.244.167  <pending>    80:30935/TCP,443:30920/TCP  0s
jxing-nginx-ingress-default-backend  ClusterIP     10.7.250.10   <none>       80/TCP                      0s

==> v1beta1/Deployment
NAME                                 DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jxing-nginx-ingress-controller       1        1        1           0          0s
jxing-nginx-ingress-default-backend  1        1        1           0          0s

NOTES:
The nginx-ingress controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace kube-system get services -o wide -w jxing-nginx-ingress-controller'

An example Ingress that makes use of the controller:

  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: example
    namespace: foo
  spec:
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                serviceName: exampleService
                servicePort: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.example.com
          secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Note: this loadbalancer will fail to be provisioned if you have insufficient quotas, this can happen easily on a GKE free account. To view quotas run: gcloud compute project-info describe
External loadbalancer created
You can now configure a wildcard DNS pointing to the new loadbalancer address 35.233.93.199
? Domain 35.233.93.199.nip.io
nginx ingress controller installed and configured
Lets set up a git username and API token to be able to perform CI/CD
? GitHub user name: steinKo
To be able to create a repository on GitHub we need an API Token
Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook

Then COPY the token and enter in into the form below:

Cloning the Jenkins X cloud environments repo to /Users/stein/.jx/cloud-environments
Counting objects: 545, done.
Total 545 (delta 0), reused 0 (delta 0), pack-reused 545
error creating cluster namespaces "jx" not found
error: namespaces "jx" not found

**Comment by Cervator** [comment]
This is happening occasionally for some users including myself. I don't know what the fix is but you can get around it by creating the namespace yourself and resuming the install.

* `kubectl create namespace jx`
* `jx install`

I believe that's all I did to continue past that point.

**Comment by steinKo** [comment]
Thanks your advice help me to create the Jenkins-x environment
