### ISSUE TITLE
 error replacing placeholders read 

### ISSUE THREAD

**Issue by steinKo** [jenkins-x/jx#922]
The error:"error: error replacing placeholders read /Users/stein/development/FullStackReactLab/ProductProject/node_modules/cypress/dist/Cypress.app/Contents/Frameworks/Electron Framework.framework/Libraries: is a directory" when I run : jx import
How can I fix this 
 

create mode 100644 package.json
 create mode 100644 public/favicon.ico
 create mode 100644 public/index.html
 create mode 100644 public/manifest.json
 create mode 100644 src/index.js

Git repository created
Already up to date.
perforning pack detection in folder /Users/stein/development/FullStackReactLab/ProductProject
--> Draft detected JSON (89.045444%)
--> Could not find a pack for JSON. Trying to find the next likely language match...
--> Draft detected JavaScript (10.641311%)
selected pack: /Users/stein/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/javascript
replacing placeholders in directory /Users/stein/development/FullStackReactLab/ProductProject
app name: ProductProject, git server: github.com, org: steinKo
failed to read file /Users/stein/development/FullStackReactLab/ProductProject/node_modules/cypress/dist/Cypress.app/Contents/Frameworks/Electron Framework.framework/Libraries: read /Users/stein/development/FullStackReactLab/ProductProject/node_modules/cypress/dist/Cypress.app/Contents/Frameworks/Electron Framework.framework/Libraries: is a directory
error: error replacing placeholders read /Users/stein/development/FullStackReactLab/ProductProject/node_modules/cypress/dist/Cypress.app/Contents/Frameworks/Electron Framework.framework/Libraries: is a directory

**Comment by rawlingsj** [comment]
Looks like a bug, seems the replace code is having an issue looping through folders in `node_modules` when we can skip that entirely.  Let's try a fix..

**Comment by rawlingsj** [comment]
Perhaps we should only replace placeholders in the Jenkinsfile, skaffold.yaml and charts dir, that would avoid looping through all files and folders.

**Comment by rawlingsj** [comment]
1.2.90 should be available in ~15 mins which hopefully fixes the issue.  @steinKo could you test it on your project and let me know if it's fixed please?

**Comment by steinKo** [comment]
> I deleted the node_module directory in the git repositiry  and excuted the  jx import with jx version >1.2.88 then I upgraded the to jx version 1.2.90 and exeuted the jx import then i got an error : creating >jenkins credential jenkins-x-chartmuseum 503 Service Temporarily Unavailable.


>log from the first jx import execution
? Do you wish to use steinKo as the git user name: Yes
Already up to date.e steinKo as the git user name: (Y/n) Y
perforning pack detection in folder /Users/stein/development/FullStackReactLab/ProductProject
--> Draft detected JSON (87.078316%)
--> Could not find a pack for JSON. Trying to find the next likely language match...
--> Draft detected JavaScript (10.406231%)
selected pack: /Users/stein/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/javascript
existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step
Using git provider GitHub at https://github.com


About to create repository ProductProject on server https://github.com with user steinKo
? Which organisation do you want to use? SteinKorsveien
? Enter the new repository name:  ProductProject


Creating repository SteinKorsveien/ProductProject
Counting objects: 34607, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (32668/32668), done.
Writing objects: 100% (34607/34607), 98.77 MiB | 2.29 MiB/s, done.
Total 34607 (delta 9664), reused 0 (delta 0)
remote: Resolving deltas: 100% (9664/9664), done.
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File node_modules/cypress/dist/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework is 70.22 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To https://github.com/SteinKorsveien/ProductProject.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Pushed git repository to https://github.com/SteinKorsveien/ProductProject

Created Jenkins Project: http://jenkins.jx.35.233.93.199.nip.io/job/SteinKorsveien/job/ProductProject/

Watch pipeline activity via:    jx get activity -f ProductProject -w
Browse the pipeline log via:    jx get build logs SteinKorsveien/ProductProject/master
Open the Jenkins console via    jx console
You can list the pipelines via: jx get pipelines
When the pipeline is complete:  jx get applications

For more help on available commands see: http://jenkins-x.io/developing/browsing/

Note that your first pipeline may take a few minutes to start while the necessary docker images get downloaded!

Creating github webhook for SteinKorsveien/ProductProject for url http://jenkins.jx.35.233.93.199.nip.io/github-webhook/
? Do you wish to use steinKo as the git user name: Yes
Already up to date.e steinKo as the git user name: (Y/n) Y
perforning pack detection in folder /Users/stein/development/FullStackReactLab/ProductProject
--> Draft detected JSON (87.078316%)
--> Could not find a pack for JSON. Trying to find the next likely language match...
--> Draft detected JavaScript (10.406231%)
selected pack: /Users/stein/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/javascript
existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step
Everything up-to-date
Job already exists in Jenkins at http://jenkins.jx.35.233.93.199.nip.io/job/SteinKorsveien/job/ProductProject/
Already has a webhook registered for http://jenkins.jx.35.233.93.199.nip.io/github-webhook/

>log from the second jx import execution

? Do you wish to use steinKo as the git user name: Yes
Already up to date.e steinKo as the git user name: (Y/n) Y
perforning pack detection in folder /Users/stein/development/FullStackReactLab/ProductProject
--> Draft detected JSON (87.078316%)
--> Could not find a pack for JSON. Trying to find the next likely language match...
--> Draft detected JavaScript (10.406231%)
selected pack: /Users/stein/.jx/draft/packs/github.com/jenkins-x/draft-packs/packs/javascript
existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step
Everything up-to-date

**Comment by rawlingsj** [comment]
I just managed to import this repo on my Jenkins X cluster.  Mind until https://github.com/jenkins-x/jx/pull/926 is merged I had to rename the root folder from `ProductProject` to lowercase, i.e. `productproject`.  I then added the `node_modules` dir to the `.gitignore` so we don't upload them to github.  I raised a PR on your repo for that https://github.com/SteinKorsveien/ProductProject/pull/1

I then ran `jx install` in the `productproject` folder and the application was imported and successfully built, deployed and running in the staging environment.

<img width="779" alt="screen shot 2018-05-29 at 15 23 16" src="https://user-images.githubusercontent.com/1457180/40665108-52d7bd6c-6354-11e8-9ad3-1ad6ced08281.png">

I wonder if you have an old jenkins URL or creds in your local `~/.jx/jenkinsAuth.yaml` file, you could try removing that file and `jx import` again after renaming the root folder as explained above.  You will be prompted to enter the Jenkins api token again.
