### ISSUE TITLE
jx sync gets confused when there are multiple devpods

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#924]
So I had jx sync working nicely for a single pod (for golang)
I created an additional app using the node http quickstart, and then successfully a devpod for it. 
I then tried to run jx sync, but noted it was still hanging on to the golang sync, so as per https://jenkins-x.io/demos/devoxx-uk-2018/ I killed that, however now when I run jx sync nothing shows up for `ksync get` and no files are synced (it just sits there). 

So I am not sure if jx sync is working for multiple pods or changing dev pods. I didn't see anything in the command that would indicate how it could chose which devpod you want to sync to...

**Comment by jstrachan** [comment]
@michaelneale you were using the latest `jx` right? I was doing a bunch of tests last week using VS Code and opening multiple windows on different projects and closing them again to ensure that the 2 devpod shells worked at the same time & that things properly closed down. Previous to last weeks fixes there were numerous issues (e.g. the 2nd devpod would delete the older devpods watch)

**Comment by michaelneale** [comment]
@jstrachan this is with 1.2.88 of jx (latest still I think), and running jx sync (I was also running vs code, it doesn't also run a sync?)

**Comment by jstrachan** [comment]
VS Code also runs a `jx sync` when you open a DevPod in vs code. But these days you can run many `jx sync` processes; they under the covers wait for there to be none running then one of them runs `ksync watch` (there can only be one of those running at once).

Then the `jx create devpod --reuse --sync` does the work of ensuring each devpod has the watch setup properly (and it should not now remove any old devpod watches provided the devpod is still running)

**Comment by michaelneale** [comment]
hrm - maybe my vs code is out of date? didn't see it sync at all (I had to run by hand)

**Comment by jstrachan** [comment]
the `jx sync` command runs in a separate terminal to the `devpod` terminal so you should be able to switch to it in the terminal drop down box

**Comment by michaelneale** [comment]
@jstrachan right - I have closed all vscode and `jx sync` cli is still not syncing things up... need to dig a bit more. 

So should I not need to run `jx sync` on cli with visual studio code?

**Comment by jstrachan** [comment]
yeah - so now `jx sync` is literally just a wrapper around running `ksync watch` which doesn't care about the current directory etc. Then `jx create devpod --reuse --sync` now sets up the watches which should show up in `ksync get` - for the current folder/devpod ensuring that any stale pods are removed from the watches - but the code is meant to allow multiple devpods on multiple projects to cooexist on separate devpods.

**Comment by michaelneale** [comment]
@jstrachan so maybe we need to freshen up the docs a bit, still a bit confused how it works with multiple devpods

**Comment by michaelneale** [comment]
Still very confused - do I run jx sync just once from anywhere? 

I just created a devpod with `jx create devpod`

and then ran `jx sync`: 

```
jx sync
Downloading https://github.com/vapor-ware/ksync/releases/download/0.1.5-hotfix/ksync_darwin_amd64 to /Users/michaelneale/.jx/bin/ksync.tmp...
Downloaded /Users/michaelneale/.jx/bin/ksync.tmp
Initialising ksync
==== Preflight checks ====
Cluster Config                              ✓ 
Cluster Connection                          ✓ 
Cluster Version                             ✓ 
Cluster Permissions                         ✓ 

==== Cluster Environment ====
Adding ksync to the cluster                 ✓ 
Waiting for pods to be healthy              ✓ 

==== Postflight checks ====
Cluster Service                             ✓ 
Service Health                              ✓ 
Service Version                             ✓ 
Docker Version                              ✓ 
Docker Storage Driver                       ✓ 

==== Initialization Complete ====
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-05-30T16:50:12+10:00" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
INFO[0000] listening                                     bind=127.0.0.1 port=40322

```
still no files are synced.. (tried with a fresh cluster in case I messed things up)

**Comment by michaelneale** [comment]
also with sync it doesn't seem to work either: 

```
jx create devpod --sync
Creating a dev pod of label: nodejs
Created pod michaelneale-nodejs2 - waiting for it to be ready...
Pod michaelneale-nodejs2 is now ready!
You can open other shells into this DevPod via jx rsh -d
synchronizing directory /Users/michaelneale/Downloads/node-http to DevPod michaelneale-nodejs2 path /home/jenkins/Downloads/node-http
retrying after error:Command failed 'ksync get': time="2018-05-30T16:59:02+10:00" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1
```

**Comment by jstrachan** [comment]
these are the commands we use inside VS Code (where it all just works BTW if you wanna try it out).:
In one shell in any folder:
```
jx sync
```

Then in the folder of a project:
```
jx create devpod --sync --reuse
```

The `--sync` on the `jx create devpod` makes the command wait for the devpod to be up then generates the `ksync create` command to start watching

**Comment by michaelneale** [comment]
yep seems to work - docs need to be updated now, but yeah, makes sense. In future could probably make sync automagic on --sync or implicit...
