### ISSUE TITLE
lets convert the repo and org names to lower case safe names when importing

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#925]
when we import a project we replace the git org name and repo name in the build packs; we should ensure we use safe kubernetes names (so no special characters or upper case names) to ensure we don't get failures like this when tagging an image:
```
Error: running skaffold steps: build: build step: tagging image: Error parsing reference: "10.39.242.230:5000/Cervator/spring-boot-rest-prometheus:0.0.1" is not a valid repository/tag: invalid reference format: repository name must be lowercase
```
We could use the `kube.ToValidName(strings.ToLower(name))` functions to ensure valid names

**Comment by michaelneale** [comment]
Why not I say LGTM

**Comment by Cervator** [comment]
Thanks! Looking forward to being able to use repos on my regular account soon :-)
