### ISSUE TITLE
add new command to start stop clusters

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#933]
initially this was a request on slack, it's not obvious how to start minikube with the correct config after a `minikube stop`.  We figured out we needed the RBAC config, i.e.
```
minikube start --vm-driver hyperkit --cpus 4 --memory 4096 --extra-config=apiserver.Authorization.Mode=RBAC
```
It probably makes sense to have a 
```
jx cluster stop minikube|gke|aks|eks
```
and
```
jx cluster start minikube|gke|aks|eks
```
Perhaps we ought to write a file locally that includes the CPU, memory etc settings originally chosen?

**Comment by hwacookie** [comment]
I'd like to support this request! Especially as a beginner, it's not so obvious that sooner or later your free budget on gke/aws/whatever will be used up by those idling kubernetes clusters you started everywhere. And even if you DO now, it's not that easy to kill/terminate/stop all those machines using the various cloud consoles...

**Comment by duffn** [comment]
Is this still the correct command to restart a cluster after it has been stopped?

1. `jx create cluster minikube`
2. `minikube stop`
3. `minikube start --vm-driver hyperkit --cpus 4 --memory 4096 --extra-config=apiserver.Authorization.Mode=RBAC`
4. This always result in the following error at the `Machine exists, restarting cluster components...` step.

```
$ minikube start --vm-driver virtualbox --cpus 3 --memory 4096 --extra-config=apiserver.Authorization.Mode=RBAC

Starting local Kubernetes v1.13.2 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Machine exists, restarting cluster components...
E0124 07:07:19.850528   40568 start.go:382] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?

To disable this prompt, run: 'minikube config set WantReportErrorPrompt false'
================================================================================
Please enter your response [Y/n]: Prompt timed out.
Bummer, perhaps next time!


minikube failed :( exiting with error code 1
```

**Comment by Minipada** [comment]
I see the same behavior, did you find a solution?

**Comment by duffn** [comment]
I have not found a solution. I can only run Jenkins X in minikube after creating a cluster, but cannot restart a stopped cluster.

**Comment by Minipada** [comment]
That's making it far too slow to work with Jenkins X locally if after a reboot, we need to delete and start a new cluster...
