### ISSUE TITLE
jenkins-x.io: documentation search points to gohugo.io

### ISSUE THREAD

**Issue by mpern** [jenkins-x/jx#935]
1. go to https://jenkins-x.io/
1. click on "search the docs", search for "quickstart"
1. click any of the results
1. -> you are now at https://gohugo.io/some/where/

**Comment by mpern** [comment]
whops, wrong repository.

See jenkins-x/jenkins-x-website#5 for the same issue

**Comment by michaelneale** [comment]
hey @jstrachan I can't work out how the algolia search thing works for this site (and should issues be on this repo for this?)

**Comment by michaelneale** [comment]
I think https://forestry.io/blog/search-with-algolia-in-hugo/ has instructions: someone needs to signup to have it crawl the site, and then change the config to use it vs the default

**Comment by jstrachan** [comment]
I've tried to follow those instructions & have setup an index. Though I get an invalid API key now in the jenkins x website - no clue why.

**Comment by jstrachan** [comment]
OK now have the correct app ID + API key, but now the javascript library barfs when it does a query:
```
6app.bundle.js:8 Uncaught (in promise) Error: [groupBy]: Object has no key lvl0
    at Object.<anonymous> (app.bundle.js:8)
    at Function.E.each (app.bundle.js:8)
    at Object.groupBy (app.bundle.js:8)
    at Function.value (app.bundle.js:8)
    at app.bundle.js:8
```
no clue as to how to fix that yet

**Comment by mpern** [comment]
Maybe it's this issue:
algolia/docsearch#186

**Comment by jstrachan** [comment]
apparently we need to have the search records created using Docsearch: https://community.algolia.com/docsearch/documentation/docsearch-scraper/overview/

**Comment by rawlingsj** [comment]
This is now fixed, credit goes to either @jstrachan or @mkramb - I can't remember which :)
