### ISSUE TITLE
Ruby buildpack should included a test step

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#936]
Currently it is just building the image.

on that note - would it be good to make the Jenkinsfiles in the packs have discrete "test" stages? (where it calls the testing before the building which happens in another stage?) even if in some cases they are combine, in some they can be distinct ... (eg npm can run tests before a full install, or mvn can run an install and THEN tests - gives the user more feedback as to the state of the runtime they are in).

**Comment by krishnakumar6893** [comment]
@michaelneale Can you paste your contents from Jenkinsfile here?

**Comment by michaelneale** [comment]
@krishnakumar6893 I don't have an example one in this case.
