### ISSUE TITLE
jx install fails

### ISSUE THREAD

**Issue by deceneu3** [jenkins-x/jx#937]
When i try run "jx install" into a minikube cluster the command fails:

`C:\> jx install`
set exposeController Config Domain 192.168.99.100.nip.io
Tiller Deployment is running in namespace [32mkube-system[0m
Cloning into 'C:\Users\dd\.jx\draft\packs\github.com\jenkins-x\draft-packs'...
remote: Counting objects: 619, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 619 (delta 14), reused 17 (delta 6), pack-reused 583
Receiving objects: 100% (619/619), 93.70 KiB | 539.00 KiB/s, done.
Resolving deltas: 100% (369/369), done.
nginx ingress controller now enabled on minikube
Lets set up a git username and API token to be able to perform CI/CD

? GitHub user name: dd
To be able to create a repository on GitHub we need an API Token
Please click this URL [32mhttps://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook[0m

Then COPY the token and enter in into the form below:

? API Token: ****
Cloning the Jenkins X cloud environments repo to C:\Users\dd\.jx\cloud-environments
Counting objects: 545, done.
Total 545 (delta 0), reused 0 (delta 0), pack-reused 545
Generated helm values [32mC:\Users\dd\.jx\extraValues.yaml[0m
Installing Jenkins X platform helm chart from: C:\Users\dd\.jx\cloud-environments\env-minikube
Error: Command failed  make ARGS=--values=C:\Users\dd\.jx\gitSecrets.yaml --values=C:\Users\diana\.jx\adminSecrets.yaml --values=C:\Users\dd\.jx\extraValues.yaml --namespace=jx --timeout=6000 install
**error: exec: "make": executable file not found in %PATH%**

Way it try to use `make` command on windows 10 system ?

I'm running on Windows 10
`>jx version`
NAME               VERSION
jx                 [32m1.2.90[0m
kubernetes cluster [32mv1.10.0[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.9.1+g20adb27[0m
helm server        [32mv2.9.1+g20adb27[0m
git                [32mgit version 2.17.0.windows.1[0m

VirtualBox: 5.1.12

`>kubectl get pods -n kube-system`
NAME                                        READY     STATUS    RESTARTS   AGE
default-http-backend-59868b7dd6-t5mc5       1/1       Running   0          9m
etcd-minikube                               1/1       Running   0          1h
kube-addon-manager-minikube                 1/1       Running   0          1h
kube-apiserver-minikube                     1/1       Running   0          1h
kube-controller-manager-minikube            1/1       Running   0          1h
kube-dns-86f4d74b45-g57t4                   3/3       Running   0          1h
kube-proxy-fggbr                            1/1       Running   0          1h
kube-scheduler-minikube                     1/1       Running   0          1h
kubernetes-dashboard-5498ccf677-rd6sc       1/1       Running   0          1h
nginx-ingress-controller-67956bf89d-9gqsw   1/1       Running   0          9m
storage-provisioner                         1/1       Running   0          1h
tiller-deploy-5c688d5f9b-68kz4              1/1       Running   0          1h

**Comment by jstrachan** [comment]
looks like the installer requires `make` right now

**Comment by deceneu3** [comment]
Good point, 
but way it try to use of make command on windows 10 system ?

**Comment by rawlingsj** [comment]
If you use cigwin on windows it should work but we ought to remove the use of the makefile from jx.

**Comment by ccojocar** [comment]
@deceneu3 I am going to close this issue since the minikube support has improved in the meantime. Fell free to open another issue if you are still facing this problem. Thanks
