### ISSUE TITLE
jx create cluster fails on windows 10

### ISSUE THREAD

**Issue by deceneu3** [jenkins-x/jx#938]
Cluster creation failed on windows 10 with VirtualBox 5.2.12
I use windows powershell with administrator

`jx create cluster minikube --verbose=true --vm-driver virtualbox`
? memory (MB) 4096
? cpu (cores) 3
[33mWARNING: We cannot yet automate the installation of VirtualBox - can you install this manually please?
Please see: https://www.virtualbox.org/wiki/Downloads
[0mCreating Minikube cluster...
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 150.53 MB / 150.53 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
Minikube cluster created.
clusterrolebinding.rbac.authorization.k8s.io "add-on-cluster-admin" created
Initialising cluster ...
set exposeController Config Domain 192.168.99.100.nip.io
Trying to create ClusterRoleBinding minikube-cluster-admin-binding for role: cluster-admin for user minikube
Created ClusterRoleBinding minikube-cluster-admin-binding
Created ServiceAccount [32mtiller[0m in namespace [32mkube-system[0m
Trying to create ClusterRoleBinding tiller for role: cluster-admin and ServiceAccount: kube-system/tiller
Created ClusterRoleBinding tiller
Initialising helm using ServiceAccount [32mtiller[0m in namespace [32mkube-system[0m
retrying after error:deployment tiller-deploy never became ready
retrying after error:existing tiller deployment found but not running, please check the kube-system namespace and resolve any issues
helm init failed: after 3 attempts, last error: existing tiller deployment found but not running, please check the kube-system namespace and resolve any issues
error creating cluster after 3 attempts, last error: existing tiller deployment found but not running, please check the kube-system namespace and resolve any issues
`C:\> minikube status`
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100

`PS C:\> kubectl get pods -n kube-system`
NAME                                    READY     STATUS    RESTARTS   AGE
etcd-minikube                           1/1       Running   0          32m
kube-addon-manager-minikube             1/1       Running   0          32m
kube-apiserver-minikube                 1/1       Running   0          31m
kube-controller-manager-minikube        1/1       Running   0          31m
kube-dns-86f4d74b45-g57t4               3/3       Running   0          31m
kube-proxy-fggbr                        1/1       Running   0          31m
kube-scheduler-minikube                 1/1       Running   0          30m
kubernetes-dashboard-5498ccf677-rd6sc   1/1       Running   0          30m
storage-provisioner                     1/1       Running   0          30m
tiller-deploy-5c688d5f9b-68kz4          1/1       Running   0          31m

`> jx version`
NAME               VERSION
jx                 [32m1.2.90[0m
kubernetes cluster [32mv1.10.0[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.9.1+g20adb27[0m
helm server        [32mv2.9.1+g20adb27[0m
git                [32mgit version 2.17.0.windows.1[0m

**Comment by ccojocar** [comment]
@deceneu3 I am going to close this issue since the minikube support has improved in the meantime. Fell free to open another issue if you are still facing this problem. Thanks
