### ISSUE TITLE
jx command does not promt on gitbash console

### ISSUE THREAD

**Issue by deceneu3** [jenkins-x/jx#939]
I' try to install jenkinsx on windows 10 system,
I've seen some wrong windows commands so I tryed gitbash console for windows with mintty.

The problems I enconter is that promt for user input does not wait for user input just step over, when on cmd console or powershell console it works fine.

**Comment by jstrachan** [comment]
I wonder if this is an issue with the underlying Survey library we use for interactive input on the CLI? https://github.com/AlecAivazis/survey

**Comment by agentgonzo** [comment]
As a workaround for this, you can prepend you string with `winpty` and it'll use the windows pty renderer thingy:
eg: `winpty jx install`

**Comment by agentgonzo** [comment]
@jstrachan - yes, this is caused by https://github.com/AlecAivazis/survey/issues/148
