### ISSUE TITLE
provide an easy way to delete clusters on GKE

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#943]
it'd be nice to have a clean way to delete clusters on GKE which removes all the underlying resources and doesn't leave load balancers / firewalls around etc

**Comment by gtseres** [comment]
Would it make sense to use `google-cloud-go` `DeleteCluster`(https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/container/container.go#L239) for this? If so, we may be able to do that for other GKE operations as well.

**Comment by jstrachan** [comment]
sounds good to me!

**Comment by pinterb** [comment]
@jstrachan @gtseres it looks like that package you suggested is deprecated.  How about this [DeleteCluster](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/container/apiv1/cluster_manager_client.go#L394) instead?

**Comment by jstrachan** [comment]
@pinterb sounds great thank you!
