### ISSUE TITLE
add support for Google Cloud source repositories

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#945]
https://cloud.google.com/source-repositories/

It would be nice to support Google Cloud Source repos: https://cloud.google.com/source-repositories/ as providers in Jenkins X.

This is a little involved as we don’t just expect being able to create/delete repos and push/pull via git but also creating Pull Requests and having git commits/branches be associated with CI jobs etc. 

Then today we need a Jenkins MultiBranchSource plugin (it’s the thing today which handles the webhooks from the git provider & triggers jobs and updates the status in the git service)

**Comment by rawlingsj** [comment]
Perhaps it's time we try the prow approach instead and use that to create + trigger a standard MultiBranchSource plugin job.  That avoids having to create and maintain another impl of the branch source plugin.

**Comment by wbrefvem** [comment]
The prow idea is intriguing, but it seems to me that prow is tightly coupled enough to GitHub that the effort of implementing & maintaining Google CSR support might be roughly equivalent to implementing & maintaining a Jenkins plugin. I wouldn't mind taking on the Jenkins plugin piece, if that's the direction we're taking here.

As far as PRs, etc., are concerned, we could always setup Gitea repos for handling those and then just synchronize the Google CSR master whenever a PR is merged on Gitea.

**Comment by jstrachan** [comment]
@wbrefvem agreed. Though am hoping now we've a nice go based library of git provider connectors it might not be too hard to extend Prow to other providers too. Plus the part of Prow we're really desperate for is being able to respond to commands + comments on PRs. e.g. to approve tests or previews for non-committers generating PRs etc.

We also need to use webhooks/notifications more on things like updatebot to avoid polling so much & running out of github API calls ;)

Agreed on the gitea idea. Maybe using Gerrit might help too as a general git integration service between arbitrary git repos? 

Another option we could look at is for git providers that don't have a way to track CI job status on them; use k8s CRDs for those kinds of git repositories?

Am not sure how complete google cloud source repos are - e.g do they support PRs? Maybe mirroring from github/gitea is simplest?

**Comment by wbrefvem** [comment]
@jstrachan AFAICT they don't support PRs, however, they *can* link to GitHub and Bitbucket repos and will automatically synchronize with them. The Gerrit idea is interesting because it also gives us a way to do code review for providers that don't support it. 

Considering that in relation to Prow, I wonder if there's a set of generic code review abstractions that would allow us to support, e.g., GitHub-esque tools as well as Gerrit and others. Gerrit in particular is interesting because it forces us to reason about source control and code review differently than if we're just following the GitHub model.

**Comment by jstrachan** [comment]
Agreed! For git providers that don't have the full Pull Request + CI status result integration, we should maybe consider a modular solution of combining the 'master copy' git repo with something else, say, Gerrit. 

It would be really awesome to be able to handle any git repository at all that you can git clone / pull / push to - then have a go-to tool to handle PRs + build status stuff  if the git provider doesn't natively support it (or until Jenkins X natively supports it ;) - irrespective of where the code is really stored long term!

I guess we should try look at Gerrit support?

**Comment by wbrefvem** [comment]
Sounds good to me. There doesn't seem to be an up-to-date Gerrit chart in `kubernetes/charts`, so maybe I'll start by hacking one together, then start hacking on a provider. Would it make sense to define a separate code review provider interface, then implement that, or should I start by implementing the git provider interface and just throwing errors for unsupported features (which is the approach I took for Bitbucket Cloud)?
