### ISSUE TITLE
installation of jx-nginx prevents a kops cluster from being upgraded

### ISSUE THREAD

**Issue by mattlawnz** [jenkins-x/jx#953]
Ive been struggling to understand why my kops cluster was able to be upgraded.

After I forceable deleted these 2 pods, it proceeded!
![image](https://user-images.githubusercontent.com/30304027/40765061-4799216e-64ff-11e8-81a7-a6c7594c510e.png)

**Comment by rawlingsj** [comment]
Wow - very interesting.  Out of interest are you using another ingress controller addon in your cluster?
