### ISSUE TITLE
Hard limit in Helm 2.8.2 hit

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#966]
Action:
```
➜ jx version
WARNING: Failed to find helm installs: Command failed 'helm list': Error: trying to send message larger than max (24572446 vs. 20971520) exit status 1
```

There is a hard-coded limit on results sizes in helm 2.8.2 which is supposed to have been removed in 2.9.1

**Comment by tdcox** [comment]
Looks like we should be using `helm list --deployed -m 10` to get paginated results of deployed releases only.

**Comment by ccojocar** [comment]
@tdcox I'm closing this issue since we updated helm at 2.9.x by now.
