### ISSUE TITLE
Current build workflow leaves projects in unrecoverable state

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#968]
Using: 
```
➜ jx version
NAME               VERSION
jx                 1.2.94
jenkins x platform 0.0.1175
kubernetes cluster v1.9.7-gke.1
kubectl            v1.9.6
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.1 (Apple Git-101)
```

Action:
Following a failure of the staging environment build, subsequent attempted project builds will cause the overall state of the platform to drift out of sync in a way that can only be recovered by manual intervention.

What appears to be happening is that new project builds create new version tags in Github and in the staging requirements.yaml but not in chartmuseum. If several project builds are executed during a broken staging environment outage, the staging requirements.yaml goes out of sync (ahead of )with the chart versions in the repo, meaning that all subsequent build attempts will fail even after the root cause of the broken staging build is fixed.

To recover, it is necessary to discover the latest versions of each chart that is in the chartmuseum, then synchronise requirements.yaml back to these and then manually trigger builds for any projects that have gone out of sync.

**Comment by rawlingsj** [comment]
I've seen this lately too when concurrent builds create PRs on the staging environment

/kind bug
/priority important-soon
