### ISSUE TITLE
Could not delete jenkins-x of helm in jenkins-x installation on kubernetes 1.10!

### ISSUE THREAD

**Issue by dongdan39** [jenkins-x/jx#971]
Hi, Experts,
I'm trying to install jenkins-x on my existing local Kubernetes 1.10 cluster(4 CentOS 7 VMs on openstack) but never succeed. And when try to delete the deployment of jenkins-x I got error and could not even delete it(tried many times). The following command are all issued on the master node of Kubernetes:

#helm version

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

#jx install --ingress-namespace kube-system

....
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.1129 --values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: a release named jenkins-x already exists.
Run: helm ls --all jenkins-x; to check the status of the release
Or run: helm del --purge jenkins-x; to delete it
make: *** [install] 错误 1
Error: Command failed make ARGS=--values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2

#helm ls --all jenkins-x

NAME REVISION	UPDATED STATUS	CHART NAMESPACE
jenkins-x	1 Thu May 31 01:07:34 2018	FAILED	jenkins-x-platform-0.0.1129	jx

#helm del --purge jenkins-x

Error: timed out waiting for the condition

So can anybody shed some light on this issue? And by the way, is it possible to configure local NFS (already available to use) for persistent volume for jenkins-x installation on local kubernetes cluster? Thanks so much!

Cheers,
Dan

**Comment by Sam123ben** [comment]
Was this issue been resolved even I am not able to clean it up
