### ISSUE TITLE
jx delete app is not cleaning up charts in chartsmuseum

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#973]
This cause that if you re import the app there are charts clashing because the version of the app starts from 1.0.0 again. 

jx delete app should delete charts published and also nexus artifacts

**Comment by rawlingsj** [comment]
I wonder if we should add a flag to `jx delete app --include-charts` or something as it's not always a good idea to delete charts from a repo as folks might be using them already?

/kind enhancement
/priority important-longterm

**Comment by salaboy** [comment]
@rawlingsj @jstrachan can we make this one jx delete app --include-charts by default? 
And I also know that nexus is not being cleaned up and the docker registry either. 
But that might be a very good reason to open a couple of more issues for that.

**Comment by salaboy** [comment]
@pablog12 I used basic Auth in Postman with user "admin" and the same password as your jenkins

**Comment by jstrachan** [comment]
shouldn't reimporting the same git repo keep all the git tags so that new releases should start after the last release anyway?
