### ISSUE TITLE
Chartmuseum Password set to "admin" instead instead of JX global password

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#974]
For some reason the Chartmuseum basic auth params are not using the global jx password used for Jenkins

executing kubectl get secret jenkins-x-chartmuseum -o  jsonpath="{.data.BASIC_AUTH_PASS}" | base64 --decode; echo

returns "admin"

**Comment by vochicong** [comment]
Is this still not fixed? If so, what is the best workaround?

**Comment by vochicong** [comment]
I tried to manually set the global jx password to BASIC_AUTH_PASS in secret `jenkins-x-chartmuseum`, then delete a chartmuseum pod to get in recreated with the correct password, but still failed to `jx import` a project. It keeps saying

```
retrying after error:500 Server Error
retrying after error:500 Server Error
error: error creating jenkins credential jenkins-x-chartmuseum after 3 attempts, last error: 500 Server Error
```

**Comment by vochicong** [comment]
Found the FAQ at https://github.com/jenkins-x/jx/issues/1234#issuecomment-409455267 .

**Comment by ccojocar** [comment]
The password is set now to global jx admin password.
