### ISSUE TITLE
Create a sample Terraform to create a k8s cluster & install Jenkins X

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#976]
It’d be great to be able to use a simple Terraform file to setup one or more k8s clusters, then install/upgrade Jenkins X.

We’ll probably need a jx plugin for Terraform so we can pass in any arguments used in `jx install / jx upgrade platform`

It’d be great also if folks could define what addons, git servers & environments are needed in the Terraform file. Longer term we could define Teams & Users too & set those up - setting up the git organization for each team & setting up RBAC for the users in K8s and git 

What would also be super cool is if a user could have a local `myvalues.yaml` file in the same directory as the Terraform file which could be used by the `jx import/upgrade` to let folks override any of the helm values in any of the charts used by Jenkins-x-platform & any addons too.

**Comment by jstrachan** [comment]
It’d be nice to be able to specify the git organizations & includes / excludes repos too in the Terraform file so we can manage via GitOps the import of repos

**Comment by petersonwsantos** [comment]
Very cool!

Jenkins-x is fantastic, but the weakness of the solution is that provisioning has some manual steps.
What do you think? We have to focus on a plugin for terraform or while we do not have a plugin, can we make a terraform code with render template scripts, variables, local_exec, etc...?
The second option I can get today.

Greetings from your friends in Brazil.

Thank you

**Comment by jstrachan** [comment]
hi @petersonwsantos nice to meet you. yeah, we've automated the apps inside Jenkins X and their promotion through the environments nicely; we just haven't yet used the same GitOps automation for provisioning/upgrading the k8s clusters + Jenkins X itself. 

So I'm hoping we can come up with some examples of how to setup and configure k8s + Jenkins X + environments via Terraform; then folks can either manually run terraform by hand or setup a CI job in a SaaS CI service like [CodeShip](http://codeship.com/) to apply any change to the terraform configuration

**Comment by jstrachan** [comment]
this issue also relates to https://github.com/jenkins-x/jx/issues/479 and https://github.com/jenkins-x/jx/issues/845

**Comment by jstrachan** [comment]
Here's a first strawman of the `resources` we'll want in the Jenkins X provider for Terraform.

* Ingress controller (though that could probably just be vanilla helm stuff via the [helm provider](https://github.com/mcuadros/terraform-provider-helm#example) so probably not a custom Resource)
* GitServers - the list of git services to use from inside Jenkins X. We need this to setup security/tokens and configure Jenkins etc. Attributes:
  * kind (github/gitea/gitlab/bitbucket-cloud/bitbucket-server etc)
  * name
  * URL
  * user name / API token to access it (could come from Vault I guess?
* Team a top level resource that contains child resources as follows.  Attributes:
  * name (the k8s service-style name and unique ID)
  * label - the textual name   
 * User the users which get mapped to users inside k8s for RBAC. Attributes:
   * name
   * email address
* Role like a k8s Role but using an environment/namespace filter to define the namespaces it applies to. e.g. for all preview environments in team Cheese. Or all environments for Team cheese.

### Team child resources

These resources live within a team:
 
* Environments are the Dev / Staging / Production environments where apps run. Dev is the special one - it gets the `jenkins-x-platform` chart with team settings inside for things like build pack git URL,ref and branch patterns for CI/CD pipelines, locations of quickstarts and stuff. Attributes:
  * name (the k8s service-style name like unique ID like `staging` or `production`
  * label (the textual description like `Production`
  * cluster API server URL for the multi-cluster case
   * namespace name in the cluster
  * git repository URL
  * promotion kind (Auto/Manual)
   * order (number) for the order the environments are processed during promotions

Creating an Environment resource in Terraform should create the underlying jx Environment CRD and associated namespace along with the associated RBAC rules for the users/environment.  

Then creating a Dev environment for a team will then install the `jenkins-x-platform` and wire it up with domains

**Comment by petersonwsantos** [comment]
It's a great starting point. I'll think about it and do some tests.
Get to work!  :-)

**Comment by jstrachan** [comment]
@petersonwsantos btw what kind of k8s cluster do you want to use? Wanna check you can get your k8s cluster all setup how you want it with Terraform - then we can drop in the Jenkins X parts when we've got that bit more solid?

**Comment by petersonwsantos** [comment]
hi @jstrachan ,

I started the development of an terraform module for Jenkins-x.
I used the Heml provider (https://github.com/mcuadros/terraform-provider-helm), but this module is not yet mature.
In fact, it's just an initial idea to start our module to define which way to go.
I'm going to continue with the tests and i will be back soon to give you more information.

Tks!

repo: https://github.com/petersonwsantos/terraform-jenkins-x/tree/core

**Comment by jstrachan** [comment]
@petersonwsantos that looks good! I took a stab at a terraform provider for creating the Environment resources https://github.com/jenkins-x/terraform-provider-jx/pull/3 which seems close (though I've not figured out why the tests fail on our CI platform ;).

Ultimately using the helm provider to install jenkins x will be good; also we're hoping to move to helm3 soon to avoid the tiller stuff. 

There's currently a bit of complexity in the installation around ingress / domain / exposecontroller that it might be simplest to write a custom resource in Terraform so we can wrap up the current `jx install` logic for use in Terraform until we eventually decouple everything into fine grained terraform resources

**Comment by rawlingsj** [comment]
@jstrachan @garethjevans can this be closed now and maybe we raise cloud provider specific issues to cover AKS/EKS etc?

/kind needs-validation
/assign jstrachan
/assign garethjevans

**Comment by ccojocar** [comment]
Let's close this issue since we have already the Terraform support for GKE.
