### ISSUE TITLE
 jx import --url  <url> fails to add post commit hook to the project

### ISSUE THREAD

**Issue by chandra-siva-exa** [jenkins-x/jx#981]
When I try to import an existing git repository using jx import --url https://<github_url> , it fails to create the webhook in github.  

error: POST https://api.github.com/repos/my-org/my-project/hooks: 404 Not Found []. 

The project already has a Dockerfile and Jenkinsfile.

There is also a message:

existing Dockerfile, Jenkinsfile and charts folder found so skipping 'draft create' step .

I have write access to this repo and I am able to commit. So there is no permission issue.

When I remove the project from github and import it , it adds the project and creates the hook correctly.

**Comment by timfallmk** [comment]
@jstrachan That is exactly the problem for scope limited api keys. I think the problem is more about bailing with an appropriate error when this happens, instead of the silent fail.
