### ISSUE TITLE
Feature request: Have installer ask more questions

### ISSUE THREAD

**Issue by andrewwippler** [jenkins-x/jx#982]
I was expecting more yes/no questions when setting up `jenkins-x` on my bare-metal/home cluster. Perhaps it is just me, but I like to re-use components if it is already installed rather than create new.

I was expecting to see questions such as:

- Use Jenkins registry (Y/n)
  - (A no would ask URL, admin user, admin pass of registry) Possible fix for #399 #400 
- Install an ingress (Y/n)
  - (A no would follow-up: Does this cluster already have an Ingress (y/N) )
- Install Cert-Manager and Let's Encrypt (Y/n)
  - possible fix for #349 
- Is this cluster publicly accessible via a wildcard subdomain (i.e. *.jenkins-x.io) (y/N)
  - (a yes you set the `--domain` flag and a new question would ask the value)

This is not an exhaustive list of questions, only a few that came to mind.

**Comment by jstrachan** [comment]
Thanks @andrewwippler for the feedback!

BTW whats a Jenkins registry? Did you mean docker registry? If so yeah, I agree.

The installer already asks if an ingress controller should be installed. 

The installer doesn't ask for cert-manager/lets encrypt/domain - but we're using CLI arguments for that: See https://jenkins-x.io/commands/jx_create_cluster_gke/ e.g. `jx create cluster ... --domain mydomain --http false --tls-acme`- though the installer does prompt for the domain

**Comment by andrewwippler** [comment]
Yes, I meant docker registry :)

**Comment by ccojocar** [comment]
Closing this since most of the requested questions are already covered in by the `install`.
