### ISSUE TITLE
Where can we get gitea chart definition

### ISSUE THREAD

**Issue by liuxiaopiao** [jenkins-x/jx#983]
Hi there,
I have tried "jx create addon gitea" and  it failed due to persistent volume setup(as our cloud provider has limitation that persistent volume needs to be 50GB higher). I want to rewrite the gitea chart definition. 
But couldn't find it. 
So I have two questions:
1. where can i get the gitea chart definition? 
`
[test@test ~]$ helm repo list
NAME            URL
stable          https://kubernetes-charts.storage.googleapis.com
local           http://127.0.0.1:8879/charts
jenkins-x       https://chartmuseum.build.cd.jenkins-x.io

`

2.  I thought the https://chartmuseum.build.cd.jenkins-x.io is public repo but couldn't access it from browser.  
Is this repo setup up by jenkins-x platform inside the K8s cluster?  

Thanks so much

**Comment by jstrachan** [comment]
here's the gitea chart:
https://github.com/jenkins-x/charts/tree/gitea/incubator/gitea

you can browse the charts we've released here: https://monocular.build.cd.jenkins-x.io/
