### ISSUE TITLE
Getting error while promoting application to namespace jx-staging

### ISSUE THREAD

**Issue by grohan2002** [jenkins-x/jx#987]
Its creating pull request but failed while querying the Pull Request. Also chartmuseum is not accessible. Please find below logs:

Promoting app SampleSpringApp version 0.0.1 to namespace jx-staging
Using pipeline: gituser/SampleSpringApp/master build: #1
Cloning into '/home/jenkins/.jx/environments/gituser/environment-cougarsharp-staging'...
Found remote branch names master, HEAD -> origin/master, master, promote-Python-Sample-Application-0.0.2, promote-demo-0.0.1
Switched to branch 'promote-SampleSpringApp-0.0.1'
[promote-SampleSpringApp-0.0.1 09ff7f8] Promote SampleSpringApp to version 0.0.1
 1 file changed, 3 insertions(+)
To https://github.com/gituser/environment-cougarsharp-staging.git
 * [new branch]      HEAD -> promote-SampleSpringApp-0.0.1
Created Pull Request: https://github.com/gituser/environment-cougarsharp-staging/pull/3

Using pipeline: gituser/SampleSpringApp/master build: #1
WARNING: Failed to query the Pull Request last commit status for https://github.com/gituser/environment-cougarsharp-staging/pull/3 ref 09ff7f81ecf5583d4f289f3b8ff139c69801412c Could not find a status for repository gituser/environment-cougarsharp-staging with ref 09ff7f81ecf5583d4f289f3b8ff139c69801412c
EXITCODE   0error: Pull request https://github.com/gituser/environment-cougarsharp-staging/pull/3 last commit has status error for ref 09ff7f81ecf5583d4f289f3b8ff139c69801412c

**Comment by jstrachan** [comment]
that all looks fine to me. the `WARNING` message should really be removed as its quite normal ;)

Did the PR job trigger in the staging repository in Jenkins? Try`jx console`  then navigate to the staging project in jenkins and have a look. My guess is its webhook related; that github cannot talk to your jenkins server so that webhooks are not triggering the environment PR / merge jobs?
