### ISSUE TITLE
Android quickstart

### ISSUE THREAD

**Issue by angoothachap** [jenkins-x/jx#994]
Please add this github quickstart:

**Comment by angoothachap** [comment]
My plan is to see what IntelliJ does to set up an Android project and replicate

**Comment by angoothachap** [comment]
@rawlingsj Would you assign this issue to me please?

**Comment by angoothachap** [comment]
Here's a sample project

https://github.com/angoothachap/android-quickstart

**Comment by rawlingsj** [comment]
OK great!  I just forked it and tried `jx create quickstart` and selected the new android one.

Jenkins X detected it was gradle, was that correct?  The Jenkins build failed with..

```
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```

I think I can sort that

**Comment by angoothachap** [comment]
Yes, it is a Gradle project. Android SDK is required to build the project.

**Comment by rawlingsj** [comment]
Great - I'll add the Android SDK to our gradle builder image https://github.com/jenkins-x/builder-gradle
